### ISSUE TITLE
Enable update of TLS certificates

### ISSUE THREAD

**Issue by pbochynski** [kyma-project/kyma#1000]
**Description**
Refactor components to use secrets for TLS. Make sure that when secret is updated all the components can get new values - provide an instruction/script how to do this.

Components to refactor:
- configuration-generator
- apiserver-proxy
- istio-ingressgateway
- gateway (remote env)
- ... (check of it is used somewhere else)

**Reasons**
TLS certificates are passed to the installer and propagated to several components. The only way to update certificates is to run installer again.

**Documentation requirements** 

Add documentation section how to rotate TLS certificates. Place documentation in the Security topic (rename Authentication and Authiorization to Security). The documentation should contain step by step manual:
- how to deploy new secret with TLS
- how to trigger components using TLS to use new values
- how to verify that new TLS is used (check in browser?)

**Comment by sjanota** [comment]
Every secret with TLS certificates in kyma in fact is the same certificate. Maybe we can change it: let there be only one secret and several deployments will be suing it?
