### ISSUE TITLE
Missing specification for function signature

### ISSUE THREAD

**Issue by a-thaler** [kyma-project/kyma#10049]
**Description**
When browsing the serverless documentation of kyma I was not able to find any specification of what the signature of my main function method is.
```
main: function (event, context) { .. }
```

What is the signature of that method? What schema the event and context variable has? What are the expected return types? How does it differ dependent on the type of trigger? What parts a runtime dependent, so will differ between node and python?

Please provide a clear specification with some examples and clarify the differences between the runtimes. My initial reasoning was how to add custom response headers to the function response in case it is exposed via an APIRule. Indeed the node/express typical response struct is located inside the `event.extensions.response` attribute and you can manipulate it as you are used to do it in node like for example that:

```
module.exports = {
    main: function (event, context) {
        res = event.extensions.response;
        res.writeHead(200, {'Content-Type': 'text/plain', 'some': 'header'});
        res.write('Hello World!');
        res.end();
        return
    }
}
```

I remember having a more specific definition in the old serverless documentation based on kubeless and was surprised that it is gone.

**Expected result**
A well-defined contract on input and output parameters for the main function method for all runtimes

**Actual result**
I found no hint on what is inside that passed structures and what is the expected return type

**Steps to reproduce**

**Troubleshooting**

**Comment by kazydek** [comment]
[This](https://github.com/kyma-project/kyma/blob/release-1.11/docs/serverless/03-03-programming-model.md) is the old Serverless doc that @a-thaler mentioned. It could be used as a reference.
