### ISSUE TITLE
Change the example to use /events endpoint

### ISSUE THREAD

**Issue by sayanh** [kyma-project/kyma#10058]
**Description**
Kyma supports cloud events from the gateway. One needs to use /events endpoint for this.

The current [example](https://github.com/kyma-incubator/examples/tree/master/cloud-events-e2e-scenario) uses CE v0.3 and /v2/events.

It should be changed to CE v1.0 using [cloudevents/sdk-go v2.xx](https://github.com/cloudevents/sdk-go/tree/v2.3.1).

**Open questions:**
- Is this [example](https://github.com/kyma-incubator/examples/tree/master/cloud-events-e2e-scenario) repo still valid?
- If not then should there be an example that shows cloud events in action [when they are sent from outside the Kyma cluster](https://github.tools.sap/skydivingtunas/how-to/blob/master/send-cloud-events-to-OSS-kyma.md)?

**Comment by alexandra-simeonova** [comment]
The https://github.com/kyma-incubator/examples repo is not valid anymore

We could add another tutorial to https://kyma-project.io/docs/kyma/latest/03-tutorials/ instead

**Comment by alexandra-simeonova** [comment]
We added a new tutorial which covers the same scenario as in the example in this issue: https://kyma-project.io/docs/kyma/main/03-tutorials/00-eventing/evnt-01-send-event-outside-cluster/
Because of that, I think this issue can be closed.

**Comment by k15r** [comment]
already implemented
