### ISSUE TITLE
Move Configurations Generator to official docs

### ISSUE THREAD

**Issue by Maladie** [kyma-project/kyma#1005]
**Description**

Please review if the following document: https://github.com/kyma-project/kyma/blob/master/resources/core/charts/configurations-generator/README.md#the-kubeconfig-file is valid and usable for users. If yes, move it to official docs. Otherwise, please, remove it.

Comes from #530

**Comment by tomekpapiernik** [comment]
This is already a part of the user-facing documentation. 
See https://kyma-project.io/docs/latest/components/authorization-and-authentication#details-kubeconfig-generator.

Closing this issue.

**Comment by tomekpapiernik** [comment]
Duplicate of #1007
