### ISSUE TITLE
Check how user are experiencing Kyma UI and Doc pages

### ISSUE THREAD

**Issue by arturskorupa** [kyma-project/kyma#10053]
**Description**

Measure real user experience at Kyma Console UI and kyma-project.io page with dedicated analytic tool like [hotjar](https://www.hotjar.com/)

**Reasons**

Such sophisticated analytic tool will let us know how user navigates on the page, where spend more time, what areas are not easy reachable. It will lead us to improve user experience. 

**Attachments**

**Comment by pbochynski** [comment]
Not a priority now.
