### ISSUE TITLE
Fix upgrade test which is failing in the prepare-eventmesh step

### ISSUE THREAD

**Issue by marcobebway** [kyma-project/kyma#10095]
**Description**

The post-master-upgrade job fails in the prepare-eventmesh step.

**Expected result**

The test should be green.

**Troubleshooting**

https://status.build.kyma-project.io/view/gcs/kyma-prow-logs/logs/post-master-kyma-gke-upgrade/1333342491277004800
https://status.build.kyma-project.io/view/gcs/kyma-prow-logs/logs/post-master-kyma-gke-upgrade/1333705565783724032

**Comment by k15r** [comment]
Event mesh has been replaced and so this step does not exist anymore
