### ISSUE TITLE
Enable clustering for NATS Streaming

### ISSUE THREAD

**Issue by abbi-gaurav** [kyma-project/kyma#1011]
To improve HA, we need to introduce clustering for NATS Streaming. This will ensure continuous execution of business workflows taking into care disruptions at the network or K8S level (pods rescheduled, ...)

The clustering configuration to refer is https://github.com/nats-io/nats-streaming-server#clustering-configuration.

At present, the cluster size is limited to 3. This will be auto-scalable in the future.

### AC
- [ ] Implement the clustering with 3 instances.
- [ ] NATS Streaming Clustering is only enabled for cluster installation and not for local
- [ ] Eventing fucntionality is working as expected.

**Comment by pbochynski** [comment]
Please ensure that minikube configuration is still lightweight.

**Comment by abbi-gaurav** [comment]
> Please ensure that minikube configuration is still lightweight.
@pbochynski thanks for the input. The same has already been covered by the acceptance criteria `NATS Streaming Clustering is only enabled for cluster installation and not for local`

**Comment by pbochynski** [comment]
Do you think it is still needed? I think that hyper-scaler's messaging infrastructure should be used for the production use case. For development HA configuration is just an additional cost.

**Comment by Abd4llA** [comment]
@pbochynski makes sense, closing.
