### ISSUE TITLE
Consistent selector scheme for prometheus-operator resources

### ISSUE THREAD

**Issue by a-thaler** [kyma-project/kyma#10112]
**Description**
The kyma monitoring chart bundles the prometheus-operator. That comes with several CRDs like ServiceMonitor, PodMonitor, PrometheusRule and Probes. When placing resources for that CRD in the cluster, the operator will pick them up following a specific selector rule. Unfortunately that rules got inconsistent for the ServiceMonitor by mainly switching off the serviceMonitorSelectorNilUsesHelmValues attribute.

Goal:
- Align on the best way to select resources
- Configure the selectors consistent across all resources
- Check if there is a way to stay compatible. If not, provide a good migration guide

**Reasons**

**Attachments**

**Comment by chrkl** [comment]
@a-thaler still relevant?
