### ISSUE TITLE
Improved operations for fluent-bit with dashboard, alert rules and aliases

### ISSUE THREAD

**Issue by a-thaler** [kyma-project/kyma#10110]
**Description**

Fluent-bit documents where to find recommended dashboards and alert rules. We should use them. Furthermore, there is an alias feature available so that the outputs are well-named in the related fluent-bit metrics.

- [ ] Bundle proper dashboards and alerts, see https://docs.fluentbit.io/manual/administration/monitoring#grafana-dashboard
- [x] Introduce aliases for all pre-configured outputs, see https://docs.fluentbit.io/manual/v/1.5/administration/monitoring#configuring-aliases (implemented with https://github.com/kyma-project/kyma/pull/10284)

Requirements:
- There is a nice way to see in grafana the throughput and health infos for fluent-bit pipelines
- Alerts are getting raised if an error rate for a pipeline is getting to high over some time range

**Reasons**

**Attachments**

**Comment by suleymanakbas91** [comment]
Aliases are already added with this PR https://github.com/kyma-project/kyma/pull/10284.
