### ISSUE TITLE
Correct the spelling of ORY in docs

### ISSUE THREAD

**Issue by majakurcius** [kyma-project/kyma#10149]
**Description**

[`ORY`](https://www.ory.sh/), as in the name of the stack, should be spelled with all capital letters.
This spelling in our documentation is not consistent in that regard and sometimes the incorrect `Ory` spelling is used. For example, see [this document](https://kyma-project.io/docs/#overview-in-a-nutshell). 
This should be corrected.

**Area**

* Documentation

**Reasons**

* The spelling in our documentation should match the official spelling of this name.

**Assignees**

@kyma-project/technical-writers

**Comment by 96RadhikaJadhav** [comment]
@majakurcius  Could you please assign this issue to me? I wish to work on it.

**Comment by mmitoraj** [comment]
Done -> see https://github.com/kyma-project/kyma/pull/11747
