### ISSUE TITLE
Rafter-upgrade job must not generate keys for minio

### ISSUE THREAD

**Issue by kwiatekus** [kyma-project/kyma#10140]
**Description**

Upon investigation of upgrade process ( 1.15.1 to 1.17 ) we identified a potential scenario that could cause corruption of rafter meta-data.
When upgrading from kyma 1.15.1 to 1.16.RC3 a rafter migration job is executed. This job  upgrades minio and adopts to minio's new way of storing the keys used for assets encryption. Unfortunately this rafter job uses helm generated keys, which, in case of upgrade unexpected crash, may leads to corrupted state.  
**In case this upgrade job hangs** ( i.e due to timeouts caused by pvc mounting ) the kyma installer will reschedule it and as a result executes the key migration once again. This causes key corruption.

We are working on:
 - script snippet that helps mitigating the problem by removing the corrupted meta-data and forces minio to re-encrypt ( [source1](https://stackoverflow.com/questions/61343885/minio-unable-to-initialize-server-switching-into-safe-mode-unable-to-initialize), [source2](https://github.com/helm/charts/issues/19864) )
 - Patching the upgrade job for 1.16 and 1.17 kyma versions so that keys are [not re-generated](https://helm.sh/docs/howto/charts_tips_and_tricks/#be-careful-with-generating-random-values) with every upgrade attempt.

**Expected result**
 It should be possible to safely re-run upgrade job upon a unexpected timeout/crash

**Actual result**

Due to key generation,  re-run of upgrade job may cause corrupted minio keys

**Troubleshooting**

According to [source1](https://stackoverflow.com/questions/61343885/minio-unable-to-initialize-server-switching-into-safe-mode-unable-to-initialize) and [source2](https://github.com/helm/charts/issues/19864)  it's possible to remove the `data/.minio.sys` directory on persistent volume to force re-encryption of Minio configuration on PV.
We will attach a script automating the operation

**Comment by aerfio** [comment]
I've created a bash script that fixes installation. If minio crashes with logs similar to 
```text
 You are running an older version of MinIO released 1 year ago 
 Update: https://docs.min.io/docs/deploy-minio-on-kubernetes 


ERROR Unable to initialize config system: invalid character '\u009c' looking for beginning of value
```
or

```
ERROR Unable to initialize server switching into safe-mode: Unable to initialize sub-systems: Unable to initialize config system: Invalid credentials
```

then you can fix it by running: 
```bash
#!/usr/bin/env bash
 
set -o errexit
set -o nounset
set -o pipefail

NAMESPACE="kyma-system"
DEPLOYMENT_NAME="rafter-minio"

PATCH=$(cat <<EOF
spec:
  template:   
    spec:
      initContainers:
      - command:
        - /bin/sh
        - -ce
        - rm -rf /export/.minio.sys/config
        name: minio-init
        image: eu.gcr.io/kyma-project/incubator/develop/minio/minio:RELEASE.2019-10-12T01-39-57Z-a67baaa0
        volumeMounts:
        - mountPath: /export
          name: export
EOF
)

kubectl -n "${NAMESPACE}" patch deployment "${DEPLOYMENT_NAME}" --patch "${PATCH}"

kubectl -n "${NAMESPACE}" rollout status deployment "${DEPLOYMENT_NAME}"

kubectl patch deployment -n "${NAMESPACE}" "${DEPLOYMENT_NAME}" \
  --patch "[{\"op\": \"remove\", \"path\": \"/spec/template/spec/initContainers\"}]" \
  --type=json

kubectl -n "${NAMESPACE}" rollout status deployment "${DEPLOYMENT_NAME}"
kubectl -n "${NAMESPACE}" delete pod -l app.kubernetes.io/instance=rafter
```
This script adds initContainer to rafter-minio deployment, which clears config directory within emptyDir volume. This leads to the situation in which clusterbuckets/buckets lose their policies, which is then fixed by deleting rafter pods (especially `rafter-upload-svc`). After running the script give rafter-ctrl-mngr max 5 min to reconcile all of its resources. All of the clusterassetgroups should turn from `Pending` to `Ready`. You can check it by running `kubectl get clusterassetgroups`.
