### ISSUE TITLE
Kyma installation changes

### ISSUE THREAD

**Issue by pbochynski** [kyma-project/kyma#10178]
**Description**

This is the list of ideas to discuss in the installation WG:
1. Decouple installation/upgrade of Kyma components from their configuration. It is ok to pass the configuration but it should be possible to configure Kyma components without triggering installation/upgrade.
2. Idempotent Kyma deployment (possible to execute in the reconciliation loop). Merge installation/upgrade into one command: deploy. It should just apply the target state in the cluster and should be more declarative than imperative. The target state should be known before triggering installation (avoid values/jobs that are mutating target state during installation). The process of upgrade/install should be possible to restart at each stage (rollback is not the option).
3. Release helm charts for Kyma components. Kyma should publish helm repository with component charts. To discuss if we should always release all the charts with Kyma or independently.
4. Develop helm charts in components. You can test the deployment of a single component independently (even with an upgrade).
5. Istio and Kyma CRD should be handled separately.

**Reasons**
Installation and upgrade is not flexible enough, not resilient enough, and too slow.

**Attachments**

**Comment by a-thaler** [comment]
Solved by https://github.com/kyma-project/kyma/issues/10297
