### ISSUE TITLE
Flag for istio-operator to enable tracing is missing

### ISSUE THREAD

**Issue by tobiscr** [kyma-project/kyma#10189]
**Description**

In release 1.18 we recognised that the flag [`enableTracing`](https://istio.io/latest/docs/reference/config/istio.mesh.v1alpha1/) no longer exists in the Istio-operator configuration. This flag was defined in release releases <= 1.16 and controls whether the tracing will be activated in Istio.

Right now, it's not fully clear which flag finally controls the Istio operator to enable/disable tracing. This needs to be sorted out up-front.

**Expected result**

The `enableTracing` flag should be explicitly defined and used to control the enablement of tracing in Istio.

See Istio operator configuration before:

https://github.com/kyma-project/kyma/blob/release-1.16/resources/istio/files/kyma_cluster_istio_operator.yaml#L356

**Actual result**

The `enableTracing` flog is no longer explicitly defined and default value is used by the Istio operator.

**Steps to reproduce**

**Troubleshooting**

**Comment by suleymanakbas91** [comment]
Will be fixed by https://github.com/kyma-project/kyma/pull/10159.
