### ISSUE TITLE
Remove dependencies to apiserver-proxy in pamela

### ISSUE THREAD

**Issue by pbochynski** [kyma-project/kyma#10200]
**Description**
Apiserver proxy component will be removed soon. Pamela has dependencies to the resources created by apiserver-proxy, e.g. service account. 

**Expected result**
Pamela works without apiserver-proxy component installed.

**Actual result**
Pamela installation hangs without apiserver-proxy. 

**Steps to reproduce**

Follow quick start guide: https://github.com/kyma-incubator/local-kyma

**Comment by pbochynski** [comment]
I fixed local-kyma script by disabling pamela (https://github.com/kyma-incubator/local-kyma/commit/810dd388e115512fc9302d404a6271a99c242403)
If you want to reproduce the problem enable it again in the script.

**Comment by pbochynski** [comment]
Nothing has changed. Still, the dependency to secret created by apiserver proxy is there:
https://github.com/kyma-project/kyma/blob/bdf39fdc82fd358d652e254bb71a28624c209b46/resources/console/charts/pamela/templates/deployment.yaml#L54-L57

**Comment by parostatkiem** [comment]
@pbochynski the PR ready and tested❕

**Comment by kubadz** [comment]
That secret is not created by apiserver-proxy. It is in fact patched by xip-patch component ([see here](https://github.com/kyma-project/kyma/blob/master/components/xip-patch/xip-patch.sh#L90)).

apiserver-proxy creates another secret - `apiserver-proxy-tls-cert` but AFAIK you are not using it.
