### ISSUE TITLE
Function should not create HPA when min and max replicas are set to 1

### ISSUE THREAD

**Issue by rakesh-garimella** [kyma-project/kyma#10201]
**Description**

If we create a function and set min and max replicas to 1 then a HPA is created with min and max replicas set to 1. As the max replicas is already reached it triggers prometheus alerts (Hpa Maxed Out). Which is not nice since by setting min and max replicas to same value the user does not want to scale out. 

**Expected result**

We should not create HPA when min and max replicas are set to same value. It should be created when min replicas is less than max replicas.

**Comment by aerfio** [comment]
@kwiatekus @tgorgol The fix is already merged so I close this
