### ISSUE TITLE
How to delete a resource in OrphanMitigation status

### ISSUE THREAD

**Issue by sundarvc** [kyma-project/kyma#10207]
Hi Kyma Team,

I have a namespace that is not fully terminating due to a hanging service instance.
Here is the output of the describe cli:

Message:                      Orphan mitigation failed: Stopping reconciliation retries because too much time has elapsed
Message:                      Error provisioning ServiceInstance of ClusterServiceClass (K8S: "xsuaa" ExternalName: "xsuaa") at ClusterServiceBroker "sm-xsuaa-fb8e7037-0c56-405f-8110-187ef9d39273": Status: 500; ErrorMessage: <nil>; Description: Service broker xsuaa failed with: org.springframework.cloud.servicebroker.exception.ServiceBrokerException: Error creating application null (Error parsing xs-security.json data: Inconsistent xs-security.json: Invalid appid "ssc-xsuaa!t15778" in grant-as-authority-to-apps: Scopes cannot be granted as authorities to the own app (list them in "authorities").); ResponseError: <nil>

I am not able to delete the resource (service instance and binding ) from cli as I get "Forbidden" error message. 

How do I clean up this namespace ?

Thanks,
Sundar

**Comment by pbochynski** [comment]
Maybe you can try to kill the namespace ith this tool: https://github.com/thyarles/knsk

**Comment by PK85** [comment]
Hello @sundarvc, strange you have Forbidden message, check your roles and then use above tool suggested by @pbochynski
