### ISSUE TITLE
Create Dockerize Workload Wizard popover

### ISSUE THREAD

**Issue by valentinvieriu** [kyma-project/kyma#10211]
**Description**

As a Matthew and Sebastian, I would like the possibility to create a Dockerized workload using the Console UI. This experience should be consistent with the creation of functions. I should be asked only the necessary informations to create a fully functional Dockerized workload

**AC**

- [ ] We will consolidate the menu on the left to align more with [Kubernetes Terminology](https://kubernetes.io/docs/concepts/workloads/)
![image](https://user-images.githubusercontent.com/478866/102093994-152ccd80-3e22-11eb-8d4e-e4f8d9ccef0e.png)

- [ ] Deploy new workload will be a dropdown, where we can choose: Functions, Dockerized Workloads, and Upload Yaml. The Functionality for Functions, and Upload Yaml will be the same
![image](https://user-images.githubusercontent.com/478866/102063744-b4d46680-3df6-11eb-98d3-c3868d4d5028.png)

- [ ] Clicking on Dockerized Workloads will bring up a similar popup as with Functions, and it will ask the user the minimal informations that are needed to create a Dockerized workload ( Docke image path, exposed ports etc ). After the popup is closed, user will be directed to the deployment page, where the deployment ( and other necessary resources will be already created )

This is part of the epic #10088

**Comment by kazydek** [comment]
GS guides and Serverless tutorials will need to be changed as well. @klaudiagrz has already logged an issue for that: https://github.com/kyma-project/kyma/issues/10260.

**Comment by pbochynski** [comment]
@valentinvieriu Is anything missing to close the ticket?
