### ISSUE TITLE
Integrate the VictorOps alerting with the Application Connector's components. 

### ISSUE THREAD

**Issue by lszymik** [kyma-project/kyma#1022]
**Description**

The Application Connector components must also send notifications to the VictorOps. It was not done during integration with monitoring. Now it is the perfect time to do it.

**Reasons**

The Application Connector components must be monitored to allow our fast support reaction to any issue with may occur.

**Comment by Szymongib** [comment]
The configuration required for alerts to be enabled is not yet present.
