### ISSUE TITLE
Services are not listed if any of them has no labels

### ISSUE THREAD

**Issue by parostatkiem** [kyma-project/kyma#10229]
**Description**
Workaround: Make sure all services in your namespace (the one with the sympthoms) have at least one label. If not, add it via `kubectl edit`.

**Expected result**
Services are always rendered.

**Actual result**
Services are not listed in the console on the _Services_ and on the _Create API Rule_ views if current namespace has at least one service which has no labels defined.

**Steps to reproduce**

**Troubleshooting**

**Comment by abbi-gaurav** [comment]
one can also try this command to label all services in one-shot, in case there are multiple services

```
for f in $(kubectl -n {provide-namespace} get svc -o jsonpath='{.items[*].metadata.name}'); do kubectl -n {provide-namespace} label svc $f test=example-label; done
```
