### ISSUE TITLE
Update DEX dependency to latest release

### ISSUE THREAD

**Issue by peteral** [kyma-project/kyma#10252]
**Description**

Please update DEX dependency to latest release (v2.27.0) as of now.

**Reasons**

I have run into a CORS problem with DEX UserInfo resource when deploying an app into Kyma and using DEX as OICD proxy. The problem has been solved in DEX in October [https://github.com/dexidp/dex/pull/1819](https://github.com/dexidp/dex/pull/1819) and released in version 2.26.0 (Nov 5th).

AFAIK this problem means, that it is currently not possible to access the JWT user information in an app exposed as API Rule and secured by DEX. The call to DEX user info endpoint is CORS and because dex only confirms the origin, but does not confirm the authorization header, the call is rejected by the browser.

**Comment by strekm** [comment]
Already taken care of in https://github.com/kyma-project/kyma/pull/10263
