### ISSUE TITLE
Istio production profile

### ISSUE THREAD

**Issue by strekm** [kyma-project/kyma#10269]
**Description**

Implement production profile for Istio component but keep production overrides still.

**Reasons**

Since Kyma features profiles Istio production overrides should be implemented as Kyma profile.

**Attachments**

**Comment by pbochynski** [comment]
Please check if our overrides are different than existing istio profiles: https://istio.io/latest/docs/setup/additional-setup/config-profiles/
We should limit the number our overrides we provide and use default as long as possible (and makes sense).
