### ISSUE TITLE
Runtime Agent fetches only the first 100 applications from Compass

### ISSUE THREAD

**Issue by NickyMateev** [kyma-project/kyma#10308]
# Runtime Agent fetches only the first 100 systems from Compass

**Description**

Currently the runtime agent in Kyma fetches only the first 100 applications from Compass. This is an issue for runtimes with a big number of applications connected.

**Expected result**

All applications part of a scenario with my runtime should be showcased in my runtime with their APIs & Events.

**Actual result**

If more than 100 systems (the max paging in Compass) are in a scenario with my runtime, then some of them will be missing in my Kyma runtime.

**Steps to reproduce**

Register 100+ systems in Compass and put them in a scenario with a Kyma runtime.

**Reference links**

https://github.com/kyma-project/kyma/blob/270e7ae033034ac7fdd3cb59efc2cec3a976c725/components/compass-runtime-agent/internal/compass/director/query.go#L7

**Comment by janmedrek** [comment]
Will be handled in: https://github.com/kyma-incubator/reconciler/issues/419
