### ISSUE TITLE
Console: permissions view bugs

### ISSUE THREAD

**Issue by Wawrzyn321** [kyma-project/kyma#10307]
**Description**

* In "Create Binding" modal, `Name` input for "User Group" should accept also camelCase.
![image](https://user-images.githubusercontent.com/10504661/104198856-0805fd00-5427-11eb-9aa3-a91b75689dd4.png)
Further name processing (like conversion to kebab-case) may be required to keep compliance with k8s naming.

* When user clicks on entry in `Cluster Roles` list (_home/namespaces/default/permissions?~selectedTab=clusterRoles_), they should be redirected to clusterRole details in `Global Permissions` in view. However, namespace admin hasn't access to that view, resulting in rather unpleasant (yet elusive) Luigi navigation error.

* If user tries to create a ClusterRoleBinding, it fails for some roles.
![image](https://user-images.githubusercontent.com/10504661/104200309-c8401500-5428-11eb-825d-bdb91bcedc51.png)
It looks like while the user has the privileges to use this role, CBS doesn't.

**Comment by Wawrzyn321** [comment]
When it comes to third bug, we could either:
* Add all missing permissions to `console-backend` clusterRole.
* Create similar clusterRoleBinding (like `console-backend`) with subject set to `kyma-runtime-developer`, so that final role includes all those permissions.

**Comment by klaudiagrz** [comment]
Since this issue is customer-facing and it breaks the flow described in the official documentation, I'm adding the `priority/critical` label.

**Comment by kwiatekus** [comment]
The third case ( missing CBS roles to create role bindings ) was fixed https://github.com/kyma-project/kyma/pull/10366

**Comment by klaudiagrz** [comment]
In case you change the name input, please let me know so that I can adjust this info in the [documentation](https://help.sap.com/viewer/65de2977205c403bbc107264b8eccf4b/Cloud/en-US/dd64ac5db9d14d7aa7f5b87dc9427f18.html). For now, we have such an instruction in the SKR docs:
`As Name, insert runtimeDeveloper.`
