### ISSUE TITLE
Extend Kyma-Eventing to integrate new messaging back-end systems

### ISSUE THREAD

**Issue by radufa** [kyma-project/kyma#10312]
**Description**

Both main Kyma Eventing components (Publisher and Subscription Manager) support now two back-end messaging systems:
- BEB for SKR offering
- NATS for  OSS offering

The Publisher should support in future additional "sender" objects which will send Cloudevents messages to other back-end messaging systems. Defining logical interfaces for this kind of extensions will allow that they  could be developed by other teams/projects or OSS contributors.
The same should be possible for Subscription Manager, which should also support additional "subscription handler" objects for additional back-end messaging systems.

**Reasons**
- This will allow to have Kafka or Hyperscaler messaging systems integrated as messaging back-end systems for Kyma and usable through a unified developer programming experience.
- The OSS offering could be used in a production environment, if it's necessary.
- Better QOS (exactly once delivery) could be provided in addition to the default one.
- These extensibility features move Kyma-Eventing further on its roadmap: https://kyma-project.io/roadmap/#eventing

**Attachments**

**Comment by k15r** [comment]
Related issue: https://github.com/kyma-project/kyma/issues/9451

**Comment by mfaizanse** [comment]
Related issue: https://github.com/kyma-project/kyma/issues/12390
