### ISSUE TITLE
Inconsistent handling of environment variables in function UI

### ISSUE THREAD

**Issue by lechnerc77** [kyma-project/kyma#10311]
**Description**

The Kyma Function UI displays a section with environment variables. The section is auto-populated in case of a  service binding (values are then obfuscated, type is "Service Binding") or the user can edit the variables and add additional custom variables in the UI (values are visible, type is "Custom").

There are two issues for variables referencing secrets or config map values:

- There is no way to add environment variables referencing secrets or config maps from the UI via the "Edit Environment Variables" dialog. 
- In case the variables are referenced in a deployment file, which is possible, and the function is deployed via CLI, the variables are not displayed in the "Environment Variables" UI section

**Expected result**

- The "Edit Environment Variables" dialog should be capable of adding environment variables referencing secrets or config maps
- If the function is deployed via CLI and environment variables are referencing secrets or config maps, the environment variables should be displayed in the Functions UI of Kyma. The values of the secrets should be obfuscated

**Actual result**

- It is not possible to add environment variables referencing secrets or config maps in the "Edit Environment Variables" dialog of Kyma Functions 
- If the function is deployed via CLI and environment variables are referencing secrets or config maps, the environment variables are not displayed in the Functions UI of Kyma.

**Steps to reproduce**

- Open the "Edit Environment Variables" dialog of Kyma Functions and try to add an environment variables referencing secrets or config maps 
- Deploy a function via CLI that contains environment variables referencing secrets or config maps. After successful deployment check the "Environment Variables" section of the Functions UI for the function.

**Troubleshooting**

-

**Comment by kwiatekus** [comment]
We should add support for ENVs referneced as `valueFrom`

**Comment by kwiatekus** [comment]
We will separate those 2 concerns mentioned in the issue.
We will approach it in the following order:

 - https://github.com/kyma-project/kyma/issues/10303 (ASAP)
 - https://github.com/kyma-project/kyma/issues/10318 ( next 1.20 release)
 - remaining UI support (this issue) a bit later

**Comment by kwiatekus** [comment]
@lechnerc77 Feel free to try out [kyma CLI](https://kyma-project.io/docs/cli/#tutorials-use-kyma-cli-to-manage-functions) that comes with serverless capabilities.
With Kyma CLI you can scaffold function ( code + manifest/config file ).
You can edit the the code and config file locally (including ENVs referencing secrets or configmaps) 
I.e
```
env:
  - name: S3_BUCKET
    valueFrom:
      configMapKeyRef:
        name: s3-config
        key: s3-bucket
  - name: S3_ACCESSKEY_ID
    valueFrom:
      secretKeyRef:
        name: s3-secret
        key: s3-accesskey-id
```

After all that you can apply the changes using CLI

**Comment by lechnerc77** [comment]
@kwiatekus  Indeed, I have to take a closer look into the Kyma CLI. Thanks for the hint. Is on my todo list :-)

**Comment by lechnerc77** [comment]
Remark: The deployment via CLI works as of version 1.19 (currently an rc is available). See issue [https://github.com/kyma-project/cli/issues/715](https://github.com/kyma-project/cli/issues/715)

**Comment by valentinvieriu** [comment]
We are going to fix this in the Kyma 2.x release.

We will follow the next high level wireframes:

![image](https://user-images.githubusercontent.com/478866/125907934-a0ea8ce0-f39d-4a2b-bb08-d3dc9221546f.png)
![image](https://user-images.githubusercontent.com/478866/125907960-dbc95257-e748-4342-8475-49e539dec36f.png)
![image](https://user-images.githubusercontent.com/478866/125908032-246bf15a-824e-44c0-8530-833f2d31405e.png)

**Comment by valentinvieriu** [comment]
@lechnerc77 
We have introduced a new UI that will allow you to control the ENV Variables in the UI.
This change will be released with version 2.x of Kyma

![image](https://user-images.githubusercontent.com/478866/126933685-4e84b3e3-ecd9-4d07-992b-3b7ac96d4cd5.png)

**Comment by lechnerc77** [comment]
Looks promising :-)
