### ISSUE TITLE
Cover SKR upgrade Azure -> BEB scenario

### ISSUE THREAD

**Issue by k15r** [kyma-project/kyma#10317]
As SAP i want all SKR instances to be switched from azure to BEB.

Acceptance Criteria:
* KEB needs to provision BEB on upgrade
* Azure eventhubs needs to be removed from the cluster

**Comment by radufa** [comment]
The associated PR for the management plane config:
 https://github.tools.sap/kyma/management-plane-config/pull/839

**Comment by radufa** [comment]
Another associated PR for the management plane config, dev environment: 
https://github.tools.sap/kyma/management-plane-config/pull/853

**Comment by radufa** [comment]
Associated issue: **"Add a configurable suffix to "EMS_PUBLISH_URL""**  #10563

**Comment by radufa** [comment]
The update of KEB documentation: https://github.com/kyma-project/control-plane/pull/509

**Comment by radufa** [comment]
Related issue: https://github.com/kyma-project/kyma/issues/10593
