### ISSUE TITLE
Checkboxes of HTTP methods in access strategies of API Rules are hardly visible on Safari

### ISSUE THREAD

**Issue by mjakobczyk** [kyma-project/kyma#10321]
**Description**

Clicking checkboxes of HTTP methods in access strategies (noop, OAuth2, JWT) are hardly visible on Safari browser. In fact o only a border of every checkbox turns grey / blue. Sometimes it is hard to distinguish whether an option is chosen or not.

Kyma v1.18.
Safari v14.0.2
macOS Big Sur v11.1

**Expected result**

I expect it to render properly as in other browsers such as Chrome, where the inner part of the checkbox is filled with a colour and a tick.

<img width="522" alt="Screenshot 2021-01-13 at 15 22 49" src="https://user-images.githubusercontent.com/14920383/104464563-5f38d880-55b3-11eb-97e4-d896aa1d3d9c.png">

**Actual result**

For now checkboxes on Safari are not filled with any colour - no matters their current state.

<img width="517" alt="Screenshot 2021-01-13 at 15 23 40" src="https://user-images.githubusercontent.com/14920383/104464697-84c5e200-55b3-11eb-9ef3-b5780570493a.png">

**Steps to reproduce**

1. Provision Kyma from 1.18 release version.
2. Login to Console.
3. Create any lambda function.
4. Go to _Configuration_ -> _API Rules_.
5. Create an API Rule for a crated lambda.
6. Choose any access strategy other than _Allow_.
7. Try clicking HTTP methods' checkboxes.
The same checkboxes are available when editing existing API Rule too.

https://user-images.githubusercontent.com/14920383/104464787-9c9d6600-55b3-11eb-88a6-6cf26c1c743d.mov

**Troubleshooting**

I have checked the same path and it renders properly on Google Chrome.

**Comment by mado0803** [comment]
Same is true for the event selection popup in the functions. Cc'ing @valentinvieriu

**Comment by mado0803** [comment]
Duplicate https://github.com/kyma-project/kyma/issues/10176
