### ISSUE TITLE
Upgrade and self-manage grafana image

### ISSUE THREAD

**Issue by a-thaler** [kyma-project/kyma#10344]
**Description**
The recent grafana version 7.3.7 fixes several security issues compared to the bundled version 7.3.3

Furthermore, the default docker image of grafana introduced a big bunch of alpine packages for supporting a scenario not relevant for kyma, see also https://github.com/grafana/grafana/pull/20214
We should introduce a custom image having the related block in the Dockerfile removed giving us the chance to also update the base image whenever we need without upgrading the actual grafana version.

**Reasons**
Staying up-to-date with dependencies to be fine from known security vulnerability perspective

**Attachments**

**Comment by suleymanakbas91** [comment]
I created a custom image excluding the non-relevant parts of the original image https://github.com/kyma-incubator/third-party-images/tree/master/grafana. It is also up-to-date with the latest version of Grafana (v7.4.0) and uses the latest alpine version (v3.13) as the base image. The change to use this custom image on the Grafana chart has also been merged: https://github.com/kyma-project/kyma/commit/0f0d5a232f7d46ef38485a365f5e645101aea133
