### ISSUE TITLE
Add new tests for Eventing-Nats to check the QOS

### ISSUE THREAD

**Issue by radufa** [kyma-project/kyma#10362]
**Description**

Tests got the follwing scenarios exist in the BEB case, but are not implemented for NATS. Both scenarios must be implemented for NATS as well (as unit tests):
```
TestHandlerForHugeRequests
TestHandlerForNATSFailures (Is it still needed?)
```
**Reasons**

Improve the QOS of Kyma-Eventing OSS offering, at the same level as the production offering.

**Attachments**

**Comment by k15r** [comment]
Are they still required?

**Comment by k15r** [comment]
Tests have been reorganized. Ticket is now invalid
