### ISSUE TITLE
Deprecate Runtimes API in Connector Service

### ISSUE THREAD

**Issue by akgalwas** [kyma-project/kyma#10403]
**Description**

Connector Service offers an API for generating certificates for both Applications and Runtimes. The API for Runtimes is no longer valid as project Compass is a replacement for it. In order to avoid confusion we should deprecate this API.

**Expected result**

The API for Runtimes is marked as deprecated and the documentation mentions what APIs should be used instead.

**Actual result**

The API is still available but there is no use case for it.

**Comment by franpog859** [comment]
After the deprecation, we can create a follow-up issue to delete the deprecated API

**Comment by ralikio** [comment]
Changes required:
* All endpoints with /v1/runtimes/* - add deprecated to kyma-project/kyma/components/connector-service/docs/api/connectorapi.yaml
* Generate documentation to verify changes
* Think about adding to response message about deprecation.
