### ISSUE TITLE
Event-mesh dashboard for pods is broken

### ISSUE THREAD

**Issue by sayanh** [kyma-project/kyma#10407]
**Description**

Following issues are happening:
- Data for event-service is missing in the event-mesh dashboard for pods. 
- istio-system namespace is appearing in the drop-down.

This is happening in Kyma 1.19rc1.

<img width="1605" alt="Screenshot 2021-01-21 at 10 39 37" src="https://user-images.githubusercontent.com/5954057/105332526-04b40380-5bd5-11eb-94fb-f1525ec6f390.png">

<img width="1438" alt="Screenshot 2021-01-21 at 10 45 19" src="https://user-images.githubusercontent.com/5954057/105333269-d08d1280-5bd5-11eb-858a-2dccc8f0ebde.png">

**Expected results**

- Event-service along with connectivity-validator and event-source should be in the dashboard.
- istio-system namespace shouldn't be appearing in the namespaces drop-down.

**Comment by k15r** [comment]
the event-service is gone from recent kyma releases
