### ISSUE TITLE
Cannot send event - 500 internal server error returned

### ISSUE THREAD

**Issue by pbochynski** [kyma-project/kyma#10409]
**Description**
In many integration tests infrastructure to send events is not started within a reasonable time (reasonable means seconds, maybe 1 minute, but not more than 5 minutes)

**Expected result**

Events can be sent when application CR is in the state ready.

**Actual result**
```
time="2021-01-21T08:04:44Z" level=info msg="Proxying request for commerce application. Path: /commerce/v1/events"
time="2021-01-21T08:04:44Z" level=info msg="Proxying request to target URL: http://commerce-event-service:8081/commerce/v1/events"
time="2021-01-21T08:04:44Z" level=info msg="Host responded with status: 500 Internal Server Error"
```

**Steps to reproduce**

One example is here:
https://github.com/kyma-incubator/local-kyma/runs/1740271643
The test cluster still exists. Contact me on (@pbochynski ) slack to get the kubeconfig.

**Comment by pbochynski** [comment]
Another example:
https://storage.googleapis.com/kyma-prow-logs/logs/kyma-integration-production-gardener-azure/1353675370502557696/build-log.txt

**Comment by sayanh** [comment]
Looks pretty stable now, https://github.com/kyma-incubator/local-kyma/actions/workflows/app-connector-e2e-k3s.yml

**Comment by k15r** [comment]
The entire event-mesh will be removed with 1.21. As this is release is getting created at the time of writing i will close
