### ISSUE TITLE
Commerce Mock test fails on kyma-integration pipeline (Timeout of 600000ms exceeded)

### ISSUE THREAD

**Issue by akgalwas** [kyma-project/kyma#10427]
**Description**

The following error occurs on kyma-integration-gardener pipelines:
```
  1) CommerceMock tests
       CommerceMock test fixture should be ready:
     Error: Timeout of 600000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/home/prow/go/src/github.com/kyma-project/kyma/tests/fast-integration/test/commerce-mock.js)
      at listOnTimeout (internal/timers.js:554:17)
      at processTimers (internal/timers.js:497:7)

  2) CommerceMock tests
       function should reach Commerce mock API through app gateway:
     Error: Request failed with status code 500
      at createError (node_modules/axios/lib/core/createError.js:16:15)
      at settle (node_modules/axios/lib/core/settle.js:17:12)
      at IncomingMessage.handleStreamEnd (node_modules/axios/lib/adapters/http.js:260:11)
      at endReadableNT (_stream_readable.js:1327:12)
      at processTicksAndRejections (internal/process/task_queues.js:80:21)

  3) CommerceMock tests
       order.created.v1 event should trigger the lastorder function:
     AssertionError: expected { order: {}, event: { data: { orderCode: '789' } } } to have nested property 'event.ce-type'
      at /home/prow/go/src/github.com/kyma-project/kyma/tests/fast-integration/test/fixtures/commerce-mock/index.js:85:41
      at processTicksAndRejections (internal/process/task_queues.js:93:5)
      at async sendEventAndCheckResponse (test/fixtures/commerce-mock/index.js:60:3)
      at async Context.<anonymous> (test/commerce-mock.js:22:5)

```
Exemplary logs:
- https://storage.googleapis.com/kyma-prow-logs/logs/kyma-integration-evaluation-gardener-azure/1352089958940151808/build-log.txt
- https://storage.googleapis.com/kyma-prow-logs/logs/kyma-integration-hibernation-gardener-azure/1352164198846566400/build-log.txt
- https://storage.googleapis.com/kyma-prow-logs/logs/kyma-integration-hibernation-gardener-azure/1352164198846566400/build-log.txt

**Expected result**

Test is green

**Comment by crabtree** [comment]
Unfortunatelly the resource limits increment did not help. We still observe failing tests:
- https://storage.googleapis.com/kyma-prow-logs/logs/kyma-integration-evaluation-gardener-azure/1358582879545724928/build-log.txt
- https://storage.googleapis.com/kyma-prow-logs/logs/kyma-integration-evaluation-gardener-azure/1358220489142571009/build-log.txt
- https://storage.googleapis.com/kyma-prow-logs/logs/kyma-integration-evaluation-gardener-azure/1358129891890958337/build-log.txt
- https://storage.googleapis.com/kyma-prow-logs/logs/kyma-integration-evaluation-gardener-azure/1357993994360983552/build-log.txt
- https://storage.googleapis.com/kyma-prow-logs/logs/kyma-integration-evaluation-gardener-azure/1358129891890958337/build-log.txt
- https://storage.googleapis.com/kyma-prow-logs/logs/kyma-integration-evaluation-gardener-azure/1357918497597820928/build-log.txt
