### ISSUE TITLE
Commerce Mock test fails on kyma-integration pipeline (event should trigger the lastorder function)

### ISSUE THREAD

**Issue by akgalwas** [kyma-project/kyma#10426]
**Description**

The following error occurs on kyma-integration-gardener pipelines:
```
1) CommerceMock tests
       order.created.v1 event should trigger the lastorder function:
     AssertionError: expected { order: 
   { orderId: '789',
     totalPriceWithTax: { value: 100 },
     cancellable: true },
  event: { data: { orderCode: '789' } } } to have nested property 'event.ce-type'
```
Exemplary logs:
- https://storage.googleapis.com/kyma-prow-logs/logs/kyma-integration-production-gardener-azure/1352452298260877313/build-log.txt
- https://storage.googleapis.com/kyma-prow-logs/logs/kyma-integration-evaluation-gardener-azure/1351999361399132161/build-log.txt

**Expected result**

Test is green

**Comment by berkanercan** [comment]
Fixed with the new eventing backend PR https://github.com/kyma-project/kyma/pull/10793. kyma-integration-gardener jobs are green.
