### ISSUE TITLE
Installer does not start installation after pod crash

### ISSUE THREAD

**Issue by crabtree** [kyma-project/kyma#1045]
When running local installation when installer pod crashes the installation does not restarts. It hangs on downloading kyma sources. The problem exists because during first start the kyma sources are delivered to the installer using `kubectl cp` and after restart they are not available.

AC:
The local installation process should handle kyma sources in more persistent way or we should switch to kyma-installer image which has sources embedded.

**Comment by ormos** [comment]
Why are we still dynamically copy the installation artefacts into the installer pod? The goal was to have one static image including all the needed artefacts for the installation - with the exception of the container images?
Where can I find a kind of architectural overview and some status diagrams how the installer is working today?

**Comment by nexus49** [comment]
Is there any update on this topic? We have also observing this a number of times during cluster installations.

**Comment by Tomasz-Smelcerz-SAP** [comment]
Local installation is using Kyma-Installer image built on the fly. It means this error will never occur again, Kyma sources are always available in Kyma-installer.
