### ISSUE TITLE
Add short tutorial on how to use unified logging library

### ISSUE THREAD

**Issue by franpog859** [kyma-project/kyma#10458]
**Description**

Add a short tutorial (for example `kyma/common/logging/README.md`) on how to use the logging library. Main features should be described and examples of the usage should be provided. We may also want to link the Application Connectivity Validator as it's the first exemplary migrated component (after the merge of [this PR](https://github.com/kyma-project/kyma/pull/10315))

The tutorial should not be merged before [this PR](https://github.com/kyma-project/kyma/pull/10315) as it is the library implementation

**Area**
* Common library
* Logging

**Reasons**

The logging library is implemented in a way that every component should be able to use it. Therefore everyone should be able to easily get to know it 

**Assignees**

@kyma-project/technical-writers
@dbadura (library owner)
@franpog859 (library owner)

**Comment by mmitoraj** [comment]
Hi @franpog859, could you update us on the status of the issue?

**Comment by franpog859** [comment]
I'm closing this issue as I haven't seen any interest in having such a document. Please, reopen it if needed
