### ISSUE TITLE
Function controller build time is too long and hits timeout

### ISSUE THREAD

**Issue by kwiatekus** [kyma-project/kyma#10478]
**Description**

The build pipeline build multiple elements
It hits the timeout

We should consider splitting it to multiple build jobs

**Expected result**

Build job should not timeout

**Actual result**

Build job hits timeout

**Steps to reproduce**

**Troubleshooting**

**Comment by kwiatekus** [comment]
license puller is not required anymore as we are no longer  offered via google marketplace

**Comment by aerfio** [comment]
It's already handled, we've gone from 15min to 8min (approx)

**Comment by aerfio** [comment]
![image](https://user-images.githubusercontent.com/17271979/107770767-30d92500-6d3a-11eb-98d8-250a7c7b4135.png)
