### ISSUE TITLE
OAuth Token Expiration Time

### ISSUE THREAD

**Issue by sundarvc** [kyma-project/kyma#10471]
Hi Team,

I am looking at the docs here - https://kyma-project.io/docs/components/api-gateway/ and it doesn't say how long the Client Credentials token is valid for ? Can someone tell me when the token will expire and a new token needs to be issued or is it supposed to be done for each call ?

Thanks,
Sundar

**Comment by colunira** [comment]
You can find this information in the [Ory Hydra documentation](https://github.com/ory/hydra/blob/master/docs/docs/reference/configuration.md) under the key `ttl`. We do not modify the defaults.
