### ISSUE TITLE
Enable publish API to use sourceId value from header if present

### ISSUE THREAD

**Issue by abbi-gaurav** [kyma-project/kyma#1048]
### Description
As discussed with @lszymik we can get away from the events service. This service is only enriching the events metadata with the `sourceId` value. 
However, this can also be done at the proxy level (nginx or istio not revelant.) 

**This is also important from resource efficiency perspective**

For publish API in event-bus, it will be required to handle the scenario where `sourceId` is sent via the headers vs in the HTTP payload.

###Order of Precedence
1.  If `sourceId` is present in the payload is highest
1.  else one in the header is used
1. If none present, an error is thrown. As decided by the team, we will return 4xx in case `sourceId` is missing. This needs to be translated to 5xx at the proxy level.

### AC:
- [x] **There is an agreement with Framefrogs about the error propagation and translation. (Do this as the first step before starting code)**
- [x] Event Bus publish API handles the sourceId header value and uses it in the FQTN.
- [x] The validations done in event service are applied in publish.
- [x] The `/re/v1/events` should remain unchanged.
- [x] The tracing for events works as expected.

**Comment by lszymik** [comment]
Thank you very much. Please keep in mind that backward compatibility must be ensured at least for a transition phase :)

**Comment by lszymik** [comment]
@abbi-gaurav we need to change dependencies here. The issue is not blocked, but it is blocking. The header with `sourceId` must be implemented first; then we will be able to test forwarding headers.

Kindly please treat it with a priority.

**Comment by abbi-gaurav** [comment]
Verified with the new image.

## source-id in body
```bash
 curl -i \
>         -H "Content-Type: application/json" \
>         -X POST http://core-publish.kyma-system:8080/v1/events \
>         -d '{"source-id": "stage.commerce.kyma.local", "event-type": "test-eve
nt-bus", "event-type-version": "v1", "event-time": "2018-11-02T22:08:41+00:00",
"data": {"orderCode": "1", "orderPrice": 123.40}}'
HTTP/1.1 200 OK
Content-Type: application/json
Date: Wed, 10 Oct 2018 11:28:42 GMT
Content-Length: 52

{"event-id":"b4f0db60-b87e-4404-8441-5a2b990aaa7b"}
```

### Source-Id as Header
```bash
/ # curl -i \
>         -H "Content-Type: application/json" \
>         -H "Source-Id: stage.commerce.kyma.local" \
>         -X POST http://core-publish.kyma-system:8080/v1/events \
>         -d '{"event-type": "test-event-bus", "event-type-version": "v1", "event-time": "2018-11-02T22:08:41+00:00", "data": {"orderCode": "2", "orderPrice": 123.40}}'
HTTP/1.1 200 OK
Content-Type: application/json
Date: Wed, 10 Oct 2018 11:34:29 GMT
Content-Length: 52

{"event-id":"6a6b3a6c-8cf6-45f3-9fe3-6be72bec9f3f"}
/ # curl -i -X GET http://example-subscriber.test-event-bus:8080/v1/events
HTTP/1.1 200 OK
date: Wed, 10 Oct 2018 11:34:32 GMT
content-length: 106
content-type: text/plain; charset=utf-8
x-envoy-upstream-service-time: 4
server: envoy

[{"orderId":"1","namespace":"default","total":123.4},{"orderId":"2","namespace":"default","total":123.4}]
```

## precedence check
```bash
/ # curl -i \
>         -H "Content-Type: application/json" \
>         -H "Source-Id: pr.commerce.kyma.local" \
>         -X POST http://core-publish.kyma-system:8080/v1/events \
>         -d '{"source-id": "stage.commerce.kyma.local", "event-type": "test-event-bus", "event-type-version": "v1", "event-time": "2018-11-02T22:08:41+00:00", "data": {"orderCode": "3", "orderPrice": 123
.40}}'
HTTP/1.1 200 OK
Content-Type: application/json
Date: Wed, 10 Oct 2018 11:36:38 GMT
Content-Length: 52

{"event-id":"21be3f61-736f-4040-a79d-4f000e9d43a9"}
/ # curl -i -X GET http://example-subscriber.test-event-bus:8080/v1/events
HTTP/1.1 200 OK
date: Wed, 10 Oct 2018 11:36:40 GMT
content-length: 158
content-type: text/plain; charset=utf-8
x-envoy-upstream-service-time: 58
server: envoy

[{"orderId":"1","namespace":"default","total":123.4},{"orderId":"2","namespace":"default","total":123.4},{"orderId":"3","namespace":"default","total":123.4}]
```

**Comment by abbi-gaurav** [comment]
Verified the traces
![Screen Shot 2018-10-10 at 14.35.59.png](https://images.zenhubusercontent.com/5b83ad9b79c9991fcdb9a287/13b8d32d-559f-423c-90ec-2b48e3846385)

![Screen Shot 2018-10-10 at 14.36.35.png](https://images.zenhubusercontent.com/5b83ad9b79c9991fcdb9a287/6dd0ac5b-86d9-4d13-985c-b1a9d9fae607)
