### ISSUE TITLE
Broken instalation of console-web on minikube with evaluation profile

### ISSUE THREAD

**Issue by dbadura** [kyma-project/kyma#10506]
**Description**
I cannot install kyma with console-web on minikube with evaluation profile
**Expected result**
I can install kyma with evaluation profile on minikube

**Actual result**
Consolwe-web can't start container:
```
  Warning  Failed     8m33s (x4 over 9m23s)   kubelet            Error: failed to start container "console": Error response from daemon: OCI runtime create failed: container_linux.go:370: starting container process caused: process_linux.go:338: getting the final child's pid from pipe caused: read init-p: connection reset by peer: unknown

```
**Steps to reproduce**
provision minikkube with `kyma provision minikube` and run `kyma install -s master --profile evaluation

**Comment by Sawthis** [comment]
I cannot reproduce it. @dbadura please reopen if needed.

**Comment by valentinvieriu** [comment]
Note: As we are switching very soon to k3s, we might not support minikube in the near future.
