### ISSUE TITLE
envFrom lost after function's pod restarted

### ISSUE THREAD

**Issue by VishnAndr** [kyma-project/kyma#10501]
**Description**
We're having an issue from time to time. A function has service bindings attached. And uses them to call external systems. 
The function works perfectly fine for a while. But once in a while, we start getting errors **Error: connect ECONNREFUSED 127.0.0.1:80**
There is nothing been done to the function manually from our end. It used to work. But for some reason (I'm guessing - hyperscaler's-related) it has been restarted just recently. And what has happened with the restart: the function container lost **"Environment Variables from:"** part completely. In Console, in the function UI, I can see service bindings and environment variables which corresponds to them (*_GATEWAY_URL). But _k describe pod_ function doesn't show "Environment Variables from " (nor _k get pod -o yaml_ shows **envFrom** ) and hence we're getting the mentioned error. Because there is no destination to call. 

And affected functions are random. Some of the functions on the restarted node still have those secrets in envFrom. Other functions on the same node lost envFrom. The services are the same in both lost and remained function 

Looking into GKE logs, I found what happened with the nodes - auto-upgrade of the node pool.
Command gcloud container operations list tells this (with the type of the operation as UPGRADE_NODES). The upgrade took 24 minutes (we have 6 nodes cluster at the moment) and this was when the functions' pods restarted and some of them lost envFrom

**Expected result**

Function doesn't lose service bindings and continue to work when restarted for whatever reason.

**Actual result**

Function loses service bindings (the pod that executes the function loses the envFrom that points to the secret with the url of the gateway)

**Steps to reproduce**

Restart nodes upgrading default pool using operation from hyperscaller (??? don't know, didn't try to reproduce, just a guess ???)

**Troubleshooting**

The workaround is to delete service bindings from function in Console and then create them again.

**Comment by kwiatekus** [comment]
Hi @VishnAndr 
 I see simple pod restart doesnt show this symptoms. Seems its  related with how serverless and service catalog components are handling node maintanance window.
 We will try to reproduce it.

**Comment by VishnAndr** [comment]
Hi @kwiatekus, thx. We have Kyma 1.18.0 on GKE.

**Comment by kwiatekus** [comment]
It does not seem as serverless bug. ENV injection (comming from service binding usage) is a duty of service binding usage controller. There seems to be a problem  during node pool upgrade.
During the node pool upgrade, GKE tries to shift pods to free-up one node at a time and perform an upgrade. The SBU's are lost in the process.
@PK85 could you validate my thinking here?
I will try to reproduce myself as well.

**Comment by tgorgol** [comment]
I tried reproducing this error, here are my findings:

1. This doesn't seem like a problem with Service Binding Usage because, as Andrei said, the Service Bindings and environment variables were visible in Console UI in Function view.
2. If SBU existed I thought that it might have been a problem with a PodPreset, either a:
    - missing PodPreset resource,
    - missing Function label that would be matched by PodPreset,
    - problem with PodPreset admission webhook.

I was able to reproduce only the thirds scenario. I scaled the `cluster-essentials-pod-preset-webhook` deployment down to `0` and deleted Function pod. The pod was recreated but because the admission webhook was down, the environment variables weren't injected. Even after scaling the admission webhook service back to `1` the pod wasn't automatically restarted. Restarting the Function pod manually after the admission webhook is working fixes this problem.

I can't be sure if that's the exact scenario that happened on Andrei's cluster but it sounds reasonable to me that during node upgrade both webhook service and Function pod might have been restarted at the same time.

**Comment by PK85** [comment]
Hi, I think we need to apply https://kubernetes.io/blog/2018/04/30/zero-downtime-deployment-kubernetes-jenkins/#rolling-update for that deployment: https://github.com/kyma-project/kyma/blob/master/resources/cluster-essentials/charts/pod-preset/templates/webhook/deploy.yaml

+ above deployment has replicaCount set to 1.

**Comment by PK85** [comment]
Please reopen if issue still exists.

**Comment by VishnAndr** [comment]
Hi @PK85 ,
The fix suggested was working for a while now, thank you. But today it's failed. Can we reopen the issue, please?

The reason I reckon is that coincidently both cluster-essentials-pod-preset-webhook pods were running on the same node. 
Once the node has been restarted because of the update from GKE, some functions lost envFrom again.

Is there a way to make these pods run on different nodes and not on the same one to prevent this from happening?

Attaching the logs from the pods.
Pod 1 started at 2021-02-22T16:26:01Z 
Pod 2 started at 2021-02-22T16:26:07Z

Logs are taken at 2021-02-22T23:04:51Z after I fixed the functions by restarting functions manually.

Both cluster-essentials-pod-preset-webhook pods are running on the same node again currently.

[pod-preset-webhook-1.txt](https://github.com/kyma-project/kyma/files/6025860/pod-preset-webhook-1.txt)
[pod-preset-webhook-2.txt](https://github.com/kyma-project/kyma/files/6025861/pod-preset-webhook-2.txt)

**Comment by PK85** [comment]
Hello @VishnAndr,

you were extremely "lucky" to have such a situation. You have 6 nodes, podpreset repilca set to 2. I'm assuming that they were distributed on two nodes, then one node was down, and pod was replicated to the node where podpreset pod 1 already exists.

Ok, there is way to prevent that situation. Please set that flag to true, see: https://github.com/kyma-project/kyma/blob/d88b1359caccc200d3906d4ac2f77eb9f9f631c7/resources/cluster-essentials/charts/pod-preset/values.yaml#L11

Cheers, Piotr
