### ISSUE TITLE
How to integrate user management such as ORY kratos

### ISSUE THREAD

**Issue by eldad87** [kyma-project/kyma#10538]
Hi,
I'm researching for an holistic open-source solution that can help me focus on what I do best, and its developing my application business logic. This is how I got here.
I went through your documentation and the project is impressive. The only missing piece is a user-management system such as Kratos. 

Can you please point me to relevant documentation on how replace Dex with Kratos, Integrate Dex with Kratos etc.
Please advise,
Thanks!

**Comment by kwiatekus** [comment]
Hi @eldad87 
We are aiming to simplify authentication stack in kyma.
Our goal (mid term) goal is to remove dex from kyma and let the users authenticate via OIDC compliant Identity provider of their choice.

With this in mind I would simply configure an OIDC capable ID provider to dex ( following this [tutorial](https://kyma-project.io/docs/components/security/#tutorials-add-an-identity-provider-to-dex) )
and later on you would be able to use the same provider once dex is gone.
