### ISSUE TITLE
Disabled reporting "kyma-integration-gardener-gcp-parallel"

### ISSUE THREAD

**Issue by adamwalach** [kyma-project/kyma#10575]
**Description**

This job is constantly red:
https://status.build.kyma-project.io/job-history/kyma-prow-logs/logs/kyma-integration-gardener-gcp-parallel

It fails on half of the tests:
```
Waiting for test suite to finish: 19 out of 19 test(s) have finished (Succeeded: 8, Failed: 11, Skipped: 0)...
```
When it's fixed we should re-enable reporting

**Comment by suleymanakbas91** [comment]
Reporting has been disabled by https://github.com/kyma-project/test-infra/commit/d578d0bb1395a885a218cf2a81724951920ed12c.

**Comment by Halamix2** [comment]
`kyma-integration-gardener-gcp-parallel` was removed in kyma-project/test-infra#3334
