### ISSUE TITLE
For open source offering, an empty "eventTypePrefix" is preferable as the current default one: "sap.kyma.custom". 

### ISSUE THREAD

**Issue by radufa** [kyma-project/kyma#10579]
## Description
For the open source offering, an empty "eventTypePrefix" is preferable as the current default one: "sap.kyma.custom". Of course this should be configurable as a global value and used by the calling applications, if necessary.

## Acceptance
- [ ] on OSS it is possible to run eventing without a prefix: ""
- [ ] documentation is updated
- [ ] prefix is configurable using a config map, so that other components can read the configured value from there

**Comment by k15r** [comment]
should be part of #11064
