### ISSUE TITLE
Oathkeeper-Maester with high uptime freezes randomly

### ISSUE THREAD

**Issue by Tomasz-Smelcerz-SAP** [kyma-project/kyma#10571]
**Description**

Oathkeeper-Maester stops reconciling Rules on long-living clusters.
We've observed a cluster with three Oathkeeper Pods. An Oathkeeper-Maester runs as a container in every Pod.
In two Pods, the Oathkeeper-Maester does not reconcile new Rules, does not produce any logs.
The process is running, but apparently doing nothing useful.

**Expected result**

The Oatkeeper-Maester is processing new Rules, which can be confirmed by looking at its logs.

**Actual result**

Logs are empty, no new entries are produced when new Rules are defined in the system.

**Steps to reproduce**

All we know is that it takes a long time, possibly days/weeks before the controller enters such a state.

**Troubleshooting**

A manual restart of the Oathkeeper Pod.

**Comment by wwosik** [comment]
Can the manual restart be done for a managed Kyma instance? If yes, how?

**Comment by Tomasz-Smelcerz-SAP** [comment]
@wwosik If you have cluster access with admin rights, deleting the Pod is enough. The deployment controller will bootstrap a new one. Just don't delete all Pods at once, because it can cause noticeable downtime.

**Comment by werdes72** [comment]
If it happens again please reopen. We haven't noticed that problem again yet.
