### ISSUE TITLE
Explain in docs how we use istio and how and why we patch it

### ISSUE THREAD

**Issue by derberg** [kyma-project/kyma#1059]
**Description**

- document component introduced with https://github.com/kyma-project/kyma/pull/861/files
- extend https://kyma-project.io/docs/latest/components/service-mesh and explain how we really use istio:
  - is it one to one? if not why and how we patch it
  - how patching works
  - what does that mean for the customer
  - what things we patch and why

**Reasons**

We do not use always latest istion one to one. We need to patch it and Kyma users need to understand why.

**Comment by piotrmsc** [comment]
We have added documentation covering kyma requirements for istio, how we install istio and what is and hows work our istio patch.

Examples : https://kyma-project.io/docs/components/service-mesh#details-istio-patch
https://kyma-project.io/docs/root/kyma#installation-installation-with-custom-istio-deployment

I will close this issue, please reopen the issue if you find some information worth adding or improving
