### ISSUE TITLE
Function-webhook is not working correctly

### ISSUE THREAD

**Issue by m00g3n** [kyma-project/kyma#10599]
**Description**

Defaulting webhook in function-webhook fails.

```
{"level":"error","msg":"Error in Check if Git Function has correct default values, error: minReplicas equal nil","suite":"serverless-integration-gitops","time":"2021-02-11T13:40:37Z"}
```

Investigation started in: [PR](https://github.com/kyma-project/kyma/pull/10574)

- The image for `function-webhook` in serverless [values](https://github.com/kyma-project/kyma/blob/master/resources/serverless/values.yaml#L240) file differs from the one that is in `webhook` subchart [values](https://github.com/kyma-project/kyma/blob/master/resources/serverless/charts/webhook/values.yaml#L9) file.

- The regression was probably introduced in commit: `c44616f06`

**Comment by kwiatekus** [comment]
@m00g3n Please check if this could be closed
