### ISSUE TITLE
CRD guidelines are missing convention to name fields

### ISSUE THREAD

**Issue by abbi-gaurav** [kyma-project/kyma#1065]
### Description
There is a guideline to write the [CRDs](https://github.com/kyma-project/community/blob/master/guidelines/custom-resource-definitions.md). However, there are no details about `How the fields should be named?`.

This is causing inconsistency in the Kyma CRDs
 Look here 

https://github.com/kyma-project/kyma/blob/master/resources/cluster-essentials/templates/eventing-subscription.crd.yaml#L42
and 
https://github.com/kyma-project/kyma/blob/master/resources/cluster-essentials/templates/event-activation.crd.yaml#L20

Before fixing or changing one of them and maybe others, there should be a decision and guideline about naming fields and it should be documented.

**Comment by pbochynski** [comment]
Just check what is the naming convention in Kubernetes project and apply this one. Period.

**Comment by pbochynski** [comment]
The convention in Kubernetes is to use camel case. So this is the recommendation for Kyma as well.
