### ISSUE TITLE
Update the document about OAuth2 server profiles

### ISSUE THREAD

**Issue by klaudiagrz** [kyma-project/kyma#10654]
**Description**

The [OAuth2 server profiles](https://kyma-project.io/docs/master/components/security#configuration-o-auth2-server-profiles) document in its current form contains outdated and misleading information. It does not contain info about OAuth2 server working in the [production profile](https://kyma-project.io/docs/master/root/kyma#installation-overview-profiles) per se, but rather info on different modes of OAuth2 server configuration recommended for production purposes. Values for production profile are also included but are mixed with other production-recommended values for OAuth2 server configuration, that's why it's quite misleading. Values specific for the production profile per se should be removed from this document as a follow-up to [this](https://github.com/kyma-project/kyma/issues/9902) issue for describing profiles in a generic way, and only the configuration part should be left in this doc. 

Since it's difficult to differentiate which values are specific for the production profile and which are a part of the OAuth2 server configuration, some help from the developer's side will be needed to update this document.

**Area**

area/documentation
area/security

**Reasons**

The document in its current form is outdated and provides misleading info about production profile / OAuth2 server configuration.

**Assignees**

@kyma-project/technical-writers

**Related issues**

https://github.com/kyma-project/kyma/issues/9238
https://github.com/kyma-project/kyma/issues/9902

**Comment by mmitoraj** [comment]
Add/ update configuration documents of the ORY chart and sub-charts:
ory -> https://github.com/strekm/kyma/blob/main/resources/ory/values.yaml
gcloud-sqlproxy -> https://github.com/strekm/kyma/blob/main/resources/ory/charts/gcloud-sqlproxy/values.yaml
hydra -> https://github.com/strekm/kyma/blob/main/resources/ory/charts/hydra/values.yaml
oathkeeper -> https://github.com/strekm/kyma/blob/main/resources/ory/charts/oathkeeper/values.yaml
postgresql -> https://github.com/strekm/kyma/blob/main/resources/ory/charts/postgresql/values.yaml

**Comment by mmitoraj** [comment]
Closed with the following PR https://github.com/kyma-project/kyma/pull/11868.
