### ISSUE TITLE
Certificates management followups

### ISSUE THREAD

**Issue by colunira** [kyma-project/kyma#10691]
**Description**

The `certificates` chart needs some adjustments:

- [x] Remove the `net-global-overrides` CM creation when https://github.com/kyma-incubator/hydroform/issues/208 and https://github.com/kyma-incubator/hydroform/issues/187 are implemented
- [x] Remove the Gardener domain fetching when https://github.com/kyma-incubator/hydroform/issues/187 is implemented

We also need to provide the documentation:

- [ ] Prepare an example ClusterIssuer for Azure
- [ ] Document installation, configuration, and current approach

**Comment by strekm** [comment]
closing in favour of https://github.com/kyma-project/kyma/issues/11628
