### ISSUE TITLE
Service Instance for SAP Sales Cloud doesn't show events specification

### ISSUE THREAD

**Issue by VishnAndr** [kyma-project/kyma#10702]
**Description**
In a service instance for standard "SAP Sales Cloud" service from the connected SAP C4C application in console UI shows an error in API section.
The error says: "Error: This is not a valid AsyncAPI Schema Object."
 

Kyma 1.19.0 (open source)

**Expected result**

Expected to see events published from the corresponding C4C system.

**Actual result**

The actual result is a described error.
**Steps to reproduce**

Connect SAP C4C application
Bind the application to a namespace
Provision service instance for "SAP Sales Cloud" service from Service Catalog
Navigate into the provisioned service instance
Observe the error in API section for 'async-api'.

**Troubleshooting**

It happens with both systems: recently connected and which was connected for a long time.

Events are still can be subscribed to in functions. And are delivered fine.

![image](https://user-images.githubusercontent.com/4543139/108788977-546b5d80-75cd-11eb-909f-184ebc363047.png)

**Comment by valentinvieriu** [comment]
@VishnAndr we are aware of this, the Api schema coming from SAP C4C needs to be adjusted.

**Comment by mado0803** [comment]
We are working on a patch that will ignore the `null`-ed objects and arrays so that this won't happen in future releases. Furthermore, I am working on getting the sources corrected. https://github.com/kyma-project/rafter/pull/101

**Comment by PK85** [comment]
Closing, if needed reopen
