### ISSUE TITLE
Kyma Dashboard - Enable Oauth Client Setting for tokenEndpointAuthMethod: client_secret_post

### ISSUE THREAD

**Issue by djochim** [kyma-project/kyma#10745]
**Description**

It should be possible to set the tokenEndpointAuthMethod Spec of an Oauth client over the kyma dashboard.
This simplifies the usage of the clients in combination with the SAP Destination Service.

**Reasons**

SAP Destination Service is often used to maintain the credentials to other systems and also to kyma functions. The find destination functionality, where the destination service retrieves the authentication token from the OAuth client, uses the client_secret_post functionality. 
This is not allowed by default which means, that every custumer has to use the CLI to adopt his OAuth client.

**Comment by djochim** [comment]
Also related to #10536

**Comment by Tomasz-Smelcerz-SAP** [comment]
@djochim Just to clarify:

You can set the `tokenEndpointAuthMethod` attribute in the spec of the OAuth2Client CR instance (apiGroup: `hydra.ory.sh/v1alpha1`) and it is propagated to the Hydra server.

From your description, I assume you know that already, and all you miss is the ability to configure the attribute using Kyma Web UI.
Is that correct?

**Comment by djochim** [comment]
@Tomasz-Smelcerz-SAP Yes I am aware of this option and besides the open issue, this is totally fine for me. Nevertheless, this is part of our extension strategy, and from the view of a customer, this would be a downside. 

All settings and development could be done in the UI, but to secure the function and connect it over the SAP Destination Service, the customer would need the CLI.

**Comment by ovidiumuntean** [comment]
Would be great if there will be a user interface to set up the tokenEndpointAuthMethod for the OAuth2Client instance.
Me and my team are new to Kyma and we spent some time figuring out how to enable the client_secret_post auth method.
In our project the chatbot and other technologies we use are only supporting the  client_secret_post auth method.

**Comment by valentinvieriu** [comment]
For Kyma 2.0 we've updated the API Rule View, so we are looking for ways to add more options as advanced ones, hope to get an update soon to this topic
<img width="1261" alt="image" src="https://user-images.githubusercontent.com/478866/150919962-e81fee7b-7235-4c08-b81b-bf8261f943ef.png">

**Comment by valentinvieriu** [comment]
@ovidiumuntean  @djochim In the new Kyma 2.0 Interface you get more options in the advance view.
Please check our implementation and reopen this issue if the solution provided is not acceptable.
https://dashboard.stage.kyma.cloud.sap

<img width="1325" alt="image" src="https://user-images.githubusercontent.com/478866/150920473-beddeba2-3f05-4f60-8e1a-591d05138469.png">
