### ISSUE TITLE
Outdated name of Config Map with overrides for TLS certificates in documentation

### ISSUE THREAD

**Issue by tgorgol** [kyma-project/kyma#10742]
**Description**

In [this](https://kyma-project.io/docs/components/security#tutorials-update-tls-certificate) tutorial, there is a command using an outdated name of Config Map containing installer overrides with TLS certificates.

```yaml
kubectl edit cm -n kyma-installer owndomain-overrides
```

Currently, this data seems to be stored in `global-installer-config` Config Map instead.

**Expected result**

Command suggested in docs should work.

**Actual result**

Command returns an error about non-existing resource.

**Steps to reproduce**

Follow the tutorial.

**Comment by superojla** [comment]
This tutorial is already corrected, changes will be visible in release 1.20.
#10383
