### ISSUE TITLE
Outdated documentation when upgrading SSL certificate

### ISSUE THREAD

**Issue by philippe-lavoie** [kyma-project/kyma#10750]
## Description

In [this](https://kyma-project.io/docs/components/security#tutorials-update-tls-certificate) tutorial, the command to removed the backend is wrong

```
kubectl delete pod -n kyma-system -l app=console-backend
```

The fix is

```
kubectl delete pod -n kyma-system -l app=backend
```

Not sure when console was removed, but it's not there in 1.19

## Expected result

Command suggested in docs should work. 

## Actual result

Command returns an error about non-existing resource.

## Steps to reproduce

Follow the tutorial.

**Comment by superojla** [comment]
This tutorial is already corrected, changes will be visible in release 1.20.
#10383
