### ISSUE TITLE
Add storage limitations for NATS to avoid OOM in production

### ISSUE THREAD

**Issue by radufa** [kyma-project/kyma#10751]
**Description**
Add a default configuration for in memory storage limits for NATS

**Reasons**
Avoid OOM under load to not lose all "in memory" stored events. This could happen if the receiver is slower as the sender.
The publisher-proxy should get an error at sending of an event to NATS if these limits are reached. 

**Attachments**

**Comment by radufa** [comment]
Some links from NATS documentation:
https://docs.nats.io/nats-server/nats_admin/slow_consumers
https://docs.nats.io/nats-server/configuration#limits

**Comment by raypinto** [comment]
Q: Is this still relevant for JetStream with file storage?
