### ISSUE TITLE
Kyma version (or branch) being released is not visible in the release action

### ISSUE THREAD

**Issue by jose-cortina** [kyma-project/kyma#10779]
**Description**

As a Release Manager I approve Kyma releases with the release workflow in GitHub. When the release is created, a branch is selected for which the release is being done, and this selection is not visible for me when I approve the workflow. 

**Reasons**

For the approval it would be beneficial to see which release branch is the release triggered for.

**Attachments**

Approval screen
![image](https://user-images.githubusercontent.com/40632700/109792787-2bbe1600-7c14-11eb-9e1d-c28790d935ac.png)

**Comment by dekiel** [comment]
We would like to drop github actions part for release process and run all steps on a prow. We will use this issue to check if release version is visible in all needed places after migration.
