### ISSUE TITLE
Make running acceptance tests for Application Connector easier

### ISSUE THREAD

**Issue by akgalwas** [kyma-project/kyma#1078]
**Description**

Currently developer does some manual steps to run acceptance tests. Having a script running acceptance tests would shorten feedback loop.

**Reasons**

Running acceptance tests should be easy. Currently there is a need to do some manual steps to run acceptance tests which is time consuming and error-prone

**Comment by Maladie** [comment]
The current idea is to build Application Connector’s images and acceptance tests images and push them to local docker registry on minikube. Then, replace image in deployment yaml inside kyma with image from minikube local registry. There is an article how to easily built docker image into minikube: https://blog.hasura.io/sharing-a-local-registry-for-minikube-37c7240d0615

To do:
- check if there is a simple and clever way to replace GCR image with image from local registry
- prepare script that will create local registry on minikube (if not present), map port 5000 to minikube registry pod,  build images, replace current images with newly built ones and launch tests.
