### ISSUE TITLE
Failing Rafter tests

### ISSUE THREAD

**Issue by dariadomagala** [kyma-project/kyma#10794]
**Description**

Rafter tests are failing due to:
```      
testsuite.go:138: Fetching data of files from asset...
      testsuite.go:258: 
          Unexpected error:
              <*errors.fundamental | 0xc0004ce120>: {
                  msg: "Invalid status code while downloading file from URL https://storage.gkeint-commit-40773735-1iuabi0fa3.a.build.kyma-project.io/test-bucket-1cq91lpi08d1s/test-asset/README.md: 404. Expected: 200",
```

Example:
https://status.build.kyma-project.io/view/gcs/kyma-prow-logs/logs/post-master-kyma-gke-rapid-integration/1367429779430576128

**Expected result**

Tests should be green

**Actual result**

Tests are unstable

**Steps to reproduce**

**Troubleshooting**

**Comment by kwiatekus** [comment]
The `storage` API is soon to be disabled. We would rather disable the test ( please see linked issue ) rather than investigating flakiness
