### ISSUE TITLE
Tests are unstable on gardener azure

### ISSUE THREAD

**Issue by dariadomagala** [kyma-project/kyma#10817]
**Description**

Commerce mock / getting started guide tests are unstable on Gardener Azure pipelines.
Examples:
* `Error: Timeout: commerce-application-gateway is not ready`
https://status.build.kyma-project.io/view/gcs/kyma-prow-logs/logs/kyma-integration-evaluation-gardener-azure-big/1367929451974758400
* `Error: Waiting for service instance redis-service timeout`
https://status.build.kyma-project.io/view/gcs/kyma-prow-logs/logs/kyma-integration-evaluation-gardener-azure-big/1367944550827429888
https://status.build.kyma-project.io/view/gcs/kyma-prow-logs/logs/kyma-integration-production-gardener-azure/1367944550831624192
https://status.build.kyma-project.io/view/gcs/kyma-prow-logs/logs/kyma-integration-production-gardener-azure/1368065347445329920
* `Error: Timeout of 600000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.`
https://status.build.kyma-project.io/view/gcs/kyma-prow-logs/logs/kyma-integration-production-gardener-azure/1368065347445329920
* `Problem while sending event: Kyma application API responded with status 500`
https://status.build.kyma-project.io/view/gcs/kyma-prow-logs/logs/kyma-integration-evaluation-gardener-azure-big/1368110645966278656
https://status.build.kyma-project.io/view/gcs/kyma-prow-logs/logs/kyma-integration-evaluation-gardener-azure-big/1368110645966278656

**Expected result**

Tests should be stable.

**Actual result**

Tests are unstable.

**Steps to reproduce**

**Troubleshooting**

**Comment by Tomasz-Smelcerz-SAP** [comment]
Another example for Getting Started Guide Tests:
```
1) Getting Started Guide Tests
       Should print report of restarted containers, skipped if no crashes happened:
     TypeError: Cannot read property 'restartCount' of undefined
      at /home/prow/go/src/github.com/kyma-project/kyma/tests/fast-integration/utils/index.js:639:42
      at Array.map (<anonymous>)
      at /home/prow/go/src/github.com/kyma-project/kyma/tests/fast-integration/utils/index.js:630:12
      at Array.map (<anonymous>)
      at printRestartReport (utils/index.js:615:6)
      at Context.<anonymous> (test/3-getting-started-guides.js:33:5)
      at processTicksAndRejections (internal/process/task_queues.js:93:5)
```
See:
- https://status.build.kyma-project.io/view/gcs/kyma-prow-logs/logs/kyma-integration-evaluation-gardener-azure/1377472141393399808
- https://status.build.kyma-project.io/view/gcs/kyma-prow-logs/logs/kyma-integration-evaluation-gardener-azure/1377441941758676992

**Comment by dekiel** [comment]
Another pipeline affected by similar errors. kyma-integration-hibernation-azure
https://status.build.kyma-project.io/job-history/kyma-prow-logs/logs/kyma-integration-hibernation-gardener-azure

**Comment by ralikio** [comment]
I have implemented a smal correction https://github.com/kyma-project/kyma/pull/11380 for undefined restartCount.
