### ISSUE TITLE
Azure pipelines failing with `Error: Waiting for shoot condition to finish: ControlPlaneHealthy`

### ISSUE THREAD

**Issue by dariadomagala** [kyma-project/kyma#10819]
**Description**

Azure pipelines failing with `Error: Waiting for shoot condition to finish: ControlPlaneHealthy.
Examples:
https://status.build.kyma-project.io/view/gcs/kyma-prow-logs/logs/kyma-integration-hibernation-gardener-azure/1368471781190406144
https://status.build.kyma-project.io/view/gcs/kyma-prow-logs/logs/kyma-integration-evaluation-gardener-azure-big/1368473038986678272
https://status.build.kyma-project.io/view/gcs/kyma-prow-logs/logs/kyma-integration-production-gardener-azure/1368473038995066881

**Expected result**

Pipelines should be stable.

**Actual result**

**Steps to reproduce**

**Troubleshooting**

**Comment by adamwalach** [comment]
We need to check if there are any reports about instability of gardener. I think for issue like that we need to gather a separate metric on our quality report

**Comment by Tomasz-Smelcerz-SAP** [comment]
A very similar set of failed jobs with error `Error: Waiting for rollout to start`
```
+ kyma provision gardener az --secret kyma-azure --name grddqvax9 --project kyma-prow --credentials /etc/credentials/gardener-kyma-prow/kubeconfig --region northeurope -z 1 -t Standard_D8_v3 --disk-type StandardSSD_LRS --kube-version=1.19 --verbose
X Provisioning Gardener cluster on Azure
Error: All attempts fail:
#1: unable to provision gardener cluster: 
Error: Waiting for rollout to start

  on ../../../../../../../root/.kyma/clusters/gardener/kyma-prow/grddqvax9/terraform.tf line 52, in resource "gardener_shoot" "gardener_cluster":
  52: resource "gardener_shoot" "gardener_cluster" {


#2: unable to provision gardener cluster: 
Error: shoots.core.gardener.cloud "grddqvax9" already exists

  on ../../../../../../../root/.kyma/clusters/gardener/kyma-prow/grddqvax9/terraform.tf line 52, in resource "gardener_shoot" "gardener_cluster":
  52: resource "gardener_shoot" "gardener_cluster" {


Error: Waiting for rollout to start


#3: unable to provision gardener cluster: 
Error: shoots.core.gardener.cloud "grddqvax9" already exists

  on ../../../../../../../root/.kyma/clusters/gardener/kyma-prow/grddqvax9/terraform.tf line 52, in resource "gardener_shoot" "gardener_cluster":
  52: resource "gardener_shoot" "gardener_cluster" {


Error: Waiting for rollout to start
``` 

Links:
- https://storage.googleapis.com/kyma-prow-logs/logs/kyma-integration-production-gardener-azure/1377245650193747969/build-log.txt
- https://storage.googleapis.com/kyma-prow-logs/logs/kyma-integration-gardener-azure/1377244391730581504/build-log.txt
- https://storage.googleapis.com/kyma-prow-logs/logs/kyma-integration-production-gardener-azure/1377215449372037120/build-log.txt
- https://storage.googleapis.com/kyma-prow-logs/logs/kyma-integration-evaluation-gardener-azure/1377200349827305472/build-log.txt

**Comment by adamwalach** [comment]
I checked stackdriver logs and in the last 3 months there is only one occurrence of the cluster names that you mentioned. So this is NOT a collision between two jobs.
My gut feeling is that somewhere in the provisioning procedure we have a loop that retries a failed operation. Maybe there is a rare scenario when we request creation of a cluster, the operation fails (but the cluster was in fact created), we try to create a cluster with the same name and this time we get the "already exists" error.

**Comment by dekiel** [comment]
This error messages were discussed here. Pipelines doesn't fail because cluster exist, but fail because cluster is not ready before timeout. The default kyma-cli behaviour is to retry cluster creation three times.
https://sap-btp.slack.com/archives/C01L56LPE65/p1617106125009800
@clebs do you know if there is a way to increase timeout for cluster creation and what's the current timeout we use?

**Comment by clebs** [comment]
Hi @dekiel,
currently creation timeout is set to 30 minutes for all providers and unfortunately we do not have a flag to dynamically set this on the CLI at the moment.

Nevertheless, I am not sure if this is a timeout issue, since 3 tries with 30 minutes each should be enough.
To me this looks like the 2nd and 3rd try immediately return because they get an error back on the request t the gardener seed.

As I suggested on the discussion we had, I would bring this to the gardener team so that we can gain more insight on why it happens.

**Comment by adamwalach** [comment]
For now the only solution that we can think of is to add a workaround to our pipeline - when this error occurs we will retry the operation with different cluster name (old "zombie" cluster will be automatically removed by cleaner)

**Comment by mfaizanse** [comment]
Multiple instances of tests `kyma-alpha-integration-evaluation-gardener-azure`, `kyma-alpha-integration-production-gardener-azure`, `kyma-integration-production-gardener-azure` and `kyma-integration-evaluation-gardener-azure` are failed with similar error:

```
X Provisioning Garden(Azure) cluster
Error: unable to provision gardener cluster: 
Error: shoots.core.gardener.cloud "grd0kpcmc" already exists

  on ../../../../../../../root/.kyma/clusters/gardener/kyma-prow/grd0kpcmc/terraform.tf line 55, in resource "gardener_shoot" "gardener_cluster":
  55: resource "gardener_shoot" "gardener_cluster" {


Error: Shoot operation failed: Flow "Shoot cluster reconciliation" encountered task errors: [task "Syncing shoot access credentials to project namespace in Garden" failed: retry failed with context deadline exceeded, last error: 4 errors occurred:
	* secrets "grd0kpcmc.monitoring" is forbidden: exceeded quota: gardener, requested: count/secrets=1, used: count/secrets=126, limited: count/secrets=126
	* secrets "grd0kpcmc.ssh-keypair.old" is forbidden: exceeded quota: gardener, requested: count/secrets=1, used: count/secrets=126, limited: count/secrets=126
	* secrets "grd0kpcmc.ssh-keypair" is forbidden: exceeded quota: gardener, requested: count/secrets=1, used: count/secrets=126, limited: count/secrets=126
	* secrets "grd0kpcmc.kubeconfig" is forbidden: exceeded quota: gardener, requested: count/secrets=1, used: count/secrets=126, limited: count/secrets=126

]


2021/07/30 12:14:10 UTC [INFO] cluster provisioning failed, trying provision new cluster
2021/07/30 12:14:10 UTC [INFO] cleaning damaged cluster first
2021/07/30 12:14:10 UTC [INFO] Deprovision cluster: grd0kpcmc
shoot.core.gardener.cloud/grd0kpcmc annotated
shoot.core.gardener.cloud "grd0kpcmc" deleted
2021/07/30 12:14:10 UTC [INFO] building new cluster name
2021/07/30 12:14:10 UTC [INFO] Provision cluster: "grdmib06y"
- Validating flags
X Provisioning Garden(Azure) cluster
Error: unable to provision gardener cluster: 
Error: shoots.core.gardener.cloud "grdmib06y" already exists

  on ../../../../../../../root/.kyma/clusters/gardener/kyma-prow/grdmib06y/terraform.tf line 55, in resource "gardener_shoot" "gardener_cluster":
  55: resource "gardener_shoot" "gardener_cluster" {


Error: Waiting for shoot condition to finish: ControlPlaneHealthy
```

Links to logs:
- https://storage.googleapis.com/kyma-prow-logs/logs/kyma-alpha-integration-evaluation-gardener-azure/1421079508575850496/build-log.txt
- https://storage.googleapis.com/kyma-prow-logs/logs/kyma-alpha-integration-production-gardener-azure/1421079508609404928/build-log.txt
- https://storage.googleapis.com/kyma-prow-logs/logs/kyma-integration-production-gardener-azure/1421079508517130240/build-log.txt
- https://storage.googleapis.com/kyma-prow-logs/logs/kyma-integration-evaluation-gardener-azure/1421079508491964416/build-log.txt
