### ISSUE TITLE
Configurable authentication for kiali and jaeger UI

### ISSUE THREAD

**Issue by a-thaler** [kyma-project/kyma#10811]
**Description**
At the moment the kiali and jaeger UI require authentication against the in-cluster dex by default. There is no way to disable it fully nor you can configure a different OIDC provider.

Goal: Make the authentication for the UIs optional (enabled by default) and have the OIDC provider configurable

Acceptance:
- A new override exists to disable authentication fully for the UIs, resulting in not deploying any unneeded resources (like the kxproxy component)
- Overrides exists to configure a custom OIDC provider with related clientId/secret

**Reasons**
Probably dex will be removed from the kyma stack by default and users should provide OIDC providers as optional config input.

**Attachments**

**Comment by JeremyHarisch** [comment]
Changed authentication for the UIs of Kiali and Jaegger to optional. 
Default is set to enabled. Can be configured in the 'values.yaml'

Furthermore, 'discoveryurl' was moved to values.yaml to make the configuration more simple.
