### ISSUE TITLE
Failing tests on GKE 1.20.2-gke.2500

### ISSUE THREAD

**Issue by adamwalach** [kyma-project/kyma#10810]
**Description**

The `post-master-kyma-gke-rapid-integration` job started failing when the new version of GKE (1.20.2-gke.2500) appeared on the rapid channel. 
First failure happened on 3.3.2021 - https://status.build.kyma-project.io/view/gcs/kyma-prow-logs/logs/post-master-kyma-gke-rapid-integration/1367004095398809600 

Two tests are failing randomly:
- kyma-system/api-gateway 
- kyma-system/rafter

**I am not sure if we should invest time in debugging** because of two reasons:
- this is a new gke version on the rapid channel - it may contain some bugs that will be fixed by google
- <s>api-gateway</s> and rafter are kind of deprecated, they might be gone till we migrate to 1.20

api-gateway is **NOT depracated**, so we might need to have a closer look into the issue

Since this job is red all the time we will disable reporting for now

**Related issue**
https://github.com/kyma-project/kyma/issues/10794

**Comment by kwiatekus** [comment]
For rafter you are right - it is in maintenance mode. No new features will be developed. API gateway stays.

Looks like the root cause for both rafter and api-gateway are probably the same 

```
  --- FAIL: TestApiGatewayIntegration (302.21s)
      main_test.go:465: 
          	Error Trace:	main_test.go:465
          	Error:      	Received unexpected error:
          	            	All attempts fail:
          	            	#1: unexpected response 404 Not Found: 
skipped 99 lines unfold_more
          	            	
          	            	#11: unexpected response 404 Not Found: {"error":{"code":404,"status":"Not Found","request":"3cc7b9e9-0e47-4a43-b41e-b6557747242b","message":"The requested resource could not be found"}}
          	            	
          	            	#12: unexpected response 404 Not Found: {"error":{"code":404,"status":"Not Found","request":"9359cc2f-1efd-45c0-8862-331498b479a2","message":"The requested resource could not be found"}}
          	Test:       	TestApiGatewayIntegration
```

```
                    cause: {
                        Op: "Get",
                        URL: "https://storage.gkeint-commit-40007ec9-y8sacuywur.a.build.kyma-project.io/test-bucket-1coji8athgcfa/test-asset/README.md",
                        Err: {
                            Op: "dial",
                            Net: "tcp",
                            Source: nil,
                            Addr: nil,
                            Err: {
                                Err: "no such host",
                                Name: "storage.gkeint-commit-40007ec9-y8sacuywur.a.build.kyma-project.io",
                                Server: "10.203.240.10:53",
                                IsTimeout: false,
                                IsTemporary: false,
                                IsNotFound: true,
                            },
                        },
```

**Comment by adamwalach** [comment]
Yes, you are right, I changed the description.
