### ISSUE TITLE
Support Kyma installation from private registry

### ISSUE THREAD

**Issue by Haegi** [kyma-project/kyma#10860]
**Description**

At the moment the kyma installer image can only get pulled from public registries.
When building the installer image from the local source and pushing it to a private registry, the kyma installation runs into an error because the `kyma-installer` service account doesn't have permissions to access/pull from the private registry.

Current workaround:

```bash
#Create the kyma-installer in advance
kubectl create namespace kyma-installer

# Create the image pull secret
kubectl create secret docker-registry image-pull-secret --docker-server=<your-private-registry> --docker-username=<your-username> --docker-password=<your-password> -n kyma-installer

# Add the image-pull-secret to the kyma-installer service account in the installer.yaml:
imagePullSecrets:
- name: image-pull-secret

# Install kyma from local source
kyma install -v --source=local --custom-image=<your-private-registry>/kyma-installer:latest --src-path=$PWD
```

**Reasons**

Support for private registries in the installation process would allow developers to extend kyma with their own software (e.g. helm charts) without having to worry about exposing the code (e.g. helm chart) to the public.

**Attachments**

**Comment by pbochynski** [comment]
Hi Haegi,
kyma-installer is going to be deprecated. We work now on the new way of the installation: https://github.com/kyma-project/kyma/issues/10297. Therefore this feature won't be implemented.
To install your software you can use helm client directly or use helm-operator instead.
