### ISSUE TITLE
Review the existing content on the website

### ISSUE THREAD

**Issue by klaudiagrz** [kyma-project/kyma#10876]
**Description**

Since we are going to totally restructure the content on the `kyma-project.io` website, first of all, we need to review the existing content and decide which parts should stay and which should be removed or moved to the components' README files. 

**Area**

area/documentation

**Reasons**

We need to decide what to do with the content before restructuring it. 

**Assignees**

@kyma-project/technical-writers

**Related issues**

https://github.com/kyma-project/kyma/issues/10857

**Comment by pbochynski** [comment]
Review of the existing documentation.
- Overview
   - In a nutshell - rewrite -> Overview (PB)
   - Main features - remove (reuse some parts in the Overview)
   - Technology stack - remove
   - Key Components - rewrite -> main areas with architecture and key feature (PB)
- Getting started - remove (reuse small parts in the Tasks section)
- Security - to be reviewed
- Service Catalog - to be reviewed
- Helm Broker - remove
- Application Connector - to be reviewed
- Event Mesh - remove
- Service mesh - to be reviewed
- Serverless - to be reviewed
- Monitoring - to be reviewed
- Tracing - to be reviewed
- Logging - to be reviewed
- Console - to be reviewed
- Rafter - remove
- Runtime Agent - to be reviewed
- Kiali - to be reviewed

**Comment by pbochynski** [comment]
I went through all of the topics and categorized them (comment above). I think we are ready to move the content to the new structure and start working on updates.
