### ISSUE TITLE
There is no resource quota for istio

### ISSUE THREAD

**Issue by sjanota** [kyma-project/kyma#1088]
**Description**
Previously we had resource quota and limit range for istio-system namespace in istio charts. Now, after we removed all customization to istio charts from kyma  both of them have been removed. They have to be brought back in patch process.

**Expected result**
There is limit range and resource quota in istio-system namespace.

**Actual result**
Resource quota and limit range are missing

**Notes**
 * make sure that limits are high enough to fit in default istio installation
 * see how istio behaves if limits are too low, e.g. containers are restarted

**Comment by piotrmsc** [comment]
Closing for now, we will not provide RQ for istio at least for now.
