### ISSUE TITLE
Application broker doesn't register service classes within 5 minutes

### ISSUE THREAD

**Issue by pbochynski** [kyma-project/kyma#10886]
**Description**
For the last week the number of failed tests with the timeout on waiting for service class registration extremely increased. More than 50% tests on evaluation profile and about 10% of tests on production profile fail because service class of commerce web services is not created on time.
Example for production profile:
https://status.build.kyma-project.io/view/gcs/kyma-prow-logs/logs/kyma-integration-production-gardener-azure/1371160748851466241
Logs from kyma-integration namespace: https://cloudlogging.app.goo.gl/xgrRVBfjKwrTXjun6
From logs it seems that connectivity validator has some issues.

On the evaluation profile the issue can be observed in almost every run. Last 3 examples from today:
https://status.build.kyma-project.io/view/gcs/kyma-prow-logs/logs/kyma-integration-evaluation-gardener-azure/1371357042236723200
https://status.build.kyma-project.io/view/gcs/kyma-prow-logs/logs/kyma-integration-evaluation-gardener-azure/1371341942436139008
https://status.build.kyma-project.io/view/gcs/kyma-prow-logs/logs/kyma-integration-evaluation-gardener-azure/1371326843105316864

**Expected result**

**Actual result**

Service class in the service catalog is not available within 5 minutes from API registration in the metadata service. The error:
```
Error: Waiting for webservices service class timeout (300000 ms)
```

**Steps to reproduce**
Just watch prow jobs: 
- https://status.build.kyma-project.io/?job=kyma-integration-evaluation-gardener-azure
- https://status.build.kyma-project.io/?job=kyma-integration-production-gardener-azure

**Troubleshooting**

Consider running tests in debug mode. You can do it with setting env:
```
export DEBUG=true
```
before tests are started.

**Comment by polskikiel** [comment]
There are 2 problems: 
- Controller manager crashes due to the issue in SC
- Application broker sometime doesn't create ServiceBrokers and fails to provide ServiceClasses
Both problems will be addressed in this PR: https://github.com/kyma-project/kyma/pull/10908
See the PR's description for more details.
