### ISSUE TITLE
*.local.kyma.dev does not work with AVM Fritz!Box Router

### ISSUE THREAD

**Issue by johgoe** [kyma-project/kyma#10881]
This issue ist just to document an issue with Routers like a AVM Fritz!Box Router.

This routers have a DNS Rebind protection which mean that all external DNS queries which resolves to a local address e.g `127.0.0.1` are blocked and results in a `Unkown host`  exception.

It's possible to define single exceptions like `console.local.kyma.dev` but currently it is not possible to add a wildcard exception like `*.local.kyma.dev`.

This kind of router is very popular in Germany.

Possible workarounds using static external dns servers like `8.8.8.8` or the one of your ISP instead of the local router DNS which is provided by DHCP.

Other workarounds like adding many single exceptions on the router or adding entries to your Hosts file is also possible.

I already contacted AVM support and hope that they will add a wildcard exception feature in one of there next releases.

**Comment by Tomasz-Smelcerz-SAP** [comment]
A long document, but comprehensible for people that are not security experts: https://crypto.stanford.edu/dns/dns-rebinding.pdf
Many routers/devices/Internet providers may implement a similar kind of protection against this attack.

**Comment by themue** [comment]
Had to solve it with the combination [local kyma](https://github.com/kyma-incubator/local-kyma) / Mac / Fritz!Box. Solved it by

- installation of `dnsmasq`,
- adding of entry `address=/local.kyma.dev/127.0.0.1` to `/usr/local/etc/dnsmasq.conf` and restarting of `dnsmasq`
- adding a `resolver` entry for `local.kyma.dev`

```
$ sudo mkdir -p /etc/resolver
$ sudo tee /etc/resolver/local.kyma.dev >/dev/null <<EOF
nameserver 127.0.0.1
EOF
```

Now DNS requests for `*.local.kyma.dev` are resolved via the locally running `dnsmasq` which answers with 127.0.0.1.
