### ISSUE TITLE
ConnectionTokenHandler deployment keeps disappearing from kyma-integration ns

### ISSUE THREAD

**Issue by sayanh** [kyma-project/kyma#10892]
**Description**

In `pre-master-kyma-integration-k3s` job pipeline, the connection-token-handler keeps disappearing from `kyma-integration` ns. 
```
$k get deploy -n kyma-integration
NAME                              READY   UP-TO-DATE   AVAILABLE   AGE
commerce-application-gateway      1/1     1            1           3m34s
commerce-connectivity-validator   1/1     1            1           3m34s
```

As a result, the `TokenRequest` does not get reconciled(there is no status) which impacts the test as it times out at fetching tokenrequest.
```
Error: Wait for TokenRequest timeout
    at Timeout._onTimeout (/home/sa_117798148653314453801/kyma/tests/fast-integration/utils/index.js:294:18)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
    1) CommerceMock test fixture should be ready
    2) function should reach Commerce mock API through app gateway
```

**Expected result**

connection-token-handler should be present and reconcile tokenrequest CRs.

Samples:
https://status.build.kyma-project.io/log?id=1371512824882270208&job=pre-master-kyma-integration-k3s
https://storage.googleapis.com/kyma-prow-logs/pr-logs/pull/kyma-project_kyma/10793/pre-master-kyma-integration-k3s/1371507918255427584/build-log.txt

**Comment by crabtree** [comment]
The deployment is deleted by the job named `eventing-post-upgrade` as it wrongly lookups the components to delete.

**Comment by sayanh** [comment]
The root cause is different, hence closing this.
