### ISSUE TITLE
Remove Rafter docs from the website

### ISSUE THREAD

**Issue by klaudiagrz** [kyma-project/kyma#10927]
**Description**

We are moving towards Kyma 2.0 release and thus we need to restructure the existing website and content to match the current vision and the roadmap. Since [Rafter](https://kyma-project.io/docs/master/components/rafter/) as a component is no longer supported in Kyma 2.0, we need to remove it from the Kyma 2.0 documentation. The existing content may be moved to the [`rafter`](https://github.com/kyma-project/rafter) repository.

**Area**

* Documentation
* Rafter 

**Reasons**

Kyma 2.0 does not support Rafter. 

**Assignees**

@kyma-project/technical-writers

**Related issues**

https://github.com/kyma-project/kyma/issues/10857
https://github.com/kyma-project/kyma/issues/10876

**Comment by kazydek** [comment]
Docs were moved and ordered properly in the `rafter` repo in [this pull request](https://github.com/kyma-project/rafter/pull/102).
