### ISSUE TITLE
Kyma UI shows error

### ISSUE THREAD

**Issue by sundarvc** [kyma-project/kyma#10942]
Hi Team,

When Pods are in initially created and in waiting mode, the Deployment UI shows "Error" state. It should also say "Waiting".

Regards,
Sundar

**Comment by valentinvieriu** [comment]
Thank you @sundarvc . We are pinking most of the time the status from Kubernetes. We will revisit all of those status labels for he release of Kyma 2.0

**Comment by valentinvieriu** [comment]
We are going to change this with the new Release of Kyma Dashboard.
