### ISSUE TITLE
Don't have permission to patch

### ISSUE THREAD

**Issue by sundarvc** [kyma-project/kyma#10941]
Hi Kyma team,

I notice that I don't have "patch" or edit permission in a namespace I created on the "servicesinstances" object.
e.g. I cannot do

kubectl edit serviceinstance1 serviceinstances -n custom_namespace.

User yy@zzz.com" cannot patch resource "serviceinstances" in API group "servicecatalog.k8s.io" in the namespace "custom_namespace"

Regards,
Sundar

**Comment by PK85** [comment]
@sundarvc We don't have such a role in the opensource Kyma project.
