### ISSUE TITLE
Filtering while searching for an event breaks for dots

### ISSUE THREAD

**Issue by suleymanakbas91** [kyma-project/kyma#10956]
**Description**

When I try to create an event subscription for my function, filtering breaks for `.` while searching for an event. For example, I'm searching for `order.created` event and writing `order` in the filter, and filtering works fine. But, when I add the `.`, it does not show anything. 

**Expected result**

It would show me all the events starting with `order.`.

**Comment by Sawthis** [comment]
@suleymanakbas91 we won't fix this issue in Console. We are working now on new Kyma Dashboard which will be released soon.
