### ISSUE TITLE
event traces stop at nats publisher in clusters with new eventing system

### ISSUE THREAD

**Issue by sayanh** [kyma-project/kyma#10957]
**Description**

Adapt tracing from application connectivity validator to function for new eventing as the trace headers are lost from Nats publisher proxy as shown in the attached screenshot.

<img width="1992" alt="Screenshot 2021-03-23 at 15 38 16" src="https://user-images.githubusercontent.com/5954057/112163970-cd220180-8bed-11eb-8bbe-d49004036831.png">

**Comment by k15r** [comment]
Labelled as a bug, as this is a feature that was working before and stopped working with the new eventing system
