### ISSUE TITLE
Api-Gateway test is failing with error 'Could not retrive status'

### ISSUE THREAD

**Issue by tobiscr** [kyma-project/kyma#10965]
**Description**

API-Gateway test case is failing because status could not be retrieved.

**Expected result**

Test case is passed successfully. If possible, please add further details to error ("Could not retrieve status" is a quite general failure which doesn't indicate what exactly went wrong).

**Actual result**

      2021/03/23 07:23:58 Fallback to default http client
       2021/03/23 07:23:58 Using namespace: api-gateway-test-rkcads
       2021/03/23 07:23:58 Using OAuth2Client with name: api-gateway-tests-client-mviyre, secretName: api-gateway-tests-secret-mviyre
       2021/03/23 07:23:58 Delete test namespace, if exists: api-gateway-test-rkcads
       2021/03/23 07:24:08 Creating common tests resources
       2021/03/23 07:24:08 Resource found: api-gateway-test-rkcads
       2021/03/23 07:24:08 Resource found: api-gateway-tests-secret-mviyre
       2021/03/23 07:24:18 Creating hydra client resources
       2021/03/23 07:24:18 Resource found: api-gateway-tests-client-mviyre
       2021/03/23 07:24:28 Resource found: api-gateway-tests-client-mviyre
       2021/03/23 07:24:28 Error: Could not retrive status, or status not found:
       <nil>
       --- FAIL: TestApiGatewayIntegration (30.11s)
       panic: Error: Could not retrive status, or status not found:
       <nil> [recovered]
       	panic: Error: Could not retrive status, or status not found:
       <nil>

       goroutine 6 [running]:
       testing.tRunner.func1(0xc00019c200)
       	/usr/local/go/src/testing/testing.go:830 +0x392
       panic(0xb03540, 0xc000328320)
       	/usr/local/go/src/runtime/panic.go:522 +0x1b5
       log.Panicf(0xc31009, 0x3a, 0xc0001e9ad8, 0x1, 0x1)
       	/usr/local/go/src/log/log.go:340 +0xc0
       github.com/kyma-project/kyma/tests/integration/api-gateway/gateway-tests/pkg/resource.(*Manager).GetStatus(0xc0001896a0, 0xd0b5e0, 0xc00000e418, 0xc000324020, 0xc, 0xc00032402d, 0x8, 0xc000326020, 0xd, 0xc000324040, ...)
       	/workspace/go/src/github.com/kyma-project/kyma/tests/integration/api-gateway/gateway-tests/pkg/resource/manager.go:96 +0x257
       command-line-arguments.TestApiGatewayIntegration(0xc00019c200)
       	/workspace/go/src/github.com/kyma-project/kyma/tests/integration/api-gateway/gateway-tests/main_test.go:176 +0x1121
       testing.tRunner(0xc00019c200, 0xc42320)
       	/usr/local/go/src/testing/testing.go:865 +0xc0
       created by testing.(*T).Run
       	/usr/local/go/src/testing/testing.go:916 +0x35a

**Steps to reproduce**

**Troubleshooting**

**Comment by Tomasz-Smelcerz-SAP** [comment]
We have to verify if it's the same root cause as in the: https://github.com/kyma-project/kyma/issues/8914

**Comment by pbochynski** [comment]
The test is replaced by fast-integration tests.
