### ISSUE TITLE
Serverless test case fails on weekly cluster tries to create resource in terminating namespace

### ISSUE THREAD

**Issue by tobiscr** [kyma-project/kyma#10967]
**Description**

Severless test case was failing on the weekly cluster because "forbidden" error response was replied when creating resources in Kubernetes.

**Expected result**

Test case is passed successfully.

**Actual result**

      {\"level\":\"error\",\"msg\":\"while executing step: Create NodeJS12 Function: while creating function: Create NodeJS12 Function: while creating Function nodejs12 in namespace test-parallel-8h-44m-5s: while creating resource Function: functions.serverless.kyma-project.io \\"nodejs12\\" is forbidden: unable to create new content in namespace test-parallel-8h-44m-5s because it is being terminated\",\"time\":\"2021-03-22T08:44:14Z\"}

**Steps to reproduce**

**Troubleshooting**

**Comment by dbadura** [comment]
Do you have more logs?
