### ISSUE TITLE
Application connnector test failing on nightly-aks cluster

### ISSUE THREAD

**Issue by tobiscr** [kyma-project/kyma#10966]
**Description**

The application connector test is failing on the nighty AKS cluster.

**Expected result**

Tests are passing successfully.

**Actual result**

Several failures were tracked.

First failing test case:

      Run kubernetes tests
      --- FAIL: TestTokenRequests (25.07s)
      --- FAIL: TestTokenRequests/should_create_token_request_CR_with_token (25.07s)
      require.go:1159:
      	Error Trace:	k8sresource_test.go:51
      	 				k8sresource_test.go:33
      	Error: 	Should be true
 	Test: 	TestTokenRequests/should_create_token_request_CR_with_token
      FAIL
      End of logs from container \"tests\" in pod \"oct-tp-testsuite-all-connection-token-handler-0\" in status \"Failed\"
      Start of logs from container \"tests\" in pod \"oct-tp-testsuite-all-connection-token-handler-1\" in status \"Failed\"
      Connection Token Handler tests
      Run kubernetes tests
      --- FAIL: TestTokenRequests (25.06s)
      --- FAIL: TestTokenRequests/should_create_token_request_CR_with_token (25.06s)
      require.go:1159:
      	Error Trace:	k8sresource_test.go:51
      	 				k8sresource_test.go:33
      	Error: 	Should be true
      	Test: 	TestTokenRequests/should_create_token_request_CR_with_token
      FAIL
      End of logs from container \"tests\" in pod \"oct-tp-testsuite-all-connection-token-handler-1\" in status \"Failed\"
      Start of logs from container \"serverless-tests\" in pod \"oct-tp-testsuite-all-serverless-0\" in status \"Failed\"
      TESTING has started

Second failing test case:

      Start of logs from container \"tests\" in pod \"oct-tp-testsuite-all-application-connector-0\" in status \"Failed\"
      Application Operator tests
      Run Application Access tests
      === RUN TestApplicationAccess
      application_access_test.go:16: Stating Application flow tests
      2021/03/23 06:26:33 Read configuration: {SkipSSLVerify:true Namespace:kyma-integration}
      application_access_test.go:20: Creating test application...
      suite.go:117: Waiting for Application to be deployed...
      suite.go:125: Application installation status does not equal deployed
      suite.go:117: Waiting for Application to be deployed...
      suite.go:125: Application installation status does not equal deployed
      suite.go:117: Waiting for Application to be deployed...
     ...
      suite.go:117: Waiting for Application to be deployed...
      application_access_test.go:24: Application created
      application_access_test.go:26: Exchanging certificates to establish connection for app-conn-tests-595d application...
      suite.go:152: Waiting for Info URL in Token Request...
      suite.go:152: Waiting for Info URL in Token Request...
      suite.go:152: Waiting for Info URL in Token Request...
      suite.go:152: Waiting for Info URL in Token Request...
     ....
      suite.go:152: Waiting for Info URL in Token Request...
      suite.go:156:
      	Error Trace:	suite.go:156
      	 				suite.go:162
      	 				application_access_test.go:27
      	Error: 	Received unexpected error:
      	 	timeout waiting for condition
      	Test: 	TestApplicationAccess
      suite.go:86: Cleaning up app-conn-tests-595d token request
      suite.go:80: Cleaning up app-conn-tests-595d application
      --- FAIL: TestApplicationAccess (138.47s)
      FAIL
      End of logs from container \"tests\" in pod \"oct-tp-testsuite-all-application-connector-0\" in status \"Failed\"

**Steps to reproduce**

**Troubleshooting**

**Comment by koala7659** [comment]
This is duplicate of https://github.com/kyma-project/kyma/issues/9191

**Comment by tobiscr** [comment]
Closed as duplicate of #9191
