### ISSUE TITLE
Cannot upgrade Kyma installation using Kyma CLI

### ISSUE THREAD

**Issue by tobiscr** [kyma-project/kyma#10964]
**Description**

It's not possible to upgrade Kyma using the Kyma CLI. This blocks customers from applying configuration changes on Kyma.

**Expected result**

Command `kyma upgrade  -s $VERSION` triggers the upgrade routine and updates overrides.

**Actual result**

     $> kyma upgrade  -s 1.21.0-rc1
     - Cluster info read
       No migration guide available for upgrade from version '1.21.0-rc1' to version '1.21.0-rc1'
       Upgrading Kyma from version '1.21.0-rc1' to version '1.21.0-rc1'
     X Preparing Upgrade
     Error: Failed to start upgrade: Failed to prepare upgrade: failed to apply Installer resources: failed to apply resource: failed to create object kyma-installer of kind PriorityClass: priorityclasses.scheduling.k8s.io is forbidden: User "admin@kyma.cx" cannot create resource "priorityclasses" in API group "scheduling.k8s.io" at the cluster scope

**Steps to reproduce**

**Troubleshooting**

* Open shell
* Install latest Kyma CLI
* Execute `kyma upgrade  -s 1.21.0-rc1`

**Comment by a-thaler** [comment]
You used a kubeconfig downloaded from the kyma console with limited permissions (I guess the kyma-admin role).
That role should not be able to install/upgrade kyma, it requires a cluster-admin role

**Comment by tobiscr** [comment]
This issue was discovered during applying test-case https://github.com/kyma-project/kyma/issues/9637

**Comment by tobiscr** [comment]
@a-thaler : ok, thanks for clarifying. But it assume we have still a permission issue as the call of the upgrade-cmd was able to delete the installer. I assume even that should not be allowed, shouldn't it ?
