### ISSUE TITLE
Cluster user test fails on weekly cluster when deleting of non-existing namespace

### ISSUE THREAD

**Issue by tobiscr** [kyma-project/kyma#10978]
**Description**

The cluster-user test case is failing on the weekly-cluster because the test tries to delete a non-existing namespace at the end of the test execution.

**Expected result**

Test can be passed successfully.

**Actual result**

Octopus reports following logs:

      ALL TESTS PASSED
      ---> Delete test Namespace created by Namespace Admin
      namespace \"test-namespace-lnd79\" deleted
      ---> Delete test RoleBinding(s)
      Error from server (NotFound): error when deleting \"/etc/cluster-users/kyma-test-bindings.yaml\": rolebindings.rbac.authorization.k8s.io \"cluster-users-test-admin-binding\" not found
      Error from server (NotFound): error when deleting \"/etc/cluster-users/kyma-test-bindings.yaml\": rolebindings.rbac.authorization.k8s.io \"cluster-users-test-ro-user-binding\" not found
      ---> Retrying in 3 seconds...
      ---> Delete test RoleBinding(s)
      Error from server (NotFound): error when deleting \"/etc/cluster-users/kyma-test-bindings.yaml\": rolebindings.rbac.authorization.k8s.io \"cluster-users-test-admin-binding\" not found
      Error from server (NotFound): error when deleting \"/etc/cluster-users/kyma-test-bindings.yaml\": rolebindings.rbac.authorization.k8s.io \"cluster-users-test-ro-user-binding\" not found
      ---> Retrying in 3 seconds...
      ---> Delete test RoleBinding(s)
      Error from server (NotFound): error when deleting \"/etc/cluster-users/kyma-test-bindings.yaml\": rolebindings.rbac.authorization.k8s.io \"cluster-users-test-admin-binding\" not found
      Error from server (NotFound): error when deleting \"/etc/cluster-users/kyma-test-bindings.yaml\": rolebindings.rbac.authorization.k8s.io \"cluster-users-test-ro-user-binding\" not found
      ---> Retrying in 3 seconds...
      ---> Delete test RoleBinding(s)
      Error from server (NotFound): error when deleting \"/etc/cluster-users/kyma-test-bindings.yaml\": rolebindings.rbac.authorization.k8s.io \"cluster-users-test-admin-binding\" not found
      Error from server (NotFound): error when deleting \"/etc/cluster-users/kyma-test-bindings.yaml\": rolebindings.rbac.authorization.k8s.io \"cluster-users-test-ro-user-binding\" not found
      ---> Retrying in 3 seconds...
      ---> Delete test RoleBinding(s)
      Error from server (NotFound): error when deleting \"/etc/cluster-users/kyma-test-bindings.yaml\": rolebindings.rbac.authorization.k8s.io \"cluster-users-test-admin-binding\" not found
      Error from server (NotFound): error when deleting \"/etc/cluster-users/kyma-test-bindings.yaml\": rolebindings.rbac.authorization.k8s.io \"cluster-users-test-ro-user-binding\" not found
      ---> Fatal! Retires failed for: Delete test RoleBinding(s)

**Steps to reproduce**

**Troubleshooting**

**Comment by Tomasz-Smelcerz-SAP** [comment]
From the attached logs it rather looks as if it couldn't delete RoleBinding(s).
Probably the same as: https://github.com/kyma-project/kyma/issues/11022

**Comment by pbochynski** [comment]
Cluster-users tests are already removed - this ticket can be closed.
