### ISSUE TITLE
K3s integration tests are failing because istioctl cannot be found

### ISSUE THREAD

**Issue by tobiscr** [kyma-project/kyma#10989]
**Description**

The Prow jobs `kyma-integration-k3s-compass-dev` and `kyma-integration-k3s`  is failing with the error message `istio-1.8.2/bin/istioctl: not found`.

**Expected result**

Compass integration test passes successfully.

**Actual result**

       1) Kyma with Compass test
            Install Kyma:
          Error: Command failed with exit code 127: istio-1.8.2/bin/istioctl install -y --set profile=demo -f /home/sa_117798148653314453801/kyma/tests/fast-integration/installer/config-istio.yaml
     /bin/sh: 1: istio-1.8.2/bin/istioctl: not found
           at makeError (node_modules/execa/lib/error.js:59:11)
           at handlePromise (node_modules/execa/index.js:114:26)
           at processTicksAndRejections (internal/process/task_queues.js:93:5)
           at async installIstio (installer/istioctl.js:37:22)
           at async Object.installKyma (installer/index.js:399:7)
           at async Context.<anonymous> (compass-test/compass-test.js:38:5)

       2) Kyma with Compass test
            Register Kyma instance in Compass:
          Error: k8sApply error, cannot create: {"apiVersion":"v1","kind":"Secret","metadata":{"name":"compass-agent-configuration","namespace":"compass-system"},"data":{"CONNECTOR_URL":"aHR0cHM6Ly9jb21wYXNzLWdhdGV3YXkubXBzLmRldi5reW1hLmNsb3VkLnNhcC9jb25uZWN0b3IvZ3JhcGhxbA==","RUNTIME_ID":"ZTcyN2RkNzMtNTFkZS00MTI1LTgyMGQtYzU3NDYyYjkzMTdj","TENANT":"ZTQ0OWY4NzUtYjViMi00NDg1LWI3YzAtOTg3MjVjMDU3MWJm","TOKEN":"Szh0Tlg3YkNCaUNIcVlkYk9WS0hCSkFCQUxPcEtpSVhRTmlxOGRpN3FnNTdJcUxHbXdmb1Y5MklaTEkzamdnSDRpVXBMRDY5dmVuSndSM0VPdG4tMlE9PQ=="}}
           at /home/sa_117798148653314453801/kyma/tests/fast-integration/utils/index.js:269:19
           at processTicksAndRejections (internal/process/task_queues.js:93:5)
           at async /home/sa_117798148653314453801/kyma/tests/fast-integration/utils/index.js:268:18
           at async Promise.all (index 0)
           at async registerKymaInCompass (compass/fixtures.js:35:5)
           at async Context.<anonymous> (compass-test/compass-test.js:42:5)

**Steps to reproduce**

See
* https://status.build.kyma-project.io/view/gcs/kyma-prow-logs/logs/kyma-integration-k3s-compass-dev/1375101499817857024
* https://status.build.kyma-project.io/view/gcs/kyma-prow-logs/logs/kyma-integration-k3s/1375116598125268992

**Troubleshooting**

**Comment by adamwalach** [comment]
Netlify was down: https://www.netlifystatus.com/incidents/r2nqshvznvyj
Apparently istio is using that:
<img width="620" alt="Screenshot 2021-03-25 at 21 21 50" src="https://user-images.githubusercontent.com/8530211/112538398-1de15800-8db0-11eb-933f-e5d32532a20b.png">

So I guess we need to improve our installation script so it stops when istio download fails.

**Comment by tobiscr** [comment]
Thanks @adamwalach  for the investigation. Closing this ticket.
