### ISSUE TITLE
Kyma integration job for azure (production and evaluation) are failing with error 'shoot.. already exists' in Terraform

### ISSUE THREAD

**Issue by tobiscr** [kyma-project/kyma#10985]
**Description**

The Prow jobs `kyma-integration-production-gardener-azure` and `kyma-integration-evaluation-gardener-azure` are both failing when waiting for the availability of the shoot cluster.

**Expected result**

Integration test can successfully create and access a Gardener shoot instance.

**Actual result**

Example failure of one of the mentioned jobs:

     2021/03/25 00:06:55 UTC [INFO] Provision cluster: "grd92mgze"
     + [[ evaluation == \e\v\a\l\u\a\t\i\o\n ]]
     + kyma provision gardener az --secret kyma-azure --name grd92mgze --project kyma-prow --credentials /etc/credentials/gardener-kyma-prow/kubeconfig --region northeurope -z 1 -t Standard_D4_v3 --scaler-max 1 --scaler-min 1 --disk-type StandardSSD_LRS --kube-version=1.19 --verbose
     X Provisioning Gardener cluster on Azure
     Error: All attempts fail:
     #1: unable to provision gardener cluster: 
     Error: Waiting for shoot condition to finish: APIServerAvailable

       on ../../../../../../../root/.kyma/clusters/gardener/kyma-prow/grd92mgze/terraform.tf line 52, in resource "gardener_shoot" "gardener_cluster":
       52: resource "gardener_shoot" "gardener_cluster" {

     #2: unable to provision gardener cluster: 
     Error: shoots.core.gardener.cloud "grd92mgze" already exists

       on ../../../../../../../root/.kyma/clusters/gardener/kyma-prow/grd92mgze/terraform.tf line 52, in resource "gardener_shoot" "gardener_cluster":
       52: resource "gardener_shoot" "gardener_cluster" {

     Error: Waiting for shoot condition to finish: APIServerAvailable

     #3: unable to provision gardener cluster: 
     Error: shoots.core.gardener.cloud "grd92mgze" already exists

       on ../../../../../../../root/.kyma/clusters/gardener/kyma-prow/grd92mgze/terraform.tf line 52, in resource "gardener_shoot" "gardener_cluster":
       52: resource "gardener_shoot" "gardener_cluster" {

     Error: Waiting for shoot condition to finish: APIServerAvailable

     + gardener::cleanup
     + EXIT_STATUS=1
     + '[' true = true ']'
     + log::error 'AN ERROR OCCURED! Take a look at preceding log entries.'

**Steps to reproduce**

See
* https://storage.googleapis.com/kyma-prow-logs/logs/kyma-integration-evaluation-gardener-azure/1374875004633616385/build-log.txt
* https://storage.googleapis.com/kyma-prow-logs/logs/kyma-integration-production-gardener-azure/1374875004633616384/build-log.txt
* https://storage.googleapis.com/kyma-prow-logs/logs/kyma-integration-gardener-azure/1374934145649610752/build-log.txt
* https://storage.googleapis.com/kyma-prow-logs/logs/kyma-upgrade-gardener-azure/1374888845186699264/build-log.txt

**Troubleshooting**

**Comment by tobiscr** [comment]
Was obviously a temporary issue - latest test runs are green in a row. Closing this issue.

**Comment by tobiscr** [comment]
https://status.build.kyma-project.io/job-history/kyma-prow-logs/logs/kyma-integration-production-gardener-azure

**Comment by adamwalach** [comment]
More info: https://github.com/kyma-project/kyma/issues/10819
