### ISSUE TITLE
Confusing subscription spec values after subscribing function to an event from console UI

### ISSUE THREAD

**Issue by kwiatekus** [kyma-project/kyma#10982]
**Description**

I noticed some confusing inconsistencies when creating subscriptions from  console UI.

**Expected result**

 - protocol and dialect point to beb
 
**Actual result**

 - protocol and dialect should refer to nats

**Steps to reproduce**

1. Create a function in console UI
2. Create subscription to one of the events available in your namespace
3. go to terminal and fetch the subscription via kubectl
3a. alternatively use Kyma CLI to sync the function into your local workspace
4. You will see that source matching filter is empty and that `protocol` and `dialect` fields are mentioning `BEB`

**Troubleshooting**

**Comment by kwiatekus** [comment]
I think protocol and dialect fields should be left empty to default to NATS, should'n them? 
Also.. what is the recommendation for UI towards the source matching filter? I guess UI should set it - this way the definition of subscription is more specific about the event source. 
@k15r please advise

**Comment by k15r** [comment]
Please leave the protocol and dialect empty on a NATS enabled instance. 
The source needs to be set at the moment. Please set it in the UI as @kwiatekus guessed.
We will cleanup the Subscription-CRD in the future and try to provide a consistent and concise design updated version of it.

**Comment by k15r** [comment]
The subscription crd has been cleaned up during #10801
