### ISSUE TITLE
Events with type with more that 2 segments fail to get published

### ISSUE THREAD

**Issue by sayanh** [kyma-project/kyma#10997]
**Description**

The subscribers don't get triggered if there are more than 2 segments after application name and version. E.g. `sap.kyma.custom.framefrog-c4c.Account.Root.Created.v1`. What happens here is, `framefrog-c4c.Account` is treated as an application and is cleaned up. 
The differences created while publishing/subscribing are as follows:
```
[PUB sap.kyma.custom.framefrogc4c.Account.Root.Created.v1 342]
[SUB sap.kyma.custom.framefrogc4cAccount.Root.Created.v1  86]
```

**Expected result**

```
[PUB sap.kyma.custom.framefrogc4c.Account.Root.Created.v1 342]
[SUB sap.kyma.custom.framefrogc4c.Account.Root.Created.v1  86]
```

**Steps to reproduce**

Sample subscription:
```
apiVersion: eventing.kyma-project.io/v1alpha1
kind: Subscription
metadata:
  name: test-c4c-2-excitable-usual
  namespace: framefrog-c4c
  ownerReferences:
  - apiVersion: serverless.kyma-project.io/v1alpha1
    kind: Function
    name: test-c4c-2
    uid: b8a95949-836c-4eb4-a938-5e9ce0beb96c
  resourceVersion: "2858069"
  selfLink: /apis/eventing.kyma-project.io/v1alpha1/namespaces/framefrog-c4c/subscriptions/test-c4c-2-excitable-usual
  uid: aa8b28a2-4d9a-4367-b73c-ff97121dc587
spec:
  filter:
    filters:
    - eventSource:
        property: source
        type: exact
        value: ""
      eventType:
        property: type
        type: exact
        value: sap.kyma.custom.framefrog-c4c.Account.Root.Created.v1
    - eventSource:
        property: source
        type: exact
        value: ""
      eventType:
        property: type
        type: exact
        value: sap.kyma.custom.framefrog-c4c.Account.Root.Updated.v1
  protocol: ""
  protocolsettings:
    exemptHandshake: true
    qos: AT-LEAST-ONCE
  sink: http://test-c4c-2.framefrog-c4c.svc.cluster.local
```

**Troubleshooting**

Kyma version 1.21-rc1

**Comment by marcobebway** [comment]
(As agreed with @k15r)

We will create the NATS Subscriptions as follows:

- If the event consists of exactly two segments, for example `prefix.application.Segment1.Segment2.v1`, the NATS subscription should be the same `prefix.application.Segment1.Segment2.v1`.
- If the event consists of more than two segments, for example `prefix.application.Segment1.Segment2.Segment3.Segment4.v1`, the NATS subscription should be `prefix.application.Segment1Segment2Segment3.Segment4.v1`.
