### ISSUE TITLE
Fast integration test `skr-trial-integration-dev` is receiving wrong event data

### ISSUE THREAD

**Issue by tobiscr** [kyma-project/kyma#10990]
**Description**

The fast integration test `skr-trial-integration-dev` is sometimes failing caused by a wrong assumption of expected event data. Could be a flaky test case.

**Expected result**

Test case should receive consistently receive expected test data.

**Actual result**

       SKR test
         ✓ Provision SKR with ID 2fc53aec-256a-451b-9cb8-dfa11da321dd (1951772ms)
         ✓ Assign SKR to scenario
         ✓ CommerceMock test fixture should be ready (134821ms)
         ✓ function should reach Commerce mock API through app gateway (13410ms)
         1) order.created.v1 event should trigger the lastorder function
         ✓ Deprovision SKR (4893298ms)
         ✓ Unregister SKR resources from Compass

       6 passing (2h)
       1 failing

       1) SKR test
            order.created.v1 event should trigger the lastorder function:
     
           AssertionError: expected { Object (order, event) } to have nested property 'event.data.orderCode' of '567', but got '789'      
           actual expected
      
           789567
      
           at /home/prow/go/src/github.com/kyma-project/kyma/tests/fast-integration/test/fixtures/commerce-mock/index.js:195:43
           at runMicrotasks (<anonymous>)
           at processTicksAndRejections (internal/process/task_queues.js:93:5)
           at async sendEventAndCheckResponse (test/fixtures/commerce-mock/index.js:166:3)
           at async Context.<anonymous> (skr-test/skr-test.js:69:5)

**Steps to reproduce**

See https://storage.googleapis.com/kyma-prow-logs/logs/skr-trial-integration-dev/1374950503561039872/build-log.txt

**Troubleshooting**

**Comment by rakesh-garimella** [comment]
If still valid please re open the issue.
