### ISSUE TITLE
Redis and Testing-addon creation doesn't work 

### ISSUE THREAD

**Issue by parostatkiem** [kyma-project/kyma#11009]
**Description**
We encountered a problem when we tried to create a Redis or a "Testing addon" service instance using Kubernetes REST API. The request payload and response are posted below. We also found out that it works well when those serviceClasses are added by a **cluster addon** (in that case we of course provide `clusterServiceClassRef`, `clusterServiceClassExternalName` and other cluster-scoped variables in the payload) but it doesn't when added as a **namespaces addon**.

Request payload:
```json
{
  "apiVersion":"servicecatalog.k8s.io/v1beta1",
  "kind":"ServiceInstance",
  "metadata":{
    "annotations":{
      
    },
    "name":"redis-wonderful-put",
    "namespace":"orders-service"
  },
  "spec":{
    "serviceClassExternalName":"redis",
    "serviceClassRef":{
      "name":"a2257daa-0e26-4c61-a68d-8a7453c1b767"
    },
    "servicePlanExternalName":"enterprise",
    "servicePlanRef":{
      "name":"a6078798-70a1-4674-af90-aba364dd6a56"
    },
    "parameters":{
      "imagePullPolicy":"IfNotPresent"
    }
  }
}
```

Request response:
```json
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {
    
  },
  "status": "Failure",
  "message": "admission webhook \"validating.serviceinstances.servicecatalog.k8s.io\" denied the request: [spec.serviceClassRef: Forbidden: serviceClassRef must not be present on create, spec.servicePlanRef: Forbidden: servicePlanRef must not be present on create]",
  "reason": "[spec.serviceClassRef: Forbidden: serviceClassRef must not be present on create, spec.servicePlanRef: Forbidden: servicePlanRef must not be present on create]",
  "code": 403
}
```

**Expected result**
The serviceInstance creation works regardless of the type of addon which was used to create the serviceClass.

**Actual result**
The serviceInstance creation works only if the serviceClass was added using a cluster-wide addon.

**Steps to reproduce**

**Troubleshooting**
As expected, when we don't provide the variables mentioned in the response, we get an error saying they have to be provided.

**Comment by dariadomagala** [comment]
❗ the same error occurs with every SAP package!
