### ISSUE TITLE
Create a list of tasks and tutorials for Kyma 2.0 docs

### ISSUE THREAD

**Issue by klaudiagrz** [kyma-project/kyma#11012]
**Description**

Since we are moving towards Kyma 2.0, we provide a new structure for the documentation. The new structure will contain `Basic tasks` and `Advanced tutorials` tabs which will guide users on how to get started with Kyma, how to perform some basic operations, and how to move on to more advanced tutorials and configure Kyma to the user's needs. This is the draft of the new docs structure: 

<img width="257" alt="Screen Shot 2021-03-30 at 13 11 51" src="https://user-images.githubusercontent.com/35192450/112979953-871eed80-9159-11eb-9e70-076a4fdfe3ad.png">

To start working on the content of `Basic tasks` and `Tutorials`, TWs need a list of tasks/tutorials that should be included in these sections. Some ideas are already listed in [this](https://github.com/kyma-project/kyma/issues/10876) issue:

```
A new section with tasks:

- deploy workload using container image (add service automatically)
- expose a service through api-gateway (API rule)
- create function and expose it
- create function triggered by event
- send event (trigger) from your code
```

**Area**

Kyma OS documentation

**Reasons**

TWs need a starting point for writing the content for Kyma 2.0 documentation.

**Assignees**

@kyma-project/technical-writers

**Related issues**

https://github.com/kyma-project/kyma/issues/10857

**Comment by NHingerl** [comment]
Just as a very short protocol of today's Kyma 2.0 docu call:

Basically, the **Getting Started** section is going to be one short tutorial/example procedure (@pbochynski is almost finished drafting the code), and all the other existing instructions/tutorials go into the **Deep Dive/Tutorials** section, with subtabs based on the main areas, which are introduced in the Overview tab.
