### ISSUE TITLE
Pipeline kyma-integration-k3s fails with: `Warning! D-Bus connection terminated.`

### ISSUE THREAD

**Issue by Tomasz-Smelcerz-SAP** [kyma-project/kyma#11030]
**Description**
The pipeline sometime fails with the error: 
```
scp: /home/sa_117798148653314453801/kyma/tests/fast-integration/junit_kyma-fast-integration.xml: No such file or directory
ERROR: (gcloud.compute.scp) [/usr/bin/scp] exited with return code [1].
```

**Expected result**

The pipeline works

**Actual result**

Pipeline works

**Example links**
https://status.build.kyma-project.io/view/gcs/kyma-prow-logs/logs/kyma-integration-k3s/1377185248848121856
https://status.build.kyma-project.io/view/gcs/kyma-prow-logs/logs/kyma-integration-k3s/1377230551089418240

**Steps to reproduce**

**Troubleshooting**

**Comment by adamwalach** [comment]
This is not a root cause, please check in the earlier lines:
```
Warning! D-Bus connection terminated.
Failed to wait for response: Connection reset by peer
```
This is the real issue.
The line that you mentioned is just a consequence of a failing job. It fails in such an early stage that the junit file was not yet generated.

**Comment by adamwalach** [comment]
Looks like this issue is solved. I am not sure what is the root cause but according to logs it is casued with systemd - it fails when k3s unit file is used.
We updated base image of our VMs - https://github.com/kyma-project/test-infra/pull/3423
I can't see any errors in last 24h.

**Comment by adamwalach** [comment]
It happens again:
<img width="1345" alt="Screenshot 2021-07-20 at 21 39 46" src="https://user-images.githubusercontent.com/8530211/126454867-78f45fd0-28fb-4792-a244-6289fe51ca4b.png">

**Comment by adamwalach** [comment]
We checked all dependencies and there is nothing that changed on our side (test-infra, kyma repos, gcp settings).
To help with debugging, we introduced a change to our base image - https://github.com/kyma-project/test-infra/pull/3947. Somehow this fixed a problem :/
So, if this problem occurs again, we should first rebuild the vm image and see if it helps.
