### ISSUE TITLE
Documentation for Application Connector 2.0

### ISSUE THREAD

**Issue by janmedrek** [kyma-project/kyma#11047]
**Description**

With the big change coming to the area of Application Connector we will need proper, up-to-date documentation on the whole flow available to the user. Technical matters such as overall architecture or troubleshooting should also be included in separate sections.

**Reasons**

We want users to have an easy way to get a deeper understanding of how our systems work and how to use them efficiently.

**Acceptance Criteria**
- Overall architecture of the solution documented
- Troubleshooting section prepared
- Tutorial/guide on the flow, including setup, configuration, and later use of functionalities such as Application Registry(?) or Application Gateway
  - Certificate creation
  - Registration
  - Sending an event
  - Reaching external API via Application Gateway
  - Examples of lambdas, events, and calls should be included

**To Do**
- [ ] New docu created, some parts imported
  - [ ] Overall description (what it is)
  - [ ] Architecture docs
  - [ ] Config
  - [ ] Application CRD description
  - [ ] Guide on how to use the new Application Gateway

**Comment by majakurcius** [comment]
See also [this comment](https://github.com/kyma-project/kyma/issues/11620#issuecomment-874595455).

**Comment by janmedrek** [comment]
The first part would need to focus on using the Central Application Gateway:
- [ ] Short description on how the new Gateway works
- [ ] Old tutorials adapted to the new flow

This aims to familiarize the users with the new flow that we are introducing.

**Comment by majakurcius** [comment]
Note to self: See the comments [here](https://github.com/kyma-project/kyma/pull/11678).
