### ISSUE TITLE
skr integration pipelines failing

### ISSUE THREAD

**Issue by dekiel** [kyma-project/kyma#11048]
**Description**

Since 01.04.2021 pipelines skr-aws-integration-dev and skr-azure-integration-dev, constantly failing on all tests.

**Expected result**

Pipeline should finish with success.

**Actual result**

Pipelines are failing on all tests.

```
SKR test
    1) Provision SKR with ID 74627922-1760-4db5-8e67-24f9311624e0
    2) Assign SKR to scenario
    3) CommerceMock test fixture should be ready
    4) function should reach Commerce mock API through app gateway
    5) order.created.v1 event should trigger the lastorder function
    ✓ Deprovision SKR (1831444ms)
    ✓ Unregister SKR resources from Compass
```

**Steps to reproduce**

See job executions logs. https://status.build.kyma-project.io/job-history/kyma-prow-logs/logs/skr-azure-integration-dev?buildId=1379419991798976512

skr-azure-integration-dev last succes run was at 2021-04-01 06:05:40 +0000 UTC on kyma HEAD at b9eacea9d and test-infra HEAD at 7eeeb524. First failure was at 2021-04-01 09:05:44 +0000 UTC on kyma at HEAD at b9eacea9d and test-infra HEAD at 54e604e3.

Jobs are subject for removing from Prow till permanent fix will be in place.

**Comment by dekiel** [comment]
@k15r could you please take a look if your commit https://github.com/kyma-project/test-infra/commit/54e604e3577286df9211464fc6883553c6809541 could cause this failures. There were two others but this one looks as best candidate.

**Comment by k15r** [comment]
if i read this job configuration correctly, then this job is about executing the fast integration test in a gardener specific way. 
My changes targeted the older not fast-integration based tests. Maybe some with a bit more experience in the fast-integration test area could help here

**Comment by dekiel** [comment]
Latest three runs of skr-azure-lite-integration-dev failed with same results. Three pipelines affect as of now.

**Comment by dekiel** [comment]
Failures are caused by issues on CLS server.
https://jtrack.wdf.sap.corp/browse/NGPBUG-145726
Example error message for provisioning SKR `"level\":\"error\",\"msg\":\"Process operation failed: Unable to create CLS Binding\",`

**Comment by dekiel** [comment]
Because of gardener related dns issues https://github.com/kyma-project/kyma/issues/11079, it's not possible to check if CLS server side fix solved the issues.
