### ISSUE TITLE
Application Connectivity 2.0

### ISSUE THREAD

**Issue by janmedrek** [kyma-project/kyma#11044]
**Description**

New, simplified handling for external Systems is needed in Kyma, right now connecting and using any application from outside of Kyma is gruesome and requires multiple unnecessary steps.

**Reasons**

With the increasing complexity of the system, it's easy to get lost, and thus, we need a simplified way of connecting and using external applications with Kyma. Multiple steps should be dropped, this results in fewer requirements when it comes to the Application Connector's components as well. Many of those (such as Application Operator) are not needed anymore in the new approach.

The main assumptions are:
- Easier configuration of new applications in Kyma
- No Service Catalog dependency
- Declarative approach to the connectivity topics

**Concept**

##### Application Gateway
✅  #10361 

Application Gateway should be "centralized" - this way we will achieve a single, scalable deployment in the cluster. Users will no longer need to wait for it to be spun up by the Application Operator. Proxying will be handled via the reference to the Application and one of its Services. It should no longer require Service Catalog in order to go through the proxying scenario.

##### Connectivity Validator
✅  #11045 

Connectivity Validator should receive the same treatment as the Application Gateway will. This will drop the requirement to have an Application Operator in the cluster, as a single deployment (scalable) will handle the requests for all Applications.

##### Application Registry
✅ 

The treatment for this component should be the major refactor of underlying interfaces. Right now it's a bunch of implementations that are no longer used/needed, it resembles more of a "Kyma History Archive" rather than a functional component. And that's why we need to focus on simplifying and improving its performance.

##### Connector Service

If we decide to completely drop the Certificate support when it comes to auth in Application Connectivity and Eventing this component can be deleted.

##### Application Operator

This component will be no longer needed. New eventing will no longer use Event Service, Application Connector will have a single deployment for Application Gateway and Connectivity Validator. In the end - all responsibilities of this component will disappear.

##### Application Broker

This component will be no longer needed, ServiceBindings and ServiceBindingUsages will be dropped in this scenario and thus, this component can be dropped as well.

**Documentation**
#11047

We need a new documentation section that will reflect the state of this area. This should be aimed at the ease of use, provide value and guide the user through the whole journey - from the configuration step all up to the invocation of external API through the Application Gateway.

**Comment by janmedrek** [comment]
**Implementation Steps**

##### Phase 1

This one is mainly focused on getting Application Gateway to work in a more of a "singleton" manner. Other components remain unchanged, there is also no conflict between the "old" and the "new" flows. Due to being separated from Service Catalog - the application Broker can also be dropped.

![app1](https://user-images.githubusercontent.com/22869996/113695179-df616c80-96d0-11eb-8cc4-94c66c79123b.png)

##### Phase 2

The second step concentrates on making Connectivity Validator work for all the Applications registered in the Kyma system. This also removes the necessity of having an Application Operator in the cluster.

![app2](https://user-images.githubusercontent.com/22869996/113695316-01f38580-96d1-11eb-897a-c01707d0f5af.png)

##### Phase 3

The last step of the migration to the new Connectivity - dropping certificates support, with this implemented we can get rid of unneeded Connector Service and Connectivity Validator. New auth methods will be supported when it comes to reaching Application Registry and Eventing.

![app3](https://user-images.githubusercontent.com/22869996/113695579-4c750200-96d1-11eb-8ce5-248b0e3cab43.png)

**Comment by pbochynski** [comment]
Please ensure that we have a link to the API spec somewhere in the application custom resource.

**Comment by pxsalehi** [comment]
Sorry for the accidental change! Hope it is ok now!
