### ISSUE TITLE
UI Bug in Firefox

### ISSUE THREAD

**Issue by lasseUrban** [kyma-project/kyma#11049]
[suggested label: area/console]

**Description**

It is not possible to add a new deployment via the "+Deploy new workload" button in the namespace overview using the Firefox browser. I can click on "Upload YAML" and the window "Deploy new resource" opens, but when I drop a yaml file and click "Deploy" it is not deployed. The window just disappears and the toolbar menu on the left is grayed out until I refresh the page. When I browse for a yaml file, select it and click "open/apply", the window immediately disappears and I cannot say "deploy".

I reproduced the issue with two different machines and accounts and used the latest Firefox 87.0 on both. With Microsoft Edge and Google Chrome browsers everything works fine. 

**Expected result**

**Actual result**

**Steps to reproduce**

- use Firefox 87.0 on Windows 10
- create a new namespace
- Overview -> "Deploy new workload" -> "Upload YAML"
- I dropped yaml files from [https://github.com/SAP-samples/xf-application-mocks/tree/master/commerce-mock/deployment](url)

**Troubleshooting**

issue does not appear in Chrome and Edge browser

**Comment by Sawthis** [comment]
@lasseUrban we won't fix this issue for Firefox. As workaround please use other web browser. We are working on new Kyma Dashboard project which will be released soon.
