### ISSUE TITLE
Monitoring for eventing must work without connected external application

### ISSUE THREAD

**Issue by k15r** [kyma-project/kyma#11052]
**Description**

Create a test that covers the following scenario:

Setup:
- kyma cluster with no external applicaton connected!
- 2 lambdas
- 1 creates an event and sends it to the publisher proxy
- 1 is configured to receive the event

Expected Result:
- events flow correctly
- dashboards work and show metrics related to the sent events correctly

**Reasons**

In cluster eventing is advertised with kyma >1.20. Dashboards must work in this scenario.

**Attachments**

**Comment by marcobebway** [comment]
Duplicate of https://github.tools.sap/kyma/backlog/issues/1682.
