### ISSUE TITLE
integration tests with compass-dev are failing

### ISSUE THREAD

**Issue by dekiel** [kyma-project/kyma#11068]
Because of problems on compass-dev instance, our tests which depend on it are failing. After initial fix on compass-dev we got another errors. Investigation on our side pointed out that compass API doesn't return application auths correctly.

> OK, after the investigation I managed to track down the problem. It looks like the compass API does not return the Application auths correctly. I notified the CMP team and here is the thread

**Comment by dekiel** [comment]
Issue on compass-dev is tracker here https://sap-btp.slack.com/archives/C01CKAN1SKV/p1617880329051900

**Comment by crabtree** [comment]
PR on kyma side: https://github.com/kyma-project/kyma/pull/11070

**Comment by dekiel** [comment]
Fixed. Many thanks @crabtree for troubleshoot and fix!!!!
