### ISSUE TITLE
After editing a functions couple of times, we end up with unused old replica sets

### ISSUE THREAD

**Issue by valentinvieriu** [kyma-project/kyma#11061]
**Description**

Old replica sets are not deleted after editing a function in Kyma Ui

**Expected result**

We should have only 1 Replica Set

**Actual result**

Old replica sets are not deleted.

**Steps to reproduce**

Create a Function. And edit that function 2-5 times. After each save a new replica set is crated, but the old one are still there

**Comment by kazydek** [comment]
As discussed, this works as expected. Pls, see the link to the official [k8s docs](https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#revision-history-limit).
