### ISSUE TITLE
Spike: Dynamic configuration of logging backend

### ISSUE THREAD

**Issue by a-thaler** [kyma-project/kyma#11105]
**Description**
The fluent-bit deployment in kyma gets reconciled as part of the upgrade process. That reconcilation will override any configuration done directly in the cluster.

Goal: Come up and evaluate a way to have a dynamic in-cluster configuration which will be not resetted by the upgrade process and gets applied automatically (no manual pod restarts required).

Criterias:
- Customers can place fluent-bit config snippets as k8s resource in a specific or in any namespace
- Full fluent-bit syntax is supported? Make a proposal
- debugging a startup problem - how to figure out which config snippet caused a problem at startup
- Have in mind that the central configuration will be overwritten at any time by reconcilation which should not reset customers config
- A rollback to the old config might be cool in case of invalid config provided by customer
- a new config gets picked up dynamically without any further interaction (like pod restart)
- Have basic validation to give early feedback on errors
- OpenTelemetry collector has the same problem to solve, so keep it in mind
- There is a way to provide the auth details for a backend config in a secure way

Result:
- spike code which can illustrate the proposed solution in a demo
  - proposes a controller framework
  - proposes a technical solution on how to restart fluent-bit
- concept document on how to solve the problem with reasoning behind
  - proposes a concrete customer-facing API
  - what kind of fluent-bit features will be supported (inputs as well?)

**Reasons**
Support in-cluster configuration for logging not being dependent on the kyma lifecycle management

**Attachments**

**Comment by a-thaler** [comment]
3 more points to address before starting realisation:
- support fur additional files like a lua script to be used in the lua filter
- Loki pipeline should be expressable via the new resources so that it can be pluggable
- the actual config element is inconvenient to configure having the key/value approach. It will be much more convenient if you can just paste a typical config snippet into the resource definition. The secret handling could be solved via placeholder like in the actual fluent-bit config

**Comment by usherfu** [comment]
> Results can be found here: https://github.com/kyma-project/community/blob/main/internal/proposals/logs/dynamic-backend-configuration/custom-operator/dynamic-fluentbit-config.md

Above link is no longer valid, could it be this one?
https://github.com/kyma-project/community/blob/main/concepts/observability-configurable-logging/05-custom-fluentbit-operator.md
