### ISSUE TITLE
Remove Azure EventHub steps after releasing 1.21

### ISSUE THREAD

**Issue by radufa** [kyma-project/kyma#11118]
**Description**

The provisioning, deprovisioning and upgrade steps related to Azure EventHub should be removed from KEB pipelines. It was used only by Eventing till 1.20.

**Reasons**

Starting with the release 1.21, Eventing is not based on Knative anymore. Azure EventHub was used by a Knative Kafka channel implementention which is obsolete now.

**Attachments**

**Comment by pxsalehi** [comment]
This issue is resolved and merged already!
