### ISSUE TITLE
Can't create application from the GUI, stuck on 'NOT SERVING'

### ISSUE THREAD

**Issue by philippe-lavoie** [kyma-project/kyma#11127]
**Description**

I'm following the Getting started guide and when I try to create an application through the GUI, it gets stuck on 'NOT SERVING'. If I fuse kubectl, it works.

**Expected result**

It should work with both kubectl and the UI console.

**Actual result**

See description

**Steps to reproduce**

Install 1.21.0 on AKS. Follow the getting started instructions for adding an application.

**Troubleshooting**

Work around is to use kubectl

**Comment by valentinvieriu** [comment]
@philippe-lavoie I think we need more context on this issue. Can you contact us on Slack?

**Comment by philippe-lavoie** [comment]
I reached out with a personal chat

**Comment by janmedrek** [comment]
@valentinvieriu @philippe-lavoie were you able to sort the problem out? Do you have any findings on why it works in kubectl and not in console?

**Comment by Sawthis** [comment]
@philippe-lavoie please reopen the issue if it is still valid.
