### ISSUE TITLE
[Test Case] - Test Logging for newly provision cluster and after upgrade

### ISSUE THREAD

**Issue by rakesh-garimella** [kyma-project/kyma#11136]
**Summary**

The purpose of the test is to make sure logging configuration for a newly provisioned cluster and after upgrade. This is valid for kyma version =>1.23

**Test Steps**
1. Upgrade Kyma to the latest version/ Provision a Kyma with latest kyma version 
2. Download the kubeconfig from kyma.
3. Check the retention period is set to 5 days
```
kubectl get secrets -n kyma-system logging-loki -ojsonpath='{.data.loki\.yaml}' | base64 -d
```
Check for following values
```
max_look_back_period: 120h
retention_period: 120h
```
4. Check the persistent volume claim size is set to 30Gi
```
kubectl get pvc -n kyma-system storage-logging-loki-0
```
5. Check logs are present from all the namespaces.
6. Check if the json log parsing works
7. With Kyma 2.0 verify that the loki is not exposed via Virtual Service anymore
```
kubectl get virtualservices.networking.istio.io -A | grep loki
```
should not return anything

**Expected Results**

All the steps pass.

**Comment by a-thaler** [comment]
Test case got automated
