### ISSUE TITLE
Making fast upgrade test executable in prow pipelines

### ISSUE THREAD

**Issue by strekm** [kyma-project/kyma#11162]
**Description**

Adapt fast upgrade integration test so it's possible to call them from within the prow pipeline.

AC:
- fast upgrade integration test has 2 phases: prepare data & execute tests, execute tests & clean-up
- first phase is executed after the installation & before the upgrade
- second phase is executed after the upgrade

out of scope:
- fixing upgrade tests

**Reasons**

Executing fast upgrade test on upgrade pipeline

**Attachments**

https://github.com/kyma-project/test-infra/issues/3410

**Comment by pbochynski** [comment]
@mjakobczyk Please explain to me how the commerce mock test separated into 3 files is related to the original test. Mocha executes by default all tests in `test` folder in alphabetical order. If you want to keep the tests in test folder remove the original test or put it in the other folder. Currently, it is not compliant with the testing convention (cleanup will be executed first).
