### ISSUE TITLE
Getting started document - pod is not auto restarted

### ISSUE THREAD

**Issue by lanphan** [kyma-project/kyma#11184]
**Description**
I followed steps in document here: https://kyma-project.io/docs/root/getting-started#getting-started-expose-the-microservice-call-and-test-the-microservice till step 5

> Remove the Pod created by the orders-service Deployment. Run this command, and wait for the system to delete the Pod and start a new one:

but the result I got is completely different: pod is not auto restarted as document said.

Noted that I use k3d for my local environment (https://github.com/kyma-incubator/local-kyma). And my environment got some problems with helm as depicted in ticket https://github.com/kyma-incubator/local-kyma/issues/77

Noted that I use k3d for my local environment (https://github.com/kyma-incubator/local-kyma), and I got some components not installed due to helm repo not existed here: https://github.com/kyma-incubator/local-kyma/issues/77

I don't know that this is a bug or not, just post here for your reference.

**Area**

**Reasons**

**Assignees**

@kyma-project/technical-writers

**Attachments**

**Comment by a-thaler** [comment]
That a Pod which belongs to a Deployment gets re-scheduled on deletion is a regular Kubernetes feature, so not really related to the tutorial.
Can you please explain a bit more what you can observe when saying "pod is not auto restarted". Do you see the pod terminating and it is disappearing from the pod list and no new pod gets created? Or does the new pod fails to startup?

**Comment by lanphan** [comment]
Hi @a-thaler ,

> Can you please explain a bit more what you can observe when saying "pod is not auto restarted". Do you see the pod terminating and it is disappearing from the pod list and no new pod gets created?
Yes, checking from detail page of "orders-service" namespace, I see that the number of pod is still 0 after deletion.

> Or does the new pod fails to startup?
As I'm new to k8s, I don't know where to check log about this?

Thanks for your explanation, I read some documents and understand a little bit about k8s, that kyma uses Deployment with replicas = 1, so that k8s must be in charged of re-creating pod when the number of replicas is not satisfied. However, on my local environment (using k3d), it doesn't work. Seems this is a bug from k3d?

**Comment by lanphan** [comment]
Hi @a-thaler ,

I submitted this bug to k3d project here:
https://github.com/rancher/k3d/issues/570

Close this one, thanks for your explanation.
