### ISSUE TITLE
Upgrade to latest NATS Server 

### ISSUE THREAD

**Issue by johgoe** [kyma-project/kyma#11187]
NATS 2.2.0 brings some features which could be very helpful:
see https://github.com/nats-io/nats-server/releases/tag/v2.2.0

- JetStream as new persistence for NATS
- MQTT Support
- WebSocket support

**Comment by k15r** [comment]
Thanks @johgoe for bringing this up. 
There are already plans to do POCs with those new features.
As we currently rely on nats-operator to deploy the nats-cluster we are limited by their support for jetstream. At this moment they do not support it.

**Comment by johgoe** [comment]
In https://github.com/nats-io/nack#getting-started there is a solution between an older nats (2.1.7) without jetstream combined with a NATS Server with JetStream enabled as a leafnode connection. 
This could already work in a kyma stack  with some manually work. I hope this could be a intermediate solution for me.

**Comment by johgoe** [comment]
Current available NATS Version v2.3.2

**Comment by sayanh** [comment]
Solved in https://github.com/kyma-project/kyma/pull/12415/files
