### ISSUE TITLE
Migrate existing tests for observabilty stack to fast integration tests

### ISSUE THREAD

**Issue by a-thaler** [kyma-project/kyma#11180]
**Description**
As the fast integration tests will be the future for kyma 2.0 we need to start migrating the existing octopus tests to it.

Criterias:
- Migrate tests if they are still meaningful, so either migrate or delete, there should no leftover
- Focus on functionality, not testing pure configuration
- Re-use existing test setup, adjust only slightly if needed, important is to not increase overall execution time
- Upgrades needs to be tested as well, or there is a clear statement on how to deal with it
- All components are covered: logging, tracing, monitoring, kiali

**Reasons**
Current test solution is fast and cumbersome, let's migrate to the future approach keeping execution tim in focus

**Attachments**

**Comment by JeremyHarisch** [comment]
Tests to migrate:
- [ ] Test if pods are ready
- [ ] Test if targets are healthy
- [ ] Check scraping pools
- [ ] Test if rules are healthy
- [ ] Check if alerts are firing
- [ ] Test if Grafana is ready
- [ ] Check the Lamba UI dashboard

**Comment by shorim** [comment]
Logging integration test is now added to the fast-integration framework https://github.com/kyma-project/kyma/pull/11492
Test Flow:

1. Before the test starts, `port-forward` is used to connect to the `Loki` pod in the cluster. After the test finishes, the forwarding session is terminated.
2. The timestamp at which the test starts is captured.
3. The test tries to fetch logs from the `commerce-mock` pod which was already being created in the `commerce-mock` scenario . We send a query to `Loki` with the labels `{app="commerce-mock", container="commerce-mock", namespace="mocks"}` and a start time equal to the timestamp captured in step 2. The reason for that is to make sure that that the fetched logs are coming from the pod created during the current test instance and not persistent logs from a previous test instance.
