### ISSUE TITLE
Fast integration test fails to create functions

### ISSUE THREAD

**Issue by sayanh** [kyma-project/kyma#11185]
**Description**

Fast integration test fails to create functions.
Samples:
https://storage.googleapis.com/kyma-prow-logs/logs/kyma-upgrade-gardener-kyma-to-kyma2/1386575905073139712/build-log.txt
https://storage.googleapis.com/kyma-prow-logs/logs/kyma-alpha-integration-production-gardener-azure/1386577164089954304/build-log.txt

**Reasons**

Not known ATM

**Comment by kwiatekus** [comment]
This was already fixed. The root cause was that docker registry was not exposed correctly via api-gateway
