### ISSUE TITLE
[Question] Console UI shows "no healthy upstream"

### ISSUE THREAD

**Issue by lanphan** [kyma-project/kyma#11191]
**Description**
I started kyma cluster successfully and did some actions on it, then sleep my PC for some time and turn on it again, come back to Console UI and got "no healthy upstream" message.
I'd like to have some questions below:
1. Is there any expiration time set here? Where can I change that setting to make it live longer?
2. In case I'd like to make it works, my stupid way is to use script `./kyma-k3d-delete.sh`, but that script will delete all my cluster and take a long time for me to wait to start a new one using `./kyma-k3d.sh` (around 15 minutes), would you please show me other way to bring kyma back?

Thanks so much for this great framework.

**Expected result**

**Actual result**

**Steps to reproduce**

**Comment by pbochynski** [comment]
This incubator project was established to prove that we can install Kyma components in parallel and use k3s for faster/lighter setup. The repository is no longer maintained and is going to be archived. We are now supporting installation on k3s with kyma cli. 
So my advice is to switch to https://github.com/kyma-project/cli
and use commands:
```
kyma alpha provision k3s
kyma alpha deploy
```
