### ISSUE TITLE
Kyma Upgrade failing with Helm upgrade of release "logging" failed: cannot patch "logging-loki" with kind StatefulSet: StatefulSet.apps "logging-loki" is invalid: spec: Forbidden

### ISSUE THREAD

**Issue by acidassassin** [kyma-project/kyma#11220]
Hello together,

I'm currently trying to update the domain of my Kyma cluster deployed on AKS. I Installed it with the default *.xip.io domain, but since this service is down for some reason, I wanted to switch domains. Now as i tried to upgrade my current kyma installation with "kyma upgrade" i am experiencing the follow errors:

`Installation error occurred while installing Kyma: installation error occurred: install component logging. Details: Installation errors: 
Component: logging, Log: Helm upgrade of release "logging" failed: cannot patch "logging-loki" with kind StatefulSet: StatefulSet.apps "logging-loki" is invalid: spec: Forbidden: updates to statefulset spec for fields other than 'replicas', 'template', and 'updateStrategy' are forbidden.
Finding last known deployed revision to rollback to.
Performing rollback to last known deployed revision: 1
Helm rollback of release "logging" was successfull
`
and
`2021/05/05 11:18:57 Error during install/update:  Details: max number of retries reached during step: install component logging
E0505 11:18:57.189352       1 controller.go:226] max number of retries reached during step: install component logging
`
The installer then just runs forever...

I would expect the command to be successful and update the domain as provided.

I am upgrading with the following format: kyma upgrade --domain domain.xyz--tls-cert $TLS_CERT --tls-key $TLS_KEY -s 1.21.0

Can anybody help me?

**Comment by a-thaler** [comment]
HI @acidassassin, so you upgraded kyma from 1.21.0 to 1.21.0, right? Or is the previous version on the cluster older than 1.21.0?
If the version is the same, nothing can change in the statefulset definition... So I assume you have a different version before..
Can you please also report the cli version by calling "kyma version"

As a workaround, you could manually delete the stateful set and run the upgrade again having the impact of loosing the log data. `kubectl -n kyma-system delete statefulset logging-loki`

**Comment by acidassassin** [comment]
Hi @a-thaler,

thank you for your quick response! I attached the version option, because otherwise the cli didnt let me start the upgrade process. My versions are as follow:
Kyma CLI version: 1.20.0
Kyma cluster version: 1.21.0

I tried to use your command and restarted the upgrade process, but now it seems like it is stuck at this point, because it only shows me the following message without doing anything:
`- Cluster info read
- Installation in version '1.21.0' is already in progress
! installation error occurred: install component logging, which may be OK. Will retry later...
  To fetch the error logs from the installer, run: kubectl get installation kyma-installation -o go-template --template='{{- range .status.errorLog }}{{printf "%s:\n %s\n" .component .log}}{{- end}}'
  To fetch the application logs from the installer, run: kubectl logs -n kyma-installer -l name=kyma-installer
/ Re-attaching installation status `

Is there a way to restart the whole process?

Thanks!

**Comment by a-thaler** [comment]
Sorry for the late response, I missed that you answered. To restart the installation just assure that the specific label is attached to the installation resource: `kubectl -n default label installation/kyma-installation action=install`. In case it was already there and the installer is already progress, then you can also restart the installation by just deleting the related pod `kubectl -n kyma-installer delete pod kyma-installer-xxx`.

**Comment by acidassassin** [comment]
@a-thaler Thank you for your help. The upgrade was completed.
