### ISSUE TITLE
Isn't the logrus.Logger intended to be a key/value logger? See https://pkg.go.dev/github.com/sirupsen/logrus#pkg-overview .

### ISSUE THREAD

**Issue by ghost** [kyma-project/kyma#11255]
Isn't the logrus.Logger intended to be a key/value logger? See https://pkg.go.dev/github.com/sirupsen/logrus#pkg-overview .

_Originally posted by @themue in https://github.com/kyma-project/kyma/pull/11211#discussion_r630010064_

**Comment by k15r** [comment]
this issue will be fixed by refactoring our code to use the common logging library
