### ISSUE TITLE
As BEB is an acronym I only would expect it in upper-case, see https://github.com/golang/go/wiki/CodeReviewComments#initialisms . But this could be done in next change for code-style.

### ISSUE THREAD

**Issue by radufa** [kyma-project/kyma#11254]
As BEB is an acronym I only would expect it in upper-case, see https://github.com/golang/go/wiki/CodeReviewComments#initialisms . But this could be done in next change for code-style.

_Originally posted by @themue in https://github.com/kyma-project/kyma/pull/11211#discussion_r629996993_

**Comment by k15r** [comment]
codestyle show be adressed in code reviews
