### ISSUE TITLE
OOM errors in ORY jobs

### ISSUE THREAD

**Issue by adamwalach** [kyma-project/kyma#11284]
**Description**

After we enabled our [new oom finder tools](https://github.com/kyma-project/test-infra/tree/main/development/tools/cmd/oomfinder) we noticed that a lot of errors are comming form ORY related jobs.
Examples (search for OOM keyword):
- https://storage.googleapis.com/kyma-prow-logs/pr-logs/pull/kyma-project_kyma/11280/pre-main-kyma-gardener-azure-alpha-eval/1394187361524387840/build-log.txt
- https://storage.googleapis.com/kyma-prow-logs/logs/kyma-cli-alpha-uninstall-gke/1394140760135176192/build-log.txt 
- https://storage.googleapis.com/kyma-prow-logs/logs/kyma-alpha-integration-production-gardener-azure/1393749431353872384/build-log.txt

Interesting part is here:
```
2021/05/16 02:28:09 UTC [INFO] *************************************************************************************
2021/05/16 02:28:09 UTC [INFO] * OOM event found
2021/05/16 02:28:09 UTC [INFO] *************************************************************************************
2021/05/16 02:28:09 UTC [INFO] Download OOM events details
2021/05/16 02:28:10 UTC [INFO] Print OOM events details
OOM event received time: 16 May 21 02:20 +0000 , namespace: kyma-system , pod: ory-oathkeeper-helper-keys-job-cbsxx ,container: override-generator , image: sha256:b12613fec0c853a73bf27df1bcf051bb6f91e0c1960f0a60ad973f10cc7bdc1c 
2021/05/16 02:28:10 UTC [INFO] Deprovision cluster: "grdg0m9db"
shoot.core.gardener.cloud/grdg0m9db annotated
```

From what I can see the failing pods are:
- ory-oathkeeper-helper-keys-job
- ory-mechanism-migration

We need to increase memory limits on these pods.

**Steps to reproduce**

This is a random issue, hard to reproduce.

**Troubleshooting**

**Comment by adamwalach** [comment]
Fixed by https://github.com/kyma-project/kyma/pull/11356/files

**Comment by mmitoraj** [comment]
Fixed by https://github.com/kyma-project/kyma/pull/11356/files
