### ISSUE TITLE
"kyma console" does not work

### ISSUE THREAD

**Issue by sayanh** [kyma-project/kyma#11312]
**Description**

After Kyma is installed from a release or main branch using `kyma install --source=local --custom-image=some-image`, when I use `kyma console` to access the UI, the domain name does not seem to work. Right now, the free domains are based on xip.io so I think something is broken there.

The browser shows the following:
<img width="1871" alt="Screenshot 2021-05-18 at 11 56 26" src="https://user-images.githubusercontent.com/5954057/118814227-33ef2e80-b8b0-11eb-8aab-c5abe1fcf095.png">

**Expected result**

Kyma console should come up.
**Actual result**

Error

**Steps to reproduce**

- Checkout Kyma main branch 
- On any GKE cluster, install kyma with `kyma install --source=local --custom-image=your-repo/kyma-installer`
- Access Kyma console UI using `kyma console`

**Comment by a-thaler** [comment]
As far as I can see the "kyma console" command works as expected. It figures out the URL of the console and opens it in your browser. Unfortunately it seems that the URL does not resolve to a valid endpoint.
Have you checked if other subdomains are working for your cluster, so if it is console specific at all? Maybe the xip DNS was not working temporary?

**Comment by JeremyHarisch** [comment]
No user feedback - Quite sure it is xip.io related. xip integration got removed with Kyma 2.0
