### ISSUE TITLE
Failing kyma-integration-k3s-compass-dev pipeline when unregistering application from Compass

### ISSUE THREAD

**Issue by crabtree** [kyma-project/kyma#11331]
**Description**

The pipeline kyma-integration-k3s-compass-dev is now constantly failing. The problem occurs when the pipeline is trying to unregister the application from Compass. After short investigation it looks like on the Compass API there was some change that now block application deletion while there is still API bundle present. The Director logs contains following error:
```
time="2021-05-20T11:22:05Z" level=error msg="SQL Error. Caused by: update or delete on table \"applications\" violates foreign key constraint \"api_definitions_bundles_ready_fk\" on table \"api_definitions\". DETAILS: Key (id, ready)=(06eb9614-48b9-4919-99fb-defd038f79d3, t) is still referenced from table \"api_definitions\"." component="persistence/sql_error_mapper.go:32:persistence.MapSQLError" error="pq: update or delete on table \"applications\" violates foreign key constraint \"api_definitions_bundles_ready_fk\" on table \"api_definitions\"" error_source="check component log field" x-request-id=a0bb6baa-b796-4e58-8d7b-3771192c9687
```

**Comment by Disper** [comment]
Also happened today - https://status.build.kyma-project.io/view/gs/kyma-prow-logs/logs/kyma-integration-k3s-compass-dev/1397086459478937600
