### ISSUE TITLE
The publisher "replicas" should be made configurable too, cause publisher could horizontally scale. It should be added into the "code" too.

### ISSUE THREAD

**Issue by radufa** [kyma-project/kyma#11348]
The publisher "replicas" should be made configurable too, cause publisher could horizontally scale. It should be added into the "code" too.

_Originally posted by @radufa in https://github.com/kyma-project/kyma/pull/11256#discussion_r638522390_

**Comment by sayanh** [comment]
Solved as the replicas are added [here](https://github.com/kyma-project/kyma/blob/main/resources/eventing/charts/controller/templates/deployment.yaml#L54).
