### ISSUE TITLE
Proposal for supporting verbose backend status information

### ISSUE THREAD

**Issue by pxsalehi** [kyma-project/kyma#11368]
**Description**

In the `Backend`-CRD:
Currently, if eventing component is down, there is only one boolean field to signal this w/o any error description. Extend this information with description about:
- when (date when the change happened)
- why (reason for the change)
- what (what is the state)

The implementation could use the common pattern of conditions to achieve this

**Acceptance**
- [ ] `Ready` status of the backend is in sync with the detailed `conditions`
- [ ] `conditions` work for different backends (not hard coded to eg NATS only)
- [ ] also create events to enable us to get a history for the backend

**Comment by k15r** [comment]
* maybe in `conditions`
* or as an event attached to the crd ?

**Comment by raypinto** [comment]
@k15r do we need to document this change?

**Comment by k15r** [comment]
This will be changed with our planned rewrite of the backend handling
