### ISSUE TITLE
Kyma Serving the old expired certificate even after TLS certificate

### ISSUE THREAD

**Issue by mdheerendra** [kyma-project/kyma#11386]
**Description**

The documentation for updating expired TLS Certificates is missing some steps. We're unable to update the tls sucessfully and getting authentication error in logging in to kyma cli and updated certificate is not getting reflected.

**Expected result**

The documentation for renewing an expired certificate should cover all the steps needed to successfully renew the cert.

**Actual result**
Kyma was still serving the old expired certificate after following the renewal instructions.

**Versions**
Kyma Version: 1.17
K8S/AKS Version: v1.18.17
Hyperscaler: Azure

Steps Followed

Following these docs:
https://kyma-project.io/docs/components/security/#tutorials-update-tls-certificate-steps

Update TLS certificate
The TLS certificate is a vital security element. Follow this tutorial to update the TLS certificate in Kyma.

NOTE: This procedure can interrupt the communication between your cluster and the outside world for a limited period of time.

Prerequisites
New TLS certificate and key for custom domain deployments, base64-encoded
kubeconfig file generated for the Kubernetes cluster that hosts the Kyma instance

Steps
Custom domain certificate

CAUTION: When you regenerate the TLS certificate for Kyma, the kubeconfig file generated through the Console UI becomes invalid. To complete these steps, use the admin kubeconfig file generated for the Kubernetes cluster that hosts the Kyma instance you're working on.

Delete the net-global-overrides ConfigMap.

kubectl delete cm -n kyma-installer net-global-overrides
Export the Kyma version, your domain, new certificate and key as the environment variables.

export KYMA_VERSION={KYMA_RELEASE_VERSION}
export DOMAIN={YOUR_DOMAIN}
export TLS_CERT={YOUR_NEW_CERTIFICATE}
export TLS_KEY={YOUR_NEW_KEY}
Trigger the update process. Run:

kyma upgrade -s $KYMA_VERSION --domain $DOMAIN --tls-cert $TLS_CERT --tls-key $TLS_KEY
The process is complete when you see the Kyma installed message.

Restart the Console Backend Service to propagate the new certificate. Run:

kubectl delete pod -n kyma-system -l app=backend

At this point the certificate in owndomain-overrides was up to date, but Kyma was still serving the old, expired certificate.

**Any Feedback and Help will be Appreciate**

**Comment by Gupta-Amrit** [comment]
I faced the similar issue and fixed it by restarting the pods running in isito-system namespace using below command :

`kubectl delete --all pods -n isito-system`

**Comment by Tomasz-Smelcerz-SAP** [comment]
@mdheerendra does the fix proposed by @Gupta-Amrit work for you?

**Comment by mdheerendra** [comment]
Yes, It helped a lot.
