### ISSUE TITLE
Rewrite metric availability checker in monitoring tests

### ISSUE THREAD

**Issue by skhalash** [kyma-project/kyma#11382]
**Description**

There is a test case in the monitoring test suite that checks the availability of metrics used by one specific Grafana dashboard (`Kyma/Function`): https://github.com/kyma-project/kyma/blob/main/tests/fast-integration/test/3-monitoring.js#L47. We could generalize the test by checking a few (2-3) most common metrics from every exporter we deploy to the cluster.

**Reasons**

The test case is quite old and was originally added because the dashboard was often in a broken state. Such a test gets outdated really quickly when the corresponding dashboard is getting modified. It's also weird that we want to make sure that 1 random dashboard out of a hundred is rendered properly.

**Acceptance criteria**
* Pick a few metrics from every exporter (node exporter, kube-state-metrics, etc.) and check their availability

**Comment by a-thaler** [comment]
Please add more metrcis from different areas, like one metric from istio, fluent-bit, loki, grafana

**Comment by Pranav-SA** [comment]
Added metrics from loki, fluent-bit, grafana, istio to increase coverage. Reduced maximum number of metrics checked from each to two so that execution time for the test doesn't increase.
