### ISSUE TITLE
Provide configuration to disable spans not originating from services

### ISSUE THREAD

**Issue by abbi-gaurav** [kyma-project/kyma#1139]
### Description
As observed in the Jaeger UI, we can see the spans and traces created for components like `istio-mixer`, `istio-pilot`, `grafana`.

It makes sense to disable them
1. They do not provide any troubleshooting information 
1. They make the trace populated with unwanted data and information 
1. This could be confusing for the developers.
1. Additional storage/memory is consumed.

To makes the traces look better and developer friendly, there should be an option to disable the traces/spans from 
- istio-pilot
- istio-mixer
- core-grafana
- prometheus
- others?

### AC
- [ ] There are configuration options to disable spans/traces for above mentioned components
- [ ] The default values are set to disabled.

**Comment by abbi-gaurav** [comment]
Refer to the following conversation on google-gropus
https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/istio-users/GrM4kNN0FzY/KovJSM_oAQAJ

and the following PR https://github.com/istio/istio/pull/9280

**Comment by a-thaler** [comment]
With the upgrade to istio 1.5 finally all the istio specific component spans are gone (except of ingressgateway which is useful in my opinion). https://github.com/kyma-project/kyma/issues/9101
Grafana and prometheus are not part of any e2e trace but have traces when being accessed itself.

Closing the ticket as for me it looks quite clean now.
