### ISSUE TITLE
ClusterRole for istio-proxy-reset Job has insufficient permissions

### ISSUE THREAD

**Issue by krasish** [kyma-project/kyma#11416]
**Description**

When upgrading Kyma the _istio-proxy-reset_ Job will fail if one of the Pods which are "eligible for restart" is created by a job. That happens because the ClusterRole which the _istio-proxy-reset_ Job uses (which happens to be named the same) does not have permissions to get job resources in apiVersion "batch". The ClusterRole in question Is the following: 
https://github.com/kyma-project/kyma/blob/5a4f7610cf45f576047dd1ff1115bf0b60242844/resources/istio/templates/istio-proxy-reset.yaml#L8

I faced this problem during an update from Kyma 1.18 to Kyma 1.19 but practically it's a bug for **all releases** (the job still hasn't got sufficient permissions even in the latest Kyma). This will cause a Kyma upgrade to fail each time there is a pod created by a job with an Istio proxy running in it during an upgrade.

**Expected result**

Kyma upgrade does not fail when there are Pods that are "eligible for restart" and are created by Jobs.

**Steps to reproduce**

1. Install Kyma
2. Create a job that has an Istio-proxy sidecar in it. Make sure it has a running pod.
3. Start a Kyma upgrade

The upgrade will on the "installing istio" step because the _istio-proxy-reset_ Job will not succeed. 

**Troubleshooting**

Add permissions for all needed verbs (get, list, etc.) for Jobs (and probably CronJobs) on the aforementioned ClusterRole.

**Comment by cnvergence** [comment]
@krasish We think there is no sense to restart jobs, we will try to exclude jobs from restarting policy.
