### ISSUE TITLE
Can't bind event as a kyma-developer

### ISSUE THREAD

**Issue by philippe-lavoie** [kyma-project/kyma#11420]
**Description**

I added a user and assigned him the kyma-developer role. The user cannot add an event binding as there is insuficiant GraphQL privileges. (Kyma 1.22)

**Expected result**

I expect that a developer can develop...

**Actual result**

The user cannot add an event binding as there is insuficiant GraphQL privileges.

**Steps to reproduce**

Follow the normal steps to add a user as per this [tutorial](https://kyma-project.io/docs/components/security#tutorials-manage-static-users-in-dex) and then use kyma-developer when doing the role binding. After this is done, create a dummy function and try to bind an event. You'll get the GraphQL privilege issue.

**Troubleshooting**

I tried to look at the differences between kyma-admin and kyma-developer but I can't see inside roles a link to any GraphQL resources.

**Comment by valentinvieriu** [comment]
We plan on removing this graphql layer in the kyma 2.x release. We don't plan any work on the graphql layer
