### ISSUE TITLE
monitoring fast integration test is failling randomly

### ISSUE THREAD

**Issue by rakesh-garimella** [kyma-project/kyma#11435]
**Description**

Fast integration test for monitoring is failling randomly for different pods. One such run

```

  5 passing (6s)
  1 failing

  1) Monitoring test
       All Prometheus targets should be healthy:
     AssertionError: Following targets are unhealthy: kiali-server: server returned HTTP status 503 Service Unavailable: expected [ Array(1) ] to be empty
      at Context.<anonymous> (monitoring-test/monitoring-test.js:53:12)
      at processTicksAndRejections (internal/process/task_queues.js:95:5
  ```
https://storage.googleapis.com/kyma-prow-logs/logs/post-main-kyma-gardener-azure-alpha-eval/1402266689948618752/build-log.txt

**Expected result**

**Actual result**

**Steps to reproduce**

**Troubleshooting**

**Comment by shorim** [comment]
I have been keeping an eye on the prow jobs and have seen that the fast-integration test for monitoring was green recently. So, I will close this issue for now.
