### ISSUE TITLE
Refactor eventing publisher default deployment specs to a configmap 

### ISSUE THREAD

**Issue by sayanh** [kyma-project/kyma#11437]
**Description**

Refactor eventing publisher env vars to a configmap so that controller does not need to set it during reconciliations.

https://github.com/kyma-project/kyma/pull/11256#discussion_r639735697

**Reasons**

Configurations should not be hard-coded.

## Acceptance
- [ ] introduce a new configmap per backend

**Comment by k15r** [comment]
This ticket will be reevaluated once we started to discuss about a potential CRD driven EPP
