### ISSUE TITLE
Event registry for cluster internal events

### ISSUE THREAD

**Issue by sayanh** [kyma-project/kyma#11479]
**Description**

Cluster internal eventing is one of the core features of Kyma. However, there needs to be a registry that will enable the discovery of such events. Additionally, enable Kyma UI to show those events to users so that they can create subscriptions for functions/microservices.

**Reasons**

Ease of use.

**Attachments**

**Comment by raypinto** [comment]
With the implementation of [this dashboard](https://github.com/kyma-project/kyma/issues/14227#issuecomment-1162800569), we can see the eventTypes that are present as subscriptions, but not published to.

**Comment by raypinto** [comment]
Required for Open Resource Discovery (ORD)!
