### ISSUE TITLE
OOM errors in connector-service-app-ca-certs-backup

### ISSUE THREAD

**Issue by Halamix2** [kyma-project/kyma#11496]
**Description**

There are OOM errors in `connector-service-app-ca-certs-backup` pods

Examples from `kyma-cli-alpha-uninstall-gke`  job:
* https://status.build.kyma-project.io/view/gs/kyma-prow-logs/logs/kyma-cli-alpha-uninstall-gke/1405359601162915840
* https://status.build.kyma-project.io/view/gs/kyma-prow-logs/logs/kyma-cli-alpha-uninstall-gke/1405299201016860672
* https://status.build.kyma-project.io/view/gs/kyma-prow-logs/logs/kyma-cli-alpha-uninstall-gke/1405450197198180352

Memory limit needs to be set in `resources/application-connector/charts/connector-service/templates/helm-certs-removal-backup.yaml`

**Steps to reproduce**

This happens randomly.

**Troubleshooting**

**Comment by a-thaler** [comment]
I guess the new limit is too small (it is even smaller then the automatic default before), not the kyma2 upgrade job crashes constantly, see https://status.build.kyma-project.io/job-history/gs/kyma-prow-logs/logs/kyma-upgrade-gardener-kyma-to-kyma2
