### ISSUE TITLE
istio 1.10 improvements

### ISSUE THREAD

**Issue by strekm** [kyma-project/kyma#11495]
**Description**

With istio 1.10 `discovery selector` feature was introduced. So far we are using `useLegacySelectors` for the sidecar injector webhook which might be removed from istio at any time. Replace this behaviour with the discovery selector. In addition logic of patching mutating webhook in installation / upgrade scripts should be updated. 

**Reasons**

Istio 1.10 introducing new features

**Attachments**

https://github.com/kyma-project/kyma/pull/11434#pullrequestreview-684634206

**Comment by cnvergence** [comment]
Legacy selectors will be removed in the next Istio releases, therefore I have created the PR with the usage of the new sidecar injection logic. Gardener patches of the mutating webhook configurations have been updated to the new version.
- https://istio.io/latest/blog/2021/discovery-selectors/
- https://docs.google.com/document/d/1umIDCxvTwfOBtNh-bbRb3eyOxJ_4jsSBXl4pfcAYqR0/edit?resourcekey=0-OOCyBAXemTcnpyDRjU48pQ#
As for the discovery selectors, it has been postponed, we will need a way to process and label all namespaces with Istio sidecars in the post-install phase.
