### ISSUE TITLE
Failing dex installation on GKE 1.21.1-gke.400

### ISSUE THREAD

**Issue by Halamix2** [kyma-project/kyma#11497]
**Description**

The post-master-kyma-gke-rapid-integration job started failing when the new version of GKE (1.21.1-gke.100) appeared on the rapid channel.
First failure happened on 8.6.2021 - https://status.build.kyma-project.io/view/gs/kyma-prow-logs/logs/post-main-kyma-gke-rapid-integration/1402184647206506496

`dex` fails to install

**Steps to reproduce**

Run `post-master-kyma-gke-rapid-integration`

**Troubleshooting**

Output of `kubectl logs -n kyma-system dex-84998f5688-bgqrz`:
```bash
{"level":"info","msg":"config using log level: info","time":"2021-06-17T11:17:29Z"}
{"level":"info","msg":"config issuer: https://dex.gkeint-commit-272e68ec-iis2ai5zq5.a.build.kyma-project.io","time":"2021-06-17T11:17:29Z"}
failed to initialize storage: failed to inspect service account token: jwt claim "kubernetes.io/serviceaccount/namespace" not found
```

**Comment by bdelage** [comment]
Hi

It seems related to https://github.com/dexidp/dex/issues/2082#issuecomment-818124478

**Comment by mmitoraj** [comment]
Already fixed.
