### ISSUE TITLE
Update the "Application" CRD document to follow the template

### ISSUE THREAD

**Issue by klaudiagrz** [kyma-project/kyma#1149]
There is a new section in the CR template. All the existing CRs must be updated with the "Related resources and components" section.
https://github.com/kyma-project/community/blob/master/guidelines/templates/resources/custom-resource.md#related-resources-and-components

**Comment by lszymik** [comment]
The `Remote Environment` will be renamed to `Application.` It is the right moment to include that ticket as we will refactor the complete documentation.
