### ISSUE TITLE
Remove unnecessary fields from subscription cr created by Console UI / Busola

### ISSUE THREAD

**Issue by k15r** [kyma-project/kyma#11509]
Subscriptions created by the console currently include the protocol, protocolsettings and dialect. Those fields are not necessary anymore and should be removed.
```
  protocol: BEB
  protocolsettings:
    exemptHandshake: true
    qos: AT-LEAST-ONCE
  sink: http://test.test.svc.cluster.local
  dialect: beb,
```

A valid minimal subscription should only contain the fields:
- sink
- filters

**Comment by Wawrzyn321** [comment]
It's done in Busola, [here](https://github.com/kyma-project/busola/pull/265). AFAWK there won't be 1.25, so we decided not to touch Console/Console Backing Service here.
