### ISSUE TITLE
Move central-application-gateway into kyma-system namespace

### ISSUE THREAD

**Issue by koala7659** [kyma-project/kyma#11519]
There was an initial decision to install  new `central-application-gateway` component  in the `kyma-integration` namespace.

On Iteration Review we got feedback that is more reasonable to move this component into `kyma-system` namespace.

As a result the all services available to access remote api should be available at:

`http://central-application-gateway.kyma-system.svc.cluster.local`

**Comment by koala7659** [comment]
We are not ready to move this element without touching other parts of application-connector. It can be done in the future.

**Comment by janmedrek** [comment]
Duplicate of https://github.com/kyma-project/kyma/issues/11620
