### ISSUE TITLE
Limit network access to Central Application Gateway API 

### ISSUE THREAD

**Issue by koala7659** [kyma-project/kyma#11520]
The new `central-application-gateway` component provides access to every registered API in the Kyma cluster with a single URL. 

As a result every lambda function in the Kyma cluster may call with new gateway any registered external system API no matter if the its original application is bound to the namespace or not.
  
We should consider to introduce some security limitation for network access to the `central-application-gateway`. 

After we identify how we want to limit an access to the gateway for implementation we can use `Kubernetes Network Policy`, `Istio AuthorizationPolicy` or we can even provide such request validation inside the source code of the gateway.

**Comment by koala7659** [comment]
This is more requirement for the UI and user experience and flow. 
This taks requires some evaluation from PO side how we should limit access to other APIs from lambdas.

In any case UI (busola) should create appropriate rules. In gateway source code we should not do it. 

Please keep in mind the Kyma cluster is a single tenant solution, maybe workloads ad registered APIs should not be separated at all.

**Comment by janmedrek** [comment]
We had a discussion about providing a multi-tenant K8S cluster to the users and the outcome was that it is not the goal for Kyma. The users are free to implement their own separation with RBAC or Istio's mechanisms, we will not provide this functionality out-of-the-box.
