### ISSUE TITLE
Enhance endpoints of central-application-gateway

### ISSUE THREAD

**Issue by koala7659** [kyma-project/kyma#11526]
On Iteration Review we got feedback  the usage of API endpoints exposed by new `central-application-gateway` component  might not very intuitive for the user.

There is a problem that same API url must be called differently on SKR and KymaOS.    

We should review our design and possibly come with a better approach. 

We can ask cmp team for an advice regarding the subject of handling multiple API Entries in one Service.

**Comment by koala7659** [comment]
We need talk to cmp team about usage of compass API and if there are really some use cases for API bundles in production. 

It is not difficult task to make convenience API, but we don't want to loose functionality.

Maybe another endpoint needs to be created. One for single entry API, and another for multiple Entry API.

Default for one entry and extended for multiple entries.

**Comment by janmedrek** [comment]
Please bear in mind that this change could require an update on the docu side. @majakurcius

**Comment by janmedrek** [comment]
For the discussion/possible ways out please refer to: https://github.com/kyma-project/kyma/issues/11609
