### ISSUE TITLE
Reflect UAA changes in kyma 2.0

### ISSUE THREAD

**Issue by kwiatekus** [kyma-project/kyma#11521]
**Description**

Things to clean up:
 - [x] Clean up dex related documents
 - [x] Clean up IAM-kubeconfig service mentions
 - [x] Clean up XSUAA mentions
 - [x] Clean up api-server-proxy mentions
 - [x] Clean up static users mentions
 - [x] XIP io stuff
 - [x] permissions controller stuff
 - [x] DIAGRAMS!!!

Things to add:
 - [x] Recipes for custom OIDC Identity provider ( in the deep dive )
   - configure OIDC ( k8s generic) - link to [k8s docu](https://kubernetes.io/docs/reference/access-authn-authz/authentication/#configuring-the-api-server)
   - best practices for RBACS - (Cluster)RoleBindings - [link to k8s](https://kubernetes.io/docs/reference/access-authn-authz/rbac/), [current docu](https://kyma-project.io/docs/components/security/#tutorials-manage-static-users-in-dex-bind-a-user-to-a-role-or-a-cluster-role)
   - how to prepare custom kubeconfig with oidc-plugin

**Reasons**

**Assignees**

@kyma-project/technical-writers

**Attachments**

**Comment by kwiatekus** [comment]
To clarify:
Do we leave the default groups as a convinience for the users ( with custom OIDC providers ) ?

**Comment by pbochynski** [comment]
Yes - we should keep the groups.

**Comment by mmitoraj** [comment]
Hi, references to `xip.io` were removed with [this PR](https://github.com/kyma-project/kyma/pull/11690). Thanks.
