### ISSUE TITLE
Get Application Connector connection link without a port-forward command

### ISSUE THREAD

**Issue by lszymik** [kyma-project/kyma#1152]
**Description**

To acquire a link to Connector service with a one-time token, a user needs to make a `kubectl port-forward` or use Console UI. 

The alternative method must be created to avoid usage of `port-forward`. 

**Reasons**

We need to avoid `port-forward` as it will not work with Kubeconfig file from Console UI. Moreover, we need to stick to K8S best practices.

Without it, the automation of one-click integration will be difficult.

**Acceptance Criteria**

- Customer resource to trigger a token generation.
- The token field in the status.
- CR will be deleted after 5 minutes.
- Update documentation (replace port-forward from AC docs, describe a new CRD)
- Test with Kubeconfig acquired from Console UI

**Comment by crabtree** [comment]
Implementation follows investigation done in #1461
