### ISSUE TITLE
Remove the KEB - EMS (EventMesh) integration

### ISSUE THREAD

**Issue by radufa** [kyma-project/kyma#11539]
**Description**

Remove `ems` related code from KEB
KEB continues to have an integration with EMS (EventMesh) which is not used by default, but can be currently activated by SRE.
Cause KEB will not "provision/deprovision/upgrade" EventMesh for  future Kyma SKR instances anymore, the related code can be cleaned-up.

The code cleanup should be done in the following projects:
https://github.com/kyma-project/control-plane
https://github.tools.sap/kyma/management-plane-config

**Comment by radufa** [comment]
The associated PRs are:
https://github.com/kyma-project/control-plane/pull/870
https://github.tools.sap/kyma/management-plane-config/pull/1065

**Comment by k15r** [comment]
fixed in kyma-project/control-plane#870
