### ISSUE TITLE
Oathkeeper token cache not invalidated on JWKS rotation

### ISSUE THREAD

**Issue by DimitarPetrov** [kyma-project/kyma#11550]
**Description**

Currently, in kyma there are two jobs rotating JWKS of oathkeeper. Once is post-upgrade job and one is cronjob. However it looks like there is a token cache in the id_token mutator which caches all the issued tokens for the configured TTL. 

More details of the oathkeeper's part of the issue here: https://github.com/ory/oathkeeper/issues/763

**Steps to reproduce**

1. Configure oathkeeper rule with id_token mutator with a long enough TTL (ex. 1h)
2. Make a call matching this rule in order for oathkeeper to cache your id_token.
3. Upgrade kyma or trigger the cronjob in order to rotate the JWKS
4. Make the same call as in 2. and the token received won't have a valid signature if validated with the most recent JWKS served by oathkeeper.

**Fix proposal**

An idea to fix the rotation in kyma until oathkeeper introduce cache invalidation on JWKS rotation:

1. Since the cache in othkeeper relies on the following key `fmt.Sprintf("%s|%s|%s|%s|%s", config.IssuerURL, ttl, config.JWKSURL, claims, session.Subject)` we have control over those things only. My proposal leverages the JWKSURL.
2. Oathkeeper has live relod of the config files where the JWKSURL is configured, however in order for this to work you need to unset this env var: https://github.com/kyma-project/kyma/blob/main/resources/ory/charts/oathkeeper/templates/deployment-with-sidecar.yaml#L77
3. Once this is done the JWKS rotator job can name the JWKS file differently with each rotation (for example append unix timestamp to the file as a suffix). This will result in a different key in the secret, resulting in a different file in the mount.
4. In order for this to work and for oathkeeper to detect the new JWKS file the jwks_url url in `ory-oathkeeper-config` configmap should be updated accordingly to match the new file.
5. This way the `config.JWKSURL` will be different invalidating the tokens in the cache issued by the old one.

**Comment by strekm** [comment]
we are working on switching to istio in api-gateway implementation and we do not plan to fix it. https://github.com/kyma-project/api-gateway/issues/322
