### ISSUE TITLE
Deprecate {application}/v2/events from validator

### ISSUE THREAD

**Issue by sayanh** [kyma-project/kyma#11565]
**Description**

There is no backing API for `{application}/v2/events` and it is not functional. Hence this API should be deprecated.

Details: https://github.com/kyma-project/kyma/blob/main/components/application-operator/charts/application/templates/virtual-service.yaml#L26

**Comment by k15r** [comment]
this is only used in the 'old' non central connectivity validator. That component is already eol. Not fixing it
