### ISSUE TITLE
Review jobs in components from service-mesh, security, api-gateway area

### ISSUE THREAD

**Issue by strekm** [kyma-project/kyma#11578]
**Description**

Review jobs running in following components:
- api-gateway
- ory
- istio
- certificates
- cluster-users
Determine which jobs can be replaced with kubernetes resources and which jobs are mandatory way of installation given ccomponent. 

**Reasons**

Kyma 2.0 components should be installed / updated with kubectl apply and helm templating. 

**Attachments**

**Comment by cnvergence** [comment]
Jobs in Certificates can be moved into helm templates, based on the variable, we can either create a secret or gardener cert resource on the cluster.

**Comment by cnvergence** [comment]
In Ory secret-migration can be also moved into helm templates - [secret-migration.sh](https://github.com/kyma-project/kyma/blob/main/resources/ory/files/secret-migration.sh)
In the Oathkeeper removing the job will be difficult, as it uses oathkeeper CLI to generate k8s secret, we need to find the way to generate it without this CLI.

**Comment by cnvergence** [comment]
As for the Istio, I don't think we should try to move jobs related to deploying Istio with IstioOperator, as they will be move to the installation library.
[Istio-proxy-reset.sh](https://github.com/kyma-project/kyma/blob/main/resources/istio/files/istio-proxy-reset.sh) logic also can't be deployed by helm templates.

**Comment by strekm** [comment]
i think that moving logic of `conditionals - secret-migration.sh` might be a bit troublesome. needs some more investigation if that's doable

**Comment by strekm** [comment]
certificates: https://github.com/kyma-project/kyma/issues/11628

**Comment by pbochynski** [comment]
As a result of the review following tasks were created:
- https://github.com/kyma-project/hydroform/issues/329
- https://github.com/kyma-project/kyma/issues/11628
- https://github.com/kyma-project/kyma/issues/11629
