### ISSUE TITLE
High memory usage of UI API Layer acceptance tests

### ISSUE THREAD

**Issue by pkosiec** [kyma-project/kyma#1158]
UI API Layer acceptance tests takes too much RAM. UI API Layer itselft takes ~20MB, but acceptance tests - 80-100MB. Investigate the issue.

**Comment by pkosiec** [comment]
We need to investigate if the bug still occurs.

**Comment by kwiatekus** [comment]
We will reduce memory consumption of the tests gradually with small steps, not with a single work unit.
