### ISSUE TITLE
Handle service name conflicts in Kyma-Compass communication

### ISSUE THREAD

**Issue by franpog859** [kyma-project/kyma#11609]
**Context**

Some time ago there was [Central Application Gateway](https://github.com/kyma-project/kyma/issues/10361) introduced. It operates on Service display names and therefore there was a need to change Service validation in the Application Registry for the open-source scenario. It disallows to register two services with the same names and to update the service name. You can find it [here](https://github.com/kyma-project/kyma/pull/11295)

**Problem**

Kyma when working in the Compass mode uses Applications and Services registered in the Compass Director. There is no validation of the Service display names in the Compass logic and after a discussion with the Compass owners, there is no plan to add such. In this case, we need to somehow take care of two Services with the same display names coming from Compass just **not to crush the system or mislead the user**

**Discussed possible solutions**
- Return an error in Compass Runtime Agent while fetching a Service from Compass with a display name that is already present. It's easy to implement but it's misleading for the user. They won't be aware of why their Service does not work until they debug the Kyma cluster and see the error log
- In Compass Runtime Agent add some prefix or suffix to the Service name so they can be distinguished by the Central Application Gateway. It doesn't seem to be super hard to implement but it's misleading for the user as the URL used in the JS function won't match the real Service name, and it contradicts Central Application Gateway's main assumption the user will know the Service URL even before the Service creation. It also does not match the open-source behavior

Feel free to take part in the discussion on how to handle such a thing. Add new proposals for the solution, TODOs, and acceptance criteria below

**Comment by janmedrek** [comment]
I would say we should go with the second approach, this does not disable the flow, only makes it a bit less convenient. The source is easy to fix so it should be documented as well.

**Comment by franpog859** [comment]
Third proposed solution:
- Allow to register two services coming from Compass but return an elaborate error from Central Application Gateway that there are two services with the same names and it cannot figure out which one to use. And it's the user's mistake. User should register only one service with such a name

**Comment by janmedrek** [comment]
Solution that @franpog859 suggested will be introduced in https://github.com/kyma-project/kyma/issues/11526
