### ISSUE TITLE
Describe as tutorial of the API Gateway how to allow CORS for further HTTP methods

### ISSUE THREAD

**Issue by mado0803** [kyma-project/kyma#11608]
**Description**

Feedback from a Kyma using team was that they had to look by themselves for quite some time how to allow CORS for further HTTP methods to expose deployments. It might be a good idea to have this as sample in the documentation.

**Area**

* API Gateway

**Reasons**

Feedback from a Kyma-using team

**Assignees**

@kyma-project/technical-writers

**Attachments**

- Find the virtual service name: `kubectl describe VirtualService -n acceptance`
- With the found name, edit the configuration to add the respective HTTP methods: `kubectl edit VirtualService <service name> -n acceptance
`

**Comment by strekm** [comment]
CORS policies are applied under the hood of APIRule. there is not additional configuration needed so i think no additional documentation is needed as well
