### ISSUE TITLE
Controller for handling Application Connector certificates

### ISSUE THREAD

**Issue by janmedrek** [kyma-project/kyma#11611]
**Description**

Right now the certificates in Kyma are handled by multiple different sources, this is especially convoluted in Application Connector. There are multiple jobs performing various actions on certificates and secrets that they are stored in. We need a simpler, more reliable, and resilient way of handling such logic.

This will also solve issues such as:
https://github.com/kyma-project/kyma/issues/11561

**Reasons**

We want a developer-friendly, stable environment.

**Acceptance Criteria**
- [ ] Jobs handling certificates removed
- [ ] New component introduced for handling the certificate logic
- [ ] Helmless installation available
- [ ] Documentation updated/created

**Out of scope**
- Logic for rotating OS mTLS certificate (will be implemented later)

**Comment by janmedrek** [comment]
Went through the jobs we have in Application Connector that are related to certificates:
- https://github.com/kyma-project/kyma/blob/main/resources/application-connector/templates/certs-setup-job.yaml
- https://github.com/kyma-project/kyma/blob/main/resources/application-connector/charts/connector-service/templates/helm-certs-removal-backup.yaml
- https://github.com/kyma-project/kyma/blob/main/resources/cluster-essentials/templates/migrate-ac-certs-job.yaml
- https://github.com/kyma-project/kyma/blob/main/resources/application-connector/templates/certs-sync-deploy.yaml

The above should be taken into account when determining the responsibilities of this controller.

**Comment by majakurcius** [comment]
Documentation bits:
- [Application Connectivity Certs Setup Job](https://kyma-project.io/docs/1.24/components/application-connector/#configuration-application-connectivity-certs-setup-job) configuration doc
- Migration guide, potentially, if needed
- ?

**Comment by franpog859** [comment]
I'd add to the acceptance criteria an explicit point so this controller could be installed using `kubectl apply` (without helm) among others Kyma components. As far as I can see [in this issue](https://github.com/kyma-project/kyma/issues/11561) we can test it using `kyma.js` installer and the `./kyma.js install --skip-components kiali,tracing --with-central-application-gateway --use-helm-template` command. After that the commerce-mock fast-integration scenario run with `mocha test/2-commerce-mock.js -b` command should pass

**Comment by koala7659** [comment]
Draft PR with some development documentation https://github.tools.sap/framefrog/documentation/pull/28

**Comment by koala7659** [comment]
It turns out controller pattern is not very well suited for this problem. Identified following areas to fix:

* fix crash in job 
* remove cert-sync-deployment and restore state from https://github.com/kyma-project/kyma/pull/9845

**Comment by koala7659** [comment]
The implementation details of the solution can can be found [here](https://github.tools.sap/framefrogdocumentation/investigations/certificates-cleanup)
