### ISSUE TITLE
Enterprise Commerce API is not fully transferred to KymaOS

### ISSUE THREAD

**Issue by koala7659** [kyma-project/kyma#11614]
**Description**

After pairing Kyma OS (version 1.23 and 1.23 rc2) with the Enterprise Commerce system - one of its API (`Platform Admin API v2`) is missing from available API list. User is not able to use it. Here is list of fetched APIs.

For SKR (14 entries): 
```
Smart Edit Webservices v1
CC OCC Commerce Webservices v2
Order Management Webservices v1
Preview Webservices v1
CC Assisted Service Module Webservices v2
CMS Webservices v1
Personalization Webservices v1
Adaptive Search Webservices v1
Warehousing Webservices v1
Permission Webservices v1
CC Events v1
Coupon Webservices v1
Platform Admin API v2
CMS Smart Edit Webservices v1

```
for KymaOS (13 entries):
```
CC Assisted Service Module Webservices v2
Adaptive Search Webservices v1
Personalization Webservices v1
CMS Smart Edit Webservices v1
Preview Webservices v1
Coupon Webservices v1
CC OCC Commerce Webservices v2
Permission Webservices v1
CC Events v1
Warehousing Webservices v1
Order Management Webservices v1
Smart Edit Webservices v1
CMS Webservices v1
  
```

**Expected result**

All EC API entries are should available in both KymaOS and SKR

**Actual result**

`Platform Admin API v2` is missing in KymaOS

**Steps to reproduce**

- Install Kyma Cluster in two different flavours - SKR and Kyma OS.
- Connect both clusters with same instance of Enterprise Commerce
- Check a list of fetched APIs

**Troubleshooting**

There is no any possible way to workaround this problem. We must investigate why this API is missing and fix it.

**Comment by koala7659** [comment]
Here are application CRDs created as representation of the same EC system on KymaOS and Kyma SKR clusters
[CRDs.zip](https://github.com/kyma-project/kyma/files/6749155/CRDs.zip)

**Comment by koala7659** [comment]
Another observation - on Enterprise Commerce side missing `Admin API` has no Target ID assigned
![image](https://user-images.githubusercontent.com/18568025/124150204-a77c8200-da91-11eb-9b78-77fee6d032cd.png)

**Comment by janmedrek** [comment]
Closing this issue as it was not replicated in any other environment. If we can confirm that it is in fact a problem on Kyma side then please feel free to reopen the issue.
