### ISSUE TITLE
Enable w3c-tracecontext support in istio

### ISSUE THREAD

**Issue by a-thaler** [kyma-project/kyma#11638]
**Description**
As part of https://github.com/kyma-project/kyma/issues/11231 the otel-collector will allow support for opencensus and with that will enable us to switch the tracer in istio to be based on opencensus, supporting [w3c-tracecontext](https://www.w3.org/TR/trace-context/) and current B3. As the w3c finally gets adopted widely and is the only vendor-neutral and open protocol in that area, Kyma should switch to that protocol by default.

Goal: Change the default istio configuration to use the w3c-tracecontext protocol as default.

Criteria:
- Requests via the istio ingressgateway will be enriched with proper w3c-tracecontext headers if not existent
- Envoys are pushing trace data to the central collector/backend
- Tracing is disabled by default and can be activated by the user
- Sampling rate can be configured by the user and is using the istio default by default

**Reasons**

**Attachments**

**Comment by chrkl** [comment]
PR #16372 introduce an OpenCensus extension provider for Istio that configures the W3C trace context. Istio tracing has to be activated using a Telemetry resource.
