### ISSUE TITLE
Spike: otel-collector managed by operator

### ISSUE THREAD

**Issue by a-thaler** [kyma-project/kyma#11630]
**Description**
As part of https://github.com/kyma-project/kyma/issues/11231 the `otel-collector` should be introduced in order to have a central point in the cluster to collect and ship traces in a flexible way. Jaeger should be just one of the possible backends.
From the beginning, the new collector setup should be fully managed by the existing `telemetry-operator` using a feature flag.
The functionality should focus on traces only and should allow adjustments of the base setup via externalized settings and adjustments of the pipeline via a future CRD.

Criteria:
- Create a new operator reconciles a `Tracing` CR where an `otlp` endpoint is set
- For simplicity, assume there is a limit of one CR
- When the CR is created an `otel-collector` is deployed to the cluster
- When the CR is deleted the `otel-collector` is undeployed
- `otel/opentelemetry-collector-contrib` image should be used
- `otlp` and `opencensus` receivers are defined in the `otel-collector` config and corresponding ports are exposed using a Kubernetes service
- Only a `traces` pipeline is defined (no metrics or logs)

**Reasons**

Kyma should mainly focus on integration with existent trace backends and with that should be based on an agent like the `otel-collector`. An in-cluster trace backend should be an optional feature that can be installed easily.

**Attachments**

**Comment by skhalash** [comment]
Described in [this PR](https://github.com/kyma-project/community/pull/720)
