### ISSUE TITLE
Simplify Istio installation / upgrade

### ISSUE THREAD

**Issue by strekm** [kyma-project/kyma#11635]
**Description**

Installing Istio via helm job performing istioctl installation is considered an antipattern. Istio should be installed via istioctl using the default configuration. This step should be part of parallel-installation lib. Implement new istio chart containing minimal IstioOperator CR including only changes which kyma is introducing. It should be possible to override each of these configuration .

AC:

- Istio installed via istioctl
- Istio installed with default configuration (by default sidecars are NOT injected)
- support for profiles
- support sidecar restarts
- preferably there are no overrides needed for managed kyma

**Reasons**

Improve Istio installation / upgrades.

---
<details>
    <summary>:warning: Funnel process - do not remove!</summary>
    </br>

Name|Value
:--- | :---
theme | Technical Debt
business value | 5
technical value | 10
user value | 5
open-source value | 8
effort | 
requested by | 
</details>

**Comment by strekm** [comment]
comment from @cnvergence 
> With Istio 1.10, there is a possibility to reduce computational load on Istiod, by using discoverySelectors.
With those labels we can control which namespaces/services/endpoints/pods Istio's control plane watches and pushes its update to.
By default Istio watches all of the cluster.
Read more:
https://istio.io/latest/blog/2021/discovery-selectors/
https://github.com/istio/istio/pull/29802

**Comment by strekm** [comment]
should fix:
- https://github.com/kyma-project/kyma/issues/10616
- https://github.com/kyma-project/kyma/issues/11416 (???)

**Comment by varbanv** [comment]
Reconciler related work tracked here: https://github.com/kyma-incubator/reconciler/issues/35

**Comment by strekm** [comment]
need to move to next milestone since few bits are still missing and reconciler task proves to be challenging
