### ISSUE TITLE
Introduce a scheduler in serverless enabling users to trigger functions on a given schedule

### ISSUE THREAD

**Issue by kwiatekus** [kyma-project/kyma#11652]
**Description**

Introduce a scheduler in serverless enabling users to trigger functions on a given schedule.

**Reasons**
A time based function trigger is a valid use-case for FaaS and its currently missing in kyma serverless.
User has option to trigger function with k8s cronjobs, but this approach requires k8s knowledge from the user and is only suitable for long intervals. Otherwise there might be a resource problem ( cluttering the cluster )

**Assumptions**

 - The time trigger does not carry any input payload. It's like a "ping" signal
 - The time trigger does not originate from the function runtime itself - as it can be scaled down to zero and inactive
 - It should be investigated weather we make our controller responsible for triggering signal ( i.e via [cron library](https://pkg.go.dev/github.com/robfig/cron) ) or should we delegate to k8s cronjobs?
 - User defines "cron"-like schedule for the function
 - Should user defines if the time precision is essential? (Might be a factor for scaled to zero functions in the period of inactivity )

**Attachments**
 - [Initial investigation](https://github.tools.sap/wookiee/documentation/pull/10)

**Comment by dktrkranz** [comment]
I'd love to see this feature implemented. I have a function which ideally should be triggered once per day, perform its job and return the results to the listeners without the need of external CURL triggers.

**Comment by kwiatekus** [comment]
thanks @dktrkranz. We will keep it in the backlog

**Comment by absqwe** [comment]
This would be a nice feature have, we wouldn't have to use a third party tool to trigger the functions.

**Comment by kwiatekus** [comment]
Confuring crob based trigger is easier with keda module (that could be installed in kyma runtime) and cron trigger
https://community.sap.com/t5/technology-blogs-by-sap/sap-btp-kyma-runtime-leveraging-keda-module-capabilities-for-efficient-and/ba-p/13573526
