### ISSUE TITLE
Make Central Application Gateway fast integration test the Application Connectivity 2.0 test

### ISSUE THREAD

**Issue by franpog859** [kyma-project/kyma#11654]
**Context**

There is Kyma 2.0 getting closer and closer. We want to automatically check the features we introduced in the Application Connectivity area. Currently, we have two optional Prow jobs `pre-main-kyma-integration-k3s-central-app-gateway` and `pre-main-kyma-integration-k3s-central-app-gateway-compass` testing the happy-path Kyma flows for the open-source and Compass mode accordingly. Both of them differentiate from the default pipelines by installing Central Application Gateway and using the adequate URLs in serverless functions

**Problem**

In the Application Connectivity area, we introduce not only Central Application Gateway but also Central Application Connectivity Validator (CACV). We'd like to test it as well

**Discussed possible solutions**

- Create [an override for the `central_application_connectivity_validator.enabled` in the `...central-app-gateway...` pipelines](https://github.com/kyma-project/kyma/blob/main/tests/fast-integration/installer/index.js#L181) so the CACV will be installed. Change the `kyma.js` arguments and interiors from `withCentralApplicationGateway` to `withApplicationConnectivity2` so everything is consistent. Rename also [the pipelines](https://github.com/franpog859/test-infra/blob/main/templates/data/kyma-integration-data.yaml) to `...-main-kyma-integration-k3s-app-conn2...` as they test not only the Central Application Gateway but the whole Application Connectivity 2.0 from now on

Feel free to take part in the discussion, propose another solution and create acceptance criteria below

**Comment by Disper** [comment]
Please consider looking at [this issue](https://github.com/kyma-project/kyma/issues/11180) for example of the implementation in the fast-integration tests area.
