### ISSUE TITLE
Create a cron or a general integration job for eventmesh 

### ISSUE THREAD

**Issue by sayanh** [kyma-project/kyma#11659]
**Description**

Due to the dependence on `APIRule` CR, it is crucial to have a cron or a general integration job for all PRs to test the eventing flow with EventMesh.

**Reasons**

Changes in APIRule or OAuth2API specs can break the eventing flow.

##Acceptance
- [ ] setup a cron job (2* per day)
- [ ] run all eventing related tests (backend switching, tracing and monitoring)
- [ ] configure slack notification on failure

**Attachments**

**Comment by pxsalehi** [comment]
Let's check in grooming, whether we need to make sure the eventing prow job also uses a freshly copied CRD for APIRule.

**Comment by marcobebway** [comment]
Ideas:
- Changes to APIRule CRD can be caught with pre-submit job:
  - It can block development so job can be optional.
  - Eventing team should be aware of the breaking change.
- Changes to APIRule CRD can be caught with post-main job + notifications.
- CronJob runs nightly + notifications.

**Comment by k15r** [comment]
will change entirely with modularization
