### ISSUE TITLE
Length of Gardener cluster name 

### ISSUE THREAD

**Issue by krasimirdermendzhiev** [kyma-project/kyma#11660]
**Description**

New cluster on Gerdener
Gardener version: 1.50.2
Kubernetes 1.20.8 and 1.19.12
Kyma chart 0.13.0 App 1.23.1
When I use cluster name with length example: kyma-cluster and try to deploy Kyma from Services Hub. I have this message.

> "Unable to create the release: template: kyma/templates/_helpers.tpl:57:4: executing "kyma.checkRequirements" at <fail (printf "Resulting cluster domain '%s' has length '%d' and exceeds maximum length of '64' for certificate generation. Please create a cluster with a shorter name." $shootInfo.data.domain $domainLen)>: error calling fail: Resulting cluster domain 'kyma-cluster.promart.shoot.canary.k8s-hana.ondemand.com' has length '65' and exceeds maximum length of '64' for certificate generation. Please create a cluster with a shorter name."

**Area**
* Application Connector

**Reasons**
 I don't see in the chart description that the name for my cluster should be shorter.

**Assignees**

@kyma-project/technical-writers

**Attachments**
![Screenshot 2021-07-09 at 9 54 21](https://user-images.githubusercontent.com/82384876/125036474-b7045800-e09b-11eb-8290-8b386b30c4c4.png)

**Comment by a-thaler** [comment]
Hi @krasimirdermendzhiev,
thanks for your feedback. As currently the Kyma installation is relying on the domain and certificate provided by the gardener cluster, this restriction exists. We assured that the helm chart is failing already at the templating to have fast feedback. The restriction will be gone with the rollout of https://github.com/kyma-project/kyma/issues/11337. 

For now, as far as I understand you would expect a clear statement in the prerequisites section of the readme file, right? I just added it now while upgrading the chart to 1.24.

Btw, you are talking here about an SAP internal way of installing kyma and you should not report problems here. Feel free to reach out to me to clarify how else you should report it.
