### ISSUE TITLE
Initial setup of telemetry-operator

### ISSUE THREAD

**Issue by a-thaler** [kyma-project/kyma#11663]
A new operator is needed to make the fluent-bit configuration modular and changable at runtime. The proposal can be found here: https://github.com/kyma-project/kyma/issues/11105

Goal: Implement a first version of the operator in a new optional kyma component

Criterias:
- There is a new kyma component marked as "experimental" and having a docker image available
- It is described how to deploy the image and related CRDs
- there is no helm chart yet (to be done in sub-sequent task)
- the dry-run option via validating webhook is not yet required
- unit testing, automated build pipeline is included
- the used image is hardened from security perspective (non-root user, non-privileged, security context, known vulnerabilities removed)

**Comment by chrkl** [comment]
Initial version of the telemetry-operator has been merged to main. Build and test pipelines have been set up. The following tasks are open to make the operator usable:
- Modify the fluent-bit chart to consume the created ConfigMaps and Secret
- Create a Helm chart to deploy the operator
- Add a webhook to validate LoggingConfigurations before applying to the configuration
