### ISSUE TITLE
Allow duplication of Application names

### ISSUE THREAD

**Issue by janmedrek** [kyma-project/kyma#11685]
**Description**

There are cases where the user would like to register two different systems which have a colliding name. Currently, it is not possible due to the 1:1 mapping of the Application name to the Custom Resource name. This logic was introduced in the past to enable the implementation of specific features which are no longer needed.

**Reasons**

We do not want to introduce unnecessary limitations for our users.

**Acceptance Criteria**
- [ ] It is possible to register two applications with the same name
- [ ] There is some kind of additional unique identifier introduced `SystemNumber`
- [ ] `Application` CR names are unique
- [ ] Just as in the situation with the conflict of service names, Application Gateway exposes additional endpoint for routing based on `SystemNumbers`
- [ ] Documentation update:
  - Application CRD
  - Application Gateway docu

**Comment by janmedrek** [comment]
The unique identifier that we agree on should also be exposed in the Kyma Console, so that the users know which Application is which.

**Comment by franpog859** [comment]
How will the GatewayURL in the Function look like? As far as I remember it was important to make it declarative (that was the main assumption for the Central Application Gateway story). If there will be some suffix created that is needed in the URL, it's no longer declarative

**Comment by rafalpotempa** [comment]
We conclude that we should reach out to Compass Team and discuss the extension of their model. If we want to do it good we need to take some additional effort.
- [ ] go
- [ ] no go

**Comment by rafalpotempa** [comment]
**Reasoning**

Compass gives us unique `SystemNumber`.
We go the same way we did with Service Names: 
- if two apps have the same name Gateway returns error -> the user must use additional endpoint that uses `SystemNumber`

**Comment by majakurcius** [comment]
Check also other AC subcomponents docu (App Registry?).
