### ISSUE TITLE
Arbitrary event type value in Subscription's filter property

### ISSUE THREAD

**Issue by m00g3n** [kyma-project/kyma#11683]
**Description**

Current solution requires event type value in subscription's `filter` property to:
- start with `sap.kyma.custom` prefix
- be 7 segments long (e.g. `sap.kyma.custom.commerce.coffee.produced.v1`)

As a user I want to be able to set arbitrary event type value in Subscription filter section.

**Reasons**

This feature may allow to integrate external systems via eventing without  a need of modifying external systems.

**Attachments**

**Comment by k15r** [comment]
- [ ]  document subscribing to events from applications directly connected to ems (eg. `sap.c4c.foo.created.v1`)
- [ ] rethink automatic type generation approach

**Comment by k15r** [comment]
will be handled here: https://github.com/kyma-project/kyma/issues/13797
