### ISSUE TITLE
Can't use firestore python dependency in serverless function.

### ISSUE THREAD

**Issue by dekiel** [kyma-project/kyma#11701]
**Description**

when building python function with dependency on google-cloud-firestore package I’m getting following error.

```
Collecting grpcio<2.0dev,>=1.29.0
  Downloading grpcio-1.37.0.tar.gz (21.7 MB)
    ERROR: Command errored out with exit status 1:
     command: /usr/local/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-xfe45w0h/grpcio_d8e06494735847a8981a81dc9e2c569a/setup.py'"'"'; __file__='"'"'/tmp/pip-install-xfe45w0h/grpcio_d8e06494735847a8981a81dc9e2c569a/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-6dyf7003
         cwd: /tmp/pip-install-xfe45w0h/grpcio_d8e06494735847a8981a81dc9e2c569a/
    Complete output (11 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-xfe45w0h/grpcio_d8e06494735847a8981a81dc9e2c569a/setup.py", line 255, in <module>
        if check_linker_need_libatomic():
      File "/tmp/pip-install-xfe45w0h/grpcio_d8e06494735847a8981a81dc9e2c569a/setup.py", line 202, in check_linker_need_libatomic
        cpp_test = subprocess.Popen([cxx, '-x', 'c++', '-std=c++11', '-'],
      File "/usr/local/lib/python3.8/subprocess.py", line 858, in __init__
        self._execute_child(args, executable, preexec_fn, close_fds,
      File "/usr/local/lib/python3.8/subprocess.py", line 1706, in _execute_child
        raise child_exception_type(errno_num, err_msg, err_filename)
    FileNotFoundError: [Errno 2] No such file or directory: 'c++'
```
It looks I can’t solve this myself. Could you please take a look and let me know if there is some way to workaround this? If not should I create a bug or this is known limitation? I didn’t found any mention in docs about that.

**Expected result**

Function image is build and run.

**Actual result**

Image build failed.

**Steps to reproduce**

Try to build python function with dependency on google-cloud-firestore

**Comment by kwiatekus** [comment]
Hi @dekiel 
It is a known limitation that is tracked under this issue:
https://github.com/kyma-project/kyma/issues/10887

Having more capable base image comes with security implications so we are not super eager to provide it.
Please see a workaround section in the linked issue

**Comment by kwiatekus** [comment]
@dekiel Should be possible with the new feature in serverless allowing you to override the function base image.
see an example that would suit your case [here](https://github.com/kwiatekus/kyma-serverless-runtime-override/blob/main/src/custom-runtime/config.yaml#L4) --> using example of  runtime image override from this [pr](https://github.com/kyma-project/examples/pull/198)

**Comment by kwiatekus** [comment]
Tutorials for this feature are on the way
