### ISSUE TITLE
NATS-subscription (on NATS server) gets deleted on every reconciliation

### ISSUE THREAD

**Issue by radufa** [kyma-project/kyma#11704]
**Description**

At each K8S reconcile call on Eventing controller for the NATS backend, the corresponding NATS subscription (on NATS server) is deleted and recreated again. 
At each deletion of a NATS subscription on NATS-server side, all the messages waiting on the NATS subject to be delivered are also deleted. Cause we are offering now the NATS backend for SKR prod too, we should avoid this.

**Expected result**

The NATS subscription should be deleted only if it's necessary. If nothing has to be changed, then the deletion should be skip

**Actual result**

**Steps to reproduce**

**Troubleshooting**

**Related Issues**
- [x] https://github.com/kyma-project/kyma/issues/12993

**Comment by k15r** [comment]
Scenarios:

**Comment by k15r** [comment]
Check if 2.2 provides a client that would allow us to check the subscription status

**Comment by k15r** [comment]
We will change the subscription logic with the implementation of jetstream

**Comment by nachtmaar** [comment]
Preferred solution is to use the SDK the and use the `/subsz`.
