### ISSUE TITLE
Document K2.0 values YAML - concept, syntax, semantics

### ISSUE THREAD

**Issue by NHingerl** [kyma-project/kyma#11715]
**Description**

Open ToDos from [a doc review](https://github.com/kyma-project/kyma/issues/11228) with @a-thaler:

- [x] Explain concept: We just need a values yaml with a "global" Kyma chart and sub-charts for the components.
- [x] Document the syntax and semantic of the prerequisites attribute in the yaml file.

I created a [document stub](https://60dd90724616b3c713c75b25--kyma-project-docs-preview.netlify.app/docs/kyma/preview/05-technical-reference/05-configuration-parameters/) in 05-technical-reference/05-configuration-parameters/. Not sure if this is the best place to document this, but seemed okay for now.

**Area**

With K2.0, ConfigMaps/Helm Overrides are obsolete. Now, configuration values are overridden in a values YAML. We need to document how this works.

**Assignees**

@kyma-project/technical-writers

**Attachments**

**Comment by majakurcius** [comment]
Q: How does this [Change Kyma settings](https://60dd90724616b3c713c75b25--kyma-project-docs-preview.netlify.app/docs/kyma/preview/04-operation-guides/operations/03-change-kyma-config-values) document correspond to this?

**Comment by NHingerl** [comment]
We're linking to the respective Helm documentation now (https://github.com/kyma-project/kyma/issues/11889)
