### ISSUE TITLE
Do we need a tutorial how to keep the cluster secure?

### ISSUE THREAD

**Issue by NHingerl** [kyma-project/kyma#11716]
**Description**

Another one from a review with @a-thaler :
We could discuss with SREs whether the current documentation is sufficient to instruct users how to keep the cluster secure. Maybe we need a new tutorial?

**Area**

**Assignees**

@kyma-project/technical-writers

**Attachments**

**Comment by NHingerl** [comment]
If we don't plan to create a tutorial for OS end users, let's close this ticket.

**Comment by TorstenD-SAP** [comment]
The best practice guide will be added to the [BTP Best Practice guide on help.sap.com](https://help.sap.com/docs/btp/best-practices/best-practices-for-sap-btp)

**Comment by NHingerl** [comment]
Security documentation improvement ongoing, project with @mmitoraj etc.
