### ISSUE TITLE
Event throughput reduced by half as compared to Kyma 1.21

### ISSUE THREAD

**Issue by radufa** [kyma-project/kyma#11710]
**Description**

The Event Load test - Kyma 1.24 - SAP Event Mesh, described in: https://wiki.wdf.sap.corp/wiki/display/kyma/Event+Load+test+-+Kyma+1.24+-+SAP+Event+Mesh
finds that the throughput of Eventing 1.24 compared to 1.21 is reduced by half.

**Expected result**
No performance lost in Eventing 1.24

**Actual result**

**Steps to reproduce**

**Troubleshooting**

**Comment by k15r** [comment]
After rerunning the tests with the latest eventing components these performance issues have been resolved
