### ISSUE TITLE
Rate Limiting based on oAuth client_id

### ISSUE THREAD

**Issue by johanneseschrig** [kyma-project/kyma#11714]
**Description**

We have set up some OAuth Clients Kyma and would like to implement rate limiting based on the `client_id`. We were able to set up a [local rate limit](https://istio.io/latest/docs/tasks/policy-enforcement/rate-limit/#local-rate-limit). This limits the number of calls to the endpoint in general, for any `client_id`. We have tried to use an [Envoy RateLimitDescriptor](https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/common/ratelimit/v3/ratelimit.proto) as described:

```
["authenticated": "true"], ["client_id": "foo"]
```

> What it does: Limits all traffic for an authenticated client “foo”

However, we were not able to get this working.

**Expected result**

When making repeated calls to an authenticated endpoint with one `client_id` A, and the rate limit is exceeded, the endpoint should return `429 Too Many Requests`. If I now send a request to the same endpoint with a different `client_id` B, the endpoint should be accessible. 

**Actual result**

Instead, the call for `client_id` B also returns `429 Too Many Requests`, once A exceeds the limit.

**Steps to reproduce**

Create two oAuth Clients in Kyma, A and B. Create some API Rule with an access strategy oAuth. Configure the rate limiting as described in the Istio documentation. The rate limit will work as described in Actual Result. We have not been able to configure it based on `client_id`, either by using the Envoy RateLimitDescriptor (see link above) or any other means. Some guidance on how to configure this in our Kyma cluster would be great. 

obtain a token for client A:
```
curl --location --request POST '<cluster URL>/oauth2/token' \
--header 'Authorization: Basic <credentials for A>' \
--form 'grant_type="client_credentials"' \
--form 'scope="read write"'
```

obtain a token for client B:
```
curl --location --request POST '<cluster URL>/oauth2/token' \
--header 'Authorization: Basic <credentials for B>' \
--form 'grant_type="client_credentials"' \
--form 'scope="read"'
```

The endpoint with local rate limiting configured:
```
curl --location --request GET '<some endpoint of the API Rule>' \
--header 'Authorization: Bearer <token A or B>'

```
If you copy token A and make 10 or so calls in short succession, you will get a 429. We’d like to configure it so that with token B we can still make further requests (until those are exceeded).

Thanks!

**Comment by strekm** [comment]
@johanneseschrig thank you for reporting, unfortunately, i need to move this to the next milestone. atm we are busy delivering tasks for kyma 2.0

**Comment by piotrkpc** [comment]
Hi @johanneseschrig, thanks for reporting this issue.
Rate limiting functionality is not a part of Istio as Service Mesh. Istio merely provides low level `EnvoyFilter` CR to allow modification to Envoy configuration, hence we cannot recommend this approach in production unless user understands Envoy configuration very well.
Moreover we have noticed that there are unresolved issues when trying to enable rate limiting with mTLS.
Given the state of this functionality in Istio we cannot recommend solution right now.
Thanks.
