### ISSUE TITLE
Jaeger CRD containing invalid version field

### ISSUE THREAD

**Issue by tobiscr** [kyma-project/kyma#11738]
**Description**

During testing the installation using the reconciler, we were identifying a Kyma CRD which has an invalid `version` field inside.

**Expected result**

**Actual result**

When applying the CRD, the validation (tested over `kubectl` - see cli-version below) fails with following error:

Example CRD:

     apiVersion: apiextensions.k8s.io/v1
     kind: CustomResourceDefinition
     metadata:
       annotations:
         helm.sh/resource-policy: keep
       labels:
         app: jaeger-operator
         origin: kyma
       name: jaegers.jaegertracing.io
     spec:
       group: jaegertracing.io
       names:
         kind: Jaeger
         listKind: JaegerList
         plural: jaegers
         singular: jaeger
       scope: Namespaced
       version: v1.   #<<< FIELD INVALID
      ...etc.

`kubectl version`

     Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.15", GitCommit:"2adc8d7091e89b6e3ca8d048140618ec89b39369", GitTreeState:"clean", BuildDate:"2020-09-02T11:40:00Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"darwin/amd64"}
     Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.0+k3s1", GitCommit:"2705431d9645d128441c578309574cd262285ae6", GitTreeState:"clean", BuildDate:"2021-04-26T21:45:52Z", GoVersion:"go1.16.2", Compiler:"gc", Platform:"linux/amd64"}

`kubectl apply -f jaegers.jaegertracing.crd.yaml`

     error: error validating "jaegers.jaegertracing.crd.yaml": error validating data: ValidationError(CustomResourceDefinition.spec): unknown field "version" in io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1.CustomResourceDefinitionSpec; if you choose to ignore these errors, turn validation off with --validate=false

**Steps to reproduce**

Apply the CRDs with kubectl:

`kubectl apply -f <crdFile>`

**Troubleshooting**

**Comment by chrkl** [comment]
@tobiscr can we close this?
