### ISSUE TITLE
Don't use istio for apiserver calls

### ISSUE THREAD

**Issue by pbochynski** [kyma-project/kyma#11731]
**Description**
Exclude all Kyma controllers from sidecar injection. Istio-proxy should be enabled only for the components that handle application workload (data plane).

Tasks:
- [ ] disable default istio sidecar injection in kyma-system namespace

**Reasons**

Kyma controllers (kubernetes controllers in general) require stable connection to the k8s API server. The connection is already secured with the service account token and all the operations are tracked in the audit log. Adding istio-proxy sidecar doesn't bring the value in this case and can cause some instability (e.g. https://istio.io/latest/docs/ops/common-problems/injection/#automatic-sidecar-injection-fails-if-the-kubernetes-api-server-has-proxy-settings)

**Comment by strekm** [comment]
not valid anymore
