### ISSUE TITLE
Introduce Fast Integration Test for calling APIs secured in different ways through the Application Gateway

### ISSUE THREAD

**Issue by k15r** [kyma-project/kyma#11764]
**Description**
Call APIs secured in different ways through the Application Gateway:

**Acceptance criteria**
- [ ] OAuth
- [ ] Basic Auth

**Stretch**
- [ ] CSRF
- [ ] Using certificate

part of the `fast integration test`

**Envrionment**
```OSS```
```SKR```

**Comment by Disper** [comment]
A question for a small spike before we start
- [ ] Which authentications methods are available in commerce mock

**Comment by janmedrek** [comment]
Will be covered in: https://github.com/kyma-project/kyma/issues/13977
