### ISSUE TITLE
Provision, upgrading, deprovisioning the SKR via Provisioner's (KCP's) API

### ISSUE THREAD

**Issue by k15r** [kyma-project/kyma#11767]
**Description**

as part of the fast integration test, the following flow needs to be implemented

- Provisioning an SKR 
- upgrading shoot
- upgrading Kyma
- deprovisioning the SKR 

All of those steps should be done via Provisioner's (KCP's) API

Environment: 
```SKR```

**Comment by janmedrek** [comment]
Installation should not be covered in this test as it will be taken over by the reconciler.

**Comment by janmedrek** [comment]
Provisioner will be moved to the Reconciler.
