### ISSUE TITLE
Introduce Fast Integration Test for renewing and revoking a certificate

### ISSUE THREAD

**Issue by k15r** [kyma-project/kyma#11768]
**Description**

As part of `fast integration test` an applications certificate needs to be renewed and also be revoked

**Environment**
```OSS```

**Comment by Disper** [comment]
We've removed ```SKR``` environment as we're not trying to test compass.

**Comment by janmedrek** [comment]
we are removing the functionality from Kyma: https://github.com/kyma-project/kyma/issues/13718
