### ISSUE TITLE
Trigger Function via Secured API Rule

### ISSUE THREAD

**Issue by k15r** [kyma-project/kyma#11769]
**Description**

As part of the `fast integration test` a function needs to be exposed using an API Rule and then must be triggered using the exposed endpoint

**Environment**
```SKR```
```OSS```

**Attachments**
[how to setup a secured api rule](https://kyma-project.io/docs/2.0/components/api-gateway/#tutorials-expose-and-secure-a-service)

**Comment by strekm** [comment]
@kwiatekus i would have an additional requirement for this task. it would be super awesome if we could expose function in a secure way using apirule with oauth 2 test client. doing so we would cover ory stack in addition. Thank you!

**Comment by kwiatekus** [comment]
We need to add the outh client as part of the test fixture:
https://kyma-project.io/docs/components/api-gateway/#tutorials-expose-and-secure-a-service
