### ISSUE TITLE
Call old Application Gateway and the new Central Application Gateway via Function

### ISSUE THREAD

**Issue by k15r** [kyma-project/kyma#11765]
**Description**

Part of `fast integration test`

**Environment**
```SKR```
```OSS```

**Comment by janmedrek** [comment]
Tests are implemented, here are the two cases: https://github.com/kyma-project/kyma/blob/a134ba7d249f884b4e1c2b81653a0069f4cf5239/tests/fast-integration/test/fixtures/commerce-mock/index.js#L97
