### ISSUE TITLE
Create Architecture Documentation for Eventing Components

### ISSUE THREAD

**Issue by k15r** [kyma-project/kyma#11761]
**Description**
Create a architecture documentation for all eventing related components.

**Reason**
Documenting HOW our components work internally and WHY the approach was taken is crucial for speeding up future development.

**Acceptance**
- [ ] diagrams for all major flows in our components

---
<details>
    <summary>:warning: Funnel process - do not remove!</summary>
    </br>

Name|Value
:--- | :---
theme | Openness
business value | 0
technical value | 5
user value | 8
open-source value | 5
effort | 
requested by | 
</details>

**Comment by mfaizanse** [comment]
Who is the target audience for this documentation? end-user?
