### ISSUE TITLE
Create migration guide for Kyma 1.23 to 1.24

### ISSUE THREAD

**Issue by Gupta-Amrit** [kyma-project/kyma#11821]
**Description**
Create migration guide for Kyma 1.23 to 1.24 and mention manually steps that might be required to upgrade from 1.23 to 1.24.

**Area**
Kyma migration guide documentation

**Reasons**
Currently tag 1.24 is having still having migration guide from 1.22 to 1.23 which may impact the users who are planning to migrate from 1.23 to 1.24 without proper migration guide.

**Assignees**

@kyma-project/technical-writers

**Comment by majakurcius** [comment]
There are no migration steps required to upgrade from Kyma 1.23 to 1.24. 
The migration guide you're referring to is old (for 1.22 -> 1.23 upgrade) and should have been removed after the 1.23 release but was somehow omitted. 
Thank you for noticing this!

**Comment by majakurcius** [comment]
The migration guide has been removed from both `main` (#11848) and the `release-1.24` branch (#11851), so I'm closing the issue.
