### ISSUE TITLE
[Telemetry Operator] Initial monitoring and logging

### ISSUE THREAD

**Issue by skhalash** [kyma-project/kyma#11823]
**Description**

Set up simple monitoring for the new `telemetry operator` based on metrics exposed with the help of `kubebuilder` SDK.
Revise the existing `Kyma / Components / Controllers` Grafana dashboard and see if we can use it to monitor the operator.

**Reasons**

**Acceptance Criteria**

* Add a Grafana dashboard to have a quick overview of the operator most important metrics (reconciliation latency, reconciliation error rate, as well as Go runtime metrics)
* Investigate if there are any meaningful alerts we could add
* Think about integration of custom scenarios into the health prope
* Use agreed log framework having log severity configurable and logs are printed in json on production

**Attachments**

https://book-v1.book.kubebuilder.io/beyond_basics/controller_metrics.html
https://github.com/kyma-project/community/blob/main/concepts/observability-consistent-logging/improvement-of-log-messages-usability.md

**Comment by chrkl** [comment]
Logging was aligned to the Kyma standards (#13331), a Service and ServiceMonitor was added (#13252), a Grafana dashboard created to show controller runtime and resource specific metrics (#13252). Custom metrics have been added by PR #13397.

The other requested tasks (alerts and probes) cannot be addressed in a meaningful way with the current set of features in the operator.
