### ISSUE TITLE
Sort out Application Connector dependencies

### ISSUE THREAD

**Issue by franpog859** [kyma-project/kyma#11826]
**Context**

~~First thing:
Application Connector consists of a number of components. All of their charts you should find [there](https://github.com/kyma-project/kyma/tree/main/resources/application-connector/charts). What is more, I'd say that Compass Runtime Agent also is a part of the Application Connector as it takes some of the open-source Application Connector components' responsibility in the Compass mode. Anyway, these components are nicely structured in the mentioned [`resources/`](https://github.com/kyma-project/kyma/tree/main/resources/application-connector) directory but not so great in the [`components/`](https://github.com/kyma-project/kyma/tree/main/components) one~~ Moved to https://github.com/kyma-project/kyma/issues/12349

Second thing:
Application Connector chart cannot be installed on its own because it won't work. We didn't dig into it much deeper so I cannot say why. It shouldn't be that way in the world of microservices

**Problem**

~~We may consider moving all of the Application Connector components into one folder under the `components/` directory and build binaries using the same sources. **It'll make the code easier to reuse. It'll also speed up bumping libraries and fixing security vulnerabilities**~~

We also want to make Application Connector a really _microservicy_ bundle. So it could be installed and run without other microservices or using only their interfaces. **That's good for the testing purposes (will enable to test Application Connector in a fast manner), fast development process (as there are much fewer dependencies on other components) and maybe rolling updates in the future**

**Discussed solutions**
- ~~move all Application Connector components into one `components/application-connector/` directory, adjust the code sources, config files, jobs, tests, and so on. This addresses only the _first thing_~~ (moved to the other issue)
- investigate why Application Connector cannot be installed and run on its own and come up with a proposal on how to tackle it. This could be a first step to address the _second thing_

Feel free to take part in the discussion, propose another solution and create acceptance criteria below. We may also consider splitting up these two _things_ into two issues as they are not really super related

**Comment by franpog859** [comment]
I created a separate issue for [*the third thing*](https://github.com/kyma-project/kyma/issues/11826#issuecomment-949322012) just to keep it easy to track. [Here it is](https://github.com/kyma-project/kyma/issues/12575)

**Comment by janmedrek** [comment]
The obvious part is that Istio **is** a requirement we cannot get rid of. We want to make Application Connector independent of other Kyma components (Service Catalog, Eventing, etc.).

We can also think of separating the AC chart into istio and non-istio versions (as a follow-up).

**Comment by akgalwas** [comment]
It will be handles as a part of [#15826](https://github.com/kyma-project/kyma/issues/15826)
