### ISSUE TITLE
[Spike] Figure out a good structure for fast-integration tests

### ISSUE THREAD

**Issue by skhalash** [kyma-project/kyma#11825]
**Description**

**Reasons**

At the moment, fast-integration tests have no structure, which makes them hard to maintain. It's also unclear which guidelines to follow when adding a new test suite. The spike is about analyzing the pain points with fast-integration tests and presenting a possible solution, which will be broken down into follow-up tasks.

**Acceptance Criteria**

* Investigate how to make it possible to easily reuse test scenarios for install, upgrade tests for OSS and SKR Kyma
* Reduce the number of `make` targets by passing test scenarios, environment flags (compass+), etc. as parameters
* Investigate if we could use tags to solve the problems above
* Set up a linter https://github.com/kyma-project/kyma/issues/11370
* Improve directory structure
* Extract the `installer` module since it is not used by any tests
* Present the proposed solution to the team

**Attachments**

**Comment by elchead** [comment]
Should we have a linter? Currently style is not consistent

**Comment by Ressetkk** [comment]
Regarding test scenarios re-usability: Mocha tests work around one object that is passed between test cases. That means every test case has access to the fields under `this` directive, and those will be persistent around all child `describe()` and `it()` blocks. This thing is called *shared behaviours* and you can read more on the mocha's wiki. https://github.com/mochajs/mocha/wiki/Shared-Behaviours

Each set of tests can be defined as a function. Each tests retrieves the object to be tested using `this` directive. Let's say we have the following example the `foo` test will pass:
```js
function foo() {
  describe('foo', function () {
    it('foo', async function() {
      this.var.has.to.be.true;
    })
  })
}

describe('test-case', function () {
  before(async function() {
    this.var = true;
  })
  foo();
})
```
This approach should come in handy when re-using the tests are advised. Check my still-in-progress PRs that tackle this with the approach mentioned above #12514

**Comment by lindnerby** [comment]
Closing this, since we introduced the following changes:
* Reduce the number of make targets 
* Introduce a linter
* Improve encapsulation of tests and commerce-mock
* Remove installer module
Still ideas to improve: utils.js is unmaintainable due to size, commerce-mock is too complex and should be rather separated for various scenarios.
For remaining improvements teams themself are responsible
