### ISSUE TITLE
[Telemetry Operator] Make Fluent Bit mount custom configuration snippets

### ISSUE THREAD

**Issue by skhalash** [kyma-project/kyma#11824]
**Description**

The initial implementation of `telemetry-operator` (see #11663) generates config maps/secrets with Fluent Bit configuration snippets based on the `LoggingConfigurations` CRs, but they are not yet used by Fluent Bit, thus, having no effect at all. To make the operator usable we have to include the custom configurations into the main Fluent Bit configuration.

**Acceptance Criteria**

* Make Fluent Bit make use of config snippets generated for `LoggingConfiguration`
* The customers' configuration must not be reset during reconciliation, even though the central configuration might be overwritten at any time
* Implement an end-to-end test, which will prove that a custom configuration is picked up by Fluent Bit. The test does not have to be automated for now, manual execution would suffice

**Attachments**

Design docs: https://github.com/kyma-project/community/blob/main/internal/proposals/logs/dynamic-backend-configuration/custom-operator/dynamic-fluentbit-config.md

**Comment by elchead** [comment]
The mounting is achieved through the fluent-bit INCLUDE statement in the main configuration.
Fluent-bit is picky about including other file directories, so they need to be mounted in a subpath of the main config.

For this purpose, an initContainer was introduced which prepares all config files (with dynamic user settings) and shares this volume with the fluent-bit container.

A manual test was integrated under `fast-integration/telemetry-test` which configures an HTTP output plugin and sends the traffic to a mockserver.

The changes were merged in this PR:
https://github.com/kyma-project/kyma/pull/11901
