### ISSUE TITLE
Prometheus doesn't pick up logging alert rules

### ISSUE THREAD

**Issue by elchead** [kyma-project/kyma#11835]
**Description**

Currently, Prometheus doesn't pick up the rules from [fluent-bit](https://github.com/kyma-project/kyma/blob/afbb7b915d243d02e707def3680f69ecd8e8ecb7/resources/logging/charts/fluent-bit/templates/kyma-additions/fluent-bit.rules.yaml) and [loki](https://github.com/kyma-project/kyma/blob/afbb7b915d243d02e707def3680f69ecd8e8ecb7/resources/logging/charts/loki/templates/kyma-additions/loki.rules.yaml) (because it doesn't match the expected labels `app=monitoring, release=monitoring` as configured in the monitoring chart:
https://github.com/kyma-project/kyma/blob/33d08542b2338beb7a836200f855ac71891abc21/resources/monitoring/templates/prometheus/prometheus.yaml#L189

The possible solutions are:

1. add the labels to the rules (but somehow unintuitive to have monitoring in the logging chart)
2. empty the ruleSelector (no label rules)
3. rename the expected labels from monitoring to something more generic

**Tests**
We should add a test to check if there are prometheus rules (kubectl) that are not registered in prometheus.
E.g.:
` kubectl get prometheusrules.monitoring.coreos.com` 
and then query prometheus if the resources got applied

**Comment by elchead** [comment]
As discussed with @a-thaler, the ruleSelector is emptied to match for all rules.
The test adds a new rule in a new namespace and verifies that all prometheusrules are applied

**Comment by shorim** [comment]
After discussion with @a-thaler and @skhalash, we have decided that the test will check only that the pre-defined rules are picked up by Prometheus, but no need to add a new rule in a new namespace.
