### ISSUE TITLE
[multiple domains] Troubleshooting guide for dns related issues

### ISSUE THREAD

**Issue by strekm** [kyma-project/kyma#11849]
**Description**

Create a troubleshooting guide for dealing with gardener dns-management resources like DNSEntry & DNSProvider.

**Area**

* API Gateway

**Reasons**

User following step by step guide on how to expose workload under given domain can face issues around DNS management: e.g. misconfiguration of DNSProvider or DNSEntry CR. This guide should cover most common cases. 

**Assignees**

@kyma-project/technical-writers

**Attachments**

part of: https://github.com/kyma-project/kyma/issues/11839
depends on: https://github.com/kyma-project/kyma/issues/11828

**Comment by strekm** [comment]
Examples:
- referenced secret in DNSProvider doesn't exist
- invalid credentials
- invalid ingressgateway IP

**Comment by Tomasz-Smelcerz-SAP** [comment]
- gardener annotations on a not-gardener cluster (e.g. GKE) -> resource is ignored by the controller
