### ISSUE TITLE
Canary upgrades for Istio

### ISSUE THREAD

**Issue by pbochynski** [kyma-project/kyma#11842]
**Description**

Istio upgrades should not cause customer workload downtimes.
Acceptance criteria:
- [ ] istio is upgraded in phases (precheck, install the new revision, migrate namespaces with istio-injection to the new revision, uninstall old revision)
- [ ] upgrade test is provided that proves that no downtime is observed during upgrade (monitoring sample workload during upgrade process)

**Reasons**

Istio upgrades have an impact on customer workload. Istio provides tools for [canary upgrades](https://istio.io/latest/docs/setup/upgrade/canary) - install the new version, use it with a small percentage of the workloads, before migrating all of the traffic to the new version. 

---
<details>
    <summary>:warning: Funnel process - do not remove!</summary>
    </br>

Name|Value
:--- | :---
theme | Enterprise-grade
business value | 8
technical value | 2
user value | 10
open-source value | 5
effort | 
requested by | 
</details>

**Comment by loewenstein** [comment]
So, currently, the Istio update **does lead to downtimes**?

**Comment by pbochynski** [comment]
I still believe it is needed.

**Comment by strekm** [comment]
Canary upgrades of Istio was considered as supporting of zero downtime upgrade of Istio. Zero downtime upgrade is resolved by supporting configuration of Istio (production setting for managed Kyma offering). Each release of Istio module is also tested if upgrade is zero downtime.
