### ISSUE TITLE
Clean up the Central Application Connectivity fast integration tests

### ISSUE THREAD

**Issue by franpog859** [kyma-project/kyma#11870]
**Context**

Some time ago we [enabled the Central Application Connectivity components by default](https://github.com/kyma-project/kyma/pull/11830). Before that, we introduced [two new prow pipelines](https://github.com/kyma-project/test-infra/pull/3581) to test the central components there, before making them the default option ([here we adapted them to also test the Central Application Connectivity Validator](https://github.com/kyma-project/test-infra/pull/3905)). Keep also in mind that whereas right now there is no Application Connectivity Validator per Application present by default, the old Application Gateway is still there (to provide backward compatibility)

**Problem**

The central components are enabled by default so there is no need to keep the additional jobs running. Adjust the fast-integration suits so they test the central components by default. Right now there could be a case that Kyma is installed with the central components (as they are installed by default and do not need any overrides) but the suites are testing the old components (that are no longer here) because of a lack of the `WITH_CENTRAL_APP_CONNECTIVITY=true`. There could be more potential issues and we should clean this mess 

**Discussed solutions**
- 1. Remove `*-k3s-central-app-connectivity*` jobs from the Prow. Refactor fast-integration suites so they look like they have always `WITH_CENTRAL_APP_CONNECTIVITY=true`. Check what needs to be done to enable [the `Getting Started Guide test`](https://github.com/kyma-project/kyma/blob/main/tests/fast-integration/test/3-getting-started-guides.js#L15-L18) and do it (it should not be a super huge thing)
  2. ~~Check what needs to be done to check both Central Application Gateway and the old Application Gateway (as they are still both present) and do it (there probably should be the second lambda created and checked or the previous should be changed after the first test to use new Gateway URL) (and that could be a little bit larger in terms of the implementation)~~
- Remove [the Application Connectivity Validator check](https://github.com/kyma-project/kyma/blob/main/tests/fast-integration/test/fixtures/commerce-mock/index.js#L292) in the Commerce Mock + Compass scenario and hope for the best (I think that's quite a short term solution though)

Feel free to take part in the discussion, propose another solution and create acceptance criteria below

**Comment by Disper** [comment]
@kyma-project/framefrog  on our side we will have to do 
> Check what needs to be done to check both Central Application Gateway and the old Application Gateway (as they are still both present) and do it (there probably should be the second lambda created and checked or the previous should be changed after the first test to use new Gateway URL) (and that could be a little bit larger in terms of the implementation)

**Comment by franpog859** [comment]
It came up not to be that easy. After implementing the first part of the acceptance criteria we got a bug ([see the issue](https://github.com/kyma-project/kyma/issues/12071)). Current idea is to wait till Kyma 2.0 is the default SKR version and then do the cleaning of fast-integration tests (so probably on our side we'll do the whole issue then, @Disper). If you have other ideas or concerns, join the discussion!

**Comment by janmedrek** [comment]
We've decided to put in on freeze until we have changes introduced in https://github.com/kyma-project/kyma/issues/12845 present on the main branch.

**Comment by janmedrek** [comment]
Tackled in: https://github.com/kyma-project/kyma/issues/13977
