### ISSUE TITLE
Update API Gateway documentation

### ISSUE THREAD

**Issue by derberg** [kyma-project/kyma#1188]
**Description**

- explain that security will not work if my application doesn't have a side-car injected
- CRD ref doc doesn't say anything about the CRD `status`. Is the underlying controller saying something like `securing your application doesn't work`?

**Reasons**

It is not clear in the Docs, also in UI, what I need to do first with my application to make sure it can actually be exposed in a secure way

**Comment by sjanota** [comment]
@derberg 
First point you mentioned is addressed by #1414 .
Answer to second one: there is no additional information in status right now. We have a ticket to make it more user-friendly: #470.

**Comment by derberg** [comment]
@sjanota then just update #470 to make sure it will not cover implementation but documentation update as well and then you can close this one

**Comment by piotrmsc** [comment]
Please update docu by describing whole status object in the CRD (VirtualService status and AuthenPolicy status)
