### ISSUE TITLE
Installing Kyma on AKS - fetching of service principal

### ISSUE THREAD

**Issue by lechnerc77** [kyma-project/kyma#11904]
**Description**

The documentation for fetching the service principal to provision a Kyma cluster on AKS is referencing the official Microsoft documentation which makes it unnecessarily hard for a user to provision the cluster via the Kyma CLI that is using Terraform under the hood.

A link to the Terraform documentation for this scenario would be more helpful and would give better guidance to the user.

**Area**

- Installation of Kyma on AKS

**Reasons**

The link provided in the section for installing [Kyma on AKS](https://kyma-project.io/docs/#installation-install-kyma-on-a-cluster-prepare-the-cluster) i.e. for fetching the service principal to AKS points to [https://docs.microsoft.com/en-us/azure/aks/kubernetes-service-principal#manually-create-a-service-principal](https://docs.microsoft.com/en-us/azure/aks/kubernetes-service-principal#manually-create-a-service-principal). 

This is _per se_ not wrong but not very helpful for the further installation procedure as the user must find out the parameters by himself. 

It would be a big improvement imho if the reference would point to the corresponding section in the Terraform documentation namely to [https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/guides/service_principal_client_secret](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/guides/service_principal_client_secret) that clearly explains the commands needed for the service principal

**Assignees**

@kyma-project/technical-writers

**Attachments**

none

**Comment by pbochynski** [comment]
We are in the process of removing provision commands from Kyma CLI. In this case azure cli would be better choice. I mean we are not going to invest in this area any more as Kyma can be installed on any k8s cluster.
