### ISSUE TITLE
Installation of Kyma - Link to yaml for additional privileges

### ISSUE THREAD

**Issue by lechnerc77** [kyma-project/kyma#11905]
**Description**

When installing Kyma on a AKS cluster the parameter of the Kyma release version (see <https://kyma-project.io/docs/#installation-install-kyma-on-a-cluster-choose-the-release-to-install>) is not fitting the URL used later for adding additional privileges to be able to access readiness probes endpoints on your AKS cluster (see <https://kyma-project.io/docs/#installation-install-kyma-on-a-cluster-prepare-the-cluster> -> step 5) or at least the structure is not obvious. 

**Area**

- Installation Kyma on AKS

**Reasons**

As no further restrictions are made the assumption is that the Kyma version is the one from the GitHub releases like "1.24".
However the execution the command shown in the documentation to apply additional privileges (see <https://kyma-project.io/docs/#installation-install-kyma-on-a-cluster-prepare-the-cluster> -> step 5) will fail as the the path to the right yaml is not

_ ... /kyma-project/kyma/**1.24**/installation/resources/azure-crb-for-healthz.yaml _

but

_ ... /kyma-project/kyma/**release-1.24**/installation/resources/azure-crb-for-healthz.yaml _

In addition only major and minor releases are taken into account for this reference.

However, for the later installation the exported version in the form 1.24.x works as expected (see doc <https://kyma-project.io/docs/#installation-install-kyma-on-a-cluster-install-kyma>)

Proposal would be to clearly state the expected structure of the release version for each command and adopt the export commands.

**Assignees**

@kyma-project/technical-writers

**Attachments**

none

**Comment by NHingerl** [comment]
Documentation will be updated for the next release.
