### ISSUE TITLE
Update the location of the Azure Service Classes images

### ISSUE THREAD

**Issue by kazydek** [kyma-project/kyma#1191]
**Description**

Update the location of the Azure Service Classes images in the `azure-service-classes-docu.yaml` file to reflect the current  setup (`develop/` dir):
https://github.com/kyma-project/kyma/blob/master/resources/core/charts/azure-broker/templates/azure-service-classes-docu.yaml#L20
https://github.com/kyma-project/kyma/blob/master/resources/core/charts/azure-broker/templates/azure-service-classes-docu.yaml#L27
https://github.com/kyma-project/kyma/blob/master/resources/core/charts/azure-broker/templates/azure-service-classes-docu.yaml#L34

**Comment by jasiu001** [comment]
All images work. Azure repository was fixed.
