### ISSUE TITLE
Error in Istio configuration of Central Application Connectivity Validator component 

### ISSUE THREAD

**Issue by koala7659** [kyma-project/kyma#11913]
**Description**

There is an apparent problem with Istio configuration of VirtualService of the central-application-connectivity-validator component. We can observe some warnings during installation and then errors reported by istioctl analyze tool. More details below.

Technical details:
- Kyma version: **installed from main** (the date is 19 august 2021)
- Kubernetes version **1.21.3**
- Istio version: **1.10.2**
- Kyma installation type: **Kyma OS**
- Cluster type: Azure, installed on Gardener

**Expected result**

The referenced gateway for VirtualService central-application-connectivity-validator.kyma-system is provided.
No warning about central-application-connectivity-validator is logged during installation.
The tool istioctl analyze does not report any errors.

**Actual result**

Following warning is logged during installation:

`Legacy gatewayName format "kyma-gateway-application-connector.kyma-system.svc.cluster.local"; prefer the <namespace>/<name> format: "kyma-system/kyma-gateway-application-connector"
`

Following errors and warnings are logged while running istioctl analyze tool:

```
Error [IST0101] (VirtualService central-application-connectivity-validator.kyma-system) Referenced gateway not found: "kyma-gateway-application-connector.kyma-system.svc.cluster.local"
Warning [IST0132] (VirtualService central-application-connectivity-validator.kyma-system) one or more host [gateway.pg1.frog-dev.shoot.canary.k8s-hana.ondemand.com] defined in VirtualService kyma-system/central-application-connectivity-validator not found in Gateway kyma-system/kyma-gateway-application-connector.kyma-system.svc.cluster.local.
Warning [IST0133] (VirtualService central-application-connectivity-validator.kyma-system) Schema validation warning: using legacy gatewayName format "kyma-gateway-application-connector.kyma-system.svc.cluster.local"; prefer the <namespace>/<name> format: "kyma-system/kyma-gateway-application-connector" 
```

**Steps to reproduce**

- Create empty Kubernetes cluster on Gardener
- install Kyma latest version from main
- run istioctl analyze tool

**Troubleshooting**

This problem can be probably fixed manually by editing Istio resources, but the best way is to fix in the Kyma source code.

**Comment by janmedrek** [comment]
Solved by: https://github.com/kyma-project/kyma/pull/13061
