### ISSUE TITLE
Prepare Istio test flow for Kyma 2.0

### ISSUE THREAD

**Issue by cnvergence** [kyma-project/kyma#11944]
**Description**

As a followup to [11702](https://github.com/kyma-project/kyma/pull/11702), we need to move and refactor old Istio tests for Kyma 2.0.
They should be run in the existing prow integration and upgrade jobs. 

**Reasons**

**Attachments**

**Comment by strekm** [comment]
https://github.com/kyma-project/kyma/blob/release-1.24/resources/istio/files/istio-kyma-validate-test.sh

**Comment by dariusztutaj** [comment]
Closing: testing strategy will be changed because of modularization.
