### ISSUE TITLE
Disabling SSL certificate verification per Application with Central App Gateway

### ISSUE THREAD

**Issue by majakurcius** [kyma-project/kyma#11946]
**Description**

With the introduction of Central Application Gateway, disabling SSL certificate verification disables it for all Applications. 
We need to fix it so that we can disable it for a specific Application. 

**Expected result**

Disabling SSL certificate verification disables it for a specific Application.

**Actual result**

Disabling SSL certificate verification disables it for all Applications.

**Steps to reproduce**

Follow [this](https://kyma-project.io/docs/components/application-connector/#details-security-disable-ssl-certificate-verification) guide.

**Reasons**

User should be able to disable the SSL certificate verification for a specific Application. 

**Acceptance Criteria**

- [ ] Disabling SSL verification in Application Connector 2.0 disables it for a specific Application, not all Applications
- [ ] Documentation updated:
    - [x] [guide](https://kyma-project.io/docs/components/application-connector/#details-security-disable-ssl-certificate-verification) ([2.0](https://kyma-2-0-docu--kyma-project-docs-preview.netlify.app/docs/kyma/preview/03-tutorials/00-application-connectivity/ac-14-disable-ssl-certificate-verification/))
    - [x] [Application CR](https://kyma-project.io/docs/components/application-connector/#custom-resource-application) [(2.0)](https://kyma-2-0-docu--kyma-project-docs-preview.netlify.app/docs/kyma/preview/05-technical-reference/06-custom-resources/ac-01-application/)

**Comment by majakurcius** [comment]
Application CR must be extended and say whether verification for this App should be done.

**Comment by koala7659** [comment]
Plan for implementation 

- Extending Application CR with new `skipVerify` flag
-  Central Application Gateway. Processing `SkipVerify` flag from Application CR to create proxy cache entry for each API. Removing old parameter from configuration.
-  Compass Runtime Agent. New configuration parameter to setup the value of `skipVerify` flag for each created Application CR from Director
- Application Registry. Ensure `skipVerify` flag is set to false for each created Application CR

**Comment by franpog859** [comment]
The [PR](https://github.com/kyma-project/kyma/pull/12257) is currently in the review process. The [documentation](https://github.com/kyma-project/kyma/pull/12840) is ready to be merged

**Comment by franpog859** [comment]
The [implementation](https://github.com/kyma-project/kyma/pull/12257) and the [documentation](https://github.com/kyma-project/kyma/pull/12840) are merged
