### ISSUE TITLE
Make BEB-Eventing more EventMesh friendly during Kyma upgrade

### ISSUE THREAD

**Issue by ghost** [kyma-project/kyma#11988]
**Description**

In order to minimize the failing calls of delivering messages to webhooks during the Kyma upgrade, the BEB subscriptions should first be "paused". After that, the Kyma upgrade process should be started and at the end, the BEB subscriptions should be "resumed". After resuming them, BEB will start to send messages again.
BEB continues to receive messages for a "paused" subscription, saving them in the EMS queue associated with the subscription. After a subscription is "resumed" BEB sends all queued messages to webhook, so no messages will be lost.

**Reasons**
It should avoid the failing of messages delivered during Kyma upgrade.

**Attachments**

**Comment by k15r** [comment]
Flow:

1. in the kyma reconciler: in the preaction: stop all subscriptions
2. upgrade eventing
3. in kyma reconciler: in the post action: resume all subscriptions

**Comment by nachtmaar** [comment]
This is how you can pause a subscription:

```go
// source: https://github.com/kyma-project/kyma/blob/main/components/eventing-controller/pkg/ems/api/events/client/client.go#L201

func (c Client) UpdateState(name string, state types.State) (*types.UpdateStateResponse, error) {
    req, err := c.client.NewRequest(http.MethodPut, fmt.Sprintf(UpdateStateURLFormat, name), state)

type State struct {
	Action StateAction `json:"action,omitempty"`
}

type StateAction string

const (
	StateActionPause  StateAction = "pause"
	StateActionResume StateAction = "resume"
)

```
