### ISSUE TITLE
Nats recommends not to use the Operator for new deployments anymore

### ISSUE THREAD

**Issue by johgoe** [kyma-project/kyma#11982]
Nats recommends not to use the Operator for new deployments anymore

See https://github.com/nats-io/nats-operator/pull/329

Is it possible to switch from operator to a helm installation of nats?

**Comment by k15r** [comment]
Thanks for the heads up. We will check if we can use the helm charts in kyma.

**Comment by k15r** [comment]
Possible future solutions for deploying the in-cluster nats instance will be evaluated here: https://github.com/kyma-project/kyma/issues/12137
