### ISSUE TITLE
Event delivery for NATS is broken with multiple subscriptions

### ISSUE THREAD

**Issue by marcobebway** [kyma-project/kyma#11989]
**Description**

Not all Event subscribers receive Events when NATS is used as the Eventing backend.

**Steps to reproduce**

Can be reproduced from Kyma main branch (for example this [commit](https://github.com/kyma-project/kyma/commit/0cd4d2c7ad12ca9b5983e81d3d36a92c2048519b))

1. Install Kyma.
2. Make sure NATS is the default Eventing backend.
3. Create more than one function/subscriber with different sinks but all interested in the same EventType.
4. Publish one Event with the EventType mentioned above.
5. Check logs not all functions/subscribers receive the Event.

**Troubleshooting**

- Check Eventing controller logs, only one dispatch call is made to one of the subscribers.
- All created Kyma subscriptions should be ready.

**Comment by radufa** [comment]
We have manually tested it during the tests of https://github.com/kyma-project/kyma/issues/11719 using Kyma 1.24.2 for OSS and 1.24.0 for SKR.
It seems that "main" is dirty now

**Comment by radufa** [comment]
This issue is related to https://github.com/kyma-project/kyma/issues/11719

**Comment by radufa** [comment]
Tested with Kyma 1.24.3 on SKR. It's working as expected. 
We should focus on "main" to fix it.
