### ISSUE TITLE
Direct links to documentation do not work at https://kyma-project.io/docs

### ISSUE THREAD

**Issue by pbochynski** [kyma-project/kyma#1199]
**Description**

If you paste this url in the browser you will get 404 page:
https://kyma-project.io/docs/latest/root/kyma#getting-started-local-kyma-installation
In the result links from github are broken.

**Expected result**
Documentation page should be rendered

**Actual result**
404 page is rendered 

**Steps to reproduce**

Go to https://kyma-project.io/docs
Open any link on the left-hand side. The URL in the browser will change to something like:
https://kyma-project.io/docs/latest/root/kyma#getting-started-local-kyma-installation

Now click on the address bar and press enter. The result will be *Page not found.*

**Comment by akucharska** [comment]
This is not a problem with kyma-project website but with a slow internet connection. 
You can also try to clear cache.
