### ISSUE TITLE
Gateway URL present in the Application CustomResource

### ISSUE THREAD

**Issue by janmedrek** [kyma-project/kyma#11999]
**Description**

Application Gateway right now supports preconstructed URLs, while creating them up-front is quite easy it would be helpful to also include those in the Application CR.

**Reasons**

We want a simple design and contract between our internal components. This also makes all automation easier as there is no need for hardcoding URLs in UIs or Services that create Applications on the run.

**Acceptance Criteria**
- [ ] GatewayURL for each service is also saved in the Application CR

**Comment by ralikio** [comment]
Work must be done in the area of compass-runtime-agent and/or application-registry. App name "Uniqueness" does not have anything to do with the current issue.

**Comment by koala7659** [comment]
Here is PR with a draft of our design document https://github.tools.sap/framefrog/documentation/pull/32
