### ISSUE TITLE
[Configurable Logging] Adjust logging chart to work with telemetry chart

### ISSUE THREAD

**Issue by a-thaler** [kyma-project/kyma#12029]
**Description**
The `telemetry` component will contain the new base observability feature (the configurable agents) of kyma and will work on it's own.

Additional the current `logging` chart can be installed, bringing the optional in-cluster logging backend aka Loki. For now you also would need to install `monitoring` to get Grafana as a UI.

Goal: Assure that the logging and monitoring component can be installed optional to the telemetry component, so that only the fluent-bit installation of the `telemetry` chart is active and `Loki` will integrate out of the box with it as one possible backend.

**Reasons**
The `logging` and `monitoring` will for now contain the optional backends and must integrate from the beginning well with the new `telemetry` component

**Criterias**
- Have a feature flag to enable the integration mode with the telemetry chart
- when enabled, the old fluent-bit config located in logging chart is disabled fully
- when enabled, loki gets integrated via the new telemetry CRDs only (located in logging chart)
- when disabled, the new telemetry components may startup but are not used by the backends will not have any effect
- There is a migration script available to cleanup old fluent-bit instances on the cluster, or a no-op config gets generated so that the instances have no effect anymore
- Dependent features like prom alerting can handle both situations or is also configured via the new flag
- Assure that the existing logging functionality is tested in an automated way

**Comment by chrkl** [comment]
PR #13729 makes the following changes to address this:
* Add a LogPipeline with a Loki output to the logging chart and a Helm value to enable it
* The LogPipeline CRD is installed using the regular reconciling mechanism to avoid any dependencies between the logging and telemetry chart
* Fluent Bit settings in the telemetry chart have been aligned with the logging chart
* A ServiceMonitor for the telemetry-fluent-bit DaemonSet has been set up
* The telemetry fast-integration test was modified to test E2E Loki integration
* Necessary steps to activate and roll-back the Loki integration have been documented
