### ISSUE TITLE
[CLI Reconciler] Support for all sources

### ISSUE THREAD

**Issue by a-thaler** [kyma-project/kyma#12037]
Goal: "kyma deploy --source" should work as in the old command, especially from local sources

Assure that installing from main branch will check the revision in local workspace and assure that it gets overriden if upstream revision is changed.

**Comment by jeremyharisch** [comment]
We need to wait merging [the corresponding PR](https://github.com/kyma-incubator/reconciler/pull/180) until the PR regarding [supporting private repos](https://github.com/kyma-incubator/reconciler/pull/125) is merged.

**Comment by rakesh-garimella** [comment]
The source flag has been added and supports the same features like the `deploy` command
