### ISSUE TITLE
Function not triggered from events sent via curl

### ISSUE THREAD

**Issue by shreyasdn** [kyma-project/kyma#12035]
hi experts 
I have created all the necessary bindings in kyma and am able to see the event created and bound via service to function in a namespace. However when i call the event using curl i am  unable to see any logs in my function and nor see any failure response. I get a response like
{"event-id":"xxxxxx-xxxx-xxx-xxx-xxxxxxx","status":"","reason":""}

I have used a hosted sap btp account with kyma provisioned. I am unable to understand why the event is not triggering the function. I am using kyma 1.24.2 version. 

How can i verify that the function is called successfully?

**Comment by k15r** [comment]
Hello,

we would like to help you. But to do this we need a bit more information:
- how does your curl command look like
- how did you configure your subscription

**Comment by shreyasdn** [comment]
hi,
     I have configured my subscription via the UI by adding a event-subscription in the configuration tab for the function i have created. 
<img width="894" alt="Screen Shot 2021-09-06 at 1 18 15 PM" src="https://user-images.githubusercontent.com/6490281/132180115-aa90f731-ad8f-4b4e-9502-d343e451c707.png">


The curl command i use is below
```curl -X POST --key generated.key --cert clientCrtDecoded.crt https://gateway.url/v1/events --header "Content-Type: application/json" --data '{"event-type":"event-type","abc.acc.c.c.c.v1":"xxxxxx-xxx-xxx-xxxxx","event-type-version":"v1","event-time":"2021-09-03T13:54:00Z","data":{"billing":{"count":200}}}'```. 

I have verified each and every entry in the curl command and also the url.

I was going over a few tutorials and saw that some of them create an event trigger. Is this necessary in my case?

**Comment by k15r** [comment]
The event that you send seems a bit off:
```yaml
{
"event-type":"event-type",
"abc.acc.c.c.c.v1":"xxxxxx-xxx-xxx-xxxxx",
"event-type-version":"v1",
"event-time":"2021-09-03T13:54:00Z",
"data": {
  "billing": {
    "count":200
  }
}
}
```

it should be something like:
```yaml
{
"event-type":"abc.acc.c.c.c.v1",
"event-id":"xxxxxx-xxx-xxx-xxxxx",
"event-type-version":"v1",
"event-time":"2021-09-03T13:54:00Z",
"data": {
  "billing": {
    "count":200
  }
}
}

**Comment by k15r** [comment]
I hope fixing the event data section fixed your issue. In case the issue still exists please don't hesitate to reopen this issue / open a new issue.
