### ISSUE TITLE
Log the communication requests between eventing and BEB

### ISSUE THREAD

**Issue by radufa** [kyma-project/kyma#12032]
**Description**

Having a "log" file with the dump of all REST requests sent to BEB is necessary for the errors analysis  of the communication with BEB.
Reproducing an issue using manually created REST requests (for ex. using Insomnia) is very time consuming and it cannot be done in all cases (for ex. for issues which appears only under load)

**Reasons**

**Attachments**

**Comment by k15r** [comment]
Closing for now, we will create a new issue if we see more value in implementing
