### ISSUE TITLE
Throttle log shipment to loki

### ISSUE THREAD

**Issue by a-thaler** [kyma-project/kyma#12030]
**Description**

The batteries-included-like setup of loki within Kyma is a non-scalable setup and with that will have it's limit in regards to scalability.
In order to protect the loki instance of getting instable, the throughput of log shipment should be throttled with a configurable value.

Goal: Have a meaningful default in place, document it and alert on it

- Make some performance test and come up with a meaningful default for a ingestion rate limit
- Assure that the storage size fits to the limit in combination with the retention time
- Prove that limit by checking real clusters
- Introduce the limit and have it configurable
- Document it
- Introduce an alert when reaching the limit

**Reasons**

**Attachments**

**Comment by chrkl** [comment]
Update for docs missing

**Comment by chrkl** [comment]
A generic alert for a filling up PVC is already in place (KubePersistentVolumeFillingUp). No specific alert required for the Loki PVC.
