### ISSUE TITLE
Redeploying functions after getting request

### ISSUE THREAD

**Issue by mwisnia97** [kyma-project/kyma#12048]
**Description**
After request an function, it is redeploying sometimes without any error and it does not depend on high availability.

Kyma version: 1.24.4
Chart Versions: 0.14.4
Kubernetes version: 1.18.20
Kyma-showcase commit version: 4a5e6f376b569d450b6f63258771af97abcc8cd5

**Expected result**
Serverless functions are not redeploying.

**Actual result**
After posting an image, serverless functions are redeploying without an error.

**Steps to reproduce**
- Apply  [kyma-showcase project](https://github.com/kyma-incubator/Kyma-Showcase)
- Upload an [image](https://cdn.cnn.com/cnnnext/dam/assets/160122124623-01-national-handwriting-day.jpg) and POST it 

**Troubleshooting**
This bug is nondeterministic, you need to retry posting images a couple of times.
To monitor function deploying: ```kubectl get function -w```

**Comment by kwiatekus** [comment]
There is a problem with probes configuration that makes it hard to distinguish between states when container is busy and when it's dead and needs to be restarted.
We will fix that and track progress under this issue : https://github.com/kyma-project/kyma/issues/12005
@mwisnia97 Please track the linked issue
