### ISSUE TITLE
[CLI Reconciler] UX - support logging as in old command

### ISSUE THREAD

**Issue by a-thaler** [kyma-project/kyma#12040]
Goal: Use of kyma deploy command will see only relevant informations. Here basic success infos are important and transparent info on failures with quick summary of the problem is relevant. The verbose flag should enable all logs.

**Comment by skhalash** [comment]
#Summary

* Non-verbose mode - very basic implementation, every time the installation status of a component changes, a new line is getting appended. No internal logs are printed.
* Verbose mode - reconciler logs are printed in a structured format
