### ISSUE TITLE
Fast-integration test pipelines fail on deployment of central-application-gateway

### ISSUE THREAD

**Issue by cnvergence** [kyma-project/kyma#12071]
**Description**
The pipeline fails on fast-integration tests with the error:
```
  Upgrade test preparation
Error: Waiting for deployment central-application-gateway timeout (90000 ms)
    at Timeout._onTimeout (/home/prow/go/src/github.com/kyma-project/kyma/tests/fast-integration/utils/index.js:380:18)
    at listOnTimeout (internal/timers.js:557:17)
    at processTimers (internal/timers.js:500:7)
    1) CommerceMock test fixture should be ready
    ✓ Helm Broker test fixture should be ready (34567ms)


  1 passing (5m)
  1 failing

  1) Upgrade test preparation
       CommerceMock test fixture should be ready:
     Error: Waiting for deployment central-application-gateway timeout (90000 ms)
      at Timeout._onTimeout (utils/index.js:380:18)
      at listOnTimeout (internal/timers.js:557:17)
      at processTimers (internal/timers.js:500:7)
```

**Expected result**

Pipeline works

**Actual result**
Pipeline does not work

**Steps to reproduce**

**Links**

https://status.build.kyma-project.io/view/gs/kyma-prow-logs/logs/kyma-upgrade-gardener-kyma-to-kyma2/1435271788148822016
https://status.build.kyma-project.io/view/gs/kyma-prow-logs/logs/kyma-upgrade-gardener-kyma-to-kyma2/1435271788148822016
https://status.build.kyma-project.io/view/gs/kyma-prow-logs/logs/skr-azure-lite-integration-dev/1435771334989713408
https://status.build.kyma-project.io/view/gs/kyma-prow-logs/logs/skr-trial-integration-dev/1435665637434200064

**Comment by franpog859** [comment]
Pipeline `kyma-upgrade-gardener-kyma-to-kyma2` in `prow/scripts/lib/gardener/azure.sh` (or `gcp.sh` or `aws.sh`) script installs Kyma in version 1.24.X which has [Central Application Connectivity components disabled by default](https://github.com/kyma-project/kyma/blob/release-1.24/resources/application-connector/values.yaml). After that, it runs `make ci-pre-upgrade` which waits for the Central Application Gateway while `ensureCommerceMockLocalTestFixture(...` in `tests/fast-integration/upgrade-test/upgrade-test-prep.js` script. It's not there and it fails on timeout. Kyma 1.24.X should not be tested with the default fast integration flow as it requires Central Application Connectivity components

Pipeline `skr-azure-lite-integration-dev` or `skr-trial-integration-dev` test the SKR fast integration flow. In this case, I'm not 100% sure but it's my best guess. To provision, the test SKR pipelines use KEB and Provisioner od DEV environment. Current components cannot provision Kyma in version 2.0 so I assume that they provision it in some previous version. Kyma versions before 2.0 have Central Application Connectivity components disabled by default so there is no Central Application Gateway installed. Pipeline tests Kyma by running `make ci-skr` which also waits for the Central Application Gateway while `ensureCommerceMockWithCompassTestFixture(...` in `tests/fast-integration/skr-test/skr-test.js` script. Kyma prior to 2.0 version should not be tested with the default fast integration flow as there is no Central Application Connectivity component enabled

@lindnerby , may I ask you to take a look at that? These problems may be related to the refactoring you worked on. I mean for example [this PR](https://github.com/kyma-project/kyma/pull/11935/files) or [this one](https://github.com/kyma-project/test-infra/pull/4065/files)

**Comment by franpog859** [comment]
I'm on it

**Comment by franpog859** [comment]
I merged two PRs ([Kyma PR](https://github.com/kyma-project/kyma/pull/12116) and [TestInfra PR](https://github.com/kyma-project/test-infra/pull/4144)) that revert the problematic changes. I'm closing this issue. Please, reopen it if the problem occurs in the future
