### ISSUE TITLE
Investigate and enable multi-line and containerd support with fluent-bit

### ISSUE THREAD

**Issue by a-thaler** [kyma-project/kyma#12118]
**Description**
Now after the upgrade to [fluent-bit 1.8](https://github.com/kyma-project/kyma/issues/10582), the new multi-line feature is available and should be activated. It will simplify the configuration of the typical parsers for the different application scenarios.

Goal: Enable the new feature and provide a setup which allows an easy enablement for an application written in a specific programming language

Criterias:
- Logs are getting parsed proper on the different container runtimes, mainly docker, containerd and general cri
- Investigate if multi-line logs will work for all kind of applications when running on containerd/cri. It looks like there is a generic mechanism available as every log line has an entry indicating if it is a partial or final line. If yes, focus on the containerd/cri setup only
- If not, describe how a custom parser can be activated for your application so that multi-line logs are kept within a single log entry

**Reasons**
With the general move to containerd we need to support both runtimes for a while in a transparent way
Multi-line logs are hard to read when using dedicated log backends. Combining multi-lines back into one line will heavily increase the debug experience.

**Attachments**

**Comment by a-thaler** [comment]
I tested the new multiline feature on docker and containerd based environments and it worked very well. Logs are parsed proper in both environments while the containerd support was not working before.
So I created a PR to enable that by default, adding with that support for containerd.

Furthermore I tested multiline support for an sample app throwing a java based stacktrace. Specifying an multiline filter for the logs of my app referencing the built-in java parser worked instantly: https://docs.fluentbit.io/manual/pipeline/filters/multiline-stacktrace

With that the multiline parsing is and will stay app specific and requires an app specific configuration which is working very easy with that new filter (it seems annotation based support is missing yet). However there cannot be activated anything by default and it will require a custom config always. We need to see how to cover that smoothly in the new #11236 approach

Only consideration is that the default flush setting is not sufficient to contain all log lines of a stacktrace. It should be possibly increased to the default of 5s.

**Comment by skhalash** [comment]
Tested the multiline setup on a k3d cluster (using `containerd` as a container runtime) and a Gardener cluster (using `dockershim` as a container runtime).

* Enabling cri multiline parser fixes the problem with fixing logs on k3d, there is no difference on Gardener
* It's possible to add language-specific multiline filters (go, java), which works fine
* Compared resource consumption of #12554 vs `main` (CPU/memory utilization, input/output processing rate) on Gardener clusters and came to a conclusion that it does not change.
