### ISSUE TITLE
[CLI Reconciler] Update version command

### ISSUE THREAD

**Issue by a-thaler** [kyma-project/kyma#12138]
## Description

The "kyma version" command currently does not work with a kyma2 cluster. Add support so that users can figure out the currently installed version.

Goal: Support kyma2 clusters in the "kyma version" command
Criterias:
- Version command works still with kyma1 clusters
- Deploy command propagates version number
- Version command works with Kyma2 clusters as well

Details:
The reconciler annotates all resources with the targeted version. That can be leveraged to figure out the current version of a cluster by getting the annotation of the kyma-system namespace for example. In order to have the version applied on the resources, the version number must be supplied as part of the deploy command.

## References:
https://github.com/kyma-incubator/reconciler/pull/181/files

**Comment by rakesh-garimella** [comment]
The Version command checks if the installed kyma cluster is kyma 1 and kyma 2 and then it prints the version also the version is propagated for making upgrade decisions.

**Comment by a-thaler** [comment]
Please remove the "2" from the "Kyma 2" in the command output:

```
Kyma CLI version: stable-23-g9fad8e8
Kyma 2 cluster version: main
```
