### ISSUE TITLE
[CLI Reconciler] Remove alpha flavor

### ISSUE THREAD

**Issue by a-thaler** [kyma-project/kyma#12134]
## Description
After the reconciler got integrated to the CLI as alpha command, remove the alpha flavor and make it the default way of installation

Goal: Replace the "kyma deploy" command with the new logic and have the alpha removed

Criterias:

- [x]  There is no alpha anymore
- [x] There is no dependency to the parallel-install library anymore (Those regarding kyma upgrade will stay)
- [ ] Prow jobs are working as before

**Comment by shorim** [comment]
We will also need to change `-X github.com/kyma-project/cli/cmd/kyma/alpha/deploy.defaultSource` and `-X github.com/kyma-project/cli/cmd/kyma/alpha/deploy.isRelease` in the `Makefile` and `goreleaser.yml` to `-X github.com/kyma-project/cli/cmd/kyma/deploy.defaultSource` and `-X github.com/kyma-project/cli/cmd/kyma/deploy.isRelease` respectively.

**Comment by a-thaler** [comment]
We decided to fix the prow jobs in dedicated tickets, so the story is done
