### ISSUE TITLE
Job kyma-upgrade-gardener-kyma-to-kyma2 fails with kyma-tls-cert error

### ISSUE THREAD

**Issue by franpog859** [kyma-project/kyma#12151]
**Description**

`kyma-upgrade-gardener-kyma-to-kyma2` job fails with an error: `2021-09-17T10:32:42.687Z ERROR cli/logs.go:56 [helm/client.go] Error: rendered manifests contain a resource that already exists. Unable to continue with install: Certificate "kyma-tls-cert" in namespace "istio-system" exists and cannot be imported into the current release: invalid ownership metadata; label validation error: missing key "app.kubernetes.io/managed-by": must be set to "Helm"; annotation validation error: missing key "meta.helm.sh/release-name": must be set to "certificates"; annotation validation error: missing key "meta.helm.sh/release-namespace": must be set to "istio-system"`

**Expected result**

`kyma-upgrade-gardener-kyma-to-kyma2` job succeeds

**Steps to reproduce**

Open a PR to this repository, comment it with `/test kyma-upgrade-gardener-kyma-to-kyma2` and see the logs of the triggered job

You can also check out the existing failures, for example [this one](https://status.build.kyma-project.io/view/gs/kyma-prow-logs/logs/kyma-upgrade-gardener-kyma-to-kyma2/1440194092595154944)

**Comment by werdes72** [comment]
https://status.build.kyma-project.io/job-history/gs/kyma-prow-logs/logs/kyma-upgrade-gardener-kyma-to-kyma2
