### ISSUE TITLE
Loki test fails on k3d provisioned with kyma cli (reconciler)

### ISSUE THREAD

**Issue by pbochynski** [kyma-project/kyma#12183]
**Description**

Fast integration test for commerce-mock fails:
```
1) CommerceMock tests
       Logs from commerce mock pod should be retrieved through Loki:
     Error: Error when querying Loki: Error: timeout of 1ms exceeded
```

**Expected result**

Test passes.

**Actual result**

Logs cannot be retrieved.

**Steps to reproduce**

0. Prerequisites

    Checkout `github.com/kyma-project/cli` and `github.com/kyma-project/kyma` repositories to `$GOPATH/src/github.com/kyma-project` folder.
    
    Install [node.js](https://nodejs.org/en/) and install [mocha](https://mochajs.org/) globally:

    ```
    npm install --global mocha
    ```

1. Install istioctl
    ```
    export ISTIO_VERSION=1.11.2
    curl -L https://istio.io/downloadIstio | sh -
    export ISTIOCTL_PATH=$PWD/istio-$ISTIO_VERSION/bin/istioctl
    ```

2. Build Kyma CLI
    ```
    cd $GOPATH/src/github.com/kyma-project/cli
    make build-darwin
    ```

3. Provision k3d cluster
    ```
    ./bin/kyma-darwin provision k3d
    ```

4. Install Kyma
    ```
    ./bin/kyma-darwin alpha deploy
    ```
5. Build tests
    ```
    cd $GOPATH/src/github.com/kyma-project/kyma/tests/fast-integration
    npm install
    ```

6. Run tests
    ```
    mocha -b test/1-commerce-mock.js
    ```

**Comment by shorim** [comment]
@pbochynski are you sure that `istio` was installed successfully on your cluster?
I had to change the `ISTIOCTL_PATH ` to be `export ISTIOCTL_PATH=$PWD/istio-$ISTIO_VERSION/bin/istioctl`. So, there is the `istio-` part missing in the path you pasted or was that just a typo?

Loki test is actually not failing on my machine.

**Comment by shorim** [comment]
Also, if you would like to query Loki manually, you can do it like that:

1. Port-forward: `kubectl port-forward -n kyma-system pods/logging-loki-0 3100:3100`
2. An example query: `curl -G -s "http://localhost:3100/api/prom/query" --data-urlencode 'query={job="fluent-bit"}'`

**Comment by pbochynski** [comment]
Istio was installed - I added the missing `istio-` to the path.
The query you provided works.
But I got a test failure all the time (tried 3 times with a fresh cluster).

**Comment by pbochynski** [comment]
I got the response in 5033 ms. The timeout was too small for my machine. I am still not sure why the reported timeout is 1ms (it was 5000).

**Comment by a-thaler** [comment]
We agreed to remove the axios-retry dependency
