### ISSUE TITLE
Create a Java application integrated with the Application Connector

### ISSUE THREAD

**Issue by lszymik** [kyma-project/kyma#1220]
**Description**

Develop the Java application, which can be used as smoke tests.
We already have a client library developed in Java for one-click integration and API/Event catalog registration. It must be used.

**Acceptance criteria**

- A Java application integrated with libraries for accessing the Application Connector.
- The application is connecting to the Kyma cluster and acquires the client certificate (therefore, creates an RE.)
- The client certificate is used for getting a list of registered services (an empty list is ok)

**Comment by lszymik** [comment]
Review:
- The `ACTOKEN` variable is a little bit misleading.
- The test should get a kubeconfig file and request connection string with a remote env name
- The documentation should highlight at the beginning that test Remote Env with a name is created automaticaly

**Comment by franpog859** [comment]
App works on local minikube and on cluster. 
At this time invalid store creation is handled by the `sleep(5000)` function. Consider to do it in more elegant way. I suggest to use `RetryClosure` as I wrote in the `//TODO: ` comment.

**Comment by Maladie** [comment]
I have added deleting cert files after tests and renamed Remote Environment to Application (in case of need for version with Remote Envs, there is a `pre-renaming` branch. 
Problem with sleep() method is still not resolved.
