### ISSUE TITLE
kyma-integration-k3d-compass-dev periodic job fails (every run)

### ISSUE THREAD

**Issue by pbochynski** [kyma-project/kyma#12234]
**Description**

The periodic job [kyma-integration-k3d-compass-dev](https://status.build.kyma-project.io/job-history/gs/kyma-prow-logs/logs/kyma-integration-k3d-compass-dev) is failing for a week now. 

**Expected result**

It is green.

**Actual result**

It is red.
The error is always the same:
```
  1) Kyma with Compass test
       order.created.v1 event should trigger the lastorder function:
     Error: Cannot send event, the response from event gateway
500: Internal Server Error: {"error":"Problem while sending event: Kyma application API responded with status 403 {\n  \"code\": 403,\n  \"error\": \"no valid subject found\"\n}"}
      at convertAxiosError (utils/index.js:95:10)
      at /home/sa_117798148653314453801/kyma/tests/fast-integration/test/fixtures/commerce-mock/index.js:165:17
      at processTicksAndRejections (internal/process/task_queues.js:95:5)
      at async /home/sa_117798148653314453801/kyma/tests/fast-integration/test/fixtures/commerce-mock/index.js:146:7
      at async sendEventAndCheckResponse (test/fixtures/commerce-mock/index.js:144:3)
      at async Context.<anonymous> (compass-test/compass-test.js:46:5)
```

**Steps to reproduce**

Just wait for the next run and see.

**Troubleshooting**

**Comment by pbochynski** [comment]
The compass team is working on it. There are some PRs:
- https://github.com/kyma-incubator/compass/pull/2045
- https://github.com/kyma-incubator/compass/pull/2046

**Comment by k15r** [comment]
maybe some debugging information:

**Comment by pbochynski** [comment]
The issue is resolved now. Tests are passing again.
