### ISSUE TITLE
Clean up of Dex component

### ISSUE THREAD

**Issue by strekm** [kyma-project/kyma#12258]
**Description**

Since Dex won't be a part of kyma 2.0:
- [x] remove it from kyma resources
- [x] remove prow pipelines related to dex
- [x] remove all dex related settings from other charts
- [x] remove dex related mentions in docu

Please make sure that dex is not used in control-plane, management-plane in any way. 

**Reasons**

Removing unused components from kyma 2.0

**Attachments**

**Comment by piotrkpc** [comment]
Cannot remove/archive dex from kyma-incubator: https://github.com/kyma-incubator/dex
Repo owner needs to do that or somebody with appropriate permissions.

**Comment by mjakobczyk** [comment]
@piotrkpc For now we agreed that no repository should be removed as long as we maintain Kyma 1.X.

**Comment by mmitoraj** [comment]
THi @piotrkpc, all tests regarding Dex should be also removed. See `/kyma/tests/integration/dex/`.

**Comment by mmitoraj** [comment]
I did not find any additional Dex mentions in the documentation.

**Comment by strekm** [comment]
removal of dex fork will be handled in https://github.com/kyma-project/kyma/issues/13684
