### ISSUE TITLE
[CLI Reconciler] Consume reconciler undeploy API

### ISSUE THREAD

**Issue by a-thaler** [kyma-project/kyma#12272]
## Description

At the moment the CLI is removing in a best-effort approach left-overs on a cluster. That is good as a safety net measurement in case the reconciler has leftovers but should not be the main logic for the removal. Instead the reconciler should try to remove everything it applied to a cluster. As a first step a new interface should be introduced for that to the reconciler and consumed by the CLI. Then, the cleanup can be improved step-wise by keeping the CLI untouched.

Goal: Trigger the undeploy of the reconciler before removing resources from the cluster
Criterias:
- There is a well-defined interface in the reconciler for undeploying kyma
- The CLI command is calling it before doing the best-effort removal (without op)
- Consider individual component removal as part of the API

**Comment by clebs** [comment]
The reconciler undeploy API is already fully used by the CLI with individual component removal.
Issue can be closed.
