### ISSUE TITLE
provision-bundles.sh script may fail in cluster setup

### ISSUE THREAD

**Issue by KarolGrzyb** [kyma-project/kyma#123]
Confirm these statements before you submit the issue:

- [x] I have searched open and closed issues for duplicates.
- [x] I have read the contributing guidelines.
---

**Description**
`provision-bundles.sh` script used during Helm Broker Repository synchronisation assumes that pod defined in `po.yaml` will be deployed to same node as `core-helm-broker-reposerver` as it requires to share same PersistentVolumeClaim. This may not happen in multi-node cluster setup - `bundles-repository-provisioner` will fail to start in this case and will stay in broken state.

**Comment by aszecowka** [comment]
sync-bundles.sh doesnt work with cluster. Fix it or if hard to achieve contact PO and decide if documentation about "only local" is allowed.

**Comment by PK85** [comment]
External repository with bundles will be used.
