### ISSUE TITLE
Backpressure propagation to events producer

### ISSUE THREAD

**Issue by radufa** [kyma-project/kyma#12341]
## Description
With NATS as an active eventing backend: If the eventing consumer is slower as the the eventing producer, a kind of backpressure strategy should be implemented by event-publisher-proxy.

## Reasons

The backpressure propagation will slow down the producer and protect the brocker, avoiding OOM (or OO-file system) or losing events

## Acceptance
- [ ] implement returning HTTP-429 to senders in case nats detects a slow receiver
- [ ] document the behaviour

**Attachments**

**Comment by pxsalehi** [comment]
IMO, this is very specific to our current NATS backend, as the only mechanism it has for protecting itself from producers with high number of messages, is to drop messages. Generally speaking (backend-agnostic), we need to be able to address two issues:

1. Protecting the broker from getting its resources exhausted by one or a few producers. 
2. Detecting slow consumers.

I think detecting slow consumers is highly application-specific, and would be tricky to provide consistently across different backends. With backends such as BEB or JetStream (a sequential log-based storage for messages), this concept is also difficult to define. For example, if we allow subscriptions to consume topics from the very first event available for that topic (a.k.a. event type), defining "slowness" becomes very difficult. Furthermore, whether slowing down the flow of messages being ingested, as a result of one slow consumer, which would slow down other consumers, is desirable or not, is highly dependant on the application, and difficult to generalize.

IMO, we should seek other primitives that help us mitigate the two problems above, e.g.:

- Subscribers can regulate the speed at which they consume messages using parameters available at subscription level, such as MaxInFlight.
- Brokers can be protected from producers with very high message rates using two mechanisms. 1) Proper configuration on the broker that allows trimming topics. 2) Introducing throttling for publication rate on the Publisher Proxy, which prevents a producer from publishing more than e.g. 100 message/second. This allows calculating the maximum number of messages that could be produced and ingested, even if a faulty producer would produce at max speed for several days, and configuring correct PV size or retention period for topics.

**Comment by radufa** [comment]
In an ideal word, EPP will recognize that the backend messaging system has issues at "injection" and it could returns "429" to its client, so that this one could slow down too. Manually tuning the eventing flow "producer -> EPP -> backend -> dispatcher ->subscriber (consumer)" is difficult.

**Comment by nachtmaar** [comment]
/remove-lifecycle/stale
