### ISSUE TITLE
Reorganise the Application Connector components structure

### ISSUE THREAD

**Issue by mvshao** [kyma-project/kyma#12349]
**Description**
The [`/components`](https://github.com/kyma-project/kyma/tree/main/components) directory needs a reorganization to get a file structure similar to the [`/resources`](https://github.com/kyma-project/kyma/tree/main/resources/application-connector) directory.

**Reasons**
As a result of the reorganization, we can reuse the code with ease. It will also speed up bumping the libraries and fixing security vulnerabilities.

**Attachments**
Have a look at the main issue #11826

**Comment by franpog859** [comment]
I suggest structuring it as:
```
components/application-connector/
  - go.mod
  - go.sum
  - pkg/
  - connector-service/
    - cmd/
    - internal/
  - application-registry/
    - cmd/
    - internal/
  - ...
```
Having one `go.mod` covers the *It will also speed up bumping the libraries and fixing security vulnerabilities* from acceptance criteria and having one `pkg/` directory covers the *reuse the code with ease* part

**Comment by mvshao** [comment]
Due to the planned clean-up of the application-connector components in the future Kyma releases, we decided to freeze this task. As @franpog859 commented above, we are planning to have only one `go.mod` and `pkg/` directory.

Pinned epic to this issue #12353

**Comment by janmedrek** [comment]
Thanks, @mvshao! I will update the issue to reflect the changes needed after the Application Connector clean-up. Let's postpone this until we are done with prerequired changes.

**Comment by akgalwas** [comment]
It will be handled as a part of [#15826](https://github.com/kyma-project/kyma/issues/15826)
