### ISSUE TITLE
Clean up of xip-patch component

### ISSUE THREAD

**Issue by strekm** [kyma-project/kyma#12371]
**Description**

Since xip-patch won't be a part of kyma 2.0:
- [x] remove it from kyma resources / components
- [x] remove prow pipelines related to xip-patch
- [x] remove xip-patch related mentions in docu

**Reasons**

Removing unused components from kyma 2.0

**Attachments**

**Comment by mmitoraj** [comment]
I did not find any additional mentions of `xip` in the documentation.
