### ISSUE TITLE
Clean up of iam-kubeconfig component

### ISSUE THREAD

**Issue by strekm** [kyma-project/kyma#12373]
**Description**

Since iam-kubeconfig service won't be a part of kyma 2.0:
- [x] remove it from kyma resources / components
- [x] remove prow pipelines related to iam-kubeconfig
- [x] remove iam-kubeconfig related mentions in docu

**Reasons**

Removing unused components from kyma 2.0

**Attachments**

**Comment by mmitoraj** [comment]
I did not find any additional mentions of `iam-kubeconfig` in the documentation.
