### ISSUE TITLE
Clean up of permission controller component

### ISSUE THREAD

**Issue by strekm** [kyma-project/kyma#12376]
**Description**

Since permission controller won't be a part of kyma 2.0:
- [x] remove it from kyma resources / components
- [x] remove prow pipelines related to permission controller
- [x] remove permission controller related mentions in docu

**Reasons**

Removing unused components from kyma 2.0

**Attachments**

**Comment by piotrkpc** [comment]
related PR: https://github.com/kyma-project/kyma/pull/12967

**Comment by piotrkpc** [comment]
related PR: (test infra) https://github.com/kyma-project/test-infra/pull/4655

**Comment by mmitoraj** [comment]
I didn't find any mentions of the `permission controller` in the Kyma documentation or any `.md` file in the `kyma` repository.
