### ISSUE TITLE
Clean up of istio component

### ISSUE THREAD

**Issue by strekm** [kyma-project/kyma#12375]
**Description**

Since Istio is replaced with istio-configuration component for kyma 2.0:
- [x] remove it from kyma resources
- [x] remove prow pipelines related to istio
- [x] replace istio component related mentions in docu with istio-configuration
- [x] add README to istio-configuration

**Reasons**

Removing unused components from kyma 2.0

**Attachments**

**Comment by piotrkpc** [comment]
iiuc, first two points are already done. I've addressed third with this PR: https://github.com/kyma-project/kyma/pull/13039

**Comment by mmitoraj** [comment]
`README.md` for the Istio Configuration chart merged. 

I checked and did not find any place in the documentation where `istio` should be changed to `istio-operator`.
