### ISSUE TITLE
Clean up apiserver-proxy component

### ISSUE THREAD

**Issue by strekm** [kyma-project/kyma#12372]
**Description**

Since apiserver-proxy won't be a part of kyma 2.0:
- [x] remove it from kyma resources / components
- [x] remove prow pipelines related to apiserver-proxy
- [x] remove apiserver-proxy related mentions in docu

**Reasons**

Removing unused components from kyma 2.0

**Attachments**

**Comment by mmitoraj** [comment]
I did not find any additional mentions of `apiserver-proxy` in the documentation.
