### ISSUE TITLE
Grafana not having datasources from Loki and Tracing

### ISSUE THREAD

**Issue by rakesh-garimella** [kyma-project/kyma#12403]
**Description**
Installing Kyma via reconciler has a side effect that multiple components are installed in parallel, if during installation the monitoring chart is applied before Logging or Tracing then the datasource from Logging/Tracing is not picked by Grafana.  Restarting the grafana pod picks up the datasources.

Grafana loads datasource via configmap and these configmaps should be created before Grafana is deployed so that it can be picked up by Grafana

A component reconciler would be needed in such a case as to mitigate the issue.

**Expected result**
Grafana should have all the datasources configured.

**Actual result**
There can be scenarios when some datasources might be present but not picked by 

**Steps to reproduce**

**Workaround**
Restart the grafana Pod.

**Comment by jeremyharisch** [comment]
This Bug will be resolved with the following PRs. Please stick to the described testing description in the first PR:

1. https://github.com/kyma-project/third-party-images/pull/142
2. https://github.com/kyma-project/kyma/pull/12486

When the first PR is merged an image will be build and pushed in the Kyma GCP project. When this is done, the image tag needs to be updated in the second PR.

Please contact me, if you need any help testing or I can also show you and we review it together to save some time.

**Comment by jeremyharisch** [comment]
Issues has been resolved by mentioned PRs with a new layer, called `Grafana-Watcher`, on top of Grafana. This has been implemented in the third-party-images repository.
