### ISSUE TITLE
Annotations on bundled grafana dashboards are not persisted after pod restart

### ISSUE THREAD

**Issue by rakesh-garimella** [kyma-project/kyma#12400]
**Description**

Annotations on the bundled grafana dashbaords are deleted after the pod restart. However if a user creates a dashboard and puts the annotations on this dashboard it survives a pod restart.

Further checking into the grafana db it looks like the table with `annotations` is completely re-created (thus deleting the annotations on bundled dashboards) after a pod restart however the table `annotation_tags` table is persisted. Currently looks like on startup of grafana pod when it applies the dashboards from the configmaps the annotations is deleted.

**Expected result**
The annotations should be persisted

**Actual result**
The annotations are deleted.

**Steps to reproduce**
1. Goto grafana console and try to create an annotation and annotation tag on an existing dashboards
2. Restart the grafana pod and the annotation is deleted.

**Workaround**
 Annotations on user created dashboard survive the pod pod restart.

**Comment by jeremyharisch** [comment]
# What causes the problem?
Grafana saves the dashboards, as well as its annotations, in an internal SQL-database. The pre-defined dashboards, which are getting deployed together with the Grafana deployment, are stored in different tables than the dashboards created by the user after the deployment. 

By default when Grafana restarts, all tables which refer to deployment resources, are getting deleted and newly build based on the Grafana deployment resources. Thus, the annotations of the bundled Grafana dashboards will be not persisted after a restart.

# Workaround
As a workaround, we suggest to copy the needed dashboard after the Grafana deployment, to store it and its annotations into a SQL-table which will not be deleted on a restart. 

To do this, please follow these steps:
1. Open the needed dashboard on the Grafana UI
2. Open the settings of the dashboard (right-upper corner)
3. Click on `JSON Model`
4. Copy the whole JSON file into the clipboard
5. Go back to the Grafana UI, and click on `Import` in the `Create` section
6. Paste the copied JSON code into the panel and click on `Load`
7. Do the necessary changes Grafana tells you (New `name` and `uid`)
8. Click on `Import`

Now, this newly created dashboard is a copy of the original dashboard, but its annotations will be persisted even after Grafana restarts.
