### ISSUE TITLE
Specify the shape for boxes in the content guidelines

### ISSUE THREAD

**Issue by majakurcius** [kyma-project/kyma#12412]
**Description**

Our [guidelines](https://github.com/kyma-project/community/blob/main/docs/guidelines/content-guidelines/02-diagrams.md#shapes) state what color to use for shapes such as boxes, but they don't specify whether to use rounded boxes or rectangular ones. 
We should specify the shape for boxes in the guidelines. 

**ACs**

- [x] Specify the shape for boxes (rounded) in the guidelines
- [ ] Adjust the diagrams on the [Kyma Website](https://kyma-project.io/docs/kyma/latest) to the new guideline

**Area**

* Documentation - diagrams

**Reasons**

For the sake of consistency throughout our documentation, we want to specify it so that everyone applies the same formatting. 

**Assignees**

@kyma-project/technical-writers

**Attachments**

![image](https://user-images.githubusercontent.com/53601578/138089593-f6b4cd17-230e-4da3-86c2-b098536f5af8.png)

**Comment by NHingerl** [comment]
The [guide](https://kyma-project.io/community/guidelines/content-guidelines/08-diagrams/#shapes-and-fills) has been updated in the meantime:

<img width="706" alt="image" src="https://user-images.githubusercontent.com/76950046/167590289-57e401d5-8d97-4f72-83f9-99c298205a8e.png">

I'm applying the rounded shapes for Observability in https://github.com/kyma-project/kyma/pull/14063 but for other areas, it's still open.

**Comment by grego952** [comment]
New diagrams will be created for Modular Kyma
