### ISSUE TITLE
Investigate and fix OutOfMemory in pre-main-kyma-gardener-gcp-eventing job

### ISSUE THREAD

**Issue by marcobebway** [kyma-project/kyma#12440]
**Description**

Investigate and fix OutOfMemory in `pre-main-kyma-gardener-gcp-eventing` job.

**Sample failures**

- https://status.build.kyma-project.io/view/gs/kyma-prow-logs/pr-logs/pull/kyma-project_kyma/12415/pre-main-kyma-gardener-gcp-eventing/1451452984813686784.
- https://status.build.kyma-project.io/view/gs/kyma-prow-logs/pr-logs/pull/kyma-project_kyma/12415/pre-main-kyma-gardener-gcp-eventing/1451479860860948480.
- https://status.build.kyma-project.io/view/gs/kyma-prow-logs/pr-logs/pull/kyma-project_kyma/12397/pre-main-kyma-gardener-gcp-eventing/1450807865978654720.
- https://status.build.kyma-project.io/view/gs/kyma-prow-logs/pr-logs/pull/kyma-project_kyma/12397/pre-main-kyma-gardener-gcp-eventing/1450781490831953920.

**Initial analysis**

```
2021/10/22 09:00:01 UTC [INFO] *************************************************************************************
2021/10/22 09:00:01 UTC [INFO] * OOM event found
2021/10/22 09:00:01 UTC [INFO] *************************************************************************************
2021/10/22 09:00:01 UTC [INFO] Download OOM events details
2021/10/22 09:00:01 UTC [INFO] Print OOM events details
OOM event received time: 22 Oct 21 08:18 +0000 , namespace: kyma-system , pod: tracing-jaeger-747fcf7b5-jsh9d ,container: jaeger , image: jaegertracing/all-in-one@sha256:db45c07f2e1bc208d69d5a8c5243e9fb18a25ffa4bc2c5b46ff7581c7a4e41df 
OOM event received time: 22 Oct 21 08:49 +0000 , namespace: kyma-system , pod: tracing-jaeger-747fcf7b5-jsh9d ,container: jaeger , image: sha256:0e2e4c273c1d9e999ccfdfa242f4753198bc65a06f2a895f6c7d5dccd6682d77 
```

**Comment by mfaizanse** [comment]
evaluation-profile for tracing has been increased in this [PR](https://github.com/kyma-project/kyma/pull/12515).
