### ISSUE TITLE
Probe configured sink to verify valid sink configuration

### ISSUE THREAD

**Issue by k15r** [kyma-project/kyma#12474]
**Description**

As a user of eventing i want to be able to check the subscription status to figure out if theoretically eventing could use this subscription.

If the sink is misconfigured there is currently no way to figure this out by just checking the subscription itself. Only the eventing controller itself reports in the logs, that the sink did not respond correctly.

e.g: 
```js
{
  "level": "ERROR",
  "timestamp": "2021-10-27T13:47:37Z",
  "logger": "reconciler.Subscription",
  "caller": "handlers/nats.go:182",
  "message": "failed to dispatch event",
  "context": {
    "error": "401: "
  }
}
```

upon reconciliation our controller should probe the configured endpoint to check if it could be reached.

**Acceptance:**
- [ ] probe configured endpoint (eg. HEAD request)

**Comment by k15r** [comment]
Reevaluate after implementing https://github.com/kyma-project/kyma/issues/11463

**Comment by mfaizanse** [comment]
Currently, eventing-controller verifies if a k8s svc exists for the sink or not ([here](https://github.com/kyma-project/kyma/blob/bc02f26e83cf7e5d4a60e2d5583b2356cf3b13d8/components/eventing-controller/pkg/handlers/sink/validator.go#L84)).

**Comment by k15r** [comment]
a more complete solution will be implemented here: https://github.com/kyma-project/kyma/issues/14218
