### ISSUE TITLE
website-governance-nightly keeps failing due to 'too many requests' error

### ISSUE THREAD

**Issue by kwiatekus** [kyma-project/kyma#12478]
**Description**

See the test results : https://status.build.kyma-project.io/?type=periodic&job=website-governance-nightly
Its Failing as we probably call github api too frequently

**Expected result**

Periodic job should not fail. Fix the problem or delete the job

**Actual result**

https://status.build.kyma-project.io/?type=periodic&job=website-governance-nightly

**Troubleshooting**
We should check if its the same reason as for https://github.com/kyma-incubator/milv/issues/8
Did we exceed the limits again with the new website in place?

**Comment by Halamix2** [comment]
Perhaps setting `backoff` value to a few seconds in the `milv.conf.yaml` file in the `website` repo would help?
Example: https://github.com/kyma-incubator/milv/blob/main/pkg/test-markdowns/milv-test.config.yaml#L3
