### ISSUE TITLE
Documentation of release/branching/tagging strategy

### ISSUE THREAD

**Issue by KarolGrzyb** [kyma-project/kyma#125]
Confirm these statements before you submit the issue:

- [x] I have searched open and closed issues for duplicates.
- [x] I have read the contributing guidelines.
---

**Description**
There is no information about what branch/tag should be checked out to obtain tested/stable release in the documentation (main page or "Getting started" page). Users may (like us) assume that they can  just use `master` branch, which may not be stable at given moment. Also some general information about release cycle should be useful.

**Comment by gopikannappan** [comment]
Gaurav and Lukasz G to sync on the exact scope of this ticket compared to the task planned during planning.

**Comment by derberg** [comment]
This still needs to be addressed once we have final strategy defined

**Comment by derberg** [comment]
There are 3 different aspects here:
1. `master` stability -> For us it is clear master has to be stable and we have official document about installing Kyma from sources https://kyma-project.io/docs/root/kyma#installation-install-kyma-locally-from-sources
2. release process -> is also documented already https://github.com/kyma-project/test-infra/blob/master/docs/prow/release-process.md
3. release strategy -> this is the current scope of this task, we worked on a proper strategy few months and we are now ready to publish it https://github.com/kyma-project/community

**Comment by kazydek** [comment]
#https://github.com/kyma-project/community/pull/218
