### ISSUE TITLE
Reconciler not waiting for resources when rolling update is performed

### ISSUE THREAD

**Issue by rakesh-garimella** [kyma-project/kyma#12501]
**Description**

Reconciler is not waiting checking if the pod has restarted when installing a component using kyma cli eg
`kyma deploy --component logging@kyma-system ` In such a scenario the the runLocal is returning immediately.  It should ideally wait for the logging pod to come up.

**Comment by skhalash** [comment]
Seems like we have a bigger problem there.

After performing some tests I found a problem in the progress package: https://github.com/kyma-incubator/reconciler/tree/main/pkg/reconciler/kubernetes/progress. Currently, the logic is as follows:
1. Render a component chart and deploy resources.
2. If the resource creates pods (it’s a deployment, daemonset, statefulset, etc.) wait for it. The progress package is provided with the kind, the name, and the namespace.

It only works if Kyma is deployed on an empty cluster. If you are patching a Kyma installation, this mechanism does not work anymore. 

For example, if you are patching a deployment in the `kyma-system` namespace, the progress pkg will check if there is a deployment with that name in the `kyma-system`  namespace, will find the old deployment, and will report the ready state. `kyma deploy`  will end before the rolling update event starts.

My suggestion is - if we are re-implementing some features of Helm, it’s maybe worth looking at their code: https://github.com/helm/helm/blob/39fc522ebb77b0e71cae8e809076ab2603263470/pkg/kube/ready.go#L91

**Comment by skhalash** [comment]
For example, here's our checking logic for daemonsets:
```go
	daemonSetClient := pt.client.AppsV1().DaemonSets(object.namespace)
	daemonSet, err := daemonSetClient.Get(context.TODO(), object.name, metav1.GetOptions{})
	switch inState {
	case ReadyState:
		if err != nil {
			return false, err
		}
		return daemonSet.Status.NumberUnavailable == 0, nil
	case TerminatedState:
		if err != nil && errors.IsNotFound(err) {
			return true, nil
		}
		return false, err
	default:
		return false, fmt.Errorf("state '%s' not supported", inState)
	}
```
It will work in the case of the first installation, but will not wait for a rolling update.

**Comment by skhalash** [comment]
That's for example what `helm install` is doing: https://github.com/helm/helm/blob/39fc522ebb77b0e71cae8e809076ab2603263470/pkg/kube/ready.go#L283

```go
func (c *ReadyChecker) daemonSetReady(ds *appsv1.DaemonSet) bool {
	// If the update strategy is not a rolling update, there will be nothing to wait for
	if ds.Spec.UpdateStrategy.Type != appsv1.RollingUpdateDaemonSetStrategyType {
		return true
	}

	// Make sure all the updated pods have been scheduled
	if ds.Status.UpdatedNumberScheduled != ds.Status.DesiredNumberScheduled {
		c.log("DaemonSet is not ready: %s/%s. %d out of %d expected pods have been scheduled", ds.Namespace, ds.Name, ds.Status.UpdatedNumberScheduled, ds.Status.DesiredNumberScheduled)
		return false
	}
	maxUnavailable, err := intstr.GetValueFromIntOrPercent(ds.Spec.UpdateStrategy.RollingUpdate.MaxUnavailable, int(ds.Status.DesiredNumberScheduled), true)
	if err != nil {
		// If for some reason the value is invalid, set max unavailable to the
		// number of desired replicas. This is the same behavior as the
		// `MaxUnavailable` function in deploymentutil
		maxUnavailable = int(ds.Status.DesiredNumberScheduled)
	}

	expectedReady := int(ds.Status.DesiredNumberScheduled) - maxUnavailable
	if !(int(ds.Status.NumberReady) >= expectedReady) {
		c.log("DaemonSet is not ready: %s/%s. %d out of %d expected pods are ready", ds.Namespace, ds.Name, ds.Status.NumberReady, expectedReady)
		return false
	}
	return true
}
```

**Comment by varbanv** [comment]
PR: https://github.com/kyma-incubator/reconciler/pull/347

**Comment by skhalash** [comment]
Cannot test because of another issue: https://github.com/kyma-incubator/reconciler/issues/368

**Comment by pbochynski** [comment]
@rakesh-garimella Please review if it works now.

**Comment by skhalash** [comment]
It works now.
