### ISSUE TITLE
Use ServiceEntry instead of IPRanges

### ISSUE THREAD

**Issue by pbochynski** [kyma-project/kyma#1251]
**Description** 
In order to allow access to external services envoy in Kyma is configured to intercept only traffic on IP ranges from subnet 10.0.0.1/8. This setting is too wide for most of cloud providers and is not recommended way to solve this problem. Istio has concept of [ServiceEntry](https://istio.io/docs/concepts/traffic-management/#service-entries) which is designed to add external services to service mesh. 

**Reasons** 
 * For some requests we are bypassing envoy. Because of that we are loosing it's capabilities to trace and secure traffic.
* It is not obvious which network mask must be used to be specific and they differ from from one cloud provider to the other.
* ServiceEntry is recommended and officially supported by istio way to enable external access.

**Comment by sjanota** [comment]
[WIP] 
1. Which Kyma features requires external access:
 * application-connector - ?
 * lambda - ?
2. Can we predict what external services will be used before they are accessed?
3. Other options:
* ServiceEntry with wildcard is coming in 1.2 - istio/istio#6146
* Stay with IPRanges without telemetry

**Comment by sjanota** [comment]
We're going to wait for istio/istio#6146. Blocking access to outside world now will cause too much trouble and is not worth the effort.

**Comment by piotrmsc** [comment]
Closing it, we will document when to use SE in our documentation : https://github.com/kyma-project/kyma/issues/9189
