### ISSUE TITLE
Add serverless e2e test with different git providers

### ISSUE THREAD

**Issue by dbadura** [kyma-project/kyma#12521]
**Description**

It would be nice to have automated test which check if our implementation can authorize against different git providers.

**Reasons**
Every time we bump the `lib-git2` library or change to code, we have to manually test git integration.

** Acceptance Criteria

Create private repos with `Hello World` function in:
- github
- azure devops

The test should build and run `Hello World` function using basic auth, ssh key and bad credentials.
  
**Attachments**

**Comment by kwiatekus** [comment]
The job history shows some problems
```
{"level":"error","msg":"Scenario git-auth-integration not exist","time":"2021-12-30T03:05:52Z"}
```
https://status.build.kyma-project.io/job-history/gs/kyma-prow-logs/logs/serverless-git-auth-integration-k3s-nightly
