### ISSUE TITLE
Monitoring Stack not showing up on Busola

### ISSUE THREAD

**Issue by jeremyharisch** [kyma-project/kyma#12538]
**Description**

The monitoring stack (Logging, Tracing, Metrics) are not shown on Busola dashboard.
All three components are successfully installed on the Kyma cluster and can be reached through port-forwarding. (i.e. `kpf svc/monitoring-grafana 8080:80 -n kyma-system`)

The virtual services are also available for the three components:
```bash
k get virtualservice
NAME                                         GATEWAYS                                                               HOSTS                        AGE
kiali                                        ["kyma-system/kyma-gateway"]                                           ["kiali.local.kyma.dev"]     32m
monitoring-grafana                           ["kyma-system/kyma-gateway"]                                           ["grafana.local.kyma.dev"]   31m
central-application-connectivity-validator   ["kyma-gateway-application-connector.kyma-system.svc.cluster.local"]   ["gateway.local.kyma.dev"]   31m
tracing                                      ["kyma-system/kyma-gateway"]                                           ["jaeger.local.kyma.dev"]    30m
ory-hydra                                    ["kyma-system/kyma-gateway"]                                           ["oauth2.local.kyma.dev"]    30m
```
`logging` and `metrics` components are both covered by `monitoring-grafana`

![Screenshot 2021-11-04 at 09 39 56](https://user-images.githubusercontent.com/48282931/140290039-0d0a2a66-e779-4b7f-bbaa-fb211c52a3be.png)

**Expected result**
Logging, Tracing, and Metrics should be shown on Busola dashboard.

**Actual result**
Whole monitoring stack not reachable through Busola.

**Steps to reproduce**
1. `kyma alpha provision k3d`
2. `kyma deploy -s local`
3. `kyma dashboard`
For this the latest main version of Kyma was used, and the latest stable CLI.

**Comment by valentinvieriu** [comment]
This is a Busola Bug that happens on the Local Docker only, and it's not a release blocker
We will pick this up in our backlog

**Comment by jeremyharisch** [comment]
I will remove release-blocker tag then 👍🏻

**Comment by Sawthis** [comment]
Fixed in https://github.com/kyma-project/busola/pull/508 pull request.
