### ISSUE TITLE
Fluent Bit should collect label app.kubernetes.io/name

### ISSUE THREAD

**Issue by johgoe** [kyma-project/kyma#12536]
My experience shows that a lot of charts using 

a label `app.kubernetes.io/name` instead of `app` which is quite common https://kubernetes.io/docs/concepts/overview/working-with-objects/common-labels/ 

I think `app.kubernetes.io/component` can also be useful.

In Loki only the Apps with label "app" appears. I'm not sure but I thing the label should be added here

https://github.com/kyma-project/kyma/blob/cfa81506876c3037048dedbf0f01c557ba127888/resources/logging/charts/fluent-bit/values.yaml#L252

Maybe it's also possible to get a v1.24.x backport?

**Comment by johgoe** [comment]
I tested it with a configuration in kubectl get cm -n kyma-system logging-fluent-bit
```
 labelmap.json: |-
    {
      "kubernetes": {
        "container_name": "container",
        "host": "node",
        "labels": {
          "app": "app",
          "release": "release",
          "app.kubernetes.io/component": "appComponent",
          "app.kubernetes.io/name": "appName",
          "serverless.kyma-project.io/function-name": "function",
          "serverless.kyma-project.io/uuid": "functionUID"
        },
        "namespace_name": "namespace",
        "pod_name": "pod"
      },
      "stream": "stream"
    }
```

**Comment by a-thaler** [comment]
Hi @johgoe, very good point and we should improve it.

With Loki you always have the considerations on dynamic labelling, keeping an eye on the log stream cardinality, see https://grafana.com/blog/2020/04/21/how-labels-in-loki-can-make-log-queries-faster-and-easier/

It is hard to define a setup which generically fits all and we should reducing dynamic labels as much as possible. Having that in mind I have the following idea on improve the current situation:

Let's first of all keep the "kubernetes" attribute as part of the log entry (it is currently dropped as part of the loki plugin config). With that you can use the LokiQL to search for label expressions in any way. With that you can also search for other standard labels like "app.kubernetes.io/instance".

The proposed label app.kubernetes.io/name is the current recommend way for labelling and usually will not used in conjunction with the old "app" label, so maybe we can just mix-up the values in one label, giving prio on the new way.
Furthermore we can include the proposed component label if you think that really can bring value.

And we exclude the labels "functionUID" (you can use the "function" instead, no need to increase cardinality for having alternatives) and also "release" (anyway fading out with helm2).

Summarized:
keep "kubernetes" attribute as part of the log + 
 labelmap.json: |-
    {
      "kubernetes": {
        "container_name": "container",
        "host": "node",
        "labels": {
          "app": "app",
          "app.kubernetes.io/component": "component",
          "app.kubernetes.io/name": "app",
          "serverless.kyma-project.io/function-name": "function"
        },
        "namespace_name": "namespace",
        "pod_name": "pod"
      },
      "stream": "stream"
    }

@skhalash what do you think?

**Comment by skhalash** [comment]
I agree that we should restrict dynamic labels to the bare minimum. Having the `app`, the `component`, and the `function` labels should suffice.
