### ISSUE TITLE
ORY stack version upgrade

### ISSUE THREAD

**Issue by strekm** [kyma-project/kyma#12557]
**Description**

Update ORY components to latest version. 

AC:
- [x] ORY components running on latest version
- [x] sec scans green
- [x] release notes 

**Reasons**

Keeping 3rd party dependencies up to date

**Attachments**

**Comment by veichtj** [comment]
bumps merged, wait for sec issue to be gone

**Comment by pbochynski** [comment]
Please verify: https://github.com/kyma-project/kyma/issues/12608#issuecomment-970051509
