### ISSUE TITLE
Provide clear statement about supported Kubernetes versions in the documentation

### ISSUE THREAD

**Issue by pbochynski** [kyma-project/kyma#12558]
**Description**

**Area**

**Reasons**

**Assignees**

@kyma-project/technical-writers

**Attachments**

**Comment by mmitoraj** [comment]
What PB means is probably that **Kyma does not support Kubernetes 1.22** so we should recommend using version from 1.19 to 1.21, is that correct @pbochynski ? I will update this on my PR once confirmed.

**Comment by pbochynski** [comment]
Yes, exactly.

**Comment by mmitoraj** [comment]
PR merged
