### ISSUE TITLE
NATS Backend: configurable exponential backoff

### ISSUE THREAD

**Issue by k15r** [kyma-project/kyma#12563]
**Description**

Make the parameters of "Retries with Exponential Backoff" (period, maxTries) configurable. Sometimes this is required to improve performance with the tradeoff of potentially lower delivery reliability.

**Acceptance**
- [ ] backoff configurable via subscription
- [ ] documentation updated
- [ ] provide suggestions for values

**Comment by nachtmaar** [comment]
Exponential backoff is already implemented, we just need to make it configurable.
