### ISSUE TITLE
Align IstioOperator overrides between Kyma 1.X and Kyma 2.0

### ISSUE THREAD

**Issue by mjakobczyk** [kyma-project/kyma#12576]
**Description**

We need to align `IstioOperator` spec between Kyma 1.X and Kyma 2.0 versions. Install Istio in both of them using `production` profile and compare any inconsistency.

**Reasons**

We can not omit functionalities that were present in Kyma 1.X but were for some reason omitted in Kyma 2.0.

**Attachments**

Install Kyma 1.X from the [release 1.24](https://github.com/kyma-project/kyma/tree/release-1.24).
Install Kyma 2.0 from the [release 2.0-rc4](https://github.com/kyma-project/kyma/tree/release-2.0-rc4/resources/istio-configuration).

**Comment by Kaktusowy500** [comment]
I installed Kyma 1.24.7 and Kyma 2.0-rc4 with production profiles. After extracting an IstioOperator resources, I compared them. All differences can be found [here](https://www.diffchecker.com/xf9fJlMX).
The most important changes in enabled components:
- ingressGateways: no scaleTargetRef and service property with port forwarding
- pilot: less in hpaSpec(missing metrics: -resource and  scaleTargetRef), no readinessProbe and rolling update strategy 
- some envs are missing in both components

**Comment by Tomasz-Smelcerz-SAP** [comment]
`ISTIO_META_ROUTER_MODE` with `sni-dnat` is necessary for `AUTO_PASSTHROUGH` mode, which we don't use in Kyma (to verify). IMO we can skipt that.

**Comment by Tomasz-Smelcerz-SAP** [comment]
`scaleTargetRef` property, although missing in IstioOperator, is properly configured on the `istio-system/istio-ingressgateway` `HorizontalPodAutoscaler` CR instance.

**Comment by Tomasz-Smelcerz-SAP** [comment]
Configuration for `ingressGateways.k8s.service.ports` is different. Istio by default creates a config that looks different. Requires further analysis.

**Comment by Kaktusowy500** [comment]
> `scaleTargetRef` property, although missing in IstioOperator, is properly configured on the `istio-system/istio-ingressgateway` `HorizontalPodAutoscaler` CR instance. I think Istio sets this to a correct value, but allows users to fine-tune the setting, if necessary. I think we can safely skip it in our IstioOperator configuration.

Yes, I have just checked HPAs of installed Kyma2.0 and it looks fine(references and targets are set properly):
```
k get hpa -n istio-system                                                                                                     
NAME                   REFERENCE                         TARGETS           MINPODS   MAXPODS   REPLICAS   AGE
istio-ingressgateway   Deployment/istio-ingressgateway   45%/80%, 5%/80%   3         10        3          11m
istiod                 Deployment/istiod                 1%/80%            2         5         2          11m
```

**Comment by Tomasz-Smelcerz-SAP** [comment]
As for `pilot.hpaSpec`, it looks like we don't have explicit config, but Istio defaults to the same values (`targetCPUUtilizationPercentage: 80`) as in Kyma 1.24.x. We need this config to be explict though, because users may want to override this. Perhaps we need to extend our charts with explicit configuration here.

**Comment by Tomasz-Smelcerz-SAP** [comment]
The `readinessProbe` config in 1.24.x is explicit, but Istio defaults to the same values. Perhaps we don't need to define it in our IstioOperator, it's redundant.

**Comment by Tomasz-Smelcerz-SAP** [comment]
Same for `strategy: rollingUpdate`
We might expose `replicaCount` though, it is something we (or the users) may want to change.

**Comment by Tomasz-Smelcerz-SAP** [comment]
The `POD_NAME` and `POD_NAMESPACE` are set correctly, no need to repeat the defaults in our IstioOperator

**Comment by Tomasz-Smelcerz-SAP** [comment]
We may want to expose `pilot` `replicaCount` property so it can be overridden.

**Comment by Kaktusowy500** [comment]
Pilot's `replicaCount` and `targetAverageUtilization` for cpu can be overridden by users

**Comment by Kaktusowy500** [comment]
It seems like all ports are bound to the range 30000-32767 by default, moreover ports: 15021, 80 and 443 are forwarded even if they are not listed in istioOperator. 
Default Kyma 2.0 installation(without any explicit bindings):
```
k get svc -n istio-system                                                                                   
NAME                   TYPE           CLUSTER-IP       EXTERNAL-IP      PORT(S)                                      AGE
istio-ingressgateway   LoadBalancer   100.64.70.101    34.140.208.144   15021:30489/TCP,80:31101/TCP,443:30099/TCP   3h24m
istiod                 ClusterIP      100.65.200.128   <none>           15010/TCP,15012/TCP,443/TCP,15014/TCP        3h24m
  ```
After adding ports binding(imported from Kyma 1.24 profiles) and installing from this [PR](https://github.com/kyma-project/kyma/pull/12612/files):
```
k get svc -n istio-system                                                                                     
NAME                   TYPE           CLUSTER-IP       EXTERNAL-IP      PORT(S)                                                                                                                                                      AGE
istio-ingressgateway   LoadBalancer   100.64.70.101    34.140.208.144   15021:30489/TCP,80:31101/TCP,443:30099/TCP,15012:30026/TCP,31400:31955/TCP,15443:30050/TCP,15029:30555/TCP,15030:32455/TCP,15031:31083/TCP,15032:31402/TCP   4h6m
istiod                 ClusterIP      100.65.200.128   <none>           15010/TCP,15012/TCP,443/TCP,15014/TCP
```
It looks very similar to default Kyma 1.24.8 installation:
```
k get svc -n istio-system                                                                                                                                               
NAME                   TYPE           CLUSTER-IP       EXTERNAL-IP     PORT(S)                                                                                                                                                      AGE
istio-ingressgateway   LoadBalancer   100.71.255.127   35.195.62.201   15021:31435/TCP,15012:31884/TCP,80:30399/TCP,443:30728/TCP,31400:32664/TCP,15443:32023/TCP,15029:32186/TCP,15030:31427/TCP,15031:31010/TCP,15032:30309/TCP   10m
istiod                 ClusterIP      100.70.153.29    <none>          15010/TCP,15012/TCP,443/TCP,15014/TCP                                                                                                                        10m
```

I assume that explicit binding of ports 80, 443 and 15021 can be omitted because it is done by default. Probably only binding for the rest of the ports should be added to profiles like, in mentioned PR.

**Comment by Kaktusowy500** [comment]
I have compared Istio-operators after applying overrides listed in these control-plane configs: [kyma1.24](https://github.tools.sap/kyma/management-plane-config/blob/master/resources/control-plane/config/base/runtimes/1.24/istio.yaml) and [kyma2.0](https://github.tools.sap/kyma/management-plane-config/blob/master/resources/control-plane/config/base/runtimes/2.0/istio.yaml). Only new differences brought by these overrides are:

```
ingressGateways:
    strategy:		       
          rollingUpdate:		        
            maxSurge: 50%		           
            maxUnavailable: 1 
```   
in Kyma2.0 changed to:
```
ingressGateways:
    strategy:		       
          rollingUpdate:		        
            maxSurge: 100%		           
            maxUnavailable: 0 
```   
Similar change occurs in pilot:
```
pilot:
    strategy:		       
          rollingUpdate:		        
            maxSurge: 50%		           
            maxUnavailable: 1 
```   
changed to:
```
pilot:
    strategy:		       
          rollingUpdate:		        
            maxSurge: 50%		           
            maxUnavailable: 0
```   
These changes are rather improvements to the availability of mentioned services so we do not have to change any configuration. All differences between Istio-operators after overriding can be found [here](https://www.diffchecker.com/e2EwV2eU)

**Comment by Kaktusowy500** [comment]
I also compared tracing yamls [kyma1.24](https://github.tools.sap/kyma/management-plane-config/blob/master/resources/control-plane/config/base/runtimes/1.24/tracing.yaml) and [kyma2.0](https://github.tools.sap/kyma/management-plane-config/blob/master/resources/control-plane/config/base/runtimes/2.0/tracing.yaml). The only difference is that Kyma 2.0 adds label: `overrides-plan-preview: "true"`
