### ISSUE TITLE
Compass Runtime Agent should reconcile the mTLS secret in `istio-system`

### ISSUE THREAD

**Issue by janmedrek** [kyma-project/kyma#12573]
**Description**

Right now there is no component responsible for reconciliation of mTLS secret in `istio-system`, in order to provide a stable environment Compass Runtime Agent should handle that.

**Reasons**
We want our components to be fully reconciled.

**Acceptance Criteria**
- mTLS secret in `istio-system` is recreated if removed/modified

**Comment by akgalwas** [comment]
The fix has been implemented. We are in progress of testing the [proposed solution](https://github.com/kyma-project/kyma/pull/12626).
