### ISSUE TITLE
Clean up Application Connector charts

### ISSUE THREAD

**Issue by franpog859** [kyma-project/kyma#12575]
**Description aka Acceptance Criteria**

1. [probably will be dropped] move Compass Runtime Agent to Application Connector (namespace, charts, and so on) - it's just a part of Application Connector and it should be there in a first place
1. move all Application Connector components to `kyma-system` namespace  - components created by Application Operator are removed, Application Operator will be removed soon. There is no reason to keep Application Connector components in a separate namespace
1. get rid of `disableLegacyConnectivity` flag from charts. Clean up the spaghetti modes from charts and replace them with just one `compassMode` flag. It should distinguish open-source mode and Compass one
1. update the documentation with these changes wherever it's necessary 

**Reasons**

There are a lot of old technical decisions present that are no longer relevant to the current project. Keep it clean and do not leave the mess

**Comment by janmedrek** [comment]
Subset of tasks from: https://github.com/kyma-project/kyma/issues/12353
