### ISSUE TITLE
Fast-integration test fails to update label definition with key scenarios

### ISSUE THREAD

**Issue by franpog859** [kyma-project/kyma#12583]
**Description**

**Sometimes** the fast-integration test fails while trying to register/ unregister Kyma resources from Compass. It fails while either assigning SKR to a scenario or unregistering Kyma resources from Compass. In both cases, it fails with this kind of error: `Error: Error when setting runtime 123123123-123-123-1231-123123123 label scenarios and value test-123: Error: Error calling Director API: GraphQL responded with errors: Invalid data [reason=input value=[test-123], key=scenarios, is not valid against JSON Schema={"items":{"enum":["DEFAULT","123123-e2e-test", ...` 

Ok, so after some investigation, @pankrator found the potential issue:
>Is it possible to execute jobs in parallel. If so, the `updateLabelDefinitions` mutation contains all the current scenarios. In your code you built the new array of scenarios by first request them and then update label definitions. So in case there are multiple requests doing the same thing, they might end up updating different label definitions.
Can you check if there are 2 e2e test jobs executing at approximately the same time and at least one them failing? If this is the case, then perhaps the problem is the update label definition executing at the same time with different input as you don’t add, but rather override label definitions.

Some time ago, @ataleksandrov from CMP team introduced [new Director API](https://github.com/kyma-incubator/compass/pull/2085) with [a specific error](https://github.com/kyma-incubator/compass/pull/2089) that prevents lost updates. We should use it in our tests and check if it could be useful also in the KEB area as it operates on such calls too

**Expected result**

All the tests and components use the new Director API. Tests don't fail while updating scenarios in Director

**Actual result**

Here you can find some logs: 
- [log1](https://status.build.kyma-project.io/view/gs/kyma-prow-logs/logs/skr-trial-integration-dev/1427073930031534080)
- [log2](https://status.build.kyma-project.io/view/gs/kyma-prow-logs/pr-logs/pull/kyma-project_kyma/12555/pre-main-kyma-integration-k3d-compass-dev/1458149615105740800)

**Steps to reproduce**

Run multiple fast-integration tests with Compass flow and keep your fingers crossed that it occurs

**Comment by pbochynski** [comment]
I downgraded hydra-maester from v0.0.24 to v0.0.21 and it works again.

**Comment by Maladie** [comment]
We are working on the fix: https://github.com/kyma-project/kyma/pull/12620
