### ISSUE TITLE
Helm broker doesn't deploy functions properly

### ISSUE THREAD

**Issue by KarolGrzyb** [kyma-project/kyma#126]
Confirm these statements before you submit the issue:

- [x] I have searched open and closed issues for duplicates.
- [x] I have read the contributing guidelines.
---

**Description**
[lambdatest-0.0.1.zip](https://github.com/kyma-project/kyma/files/2262421/lambdatest-0.0.1.zip)
Problem can be reproduced with example bundle above.

There is a strange problem with Helm Broker - when it is used to do the deploy using Service Catalog on UI - lambda function is created, but no deployment/pods are created based on it. However, when same chart definition is deployed using `helm install` in terminal everything works correctly, after function resource is created also deployment and pod are present on cluster. We experienced this problem both locally and on real cluster. I haven't noticed any information what could go wrong in logs.

**Comment by PK85** [comment]
cannot reproduce. Locally your example works and produces deployment and pod

**Comment by KarolGrzyb** [comment]
I'am still able to reproduce it. Last test was done yesterday on master branch.

**Comment by derberg** [comment]
@mszostok @aszecowka Hi guys, could you please take a look

**Comment by lszymik** [comment]
It is working in the newest version.

**Comment by brendandobbs** [comment]
@KarolGrzyb, if you experience the issue again can you check if there is anything in the cluster event logs e.g. `kubectl get events -w`. Maybe you're reached a resource (e.g. memory) limit that prevents the deployment.
