### ISSUE TITLE
CRDs are deleted before reconciliation deletion is invoked in SKR DEV

### ISSUE THREAD

**Issue by varbanv** [kyma-project/kyma#12602]
**Description**
CRDs start disappearing before the call to reconciler is made to delete the SKR.

**Expected result**

CRDs are deleted last by the reconciler.

**Actual result**

CRDs are deleted before the reconciler execution.

**Steps to reproduce**

Delete an SKR via the BTP cockpit.

**Troubleshooting**

**Comment by ksputo** [comment]
https://github.com/kyma-project/control-plane/issues/1080

**Comment by varbanv** [comment]
KEB now waits for the reconciler delete process.
