### ISSUE TITLE
Use a label to distinguish between different publisher proxy types

### ISSUE THREAD

**Issue by pxsalehi** [kyma-project/kyma#12606]
**Description**

Our [current approach](https://github.com/kyma-project/kyma/pull/12312) for figuring out the backend type of the existing publisher proxy in the cluster, relies on fetching the deployment and figuring our from the env vars, etc, what backend type it has. A simpler alternative, could be to add the proper labels to the publisher proxy when it is created by the eventing backend controller, and later simply, query using that label. 

As the publisher proxy deployment is watched by the eventing backend controller, any manual label changes on the deployment will be undone, by the backend controller.

**Comment by VladislavPaskar** [comment]
Should work on that after reconciler gets more stable

**Comment by radufa** [comment]
Will be implemented in two steps, without touching the "component" reconciler:
- first, just label the EEP deployment with the corresponding label
- second (later in a new version) cleanup the code and use only the label to identify (find) the EPP deployment.

**Comment by VladislavPaskar** [comment]
The second part of the comment above is done here: https://github.com/kyma-project/kyma/issues/13656
