### ISSUE TITLE
#12546 recommends kubernetes v1.19 but Kyma CLI uses v1.20 as default

### ISSUE THREAD

**Issue by johgoe** [kyma-project/kyma#12615]
Kyma CLI default ist v1.20. The documentation should not recommend older versions (#12546), if the default in Kyma CLI is already newer.  

For local installations you should recommend  K3ds built-in Docker registry instead of Kyma's built-in Docker registry, which is working fine and already installed by Kyma CLI.

For real kind of installations it's basically wrong to recommend docker instead of containerd, because the base product kubernetes does not.

**Comment by pbochynski** [comment]
Thanks for your report. For local installation, we already use k3d registry. We do not recommend docker instead of contained. 
We are switching our test pipelines and production profiles from 1.19 to 1.20. The documentation will be updated when we are complete.
