### ISSUE TITLE
OKLog Documentation

### ISSUE THREAD

**Issue by akrausesap** [kyma-project/kyma#1262]
**Description**

Hi Colleagues,

the documentation of OKLog (https://kyma-project.io/docs/latest/components/logging#details-access-ok-log) contains a minor bug. It sais:

"Access the OK Log UI at http://localhost:7650". However it should say "Access the OK Log UI at http://localhost:7650/ui".

Cheers

Andreas

**Comment by joek** [comment]
It seems the port forwarding command is not correct too.

**Comment by phoenix086** [comment]
pls also adapt the port-forwarding command, the service name is incorrect, it should be like this:

kubectl port-forward -n kyma-system svc/logging-oklog 7650:7650

**Comment by venturasr** [comment]
The url issue was fixed in PR #1646
