### ISSUE TITLE
Update prometheus-operator to support slackConfigs

### ISSUE THREAD

**Issue by tr32** [kyma-project/kyma#12649]
**Description**

The `prometheus-operator` got updated and supports e. g. `slackConfigs`, the current version in kyma [prometheus-operator/v0.43.2](https://github.com/prometheus-operator/prometheus-operator/commits/v0.43.2) does not have `slackConfigs` key. 

More information about `prometheus-operator ` can be found here: [prometheus-operator/alerting](https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/user-guides/alerting.md)

**Reasons**

Support slack notifications and support new keys in `AlertmanagerConfig `

See https://kyma-project.io/docs/kyma/latest/03-tutorials/00-observability/obsv-04-send-notifications/

**Attachments**

**Comment by a-thaler** [comment]
Hi @tr32 , thanks for your feedback. The upgrade of the prometheus stack we have on our plate and will do that as next most important topic after the kyma2 finalizations. I added your criteria to https://github.com/kyma-project/kyma/issues/11567 and would like to close this ticket her in favor of the linked one.
