### ISSUE TITLE
Cloud Events URL is missing in InfoResponse and in Kyma Docu

### ISSUE THREAD

**Issue by k15r** [kyma-project/kyma#12651]
## Description

The InfoResponse available from the application connection connector-service does not contain information about the `/publish` endpoint ( this endpoint allows the user to directly send CloudEvents)
 
also the documentation should be updated to show it here: 
https://kyma-project.io/docs/kyma/latest/03-tutorials/00-application-connectivity/ac-02-get-client-certificate/#get-the-csr-information-and-configuration-details-from-kyma

**Comment by alexandra-simeonova** [comment]
The different URLs for publishing cloud and legacy events are documented [here](https://kyma-project.io/docs/kyma/main/03-tutorials/00-eventing/evnt-01-send-event-outside-cluster#use-the-certificates-generated-to-send-an-event-to-kyma), while in the [AC tutorial]( https://kyma-project.io/docs/kyma/latest/03-tutorials/00-application-connectivity/ac-02-get-client-certificate#get-the-csr-information-and-configuration-details-from-kyma) in this issue, the URL returns the list of subscriptions for events of that particular application. So it doesn't look like anything needs to be changed in the Application Connectivity tutorial. I might be wrong though.

**Comment by raypinto** [comment]
Not relevant anymore since application connectivity in OSS is obsolete.
