### ISSUE TITLE
Enhance the KO environment for subscription manager

### ISSUE THREAD

**Issue by radufa** [kyma-project/kyma#12666]
i know this is will not be easy, but think about a way to:
- either update this whenever a new epp is released (maybe a make target that takes care of it)
- or load automatically the latest image
- or just have ko compile it for you

_Originally posted by @k15r in https://github.com/kyma-project/kyma/pull/12653#discussion_r753310748_

**Comment by k15r** [comment]
a viable solution was merged here: #12653
