### ISSUE TITLE
rename eventing-controller's make target `test-local-local` 

### ISSUE THREAD

**Issue by FriedrichWilken** [kyma-project/kyma#12678]
In `eventing-controller` the make target name `make test-local-local` [(here)](https://github.com/kyma-project/kyma/blob/ceeb73d8a841c5386ae8f9d050779f347a83e16f/components/eventing-controller/Makefile#L71) is causing ongoing confusion.

- [x] Rename the build flag `local` to `debug`. This should make the intention of this flag more clear
- [ ] Check if this target is needed at all.

**Comment by k15r** [comment]
Check if we really need those targets. The intention was to run unit tests with both scenarios ( with `local` build-flag and without it). Currently tests fail with the buildflag, but the flag is only meant to be used in a dev setup and will not be active when a shippable binary is generated.
