### ISSUE TITLE
CommerceMock tests on SKR-nightly return various internal errors

### ISSUE THREAD

**Issue by Ressetkk** [kyma-project/kyma#12673]
**Description**
CommerceMock tests return various Internal errors upon calling the `ServiceInstances` mutating webhook:
```
 body: {
      kind: 'Status',
      apiVersion: 'v1',
      metadata: {},
      status: 'Failure',
      message: 'Internal error occurred: failed calling webhook "mutating.serviceinstances.servicecatalog.k8s.io": Post "https://service-catalog-catalog-webhook.kyma-system.svc:443/mutating-serviceinstances?timeout=30s": context deadline exceeded (Client.Timeout exceeded while awaiting headers)',
      reason: 'InternalError',
      details: [Object],
      code: 500
    },
```
The problem seems to be the Service Catalog not responding correctly (timing out) to the requests. This problem started happening after the runtime had issues with the deprovisioning loop, which @piotrmiskiewicz helped with. 

SKR nightly is always registered to compass with scenario name `skr-nightly`. Every time the SKR nightly is provisioned, a new runtime is registered under the same name. Maybe this approach is incorrect?

**Logs**
https://status.build.kyma-project.io/view/gs/kyma-prow-logs/logs/skr-azure-nightly/1462950293535723520

**Related issues**
https://github.com/kyma-project/test-infra/issues/4127

**Comment by adamwalach** [comment]
The same issue was reported here: https://github.com/kyma-project/kyma/issues/12670
