### ISSUE TITLE
kyma-preview-integration-dev test fails

### ISSUE THREAD

**Issue by pbochynski** [kyma-project/kyma#12670]
**Description**

Such error is reported during creating fixture for commerce mock (create service binding in skr-test namespace):
```
    body: {
      kind: 'Status',
      apiVersion: 'v1',
      metadata: {},
      status: 'Failure',
      message: 'Internal error occurred: failed calling webhook "mutating.servicebindings.servicecatalog.k8s.io": Post "https://service-catalog-catalog-webhook.kyma-system.svc:443/mutating-servicebindings?timeout=30s": x509: certificate signed by unknown authority (possibly because of "crypto/rsa: verification error" while trying to verify candidate authority certificate "service-catalog-webhook-ca")',
      reason: 'InternalError',
      details: [Object],
      code: 500
    },
```

**Steps to reproduce**

See logs: https://status.build.kyma-project.io/view/gs/kyma-prow-logs/logs/kyma-preview-integration-dev/1462994334247817216

**Comment by piotrmiskiewicz** [comment]
https://istio.io/latest/docs/ops/common-problems/validation/#invalid-configuration-is-accepted

**Comment by piotrmiskiewicz** [comment]
fixed by https://github.com/kyma-project/kyma/commit/04da27f7a5e17cb8b91dd2e5ba5f35a2f8ac0f52
