### ISSUE TITLE
Observability tests to be integrated into standard test scenario

### ISSUE THREAD

**Issue by a-thaler** [kyma-project/kyma#12692]
**Description**

The fast-integration tests are providing tests for logging and monitoring. Unfortunately are not covered in any upgrade scenario and the monitoring test is isolated so that it often does not get executed.

Goal: Assure that logging and monitoring tests are part of the standard test suite and the standard upgrade tests

Criterias:
- monitoring and logging are executed as part of the regular "npm test" command having well-defined assertions
- monitoring and logging are executed as part of the upgrade tests, preparing and verifying on the non-upgraded and verifying on the upgraded cluster

**Reasons**
Assure that the tests are executed always to detect problems as soon as possible

**Attachments**

**Comment by lindnerby** [comment]
Review & merge order:

1. https://github.com/kyma-project/kyma/pull/13507
2. https://github.com/kyma-project/test-infra/pull/4960
3. https://github.com/kyma-project/kyma/pull/13318
