### ISSUE TITLE
Revamp the Loki Grafana dashboard

### ISSUE THREAD

**Issue by skhalash** [kyma-project/kyma#12728]
**Description**

Add the following information to the Loki dashboard:
1. Some very simple CPU/memory panels (similar to the FluentBit dashboard).
2. How full is the PVC (a gauge would suffice).
3. A graph that shows at what rate logs are being discarded (based on discarded_samples_total and/or discarded_bytes_total counter), which can be useful to detect ingestion rate limiting.

Simplify the existing graphs:
1. In our setup there is only one fake tenant, so we should not have per-tenant-based graphs.
2. Is the Logs panel even useful? 

**Reasons**

Our current Loki dashboard is very detailed, but it's missing some high-level information, which would be useful for a person who is not a Loki expert.

**Attachments**

**Comment by Pranav-SA** [comment]
With PR #12881, a top row with high-level information has been added to the Loki dashboard.

**Achieved:**
- Pod status.
- Error Rate.
- Memory Utilisation.
- CPU Utilisation.
- Volume claimed.
- Active Streams count.
- Other changes include Collapsed rows (except top high-level information row).

**yet to achieve**: Volume metrics are not exposed for rancher/k3d CSI plugin - https://github.com/rancher/rancher/issues/27522

**Comment by skhalash** [comment]
A new stats dashboard was added. The dashboard contains information about logging patterns of both kyma and custom workloads (log rate/pod, error rate/pod, etc.).
