### ISSUE TITLE
Installation fails for fluent-bit daemonset as CPU is insufficient

### ISSUE THREAD

**Issue by a-thaler** [kyma-project/kyma#12720]
**Description**
When starting the installation on a kubernetes cluster with a minWorkerNodes=1, all the components are getting installed on that one initial node. When it fills, kubernetes will spawn a second node where the rest of the components gets applied after a while.

If the logging component with the fluent-bit daemonset gets applied in a late stage, that first initial node is very full with workload and there is no CPU left to deploy a pod there. It will stay in pending state with the message "Insufficient CPU" and the installation times out. That situation do not recover on it's own.

**Expected result**
There are enough resources available, just the workload is distributed in a bad way. I expect that the installation succeeds and fluent-bit gets resources to run a pod on every node.

**Actual result**
One one node fluent-bit cannot start as other workloading is not rescheduling to different nodes.

**Steps to reproduce**
Install kyma on a cluster with initial one node only

**Troubleshooting**
Delete random pods manual from the initial node. They will get re-scheduled indeed on other nodes and fluent-bit can continue.

**Comment by a-thaler** [comment]
Re-opening till the backport is merged

**Comment by chrkl** [comment]
Solved by introducing a priorityClass that gives DaemonSet Pods a higher priority than other pods. In the case of a resource shortage, Deployment or StatefulSet related Pods will be evicted and can be scheduled to another node after the cluster have been scaled up.
