### ISSUE TITLE
Replica sets do not scale down for ORY

### ISSUE THREAD

**Issue by raypinto** [kyma-project/kyma#12732]
**Description**

When upgrading kyma from production profile to evaluation profile, the replica sets do not scale down.

**Expected result**

Replica sets scale down from 3 (as mentioned in the production profile) to 1 (as mentioned in the evaluation profile) for ORY.

**Actual result**

Replica sets do not scale down.

**Steps to reproduce**
- Install kyma 2.0 with production profile
- Upgrade kyma 2.0 with evaluation profile

**Troubleshooting**

After upgrade from production to evaluation profile, the hpa resource created in the production profile is not updated/deleted.
```sh
➜  reconciler git:(main) ✗ k get hpa                        
NAME             REFERENCE                   TARGETS           MINPODS   MAXPODS   REPLICAS   AGE
ory-hydra        Deployment/ory-hydra        30%/75%, 3%/80%   1         3         1          31m
ory-oathkeeper   Deployment/ory-oathkeeper   42%/75%, 2%/80%   3         10        3          31m
```

**Comment by cnvergence** [comment]
This is similar issue, I have checked: https://github.com/kyma-incubator/reconciler/issues/644
Do we support changing from production to evaluation?

**Comment by cnvergence** [comment]
It won't be supported.
