### ISSUE TITLE
Kyma cluster deletion blocked in Gardener due to stuck rafter CRDs

### ISSUE THREAD

**Issue by varbanv** [kyma-project/kyma#12738]
**Description**

When deleting a Kyma cluster on SKR Dev, Gardener fails to delete the cluster due to stuck CRDs.

**Expected result**
Deletion proceeds without any delays.

**Actual result**
Deletion takes a long time.

**Steps to reproduce**
Delete a Kyma cluster in SKR dev.

**Troubleshooting**
Gardener reports that the following resources are stuck in deleting state:
```
*v1.CustomResourceDefinition /clusterassets.rafter.kyma-project.io 
*v1.CustomResourceDefinition /clusterbuckets.rafter.kyma-project.io 
*v1.CustomResourceDefinition /clusterservicebrokers.servicecatalog.k8s.io 
*v1.CustomResourceDefinition /usagekinds.servicecatalog.kyma-project.io
```

**Comment by tobiscr** [comment]
will be addressed by deletion reconciler: https://github.com/kyma-incubator/reconciler/issues/333

**Comment by pbochynski** [comment]
It is technically not blocking the release, but still very important and we should keep working on it.
