### ISSUE TITLE
Job kyma-periodic-gardener-gcp-busola-kyma always fails 

### ISSUE THREAD

**Issue by pbochynski** [kyma-project/kyma#12734]
**Description**

The job kyma-periodic-gardener-gcp-busola-kyma fails. The job tries to undeploy kyma and deploy it again. The deployment fails with:
```
Deployed Components: 1/2
Could not deploy the following components:
- cluster-essentials

Error: Kyma deployment failed.
```
See logs: https://status.build.kyma-project.io/job-history/gs/kyma-prow-logs/logs/kyma-periodic-gardener-gcp-busola-kyma

**Comment by pbochynski** [comment]
Probably related to this one: https://github.com/kyma-incubator/reconciler/issues/416

**Comment by tobiscr** [comment]
Kyma CLI is not yet fully integrated:

* `kyma deploy` is calling the deploy-cmd and installs pre-requisites in parallel
* `kya undeploy` is still using the CLI specific deletion logic, integration with reconciler is ongoing (requires to hold the cluster config inside the cluster - [implementation in progress](https://github.com/kyma-incubator/reconciler/issues/334))

**Comment by pbochynski** [comment]
It is fixed now.
