### ISSUE TITLE
Add a note about backing up Secrets

### ISSUE THREAD

**Issue by mmitoraj** [kyma-project/kyma#12733]
**Description**
Add a NOTE about backuping Secrets from `user-ns`, `kyma-system`, `istio-system`, `kyma-integration`. Include a command showing how to do it.

**Area**

Security

**Reasons**

**Assignees**

@kyma-project/technical-writers

**Attachments**

**Comment by NHingerl** [comment]
@a-thaler this ticket is in the OS github, it's not about managed Kubernetes.

**Comment by a-thaler** [comment]
Usually you run your cluster on a managed offering like GKE where the apiserver content is durable.

**Comment by a-thaler** [comment]
Without a proper motivation why a user should backup secrets explicitly (and not also configmaps, for example) we should close the ticket.
We anyway already have a documentation on general backup of apiserver content https://kyma-project.io/docs/kyma/latest/04-operation-guides/operations/10-backup-kyma/
