### ISSUE TITLE
Kyma-installer always update status of one instance of CR

### ISSUE THREAD

**Issue by mwieczorek** [kyma-project/kyma#1274]
**Description**
I'd like to install kyma using a resource of kind `Installation` but with a different name than 'kyma-installation'.
It's not possible because installer wants to update always the same resource (kyma-installation).
If the `kyma-installation` is deleted we get an error:

`E1015 13:14:19.416075       1 controller.go:284] installation.installer.kyma-project.io "kyma-installation" not found`

**Expected result**
I can use CR of type Installation with different names.

**Actual result**
Error as above

**Steps to reproduce**
Change name of resource of type Installation from the default one and try to install.

**Troubleshooting**

**Comment by strekm** [comment]
we agreed to simple implementation: installer looks for any cr, if finds more than one fails with error

**Comment by jakkab** [comment]
This issue should be closed as its implementation would be too costly right now. Another issue will be raised if required.
