### ISSUE TITLE
Investigate EventMesh 422 error

### ISSUE THREAD

**Issue by k15r** [kyma-project/kyma#12740]
During long running tests with EventMesh as a backend we experience the following error

```
time="2021-11-30T05:00:04Z" level=info msg="Event dispatched" duration=191.187908ms id=59fd12fd-82f2-44508eae-419d443c4024 responseB
ody="{\"error\":{\"code\":\"SPOOL_LIMIT_EXCEEDED\",\"message\":\"Queue or Topic spool limit exceeded\"}}" source=/default/my.kyma/gaurav-10-1 statusCode=422 type=sap.kyma.custom.mpgauravskrloadtest.stagecomexternalsolutionorder.created.v1
```

## Acceptance
- [ ] investigate the actual reason and check if we can expose this information in the subscription
- [ ] document the reason and check for similar limitations and also document them

**Comment by k15r** [comment]
Contact @abbi-gaurav for details

**Comment by VladislavPaskar** [comment]
Possible reason: https://answers.sap.com/questions/13479462/422-unprocessable-entity-queue-or-topic-spool-limi.html

**Comment by k15r** [comment]
this behaviour could not be replicated lately, closing for now
