### ISSUE TITLE
Distinguish function `unhealthy` state  from `pending` 

### ISSUE THREAD

**Issue by kwiatekus** [kyma-project/kyma#12777]
**Description**

In case availibility of minimum amount of replicas is not met the function enters Unhealthy state.
We should distinguish between the true unhealthy state ( replicas restarting ) from startup case.

When Function is starting and replicas are "booting up" we should mark the function as `pending`
When Function replicas are crashing we should mark the function as `unhealthy`

 - [ ] adjust serverless code and tests
 - [ ] adjust [kyma documentation](https://kyma-project.io/docs/kyma/latest/05-technical-reference/svls-02-function-processing-stages/)
 - [ ] Kyma dashboard UI

**Reasons**

`Unhealthy`doesn't really reflect the initial startup case. It becomes a false alarm  for users who have just created a function..

**Attachments**

**Comment by valentinvieriu** [comment]
This is an error state. I think we need to keep the user aware that this is an error. We can clarify via tooltip what is the detail.
We track this under this topic https://github.com/kyma-project/busola/issues/620
I will close this one

**Comment by valentinvieriu** [comment]
Sorry, If you plan to change this in the CRD then let's keep it open, if you want to change this in the UI, we track this in the issue above

**Comment by grego952** [comment]
The `pending` status is ok when the function starts, but when the health check fails I guess we should stick to `unhealthy`. Can we introduce additional status - `pending` only when the function starts?

**Comment by kwiatekus** [comment]
Closing as irrelevant
See explenation here:
https://github.com/kyma-project/busola/issues/731#issuecomment-1059031104
