### ISSUE TITLE
PVC does not delete on Reconciler Delete Action - ORY fails on reinstall

### ISSUE THREAD

**Issue by raypinto** [kyma-project/kyma#12770]
**Description**

Since PVC is not deleted on reconciler delete action, when kyma is installed again on the same cluster, ORY fails since `ory-hydra` pod goes into `CrashLoopBackoff` state!!

**Expected result**

Kyma installs successfully!

**Actual result**

ORY hydra pod fails since the existing cookies on the PVC are connected to the previous install and are not updated.

**Steps to reproduce**

- Install kyma 2.0 with production profile using reconciler: `./bin/mothership-darwin local --kubeconfig <kubeconfig_path> --value global.ingress.domainName=<domain_name>,global.domainName=<domain_name> --profile production`
- Delete kyma 2.0 using reconciler: `./bin/mothership-darwin local --kubeconfig <kubeconfig_path> --value global.ingress.domainName=<domain_name>,global.domainName=<domain_name> --profile production --delete true`
- Install kyma 2.0 again with production profile using reconciler: `./bin/mothership-darwin local --kubeconfig <kubeconfig_path> --value global.ingress.domainName=<domain_name>,global.domainName=<domain_name> --profile production`

**Troubleshooting**

The PVC data-ory-postgresql-0 persists data from the previous installation which clashes with the new installation and hence `ory-hydra` pod fails to come up. The PVC deletion should be taken care of with the deletion of the Stateful Set by the reconciler. As a temporary alternative, we could fix this by deleting the PVC as part of the Post Delete action, but that is subject to discussion.

**Comment by strekm** [comment]
closing it as api-gateway will be reworked as module + ORY is deprecated
