### ISSUE TITLE
Kyma 2.0.0-rc-8  auth for jaeger

### ISSUE THREAD

**Issue by johgoe** [kyma-project/kyma#12774]
https://kyma-project.io/docs/kyma/latest/04-operation-guides/security/sec-06-access-expose-kiali-grafana 

writes

```
kubectl -n kyma-system delete pod -l app.kubernetes.io/name=auth-proxy,app.kubernetes.io/instance=tracing
```

but the pod for jaeger only matches to

```
kubectl -n kyma-system delete pod -l app.kubernetes.io/component=auth-proxy,app.kubernetes.io/name=tracing
```

Kiali and grafana are working fine

**Comment by chrkl** [comment]
Changed docs to use the `kubectl rollout restart` command instead of deleting pods.
