### ISSUE TITLE
Upgrade test fails (periodic-main-kyma-incubator-reconciler-kyma1-kyma2-upgrade)

### ISSUE THREAD

**Issue by pbochynski** [kyma-project/kyma#12776]
**Description**
periodic-main-kyma-incubator-reconciler-kyma1-kyma2-upgrade fails frequently on getting access token:
```
  1) Upgrade test tests
       function should be reachable through secured API Rule:
     Error: Error when requesting bearer token from https://oauth2.grd7quvft.kyma-prow.shoot.canary.k8s-hana.ondemand.com/oauth2/token: 401 Unauthorized
      at OAuthToken.getToken (lib/oauth.js:69:27)
      at processTicksAndRejections (internal/process/task_queues.js:95:5)
      at async checkFunctionResponse (test/fixtures/commerce-mock/index.js:123:23)
      at async Context.<anonymous> (upgrade-test/upgrade-test-tests.js:29:5)
```
It looks like OAuth client created before upgrade doesn't work. This is a test code:
https://github.com/kyma-project/kyma/blob/2b1f67bebf1f1f674a7160afc3ecccccd90defea/tests/fast-integration/test/fixtures/commerce-mock/index.js#L116-L123

**Expected result**

Access token can be requested after upgrade.

**Actual result**

401 response from OAuth2 server (ory-hydra)

**Steps to reproduce**
Rerun the job https://status.build.kyma-project.io/?job=periodic-main-kyma-incubator-reconciler-kyma1-kyma2-upgrade
It fails frequently. Sample logs from the last 24 hours: 
- https://storage.googleapis.com/kyma-prow-logs/logs/periodic-main-kyma-incubator-reconciler-kyma1-kyma2-upgrade/1466633350671241216/build-log.txt
- https://storage.googleapis.com/kyma-prow-logs/logs/periodic-main-kyma-incubator-reconciler-kyma1-kyma2-upgrade/1466572952261627904/build-log.txt
- https://storage.googleapis.com/kyma-prow-logs/logs/periodic-main-kyma-incubator-reconciler-kyma1-kyma2-upgrade/1466512553529053184/build-log.txt
- https://storage.googleapis.com/kyma-prow-logs/logs/periodic-main-kyma-incubator-reconciler-kyma1-kyma2-upgrade/1466452154934890496/build-log.txt

**Comment by veichtj** [comment]
Job fails now with a different reconciler issue, which is in progress --> https://github.com/kyma-incubator/reconciler/issues/557

**Comment by pbochynski** [comment]
Now the job fails due to a different reason: https://github.com/kyma-project/kyma/issues/12977
