### ISSUE TITLE
Installation instruction for Kyma 2.0 - Windows

### ISSUE THREAD

**Issue by lechnerc77** [kyma-project/kyma#12809]
**Description**

Installation of Kyma 2.0 needs the corresponding CLI version. Currently the installation instruction  <https://kyma-project.io/docs/kyma/latest/04-operation-guides/operations/01-install-kyma-CLI/> for Windows points to an outdated version for 2.0:
![2021-12-07 17_13_11-Install Kyma CLI - Docs _ Kyma - An easy way to extend enterprise applications o](https://user-images.githubusercontent.com/22294087/145065999-494b5fcf-2e9b-475f-883d-99fefe95f872.png)

Using this version would cause the installation of Kyma 2.0 to fail. 

In addition the documentation for release 1.2x must be adopted in the corresponding area (https://kyma-project-old.netlify.app/docs/cli/#installation-installation), as the installation of chocolatey will probably fail once version 2.0 of the CLI is available. Here the installation command must comprise the version.

**Area**

Operation Guides -> Operations -> Install Kyma CLI 

**Reasons**

Not an improvement, it is an error

**Assignees**

@kyma-project/technical-writers

**Attachments**

**Comment by a-thaler** [comment]
I guess we should not specify the version but just formulate it like in the "other" tab.

About the 1.2x releases: The CLI still contains the old "install" command which is using by default the latest 1.2x version. When releasing the CLI we will maintain both defaults until it gets decided that 1.2x is not supported anymore.

**Comment by lechnerc77** [comment]
Sounds good to me

**Comment by NHingerl** [comment]
Can I drop the line `${KYMA_VERSION}=1.2.0` completely, or should it be replaced by <something else> ?
