### ISSUE TITLE
Links in auto-generated command docs don't work

### ISSUE THREAD

**Issue by NHingerl** [kyma-project/kyma#12817]
**Description**

For example, in [kyma.md](https://github.com/kyma-project/cli/blob/main/docs/gen-docs/kyma.md), when I click at `kyma deploy`, I don't see the documentation for `kyma deploy`.

**Expected result**

I see the page of the command/flag that I selected.

**Actual result**

The URL shows the anchor. The content of the page doesn't change

**Steps to reproduce**

In the github folder, open a command .md file and click a link to any other command.

**Troubleshooting**

The linking pattern in the following script follows the old website pattern. We must adjust it to follow the markdown/github standard

https://github.com/kyma-project/cli/blob/main/cmd/gendocs/gendocs.go .

**Comment by rakesh-garimella** [comment]
The issue has been fixed via this PR: https://github.com/kyma-project/cli/pull/1119
