### ISSUE TITLE
Test upgrade paths

### ISSUE THREAD

**Issue by pbochynski** [kyma-project/kyma#12819]
**Description**

The Kyma CI should contain pipelines that verify:
- [x] upgrade from the previous minor release to the current release branch used for patch releases (version 1.24.8 -> release-2.0 branch)
- [x] upgrade from the previous minor release to the main branch (release 2.0.0 -> main branch)

The upgrades should run on:
- [x] k3s
- [x] Gardender cluster

**Comment by tobiscr** [comment]
We agreed with @a-thaler  to use for the test-scenario always the CLI version of the TARGET Kyma release version

**Comment by pbochynski** [comment]
@ruanxin Please provide update here.

**Comment by tobiscr** [comment]
Pipelines accessible in PROW

Upgrade Kyma 1 to Kyma 2 using Gardener cluster: [kyma-upgrade-gardener-kyma-to-kyma2](https://status.build.kyma-project.io/?job=kyma-upgrade-gardener-kyma-to-kyma2)
Upgrade Kyma 2 to Kyma-latest using Gardener cluster: [kyma-upgrade-gardener-kyma2-to-main](https://status.build.kyma-project.io/?job=kyma-upgrade-gardener-kyma2-to-main)
Upgrade Kyma 1 to Kyma 2 using K3d cluster: [kyma-upgrade-k3d-kyma-to-kyma2](https://status.build.kyma-project.io/?job=kyma-upgrade-k3d-kyma-to-kyma2)
Upgrade Kyma 2 to Kyma-latest using K3d cluster: [kyma-upgrade-k3d-kyma2-to-main](https://status.build.kyma-project.io/?job=kyma-upgrade-k3d-kyma2-to-main)
