### ISSUE TITLE
Authorization of graphql queries doesn't work.

### ISSUE THREAD

**Issue by magicmatatjahu** [kyma-project/kyma#1281]
**Description**

After creation a `ServiceRole` and `ServiceRoleBinding` for secure a specific query in `/graphql` path, the non-specific users in `ServiceRoleBinding` can query the path for resources.

**Expected result**
 
Users (not specific in `ServiceRoleBinding`) cannot query a specific `/graphql` path for resources.

**Actual result**

Authorizations of the `graphql` queries doesn't work after creation `ServiceRole` and `ServiceRoleBinding`.

**Steps to reproduce**

Create `ServiceRole` and `ServiceRoleBinding` described in [this](https://github.com/kyma-project/kyma/tree/master/resources/core/charts/ui-api#example) example, and then logIn as `user1` in `console` of Kyma and go to `/home/settings/remoteEnvs`.

**Comment by piotrmsc** [comment]
Additionally, after finding the root cause, we should create a test covering this scenario.

**Comment by sjanota** [comment]
For now only authentication on graphql was enabled. There is follow up issue #474 where authorisation will be brought back to live.
