### ISSUE TITLE
APIRules are not reachable when ORY is upgraded from eval to prod profile 

### ISSUE THREAD

**Issue by raypinto** [kyma-project/kyma#12821]
**Description**

APIRules are not reachable when ORY is upgraded from evaluation to production profile in Kyma 2.0. 

**Expected result**

API Rules created when ORY was running with evaluation profile must be reachable after ORY was upgraded to production profile.

**Actual result**

API Rules are not reachable

**Steps to reproduce**

- Install Kyma 2.0 with evaluation profile
- Perform fast integration test: `make ci-pre-upgrade`
- Upgrade Kyma (or just ORY) to production profile.
- Perform fast integration test: `make ci-post-upgrade`

**Troubleshooting**

- The result of the post upgrade fast-integration test:

```   
✓ in-cluster event should be delivered
    1) function should be reachable through secured API Rule
    ✓ order.created.v1 event should trigger the lastorder function
    ✓ service instance provisioned by helm broker should be reachable
    ✓ Should print report of restarted containers, skipped if no crashes happened


  5 passing (5s)
  1 failing

  1) Upgrade test tests
       function should be reachable through secured API Rule:
     Error: Error when requesting bearer token from https://oauth2.rp-ory4.goatz.shoot.canary.k8s-hana.ondemand.com/oauth2/token: 401 Unauthorized
      at OAuthToken.getToken (lib/oauth.js:69:27)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      at async checkFunctionResponse (test/fixtures/commerce-mock/index.js:128:23)
      at async Context.<anonymous> (upgrade-test/upgrade-test-tests.js:29:5)
```

- Restarting hydra-maester pod also does not resolve these tests.
- Also its interesting to see 4 replicasets of ory-hydra even though the upgrade happened just once.

**Comment by cnvergence** [comment]
This is fixed now
