### ISSUE TITLE
Provide clear contribution guide section for backporting fixes to patch releases. 

### ISSUE THREAD

**Issue by pbochynski** [kyma-project/kyma#12822]
**Description**

Document that you need to push also code changes not only image bumps to release branch or find this procedure and review it.

**Comment by pbochynski** [comment]
@Sawthis @arturskorupa Maybe you can take care of this ticket? @mareknawa probably forgot about it ;-)

**Comment by Sawthis** [comment]
@mareknawa https://github.com/kyma-project/community/pull/657/files - is it enough?

**Comment by Sawthis** [comment]
https://github.com/kyma-project/community/pull/672/files

**Comment by mareknawa** [comment]
@Sawthis  yes, it should be enough. The patch-release is also described in the [internal documentation for managed offering](https://github.tools.sap/kyma/documentation/blob/main/how-to-guides/kyma-patch-release.md) the part about open source refers to the document you updated. It looks fine.
