### ISSUE TITLE
Common parsing of the "sink" value of a subscription for eventing backends

### ISSUE THREAD

**Issue by radufa** [kyma-project/kyma#12823]
**Description**

The parsing of the "sink" string and its validation should be identical for both backends (NATS and BEB), cause the 
semantic of the "sync" is not dependent from the backend.
Also common tests for the parsing of subscription's "sink" are necessary, to avoid bugs such: 
- https://github.com/kyma-project/kyma/issues/12810
- https://github.com/kyma-project/kyma/pull/12811

**Comment by raypinto** [comment]
We have a common sink Validator across backends and it was tested. So we can close this issue.
