### ISSUE TITLE
Define test implementation guidelines [5d]

### ISSUE THREAD

**Issue by k15r** [kyma-project/kyma#12820]
## Description
Our components (`eventing-controller`, `event-publisher-proxy`) contain a large number of tests. Unfortunately the way our tests are implemented varies in style and granulatity a lot. This makes it hard to understand and extend theses tests.
The result of this issue should be a guide line for writing tests in our components and should be used in future refactorings and implementation of new tests.

## Acceptance
- [x] get to know ginkgo (as it is the currently used test framework)
  - how does it run tests
  - best practices for the framework
  - shortcomings
  - diff ginkgo framework v1, v2
    - is it worth upgrading 
    - should we wait for v2  
- [x] analyse the currently implemented tests and used libraries
- [x] define an implementation guideline 
- [x] apply the new guideline to at least one (not too simple) test case to be used as an example

**Comment by nachtmaar** [comment]
This is comment is a collection of testing/assertion frameworks used in the eventing code. Please update my comment whenever you want to add something:

Assertion Frameworks (format: library: kyma component)
- `github.com/stretchr/testify/assert`: [epp](components/event-publisher-proxy/pkg/sender/nats_test.go)

**Comment by nachtmaar** [comment]
Task List:

- [ ] Nats Controller Unit Tests @VladislavPaskar 
- [ ] Nats Controller Integration Tests @FriedrichWilken 
- [ ] Improve file eventing-publisher-proxy/pkg/sender/nats_test.go @nachtmaar

**Comment by nachtmaar** [comment]
After a team discussion we decided to get rid of ginkgo for the controller integration tests. For this reason it does not make sense to provide ginkgo best practices or advice on how to move from ginkgo v1 to v2.
