### ISSUE TITLE
We should have a "positive" tests  for "Valid Sink" too

### ISSUE THREAD

**Issue by radufa** [kyma-project/kyma#12835]
Perhaps we should have a "positive" test too, something like:
```
 getSubscriptionWithValidSink(...)
 ```
 which should avoid issues like this: https://github.com/kyma-project/kyma/issues/12810
 If you think that's another issue, please create a new one and link it

_Originally posted by @radufa in https://github.com/kyma-project/kyma/pull/12826#r765944603_

**Comment by k15r** [comment]
closed: duplicate https://github.com/kyma-project/kyma/issues/12812
