### ISSUE TITLE
Test Eventing E2E upgrade and cluster reconciliation [SKR]

### ISSUE THREAD

**Issue by pxsalehi** [kyma-project/kyma#12847]
**Description**

We need to check if we need to have the same automated test as https://github.com/kyma-project/kyma/issues/12846, but for SKR. Also, details of how to upgrade an SKR cluster from inside a Prow job, is unclear. 
Assumption: The upgrade will be done by KEB and it is stable.

Related release test case: https://github.tools.sap/kyma/backlog/issues/1678

## Acceptance
- [ ] fast integration test should accept the `COMPASS_ID` instead of reading it using the gardener kubeconfig
- [ ] Document how to run fast-integration eventing tests on an existing cluster
- [ ] Figure out a way to get these credentials automatically for automated tests
- [ ] Have two jobs with configurable backend (NATS and BEB)

**Comment by VladislavPaskar** [comment]
Possible reason: https://answers.sap.com/questions/13479462/422-unprocessable-entity-queue-or-topic-spool-limi.html

**Comment by VladislavPaskar** [comment]
I can reuse the logic from here: https://github.com/kyma-project/kyma/issues/12848 once it's done, so for now this issue is blocked.

**Comment by nachtmaar** [comment]
@pxsalehi Is this just about figuring out stuff or also about implementing the test ?

**Comment by raypinto** [comment]
Question: Do we need it per PR?

**Comment by nachtmaar** [comment]
@pxsalehi For AC 2:
> Document how to run fast-integration eventing tests on an existing cluster
This is documented here: https://github.com/kyma-project/kyma/blob/main/tests/fast-integration/eventing-test/README.md
Are you missing something where ?

**Comment by VladislavPaskar** [comment]
1. Pre-requisites:
	- [ ] The pre-main-skr-eventing pipeline should be stable and reliable
	- [ ] We need a support of the configurable backend in the fi tests (https://github.com/kyma-project/kyma/issues/13520): 
		- [ ] Setting the first and last backend, be it BEB or NATS ( currently its only NATS)
		- [ ] How to set it ? Env variables in the prowjob
2. Tasks:
	- [ ] Check if the existing eventing fi tests README is complete, if not complete it
	- [ ] Borrow all the env variables from the running pre-main-skr job and add the upgrade flow
	
3. Acceptance criteria
- [ ] Reuse as much logic of the existing(stable) pre-main-skr job as possible to avoid duplicates
- [ ] Documentation is up-to-date with the latest eventing fi tests (all envs and options are listed)
Two(three?) jobs for each of the backend

**Comment by marcobebway** [comment]
Moved to backlog and next grooming to check if it is still needed.
