### ISSUE TITLE
Drop Rafter - Application Connector integration

### ISSUE THREAD

**Issue by janmedrek** [kyma-project/kyma#12844]
**Description**

We need to drop the functionality of uploading docs into the Rafter in Kyma. The feature will be no longer used and the component will be removed. This applies both to Application Registry and Compass Runtime Agent.

**Reasons**

We are dropping the Service Catalog UI and docs will no longer be displayed.

**Acceptance Criteria**
- Application Registry does not depend on Rafter's interfaces
- Compass Runtime Agent does not depend on Rafter's interfaces
- Contract should remain unchanged
- Documentation mentions that the API Spec is not required

**Attachments**
Cleanup script - https://github.com/kyma-project/kyma/pull/14095

**Comment by mvshao** [comment]
This task is now done, but we are waiting for the right time to merge it.

**Comment by janmedrek** [comment]
Before merging - please test the Rafterless cluster with external solutions that integrate with Kyma (i.e. C4C/CC). We need to make sure that this change does not impair the regular flow of those integrations.

**Comment by janmedrek** [comment]
So all that is left is resolving the conflict, provisioning a new cluster, and running the tests. As simple as that. 🙂
