### ISSUE TITLE
Run eventing fast-integration for SKR as a pre-submit job

### ISSUE THREAD

**Issue by pxsalehi** [kyma-project/kyma#12848]
**Description**
Create a Prow job that runs the eventing fast-integration test suite for SKR as a pre-submit job

related missing test case: https://github.tools.sap/kyma/backlog/issues/1679

**Comment by mfaizanse** [comment]
Related PR(s):
- https://github.com/kyma-project/kyma/pull/12882

**Comment by mfaizanse** [comment]
Requested this [feature](https://github.com/kyma-project/control-plane/issues/1252) for the KEB, which would be useful in this job.
