### ISSUE TITLE
Remove Application Operator and Access Service creation in Application Registry

### ISSUE THREAD

**Issue by janmedrek** [kyma-project/kyma#12845]
**Description**

Application Operator and other deprecated and no-longer-used logic in the Application Connector area should be removed.

We can postpone the removal of the Application K8S Go client, for now, the code can be left in the directory and migrated afterward.

**Reasons**

We do have a new way of reaching external applications, thus, we should no longer provision deprecated components in the cluster.

**Acceptance Criteria**

- Application Operator should be removed
- Access Service creation from Application Registry should be removed
- Tests and pipelines adjusted
- Technical documentation should reflect the state (AO no longer there)

> Due to migration reasons we need to make sure that deletion of Application Operator on the cluster will not result in removing the Gateways it has created - this can lead to degradation of setup and can break the already existing workload before it is migrated to the new Central Application Gateway. **Gateways should stay.**

**Comment by majakurcius** [comment]
@franpog859 It seems that what you described in the input for documentation has already been covered by PRs #12259 and #12465.

**Comment by franpog859** [comment]
Yup, it seems so, @majakurcius . I didn't see any information about the upgrade process (the fact that old Gateways will stay but are deprecated and won't be updated). It'll be covered probably on some release notes
