### ISSUE TITLE
Get rid of ginkgo

### ISSUE THREAD

**Issue by kwiatekus** [kyma-project/kyma#12850]
**Description**

Get rid of ginkgo in serverless unit tests

**Reasons**

Improve devx around tests.
Enable external contributions to serverless.
Allow us to run single tests selectively.

**Comment by kwiatekus** [comment]
I still found references in `go.sum`.  Shouldn't those be cleaned up as well? security scanning tools may produce some false positives if we won't clean those references
@dbadura

**Comment by dbadura** [comment]
`go mod why` says that it's indirect import from `sigs.k8s.io/controller-runtime`
