### ISSUE TITLE
[Daily Business] Use semver for image tags

### ISSUE THREAD

**Issue by halamix2** [kyma-project/kyma#12859]
**Description**

Make all images tags to be in the `m.m.p-YYYYMMDD-HHMM-<Short commit hash>` format, e.g. `2.1.0-20220523-1431-abcdef`, or another semantically versioned format, e.g. `2.1.0-20220523.1431.abcdef`

These tags are compatible with semver, and would be usable with the [CNUDIE Component-Descriptor](https://github.com/gardener/component-spec), as well as they would be suitable for the autobumper.

**Reasons**

Using semver for image tagging:
* will be compatible with [CNUDIE Component-Descriptor](https://github.com/gardener/component-spec), which could be used for image signing
* easy to compare with other tag, making image bumping easy (as opposed to hash-only tags)

**Attachments**

**Comment by pbochynski** [comment]
@Halamix2 This format is not [semver](https://semver.org/) compliant. Please adjust the ticket.
