### ISSUE TITLE
Compass Runtime Agent should label resources managed by it

### ISSUE THREAD

**Issue by janmedrek** [kyma-project/kyma#12871]
**Description**

Compass Runtime Agent should put a label that indicates synchronized applications are managed by the component.

**Reasons**

We need a way to differentiate between user-created applications and the ones synced with the Compass.

**Acceptance Criteria**
- Compass Runtime Agent should put a label on managed applications
  -  consider using such label: `applicationconnector.kyma-project.io/managed-by: compass-runtime-agent`

**Comment by franpog859** [comment]
We can differentiate between user-created applications and the ones synced with the Compass by looking at its `application.spec.compassMetadata`. This field is `nil` [when it's not managed by Compass Runtime Agent](https://github.com/kyma-project/kyma/blob/main/components/compass-runtime-agent/internal/kyma/service.go#L110-L119)

Do we have to implement additional labeling in this case?

**Comment by franpog859** [comment]
PR with the feature - https://github.com/kyma-project/kyma/pull/12876
PR with the cherry-pick - https://github.com/kyma-project/kyma/pull/12916

Example application:
```yaml
apiVersion: applicationconnector.kyma-project.io/v1alpha1
kind: Application
metadata:
  creationTimestamp: '2021-12-16T11:12:50Z'
  finalizers:
    - finalizer.applicationconnector.kyma-project.io
  generation: 2
  labels:
    applicationconnector.kyma-project.io/managed-by: compass-runtime-agent
  managedFields:
    - apiVersion: applicationconnector.kyma-project.io/v1alpha1
...
```
