### ISSUE TITLE
Enable nightly links validation on repositories

### ISSUE THREAD

**Issue by michal-hudy** [kyma-project/kyma#1290]
**Description**

Currently governance job is executed on master when PR is merged. That validation should be disabled, because it sometimes blocks PR when `external service` is not available. Instead of that nightly links validation should be enabled on all repositories.

AC:
 - [ ] Nightly links validation enabled on all repositories
 - [ ] Links validation on master disabled on all repositories
 - [ ] Send notification about failed validation to technical writers

**Comment by mjasinski5** [comment]
Review: @michal-hudy
