### ISSUE TITLE
Upgrade test fails constantly

### ISSUE THREAD

**Issue by pbochynski** [kyma-project/kyma#12917]
**Description**

Fails on Kyma 1.24.8 installation:

Logs: https://storage.googleapis.com/kyma-prow-logs/logs/kyma-upgrade-k3d-kyma-to-kyma2/1473201622132723712/build-log.txt
Build status: https://status.build.kyma-project.io/job-history/gs/kyma-prow-logs/logs/kyma-upgrade-k3d-kyma-to-kyma2

**Comment by pbochynski** [comment]
Kyma 1.24 doesn't work on K3d out of the box. This plan should be disabled/removed until we test upgrade from 2.0->2.1.

**Comment by Sawthis** [comment]
https://github.com/kyma-project/test-infra/pull/4602

**Comment by Sawthis** [comment]
The plan was removed on 23 December.
