### ISSUE TITLE
Eventing Troubleshooting document 

### ISSUE THREAD

**Issue by alexandra-simeonova** [kyma-project/kyma#12924]
**Description**

Create documentation on how to troubleshoot in Kyma within the system namespace "kyma-system" and the logs of the container "eventing-publisher-proxy" inside the pod "eventing-publisher-proxy-*".

The troubleshooting guide should be linked here: https://kyma-project.io/docs/kyma/2.0/04-operation-guides/troubleshooting/
And follow the structure: 
- Symptom (What exactly is the error the end user will see?)
- Cause (Why did the problem occur?)
- Remedy (How can the user solve this?)  

**Area**

Documentation

**Assignees**

@kyma-project/technical-writers

**Attachments**

**Comment by raypinto** [comment]
Will be taken care of as part of [this issue](https://github.com/kyma-project/kyma/issues/14195).
