### ISSUE TITLE
Event delivery for existing subscriptions is broken when NATS server is restarted

### ISSUE THREAD

**Issue by marcobebway** [kyma-project/kyma#12930]
**Description**

Event delivery for existing subscriptions is broken when NATS server is restarted.

**Expected result**

Event delivery for existing subscriptions should continue to be working after NATS server is restarted.

**Steps to reproduce**

1. Scale down the NATS StatefulSet replicas to one (or use the Eventing [evaluation](https://github.com/kyma-project/kyma/blob/8238d01397fa9abb08d0ff0913f620676b83f795/resources/eventing/profile-evaluation.yaml#L21) profile).
2. Create Kyma subscriptions and their corresponding subscriber(s).
3. Publish Events.
4. Check that Events are reaching the subscriber(s).
5. Delete the NATS server pod.
6. Publish Events.
7. The subscriber(s) will not receive Events from already existing subscriptions.

**Troubleshooting**

When the NATS server pod is restarted, the Eventing controller does not recreate the NATS subscriptions on the new NATS server instance.

**Comment by k15r** [comment]
Is this only about subscriptions?
Is publishing also affected?

**Comment by pxsalehi** [comment]
We need to look into that too. At the moment with the default configs, EPP seems to recover (first publish request fails, but when repeated, it works). I can check it as part of this PR.
