### ISSUE TITLE
kyma-preview-integration-dev plan fails 

### ISSUE THREAD

**Issue by pbochynski** [kyma-project/kyma#12945]
**Description**
Provisioning fails:
```
 1) Execute SKR test
       "before all" hook: Provision SKR in "Execute SKR test":
     Error: before hook failed: operation didn't succeed in 2h: {"state":"failed","description":"Operation created : call to the provisioner service failed"}
      at Context.<anonymous> (skr-test/test.js:31:19)
      at processTicksAndRejections (internal/process/task_queues.js:95:5)
```

Job history: https://status.build.kyma-project.io/job-history/gs/kyma-prow-logs/logs/kyma-preview-integration-dev
Executions with this failure:
- https://storage.googleapis.com/kyma-prow-logs/logs/kyma-preview-integration-dev/1476100754761584640/build-log.txt
- https://storage.googleapis.com/kyma-prow-logs/logs/kyma-preview-integration-dev/1475859160355573760/build-log.txt
- https://storage.googleapis.com/kyma-prow-logs/logs/kyma-preview-integration-dev/1475617565819539456/build-log.txt

**Comment by pbochynski** [comment]
Now the pipeline fails due to missing ENV variable KCP_KEB_API_URL:

```
> fast-integration-tests@0.0.1-alpha.12 test-skr /home/prow/go/src/github.com/kyma-project/kyma/tests/fast-integration
> mocha --inline-diffs --check-leaks --reporter mocha-multi-reporters --reporter-options configFile=mocha-reporter-config.json ./skr-test/


Error: Env KCP_KEB_API_URL not present
    at getEnvOrThrow (/home/prow/go/src/github.com/kyma-project/kyma/tests/fast-integration/utils/index.js:1191:11)
    at Function.fromEnv (/home/prow/go/src/github.com/kyma-project/kyma/tests/fast-integration/kcp/client.js:13:13)
```

**Comment by pbochynski** [comment]
@ksputo I think you need to extend this [PR](https://github.com/kyma-project/test-infra/pull/4641) to cover also kyma-preview-integration-dev plan.

**Comment by szwedm** [comment]
I added required envs in fast-integration tests to Prow config and then provided appropriate label to use the envs in prowjobs related to fast-integration: https://github.com/kyma-project/test-infra/pull/4658
