### ISSUE TITLE
Move kyma-installer to tools

### ISSUE THREAD

**Issue by derberg** [kyma-project/kyma#1296]
**Description**

Kyma repo has pretty clear structure that is clearly described here https://github.com/kyma-project/kyma#project-structure and should be extended for a good reason, not in case a folder with one jenkins and one docker file.

**Expected result**

- https://github.com/kyma-project/kyma/tree/master/tools/installer
- Dockerfile

**Actual result**

- https://github.com/kyma-project/kyma/tree/master/kyma-installer
- kyma.Dockerfile

**Comment by piotrmsc** [comment]
Remember about changes that need to be done in prow

**Comment by jakkab** [comment]
workflow:
- [ ] copy the 'kyma-installer' dir into the 'tools' dir;
- [ ] adapt kyma-project/test-infra repo;
- [ ] adapt extermal repos;
- [ ] remove the original 'kyma-installer' dir.
