### ISSUE TITLE
Kyma 2.0.0 jaeger operator never finish to status phase Running

### ISSUE THREAD

**Issue by johgoe** [kyma-project/kyma#12972]
The log of  the jaeger operator  "kubectl logs -f -n kyma-system tracing-jaeger-operator-xxxx" shows a lot of errors like

```
time="2022-01-03T14:37:13Z" level=error msg="failed to store the running status into the current CustomResource" error="jaegers.jaegertracing.io \"tracing-jaeger\" not found" execution="2022-01-03 14:37:12.860699401 +0000 UTC" instance=tracing-jaeger namespace=kyma-system
```

After searching a little bit I found a workaround:

Adding  the following snippet to crd of jaegers.jaegertracing.io fixes the problem
```
    subresources:
      status: {}
```

It's already fixed in main branch:

https://github.com/kyma-project/kyma/blob/bc5fbcdf1c4fb7d7b327a521261e7deed66d5c40/installation/resources/crds/tracing/jaegers.jaegertracing.crd.yaml#L11431

but a backport of these 2 lines to 2.0.1 is also required.

**Comment by rakesh-garimella** [comment]
Hi @johgoe its a bit unclear what happened. Recently the jaeger operator has been updated to latest image and the CRD has also been updated in the same step. These changes have been done on the main branch. From what you are running looks like you are running kyma 2.0.0 branch. Can you please share how you installed the kyma ?  What here looks like is that the jaeger opeator is running the new image but corresponding CRD is not updated.

**Comment by johgoe** [comment]
My installation is already some days old. The installation comand was `kyma deploy -c components.yaml --verbose --source=2.0.0 -p production --value global.ingress.domainName=$DOMAIN --tls-crt $TLS_CERT --tls-key $TLS_KEY`.
The operator image is eu.gcr.io/kyma-project/tpi/jaeger-operator:1.18.1-e0da5a68
The operator works but the CR never change state and I have a lot of error messages in my log files (see my reporting).

**Comment by johgoe** [comment]
It should look like this:

![grafik](https://user-images.githubusercontent.com/1584475/147953931-03faff5d-c448-4837-b0cf-b32c2ac1b263.png)

**Comment by rakesh-garimella** [comment]
Closed via https://github.com/kyma-project/kyma/issues/12972. Thanks @johgoe  for the PR.
