### ISSUE TITLE
Ability to use cloud KMS in BTP Kyma cluster projects

### ISSUE THREAD

**Issue by AribaOpensource** [kyma-project/kyma#12982]
Provide ability to use cloud native KMS services. Eample Vault rely on cloud provider KMS for auto unsealing. As of now the Kyma clusters doesnt provide/expose the details using which vault can use cloud KMS service. Please provide ability for the same

**Reasons**
Vault need ability to use KMS inorder to auto-unseal itself.

**Attachments**

https://learn.hashicorp.com/tutorials/vault/autounseal-gcp-kms?in=vault/auto-unseal
https://itnext.io/hashicorp-vault-on-kubernetes-with-auto-unseal-b7e64edbe63e

**Comment by mjakobczyk** [comment]
Closing - this will be tracked elsewhere.
