### ISSUE TITLE
Using HTTPS sinks with Kyma Eventing

### ISSUE THREAD

**Issue by pxsalehi** [kyma-project/kyma#12992]
**Description**

In the [Eventing documentation](https://kyma-project.io/docs/kyma/latest/05-technical-reference/00-custom-resources/evnt-01-subscription#custom-resource-parameters), we mention that the sink specified in a Subscription can be HTTP. There is no mention of HTTPS. However, in the [sink validation code](https://github.com/kyma-project/kyma/blob/main/components/eventing-controller/controllers/subscription/nats/reconciler.go#L357), we explicitly check for HTTP and HTTPS.

We should verify whether there are use cases where we need to support an HTTPS sink, and clearly mention what are the requirements that the sink should provide so that event delivery to the HTTPS URL would work.

**Comment by raypinto** [comment]
Currently, if we replace the sink (kyma function) with https, the events do not reach the sink. But this is not validated by the sink validator and the subscription tends to be ready for NATS. For BEB, the webhook is gets a 500 and hence updates the subscription as not ready after a few minutes.

**Comment by k15r** [comment]
this feature was never requested by any user
