### ISSUE TITLE
NATS EPP does not retry failed publish request after NATS server restarts

### ISSUE THREAD

**Issue by pxsalehi** [kyma-project/kyma#13029]
**Description**

While investigating #12930, I found out that once the NATS server is up again, the eventing publisher proxy fails with `HTTP/1.1 502 Bad Gateway` the first time I publish an event. A second publish request to the EPP succeeds. It seems we have a way of reconnecting to NATS, however we are not retrying upon failure, and the client has to retry. 

**Expected result**

If possible, the EPP should reconnect to NATS and retry publishing the event.

**Actual result**

**Steps to reproduce**

To reproduce, you can follow the same approach as #12930.

**Troubleshooting**

**Comment by marcobebway** [comment]
This ticket is blocked until we decide which approach to use for the fix.

**Comment by marcobebway** [comment]
We decided to implement a proper readiness probe for publisher that depends on the readiness of NATS server(s).
