### ISSUE TITLE
optimize reconciler for BEB

### ISSUE THREAD

**Issue by k15r** [kyma-project/kyma#13026]
- Details in: https://github.com/kyma-project/kyma/issues/9766

**Comment by raypinto** [comment]
With the current changes, the number of reconciliations reduced in the following scenario's:

- A newly created subscription: reconciliations reduced from `11 to 6`
- Second subscription with the same sink: reconciliations reduced from `8+1 to 4+1`
- Second subscription with the different sink: reconciliations reduced from `10+1 to 7+1`
- Moving existing subscription to a new sink: reconciliations reduced from `9 to 7`

We will further investigate to see if the reconciliations can reduced/optimized and update this comment.
