### ISSUE TITLE
Change reconciliation period based on resource status

### ISSUE THREAD

**Issue by k15r** [kyma-project/kyma#13059]
## Description

Subscriptions should be reconciled more often if they are not ready. 
If a subscription is not ready due to a non existing sink the default 10 minute reconciliation period is not optimal. 

Consider this scenario:
* service and subscription are created at the same time
* subscription gets reconciled, but the service is not ready yet, but will be ready few seconds later
* subscription will not be ready
* 10 mins later the subscription will be reconciled again. This time everything is ready. Subscription will turn ready

## Proposed solution
* `not ready` subscriptions should be reconciled more often. Ideally every few seconds in the beginning, then with exponential backoff 
* `ready` subscriptions should be reconciled with a constant delay in order to react to other state changes

**Comment by nachtmaar** [comment]
Maybe this can help: https://github.com/kubernetes-sigs/kubebuilder/issues/460 (did not check the content yet)

**Comment by pxsalehi** [comment]
Reading the `controller-runtime` code, to me it seems, that this is what the default queue of the controller does, as long as the reconcile function returns error or `Requeue: true`. 
https://github.com/kubernetes-sigs/controller-runtime/blob/master/pkg/internal/controller/controller.go#L311-L334
This is also pointed out by the issue that @nachtmaar shared.

The only difference between returning error or `Requeue: true`, seems to be logging the error and counting it into controller metrics. So as long as we just return error from the reconciler when we cannot mark the subscription as ready, this should work. IMO, this makes the code more readable in comparison to selectively returning `Requeue: true`.

**Comment by pxsalehi** [comment]
For BEB, as I see in the BEB subscription controller, it seems that we do return error whenever we cannot mark the subscription as ready. However, I'd rather verify/document it with a unit test as planned also for NATS. For this kind of unit test, some minor refactoring would help to reduce mocking or making it easier to mock the controller dependencies. However, as currently a general refactoring of the BEB subscription controller is in progress, I'll do this once we have finished https://github.com/kyma-project/kyma/issues/13026

**Comment by k15r** [comment]
already addressed by https://github.com/kyma-project/kyma/pull/13070
