### ISSUE TITLE
OOM Error on auth-proxy for grafana, jaeger and kiali

### ISSUE THREAD

**Issue by johgoe** [kyma-project/kyma#13095]
Since our azure kyma upgrade ist on 2.0.x the new auth proxy pods recently have been killed by oom error during the usage of the tools.

kubectl describe pod -n kyma-system monitoring-auth-proxy-grafana-558c66ff96-9r49k shows the following limits:

    Limits:
      cpu:     50m
      memory:  20Mi
    Requests:
      cpu:      10m
      memory:   5Mi

The oauth proxy is configured to use Microsoft Azure AD.

**Comment by chrkl** [comment]
Thanks for reporting this @johgoe. Could you please verify that the usage on your cluster does not exceed the proposed limit of PR #13096?

**Comment by johgoe** [comment]
@chrkl Thanks you for the fast reply. I will test the settings from #13096 tomorrow and give feedback to you.

**Comment by chrkl** [comment]
Memory reservation and limits were adjusted by the mentioned PRs. Also backported to 2.0.x.

**Comment by johgoe** [comment]
@chrkl Seems to be working with the settings from #13096.

**Comment by chrkl** [comment]
@johgoe thanks for testing
