### ISSUE TITLE
Document setup of Kyma 2 OS cluster on Azure and GKE

### ISSUE THREAD

**Issue by Sawthis** [kyma-project/kyma#13093]
**Description**

- Document how to setup Azure and GKE cluster with Kyma 2 Open Source version and connect Busola to it. 
- We should be able to add cluster-admin role for required users.
- Can we provide a simple 1 line command to create a service account with cluster-admin rights, and use then that kubeconfig file?

**Area**

* Kyma Dashboard
* Kyma CLI

**Reasons**

It's not straightforward process and requires some knowledge about IAM/Service Users configuration. 
It would be great advantage for our Kyma 2 Open Source adoption.

**Assignees**

@kyma-project/technical-writers

**Attachments**

**Comment by Ressetkk** [comment]
GKE and possibly AKS clusters roles are managed by their respective IAM. The user connecting should have required roles assigned to their account before accessing the cluster. It is something the Kyma adopter should have in mind.

For GKE the admin account that ought to have full access to the cluster and its access management needs to have the `Kubernetes Engine Admin` role assigned in GCP IAM for their user.

**Comment by dekiel** [comment]
Granting `Kubernetes Engine Admin` role to users on project should be temporary solution. This role let user do anything with k8s clusters on a project. That means a user can manually influence any prowjob running it's workload on this project.

As far I understand the problem, users need a kubeconfig from a test cluster to attach a busola instance to it. Can kubeconfig be provided in the same way as admin password were provided for earlier kyma versions? So no need to grant additionall roles to users.

**Comment by valentinvieriu** [comment]
This is not really a Kyma Dashboard issue. ( I've removed the label )

**Comment by majakurcius** [comment]
@Sawthis @Ressetkk @dekiel Where are we with this issue? Should this be documented as is?
Or does it need more clarification/changes to the procedure first? (I'm referring to @dekiel 's comment that we should not rely on the role and his question about going back to the previous solution). 
Please clarify.

**Comment by valentinvieriu** [comment]
@majakurcius I think we should document only the envs that we officially support and commit to update them on a regular basis.

**Comment by varbanv** [comment]
@majakurcius I would like to include some documentation to help customers when they try to evaluate Kyma OS on any of the major hyperscalers. It does not have to be a full guide (although it would be nice) if there is concern that it would require support effort from us. But at a minimum, information like https://github.com/kyma-project/kyma/issues/13093#issuecomment-1016248930 should be part of the installation manual.

**Comment by dekiel** [comment]
My comment intention was to bring attention that granting IAM roles related to kubernetes on a project level works on all clusters in a project. That might not be an issue for some setups, but in our case we have many clusters in one project and we doesn't need to grant such broad rights to users, on all of them. In our case granting IAM role on project level is a temporary solution and we will work to find a way to grant required permissions on a cluster level. See https://github.com/kyma-project/test-infra/issues/4851 However documentation can include examples for both ways.
