### ISSUE TITLE
Evaluate Requirement of E2E Tracing Test

### ISSUE THREAD

**Issue by chrkl** [kyma-project/kyma#13104]
**Description**

The E2E tracing test-case that is described in Issue #9631 has a significant overlap with the eventing-test extension that has been added by PR #12355. Validate if the manual release test is still required or sufficiently covered by the eventing-test.

**Reasons**

Reduce manual testing effort.

**Attachments**

**Comment by Pranav-SA** [comment]
**Conclusion**: The eventing Test covers the scope of the test described in #9631. Test added by PR #12355 and further extended with #12661 makes manual testing for tracing futile.

**Comment by a-thaler** [comment]
Is this really executed as part of the regular integration tests? For me it looks like it gets executed with the eventing-test.js only. That would be not sufficient in my oppinion
