### ISSUE TITLE
Replace API Gateway

### ISSUE THREAD

**Issue by varbanv** [kyma-project/kyma#13115]
**Description**

Replace the current API Gateway implementation in Kyma.

**Reasons**

The current solution is based on api-gateway controller creating Istio & Ory resources. This solution proves to be error-prone and limiting the implementation of customer's use-cases. We need to find a more flexible and stable solution.

**Tasks**

- [ ] [[MVP] Secure workload using Istio external auth](https://github.com/kyma-project/kyma/issues/12669)

---
<details>
    <summary>:warning: Funnel process - do not remove!</summary>
    </br>

Name|Value
:--- | :---
theme | Enterprise-grade
business value | 9
technical value | 9
user value | 8
open-source value | 5
effort | 
requested by | 
</details>

**Comment by strekm** [comment]
closed in favour of: https://github.com/kyma-project/kyma/issues/12669
