### ISSUE TITLE
Support k8s 1.21 & prepare support for k8s 1.22

### ISSUE THREAD

**Issue by a-thaler** [kyma-project/kyma#13135]
**Description**
Currently kyma support k8s 1.20. As it will soon reach EOL the next version should be supported.

Furthermore the support for version 1.22 should be prepared by already having a pipeline in place to identify problems fast and start addresing them.

AC:
- all pipelines are upgraded to k8s 1.21
- CLI provisioning is adjusted to new versions
- documentation is updated
- migration guide with potential manual actions is ready
- there is one new k3d based pipeline running on k8s 1.22 (pre-main-kyma-integration-k3d-k8s-preview)
- 

**Reasons**
Support for k8s 1.20 will be discontinued at some point in time

**Tasks**
- [x] #13301
- [x] #13302
- [x] #13303
- [x] Default version for kubectl is 1.21
- [x] document new version and release notes (https://github.com/kyma-project/kyma/pull/13417)
- [x] #13304

**Attachments**

---
<details>
    <summary>:warning: Funnel process - do not remove!</summary>
    </br>

Name|Value
:--- | :---
theme | Technical Debt
business value | 2
technical value | 10
user value | 10
open-source value | 10
effort | 
requested by | 
</details>

**Comment by varbanv** [comment]
1.20 is EOL on 28.02.2022 which is a bit over a month from now.

**Comment by dekiel** [comment]
@a-thaler I was thinking how we can track which versions of k8s we use for tests and run some verification against this list to check if k8s version used in tests is aligned with k8s releases lifecycle.

We could add annotation to represent used k8s version in [test-inventory-integration.md](https://github.com/kyma-project/test-infra/blob/main/test-inventory-integration.md). Then values can be check by automation and rise github issues if test drift from releases lifecycle.

Additionally we should run some test to check if all required prowjobs provide annotation value.

Questions
Can we have automated way of tracking k8s release timeline?
Do we need some verification which k8s version we use in cli?
How to verify documentation is aligned?

**Comment by a-thaler** [comment]
All items are done as outlined in the description. New supported version is k8s 1.21. K8s 1.22 is indeed having problems, see finding https://github.com/kyma-project/kyma/issues/13419
