### ISSUE TITLE
[Telemetry Operator] Limit the initial plugins to a minimal set

### ISSUE THREAD

**Issue by a-thaler** [kyma-project/kyma#13146]
**Description**
The goal is to offer the most open and typical integration options. Anything specific should be covered by running a custom fluentd instance. Assure that the offered feature set is minimal for now and that the way of doing advanced integrations is documented.

**Reasons**
By keeping the options minimal in the beginning the operations will be simplified a lot and improved over time to support even more in future with a more mature setup.

**Criterias**
- Validate what elements are usually needed and can be really supported by the kyma team (for example for a typical ELK integration via HTTP output) and enable only these ones (to not get new features in accidently when updating)
  - filters
  - outputs
 - Either use whitelisting, strict schema for the CRD or bundle only supported plugins in the binary
 - Loki, fluentd via forward and ELK via fluentd HTTP scenario must be supported

**Comment by chrkl** [comment]
PR #14202 allows defining a whitelist of Fluent Bit output and filter plugins that can be used by LogPipelines. The telemetry chart has been configured to allow the grafana-loki, http and forward output plugin and all filter plugins for now.
