### ISSUE TITLE
Add a test for prometheus pushgateway

### ISSUE THREAD

**Issue by skhalash** [kyma-project/kyma#13157]
**Description**

1. Add a fast-integration test that will ensure that Prometheus pushgateway works (e.g. push a metric and make sure it's queriable from Prometheus).
2. Prometheus pushgateway is disabled by default in Kyma. Either it should be enabled in test jobs and the test should be skipped if it's not enabled, or the test should be executed only is some kind of feature flag is set.

**Reasons**

Prometheus pushgateway is used by https://github.com/kyma-incubator/compass and we don't have any tests that ensure it still works after an upgrade.

**Attachments**

**Comment by a-thaler** [comment]
The component does not fit to our strategy anymore and in mid-term gets removed, so not worth of investing here: https://kyma-project.io/blog/2022/9/21/observability-strategy/
