### ISSUE TITLE
Kyma deployment fails using Kyma deploy cmd

### ISSUE THREAD

**Issue by ayushbudh** [kyma-project/kyma#13163]
**Description**

I was trying to deploy kyma with the k3d using quick install guide (https://kyma-project.io/docs/kyma/latest/02-get-started/01-quick-install) and the kyma deploy command failed to deploy component ory-oathkeeper which lead to kyma deployment failure.

Kyma CLI version: 2.0.2
Kyma cluster version: 2.0.2
Google Chrome Version 97.0.4692.99

Containerization platform: Docker client: v20.10.11 server: v20.10.11

**Expected result**

Expecting kyma deployment successful.

**Actual result**

<img width="547" alt="Screen Shot 2022-01-24 at 1 33 59 PM" src="https://user-images.githubusercontent.com/56787472/150843005-239e3c5a-3f28-4fd0-a2b6-69b8757707ee.png">

**Steps to reproduce**

Step 1: Complete prerequesite: https://kyma-project.io/docs/kyma/latest/02-get-started/
Step 2: https://kyma-project.io/docs/kyma/latest/02-get-started/01-quick-install/

**Troubleshooting**

Used minikube instead of k3d for provisioning but the deployment still failed.

**Comment by SAP-Ayush** [comment]
Hello,
Any updates on this issue ? 
I was trying to replicate this issue for Windows machine and the deployment fails after provisioning k3d cluster.

Command: ```Kyma deploy```
Output:
<img width="949" alt="kymadeploy" src="https://user-images.githubusercontent.com/91093323/155750419-0d6fde5b-feef-4a88-87a0-a7e221e3bb24.PNG">

**Comment by strekm** [comment]
@SAP-Ayush do you have maybe Umbrella app running on your machine?

**Comment by SAP-Ayush** [comment]
Yes. Umbrella Roaming Client app is running on my windows machine.

**Comment by jeremyharisch** [comment]
As described in your issue, you are using CLI 2.0.2, which is already outdated. We had some known issues in CLI 2.0.2 and 2.0.4 regarding Windows. Some of my team and myself we tried to provision a k3d cluster and deploy latest Kyma using latest Kyma CLI on Windows (Powershell and WSL2) and it worked fine.

Could you please try it with the latest CLI version? And if it does not work, please run it with `--verbose` flag and post the logs in this issue.

https://github.com/kyma-project/cli/releases

**Comment by SAP-Ayush** [comment]
Thanks for your help @jeremyharisch . Deployment was successful with Kyma CLI 2.0.4
