### ISSUE TITLE
Expose and secure a service developer tutorial should include JWT

### ISSUE THREAD

**Issue by mjakobczyk** [kyma-project/kyma#13168]
**Description**

Among `Developer tutorials` sections we currently have a guide on how to [Expose and secure a service](https://kyma-project.io/docs/kyma/latest/03-tutorials/00-api-exposure/apix-03-expose-and-secure-service). It contains information only about oAuth2 and not about JWT, however. It could show an example of how to configure JWT for Kyma. There are already some technical references in place (see **Attachments** section) that contain more general details of configuring JWT and even custom identity provider for this purpose. They may also have been referenced in the developer tutorial.

**Area**

* API Gateway

**Reasons**

Knowledge about securing a service should be aggregated in one place, easy to understand and find by a customer. Now we lack consistency because JWT is not included there.

**Assignees**

@kyma-project/technical-writers

**Attachments**

[Configure Authorization (OAuth2, JWT)](https://kyma-project.io/docs/kyma/latest/05-technical-reference/apix-01-config-authorizations-apigateway/)
[Set up a custom identity provider](https://kyma-project.io/docs/kyma/latest/03-tutorials/03-set-up-idp#documentation-content)

**Comment by veichtj** [comment]
Using https://demo.c2id.com does no long work with ory oathkeeper, it looks like oathkeeper is not supporting the elliptic curve used within JSON Web Key Set, see logs of oathkeeper:

```
An internal server error occurred, please contact the system administrator
reason=Unable to decode JSON Web Keys from location "https://demo.c2id.com/jwks.json" because "square/go-jose: unsupported elliptic curve 'secp256k1'".
```

**Comment by mmitoraj** [comment]
I'm attaching input for the JWT tutorial, once we find another demo solution compatible with Ory.

[apix-04-expose-and-secure-workload-jwt.md](https://github.com/kyma-project/kyma/files/8178365/apix-04-expose-and-secure-workload-jwt.md)

**Comment by ptesny** [comment]
FYI:
Hello, I have some spent time with the API rules secured with the JWT strategy. 
I wrote these 2 blogs about it, namely:
https://blogs.sap.com/2021/11/22/hardening-access-to-sap-kyma-runtime-apis-with-jwt-tokens./
and
https://blogs.sap.com/2021/11/25/hardening-access-to-kyma-apis-with-a-self-made-jwt-token./

Let me know if the above material could be relevant for the developer tutorials you are working upon. thanks; Piotr

**Comment by strekm** [comment]
https://kyma-project.io/docs/kyma/main/03-tutorials/00-api-exposure/apix-04-expose-and-secure-workload-jwt/

@ptesny thank you for your input. it was an interesting read ofc. is this available outside SAP also?
