### ISSUE TITLE
Missing datacontenttype CE attribute results in stringified payloads sent via NATS

### ISSUE THREAD

**Issue by kwiatekus** [kyma-project/kyma#13182]
**Description**

I noticed that event data payload type is not resolved and equivalent CE `datacontenttype ` fields  are not set.
In case of NATS backend this results in situations that json payloads get stringified.

From the function developer perspective it is unconvinient. I'd like to be able to re-use the same function code regardless of the eventing backend selected. Right now I have to manually specify `datacontenttype` in case of json obejcts

**Expected result**
I'd expect the event payload data type is recognised at the [utility function](https://github.com/kyma-project/kyma/blob/19830ec3d3a36e924186e8c55001dc83a3b37a1c/components/function-runtimes/nodejs14/kubeless/kubeless_rt/lib/ce.js#L56)
I'd expect the incoming `event.data` to be of same type (preferably json object, not stringified object) 

**Actual result**

In case NATS is used, and datacontenttype is not set explicitly, the payload gets stringified

```js
module.exports = {
    main: function (event, context) {
...
    const eventType = "sap.kyma.custom.aaa.bbb.ccc.v1"
    var eventOut=event.buildResponseCloudEvent("123124",eventType,{"foo": "bar"});
    eventOut.source="kyma"
    eventOut.specversion="1.0"
    // eventOut.datacontenttype="application/json"

    event.publishCloudEvent(eventOut);
...
    }
}
```

**Comment by pxsalehi** [comment]
@kwiatekus Thanks for creating the issue. I am not able to reproduce this using `main`. I have tried the following function:
```
module.exports = {
    main: function (event, context) {
        console.log('Type of event.data: ', typeof event.data)
        console.log(event.data)
    }
}
```

And for each backend I publish an event that has the active backend in the event data. For example:
```
curl -k -i --data @<(cat <<EOF
    {
        "source": "/default/sap.kyma/tunas-develop",
        "specversion": "1.0",
        "eventtypeversion": "v1",
        "data": {"current-backend":"NATS"},
        "datacontenttype": "application/json",
        "id": "759815c3-b142-48f2-bf18-c6502dc0998f",
        "type": "sap.kyma.custom.myapp.order.created.v1"
    }
EOF
    ) -H "Content-Type: application/cloudevents+json" "http://localhost:8080/publish"
```

This is what I'll see in the function log:
```
Type of event.data:  object
{ 'current-backend': 'BEB' }

Type of event.data:  object
{ 'current-backend': 'NATS' }
```

So in both cases I get an object in the function. 

Another evidence suggesting that in both cases the function receives an object is [this part of the fast integration tests](https://github.com/kyma-project/kyma/blob/main/tests/fast-integration/test/fixtures/commerce-mock/index.js#L780). Regardless of the backend, the function asserts that a certain property in the receive object exists. If the function would have received a string, this would fail. We run this test a `pre-main` with both backends.

**Comment by kwiatekus** [comment]
It seems "buildResponseCloudEvent" function  doesn't recognise the payload type and is not setting appropriate CE attribute `datacontenttype`

The workaround is simple, but I think its still worth to add that extra detection
