### ISSUE TITLE
Nginx Ingress fails due to lack of resources on GKE

### ISSUE THREAD

**Issue by akgalwas** [kyma-project/kyma#1320]
**Description**

The resource limits for Nginx Ingress are too restrictive causing failures on GKE. 

**Expected result**

Memory limits should be increased.

**Comment by nexus49** [comment]
Is this related to: https://github.com/kyma-project/kyma/issues/1332 ?

**Comment by lszymik** [comment]
Hello @nexus49,
This is similar issues. Both components were having too less memory after deployment on GKE.
