### ISSUE TITLE
Enhance Metadata API to align with the new documentation handling model

### ISSUE THREAD

**Issue by akgalwas** [kyma-project/kyma#1321]
**Description**

There is a general proposal concerning a new way of handling documentation : https://github.com/kyma-project/community/pull/107.  API specs validation is a part of this proposal. 
Application Registry currently:
- stores documentation directly in Minio
- doesn't performa any validation on REST API and async API specs

Application Registry needs to be enhanced to fit into the new documentation architecture.

The following needs to be considered:
- changes to the  API
- asynchronous nature of the specs validation
- API should support providing specifications inline and in a form of a link

**Comment by lszymik** [comment]
The integration with the Asset Store is resolving that issue.
