### ISSUE TITLE
Investigate failing pipelines

### ISSUE THREAD

**Issue by VladislavPaskar** [kyma-project/kyma#13212]
Currently two pipelines are failing due to event publishing errors in fi tests, the original issue is: https://github.com/kyma-incubator/reconciler/issues/725

For the https://storage.googleapis.com/kyma-prow-logs/logs/kyma-upgrade-gardener-kyma2-to-main/1486700725625950208/build-log.txt which fails with `error: 'Problem while sending event: Kyma application API responded with status 503 "no healthy upstream"'` there is a guess, that the EPP is not yet ready to receive the events after the upgrade due to restart. For this guess there are two possible solutions:

1. Increase the timeout time/interval time for event publishing in the fast integration tests
2. Add a check before publishing the events, that EPP is in the ready state. This one requires a proper ready check on the EPP side.

The other pipeline failure could be related to central-connectivity gateway which also did not start yet by the time of sending the events to commerce mock. This seems only to happen, when the cluster is upgraded from 1.24.x to 2.x. This might be not even connected to the eventing and needs further investigation.

**Comment by VladislavPaskar** [comment]
The pipeline with the `error: 'Problem while sending event: Kyma application API responded with status 503 "no healthy upstream"'` happened only in one job and job itself seems to be flaky https://status.build.kyma-project.io/?job=kyma-upgrade-gardener-kyma2-to-main. It is failing every second or third time and every time with the different error. So perhaps it is better to create a pipeline which will trigger this job automatically to be able to see the patterns.

**Comment by janmedrek** [comment]
I believe this should be closed, it's the exact duplicate of: https://github.com/kyma-incubator/reconciler/issues/725
@VladislavPaskar please align with the team on whether to keep this or close and move to the other issue.

**Comment by VladislavPaskar** [comment]
Closed in favour of kyma-incubator/reconciler#725
