### ISSUE TITLE
Avoid logging reconciliation errors more than once

### ISSUE THREAD

**Issue by pxsalehi** [kyma-project/kyma#13219]
**Description**
As discussed in this thread https://github.com/kyma-project/kyma/pull/13205#discussion_r794469842, when returning an error from the reconciler, we do not need to explicitly log the error if we are not adding any information to the error. 

If we are adding more info to the error, we could just wrap the error and returned the "enriched" error. Returning an error from the `Reconcile` method, causes the controller-runtime to log the error anyway. IMO, logging it before returning the error, would just create noise in the log.

**Comment by raypinto** [comment]
Being tracked as part of https://github.com/kyma-project/kyma/issues/15174
