### ISSUE TITLE
[Telemetry Operator] Simple Status on CRD

### ISSUE THREAD

**Issue by a-thaler** [kyma-project/kyma#13213]
**Description**
A `LogPipeline` must indicate crucial status information so that the user knows if the desired state is reached, what potential problems blocked it, what implied attributes are relevant. All needs to be reflected in the CRD so that also a UI can display it nicely.

**Goal**
Have a proper status for LogPipelines which are indicating:
- a state - ready, pending
- conditions - listing when a state was achieved

**Comment by skhalash** [comment]
Implemented status conditions similar to standard Kubernetes resources (pods, replicasets, deployments, etc.).
