### ISSUE TITLE
Allow multiple active backends per cluster

### ISSUE THREAD

**Issue by k15r** [kyma-project/kyma#13217]
## Description

Allow a user to have a kyma cluster with more than one active eventing backend.

## Acceptance Criteria

- [ ] Allow users to create an Eventing cr with all required information for their backends
- [ ] Allow users to set a default backend for subscriptions without declared backend
- [ ] Allow users to specify a backend per subscription.

## Context
**Problem**

Currently we only support one single active eventing backend per cluster. This is ok if all events come from and need to be sent to only one backend. But if a user want to use different backends for different usage scenarios this is not enough. With the ability to have more than one active eventing backend the user can use eg. NATS for in-cluster eventing (without the need of exposing the subscribers to the public) and have 1 or more EventMesh instances for communication with other applications.

**Addtitional Information**
In order to support scaling the individual components it might be required to separate the current implementation of the operator/controller/dispatcher into individual deployables. 
- [ ] the operator only has the responsibility to setup the infrastructure for all backends
- [ ] the controller reconciles subscriptions per backend
- [ ] if a backend requires a dispatching component, this component would be deployed by the operator, but can be scaled indiviually in order to support higher load and/or support HA requirements

**Missing**
- [ ] selecting the publishing endpoint should not be done in the publishing code, but it should be able to be changed using configuration 

---
<details>
    <summary>:warning: Funnel process - do not remove!</summary>
    </br>

Name|Value
:--- | :---
theme | Enterprise-grade
business value | 8
technical value | 8
user value | 6
open-source value | 6
effort | 
requested by | 
</details>

**Comment by raypinto** [comment]
Questions from grooming:
1. What should Vanilla kyma look like? All backends?
2. If no subscriptions for NATs (for example), then should we scale nats to zero?
3. Is backend optional or mandatory field in subscription spec?

**Comment by k15r** [comment]
> * why is scaling the components necessary to implement this epic ?
This does not have to be implemented as part of the ticket, but it should be kept in mind when deciding on an implementation.

> * Instead of creating a "backend CR", can't we reuse `eventingbackends.eventing.kyma-project.io` ? It has an empty spec atm.
This is perfectly fine.

> * Do we need to support changing the default backend (e.g. from NATS -> BEB) ? If yes: if a subscription with default backend is created, does this need to migrated to BEB in this case or can it stay with NATS (the previous default backend) ?
if the customer changes the default backend and he did not specify a different backend on the subscription then that subscription needs to be switched as well.
for subscriptions with a specified backend (other than default) this is not the case

**Comment by k15r** [comment]
> 1. What should Vanilla kyma look like? All backends?

just one default backend. Exactly as it is currently implemented

> 2. If no subscriptions for NATs (for example), then should we scale nats to zero?

This is optional and can be decided later. ATM if a user switches the backend the nats cluster is still kept in the kyma cluster

> 3. Is backend optional or mandatory field in subscription spec?

It should be possible for the customer to ignore specifying a backend. In that case the subscription should use the default backend

**Comment by k15r** [comment]
this will not be implemented for now.
