### ISSUE TITLE
Implement sending to Nats Jetstream using EPP

### ISSUE THREAD

**Issue by k15r** [kyma-project/kyma#13224]
## Acceptance
- [ ] use new client to connect to jetstream enabled server
- [ ] read consumer information using jetstream client (info endpoint for legacy applications)
- [ ] use flag from controller to enable jetstream mode
- [ ] use jetstream enabled nats test server in unit/integration tests

**Comment by pxsalehi** [comment]
The EPP for JetStream needs to take into account the stream name when publishing to a subject. As of https://github.com/kyma-project/kyma/commit/72dce8ae360c554ee765127c301e7a0b3fc6edc5, this means the subject that the EPP publishes to is `StreamName.EventType` (for an example, see https://github.com/kyma-project/kyma/issues/13223#issuecomment-1048719937).

**Comment by mfaizanse** [comment]
Related: https://github.com/kyma-project/kyma/issues/13544
