### ISSUE TITLE
Analyze prometheus KPI and define the limits

### ISSUE THREAD

**Issue by a-thaler** [kyma-project/kyma#13269]
**Description**
The prometheus stack coming with kyma is a non-scalable setup. While the general solution is to focus on integration and support external scalable solutions (see https://github.com/kyma-project/kyma/issues/13079), we need to be precise about the KPIs influencing the stability of the prometheus stack. For that we need to identify the indicators influencing the stability and define limits for them.

**Goal**
Identify the limiting indicators and find the relevant thresholds

**Actions**
- Put the stack under stress with different aspects like
  - Increased timeseries by introducing high cardinality with a bad custom metric
  - Increased timeseries by high changing istio topology
  - Increased queries by having long running queries in parallel
  - Increased sample data size by having a custom metric with huge size
  - Increased targets by bringing in a lot of scrape targets
- Identify the indicators which are really harming the stability and document them for the production profile
- As a result, document findings and process for repeatability. Meaning this includes doing https://github.com/kyma-project/kyma/issues/10033

**Comment by chrkl** [comment]
Our tests have shown that the number of ingested time series is the limiting factor. The limits for the time series count have been documented for the production profile in PR #13699.
