### ISSUE TITLE
Improve test coverage of oauth2-proxy

### ISSUE THREAD

**Issue by a-thaler** [kyma-project/kyma#13275]
**Description**
In the integration tests it is assured that the exposure of grafana works in general, but it is not testing that via placing the sepcific user provided secret as defined in the documentation.

The current Grafana fast-integration test patches the Deployment with the `trusted-ip` flag to remove the `reverse-proxy` flag in the same step. The `reverse-proxy` setting should be moved to the default config Secret and be overwritten by the user given Secret in the test. 

**Goal**
Improve the test to cover the typical user flow

**Criterias**
- Test is verifying that no exposure is happening by default
- Test is checking that settings from a user provided secret are picked up
- Test is cleaning up

**Comment by chrkl** [comment]
PR #14282 uses the secret to expose Grafana in the test as intended. The PR removes the --reverse-proxy flag of the oauth2 proxy, since it is not effective with out Istio Ingress Gateway.
