### ISSUE TITLE
kyma-preview-integration-dev job fails with timeouts

### ISSUE THREAD

**Issue by pbochynski** [kyma-project/kyma#13271]
**Description**

The job [kyma-preview-integration-dev](https://status.build.kyma-project.io/job-history/gs/kyma-prow-logs/logs/kyma-preview-integration-dev) fails:
```
  1) Execute SKR test
       "before all" hook: Provision SKR in "Execute SKR test":
     Error: before hook failed: Error: Error: wait timeout
Runtime status: {
	"data": [
		{
			"instanceID": "e3ce3ea0-5861-4d8e-ba43-aaef6a59481f",
			"runtimeID": "8045c44c-553a-455f-b47e-4d89629c30ab",
			"globalAccountID": "e449f875-b5b2-4485-b7c0-98725c0571bf",
			"subAccountID": "prow-keb-integration",
			"region": "eu-central-1",
			"subAccountRegion": "cf-eu10",
			"shootName": "abbbcdb",
			"serviceClassID": "47c9dcbf-ff30-448e-ab36-d3bad66ba281",
			"serviceClassName": "kymaruntime",
			"servicePlanID": "5cb3d976-b85c-42ea-a636-79cadda109a9",
			"servicePlanName": "preview",
			"provider": "AWS",
			"status": {
				"createdAt": "2022-02-03T04:01:40.380657Z",
				"modifiedAt": "2022-02-03T04:11:42.360102Z",
				"state": "provisioning",
				"provisioning": {
					"state": "in progress",
					"description": "Operation created",
					"createdAt": "2022-02-03T04:01:40.375597Z",
					"operationID": "e7a3690b-e21e-4c2a-a8d0-d38d28996509"
				}
			},
			"userID": "test@test.com",
			"avsInternalEvaluationID": 170655395
		}
	],
	"count": 1,
	"totalCount": 1
}
      at Context.<anonymous> (skr-test/test.js:41:13)
      at processTicksAndRejections (internal/process/task_queues.js:95:5)

  2) Execute SKR test
       "after all" hook: Deprovision SKR in "Execute SKR test":
     Error: Error: wait timeout
Runtime status: {
	"data": [
		{
			"instanceID": "e3ce3ea0-5861-4d8e-ba43-aaef6a59481f",
			"runtimeID": "8045c44c-553a-455f-b47e-4d89629c30ab",
			"globalAccountID": "e449f875-b5b2-4485-b7c0-98725c0571bf",
			"subAccountID": "prow-keb-integration",
			"region": "eu-central-1",
			"subAccountRegion": "cf-eu10",
			"shootName": "abbbcdb",
			"serviceClassID": "47c9dcbf-ff30-448e-ab36-d3bad66ba281",
			"serviceClassName": "kymaruntime",
			"servicePlanID": "5cb3d976-b85c-42ea-a636-79cadda109a9",
			"servicePlanName": "preview",
			"provider": "AWS",
			"status": {
				"createdAt": "2022-02-03T04:01:40.380657Z",
				"modifiedAt": "2022-02-03T04:31:40.888133Z",
				"state": "deprovisioning",
				"provisioning": {
					"state": "in progress",
					"description": "Operation created",
					"createdAt": "2022-02-03T04:01:40.375597Z",
					"operationID": "e7a3690b-e21e-4c2a-a8d0-d38d28996509"
				},
				"deprovisioning": {
					"state": "in progress",
					"description": "Operation created",
					"createdAt": "2022-02-03T04:31:40.888133Z",
					"operationID": "65a71949-c8fd-4bfc-baf9-040f5fd57eba"
				}
			},
			"userID": "test@test.com",
			"avsInternalEvaluationID": 170655395
		}
	],
	"count": 1,
	"totalCount": 1
}
      at /home/prow/go/src/github.com/kyma-project/kyma/tests/fast-integration/kyma-environment-broker/helpers.js:100:11
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (internal/process/task_queues.js:95:5)
      at async ensureOperationSucceeded (kyma-environment-broker/helpers.js:93:15)
      at async deprovisionSKR (kyma-environment-broker/helpers.js:61:5)
      at async Context.<anonymous> (skr-test/test.js:49:5)
```

**Comment by PK85** [comment]
@pbochynski Investigation from KEB side here: https://github.com/kyma-incubator/reconciler/issues/768#issuecomment-1028879847

**Comment by PK85** [comment]
Current status: SKR provisioning timeouts, reason 503 from reconciler APIs.

**Comment by Tomasz-Smelcerz-SAP** [comment]
@PK85 Now the pipeline consistently returns: "no shootName provided by runtimeStatus". I observed the same problem  also in another pipeline: https://storage.googleapis.com/kyma-prow-logs/logs/skr-kyma-to-kyma2-upgrade-aws-dev/1491502401931186176/build-log.txt
Is it a known issue? Or maybe it's a normal condition? I can see the cluster exists in kyma-dev Gardener project.

Example log below:

```
  Execute SKR test
Provision SKR with instance ID 3223df3b-5634-4c57-be02-a074ddeb369d
Operation e2c8ce5a-8339-4852-ab6d-b74e974a5b3c finished with state succeeded
executing reconcileInformationLog 
executing getReconciliationsOperations
number of reconciliations operations: 1
reconciliation operation status: ready
    1) "before all" hook: Provision SKR in "Execute SKR test"
Deprovision SKR - operation ID 21c39008-f724-4350-89dd-121b169e5aad
Operation 21c39008-f724-4350-89dd-121b169e5aad finished with state succeeded
executing reconcileInformationLog 
skipping reconciliations logging: no shootName provided by runtimeStatus


  0 passing (28m)
  1 failing

  1) Execute SKR test
       "before all" hook: Provision SKR in "Execute SKR test":
     ReferenceError: getReconciliationsInfo is not defined
      at KCPWrapper.reconcileInformationLog (kcp/client.js:316:62)
      at processTicksAndRejections (internal/process/task_queues.js:95:5)
      at async Context.<anonymous> (skr-test/test.js:41:7)

**Comment by tillknuesting** [comment]
> @PK85 Now the pipeline consistently returns: "no shootName provided by runtimeStatus". I observed the same problem also in another AWS pipeline: https://storage.googleapis.com/kyma-prow-logs/logs/skr-kyma-to-kyma2-upgrade-aws-dev/1491502401931186176/build-log.txt Is it a known issue? Or maybe it's a normal condition? I can see the cluster exists in kyma-dev Gardener project.
> 
> Example log below:
> 
> ```
>   Execute SKR test
> Provision SKR with instance ID 3223df3b-5634-4c57-be02-a074ddeb369d
> Operation e2c8ce5a-8339-4852-ab6d-b74e974a5b3c finished with state succeeded
> executing reconcileInformationLog 
> executing getReconciliationsOperations
> number of reconciliations operations: 1
> reconciliation operation status: ready
>     1) "before all" hook: Provision SKR in "Execute SKR test"
> Deprovision SKR - operation ID 21c39008-f724-4350-89dd-121b169e5aad
> Operation 21c39008-f724-4350-89dd-121b169e5aad finished with state succeeded
> executing reconcileInformationLog 
> skipping reconciliations logging: no shootName provided by runtimeStatus
> 
> 
>   0 passing (28m)
>   1 failing
> 
>   1) Execute SKR test
>        "before all" hook: Provision SKR in "Execute SKR test":
>      ReferenceError: getReconciliationsInfo is not defined
>       at KCPWrapper.reconcileInformationLog (kcp/client.js:316:62)
>       at processTicksAndRejections (internal/process/task_queues.js:95:5)
>       at async Context.<anonymous> (skr-test/test.js:41:7)
> ```
Fix for error:
https://github.com/kyma-project/kyma/pull/13341

**Comment by a-thaler** [comment]
It is worked on a solution as part of https://github.com/kyma-incubator/reconciler/issues/782

**Comment by varbanv** [comment]
Pipeline is now green.
