### ISSUE TITLE
Analyse and optimise performance of eventing reconciler

### ISSUE THREAD

**Issue by k15r** [kyma-project/kyma#13278]
## Descriptions

All component reconcilers are expected to finish as quickly as possible in case no change has to be done to a reconciled cluster.

## Acceptance

- [ ] Analyse duration of a 'noop' reconciliation of eventing components
- [ ] Reduce time taken (if possible)

**Comment by nachtmaar** [comment]
@k15r is this still required ? If yes please reopen it.
