### ISSUE TITLE
Use bundle release

### ISSUE THREAD

**Issue by piotrmiskiewicz** [kyma-project/kyma#1328]
AC:
 - create first bundle GitHub release with one bundle - redis
 - set the helm-broker repository url to that release

**Comment by mszostok** [comment]
I've created a new release manually. The name is **0.1.0**. I didn't create any release branch I only added a tag 0.1.0. The release branches can be done when we will agree on some approach about that. For now, we do not have any correlation between _bundles_ repo and _kyma_ repo.

The possible solution which can be accepted:

They have a different repositories related to the Kubernetes project (https://github.com/kubernetes/kubernetes) but not all are consolidated f.e.:
- https://github.com/kubernetes/api
- https://github.com/kubernetes/apimachinery
- https://github.com/kubernetes/client-go
- https://github.com/kubernetes/website

The correlation is based on the release branches and tags
The https://github.com/kubernetes/kubernetes repository always have a releases branches e.g
- release-1.9
- release-1.10
- release-1.11
- etc.
and proper tags:
- v1.9.0
- v1.9.5
- v1.9.7-beta.0
- etc.

all other repositories have a releases branches which reflect those from main repository e.g:
- release-1.9
- release-1.10
- release-1.11
- etc.

and tags which refers to the main repo:
- kubernetes-v1.9.0
- kubernetes-v1.9.5
- kubernetes-v1.9.7-beta.0
- etc.

the in dependency management it’s looks like follows:
```# main repo
[[constraint]]
  name = "k8s.io/kubernetes"
  branch = "release-1.10"

# related repos  
[[constraint]]
  name = "k8s.io/api"
  version = "kubernetes-1.10.1"

[[constraint]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.10.1"

[[constraint]]
  name = "k8s.io/client-go"
  version = "kubernetes-1.10.1"```
