### ISSUE TITLE
Installation timeout on helm-broker component

### ISSUE THREAD

**Issue by pbochynski** [kyma-project/kyma#13280]
**Description**

Some pipelines fail due to timeout on installing helm-broker component:
- https://storage.googleapis.com/kyma-prow-logs/logs/kyma-upgrade-gardener-kyma2-to-main/1489479065785077760/build-log.txt
- https://storage.googleapis.com/kyma-prow-logs/logs/kyma-upgrade-gardener-kyma2-to-main/1489267670472724480/build-log.txt

**Comment by PK85** [comment]
This thing is investigated under: https://github.com/kyma-incubator/reconciler/issues/724
