### ISSUE TITLE
Improve logging stats dashboard

### ISSUE THREAD

**Issue by a-thaler** [kyma-project/kyma#13298]
**Description**
The current logging statistics dashboard in Grafana has some flaws and should be improved.

**Goal**
- Remove that filter when clicking on the left chart
- Either introduce conscious thresholds or drop them in the left chart
- Change the right chart to be an average error rate over time per pod

**Comment by Pranav-SA** [comment]
Dashboard with the above Goal:

`apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "loki.fullname" . }}-grafana-stats-dashboard
  labels:
    grafana_dashboard: "1"
    app: {{ template "loki.name" . }}
    chart: {{ template "loki.chart" . }}
    release: {{ .Release.Name }}
data:
  loki-stats-dashboard.json: |- 
      {
        "annotations": {
          "list": [
            {
              "builtIn": 1,
              "datasource": "-- Grafana --",
              "enable": true,
              "hide": true,
              "iconColor": "rgba(0, 211, 255, 1)",
              "name": "Annotations & Alerts",
              "type": "dashboard"
            },
            {
              "datasource": "Loki",
              "enable": true,
              "expr": "{container=\"kube-diff-logger\"} | json | namespace_extracted=\"$namespace\"",
              "hide": true,
              "iconColor": "rgba(255, 96, 96, 1)",
              "name": "deployments",
              "showIn": 0,
              "target": {}
            }
          ]
        },
        "editable": false,
        "gnetId": null,
        "graphTooltip": 1,
        "iteration": 1644400039606,
        "links": [],
        "panels": [
          {
            "datasource": "Loki",
            "fieldConfig": {
              "defaults": {
                "color": {
                  "mode": "thresholds"
                },
                "custom": {
                  "align": "left",
                  "displayMode": "basic",
                  "filterable": false
                },
                "mappings": [
                  {
                    "from": "",
                    "id": 1,
                    "text": "",
                    "to": "",
                    "type": 1
                  }
                ],
                "noValue": "No data",
                "thresholds": {
                  "mode": "percentage",
                  "steps": [
                    {
                      "color": "light-green",
                      "value": null
                    }
                  ]
                },
                "unit": "Bps"
              },
              "overrides": [
                {
                  "matcher": {
                    "id": "byName",
                    "options": "Value #A"
                  },
                  "properties": [
                    {
                      "id": "custom.displayMode",
                      "value": "lcd-gauge"
                    },
                    {
                      "id": "displayName",
                      "value": "Rate"
                    },
                    {
                      "id": "custom.filterable",
                      "value": false
                    }
                  ]
                },
                {
                  "matcher": {
                    "id": "byName",
                    "options": "pod"
                  },
                  "properties": [
                    {
                      "id": "displayName",
                      "value": "Pod"
                    },
                    {
                      "id": "custom.displayMode",
                      "value": "auto"
                    },
                    {
                      "id": "custom.filterable",
                      "value": false
                    }
                  ]
                }
              ]
            },
            "gridPos": {
              "h": 16,
              "w": 12,
              "x": 0,
              "y": 0
            },
            "hideTimeOverride": false,
            "id": 113,
            "links": [],
            "maxDataPoints": 80,
            "options": {
              "frameIndex": 1,
              "showHeader": true,
              "sortBy": [
                {
                  "desc": true,
                  "displayName": "Value #A"
                }
              ]
            },
            "pluginVersion": "",
            "targets": [
              {
                "expr": "topk(15,sum(bytes_rate({namespace=\"$namespace\" ,job=\"fluent-bit\"}[5m]))by (pod)) ",
                "instant": true,
                "legendFormat": "{{`{{pod}}`}}",
                "range": false,
                "refId": "A"
              }
            ],
            "timeFrom": null,
            "timeShift": null,
            "title": "Log Rate/Pod",
            "transformations": [
              {
                "id": "organize",
                "options": {
                  "excludeByName": {
                    "Time": true
                  },
                  "indexByName": {},
                  "renameByName": {
                    "Value #A": "Rate",
                    "pod": ""
                  }
                }
              },
              {
                "id": "sortBy",
                "options": {
                  "fields": {},
                  "sort": [
                    {
                      "desc": true,
                      "field": "Rate"
                    }
                  ]
                }
              }
            ],
            "type": "table"
          },
          {
            "aliasColors": {},
            "bars": false,
            "cacheTimeout": null,
            "dashLength": 10,
            "dashes": false,
            "datasource": "Loki",
            "decimals": 0,
            "fieldConfig": {
              "defaults": {
                "unit": "short"
              },
              "overrides": []
            },
            "fill": 10,
            "fillGradient": 10,
            "gridPos": {
              "h": 16,
              "w": 12,
              "x": 12,
              "y": 0
            },
            "hiddenSeries": false,
            "id": 132,
            "interval": "1m",
            "legend": {
              "alignAsTable": true,
              "avg": false,
              "current": true,
              "hideEmpty": false,
              "hideZero": false,
              "max": false,
              "min": false,
              "rightSide": false,
              "show": true,
              "sort": "current",
              "sortDesc": true,
              "total": false,
              "values": true
            },
            "lines": true,
            "linewidth": 1,
            "links": [],
            "maxDataPoints": null,
            "nullPointMode": "null as zero",
            "options": {
              "alertThreshold": true
            },
            "percentage": false,
            "pluginVersion": "",
            "pointradius": 2,
            "points": false,
            "renderer": "flot",
            "seriesOverrides": [],
            "spaceLength": 10,
            "stack": true,
            "steppedLine": false,
            "targets": [
              {
                "expr": "sum(count_over_time(({namespace=\"$namespace\" ,pod=\"$pod\", stream=~\"std.*\"} |~ \"(?i)error\")[5m])) by (pod)",
                "instant": false,
                "legendFormat": "{{`{{pod}}`}}",
                "maxLines": 0,
                "range": true,
                "refId": "A"
              }
            ],
            "thresholds": [],
            "timeFrom": null,
            "timeRegions": [],
            "timeShift": null,
            "title": "Errors/Pod (selected)",
            "tooltip": {
              "shared": true,
              "sort": 2,
              "value_type": "cumulative"
            },
            "type": "graph",
            "xaxis": {
              "buckets": null,
              "mode": "time",
              "name": null,
              "show": true,
              "values": []
            },
            "yaxes": [
              {
                "$$hashKey": "object:425",
                "decimals": 0,
                "format": "short",
                "label": "Count",
                "logBase": 1,
                "max": null,
                "min": null,
                "show": true
              },
              {
                "$$hashKey": "object:426",
                "format": "short",
                "label": null,
                "logBase": 1,
                "max": null,
                "min": null,
                "show": false
              }
            ],
            "yaxis": {
              "align": false,
              "alignLevel": null
            }
          }
        ],
        "refresh": "30s",
        "schemaVersion": 27,
        "style": "dark",
        "tags": [
          "kyma",
          "logging"
        ],
        "templating": {
          "list": [
            {
              "allValue": null,
              "current": {
                "selected": false,
                "text": "kyma-system",
                "value": "kyma-system"
              },
              "datasource": "Prometheus",
              "definition": "label_values(kube_pod_container_info, namespace)",
              "description": null,
              "error": null,
              "hide": 0,
              "includeAll": false,
              "label": null,
              "multi": false,
              "name": "namespace",
              "options": [],
              "query": {
                "query": "label_values(kube_pod_container_info, namespace)",
                "refId": "StandardVariableQuery"
              },
              "refresh": 1,
              "regex": "",
              "skipUrlSync": false,
              "sort": 0,
              "tagValuesQuery": "",
              "tags": [],
              "tagsQuery": "",
              "type": "query",
              "useTags": false
            },
            {
              "allValue": null,
              "current": {
                "selected": false,
                "text": "monitoring-grafana-74b7f55759-tqhfn",
                "value": "monitoring-grafana-74b7f55759-tqhfn"
              },
              "datasource": "Loki",
              "definition": "label_values(kube_pod_labels{label_kyma_project_io_component=\"controller\",namespace=\"$namespace\"},pod)",
              "description": null,
              "error": null,
              "hide": 0,
              "includeAll": false,
              "label": null,
              "multi": false,
              "name": "pod",
              "options": [],
              "query": "label_values(kube_pod_labels{label_kyma_project_io_component=\"controller\",namespace=\"$namespace\"},pod)",
              "refresh": 2,
              "regex": "",
              "skipUrlSync": false,
              "sort": 1,
              "tagValuesQuery": "",
              "tags": [],
              "tagsQuery": "",
              "type": "query",
              "useTags": false
            }
          ]
        },
        "time": {
          "from": "now-3h",
          "to": "now"
        },
        "timepicker": {
          "refresh_intervals": [
            "10s",
            "30s",
            "1m",
            "5m",
            "15m",
            "30m",
            "1h",
            "2h",
            "1d"
          ]
        },
        "timezone": "",
        "title": "Kyma / Logging / Stats",
        "uid": "lokidashboardstats",
        "version": 1
      }`

**Comment by rakesh-garimella** [comment]
The dashboard changes has been reverted here: https://github.com/kyma-project/kyma/pull/13381

**Comment by a-thaler** [comment]
I will close the ticket for now. It turned out that the metrics based on logs are causing too much resource consumption in should be avoided in a bigger scale for now
