### ISSUE TITLE
Bring back mTLS between Prometheus and Ory

### ISSUE THREAD

**Issue by cnvergence** [kyma-project/kyma#13299]
**Description**

In the latest Prometheus update to 2.31.1 version, there was an issue with mTLS scraping in `ory-hydra-maester` and `ory-oathkeeper` pods. They are currently scraped with plain HTTP. We should restore that additional layer of security to the Ory component.

**Expected result**

Ory pods are scrapped with STRICT mTLS setting.

**Actual result**

Ory pods are scrapped with PERMISSIVE mTLS setting.

**Steps to reproduce**

**Troubleshooting**

**See also**
[13043](https://github.com/kyma-project/kyma/pull/13043)

**Comment by strekm** [comment]
closing due to @skhalash comment
