### ISSUE TITLE
[k8s update] Verify that kyma can run with k8s 1.22

### ISSUE THREAD

**Issue by a-thaler** [kyma-project/kyma#13304]
**Description**
Assure that there is a job in place testing kyma with k8s 1.22.

For that bump the version in the job resulting from https://github.com/kyma-project/kyma/issues/13301 to the next version

**Comment by rakesh-garimella** [comment]
The preview job has been updated to use k8s version 1.22.6

**Comment by a-thaler** [comment]
The job is failing because of https://github.com/kyma-project/kyma/issues/13419
