### ISSUE TITLE
[k8s update] Default version for Kyma CLI is k8s 1.21

### ISSUE THREAD

**Issue by a-thaler** [kyma-project/kyma#13302]
**Description**
The CLI needs to be updated to use K8S 1.21 as default version for all cluster provisioning

**Criteria**
- Update all provision command to use a k8s 1.21 version by default: https://github.com/kyma-project/cli/pull/1185
- Publish a new stable binary: done
- Verify that all jobs are still fine
- Update the k8s client version to 1.21: https://github.com/kyma-project/test-infra/pull/4944

**Comment by rakesh-garimella** [comment]
The default version for k8s has been updated in the provision commands (check the PR in the description). 
The jobs are green and the latest stable binary has been published. The k8s client has also been updated.
