### ISSUE TITLE
[k8s update] Verify k8s 1.21 support on k3d

### ISSUE THREAD

**Issue by a-thaler** [kyma-project/kyma#13301]
**Description**
Introduce a k3d post-submit job for the k8s-preview version and make it green in order to assure that support of k8s 1.21 is covered

**Actions**
- Introduce the new job on base of CLI setting the k8s version via preset
- Verify that the job is green

**Comment by rakesh-garimella** [comment]
The preview job has been created and its called: `post-main-k3d-k8s-preview`
