### ISSUE TITLE
Generate a deletion script based on resource diff of two clusters

### ISSUE THREAD

**Issue by a-thaler** [kyma-project/kyma#13308]
**Description**
Extend https://github.com/kyma-project/kyma/issues/13566 to cover the full story:
As resource deletions (or moves) in Kyma components are not deleted on an upgrade procedure, people need to remember to list all the orphaned resources within two versions and note them down in a migration script. As this is tedious work that is error-prone and repeating, there should be some tooling around that which can be used for automation in a later step.

**Acceptance criteria**
Have a tool to:
- diff two of such dry-run "resource files" in order to generate a deletion script out of the diff
- it must be possible to configure exclusion for the final script to ignore specific resources/types/namespaces from deletion

**Comment by a-thaler** [comment]
See also https://github.com/kyma-project/kyma/issues/13297#issuecomment-1031962563

**Comment by skhalash** [comment]
After some discussion, the decision was made to go with implementing the dry run mode in the reconciler and the CLI to diff Kubernetes manifests: https://github.com/kyma-incubator/reconciler/issues/797

**Comment by a-thaler** [comment]
Already solved with https://github.com/kyma-project/kyma/issues/13566
