### ISSUE TITLE
[k8s update] Testing is based on K8S 1.21

### ISSUE THREAD

**Issue by a-thaler** [kyma-project/kyma#13303]
**Description**
All major CI jobs should be based on k8s 1.21 as it is the supported version.

**Criteria**
- Verify that all CLI based jobs are either using the default version or update the version
- For non-CLI jobs, update the version: https://github.com/kyma-project/test-infra/pull/4961

**Comment by rakesh-garimella** [comment]
All the jobs based on hyperscalers have been updated to 1.21.x version.
