### ISSUE TITLE
Clean up the Application Connector Octopus tests

### ISSUE THREAD

**Issue by franpog859** [kyma-project/kyma#13338]
**Description**

Clean up the Application Connector Octopus tests. It should be pretty simple. Delete Application Connector tests located [here](https://github.com/kyma-project/kyma/tree/main/tests). Clean up also the related jobs in the test-infra repo

**Reasons**

There is no reason to keep them here. There is no Octopus anymore and they are not used anywhere for about half a year.

**Comment by janmedrek** [comment]
will be handled by: https://github.com/kyma-project/kyma/issues/13977
