### ISSUE TITLE
ErrorCodeNotFound from git lib should be recoverable

### ISSUE THREAD

**Issue by dbadura** [kyma-project/kyma#13360]
**Description**
When user create function with reference to not existing branch, we shouldn't stop reconciliation for this function.

**Expected result**
The function will be reconciled

**Actual result**
The function 
**Steps to reproduce**
Create the function with reference to not existing branch. The fn controller won't reconcile it.

**Comment by kwiatekus** [comment]
Let make it AC of #13545

**Comment by kwiatekus** [comment]
Two facts to check
 - we mark some errors as non recoverable - this one is an example where we could change it to recoverable
 - the back-off steps are configured very large - it may seem as if it is not retried, but maybe it but after a long time of waiting
