### ISSUE TITLE
Test-core-kubeless is failing in stability checker test

### ISSUE THREAD

**Issue by rakesh-garimella** [kyma-project/kyma#1338]
**Description**
`test-core-kubeless` is failling in stability checker test. We need to investigate why is this happening.
```
*Summary:* 20 test executions and 20 of them failed :sad-frog:
Test statistics from failed executions:
   20 failures of test-core-core-acceptance
   5 failures of test-core-kubeless
   1 failures of metadata-service-tests
```

**Comment by venturasr** [comment]
Practically all the errors found are related to deletion of the **ServiceInstance**.

A possible bug was found during the call of `deleteFun(namespace, name string)`

Here is the PR https://github.com/kyma-project/kyma/pull/1384
