### ISSUE TITLE
Verify apiserver metrics before 2.1 rollout

### ISSUE THREAD

**Issue by a-thaler** [kyma-project/kyma#13386]
**Description**
validate that we have not increased prometheus footprint by latest prom upgrade

apiserver metrics are talking 1/3 of all metrics, so we need to be sure that we have not increased the amount by unused rules and metrics. 

**Criterias**
- There is only one apiserver dashboard left showing meaningful like latencies (not strange SLO/SLA calculations)
- Rules are active required by the dashboard and essential alerts (do we need kubeApiserverSlos: true?)

**Comment by dennis-ge** [comment]
Findings:
- The only apiserver metric with high utilization was `apiserver_request_duration_seconds_bucket`. We reduced the footprint of this metric by only considering some selected buckets and not all (initially around 30 buckets, now only 6). This was done in the first PR. 
- The apiserver dashboard used the previous mentioned metric and some other metrics with low count (no recording rules are used in the dashboard)
- The `kubeApiserverSlos` rules were disabled with this PR as they include SLO/SLA calculations
- The second PR reduced the footprint of the second highest metric in Prometheus, the `rest_client_request_latency_seconds_bucket` metric. We reduce the footprint of this metric two ways:
    - Reduce amount of buckets for the metric
    - Only consider metric data from specific k8s API groups (core, apps, batch and one special API group, e.g., jaegertracing.io for the tracing component)
- Moreover, the telemetry component got upgraded in the second PR to a newer controller-runtime where the metric is optional and disabled by default.
