### ISSUE TITLE
Fix pre-*-kyma-skr-eventing

### ISSUE THREAD

**Issue by k15r** [kyma-project/kyma#13393]
## Description

Before we can convert the optional job https://status.build.kyma-project.io/?job=pre-main-kyma-skr-eventing into a mandatory job, we have to ensure that it is green most of the time and only fails if a proper error occurs

## Acceptance
- [x]  investigate into the failing job history and fix if needed
- [x] test must be stable when no change to any kyma component was introduced

**Comment by VladislavPaskar** [comment]
test infra PR: https://github.com/kyma-project/test-infra/pull/4834
