### ISSUE TITLE
Issue while Deploying from GCP Marketplace

### ISSUE THREAD

**Issue by brualves** [kyma-project/kyma#13413]
Hi team,
I'm facing an issue while deploying Kyma 1.9 from GCP Marketplace. 
Similar to #6379 and #7192. 

As described on #9022, GCP deployment should be disabled but it is not. 

Is it still the case that Kyma cannot be installed via the GCP marketplace anymore?

**Comment by kwiatekus** [comment]
Kyma was removed from GCP Marketplace
![Screenshot 2022-05-05 at 09 45 04](https://user-images.githubusercontent.com/6783567/166881385-f037eb18-2896-43b5-b3a1-86f301511cc2.png)
