### ISSUE TITLE
Cover the `sampled` header in context of tracing in function runtimes

### ISSUE THREAD

**Issue by pPrecel** [kyma-project/kyma#13423]
**Description**

After finishing [this story](https://github.com/kyma-project/kyma/issues/11327) add functionality to configure tracer (or tracer context) to record only spans when TraceID would be recorded. There are the following example headers coming together with a request:

```
"x-b3-traceid": "907be1c761e4cd9265d3387e341d8700",
"x-b3-spanid": "a4146c9faad5fb02",
"x-b3-parentspanid": "468ff3491ae7bb61",
"x-b3-sampled": "1"
``` 

There is a header `x-b3-sampled` which means if is this call recorded or not. If this value is set to 1 then we should record all spans around this request and if not then we should only allow to create spans but not send them to the jaeger service.

**Reasons**

This proposition is logged to be consistent with the whole istio-mesh which is reacting to this header and to keep the configuration of the functions sampling in one place together with the istio

**Comment by kwiatekus** [comment]
There is a problem with proper handling of the `b3-sampled` header in case axios is required in the user code.
 I.e
 
 ```js
require('axios')
module.exports = { 
  main: function (event, context) {
    console.log("Sampled?", event.extensions.request.headers['x-b3-sampled'])
    return "Hello World!";
  }
}
```
For the above function that traces are still pushed to jaeger backend even in case a request is marked as not sampled:

![Screenshot 2022-03-25 at 14 31 28](https://user-images.githubusercontent.com/6783567/160130232-7f4dcc97-dc64-415b-bd2f-76e8b83a536a.png)

![Screenshot 2022-03-25 at 14 31 09](https://user-images.githubusercontent.com/6783567/160130497-c0182b30-eec8-4630-9767-39bec5300cc5.png)

**Comment by kwiatekus** [comment]
There are two following traces in jeager.
First one (chronologically) corresponds to a request with sampled enforced - we can observer span from istio gateway
Second one corresponds to a request w/o `b3-sampled` header
![Screenshot 2022-03-25 at 15 32 20](https://user-images.githubusercontent.com/6783567/160141625-2dc85729-bbcd-418d-a6c1-887f467c7f3d.png)
