### ISSUE TITLE
Adapt mutatingWebhookConfiguration for pod-preset to be compliant with apiVersion: admissionregistration.k8s.io/v1

### ISSUE THREAD

**Issue by rakesh-garimella** [kyma-project/kyma#13442]
**Description**

With k8s 1.22 the support for `apiVersion: admissionregistration.k8s.io/v1beta1` is dropped and only `apiVersion: admissionregistration.k8s.io/v1` is supported. For this we need to adapt the [pod-preset](https://github.com/kyma-project/kyma/blob/main/resources/cluster-essentials/charts/pod-preset/templates/webhook/webhook.yaml) yaml configuration. The current fields are missing

```yaml
admissionReviewVersions: ["v1beta1"]
sideEffects: None
```

**Expected result**
The pod-preset  mutatingwebhook is installed properly

**Actual result**

Currently it fails with following error on k8s 1.22
no matches for kind "MutatingWebhookConfiguration" in version "admissionregistration.k8s.io/v1beta1"

**Steps to reproduce**
Install kyma on a cluster with k8s 1.22

**Comment by PK85** [comment]
Docs: https://kubernetes.io/docs/reference/using-api/deprecation-guide/#webhook-resources-v122

**Comment by PK85** [comment]
fixed by: https://github.com/kyma-project/kyma/pull/13518/files
