### ISSUE TITLE
Functions consistently failing for skr-aws-svcat-migration-dev

### ISSUE THREAD

**Issue by wozniakjan** [kyma-project/kyma#13443]
**Description**

The fast-integration test [`skr-aws-svcat-migration-dev`](https://github.com/kyma-project/kyma/blob/main/tests/fast-integration/skr-svcat-migration-test/skr-svcat-migration-test.js) currently consistently fails when checking the status of functions. The test creates 3 functions and then checks if there is a single running pod per each function.

There are exactly 3 types of failures
A) pod stuck in `Pending` status
```
  1) SKR SVCAT migration test
       Should check if pod presets injected secrets to functions containers:
     Error: Failed to find function svcat-auditlog-api-1 pod in 5 minutes.
  Expected 1 serverless.kyma-project.io/function-name=svcat-auditlog-api-1,serverless.kyma-project.io/resource=deployment pod with phase "Running" but found 1, svcat-auditlog-api-1-97l5k-8944db695-phxf7, Pending
      at getFunctionPod (skr-svcat-migration-test/test-helpers.js:68:9)
      at processTicksAndRejections (internal/process/task_queues.js:95:5)
      at async Object.checkPodPresetEnvInjected (skr-svcat-migration-test/test-helpers.js:76:17)
      at async Context.<anonymous> (skr-svcat-migration-test/skr-svcat-migration-test.js:103:5
```
B) pod never coming up
```
  1) SKR SVCAT migration test
       Should check if pod presets injected secrets to functions containers:
     Error: Failed to find function svcat-auditlog-api-1 pod in 5 minutes.
  Expected 1 serverless.kyma-project.io/function-name=svcat-auditlog-api-1,serverless.kyma-project.io/resource=deployment pod with phase "Running" but found 0, , 
      at getFunctionPod (skr-svcat-migration-test/test-helpers.js:68:9)
      at processTicksAndRejections (internal/process/task_queues.js:95:5)
      at async Object.checkPodPresetEnvInjected (skr-svcat-migration-test/test-helpers.js:76:17)
      at async Context.<anonymous> (skr-svcat-migration-test/skr-svcat-migration-test.js:103:5
```
C) multiple pods per function
```
  1) SKR SVCAT migration test
       Should check if pod presets injected secrets to functions containers:
     Error: Failed to find function svcat-auditlog-api-1 pod in 5 minutes.
  Expected 1 serverless.kyma-project.io/function-name=svcat-auditlog-api-1,serverless.kyma-project.io/resource=deployment pod with phase "Running" but found 2, svcat-auditlog-api-1-jhjzk-55b785c5d7-4m5m8,svcat-auditlog-api-1-jhjzk-757c4f649-mznr6, Running,Running
      at getFunctionPod (skr-svcat-migration-test/test-helpers.js:68:9)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (internal/process/task_queues.js:95:5)
      at async Object.checkPodPresetEnvInjected (skr-svcat-migration-test/test-helpers.js:76:17)
      at async Context.<anonymous> (skr-svcat-migration-test/skr-svcat-migration-test.js:103:5)
```

**Expected result**

When a function is created, successfully running single pod within 5 minutes.

**Actual result**

Either 0 pods found, or 1 in pending or 2 in running.

**Steps to reproduce**

https://storage.googleapis.com/kyma-prow-logs/logs/skr-aws-svcat-migration-dev/1495126135929835520/build-log.txt
https://storage.googleapis.com/kyma-prow-logs/logs/skr-aws-svcat-migration-dev/1495246933264961536/build-log.txt
https://storage.googleapis.com/kyma-prow-logs/logs/skr-aws-svcat-migration-dev/1495307332123365376/build-log.txt
https://storage.googleapis.com/kyma-prow-logs/logs/skr-aws-svcat-migration-dev/1495609324838326272/build-log.txt

**Troubleshooting**

**Comment by dbadura** [comment]
You should watch for function status, not functions pod as our controller has race conditions and can create 2 or more deployments.

**Comment by kwiatekus** [comment]
After improving function readiness state there is a different error, but the origina  problem is resolved

**Comment by wozniakjan** [comment]
@kwiatekus unfortunately it doesn't look like readiness check helped at all. The status in `function` may report ready but still, there are frequently either 0 pods, 2 running or 1 pending. Error states happen more frequently than the correct state - a single running pod.

**Comment by kwiatekus** [comment]
I'm running a reduced scenario focused on the function pod lookup against an existing runtime ( not on one that is part of the test setup ):
```js
  it('Should install sample Service Catalog resources', async function() {
    await sampleResources.deploy();
  });

  let secretsAndPresets;
  it('Should store secrets and presets of sample resources', async function() {
    secretsAndPresets = await sampleResources.storeSecretsAndPresets();
  });

  it('Should check if pod presets injected secrets to functions containers', async function() {
    await t.checkPodPresetEnvInjected();
  });
  
   it('Should destroy sample service catalog resources', async function() {
    await sampleResources.destroy();
  });
 ```
 
 Such case is 100% succesful
 
 For me it shows that the flakiness is related with the readiness of the runtime under test.

**Comment by wozniakjan** [comment]
it does look like it reproduces only on freshly provisioned SKRs, along with few other problems,
during the debug session, I created parallel 10 executions of the test from the beginning and it happened for 2
* https://status.build.kyma-project.io/view/gs/kyma-prow-logs/logs/wozniakjan_test_of_prowjob_skr-aws-svcat-migration-dev/1506943305655521280
* https://status.build.kyma-project.io/view/gs/kyma-prow-logs/logs/wozniakjan_test_of_prowjob_skr-aws-svcat-migration-dev/1506943561973633024
As agreed, I will bump the wait period from 5 to 30 minutes for the function to get warmed up and ready. Hopefully, that will reduce the flakiness.

**Comment by wozniakjan** [comment]
for completion, adding findings from @dbadura 

> We noticed that creating service binding usage restart function deployment

Thanks for debugging this, it should be now sufficient concluded and safe to close given service binding usage is deprecated in kyma2 and should be removed fully in kyma2.2
