### ISSUE TITLE
Failure in `kyma-preview-integration-devkyma-preview-integration-dev` pipeline related to OAuth2 connection issues

### ISSUE THREAD

**Issue by tobiscr** [kyma-project/kyma#13446]
**Description**

We are facing multiple failures in the pipeline `kyma-preview-integration-devkyma-preview-integration-dev` (https://status.build.kyma-project.io/?job=kyma-preview-integration-dev) which are related to OAuth2 connctions (TLS handshake seems to fail):

         function should be reachable through secured API Rule:
         Error: Error when requesting bearer token from https://oauth2.d73aa4d.dev.kyma.ondemand.com/oauth2/token: Error: Client network socket disconnected before secure TLS connection was established
          at OAuthToken.getToken (lib/oauth.js:71:17)

**Expected result**

Pipeline runs stable without temporarily failing with OAuth2 connection issues.

**Actual result**

Temporarily failing issues are occurring and root cause analysis are required.

**Steps to reproduce**

**Troubleshooting**

**Comment by varbanv** [comment]
Pipeline is green now.
