### ISSUE TITLE
Correct "ybundles" into "bundles"

### ISSUE THREAD

**Issue by klaudiagrz** [kyma-project/kyma#1344]
There are still some "ybundle" references in the documentation that need to be turned into "bundles".

**Comment by PK85** [comment]
I found some occurrences, please fix:
https://github.com/search?q=org%3Akyma-project+ybundle&type=Code

**Comment by klaudiagrz** [comment]
@PK85 The changes in Markdown files are dealt with by @piotrmiskiewicz in this PR (not merged yet):
https://github.com/kyma-project/bundles/pull/16

I've corrected "ybundles" reference in loader.go in this PR:
https://github.com/kyma-project/kyma/pull/1436

As for the navigation.json and content.json in the website repository, I've contacted the Wookiees team and found out that those files are updated automatically after every release. So we just have to wait until the release and the "ybundle" references will be gone.
