### ISSUE TITLE
More linting rules for eventing components

### ISSUE THREAD

**Issue by nachtmaar** [kyma-project/kyma#13463]
**Description**

While discussing the [results of the Eventing code guidelines](https://github.com/kyma-project/community/pull/628#discussion_r811131065) we started thinking about `linter rules`.
Let's see if we can create some rules out of the code guidelines. 

**Reasons**

Linting rules help us `enforcing` on agreed guidelines. By moving the validation from the reviewer to the linter, it helps us as the reviewer to `concentrate` on the `important aspects` of a PR.

**Comment by nachtmaar** [comment]
Let's collect liniting ideas here:

1. Can we enforce a leading slash on comments ?
```
//TestCreateSubscription tests if subscriptions get created properly by the reconciler.
```

**Comment by k15r** [comment]
We will add additional linters as needed to our build process
