### ISSUE TITLE
Fast integration test fails during checking monitoring component two times in a row

### ISSUE THREAD

**Issue by tobiscr** [kyma-project/kyma#13471]
**Description**

Fast integration tests are failing in pipeline `nightly-main-reconciler-e2e` (see [example](https://storage.googleapis.com/kyma-prow-logs/logs/nightly-main-reconciler-e2e/1495986816472322048/build-log.txt)).

       1) Executing Standard Testsuite:
            Prometheus Tests:
              Prometheus targets should be healthy:
           AssertionError: Following targets are unhealthy: monitoring-operator: Get "http://100.96.1.28:8080/metrics": context deadline exceeded: expected [ 'monitoring-operator: Get "http://100.96.1.28:8080/metrics": context deadline exceeded' ] to be empty
           at Object.assertAllTargetsAreHealthy (monitoring/prometheus.js:36:10)
           at async Context.<anonymous> (test/3-monitoring.js:26:7)

**Expected result**

Fast integration test for monitoring can be passed without issues.

**Actual result**

Fast integration tests are failing when verifying monitoring metrics.

**Steps to reproduce**

**Troubleshooting**

**Comment by pbochynski** [comment]
It should be resolved now.
