### ISSUE TITLE
Configurable stream storage (volume, in-memory)

### ISSUE THREAD

**Issue by pxsalehi** [kyma-project/kyma#13486]
The storage type (file or memory) of the stream used by the JetStream backend should be configurable and have defaults set via the in the execution profiles:
- Evaluation profile should use `memory` by default.
- Production profile should use `file` by default.

**Comment by k15r** [comment]
Do we already have any documentation stating how to select / configure this storage?

**Comment by pxsalehi** [comment]
https://github.com/kyma-project/kyma/commit/20bc83c2c797ff68cefdc785465bf2e8b971926f
https://github.com/kyma-project/kyma/blob/main/resources/eventing/charts/controller/values.yaml#L77
