### ISSUE TITLE
Enable forwarding X-Forwarded-Client-Cert headers in Istio

### ISSUE THREAD

**Issue by mjakobczyk** [kyma-project/kyma#13492]
**Description**

We should enable forwarding `X-Forwarded-Client-Cert` header values in Istio for mTLS connection. Until now we sanitise it. Quote from [Istio docs](https://istio.io/latest/docs/ops/configuration/traffic-management/network-topologies/#forwarding-external-client-attributes-ip-address-certificate-info-to-destination-workloads):

> While Istio provides an [ingress gateway](https://istio.io/latest/docs/tasks/traffic-management/ingress/ingress-control/), given the varieties of architectures mentioned above, reasonable defaults are not able to be shipped that support the proper forwarding of client attributes to the destination workloads.

As a result, [according to the docs, we use `SANITIZET_SET` as default value](https://istio.io/latest/docs/ops/configuration/traffic-management/network-topologies/#forwarding-external-client-attributes-ip-address-certificate-info-to-destination-workloads):

> SANITIZE_SET | When the client connection is mTLS, reset the XFCC header with the client certificate information and send it to the next hop. This is the default value for a gateway.

**Reasons**

There are plenty of use cases which may require passing additional information in this header. Istio offers plenty of different modes for this header so we can offer a solution that could be used by customers.

**AC**

- [ ] `X-Forwarded-Client-Cert` headers are sanitised by Istio when using Kyma Gateway
- [ ] `X-Forwarded-Client-Cert` headers are not sanitised by Istio when using custom Gateway with mTLS enabled
- [ ] docs updated

**Attachments**

Have a look at official Istio docs considering [configuration of X-Forwarded-Client-Cert headers](https://istio.io/latest/docs/ops/configuration/traffic-management/network-topologies/#configuring-x-forwarded-client-cert-headers)

**Comment by cnvergence** [comment]
Decided to not change the default value, as the feature request is not valid anymore.
