### ISSUE TITLE
Pipeline failing with OAuth issue

### ISSUE THREAD

**Issue by tobiscr** [kyma-project/kyma#13498]
**Description**

Following pipelines files 80% of the runs caused by a failing OAuth2 authentication:

https://status.build.kyma-project.io/?job=pre-main-control-plane-reconciler-upgrade-kyma2-latest-to-main-gardener

      1) Upgrade test tests
           function should be reachable through secured API Rule:
         Error: Error when requesting bearer token from https://oauth2.grdpxu2vv.kyma-prow.shoot.canary.k8s- 
   hana.ondemand.com/oauth2/token: 401 Unauthorized
          at OAuthToken.getToken (lib/oauth.js:69:17)
          at processTicksAndRejections (internal/process/task_queues.js:95:5)
          at async checkFunctionResponse (test/fixtures/commerce-mock/index.js:130:23)
          at async Context.<anonymous> (upgrade-test/upgrade-test-tests.js:29:5)

**Expected result**

Oauth2 authentication is not causing failures in the pipeline.

**Actual result**

STable pipeline.

**Steps to reproduce**

**Troubleshooting**

**Comment by veichtj** [comment]
After first analysis it turned out that the synchronization of OAuth2Clients between hydra-maester and hydra is not working properly. We are currently improving this and verify if it solves the frequent pipeline issues

**Comment by veichtj** [comment]
Issue should be fixed, waiting for bump of reconciler in control plane: https://github.com/kyma-project/control-plane/pull/1451

**Comment by cnvergence** [comment]
I could reproduce it during the upgrade from Kyma 2.0.4 to main on the Gardener cluster.
After upgrade reconciliation, ory-hydra was rolled back to the old replica set and hydra-maester was not restarted, so oauth2 clients were lost.
The root cause was the Istio Proxy Reset during the upgrade also restarted ory-hydra, so our syncer logic was missing a few checks to overcome this issue.

**Comment by cnvergence** [comment]
'm closing this one as there is another issue with this pipeline
https://github.com/kyma-project/kyma/issues/13835

**Comment by cnvergence** [comment]
I'm closing this one as there is another issue with this pipeline
https://github.com/kyma-project/kyma/issues/13835
