### ISSUE TITLE
API Gateway Documentation still references Istio Ingress

### ISSUE THREAD

**Issue by akrausesap** [kyma-project/kyma#135]
Confirm these statements before you submit the issue:

- [ X] I have searched open and closed issues for duplicates.
- [X ] I have read the contributing guidelines.
---

**Description**
Hi Colleagues,
The API Gateway Architecture Documentation (kyma/docs/api-gateway/docs/005-architecture.md) still references Istio Igress which should be changed to Virtual Service.

Cheers

Andreas

**Expected result**

N/A

**Actual result**

N/A

**Steps to reproduce**

N/A

**Troubleshooting**

N/A

**Comment by tomekpapiernik** [comment]
@akrausesap Docs updated
