### ISSUE TITLE
Create upgrade pipeline per eventing backend

### ISSUE THREAD

**Issue by friedrichwilken** [kyma-project/kyma#13504]
**Description**

Create an automated test covering the scenario for upgrading a cluster.

in case of normal pipelines (merge to main):
* kyma cluster with latest kyma release get upgraded to kyma main

in case of release testing:
* kyma cluster with previous released version get upgraded to release under test.

consider:
reevaluate existing eventing upgrade job: 
- create one upgrade job per backend
- investigate: do we still need testing backend switching in the upgrade job?

if it is possible, configurable with env, to test eventing upgrade per backend, that takes the backend type as an env var

**Reasons**

ensure clusters work after upgrading

**Acceptance**

- [ ] validate eventing works before and after upgrade
- [ ] validate subscriptions created before upgrade still work after upgrade
- [ ] create one upgrade job per backend

**Attachments**

**Comment by k15r** [comment]
New pipelines will be introduced with modular eventing
