### ISSUE TITLE
add istio 1.12.x bump to release notes of 2.1

### ISSUE THREAD

**Issue by piotrkpc** [kyma-project/kyma#13531]
**Description**
Istio is expected to be in 1.12.x version for 2.1. Ensure information is added to release notes.

**Attachments**

https://github.com/kyma-project/kyma/issues/12668

**Comment by mjakobczyk** [comment]
The following statement was added:
> ### Istio upgraded to 1.12.3 
> In this release, we upgraded Istio from 1.11.4 to 1.12.3. For more details on the introduced changes, read the official [Istio 1.12.3 release notes](https://istio.io/latest/news/releases/1.12.x/announcing-1.12.2/). 

Closing.
