### ISSUE TITLE
Use an appropriate stream name extracted out of eventPrefix [JetStream]

### ISSUE THREAD

**Issue by mfaizanse** [kyma-project/kyma#13544]
**Description**
Currently, in the JetStream eventing backend we have separately defined stream name (which is also configurable). But it would be better to extract out an appropriate stream name out from the eventPrefix which is present in [this configMap.](https://github.com/kyma-project/kyma/blob/main/resources/eventing/templates/configmap.yaml) Unless, if the eventPrefix is empty, then we can use some default value for stream name.

**Reasons**

The benefit would be that we won't have to append any other prefix to the subscription's subjects while creating consumers on JetStream.

**Comment by mfaizanse** [comment]
Question: What if the event prefix is empty? What should be the stream name in this case?

**Comment by k15r** [comment]
> Question: What if the event prefix is empty? What should be the stream name in this case?

Introduce a hardcoded prefix for that case. This needs to be prepended during publishing and be removed during dispatching.

**Comment by mfaizanse** [comment]
The `streamName` will be passed to EPP as a ENV variable and will be taken care of in this [issue](https://github.com/kyma-project/kyma/issues/13224).

**Comment by mfaizanse** [comment]
Updates:
- Decoupled stream subjects filter from stream name.
- If `eventTypePrefix` is not empty, then we will use `eventTypePrefix` in stream subjects filter. Otherwise if `eventTypePrefix` is empty, then we will use some default value.
