### ISSUE TITLE
Tutorial on how to secure workload with JWT token using Istio

### ISSUE THREAD

**Issue by strekm** [kyma-project/kyma#13556]
**Description**

Create step by step tutorial explaining how to expose workload using [Istio authorization policy](https://istio.io/latest/docs/reference/config/security/authorization-policy/) and [Istio request authentication](https://istio.io/latest/docs/reference/config/security/request_authentication/). The tutorial should contain the necessary steps and example resources to secure a workload. Deploying workload and obtaining JWT should not be a part of this tutorial. 

AC:
- [x] Tutorial (an `.md` file) with complete steps on how to expose and secure a deployed workload
- [x] Location: `kyma` respository `kyma-project/kyma/tree/main/docs/03-tutorials/00-api-exposure`
- [x] When you create the new file, stick to the following naming convention: `{COMPONENT_ABBRV}-{NUMBER_PER_COMPONENT}-{FILE_NAME}.md}`, and for example name it `apix-04-expose-and-secure-workload-jwt-istio-ext-auth.md` 
- [x] The tutorial should be a follow-up of the [Create a workload](https://deploy-preview-13513--kyma-project-docs-preview.netlify.app/docs/kyma/preview/03-tutorials/00-api-exposure/apix-02-create-workload/) tutorial
- [x] Add links to the new tutorial in the **Next steps** section of [Create a workload](https://deploy-preview-13513--kyma-project-docs-preview.netlify.app/docs/kyma/preview/03-tutorials/00-api-exposure/apix-02-create-workload/#next-steps) and in the **Next steps** section of [Use a custom domain to expose a workload ](https://deploy-preview-13513--kyma-project-docs-preview.netlify.app/docs/kyma/preview/03-tutorials/00-api-exposure/apix-01-own-domain/#next-steps)
- [x] Add a link to the document to the [Useful links](https://deploy-preview-13513--kyma-project-docs-preview.netlify.app/docs/kyma/preview/01-overview/main-areas/api-exposure/apix-02-useful-links/) document in the **Overview -> Main areas -> API Exposure -> Useful links**
- [x] Use the [tutorial template](https://github.com/kyma-project/community/blob/main/templates/resources/tutorial.md)
- [x] Test the complete flow

> **TIP:** You can use the unpublished document **Expose and secure a workload with JWT** as a template/sample document on a similar topic:
> - [apix-04-expose-and-secure-workload-jwt.md](https://github.com/kyma-project/kyma/files/8197784/apix-04-expose-and-secure-workload-jwt.md)

**Area**

- Service mesh
- Security / API Exposure

**Reasons**

**Assignees**

@kyma-project/technical-writers

**Attachments**

part of: https://github.com/kyma-project/kyma/issues/12669

**Comment by werdes72** [comment]
Tutorial is ready: https://kyma-project.io/docs/kyma/main/03-tutorials/00-api-exposure/apix-04-expose-and-secure-workload-istio/
