### ISSUE TITLE
Enable NAT Gateway for Azure clusters on Prod landscapes

### ISSUE THREAD

**Issue by varbanv** [kyma-project/kyma#13553]
**Description**
Enable NAT Gateway for Azure clusters on production landscapes.

**Reasons**
We have many requests from customers for stable egress IPs for Kyma clusters in order to implement access lists in target services consumed from Kyma workloads. 
Currently, the IPs on AWS and GCP clusters are stable and this allow for inclusion in access lists. However, NAT Gateway on Azure is disabled by default and thus the egress IPs could change.
One of the major use cases is for HANA Cloud consumption from Kyma workloads.

**Comment by janmedrek** [comment]
In the past we've seen that Gardener-assigned IP for NAT Gateways sometimes may change, we've confirmed that it is indeed a bug and should not happen. We will proceed with enabling the NAT Gateway for each Azure cluster without creating a new resource group with a public IP, if the problem pops up we will need to solve it on the Gardener level. 

If it is indeed changing - I will drop the link to the issue here.

**Comment by pbochynski** [comment]
@janmedrek @Maladie Can we somehow expose the NAT Gateway IP to the user? What is the recommendation? 
I couldn't find a better way then just to create some pod in the cluster and call some external service from inside the cluster:
```
kubectl run -i --tty busybox --image=yauritux/busybox-curl --restart=Never 
curl ifconfig.me
```

**Comment by janmedrek** [comment]
@pbochynski Unfortunately, there is no info on the assigned IP for the NAT Gateway in Gardener. This would mean the possible options are:
- Calling external service to check the IP (the method you've presented)
- Extracting that from the Azure API and putting some kind of ConfigMap in the cluster that would contain the IP, then displaying that in Busola

The problem with the second option is that we are not directly interacting with Azure when it comes to infrastructure. It may be the responsibility of the Network Reconciler in the [proposed new architecture of Control-Plane](https://github.com/kyma-project/kyma/issues/13759). I would keep it on the list and go with the 1st option, for now, implementing automation would require a lot of shifts in the approach we currently have and would introduce quite a lot of implementation effort which we really cannot afford right now.

**Comment by PK85** [comment]
Keb need to set https://github.com/kyma-project/control-plane/pull/1561/files#diff-1f250467b2cc0db8677f6ceedeb518579772a4d74cb7ee1647a78d6e319e398c to true for Kyma Azure Plan

**Comment by tillknuesting** [comment]
> We MUST NOT reconfigure existing cluster to use NAT gateway as it would involve change of the outbound IPs used for the exiting runtimes. Who requested this change?
SRE @ebensom states that upgrades are not needed therefore https://github.com/kyma-project/control-plane/pull/1942 is closed.

**Comment by ebensom** [comment]
@PK85 

> Set that Nat Gateway for all existing Azure/Azure_lite Kymas ( maybe in upgrade Cluster phase, when SRE will need call upgrades of clusters)

This action is not needed because it would involve change of the outbound IPs used for the exiting runtimes, and for many runtimes the customer already assume the IPs not to change and they configured ACLs in their respective corporate firewalls.
