### ISSUE TITLE
Implement Testing framework  in eventing components as per guidelines

### ISSUE THREAD

**Issue by nachtmaar** [kyma-project/kyma#13564]
Use `testing.T` in all eventing components. This especially means we need to migrate from `ginkgo` to `testing.T` for all of our controller integration tests.
This has already been done for the nats controller integration tests, see this [PR](https://github.com/kyma-project/kyma/pull/13409)

See [Recommended libraries section of eventing team code/testing guidelines](https://github.com/kyma-project/community/blob/main/concepts/eventing-code-guidelines.md#recommended-libraries).

#### Acceptance Criteria
Component status for controller **integration** tests:
- [ ] components/`eventing-controller`: 
  - [ ] BEB: ginkgo + gomega [**fail** 𐄂]
  - [ ] NATS: ginkgo + gomega (soon: **testing.T** + gomega) [**fail** 𐄂]
  - [ ] Backend: ginkgo + gomega/testify(only few lines) [**fail** 𐄂] [src](https://github.com/FriedrichWilken/kyma/blob/reimplement-nats-intgration-with-plain-go/components/eventing-controller/controllers/backend/reconciler_test.go)
- [ ] Also look for additional places where we need to update.

**Comment by nachtmaar** [comment]
I did a quick check on our eventing components:

Syntax of bullet points: \<Testing lib\> + \<assertion lib\>

Component status for **unit** tests:
- [ ]  components/`eventing-controller`: [**fail** 𐄂] 
  - testing.T + gomega and
  - testing.T as test runner + testing.T as assertion lib and
  - testing.T + stretchr/testify (only few lines in /controllers/backend/reconciler_test.go)
- [ ] components/`event-publisher-proxy`: [nearly check ✔]
  - testing.T + stretchr/testify
  - testing.T + gomega (only 1 file: pkg/tracing/helpers_test.go)
- [ ] control-plane/components/`kyma-metrics-collector`: testing.T + gomega [**fail** 𐄂]  [src](https://github.com/kyma-project/control-plane/blob/main/components/kyma-metrics-collector/pkg/keb/client_test.go)

Component status for controller **integration** tests:
- [ ] components/`eventing-controller`: 
  - [ ] BEB: ginkgo + gomega [**fail** 𐄂]
  - [ ] NATS: ginkgo + gomega (soon: **testing.T** + gomega) [**fail** 𐄂]
  - [ ] Backend: ginkgo + gomega/testify(only few lines) [**fail** 𐄂] [src](https://github.com/FriedrichWilken/kyma/blob/reimplement-nats-intgration-with-plain-go/components/eventing-controller/controllers/backend/reconciler_test.go)

**Comment by k15r** [comment]
with ongoing refactoring this ticket will be automatically addressed
