### ISSUE TITLE
`make test` for `event-publisher-proxy` fails

### ISSUE THREAD

**Issue by k15r** [kyma-project/kyma#13568]
**Description**

running `make test` in for the event-publisher proxy component fails

**Expected result**

it works

**Actual result**

```
Unable to find image 'make:latest' locally
Error response from daemon: pull access denied for make, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
make test
must specify at least one container source
make: *** [test] Error 1
```

**Steps to reproduce**

run `make test`

**Troubleshooting**

**Comment by mfaizanse** [comment]
PR: https://github.com/kyma-project/kyma/pull/13949
