### ISSUE TITLE
Implement Structured logging in eventing components and KMC as per guidelines

### ISSUE THREAD

**Issue by nachtmaar** [kyma-project/kyma#13560]
Use `uber-go/zap` as `structured logging library` in all eventing components.

See [Recommended libraries section of eventing team code/testing guidelines](https://github.com/kyma-project/community/blob/main/concepts/eventing-code-guidelines.md#recommended-libraries).

Furthermore, consider using `github.com/kyma-project/kyma/common/logging/logger`, which provides further abstraction over uber-go/zap.

#### Acceptance Criteria
- [ ] Investigate which parts of code needs to be updated, along with:
  - [ ] components/event-publisher-proxy: logrus  [**fail** 𐄂] 
  - [ ] Check for KMC again.

**Comment by nachtmaar** [comment]
I did a quick check on our eventing components:
- [ ] components/eventing-controller: zap [check ✔]
- [ ] components/event-publisher-proxy: logrus  [**fail** 𐄂]
- [ ] control-plane/components/kyma-metrics-collector: zap [check ✔]

**Comment by raypinto** [comment]
As logging situation was improved lately, closing this issue. Reopen when needed.
