### ISSUE TITLE
Alertmanager alerts: Many Kubelets cannot be scraped

### ISSUE THREAD

**Issue by nexus49** [kyma-project/kyma#1359]
**Description**
When running kyma on GKE we see the following slack alerts frequently firing: 

![image](https://user-images.githubusercontent.com/52737/47265220-c5de0180-d524-11e8-9a7f-e68241e0f490.png)

**Expected Result**
a) I don't expect to see alerts on a healthy system after the installation.

b) When receiving an alert i'd expect that it is easy to track from what system the alert originated. The link in the alert links to `http://core-alertmanager.kyma-system:9093/#/alerts?receiver=slack` which is not a valid url for the system.

I'm happy to provide access to test systems for investigations.

**Comment by venturasr** [comment]
Related PR https://github.com/kyma-project/kyma/pull/1463

**Comment by joek** [comment]
The issues should be fixed with 0.5 version
