### ISSUE TITLE
Kyma main version installed on gardener can't be hibernated

### ISSUE THREAD

**Issue by strekm** [kyma-project/kyma#13617]
**Description**

Gardener cluster with kyma main version installed can't be hibernated. 
`MutatingWebhookConfiguration "istio-revision-tag-default" is problematic...`

**Expected result**

Cluster can be hibernated

**Actual result**

Gardener hibernate button is inactive

**Steps to reproduce**

Install kyma main with stable kyma cli on gardener cluster.

**Troubleshooting**

Kyma commit used for installation: [4e21921](https://github.com/kyma-project/kyma/commit/4e21921a23feed0d241d92f4e054fcf9becc3c1e)
Kyma cli version: `stable-9407a4a`
Cluster: gardener gcp cluster with k8s 1.21.9

**Comment by piotrkpc** [comment]
After renaming [Istio components ](https://github.com/kyma-project/kyma/pull/13603) we enabled logic introduced with PR: [Well defined actions for Istio reconciler](https://github.com/kyma-incubator/reconciler/pull/789). However, reconciler currently does not allow registering multiple `PostReconcileAction`s:
https://github.com/kyma-incubator/reconciler/blob/26e680a8dde664cb5689fcbd79fb38fbcacd8209/pkg/reconciler/service/reconciler.go#L203-L206
This is causing that with new approach the first `PostReconcileAction` is overwritten and not executed in the control loop (`MutatingWebhookPostAction` in our case)
We need to improve test coverage of Istio Reconciler.

**Comment by piotrkpc** [comment]
After https://github.com/kyma-incubator/reconciler/pull/939 merge, we need to bump kyma cli

**Comment by veichtj** [comment]
Ready for retest

**Comment by strekm** [comment]
verified with [kyma](https://github.com/kyma-project/kyma/commit/d208b98c8202d49253fb02b78636e95077ce28b3) and kyma-cli version: `stable-9d40643`
