### ISSUE TITLE
Tracing Instrumentation doesn't work for outgoing axios requests in nodejs function runtimes 

### ISSUE THREAD

**Issue by kwiatekus** [kyma-project/kyma#13635]
**Description**

It looks like our tracing instrumentation configuration does not cover all cases for outgoing requests.
We realised i.e that there are missing tracing spans matching axios outgoing requests as seen from the initiating function. 

It is most likely related to the selected instrumentation API chosen.
We could use the latest HttpInstrumentation or use  [`XMLHttpRequestInstrumentation`](https://www.npmjs.com/package/@opentelemetry/instrumentation-xml-http-request) as it supports axios requests as well

**Expected result**

Tracing headers should be automatically passed to the outgoing requests.
Outgoing requests (realised via axios in the function ) should have matching spans in the jaeger.

**Actual result**

Axios requests are lacking trace headers even though http intrumentation is [configured](https://github.com/kyma-project/kyma/blob/339429ba4a8d084b46a812c50d5c6ca51616f59f/components/function-runtimes/nodejs14/kubeless/kubeless_rt/lib/tracer.js#L17).

**Steps to reproduce**

Create 2 functions, ie in the emitter-receiver setup as described in the [example](https://github.com/kyma-project/examples/tree/main/incluster_eventing)
Send http request to the first one.
The second function will be called via evening, but there will be no trace for that call visible in the call stack in jaeger.

**Comment by pPrecel** [comment]
Story described in the ticket is not a bug. Node runtimes support auto-instrumented trace for `http`, `https`, `XMLHttpRequest` and `axios` and there is no need to implement another instrumentation tool like `XMLHttpRequestInstrumentation`. The only problem is when you would use functions SDK method `publishCloudEvent` (which is using axios) and you would not import axios then tracing of outgoing events would not work well from your function. To avoid misunderstanding and confusion of this topic I've created [the PR](https://github.com/kyma-project/kyma/pull/13696) to improve documentation.
