### ISSUE TITLE
Enable dependabot for some projects in Kyma

### ISSUE THREAD

**Issue by koala7659** [kyma-project/kyma#13646]
Please enable dependabot for automatic dependency bump of libraries in following projects in Kyma:

- compass-runtime-agent
- central-application-gateway
- central-application-connectivity-validator
- application-registry
- application-connectivity-certs-setup-job
- application-operator
- application-gateway
- connector-service

**Comment by dekiel** [comment]
@koala7659 by projects you mean directories in `components` directory? it's only about golang dependency or we should enable it for Dockerfiles too?

**Comment by koala7659** [comment]
@dekiel Yes, please enable it for Dockerfile as well
