### ISSUE TITLE
Support switching with other backend (cleanup on JetStream side)

### ISSUE THREAD

**Issue by pxsalehi** [kyma-project/kyma#13679]
Similar to NATS, when the active backend is switch from JetStream to BEB, we need to clean up resources that have been created on JetStream when sync'ing the Kyma subscriptions.

JetStream-specific issues to consider:
- [x] Do we need to delete the Stream?

**Comment by raypinto** [comment]
As discussed, we agreed to delete the Stream and the associated PVC for JetStream as part of the cleanup. Since we can only implement this after this issue is resolved, we will update the JetStream cleanup as part of [this issue.](https://github.com/kyma-project/kyma/issues/13704)
