### ISSUE TITLE
Remove dex fork

### ISSUE THREAD

**Issue by strekm** [kyma-project/kyma#13684]
**Description**

Since dex is not part of kyma since kyma 2.0 release remove dex for from https://github.com/kyma-incubator/dex

**Reasons**

Removing unused components from Kyma.

**Attachments**

https://github.com/kyma-project/kyma/issues/12258

**Comment by barchw** [comment]
PR: https://github.com/kyma-project/test-infra/pull/5929

**Comment by strekm** [comment]
https://github.com/kyma-incubator/dex is archived. it will be deleted in by the end of year

**Comment by strekm** [comment]
closing as dex fork was removed
