### ISSUE TITLE
Remove tight coupling of publish URL to applications deployed in Kyma for creating events

### ISSUE THREAD

**Issue by abbi-gaurav** [kyma-project/kyma#1368]
### Description

It is possible in Kyma to create internal events and use them to trigger computation. 

This is achieved by making an HTTP POST request to `http://core-publish.kyma-system:8080/v1/events` with the event payload as a part of the request body.

### Problem
This tightly couples the URL details with the applications using it.

### Proposed Solution
A better approach would be to inject the URL as an environment variable inside each pod created in Kyma.

### Implementation:
* Inject `publish URL` into PODs created in the Kyma environment. (if possible do not inject for `istio-system` namespace).

>Hint: Look at POD Preset.

### AC:
- [ ] Applications requiring to create events do not hardcode the publish URL.
- [ ] The information about the environment variable is documented.

**Comment by Abd4llA** [comment]
Still relevant
