### ISSUE TITLE
End to End Principal Propagation via Application Connector

### ISSUE THREAD

**Issue by akrausesap** [kyma-project/kyma#1370]
**Description**

To better support extensibility it would be good to have an End 2 End Principal Propagation Capability in the Application Connector. This should cover incoming Events as well as outgoing API Calls (assuming incoming API Calls are covered via the JWT Token). 

For outgoing calls, many SAP Systems support SAML2 oAuth2 Grant Type (Basically the same as resource owner credentials, but with a SAML2 Assertion instead of UN/PW).

**Reasons**

Have E2E Authorizations and Audit log

**Attachments**

https://wiki.scn.sap.com/wiki/display/Security/Using+OAuth+2.0+from+a+Web+Application+with+SAML+Bearer+Assertion+Flow

**Comment by hansamann** [comment]
Absolutely necessary feature, e.g. for layers that build on top of app connectors such as a GraphQL kyma service ....  +1

**Comment by gregorwolf** [comment]
Hi @akrausesap,

the SAML Bearer Assertion Flow is quite a lot of back and forth. Also it requires a lot of setup work. The default option currently used in SAP Cloud Platform Neo and also Cloud Foundry for principal propagation is to use the SAP Cloud Connector which has a trusted connection to the Cloud Platform and exchanges the principal that is forwarded in the request with a short living X.509 Client Certificate. That needs only to be setup once and works for all API endpoints. Not only OData services as the SAML Bearer Assertion Flow.

Best regards
Gregor

**Comment by gregorwolf** [comment]
Would still hope that Principal Propagation is still on the things coming.

**Comment by gregorwolf** [comment]
Can the Kyma team give an update to this issue?

**Comment by gregorwolf** [comment]
Still hope for a solution.

**Comment by gregorwolf** [comment]
Maybe this issue is solved for the SAP Hosted Kyma as described here: [Connectivity Proxy for Kubernetes](https://help.sap.com/viewer/cca91383641e40ffbe03bdc78f00f681/Cloud/en-US/e661713ef7d14373b57e3e26b0b03b86.html)

**Comment by gregorwolf** [comment]
As there was no answer to my question I would suggest that this issue is opened again.

**Comment by pbochynski** [comment]
Yes - the principal propagation is supported by the Connectivity Proxy which is part of Kyma Runtime hosted by SAP. There is no plan to implement it in Kyma OSS.
