### ISSUE TITLE
JetStream Cleanup should also cleanup the PVC for file storage

### ISSUE THREAD

**Issue by raypinto** [kyma-project/kyma#13704]
**Description**

With cleanup implemented [here](https://github.com/kyma-project/kyma/pull/13703), we cleanup only the subscription status. In addition we need to clean up the PVC created for Jetstream file storage. At the moment this is not possible, since the PVC goes into `Terminating` state and is removed only if the `eventing-nats` StatefulSet is either deleted or scaled down. The deletion of the StatefulSet will be done as part of [this issue](https://github.com/kyma-project/kyma/issues/11653) after which we can update the JetStream controller cleanup logic to remove the PVCs and streams, if any.

**Reasons**

Complete cleanup of JetStream resources.

**Attachments**

**Comment by friedrichwilken** [comment]
@raypinto do we have any updates here?

**Comment by k15r** [comment]
not required with the planned NATS-manager
