### ISSUE TITLE
Make the pre-main-skr-eventing-job required and add it as a pre-submit for release branches

### ISSUE THREAD

**Issue by vpaskar** [kyma-project/kyma#13709]
**Description**

In https://github.com/kyma-project/kyma/issues/13393 the [pre-main-skr-eventing ](https://status.build.kyma-project.io/job-history/gs/kyma-prow-logs/pr-logs/directory/pre-main-kyma-skr-eventing) pipeline was refactored and fixed. 

**Tasks**

pre-requisite: https://github.com/kyma-project/kyma/issues/15128

Let's wait until the job gets executed some time on the different PRs and check whether it's reliable or not. If the job will be green and reliable then:  

- [ ] convert into mandatory job as soon as its execution stabilised
- [ ] add as pre submit also to the release branches (starting latest release)

**Comment by FriedrichWilken** [comment]
Here is [a PR](https://github.com/kyma-project/test-infra/pull/5238) to make the job required. Since the job is flaky at the moment, consider this issue and PR to be blocked.

**Comment by mfaizanse** [comment]
https://github.com/kyma-project/kyma/issues/15128
