### ISSUE TITLE
Installation guide should outline docker resource requirements

### ISSUE THREAD

**Issue by a-thaler** [kyma-project/kyma#13723]
**Description**
When running Kyma local using K3D, the default settings for the docker runtime are not sufficient and not all pods will start up.
The installation guide should outline that prerequisite with a suggestion for proper values for memory and CPU.

**Expected result**

**Actual result**

**Steps to reproduce**

**Troubleshooting**

**Comment by NHingerl** [comment]
Who can advise which Docker resources are required?

**Comment by NHingerl** [comment]
Current assumption would be 4 CPUs and 8 GB RAM for Eval profile. 
Waiting for confirmation by @dennis-ge, and for information about the Prod profile.
