### ISSUE TITLE
TLS cert rotation causes ingress gateway downtime

### ISSUE THREAD

**Issue by sjanota** [kyma-project/kyma#1372]
**Description**

In order to change TLS certs in front of Kyma one need to restart ingress gateway. Ingress gateway should be scaled up and its restart should be done via rolling update.

**Reasons**

This makes Kyma to be unresponsive for some time.

**Attachments**

**Comment by nexus49** [comment]
FYI

As part of the certificate update process on our end we solved this now by patching the `istio-ingressgateway` deployment causing a rolling update.
