### ISSUE TITLE
test e2e eventing with empty prefix

### ISSUE THREAD

**Issue by nachtmaar** [kyma-project/kyma#13738]
## Description

in theory eventing can be configured with an empty `event-type-prefix`. Unfortunately there are no tests to verify the e2e flow with such a configuration.

## Acceptance:
- [ ] setup cluster with empty prefix
- [ ] run entire eventing test suite on that cluster (backend switching, tracing, monitoring, server restarts ... )

**Comment by k15r** [comment]
will be obsolete when #13797 is implemented
