### ISSUE TITLE
Implement the e2e scenario for JetStream in the FastIntegration tests

### ISSUE THREAD

**Issue by nachtmaar** [kyma-project/kyma#13739]
- [x] test switching scenario (from BEB to JS and from JS to BEB) in the FI tests
  - [x] Create a new Prow job.
  - [x] Event-Mesh instance on Prow both should use different names when creating BEB webhooks to avoid collisions. 
  - [ ] test server restart scenario (jetstream with file storage)

Partial Dependency:
- https://github.com/kyma-project/kyma/issues/13742

**Comment by marcobebway** [comment]
Tasks:
- [x] test switching scenario (from BEB to JS and from JS to BEB) in the FI tests
- [x] Create a new Prow job.
- [x] Event-Mesh instance on Prow both should use different names when creating BEB webhooks to avoid collisions.
- [x] test server restart scenario (jetstream with file storage)
