### ISSUE TITLE
Tracing and Observability for JetStream

### ISSUE THREAD

**Issue by raypinto** [kyma-project/kyma#13742]
- Dashboards to visualise metrics that we emit
  - [ ] dashboard to visualise Stream usage
  - [ ] Rework existing dashboard for JS
  - [ ] NATS specific metrics (CPU, storage, errors) for JS
- Tracing: 
  - [ ] Make sure tracing still works
- [ ] Update Prow jobs created [here](https://github.com/kyma-project/kyma/issues/13739) if necessary

**Comment by mfaizanse** [comment]
Tracing seems to be working:

![image](https://user-images.githubusercontent.com/9897945/161936766-0166a49d-8da1-4026-b712-fa8e713c1714.png)

**Comment by mfaizanse** [comment]
![image](https://user-images.githubusercontent.com/9897945/161972416-d6dd2bd3-69c2-480f-8264-02a70eddfb32.png)

--

![image](https://user-images.githubusercontent.com/9897945/161972492-afbff930-7d61-4c45-9a8c-27ba640f8e34.png)

**Comment by mfaizanse** [comment]
Follow up: Check if we can somehow show actual consumer names.
