### ISSUE TITLE
[Automated updates] Categorise charts customisations for monitoring/prometheus-node-exporter

### ISSUE THREAD

**Issue by lindnerby** [kyma-project/kyma#13754]
**Description**

Have a look at all charts present in https://github.com/kyma-project/kyma/tree/main/resources/monitoring/prometheus-node-exporter and compare it with the upstream charts of the corresponding version (may be not the latest!).
Charts locations: tbd
Upstream version: tbd

**Acceptance criteria**

* List all customizations and categorize as a comment in here
* List items format:
  * Per file short summary of customizations
  * Relative link to file and line number of customization
* Make a decision on either **dropping customizations** or **contributing them to upstream** or **patching them on updates**

**Comment by a-thaler** [comment]
It is not clarified on how to continue with the overall story. Having dummy sub-tickets is not helping, so closing them for now
