### ISSUE TITLE
job: pre-main-reconciler-cli-kyma-prev-to-last-release-upgrade-k3d always fails

### ISSUE THREAD

**Issue by Tomasz-Smelcerz-SAP** [kyma-project/kyma#13761]
**Description**

The job is failing on unit tests. Two most occuring failures:
- Prometheus scrape pools should have a target: Upgrade test tests Prometheus Tests: Prometheus scrape pools should have a target 
- function should be reachable through secured API Rule: Upgrade test tests function should be reachable through secured API Rule

The error from the Prometheus failure:
```
{Following scrape pools have no targets: kyma-system/monitoring-node-exporter/0, kyma-system/monitoring-alertmanager/0: expected [ Array(2) ] to be empty AssertionError AssertionError: Following scrape pools have no targets: kyma-system/monitoring-node-exporter/0, kyma-system/monitoring-alertmanager/0: expected [ Array(2) ] to be empty
    at Object.assertScrapePoolTargetsExist (monitoring/prometheus.js:66:10)
    at async Context.<anonymous> (monitoring/index.js:40:7)}
```

The error from the API Rule failure:
```
{Error when requesting bearer token from https://oauth2.local.kyma.dev/oauth2/token: 401 Unauthorized Error Error: Error when requesting bearer token from https://oauth2.local.kyma.dev/oauth2/token: 401 Unauthorized
    at OAuthToken.getToken (lib/oauth.js:69:17)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async checkFunctionResponse (test/fixtures/commerce-mock/index.js:130:23)
    at async Context.<anonymous> (upgrade-test/upgrade-test-tests.js:36:5)}
```

Link to the job:
https://status.build.kyma-project.io/?job=pre-main-reconciler-cli-kyma-prev-to-last-release-upgrade-k3d

**Expected result**
Job is not failing

**Comment by jakobmoellersap** [comment]
Also affects `pre-main-reconciler-cli-kyma-prev-to-last-release-upgrade-k3d `

**Comment by jakobmoellersap** [comment]
@Tomasz-Smelcerz-SAP Closing since Job has stabilized after updates of the kyma pipeline scripts for migration
