### ISSUE TITLE
job: kyma-preview-integration-dev is unstable

### ISSUE THREAD

**Issue by Tomasz-Smelcerz-SAP** [kyma-project/kyma#13760]
**Description**

kyma-preview-integration-dev failed twice today (28.03.2022) with:

```
 1) Execute SKR test
       CommerceMockTest()
         function should be reachable through secured API Rule:
     Error: Function lastorder responded with error
500: Internal Server Error: "Internal Server Error"
      at convertAxiosError (utils/index.js:109:10)
      at /home/prow/go/src/github.com/kyma-project/kyma/tests/fast-integration/test/fixtures/commerce-mock/index.js:141:11
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (internal/process/task_queues.js:95:5)
      at async checkFunctionResponse (test/fixtures/commerce-mock/index.js:133:13)
      at async Context.<anonymous> (skr-test/skr-test.js:135:7)
```

Link to the job:

https://status.build.kyma-project.io/?job=kyma-preview-integration-dev

**Expected result**
Pipelines are more stable.

**Comment by Sawthis** [comment]
Last twelve runs are red.

**Comment by kwiatekus** [comment]
Its related to CommerceMock scenario and it's fixture
https://github.com/kyma-project/kyma/issues/13563#issuecomment-1085597552

**Comment by jakobmoellersap** [comment]
Multiple observed failures in test Fixture:
OIDC E2E Test Error from Runtime Status (401)
https://status.build.kyma-project.io/view/gs/kyma-prow-logs/logs/kyma-preview-integration-dev/1511191999837900800#1:build-log.txt%3A601-609

SKR Error with 401
https://status.build.kyma-project.io/view/gs/kyma-prow-logs/logs/kyma-preview-integration-dev/1511373195939155968

**Comment by PK85** [comment]
its is green 15+ times in a row, closing
