### ISSUE TITLE
Create pipeline for Prometheus load tests

### ISSUE THREAD

**Issue by chrkl** [kyma-project/kyma#13767]
**Description**

The Prometheus KPIs and limits that have been identified and documented in #13741, should be reevaluated on a regular base (weekly?). The goal of this regular tests is to:

* Identify changes in the number of time series that are exported by Kyma components (for instance through changed label cardinality).
* Find changing resource requirements for our workload, caused by any changes to Prometheus.

**Acceptance Criteria**

To observe these factors, the pipeline should:

* Provision a Gardener cluster and install Kyma with the production profile
* Run the Prometheus load tests
* Collect the results (time series count after the test) and store to a central place
* Define a limit for the time series count over that the test fails

See also #13269, #10033

**Comment by a-thaler** [comment]
We have a working setup in place being executed on a manual base. As the monitoring stack as it is not fitting to the strategy, we will not invest further here.
