### ISSUE TITLE
Handle enabling `file` storage in the NATS cluster

### ISSUE THREAD

**Issue by pxsalehi** [kyma-project/kyma#13777]
Enabling the `file` storage type in an existing NATS cluster using the Kyma reconciler results in the following error:
```
 WARN    kubernetes/adapter.go:486       kubeClient failed to update StatefulSet 'eventing-nats' (namespace: kyma-system)  with strategy 'PATCH': cannot patch "eventing-nats" with kind StatefulSet: StatefulSet.apps "eventing-nats" is invalid: spec: Forbidden: updates to statefulset spec for fields other than 'replicas', 'template', and 'updateStrategy' are forbidden
```

The issue seems to be that the reconciler uses PATCH for StatefulSets, which doesn't allow adding a PVC to the manifest.

This can happen when enabling the JetStream feature flag on a production profile (which by default uses `file` storage) or probably also when we change a cluster to use `file` rather than `memory` storage for JetStream.

To reproduce, create a Kyma cluster with the production profile, and then reconcile the cluster to enable JetStream with:
```
kyma deploy --profile=production --value global.jetstream.enabled=true --verbose --non-interactive --component eventing
```

This could potentially mean that we must have some pre-upgrade action in the Eventing component reconciler!

**Comment by k15r** [comment]
Both profiles (evaluation|production) will use file as their stream storage. So at least on a managed cluster there will be no switch from `memory` to `file` or `file` to `memory`. Closing this ticket for now. If requirements change, we will recreate it if the issue still exists.

**Comment by k15r** [comment]
This ticket has to be reopened as we will have to introduce PVCs on all existing clusters as soon as a cluster shall use jetstream. The decision has been made to always use file storage (even for evaluation profiles).

**Comment by mfaizanse** [comment]
**Tasks:**
- [ ]  Implement a pre-action in eventing component reconciler.
  - Scenarios: 
    - From NATS to JetStream `file storage`.

**Notes:**
- From JetStream `in-memory` to JetStream `file storage`. (We do not support this flow)

**Comment by VladislavPaskar** [comment]
PR: https://github.com/kyma-incubator/reconciler/pull/1072
