### ISSUE TITLE
synchronize test version and installed kyma version

### ISSUE THREAD

**Issue by k15r** [kyma-project/kyma#13789]
# Description
Test implementations of fast-integration test and kyma version should be in sync. This will allow us to focus implementing features in the fast-integration test that are specific to the kyma version under test.

# Details
currently, especially in the upgrade scenarios, the fast integration test implementation is taken from the latest version of kyma:
eg. a upgrade from version 2.0.4 to 2.1 will be tested.
In this case kyma version 2.0.4 is installed on the cluster, but the fast integration test implementation is used from kyma version 2.1.
This forces every change on fast integration test to be backwards compatible to version 2.0.4

The drawback of this approach is that for breaking changes the fast integration test has to do some assumptions and even backwards compatible changes to successfully run on the older version.

My proposal is to always use the fast-integration test version shipped with the version of kyma under test.
In this case you would run fast integration test 2.0.4 on a 2.0.4 cluster, and after the upgrade the fast integration test version would be automatically changed to 2.1 as the cluster is now on 2.1 as well.

For upgrade tests this will also lead to some interesting opportunities:
in the preparation phase the preparation test code of version 2.0.4 would be used.
during the upgrade all migration steps would be executed by the installer (kyma cli / kyma reconciler).
later after the upgrade the evaluation would be executed based on the updated evaluation code of the target kyma version.

The benefit of this approach is, that in the implementation of FI the developer does not need to know the specifics of the older kyma version. Even upgrades spanning multiple kyma versions are possible, as long as the migration logic takes care of properly upgrading the created resources.

Drawbacks of this approach during a multi version kyma upgrade are, that the preparation phase needs to be executed on every kyma version during the upgrade (eg 1.24 and 2.0 for an upgrade spanning 1.24 -> 2.1)

Required changes to implement this:
- [ ] change upgrade tests to use not only the latest kyma repository version, but every version of kyma used during the upgrade, to be able to run specific versions of the upgrade test
- [ ] make preparation code resilient to already existing resources (resource installed during a previous versions prep phase)

**Comment by mfaizanse** [comment]
We have implemented it for eventing. After the modularisation, it would not be relevant anymore.
