### ISSUE TITLE
Installation failed for Jaeger from resources folder

### ISSUE THREAD

**Issue by krasimirdermendzhiev** [kyma-project/kyma#13784]
**Description**

When I try to install jaeger with [tracing](https://github.com/kyma-project/kyma/tree/main/resources/tracing)

`helm install jaeger tracing -n kyma-system`
return error INSTALLATION FAILED

**Expected result**

To see something like this
```
NAME: jaeger
LAST DEPLOYED: Wed Mar 30 13:43:25 2022
NAMESPACE: kyma-system
STATUS: deployed
REVISION: 1
TEST SUITE: None
```

**Actual result**

```
Error: INSTALLATION FAILED: unable to build kubernetes objects from release manifest: error validating "": error validating data: [ValidationError(Jaeger.spec.securityContext): unknown field "allowPrivilegeEscalation" in io.jaegertracing.v1.Jaeger.spec.securityContext, ValidationError(Jaeger.spec.securityContext): unknown field "privileged" in io.jaegertracing.v1.Jaeger.spec.securityContext]
```

**Steps to reproduce**

`helm install jaeger tracing -n kyma-system`

**Troubleshooting**

When I comment this lines in file values.yaml I can install jaeger
```yaml
      # allowPrivilegeEscalation: false
      # privileged: false
```

**Comment by skhalash** [comment]
@krasimirdermendzhiev Helm CLI is not an official way to install a Kyma component, please try installing it by running `kyma deploy --component=tracing`. From the error message you provided, it seems like the right version of the `Jaeger` CRD is not installed. Kyma CLI will take care of it.

**Comment by krasimirdermendzhiev** [comment]
Thanks! Yes with `kyma deploy` is working. I have another question. How to configure istio proxies to send traces to jaeger-collector? Because now I have only one service - `jaeger-query`.
