### ISSUE TITLE
Event type specified in published event

### ISSUE THREAD

**Issue by k15r** [kyma-project/kyma#13796]
As a user of kyma eventing, I find it very confusing that some fields of my event type get modified during dispatching, or even get removed / merged with other fields.
What i really want is to be able to dispatch an event specifying only the following fields:
`businessobject.operation.version` 

Kyma eventing shall then take care of enriching the event type with all additionally required information so that the backend that will receive the event can handle it.

**Comment by raypinto** [comment]
Related issue: https://github.com/kyma-project/kyma/issues/13797
