### ISSUE TITLE
Logging in eventing components

### ISSUE THREAD

**Issue by k15r** [kyma-project/kyma#13799]
As a user of kyma eventing I want to be able to easily understand logs created during publishing / subscribing / dispatching of my events. The current situation requires internal knowledge about how events are renamed. I want to be able to understand those logs without having to know that internal knowlege. 

Acceptance:
- [ ] logs created during working with events shall contain the initially sent event type and source of the events

**Comment by raypinto** [comment]
Currently the logs contain information when events are published and dispatched.
