### ISSUE TITLE
Enable code sharing between eventing components

### ISSUE THREAD

**Issue by nachtmaar** [kyma-project/kyma#13795]
**Description**

Eventing consists of several components (eventing-publisher proxy and eventing-controller. In order to **avoid code duplication** and **enable code re-usage** we need to agree on a way how we can re-usage code among multiple components. 

**Possible code for sharing**
- [CloudEventBuilder](https://github.com/kyma-project/kyma/blob/main/components/event-publisher-proxy/testing/fixtures.go#L54)
- [Cloud Event Test Cases](https://github.com/kyma-project/kyma/blob/main/components/event-publisher-proxy/pkg/handler/handlertest/handlertest.go#L91)
- What else ? ✍️ it 👇
- Unify Event type cleanup [here](https://github.com/kyma-project/kyma/tree/main/components/event-publisher-proxy/pkg/cloudevents/eventtype) and [here](https://github.com/kyma-project/kyma/tree/main/components/eventing-controller/pkg/handlers/eventtype).
- Unify Application listers [here](https://github.com/kyma-project/kyma/tree/main/components/event-publisher-proxy/pkg/application) and [here](https://github.com/kyma-project/kyma/tree/main/components/eventing-controller/pkg/application).

**AC**
- [ ] Reusable code in our eventing components were identified and moved to a shared "place"
- [ ] All eventing components make use of this shared code (if it makes sense).

**Reasons**

We don't need to reinvent the wheel then starting a new eventing component. Instead let us improve the code which we already have and reuse it.

**Implementation Ideas**
1. Reorganise kyma eventing components folders to the following structure:
```
|- kyma/components/eventing
                             |-> pkg          // shared code goes here (for actual code and for tests)
                             |-> publisher
                             |-> controller
                             |-> dispatcher
```
- Disadvantage: 
    - breaks the current folder structure. This means it will break prow jobs and also break our eventing API (external code needs to change the import path).
1. Move shared code to `kyma/common/eventing`

**Attachments**

**Comment by k15r** [comment]
according to [go project layout standards](https://github.com/golang-standards/project-layout) the publishers / controllers /dispatchers should go here:
