### ISSUE TITLE
Service Broker does not pick up registered services

### ISSUE THREAD

**Issue by Szymongib** [kyma-project/kyma#1379]
**Description**

Sometimes after registering a service using Metadata Service, the Service Class is not created and the service is not visible in the Service Catalog.

After manually editing `relistRequests` in Service Broker chart Service Classes are created and services appear in the Service Catalog.

**Comment by PK85** [comment]
@Szymongib what was exactly a scenario? Have you updated the given Remote Envirnment with new service classes?

**Comment by PK85** [comment]
Section: how to reproduce will be not provided. In case issue will be reproducable issue will be reopened.
