### ISSUE TITLE
Multiple active backends

### ISSUE THREAD

**Issue by k15r** [kyma-project/kyma#13798]
As a user of eventing 
I want to be able to have multiple backends active in my cluster. 

This will allow me to publish internal only events to a cluster internal backend (events will not leave my cluster) and still be able to subscribe to events delivered directly to a cluster external backend (eg. EventMesh).

Publishing and subscribing should be able to fulfil these requirements:

Subscribing:
- I want to be able to omit specifying the backend used for a specific subscription. In that case a cluster wide default shall be used. If I later change the cluster default, such subscriptions shall be moved from the previous default to the new default.
- I want to be able to specify a backend per subscription. A subscription will either be active if the specified backend exists or be inactive if that backend is not available. This information must be visible on the subscription itself.

Publishing:
- I want to have the eventing system automatically figure out which backend needs to be used based on the event I send. (Ideal solution)
- I want to be able to publish either to the default backend or to any of the active backends directly.

see: https://github.com/kyma-project/kyma/issues/13217, ~~https://github.com/kyma-project/kyma/issues/12390~~

**Comment by nachtmaar** [comment]
We had an initial discussion on the topic and will create further tickets soon.

**Comment by raypinto** [comment]
Also see: https://github.com/kyma-project/kyma/issues/13800

**Comment by k15r** [comment]
closing in favor of #13217
