### ISSUE TITLE
Istio 1.12.5 Patch Release for Kyma 2.1.1

### ISSUE THREAD

**Issue by johgoe** [kyma-project/kyma#13802]
Kyma 2.1.x has not the latest security release of istio. 

It's still on 1.12.3 (since 10.02.2022)

Current release for 1.12.x is already from 09.03.2022 

https://istio.io/latest/news/releases/1.12.x/announcing-1.12.5/

**Comment by dariusztutaj** [comment]
We're planning to update Istio to 1.13.x in Kyma 2.2.
[See also](https://github.com/kyma-project/kyma/issues/13620)
