### ISSUE TITLE
Upgrade Fluent Bit to 1.9.x

### ISSUE THREAD

**Issue by a-thaler** [kyma-project/kyma#13806]
**Description**
With fluentbit 1.9.x multiple issues got fixed related to chunks being not processed anymore, see also umbrella ticket https://github.com/fluent/fluent-bit/issues/3581#event-6321502417.
Furthermore performance improvements got realized.

Kyma should upgrade to the new release line and check if everything works as before:
- upgrade the image to latest version
- Check for no degraded performance
- Check for no log messages spamming the output periodically
- Update the telemetry/fluentbit chart to the latest upstream version
- List all customizations in the chart and categorize as a comment in here
- List items format:
  - Per file short summary of customizations
  - Relative link to file and line number of customization

**Comment by rakesh-garimella** [comment]
The fluentbit has been updated to 1.9.2 version. Also the customisations have been documented [here](https://github.com/kyma-project/community/pull/659). Also the telemetry operator dryrun feature was adjusted to work with the new fluentbit version.
