### ISSUE TITLE
Use a hard-coded prefix for JetStream subject filter prefix

### ISSUE THREAD

**Issue by mfaizanse** [kyma-project/kyma#13825]
The current solution with JetStream subject filter prefix is:

**Case 1: Non-empty prefix**
- Event Type Prefix: "pre.custom.kyma"
- JS Stream Subject Filter: "pre.custom.kyma.>"
- Event Type in kyma Subscription: "pre.custom.kyma.x.y.z"

- **Note**: No need to append anything to the subject when creating subscription on JetStream server.
or when publishing events in EPP.

**Case 2: Empty prefix**
- Event Type Prefix: ""
- JS Stream Subject Filter: "kyma"  (some default value)
- Event Type in kyma Subscription: "x.y.z"

 - **Note**: 
    - When creating subscription on JetStream, we need to append `JSStreamSubjectPrefix: kyma` to the start of subject.
        - e.g. "kyma.x.y.z"
    - Also EPP needs to append `JSStreamSubjectPrefix: kyma` to the start if subject when publishing events
        - e.g. User --> "x.y.z" --> EPP --> "kyma.x.y.z"

### Task:
- Check if it would better to ALWAYS use some hard-coded prefix for JetStream subject filter prefix for both cases (i.e. empty and non-empty prefix)?

**Attachments**

Follow-up of: https://github.com/kyma-project/kyma/issues/13544

**Comment by pxsalehi** [comment]
Please just use a fixed prefix.
