### ISSUE TITLE
[telemetry-operator] Improve telemetry-operator Makefile

### ISSUE THREAD

**Issue by chrkl** [kyma-project/kyma#13836]
**Description**

The developer experience should be improved by updating the Makefile and documentation.

**Criteria**
* The `run-local` target should allow the execute the local source of the operator and reconcile the cluster, reachable under the active kubeconfig file
  * Required arguments after adding the webhook are missing
* Ensure that `deploy-local` works after the webhook has been added. Alternatively remove it and document how to run the telemetry chart with a custom operator image
* Check if any make targets are unused and can be removed
* Automate the sync of generated yaml files with the installable component (CRD, RBAC, etc.)
* Update the README file to cover all useful make targets for the development flow

**Comment by chrkl** [comment]
The following changes have been made to address this issue:
- Changed the operator and Makefile to run it will a self signed certificate for the webhook server.
- Removed orphaned manifest files that have been generated by Kubebuilder and change the documented development flow to use our Helm chart.

**Comment by skhalash** [comment]
/retitle [Telemetry Operator] Improve telemetry-operator Makefile
