### ISSUE TITLE
pre-main-control-plane-reconciler-upgrade-kyma2-latest-to-main-gardener pipelines fails on Logging tests

### ISSUE THREAD

**Issue by cnvergence** [kyma-project/kyma#13835]
**Description**
Currently this [pipeline](https://status.build.kyma-project.io/?job=pre-main-control-plane-reconciler-upgrade-kyma2-latest-to-main-gardener) always fails on this issue

```bash
    Logging Tests:
      ✓ Check Loki logs from kyma-system and kyma-integration namespaces
      ✓ Retention Period and Max look-back Period should be 120h
      1) Persistent Volume Claim Size should be 30Gi
      ✓ Loki should not be exposed through Virtual Service
  19 passing (55s)
  1 failing

  1) Upgrade test tests
       Logging Tests:
         Persistent Volume Claim Size should be 30Gi:
     HttpError: HTTP request failed
      at Request._callback (node_modules/@kubernetes/client-node/dist/object.js:416:32)
      at Request.self.callback (node_modules/request/request.js:185:22)
      at Request.<anonymous> (node_modules/request/request.js:1154:10)
      at IncomingMessage.<anonymous> (node_modules/request/request.js:1076:12)
      at endReadableNT (internal/streams/readable.js:1334:12)
      at processTicksAndRejections (internal/process/task_queues.js:82:21)
```
**Expected result**
Pipeline succeeds on upgrade tests

**Comment by a-thaler** [comment]
In the logs I can see that the evaluation profile is used where no persistence is used at all for loki, that's why the test is failing.
Instead of making the test case aware of the profile, we should just execute the assertion only if a PVC is present. If a PVC is not present by mistake, the installation would already fail, so there is no need to assert that.

**Comment by jakobmoellersap** [comment]
@skhalash is this verfied to fix the issue?

**Comment by jakobmoellersap** [comment]
After this was merged we face more issues related to the Fast Integration Test Suite and Prometheus: https://status.build.kyma-project.io/view/gs/kyma-prow-logs/pr-logs/pull/kyma-project_control-plane/1519/pre-main-control-plane-reconciler-upgrade-kyma2-latest-to-main-gardener/1511388569774592000#1:build-log.txt%3A466-552

**Comment by skhalash** [comment]
Logging tests are passing now https://status.build.kyma-project.io/?job=pre-main-control-plane-reconciler-upgrade-kyma2-latest-to-main-gardener

**Comment by a-thaler** [comment]
@jakobmoellersap Your problem is not directly related and worked on in a different ticket, please subscribe to https://github.com/kyma-project/kyma/issues/13375
