### ISSUE TITLE
[Configurable Logging] Performance analysis: filesystem buffer size

### ISSUE THREAD

**Issue by a-thaler** [kyma-project/kyma#13833]
**Description**
The default setup of fluent-bit needs to be tested against typical operational issues like availability, communication disruptions, scalability and so on. This ticket focusses on the specific aspect of the filesystem buffer size
That analysis needs to be documented and repeatable.

A reasonable buffer sizing should be defined by considering the following aspects:
- Since Fluent Bit drops chunks once the filesystem buffer is filled, its size is relevant for the question under which circumstances we guarantee not loosing logs. What is the minimal minimal outage of a logging backend that we want to back without loosing logs. How many logs can can we assume in this time to be generated?
- Can we derive any sizing requirements from the [Kubelet log rotation](https://kubernetes.io/docs/concepts/cluster-administration/logging/#logging-at-the-node-level) functionality?
- Fluent Bit should use a hostPath volume to store the filesystem buffer persistently. Does this imply any new requirements for the node's disk size?
- Does Fluent Bit already have any limitations or defined behaviour if not filesystem size limit is configured? Will it fill up the whole disk and cause any risk for the availability of the nodes?
- The buffer size should not be optimized to cover a long-lasting outage of the backend but rather a short-lived outage (hours) in combination with log spikes.

After activating a filesystem buffer for an input or rewrite_tag filter, its actual size is defined per output and thus under the control of the user. The telemetry-operator has to ensure that output specific filesystem size settings do not exceed the node limit.

**Reasons**
Assure typical NFRs upfront to allow a smooth operation

**Criteria**
- Document a test setup which could be automated in future
- Document resulting limits
- Document conceptual changes and create follow-up ticket

**Comment by chrkl** [comment]
The following analysis have been done:
* Gathered data about node filesystem usage from existing Kyma clusters
* Validated that the filesystem buffer usage grows as expected from the amount of generated logs
* Described test-case in internal documentation

The implementation of an actual limit will be covered by issue [#14559](https://github.com/kyma-project/kyma/issues/14559)
