### ISSUE TITLE
Rename the EPP backend type label

### ISSUE THREAD

**Issue by VladislavPaskar** [kyma-project/kyma#13847]
**Description**

As per https://github.com/kyma-project/kyma/pull/12706 we now label the event-publisher-proxy deployment with the  `"kyma-project.io/eventingBackend"` : `backendType`. A better and more consistent naming would be: `"eventing.kyma-project.io/eventing"` : `backendType`.

**Related Issue** 
https://github.com/kyma-project/kyma/issues/12606

**Comment by k15r** [comment]
i vote for:
`eventing.kyma-project.io/eventing:backend`

**Comment by FriedrichWilken** [comment]
#13965

**Comment by k15r** [comment]
in hindsight it seems there was a mistake in my comment:
`eventing.kyma-project.io/backend:<backendType>` makes more sense, than mentioning eventing twice

that way you should be able to filter for all backends, and for specific backends per backendtype. please correct me if im wrong
