### ISSUE TITLE
Clean the compass resources created by pre-main-skr-eventing if it was interrupted

### ISSUE THREAD

**Issue by VladislavPaskar** [kyma-project/kyma#13848]
**Description**

The skr eventing prowjob includes:
- the cluster provisioning
- registering a compass scenario
- assigning the prowjob's cluster runtime id to this compass scenario

To assure, that all the resources including compass will be deleted after the prowjob is executed there is a trapped cleanup: https://github.com/kyma-project/test-infra/blob/main/prow/scripts/cluster-integration/kyma-integration-skr-eventing.sh#L81, which is being executed even if the prowjob fails.

But this cleanup script does not cover the scenario:

The `pre-main-skr-eventing` is called:

1.  skr cluster got provisioned 
2. compass resources got registered
3. eventing tests are being executed...
4.  the `pre-main-skr-eventing` is re-executed

      
this re-execution of the prowjob would instantly kill the execution of the current prowjob and start the new provisioning. The problem of this scenario is, that the compass resources would not get deleted and remain orphaned. 

So we need to address this issue somehow.

**Comment by mfaizanse** [comment]
The job `pre-main-kyma-skr-eventing` is removed, so keeping this ticket closed.
