### ISSUE TITLE
Unreliable Gardener Provisioning on existing Shoot in multiple Pipelines causes Test Failure

### ISSUE THREAD

**Issue by jakobmoellersap** [kyma-project/kyma#13855]
**Description**

During various Pipelines we experience failure due to gardener provisioning having issues as they are reusing a gardener cluster id:

- kyma-upgrade-gardener-kyma2-to-main-reconciler-main: https://status.build.kyma-project.io/view/gs/kyma-prow-logs/logs/kyma-upgrade-gardener-kyma2-to-main-reconciler-main/1511312796938145792#1:build-log.txt%3A28-30 (grd891vfn, timeout after 30m)
- kyma-upgrade-gardener-kyma-to-kyma2: https://status.build.kyma-project.io/view/gs/kyma-prow-logs/logs/kyma-upgrade-gardener-kyma-to-kyma2/1511312796904591360#1:build-log.txt%3A28-29 (grd2hg9dj, timeout after 30m)

**Expected result**

Cluster is reused or deleted and recreated for these tests instead of causing pipeline failure

**Actual result**

Pipeline runs fail completely

**Steps to reproduce**

Observe given Links

**Troubleshooting**

Retry will help but can only circumvent, not solve the issue

**Comment by raypinto** [comment]
There is also quota filled errors at times and the test fails with the following error message:
```
error when creating "STDIN": shoots.core.gardener.cloud "grdrx7wg0" is forbidden: exceeded quota: gardener, requested: count/shoots.core.gardener.cloud=1, used: count/shoots.core.gardener.cloud=50, limited: count/shoots.core.gardener.cloud=50
```

**Comment by jakobmoellersap** [comment]
Timeout happens in `pre-main-control-plane-reconciler-e2e-latest-release` regularly as can be seen in https://storage.googleapis.com/kyma-prow-logs/pr-logs/pull/kyma-project_control-plane/1550/pre-main-control-plane-reconciler-e2e-latest-release/1512453812286132224/build-log.txt

**Comment by jakobmoellersap** [comment]
Additionally sometimes, the Cluster Nodes are not allowed to be read through API : https://status.build.kyma-project.io/view/gs/kyma-prow-logs/pr-logs/pull/kyma-project_control-plane/1551/pre-main-control-plane-reconciler-upgrade-kyma2-latest-to-main-gardener/1512436161417580544

**Comment by jakobmoellersap** [comment]
Additionally there can be failures when reaching out to the gardener API for requesting a shoot: https://storage.googleapis.com/kyma-prow-logs/logs/kyma-upgrade-gardener-kyma2-to-main-reconciler-main/1512369758589161472/build-log.txt

**Comment by tobiscr** [comment]
Relates to https://github.com/kyma-project/test-infra/issues/5229

**Comment by adityabhatia** [comment]
Two pipelines have been flaky recently, during Gardener shoot provisioning. The error seems to be due to an authorization (RBAC) issue. I am attaching some examples below:

https://status.build.kyma-project.io/job-history/gs/kyma-prow-logs/pr-logs/directory/pre-main-control-plane-reconciler-e2e-latest-release

https://status.build.kyma-project.io/job-history/gs/kyma-prow-logs/pr-logs/directory/pre-main-control-plane-reconciler-upgrade-kyma2-latest-to-main-gardener

```
2022/04/21 [10](https://status.build.kyma-project.io/view/gs/kyma-prow-logs/pr-logs/pull/kyma-project_control-plane/1590/pre-main-control-plane-reconciler-upgrade-kyma2-latest-to-main-gardener/1517088469476708352#1:build-log.txt%3A10):31:08 UTC [INFO] Deprovision cluster: grdqffea4
Error from server (NotFound): shoots.core.gardener.cloud "grdqffea4" not found
2022/04/21 10:31:08 UTC [ERROR] AN ERROR OCCURED! Take a look at preceding log entries.
Error from server (Forbidden): nodes is forbidden: User "system:serviceaccount:garden-kyma-prow:gardener-kyma-prow" cannot list resource "nodes" in API group "" at the cluster scope
Error from server (Forbidden): unknown (get services http:heapster:)
Error from server (Forbidden): unknown (get services http:heapster:)
2022/04/21 10:31:08 UTC [INFO] Deprovision cluster: "grdqffea4"
2022/04/21 10:31:08 UTC [INFO] Deprovision cluster: grdqffea4
Error from server (NotFound): shoots.core.gardener.cloud "grdqffea4" not found
Error from server (NotFound): shoots.core.gardener.cloud "grdqffea4" not found
2022/04/21 10:31:08 UTC [INFO] Job is finished (exit status: 1)
```

**Comment by kwiatekus** [comment]
Recent fail indicate quota limit reached
```
2022/04/27 08:39:38 UTC [INFO] Creating cluster: grdq7pwgi
Error from server (Forbidden): error when creating "STDIN": shoots.core.gardener.cloud "grdq7pwgi" is forbidden: exceeded quota: gardener, requested: count/shoots.core.gardener.cloud=1, used: count/shoots.core.gardener.cloud=50, limited: count/shoots.core.gardener.cloud=50
```

**Comment by kwiatekus** [comment]
Me and @dekiel analysed the retry operation for shoot cluster creation (https://github.com/kyma-project/test-infra/issues/5229#issuecomment-1110740401)
 
We see its used - but we are always at the quota limit. Retry for shoot provisoning is not going to solve it

**Comment by kwiatekus** [comment]
To improve the quota issue we should improve kyma  cleanup  on the test clusters.
There is a lot of shoot clusters in prow namespace that cannot be cleaned due to orphaned CRDs
@kyma-project/gopher 
![Screenshot 2022-04-27 at 11 07 16](https://user-images.githubusercontent.com/6783567/165483865-a88c8d6e-8c94-4eb1-9339-035d14348c74.png)

**Comment by dekiel** [comment]
If you would like to troubleshoot bash scripts you can use `set -x` to enable debug printing from bash execution. I use it for troubleshooting retry logic, see usage [here](https://github.com/kyma-project/test-infra/pull/5287/files). It will print commands with arguments which are executed along with it results and variable values. Pay attention to any sensitive data like tokens and passwords which might be printed then. To mask this values use this helper functions:
https://github.com/kyma-project/test-infra/blob/bbc80f6c3833c179913899e3d3f0847e0f051083/prow/scripts/lib/utils.sh#L750
https://github.com/kyma-project/test-infra/blob/bbc80f6c3833c179913899e3d3f0847e0f051083/prow/scripts/lib/utils.sh#L760

Example usage [here](https://github.com/kyma-project/test-infra/blob/c3ba8171f5cb1b04691fd488cd01426b887d75ba/prow/scripts/cluster-integration/kyma-upgrade-gardener-kyma2-to-main.sh#L84)

**Comment by kwiatekus** [comment]
`periodic-main-kyma-incubator-reconciler-kyma1-kyma2-upgrade` is one of the pipelines that introduces a shoot cluster that cannot be cleaned.
Currently investigated by @kyma-project/jellyfish if can be removed

**Comment by jakobmoellersap** [comment]
I think the cleaner changes may have introduced some unintended side effects.
https://github.com/kyma-project/test-infra/pull/5332#pullrequestreview-956081697
I think the cleanup changes now cause various pipeline failures as the deprovisioning is not working as expected (e.g. https://storage.googleapis.com/kyma-prow-logs/pr-logs/pull/kyma-project_control-plane/1633/pre-main-control-plane-reconciler-e2e/1519356205519081472/build-log.txt)

**Comment by jakobmoellersap** [comment]
Regarding `periodic-main-kyma-incubator-reconciler-kyma1-kyma2-upgrade` we are working on removing it

**Comment by dekiel** [comment]
This is stated in log messages.

```
2022/04/27 17:04:49 UTC [INFO] Deprovision cluster: ""
2022/04/27 17:04:49 UTC [ERROR] Cluster name is empty. Exiting... Exiting
```

**Comment by adityabhatia** [comment]
> periodic-main-kyma-incubator-reconciler-kyma1-kyma2-upgrade
https://github.com/kyma-project/test-infra/pull/5353 should remove this pipeline

**Comment by adityabhatia** [comment]
Linking more instances of failing pipeline because of gardener issues:

https://status.build.kyma-project.io/view/gs/kyma-prow-logs/logs/kyma-upgrade-gardener-kyma2-minor-versions/1522244843005284352

https://status.build.kyma-project.io/view/gs/kyma-prow-logs/logs/kyma-upgrade-gardener-kyma2-minor-versions/1522214643546722304

**Comment by kwiatekus** [comment]
This is the example where the flakiness of the gardener shoot cluster shows up:
```
2022/05/05 16:02:45 UTC [INFO] ### Provisioning Gardener cluster
2022/05/05 16:02:45 UTC [INFO] Provision cluster: "grdc9prp0"
- Validating flags
X Provisioning Gardener(Azure) cluster
Error: unable to provision gardener cluster: shoots.core.gardener.cloud "grdc9prp0" already exists
2022/05/05 16:32:46 UTC [INFO] cluster provisioning failed, trying provision new cluster
2022/05/05 16:32:46 UTC [INFO] cleaning damaged cluster first
2022/05/05 16:32:46 UTC [INFO] Deprovision cluster: grdc9prp0
shoot.core.gardener.cloud/grdc9prp0 annotated
shoot.core.gardener.cloud "grdc9prp0" deleted
2022/05/05 16:32:46 UTC [INFO] building new cluster name
2022/05/05 16:32:46 UTC [INFO] Provision cluster: "grdwdh659"
- Validating flags
X Provisioning Gardener(Azure) cluster
Error: unable to provision gardener cluster: shoots.core.gardener.cloud "grdwdh659" already exists
2022/05/05 17:02:47 UTC [ERROR] AN ERROR OCCURED! Take a look at preceding log entries.
2022/05/05 17:02:47 UTC [INFO] Cleanup
```
ATM I have no clue why it happens. I need help from your team @dekiel

**Comment by dekiel** [comment]
For me this looks like case for Gardener team. I think it should be possible to get some more logs from Gardener. Will check if we can have more details to share with Gardener team.

**Comment by kwiatekus** [comment]
The following comes from the fact that kyma cli command is configured with `--attempts 2` flag.
Second attempt made by kyma CLI always fails with "{shootID} already exists"
```
2022/05/05 16:02:45 UTC [INFO] Provision cluster: "grdc9prp0"
...
Error: unable to provision gardener cluster: shoots.core.gardener.cloud "grdc9prp0" already exists
```

This may be also a bug in the kyma cli built-in retry mechanism

**Comment by jakobmoellersap** [comment]
to see all retries of the cli, i think we can run in verbose mode, will double check. The "clearing of the shoot" is probably related to the cluster delete not happening during a retry.

**Comment by kwiatekus** [comment]
☝️ recent changes have improved the stability IMO and log transparency.
IMO that is no longer a release blocker
CC: @Sawthis 

I cant see any problems related with gardener shoot provisioning other than reaching quota limits, i.e:
https://storage.googleapis.com/kyma-prow-logs/logs/kyma-upgrade-gardener-kyma-to-kyma2/1517171502456246272/build-log.txt

There are a few orphaned clusters where gardener report problems with `kyma-azure` secret.
@kasiakepka can you guys look into it?
```
Action required
There is a problem with your secret [kyma-azure](https://dashboard.garden.canary.k8s.ondemand.com/namespace/garden-kyma-prow/secrets/kyma-azure): Infrastructure operation failed as unmanaged resources exist in your cloud provider account. Please delete all manually created resources related to this Shoot.
```
```
task "Waiting until shoot worker nodes have been terminated" failed: Failed to delete Worker shoot--kyma-prow--grd1rrjmf/grd1rrjmf: Error deleting worker: Failed while waiting for all machine resources to be deleted: 'machine shoot--kyma-prow--grd1rrjmf-cpu-worker-z1-7f95b-z92v9 failed: Cloud provider message - machine codes error: code = [Internal] message = [compute.VirtualMachinesClient#CreateOrUpdate: Failure sending request: StatusCode=0 -- Original Error: autorest/azure: Service returned an error. Status=<nil> Code="ConflictingUserInput" Message="Disk shoot--kyma-prow--grd1rrjmf-cpu-worker-z1-7f95b-z92v9-os-disk already exists in resource group SHOOT--KYMA-PROW--GRD1RRJMF. Only CreateOption.Attach is supported." Target="/subscriptions/8526f76e-07a7-48a3-90a6-f62d550c11ea/resourceGroups/shoot--kyma-prow--grd1rrjmf/providers/Microsoft.Compute/disks/shoot--kyma-prow--grd1rrjmf-cpu-worker-z1-7f95b-z92v9-os-disk"]'
```
![Screenshot 2022-05-12 at 11 02 54](https://user-images.githubusercontent.com/6783567/168034291-5256c947-8eb0-4560-aee4-5683368a95a6.png)

**Comment by jakobmoellersap** [comment]
Regarding Quota limit, would it be possible to increase quota or check again which clusters cause the buildup of clusters? Is this maybe again related to the cleanup?

**Comment by kwiatekus** [comment]
@kyma-project/gopher 
And there are a lot of orphaned shoots suffering from the fact that `clusterservicebroker` cannot be removed:

```
Action required
 Cleaning up the cluster failed as some resource are stuck in deletion. Please remove these resources properly or a forceful deletion will happen if this error persists. 
 ```
 ```
task "Cleaning extended API groups" failed: 1 error occurred:
	* retry failed with context deadline exceeded, last error: remaining objects are still present: [*v1.CustomResourceDefinition /clusterservicebrokers.servicecatalog.k8s.io]
```

![Screenshot 2022-05-12 at 11 16 19](https://user-images.githubusercontent.com/6783567/168036993-dbde8fe1-f13a-4ce9-adea-b415eebba005.png)

**Comment by kwiatekus** [comment]
all the above mentioned cleanup problems make us reach quota frequently

**Comment by kasiakepka** [comment]
We've raised an [issue with Gardener](https://github.tools.sap/kubernetes-canary/issues-canary/issues/2153) to increase quota

**Comment by kwiatekus** [comment]
Looks like latest changes have done the trick
 + tests cleanup
 + gardener provisioning code 
 + shoot count quota
 
 Closing.

**Comment by clebs** [comment]
Some issues were also caused be the CLI failing when the cluster already exists. That bug is being fixed in the CLI to also improve stability on pipelines: https://github.com/kyma-project/cli/issues/1267
