### ISSUE TITLE
pre-main-control-plane-reconciler-upgrade-kyma2-latest-to-main-gardener - Post-Reconciliation Error in FastIntegrationTests: Prometheus UI should be reachable

### ISSUE THREAD

**Issue by jakobmoellersap** [kyma-project/kyma#13861]
Description

I expect pre-main-control-plane-reconciler-upgrade-kyma2-latest-to-main-gardener to be running fine after successful reconciliation and not produce errors in the Monitoring Stack

Expected result

Pipelines should include enough verbosity to have sufficient info for root cause analysis of pipeline failures

**Actual result**

https://status.build.kyma-project.io/view/gs/kyma-prow-logs/pr-logs/pull/kyma-project_control-plane/1519/pre-main-control-plane-reconciler-upgrade-kyma2-latest-to-main-gardener/1511388569774592000#1:build-log.txt%3A468-552

**Steps to reproduce**

Check Build status and try to use images from build.

**Troubleshooting**

Retrying solved the issue, possibly flakiness

**Comment by jakobmoellersap** [comment]
Also spotted and managed in https://github.com/kyma-project/kyma/issues/13375

**Comment by varbanv** [comment]
Fixed in https://github.com/kyma-project/kyma/issues/13375
