### ISSUE TITLE
Flaky pre-main-control-plane-reconciler-e2e in FastIntegrationTests

### ISSUE THREAD

**Issue by jakobmoellersap** [kyma-project/kyma#13860]
Description

I expect pre-main-control-plane-reconciler-e2e to be unflaky as it Executes on every reconciler image-bump pull-request on control-plane repository. That means by then we should be stable or we have issues in previous steps that are ignored. However, to stabilize the pipeline we have to have enough verbosity to find the root cause. Right now, when the cluster reconciliation succeeds but the FastIntegrationTests fail, we do not know what causes the issue

Expected result

Pipelines should include enough verbosity to have sufficient info for root cause analysis of pipeline failures

Actual result
Timeout Right after Eventing Tests
https://status.build.kyma-project.io/view/gs/kyma-prow-logs/pr-logs/pull/kyma-project_control-plane/1519/pre-main-control-plane-reconciler-e2e/1511328231528075264
https://storage.googleapis.com/kyma-prow-logs/pr-logs/pull/kyma-project_control-plane/1519/pre-main-control-plane-reconciler-e2e/1511328231528075264/build-log.txt

Failure during Eventing Tests
https://status.build.kyma-project.io/view/gs/kyma-prow-logs/pr-logs/pull/kyma-project_control-plane/1519/pre-main-control-plane-reconciler-e2e/1511086525536800768
https://storage.googleapis.com/kyma-prow-logs/pr-logs/pull/kyma-project_control-plane/1519/pre-main-control-plane-reconciler-e2e/1511086525536800768/build-log.txt

Steps to reproduce

Produce a Pipeline run that succeeds in reconciliation, but still causes FastIntegrationTests to fail

Troubleshooting

Cannot be circumvented

**Comment by jakobmoellersap** [comment]
> I checked the last 10 failing tests and here is the summary:
> 
> * 4 tests fail with the following error:
> 
> ```
> Timeout reached while waiting for reconciler to be ready. Exiting
> ```

@raypinto please provide the build logs and not just the pasted errors? E.g. for the Reconciler ones, usually the error is appearing in a component reconciler and this error message is not showing the actual failure.

> 
> * 1 test failed due to cloning issue

The cloning issue (if it is reoccuring) we should probably track in a separate issue.

> * 1 due to provisioning failure
> 
> ```
> error: timed out waiting for the condition on shoots/grdrn8yau
> ```

this should be targeted by the retry in the cluster provisioning, maybe you can add more context in https://github.com/kyma-project/kyma/issues/13855

> 
> * One Getting Started Guide issue with persistence
> 
> ```
> Getting Started Guide Tests:
>          Order should be persisted and should survive pod restarts (redis storage):
>      Error: Order not found: 762727210
> ```

I think this is a separate issue but we would still need to find out the Root Cause before creating a new ticket

> 
> * The last 3 are CommerceMock Tests that are failing due to:
> 
> ```
> Test namespaces should be deleted:
>      Error: Timeout of 600000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves
> ```

This is usually because of a failure above that cant be observed in this log message, it would help if you could also paste the build logs and not only the error messages

> 
> ```
> function should be reachable through secured API Rule:
>      Error: Function lastorder responded with error
> 500: Internal Server Error: "Internal Server Error"
> ```

This one I think is related to the Setup of the Virtual service and is the same as below

> 
> ```
> CommerceMock test fixture should be ready:
>      Error: Wait for VirtualService commerce-mock timeout (20000 ms)
> ```

This I think is one of the main causes of instability and it would be great if we could find out the cause here

**Comment by raypinto** [comment]
@jakobmoellersap  So in summary the main issues to tackle are:
- More detailed logs on the prow job: which component reconciler fails and why
- Further investigation into `VirtualService commerce-mock timeout`

**Comment by jakobmoellersap** [comment]
First One I think we misunderstand: Im saying in the logs there are already information available, but you have to copy that log as well and not just look at the final timeout of the reconciler

The`VirtualService commerce-mock timeout` I agree, would be cool if you could tell me where this is best situated. 

However there are also lots of other issues that you left out in your summary which also need follow-ups. Even if you don't tackle them, I think we should create follow-up issues.

**Comment by raypinto** [comment]
After our discussion we concluded that:
- The main reason for flakiness comes from the Commerce mock tests timing out and I created [this](https://github.com/kyma-project/kyma/issues/13873) ticket for the same.
- Also created an issue for the `Getting Started Guides` test failing due to persistence issue [here](https://github.com/kyma-project/kyma/issues/13874).
- I have updated the [issue](https://github.com/kyma-project/kyma/issues/13855) with the provisioning error - quota filled 
- The [cloning issue](https://storage.googleapis.com/kyma-prow-logs/pr-logs/pull/kyma-project_control-plane/1481/pre-main-control-plane-reconciler-e2e/1509482796505108480/build-log.txt) occurs rarely but we need to keep an eye out for it.
- There is no eventing issue and hence I can remove the label.

If there is nothing I missed out, feel free to close the issue.

**Comment by jakobmoellersap** [comment]
Thanks for looking into everything and for the analysis. I will close the issue here as all follow-ups are created
