### ISSUE TITLE
Commerce Mock Tests timeout on multiple pipelines

### ISSUE THREAD

**Issue by raypinto** [kyma-project/kyma#13873]
**Description**

The commerce mock tests, which are part of the fast integration tests time out multiple times on multiple pipelines, which seem to be one of the reasons for flakiness.

Some of the test runs can be found [here](https://storage.googleapis.com/kyma-prow-logs/pr-logs/pull/kyma-project_control-plane/1519/pre-main-control-plane-reconciler-e2e/1511086525536800768/build-log.txt) and [here](https://storage.googleapis.com/kyma-prow-logs/pr-logs/pull/kyma-project_control-plane/1519/pre-main-control-plane-reconciler-e2e/1511328231528075264/build-log.txt).

**Expected result**

The commerce mock is initialised properly and the tests succeed (do not timeout).

**Actual result**

The tests time out with the following error:

```
1) Executing Standard Testsuite:
       CommerceMock Tests:
         CommerceMock test fixture should be ready:
     Error: Wait for VirtualService commerce-mock timeout (20000 ms)
      at Timeout._onTimeout (utils/index.js:404:20)
      at listOnTimeout (internal/timers.js:557:17)
      at processTimers (internal/timers.js:500:7)

  2) Executing Standard Testsuite:
       CommerceMock Tests:
         in-cluster event should be delivered (structured and binary mode):
     Error: Fetching published event responded with error: AssertionError: The same event id expected in the result: expected { podName: 'lastorder-vsf92-6dbfb4b797-jphdd' } to have nested property 'event.id'
      at convertAxiosError (utils/index.js:97:12)
      at /home/prow/go/src/github.com/kyma-project/kyma/tests/fast-integration/test/fixtures/commerce-mock/index.js:873:15
      at processTicksAndRejections (internal/process/task_queues.js:95:5)
      at async checkInClusterEventDeliveryHelper (test/fixtures/commerce-mock/index.js:860:10)
      at async checkInClusterEventDelivery (test/fixtures/commerce-mock/index.js:825:3)
      at async Context.<anonymous> (test/1-commerce-mock.js:58:7)

  3) Executing Standard Testsuite:
       CommerceMock Tests:
         function should be reachable through secured API Rule:
     Error: Wait for VirtualService commerce-mock timeout (20000 ms)
      at Timeout._onTimeout (utils/index.js:404:20)
      at listOnTimeout (internal/timers.js:557:17)
      at processTimers (internal/timers.js:500:7)

  4) Executing Standard Testsuite:
       CommerceMock Tests:
         order.created.v1 event should trigger the lastorder function:
     Error: Wait for VirtualService commerce-mock timeout (20000 ms)
      at Timeout._onTimeout (utils/index.js:404:20)
      at listOnTimeout (internal/timers.js:557:17)
      at processTimers (internal/timers.js:500:7)

  5) Executing Standard Testsuite:
       CommerceMock Tests:
         order.created.v1 cloud event in structured mode should trigger the lastorder function:
     Error: Wait for VirtualService commerce-mock timeout (20000 ms)
      at Timeout._onTimeout (utils/index.js:404:20)
      at listOnTimeout (internal/timers.js:557:17)
      at processTimers (internal/timers.js:500:7)

  6) Executing Standard Testsuite:
       CommerceMock Tests:
         order.created.v1 cloud event in binary mode should trigger the lastorder function:
     Error: Wait for VirtualService commerce-mock timeout (20000 ms)
      at Timeout._onTimeout (utils/index.js:404:20)
      at listOnTimeout (internal/timers.js:557:17)
      at processTimers (internal/timers.js:500:7)

  7) Executing Standard Testsuite:
       CommerceMock Tests:
         should add, update and delete a service:
     Error: Wait for VirtualService commerce-mock timeout (20000 ms)
      at Timeout._onTimeout (utils/index.js:404:20)
      at listOnTimeout (internal/timers.js:557:17)
      at processTimers (internal/timers.js:500:7)
```

**Steps to reproduce**

**Troubleshooting**

**Comment by jakobmoellersap** [comment]
@a-thaler could you help me identify who could work on this for making sure the CommerceMock is synced properly? @raypinto mentioned this is possibly related to the CommerceMock not being ready at the time the tests run, can you confirm this?

**Comment by a-thaler** [comment]
There is an assertion to assure that the commerce-mock deployment is running. That assertion was successful as it is called directly before the assertion about virtualservice.

The assertion about the virtualservice is checking that the virtualservice gets created and has a host assigned. The mock gets deployed using an apirule, maybe there was a problem with the api-gateway not generating the related virtualservice.

**Comment by wozniakjan** [comment]
I am observing commerce mock failures to block https://github.com/kyma-project/control-plane/pull/1600, https://github.com/kyma-project/control-plane/pull/1576 to merge. These are on completely unrelated topics without any overlap with commerce mock. Current error is:
```
  1) Executing Standard Testsuite:
       "before all" hook: CommerceMock test fixture should be ready in "Executing Standard Testsuite:":
     Error: Commerce mock local API not available - timeout
503: Service Unavailable: "no healthy upstream"
      at convertAxiosError (utils/index.js:118:10)
```

would be great to get this resolved or at least temporarily allow a workaround so it is not blocking other work.

**Comment by Sawthis** [comment]
@PK85 what is the status of this issue? It's release blocker for Kyma Runtime 2.3 release and should be fixed before 15th of June.

**Comment by arturskorupa** [comment]
@PK85 @wozniakjan @a-thaler @raypinto if you expect some change to the code to fix it the last possible date to deliver it would be 1 June in the morning.

**Comment by koala7659** [comment]
I think it should not be a release blocker. In our team we have recently spent a lot of time fixing and debugging these tests. We consider them are rather reliable and we got repeatable results during the whole last week. However there are some issues that we should be aware of:

1) Commerce Mock Fast Integration Tests are executed on different jobs and on different environments. Some of them are heavily dependent on external systems like provisioning on Gardener, Registration in Compass or reconciliation. Any problems in those areas (that happens from time to time) ends as failed test run.

2) Sometimes tests just fail randomly because some Kyma components cannot be installed. We are tracking this problem as possible reconciler bug

3) Commerce Mock code is used by multiple tests (eventing, skr, compass) Any change in the code must be done very carefully to not break any exiting tests.

**Comment by khlifi411** [comment]
I am observing a similar error on the following reconciler [pipeline](https://status.build.kyma-project.io/job-history/gs/kyma-prow-logs/logs/nightly-main-reconciler-e2e):
```
Executing Standard Testsuite:
[ERROR] Error: Waiting for lastorder function timeout (90000 ms)
    1) "before all" hook: CommerceMock test fixture should be ready in "Executing Standard Testsuite:"


  0 passing (4m)
  1 failing

  1) Executing Standard Testsuite:
       "before all" hook: CommerceMock test fixture should be ready in "Executing Standard Testsuite:":
     Error: Waiting for lastorder function timeout (90000 ms)
      at Timeout._onTimeout (utils/index.js:342:20)
      at listOnTimeout (internal/timers.js:557:17)
      at processTimers (internal/timers.js:500:7)
```

Would be great if you have another look at it.
