### ISSUE TITLE
Getting Started Guide Tests fail with persistence issue

### ISSUE THREAD

**Issue by raypinto** [kyma-project/kyma#13874]
**Description**

Some of the pipelines are flaky due to the failing `Getting Started Guide Tests` with the following error:
```
Executing Standard Testsuite:
       Getting Started Guide Tests:
         Order should be persisted and should survive pod restarts (redis storage):
     Error: Order not found: 762727210
      at findOrder (test/fixtures/getting-started-guide/index.js:98:9)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (internal/process/task_queues.js:95:5)
      at async verifyOrderPersisted (test/fixtures/getting-started-guide/index.js:84:3)
      at async Context.<anonymous> (test/2-getting-started-guide.js:36:7)
```

Some of the failing tests can be found [here](https://storage.googleapis.com/kyma-prow-logs/pr-logs/pull/kyma-project_control-plane/1521/pre-main-control-plane-reconciler-e2e/1511687021553258496/build-log.txt), [here](https://storage.googleapis.com/kyma-prow-logs/pr-logs/pull/kyma-project_control-plane/1477/pre-main-control-plane-reconciler-e2e/1509153873531506688/build-log.txt
), [here](https://storage.googleapis.com/kyma-prow-logs/pr-logs/pull/kyma-project_control-plane/1477/pre-main-control-plane-reconciler-e2e/1508791476417466368/build-log.txt) and [here](https://storage.googleapis.com/kyma-prow-logs/pr-logs/pull/kyma-project_control-plane/1467/pre-main-control-plane-reconciler-e2e/1504732331099820032/build-log.txt).

**Expected result**

The tests pass.

**Actual result**

The tests are failing with persistence error.

**Steps to reproduce**

**Troubleshooting**

**Comment by kwiatekus** [comment]
@raypinto yes, lets track it there.
