### ISSUE TITLE
Instaler repeats operation on error

### ISSUE THREAD

**Issue by Tomasz-Smelcerz-SAP** [kyma-project/kyma#1388]
Installer must repeat operation on error instead of putting entire process in "Error" state.
Note: Consider back-off strategy for repetition.

AC:
- Installer retries installation on error (verify with two cases - non-existing component, wrong chart/helm error)
Installer retries update on error (verify like installation case)
- Installer retries uninstallation of a chart on error (verify with two cases - non-existing component, helm error)

**Comment by piotrmsc** [comment]
We should change the current workflow of install/upgrade retries.
The installer should make a retry only on the release that has failed to install/upgrade, not on all of them. Additionally, it should have a backoff policy for retries.

**Comment by Morriz** [comment]
Any updates here? I still notice the 1.3.0 installer starts from the beginning and reinstalls packages that were installed succesfully as well...

**Comment by piotrmsc** [comment]
Closing this one on favor of https://github.com/kyma-project/kyma/issues/5849. IF we stick to kyma operator we will build new roadmap for it
