### ISSUE TITLE
Installer resumes operation after crash/restart

### ISSUE THREAD

**Issue by Tomasz-Smelcerz-SAP** [kyma-project/kyma#1389]
Installer must be able to resume operation after restart

AC:

After Installer pod restart...
- Installer resumes installation
- Installer resumes update
- Installer resumes uninstallation

**Comment by piotrmsc** [comment]
@Tomasz-Smelcerz-SAP is it still valid?

**Comment by piotrmsc** [comment]
@Tomasz-Smelcerz-SAP bump

**Comment by Tomasz-Smelcerz-SAP** [comment]
I am closing this issue for the following reasons:
Installer pod crashes are extremely rare, I have never seen one actually and this issue targets such scenarios.
The installation process is likely to be handled correct in case of Installer Pod restart (eventual consistency) - this has been tested manually.
For update/uninstallation scenarios, the process probably won't finish correctly when Installer Pod is restarted. But, as mentioned, it almost never happen (we  don't have any reports?), so there's no value in fixing it now.
