### ISSUE TITLE
SKR integration tests fail - multiple reasons on kyma-preview-integration-dev pipeline

### ISSUE THREAD

**Issue by adityabhatia** [kyma-project/kyma#13959]
**Description**

SKR fast-integration tests are failing due to multiple reasons on kyma-preview-integration-dev pipeline

**Expected result**

No failures

**Actual result**

Tests are flaky - as per the last 2 runs

**Steps to reproduce**

1. https://status.build.kyma-project.io/view/gs/kyma-prow-logs/logs/kyma-preview-integration-dev/1513728710912512000#1:build-log.txt%3A261
2. https://status.build.kyma-project.io/view/gs/kyma-prow-logs/logs/kyma-preview-integration-dev/1513668312301572096#1:build-log.txt%3A85

**Troubleshooting**

Retest locally against current dev codebase, check pipeline setup

**Comment by PK85** [comment]
That was temporary issue with getting status from kcp CLI. Right now we have 6 green ones in a row.
