### ISSUE TITLE
Label Version on Installation Resource

### ISSUE THREAD

**Issue by nexus49** [kyma-project/kyma#1395]
**Description**
To be able to better understand what release was deployed to a kyma cluster it would be great if the kyma-installer could potentially leave a label or some other flag on the installation crd that indicates what release was installed.

**Comment by Tomasz-Smelcerz-SAP** [comment]
I have mixed feelings about this. Labels can be modified by anyone, so it's not the best choice for  informations that should reflect system status data such as version. I would prefer something nobody can easily change.
For now, the available option is to look at Kyma-Installer docker image tag. The released images do have semantic version on them, and it's a good "source of truth" for detecting versions.
Isn't that enough?

**Comment by nexus49** [comment]
Thank you for the hint on the image name i think it is good to have something that cannot be changed as you said. Yes i think this addresses my point, thank you!
