### ISSUE TITLE
Kyma deploy command fails with `client_loop: send disconnect: Broken pipe`

### ISSUE THREAD

**Issue by pbochynski** [kyma-project/kyma#13968]
**Description**

```
- No previous Kyma version found
- Using Kyma from the workspace directory: ./kyma
client_loop: send disconnect: Broken pipe
ERROR: (gcloud.compute.ssh) [/usr/bin/ssh] exited with return code [255].
2022/04/13 03:07:58 UTC [INFO] Stopping instance kyma-integration-test-01746b3e
2022/04/13 03:07:58 UTC [INFO] It will be removed automatically by cleaner job
scp: /home/sa_11779814865331[44](https://status.build.kyma-project.io/spyglass/lens/buildlog/iframe?req=%7B%22artifacts%22%3A%5B%22build-log.txt%22%5D%2C%22index%22%3A1%2C%22src%22%3A%22gs%2Fkyma-prow-logs%2Flogs%2Fkyma-integration-k3d-compass-dev%2F1514077267217616896%22%7D&topURL=https%3A//status.build.kyma-project.io/view/gs/kyma-prow-logs/logs/kyma-integration-k3d-compass-dev/1514077267217616896&lensIndex=1#build-log.txt:44)53801/kyma/tests/fast-integration/junit_kyma-fast-integration.xml: No such file or directory
ERROR: (gcloud.compute.scp) [/usr/bin/scp] exited with return code [1].
2022/04/13 03:08:01 UTC [INFO] Retrying in 15 seconds..
scp: /home/sa_117798148653314[45](https://status.build.kyma-project.io/spyglass/lens/buildlog/iframe?req=%7B%22artifacts%22%3A%5B%22build-log.txt%22%5D%2C%22index%22%3A1%2C%22src%22%3A%22gs%2Fkyma-prow-logs%2Flogs%2Fkyma-integration-k3d-compass-dev%2F1514077267217616896%22%7D&topURL=https%3A//status.build.kyma-project.io/view/gs/kyma-prow-logs/logs/kyma-integration-k3d-compass-dev/1514077267217616896&lensIndex=1#build-log.txt:45)3801/kyma/tests/fast-integration/junit_kyma-fast-integration.xml: No such file or directory
ERROR: (gcloud.compute.scp) [/usr/bin/scp] exited with return code [1].
2022/04/13 03:08:18 UTC [INFO] Retrying in 15 seconds..
scp: /home/sa_1177981[48](https://status.build.kyma-project.io/spyglass/lens/buildlog/iframe?req=%7B%22artifacts%22%3A%5B%22build-log.txt%22%5D%2C%22index%22%3A1%2C%22src%22%3A%22gs%2Fkyma-prow-logs%2Flogs%2Fkyma-integration-k3d-compass-dev%2F1514077267217616896%22%7D&topURL=https%3A//status.build.kyma-project.io/view/gs/kyma-prow-logs/logs/kyma-integration-k3d-compass-dev/1514077267217616896&lensIndex=1#build-log.txt:48)653314453801/kyma/tests/fast-integration/junit_kyma-fast-integration.xml: No such file or directory
ERROR: (gcloud.compute.scp) [/usr/bin/scp] exited with return code [1].
2022/04/13 03:08:35 UTC [INFO] Retrying in 15 seconds..
scp: /home/sa_117798148653314453801/kyma/tests/fast-integration/junit_kyma-fast-integration.xml: No such file or directory
ERROR: (gcloud.compute.scp) [/usr/bin/scp] exited with return code [1].
2022/04/13 03:08:[52](https://status.build.kyma-project.io/spyglass/lens/buildlog/iframe?req=%7B%22artifacts%22%3A%5B%22build-log.txt%22%5D%2C%22index%22%3A1%2C%22src%22%3A%22gs%2Fkyma-prow-logs%2Flogs%2Fkyma-integration-k3d-compass-dev%2F1514077267217616896%22%7D&topURL=https%3A//status.build.kyma-project.io/view/gs/kyma-prow-logs/logs/kyma-integration-k3d-compass-dev/1514077267217616896&lensIndex=1#build-log.txt:52) UTC [INFO] Retrying in 15 seconds..
scp: /home/sa_1177981486[53](https://status.build.kyma-project.io/spyglass/lens/buildlog/iframe?req=%7B%22artifacts%22%3A%5B%22build-log.txt%22%5D%2C%22index%22%3A1%2C%22src%22%3A%22gs%2Fkyma-prow-logs%2Flogs%2Fkyma-integration-k3d-compass-dev%2F1514077267217616896%22%7D&topURL=https%3A//status.build.kyma-project.io/view/gs/kyma-prow-logs/logs/kyma-integration-k3d-compass-dev/1514077267217616896&lensIndex=1#build-log.txt:53)314453801/kyma/tests/fast-integration/junit_kyma-fast-integration.xml: No such file or directory
ERROR: (gcloud.compute.scp) [/usr/bin/scp] exited with return code [1].
2022/04/13 03:09:10 UTC [ERROR] Failed after 5 attempts.
```

Failed jobs from last 24 hours:
- https://status.build.kyma-project.io/view/gs/kyma-prow-logs/logs/kyma-integration-k3d-compass-dev/1514077267217616896
- https://status.build.kyma-project.io/view/gs/kyma-prow-logs/logs/kyma-integration-k3d-compass-dev/1514062167962292224
- https://status.build.kyma-project.io/view/gs/kyma-prow-logs/logs/kyma-integration-k3d-compass-dev/1513911165481127936
- https://status.build.kyma-project.io/view/gs/kyma-prow-logs/logs/kyma-integration-k3d-compass-dev/1513850766660472832
- https://status.build.kyma-project.io/view/gs/kyma-prow-logs/logs/kyma-integration-k3d/1513865866540748800

**Comment by jakobmoellersap** [comment]
Expectation would be to reconnect via ssh into the GCP VM if we loose connectivity (e.g. due to a hickup). Also we should wrap the error and exit gracefully if we cannot reestablish connectivity by giving a better error message like "Connection to VM was lost and could not be reestablished for executing test: Cause..."

**Comment by tobiscr** [comment]
We will check if we can either execute the SSH call within a retry-loop and we will also check if it helps to adjust the SSH client settings (https://unix.stackexchange.com/questions/2010/what-does-the-broken-pipe-message-mean-in-an-ssh-session).

**Comment by tobiscr** [comment]
Using a retry for the SSH call could be risky as we are not sure that the executed bash-script is behaving idempotent and allows multiple re-runs.

For now, we adjusted the ALIVE timeouts of SSH - hope this solves this instability: https://github.com/kyma-project/test-infra/pull/5272

**Comment by tobiscr** [comment]
Issue happens again on 19th April

**Comment by tobiscr** [comment]
https://status.build.kyma-project.io/view/gs/kyma-prow-logs/logs/kyma-integration-k3d-compass-dev/1516644262148575232

**Comment by ruanxin** [comment]
Take into consider this issue: https://github.com/kyma-incubator/reconciler/issues/1042

**Comment by jakobmoellersap** [comment]
Unfortunately we still have problems with broken_pipe in some pipelines:
https://status.build.kyma-project.io/view/gs/kyma-prow-logs/pr-logs/pull/kyma-incubator_reconciler/1061/pre-main-reconciler-cli-kyma-prev-to-last-release-upgrade-k3d/1519280177689923584

**Comment by tobiscr** [comment]
Issue still happening a few times for this pipeline:

 https://status.build.kyma-project.io/?job=kyma-integration-k3d

**Comment by tobiscr** [comment]
Waiting for important improvement: https://github.com/kyma-project/test-infra/pull/5335

**Comment by jakobmoellersap** [comment]
can this be closed after the recent changes? @tobiscr

**Comment by tobiscr** [comment]
Yes, all changes are merged. Will close the ticket now.

**Comment by jakobmoellersap** [comment]
Still happening in https://status.build.kyma-project.io/view/gs/kyma-prow-logs/logs/kyma-upgrade-k3d-kyma2-to-main/1556701916606500864#1:build-log.txt%3A112-121 unfortunately, meaning its not fixed.

**Comment by arturskorupa** [comment]
It's temporarily happening and retry usually helps. Not a Release Blocker.

**Comment by tobiscr** [comment]
Issue is currently not happening, but cannot promise that it's permantely fixed. Solution could be to focus on https://github.com/kyma-project/test-infra/issues/5442
