### ISSUE TITLE
[Telemetry Operator] Detect naming collisions by validation webhook

### ISSUE THREAD

**Issue by chrkl** [kyma-project/kyma#13961]
**Description**
Users can define LogPipeline elements like files or parsers under a user-given name that can be referenced in other parts of the LogPipeline. These LogPipeline elements are stored in a shared ConfigMap by the telemetry-operator. If LogPipelines use a name for their resources, which has already been created by another LogPipeline, the following behaviour can happen:

* Deleting a LogPipeline deletes ConfigMap elements that are still in use by another LogPipeline (see #13882)
* ConfigMap elements can be overwritten with new values by another LogPipeline

The existing ValidatingWebhook for the LogPipeline CRD should detect and reject these collisions.

**Acceptance Criteria**
* A LogPipeline must not create files or parsers under a name that already exists.
* Referenced secrets must not contain keys that are already injected to the environment by other LogPipelines. The webhook should ensure that referenced secrets exist.

**Comment by a-thaler** [comment]
We will solve the problems for the different elements individual, for secrets/variables in https://github.com/kyma-project/kyma/issues/14558 and for parsers in https://github.com/kyma-project/kyma/issues/14554.
Then only files will be left which will be addressed with the bug report itself at https://github.com/kyma-project/kyma/issues/13882, will close the ticket
