### ISSUE TITLE
Restore blocker: REB should not recreate eventactivation when the serviceinstance is recreated

### ISSUE THREAD

**Issue by mwieczorek** [kyma-project/kyma#1398]
**Description**
When we restore a remote environment and related serviceinstances the remote environment broker tries to recreate eventactivation even if the resource already exists

**Expected result**
REB should check if EA exists and not create one if so

**Actual result**
We get an error:

```
OrphanMitigation - Provision call failed: provisioning failed while creating EventActivation on error:
while creating EventActivation with name: "ac031e8c-9aa4-4cb7-8999-0d358726ffaa" in 
namespace: "production": eventactivations.applicationconnector.kyma-project.io "ac031e8c-9aa4-4cb7-8999-0d358726ffaa" 
already exists @ 2018-10-23 11:58:21 +0000 UTC
```

**Steps to reproduce**

- Install kyma
- `kc apply -f https://raw.githubusercontent.com/kyma-project/kyma/master/components/remote-environment-broker/contrib/examples/remote-env.yaml`
- bind remote env to one of the environments, f.e. production
- add serviceinstance (class: promotions)
- create ark backup:
```
ark create backup reb-cs --include-resources remoteenvironment
ark create backup reb-prod --include-namespaces production
```
- install a new cluster with kyma
- restore:
```
ark restore create reb-cs --from-backup reb-cs
ark restore create reb-prod --from-backup reb-prod
```

**Troubleshooting**

**Comment by polskikiel** [comment]
It seems to be the same error as here: #546

**Comment by jasiu001** [comment]
**Order of restoration resources**

I tested twice restore backup operation to check which resources are restored first.

Result of first test:
1) ApplicationMapping
2) Application (2 sec later)
3) EventactivAtions (3 sec later)
4) ServiceInstance (9 sec later)

Result of second attempt
1) Application
2) ApplicationMapping (1sec later)
3) EventactivAtions (27 sec later)
4) ServiceInstance (14 sec later)

In both cases error from https://github.com/kyma-project/kyma/issues/1398#issuecomment-451919035 appears

**Comment by jasiu001** [comment]
**TO DO**
Add all ServiceInstance logs. Add first reason of failed for ServiceInstance.

**Comment by polskikiel** [comment]
Ok, so there was 2 troubles which are already addressed:
1. Not updated RBAC `update` role for EA. #2230 
2. With the RBAC fixed we got an error: `while updating EventActivation: metadata.resourceVersion: Invalid value: 0x0: must be specified for an update`. https://github.com/kyma-project/kyma/pull/2254
