### ISSUE TITLE
Define process to provide consistent testing windows for new Kyma versions

### ISSUE THREAD

**Issue by varbanv** [kyma-project/kyma#13985]
**Description**

Provide a way for customers to test and validate new Kyma versions before their managed production clusters are upgraded.

**Reasons**

Kyma version upgrades can introduce breaking changes for customer workloads. We extensively test the upgrades with our components but we do not have an official process on how to enable our customers to test their workloads with the new version. 
Customers have requested that there is a defined window when they can test Kyma version upgrades on their Dev and Test managed environments and that window should be longer than few days. 
We also have requests from internal teams to be able to test new functionality for longer periods with the help of a subset of users in order to get better feedback and detect any potential issues. Providing a testing window to customers would give us such capability.

**Attachments**

---
<details>
    <summary>:warning: Funnel process - do not remove!</summary>
    </br>

Name|Value
:--- | :---
theme | Enterprise-grade
business value | 10
technical value | 0
user value | 10
open-source value | 0
effort | 
requested by | 
</details>

**Comment by Sawthis** [comment]
Collect stage/dev global accounts from customers and perform upgrade together with kyma-integration upgrade. Provide one week window for customers tests.

**Comment by varbanv** [comment]
Multiple requests for this here: https://github.tools.sap/kyma/backlog/issues/1146

**Comment by mperumalswamy** [comment]
Any updates on this issue about availability?

Best regards,
Madhu

**Comment by varbanv** [comment]
Hi @mperumalswamy we are making steady progress with our modularization approach that includes the concept of release channels. Based on the release channels, end users would be able to select and use upcoming versions of each component in their clusters in order to preview and/or test new functionality ahead of the official releases. And, of course, the new approach allows users to only select the components they need in order to reduce upgrade times and disruption potential.

**Comment by mperumalswamy** [comment]
> Hi @mperumalswamy we are making steady progress with our modularization approach that includes the concept of release channels. Based on the release channels, end users would be able to select and use upcoming versions of each component in their clusters in order to preview and/or test new functionality ahead of the official releases. And, of course, the new approach allows users to only select the components they need in order to reduce upgrade times and disruption potential. 

Hi @varbanv Any timeline regarding this?

**Comment by varbanv** [comment]
We have completed the Kyma modularization project and will migrate the last component in existing clusters to the corresponding module this weekend.
From then on, users can test upcoming versions of any module by using the Fast channel in their **non-production** clusters and will receive that same module version in the Regular channel 2 weeks later.
Please, do not use Fast channel on production clusters!
