### ISSUE TITLE
Migrate fast-integration tests to the new Director API

### ISSUE THREAD

**Issue by franpog859** [kyma-project/kyma#14003]
**Why to do**

Compass plan (info from 13.04.2022) to deprecate the old Director API (direct management of scenario labels and label definitions) but they can do that only if all of the clients are properly migrated to the new one

The deadline: Q2 or early Q3 (info from 27.04.2022)

**What to do**

Migrate [fast-integration tests](https://github.com/kyma-project/kyma/blob/main/tests/fast-integration/compass/gql.js) to the new Compass Director API

List of mutations replacements to be done based on the discussion from 14.04.2022 with @DimitarPetrov :
- `updateLabelDefinition` - Can be dropped in favour of CreateFormation / DeleteFormation
- `registerApplication` with scenario label - In the future scenario label may be treated as protected and modified only via formation APIs. You can register the application and then assign it to a formation in separate calls.
- `setApplicationLabel` with scenario key - In the future scenario label may be treated as protected and modified only via formation APIs.  Can be dropped in favour of assign/unassign it to/from a formation.
- `deleteApplicationLabel` with scenario key - In the future scenario label may be treated as protected and modified only via formation APIs.  Can be dropped in favour of unassign from a formation.
- `setRuntimeLabel` with scenario key - In the future scenario label may be treated as protected and modified only via formation APIs.  Can be dropped in favour of assign/unassign it to/from a formation.
- `registerRuntime` with scenario label - In the future scenario label may be treated as protected and modified only via formation APIs. You can register the runtime and then assign it to a formation in separate calls.
- `deleteRuntimeLabel` with scenario key - In the future scenario label may be treated as protected and modified only via formation APIs.  Can be dropped in favour of unassign from a formation.

The new API is concurrent safe and responds with the error if one occurred

You can find the new API [here](https://github.com/kyma-incubator/compass/blob/main/components/director/pkg/graphql/schema.graphql#L1379)

**Comment by DimitarPetrov** [comment]
Are there any updates or timeline estimates for that?

**Comment by mvshao** [comment]
As @franpog859 mentioned in the [comment](https://github.com/kyma-project/kyma/issues/15037), we are implementing a new set of tests as a replacement for our fast-integration tests. We will be using the new Director API in them.
