### ISSUE TITLE
Add missing transient conditions in function reconciliation loop 

### ISSUE THREAD

**Issue by kwiatekus** [kyma-project/kyma#14002]
**Description**

Fix function status handling (the `if length > 1` delete problem)  e.g. handling of transient resources when updating function
- [ ] [configmap](https://github.com/kyma-project/kyma/pull/13859/files#diff-a16c292e5a7ff9790097faf8d7158e7d65c7093e560175d266c0ef8aab693068R37)
- [ ] [deployment](https://github.com/kyma-project/kyma/pull/13859/files#diff-3e3e2a41a3b756083f170518f0eee9612d24202fdffb0c75c626adb76f1bd360R60)

**Ideas**
 - more granularity in conditions ( i.e `configMapCreated`) - condition per phase

**Comment by m00g3n** [comment]
reference: https://maelvls.dev/kubernetes-conditions/

**Comment by kwiatekus** [comment]
Closing in favour of https://github.com/kyma-project/kyma/issues/15268
