### ISSUE TITLE
Remote Environment Issue

### ISSUE THREAD

**Issue by ektajhasapcom** [kyma-project/kyma#1401]
Hi Team,

Sometimes back, I have created remote environment using the below command:

 "helm install --name c4hana --set deployment.args.sourceType=c4hana --set global.isLocalEnv=false --set global.domainName=kyma.com --namespace kyma-integration ./resources/remote-environments"

It installed all the required metadata , gateway services and the role bindings.

But if I do the same thing today with latest kyma code from github it installs nothing. It installed only default remote environments.

What I can understand from the readme file is that now it is the job of remote-environment-controller to create the remote environment. 

But the document  doesn't provide clear understanding  of how to install it. It would be good if the document is updated with latest changes.

Thanks & Regards,
Ekta Jha

**Comment by Szymongib** [comment]
Hi Ekta,

Not to long ago we have implemented some changes regarding Remote Environment creation, you no longer need Helm for it. Now you only need to create Remote Environment resource and all the other required resources will be installed by Remote Environment Controller.

You can install RE using Kyma console (`https://console.{CLUSTER_DOMAIN}/home/settings/remoteEnvs`) or from terminal using `kubectl`. You can refer to https://kyma-project.io/docs/components/application-connector#getting-started-getting-started
