### ISSUE TITLE
Availability of Node.js16 and 18

### ISSUE THREAD

**Issue by lechnerc77** [kyma-project/kyma#14022]
**Description**

When will Kyma Functions support Node.js 16 and 18 as current and future active LTS releases? Is there a strategy which node versions will be supported and in which periods they are updated like "support for the last two LTS releases"?

**Reasons**

No roadmap information available

**Attachments**

-

**Comment by kwiatekus** [comment]
Thanks @lechnerc77 
Fair point with nodejs 16 - we will add it as part of 2.3 release.
I have created an issue for that 
https://github.com/kyma-project/kyma/issues/14067

As for nodejs 18 - it will become a supported runtime in kyma in Q4 2022 as it is planned to become active LTS in Q4
