### ISSUE TITLE
Sample Code of Kyma Functions

### ISSUE THREAD

**Issue by lechnerc77** [kyma-project/kyma#14023]
**Description**

The current sample code when creating Kyma Functions is very slim and is even not creating output into the logs. For the both supported languages it would be nice to have at least a "Hello World" sample that logs to console and uses some input parameters.

It would make sense to:

- access the context
- log to the console
- return string

*Remark* The context parameter `function-name` is not the Kyma Function name but the JavaScript function name, which is always `main` that cannot be changed. The parameter is not very useful this way. 

**Reasons**

Having an easier entry point when starting with Kyma Functions. 

**Attachments**

Proposal:

```javascript
module.exports = {
  main: async function (event, context) {

    const message = `Hello World from the Kyma Function ${context["function-name"]} running on ${context.runtime}!`;

    console.log(message);
    return message;
  }
}
```

```python
from string import Template

def main(event, context):
    
    message = Template('Hello World from the Kyma Function $functionname running on $runtime').substitute(functionname=context.get("function-name"), runtime=context.get("runtime") )

    print(message)
    return message
```

**Comment by lechnerc77** [comment]
As this seems to be too much work to be copied into the sample code (going stale now the second time), I close the issue

**Comment by kwiatekus** [comment]
Haven't the PR fix it?
https://github.com/kyma-project/busola/pull/1800

![Screenshot 2022-09-29 at 10 14 57](https://user-images.githubusercontent.com/6783567/192978021-05b0b1d8-4de7-4117-91b3-461793448e52.png)

**Comment by kwiatekus** [comment]
@lechnerc77 pls reopen if you see this is not working as you imagine
