### ISSUE TITLE
Error while editing remote environments

### ISSUE THREAD

**Issue by dariadomagala** [kyma-project/kyma#1402]
**Description**

After updating one of the default remote environments (`ec-default` or `hmc-default`) using Console, the Ui-api-layer throws an error `Error: internal error [name: "ec-default"]`. Even though there was an error, the remote environment has been updated properly. 
The same problem doesn't show up after updating remote environments created previously from the Console.

**Expected result**

The remote environment should be updated without errors.

**Actual result** 

We get an error:
`Error: internal error [name: "ec-default"]`.
From the ui-api pod logs:
`spec.services in body must be of type array: "null"`.

**Steps to reproduce**

Update one of the `ec-default` or `hmc-default` remote-environments using the Ui-api-layer.

**Comment by PK85** [comment]
We dont have default env anymore. Closed.
