### ISSUE TITLE
Remove Eventing component reconciler migration steps for Kyma 1.24.X

### ISSUE THREAD

**Issue by marcobebway** [kyma-project/kyma#14021]
**Description**

Remove Eventing component reconciler pre-action migration steps for Kyma 1.24.X here: https://github.com/kyma-incubator/reconciler/tree/main/pkg/reconciler/instances/eventing/preaction.

**Reasons**

- These steps are not required anymore since Kyma version **2.X.X** is released.
- This should be done before Kyma CLI upgrade their [helm](https://github.com/kyma-project/cli/blob/7763dda8496bbe209f35a190a58fb2e649d1ffcc/go.mod#L34) client to **v3.8.2** which introduces some breaking changes for rendering 1.24.X nats charts:
   ```
   failed helm client render: Failed to render HELM template for component 'eventing/charts/nats':
   release name "eventing/charts/nats": invalid release name, must match regex
   ^[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*$
   and the length must not be longer than 53
   ```

**Comment by mfaizanse** [comment]
PR: https://github.com/kyma-incubator/reconciler/pull/1071
