### ISSUE TITLE
Investigate failed helm client rendering for Eventing component reconciler

### ISSUE THREAD

**Issue by marcobebway** [kyma-project/kyma#14025]
### Description

This [PR](https://github.com/kyma-incubator/reconciler/pull/1041) is failing to reconciler Eventing component with the following error:

```
failed helm client render: Failed to render HELM template for component 'eventing/charts/nats':
release name "eventing/charts/nats": invalid release name, must match regex
^[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*$
and the length must not be longer than 53
```

**Comment by marcobebway** [comment]
### Facts

- PR: https://github.com/kyma-incubator/reconciler/pull/1041
- Reconciler commit: `a0b3c2fa1f1df27bf7e4cf19c686bf63f6b86805`.
- CLI commit: `6a02b72797b4d27880176480fd866ebda13c264d`.

### Findings

Upgrading helm to **v3.8.2** in Kyma CLI causes some breaking changes while rendering Kyma **1.24.X** nats charts.

### Possible solutions

1. Remove nats migration code from the Eventing component reconciler.
   - Requires team agreement.
2. Skip nats migration code in the Eventing component reconciler based on some conditions.
   - Based on what the migration should be skipped?

### Conclusion

The team agreed to go with solution #1 and created a follow-up ticket here https://github.com/kyma-project/kyma/issues/14021.

**Comment by VladislavPaskar** [comment]
I also like the first solution, as the second one requires more work.
