### ISSUE TITLE
ORY stack bump

### ISSUE THREAD

**Issue by strekm** [kyma-project/kyma#14064]
**Description**

Bump ORY chart components to latest version if possible. 

AC:
- [x] #14136
- [x] #14135
- [x] configuration updated
- [x] #14266
- [x] verification of breaking changes in components
- [x] manual tests executed
- [x] OPTIONAL CVEs are triaged or at least first analysis done on manual upload of new images
- [x] release notes
- [x] All updates need to be merged to main in single pull request

**Reasons**

Keeping components up to date

**Comment by dariusztutaj** [comment]
Feature branch created: **feature/ory-stack-bump**

**Comment by dariusztutaj** [comment]
First manual scan executed for:
eu.gcr.io/kyma-project/external/oryd/hydra-maester:v0.0.25
eu.gcr.io/kyma-project/external/oryd/oathkeeper:v0.38.25-beta.1
eu.gcr.io/kyma-project/external/oryd/hydra:v1.11.7

Most of CVEs were already triaged for older images

**Comment by cnvergence** [comment]
> Endpoint PUT /clients now returns a 404 error when the OAuth2 Client to be updated does not exist. It returned 401 previously. 
We are not affected by this change, as we don't have any test cases for updating clients that does not exist.
We run SQL migrations with auto-migrate init container.
