### ISSUE TITLE
Improve function-controller tests

### ISSUE THREAD

**Issue by m00g3n** [kyma-project/kyma#14079]
**Description**
Split tests based on [envtest](sigs.k8s.io/controller-runtime/pkg/envtest):
  - [function_reconcile_gitops_test.go](https://github.com/kyma-project/kyma/blob/88abcfe1a25889eaeef38b0583a31e0d767498b8/components/function-controller/internal/controllers/serverless/function_reconcile_gitops_test.go)
  -  [function_reconcile_test.go](https://github.com/kyma-project/kyma/blob/8e88ac391e5235f9a2a30d28b9024f1085506b64/components/function-controller/internal/controllers/serverless/function_reconcile_test.go)

Add unit tests where it's needed.

**Reasons**
Current implementation tests the flow always from beginning.
That makes those tests very long and much harder to understand.

The refactored tests should check some part of the system, not the whole as we have integration tests.
It would allow us to write more and better more specific unit tests.

**Attachments**

**Comment by kwiatekus** [comment]
This is a little bit vague, isn't it?
Please be more specific in the task description

**Comment by kwiatekus** [comment]
Currently we have very long scenarios testing the controller behavior from the begining of  control loop.
It would help to split into separate scenarios each with initial conditions to avoid starting from begining.
We agreed to improve it regularly: i.e whenever you touch the test scenario  try to extract pieces of it to separate scenarios.

**Comment by dbadura** [comment]
One important thing:
In tests we sometimes change the function. Before persisting this change in test, we should `default` and `validate` the function

**Comment by kwiatekus** [comment]
lets improve continously. Such items are hard to schedule tbh
