### ISSUE TITLE
Kyma Gardener CI Jobs fail when API Server Certificate is about to Expire and not rotated fast enough

### ISSUE THREAD

**Issue by jakobmoellerdev** [kyma-project/kyma#14104]
**Description**

Affected Pipelines:
- kyma-upgrade-gardener-kyma2-to-main-reconciler-main
- pre-main-control-plane-reconciler-upgrade-kyma2-latest-to-main-gardener

Currently all Pipelines that use Gardener and the Upgrade job in the Fast Integration Tests from https://github.com/kyma-project/kyma/blob/main/tests/fast-integration/monitoring/prometheus.js#L49 (Monitoring Tests) will fail because of an about to expire certificate. This causes massive pipeline streaks to go red which is less than ideal. 

```
  1) Upgrade test tests
       Prometheus Tests:
         No critical Prometheus alerts should be firing:
     AssertionError: Following alerts are firing: {
  labels: { alertname: [32m'K8sCertificateExpirationNotice'[39m, severity: [32m'critical'[39m },
  annotations: {
    description: [32m'Kubernetes API Certificate is expiring in less than 1 day'[39m
  },
  state: [32m'firing'[39m,
  activeAt: [32m'2022-04-26T12:28:29.368325149Z'[39m,
  value: [32m'4.732e+03'[39m
}: expected [ Array(1) ] to be empty
      at Object.assertNoCriticalAlertsExist (monitoring/prometheus.js:49:10)
      at async Context.<anonymous> (monitoring/index.js:40:7)
```

![image](https://user-images.githubusercontent.com/64904610/165335818-6fc7c8e4-8e25-4cbe-8399-83881b86d58d.png)
![image](https://user-images.githubusercontent.com/64904610/165342344-08cf0c95-5099-483c-8d42-edf90aa744f5.png)

**Expected result**

We are resilient against a short expiry and rotation remediation interval from gardener and only throw errors when the Certificate actually expired (which we would do anyway since then the API Server Connectivity would fail)

**Actual result**

Errors are thrown the day before rotation

**Steps to reproduce**

Run any pipeline with Gardener Upgrade Scripts

**Troubleshooting**

No workaround possible

Sample Runs:
https://storage.googleapis.com/kyma-prow-logs/logs/kyma-upgrade-gardener-kyma2-to-main-reconciler-main/1518923079181406208/build-log.txt
https://storage.googleapis.com/kyma-prow-logs/logs/kyma-upgrade-gardener-kyma2-to-main-reconciler-main/1518892880347795456/build-log.txt
https://storage.googleapis.com/kyma-prow-logs/logs/kyma-upgrade-gardener-kyma2-to-main-reconciler-main/1518651281722314752/build-log.txt
https://storage.googleapis.com/kyma-prow-logs/pr-logs/pull/kyma-project_control-plane/1633/pre-main-control-plane-reconciler-upgrade-kyma2-latest-to-main-gardener/1518959195888553984/build-log.txt
https://storage.googleapis.com/kyma-prow-logs/pr-logs/pull/kyma-project_control-plane/1634/pre-main-control-plane-reconciler-upgrade-kyma2-latest-to-main-gardener/1518959345209970688/build-log.txt

**Comment by jakobmoellersap** [comment]
This needs to be investigated further, I could not find out why the certificate warnings are issued

**Comment by tobiscr** [comment]
Issue with certificates is not happening again
