### ISSUE TITLE
Performance Evaluation of JetStream

### ISSUE THREAD

**Issue by raypinto** [kyma-project/kyma#14111]
**Description**

[Here](https://github.com/kyma-project/kyma/issues/13736) we did a first evaluation of performance for JetStream. As a followup we would like to:
- [x] Perform the evaluation again, but shut down nodes of the cluster during the evaluation
  - [x] No messages should be dropped
  - [x] Perform for both evaluation and production profiles

We ran the previous performance evaluations with `cpu limit` set to `1000m`. 
- [x] Use the existing profiles (evaluation and production) and test again
  - [x] No messages should be dropped
  - [x] Tweak the limits if needed.

**Comment by mfaizanse** [comment]
The first part, where we have to test the nodes shut-down will be done once we have the fix for: https://github.com/kyma-project/kyma/issues/14371

**Comment by mfaizanse** [comment]
Production Profile:
![image](https://user-images.githubusercontent.com/9897945/171613742-5b11ad5b-80ae-4eed-8ab8-ad73ef7a7e35.png)

**Comment by mfaizanse** [comment]
Eventing controller reaches the CPU limit (500m) on 100 events/sec. (Same for NATS with JetStream disabled)

**Comment by mfaizanse** [comment]
The performance of JetStream is similar to Simple NATS on Production profile, so no need to tweak the resource limits.

![image](https://user-images.githubusercontent.com/9897945/172395632-2ea55f86-de99-41d5-a48b-ce8198255791.png)

**Comment by mfaizanse** [comment]
PR: https://github.com/kyma-project/community/pull/677
