### ISSUE TITLE
Implement migration (pre-action) in Kyma Eventing Component Reconciler

### ISSUE THREAD

**Issue by mfaizanse** [kyma-project/kyma#14128]
- reminder: migration code needs to be idemponent (as usual in Kyma Eventing Component Reconciler)
  - [ ] migrate active backend from secret (label) to eventingbackend.Spec.Config.Beb.secretRef
     - [ ] edge case: if there are 2 secrets defined for BEB, fail the migration (best would be to not start the migration in this case at all)
     - [ ] create a follow-up ticket to not forget about removing the migration code
  - [ ] example Nats: read limit, maximum inflight config options from controller deployments env and write it to eventingbackend.Spec.Config)

**Comment by k15r** [comment]
The eventing reconciler was recently removed
