### ISSUE TITLE
Kyma deployment fails

### ISSUE THREAD

**Issue by MTAttic** [kyma-project/kyma#14125]
Hey!
  
I am currently trying to deploy Kyma und a k3d cluster, but the deployment fails every time.

I first run:
`kyma provision k3d`

But when I do:
`kyma deploy`

I get the error:
`Error: Cannot fetch Kyma version: Get "https://host.docker.internal:62676/apis/apps/v1/namespaces/kyma-system/deployments?labelSelector=reconciler.kyma-project.io%2Fmanaged-by%3Dreconciler": dial tcp 192.168.2.110:62676: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.`

Does anybody know the reason for this behavior?

Thanks for the help!

**Comment by tobiscr** [comment]
Hi @MTAttic : can you please provide me the CLI version you are using (can be retrieved by calling `kyma version`)?

**Comment by MTAttic** [comment]
Sure! Its "Kyma CLI version: 2.0.4"

**Comment by jakobmoellersap** [comment]
Hey! Could you add some detailed information by doing the following:
`k3d cluster delete --all` (if you have to persist a cluster please make sure to adopt this to only delete the kyma provisioned one)
`kyma provision k3d`
`docker info`
`kubectl cluster-info`

**Comment by MTAttic** [comment]
Result after running `docker info`:
`Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc., v0.8.2)
  compose: Docker Compose (Docker Inc., v2.4.1)
  sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc., 0.6.0)
  scan: Docker Scan (Docker Inc., v0.17.0)

Server:
 Containers: 9
  Running: 5
  Paused: 0
  Stopped: 4
 Images: 23
 Server Version: 20.10.14
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc io.containerd.runc.v2 io.containerd.runtime.v1.linux
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 3df54a852345ae127d1fa3092b95168e4a88e2f8
 runc version: v1.0.3-0-gf46b6ba
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 5.10.16.3-microsoft-standard-WSL2
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 12.33GiB
 Name: docker-desktop
 ID: JJYU:KH5W:CEMW:7KA5:QRJQ:SEOT:RSYS:3MFB:FOIG:XDFW:JAHF:ZXHH
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 No Proxy: hubproxy.docker.internal
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  hubproxy.docker.internal:5000
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No blkio throttle.read_bps_device support
WARNING: No blkio throttle.write_bps_device support
WARNING: No blkio throttle.read_iops_device support
WARNING: No blkio throttle.write_iops_device support`

Result after running `kubectl cluster-info`:
`
To further debug and diagnose cluster problems, use 'kubectl cluster-info dump'.
Unable to connect to the server: dial tcp 192.168.2.110:51612: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.`

**Comment by jakobmoellersap** [comment]
Hey @MTAttic, did you find a chance to look at this again? We're happy to help in case you still face issues.

**Comment by jakobmoellersap** [comment]
Closing as I am assuming this issue is solved, if you face any other issue, please reach out and reopen the ticket!

**Comment by cooshal** [comment]
Hi !
I tried the steps mentioned above, but did not succeed.

I am using Docker Desktop on Windows. I simply followed the steps mentioned in https://kyma-project.io/docs/kyma/latest/02-get-started/01-quick-install. But, it fails while executing the command and I receive the following error:
```
Error: Cannot fetch Kyma version: Get "https://host.docker.internal:52095/apis/apps/v1/namespaces/kyma-system/deployments?labelSelector=reconciler.kyma-project.io%2Fmanaged-by%3Dreconciler": dial tcp 192.168.0.10:52095: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
```

`k3d cluster list` gives
```
NAME   SERVERS   AGENTS   LOADBALANCER
kyma   1/1       1/1      true
```

If I select `docker-desktop` as the cluster, then `kubectl cluster-info` succeeds:
```
Kubernetes control plane is running at https://kubernetes.docker.internal:6443
CoreDNS is running at https://kubernetes.docker.internal:6443/api/v1/namespaces/kube-system/services/kube-dns:dns/proxy

To further debug and diagnose cluster problems, use 'kubectl cluster-info dump'.
```

However, if I select the `k3d-kyma` cluster, I receive the following error message after invoking `kubectl cluster-info`:
```
To further debug and diagnose cluster problems, use 'kubectl cluster-info dump'.
Unable to connect to the server: dial tcp 192.168.0.10:52095: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
```
I am also able to execute `kyma dashboard` and I am able to open the dashboard in the browser.

I am not sure if I configured something incorrectly. Any tips would be very helpful :)
