### ISSUE TITLE
[Telemetry Operator] Apply new findings - use rewrite tags, handle tags properly

### ISSUE THREAD

**Issue by a-thaler** [kyma-project/kyma#14141]
**Description**
After recent investigations new conclusions in regards to the concept for configurable logging are made. Thes findings needs to be reflected in the implementation of the operator.
See also https://github.com/kyma-project/community/pull/661 and https://github.com/kyma-project/community/pull/656

**Criterias**
- Implementation is reflecting the new concept
- Findings for pipelines with rewrite tags are implemented and tested
- Findings regarding tag management are implemented and tested

**Comment by a-thaler** [comment]
Please generate a default value for the match expression if not specified.
Please support custom suffixes in the match expression, only verify the prefix

**Comment by rakesh-garimella** [comment]
A default match condition is added when not passed
The checking of match condition has been improved
New config with rewrite tag is generated.
