### ISSUE TITLE
Cannot access kyma wormhole cluster

### ISSUE THREAD

**Issue by djumalin** [kyma-project/kyma#1416]
Hi, cannot access https://console.wormhole.cluster.kyma.cx
![image](https://user-images.githubusercontent.com/31624278/47429799-84cb4300-d7eb-11e8-9b16-fdf4498b8428.png)

**Comment by joek** [comment]
This ticket is probably a duplicate. Maybe @pbochynski you know the ticket where it is handled.

**Comment by sjanota** [comment]
This problem is probably because your browser caches old requests. Browsers usually stores openid configuration for 24h. You need to clear browser cache for console.<domain> and dex.<domain> to make it work again.
