### ISSUE TITLE
Improve Kyma Eventing Documentation

### ISSUE THREAD

**Issue by k15r** [kyma-project/kyma#14191]
The current version of the eventing related parts in the kyma documentation is incomplete and could be improved from a customers perspective

This issue contains subitems per section in the existing documentation:

- [x] #14192
- [x] #14193
- [x] #14194
- [x] #14195
- [x] #14196

**Comment by raypinto** [comment]
Followup: https://github.com/kyma-project/kyma/issues/11761

**Comment by mfaizanse** [comment]
Links:
- https://kyma-project.io/docs/kyma/main/02-get-started/04-trigger-workload-with-event
- https://kyma-project.io/docs/kyma/main/03-tutorials/00-eventing/
- https://kyma-project.io/docs/kyma/main/04-operation-guides/operations/evnt-01-eventing-monitoring
- https://kyma-project.io/docs/kyma/main/04-operation-guides/troubleshooting/eventing/
- https://kyma-project.io/docs/kyma/main/05-technical-reference/00-custom-resources/evnt-02-eventingbackend/
