### ISSUE TITLE
kyma eventing documentation -  operations guides

### ISSUE THREAD

**Issue by k15r** [kyma-project/kyma#14195]
Aspects to be covered here:

- Operations
   - switch jetstream storage backend (opensource only)
   - dashboards explained
     - which dashboards are shipped
- troubleshooting
   - check the subscription CR status
   - check the backend CR status
   - clean event type empty 
   - event not delivered
      - check various logs
   - event name cleanup collisions

**Comment by mfaizanse** [comment]
eventing reconciler does not support switching file storage to in-memory in Jetstream, so no need to add document for `switch jetstream storage backend (opensource only)`
