### ISSUE TITLE
Show details of remote environments in UI console

### ISSUE THREAD

**Issue by brendandobbs** [kyma-project/kyma#142]
It would be useful to see detailed information about the remote environment CRD directly in the console e.g.

- host name
- gateway URL
- availability

It would also be helpful to be able to test the connectivity to a remote environment and get back a meaningful message if the connection failed

**Comment by PK85** [comment]
About gateway URL, what do you exactly mean?
- (global)metadata service URL (registration and events), or
- (global)connection service URL, or
- (per RE) gateway URL host, or
- (per RE) gateway service URLs, or
- all of them
?

**Comment by brendandobbs** [comment]
I was referring to the per RE gateway service URL. 
After looking at a sample RE Custom Resource, the hostname is not relevant since we don't store that for the RE. As a developer I'm interested in seeing all the URLs for a specific RE.
Since the information is  all at the service levelI I would like to see these attributes for the services of a RE:

- displayName
- oauthUrl
- targetUrl 
- gatewayUrl

**Comment by brendandobbs** [comment]
Thanks, that's clear. 
Could we then include the targetUrl and oauthUrl in the "Provided Services & Events" table?

The reason for this request is that a customer can be connected to many different remote environments and the name itself will often not enough to know specifically which server/tenant is being used. A fully qualified host name is ideally what a developer would want to see. Even better that we have the URLs for the services/events so a developer can very easily copy and paste these for testing purposes.

**Comment by lszymik** [comment]
We have discussed that issue, and currently, we cannot implement it. 
One of the requirements in the Application Connector was to hide details of the connected solution and allow access only over the Service Catalog bindings.

In the future, we will create a concept of how to add customization to the Application Connector, so the administrator will have a possibility to hide or reveal details of the connector solution.
