### ISSUE TITLE
Kyma eventing on k3d not working on apple silicon

### ISSUE THREAD

**Issue by werdes72** [kyma-project/kyma#14221]
I tried running kyma cli to provision and deploy kyma onto a k3d cluster on Apple M1 SoC.

**Expected result**

After a few minutes kyma should be installed

**Actual result**

```
Component 'eventing' failed
context deadline exceeded
X Component 'eventing' failed
context deadline exceeded

Error: Kyma deployment failed.
```

**Steps to reproduce**

Commands used:

```
kyma provision k3d
kyma deploy
```

**Comment by k15r** [comment]
Tested with 2.13. Eventing works.
