### ISSUE TITLE
Hydra sqlite no such table: hydra_client

### ISSUE THREAD

**Issue by wh7577** [kyma-project/kyma#14231]
**Description**
In Kyma 1.24.9 or above (maybe Kyma 2.x also), oauth2 component hydra prompt error no such table: hydra_client.

We developed some APIs protected by oauth2, it works fine in kyma 1.24.3. But when I upgraded kyma to 1.24.11, the component hydra failed, 503 service unavailable & no such table: hydra_client displayed in log

Azure Kubernetes Cluster : 1.21.9
Kyma : 1.24.11

**Expected result**
No error

**Actual result**
Error found
![hydra failed 1](https://user-images.githubusercontent.com/3860078/167300407-c091e4bd-a125-41af-b301-e7716f9b08cf.png)
![hydra failed 2](https://user-images.githubusercontent.com/3860078/167300410-63fa221f-6752-4c82-a22d-eae1e00505c1.png)
![hydra failed 3](https://user-images.githubusercontent.com/3860078/167300411-4079c3b1-498a-4269-900c-5c1cacc2d0ed.png)

**Steps to reproduce**
Use different threads to invoke oauth2 APIs

**Troubleshooting**
https://github.com/ory/hydra/issues/2816

**Comment by werdes72** [comment]
Hello! Does that error still exists in latest kyma? We recommend upgrading to kyma 2.0.x

Please provide more precise steps to reproduce the issue.

**Comment by barchw** [comment]
We encourage you to bump to latest version of Kyma. Please reopen in case it still exists
