### ISSUE TITLE
Investigate possible performance improvements

### ISSUE THREAD

**Issue by kwiatekus** [kyma-project/kyma#14235]
**Description**
Multiple git functions result in fetching sources frequently. In case the size of git repository is big, it uses all resources and crashes the controler 

**Symptoms**
 - controller is CPU throttled - revisit CPU resources (requested and limits )
 - 5 functions declared simultaneously - total readiness time of all of them is lower than from before refactor
 - controller is entering a `crashloopBackoff`

**To Investigate**
 - optimise mounting of function sources into the build job
 - workflow for multiple functions reconciliation
 - arent'we throttled by github ? (Network bandwidth )
 - skip code fetching in some reconciliation conditions (currently it done excessively)
 - local cache per repo - to fetch only deltas
 
 
 **Attachments**
<img width="1326" alt="Screenshot 2022-05-06 at 14 23 57" src="https://user-images.githubusercontent.com/6783567/167364814-e9eb0175-d672-4a2d-9fdc-7bfbd39c0b12.png">

**Comment by kwiatekus** [comment]
I used a test runtime with kyma 2.2
I have setup multiple functions. ( many of those are git functions )
I upgraded kyma to main version

After update I see that serverless-ctrl-mngr pod doesnt restart and doesnt suffer from CPU throttling that was present before upgrade.
Thats good news 👏 

However I dont think I get how this label should work
https://github.com/kyma-project/kyma/pull/14251/files#diff-48c000138a07f94412f9f8d07d5eda1152ea8f8c0c4cf7ebcbeceb457d1bb9e7R87

I labeled one of the git functions with 
```yaml
  labels:
    serverless.kyma-project.io/continuousGitCheckout: 'true'
 ``` 
and I dont see that it reacts to git code changes more often than a function that is sourced from the same repo buut doesnt have the label.

Actually I observed quite  oposite  - labeled function is rebuilt much later than non labeled.
Do I do sth wrong?

**Comment by moelsayed** [comment]
Consider the following scenario: 
- You are working on a git function with a large git repo like test-infra. Before the performance optimization changes, we checked the code for changes _every time_ the function is reconciled. So, if you apply the function, and _during it's initial_ reconcile, pushed another change _before_ the function is ready, the changes will be picked immediately, and the new updates should be be used.

With the performance changes, we only check the source once at the beginning of the reconcile loop, and don't check it again until the function is ready and a cool off period has passed. The label allows the user to go back to the previous behavior if needed.

I think what you are looking for is the feature tracked in this [issue](https://github.com/kyma-project/kyma/issues/14279), which something new. We didn't have this functionality before.
