### ISSUE TITLE
kyma-preview-integration-dev timeout in tests

### ISSUE THREAD

**Issue by Tomasz-Smelcerz-SAP** [kyma-project/kyma#14244]
**Description**

`The kyma-preview-integration-dev` plan fails consistently with the following output:

```
0 passing (1m)
1 failing

  1) Execute SKR test
       "before all" hook: Provision SKR in "Execute SKR test":
     Error: before hook failed: Error: Error thrown by ensureOperationSucceeded: operation didn't succeed in time:
     {
	"state": "failed",
	"description": "Operation created : cannot create provisioning input creator"
}
```

No other errors or reasons are provided.
It looks like some underlying, but not reported, problem is causing that.

**Expected result**
More precise reason of failure is given - or there's no error at all.
It would be nice to have an error reported like: "error at _scriptname_:95" or something like that.

**Actual result**
The generic message doesn't point to the root cause of the problem.

**Steps to reproduce**

Observe the build log of the pipeline, for example: https://storage.googleapis.com/kyma-prow-logs/logs/kyma-preview-integration-dev/1523392415275159552/build-log.txt

**Troubleshooting**
N/A

**Comment by varbanv** [comment]
Per @PK85, preview plan is no longer supported so this pipeline should be removed.
