### ISSUE TITLE
[Configurable Logging] Performance analysis: filesystem buffer resource consumption

### ISSUE THREAD

**Issue by a-thaler** [kyma-project/kyma#14243]
**Description**
The default setup of fluent-bit needs to be tested against typical operational issues like availability, communication disruptions, scalability and so on. This ticket focusses on the specific aspect of the filesystem buffer and resource consumption.
That analysis needs to be documented and repeatable.

The analysis should should investigate about the impact of the filesystem buffer usage on other resources (CPU/memory). Does the filesystem usage require additional resources that have to be accounted during specific phases? The different phases to test are:
- Normal log shipping that stores chunks in the filesystem buffer only for a short moment
- Filling up the buffer due to a slow or stopped output
- Reading logs while the filesystem buffer operates at the capacity limit
- Draining chunks from the file system buffer when the output can receive logs again

**Reasons**
Assure typical NFRs upfront to allow a smooth operation

**Criteria**
- Document a test setup which could be automated in future
- Document resulting limits
- Document conceptual changes and create follow-up ticket

**Comment by lindnerby** [comment]
After testing with a new metric to visualize the buffer size and showing it with fluentbit's node footprint panels, it seems the increasing und decreasing buffer size and high load of logs affect the CPU and Memory consumption. Consumption of both go up but remain constant after a certain point.

![Screenshot 2022-06-02 at 15 11 14](https://user-images.githubusercontent.com/50365642/171637923-77cd1820-a10c-4dff-bb3e-a5ad0e491255.png)

**Comment by rakesh-garimella** [comment]
The results look fine here one thing needs to be considered is the calculation of filesystem buffer needs to be improved (here the buffer used is more than that of the limit set). The value should be sum of filesystem buffer limits of all the pipelines. Or the sum of allocation of buffer limits of all the pipelines should not exceed the max buffer limit
