### ISSUE TITLE
helm charts synchronised with official charts

### ISSUE THREAD

**Issue by dariusztutaj** [kyma-project/kyma#14266]
**Description**

Synchronize ory charts with officials. Version: 0.23.2

**AC:**
 - [x] hydra chart synced
 - [x] hydra-maester chart synced
 - [x] oathkeeper chart synced
 - [x] oathkeeper-maester chart synced
 - [x] all changes introduced in kyma have to be included in synced charts
 - [x] **changes made against feature branch: feature/ory-stack-bump**

**Attachments**
https://github.com/ory/k8s

**Comment by barchw** [comment]
Differences in oathkeeper charts -> https://github.com/barchw/oathkeeper/pull/1
oathkeeper-master directory name in Kyma charts was changed to oathkeeper-ma**E**ster for the purpose of this comparison

Differences in hydra charts -> https://github.com/barchw/hydra/pull/1

**Comment by cnvergence** [comment]
Regarding automount option for service account token:
- https://github.com/kyma-project/kyma/pull/14301#issuecomment-1128530248

**Comment by cnvergence** [comment]
We could not move auto-migrate to job, because we are not supporting jobs in the reconciler.
The reasoning behind this change is explained here:
- https://github.com/ory/k8s/issues/247
