### ISSUE TITLE
[Telemetry Operator] Community Plugins

### ISSUE THREAD

**Issue by a-thaler** [kyma-project/kyma#14309]
**Description**
The operator supports flexible configuration and usage of any filter and output plugin. As the Kyma main contributors cannot test all the different available plugins on every update (only the most relevant), it needs to rely on the tests done by the fluent bit contributors.
With https://github.com/kyma-project/kyma/issues/13146 we introduced an option to allow only specific plugins to be used at runtime to reflect that support conflict. However, that way is limiting the usage too much and will make the feature a lot unusable. Instead of forbidding the usage for a lot of plugins and making a native integration into other systems harder, the conflict must be expressed directly to the user and the user should be able to accept the risk of having a not fully integration-tested feature.
Still, there are some filters which can be really harmful and have no real usage without entering that harmful path. It should be possible to forbid these filters fully.

**Criterias**
- Have an option to enable "community" plugins explicitly via the CR (disabled by default)
- If disabled, you can only use the "allowed" plugins and filters in the CR (maybe rename "allowed"
- Revise the list of "allowed" plugins (currently filters are missing)
- Make the info if "community" mode is on available in the CR list view and make it observable (custom metric?)
- Forbid the usage of specific filters (kubernetes, rewrite_tag, multiline)

**Comment by TorstenD-SAP** [comment]
@a-thaler, @rakesh-garimella: Does it makes sense/is it possible to add some kind of warning somewhere that the usage of unsupported plugins can harm the system?

**Comment by rakesh-garimella** [comment]
The unsupported plugins is more like (untested plugins), we can may be give a warning message when they enable the flag in the CR.

**Comment by rakesh-garimella** [comment]
- `enableUnsupported` flag has been introduced. When set to `true` users can use unsupported/untested plugins
- When the above flag is enabled users are also presented with warning
- Printer column has been added to show the status of the flag
- A new metric `EnableUnsupportedPlugin` has been introduced to show the status of the flag
