### ISSUE TITLE
Investigate kube-state-metrics out-of-memory

### ISSUE THREAD

**Issue by skhalash** [kyma-project/kyma#14315]
**Description**

Investigate how a large number of pods impacts `kube-state-mertics` availability in terms of memory. consumption. How many pods can we handle with current resource limits?

**Reasons**

`kube-state-metrics` is getting OOM-killed on a Kyma cluster with a large number of pods (~6000 pods in the `default` namespace). 

**Attachments**

Similar problem with an older version of `kube-state-metrics`: https://github.com/kubernetes/kube-state-metrics/issues/493

**Comment by a-thaler** [comment]
kube-state-metrics got upgraded to 2.6.0 and for now we have not experienced the problem anymore. Will close the ticket for now
