### ISSUE TITLE
Failing skr-aws-upgrade-integration-dev while reconciling RMA component

### ISSUE THREAD

**Issue by khlifi411** [kyma-project/kyma#14368]
**Description**

We expect [skr-aws-upgrade-integration-dev](https://status.build.kyma-project.io/?job=skr-aws-upgrade-integration-dev) to be green. Currently, it is failing on the reconciliation of the RMA component and due to not enough logs we do not know what causes the issue.

**Expected result**

RMA component reconciles successfully

**Actual result**

Reconciliation of the RMA component fails consistently.
```
{
			"component": "rma",
			"correlationID": "64ed069c-e111-4f59-b1e3-6dd3a64916a9--85c4b101-912a-4b66-b26e-246e7c9ceb8d",
			"created": "2022-05-24T04:27:41.639642Z",
			"priority": 3,
			"reason": "context deadline exceeded",
			"schedulingID": "64ed069c-e111-4f59-b1e3-6dd3a64916a9--c78ce7a5-c367-49f0-853a-3207b1c628f8",
			"state": "error",
			"type": "reconcile",
			"updated": "2022-05-24T04:45:11.892882Z"
		},
```

**Steps to reproduce**

**Troubleshooting**

**Comment by lauraanddolay** [comment]
hi @khlifi411 now for he latest build skr `shoot--kyma-dev--fd60fa8` is deleted and its reconciler as below looks like good.
```
kcp rc -r 76f54e08-0893-4ef9-937a-2d4629ec74da
SCHEDULING ID                                                                RUNTIME ID                             CREATED AT            UPDATED               STATUES   LOCK   
76f54e08-0893-4ef9-937a-2d4629ec74da--8f9760d0-5715-4b76-a0c1-81f8fcc07b1c   76f54e08-0893-4ef9-937a-2d4629ec74da   2022/05/24 08:09:41   2022/05/24 08:13:56   ready            
76f54e08-0893-4ef9-937a-2d4629ec74da--27035277-5153-4530-8977-455da7aed4de   76f54e08-0893-4ef9-937a-2d4629ec74da   2022/05/24 08:19:41   2022/05/24 08:22:11   ready            
76f54e08-0893-4ef9-937a-2d4629ec74da--3b98e819-5bea-430c-a48f-1f717123c938   76f54e08-0893-4ef9-937a-2d4629ec74da   2022/05/24 08:27:41   2022/05/24 08:39:26   ready            
76f54e08-0893-4ef9-937a-2d4629ec74da--94dc5bdf-95b2-41a7-a159-b95a51e43b83   76f54e08-0893-4ef9-937a-2d4629ec74da   2022/05/24 08:44:41   2022/05/24 08:47:41   ready            
76f54e08-0893-4ef9-937a-2d4629ec74da--6520413b-a11d-4074-b450-22f128d821fa   76f54e08-0893-4ef9-937a-2d4629ec74da   2022/05/24 08:52:41   2022/05/24 08:55:11   ready            
76f54e08-0893-4ef9-937a-2d4629ec74da--cdd4ce35-f3aa-4951-a5b7-0f191c55382e   76f54e08-0893-4ef9-937a-2d4629ec74da   2022/05/24 08:57:41   2022/05/24 09:12:26   deleted
```

**Comment by lauraanddolay** [comment]
the build became `red` ....

**Comment by khlifi411** [comment]
Yes. Thank you, @lauraanddolay. It is failing with another error now related to the eventing gateway.
I will ping the `eventing` team to have a look 👍

**Comment by tobiscr** [comment]
Let's open a dedicated ticket for the Compass issue to have clear seapration between these problems

**Comment by arturskorupa** [comment]
@tobiscr, @khlifi411 you opened a dedicated ticket for Compass. But is this one still valid? Is there anything for eventing team ?

**Comment by varbanv** [comment]
@hanngos could you check if the failure is still RMA related and if not, open a new ticket for the pipeline failures, please?

**Comment by hanngos** [comment]
@varbanv, in the last green run of the pipeline ([on 20 June](https://storage.googleapis.com/kyma-prow-logs/logs/skr-aws-upgrade-integration-dev/1538854299382059008/build-log.txt)), the reconciliation of RMA succeeded. The reason why tests are failing is described in [this issue](https://github.com/kyma-project/kyma/issues/14650).
