### ISSUE TITLE
Failing skr-aws-integration-dev due to provisioning timeout 

### ISSUE THREAD

**Issue by tillknuesting** [kyma-project/kyma#14370]
skr-aws-integration-dev test keeps failing in the skr provisioning stage 

```

  1) SKR test
       "before all" hook: Ensure SKR is provisioned for "Execute the tests":
     Error: Timeout of 1800000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/home/prow/go/src/github.com/kyma-project/kyma/tests/fast-integration/skr-test/test.js)
      at listOnTimeout (internal/timers.js:557:17)
      at processTimers (internal/timers.js:500:7)
```

https://status.build.kyma-project.io/view/gs/kyma-prow-logs/logs/skr-aws-integration-dev/1528904942499139584

**Comment by tillknuesting** [comment]
still happening https://status.build.kyma-project.io/view/gs/kyma-prow-logs/logs/skr-aws-integration-dev/1529267334324162560

**Comment by tillknuesting** [comment]
https://status.build.kyma-project.io/view/gs/kyma-prow-logs/logs/skr-aws-integration-dev/1529629747368169472

**Comment by varbanv** [comment]
This error was fixed, new ticket will be created for the current failure in the pipeline.
