### ISSUE TITLE
Refactor the Eventing Backend integration tests to be independent from each other

### ISSUE THREAD

**Issue by marcobebway** [kyma-project/kyma#14394]
**Description**

The integration [tests](https://github.com/kyma-project/kyma/blob/788c0206cc4202b4d6613bb5b8bc166395aa0f75/components/eventing-controller/controllers/backend/reconciler_test.go#L220) for the Eventing Backend controller are dependant on each other, which means:

- The test cases must run in a particular order to succeed.
- Debugging a single test case is not possible, which makes fixing flaky tests difficult.
- In the future, if we want to run the integration tests in parallel, that would not be possible.

**Action items**

- [ ] Refactor the Eventing Backend integration tests to be independent from each other.
- [ ] The same test coverage should be maintained after the refactoring.

**Comment by nachtmaar** [comment]
@marcobebway We had a quick look at the test link which you provided and think the problem comes from this when block:
<details>
  <summary>Controller setup</summary>


```go
	When("Creating a controller deployment", func() {
		It("Should return an non empty owner to be used as a reference in publisher deployment", func() {
			ctx := context.Background()
			ensureNamespaceCreated(ctx, kymaSystemNamespace)
			ownerReferences = ensureControllerDeploymentCreated(ctx)
			// Expect
			// The matcher in the following Eventually assertion will match against the first returned parameter
			// and ensure that the second returned parameter (an error) is nil.
			Eventually(controllerDeploymentGetter(ctx), timeout, pollingInterval).ShouldNot(BeNil())
			Expect((*ownerReferences)[0].UID).ShouldNot(BeEmpty())
		})
	})
```

</details> 

We think the problem is that the controller is setup in a `when` block instead of a `BeforeSuite` block which would run before all other tests.


Can you please confirm that you mean this ?

**Comment by marcobebway** [comment]
@nachtmaar yes I confirm that.

**Comment by mfaizanse** [comment]
We will cover it when we are working on evaluating and improving the testing in Architecture Enhancement goal.
