### ISSUE TITLE
Kyma with Compass test function should be reachable through secured API Rule

### ISSUE THREAD

**Issue by Sawthis** [kyma-project/kyma#14393]
**Description**

The periodic [kyma-integration-k3d-compass-dev](https://status.build.kyma-project.io/?type=periodic&job=kyma-integration-k3d-compass-dev&state=failure)  job is constantly failing.

**Expected result**

The job is green again and we have 0 failures in last 24 hours.

**Actual result**

It failed 24 times in last 24 hours.

**Steps to reproduce**

Run the periodic kyma-integration-k3d-compass-dev job.

**Troubleshooting**

**Comment by Disper** [comment]
There is an issue on the compass side that is being tracked on some internal compass tooling that will not link here. If anyone is interested in more information, please reach either me or @franpog859.

**Comment by franpog859** [comment]
The `Error when updating label definition with key scenarios: Error: Error calling Director API: 422 Unprocessable Entity Error` problem I was working on is fixed now. I'm unassigning myself from this issue for now, @Sawthis

**Comment by Disper** [comment]
Pasting additional info that @franpog859 added [on Slack](https://sap-btp.slack.com/archives/C01CKAN1SKV/p1654773464760579?thread_ts=1653374542.850379&cid=C01CKAN1SKV):

```
function should be reachable through secured API Rule: Kyma with Compass test function should be reachable through secured API Rule

{expected { Object (event, podName) } to have nested property 'order.totalPriceWithTax.value' AssertionError AssertionError: expected { Object (event, podName) } to have nested property 'order.totalPriceWithTax.value'
    at checkFunctionResponse (test/fixtures/commerce-mock/index.js:137:35)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Context.<anonymous> (compass-test/compass-test.js:46:5)}
```
I will edit the title to reflect the current problem.

**Comment by Disper** [comment]
As the function is not reachable and api gateway exposes it (thx @nachtmaar for help with narrowing the issue down), can it be something that @wookiee or @goat would be able to know more about?

**Comment by kwiatekus** [comment]
For some reasons the last-order function in this scenario does not return proper order data in the response and hence the assertion fails (not consistently - its [flaky](https://status.build.kyma-project.io/job-history/gs/kyma-prow-logs/logs/kyma-integration-k3d-compass-dev))

Please refactor the test so it throes better errors.
To be honest, the `compass-test` doesnt tell a story. It hides a lot of details and creates false impression that api-gateway or serverless doesnt work.
What we read is an error "function should be reachable through secured API Rule" - but the function does respond via API.

IMO @kyma-project/framefrog or the compass team should investigate the flakiness

**Comment by kwiatekus** [comment]
As discussed with @pbochynski and @janmedrek this test could be dropped.
Each team should have solid test of their integrations and be accountable for them.
This test is a js based integration test that suffers from lack of ownership and flakiness

**Comment by janmedrek** [comment]
The pipeline has been removed.
