### ISSUE TITLE
Subscriptions are still in not ready state even after the sink is valid and reachable

### ISSUE THREAD

**Issue by raypinto** [kyma-project/kyma#14390]
**Description**

When the sink is not reachable or invalid, the subscription is not ready. But once the sink is up and reachable, the subscription is not in ready state, unless the user manually updates the subscription in order to trigger the reconciliation. 

**Expected result**

The subscription becomes ready once the sink is reachable

**Actual result**

The subscription ready status is false

**Steps to reproduce**

1. Create a function and subscription. The subscription must be ready
2. Delete the function. The subscription is still ready (this is also incorrect and needs to be fixed)
3. Delete the `eventing-nats-0` pod. Now the subscription ready status is false
4. Recreate the same function. The subscription status will not be ready (unless we manually add a label or change the spec)

**Troubleshooting**

Need to verify if we reconcile NATS backend every 10 mins

**Comment by mfaizanse** [comment]
The subscription is reconciled after 10 minutes and the subscription becomes ready.
Do we need to improve this so that the subscription becomes ready as soon as the SINK is reachable?

**Comment by k15r** [comment]
Open questions:
- turning the subscription ready when the sink is reachable also means that we have to render it not ready when the sink is not reachable. This would imply that we have to constantly probe the sink. Do we want to do that?
- with Jetstream even a not ready sink will not result in event loss, as the events can just be resent by jetstream. In this case we could render the subscription ready as long as the sink url is valid. 
- we could pause the subscription if an error threshold is reached on delivery.

**Comment by marcobebway** [comment]
This should start when PR https://github.com/kyma-project/kyma/pull/15295 is merged.

**Comment by muralov** [comment]
I have been able to reproduce the issue too. Whenever I delete or recreate a function it is taking less or equal to reconciliation time (10m) until subscription state is synced. 
Have you considered watching `function` CRs in a specific namespace with a subscription predicate? It means that whenever a function is changed, the subscription CRs pointing to it are reconciled.

**Comment by marcobebway** [comment]
We are not sure if this is still blocked or not. Moved to backlog and to be groomed next.

**Comment by k15r** [comment]
As we do not actively watch the service this behaviour will not change. Watching the sink introduces new discussions such as "do we need to probe the sink?"
