### ISSUE TITLE
Page loading of lambda functions is slow

### ISSUE THREAD

**Issue by brendandobbs** [kyma-project/kyma#144]
The page loading can be slow at times. In particular the page displaying the list of lambda functions is slow. It often takes 10-20s to load the page

**Comment by joek** [comment]
We will check if this problem is solved with luigification of console ui.

**Comment by PK85** [comment]
Issues that could help to implement a fix for lambda UI:
https://github.com/kyma-project/console/issues/133

**Comment by PK85** [comment]
to reproduce:
- clear browser cache and click lambda UI

**Comment by joek** [comment]
<img width="960" alt="screen shot 2018-09-19 at 15 37 35" src="https://user-images.githubusercontent.com/202380/45756878-4e197000-bc22-11e8-897c-efaf722e15ef.png">

**Comment by brendandobbs** [comment]
Thanks, looks good now.

**Comment by derberg** [comment]
yeap, bundles for angular apps are now 700kb and with additional enhancements in react apps we managed to get around 350
closing for now
