### ISSUE TITLE
Function jobs shouldn't request resources by default

### ISSUE THREAD

**Issue by dbadura** [kyma-project/kyma#14440]
**Description**
In current implementation by default we enforce build profile.

**Expected result**
By default the build profiles are not applied.

**Actual result**
Having those values set as default, that:
- function deployment request 500m cpu
- function build job request 1000m cpu
let's consider following situation:
User creates 3 function on node with 2000cpu available:
- first job requires 1000m, the available left is 1000m
- job finished and then we deploy the function which requires 500m, the available cpu is 1500m
- user deploy second function and at the end available cpu is 1000m
- user deploy third function. The job can fit, because we have 1000m cpu available and at the end we deploy function and cluster have available 500m cpu.
- the user want to upgrade one of those three functions and the upgrade stuck, because the job doesn't have enough space.

By default we shouldn't apply any build profiles or at least not enforce minimum request for build jobs.
I would consider to also remove the default profile for functions if the user didn't specify.

**Steps to reproduce**

**Troubleshooting**
Settings for minimum requests: https://github.com/kyma-project/kyma/blob/main/components/function-controller/pkg/apis/serverless/v1alpha1/function_validation.go#L28=

**Comment by kwiatekus** [comment]
function build job cannot start in an over-commited CPU environment.
The following shows the scenario: CPU utilisation is really low ( ~14%) but CPU commitment is ~100%

![Screenshot 2022-06-01 at 09 57 39](https://user-images.githubusercontent.com/6783567/171356532-3f2639ba-1403-4051-bdab-533404b9b2cb.png)

We should lower the overcommitment of CPU for kyma components

**Comment by kwiatekus** [comment]
We should 
 - delete the min and max values for the requested CPU time for function builds
 - analyse the actual CPU utilisation (% of the requested CPU time ) for kyma components that sit on most of the requested CPU
 - propose a PR with adjusted requested CPU time for kyma components

**Comment by kwiatekus** [comment]
Thanks
We have reduced the cpu overcommitment across kyma components - saving cpu cycles for build jobs.
Additionally, we removed the requested cpu and memory for the build jobs by default - allowing for more flexible job scheduling in scenarios where cpu is limited on the worker nodes
