### ISSUE TITLE
event push timeout value too low

### ISSUE THREAD

**Issue by brendandobbs** [kyma-project/kyma#1445]
**Description**

I see the following in the push logs 

`2018/10/26 09:20:08 MsgHandler :: Error send push request failed: Post http://order-validation-function.order-management:8080/: net/http: request canceled (Client.Timeout exceeded while awaiting headers)`

The default push timeout (push_request_timeout_ms) for lambda functions is 2 seconds. This is too low. In some cases we will have some logic that calls external systems that can take seconds to respond.

My suggestion would be to increase the default timeout to at least 10 seconds and increase the maximum timeout value to 60s (or even higher). 

Ideally a developer could change this value themselves if they needed to. I had to delete the subscription and create it again with a timeout of 5000ms (max timeout value) to fix the timeout issue.

**Comment by abbi-gaurav** [comment]
Assigning to @joek to increase the value when the lambda is created.
It would be nice to make it configurable in the lambda UI.
