### ISSUE TITLE
[Telemetry Operator] Limit amount of pipelines

### ISSUE THREAD

**Issue by a-thaler** [kyma-project/kyma#14459]
**Description**
The telemetry-operator is not managing yet the fluent-bit daemonset itself. With that the resource limits are hardcoded and a concept for scaling on base of amount of pipelines is still missing.
For now, the amount of pipelines which the daemonset can handle is limited (see https://github.com/kyma-project/kyma/issues/13144). So the operator should limit the amount to avoid instable setups.

**Criterias**
- define proper resource limits (have minimal settings for evaluation profile)
- derive max amount of pipelines and make it configurable (strive for 5 on prod and 3 on eval)
- if a user creates more pipelines then maximal allowed, pipeline validation must fail with a meaningful error message hinting the user in the right direction for self-helping

**Comment by chrkl** [comment]
The amount of pipelines have been limited to 3 for the default profile and 5 for the production profile by PR #14701. PR #14731 increased the Fluent Bit CPU resources to serve the pipelines in the production profile adequately.
