### ISSUE TITLE
[Telemetry Operator] Finalize fluent-bit exporter

### ISSUE THREAD

**Issue by a-thaler** [kyma-project/kyma#14460]
**Description**
In PR https://github.com/kyma-project/kyma/pull/14347 a first version of a sidecar was created, which is watching the filesystem of fluent bit and is exporting relevant metrics incl grafana panels. That sidecar needs to be finalized so that it can be included in the next release.

Another idea is to also watch the source folder of the container logs.

**Criterias**
- Verify low CPU usage under heavy filesystem size
- Improve metric naming (same prefix as fluentbit and typical naming for sizes)
- proper image creation (prow pipeline which builds, tags, pushes image)
- review helm chart
- add a small panel to the top area of fluentbit dashboard indicating that a pipeline buffer reached a limit
- add a panel to the grafana dashboard for the unsupported mode and fluentbit restarts metric (at the moment it is not even whitelisted in the servicemonitor)

**Comment by Teneroy** [comment]
Added new component called "directory-size-exporter". This component collects information about the size of top-level directories in the folder of specified container. Integrated this component, added new chart that displays collected result.
