### ISSUE TITLE
NATS JetStream rejects new messages if storage is full

### ISSUE THREAD

**Issue by mfaizanse** [kyma-project/kyma#14475]
**Description**

When the stream file storage is full, then Jetstream is failing to receive new events, even thought the stream `Discard Policy` is set to `Old`. 

**Expected result**

JetStream should remove the old messages and then receive and store the new messages when the storage is full.

**Actual result**

JetStream is failing to receive and store the new messages when the storage is full.

**Steps to reproduce**

1. Deploy Kyma (Production Profile)
2. Create function /  subscription.
3. Send events until JetStream file storage is full.
4. Try to send more events and see if they are received.

**Troubleshooting**

* Response of message request to EPP:
```
INFO[0003] Response Code---->500                         source=console
INFO[0003] Response Body---->nats: write /data/jetstream/$G/streams/sap/msgs/123.blk: no space left on device  source=console
```

* Logs from eventing-publisher-proxy:
```
time="2022-06-02T07:20:24Z" level=info msg="Event received id:[A234-1234-1234]"
time="2022-06-02T07:20:24Z" level=info msg="Stream sap exists, using it for publishing"
time="2022-06-02T07:20:24Z" level=info msg="Sending to NATS in Jetstream mode: Context Attributes,\n  specversion: 1.0\n  type: sap.kyma.custom.noapp.order.created.v1\n  source: noapp\n  id: A234-1234-1234\n  datacontenttype: application/json\nExtensions,\n  b3sampled: 1\n  eventtypeversion: v1\nData,\n  \"{\\\"foo\\\":\\\"bar\\\"}\"\n, stream name: sap"
time="2022-06-02T07:20:24Z" level=error msg="Cannot send event to NATS Jetsteram: nats: write /data/jetstream/$G/streams/sap/msgs/123.blk: no space left on device"
time="2022-06-02T07:20:24Z" level=info msg="Event dispatched" after=sap.kyma.custom.noapp.order.created.v1 before=sap.kyma.custom.noapp.order.created.v1 duration=2.053052ms id=A234-1234-1234 responseBody="nats: write /data/jetstream/$G/streams/sap/msgs/123.blk: no space left on device" source=noapp statusCode=500
```
* Logs from `eventing-nats-0`
```
[30] 2022/06/02 07:13:04.095451 [ERR] JetStream failed to store a msg on stream '$G > sap': write /data/jetstream/$G/streams/sap/msgs/123.blk: no space left on device
[30] 2022/06/02 07:13:04.099699 [ERR] JetStream failed to store a msg on stream '$G > sap': write /data/jetstream/$G/streams/sap/msgs/123.blk: no space left on device
```

* `nats stream info sap`
```
Information for Stream sap created 2022-06-01T13:41:57+02:00

Configuration:

             Subjects: kyma.>
     Acknowledgements: true
            Retention: File - Limits
             Replicas: 1
       Discard Policy: Old
     Duplicate Window: 2m0s
    Allows Msg Delete: true
         Allows Purge: true
       Allows Rollups: false
     Maximum Messages: unlimited
        Maximum Bytes: unlimited
          Maximum Age: unlimited
 Maximum Message Size: unlimited
    Maximum Consumers: unlimited


Cluster Information:

                 Name: eventing-nats
               Leader: eventing-nats-0

State:

             Messages: 1,412,458
                Bytes: 952 MiB
             FirstSeq: 1 @ 2022-06-01T11:58:22 UTC
              LastSeq: 1,419,523 @ 2022-06-02T07:00:11 UTC
     Deleted Messages: 7065
     Active Consumers: 1
```

* `nats consumer info sap`
```
? Select a Consumer 1c40e439fbcfe6b540fbca6f4af84d52
Information for Consumer sap > 1c40e439fbcfe6b540fbca6f4af84d52 created 2022-06-01T13:56:38+02:00

Configuration:

        Durable Name: 1c40e439fbcfe6b540fbca6f4af84d52
         Description: default/receiver/kyma.sap.kyma.custom.natsreceiver.order.created.v1
    Delivery Subject: _INBOX.trBwagl3mrgb7uKJ0K9V8n
      Filter Subject: kyma.sap.kyma.custom.natsreceiver.order.created.v1
      Deliver Policy: New
          Ack Policy: Explicit
            Ack Wait: 30s
       Replay Policy: Instant
  Maximum Deliveries: 100
     Max Ack Pending: 10
      Idle Heartbeat: 1m0s
        Flow Control: true

Cluster Information:

                Name: eventing-nats
              Leader: eventing-nats-0

State:

   Last Delivered Message: Consumer sequence: 1,417,519 Stream sequence: 1,419,523 Last delivery: 32m40s ago
     Acknowledgment floor: Consumer sequence: 1,417,519 Stream sequence: 1,419,519 Last Ack: 32m40s ago
         Outstanding Acks: 0 out of maximum 10
     Redelivered Messages: 0
     Unprocessed Messages: 2,006
          Active Interest: Active
```

**Comment by mfaizanse** [comment]
Info:
```
discard old doesn't mean do anything special when the server is full, it means remove old messages when you set Max Age, Max Bytes or Max Size.  You should not let your server drives go full JetStream cant manage your machines
```

**Comment by mfaizanse** [comment]
Also, retention policy in Production profile is shown as `Retention: File - Limits` and in evaluation profile its shown as `Retention: File - Interest`. Why its different in both profiles?

**Comment by k15r** [comment]
MaxBytes in combination with DiscardOld should do the trick for us. But we should expose this to the user and we must make sure default values are documented well

**Comment by raypinto** [comment]
Tasks: 
- [ ] Set the config MaxBytes in combination with DiscardOld 
- [ ] Expose this config to the user and make sure default values are documented well

**Comment by VladislavPaskar** [comment]
We want to use only [Interest](https://docs.nats.io/using-nats/developer/develop_jetstream/model_deep_dive#:~:text=NATS%20have%20it's%20own%20limit,set%20by%20LimitsPolicy%20are%20reached.) retention policy for all our profiles. Since `Discard` and `MaxBytes` configurations work only in pair with `Limits` retention policy, it is not possible to take advantage of them. 

So, let's keep the `interest` policy and once the stream storage gets full, return the 507 `StatusInsufficientStorage` HTTP code to the event publisher. By that we inform the user, that we cannot accept any new events and also won't lose old or new messages. 

As a follow-up for that, let's document the current behaviour and add some troubleshooting guides.

**Comment by k15r** [comment]
According to [here](https://natsbyexample.com/examples/jetstream/interest-stream/go#:~:text=Note%20that%20this,process%20the%20message.) Discard policies should work with retention policy limits.

**Comment by VladislavPaskar** [comment]
> According to [here](https://natsbyexample.com/examples/jetstream/interest-stream/go#:~:text=Note%20that%20this,process%20the%20message.) Discard policies should work with retention policy limits.

let's address that in [another issue](https://github.com/kyma-project/kyma/issues/15751)
