### ISSUE TITLE
Kyma 2.x with istio-1.13.2 does not install on Mac M1

### ISSUE THREAD

**Issue by krishnaarava** [kyma-project/kyma#14494]
**Description**
One of the components installed by Kyma is Istio, which should install on Mac M1.

**Expected result**

Kyma 2.x with Istio 1.13.2 installs on Mac M1.

**Actual result**

Kyma 2.x with Istio 1.13.2 does not install on Mac M1.

**Steps to reproduce**

Install Kyma 2 using homebrew  that offers Istio 1.13.2 (use Kyma CLI)

```
foo@foo-air ~ % kyma deploy
- No previous Kyma version found
- Using Kyma from the workspace directory: /Users/foo/.kyma/sources/2.2.0
- Initial setup
- Component 'CRDs' deployed
  Component istio failed. Retrying...
fork/exec /Users/foo/.kyma/istio/istio-1.13.2/bin/istioctl: bad CPU type in executable
X Component istio failed. Retrying...
fork/exec /Users/foo/.kyma/istio/istio-1.13.2/bin/istioctl: bad CPU type in executable
 
- Component 'certificates' deployed
- Component 'cluster-essentials' deployed
  Component 'istio' failed 

```

**Comment by werdes72** [comment]
Hello, did you use istioctl built for ARM?

**Comment by werdes72** [comment]
I tested this recently, Istio component can be installed on M1 mac without any troubles.
