### ISSUE TITLE
Tool tips for status icons

### ISSUE THREAD

**Issue by brendandobbs** [kyma-project/kyma#145]
We use green, grey and orange/red status icons (e.g. lambda list page) but it's not clear what they mean. We should add tool tips to explain what these mean.

Things we want to change:
* remove status bubbles and replace by colored text with tooltip for more detailed info (if available), see https://github.com/kyma-project/kyma/issues/145#issuecomment-422877552
* status column moved to last column before "Actions" column

Identified views that are affected:
* /home/settings/remoteEnvs: move status
* /home/settings/serviceBrokers: move status
* /home/environments/production/deployments: move status
* /home/environments/production/replicaSets: move status
* /home/environments/production/pods: move status
* /home/environments/production/services: move status

**Comment by derberg** [comment]
@rakesh-garimella shouldn't this feedback be taken more broadly, so to say. Lambda UI is not not the only place where we show statuses. In some UI we have icons, in some coloured text, and tooltip should be everywhere in my opinion, and this should be consistently across. @hardl are you handling such cross views consistency topics?

**Comment by rakesh-garimella** [comment]
I agree with you @derberg. It should be tackled at  a broader level.

**Comment by gopikannappan** [comment]
Overall alignment needed on how we show status for different components in Console

**Comment by derberg** [comment]
My 2 cents here, it should not be just a dot/circle with color. There are different statuses for green, red and this should already be visible to the user. This is an example from GKE console
![screen shot 2018-09-04 at 14 29 38](https://user-images.githubusercontent.com/6995927/45031418-0fdf5680-b04f-11e8-9e98-3f723497c4ee.png)

I would suggest we do it line in Service Instance view, status as colored string, red/green/yellow.

On hover the tooltip should be shown with more error details. And it should be located at the end of the row before `actions` icons

**Comment by brendandobbs** [comment]
I like this approach, very intuitive

**Comment by antiheld** [comment]
![Kyma_Instances-Details-Tab-2.png](https://images.zenhubusercontent.com/5ba20240bb59de04f7d4b3ba/57375a58-bc04-48ba-bec7-bac90548d40c)![Kyma_Instances-Details-Tab-Status.png](https://images.zenhubusercontent.com/5ba20240bb59de04f7d4b3ba/f20a3f1b-877b-4535-ad01-f3b57eb0d5bf)

**Comment by parostatkiem** [comment]
**BLOCKED BY:**
![image.png](https://images.zenhubusercontent.com/5ba8d87d4e030d642cf5cd1c/89ca7980-d7c3-4aaf-ac5b-285ff66dacba)
Happens in:
- Replica Sets
- pods
- services
- secrets

**Comment by derberg** [comment]
@parostatkiem you just need a running kubernetes dashboard

**Comment by parostatkiem** [comment]
@derberg could you extend your comment? I'm new to Kyma and all I do is '. /cmd/run.sh'. It was enaugh for a week but today something is wrong...

**Comment by derberg** [comment]
I quickly checked now and looks like tooltip functionality is not implemented. When you hover over the status there is no info about detailed message of the status. So running or error, you still don't know the details.

Please check Instances view for reference, displayed tooltip always displays detailed message, green in case of success, or yellow and red in case of other errors

**Comment by dariadomagala** [comment]
The missing tooltip text for mentioned resources will be handled in a different ticket.
