### ISSUE TITLE
Pre-Main-Control-Plane Pipelines: Failing frequently due to cluster not found

### ISSUE THREAD

**Issue by jeremyharisch** [kyma-project/kyma#14506]
**Description**
Following Pre-Main-Control-Plane Pipelines are failing on some runs due to Gardener problems:
- pre-main-control-plane-reconciler-e2e-latest-release
- pre-main-control-plane-reconciler-upgrade-kyma2-latest-to-main-gardener
- 
```
Error from server (NotFound): shoots.core.gardener.cloud "grdzqdeop" not found
Error from server (NotFound): shoots.core.gardener.cloud "grdzqdeop" not found
```

https://status.build.kyma-project.io/job-history/gs/kyma-prow-logs/pr-logs/directory/pre-main-control-plane-reconciler-e2e-latest-release
https://status.build.kyma-project.io/job-history/gs/kyma-prow-logs/pr-logs/directory/pre-main-control-plane-reconciler-upgrade-kyma2-latest-to-main-gardener

**Comment by varbanv** [comment]
Closing due to greener pipeline.
