### ISSUE TITLE
Cleanup core NATS after JetStream is in prod

### ISSUE THREAD

**Issue by raypinto** [kyma-project/kyma#14518]
**Description**

Once JetStream is in production, the pure NATS controller source code would need to be cleaned up. 

**Reasons**

To avoid maintenance of outdated source code.

**Tasks**

- [ ] Remove core NATS controller
- [ ] Remove the flag `enableJetStream` from the controller and the EPP deployment.

**Comment by nachtmaar** [comment]
@raypinto @k15r why is this ticket a high prio one ?
