### ISSUE TITLE
Expose JetStream configurations per subscription

### ISSUE THREAD

**Issue by raypinto** [kyma-project/kyma#14516]
**Description**

At the moment, JetStream configurations like `stream retention policy`, `consumer deliver policy` are set at the time of kyma installation. It would be more flexible if these configurations could be set or modified per subscription.

**Reasons**

For a particular subscription, if the user wants to receive all the messages that were already sent for a particular eventType, before creating the subscription, then he can do so by setting the config - consumer deliver policy to `all`. However, the pre-requisite for this would be to set the stream retention policy to `limits` OR we could have a new stream for subscriptions that set their `stream retention policy` to `limits`.

**Attachments**

**Comment by k15r** [comment]
will be addressed here: #13797
