### ISSUE TITLE
Subscription duplicates Content-Type on Cloud Event retry

### ISSUE THREAD

**Issue by johgoe** [kyma-project/kyma#14521]
**Description**

We are using kyma 2.2 with a nats backend. Sometimes it happens that a event could not handled by the the subscription sink service which results in an http error e.g. status 500.

We saw that the event will be delivered automatically after a some time but on the second try the content-type of the event is `application/json,application/json`. On the 3rd try the content-type header contains `application/json,application/json,application/json` and (or multiple content-type headers not sure about that because we can't log it on the network level but only in our application)

**Expected result**

We expected the content-type header stays stable with value of `application/json` on every retry.

**Actual result**

content-type header is appendens an additional `application/json` on every retry 

**Steps to reproduce**

1) Subscribe an event to a function which return an error 500 on first call.
2) Publish an event
3) Watch the received event on the 2nd retry.

**Comment by FriedrichWilken** [comment]
Thank you @johgoe we will look into this.

**Comment by bayern01kahn** [comment]
Hi Guys.  I met the same issue here. below are some logs.

`2022-06-15 05:18:59.513 WARN 7 --- [nio-8021-exec-2] .w.s.m.s.DefaultHandlerExceptionResolver : Resolved [org.springframework.web.HttpMediaTypeNotSupportedException: Invalid mime type "application/json,application/json,application/json,application/json": Invalid token character ',' in token "json,application/json,application/json,application/json"]
2022-06-15 05:25:56.630 WARN 7 --- [nio-8021-exec-4] .w.s.m.s.DefaultHandlerExceptionResolver : Resolved [org.springframework.web.HttpMediaTypeNotSupportedException: Invalid mime type "application/json,application/json,application/json": Invalid token character ',' in token "json,application/json,application/json"]
2022-06-15 05:30:56.691 WARN 7 --- [nio-8021-exec-6] .w.s.m.s.DefaultHandlerExceptionResolver : Resolved [org.springframework.web.HttpMediaTypeNotSupportedException: Invalid mime type "application/json,application/json,application/json,application/json": Invalid token character ',' in token "json,application/json,application/json,application/json"]
2022-06-15 05:33:59.801 WARN 7 --- [nio-8021-exec-9] .w.s.m.s.DefaultHandlerExceptionResolver : Resolved [org.springframework.web.HttpMediaTypeNotSupportedException: Invalid mime type "application/json,application/json,application/json,application/json,application/json,application/json,application/json": Invalid token character ',' in token "json,application/json,application/json,application/json,application/json,application/json,application/json"]
...`

**Comment by mfaizanse** [comment]
1st try (event.extensions.request.headers):

```
{
  host: 'test.tunas-testing.svc.cluster.local',
  'user-agent': 'Go-http-client/1.1',
  'content-length': '19',
  'ce-eventtypeversion': 'v1',
  'ce-id': 'A234-1234-1234',
  'ce-source': 'noapp',
  'ce-specversion': '1.0',
  'ce-time': '2022-06-20T14:33:57.261950092Z',
  'ce-type': 'sap.kyma.custom.noapp.order.created.v1',
  'content-type': 'application/json',
  'accept-encoding': 'gzip',
  'x-forwarded-proto': 'http',
  'x-request-id': '974c73b6-81bf-4b45-97d9-f9b6de86c7c7',
  'x-envoy-attempt-count': '1',
  'x-forwarded-client-cert': 'By=spiffe://cluster.local/ns/tunas-testing/sa/serverless-function;Hash=f88681b033600209a41ec90126c0d4334264679e0a8c35c091f6a035a9449c60;Subject="";URI=spiffe://cluster.local/ns/kyma-system/sa/eventing-controller',
  'x-b3-traceid': '04edc5642a98d292ce1738aa2389fd56',
  'x-b3-spanid': 'a2f414cc80399465',
  'x-b3-parentspanid': 'ce1738aa2389fd56',
  'x-b3-sampled': '1'
}
```

2nd try (event.extensions.request.headers):
```
{
  host: 'test.tunas-testing.svc.cluster.local',
  'user-agent': 'Go-http-client/1.1',
  'content-length': '19',
  'ce-eventtypeversion': 'v1',
  'ce-id': 'A234-1234-1234, A234-1234-1234',
  'ce-source': 'noapp, noapp',
  'ce-specversion': '1.0, 1.0',
  'ce-time': '2022-06-20T14:33:57.261950092Z, 2022-06-20T14:38:57.341133832Z',
  'ce-type': 'sap.kyma.custom.noapp.order.created.v1, sap.kyma.custom.noapp.order.created.v1',
  'content-type': 'application/json,application/json',
  'accept-encoding': 'gzip',
  'x-forwarded-proto': 'http',
  'x-request-id': '9b5c4c69-a7a0-44ea-8356-a142b5cc427b',
  'x-envoy-attempt-count': '1',
  'x-forwarded-client-cert': 'By=spiffe://cluster.local/ns/tunas-testing/sa/serverless-function;Hash=f88681b033600209a41ec90126c0d4334264679e0a8c35c091f6a035a9449c60;Subject="";URI=spiffe://cluster.local/ns/kyma-system/sa/eventing-controller',
  'x-b3-traceid': '5169a688f77e66609c632070c5b9e84f',
  'x-b3-spanid': '843c9e9080a41021',
  'x-b3-parentspanid': '9c632070c5b9e84f',
  'x-b3-sampled': '1'
}
```

**Comment by johgoe** [comment]
@mfaizanse did you find the root cause?  isn't it a bug? I saw you removed the bug label.

**Comment by friedrichwilken** [comment]
@johgoe we looked into this and found where and what this issue creates. To fix this we would be required to do a lot of rework of the code. Since this only effects NATS and since we will deprecate NATS in the future we decided to not put in extensive work to fix it but recommend to use JetStream instead. 

Thanks for filing the issue!

**Comment by johgoe** [comment]
@friedrichwilken thank you for your feedback. It's good to know that the JetStream implementation is different. We already switched to it with the latest update.
