### ISSUE TITLE
Application Gateway does not validate TLS certificate while fetching OAauth token for accessing remote API

### ISSUE THREAD

**Issue by koala7659** [kyma-project/kyma#14522]
There is a code in Application Gateway/Central Application Gateway that fetches OAuth token from endpoint defined as `authenticationUrl` in Service Definition in Application CR. 
This token is used later to authenticate a call to the API endpoint exposed by a remote system registered in Kyma.

This code is located in the file `components/central-application-gateway/pkg/authorization/oauth/oauthclient.go` and the function responsible for fetching the token is named `requestToken` 

**Current behavior**

The HTTP Client that fetches the token is set up in the way that it **does not check at all**  TLS certificate presented by the remote server. Such configuration is a possible security problem. 
 
``` go 
	transport := &http.Transport{
		TLSClientConfig: &tls.Config{InsecureSkipVerify: true},
	}
	client := &http.Client{Transport: transport}
```

**Expected behavior**

The Application Gateway should use the **skipVerify** flag value (from Application CR) both for the target API and for the Authorization endpoints (such as OAuth tokens).

**Comment by akgalwas** [comment]
It should be already fixed. Verify and close if needed.

**Comment by akgalwas** [comment]
It was fixed already.

**Comment by tobiscr** [comment]
Closing it as it was fixed already
