### ISSUE TITLE
Pre-Main-Control-Plaine Pipelines are failing due to Git, tmp files, and Proxy errors

### ISSUE THREAD

**Issue by jeremyharisch** [kyma-project/kyma#14537]
**Description**
The following pipelines are failing due to several reason frequently:
- [pre-main-control-plane-reconciler-e2e-latest-release](https://status.build.kyma-project.io/job-history/gs/kyma-prow-logs/pr-logs/directory/pre-main-control-plane-reconciler-e2e-latest-release)
- [pre-main-control-plane-reconciler-upgrade-kyma2-latest-to-main-gardener](https://status.build.kyma-project.io/job-history/gs/kyma-prow-logs/pr-logs/directory/pre-main-control-plane-reconciler-upgrade-kyma2-latest-to-main-gardener)

Both pipelines are failing very often (success rate <40%) due to three main reasons on different runs (alle error appear multiple times):
- After cloning the three needed Git repos, the pipeline just stops ([example](https://storage.googleapis.com/kyma-prow-logs/pr-logs/pull/kyma-project_control-plane/1765/pre-main-control-plane-reconciler-e2e-latest-release/1534523946651619328/build-log.txt))
```
...
HEAD is now at 5cc881244 Bump telemetry operator dependencies (#14523)
$ PWD=/home/prow/go/src/github.com/kyma-project/kyma  git branch --force main FETCH_HEAD
$ PWD=/home/prow/go/src/github.com/kyma-project/kyma  git checkout main
Switched to branch 'main'
$ PWD=/home/prow/go/src/github.com/kyma-project/kyma  git submodule update --init --recursive
```

- Not able to delete tmp file ([example](https://storage.googleapis.com/kyma-prow-logs/pr-logs/pull/kyma-project_control-plane/1766/pre-main-control-plane-reconciler-upgrade-kyma2-latest-to-main-gardener/1534538750279815168/build-log.txt))
```
...
tar: can't remove old file tmp: Is a directory
command terminated with exit code 1
...
```

- Proxy error ([example](https://storage.googleapis.com/kyma-prow-logs/pr-logs/pull/kyma-project_control-plane/1764/pre-main-control-plane-reconciler-upgrade-kyma2-latest-to-main-gardener/1534471520187846656/build-log.txt))
```
...
Error from server: error dialing backend: proxy error from vpn-seed-server:9443 while dialing 10.250.0.2:10250, code 503: 503 Service Unavailable
...
```

**Comment by varbanv** [comment]
Track as part of https://github.com/kyma-project/kyma/issues/14506
