### ISSUE TITLE
 pre-kyma-tests-components-application-connector pipelines fails

### ISSUE THREAD

**Issue by tillknuesting** [kyma-project/kyma#14546]
[PRs](https://github.com/kyma-project/kyma/pull/14470) are not able to merges as the test `pre-kyma-tests-components-application-connector` fails

https://status.build.kyma-project.io/view/gs/kyma-prow-logs/pr-logs/pull/kyma-project_kyma/14470/pre-kyma-tests-components-application-connector/1535146713956749312

```
Error: Directory "/home/prow/go/src/github.com/kyma-project/kyma/tests/components/application-connector" does not exist.
Usage: $ /home/prow/go/src/github.com/kyma-project/test-infra/prow/scripts/build-generic.sh /path/to/component [Makefile targets]
```

**Comment by koala7659** [comment]
Created PR with revert of the PR that have broken test pipelines https://github.com/kyma-project/test-infra/pull/5561

**Comment by ralikio** [comment]
Working again. Thanks!
