### ISSUE TITLE
Unsubscribe invalid subscribers before binding new subscriber to consumer [JetStream]

### ISSUE THREAD

**Issue by mfaizanse** [kyma-project/kyma#14540]
Currently, in the [`bindConsumersForInvalidNATSSubscriptions`](https://github.com/kyma-project/kyma/blob/0d398da15649c744f80b11b85b48a1dd8aca871b/components/eventing-controller/pkg/handlers/jetstream.go#L354) method, we are checking if the subscriber is invalid, then we are creating a new subscriber and binding it to the existing consumer.

Preferably, we should be first removing the invalid subscriber from JetStream before bind the new subscriber to the consumer.

Because sometimes there is following log in the eventing-controller:
```
{
   "level":"ERROR",
   "timestamp":"2022-06-09T08:46:56Z",
   "caller":"controller/controller.go:326",
   "message":"Reconciler error",
   "context":{
      "controller":"jetstream-subscription-reconciler",
      "object":{
         "name":"receiver",
         "namespace":"default"
      },
      "namespace":"default",
      "name":"receiver",
      "reconcileID":"51bce9c6-9ef6-40ab-92c9-8ae0dc836fe7",
      "error":"consumer is already bound to a subscription"
   }
}
```

**Comment by VladislavPaskar** [comment]
it is already covered by https://github.com/kyma-project/kyma/issues/15215
