### ISSUE TITLE
[Telemetry Operator] Support a single output only

### ISSUE THREAD

**Issue by a-thaler** [kyma-project/kyma#14555]
**Description**
With https://github.com/kyma-project/community/pull/675 we agreed to have only a single output per `LogPipeline`.

```YAML
  output: #only one output, no output should fail validation
    custom: | # no "Match" available, no filebuffer settings available, entering unsupported mode
      Name               es
      Alias              es-output
      Host               ${ES_ENDPOINT} # Defined in Secret
      HTTP_User          ${ES_USER} # Defined in Secret
      HTTP_Password      ${ES_PASSWORD} # Defined in Secret
      LabelMapPath       /files/labelmap.json
```

**Criterias**
- Only one output can be specified (no array anymore)
- Specifying no output should fail validation
- Examples are adjusted

**Comment by rakesh-garimella** [comment]
- Api has been adapted to support single output
- If no output is defined then the creation of logpipeline fails.
