### ISSUE TITLE
[Telemetry Operator] Match expression only for own pipeline

### ISSUE THREAD

**Issue by a-thaler** [kyma-project/kyma#14562]
**Description**
The operator supports custom filters and outputs with match expressions refering to other pipelines.
With https://github.com/kyma-project/community/pull/675/files that is obsolete and should be declined.

**Criterias**
- Custom filters and outputs cannot define a match expression, validation fails
- The match expression gets generated always with the expression for the respective pipeline the plugin is defined in
- Improved error message not being misleading
- Examples are adjusted and working

**Comment by Teneroy** [comment]
Prohibited match conditions for options and filters, removed the function to search for user defined match expressions, adapted and refactored tests. Now, no user can define their match expressions in outputs and filters, those are being generated automatically.
