### ISSUE TITLE
Failing periodic kyma-alpha-integration-production-gardener-azure job

### ISSUE THREAD

**Issue by Sawthis** [kyma-project/kyma#14584]
**Description**

Periodic [kyma-alpha-integration-production-gardener-azure](https://status.build.kyma-project.io/?type=periodic&job=kyma-alpha-integration-production-gardener-azure) job failed 5 times in last 24h counting from 14.06.2022 2PM.

**Expected result**

Fix or delete the job if not needed.

**Comment by Sawthis** [comment]
Periodic [kyma-alpha-integration-production-gardener-azure](https://status.build.kyma-project.io/?type=periodic&job=kyma-alpha-integration-production-gardener-azure) job failed 10 times in last 24h counting from 15.06.2022 11AM.

**Comment by varbanv** [comment]
Fixed for now, re-open if it starts failing again.
