### ISSUE TITLE
Failing periodic kyma-alpha-integration-evaluation-gardener-azure job

### ISSUE THREAD

**Issue by Sawthis** [kyma-project/kyma#14583]
**Description**

Periodic [kyma-alpha-integration-evaluation-gardener-azure job](https://status.build.kyma-project.io/?type=periodic&job=kyma-alpha-integration-evaluation-gardener-azure) failed 7 times in last 24h counting from 14.06.2022 2PM.

**Expected result**

Fix or delete the job if not needed.

**Comment by Sawthis** [comment]
Periodic [kyma-alpha-integration-evaluation-gardener-azure job](https://status.build.kyma-project.io/?type=periodic&job=kyma-alpha-integration-evaluation-gardener-azure) failed 10 times in last 24h counting from 15.06.2022 11AM.

**Comment by varbanv** [comment]
Seems to be fixed now.
