### ISSUE TITLE
Changelog creator

### ISSUE THREAD

**Issue by jasiu001** [kyma-project/kyma#1459]
AC:
- automatic creation of a change-log file by Travis-CI during release build

**Comment by derberg** [comment]
Few questions:
- what travis has to do with Kyma repo
- what is the scope of this task
- change log for kyma is already generated and there is a tool provided for it https://github.com/kyma-project/kyma/tree/master/tools/changelog-generator and we should not write another tool but invest in existing one if it is not supporting every kyma-project case
