### ISSUE TITLE
Show with an example how to inject secrets/configuration into function

### ISSUE THREAD

**Issue by kwiatekus** [kyma-project/kyma#14592]
**Description**

Publish [This](https://github.com/kwiatekus/kyma-serverless-community-hour) as kyma example.
Link the example in the basic "Create a function" tutorial

**Area**

*Serverless*

**Reasons**

After service catalog removal, [this](https://kyma-project.io/docs/kyma/latest/03-tutorials/00-serverless/svls-10-bind-a-serviceinstance-to-a-function) description is no longer valid.

**Assignees**

@kyma-project/technical-writers

**Attachments**
https://github.com/kwiatekus/kyma-serverless-community-hour

**Comment by klaudiagrz** [comment]
Please update also the linking to the [tutorial on SAP Help Portal](https://help.sap.com/docs/BTP/65de2977205c403bbc107264b8eccf4b/fe4ba5b46f794037a4aee13df9df2d3c.html?locale=en-US&version=Cloud).
