### ISSUE TITLE
Retry/Backoff policy for event subscriptions

### ISSUE THREAD

**Issue by brendandobbs** [kyma-project/kyma#146]
When events are not able to be processed (exception in the lambda function), the event sending is retried endlessly. Some strategy(ies) for handling backoff/retries are needed.

**Comment by abbi-gaurav** [comment]
@brendandobbs This is something we have on the roadmap.

**Comment by brendandobbs** [comment]
Design document for how knative eventing will handle retry and dead letter sink/channel https://github.com/knative/eventing/tree/master/docs/delivery
