### ISSUE TITLE
Investigate possibility to acquire the one-click integration URL

### ISSUE THREAD

**Issue by lszymik** [kyma-project/kyma#1461]
**Description**

That it the preflight issue before implementation of [Get Application Connector connection link without a port-forward command](https://github.com/kyma-project/kyma/issues/1152).

The issue must respond to the question of how to implement getting the connection URL.

**Reasons**

We need to select the best possible way according to:
- Kubernetes standards
- Easiness of use
- Ease of development
- Security

**Comment by crabtree** [comment]
Follow up in #1152
