### ISSUE TITLE
Improve description of binding usage

### ISSUE THREAD

**Issue by derberg** [kyma-project/kyma#1462]
**Description**

* ~section https://kyma-project.io/docs/components/service-catalog#create-a-servicebinding should include PodPreset in the architecture, or create separate doc if you want~
* make info about `envPrefix` detailed enough https://kyma-project.io/docs/components/service-catalog#custom-resource-servicebindingusage and fix word duplication errors

**Reasons**

For now we have not enough documentation and explanation of how SBU reuses PodPreset in the whole binding process and what is the role of `envPrefix` here.

**Comment by mszostok** [comment]
PodPreset - this is a technical aspect and already documented in BUC component README.md, that's a matter of exposing components docs in kyma-project.io.

**Comment by derberg** [comment]
still valid
