### ISSUE TITLE
support more current Kubernetes versions

### ISSUE THREAD

**Issue by tehret77** [kyma-project/kyma#14630]
**Description**

Please support more current Kubernetes versions. 

**Reasons**

We run Kyma on Azure and the current supported Kyma version (as of this creation date Kyma 2.3) support only up to Kubernetes 1.21.
Checking the Azure Kubernetes Service release calendar [1] the current highest supported Kubernetes version 1.21 is eol in July 2022

**Attachments**

[1] https://docs.microsoft.com/en-us/azure/aks/supported-kubernetes-versions?tabs=azure-cli#aks-kubernetes-release-calendar

**Comment by varbanv** [comment]
We are working on 1.22 support and should be available shortly.
With the recent changes to the Kyma installation process we aim to improve on the support for newer Kubernetes versions.

**Comment by tehret77** [comment]
Hi @varbanv can you already say until when? Kyma 2.4 or 2.5 release? Is there any ticket I can follow?

**Comment by varbanv** [comment]
Hi @tehret77, apologies for the late response! We do support 1.22 now and working on official 1.23 support shortly. As far as I know, we have not seen any issues with 1.23 at the moment but I have to double check.
