### ISSUE TITLE
Unable to verify the first certificate when provisioning

### ISSUE THREAD

**Issue by hanngos** [kyma-project/kyma#14650]
**Description**

An error `unable to verify the first certificate` appears on `skr-dev` pipelines causing tests to fail. The first case was noticed on the [`skr-aws-upgrade-integration-dev` pipeline on Monday 20.06 at 18:00](https://storage.googleapis.com/kyma-prow-logs/logs/skr-aws-upgrade-integration-dev/1538914698034941952/build-log.txt) and has remained since then. 

Error is caught in the provisioning step, but the provisioning itself succeeds.

**Expected result**
Not to have `unable to verify the first certificate` error.

**Actual result**

<img width="533" alt="image" src="https://user-images.githubusercontent.com/82164594/174980000-82a33069-7d3b-42ad-896b-0718e9cefe9d.png">

For more, see those skr pipelines:
 - [`skr-aws-upgrade-integration-dev`](https://status.build.kyma-project.io/?job=skr-aws-upgrade-integration-dev)
 - [`skr-aws-integration-dev`](https://status.build.kyma-project.io/?job=skr-aws-integration-dev)
 - [`skr-azure-integration-dev`](https://status.build.kyma-project.io/?job=skr-azure-integration-dev)

**Troubleshooting**

Wrap provisioning functions to find the place this error is being thrown.

**Comment by hanngos** [comment]
Error is being thrown by the `getShoot()` function.
https://github.com/kyma-project/kyma/blob/main/tests/fast-integration/kyma-environment-broker/helpers.js#L33

**Comment by varbanv** [comment]
@PK85 will check again the code history and if no changes found will drop the part testing compass.
