### ISSUE TITLE
If an arg is passed without a value, scripts exit without any error messages

### ISSUE THREAD

**Issue by suleymanakbas91** [kyma-project/kyma#1469]
**Description**

If an arg that needs a value is passed without specifying a value, then the scripts under `/installation/scripts` exit without any error. I tried with installer.sh and minikube.sh but since the other scripts have the same parsing logic, they might have the issue as well.

Try to run: 
`minikube.sh --domain`
`installer.sh --cr` 

**Expected result**

They should print out proper error messages.

**Comment by strekm** [comment]
Validate input parameters for scripts:
 - run.sh
 - installer.sh
 - minikube.sh

**Comment by Demonsthere** [comment]
I think we could make this more resilient by switching the argument passing to [getotps](https://wiki.bash-hackers.org/howto/getopts_tutorial) which has the required logic build in, and we do not need to reinvent it
