### ISSUE TITLE
Layout issue for lambda trigger popup  for events

### ISSUE THREAD

**Issue by brendandobbs** [kyma-project/kyma#147]
See screenshot
![image2018-8-1_11-1-31](https://user-images.githubusercontent.com/5688693/43796769-76d80f88-9a85-11e8-99cd-13e070d7f6ce.png)

**Comment by joek** [comment]
@sayanh your are working on it?

**Comment by sayanh** [comment]
@joek No, the refactored events view was released recently which means the letters don't overlap now. Still, we have to check if it is acceptable or not.

**Comment by joek** [comment]
IS fixed

**Comment by brendandobbs** [comment]
There are still some issues with the UI presentation 
![events-binding](https://user-images.githubusercontent.com/5688693/45953239-5e09c900-c001-11e8-82f6-efcad05fe78c.png)

**Comment by joek** [comment]
@sayanh can you check if we can do anything about it?

**Comment by pbochynski** [comment]
It looks better now but still too ugly for presentation on big stage. Can you prioritize it, please?

**Comment by joek** [comment]
Done 
![screen shot 2018-09-28 at 13 33 01](https://user-images.githubusercontent.com/202380/46206160-6cb6ef80-c323-11e8-9eb4-4ca98a1f068b.png)
