### ISSUE TITLE
Failure when creating ServiceUsageBinding

### ISSUE THREAD

**Issue by brendandobbs** [kyma-project/kyma#1470]
**Description**

Cluster : https://console.dev-demo.cluster.kyma.cx
Namespace : contacts-app

I am trying to create a service usage binding for an Azure mysql service instance. The service usage binding is created but the environment variables are not injected into the container.

**Expected result**

After creating the SBU, we should have the environment variables (e.g. host, port) injected into the container

**Actual result**

No environment variables injected for service, error messages in logs for azure service broker and core-catalog-controller-manager, no errors in the UI console

**Steps to reproduce**

1. Create service usage binding for test-function (in contacts-app env)
2. Service usage binding is created however, note there is no secret and in the lamba editor there is no service binding listed for the function

Access the HTTP trigger for the function will log the environment variables https://test-function-contacts-app.dev-demo.cluster.kyma.cx/. Environment variables from the service instance (e.g. host, port) are missing

**Troubleshooting**

From the core-catalog-controller-manager logs 

`I1030 09:55:21.760869       1 controller_binding.go:680] ServiceBinding "contacts-app/ynuyshvnye" v10481: Binding request for ServiceBinding in-flight to Broker
I1030 09:55:21.761070       1 controller_binding.go:694] ServiceBinding "contacts-app/ynuyshvnye" v10481: Setting lastTransitionTime for condition "Ready" to 2018-10-30 09:55:21.760858092 +0000 UTC m=+567539.471811889
I1030 09:55:21.964100       1 client.go:206] handling failure responses
I1030 09:55:21.964277       1 controller_binding.go:680] ServiceBinding "contacts-app/ynuyshvnye" v10482: ServiceBroker returned failure; bind operation will not be retried: Status: 500; ErrorMessage: <nil>; Description: <nil>; ResponseError: <nil>
I1030 09:55:21.964300       1 controller_binding.go:680] ServiceBinding "contacts-app/ynuyshvnye" v10482: ServiceBroker returned failure; bind operation will not be retried: Status: 500; ErrorMessage: <nil>; Description: <nil>; ResponseError: <nil>
I1030 09:55:21.964325       1 controller_binding.go:680] ServiceBinding "contacts-app/ynuyshvnye" v10482: Starting orphan mitigation
I1030 09:55:21.964837       1 event.go:221] Event(v1.ObjectReference{Kind:"ServiceBinding", Namespace:"contacts-app", Name:"ynuyshvnye", UID:"ea31205e-dc29-11e8-9441-3e782801aefd", APIVersion:"servicecatalog.k8s.io/v1beta1", ResourceVersion:"10482", FieldPath:""}): type: 'Warning' reason: 'BindCallFailed' ServiceBroker returned failure; bind operation will not be retried: Status: 500; ErrorMessage: <nil>; Description: <nil>; ResponseError: <nil>
I1030 09:55:21.964879       1 event.go:221] Event(v1.ObjectReference{Kind:"ServiceBinding", Namespace:"contacts-app", Name:"ynuyshvnye", UID:"ea31205e-dc29-11e8-9441-3e782801aefd", APIVersion:"servicecatalog.k8s.io/v1beta1", ResourceVersion:"10482", FieldPath:""}): type: 'Warning' reason: 'ServiceBindingReturnedFailure' ServiceBroker returned failure; bind operation will not be retried: Status: 500; ErrorMessage: <nil>; Description: <nil>; ResponseError: <nil>
I1030 09:55:21.964889       1 event.go:221] Event(v1.ObjectReference{Kind:"ServiceBinding", Namespace:"contacts-app", Name:"ynuyshvnye", UID:"ea31205e-dc29-11e8-9441-3e782801aefd", APIVersion:"servicecatalog.k8s.io/v1beta1", ResourceVersion:"10482", FieldPath:""}): type: 'Warning' reason: 'ServiceBindingNeedsOrphanMitigation' Starting orphan mitigation
I1030 09:55:22.162560       1 controller_binding.go:680] ServiceBinding "contacts-app/ynuyshvnye" v10483: Orphan mitigation was completed successfully
I1030 09:55:22.438865       1 event.go:221] Event(v1.ObjectReference{Kind:"ServiceBinding", Namespace:"contacts-app", Name:"ynuyshvnye", UID:"ea31205e-dc29-11e8-9441-3e782801aefd", APIVersion:"servicecatalog.k8s.io/v1beta1", ResourceVersion:"10483", FieldPath:""}): type: 'Normal' reason: 'OrphanMitigationSuccessful' Orphan mitigation was completed successfully`

From the core-azure-broker logs 

`time="2018-10-30T09:55:21Z" level=error msg="pre-binding error: error retrieving instance by id" bindingID=ea31201d-dc29-11e8-9441-3e782801aefd error="error decrypting ciphertext: cipher: message authentication failed" instanceID=978876ef-c889-11e8-926a-f27fdb1f477b`

**Comment by brendandobbs** [comment]
Tried deleting the bindings and restarting the Azure service broker. After creating the new bindings I still see the "message authentication failed" errors in the broker logs.

I created a new MySQL instance which I am able to bind to however this is not something we can expect customers to do so we do need to investigate the issue further.

**Comment by lszymik** [comment]
We need to check what is going on.

**Comment by PK85** [comment]
@brendandobbs what was a status of the serviceBinding? Looks that Azure Broker doesnt work correctly. Reassigned to Azure Broker maintainers.

**Comment by brendandobbs** [comment]
Sorry it was quite a while ago so I don't remember the details. To fix the issue I created a new Service Instance (and therefore new database). Restarting the Azure broker didn't work. I haven't seen the issue happening again since.
