### ISSUE TITLE
Refactor SKR Test to not use compass and commerce integration

### ISSUE THREAD

**Issue by PK85** [kyma-project/kyma#14721]
**Description**

The fast integration/ SKR-test will just test provisioning, oidc updates and then deprovisioning. 

**Reasons**

We do not want to test Runtime itself. All components will be tested by relevant teams.

**ACs**

- [x] getShoot in provisioning section is throwing error. Find out why and fix. See bug issue: https://github.com/kyma-project/kyma/issues/14650
- [x] remove compass preparations from provisioning phase
- [x] remove commerceMockTest from skr-test and skr-update
- [x] made codeowners to gopher only
- [x] remove Gophers from any tests that do not belong to us (like skr-eventing)

When this thing is implemented then below tickets should be resolved:
- https://github.com/kyma-project/kyma/issues/14650
- https://github.com/kyma-project/test-infra/issues/5582
- https://github.com/kyma-project/test-infra/issues/5581
- https://github.com/kyma-project/kyma/issues/14567

**Comment by tillknuesting** [comment]
The prow jobs `pre-main-kyma-integration-k3d-central-app-connectivity-compass` and pre-main-kyma-skr-eventing for PRs that only touch tests/fast-integration/skr-test should be disabled or at least not required as eventing and compass are not used in the skr-test anymore.
