### ISSUE TITLE
Define and document API lifecycle management

### ISSUE THREAD

**Issue by varbanv** [kyma-project/kyma#14737]
**Description**

We do not have an established and documented process on what and how the API lifecycle is managed. 
We need to define and document the process and rules around the API lifecycle model.
Some questions to consider:
- Do we allow alpha/beta features on production clusters?
- How long should an API be in alpha/beta stage?
- What is the process around deprecating an API?
- What commitments do we want to make around API versions?

**Links**
[Kubernetes API changes](https://kubernetes.io/docs/concepts/overview/kubernetes-api/#api-changes)
[Kubernetes features](https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates/#feature-stages)

**Comment by a-thaler** [comment]
I think there is nothing against applying the k8s policies to Kyma. Major implications where we need to improve are:
- alpha features must be disabled by default, maybe we can introduce a dedicated profile to enable them?
- beta features are enabled by default but can be disabled. Do we then really want to enable beta features by default for the production profile as you might to apply manual migration routines on upgrades

**Comment by varbanv** [comment]
- At the moment, we cannot disable alpha features by default.
- We need to start planing the migration of alpha to stable.
- We would provide advance user notice for the changes - proposed timeline 9 months, or 3 releases?
- We strive to provide an out-of-the-box migration between versions - do we need to document the details for end-users?
-
