### ISSUE TITLE
Argo workflow hangs forever with Istio-proxy

### ISSUE THREAD

**Issue by licheng5625** [kyma-project/kyma#14749]
**Description**
We are testing with Argo in Kyma environment(AWS).
Kyma deploys a istio-proxy container inside every pod. Argo workflow creates pod. The pod should be destroyed when the task is finished. I observed that the "main" container is finished, but the istio-proxy container keeps hanging there. Argo is thinking the task has not finished yet.

 
**Expected result**

Workflow (pod) should be destroyed when the argo task finished. 

**Actual result**

Argo workflow keeps hanging forever.
![image](https://user-images.githubusercontent.com/10073591/177314958-d34efd93-f6e2-4e24-99aa-967c27b6e0cb.png)

From the image, you can see the main container has been closed, only istio-proxy is still hanging there and blocks the argo process.
 
**Steps to reproduce**

1. install argo https://argoproj.github.io/argo-workflows/quick-start/
2. deploy example https://github.com/argoproj/argo-workflows/blob/4e450e250168e6b4d51a126b784e90b11a0162bc/examples/steps.yaml

 how to deploy :  https://argoproj.github.io/argo-workflows/walk-through/argo-cli/
 
**Troubleshooting**

 https://github.com/argoproj/argo-workflows/issues/7273  not sure if this is the same issue.

**Comment by strekm** [comment]
please try to reproduce it

**Comment by videlov** [comment]
Did update the upstream ticket: https://github.com/argoproj/argo-workflows/issues/7273#issuecomment-1658359969

**Comment by videlov** [comment]
another idea to workaround is to present Istio proxy sidecar by adding a label to the step pod:
https://github.com/argoproj/argo-workflows/blob/4e450e250168e6b4d51a126b784e90b11a0162bc/examples/steps.yaml#L25

just add:
```
metadata:
  labels:
    sidecar.istio.io/inject: "false"
--



```
