### ISSUE TITLE
HA Evaluation of JetStream on multi-zone K8s cluster

### ISSUE THREAD

**Issue by mfaizanse** [kyma-project/kyma#14758]
In this [issue](https://github.com/kyma-project/kyma/issues/14451), we did the HA evaluation of JetStream but on a K8s cluster on a single-zone. 

We need to see how the pvc will work if the JetStream is deployed on multi-zone k8s cluster and one of the node crashes? Would the PVC will only be able to mounted to JetStream Pod deployed in the same zone?

**Comment by muralov** [comment]
closing as it is completed with [15085](https://github.com/kyma-project/kyma/issues/15085)
