### ISSUE TITLE
Kubeless test is failling with error `503 Service unaivalable`

### ISSUE THREAD

**Issue by rakesh-garimella** [kyma-project/kyma#1476]
**Description**

Kubeless test fails with error `503 service unavailable`. This happens sporadically. We need more info why this is happening. 

We need to check if the pod was in stage `running` also logs from the pods should be helpful. As pointed by Jakub we should print logs both from the container with logic and from the istio-proxy (envoy) container in the pod. Check if service is created and exists. Also print the response body.

**Troubleshooting**
```
12:15:27 time="2018-10-30T11:01:56Z" level=info msg="Skipped: all changes has been already applied to the API (both specs are equal)."
12:15:27 time="2018-10-30T11:01:56Z" level=info msg="Trying to process next item..."
12:15:27 
12:15:27 2018/10/30 11:04:19 [test-hello] Timeout: Getting Virtual Service: 'test-hello' and result is: NAME         AGE
12:15:27 test-hello   2m
12:15:27 2018/10/30 11:04:19 [test-hello] Timeout: Check http Get one last time
12:15:27 2018/10/30 11:04:19 [test-hello] Timeout: Response is: &{503 Service Unavailable 503 HTTP/1.1 1 1 map[Date:[Tue, 30 Oct 2018 11:04:19 GMT] Server:[envoy] Content-Length:[57] Content-Type:[text/plain]] 0xc420864d80 57 [] false false map[] 0xc4207fb600 0xc42081c6e0}
```

The api and the virtual service was created
```
12:15:27 2018/10/30 11:03:47 Function test-event works correctly
12:15:27 2018/10/30 11:04:17 [test-hello] Timeout: Check if Virtual Service has been created
12:15:27 2018/10/30 11:04:17 Function pods status:
12:15:27 NAME                         READY     STATUS    RESTARTS   AGE
12:15:27 test-hello-9dcb8c4c9-d2k7r   2/2       Running   0          2m
12:15:27 
12:15:27 2018/10/30 11:04:17 API List:
12:15:27 NAME         AGE
12:15:27 test-hello   2m
```

**Comment by rakesh-garimella** [comment]
After discussion with @piotrmsc   this is more issue about docker in docker setup we are running on Jenkins. There is no issue with Kubeless and Istio here.

**Comment by piotrmsc** [comment]
Tests on a minikube (not DiD) are passing, on a cluster test are passing as well. Moreover, stability checker on a nightly cluster executes those tests in a loop and they pass as well. Mentioned failures happened on CI when all slaves where running builds, with additional waiting in a queue so jenkins was 'under pressure'. It has an impact on istio, kubeless or any other component in the Kyma. 

Here we observed lack of logs in the sidecar connected with 503, reasons for 503 can be many, but basically, it indicates that envoy was not able to connect to the app or another envoy. In kubeless tests we have requests being made via ingress controller which is itself is an envoy. So it could be the envoy of the lambda pod was not ready. It could be even k8s apiserver also under pressure, but if the docker running minikube has performance issues it can affect any component actually. 

What could be checked is what will happen if we limit number of slaves on the CI to give a little bit more resources for other slaves running builds.

**Comment by Demonsthere** [comment]
Hi,
I was in charge of creating the k8s infrastructure on which your CI/CI Jenkins pipelines are setup. In my opinion, your problems may result from the heavily nested network stack: physical blades, ceph, vms, kubernetes, dind, minikube and isitio. 
Each layers creates some overhead, which will over time converge into a timeout. Additionally, as @piotrmsc mentioned, you are not the only ones that are using the cluster. 
In my opinion, as this issue happens sporadically we can assume that the CI/CD clusters performance and load is the reason for such nondeterministic behaviour.

**Comment by joek** [comment]
We disabled the test on minikube as it is probably just a timing issue. For cluster setups it is not an problem.
