### ISSUE TITLE
Add a possibility to disable URL decoding in Application Gateway

### ISSUE THREAD

**Issue by janmedrek** [kyma-project/kyma#14783]
**Description**

There should be a way to enable/disable URL decoding in the Application Gateway. Right now - the URL is always decoded so there is no possibility to pass on encoded path segments (i.e. `curl http://central-application-gateway.kyma-system:8080/application/service/path/segment/abc%2Fsome%2Fvalue%2F`)

**Reasons**

Sometimes the user would like to have the undecoded part sent in the proxied request via Application Gateway.

**Acceptance**
- [ ] There is a switch added in Application CR that enables/disables URL decoding in Application Gateway for the whole Application
- [ ] By default, decoding is enabled (behavior used so far)
- [ ] Application Gateway passes the request without decoding the whole URL when decoding is disabled

**Comment by janmedrek** [comment]
I have used the https://webhook.site/ to investigate the issue, the single-encoded path segments are decoded but there is no decoding for the double-encoded segments (i.e. `/%252Fabc%252Fdef`).

My guess would be that somehow URL parsing in Go automatically decodes the request's path: https://github.com/kyma-project/kyma/blob/9ec2d8f628c9f7c141c89fe276525c7772da4fcd/components/central-application-gateway/internal/proxy/reverseproxy.go#L25

**Comment by VOID404** [comment]
Solved by #16577
