### ISSUE TITLE
Feature requests for Kyma eventing custom metrics

### ISSUE THREAD

**Issue by vvxxvvxx** [kyma-project/kyma#14782]
**Description**

We are trying to monitor the requests latency and response codes for eventing. As `eventing-nats` has no istio injected, we can achieve it using the eventing custom metrics. So we are raising this issue ticket to ask for some features added for some custom metrics of eventing.

**eventing-publisher-proxy**

1. histogram metric `event_publish_to_messaging_server_latency` (bucket/count/sum)

(1) Add label `destination_service` to show the destination of requests from `eventing-publisher-proxy`. The destination is to indicate if the requests is to nats or to sap event mesh.

In istio metric `istio_requests_total`, it includes the destination info as below (for reference). `destination_service` is sufficient for us to use.
```
destination_service="api-mssql-go.default.svc.cluster.local", destination_service_name="api-mssql-go", destination_service_namespace="default", destination_workload="api-mssql-go", destination_workload_namespace="default"
```

(2) Make all requests fall in the histogram bucket.

We checked the istio histogram metric, it will capture all response codes and drop them into the corresponding histogram bucket. Last time in the call with Raymond, he checked, when nats server returned 502 response code, it wasn't captured in this current histogram metric.

Take istio metric `istio_requests_total` for example, as the metric shown below, it got response codes 200 for 3 times, 304 once, 500 for 4 times. then in the histogram metric `istio_request_duration_milliseconds_bucket`, all requests will be covered.
![image](https://media.github.tools.sap/user/22328/files/4d40cdf1-777c-47ab-8b2f-4a3aaea9be98)
  
istio_request_duration_milliseconds_bucket{destination_service="get-order.default.svc.cluster.local", reporter="destination"}
(only paste le=Inf and le=1000, same for the others)
![image](https://media.github.tools.sap/user/22328/files/60f29b58-839d-4f35-82a6-3869062f2b61)
![image](https://media.github.tools.sap/user/22328/files/cbdd6164-9fee-4a29-b60f-f039c186d4c9)
  

(3) Is that possible to calculate le by millisecond instead of second?

2. Create a counter metric counting the requests from eventing-publisher-proxy to nats server. could refer to istio metric `istio_requests_total` as below. The labels should have `destination_service`, `response_code` included.
```
istio_requests_total{connection_security_policy="unknown", destination_cluster="Kubernetes", destination_service="eventing-event-publisher-proxy.kyma-system.svc.cluster.local", destination_service_name="eventing-event-publisher-proxy", destination_service_namespace="kyma-system", destination_workload="eventing-publisher-proxy", destination_workload_namespace="kyma-system", job="istio-system/envoy-stats/0", reporter="source", response_code="200", service="monitoring-prometheus-istio-server", source_cluster="Kubernetes", source_workload="central-application-connectivity-validator", source_workload_namespace="kyma-system"}
```

current custom metric `event_type_published` seems only counting the total number of event types published, not for requests.

**Reasons**

**Attachments**

**Comment by raypinto** [comment]
Tasks:
- [ ] Add label `destination_service` to `event_publish_to_messaging_server_latency` metric.
- [ ] Add label `response_code` (with value 200, 304, 500 etc.) to `event_publish_to_messaging_server_latency` metric.
- [ ] Calculate latency by millisecond instead of second for metric `event_publish_to_messaging_server_latency` 
- [ ] Create a new Counter metric to count the requests with a label `status code` of the response. Also include the `destination service` as a label.
