### ISSUE TITLE
domain name for kyma installation

### ISSUE THREAD

**Issue by sachitaggarwal** [kyma-project/kyma#1479]
**Description**
Hi

Why is it necessary to have domain name registered for kyma installation ? Are there any workarounds possible ?

Best Regards
Sachit

**Comment by pbochynski** [comment]
It is not mandatory to hava domain name registered. You can use domain name you don't own. This way local installation works - it uses kyma.local domain. What you need is:
- domain name
- SSL wildcard certificate for that domain
- DNS record pointing to the IP of your ingress gateway controller
With the registered domain you can get trusted SSL certificate and you can manage DNS records. You can get domain for free using sites like freenom.com.

But if you still don't want to register your own domain you can install your kyma in the similar way as local installation works:
- use domain of your choice (e.g. example.com)
- generate self signed wildcard certificate for it
- create entry in /etc/hosts that points load balancer IP (ingress gateway) to all subdomains used in kyma (see: https://github.com/kyma-project/kyma/blob/a84b8f6ec9b70e4c23aaf355d24b24d105b22bc7/installation/scripts/minikube.sh#L189)

The workaround above has 2 big issues:
1. It works only for your local machine (or machines with /etc/hosts entry as yours)
2. You can't get trusted SSL certificate so you need to create exception in your system for generated self signed cert.

So it is still more convenient to have domain registered. Many people raise questions/problems like you, and we think about using public DNS like xip.io to have quick installation without managing DNS. So you can expect some improvements in this area.
