### ISSUE TITLE
Istio sidecars failing on Mac M1 

### ISSUE THREAD

**Issue by janmedrek** [kyma-project/kyma#14797]
**Description**

Installation of Kyma fails on Mac M1 chips as Istio's sidecars init containers are not able to run successfully. After removing the sidecar injection for the components that failed previously (Application Connector, Kiali, ...) those get up.

**Expected result**

Components that have Istio sidecars injected run on local Mac M1 installation.

**Actual result**

Istio sidecars' init containers fail:
```
2022-07-13T08:52:18.156585Z	info	Istio iptables environment:
ENVOY_PORT=
INBOUND_CAPTURE_PORT=
ISTIO_INBOUND_INTERCEPTION_MODE=
ISTIO_INBOUND_TPROXY_ROUTE_TABLE=
ISTIO_INBOUND_PORTS=
ISTIO_OUTBOUND_PORTS=
ISTIO_LOCAL_EXCLUDE_PORTS=
ISTIO_EXCLUDE_INTERFACES=
ISTIO_SERVICE_CIDR=
ISTIO_SERVICE_EXCLUDE_CIDR=
ISTIO_META_DNS_CAPTURE=
INVALID_DROP=

2022-07-13T08:52:18.159404Z	info	Istio iptables variables:
PROXY_PORT=15001
PROXY_INBOUND_CAPTURE_PORT=15006
PROXY_TUNNEL_PORT=15008
PROXY_UID=1337
PROXY_GID=1337
INBOUND_INTERCEPTION_MODE=REDIRECT
INBOUND_TPROXY_MARK=1337
INBOUND_TPROXY_ROUTE_TABLE=133
INBOUND_PORTS_INCLUDE=*
INBOUND_PORTS_EXCLUDE=15090,15021,15020
OUTBOUND_OWNER_GROUPS_INCLUDE=*
OUTBOUND_OWNER_GROUPS_EXCLUDE=
OUTBOUND_IP_RANGES_INCLUDE=*
OUTBOUND_IP_RANGES_EXCLUDE=
OUTBOUND_PORTS_INCLUDE=
OUTBOUND_PORTS_EXCLUDE=
KUBE_VIRT_INTERFACES=
ENABLE_INBOUND_IPV6=false
DNS_CAPTURE=false
DROP_INVALID=false
CAPTURE_ALL_DNS=false
DNS_SERVERS=[],[]
OUTPUT_PATH=
NETWORK_NAMESPACE=
CNI_MODE=false
EXCLUDE_INTERFACES=

2022-07-13T08:52:18.162283Z	info	Writing following contents to rules file: /tmp/iptables-rules-1657702338161589501.txt1460946964
* nat
-N ISTIO_INBOUND
-N ISTIO_REDIRECT
-N ISTIO_IN_REDIRECT
-N ISTIO_OUTPUT
-A ISTIO_INBOUND -p tcp --dport 15008 -j RETURN
-A ISTIO_REDIRECT -p tcp -j REDIRECT --to-ports 15001
-A ISTIO_IN_REDIRECT -p tcp -j REDIRECT --to-ports 15006
-A PREROUTING -p tcp -j ISTIO_INBOUND
-A ISTIO_INBOUND -p tcp --dport 15090 -j RETURN
-A ISTIO_INBOUND -p tcp --dport 15021 -j RETURN
-A ISTIO_INBOUND -p tcp --dport 15020 -j RETURN
-A ISTIO_INBOUND -p tcp -j ISTIO_IN_REDIRECT
-A OUTPUT -p tcp -j ISTIO_OUTPUT
-A ISTIO_OUTPUT -o lo -s 127.0.0.6/32 -j RETURN
-A ISTIO_OUTPUT -o lo ! -d 127.0.0.1/32 -m owner --uid-owner 1337 -j ISTIO_IN_REDIRECT
-A ISTIO_OUTPUT -o lo -m owner ! --uid-owner 1337 -j RETURN
-A ISTIO_OUTPUT -m owner --uid-owner 1337 -j RETURN
-A ISTIO_OUTPUT -o lo ! -d 127.0.0.1/32 -m owner --gid-owner 1337 -j ISTIO_IN_REDIRECT
-A ISTIO_OUTPUT -o lo -m owner ! --gid-owner 1337 -j RETURN
-A ISTIO_OUTPUT -m owner --gid-owner 1337 -j RETURN
-A ISTIO_OUTPUT -d 127.0.0.1/32 -j RETURN
-A ISTIO_OUTPUT -j ISTIO_REDIRECT
COMMIT
2022-07-13T08:52:18.162539Z	info	Running command: iptables-restore --noflush /tmp/iptables-rules-1657702338161589501.txt1460946964
2022-07-13T08:52:18.350869Z	error	Command error output: xtables parameter problem: iptables-restore: unable to initialize table 'nat'

Error occurred at line: 1
Try `iptables-restore -h' or 'iptables-restore --help' for more information.
2022-07-13T08:52:18.351500Z	error	Failed to execute: iptables-restore --noflush /tmp/iptables-rules-1657702338161589501.txt1460946964, exit status 2
```

**Steps to reproduce**

- Install Kyma locally on a Mac M1 machine.
- Check failed pods init-container logs (i.e. Kiali)
- Remove sidecar injection
- Pod gets up

**Comment by dariusztutaj** [comment]
Istio is not officialy supported on cluster on M1 - https://github.com/istio/istio/issues/36762

As workaround you can use images in repository: ghcr.io/resf/istio

```
➜  istio git:(main) kyma deploy --value istio.global.images.istio_pilot.containerRegistryPath=ghcr.io --value istio.global.images.istio_pilot.directory=resf/istio 
- No previous Kyma version found
- Using Kyma from the workspace directory: /Users/I552063/.kyma/sources/2.4.2
- Initial setup
- Component 'CRDs' deployed
- Component 'certificates' deployed
- Component 'cluster-essentials' deployed
- Component 'istio' deployed
- Component 'api-gateway' deployed
- Component 'serverless' deployed
- Component 'eventing' deployed
- Component 'ory' deployed
- Component 'istio-resources' deployed
- Component 'tracing' deployed
- Component 'monitoring' deployed
- Component 'logging' deployed
- Component 'cluster-users' deployed
- Component 'application-connector' deployed
- Component 'kiali' deployed
- Kyma deployed successfully!

Kyma is installed in version:	2.4.2
Kyma installation took:		0 hours 5 minutes

Happy Kyma-ing! :)
```

**Comment by janmedrek** [comment]
@strekm do we have something in the docu about this issue then? I believe we should at least indicate that there is no support for Mac M1s if we won't support it.

**Comment by triffer** [comment]
**Analysis of current situation**
The Docker images from istio support multiple platforms, e.g. linux/arm64, linux/amd64.
Based on the platform a different binary is built into the image.

We use image-syncer in test-infra to copy external images into our registry. During this process, image-syncer pulls the image. That pull uses the platform of the machine on which the image-syncer is running. This means that we only push the image for the linux/amd64 platform into our registry. If we deploy Kyma locally, the Linux/amd64 image will cause problems for the istio-proxy on M1.

Istio/pilot image supported platforms:
```
Image: istio/pilot:1.15.3-distroless (digest: sha256:0307bce43d32c867d7877ac49b2d456799d7fc69186f9c6292ffa93361bd929b)
 * Manifest List: Yes (Image type: application/vnd.docker.distribution.manifest.list.v2+json)
 * Supported platforms:
   - linux/arm64
   - linux/amd64
```
eu.gcr.io/kyma-project/external/istio/pilot supported platforms:
```
Image: eu.gcr.io/kyma-project/external/istio/pilot:1.15.3-distroless (digest: sha256:b87ae0a537d3cae1c8dfa1bac0b10eb66002e6dc74a9771e57ad2f9e9e837078)
 * Manifest List: No (Image type: application/vnd.docker.distribution.manifest.v2+json)
 * Supports: linux/amd64
```

**Why does it work locally with official image?**
If we now replace the external image (`eu.gcr.io/kyma-project/external/istio/...`) with the official istio image in the config, the image from DockerHub is pulled during the deployment of Kyma.
This pulls the correct image for local platform for Mac M1 (linux/arm64) and therefore causes no problems.

**How can we solve it?**
If image-syncer supports the sync of multiple platforms per images we should be able to solve this.

**Comment by tobiscr** [comment]
Thanks to @Ressetkk investigations, we can confirm that the image syncer is currently not supporting the download of AMR architectures. This was not required in the past and is currently a missing feature.

We will take this request into our backlog and groom how to solve it (either by extending the syncer to support multiple features or by offering a more mature tooling).

**Comment by tobiscr** [comment]
Will be followed up on Neighbors side in issue https://github.com/kyma-project/test-infra/issues/6388

**Comment by VOID404** [comment]
https://github.com/kyma-project/test-infra/issues/6388 is closed, Kyma installs and runs correctly on M1 with default modules, everything in `istio-system` and `kyma-system` is running, nothing is crashing
