### ISSUE TITLE
Show deployment status for lambda functions

### ISSUE THREAD

**Issue by brendandobbs** [kyma-project/kyma#148]
There is no indication on the lambda functions page when a function/pod crashes and fails to deploy

A status column similar to the pods list page would help here.

**Comment by joek** [comment]
We have already a story to improve function status.

**Comment by joek** [comment]
- Add status logic to the UI
- Have a Description of the state (Crash, Running, Deployment)
- Find right metrics 
- Show green (running), yellow (running with issues), red (nothing works or deploying), pink (lilit is logged in) status.

**Comment by joek** [comment]
Won't fix for kubeless. The implementation is pretty tricky and should be solved using knative.
