### ISSUE TITLE
Add a troubleshooting guide for (central) Application Gateway

### ISSUE THREAD

**Issue by majakurcius** [kyma-project/kyma#14807]
**Description**

Add a troubleshooting guide for central Application Gateway. 
This is a follow-up to #14740.

Consider describing these: 
- [ ] Check if the Pod is up and running
- [ ] Check the logs
- [ ] Check the URLs in Application
- [ ] Check if the Secrets exist
  - [ ] Check if the Secrets contain proper credentials
- [ ] Check the API server

**Related issues**
#11047 
#12353 
#14740

**Comment by Disper** [comment]
Closing as we will create troubleshooting guide for [Application Connector Module](https://github.com/kyma-project/application-connector-manager/issues/20)
