### ISSUE TITLE
Support reusing the kyma-gateway for custom domains

### ISSUE THREAD

**Issue by abbi-gaurav** [kyma-project/kyma#14849]
### Description

With kyma 2.0, customers can go ahead and create custom domains. However, for this, they need to created their own Istio gateway. This causes unnecessary overhead on customer's part as they need to understand the details of Istio gateway. We can simplify the workflow by letting customers reuse the existing gateway.

**Comment by strekm** [comment]
Kyma default gateway is managed by certificates component. any changes done to gateway will be wiped out to default changes. Also i think that own gateway in case of custom domain brings our customers more configuration flexibility. we provide our customers with tutorials on basic configuration. Creating "wildcard gateway" also enable reusing it in APIRules. closing as won't fix
