### ISSUE TITLE
Align status codes for errors in Application Gateway

### ISSUE THREAD

**Issue by akgalwas** [kyma-project/kyma#14842]
**Description**
As a general rule REST service should return `5xx` for errors that occurred on the server side and `4xx` for errors on the client side. Error code should be as informative as possible. There is a number of cases that needs to be corrected.  

**Expected result**
There are the following error cases that needs to be fixed to adhere to HTTP errors conventions:
- when application specified in path doesn't exist Application Gateway must return `404 Not Found` 
- when application, service or entry for Compass use case is not specified in the path, Application Gateway must return `400 Bad Request `
- when call to target API timeouts Application Gateway must return `504 Gateway Timeout` 

**Actual result**
There are the following error cases that doesn't adhere to common HTTP error conventions:
- when call to target API timeouts Application Gateway returns `503 Service Unavailable` 
- when application specified in path doesn't exist Application Gateway returns '500 Internal Server Error' 
- when application, service or entry for Compass use case is not specified in the path, Application Gateway returns `500 Internal Server error `

**Steps to reproduce**

The above cases are tested in Application Gateway component integration tests (see [missing resources errors handling](https://github.com/kyma-project/kyma/blob/main/tests/components/application-connector/resources/charts/gateway-test/templates/applications/missing-resources-error-handling.yml) and [path related errors handling](https://github.com/kyma-project/kyma/blob/main/tests/components/application-connector/resources/charts/gateway-test/templates/applications/path-related-error-handling.yml))

**Comment by mvshao** [comment]
**Workplan**

- [ ] align status code when the application specified in the path doesn't exist 
  - [ ] make appropriate corrections to the Application Gateway test code
  
- [ ] align status code when application, service or entry for Compass use case is not specified in the path
  - [ ] make appropriate corrections to the Application Gateway test code
  
- [ ] align status code when call to target API timeouts
  - [ ] make appropriate corrections to the Application Gateway test code

**Comment by mvshao** [comment]
It's done. I'm closing this issue.
