### ISSUE TITLE
New Application Connectivity tests - Test suite for Application Connectivity Validator

### ISSUE THREAD

**Issue by franpog859** [kyma-project/kyma#14888]
**Description**

We need an integration test of (Central) Application Connectivity Validator. The test should be implemented **with a similar structure** to [the Application Gateway test](https://github.com/kyma-project/kyma/pull/14743). It should be fast, simple, and easy to maintain. If something breaks on some end-to-end pipeline or some environment, this test should clearly tell if there is a problem with the Validator or not

 **Acceptance criteria**
 
- [ ] A test checking Connectivity Validator functionality is implemented (consider using a static TLS certificate and just sending a request there)
- [ ] The test takes minimal possible execution time
- [ ] The test is considered as easy to maintain and has a similar structure to the Application Gateway tests
- [ ] The test runs on the Prow pipeline
- [ ] The test is runnable locally/ on a custom cluster

**Attachments**

epic issue - https://github.com/kyma-project/kyma/issues/13977
PR with pipelines - https://github.com/kyma-project/test-infra/pull/5563
PR with new test - https://github.com/kyma-project/kyma/pull/14912/files

**Comment by franpog859** [comment]
Work plan:
- [ ] Analyze the (Central) Application Connectivity Validator duties as described in [the doc](https://kyma-project.io/docs/kyma/latest/05-technical-reference/00-architecture/ac-01-application-connector-components/#application-connectivity-validator) and [the readme](https://github.com/kyma-project/kyma/tree/main/components/central-application-connectivity-validator), and prepare a task-oriented work plan like [this one](https://github.com/kyma-project/kyma/issues/14654#issuecomment-1177186152) - **In progress** - @franpog859 @akgalwas

**Comment by koala7659** [comment]
Project design:

- Kyma cluster installed in k3d mode
- AppConnectivityValidator exists in kyma-system namespace
- Deployed TestPod, and HttpBin service in separate testing namespace 
- AppConnectivityValidator patched to proxy requests to HttpBin service (simulating enpoints of event-publisher-proxy)
- Application CR deployed to Kyma
- TestPod sending HTTP prepared requests with certificate details to AppConnectivityValidator pod
- Check return code

**Comment by koala7659** [comment]
PR with new test - https://github.com/kyma-project/kyma/pull/14912/files
