### ISSUE TITLE
Add documentation explaining how to configure APIRule exposing multiple services

### ISSUE THREAD

**Issue by strekm** [kyma-project/kyma#14887]
**Description**

Create tutorial under [API Exposure tutorials](https://kyma-project.io/docs/kyma/latest/03-tutorials/00-api-exposure/) explaining how user can expose multiple services under same host. Tutorial should describe 2 scenarios:
- using different services per path
- using service defined on root and different service in path

ACs:
- [x] Tutorial (an `.md` file) with complete steps on how to expose and secure a deployed workload
- [x] Location: `kyma` respository `kyma-project/kyma/tree/main/docs/03-tutorials/00-api-exposure`
- [x] When you create the new file, stick to the following naming convention: `{COMPONENT_ABBRV}-{NUMBER_PER_COMPONENT}-{FILE_NAME}.md}`, and for example name it `apix-04-expose-multiple-services.md` 
- [x] The tutorial should be a follow-up of the [Create a workload](https://deploy-preview-13513--kyma-project-docs-preview.netlify.app/docs/kyma/preview/03-tutorials/00-api-exposure/apix-02-create-workload/) tutorial
- [x] Add links to the new tutorial in the **Next steps** section of [Create a workload](https://deploy-preview-13513--kyma-project-docs-preview.netlify.app/docs/kyma/preview/03-tutorials/00-api-exposure/apix-02-create-workload/#next-steps)
- [x] Add a link to the document to the [Useful links](https://deploy-preview-13513--kyma-project-docs-preview.netlify.app/docs/kyma/preview/01-overview/main-areas/api-exposure/apix-02-useful-links/) document in the **Overview -> Main areas -> API Exposure -> Useful links**
- [x] Use the [tutorial template](https://github.com/kyma-project/community/blob/main/templates/resources/tutorial.md)
- [x] Test the complete flow

**Area**

* API Exposure

**Reasons**

Reflecting changes introduced by new version of APIRule CR

**Assignees**

@kyma-project/technical-writers

**Attachments**

part of: https://github.com/kyma-project/kyma/issues/9936, see also: https://github.com/kyma-incubator/api-gateway/issues/140

**Comment by SamehMKhattab** [comment]
PR:
https://github.com/kyma-project/kyma/pull/15213
