### ISSUE TITLE
Improve local development with admin user

### ISSUE THREAD

**Issue by derberg** [kyma-project/kyma#1488]
**Description**

- for local installation keep static dummy password
- would be awesome to display it in the UI or autologin on local

**Reasons**

admin static user is now secured and the password is always unique. Problem is that it is also secured for local and it is complicating dev flow, with each installation you always need to check the new password.

**Comment by piotrmsc** [comment]
Static password cannot stay but we can improve UX in other way.
We should allow users to specify their own password during the installation phase, if not specified then generate it as we do now.
In such case we can add a flag ie. `-p` to startup script which will pass given string to the overrides, then dex patch can use this values from helm. 
Input password parameter should be base64 encoded as later on dex patch bcrypts it.

**Comment by tomekpapiernik** [comment]
Documentation must be updated to indicate that local deployments can have their admin password set by the user.

**Comment by kfurgol** [comment]
@kfurgol  - assigne for bash modifications
