### ISSUE TITLE
Upgrade prometheus-operator 

### ISSUE THREAD

**Issue by johgoe** [kyma-project/kyma#14896]
**Description**

Upgrade prometheus-operator to v0.58.0 or newer

**Reasons**

With a istio enabled scrape config there can be problems with http2

https://github.com/prometheus-operator/prometheus-operator/releases/tag/v0.58.0 has a new feature to disable http2 in the servicemonitor for this services

**Comment by a-thaler** [comment]
prometheus-operator, prometheus, prometheus-configmap-reloader and kube-state-metrics have newer versions available.
With that we should update the main monitoring chart, the kube-state-metrics subchart and the prometheus-istio chart
