### ISSUE TITLE
Fix defaulting and validation around the two modes for function scaling ( default vs. external scaler )

### ISSUE THREAD

**Issue by kwiatekus** [kyma-project/kyma#14900]
**Description**

Fix the validation, defaulting logic so that it conforms with the following case description.
Write  tests that validates the scenarios.

1) 
_when_ 
    user defines `spec.scaleConfig.minReplicas` and `spec.scaleConfig.maxReplicas` (higher than min)
_than_
    default ( serverless managed  Horizontal Pod Autoscaler kicks in to scale the function)

2)
_when_ 
    user defines `spec.scaleConfig.minReplicas` and `spec.scaleConfig.maxReplicas` (values equal or max lower than min)
_than_
    validation webhook rejects such configuration

3) 
_when_
  user leaves `spec.scaleConfig` empty 
_then_
  the default HPA scaler would not kick in

4) 
_when_
  user defines `spec.replicas` with X 
_then_
  the deployment has X replicas

5) 
_when_
  user leaves both `spec.replicas` and `spec.scaleConfig` empty 
_then_
  the defaulting webhook should fill in spec.replicas=1

**Reason**
Function CR support scale subresource that would enable scaling functions via external scalers.
Additionally it still offers the way to configure default scaling ( via serverless managed HPA ) based on cpu consumption
Those configuration modes should be tested

**Related**
https://github.com/kyma-project/kyma/issues/15291
https://github.com/kyma-project/kyma/issues/15292

**Comment by kwiatekus** [comment]
Investigate whether  function controller managed HPA scaling the function would simplify the logic ( p 3 ).

**Comment by dbadura** [comment]
I would add case when user to `max` or `min` replicas. 
In this case we should reject such configuration.

**Comment by kwiatekus** [comment]
Works like described since https://github.com/kyma-project/kyma/pull/15576
