### ISSUE TITLE
Test Horizontal Pod Autoscaler on Azure and minikube

### ISSUE THREAD

**Issue by joek** [kyma-project/kyma#1490]
As a kyma user I need to rely on the HPA for functions.

AC:
- Implement Performance tests with 200 parallel requests during 30 minutes and check how the autoscaler is working
- Run tests on minikube (maybe lower requirements)
- Run tests on Azure

GKE: Manual execution
Azure: Automated
Minikube: Manual execution

**Comment by sayanh** [comment]
Executing 1600 calls per goroutine to trigger horizontal pod autoscaling. As discussed, GKE and Minikube are out of scope for this issue.
