### ISSUE TITLE
Automated test for access logs feature

### ISSUE THREAD

**Issue by a-thaler** [kyma-project/kyma#14925]
**Description**
With 1.14 upgrade the istioAccessLog feature got spoiled and was not working anymore as expected. An automated test should assure that this feature works as expected

**Criterias**
Have an automated test which:
- deploys an istio telemetry resource selecting the loki pod in kyma-system namespace
- queries for istio-proxy logs of the loki pod and checks that they arrive in a structured format

**Attachments**
https://github.com/kyma-project/kyma/issues/14909

**Comment by dennis-ge** [comment]
Added a test in the fast integration logging scenario which deploys a istio telmetry resource, then queries logs and checks that they arrive in json format an have specific fields, e.g. `response_code`.
