### ISSUE TITLE
Investigate Stream Setup limitations [TB: 3 days]

### ISSUE THREAD

**Issue by k15r** [kyma-project/kyma#14929]
**Erroneous setup:**

On a NATS Jetstream enabled cluster:
- Setup two subscriptions
    - 1 subscription receiving event type a
    - 1 subscription receiving event type b
- send events with highest possible rate to for both event types. (Use production profile)
- shutdown 1 subscriber, but keep the corresponding subscription.

**Expected result:**

- Verify: Events for disabled subscriber will not block/effect event delivery even for the other subscriber.
- Check Grafana dashboards to verify streams filling up with events and delivery rate of 'good' events will not decrease.

With this setup:
- [ ] If it happens, then investigate the exact reason for this behaviour. (if disabled subscriber is blocking/effecting event delivery for the other subscriber).
- [ ] Document known issue in kyma documentation
- [ ] Provide solution (if possible within current streams setup)

**Comment by mfaizanse** [comment]
TB: 3 days

**Comment by mfaizanse** [comment]
Cloud Provider: Azure
2 subscriptions with single event type.
EPS: 400 per Event Type (Total 800 EPS)

Around 15:40H, one of the sink was made to throw errors.

![image](https://user-images.githubusercontent.com/9897945/187217425-19696a49-356a-466a-8c3a-8f03125db841.png)

![image](https://user-images.githubusercontent.com/9897945/187217828-494afdc4-bee2-4cfd-965c-8261550d2fce.png)

**Comment by mfaizanse** [comment]
![image](https://user-images.githubusercontent.com/9897945/187367448-f0f6f1d1-74ce-4a92-b41c-478b8f0eecaa.png)

![image](https://user-images.githubusercontent.com/9897945/187367534-169bebae-38ca-4f39-a2b7-1b09803257c7.png)

**Comment by mfaizanse** [comment]
**Conclusion:**
The Events for disabled subscriber is not blocking/effecting event delivery even for the other subscriber. Delivery rate of 'good' events is not effected.
