### ISSUE TITLE
Allow using `nats server info`

### ISSUE THREAD

**Issue by k15r** [kyma-project/kyma#14963]
## Description

As an administrator of eventing based on NATS i want to be able to run `nats server info` on my NATS cluster to get as much information about my server as possible

## Acceptance
- [x] `nats server info` works
-> #15274 
- [x] documentation exists
-> #15381
---
when the above is active, NATS server will [fail after getting upgraded](https://github.com/kyma-project/kyma/issues/15476).
- [ ] reenable the NATS server account.
- [ ] fix the problem that occurs during the upgrade of NATS server.
- [ ] find out why this was not caught by the prow upgrade jobs.
- [ ] do we need an additional upgrade job for the NATS server?
-> create a new ticket for it.

**Comment by friedrichwilken** [comment]
One possible solution to this might be to simply adding these two lines to the configmap of the nats-server

```yaml
     accounts:{"SYS":{"users":[{"pass":"admin","user":"admin"}]}}
     system_account: SYS
```
here:
```yaml
 data:
   nats.conf: |
   <add here>
```
after the `config-reloader` gets triggered
```sh
2022/08/17 07:36:55 changed config; file="/etc/nats-config/nats.conf" existing=true total-files=1
2022/08/17 07:36:55 Sending signal 'hangup' to server to reload configuration due to: /etc/nats-config/..2022_08_17_07_36_55.271669194
```
one can run 
```
nats --user admin --password admin server info
```
 and other commands that require `system account privileges`

**Comment by friedrichwilken** [comment]
[this](https://github.com/kyma-project/kyma/pull/15274) might be a better solution.

**Comment by mfaizanse** [comment]
Reverted the changes because of the upgrade ([issue](https://github.com/kyma-project/kyma/issues/15476)).

Reopening this issue as we need to investigate the problem and provide a fix.

**Comment by k15r** [comment]
Hint from the linked issue:
> Seems like the [PR](https://github.com/kyma-project/kyma/pull/15274/files) to add user account to NATS have a side-effect with the upgrade. According to NATS support, if the user account is changed during the upgrade then it could be the issue. From the intitial check, it seems that the secret eventing-nats-secret is getting updated during the kyma upgrade.
