### ISSUE TITLE
Verify NATS health checks

### ISSUE THREAD

**Issue by k15r** [kyma-project/kyma#14964]
## Descriptions

in a recent incident the NATS Server itself reported as healthy (via its health checks). Unfortunately only the Core Nats control plane worked properly. Jetstream itself could not be accessed.

## Acceptance

- [ ] investigate why the servers health check does not fail if Jetstream is inaccessible
- [ ] investigate if it could be changed
- [ ] investigate (with NATS-io) if could have any negative effects on the cluster if nodes would be killed automatically in such a scenario

**Comment by k15r** [comment]
TB: 3d

**Comment by mfaizanse** [comment]
- There are some improvements related to RAFT and heartbeats for JetStream in [v2.8.3](https://github.com/nats-io/nats-server/releases/tag/v2.8.3)

**Comment by mfaizanse** [comment]
- Deployed Kyma with production profile

- Deleted the `/data/jetstream` directory in `eventing-nats-0` Pod.
- Published an event.
- JetStream got disabled in `eventing-nats-0` Pod.
```
[30] 2022/08/01 14:27:46.616717 [ERR] JetStream out of resources, will be DISABLED
[30] 2022/08/01 14:27:46.616814 [WRN] JetStream initiating meta leader transfer
[30] 2022/08/01 14:27:46.616941 [INF] JetStream cluster no metadata leader
[30] 2022/08/01 14:27:48.617328 [WRN] JetStream timeout waiting for meta leader transfer
[30] 2022/08/01 14:27:48.618313 [INF] Initiating JetStream Shutdown...
[30] 2022/08/01 14:27:48.618487 [INF] JetStream Shutdown
```

- Health probe `http://localhost:8222/healthz` returns `200 OK`.
- JetStream Info `http://localhost:8222/jsz` returns `data.disabled: true`:
```
{
"server_id": "NBKAYBIGPZ73E4LYEY64FU2BWTCGO53TTEYLJ5NVCP3DTM4H2DNQZFL6",
"now": "2022-08-01T14:57:56.528474816Z",
"disabled": true,
"config": {
"max_memory": 0,
"max_storage": 0
},
"memory": 0,
"storage": 0,
"reserved_memory": 0,
"reserved_storage": 0,
"accounts": 0,
"ha_assets": 0,
"api": {
"total": 0,
"errors": 0
},
"streams": 0,
"consumers": 0,
"messages": 0,
"bytes": 0
}
```

**Comment by mfaizanse** [comment]
http://localhost:8222/jsz

```
{
   "server_id":"NDQSBNWV5E54T53H2YGMNFZINVOOOG4YO5XXUJVKYKNPZF4ZJ7DPF33I",
   "now":"2022-08-02T07:17:44.752285558Z",
   "config":{
      "max_memory":1073741824,
      "max_storage":1073741824,
      "store_dir":"/data/jetstream"
   },
   "memory":0,
   "storage":0,
   "reserved_memory":0,
   "reserved_storage":0,
   "accounts":1,
   "ha_assets":3,
   "api":{
      "total":2,
      "errors":0
   },
   "streams":1,
   "consumers":1,
   "messages":0,
   "bytes":0,
   "meta_cluster":{
      "name":"eventing-nats",
      "leader":"eventing-nats-1",
      "cluster_size":3
   }
}
```

**Comment by mfaizanse** [comment]
JetStream related metrics exported by the nats-promethues-exporter at http://localhost:7777/metrics:

![image](https://user-images.githubusercontent.com/9897945/182378301-272e80c7-3310-4ded-b81d-5f904d5c5365.png)


![image](https://user-images.githubusercontent.com/9897945/182378367-5b4d47de-61bd-443c-9a80-cb94cf2a9667.png)

**Comment by mfaizanse** [comment]
![image](https://user-images.githubusercontent.com/9897945/182383208-2b76ee25-7624-4676-b371-22ac41733e34.png)

**Comment by mfaizanse** [comment]
Added a [PR](https://github.com/nats-io/prometheus-nats-exporter/pull/182) to export `nats_server_jetstream_disabled`.

```
# HELP nats_server_jetstream_disabled JetStream disabled or not
# TYPE nats_server_jetstream_disabled gauge
nats_server_jetstream_disabled{cluster="xxx-nats",domain="",is_meta_leader="false",meta_leader="xxx-nats-1",server_id="NBUCPIJXXPLYEEKPF6C7EBZDFX3QCDHLEO2II4YMU5JEJXEAMOJ7AHJZ",server_name="xxx-nats-2"} 0
```

**Comment by mfaizanse** [comment]
Conclusion:
Currently the health checks of JetStream are not reliable. Also, if any I/O error happens then NATS Server will just disable JetStream in that NATS instance and start reporting 200 OK in the health checks, which is not consistent behaviour. But in the `/jsz` endpoint it will return `response.disabled: true`.

Proposal:
- [ ] Upgrade NATS version to latest
- [ ] Change liveness check from `/` endpoint to `/healthz` because `/healthz` internally also does some health checks for JetStream server, streams and consumers.
- [ ]

**Comment by mfaizanse** [comment]
Created Follow-ups:
- https://github.com/kyma-project/kyma/issues/15046
