### ISSUE TITLE
Multiple jobs fail on fetching resource metadata for serverless.kyma-project.io/v1alpha2

### ISSUE THREAD

**Issue by Tomasz-Smelcerz-SAP** [kyma-project/kyma#14978]
**Description**

Multiple jobs fail with the following error:
```
 Upgrade test preparation
[ERROR] HttpError: Failed to fetch resource metadata for serverless.kyma-project.io/v1alpha2/Function: HTTP request failed
    1) CommerceMock test fixture should be ready


  0 passing (842ms)
  1 failing

  1) Upgrade test preparation
       CommerceMock test fixture should be ready:
     HttpError: Failed to fetch resource metadata for serverless.kyma-project.io/v1alpha2/Function: HTTP request failed
      at Request._callback (node_modules/@kubernetes/client-node/dist/object.js:416:32)
      at Request.self.callback (node_modules/request/request.js:185:22)
      at Request.<anonymous> (node_modules/request/request.js:1154:10)
      at IncomingMessage.<anonymous> (node_modules/request/request.js:1076:12)
      at endReadableNT (internal/streams/readable.js:1333:12)
      at processTicksAndRejections (internal/process/task_queues.js:82:21)

```
[An example](https://storage.googleapis.com/kyma-prow-logs/logs/kyma-upgrade-k3d-kyma2-to-main/1553983978631860224/build-log.txt)

It could be related to the `v1alpha2` API version which is not recognized.

**Expected result**

The job doesn't fail

**Actual result**

[Example 1](https://storage.googleapis.com/kyma-prow-logs/logs/kyma-upgrade-k3d-kyma2-to-main/1554014178413383680/build-log.txt)
[Example 2](https://storage.googleapis.com/kyma-prow-logs/logs/kyma-upgrade-gardener-kyma2-to-main-reconciler-main/1553983978430533632/build-log.txt)
[Example 3](https://storage.googleapis.com/kyma-prow-logs/pr-logs/pull/kyma-incubator_reconciler/1143/pre-main-reconciler-cli-kyma-prev-to-last-release-upgrade-k3d/1553994712480747520/build-log.txt)

**Steps to reproduce**

**Troubleshooting**

**Comment by cnvergence** [comment]
It is also blocking us in https://github.com/kyma-incubator/reconciler/pull/1141

**Comment by jeremyharisch** [comment]
The following pipeline is still failing with the same issues mentioned in this ticket:
- `pre-main-reconciler-cli-kyma-prev-to-last-release-upgrade-k3d` ([link](https://status.build.kyma-project.io/job-history/gs/kyma-prow-logs/pr-logs/directory/pre-main-reconciler-cli-kyma-prev-to-last-release-upgrade-k3d))

**Comment by jakobmoellersap** [comment]
@m00g3n could you take another look here?

**Comment by adityabhatia** [comment]
```  1) Upgrade test tests
       Logging Tests:
         Istio Access Logs tests
           Should query Loki and verify format of Istio Access Logs:
     TypeError: Cannot read property 'values' of undefined
      at Object.verifyIstioAccessLogFormat (logging/loki.js:57:45)
      at processTicksAndRejections (internal/process/task_queues.js:95:5)
      at async Context.<anonymous> (logging/index.js:29:7)```

**Comment by tobiscr** [comment]
> There has been another failure reported regulary. Seems to me an implementation issue. Could you have a look please @dbadura?
> 
> ```
>        Logging Tests:
>          Istio Access Logs tests
>            Should query Loki and verify format of Istio Access Logs:
>      TypeError: Cannot read property 'values' of undefined
>       at Object.verifyIstioAccessLogFormat (logging/loki.js:57:45)
>       at processTicksAndRejections (internal/process/task_queues.js:95:5)
>       at async Context.<anonymous> (logging/index.js:29:7)```
> ```

Issue found in our pipeline, is fixed with PR https://github.com/kyma-project/test-infra/pull/5932
