### ISSUE TITLE
kyma-admin role has not sufficient privileges to execute kubectl top commands

### ISSUE THREAD

**Issue by a-thaler** [kyma-project/kyma#1499]
**Description**
When using the kubeconfig downloaded from console (kyma-admin role), then "top pods" command is not working.

```
kubectl top pods  --namespace=production
Error from server (Forbidden): Forbidden (user=xxx@xxx.com, verb=list, resource=pods, subresource=) (get pods.metrics.k8s.io)
```

It seems that the resource group metrics.k8s.io is not configured for the role

**Expected result**
I would expect that this command will work for user authorized for the kyma-admin role.

**Comment by lszymik** [comment]
This need to be discussed.
