### ISSUE TITLE
Improve error logs in Application Connector integration tests

### ISSUE THREAD

**Issue by franpog859** [kyma-project/kyma#14994]
**Description**

@kyma-project/framefrog , improve logs from the `pre-main-kyma-integration-k3d-{application-connector-component}` pipelines. Currently, they look kinda gross when they fail. For example, there are multiple dropdowns for a single failure:
<img width="1493" alt="Screenshot 2022-08-03 at 10 01 10" src="https://user-images.githubusercontent.com/32485355/182556179-87f77316-817e-4849-b1d0-ec4d1a91f735.png">
There are also multiple bolded and covered in red lines in the logs below even if they are not important. [Here is an example of such log](https://status.build.kyma-project.io/view/gs/kyma-prow-logs/pr-logs/pull/kyma-project_kyma/14804/pre-main-kyma-integration-k3d-app-gateway/1554052034313850880)

For the successful runs, it doesn't look beautiful either. Look at these bolded errors that mean nothing, as [the pipeline is green](https://status.build.kyma-project.io/view/gs/kyma-prow-logs/pr-logs/pull/kyma-project_kyma/14972/pre-main-kyma-integration-k3d-app-gateway/1554480421897506816):
<img width="1152" alt="Screenshot 2022-08-03 at 10 27 12" src="https://user-images.githubusercontent.com/32485355/182561480-47210135-5bea-4367-85e6-c56246ce9d81.png">

**Reasons**

The log message should be clear. If there are errors, there should be a single dropdown for each one. If there are no errors and the pipeline is green, the logs should not scream with bolded red colored errors everywhere

**Comment by franpog859** [comment]
Notes from 04.08.2022 meeting:
1. Multiple dropdowns - there should be an option in the junit library that we use to ignore the parent tests
1. Error with the timeout - we can redirect the timeout with the `kubectl wait` to the dev null
1. Errors in bodies - maybe we can override regex that finds the `error` strings that appear in the request bodies, we should check this option. The error should be in the log but it should not be bolded and colored in red

We also talked about [this PR](https://github.com/kyma-project/kyma/pull/14851). It probably should be merged, @mvshao , @VOID404

**Comment by janmedrek** [comment]
@mvshao the PR was merged, should we close this issue?

**Comment by mvshao** [comment]
@janmedrek Yes, now we can close the issue.
