### ISSUE TITLE
Failing Pipelines: `Error from server: error dialing backend` (VPN connection issue)

### ISSUE THREAD

**Issue by jeremyharisch** [kyma-project/kyma#14992]
**Description**
The following pipelines are failing since they are not able to communicate with the backend:
- [pre-main-control-plane-reconciler-e2e-latest-release](https://status.build.kyma-project.io/job-history/gs/kyma-prow-logs/pr-logs/directory/pre-main-control-plane-reconciler-e2e-latest-release)
- [pre-main-control-plane-reconciler-upgrade-kyma2-latest-to-main-gardener](https://status.build.kyma-project.io/job-history/gs/kyma-prow-logs/pr-logs/directory/pre-main-control-plane-reconciler-e2e-latest-release)

Here are the errors from the log:

```
Error from server: error dialing backend: dial tcp 10.243.3.59:9443: connect: connection refused
...
Error from server: error dialing backend: proxy error from vpn-seed-server:9443 while dialing 10.250.0.3:10250, code 503: 503 Service Unavailable
```

**Comment by jakobmoellersap** [comment]
Additional run showed slightly different error:
https://storage.googleapis.com/kyma-prow-logs/pr-logs/pull/kyma-project_control-plane/1911/pre-main-control-plane-reconciler-e2e-latest-release/1556687145354137600/build-log.txt
```
2022-08-08 17:13:07 UTC [INFO] PID:13 --- [/home/prow/go/src/github.com/kyma-project/test-infra/prow/scripts/cluster-integration/helpers/reconciler.sh] reconciler::wait_until_kyma_reconciled:127 Waiting for reconciliation to finish, current status: reconciling ....
Error from server: unexpected EOF
```

**Comment by tobiscr** [comment]
It was brought up that this issue could be caused by https://github.tools.sap/kyma/backlog/issues/2818. Investigation by colleagues is ongoing.

**Comment by adityabhatia** [comment]
`Warning: you should consider disabling the static token kubeconfig, see https://github.com/gardener/gardener/blob/master/docs/usage/shoot_access.md for details`

This seems to be a constant warning in all pipelines at the moment

**Comment by kasiakepka** [comment]
I am looking at last successful run (from 28 July) and there is similar error about backend, see [logs](https://status.build.kyma-project.io/view/gs/kyma-prow-logs/pr-logs/pull/kyma-project_control-plane/1894/pre-main-control-plane-reconciler-e2e-latest-release/1552640340173787136#1:build-log.txt%3A309).
The pipeline is calling: `10.250.0.3:10250` but on July 28th it was calling `10.250.0.2:10250`

**Comment by tobiscr** [comment]
This ticket is dealing with two issues:

1) VPN connection problem 
2) Warning message replied from Gardener

I opened a dedicated issue to solve the warning from Gardener accordingly : https://github.com/kyma-incubator/reconciler/issues/1162

**Comment by tobiscr** [comment]
Raised an issue in Gardener project - https://github.com/gardener/gardener/issues/6588

**Comment by afjaguarking** [comment]
I've solve the issue by deleting many old folders in /nfsroot/.
Does deleting a notebook server instance leave the related persitent volumes untouched?
Because this behavior is not evident from the Dashboard

**Comment by jeremyharisch** [comment]
https://status.build.kyma-project.io/job-history/gs/kyma-prow-logs/pr-logs/directory/pre-main-control-plane-reconciler-e2e-latest-release now also fails for the same error

**Comment by ruanxin** [comment]
fix in PR: https://github.com/kyma-project/test-infra/pull/6348

**Comment by jeremyharisch** [comment]
Issue already has been fixed

**Comment by khlifi411** [comment]
The following pipelines are failing with the same error:

- [pre-main-control-plane-reconciler-e2e-latest-release](https://status.build.kyma-project.io/job-history/gs/kyma-prow-logs/pr-logs/directory/pre-main-control-plane-reconciler-e2e-latest-release)
- [pre-main-control-plane-reconciler-upgrade-kyma2-latest-to-main-gardener](https://status.build.kyma-project.io/job-history/gs/kyma-prow-logs/pr-logs/directory/pre-main-control-plane-reconciler-upgrade-kyma2-latest-to-main-gardener)

**Comment by ruanxin** [comment]
vpn connection issue is not the root cause.
