### ISSUE TITLE
Create alerts for NATS JetStream

### ISSUE THREAD

**Issue by raypinto** [kyma-project/kyma#15011]
**Description**

We would need alerts in case of any misbehaviour on the NATS server within the cluster. The following two alerts would be recommended:
-  [ ] Alert when NATS JetStream is disabled when the active backend is NATS.
    -  This alert is critical.

**Reasons**

This would help us be proactive with incidents and tackle problems at an early stage.

**Troubleshooting**

Adding an alert for stream message count might be counter productive since we may receive alerts for users who deleted the sink and forgot to delete the subscription. But this is also helpful in mitigating future problems as the stream can get full and choke the flow of events to valid sinks.

**Comment by k15r** [comment]
i agree with the first. but the second will probably lead to wrong alerts:
- subscription is misconfigured (endpoint rejects messages)
- subscription is intentionally disabled

**Comment by raypinto** [comment]
@k15r Agree! That's what I wrote in the `Troubleshooting` section. And this could potentially impact the flow of events that are configured correctly and are enabled.

**Comment by mfaizanse** [comment]
Follow-up: https://github.com/kyma-project/kyma/issues/15098

**Comment by nachtmaar** [comment]
Alert is implemented. Will be rolled out soon. Moving it to blocked (as it is out of my hands now).

**Comment by friedrichwilken** [comment]
@nachtmaar can this be closed? can the box in the original issue be checked?

**Comment by nachtmaar** [comment]
Jep. /close
