### ISSUE TITLE
Reliability testing of NATS JetStream

### ISSUE THREAD

**Issue by raypinto** [kyma-project/kyma#15010]
**Description**

NATS JetStream is currently being used in production and we should make sure to cover all edge cases and failure scenarios. The way to achieve this would be to send events continuously for a week (automated) and monitor the state of the consumers and streams every other day. 

**Expected result**

No failures should occur. If any issues do occur, create bugs and address them ASAP.

**Steps to reproduce**

- Install the latest Kyma with the latest NATS version
- Create 2 sinks that would receive events from two subscriptions
- Create 2 subscription with 10 filters each
- Create a automated script that would publish events periodically to the EPP
  - Events for the first eventType must be published 100 times per second
  - Events for the second eventType must be published 75 times per second
  - Events for the third eventType must be published every 50 times per second and so on
- Make sure the cluster does not hibernate and the script to auto-publish is run from within the cluster.

**Troubleshooting**

Clustersetup:
- Gardener (production like setup)
- nats in production mode (3 cluster nodes)
- no hibernation
- increase log retention (one week if possible)

**Comment by k15r** [comment]
we should have some event types with higher eps (>=50eps)

**Comment by marcobebway** [comment]
Eventing with JetStream backend was tested on multiple GCP and Azure clusters:

![summary](https://user-images.githubusercontent.com/24314423/185973039-f77661c9-3adb-4a19-bdd2-c308b8a429a7.png)

The following issues were found during testing:

- [Eventing publisher proxy reports OOM errors under load](https://github.com/kyma-project/kyma/issues/15219).
- [JetStream is disabled on all NATS cluster nodes when the storage is full](https://github.com/kyma-project/kyma/issues/15220).
- [Eventing does not perform as expected on Azure](https://github.com/kyma-project/kyma/issues/15221).
- [NATS container logs are not persisted in Loki](https://github.com/kyma-project/kyma/issues/15222).
