### ISSUE TITLE
Document upgrade and downgrade processes

### ISSUE THREAD

**Issue by zamazan4ik** [kyma-project/kyma#15033]
**Description**
After reading the documentation it is not clear for me, how upgrade and downgrade processes should be performed over the solution. Could you please describe somewhere in the documentation:

- How to upgrade Kyma to the newer version without downtime
- How to downgrade Kyma to the older version (hopefully with no downtime)
- Maybe some compatibility policies and notes between versions

**Area**

* Operations

**Reasons**

It makes Kyma operations easier.

**Assignees**

@kyma-project/technical-writers

**Comment by PK85** [comment]
Downgrades not supported.

**Comment by PK85** [comment]
@zamazan4ik have u seen this: https://kyma-project.io/docs/kyma/latest/04-operation-guides/operations/05-upgrade-kyma ? Do you expect more?

**Comment by zamazan4ik** [comment]
@PK85 Yes, I have read it. For me it is not clear, does it support zero-downtime upgrades or not from reading the documentation.

So please add a note about zero-downtime upgrade. And add explicit informtation that downgrade is not supported.

Thank you!

**Comment by tobiscr** [comment]
@NHingerl : We should also make clear in our documentation that we are at the moment NOT supporting zero-downtime upgrades.

**Comment by tobiscr** [comment]
![Screen Shot 2022-10-27 at 13 57 41](https://user-images.githubusercontent.com/73824711/198278282-777b0164-809c-4298-82df-dfbbf1e385a4.png)
