### ISSUE TITLE
New Application Connectivity tests - Test suite for Compass Runtime Agent

### ISSUE THREAD

**Issue by akgalwas** [kyma-project/kyma#15037]
**Description**

We need an integration test of Compass Runtime Agent. The test should be implemented **with a similar structure** to [the Application Gateway test](https://github.com/kyma-project/kyma/pull/14743). It should be fast, simple, and easy to maintain. If something breaks on some end-to-end pipeline or some environment, this test should clearly tell if there is a problem with the Validator or not

 **Acceptance criteria**
 
- [x] A test checking Compass Runtime Agent functionality is implemented 
- [x] The test takes minimal possible execution time
- [x] The test is considered as easy to maintain and has a similar structure to the Application Gateway tests
- [x] The test runs on the Prow pipeline
- [x] The test is runnable locally/ on a custom cluster

**Attachments**

epic issue - https://github.com/kyma-project/kyma/issues/13977

**Comment by akgalwas** [comment]
Work plan:
- [ ] Prepare and merge initial PR with project structure. It should contain: Dockerfile, Makefile and minimal code changes that could be run on a Prow pipeline.
- [ ] Modify test pipeline to install Compass Runtime Agent 
- [ ] Implement testcase for creating Applications
- [ ] Implement testcase for updating Applications
- [ ] Implement testcase for deleting Applications

**Comment by franpog859** [comment]
Please, remember to use the new Compass Director API in regard to the scenarios

**Comment by franpog859** [comment]
Please, create a ticket for the additional follow-up that covers all the possible Compass Runtime Agent cases, that covers ADDITIONAL cases in regards to the manual tests. Certs renewal and stuff like this
