### ISSUE TITLE
Create an alert if `nats_server_jetstream_disabled` changes from false to true.

### ISSUE THREAD

**Issue by mfaizanse** [kyma-project/kyma#15047]
As a follow up of [ticket](https://github.com/kyma-project/kyma/issues/14964).

If any I/O error happens then NATS Server will just disable JetStream in that NATS instance and start reporting 200 OK in the health checks. The JetStream status endpoint with start returning `disabled: true`, which is exported to Prometheus as `nats_server_jetstream_disabled`.

- [ ] Create an alert if `nats_server_jetstream_disabled` changes from false to true. Wait until this [PR](https://github.com/nats-io/prometheus-nats-exporter/pull/182) is included in new release.

**Comment by raypinto** [comment]
Being tracked [here](https://github.com/kyma-project/kyma/issues/15011).
