### ISSUE TITLE
[Telemetry Operator] Restructure Go packages

### ISSUE THREAD

**Issue by chrkl** [kyma-project/kyma#15041]
**Description**

PR https://github.com/kyma-project/kyma/pull/15018 restructured the Go packages of the telemetry-operator's webhooks to be align by the existing APIs. This should be continued for the controllers as well.

**Criteria**

- Organize the packages by controllers
- Move code that is shared between different controllers to an explicitly shared package
- Ensure that the new structure is ready to add additional controllers in future

**Comment by dennis-ge** [comment]
Restructuring:
- move internal/webhook to webhook
- move controllers of CR's into dedicated subdirectory in controller directory
- adding/rename internal structs
- make struct fields private
