### ISSUE TITLE
Refactor documentation in API Exposure domain

### ISSUE THREAD

**Issue by strekm** [kyma-project/kyma#15052]
**Description**

General improvement around service mesh, security and api exposure documentation:
- env variable DOMAIN_TO_EXPOSE_WORKLOADS should be consistent across all api exposure tutorials. e.g. `export DOMAIN_TO_EXPOSE_WORKLOADS={DOMAIN_NAME} #This is a Kyma domain or your custom subdomain e.g. api.mydomain.com.`. consider transferring comment to separate note
- in expose tutorials export `GATEWAY` env variable which can be set to `$NAMESPACE/httpbin-gateway` if user followed [Use a custom domain to expose a workload](https://kyma-project.io/docs/kyma/latest/03-tutorials/00-api-exposure/apix-01-own-domain/) or to default kyma gateway: `kyma-system/kyma-gateway`. e.g. `export GATEWAY=$NAMESPACE/httpbin-gateway # If you don't want to use your custom domain but a Kyma domain, use the following Kyma Gateway: 'kyma-system/kyma-gateway'.`. consider moving comment to a note

Changes in [Use a custom domain to expose a workload](https://kyma-project.io/docs/kyma/latest/03-tutorials/00-api-exposure/apix-01-own-domain/):
- rename [Use a custom domain to expose a workload](https://kyma-project.io/docs/kyma/latest/03-tutorials/00-api-exposure/apix-01-own-domain/) to `Prepare custom domain for a workload`
- move [Use a custom domain to expose a workload](https://kyma-project.io/docs/kyma/latest/03-tutorials/00-api-exposure/apix-01-own-domain/) after `Create a workload` tutorial
- add a note to [Use a custom domain to expose a workload](https://kyma-project.io/docs/kyma/latest/03-tutorials/00-api-exposure/apix-01-own-domain/) that this tutorial can be skipped in favour of using kyma domain and kyma gateway
- `Create a workload` tutorial should be added to pre-reqs of [Use a custom domain to expose a workload](https://kyma-project.io/docs/kyma/latest/03-tutorials/00-api-exposure/apix-01-own-domain/)
- step `Create a Namespace` can be removed from [Use a custom domain to expose a workload](https://kyma-project.io/docs/kyma/latest/03-tutorials/00-api-exposure/apix-01-own-domain/) since ns was already created in `Create a workload` tutorial 
- remove env variable `WILDCARD` in favour of `*.DOMAIN_TO_EXPOSE_WORKLOADS` in [Use a custom domain to expose a workload](https://kyma-project.io/docs/kyma/latest/03-tutorials/00-api-exposure/apix-01-own-domain/)
- in `Create a Certificate CR` of [Use a custom domain to expose a workload](https://kyma-project.io/docs/kyma/latest/03-tutorials/00-api-exposure/apix-01-own-domain/) add sentence to check certificate status
- `Next steps` of [Use a custom domain to expose a workload](https://kyma-project.io/docs/kyma/latest/03-tutorials/00-api-exposure/apix-01-own-domain/) should be about exposing workload tutorials
- remove `You can use it as a follow-up to the [Use a custom domain to expose a workload](https://kyma-project.io/docs/kyma/latest/03-tutorials/00-api-exposure/apix-01-own-domain/) tutorial.` from [Create a workload](https://kyma-project.io/docs/kyma/latest/03-tutorials/00-api-exposure/apix-02-create-workload/)

Changes in [Create a workload](https://kyma-project.io/docs/kyma/latest/03-tutorials/00-api-exposure/apix-02-create-workload/):
- `Create a Gateway CR` step should be moved as last step of [Use a custom domain to expose a workload](https://kyma-project.io/docs/kyma/latest/03-tutorials/00-api-exposure/apix-01-own-domain/) tutorial.
- [Use a custom domain to expose a workload](https://kyma-project.io/docs/kyma/latest/03-tutorials/00-api-exposure/apix-01-own-domain/) tutorial should be added as optional tutorial before exposing tutorials

**Area**

*Service Mesh*
*API exposure*
*Security*

**Assignees**

@kyma-project/technical-writers

**Attachments**

**Comment by SamehMKhattab** [comment]
PR:
https://github.com/kyma-project/kyma/pull/15332/files
