### ISSUE TITLE
setup mTLS gateway and access exposed workload with certificate tutorials

### ISSUE THREAD

**Issue by strekm** [kyma-project/kyma#15078]
**Description**

Add tutorial for to configure mTLS gateway. Under Developer tutorial create new section called `Security`. Tutorial should be new tutorial Developer tutorials -> Security -> Setup mTLS gateway. After finishing this tutorial user will have mTSL gateway configured with certificate and additional cacert bundle. Follow up to this tutorial will be tutorial how to expose and secure workload with Istio CRs.

Move [Set up a custom identity provider](https://kyma-project.io/docs/kyma/latest/03-tutorials/03-set-up-idp) and [Set up your custom domain TLS certificate](https://kyma-project.io/docs/kyma/latest/03-tutorials/sec-01-tls-certificates-security/) to new `Security` developer tutorials section. 

Add tutorial for exposing and securing workload with certificate. Tutorial should be new tutorial in API Exposure tutorials. Pre-req for this tutorial should be create workload and setup mTSL gateway tutorial. User should be able to access secured workload using certificate. 

ACs:
- [x] Tutorial (an `.md` file) with complete steps on how setup mTLS gateway
- [x] Location: `kyma` respository `kyma-project/kyma/tree/main/docs/03-tutorials/xx-security`
- [x] Tutorial (an `.md` file) with complete steps on how to expose and secure with certificate a deployed workload
- [x] Location: `kyma` respository `kyma-project/kyma/tree/main/docs/03-tutorials/00-api-exposure`
- [x] "expose and secure with certificate" tutorial should be a follow-up of the [Create a workload](https://deploy-preview-13513--kyma-project-docs-preview.netlify.app/docs/kyma/preview/03-tutorials/00-api-exposure/apix-02-create-workload/) tutorial
- [x] Add links to the new "expose and secure with certificate" tutorial in the **Next steps** section of [Create a workload](https://deploy-preview-13513--kyma-project-docs-preview.netlify.app/docs/kyma/preview/03-tutorials/00-api-exposure/apix-02-create-workload/#next-steps)
- [x] Add a link to the "expose and secure with certificate" document to the [Useful links](https://deploy-preview-13513--kyma-project-docs-preview.netlify.app/docs/kyma/preview/01-overview/main-areas/api-exposure/apix-02-useful-links/) document in the **Overview -> Main areas -> API Exposure -> Useful links**
- [x] When you create the new file, stick to the following naming convention: `{COMPONENT_ABBRV}-{NUMBER_PER_COMPONENT}-{FILE_NAME}.md}`
- [x] Use the [tutorial template](https://github.com/kyma-project/community/blob/main/templates/resources/tutorial.md)
- [x] Test the complete flow

**Area**

* Service Mesh*
* Security *
* API Exposure *

**Assignees**

@kyma-project/technical-writers

**Comment by SamehMKhattab** [comment]
PR:
https://github.com/kyma-project/kyma/pull/15302

**Comment by SamehMKhattab** [comment]
New PR:
https://github.com/kyma-project/kyma/pull/15505

**Comment by dariusztutaj** [comment]
#15716

**Comment by strekm** [comment]
https://github.com/kyma-project/kyma/pull/15879
