### ISSUE TITLE
E2E tests for reconciler (Gherkin based)

### ISSUE THREAD

**Issue by tobiscr** [kyma-project/kyma#15084]
**Description**

The new reconciler architecture is using Gherkin notation in its end2end tests to verify business features.

A first draft including [business features](https://github.com/kyma-project/kyma/tree/main/tests/components/reconciler/features) and a mapping between [Gherkin statements to Go functions] (https://github.com/kyma-project/kyma/blob/main/tests/components/reconciler/cucumber_test.go#L90-L113)was already merged to the Kym repository:

https://github.com/kyma-project/kyma/tree/main/tests/components/reconciler

The first version includes only calls to empty test functions which don't include any logic yet. The goal of this ticket is to implement the related testing logic per test function.

AC:
* Implement test logic for each test case (see [test functions](https://github.com/kyma-project/kyma/blob/main/tests/components/reconciler/cucumber_test.go)).
    - [ ] Create KCP cluster
    - [ ] Create SKR cluster
    - [ ] Install Reconciler in KCP cluster
    - [ ] Create Kyma CR
    - [ ] Update Kyma CR
    - [ ] Update Kyma CR with an invalid change
    - [ ] Delete Kyma CR
    - [ ] Delete Watcher webhook
    - [ ] Delete module operator in SKR
    - [ ] Delete module CRD in SKR
    - [ ] Update module template
    - [ ] Assertion of a module CR
    - [ ] Assertion of a manifest CR
    - [ ] Assertion of a deployed module
    - [ ] Assertion of an undeployed module
    - [ ] Assertion of a state in the Kyma CR
    - [ ] Assertion of updated conditions in Kyma CR
    - [ ] Assertion for copied Kyma CRs
    - [ ] Assertion for event in Kyma CR
    - [ ] Assertion for log output of Validation Webhook
    - [ ] Assertion for creating Watcher webhook
    - [ ] Assertion for an SKR reconciliation (check that cluster got reconciled)
    - [ ] Assertion for created module operator
    - [ ] Assertion for created module CRD
    - [ ] Assertion for updated module CR

**Comment by jakobmoellersap** [comment]
Waiting until Specs of Tests finish

**Comment by tobiscr** [comment]
Missing test specs provided in PR https://github.com/kyma-project/kyma/pull/15103
