### ISSUE TITLE
add `zone` affinity to nats-server pod

### ISSUE THREAD

**Issue by friedrichwilken** [kyma-project/kyma#15085]
this is a followup to #14962 

- [ ] add the `topology` key `zone` to `nats-server`'s `sts` to assure that, in case there are multiple zones available, the pods are distributed over these zones. 
    - this should be in addition to `hostname` and not replace it
    - it should have more `weight` than `hostname`
    - [more info](https://github.com/kyma-project/kyma/issues/14962#issuecomment-1208581844)
- [ ] run the [`sre-performance test`](https://github.tools.sap/skydivingtunas/sre-performance) to validate this setup on a cluster with at least 3 nodes in three zones.

**Comment by raypinto** [comment]
Note: Don't merge changes to main without evaluating the performance!

**Comment by k15r** [comment]
Task:
- [ ] setup cluster (production profile, Kyma version 2.X.X)
- [ ] run performance test to create baseline
- [ ] setup similar cluster but using multiple zones
- [ ] apply topology antiaffinity
- [ ] rerun performance test and compare with baseline

**Comment by muralov** [comment]
<ul>
<li>Publishing is faster with One-Zone</li>
<li>Dispatching looks similar in both cases with smaller difference</li>
<li>Re-election didn’t cause much difference</li>
<li>Slow and Faster RPS didn’t have much effect on the test results</li>
</ul>
<h3>Publishing Test Results</h3>


http_req_duration | One Zone | Multi Zone | One Zone (p(90), p(95)) | Multi Zone (p(90), p(95)) | Notes | Dispatching
-- | -- | -- | -- | -- | -- | --
1st try | 2.06 ms | 3.2  ms | 3.59 ms,  5.02 ms | 4.65 ms,   6.3 ms |   |  
2nd try | 1.9 ms | 3.19 ms | 2.89 ms,  4.08 ms | 4.65 ms,   6.26 ms |   |  
3rd try | 1.82 ms | 2.83 ms | 2.81 ms,   3.95 ms | 3.84 ms,   5.2 ms | w/ leader re-election |  
4th try | 1.39 | 2.56 | 1.57 ms,   2.04 ms | 4.37 ms,   6 ms | fresh new cluster |  
5th try | 1.39 | 2.57 | 1.57 ms,   2.05 ms | 4.42 ms,   6.05 ms | second try in fresh new cluster |  
  |   |   |   |   |   |  


<h3>Dispatching from NAT JetStream to Receiver</h3>


Tries | One Zone(mps) | Multi Zone (mps)
-- | -- | --
1st | 400 | 380
2nd | 400 | 380
3rd | 390 | 370
4th | 350 | 320
5th | 360 | 320
6th | 280 | 275

**Comment by muralov** [comment]
Here are last NATS multizone setup tests, which did perform event better than one-zone. You see event putting nats-bench, nats-server, and nats stream leader on different zones perform even better. Hence, NATS JetStream works totally fine with multizone setup.

<h3>NATS Benchmarking Results</h3>
<p>z2 → z1 → z3 :    nats-bench tool (z2) → nats server (z1) → nats stream leader (z3)</p>


one zone | z2→z2-z2 | z2→z2-z1 | z2→z2-z3 | z2→z3-z3 | z2→z1-z3 | z2→z3-z2 | z2→z1-z3 | z2→z3-z1 | z2→z3-z1
-- | -- | -- | -- | -- | -- | -- | -- | -- | --
2,842 | 2,966 | 3,406 | 3,125 | 3,188 | 2,979 | 3,182 | 3,695 | 3,725 | 3,831
3,071 | 2,952 | 3,465 | 3,032 | 3,170 | 3,158 | 3,139 | 3,560 | 3,707 | 3,873
2,883 | 2,799 | 3,574 | 3,016 | 3,142 | 2,901 | 3,068 | 3,653 | 3,534 | 3,695
2,888 | 2,771 |   | 3,001 | 3,167 | 2,791 | 2,980 | 3,542 | 3,637 | 3,729
