### ISSUE TITLE
Unify app label in serverless pods

### ISSUE THREAD

**Issue by kwiatekus** [kyma-project/kyma#15099]
**Description**
We have inconsistent labels across serverless pods:
 - Ctrl manager has: `app: serverless`
 - webhook has `app: serverless-webhook`

I think that we should unify them as together they are serverless application.
I would also look at internal container registry

**Reason**
Serverless is an app (module) that consists of multiple pods.
Using one label would help us with gathering logging from all parts of our system in test as we're using `kubectl logs -n kyma-system -l app=serverless --tail=-1`

**Comment by dbadura** [comment]
Deployment `podSelector` field is not mutable (https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#label-selector-updates) so we cannot simply change pod labels.
The only solution to fix it, is to delete and apply the deployment.
We can do it in several ways:
- write custom code in reconciler: https://github.com/kyma-incubator/reconciler/blob/67d6459b9b280ec7895d254d5df3f5330c03bb5b/pkg/reconciler/kubernetes/updatestrategyresolver.go
- wait for serverless operator and write the custom code
- set replicas to 0 to current deployment or delete (I don't know how reconciler will behave), create new deployment with new name and use proper labels.

**Comment by dbadura** [comment]
Reconciler will delete deployment if we change the name of it

**Comment by moelsayed** [comment]
@dbadura I am unable to reproduce this. If I changed the webhook deployment name, the old deployment is not deleted when I upgrade to the new version. Can you please describe exactly how you did this?
