### ISSUE TITLE
`nightly-main-reconciler-e2e` failing after the recent changes to fluent bit monitoring

### ISSUE THREAD

**Issue by jakobmoellersap** [kyma-project/kyma#15090]
**Description**

The Job `nightly-main-reconciler-e2e` is failing after the recent changes to fluent bit and they need to be corrected /adjusted to after switching to telemetry

```
Executing Standard Testsuite:
       Prometheus Tests:
         Metrics used by Kyma Dashboard should exist:
     AssertionError: Following queries return no results: topk(10,fluentbit_input_bytes_total{name=~"..*"})metric from service monitor: logging-fluent-bit: expected [ 'topk(10,fluentbit_input_bytes_total{name=~"..*"})metric from service monitor: logging-fluent-bit' ] to be empty
```

**Expected result**

The Job `nightly-main-reconciler-e2e` should not fail due to telemetry

**Actual result**

The Job `nightly-main-reconciler-e2e` is failing

**Steps to reproduce**

Look at https://status.build.kyma-project.io/job-history/gs/kyma-prow-logs/logs/nightly-main-reconciler-e2e

**Troubleshooting**

**Comment by chrkl** [comment]
Job succeeded again after merging the pr: https://status.build.kyma-project.io/view/gs/kyma-prow-logs/logs/nightly-main-reconciler-e2e/1558015549710012416
