### ISSUE TITLE
Create troubleshooting guide explaining possible reasons why exposed service cannot be reached (5xx)

### ISSUE THREAD

**Issue by strekm** [kyma-project/kyma#15116]
**Description**

Create troubleshooting guide under [API Exposure](https://kyma-project.io/docs/kyma/latest/04-operation-guides/troubleshooting/api-exposure/) explaining possible reason that workload cannot be reached returning 5xx response code. Explain in troubleshooting guide how exposing `/*` and `/headers` is treated in ORY oathkeeper misconfiguration and leads to 5xx errors. 

ACs:
- [x] document should follow troubleshooting guide template
- [x] document title should follow other `Cannot connect to a service exposed by an API Rule` troubleshooting guides
- [x] document should be linked in [basic diagnostics](https://kyma-project.io/docs/kyma/latest/04-operation-guides/troubleshooting/api-exposure/apix-01-apigateway-connect-api-rule)
- [x] document should explain how paths `/*` and `/headers` can lead to misconfiguration

**Area**

*API Exposure*

**Assignees**

@kyma-project/technical-writers

**Attachments**

https://github.com/ory/oathkeeper/issues/157

**Comment by videlov** [comment]
@strekm @nataliasitko what is the state with this issue?
