### ISSUE TITLE
[Telemetry Operator] Controller logs contain incorrect metadata

### ISSUE THREAD

**Issue by chrkl** [kyma-project/kyma#15117]
**Description**

The telemetry-operator logs records like 
```
{"level":"INFO","timestamp":"2022-08-16T12:21:57Z","caller":"sync/sync.go:113","message":"Adding finalizer","context":{"controller":"logparser","controllerGroup":"telemetry.kyma-project.io","controllerKind":"LogParser","logPipeline":{"name":"loki"},"namespace":"","name":"loki","reconcileID":"99582177-8e2d-4bef-8dbf-361a8ed632ad"}}
```
where the controller and controllerKind does not match the reconciled resource.

**Criteria**
- Log record metadata should be correct

**Comment by dennis-ge** [comment]
The issue was an outdated `controller-runtime` version of 0.12.1. Updated it to the latest version, 0.12.3.
