### ISSUE TITLE
[Configurable Logging] Running `kyma deploy` causes fluent-bit restart without changes

### ISSUE THREAD

**Issue by chrkl** [kyma-project/kyma#15118]
**Description**
Re-deploying the Kyma logging component results in a restart of the telemetry-fluent-bit DaemonSet, even without any changes.

Each re-deploy of the logging component removes the `FLUENT_BIT_SECTIONS_CONFIG_MAP` finalizer from the `loki` LogPipeline. The telemetry-operator adds the finalizer again and restarts the `telemetry-fluent-bit` DaemonSet..

**Steps to Reproduce**
1. Deploy kyma: `kyma deploy`
2. Redeploy kyma with the same configuration (logging component is enough): `kyma deploy --component=logging`

The `loki` LogPipeline will switch to `pending` and the telemetry-fluent-bit DaemonSet restarts.

**Criteria**
- Fluent Bit should only be restarted if changes to the chart or custom resource (LogPipeline or LogParser) are applied.

**Comment by tobiscr** [comment]
We could fix this issue by introducing an interceptor which is checking for existing particular labels and injects them into the rendered HELM chart before it gets applied. We do similar thing for HPAs.. there we copy the value of the `replicas` into the rendered HELM chart to avoid accidentally triggered rescaling of pods.

Here the code we use for HPA: https://github.com/kyma-incubator/reconciler/blob/main/pkg/reconciler/service/hpainterceptor.go#L57-L84

**Comment by tobiscr** [comment]
Quick summary how we agreed to address this issue:

* We add a custom interceptor which is adjusting the rendered HELM charts before they are getting deployed to add there the missing labels (example interceptors are here available: https://github.com/kyma-incubator/reconciler/tree/main/pkg/reconciler/service)
* The new reconciler can be instantiated and injected to the interception-queue [here](https://github.com/kyma-incubator/reconciler/blob/main/pkg/reconciler/service/install.go#L52-L62)
* For testing purposes, we recommend to use the CLI directly and add an `replace`-instruction on top of the go.mod file to use your local reconciler sources: https://github.com/kyma-project/cli/blob/main/go.mod#L40
* You can trigger the CLI over an IDE and run it in debug-mode by starting the [CLI's main.go file](https://github.com/kyma-project/cli/blob/main/cmd/main.go) (e.g. `go run main.go deploy ...`)

**Comment by chrkl** [comment]
Fixed by preserving finalizers during reconciliation (PR https://github.com/kyma-incubator/reconciler/pull/1160). Also the telemetry operator has been improved to restart Fluent Bit only if the configuration has changed, but not ifif finalizers were added to the CR (PR https://github.com/kyma-project/kyma/pull/15132)
