### ISSUE TITLE
Bump Istio virtual service version in fast-integration tests

### ISSUE THREAD

**Issue by barchw** [kyma-project/kyma#15123]
**Description**

Fast integration tests are fetching Istio VS in version v1beta1 although it was deprecated in favour of v1alpha3

**Actions**
- [ ] Bump Istio virtual service to v1alpha3

**Attachments**

Example place where this is done:
https://github.com/kyma-project/kyma/blob/91de6c13752ae7fcbb5912b1c8534c480359e28a/tests/fast-integration/utils/index.js#L595

**Comment by strekm** [comment]
leaving it closed since we will be reworking our tests from fast integration tests
