### ISSUE TITLE
Fix failing job: pre-main-kyma-skr-eventing

### ISSUE THREAD

**Issue by mfaizanse** [kyma-project/kyma#15128]
The job: [pre-main-kyma-skr-eventing](https://status.build.kyma-project.io/job-history/gs/kyma-prow-logs/pr-logs/directory/pre-main-kyma-skr-eventing) is failing to provision a SKR, with the following [error](https://storage.googleapis.com/kyma-prow-logs/pr-logs/pull/kyma-project_kyma/15127/pre-main-kyma-skr-eventing/1559873213897379840/build-log.txt):

```
"provisioning": {
			"state": "failed",
			"description": "Operation created : cannot create provisioning input creator",
			"createdAt": "2022-08-17T12:02:42.772529Z",
			"operationID": "42468763-55da-49d3-b8f4-23d442a9dd38"
		}
```

**Comment by mfaizanse** [comment]
https://github.com/kyma-project/control-plane/blob/main/docs/kyma-environment-broker/03-14-broker-configuration-for-given-version-and-plan.md

Gophers need to come up a way to use default config (which could be the latest official release) for Kyma provision of PR-xxx version.

**Comment by nachtmaar** [comment]
Let's fix this asap, it is failing all the time: https://status.build.kyma-project.io/job-history/gs/kyma-prow-logs/pr-logs/directory/pre-main-kyma-skr-eventing

**Comment by marcobebway** [comment]
@k15r does it still make sense to have this job running pre-main for every pr?

**Comment by nachtmaar** [comment]
We decided it does not make sense to have this job and will about a replacement job. Let's delete it as part of the ticket.

**Comment by VladislavPaskar** [comment]
according to @kyma-project/gopher, they will introduce a fix, which should make the provisioning part green again.

**Comment by VladislavPaskar** [comment]
the provisioning issue is tracked [here](https://github.com/kyma-project/control-plane/issues/2167)

**Comment by VladislavPaskar** [comment]
This issue is now unblocked, since the SKR can be provisioned with the PR version.

**Comment by mfaizanse** [comment]
The job `pre-main-kyma-skr-eventing` is removed for now.
