### ISSUE TITLE
Fix pre-main-kyma-integration-k3d-central-app-connectivity-compass pipeline

### ISSUE THREAD

**Issue by barchw** [kyma-project/kyma#15137]
**Description**

This pipeline seems to be failing on every PR, blocking merging

**Expected result**
Pipeline should run successfuly

**Comment by koala7659** [comment]
It seems ike issue with registering Kyma with compass: ([logs](https://storage.googleapis.com/kyma-prow-logs/pr-logs/pull/kyma-project_kyma/15125/pre-main-kyma-integration-k3d-central-app-connectivity-compass/1560143558697029632/build-log.txt))
1) Kyma with Compass test
       Register Kyma instance in Compass:
     Error: Error when updating label definition with key scenarios: Error: Error calling Director API

**Comment by strekm** [comment]
pipeline marked as optional with https://github.com/kyma-project/test-infra/pull/5881

**Comment by franpog859** [comment]
The `pre-*` job is optional, the `post-*` job fails constantly. I think we should consider removing it after the merge of [this test](https://github.com/kyma-project/kyma/issues/15037)

**Comment by tobiscr** [comment]
Outdates, closing it
