### ISSUE TITLE
Introduce non blocking way of installing Remote Environments charts

### ISSUE THREAD

**Issue by Szymongib** [kyma-project/kyma#1514]
**Description**

Remote Environment Controller installs Remote Environment charts with Helm. If Helm installation is taking to long the whole Controller is blocked.

Acceptance:
- Installation of RE does not block the Controller
- Approaches with gorutines and Helm installation without `wait` considered

**Comment by janmedrek** [comment]
This will be addressed by the switch to Helm 3.0
