### ISSUE TITLE
Validation Webhook Certificate of telemetry mismatch with that of the operator

### ISSUE THREAD

**Issue by rakesh-garimella** [kyma-project/kyma#15142]
**Description**
I had an old kyma installation with telemetry operator and when I execute `kyma deploy` we see  following error and deploy fails.

```
{"level":"ERROR","timestamp":"2022-08-17T14:38:12Z","caller":"controller/controller.go:326","message":"Reconciler error","context":{"controller":"logparser","controllerGroup":"telemetry.kyma-project.io","controllerKind":"LogParser","logParser":{"name":"apache-error"},"namespace":"","name":"apache-error","reconcileID":"b4f6289c-175c-45df-b27a-98dad787ffa4","error":"Internal error occurred: failed calling webhook \"validation.logparsers.telemetry.kyma-project.io\": Post \"[https://telemetry-operator-webhook.kyma-system.svc:443/validate-logparser?timeout=30s](https://telemetry-operator-webhook.kyma-system.svc/validate-logparser?timeout=30s)\": x509: certificate signed by unknown authority (possibly because of \"crypto/rsa: verification error\" while trying to verify candidate authority certificate \"telemetry-validating-webhook-ca\")"}}
```

The issue seems to be certificate mismatch between `validation webhook` and `telemetry operator`.

After deleting `webhook` and `telemetry operator` and then performing `kyma deploy` multiple times it did not occur again.

We should investigate further to understand the behaviour as to why it occurred at first place.

**Comment by a-thaler** [comment]
We couldn't proof it fully but are very sure finally that the issue boils down to an instable order of applying the chart resources in the reconciler.
Here the findings:
- Sometimes the installation times out as the LogParser resources cannot be applied, they cannot be applied as the ca-bundle configured for the related webhook does not fit to the ca-bundle used to generate the webhook certificate
- In the error situation the webhook does not recover, only deleting the webhookConfig and the operator deployment fixed the problem
- In the error situation we detected that the ca-buncle for the webhookConfig was not updated to the one used for the webhhok certificate, so mot probably the webhookConfig was not updated at all
- We realized that the reconciler will apply the resources of a chart till the first failure and then it stops (till next retry). If a first the secret of the operator/webhook gets updated (it seem to get refreshed immediately in the operator deployment) and then a logParser gets applied, we get a failure where webhook got updated but not the webhookConfig.

We discussed several solutions, here the findings:
- For sure we need to remove the LogParser resources from the chart which seems doable, as then the webhook initialization has time till first resources get applied. A pre-hook is not possible with the reconciler, only a custom reconciler could help here.
- The best way is to manage the certificates by a certManager. Assuming Gardener underneath will even make that quite simple. The certmanager will take care of cert generation and also webhookConfig
- As a short term solution we will adjust the controller to generate certs at startup and configure the webhookConfig

**Comment by a-thaler** [comment]
We decided that the short-term approach is really not nice as it is and would take quite some effort. Instead we will drop the parsers only which fixes already the actual problem and invest separately into a nicer solution which will not cause the webhookConfig reload so often.

**Comment by skhalash** [comment]
To be continued in https://github.com/kyma-project/kyma/issues/15195
