### ISSUE TITLE
Deploying telemetry component fails regularly in nightly-main-reconciler-e2e test 

### ISSUE THREAD

**Issue by chrkl** [kyma-project/kyma#15145]
**Description**

```
{"level":"DEBUG","time":"2022-08-18T03:26:27.979Z","message":"Bookkeeper evaluated reconciliation (schedulingID:6f8ec1bc-f300-4f00-bb65-6fec5dcd0ba5--17d6539d-637c-468a-b25d-c2dd60de0df7) for cluster '6f8ec1bc-f300-4f00-bb65-6fec5dcd0ba5' to cluster status 'error': Done=cluster-users[3],CRDs[1],certificates[2],eventing[3],istio[2],cluster-essentials[2],kiali[3],istio-resources[3],api-gateway[3],tracing[3],monitoring[3],application-connector[3],ory[3],serverless[3] / Error=telemetry[3][error: context deadline exceeded],logging[3][error: context deadline exceeded] / New= / Running="}
```

Some of the failed test runs:
- https://status.build.kyma-project.io/view/gs/kyma-prow-logs/logs/nightly-main-reconciler-e2e/1558045749646725120
- https://status.build.kyma-project.io/view/gs/kyma-prow-logs/logs/nightly-main-reconciler-e2e/1558075949478580224
- https://status.build.kyma-project.io/view/gs/kyma-prow-logs/logs/nightly-main-reconciler-e2e/1558106148614180864

**Comment by a-thaler** [comment]
Might be caused by https://github.com/kyma-project/kyma/issues/15142

**Comment by rakesh-garimella** [comment]
The PR: https://github.com/kyma-project/kyma/pull/15161 has been merged lets check the next run

**Comment by chrkl** [comment]
Job is green again after merging https://github.com/kyma-project/kyma/pull/15216
