### ISSUE TITLE
Use public DNS pointing localhost for development mode (minikube)

### ISSUE THREAD

**Issue by pbochynski** [kyma-project/kyma#1515]
Local kyma setup requires entries in /etc/hosts for all subdomains used in kyma. Because minikume IP address is dynamic and list of subdomains is also dynamic it is difficult to maintain and requires shell scripts running with administrator privileges. 

The idea is to use one of public DNS servers pointing to 127.0.0.1 (localhost):
- lvh.me
- localtest.me
- fuf.me
- ulh.us
- 127-0-0-1.org.uk
- ratchetlocal.com
- smackaho.st
- 42foo.com
- vcap.me
- beweb.com
- yoogle.com
- ortkut.com
- feacebook.com

Consider using one of this as domain name for local setup on minikube.

**Comment by adamwalach** [comment]
We could also create a wildcard subdomain like *.local.kyma-project.io or *.minikube.kyma-project.io and set it to 127.0.0.1. This way we could preserve control over the name.

**Comment by piotrmsc** [comment]
minikube ip is not localhost.
