### ISSUE TITLE
Function controller brings down replicas to the desired minimum for currently scaled up function deployments

### ISSUE THREAD

**Issue by pPrecel** [kyma-project/kyma#15152]
**Description**

Now template for functions deployment always use `minReplicas` as value for the `deployment.spec.replicas` field. It's a little bit confusing and may cause problems when existing deployment is scaled up to a value higher than the minimum. To avoid the potential risk of scaling problems we should think about a better solution and introduce them. Initial conversation and first iteration (first shape) of the solution for this problem were proposed [here](https://github.com/kyma-project/kyma/pull/14704#discussion_r934352178).

**Comment by kwiatekus** [comment]
AFAIU the case is as follows:

Given that:
   deployment replicas is managed by HPA ( HPA managed by function controller ) 
When 
   function deployment's current state is compared with desired state by the control loop
AND
   deployment replicas has been scaled up by HPA
Then
   function controller sets the replicas down to the value of `minReplicas`

But it should do that. The current amount of replicas ( as managed by HPA ) should not be forcefully brought down by function controller

Shouldn't we simply leave that part for HPA to manage?

**Comment by kwiatekus** [comment]
Closing.
There is a follow up bug to be fixed regarding corrupted v1alpha1->v1aloha2 conversion
