### ISSUE TITLE
Introduce custom logic to identify that the JetStream storage is full

### ISSUE THREAD

**Issue by VladislavPaskar** [kyma-project/kyma#15150]
**Description**
Currently Jetstream part of NATS gets disabled when the storage gets full. The error which we get by publishing when the storage is full is `no response from stream`. This is misleading, because doesn't specify the exact problem what happened in the background. And what happens is that Jetstream got disabled due to the full storage. 

According to NATS: they are currently revising([reference](https://natsio.slack.com/archives/CTM4A2TR7/p1660649687188479)) their error handling in nats.go to be able to inspect api errors via errors package, so there is no direct propagation of the expected error yet.

So we need to come up with a custom logic to identify that Jetstream is disabled due to the full storage.

Further reasoning is here https://github.com/kyma-project/kyma/issues/14965#issuecomment-1217993076

**Comment by mfaizanse** [comment]
Todo: Lets find an issue on JetStream repo and link it here. Otherwise create an issue on JetStream.

**Comment by VladislavPaskar** [comment]
let's track this here: https://github.com/kyma-project/kyma/issues/15220
