### ISSUE TITLE
LogPipeline resources are hanging in deletion on cluster removal

### ISSUE THREAD

**Issue by kasiakepka** [kyma-project/kyma#15165]
**Description**
Gardener has issues deleting clusters as there are still some telemetry CRDs on the cluster.
<img width="1001" alt="Screen Shot 2022-08-17 at 16 19 58" src="https://user-images.githubusercontent.com/48180632/185586059-782214ec-85d4-47b4-b581-6a992264195d.png">

**Expected result**
Cleanup telemetry CRD.

**Comment by kasiakepka** [comment]
I think this issue is for huskies.

**Comment by chrkl** [comment]
I can reproduce this issue. I observed the following situation:

- The telemetry-operator uses the LogPipeline and LogParser CRDs
- During the deletion of a Gardener cluster, all resources are deleted without any particular order
- We delete 16 LogParsers and 1 LogPipeline. The corresponding CRDs are deleted after all objects are gone.
  - Deleting the single LogPipeline is quite fast and the LogPipeline CRD will be deleted
  - The telemetry-operator does not work properly without finding its LogPipeline CRD and stops deleting the finalizers from the remaining LogParsers

**Comment by chrkl** [comment]
@kasiakepka to solve the issue, just delete the finalizers from all remaining LogParser objects.

**Comment by chrkl** [comment]
After we removed the LogParsers from the default installation, this issue became an edge-case and should not appear anymore during regular use of Kyma. We decided not to fix this.
