### ISSUE TITLE
Istio 1.14.3 bump

### ISSUE THREAD

**Issue by strekm** [kyma-project/kyma#15162]
**Description**

Update Istio version to 1.14.3. 

ACs:
- [x] istio images available in external kyma repository
- [x] istio chart updated
- [x] istio reconciler uses istioclt 1.14.3 to install / upgrade istio 
- [x] reconciler bumped in kyma cli and in control-plane
- [x] RN created

**Reasons**

applying security patch

**Current status**
Waiting for https://github.com/kyma-project/control-plane/pull/1980

**Comment by barchw** [comment]
Image syncer: https://github.com/kyma-project/test-infra/pull/5894
Kyma: https://github.com/kyma-project/kyma/pull/15160
Reconciler: https://github.com/kyma-incubator/reconciler/pull/1161
