### ISSUE TITLE
allow switching the loglevel without restarting the component

### ISSUE THREAD

**Issue by friedrichwilken** [kyma-project/kyma#15175]
## Description

Allow changing the loglevel at runtime without restarting the component.

This has as a prerequisite: https://github.com/kyma-project/kyma/issues/15174

## Steps
- [x] make loglevel configureable via configmap for epp
- [x] make loglevel configureable via configmap for ec 
- [ ] allow switching the loglevel without restarting the component

**Comment by k15r** [comment]
the log level will be configured in the eventing cr. With this we do not need a config map watcher to implement this feature
