### ISSUE TITLE
[Telemetry Operator] Investigate possible options to manage the webhook server certificates

### ISSUE THREAD

**Issue by skhalash** [kyma-project/kyma#15195]
**Description**

The validating webhook endpoints of the `telemetry-operator` serve secure traffic via HTTPS. In addition to that, the server cert is signed by a custom CA. The webhook is provided with the CA bundle using the `clientConfig.caBundle` field of the `validatingwebhookconfiguration`. This allows the Kubernetes API server to validate the service CA certificate used to secure the targeted endpoint.

Currently, both the server cert/key and the CA cert/key are generated on the fly using built-in Helm cert management utils. The server cert/key is stored in a k8s `secret`, which is mounted to the `operator` container. The CA cert is set on the `validatingwebhookconfiguration` side. This setup is far from perfect and we are observing some issues described in https://github.com/kyma-project/kyma/issues/15142.

Investigate alternative ways to manage the webhook certificates that fulfill the following conditions:
* CA cert has to be long-living and should not be generated on every reconciliation/app start
* The should be a possibility to automatically rotate the CA and the server certs
* Cert management has to be handled by a third-party infrastructure component and not by the `operator` itself.
* Non-gardener setup needs to be supported

Possible solutions:
* Gardener cert-manager
* Custom cert-manager
* Custom reconciler
* Kyma gateway CA cert

**Comment by a-thaler** [comment]
Serverless team is doing investigations as well it seems: https://sap-btp.slack.com/archives/G01KVRB6K8A/p1661499184446719

**Comment by a-thaler** [comment]
Eventing team is investing as well: https://github.com/kyma-project/kyma/issues/15346

**Comment by raypinto** [comment]
Api gateway is already using self signed and generated certificates for the webhook: https://github.com/kyma-project/api-gateway/blob/main/internal/webhook/certificates.go

**Comment by skhalash** [comment]
From the [concept document](https://github.com/kyma-project/community/pull/709):
>## Conclusion

After some discussions, we came to the conclusion that even though `cert-manager` is a recommended solution, it would be an overkill for our use case. Self-signed certificate generation and rotation is a tiny subset of all `cert-manager` capabilities and can be implemented in future component operators as a part of the modularization strategy.

**Comment by skhalash** [comment]
@tobiscr Any estimates on when you document it? 😄  We are really interested in it

**Comment by tobiscr** [comment]
Oooh.. let's have a call and I will explain it - will be faster and we can directly clarify questions. I will schedule a call :)
