### ISSUE TITLE
Sometime telemetry operator fails to restart fluentbit pod

### ISSUE THREAD

**Issue by rakesh-garimella** [kyma-project/kyma#15199]
**Description**

Af the changes implemented [here](https://github.com/kyma-project/kyma/issues/15118) there is a corner case when fluentbit might not be restarted.

During the installation it can happen that webhook service might not be ready and if the logging chart has been installed before then the operator. In such scenario operator would update the fluentbit configmap but wont be able to add finalizer to pipeline CR (as the webhook service is not ready). In such a scenario the fluentbit restart is missed as currently we return the error when the pipeline CR update fails and requeue the request. In the next interation we only update the CR and not restart the fluentbit

To fix this we should collect the errors from pipeline update and fluentbit restart and then decide to return error and reque the request.

**Comment by chrkl** [comment]
Will be solved with https://github.com/kyma-project/kyma/issues/15956. Closing this issue.
