### ISSUE TITLE
Provide dashboard configuration for LogPipeline and LogParser

### ISSUE THREAD

**Issue by a-thaler** [kyma-project/kyma#15204]
**Description**
The kyma dashboard provides a new extension mechanism to have customised views for resources of a CRD.
Goal is to provide customised views for the LogPipeline and LogParser.

**Criterias**
- New navigation node under "Observability" for a LogPipeline/LogParser
- List view with most important infos like the used output, unsupported mode and status
- Details view making it easy to enter the proper types, especially the secret reference

**Comment by chrkl** [comment]
Initial version of the dashboard extension has been merged with PR https://github.com/kyma-project/kyma/pull/15317. Improvements will be made after our requirements are made available for extensions.
