### ISSUE TITLE
Eventing publisher proxy reports OOM errors under load

### ISSUE THREAD

**Issue by marcobebway** [kyma-project/kyma#15219]
**Description**

The Eventing publisher proxy reports OOM errors under load.

**Steps to reproduce**

- Provision Kyma with evaluation or production profiles.
- Start a high pace load testing with more that 1.5K Events per second.
- The Eventing publisher proxy is unavailable with OOM errors.

**Expected behaviour**
- The Eventing publisher proxy should be available under load.
- It should handle as many requests as it could, and return the proper http status-code if it can't (e.g. `429` with a retry header).

**Comment by marcobebway** [comment]
@VladislavPaskar could you please create follow-up tickets if you haven't done that already?

**Comment by VladislavPaskar** [comment]
> @VladislavPaskar could you please try with more than 1.5K EPS? as per the ticket description:
> 
> > Start a high pace load testing with more that 1.5K Events per second.

@marcobebway in fact, I tried with 2k as well, the result was the same.

**Comment by marcobebway** [comment]
LGTM

**Comment by VladislavPaskar** [comment]
Let's try to address the follow-ups.
