### ISSUE TITLE
 Add a troubleshooting guide of how to handle the the case when JetStream gets disabled

### ISSUE THREAD

**Issue by vpaskar** [kyma-project/kyma#15210]
**Description**

In https://github.com/kyma-project/kyma/issues/14965 we've found out, that JetStream gets disabled when the storage gets full. We would like to add a troubleshooting guide for the users, where we describe how to handle the case, when Jetstream gets disabled and NATS-server is still working and reporting healthy.

**Comment by k15r** [comment]
we cannot reproduce this issue. ATM no need to document the behaviour
