### ISSUE TITLE
NATS container logs are not persisted in Loki

### ISSUE THREAD

**Issue by marcobebway** [kyma-project/kyma#15222]
**Description**

As part of working on [testing the reliability of NATS JetStream](https://github.com/kyma-project/kyma/issues/15010), we could not find the historical NATS logs persisted on Loki.

**Expected behaviour**

The historical NATS logs are persisted and accessible on Loki.

**Comment by nachtmaar** [comment]
**ToDos**
- [ ] Check if we are missing any kind of configuration for Loki for the NATS server(s)
- [ ] Fix the problem

**Comment by VladislavPaskar** [comment]
We don't miss any logs from NATS Backend. The problem is NATS pods do not log lots of information.
