### ISSUE TITLE
Evaluate Kyma Eventing on Azure

### ISSUE THREAD

**Issue by marcobebway** [kyma-project/kyma#15221]
**Description**

As a result of working on [testing the reliability of NATS JetStream](https://github.com/kyma-project/kyma/issues/15010), we discovered that Kyma Eventing does not perform as expected on Azure clusters compared to GCP. Eventing was not able to handle a sustainable load of 200 Events per second for 2 days with the production profile. Ideally, Kyma Eventing should perform similar on Azure and GCP.

**Comment by nachtmaar** [comment]
ToDos
- [ ] Install kyma with production profile on a Gardener Azure cluster ([more details](https://github.com/kyma-project/kyma/issues/15010)
- [ ] Reproduce the bug
- [ ] Investigate why the problem only happens on Azure
- [ ] Try to fix it or discuss it with the NATS folks

@marcobebway Is there anything special required for the azure setup except what is already described in https://github.com/kyma-project/kyma/issues/15010 ?

**Comment by marcobebway** [comment]
> Is there anything special required for the azure setup except what is already described in https://github.com/kyma-project/kyma/issues/15010 ?

No

**Comment by k15r** [comment]
will be covered by the performance evaluation that is executed on all supported hyperscalers
