### ISSUE TITLE
Can't login to Kyma cluster anymore

### ISSUE THREAD

**Issue by pbarbier** [kyma-project/kyma#1522]
Cluster: https://console.sharp-antonelli.cluster.extend.sap.cx

Error message:
![image](https://user-images.githubusercontent.com/250970/48001014-9247cd80-e107-11e8-8753-90a3a2208364.png)

Clickin on top left logo doesn't help
Logout and login again doesn't help
Flush Chrome Application local storage doesn't help

**Comment by mwilczek-net** [comment]
Sometimes kyma needs 15 ~ 20 minutes to allow me to log in again.

On local instalation (minikube) sometimes started working after 1 hour. Once after waiting to long I reinstalled kyma.

Pretty annoying.

**Comment by lszymik** [comment]
We believe that issue is already solved or improved with the recent changes in security.
