### ISSUE TITLE
Remove fluentbit from logging component

### ISSUE THREAD

**Issue by a-thaler** [kyma-project/kyma#15266]
**Description**
After the [Configurable Logging](https://github.com/kyma-project/kyma/issues/11236) feature is released for a while, the migration guide mentions that the old Fluent Bit installation will be removed from the logging chart with Kyma 2.8. Let's do that.

**Criteria**
- `fluent-bit` sub-chart is removed
- values.yaml is cleaned up
- Documentation does not contain any usage of old settings
- No old overrides are used anywhere (prow)
- Assure that release notes are mentioning the removal (incl. a link to the old migration script)
- Check `loki` sub-chart for findings like removing logging SA from the `loki` AuthorizationPolicy

**Comment by chrkl** [comment]
Fluent Bit has been removed from the logging component.
