### ISSUE TITLE
Remove resource race conditions in serverless

### ISSUE THREAD

**Issue by dbadura** [kyma-project/kyma#15268]
**Description**
In serverless we have problem with resources created 2 times:
https://github.com/kyma-project/kyma/blob/main/components/function-controller/internal/controllers/serverless/deployment.go#L61

Let's mitigate the problem with doubled created resources by function controller by creating the object with fixed or predictable name. 
For example:
Create configmap with fixed/predictable name. It can be achieved in two ways:
- use fixed name like `function-name`, instead of function-name-"radomly-generated-hash". 
- implement behavior similar to deployment and it's label `pod-template-hash: 85464ddd6`                                                                                                                                                      

**Reasons**
We won't be able to create the same resource twice .
The source code will be cleaner and easier to maintain.

**Comment by kwiatekus** [comment]
No action , no priority since over a year.
