### ISSUE TITLE
[istio] component tests checking sidecar injection during reconciliation

### ISSUE THREAD

**Issue by strekm** [kyma-project/kyma#15279]
**Description**

Enhance Istio component tests with checking sidecar injection during reconciliation. There's know issue reported to Istio that during Istio installation sidecars might not be injected. Istio reconciler implemented post action to identify workloads w/o sidecars and restarting them. Test should have following scenario:
- create ns labeled with sidecar injection enabled
- run reconciliation
- create workload(s)
- after finished reconciliation workload(s) should have sidecars

ACs:
- [x] istio tests enhanced
- [x] pipeliens green
- [x] workloads created during reconciliation
- [x] workloads have sidecars injected

**Reasons**

reduce effort of manual testing

**Attachments**

**Comment by barchw** [comment]
Pipeline PR: https://github.com/kyma-project/test-infra/pull/5974#issuecomment-1243421352
Test PR: https://github.com/kyma-project/kyma/pull/15388
