### ISSUE TITLE
Kyma OS documentation: point out that downgrades are officially not supported in Kyma 

### ISSUE THREAD

**Issue by tobiscr** [kyma-project/kyma#15284]
**Description**

We got a [request from a customer](https://github.com/kyma-project/kyma/issues/15033) to improve our documentation in regards to upgrades and downgrades of Kyma. Currently, our online documentation covers only upgrades of Kyma. We should extend this section and point out, that downgrades are officially not supported (no explicity testing happens and also the tooling like the Kyma CLI is not prepared to support downgrades).

Such a section could be handled as separate menu item like `Operation Guide > Operations > Downgrade Kyma`.

**Area**

Kyma operations (see https://kyma-project.io/docs/kyma/main/04-operation-guides/operations/)

**Reasons**

Documentation lacks the downgrade section.

**Assignees**

@kyma/technical-writers

**Attachments**

**Comment by grego952** [comment]
Since we do not support the downgrades, is it really necessary to create a separate document? Maybe it's enough that we mention that as a note or warning in the [Upgrade Kyma](https://kyma-project.io/docs/kyma/main/04-operation-guides/operations/05-upgrade-kyma/) doc?

**Comment by jeremyharisch** [comment]
Instead of having a full page to declare, that downgrades are not supported, I suggest to put a Caution Note instead.

Please have a look at my suggestion: #15508
