### ISSUE TITLE
Remove default scale config preset

### ISSUE THREAD

**Issue by dbadura** [kyma-project/kyma#15291]
**Description**
In function CR there are two fields connected with replicas:
- scaleConfig 
- replicas

Serverless has default scale config preset which is not needed because if user decide to use `scaleConfig`, the min/max field are required to be set.
Additionally the `replicas` field should be the default configuration about replicas

**Reasons**

In v1alpha2 the min/max values in scaleConfig are required, so the default scale config preset is not needed and it should be deleted

**Attachments**

**Comment by kwiatekus** [comment]
Closing in favor of https://github.com/kyma-project/kyma/issues/14900
