### ISSUE TITLE
Make eventing available in Kyma (w/o application Connector)

### ISSUE THREAD

**Issue by akrausesap** [kyma-project/kyma#153]
Confirm these statements before you submit the issue:

- [X] I have searched open and closed issues for duplicates.
- [X] I have read the contributing guidelines.
---

**Description**

Dear Colleagues,

Kyma allows for event-driven extensibility. So far this feature is tightly coupled to the Application Connector (Binding, Event Registration, etc.). However I can see use cases where services running within the same Kubernetes cluster are also raising and consuming events themselves. 

**Reasons**
To avoid the overhead (development complexity and runtime) of the application connector it would be cool to have a internal API as well.

**Attachments**

N/A

**Comment by abbi-gaurav** [comment]
@akrausesap Eventing is at present possible inside Kyma. Please refer to [this example](https://github.com/kyma-project/examples/tree/master/event-subscription/service) and the [API docs](https://github.com/kyma-project/kyma/blob/master/components/event-bus/docs/api.yaml). 

Please note that the API is currently evolving and could change in the future.

**Comment by abbi-gaurav** [comment]
Closing this as we currently support eventing inside Kyma. Details shared in the comment above.
