### ISSUE TITLE
Fix validation and defaulting of function dependencies in v1alpha2

### ISSUE THREAD

**Issue by kwiatekus** [kyma-project/kyma#15339]
Validation and defaulting of function dependencies works differently in v1alpha2 comparing to v1alpha1.
This results with broken UX in busola

**Actual behaviour**
- we do not default the value in case user leaves it empty
- if user provides empty string we read it as no value
For those two cases the stored function is w/o dependencies and its not editable in Kyma UI unless user provides a valid json as dependencies 

![Image](https://user-images.githubusercontent.com/6783567/187863707-94e680f8-62d5-48da-ba48-7ffa8c204934.png)

**Expected behaviour**
 - when user doesnt provide dependencies it should be defaulted with empty json
 - when user provides any value it should be validated it is a parsable JSON

**Reason**
The defaulting and validation should be consistent with v1alpha1 not to cause surprises in the Kyma UI

**Comment by pPrecel** [comment]
This ticket is related with the busola's codebase only. On the controller's side we are handling cases when a user does not provide any `dependencies` field. If I'm not wrong, [here](https://github.com/kyma-project/busola/blob/main/core-ui/src/components/Functions/helpers/runtime/runtime.js#L75) is the line where the busola is checking if dependencies are JSON, problem is we have to check if deps are JSON only when a string is not empty.

**Comment by pPrecel** [comment]
I figure out not only our webhooks may have such problems. I found same annotation in the telemetry webhook:

```bash
 kubectl get MutatingWebhookConfiguration -A -ojson | jq '.items[] | select(.metadata.annotations | has("gardener.cloud/warning")) | .metadata.name'

"converting.webhook.serverless.kyma-project.io"
"defaulting.webhook.serverless.kyma-project.io"
```

&&

```bash
kubectl get ValidatingWebhookConfiguration -A -ojson | jq '.items[] | select(.metadata.annotations | has("gardener.cloud/warning")) | .metadata.name'

"validation.webhook.serverless.kyma-project.io"
"validation.webhook.telemetry.kyma-project.io"
```
