### ISSUE TITLE
Study a real world well written k8s controller and present the learnings from it [TB: 3]

### ISSUE THREAD

**Issue by marcobebway** [kyma-project/kyma#15351]
**Description**

Study a real world well written k8s controller and present the learnings from it (controller architecture and testing).

**Comment by muralov** [comment]
Here is the [recording](https://sap.sharepoint.com/:v:/r/teams/SkydivingTunas/Shared%20Documents/General/Recordings/Meeting%20in%20_General_-20220908_111010-Meeting%20Recording.mp4?csf=1&web=1&e=9n7WOd) sharing the results of the investigation.
