### ISSUE TITLE
Separate the unit, integration and component tests and let them be run by separate entrypoints ( go test or make target)

### ISSUE THREAD

**Issue by marcobebway** [kyma-project/kyma#15352]
**Description**

Separate the unit, integration and component tests and let them be run by separate entry points (go test or make target).

> Note: This might be helpful: https://mickey.dev/posts/go-build-tags-testing/.

**AC**
- [x] #15861
- [x] #15863
- [ ] Document the build tag flow and the conventions for naming and separating test files 
- [ ] Enable the disabled linters(i.e. testpackage as part of this [PR](https://github.com/kyma-project/kyma/pull/15762))

**Comment by friedrichwilken** [comment]
#15489

**Comment by k15r** [comment]
individual test can already be executed using go test / goland. no need to invest so much time to introduce this feature
