### ISSUE TITLE
migrate BEB controller to use new CRD version

### ISSUE THREAD

**Issue by k15r** [kyma-project/kyma#15364]
Acceptance

- [ ] use new crd in BEB handler and controller
   - [x] Handler
   - [ ] Reconciler
- [ ] Update tests relevant to these.

**Comment by mfaizanse** [comment]
PR to feature-branch: https://github.com/raypinto/kyma/pull/90

**Comment by mfaizanse** [comment]
PR for common: https://github.com/kyma-project/kyma/pull/15582

**Comment by mfaizanse** [comment]
1. Uncomment the line `- patches/cainjection_in_eventingbackends.yaml` in `/config/crd/kustomization.yaml`.
2. `export ENABLE_NEW_CRD_VERSION=true`
3. `make manifests-local`
4. `make copy-crds`
5. Change the `enableNewCRDVersion` flag to `true` in helm chart.
6. `kyma deploy --source=local --workspace=$HOME/git/mfaizanse/kyma --component=eventing`
