### ISSUE TITLE
migrate NATS/Jetstream controller to use new CRD version

### ISSUE THREAD

**Issue by k15r** [kyma-project/kyma#15363]
Acceptance
- [ ] use new crd in controller and tests

**Comment by raypinto** [comment]
Current status:
Backend/Handler PR: https://github.com/kyma-project/kyma/pull/15647
Reconciler is in progress. Should be ready for review next week.

**Comment by raypinto** [comment]
The reconciler implementation with unit tests are part of [this PR](https://github.com/kyma-project/kyma/pull/15722).
The integration tests will be added as part of [this issue](https://github.com/kyma-project/kyma/issues/15706).
