### ISSUE TITLE
changes in `nats-eventing-secret` should trigger `nats-config-reloader`.

### ISSUE THREAD

**Issue by friedrichwilken** [kyma-project/kyma#15377]
in eventing we have this [`configmap`](https://github.com/kyma-project/kyma/blob/main/resources/eventing/charts/nats/templates/configmap.yaml) to configure the `nats-server`. when changes are done to it, the [`config-reloader`](https://github.com/kyma-project/kyma/blob/1f93f1574816d571ffe675d2f8298aec3e71e3e2/resources/eventing/charts/nats/templates/statefulset.yaml#L98) will reload the config for the [`nats-server`](https://github.com/kyma-project/kyma/blob/1f93f1574816d571ffe675d2f8298aec3e71e3e2/resources/eventing/charts/nats/templates/statefulset.yaml#L146) and so apply the changes.

eventing also has as secret dubbed [`eventing-nats-secret`](https://github.com/kyma-project/kyma/blob/main/resources/eventing/charts/nats/templates/secret.yaml) to access the `nats-server` with `system account` privileges. however if changes are done to it --including its deletion and recreation by the reconciler-- the changes will not be applied. 

- [ ] make the `config-reloader` also get triggered by changes in `eventing-nats-secret`

for clarification: when the `config-reloader` gets triggered by changes in `configMap` it will also reload the changes in the secret.

ideas how this could be done:
- [here](https://github.com/kyma-project/kyma/blob/1f93f1574816d571ffe675d2f8298aec3e71e3e2/resources/eventing/charts/nats/templates/statefulset.yaml#L106) the config-reloader will set to watch the configmap. can it be set up to also watch the secret?

---

Here is an overview; the dotted arrow is the wanted feature that is described in this issue:
```mermaid
flowchart
subgraph kymasystem[namespace: kyma-system]
	subgraph podnats[pod: eventing-nats-n]
		containernatsserver[container: nats-server]
		containerconfigreloader[container: config-reloader]
	end
	secret[secret: eventing-nats-server]
	configmap[configMap: eventing-nats-config]
end

containernatsserver--mounts-->secret
containernatsserver--mounts-->configmap

containerconfigreloader--watches-->configmap
containerconfigreloader-.watches.->secret

containerconfigreloader--triggers reload-->containernatsserver
```

**Comment by k15r** [comment]
already implemented
