### ISSUE TITLE
Evaluate using eBPF instead of iptables in Kyma Istio

### ISSUE THREAD

**Issue by cnvergence** [kyma-project/kyma#15393]
**Description**
Open source project called Merbridge is designed to make traffic interception and forwarding more efficient for service mesh. It replaced iptables with eBPF. 
The packet datapath can be shortened directly from one socket to another destination socket.

The data path between pods in service mesh on the same node without eBPF:
![image](https://user-images.githubusercontent.com/26778356/188896779-d5639033-c306-462c-be82-e38e62282feb.png)
The data path between pods in service mesh on the same node with eBPF:
![image](https://user-images.githubusercontent.com/26778356/188897750-fcbe775b-b107-4705-bc7e-3b8dead31dc8.png)

**Reasons**
While merbridge is still at early phase, using eBPF in service mesh will definitely gain more momentum in the future.
By replacing iptables with eBPF, the data transportation process can be accelerated in a mesh scenario. At the same time, Istio will not be changed at all. This means if you do not want to use eBPF any more, just delete the DaemonSet, and the datapath will be reverted to the traditional iptables-based routing without any problems.

**Attachments**
- https://istio.io/latest/blog/2022/merbridge/
- https://github.com/merbridge/merbridge
- https://istio.io/latest/zh/blog/2021/istiomeetups-china-report/IstioMeetupChina-AccelerateServiceMeshNetworkwithebpf.pdf

**Comment by strekm** [comment]
leaving it closed as we do not plan to implement it in near future
