### ISSUE TITLE
Kiali tutorial

### ISSUE THREAD

**Issue by a-thaler** [kyma-project/kyma#15410]
**Description**

Following the new [Strategy](https://github.com/kyma-project/community/blob/main/concepts/observability-strategy/strategy.md), deprecation of the Kiali component must happen. In order to execute that, a replacement in the shape of a tutorial needs to be ready. So the goal is to have a tutorial on how to deploy Kiali in a self-managed manner into a Kyma runtime, having a similar good integration experience as it is now. Hereby, it is essential to not copy anything from upstream to have a very low maintenance effort.

**Criteria**
- have a tutorial on how to deploy Kiali via helm
- outline how to expose Kiali (point to built-in feature) but do not activate anything, just describe port-forward
- tutorial artifacts should be usable in automated tests (own resources in a repository, not in-line markdown)
- do not copy the upstream chart anywhere
- mention Jaeger and Grafana configuration options but have it disabled
- Proposed deployment should be
  - integrated with Prometheus/Istio/Grafana/Jaeger (as it is already)
  - not exposed (drop oauth2-proxy)
  - based on Kiali operator (check what is recommended)

**Comment by a-thaler** [comment]
I created an initial PR already which is not finished yet

**Comment by chrkl** [comment]
The example has been provided by PRs https://github.com/kyma-project/examples/pull/207 and https://github.com/kyma-project/examples/pull/210. https://github.com/kyma-project/kyma/pull/15707 linked the example to the Kyma docs and added a deprecation warning.
