### ISSUE TITLE
UI for modular Kyma

### ISSUE THREAD

**Issue by arturskorupa** [kyma-project/kyma#15426]
## Description

Kyma Dashboard provides UI for configuring modules (enable/disable module, select Release Channel). Dashboard adjusts its UI to  the selected set of modules (views for disabled modules are not displayed).

Detailed description of particular requirements is in attached issues.

## Acceptance Criteria
- [x] Dashboard displays a list of available Kyma modules and let user to enable/disable selected ones
- [x] Along with enabling the module, a release channel can be selected   
- [ ] ~catalog CR defined and aligned for the discovery of available modules~ ModuleTemplate will be used instead and adjusted to contain the right metadata
- [x] Dashboard displays a configuration page for selected modules and does not display it for disabled ones (leveraging extendability mechanism)

**Links**
- [Concept document](https://github.com/kyma-project/community/tree/main/concepts/modularization)
- [Transition plan ](https://github.com/kyma-project/community/blob/main/concepts/modularization/transition.md)
- [Lifecycle manager](https://github.com/kyma-project/lifecycle-manager)
- [Module manager](https://github.com/kyma-project/module-manager)

**Comment by jakobmoellersap** [comment]
- [ ] catalog CR defined and aligned for discovery of modules

**Comment by valentinvieriu** [comment]
we will evaluate the feasibility of synchronizing the ModuleTemplate to the SKR Cluster and adjust them so that they can be used by the UI to display the list of available Modules.

If we decide to use ModuleTemplate we will need to adjust the fields so that we have Human Readable fields that can be rendered in UI – things like description, categories ( to be decided )

**Comment by valentinvieriu** [comment]
We decided not to use a Catalog CR but instead sync ModuleTemplate to the target cluster and use those instead.
We will have to adjust the ModuleTemplate to contain some user-facing metadata

**Comment by valentinvieriu** [comment]
- [ ] We need to agree on what type of extra metadata is needed for ModuleTemplate to improve the UX.
- [ ] We need to improve the visual appearance - consider wizard style and deep link

**Comment by valentinvieriu** [comment]
I consider this task closed. The above improvements are not critical and we will add them as we go.
