### ISSUE TITLE
Serverless module development on a "preview" plan with delivery process E2E

### ISSUE THREAD

**Issue by arturskorupa** [kyma-project/kyma#15429]
## Description

An existing Kyma component Serverless is redesigned to the modular architecture according to the guidelines and can be operated by the `Lifecycle Manager` running both locally and with the `Lifecycle Manager` running as a central service.

Serverless module brings pipeline to build and test conformance with the `Lifecycle Manager`. Respective documentation is created.

Detailed description of particular requirements is in attached issues.

## Acceptance Criteria

- [ ] Serverless is developed according to the architecture guidelines
https://github.com/kyma-project/kyma/issues/15856
   - [x] design and discuss configurability and dependencies of modular serverless
   https://github.com/kyma-project/serverless-manager/issues/3  
   - [x] scaffold serverless manager in a dedicated repository under `kyma-project`
   https://github.com/kyma-project/kyma/issues/15858 
   - [x] dependency management (Serverless can detect its optional dependencies and assumes default configuration)
    https://github.com/kyma-project/serverless-manager/issues/6 (in Progress)
   - [ ] Module has pipeline for building the binary image, assuring all needed quality standards and running conformance tests
   https://github.com/kyma-project/serverless-manager/issues/22

- [x] Serverless module is operated by `Lifecycle Manager`, both installed locally. It is optional module of Kyma, can be disabled/enabled by user (it should trigger installation/uninstallation of module's subcomponents)
- [ ] Serverless module is operated by `Lifecycle Manager` running as a central service (dev/stage/prod, introduced in kyma-project/kyma#15443). It is optional module of Kyma, can be disabled/enabled by user (it should trigger installation/uninstallation of module's subcomponents)
https://github.com/kyma-project/serverless-manager/issues/40

- [ ] Semi-automatic _Module submission process_ (PR with respective `ModuleTemplate` that will be used to deliver `keda-manager` to selected release channel is created manually)
https://github.com/kyma-project/serverless-manager/issues/40

- [ ] Frontrunner module renders its UI according to the available feature set (e.g. UI for configuration for  missing module dependencies is not rendered)
https://github.com/kyma-project/kyma/issues/16234

- [ ] https://github.com/kyma-project/serverless-manager/issues/39

- Core module tests implemented according to [test strategy](https://github.tools.sap/pandas/testing-strategy/tree/master/modularisation/governance/operational_test_management):
  - [ ] Conformance tests (run against `serverless-module` and `ModuleTemplate` that is going to be published) 
  https://github.com/kyma-project/serverless-manager/issues/41
  - [ ] Integration test (including the deletion without orphan resources check)
  https://github.com/kyma-project/serverless-manager/issues/42

**Links**
- [Concept document](https://github.com/kyma-project/community/tree/main/concepts/modularization)
- [Transition plan ](https://github.com/kyma-project/community/blob/main/concepts/modularization/transition.md)
- [Lifecycle manager](https://github.com/kyma-project/lifecycle-manager)
- [Module manager](https://github.com/kyma-project/module-manager)
- https://github.com/kyma-project/kyma/issues/15856

**Comment by Disper** [comment]
- blocked by https://github.com/kyma-project/test-infra/issues/6728 
- waiting until https://github.com/kyma-project/lifecycle-manager/pull/351 will be propagated to kyma-cli

**Comment by kwiatekus** [comment]
Because we needed to shift the priorities in the team (towards the crown jewels topic) we are progressing slower than anticipated. Additionally we had to heavily refactor reconciliation logic by dropping the declarative library that was not fitting our complex installation cases with optional dependencies.

 - We still need to configure CI jobs that would build artefacts for pre-submit (PRs) and post-submit (main) stages.
 - We are still missing basic integration tests of the serverless module installed on the modular kyma.
 - We are missing conformance checks (test optional dependencies, upgradability test, etc..)

We definitely need more time to finalise serverless manager together with its E2E testing
I'd set the 20th February as a new target date

**Comment by kwiatekus** [comment]
We have configured CI jobs that would build artefacts for pre-submit (PRs) and post-submit (main) stages.
We need to work on 
 - configurability towards external docker registry 
 - auto-configurability for internal docker registry
 - auto-configurability for tracing and eventing integrations
 
 The development goes much slower than assumed. We are developing against alpha kyma CLI. We are forced to overcome very frequent regressions towards lifecycle manager and kyma alpha commands.
 
 I need to push the date to April 1st
