### ISSUE TITLE
Identify memory/cpu limits for fluent-bit on a cluster with hight log rate

### ISSUE THREAD

**Issue by rakesh-garimella** [kyma-project/kyma#15439]
**Description**

There can be scenarios where the Kyma cluster could have a setup with deployments that have extremely high replica count and all the pods logging heavily. The previous memory limits of 256 Mi is usually not enough in such scenarios.

* Identify which part of logpipeline is creating heavy memory consumption like filter, rewrite tag, outputs etc
* Try to come up with mem/cpu values that would be enough to cover all scenarios

**Comment by chrkl** [comment]
Investigations have shown that Fluent Bit's resource usage increases while utilizing the filesystem buffer heavily. This situation can be triggered on a Kyma cluster when Loki's ingestion rate limit is reached. Our investigations have shown that the resource limits that have been introduced with PR https://github.com/kyma-project/kyma/pull/15409 are sufficient even under high log load.
