### ISSUE TITLE
Concept of Module governance model

### ISSUE THREAD

**Issue by arturskorupa** [kyma-project/kyma#15436]
## Description

Module governance is a set of principal guidelines for module owners to let them access Kyma module ecosystem with their modules. The governance basically covers the whole lifecycle of the module, starting from assessing build decision of a module, through the development in alignment to the Module Development Guideline and all activities performed after module entered the Kyma ecosystem for a first time (next releases of the module).

## Acceptance Criteria

- [ ] Principal rules of governance for Kyma modules are defined, including module lifecycle and responsibilities for module owners
- [ ] Governance checks are defined in regards to the particular stages of module lifecycle
- [ ] Module Development Guide is defined  
- [ ] Submission form for 3rd party module is defined
 

**Links**
- [Concept document](https://github.com/kyma-project/community/tree/main/concepts/modularization)
- [Transition plan ](https://github.com/kyma-project/community/blob/main/concepts/modularization/transition.md)
- [Lifecycle manager](https://github.com/kyma-project/lifecycle-manager)
- [Module manager](https://github.com/kyma-project/module-manager)

**Comment by jakobmoellersap** [comment]
Is this module conformance already defined? Ideally we want to include it in the module bundling as well as the E2E verification. @clebs fyi

**Comment by arturskorupa** [comment]
@jakobmoellersap I need to think where the module conformance will be defined. It is now being discussed more closer to the Release process than to the governance who is mean more to focus on a higher level domain - the whole module lifecycle, without going into details of particular check being performed.

**Comment by arturskorupa** [comment]
governance model for OS modules are not in scope of the project yet. We governance for modules in SKR.
