### ISSUE TITLE
Release strategy for modular Kyma

### ISSUE THREAD

**Issue by arturskorupa** [kyma-project/kyma#15431]
## Description

Definition of the `Release Strategy` for modularised Kyma. Leverage the concept of [Release Channels](https://github.com/kyma-project/kyma/issues/15430) and add a strategy of promoting deliveries from one channel to another, define possibility of migration between channels and different versions of module. 
Other current parts of release process must be checked against the new strategy (what's new communication, changelog, team definition of readiness).  

## Acceptance Criteria

- [x] Release strategy is documented and available to module development teams (microdelivery)
- [x] Release channel approach is compliant with OS and corporate standards (release snapshot for OS, microdelivery)
- [x] Release strategy is confirmed with standard requirements from SRE teams
- [x] What's new communication is defined
- [x] The way of handling module Changelog is defined
- [x] Strategy of promotion of deliveries between release channels is defined
- [x] Release strategy is aligned with contract statements
- [x] Security validation process is set up 
- [x] Policy of migration for a module already running in workload between from one release channel to another is defined
- [x] [Mechanism](https://wiki.one.int.sap/wiki/display/kyma/Microdelivery+and+Testing+Strategy#MicrodeliveryandTestingStrategy-Backwardcompatibilitycheck) for assuring compatibility between different versions of dependant components is defined
- [x] Define a Code structure to assure an independent release process for modules (mono-repo approach vs multiple repos to enable doing releases and security scanning in an easy way )  
- [x] A module submission process is defined and implemented. It should let module to be delivered E2E to a target environment with all mandatory checks run in the middle (leverage governance checklist (https://github.com/kyma-project/kyma/issues/15436) and conformance tests (https://github.com/kyma-project/kyma/issues/15425))
- [x] The module uses any 3rd party component in alpha version cannot be released to any stable channels with SLA  

**Links**
- [Concept document](https://github.com/kyma-project/community/tree/main/concepts/modularization)
- [Transition plan ](https://github.com/kyma-project/community/blob/main/concepts/modularization/transition.md)
- [Lifecycle manager](https://github.com/kyma-project/lifecycle-manager)
- [Module manager](https://github.com/kyma-project/module-manager)

**Comment by zhoujing2022** [comment]
initial Release Strategy: https://wiki.one.int.sap/wiki/display/kyma/Microdelivery+Strategy.  (Still improving)

**Comment by zhoujing2022** [comment]
https://wiki.one.int.sap/wiki/display/kyma/Modular+Kyma+Release+Strategy

**Comment by zhoujing2022** [comment]
Open Question:
- Delivery Approach of Release Note.
- Communication Strategy (General Information, Release Communication, Maintenance Communication, Direct Communication)
- Review Breaking Change Process.

**Comment by zhoujing2022** [comment]
All planned tasks are done. This ticket will be closed. for the additional topics like communication strategy, breaking change strategy, approach for working with Sirius, I will create a separate Task for the next quarter.
