### ISSUE TITLE
Concept of release channels for modular Kyma

### ISSUE THREAD

**Issue by arturskorupa** [kyma-project/kyma#15430]
## Description

The concept of release channels is described and validated against use for OS and corporate release processes.

## Acceptance Criteria

- [x] The concept of release channels is validated against use for OS and corporate release processes and consulted with stakeholders of the release process (module development teams, SRE)
- [x] A deployment rings can be implement by users (user can get upfront changes planned for a release in stable channel in coming days)
- [x] Team who uses module from alpha channel for evaluation (module frontrunner) is properly informed about limitations of the alpha channel (no SLA, possible lack of backward compatilbity, module removal)     
- [x] A way of receiving feedback from alpha module frontrunners is established
   

**Links**
- [Concept document](https://github.com/kyma-project/community/tree/main/concepts/modularization)
- [Transition plan ](https://github.com/kyma-project/community/blob/main/concepts/modularization/transition.md)
- [Lifecycle manager](https://github.com/kyma-project/lifecycle-manager)
- [Module manager](https://github.com/kyma-project/module-manager)

**Comment by jakobmoellersap** [comment]
I would need to know here where the release channels are defined and how they are governed since they are only a field in the Kyma Resource in a Cluster right now. What is a deployment ring concretely?

**Comment by arturskorupa** [comment]
@jakobmoellersap the first concept of release channels is [here](https://github.com/kyma-project/kyma/issues/15431), @pbochynski can maybe adjust the description as we already discussed more details. Still alpha channel concept is discussed.

_Deployment ring_ can be implemented with fast and regular release channel. New version of the component is put first to _fast_ channel, then after some agreed amount of time it's promoted to the _regular_ channel. Users are free to decide if they take fast version or wait on regular channel to get it.

**Comment by jakobmoellersap** [comment]
For the three pending Acceptance Criteria, there is no sufficient input from Governance stream to actually implement this. We will need more detailed input on how to implement these points

**Comment by pbochynski** [comment]
Q3 is over. Please update the timeline.

**Comment by zhoujing2022** [comment]
initial Version:
https://wiki.one.int.sap/wiki/display/kyma/Modular+Kyma+Release+Concept.
Still under reviewing.

**Comment by zhoujing2022** [comment]
Review Session 1 is over. The follow-up Session will be organized, when PB is finished with the redesign of the channels.

**Comment by jakobmoellersap** [comment]
Concept Deadline was set for 18. Nov. What's the current state here?

**Comment by zhoujing2022** [comment]
under review with POs. I will update the deadline, thx.

**Comment by zhoujing2022** [comment]
Alpha Channel Solution (incl. the restrict term of use) is still in discussion. Review and approval from CQ Team and Legal are needed. Maybe we start to think about Plan-B.

**Comment by zhoujing2022** [comment]
It has been presented in the SIG Quality Meeting on 11.01.2023. Currently there are no open questions. Ticket will be closed. Improvements will continue.
