### ISSUE TITLE
Frontrunner modules managed by Lifecycle manager in regular Kyma plans

### ISSUE THREAD

**Issue by arturskorupa** [kyma-project/kyma#15446]
## Description

Frontrunner modules (#15429 and #15427) in regular Kyma plans are managed by new `Lifecycle manager` and not managed by central `Kyma Reconciler`. 

The migration process is required only for the modules that replace existing components installed by reconciler. The biggest challenge in the migration process is to ensure that new operator is not competing with reconciler (they should not manage the same resources). It will be resolved by:
- [x] https://github.com/kyma-incubator/reconciler/issues/1306

The second challenge is how to test new operators in the SKR before making it available all customers. The problem will be solved with:
- [x] https://github.com/kyma-project/lifecycle-manager/issues/457

Independently from the issues above teams can prepare themselves for migrating their components. The checklist for each module:
- develop and release the module operator and prepare the module template for that release
- provision the SKR cluster with the module installed and managed by reconciler
- install module template in the SKR and enable module in the Kyma CR
- verify that reconciler stops to reconcile the component and the new operator takes over the resources created by reconciler without disruptions for any workload using the module features
- inform SRE that your migration path is ready and plan together the migration of existing clusters
- release a version of Kyma without migrated component
- execute migration for existing clusters
- update Kyma to the version without a migrated component (execute the previous step for clusters created after migration was completed and before new version was published)

Remarks:
- If your module requires customised configuration (custom resource) for existing clusters (e.g. different spec for trial clusters) enable module with `customResourcePolicy=Ignore` and provide the module CR for each cluster (required by SRE for migration procedure)
- The end to end test on production environment should not replace your fast development environment - it is just last sanity check. Test upgrade from reconciler to your operator in local k3s/k3d cluster without waiting for big managed cluster. You can setup current component with kyma CLI and apply your operator with kubectl. You should already discover 99% of issues.
- Provide a way to test quickly your operator. Module template and lifecycle manager is not essential for that test. You can save a lot of time having a way to start your operator just with kubectl apply.
- You can do end-2-end test on production environment even now.  Just provision SKR, disable reconciliation (from KCP CLI) and apply your operator in the cluster.

Detailed description of particular requirements is in attached issues.

## Acceptance Criteria

- [x] KEB manages both reconciler and lifecycle manager on dev and stage [end of Q4/2022, PK]
- [ ] KEB manages both reconciler and lifecycle manager on prod [Q1/2023, PK]
- [ ] Frontrunner modules are disabled in `Kyma Reconciler` and enabled in `Lifecycle manager` for new created modules on **dev** environment [Q4/2022]
- [ ] Frontrunner modules are disabled in `Kyma Reconciler` and enabled in `Lifecycle manager` for new created modules on  **stage** environment  (after it worked fine for 1 weeks on dev)
- [ ] Frontrunner modules are disabled in `Kyma Reconciler` and enabled in `Lifecycle manager` for new created modules **prod** environment (after it worked fine for 2 weeks on stage)
- [ ] Frontrunner modules are disabled in `Kyma Reconciler` and enabled in `Lifecycle manager` for existing modules on **dev** environment 
- [ ] Frontrunner modules are disabled in `Kyma Reconciler` and enabled in `Lifecycle manager` for existing modules on **stage** environment (after it worked fine for 1 weeks on dev)
- [ ] Frontrunner modules are disabled in `Kyma Reconciler` and enabled in `Lifecycle manager` for existing modules on **prod** environment (after it worked fine for 2 weeks on stage)
- [ ] Frontrunner module are fully managable by cluster admin (disable / enable) with Kyma CR
- [ ] Frontrunner module are fully managable by cluster admin (disable / enable) with Dashboard ) (#15426)
  
- [ ] Documentation of frontrunner modules reflects above changes and is ready for release to end users
- https://github.com/kyma-project/serverless-manager/issues/33 
- https://github.com/kyma-project/keda-manager/issues/80
- https://github.com/kyma-project/kyma/issues/16421

**Links**
- [Concept document](https://github.com/kyma-project/community/tree/main/concepts/modularization)
- [Transition plan ](https://github.com/kyma-project/community/blob/main/concepts/modularization/transition.md)
- [Lifecycle manager](https://github.com/kyma-project/lifecycle-manager)
- [Module manager](https://github.com/kyma-project/module-manager)

**Comment by arturskorupa** [comment]
2b

**Comment by pbochynski** [comment]
Migration plan from reconciler to lifecycle-manager is here: https://github.com/kyma-project/community/blob/main/concepts/modularization/migration.md
