### ISSUE TITLE
Unable to delete ServiceBinding from Lambda UI

### ISSUE THREAD

**Issue by PK85** [kyma-project/kyma#1546]
**Description:**
- Deletion action works only if user has created a ServiceBinding via Lambda UI with selected option "create new secret for binding" (It means SBU is deleted and SB stays untouched)
- Deletion action does nothing in other cases which is:
  -  if user has created a ServiceBinding via Lambda UI with selected select existing secret for binding.
  - if user has created a ServiceBinding from ServiceCatalog view.

**How to reproduce**
Create a Redis Service instance (plan Basic to speedup provisioning process) and execute steps from description.

**Expected behaviour**
Always delete SBU and SB stays untouched.

**Existing workaround**
Delete given SBU, SB from ServiceInstance view.

**Comment by PK85** [comment]
Hello @venturasr, what is a progress here?

**Comment by rakesh-garimella** [comment]
Hi @PK85  This works as designed. We are deleting the stuff we are creating. If some one is reusing `servicebinding` or `servicebindingusage`.

**Comment by venturasr** [comment]
New PR:  https://github.com/kyma-project/console/pull/395 fixing #349
