### ISSUE TITLE
Application Gateway tests - ReverseProxy forward 1xx responses

### ISSUE THREAD

**Issue by mvshao** [kyma-project/kyma#15471]
**Description**
Golang in version 1.19 doesn't correctly forward 1xx code response, due to regression between 1.18.3 and 1.19 versions.
Golang community planned to patch responses in the 1.20 version.
For now, we are removing the failed test case in #15421. We will restore it when the Go version will again properly support this functionality. You can find more info [here, at the official Golang GitHub issue](https://github.com/golang/go/issues/26088)

**Comment by akgalwas** [comment]
It is not critical.
