### ISSUE TITLE
Configurable Application Gateway

### ISSUE THREAD

**Issue by janmedrek** [kyma-project/kyma#15526]
**What:** Provide more ways for configuring the behaviour of Application Gateway. This includes toggles for URL decoding, redirect handling, configurable timeouts etc.

**Gains:**

- **Kyma Users** will be able to tailor the behaviour of Application Gateway to suit their needs. It will provide better integration and a more customizable experience when it comes to connecting external systems to Kyma.

**Reasons:** There were multiple requests coming from the customers to expose various parameters for user configuration, we want to provide a customizable solution that users will be able to leverage not only for SAP systems but for any external API they would like to use.

**Comment by koala7659** [comment]
Closing as application gateway is moving to new modular architecture with own UI
