### ISSUE TITLE
Add a new prow pre-main job with this Flag enabled.

### ISSUE THREAD

**Issue by mfaizanse** [kyma-project/kyma#15521]
Once we have the [feature flag](https://github.com/kyma-project/kyma/issues/15518) to enable new Subscription CRD, we need a new pre-main job to run the tests with the feature flag enables.

- [x] Fast-integration tests with new CRD
- [x] gcp-eventing pipeline with the new CRD

Followup:
- [ ] #15815

**Comment by mfaizanse** [comment]
How to deploy new CRD:
1. Uncomment the line `- patches/cainjection_in_eventingbackends.yaml` in `/config/crd/kustomization.yaml`.
2. `export ENABLE_NEW_CRD_VERSION=true`
3. `make manifests-local`
4. `make copy-crds`
5. Change the `enableNewCRDVersion` flag to `true` in helm chart.
6. `kyma deploy --source=local --workspace=$HOME/git/mfaizanse/kyma --component=eventing`

**Comment by mfaizanse** [comment]
Check if this is pre-requisite: https://github.com/kyma-project/kyma/issues/15684

**Comment by nachtmaar** [comment]
Idea: let's duplicate the normal eventing + the upgrade tests on prow

**Comment by raypinto** [comment]
I agree with @mfaizanse that [this](https://github.com/kyma-project/kyma/issues/15684) is a pre requisite to this ticket!
And yes we need the upgrade job as well!

**Comment by raypinto** [comment]
For the fast-integration tests: 
we need to obtain the ENV variable "ENABLE_NEW_CRD" and based on this value check the relevant fields of the spec (for eg: Spec.CleanEventTypes will now be Spec.Types)
