### ISSUE TITLE
CLI support for Kyma module deployment and enabling

### ISSUE THREAD

**Issue by tobiscr** [kyma-project/kyma#15567]
## Description

Kyma CLI supports the deployment, enabling and disabling of Kyma modules.

Detailed description of particular requirements is in attached issues.

## Acceptance Criteria
- [x] Module can be installed  (https://github.com/kyma-project/cli/issues/1318)  [Q4/2022]
- [ ] Module can be enabled/disabled by editing Kyma CR (https://github.com/kyma-project/cli/issues/1328) [Q4/2022]

**Links**
- [Concept document](https://github.com/kyma-project/community/tree/main/concepts/modularization)
- [Transition plan ](https://github.com/kyma-project/community/blob/main/concepts/modularization/transition.md)
- [Lifecycle manager](https://github.com/kyma-project/lifecycle-manager)
- [Module manager](https://github.com/kyma-project/module-manager)

**Comment by jakobmoellersap** [comment]
Changed Due Date to 31. Jan as we still have internal discussions on what exactly we want to support for the CLI enable/disable set. I am currently still propagating that kubectl should be sufficient on top of Busola but we will have to wait for the discussion results.

**Comment by janmedrek** [comment]
Will be tracked by: https://github.com/kyma-project/cli/issues/1433
