### ISSUE TITLE
Cannot update subscription max-in-flight messages

### ISSUE THREAD

**Issue by muralov** [kyma-project/kyma#15577]
Cannot update subscription max-in-flight messages. When I try to update subscription CR maxInFlightMessages from 10 to 20, the EC cannot update subscription in NATS Jetstream with the following error :
```
"error":"configuration requests max ack pending to be 20, but consumer's value is 10"
```

This happened with the Kyma versions 2.6.2, 2.7.0-rc2 

Steps to reproduce:
Just edit subscription CR spec.config.maxInFlightMessages different than current value.

Subscription creation works fine.

**Comment by mfaizanse** [comment]
Also check the event loss in the upgrade scenario after the fix.

**Comment by VladislavPaskar** [comment]
still need to fix for the v1alpha2

**Comment by VladislavPaskar** [comment]
let's handle the fix for v2 in this [issue](https://github.com/kyma-project/kyma/issues/15818)

**Comment by k15r** [comment]
accidentally reopened
