### ISSUE TITLE
Cleanup webhook configuration

### ISSUE THREAD

**Issue by dbadura** [kyma-project/kyma#15573]
**Description**
Currently webhook is configured by reading envs and parsing them as json.
Additionaly, the configuration is common for v1alpha2 and v1alpha1 which makes cleanup harder.

I propose to:
- create separate configuration for v1alpha2 and future v1alpha3
- mount configuration as json files
- remove `{{ include "tplValue" ( dict "value" .Values.values.function.replicas.minValue "context" . ) | quote }}` such constructs as it's complex and not readable.

**Reasons**

It would allow us to:
- cleanup old code
- configure webhook by json files or file, which is more handy when developing locally.
- simplify configuration

**Attachments**

**Comment by kwiatekus** [comment]
#17562
