### ISSUE TITLE
Update eventing upgrade job to test event loss scenario for JetStream

### ISSUE THREAD

**Issue by mfaizanse** [kyma-project/kyma#15578]
In our current implementation of `pre-main-kyma-gardener-gcp-eventing-upgrade`, we are not testing the event loss scenario which is to verify that all the events sent before the upgrade are still persisted after the upgrade. We should test this scenario as well, it would be good for especially which we are upgrading the NATS major/minor version (e.g. NATS `v2.8.4` --> `v2.9.0`).

The test scenario (We can have a flag to enable/disable this test scenario) could be in our fast-integration tests as:
1. Create a second sink + subscription and wait for them to be healthy.
2. Send an event and verify if it is received by the sink.
3. Delete the sink (or make the sink to return error).
4. Publish an event.
5. Upgrade the Kyma cluster.
6. Revert back the sink (to not return error)
7. Check if the sink receives the event which was sent before the upgrade.

**Comment by raypinto** [comment]
Isn't it similar to [this](https://github.com/kyma-project/kyma/blob/7da7bc64853b1003fa503c4259810f9a0734b076/components/eventing-controller/pkg/backend/nats/jetstream/jetstream_test.go#L1147) test that we have in our eventing controller? 

But I agree that we should have this test in the upgrade scenario.

**Comment by k15r** [comment]
will be covered using kyma-project/eventing-tools in the future
