### ISSUE TITLE
prepare busola ui for new CR

### ISSUE THREAD

**Issue by k15r** [kyma-project/kyma#15586]
**Description**

with the new CR installed on clusters, users need to be able to create subscriptions using the new definition using busola

- [Sample Busola extension configMap for Subscription v1alpha2 CRD](https://github.com/kyma-project/kyma/issues/16056#issuecomment-1337016611)

**Acceptance**
- [x] Busola UI implemented using Busolas extensibility feature for the new UI
- [x] ui will be installed automatically with the eventing component
- [x] `status` will be displayed in list view and per individual subscription 
- [x] not-ready subscriptions are red, ready subscriptions will be shown as green
- [x] `sink` links to actual linked service
- [x] possibility to create Subscriptions using both `standard` and `exact` method
- [x] `config` section with yaml validation (configuration here must result in a valid config block)
  - [x]  free text for key value pairs
- [x] `source` field can be filled using dropdown and free text (dropdown for applications in the cluster, free text for external sources such as EventMesh namespaces)
- [x] Check if the subscription can be interacted properly from `Functions > configuration` tab.
- [x] Check if the response of the validating webhook is reflected properly on busola 

Note: Create the configMap resource from our eventing charts (which will override the original subscription configMap for busola) only when the flag `ENABLE_NEW_CRD_VERSION` is set to true.

**Follow-up**
- [ ] Remove the ConfigMap extension(which will be result of this ticket) after the v1alpha2 Subscription will be enabled per default and this ConfigMap will be moved to [kyma-dashboard repository.](https://github.com/kyma-project/kyma-dashboard/blob/main/extensions/configuration/subscriptions.yaml)

As a result of working of this I created the following issue on the kyma-dashboard repo:
- https://github.com/kyma-project/kyma-dashboard/issues/44
- https://github.com/kyma-project/kyma-dashboard/issues/45
- https://github.com/kyma-project/kyma-dashboard/issues/49
- https://github.com/kyma-project/kyma-dashboard/issues/51

**Comment by raypinto** [comment]
Open questions:

- Who takes care of this?
  - We, the eventing team needs to take care of this using the extensibility feature of busola by applying a configMap/annotations.
- Can we support creating/updating multiple versions of the CRD in one screen as tabs? 
  - We need to reach out to the busola guys (@valentinvieriu)

**Comment by VladislavPaskar** [comment]
As a result of working on this issue, I created the following issues on the kyma-dashboard repository:
- https://github.com/kyma-project/kyma-dashboard/issues/44
- https://github.com/kyma-project/kyma-dashboard/issues/43

**Comment by VladislavPaskar** [comment]
Follow-up for the UI enhancements https://github.com/kyma-project/kyma/issues/16444
