### ISSUE TITLE
[Test Case] - Get Started guides - Deploy and expose a Function

### ISSUE THREAD

**Issue by Disper** [kyma-project/kyma#15616]
**Summary**

The purpose of the test is to make sure that [Deploy and expose a Function](https://kyma-project.io/docs/kyma/latest/02-get-started/02-deploy-expose-function/) part of `Get Started guides` is up to date and working properly.

**Test Steps**
1. Download the kubeconfig from Kyma.
2. Go through the [Deploy and expose a Function](https://kyma-project.io/docs/kyma/latest/02-get-started/02-deploy-expose-function/) and make sure it's up to date and working properly.

> **CAUTION:** Remember to test BOTH PATHS - **CLI** and **Kyma Dashboard** ❗ Just because one is working doesn't necessarily mean the other must be too. There might be new UI changes that haven't been accounted for, or some backend case that was not implemented in the UI, or a bug/typo in a CLI command, and so on.

**Expected Results**
The tutorial is up to date and working properly.

**Comment by mmitoraj** [comment]
Closing as the Getting Started guides are no longer valid.
