### ISSUE TITLE
Implement new publishing logic in event-publisher-proxy (EPP)

### ISSUE THREAD

**Issue by raypinto** [kyma-project/kyma#15618]
Tasks:

- [ ] ~~Implement new version for publishing (v2) using cloud events (CE)~~
- [x] Support the older version of the CRD as well for CE and update the logic for the new version
- [x] Update the logic for the existing Legacy endpoint, without changing the endpoint or the response.

Note: EPP would still support the application lister.

**Comment by raypinto** [comment]
Changes expected:

- [convertPublishRequestToCloudEvent](https://github.com/kyma-project/kyma/blob/a7bb098cee1df9ab59a90eef6f324269ada0f244/components/event-publisher-proxy/pkg/legacy/legacy.go#L159)
- [add new publish endpoint for v1alpha2](https://github.com/kyma-project/kyma/blob/a7bb098cee1df9ab59a90eef6f324269ada0f244/components/event-publisher-proxy/pkg/handler/handler.go#L80)
- [modify subscribed endpoint](https://github.com/kyma-project/kyma/blob/a7bb098cee1df9ab59a90eef6f324269ada0f244/components/event-publisher-proxy/pkg/handler/handler.go#L82)

**Comment by raypinto** [comment]
> Note: Here `prefix` stands for `sap.kyma.custom`

| Scenario      | Subscription |  Backend |   Publish |
| ----------- | ----------- | ----------- | ----------- |
| JS v1alpha1      | source: ""  <br/> et: “prefix.noapp.order.created.v1”      | kyma.prefix.noapp.order.created.v1 | source: does not matter <br/>  et: “prefix.noapp.order.created.v1” |
| JS v1alpha2 - standard     | source: "test"  <br/> et: “order.created.v1”      | kyma.test.order.created.v1 | source: "test" <br/>  et: “order.created.v1” |
| JS v1alpha2 - exact <br/> (Should not be removed as soon as we deprecate v1alpha1)     | source: does not matter  <br/> et: “order.created.v1”      | kyma.order.created.v1 | source: does not matter <br/>  et: “order.created.v1” |
| JS upgrade     | source: "" <br/> et: “prefix.noapp.order.created.v1”      | kyma.prefix.noapp.order.created.v1 | source: does not matter <br/>  et: “prefix.noapp.order.created.v1” |
| | | |
| EM v1alpha1      | source: ""  <br/> et: “prefix.noapp.order.created.v1”      | prefix.noapp.order.created.v1 | source: “/default/asd/asd” <br/>  et: “prefix.noapp.order.created.v1” |
| EM v1alpha2 - standard | source: "test"  <br/> et: “order.created.v1”      | prefix.test.order.created.v1 | source: "test" <br/>  et: “order.created.v1” |
| EM v1alpha2 - exact | source: ""  <br/> et: “prefix.noapp.order.created.v1”      | prefix.noapp.order.created.v1 | source: does not matter??? <br/>  et: “prefix.noapp.order.created.v1” |
| EM upgrade | source: ""  <br/> et: “prefix.noapp.order.created.v1”      | prefix.noapp.order.created.v1 | source: does not matter??? <br/>  et: “prefix.noapp.order.created.v1” |

> Note: `source` for the CE header will be picked up from the secret in the case of EM v1alpha2 (standard and exact) and upgrade.

**Comment by raypinto** [comment]
@k15r Open questions:

- In case of `exact` typematching, what should be the “source” mentioned the subscription for EM?
- In what case will the source be different from the one provided in the event mesh secret?

**Comment by friedrichwilken** [comment]
What I understand:

In the event-publisher-proxy, implement new logic for the publication of events.

Tasks:
- [ ] keep support subscription v1alpha1 for ce
- [ ] update the publishing logic for v1alpha2
- [ ] Update the logic for the existing Legacy endpoint, without changing the endpoint or the response.

Questions:
 1.
> Note: EPP would still support the application lister. 
Is this supposed to be: "EPP will still support the application lister"? or "EPP should still support application lister"?

2.
```
If the new version of the crd is in place:
   If the `prefix` is present in the event type:
        add `jetstream_prefix` for jetstream and do nothing for eventmesh
   else
         construct the type as `jetstream_prefix.source.type` for jetstream \
         construct the type as `source.type` for eventmesh, 
         add `source` value in the header (for eventmesh obtain this from the secret)
done
```
This is exactly the behaviour described in the subscription crd proposal under the point `current`. If that

**Comment by mfaizanse** [comment]
PR: https://github.com/kyma-project/kyma/pull/16388
