### ISSUE TITLE
Update the subscribed endpoint for EPP

### ISSUE THREAD

**Issue by raypinto** [kyma-project/kyma#15624]
The `/subscribed` endpoint gives the eventTypes that are subscribed to, by an application. Update the endpoint to obtain the eventTypes based on the new version of the subscription CRD.

AC:
- [ ] Gets the right eventTypes for JetStream
- [ ] Gets the right eventTypes for EventMesh

**Comment by raypinto** [comment]
Pseudocode to detect event types for subscriptions in the new version:

```
if the appName is present is present in the source
  return all the event types present in the subscription
else 
  if typematching is exact
    if appName is present in the eventType
        return that event type
```

**Comment by muralov** [comment]
> Pseudocode to detect event types for subscriptions in the new version:
> 
> ```
> if the appName is present is present in the source
>   return all the event types present in the subscription
> else 
>   if typematching is exact
>     if prefix AND appName is present in the eventType
>         return that event type
> ```
The following current logic is almost equivalent to your pseudocode, isn't it? The diff is typematching `exact` is checked first.
```
if typematching is exact
    if prefix AND appName is present in the eventType
        return that event type
else 
if the appName is present in the source
  return all the event types present in the subscription
```

**Comment by raypinto** [comment]
> The following current logic is almost equivalent to your pseudocode, isn't it? The diff is typematching `exact` is checked first.
> 
> ```
> if typematching is exact
>     if prefix AND appName is present in the eventType
>         return that event type
> else 
> if the appName is present in the source
>   return all the event types present in the subscription
> ```

Please focus on the part that says:
` if prefix AND appName is present `
