### ISSUE TITLE
Investigate if we need to Cleanup our JetStreamPrefix before we dispatch events

### ISSUE THREAD

**Issue by raypinto** [kyma-project/kyma#15638]
**Description**

The idea here is whatever is defined on the Subscription as event-type is what arrives at the sink. Internally we are allowed to change the event-type as long as we change it back in the headers when dispatching.
For EventMesh we cannot do this however for NATS should do it.

**Reasons**

**Attachments**

**Comment by mfaizanse** [comment]
We were appending the JetStream prefix `kyma.` to the event types internally when publishing.
When this event was received by the sink, the header was `ce-type: kyma.order.created.v1`, but the user published on `ce-type: order.created.v1`. 

So, after the PR, now the sink will receive the original event type as published by the user as:
```
ce-type: order.created.v1
```
