### ISSUE TITLE
Cannot publish events because NATS stream does not exist

### ISSUE THREAD

**Issue by nachtmaar** [kyma-project/kyma#15658]
**Description**

There seems to be a case where **event publishing fails** because the stream does not exist.

**Expected result**

_Stream exists_ and the customer can always publish events.

**Actual result**

Stream _does not exist_ (at least according to the controller log):

```
{"level":"INFO","timestamp":"2022-09-27T14:27:21Z","logger":"nats-handler","caller":"nats/handler.go:195","message":"Event dispatched","context":{"id":"xxx","source":"/default/my.kyma/xyz","before":"sap.kyma.custom.internal.product.viewed.v1","after":"sap.kyma.custom.internal.product.viewed.v1","statusCode":404,"duration":0.002290214,"responseBody":"nats: stream not found"}}
```

**Steps to reproduce**

Unclear!

**Troubleshooting**

**Comment by muralov** [comment]
I somehow observed it when a sink is unreachable and EC cannot create the stream. I need to try to reproduce it again.

**Comment by muralov** [comment]
I was not able to reproduce it. However, I can leave my some findings, that might be useful in the future if the issue occurs agian:
* When I deleted the stream and published events, the following errors occurred in the EPP log:
```
{"level":"ERROR","timestamp":"2023-06-07T07:58:06Z","logger":"jetstream-handler","caller":"jetstream/jetstream.go:86","message":"Cannot send event to backend","context":{"backend":"nats","jetstream enabled":true,"error":"nats: no response from stream"}}
{"level":"ERROR","timestamp":"2023-06-07T07:58:06Z","caller":"handler/handler.go:274","message":"publishing target on backend not found : cannot send to stream, nats: no response from stream","context":{}}
```

* The following Github issues found that have this error when stream is really not existing:
  - https://github.com/nats-io/nats-server/issues/2906
  - https://github.com/nats-io/nats-server/issues/2307
* The function [](https://github.com/nats-io/nats-server/blob/822ad00d50f27db69b52b182a3daf33d4f8cfc50/server/jetstream.go#L1488) where error initiates might be interesting

**Comment by muralov** [comment]
I was not able to reproduce it. However, I can leave my some findings, that might be useful in the future if the issue occurs agian:
* When I deleted the stream and published events, the following errors occurred in the EPP log:
```
{"level":"ERROR","timestamp":"2023-06-07T07:58:06Z","logger":"jetstream-handler","caller":"jetstream/jetstream.go:86","message":"Cannot send event to backend","context":{"backend":"nats","jetstream enabled":true,"error":"nats: no response from stream"}}
{"level":"ERROR","timestamp":"2023-06-07T07:58:06Z","caller":"handler/handler.go:274","message":"publishing target on backend not found : cannot send to stream, nats: no response from stream","context":{}}
```

* The following Github issues found that have this error when stream is really not existing:
  - https://github.com/nats-io/nats-server/issues/2906
  - https://github.com/nats-io/nats-server/issues/2307
* The function [](https://github.com/nats-io/nats-server/blob/822ad00d50f27db69b52b182a3daf33d4f8cfc50/server/jetstream.go#L1488) where error initiates might be interesting
