### ISSUE TITLE
[Telemetry Manager] Document and publish API reference doc

### ISSUE THREAD

**Issue by skhalash** [kyma-project/kyma#15663]
**Description**

Log Pipeline and Log Parser CRDs are the public API of the Telemetry Operator and should be well documented. The content is already present in https://kyma-project.io/docs/kyma/latest/01-overview/main-areas/observability/obsv-04-telemetry-in-kyma/#parameters and should be just copied over.

**Expected result**

Document every field and type of LogPipeline, LogParser, and all the types they consist of. Explore the possibility of automatically generating the telemetry parametes section in the Kyma docs based on the CRDs.

**Actual result**

Log Pipeline and Log Parser are poorly documented, and some types and fields lack documentation. The comments are inconsistent. 
**Steps to reproduce**

**Troubleshooting**

**Criterias**
- Have a complete documentation of the spec located in the go files so that it is available with the CRDs
- Find a mechanism to link the spec docu in a readable way from the kyma documentation. In worst case copy it over.
**Attachements**
Investigations are done already in the serverless team, see https://github.com/kyma-project/kyma/pull/16242

**Comment by Teneroy** [comment]
The new tool was introduced to automatically generate documentation out of CRDs. Also, the new prow job that checks whether the documentation is up to date is in place.
