### ISSUE TITLE
Enhance Compass Runtime Agent integration tests

### ISSUE THREAD

**Issue by franpog859** [kyma-project/kyma#15666]
**Description**

Extend Compass Runtime Agent integration tests with the checks of all of the component's responsibilities. After the two phases mentioned in [this comment](https://github.com/kyma-project/kyma/issues/15037#issuecomment-1207930709), there are still areas that need to be tested:
- Maintaining Compass connection:
  - Compass Runtime Agent fetches certificates from Compass Connector and stores them in Secrets
  - Compass Runtime Agent renews the certificate if it is about to expire
  - Compass Runtime Agent renews the certificate if the `resyncNow` flag is set to `true`
- Labeling a Runtime with the Eventing URL

This issue should be a part of the epic issue https://github.com/kyma-project/kyma/issues/13977

**Reasons**

The https://github.com/kyma-project/kyma/issues/15037 issue covers all of the checks needed to abandon the manual release testing. There are more things we want to test automatically though. We should check all of the Compass Runtime Agent responsibilities in the integration tests

**Comment by akgalwas** [comment]
We indirectly test the connection maintenance functionality.
