### ISSUE TITLE
[Telemetry Operator] Replace custom secret cache with the controller-runtime built-in cache

### ISSUE THREAD

**Issue by skhalash** [kyma-project/kyma#15675]
**Description**

In [the initial secrets watcher implementation](https://github.com/kyma-project/kyma/pull/15428) we used a simple self-written cache to store the links between secrets and LogPipelines referencing them. As @jakobmoellersap pointed out, we could instead leverage the built-in controller-runtime cache since by default all client read requests are delegated to the cache.

**Reasons**

It would allow us to simplify the code and get rid of the custom cache.

**Related issue(s)**

https://github.com/kyma-project/kyma/issues/14793

**Comment by a-thaler** [comment]
Fixed by https://github.com/kyma-project/kyma/pull/16171
