### ISSUE TITLE
Consistent naming for EventMesh in eventing-controller and EPP codebase

### ISSUE THREAD

**Issue by mfaizanse** [kyma-project/kyma#15688]
In our EventMesh codebase, we are sometimes using BEB, ems, eventMesh etc. 
Once all the the new CRD changes are done, make the naming consistent and rename all ems or beb etc terms as EventMesh.

**Comment by mfaizanse** [comment]
Re-opening this as it is still valid:

- [ ] Rename all BEB to eventMesh in EC and EPP.

**Comment by k15r** [comment]
Keep `BEB` as the required label value to switch backends. All other occurrences of `BEB` `ems`  should be changed consistently to `EventMesh`.

**Comment by friedrichwilken** [comment]
here is a first PR for EC https://github.com/kyma-project/kyma/pull/17568
