### ISSUE TITLE
Automate the enableNewCRDVersion flag procedure

### ISSUE THREAD

**Issue by mfaizanse** [kyma-project/kyma#15684]
Currently, to deploy the New CRD version, we have to follow the steps:

1. Uncomment the line `- patches/cainjection_in_eventingbackends.yaml` and `- patches/webhook_in_subscriptions.yaml` in `/config/crd/kustomization.yaml`.
2. `export ENABLE_NEW_CRD_VERSION=true`
3. `make manifests-local`
4. `make copy-crds`
5. Change the `enableNewCRDVersion` flag to `true` in helm chart.
6. `kyma deploy --source=local --workspace=$HOME/git/mfaizanse/kyma --component=eventing`

Make this flow better so that only enabling `enableNewCRDVersion` flag will deploy and use the new CRD. It can then be useful in pre-main job as well.

**Goal:**
I want to be able to deploy kyma with new CRD using:
```
kyma deploy --source=PR-xxxx --set-value enableNewCRDVersion=true
```

**Comment by raypinto** [comment]
With the introduction of [this](https://github.com/kyma-project/kyma/pull/15896) PR, the above 6 steps will reduce to 3 following steps:
- `export ENABLE_NEW_CRD_VERSION=true`
- `make copy-crds`
- `./bin/kyma-darwin deploy --source=local -w /localdir/kyma --value eventing.controller.enableNewCRDVersion=true`
