### ISSUE TITLE
Move backend/jetstreamv2 to controller-integration-tests

### ISSUE THREAD

**Issue by k15r** [kyma-project/kyma#15706]
From looking closely into our integration tests for the jetstream backend, we noticed that most of the tests are covered at the reconciler level (for eg: adding filters/eventTypes, deleting subscription, changing configuration etc.) These tests are redundant and do not need to be tested at this level. The only tests that should stay back are the ones that test the dispatching of events to a subscriber since the dispatcher is part of our jetstream backend.

### Summary of the tests that we currently have at the reconciler level:

`Tests subscription conditions, and whether it is ready or not ready!`
| Test      | Steps |  Checks |
| ----------- | ----------- | ----------- |
| ~~TestUnavailableNATSServer~~      | CreateSubscription <br/> Shutdown <br/>  StartJetstream       | Check conditions, sub ready and cleanEventTypes on K8s <br/> Sub not ready <br/> Sub ready |
| ~~TestCreateSubscription~~   | creating the k8s subscription  <br/> testing the k8s events  <br/> testing the nats subscriptions <br/> testing the deletion of the subscription  <br/> testing the deletion of the NATS subscription(s)        |   create and delete <br/> filter with empty event type (In my opinion it should not be allowed) <br/> invalid sink (too many versions, I think one check should be sufficient since the other variants are tested at the sink level) <br/> valid sink (again many variants, not needed) <br/> |
| ~~TestChangeSubscription~~   | creating the k8s subscription <br/>testing the k8s subscription <br/> testing the k8s events <br/>testing the nats subscriptions <br/> change and update the subscription <br/> testing the k8s subscription <br/> testing the k8s events <br/> testing the nats subscriptions <br/> testing the deletion of the subscription <br/> testing the deletion of the NATS subscription(s) <br/> <br/> Note: we test deletion both here and in the above scenario! Is it required?        | invalid sink <br/> add filters to subscription without filters <br/> change filters <br/> delete a filter <br/> change configuration (eg. Maxinflightmessages) <br/> resolve multiple conditions (not sure if this is even required??) line 527 -> not needed as change but as part of the “create and delete” above <br/> update valid filter to a filter with an invalid prefix -> not needed! <br/> |
 
### Integration Tests at the jetstream backend level that are duplicates or can be moved to the reconciler:

`Deciding factor: If the dispatching part needs to be tested here and is covered by the reconciler??`

| Test      | Comment |
| ----------- | ----------- |
| ~~TestJetStream_SubscriptionDeletion~~(just removed)     | Already covered twice in integration tests. No need to test dispatching since we can just check if the NATS subscription is deleted       |
| ~~TestJetStreamSubAfterSync_NoChange~~(also moved to reconciler)      | Can be useful to make sure reconciliation does not cause any change. Indirectly can be covered by adding a label for example       |
| ~~TestJetStreamSubAfterSync_FiltersChange~~(just removed)      | Already covered      |
| ~~TestJetStreamSubAfterSync_FilterAdded~~ (just removed)    | Already covered       |
| ~~TestJetStreamSubAfterSync_FilterRemoved~~ (just removed)     | Already covered      |
| ~~TestJetStreamSubAfterSync_MultipleSubs~~ (just removed)     | Not covered but question is if this is even needed??? -> not needed (team)     |
| ~~TestJSSubscriptionWithDuplicateFilters~~(covered by the validating webhook)      | Not covered but can be added. Can be moved to the validating webhook and  test removed from here     |
| ~~TestJSSubscriptionWithMaxInFlightChange~~(already covered by unit test)      | Covered as a config change but functionality not tested. Can also be tested but do we need to test it? Its a NATS feature. Team -> Only unit test is sufficient     |
| ~~TestJSSubscriptionUsingCESDK~~(removed, the same call is now used throughout all the int tests)      | Why do we need it here? It needs to be at the EPP and not here. Moreover why do we test with legacy if we already deprecated it????  |
| ~~TestJetStream_NATSSubscriptionCount~~(already covered by unit test)      | This need not move instead can be converted to a unit test. Vlad will take care of it!      |
| ~~TestJetStreamInitialize_NoStreamExists~~(removed, the unit test,which covers this logic, should be introduced [here](https://github.com/kyma-project/kyma/issues/15705))  | Can be unit tested! Need not test it at the reconciler      |
| ~~TestJetStreamInitialize_StreamExists~~(removed, the unit test,which covers this logic, should be introduced [here](https://github.com/kyma-project/kyma/issues/15705))       | Can be unit tested! Need not test it at the reconciler  |

### Finally the tests that will stay back at the backend reconciler are the following ones since they mainly test the behaviour with the sink:

`Dispatcher!`
| Test      | Comment |
| ----------- | ----------- |
| TestDispatch      | Create a subscription once, dispatch the event and see if it works       |
| TestMultipleJSSubscriptionsToSameEvent   | Might need to stay back since we test the feature of eventing where we send one event and it reaches multiple sinks        |
| TestJSSubscriptionRedeliverWithFailedDispatch   | Subscriber is shut down and then started again        |
| TestJetStream_ServerAndSinkRestart   | messages persisted (not ack'd) in the stream  <br/> // when the sink is down reach the subscriber even when the NATS server is restarted. -> FI tests as this is really important        |
| TestJetStream_ServerRestart   | scenarios involving the stream storage type and when reconnect attempts are exhausted |
| TestJetStreamSubAfterSync_SinkChange      | Can be removed once the unit tests cover the multiple dispatcher case     |

**Comment by nachtmaar** [comment]
@raypinto and me will look into the file `https://github.com/kyma-project/kyma/blob/main/components/eventing-controller/pkg/backend/jetstreamv2/jetstream_integration_test.go` and decide if there are any integration tests which should be moved to the controller integration tests instead.
Based on our findings, we will either update or delete the ticket.

**Comment by raypinto** [comment]
The ticket has been updated based on the discussion with @nachtmaar and @VladislavPaskar!
