### ISSUE TITLE
[Configurable Tracing] Basic otel-collector deployment

### ISSUE THREAD

**Issue by a-thaler** [kyma-project/kyma#15708]
**Description**
Let's get started with the tracing journey by implementing the results of https://github.com/kyma-project/kyma/issues/11630. Again, the new collector setup should be fully managed by the existing telemetry-operator using a feature flag which is disabled by default.

**Criterias**
- Have a feature flag to enable the tracing feature (helm values flag which propagates into the operator args)
- Create a new controller which reconciles a Tracing CR where an otlp endpoint is set
- When the CR is created an otel-collector is deployed to the cluster
- Pipeline updates will get ignored for now
- When the CR is deleted the otel-collector is undeployed
- No status yet on CRD
- otel/opentelemetry-collector-contrib image should be used for now
- otlp and opencensus receivers are defined in the otel-collector config and corresponding ports are exposed using a Kubernetes service
- Only a traces pipeline is defined (no metrics or logs)
- important default settings (for administrative purpose) like memory limits can be configured via arguments or an optional configmap
- Have a test assuring that a deployment is running after a TracePipeline got created (and vice versa)

Work packages:
- Define basic CRD
- Add feature flag E2E
- Add new controller which watches new CRD
- Define basic Otel Collector config
- Controller deploys Otel Collector + Service
- Controller undeploys Otel Collector
- Integration test which deploys a pipeline and validate results

Follow-Ups:
- When CR gets updated, the config gets re-configured and deployment restarted
- Pipeline Singleton
- E2E integration test
- CR Status

**Comment by chrkl** [comment]
Initial support to deploy an otel-collector has been added to the telemetry-operator by PR https://github.com/kyma-project/kyma/pull/15730.
