### ISSUE TITLE
clean up Makefile in epp

### ISSUE THREAD

**Issue by friedrichwilken** [kyma-project/kyma#15718]
Clean up the [Makefile in epp](https://github.com/kyma-project/kyma/blob/main/components/event-publisher-proxy/Makefile):
- remove the `include` of the generic Makefile. 
   - For the modularisation of our components we need to be independent of the common, generic Makefile.
- reimplement the required targets from the generics Makefile but fit them better to the requirements of the epp.
- remove `make test-local` and make `make test` run the tests locally instead. 
   - For now we don't need tests that run in containers.
- look into the Makefile of kubebuilder:
   - are there things we can borrow from it?
   - can we let kubebuilder manage our Makefile?

**Comment by k15r** [comment]
will be rewritten during modularization
