### ISSUE TITLE
Bump NATs to v2.9.3

### ISSUE THREAD

**Issue by friedrichwilken** [kyma-project/kyma#15729]
https://github.com/nats-io/nats-server/releases

**Comment by friedrichwilken** [comment]
#15727

**Comment by raypinto** [comment]
We need this on release 2.8 as well as a hot fix!

**Comment by nachtmaar** [comment]
@friedrichwilken Can we close this ?

**Comment by friedrichwilken** [comment]
@nachtmaar yes, methinks. Wasn't it in "to accept" anyhow? I dropped it there.

**Comment by friedrichwilken** [comment]
@nachtmaar maybe it was removed from there for cherry picking the PR to one of the release branches. If that was done, close it.
