### ISSUE TITLE
Non-sane configuration - read timeout equals write timeout

### ISSUE THREAD

**Issue by DubbaThony** [kyma-project/kyma#15731]
Weird server initialization in file [applicationproxy.go](https://github.com/kyma-project/kyma/blob/main/components/central-application-gateway/cmd/applicationgateway/applicationproxy.go)

When spawning server (lines 82, 89, 96), write timeout equals read timeout. If requested resource times out, it will also immidietely time out response. This will prohibit any handling of any timeout of requested resource.

**Expected result**

When requesting resource, that times out, a timeout (504) is expected.

**Actual result**

Connection gets dropped without any data being written

**Steps to reproduce**

Prepare resource in a way that will cause timeout, and request it via proxy

**Troubleshooting**

Adding 1 second to write timeout solves the problem for me.

**Comment by VOID404** [comment]
Related: #14842

**Comment by franpog859** [comment]
Is it already done, @mvshao ? Should we close this issue?

**Comment by franpog859** [comment]
It's done. I'm closing this issue
