### ISSUE TITLE
A valid LogPipeline gets rejected as the webhook is temporarily misconfigured

### ISSUE THREAD

**Issue by a-thaler** [kyma-project/kyma#15765]
**Description**

When deploying a LogPipeline from time to time you can run into that decline of the resource:

```
{"log":"Failed calling webhook, failing closed validation.logpipelines.telemetry.kyma-project.io: failed calling webhook \"validation.logpipelines.telemetry.kyma-project.io\": failed to call webhook: Post \"https://telemetry-operator-webhook.kyma-system.svc:443/validate-logpipeline?timeout=30s\": x509: certificate signed by unknown authority (possibly because of \"crypto/rsa: verification error\" while trying to verify candidate authority certificate \"telemetry-validating-webhook-ca\")","pid":"1","severity":"WARN","source":"dispatcher.go:153"}
```

That is caused by a bad way of setting up the LogPipeline webhook certificate, see also https://github.com/kyma-project/kyma/issues/15142

Investigations were done already how to solve it best in long term and in a consistent way across modules, see also https://github.com/kyma-project/kyma/issues/15195

However, the problem seem to happen more often then expected and should be fixed before the proper solution is in place.

The idea is to have an initContainer for the telemetry-operator which sets up the certificate once per startup.
Tasks for new solution:
- Have a dedicated initiContainer for the telemetry-operator which is using an image with only needed and updated dependencies, proper securityContext and resource limits
- The new container gets or generates a fixed secret (containing the ca-certificate)
- The secret should have a valid certificate (ca-certificate) stored inside. If not, it generates it. If yes, it validates the expiration time and potential refreshs it
- The container verifies if the specific ca-certificate is configured at the related webhook configuration (not an expired one), if not it will configure it
- It always generates a new certificate (webhook-certificate) from the loaded one to be used as certificate for the webhook via volume mount

**Expected result**
A valid LogPipeline can be applied at any time

**Actual result**
Sometimes a valid LogPipeline gets rejected

**Steps to reproduce**

**Troubleshooting**

**Comment by a-thaler** [comment]
I see that there is no resources block defined for the initContainer. With that the default limit of the kyma-system namespace gets applied:
```yaml
  spec:
    limits:
    - default:
        memory: 96Mi
      defaultRequest:
        memory: 32Mi
```
Was it verified that this resources will be enough? Can the request maybe reduced to a much smaller value?

**Comment by lindnerby** [comment]
@a-thaler This PR introduced the missing resources limits and requests for the init container:
https://github.com/kyma-project/kyma/pull/16188
