### ISSUE TITLE
Helm displays wrong namespace in the hint when the tests of Application Connector fail

### ISSUE THREAD

**Issue by franpog859** [kyma-project/kyma#1577]
**Description**

Helm displays wrong namespace in the hint when the tests of Application Connector fail. A whole Application Connector release is created in the namespace `kyma-system` so Helm displays it in the hint while testing a whole component (look at the picture). Pod for Remote Environment Controller Tests is created while testing Application Connector in the namespace `kyma-integration` not `kyma-system` so the displaying logs command should be `kubectl logs remote-environment-controller-tests --namespace kyma-integration`.

Please, find out if it is something we can do on the Kyma side. It may be an issue of the Helm Test workflow and we may not be able to change it.

**Reasons**

The hint will be correct and the user won't have to remember that not every pods are in the namespace `kyma-system`.

**Attachments**

![image](https://user-images.githubusercontent.com/32485355/48184081-31034280-e331-11e8-9509-3377558323ca.png)

**Acceptance criteria**

- Find out if it can be done on the Kyma side:
  - If the tests fail Helm Test displays a hint with correct namespace for every pod

**Comment by lszymik** [comment]
The issue with the wrong namespace is already solved.
