### ISSUE TITLE
slack invite link on kyma-project.io broken

### ISSUE THREAD

**Issue by mado0803** [kyma-project/kyma#15772]
**Description**

the slack invite link on kyma-project.io/community has expired/is invalid as reported by [@vobu](https://github.com/vobu) at https://twitter.com/vobu/status/1578769369303506945?s=21&t=us01Sa_9O6Qvl5wRgeehpA

**Expected result**

Working invite link

**Actual result**

Link is broken

**Steps to reproduce**

Visit kyma-project.io/community and try to join Slack

**Troubleshooting**

**Comment by valentinvieriu** [comment]
it's been fixed
