### ISSUE TITLE
Do performance tests for Eventing Controller component

### ISSUE THREAD

**Issue by muralov** [kyma-project/kyma#15817]
**Description**

Perform performance tests for the eventing controller isolated on the different cloud providers GCP, Azure, AWS for at least 2 days.

**Reasons**

We need to make sure that EC doesn't have any performance issues.

This issues is result of the performance test [issue](https://github.com/kyma-project/kyma/issues/15198)

## Steps
- [ ] Do performance tests for EC isolated
  - [ ] First only publish events to NATS Jetstream with NATS benchmarking  `$ nats bench --pub=1 ...`
  - [ ] Measure how fast EC dispatches the JetStream messages to the consumer. There is a dashboard for this, check the dashboard.
        NATS --> dispatcher --> Kyma function (subscriber)
  - [ ] Measure how fast NATS benchmarking consumes the same amount of messages to compare with EC throughput.
        NATS --> mock subscriber
- [ ] Investigate the EC performance issues if there is one

**Comment by k15r** [comment]
not required anymore
