### ISSUE TITLE
Investigate Eventing Publisher Proxy Request Throttling

### ISSUE THREAD

**Issue by muralov** [kyma-project/kyma#15813]
**Description**

Investigate why EPP throttles the requests. Moreover, please consider different cloud providers GCP, Azure, AWS.

**Reasons**

We noticed in our E2E performance tests that EPPs request-per-second (rps) doesn't increase after certain value (e.g. 1000). The reasons could be service mesh or its sync publishing.  We could not bring down the EPP with more than 2000 as it just throttled to less than 1000 rps. Moreover, we have noticed with our performance tests that K6 rps is different than EPP rps from our dashboards.

This issue is observed while working on the performance tests [issue](https://github.com/kyma-project/kyma/issues/15198)

## Steps
- [ ] Reproduce EPP request throttling issue with in-cluster eventing
   - [ ] Reproduce with load testing tools
   - [ ] Observe it with `NATS Delivery -> Event Publisher Requests` dashboard  
- [ ] Investigate why EPP requests get throttled. Some ideas:
  - [ ] Compare direct versus EPP publishing to NATS (check [NATS throughput tests](https://github.com/kyma-project/community/blob/main/concepts/eventing/performance%20evaluation/nats-jetstream/different-cloud-providers/nats-throughput-test.md) for direct publishing msgs/sec)
  - [ ] If you run K6 load test against arbitrary web server inside service mesh, do you observe any throttling?
  - [ ] Try some optimisations, e.g. do not to check stream existence every time

## Acceptance criteria
- [ ] Reproduce the issue
- [ ] Find out the bottleneck

**Comment by muralov** [comment]
Consider the point: check if we really need to check if stream exists slows EPP down.

**Comment by k15r** [comment]
not of priority anymore
