### ISSUE TITLE
Improve common logging to allow the use of AtomicLevel 

### ISSUE THREAD

**Issue by pPrecel** [kyma-project/kyma#15823]
**Description**

To use `AtomicLevel` to change log level dynamically instead of using custom implementation of the logging  registry we have to refactor a bit of common logging library. Things to do:

* refactor [common logging](https://github.com/kyma-project/kyma/tree/main/common/logging/logger) to allow users to use [AtomicLevel](https://pkg.go.dev/go.uber.org/zap#example-AtomicLevel)
* replace the [logging registry](https://github.com/kyma-project/kyma/blob/main/components/function-controller/internal/logging/registry.go) with the new version of the `common logging` implemented [here](https://github.com/kyma-project/kyma/pull/15648)

**Attachments**

https://github.com/kyma-project/kyma/issues/15593

**Comment by dbadura** [comment]
Resolving this issue allow us to change log level for controller runtime in much simpler way.. See the comment: https://github.com/kyma-project/kyma/pull/15746/files#r997422925
