### ISSUE TITLE
Singularity by simple status for TracePipelines

### ISSUE THREAD

**Issue by a-thaler** [kyma-project/kyma#15836]
**Description**
In the beginning a TracePipeline resource should exist only once as this will cover the most common use case already. Support for multiple resources should be added at a later time.
As a validation webhook cannot fully guarantee such singularity for a resource type, a safe and acceptable solution is to introduce a status for a pipeline and bring it into an error status if there is already a pipeline defined.

**Criterias**
- Have a status subresource with the typical fields for conditions
- Have a Running and Error condition
- The error condition is used when there is already an existing pipeline in Running state
- Otherwise it is Running

**Reasons**

**Attachments**

**Comment by chrkl** [comment]
The concept to enfore singularity has been documented here: https://github.com/kyma-project/community/pull/748. Keeping this issue open to track the implementation status.

**Comment by skhalash** [comment]
The singularity concept has been implemented in https://github.com/kyma-project/kyma/pull/16413
