### ISSUE TITLE
Updated TracePipeline updates the otel-collector configuration

### ISSUE THREAD

**Issue by a-thaler** [kyma-project/kyma#15831]
**Description**

The user of a TracePipeline expects that a update of the resource will result in an effective otel-collector config. That is not the case currently and you would need to re-create the pod/TracePipeline?.
A nice idea might be to just annotate the Deploment of the otel-collector with a hash representing the config value so that kubernetes will take care of the restart.

**Criterias**
- A changed TracePipeline will lead to otel-collector setup reflecting that change

**Reasons**

**Attachments**

**Comment by chrkl** [comment]
With PR #15941, the telemetry-operator adds an annotation with a hash over the ConfigMap and Secret data to the Otel Collector Pod template (same way how it's usually done in Helm charts). With this, Kubernetes automatically recreates the pod if the configuration has changed.
