### ISSUE TITLE
Implement mvp for serverless manager in a dedicated repository under kyma-project

### ISSUE THREAD

**Issue by kwiatekus** [kyma-project/kyma#15858]
**Description**

Make the firsts steps on the path towards a serverless module.
 - Generate project using kubebuilder,
 - use the makefile from the  [template-operator](https://github.com/kyma-project/lifecycle-manager/tree/main/samples/template-operator)
 - adjust the code for serverless manager in a new repo that ( initially ) would use charts from current location in kyma repository.

STRETCH:
 - implement unti tests for serverless manager - C(R)UD operation of  Serverless CR 

**AC**

 - there is a dedicated git repository for serverless manager in `kyma project` organisation.
 - serverless manager can be run locally and install serverless on a target k8s cluster

**Comment by pPrecel** [comment]
I face one problem with deploying some resources by the `serverless-manager` for more details go [here](https://github.com/kyma-project/module-manager/issues/171).

**Comment by kwiatekus** [comment]
In general the MVP works.
I was able to install serverless  and configure it via Serverless CR (external docker registry)
I was able to run a sample function.

There are few things discovered:
 - https://github.com/kyma-project/serverless-manager/issues/12
 - Serverless charts depend on `crds` component of kyma (as it tries to apply `servicemonitor` cr) - should be included in https://github.com/kyma-project/serverless-manager/issues/6
 - there is no clear recipe how to install it
