### ISSUE TITLE
Separate unit, integration and component test in EC

### ISSUE THREAD

**Issue by friedrichwilken** [kyma-project/kyma#15863]
- [ ] separate unit, integration and component tests where needed into different `_test.go` files
- [ ] add corresponding [build tags](https://mickey.dev/posts/go-build-tags-testing/) to all the test files
- [ ] create make targets to run only unit, integration or component tests

**Comment by k15r** [comment]
individual test can already be executed using go test / goland. no need to invest so much time to introduce this feature
