### ISSUE TITLE
Acceptance tests for Proxy Service

### ISSUE THREAD

**Issue by janmedrek** [kyma-project/kyma#1589]
**Description**

Currently, we have no acceptance tests for our gateway-service, these should be created and integrated with the rest of application-connector tests.

**Acceptance Criteria**
- Scenarios for acceptance tests prepared, mind:
  - Basic Authentication
  - No authentication methods
- Above scenarios implemented
- Charts updated for new tests

**Comment by Szymongib** [comment]
Follow up issue created: #3256
