### ISSUE TITLE
Finalize dashboard configuration for LogPipeline resource type

### ISSUE THREAD

**Issue by a-thaler** [kyma-project/kyma#15894]
**Description**
After https://github.com/kyma-project/kyma/issues/15204 got realized but not activated and feedback was provided to the dashboard team, it is time to fix the remaining problems to finally activate the UI for the LogPipeline.

Current problems to solve:
- In the simple view only the Input section and the http output should be selectable as this is the main flow
- In the advanced section also the custom plugins are configurable (not the loki ouput)
- Do not render empty sections in the view mode
- Language editor for the LogParser uses the proper language
- secret key reference with auto-completion

**Criterias**
- Mentioned problems are solved
- Views are activated by default

**Comment by chrkl** [comment]
The following issues have been solved: 
- Loki configuration has been removed from all views (#16037).
- The details view shows only information about the used output plugins (#16037).
- LogParsers are shown with correct line-breaks while editing (#15992).

Open issues:
- Show only intended sections in the simple view. #16037 already configures the intended limitations for the simple view, but the dashboard does not show them correctly.
- Secret key auto-completion is missing. The [ResourceRef example](https://github.com/kyma-project/busola/blob/main/docs/extensibility/form-section.md#resourceref) from the Busola documentation results in an empty form.
- The grafana-loki details view does not show any attributes. Maybe related to the `-` in the sub-resource name?
- All panels are collapsed when opening the form.

Additional topics:
- The dashboard extension uses CRD description fields. These were exposing internal Go names (#16054)

**Comment by chrkl** [comment]
The open issues have been solved by the linked PRs and the dashboard extensions have been enabled.
