### ISSUE TITLE
Check if we can enable debug logs in the NATS pods at runtime

### ISSUE THREAD

**Issue by vpaskar** [kyma-project/kyma#15905]
**Description**

This [config map](https://github.com/kyma-project/kyma/blob/main/resources/eventing/charts/nats/templates/configmap.yaml#L91-L93) contains the following code, which can potentially enable/disable NATS debug logs at runtime with the help of the config-reloader.

```yaml
{{- with .Values.nats.logging.debug }}
debug: {{ . }}
{{- end }}
```

> Note: There is a `-D` [argument](https://docs.nats.io/running-a-nats-service/configuration/logging) that can be passed to the NATS container to enable debug logs. But, this will cause a container restart, which is not the intent of this ticket.

**Tasks**

- [ ] Check if the NATS debug logs can be enabled/disabled at runtime, and if it provides any helpful information.
   - [ ] Update our documentation (e.g. Eventing troubleshooting guide) with the findings.

**Comment by marcobebway** [comment]
This can be done with the following command:

```bash
$ kubectl edit configmap --namespace kyma-system eventing-nats-config
```

Add the following configuration:

```yaml
data:
  nats.conf: |
    debug: true
```

After sometime the following logs should be printed in the nats container:

```
$ kubectl logs -f -n kyma-system eventing-nats-0 -c nats

[29] 2023/01/11 20:11:19.151707 [INF] Reloaded: debug = true
[29] 2023/01/11 20:11:19.151725 [INF] Reloaded: authorization users
[29] 2023/01/11 20:11:19.151730 [INF] Reloaded: accounts
[29] 2023/01/11 20:11:19.152077 [INF] Reloaded server configuration
[29] 2023/01/11 20:11:34.592952 [DBG] 100.64.0.24:36232 - rid:25 - Router Ping Timer
```

**Comment by k15r** [comment]
can you link the updates to the documentation for reference?
