### ISSUE TITLE
Istio 1.15.3 bump

### ISSUE THREAD

**Issue by strekm** [kyma-project/kyma#15912]
**Description**

Update Istio version to 1.15.3. 

ACs:
- [x] istio images available in external kyma repository
- [x] istio chart updated
- [x] istio reconciler uses istioclt 1.15.3 to install / upgrade istio 
- [x] reconciler bumped in kyma cli and in control-plane
- [x] RN created

**Reasons**

applying security patch

**PRs**

- https://github.com/kyma-project/test-infra/pull/6295
- https://github.com/kyma-project/kyma/pull/15959
- https://github.com/kyma-incubator/reconciler/pull/1226
- https://github.com/kyma-project/control-plane/pull/2211
- https://github.com/kyma-project/cli/pull/1434

**Comment by Sawthis** [comment]
It's done.
