### ISSUE TITLE
Clean up Application Connector charts

### ISSUE THREAD

**Issue by akgalwas** [kyma-project/kyma#15915]
**Description**
  - [x] Remove `kyma-integration` namespace (note: application-gateway looks for application credentials secrets in `kyma-integration`, we need to change this)
  - [x] Prepare migration guide to support `kyma-integration` namespace removal
  - [x]  Remove `compass-system` namespace from `kyma` and `control-plane` repositories
  - [x]  Remove creation of `compass-system` namespace after 25.03.2023
  - [x] Notify teams that are referring to `compass-system` that they can remove those references
  - [ ] Remove unused values from `application-connector/values.yaml` (`isLocal`, `strictMode`)  
  - [ ] Rename `disableLegacyConnectivity` flag to `isCompass`

**Reasons**

It is required to install all Kyma components to `kyma-system` namespace.

**Comment by akgalwas** [comment]
- Replace `disableLegacyConnectivity` with `isCompassMode` (or something similar).
- Remove condition for installing Application Gateway (see chart.yaml)

**Comment by akgalwas** [comment]
I would suggest to split the work into the following PRs:
- removing kyma-integration from Application Connector (code, charts, tests) 
- removing references to kyma-integration from other components (telemetry-operator, function-controller)
- update docs including tutorials

**Comment by Sawthis** [comment]
@Disper will ask about the status.

**Comment by mvshao** [comment]
**Workplan** 
Removing kyma-integration from:
 - [ ] Application Gateway (code, charts, tests, docs including tutorials) https://github.com/kyma-project/kyma/pull/16024
 - [ ] Compass Runtime Agent and Connectivity Validator (code, charts, tests, docs including tutorials)
 
 Other components
 - [ ] Removing references to kyma-integration from other components (telemetry-operator, function-controller, docs)

**Comment by akgalwas** [comment]
When moving CRA from compass-system to kyma-system we must mind that:
- Provisioner creates compass-system namespace and configuration secret
- Provisioner needs to be modified to place configuration in the kyma-system namespace
- Migration guide

**Comment by mvshao** [comment]
**Workplan for removing compass-system namespace**
- [ ] Compass Runtime Agent (code, charts, documentation) 
- [ ] Re-configure the Provisioner logic, to use `kyma-system` instead of `compass-system`
- [ ] Prepare the infrastructure for manual testing purposes and test it manually e.g. Kyma upgrade and EC integration
- [ ] Clean up in control-plane, test-infra, 
- [ ] Prepare Migration Guide

**Comment by koala7659** [comment]
Testing of PR for [moving compass-runtime-agent](https://github.com/kyma-project/kyma/pull/16525)

- [ ] installation on empty kubernetes cluster
- [ ] provisioning with KEB
- [ ] provisioning 2.10.1 with BTP than upgrade to PR-16525

**Comment by koala7659** [comment]
In scenario **provisioning 2.11 with BTP than upgrade to PR-16525** I discovered that existing compassconnection was in ` SynchronizationFailed` state after the upgrade operation. It may be a result of interfering old compass-runtime-agent deployment running without secrets.  To mitigate that I suggest refreshing credentials at the end of migration script with command:

`-  kubectl patch compassconnection compass-connection --type=merge -p '{"spec":{"refreshCredentialsNow":true}}'`

**Comment by akgalwas** [comment]
It was decided we don't need to clean up the charts, as they are in good enough shape to prepare yamls to be used by the Application Connector module.
