### ISSUE TITLE
Prometheus tutorial

### ISSUE THREAD

**Issue by a-thaler** [kyma-project/kyma#15914]
**Description**

Following the new [Strategy](https://github.com/kyma-project/community/blob/main/concepts/observability-strategy/strategy.md), deprecation of the monitoring component should happen. In order to execute that, a replacement in the shape of a tutorial needs to be ready. So the goal is to have a tutorial on how to deploy a typical stack based on prometheus and grafana in a self-managed manner into a Kyma runtime, having a similar good integration experience as it is now. Hereby, it is essential to not copy anything from upstream to have a very low maintenance effort.

**Criteria**
- have a tutorial on how to deploy prometheus and co. via helm
- outline how to access the API but do not expose it, just describe port-forward
- tutorial artifacts should be usable in automated tests (own resources in a repository, not in-line markdown)
- do not copy the upstream chart anywhere
- add a license disclaimer on top
- brings k8s and istio setup
- supports custom metrics with mTLS
- enables generic scraping for workloads having prometheus annotation present

--- to be done
- At the moment the kubernetes/statefulset dashboard is missing, please figure out why
- have an alerting and custom metric example referenced, clear out confusion with current stack
  - remove the old tutorials from the public docu and just keep a redirect text
  - move the old monitoring-custom-alert/monitoring-custom-metrics examples as sub-instructions into the new tutorial and have it based on the new custom stack (using same placeholders)

--- will be done later
- Potentially bundle eventing and function dashboards

**Comment by chrkl** [comment]
@abbi-gaurav FYI

**Comment by chrkl** [comment]
The following changes have been performed:
- Making the monitoring-custom-alert and monitoring-custom-metrics examples subresources of the Prometheus example and aligned all commands and namespaces
- Removed monitoring tutorials from the Kyma docs and added links to the examples
- Enhanced the Prometheus example with instructions to set up alerting channels
