### ISSUE TITLE
Implement new Kyma website that follows the new Documentation concept

### ISSUE THREAD

**Issue by jacekon** [kyma-project/kyma#15920]
As part of the modularization, the OS website structure needs to be adapted accordingly.
Moreover, the low capacity for technically maintaining `kyma-project.io`, forces the community to start using a new solution (engine) and migrate the content.

AC:
- [ ] UX proposals by UX Specialist: ...?
- [x] a concise and user-friendly domain
- [x]  intuitive linking
- [x] search feature
- [ ] right-side navigation displaying the document's headers (to avoid a really, really long left-side navigation node)
- [ ] analytics options - how many clicks we have on the page and where they come from
- [ ] documentation and guides on how the new website works (a guide how to add content and publish it)

Related issues:
- https://github.com/kyma-project/kyma/issues/16775
- All of the OS-documentation-related tasks are listed [here](https://github.com/kyma-project/kyma/labels/docs%2Fmodularization)
- The documentation concept is located [here](https://wiki.one.int.sap/wiki/display/kyma/Documentation+Concept)

**Comment by NHingerl** [comment]
I think this is more UX, Mariya Pavlenko's area, than UA. 
I can't assign her though :/

**Comment by valentinvieriu** [comment]
I propose to move this topic to the website repo: https://github.com/kyma-project/website

**Comment by valentinvieriu** [comment]
For the first release, we plan on keeping the current website, and just adding external links to our micro website for each module. The micro websites for the modules will use https://kyma-docs.netlify.app/ to display the content from the markdown files

**Comment by valentinvieriu** [comment]
We will adapt the kyma-project.io website to the same engine ( https://docsify.js.org/ ) after the initial release of the Kyma Modularisation

**Comment by mmitoraj** [comment]
@valentinvieriu, could you confirm if the implementation of a custom search feature is possible for Docsify? If yes, how would that work? Would it be located in the central repo? Will the search work per each micro website? Can we list results from all micro websites?

**Comment by mmitoraj** [comment]
> **NOTE:** After switching the Docify Kyma docs to the `kyma-project.io`  domain, remove the `docs/01-overview/README.md`

**Comment by mmitoraj** [comment]
Preview version: https://kyma-project.github.io/kyma/#/

**Comment by mmitoraj** [comment]
Production version on https://kyma-project.io
Links to documentation: 
- https://github.com/kyma-project/community/blob/main/docs/guidelines/content-guidelines/01-user-docs.md
- https://github.com/kyma-project/community/blob/main/docs/guidelines/content-guidelines/05-tabs-toggles.md
- https://github.com/kyma-project/community/blob/main/docs/guidelines/content-guidelines/10-docs-preview.md
