### ISSUE TITLE
Remove PSPs that apply for function managed workloads

### ISSUE THREAD

**Issue by kwiatekus** [kyma-project/kyma#15921]
**Description**

Remove `serverless-function` and `serverless-build` PSP and their service accounts and roles

**Reasons**

Kubernetes in version 1.25 stops supporting those in favor of PosSecurity standards

**Attachments**

**Comment by pPrecel** [comment]
Plan to resolve this issue:

- [ ] Remove mechanism that injects serviceaccounts, roles, rolebingings, and PSPs to all namespaces:
- - [ ] Remove PRP injection
- - [ ] Remove Role injection
- - [ ] Remove RoleBinding injection
- - [ ] Remove ServiceAccount injection
- [ ] Remove these resources from the `resources/serverless` chart

The functionality of injecting described resources was added in the following PRs:
- https://github.com/kyma-project/kyma/pull/10292
- https://github.com/kyma-project/kyma/pull/10436
- https://github.com/kyma-project/kyma/pull/10554
