### ISSUE TITLE
Upgrade Fluent Bit to 2.0

### ISSUE THREAD

**Issue by a-thaler** [kyma-project/kyma#15932]
**Description**
Fluentbit 2.0 is out!! https://fluentbit.io/announcements/v2.0.0/

Besides leveraging new features and seeing how we finally can add OTLP support, we first need to simply upgrade to that version.
From the release notes perspective it looks very promising that an upgrade should be without compatibility problems.

**Criterias**
- a new 2.x.x base binary is used
- all works as before
- performance is tested (load test assuring proper throughput and resource limits)
- HTTP based OpenSearch integration is tested

**Comment by a-thaler** [comment]
I tested already the newest version 2.0.2
It turned out to have a problem with long env variable keys which needs to be fixed before, see https://github.com/kyma-project/kyma/issues/15939
Besides that I found no incompatibilities yet, was able to integrate with Loki and HTTP-OpenSearch. Resource footprint was similar without creating log stress.

**Comment by skhalash** [comment]
Performed some load tests with the new Fluent Bit version, which show reduced memory consumption.
