### ISSUE TITLE
Make eventing_epp metrics registered and present from the moment that epp starts running

### ISSUE THREAD

**Issue by vvxxvvxx** [kyma-project/kyma#15964]
**Description**
We are using the eventing custom metrics `eventing_epp_messaging_server_latency_duration_milliseconds` and `eventing_epp_requests_total` to measure the availability. But in the current implementation, these metrics will only start to be present when the `POST` request to `PublishEndpoint` is received by the handler https://github.com/kyma-project/kyma/blob/ed3c29e72cf2a7c81d126da8fb2dbaa9c57bedcc/components/event-publisher-proxy/pkg/handler/handler.go#L80
  
  
In order to differentiate the below 2 scenarios. We recommend to make these metrics to be present from the moment that epp starts running.
- the handler for route path `PublishEndpoint` is not triggered yet, then no `eventing_epp_messaging_server_latency_duration_milliseconds` and `eventing_epp_requests_total` present.
- something wrong in the epp app, so no `eventing_epp_messaging_server_latency_duration_milliseconds` and `eventing_epp_requests_total` emitted

This can be achieved using `metrics.Registry.MustRegister` to register the metrics in Init. could refer to https://github.com/kubernetes-sigs/controller-runtime/blob/4c9c9564e4652bbdec14a602d6196d8622500b51/pkg/webhook/internal/metrics/metrics.go#L63.

**Reasons**

**Attachments**

**Comment by k15r** [comment]
The linked PR renames few metrics and introduces new metrics.
especially a metric containing ALL requests to the EPP and a separate metric for all backend requests
