### ISSUE TITLE
Update documentation and tutorials to use the new subscription CRD version v1alpha2

### ISSUE THREAD

**Issue by raypinto** [kyma-project/kyma#16029]
**Description**

Once we have all our changes in place, but before we switch the boolean to use the new subscription CRD version (v1alpha2) on main, we must have our documentation ready on how to use and create subscriptions using the v1alpha2 version of the CRD.

**Area**

* Eventing

**Reasons**

So that the users can directly use the new version of the subscription CRD

**Assignees**

@kyma-project/technical-writers

**Attachments**

**Comment by raypinto** [comment]
Possible changes:

- Subscription CR [here](https://kyma-project.io/docs/kyma/latest/05-technical-reference/00-custom-resources/evnt-01-subscription)
- Get started guide [here](https://kyma-project.io/docs/kyma/latest/02-get-started/04-trigger-workload-with-event/)
- Info regarding event names [here](https://kyma-project.io/docs/kyma/latest/05-technical-reference/evnt-01-event-names)
- Eventing tutorials [here](https://kyma-project.io/docs/kyma/latest/03-tutorials/00-eventing/evnt-02-subs-with-multiple-filters/)

We also need to clearly document information regarding the change in the CRD, the different publish scenarios, the typeMatching use-case (eg. for JetStream it is only supported for the duration of the migration), the event prefix restriction etc.

**Comment by mfaizanse** [comment]
Blocked!!
Need to do testing after these issues are done:
- https://github.com/kyma-project/kyma/issues/15618
- https://github.com/kyma-project/kyma/issues/15586

**Comment by mfaizanse** [comment]
Todos:
- Create a Function steps needs to be updated.
- Verify the event delivery steps needs to be updated.

**Comment by mfaizanse** [comment]
The PR is approved. It will be merged to main when we are releasing the new Subscription CRD. Until then it is blocked!!!
