### ISSUE TITLE
Add Istio CRD

### ISSUE THREAD

**Issue by strekm** [kyma-project/kyma#16042]
**Description**

Add to installation and document [Istio CRD](https://github.com/kyma-project/istio/blob/main/operator/config/crd/bases/operator.kyma-project.io_istios.yaml).
ACs:
- [x] Istio CRD documented in [CRD Docs](https://kyma-project.io/docs/kyma/latest/05-technical-reference/00-custom-resources/)
- [x] Istio CRD added to [istio CRDs folder](https://github.com/kyma-project/kyma/tree/main/installation/resources/crds)

**Attachments**
part of: https://github.com/kyma-project/kyma/issues/15865

**Comment by videlov** [comment]
**PR**:
- https://github.com/kyma-project/kyma/pull/16103
