### ISSUE TITLE
Create a blogpost explaining how to use XFF 

### ISSUE THREAD

**Issue by strekm** [kyma-project/kyma#16041]
**Description**

Create a blogpost explaining how to configure `numTrustedProxies` using Istio CR and then use it to control access to workload. Documentation should state that it is alpha feature that is available in Kyma 2.10.x. Blogpost should contain:
- Istio configuration and diagram explaining for numTrustedProxies should be configured 
- deploying and securing httpbin workload
- granting access to httbin based on original IP

**Area**

* Service Mesh
* API Exposure

**Assignees**

@kyma-project/technical-writers
@kyma-project/goat 

**Attachments**
part of: https://github.com/kyma-project/kyma/issues/15865

**Comment by videlov** [comment]
*PRs*:
- https://github.com/kyma-project/website/pull/917

**Comment by videlov** [comment]
Waiting for Kyma 2.10 release before merging it. Blocked until then.

**Comment by strekm** [comment]
https://kyma-project.io/blog/2023/1/11/istio-xff-support/
