### ISSUE TITLE
Support kyverno as kubernetes policy engine

### ISSUE THREAD

**Issue by runzexia** [kyma-project/kyma#16058]
Hi kyma team
kyverno could support us with many functions that require writing a webhook to achieve
For example,
- Injecting image pull secret
- Review deprecated api call
- Verify that the apply pod has a securityContext set, etc.

Are there any plans for supporting such policy components?

**Comment by varbanv** [comment]
Hi @runzexia, there already is an SAP project that provides Kyverno paired with some other functionality called Service Advisor. You can use that in any Kyma cluster. We do not have plans to offer equivalent functionality at this time.
