### ISSUE TITLE
Odata apis are STILL URL encoded by Kyma causing the API call to fail

### ISSUE THREAD

**Issue by ArthurPerry** [kyma-project/kyma#16053]
**Description**
Related to #5164

**Description**

In that case, the OData object had a simple string as a key.  In this case I am requesting an OData object from Commerce which has a composite key: 
`Online|apparelProductCatalog|1667409165852|29533|reviewer1@hybris.com`.  

The composite key elements are delimited by `|` which should be escaped, but the Central API Gateway also encodes the parenthesis `(` and `)` which causes the Commerce OData API to be unable to parse the query.

Version
Kubernetes: v1.23.12
Kyma: 2.7.3

API Server Address
https://api.c-81b58c5.kyma.shoot.live.k8s-hana.ondemand.com

**Expected result**

Here is the Commerce OData URL which succeeds:
https://backoffice.crz8nbwca-internalc6-d30-public.model-t.cc.commerce.ondemand.com/odata2webservices/CustomerProductReview/CustomerReviews('Online%7CapparelProductCatalog%7C1667409165852%7C29533%7Creviewer1%2540hybris.com')

**Actual result**

`"Modified request url : 'https://backoffice.crz8nbwca-internalc6-d30-public.model-t.cc.commerce.ondemand.com/odata2webservices/CustomerProductReview/CustomerReviews%28%27Online%7CapparelProductCatalog%7C1667409165852%7C29533%7Creviewer1@hybris.com%27%29', schema : 'https', path : '/odata2webservices/CustomerProductReview/CustomerReviews('Online|apparelProductCatalog|1667409165852|29533|reviewer1@hybris.com')'\""`

**Steps to reproduce**

Any call to the Central API Gateway for this API: i.e.

http://central-application-gateway.kyma-system.svc.cluster.local:8082/mp-demo-ccv2-d30-tst-eu20/customerproductreview-integration-api/customerproductreview-integration-api/CustomerReviews('Online|apparelProductCatalog|1667409165852|29533|reviewer1@hybris.com')

**Troubleshooting**

I have tried to encode the URL path and object key different ways. but I cannot influence how the Central Application Gateway handles the encoding.

**Comment by VOID404** [comment]
#14783 got closed with #16577. The feature is present on `main`. You can now disable encoding with `encodeUrl` in Application CR.

**Comment by ArthurPerry** [comment]
Is this fixed in Kyma 2.10.1?  I still get the issue.  Do I need to change something with my Application CR?

**Comment by VOID404** [comment]
Release 2.11 will be the first one supporting this feature.
You'll have to add `spec.encodeUrl` to your Application, and set it to `false`.
This way path encoding will stay intact while passing through gateway - gateway won't re-encode it

**Comment by Disper** [comment]
Fixed by https://github.com/kyma-project/kyma/pull/16577
