### ISSUE TITLE
SAP Field Service Management API - permanent redirect

### ISSUE THREAD

**Issue by VishnAndr** [kyma-project/kyma#16089]
**Description**

After the team resolved https://github.com/kyma-project/kyma/issues/14717 I further discovered and investigated the issue with SAP Field Service Management API that I mentioned in the comments there.

The current issue is that for some reason, direct calls to https://us.coresuite.com get permanently redirected with 308 status code. I was not able to find the root cause, hence raising it here.

The way it is set up:
1. I have an application connected that contains OAuth credentials and target URL as https://us.coresuite.com/api/query/
2. I have a namspace created with the sidecar injection enabled.
3. I have a NodeJS16 function pingfsm that does the call to SAP FSM Query API with axios library (or with cross-fetch or with undici lirbaries) using the registered application via its centralGatewayUrl. Doing the call to this function should get me back the resul of the corresponding Query API call.
3. However, if I go with the standard axios setup, I'm getting too many redirects error (maxRedirects in axios is 21 by default):
"Error [ERR_FR_TOO_MANY_REDIRECTS]: Maximum number of redirects exceeded"
5. If I set maxRedirects to 0 to prevent axios following any redirects or use cross-fetch or undici libraries (that have no redirects support or 0 redirects to follow by default), I'm getting permanently moved status code 308 with location header (I'm guessing rewritten by CAG) as /mp-fsm-bl-us/query-api/query-api/v1?dtos=CompanyInfo.15 . That is the same centralGatewayUrl plus my path (/v1) and query parameter (dtos=CompanyInfo.15) except protocol, host and port are excluded.
6. If I use some 3rd party external proxy (like in the example I'm using https://beeceptor.com) and change only the host in the targetUrl of the registered application, it works just fine
7. If I implement a simple proxy function in Kyma called fsmproxy where I'm passing through the call as is, it works fine too. I needed to change the host header to us.coresuite.com because otherwise I was getting
Error [ERR_TLS_CERT_ALTNAME_INVALID]: Hostname/IP does not match certificate's altnames: Host: fsmproxy.<tenant>.kyma.ondemand.com. is not in the cert's altnames: DNS:us.coresuite.com
error.

Looking into central application gateway log didn't give much hints. Even with requestLogging enabled, all I see there is:
..when making a call to the application with us.coresuite.com:
```
time="2022-11-12T12:36:26Z" level=info msg="Proxy call for service 'query-api' to 'https://us.coresuite.com/api/query'"
time="2022-11-12T12:36:26Z" level=info msg="Modified request url : 'https://us.coresuite.com/api/query/v1?dtos=CompanyInfo.15', schema : 'https', path : '/api/query/v1'"
time="2022-11-12T12:36:26Z" level=info msg="Internal handler: : POST /mp-fsm-bl-us/query-api/query-api/v1?dtos=CompanyInfo.15 HTTP/1.1 308 391"
```

..when making a call to the application with 3rd party proxy:
```
time="2022-11-12T12:34:39Z" level=info msg="Proxy call for service 'query-api' to 'https://blahblah.free.beeceptor.com/api/query'"
time="2022-11-12T12:34:39Z" level=info msg="Modified request url : 'https://blahblah.free.beeceptor.com/api/query/v1?dtos=CompanyInfo.15', schema : 'https', path : '/api/query/v1'"
time="2022-11-12T12:34:40Z" level=info msg="Internal handler: : POST /mp-fsm-bl-us/query-api/query-api/v1?dtos=CompanyInfo.15 HTTP/1.1 200 1195"
```

Something strange is going on when CAG tries to call us.coresuite.com direct.

The setup is on Kyma 2.8.2 (managed version on SAP BTP, Azure hyperscaler, Singapore region)
Originally, the issue is with an SAP FSM application registered via SAP BTP landscape (system and formation). However, it is reproduciable with manualy created application too.

**Expected result**

I should be able to call connected SAP FSM system.

**Actual result**

I'm getting infinite number of permanent redirects.

**Steps to reproduce**
1. Register the application and corresponding secret for OAuth.
2. Create a namespace with sidecar injection enabled.
2. Deploy pingfsm function in that namespace and configure its environment variables. Configure API rule to allow any method to any path.
3. Do the call to the pingfsm function. Observe 308 status code.
4. Change the host in targetURL in the application to either 3rd party proxy like beeceptor or to other proxyfsm Kyma function deployed
5. Do the call to the pingfsm function again. Observe that it works

Attaching pingfsm and proxyfsm functions and the application. https://1drv.ms/u/s!ArgsAhOzBl8mgdsZnWI-oN0W8rTdoA?e=7DBLfx

Happy to provide more details or even access to the Kyma instance if it would help. Can also demonstrate the issue live to anyone interested.

**Troubleshooting**

I did the steps describe above. Hoping the diagram would help to understand them too.
I tried the described setups. I tried using external tool (insomnia/postman, curl), setting the headers, the url and query parameters as they logged in beeceptor and/or fsmproxy function and was not able to reproduce 308 redirect there.
App 1 - doesn't work
App 2 - works ok
App 3 - works ok

![call_diagram](https://user-images.githubusercontent.com/4543139/201631760-f7aed113-9c0a-4462-ae18-c087bbb986f9.png)

**Comment by akgalwas** [comment]
@VishnAndr It is not planned for Q4 2023. Please reopen the ticket if it is still important, so that we will consider it for 2024.
