### ISSUE TITLE
Migrate Application Connector to Istio 1.1

### ISSUE THREAD

**Issue by lszymik** [kyma-project/kyma#1608]
**Description**

The application connector components must be exposed using Istio 1.1.

**Reasons**

We need to get rid of the Nginx-Ingress controller.

**Acceptance criteria**
- Application Connector components exposed with use of Istio
- Documentation updated (no more NodePort, component diagram updated, ...)

**Comment**

Currently, it is blocked by the Istio 1.1 release.

**Comment by lszymik** [comment]
The big part of that story is a documentation update.

**Comment by Szymongib** [comment]
The proposed solution is to create a reverse proxy component, that will handle validation of certificate subject and pass the required information - like the subject or certificate hash - to the services.
