### ISSUE TITLE
Test dry run deploy with prod profile in k3d-telemetry-integration

### ISSUE THREAD

**Issue by lindnerby** [kyma-project/kyma#16112]
**Description**
To test the production overwrites we should at least do a `kyma deploy --dry-run` with production profile to see if rendering with telemetry values in production profile is not failing.

Within this task it may be suitable to start already extracting test execution scripts for telemetry-integration. Meaning, currently we are using `prow/scripts/cluster-integration/kyma-integration-k3d.sh` to execute make/npm, but we should have our own designated script `kyma-integration-k3d-telemetry.sh` which is used and sent to the integration test VM that only contains our TELEMETRY_ENABLED script execution path. 

**Criteria**
- Verify that the production profile renders (does not contain syntax errors)
- Try to have a new telemetry script that gets used by `provision-vm-and-start-kyma-upgrade-k3d.sh`

**Comment by Teneroy** [comment]
Added the new script file `kyma-integration-k3d-telemetry.sh` where we now have all telemetry related code, and we call `kyma deploy --dry-run`  with production profile at the end. We call this script now from `provision-vm-and-start-kyma-upgrade-k3d.sh`.
