### ISSUE TITLE
SKR tests prints proper information about failed instance

### ISSUE THREAD

**Issue by piotrmiskiewicz** [kyma-project/kyma#16179]
**Description**

AC:
 - in case of a failure the log contains proper information (not only reconciliations), for example KEB Events (`--events` option in kcp cli)

**Comment by wozniakjan** [comment]
bumping kcp for test-infra in https://github.com/kyma-project/test-infra/pull/6606
adding `--events` usage in tests in https://github.com/kyma-project/kyma/pull/16370
