### ISSUE TITLE
Patch releases should contain short summary and should be announced in the slack channels

### ISSUE THREAD

**Issue by pbochynski** [kyma-project/kyma#16196]
**Description**
Each patch release should contain short summary that describes the reason for having that patch (important bug fixes or security vulnerabilities). The message can be part of the github release (having blog post for each patch seems to be an overkill).
The notification in the slack channel should be triggered for each patch (but we should skip release candidates IMHO).

**Reasons**
Our users should be notified about patches and why they have been released.

**Comment by tobiscr** [comment]
Could imagine to handle this as part of the [notification dashboard](https://github.tools.sap/kyma/backlog/issues/1622).

**Comment by tobiscr** [comment]
Passing the issue to @zhoujing2022 as it is related to customer communications and be considered in the new communication concepts.

**Comment by tobiscr** [comment]
@zhoujing2022 : by moving the release process completely to the teams, it can become tricky for Neighbors to support here. Please let me know if you have some special requirements we can implement on our side to automate this requirement.

**Comment by pbochynski** [comment]
As we moved releases from blog posts to GitHub releases this issue became irrelevant.
@zhoujing2022 Please ensure all the teams use GitHub releases for their modules.
