### ISSUE TITLE
Deploy and update simple fluentbit daemonset by telemetry-operator

### ISSUE THREAD

**Issue by a-thaler** [kyma-project/kyma#16200]
**Description**
As part of https://github.com/kyma-project/kyma/issues/15955 the telemetry-operator should deploy and update a fluentbit installation if a LogPipeline is present.

**Criteria**
- Have a feature flag to enable the new feature in the operator and disable the helm sub-chart deployment
- If there is no LogPipeline defined, then there is no fluenbit instance running (only initial, deletion will be implemented later)
- If there is a LogPipeline, a fluenbit instance gets created and configured with all resources as deployed before via the helm chart
- Ignore the ServiceMonitor

**Comment by skhalash** [comment]
The feature is hidden behind a feature flag and is not enabled by default. It should be enabled when daemonset deletion is implemented. For now, I added a job that tests the operator with the. feature flag enabled https://status.build.kyma-project.io/?job=kyma-integration-k3d-telemetry-alpha.
