### ISSUE TITLE
Implement orphaned image cleanup for internal docker registry

### ISSUE THREAD

**Issue by kwiatekus** [kyma-project/kyma#16208]
**Description**

Implement a periodically running cleanup job that identifies orphaned function images and deletes them.

 - the clean up job should be part of internal docker registry manifests - deployed/configurable only in case internal docker registry is enabled
 - It should be possible to disable/enable cleanup job (via values.yaml / via Serverless CRD)

**Reason**
The current implementation for the Internal Registry deployed with Kyma Functions doesn't include any garbage collection logic. In dynamic environments with several Functions with multiple versions, if the Internal Registry is used with a cluster PVC storage backend, the volume disk space can fill up very quickly, resulting in build failures for new Function versions.

**Attachments**
[proposal](https://github.com/kyma-project/kyma/blob/main/components/function-controller/design/internal_registry_garbage_collection.md#internal-registry-garbage-collection)

**Comment by kwiatekus** [comment]
IMO currennt state of the garbage collector at main branch removes too much. 

I changed the config of the garbage-collect container and the schedule of the cron job to run every 5 minutes.

I saw in the logs  of the garbage-collect container that some of the blobs got removed after a function was updated.

However this function cannot be replicated anymore.. as kubernetes cannot pull the image


![Image](https://user-images.githubusercontent.com/6783567/209810158-203a5305-f89e-40f3-b75d-aa03db71a0c8.png)

Moreover, I see that the gc cronjob schedulej jobs and they fail in such scenario as they cannot remove something ('unknown manifest'). The cron job tries again and again until the job reaches the max back off retries.

```
{"level":"info","ts":1672229447.1506612,"logger":"internal registry gc","msg":"reading configuration"}
I1228 12:10:48.202191 1 request.go:665] Waited for 1.02762516s due to client-side throttling, not priority and fairness, request: GET:https://api.kk-gc.wookiee.internal.canary.k8s.ondemand.com:443/apis/autoscaling/v2?timeout=32s
{"level":"info","ts":1672229448.4251747,"logger":"internal registry gc","msg":"removing function images"}
{"level":"info","ts":1672229449.720219,"logger":"internal registry gc","msg":"removing cached layers"}
{"level":"error","ts":1672229450.241133,"logger":"internal registry gc","msg":"while getting registry cached layers","error":"manifest unknown: manifest unknown","stacktrace":"runtime.main\n\t/usr/local/go/src/runtime/proc.go:250"} 
```

**Comment by kwiatekus** [comment]
Also I think if the GC action jumps after the image build but before the function is deployed, than the deployment resolves into error state as it cannot pull the image.

**Comment by moelsayed** [comment]
OK, There is no timestamps on images/layers that can be accessed via the API as far as I can see. So, there are two possible solutions to this:
1. lookup replicasets instead of deployments as an image name source. This avoid the issue where the deployment returns the image for the ready image, not the updated one.
2. Check the function itself first, and make sure it's not transitioning/updating, then lookup the images.

For both cases,  there is a theoretical window where this could happen again in the duration between listing the images on the cluster and listing the tags on the registry, although it's very short...

**Comment by anoipm** [comment]
Removing orphaned images looks much more difficult than we thought before. There is still some uncertainty as to whether we will remove the relevant images. Now we decide to freeze the work on it.
