### ISSUE TITLE
UI API memory consumption constantly growing

### ISSUE THREAD

**Issue by michal-hudy** [kyma-project/kyma#1623]
**Description**

UI API memory consumption constantly growing in time. UI API has multiple in-memory caches, so maybe it related to this - informers and cache for content (BigCache). It is also possible that there is a memory leak. It should be investigated.

Memory consumption from ~10H:
![image](https://user-images.githubusercontent.com/26445970/48304726-805a9600-e51e-11e8-9c0b-64854d6d8d50.png)

**Expected result**

Memory should be released if not needed.

**Comment by Szymongib** [comment]
Should be resolved by #1910
