### ISSUE TITLE
Make oauth2-proxy configurable for user-provided services

### ISSUE THREAD

**Issue by s4heid** [kyma-project/kyma#16267]
**Description**

As a Kyma user, I would like to make use of the anyways deployed oauth2-proxy for exposing and securing user-provided services via a custom oidc provider. 

Grafana and Jaeger are ["natively" supported](https://github.com/kyma-project/kyma/blob/f8fd5e90a9822f0e723febd2dcb7f90e4108437d/docs/04-operation-guides/security/sec-06-access-expose-grafana.md) by Kyma. It would be convenient if I could bring my own oidc config (e.g. via Kubernetes secret) and Kyma exposes and secures my service with oauth2-proxy.

_Example Use case:_ A scenario where this would be useful is the exposure of the [tekton dashboard](https://tekton.dev/docs/dashboard/). The dashboard is user-provided and should be exposed and secured via a custom oidc provider (e.g. SAP IAS). As the kyma deployed oauth2-proxy cannot be used for this, it is necessary to deploy a dedicated proxy instance for this.

**Reasons**

Avoid deploying oauth2-proxy twice and avoid maintenance effort.

**Comment by a-thaler** [comment]
That is a good feature which should be provided in my opinion via the API Gateway. Here, you expose your workload and you should be able to specify your OIDC settings and also configure oauth2 flows initiated by a proxy. Then it is implementation detail how to realize it (like with a single or multiple proxies deployments).

Istio provides the externalAuth feature already and as far as I understand @strekm already was thinking about such kind of integration via the APIGateway. Do you have prepared already some epics which we could link and where @s4heid could provide more requirements?

**Comment by pbochynski** [comment]
@strekm What about the plans to use oauth2-proxy as an external authorizer? I couldn't find any ticket about it.

**Comment by strekm** [comment]
i do not have specifics yet but i would need to implement it for [APIRule v1](https://github.com/kyma-project/api-gateway/issues/322). i will close this ticket for now. cheers
