### ISSUE TITLE
Create a suite of end-to-end tests for Application Connector - part 1

### ISSUE THREAD

**Issue by lszymik** [kyma-project/kyma#1626]
**Description**

The suite of the end-to-end tests must be created which will ensure the quality of the Application Connector components.

The tests must simulate usage of the Application Connector components from the external system point of view.

The tests must be integrated with delivery pipelines and smoke tests. The tests must also work in standalone mode for a development.

**Reasons**

The Application Connector components must be well tested to allow smooth usage across all integrated solutions.

**Language**
The tests will be implemented using SPOCK.

**Comment by Disper** [comment]
Will be continued in #2716
