### ISSUE TITLE
JetStream breaks under high load

### ISSUE THREAD

**Issue by vpaskar** [kyma-project/kyma#16286]
**Description**

As discovered in [that investigation](https://github.com/kyma-project/kyma/issues/15219#issuecomment-1339316352), NATS JetStream still breaks under the high load. When the stream size increases fast enough to eventually be close to 800Mi, the JetStream just gets disabled. Even sometimes it is beyond repair. 

_Idea: find out at which percentage JetStream get disabled and decrease the limits to 80% and add alerts._

@k15r mentioned that JetStream is now also breaking without high load (NATS version 2.9.7).

**Steps to reproduce**

1. Start publishing at a high rate, i.e. 1.5k EPS 
2. Observe that the stream size is increasing
3. At around 800Mi the JetStream should break

**Comment by k15r** [comment]
cannot be observed with newer versions of nats
