### ISSUE TITLE
`pull-function-registry-gc-build` is broken

### ISSUE THREAD

**Issue by friedrichwilken** [kyma-project/kyma#16288]
The job is failing [almost all the time](https://status.build.kyma-project.io/job-history/gs/kyma-prow-logs/pr-logs/directory/pull-function-registry-gc-build). Yet, it is required and so it makes merging PRs impossible.

Please fix asap.

**Comment by pbochynski** [comment]
@moelsayed Are you working on it? Please update the status here.

**Comment by moelsayed** [comment]
This is a build job and it was set to optional, but there is regex match on the name that blocked other jobs nevertheless, so it was  removed completely. The last failed run on the posted log is over a  week ago and the pipeline is unblocked.
