### ISSUE TITLE
Investigate why the Dispatcher cannot keep up with the EPP and NATS Server

### ISSUE THREAD

**Issue by vpaskar** [kyma-project/kyma#16287]
**Description**

When we publish to EPP with high load (1.5k+ EPS), the EPP is able to sustain the load and the NATS Server is also able to ACK those messages ([reference](https://github.com/kyma-project/kyma/issues/15219#issuecomment-1339316352)):
```
loadtester-7944857bf5-btdsz loadtester 2022/12/06 14:02:40 | eps:1500 | undelivered:0000 | ack:1500 | nack:0000 | sum:1500 |
loadtester-7944857bf5-btdsz loadtester 2022/12/06 14:02:41 | eps:1500 | undelivered:0000 | ack:1500 | nack:0000 | sum:1500 |
loadtester-7944857bf5-btdsz loadtester 2022/12/06 14:02:42 | eps:1500 | undelivered:0000 | ack:1500 | nack:0000 | sum:1500 |
loadtester-7944857bf5-btdsz loadtester 2022/12/06 14:02:43 | eps:1500 | undelivered:0000 | ack:1500 | nack:0000 | sum:1500 |
loadtester-7944857bf5-btdsz loadtester 2022/12/06 14:02:44 | eps:1500 | undelivered:0000 | ack:1500 | nack:0000 | sum:1500 |
loadtester-7944857bf5-btdsz loadtester 2022/12/06 14:02:45 | eps:1500 | undelivered:0000 | ack:1500 | nack:0000 | sum:1500|
```
Nevertheless the stream size keeps increasing. That could only mean, that our dispatcher is the bottle neck. Increasing the sink replicas to 4 and EC to 2 didn't help. So, we need to investigate is the reason, the dispatcher is not performing and if we can improve it somehow.

**Idea: maybe increasing the maxInFlight will do the job**

**Steps to reproduce**

1. Start publishing at a high rate, i.e. 1.5k EPS 
2. Check that NATS Server ACKs at the same rate as we publish
3. Observe that the stream size is increasing

**Comment by k15r** [comment]
Did you try increasing the max in flight for the subscriptions? If the sink responds slow but can process more than 10 events at a time, that would be a fix

**Comment by VladislavPaskar** [comment]
> Did you try increasing the max in flight for the subscriptions? If the sink responds slow but can process more than 10 events at a time, that would be a fix

good idea! I will try to do that.

**Comment by k15r** [comment]
we increased requests and limits to fix this issue
