### ISSUE TITLE
Create a test lambda and the verification flow

### ISSUE THREAD

**Issue by lszymik** [kyma-project/kyma#1628]
**Description**

The suite must verify if the events are delivered and access to the registered API works. Therefore, we need to implement a lambda function triggered by the event. The lambda will call a registered API and mark the whole tests as successful.

**Acceptance criteria**

- The verification lambda implemented.
- The mechanism for calling registered API and marking a test as successfully implemented.
-- That might be a public service like a weather service
- The event sending functionality implemented.

**Comment by lszymik** [comment]
We need to design the way to verify if the event has been delivered and the lambda was executed. Probably, we need to have some kind of persistence in Kubernetes as well.

**Comment by lszymik** [comment]
I have executed the end 2 end test six times today. Only one execution was successful. I would like to discuss the result and double check if my setup was broken or there are some issues in tests.

**Comment by akgalwas** [comment]
We need to fix the way clean up is done:
- Service Binding and Service Instance should be deleted
- Resources deallocated in reverse order

**Comment by akgalwas** [comment]
> We need to design the way to verify if the event has been delivered and the lambda was executed. Probably, we need to have some kind of persistence in Kubernetes as well.

The current approach is as follows:
- test deploys sample service with one endpoint (/counter)
- before triggering event the test calls GET /counter to get the current value
- test triggers lambda, lambda makes call to POST /counter 
- test periodically calls GET /counter and checks if value has been changed

**Comment by lszymik** [comment]
The pull request has been created. https://github.com/lszymik/application-connector-e2e/pull/1
The tests are improved a little bit. The order of the data clean-up has been changed. More tests are now working as the suit. It is still not perfect but at least we can start thinking about integration with the pipeline.

**Comment by lszymik** [comment]
After merging it, we need to add the tag 0.8.
