### ISSUE TITLE
Integrate end-to-end tests

### ISSUE THREAD

**Issue by lszymik** [kyma-project/kyma#1629]
**Description**

The whole end-to-end suite must be integrated with a CI/CD pipeline. It must be also integrated with smoke tests.

**Reasons**

We need to ensure the quality of our deliverables in an automatic way.

**Comments**

We need to discuss how to implement a smoke test. Maybe we will need to create a follow-up story.

**Comment by pbochynski** [comment]
The issue is obsolete. Done in the separate initiative.
