### ISSUE TITLE
Activate configurable tracing feature

### ISSUE THREAD

**Issue by a-thaler** [kyma-project/kyma#16299]
**Description**
After [configurable tracing](https://github.com/kyma-project/kyma/issues/11231) is implemented as MVP, it is time to release it. For that it needs to be activated by default, still having the option to disable it via feature flag for a rollout. Furthermore, the old behaviour with the tracing module should kept stable to have enough time to deprecate the module and adjust testing and so on.

**Criterias**
- CRD gets deployed always
- feature flag is activated by default (not removed yet to allow a phased rollout)
- tracing module activates tracing in istio - in evaluation profile it configures a 100% sampling rate
- tracing module deploys a default TracePipeline

**Comment by chrkl** [comment]
PR #16372 activates configurable tracing in the telemetry-operator. The tracing component activates Istio tracing by creating a Telemetry CR and activates trace shipping to Jaeger with a TracePipeline.
