### ISSUE TITLE
Verify eventing and tracing is working for 0.5 release candidate

### ISSUE THREAD

**Issue by Abd4llA** [kyma-project/kyma#1630]
## Description ##
Verify [Kyma 0.5 release candidate](https://github.com/kyma-project/kyma/releases/tag/0.5-rc) eventing and tracing functionalities.

Notes:

- Verify Kyma eventing example scenarios
- Verify Jaeger traces afterwords
- Verify Jaeger UI security feature.

AC:
- [ ] Kyma 0.5 RC tested for local installation for eventing and tracing.
- [ ] Kyma 0.5 RC tested for cluster installation for eventing and tracing.

**Comment by Abd4llA** [comment]
worked with @sayanh to verify it on https://console.kyma-05rc-etcdfix.cluster.stage.b.cluster.kyma.cx/

**Comment by Abd4llA** [comment]
Local verified by me

**Comment by abbi-gaurav** [comment]
The verification needs to be done for RC2 again.

**Comment by abbi-gaurav** [comment]
No request coming for the verification and 0.5 has been released.
