### ISSUE TITLE
Proper metadata enrichment for traces

### ISSUE THREAD

**Issue by a-thaler** [kyma-project/kyma#16300]
**Description**
When pushing trace data to the new otlp based traces endpoint and when having a tracepipeline configured, the span data ariving at the backen has not sufficient metadata attached. There must be enough metadata enriched by the agent technology so that the source of the span can be identified properly, usually using the otel k8sattribute processor plus some cluster info.

**Criterias**
The otel-collector by default is adding resource attributes to every span data so that the [k8s semantics](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/resource/semantic_conventions/k8s.md) are satisified at any time
If the incoming span data already contains dedicated resource attributes, they should be kept (or overriden?) in a consistent approach

**Details**
- using the k8s attribute processor requires access to the APIServer -> new serviceaccount with minimal privileges
- attributeprocessor needs to be bundled in the image
- cluster name might not be a feature of the processor but need a regular attribute processor
- assure that memory footprint is not increased
- understand the dependency to api-server
- understand if the attribute enrichment is performing an insert or upsert

**References**
https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/resource/semantic_conventions/k8s.md
https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor/k8sattributesprocessor

**Comment by rakesh-garimella** [comment]
Support for k8s attributes and resource processor has been added to otel collector image. 
The required RBAC for fetching k8s metadata has been added.
The cluster name is being injected into the spans using resource processor.

**Comment by hisarbalik** [comment]
Test scenario 1: User provide tags with span which should be enriched by the k8sprocessor

<img width="627" alt="attribute_override_2" src="https://user-images.githubusercontent.com/6337703/208418294-345bdd49-66b5-4942-93b5-b7ea69c90cc4.png">

<img width="1387" alt="attribute_override_1" src="https://user-images.githubusercontent.com/6337703/208418266-f27c603f-9bc7-4136-9d0f-8e1bbd9a9dae.png">

Processor take no action in this case, no overrides

Test scenario 2:  k8sprocessor impact on memory and overall throughput

<img width="1773" alt="k8s_proc_memory" src="https://user-images.githubusercontent.com/6337703/208418806-5f328ce8-a9ef-41ea-9b35-601de34109ec.png">

<img width="871" alt="k8s_proc_accepted" src="https://user-images.githubusercontent.com/6337703/208419304-89ff9349-5b21-40b1-905a-cae8b8c5ed4b.png">

<img width="871" alt="k8s_proc_sent" src="https://user-images.githubusercontent.com/6337703/208419307-a453f2e7-5b51-409a-b93b-1c053675e42b.png">

Test run around 1 hour, no memory issues observed overall throughput is 4.444 span/sec, no performance impact observed compared with setup no k8sprocessor

Test scenario 2:  k8sprocessor has no access to the k8s API server or API server not responding

<img width="1783" alt="cpu_k8sproc_noaccess_k8sapi" src="https://user-images.githubusercontent.com/6337703/208419989-296d6d59-c306-43a3-a53d-c26a7fdc8902.png">

<img width="1783" alt="memory_k8sproc_noaccess_k8sapi" src="https://user-images.githubusercontent.com/6337703/208420514-6a4f4f6e-f1e7-4748-a9f5-e348b523437a.png">

<img width="875" alt="accepted_k8sproc_noaccess_k8sapi" src="https://user-images.githubusercontent.com/6337703/208421213-aef06e1b-c96d-4ed1-a69f-7265a5d1a689.png">

<img width="875" alt="sent_k8sproc_noaccess_k8sapi" src="https://user-images.githubusercontent.com/6337703/208421217-d194bb17-6bf1-424e-8b7d-28c068261b10.png">

In case of k8s API server not reachable, the collector in first ~4 minutes accepted no spans, the load generator report connection timeouts in this time period, after ~4 minutes load generator and collector was back in normal operation.

Another observation was, even with low load on collector, collector CPU usage was high.

Around %1 of accepted spans was not successfully exported to the backend.

**Comment by a-thaler** [comment]
The tests are showing that the processor is not harming the memory footprint, it is doing an insert and not an upsert and with that keeps original data. On error situations it seems to skip the processing which is an adequate behaviour.
