### ISSUE TITLE
Deep dive into NATS JetStream consumer-subscription logic

### ISSUE THREAD

**Issue by vpaskar** [kyma-project/kyma#16312]
**Description**

Since the NATS Subscription/Consumer logic is crucial for the NATS EventingBackend, we still need to investigate the following topics:

- Do we need to take any further actions at the graceful/ungraceful EC restart ?
- Do we need to perform the NATS Unsubscribe on the EC restart ? 
- How are the NATS Subscriptions and Consumer in the 1:1 relationship ?
- Is our AddConsumer/Subscribe/BindConsumer logic right according to NATS Documentation ?

**Comment by k15r** [comment]
Not needed anymore
