### ISSUE TITLE
Add a job that will check all the sinks and pause the subscriptions if needed

### ISSUE THREAD

**Issue by vpaskar** [kyma-project/kyma#16329]
**Description**

Once the https://github.com/kyma-project/kyma/issues/15087 is implemented we could add a job, which could recurrently check all the existing sinks and in case the sinks are not ready, pause their Subscriptions.

**Reason** 

Currently we reconcile the Subscription every 10 minutes. So, in case a Subscription's sink becomes invalid on the 2nd minute, the Subscription will be paused only after 8 minutes. Job like this would speed up the feedback to the Eventing user

**Comment by k15r** [comment]
will not implement
