### ISSUE TITLE
NATS goes OOM after dying due to full storage

### ISSUE THREAD

**Issue by k15r** [kyma-project/kyma#16346]
Scenario

- Stream usage close to limits (900MB on 1Gb storage)
- NATS dies for no obvious reason

Expected behaviour
- NATS can be restarted and load all stream data from the storage

Actual:
 NATS goes OOM while loading the stream

**Comment by marcobebway** [comment]
I could not reproduce the OOM issue with NATS 2.9.9.

However, the NATS cluster breaks when the stream size reaches the configured max-bytes value of 900Mi, and restarting the NATS cluster pods does help recovering from this.

Testing a lower max-bytes value of 700Mi seems to be more stable and although the NATS cluster could still break under high load when the stream size reaches the 700Mi, but restarting the NATS pods was sufficient to recover the NATS cluster.

Here is a [PR](https://github.com/kyma-project/kyma/pull/16423) to change the max-bytes value to be 70% of the stream storage.
