### ISSUE TITLE
Finalize TracePipeline API - Constraints and docu

### ISSUE THREAD

**Issue by a-thaler** [kyma-project/kyma#16345]
**Description**
Make the API ready for a first release by verifying all descriptions and check if constraints are mising in the CRD definition.

**Criterias**
- All properties have a meaningful description
- All properties have meaningful constraints applied if possible (NotNull, maxLength, patterns, ...)

**Comment by rakesh-garimella** [comment]
The API documentation has been improved and desired constraints have been applied.
