### ISSUE TITLE
Update documentation with v1alpha1

### ISSUE THREAD

**Issue by anoipm** [kyma-project/kyma#16375]
Still we have samples in doc which contains v1alpha1:
- [x] docs/02-get-started/04-trigger-workload-with-event.md
- [x] docs/03-tutorials/00-application-connectivity/ac-05-call-registered-service-from-kyma.md
- [x] docs/03-tutorials/00-eventing/evnt-03-type-cleanup.md
- [x] docs/03-tutorials/00-eventing/evnt-04-change-max-in-flight-in-sub.md
- [x] docs/03-tutorials/00-serverless/svls-01-create-inline-function.md
- [x] docs/03-tutorials/00-serverless/svls-02-create-git-function.md
- [x] docs/03-tutorials/00-serverless/svls-13-override-runtime-image.md
- [x] docs/03-tutorials/00-serverless/svls-14-inject-envs.md
- [x] docs/05-technical-reference/svls-01-sample-functions.md
- [x] docs/05-technical-reference/00-configuration-parameters/svls-02-environment-variables.md

**Comment by kwiatekus** [comment]
Thank you
