### ISSUE TITLE
Issue JWT - best practices blogpost

### ISSUE THREAD

**Issue by strekm** [kyma-project/kyma#16383]
**Description**

Based on internal evaluation of JWT best practices create a blogpost explaining best practices to issue JWT.

**Area**
* Security

**Assignees**

@kyma-project/technical-writers
@kyma-project/goat 

**Attachments**

**Comment by nataliasitko** [comment]
The [blog post](https://kyma-project.io/blog/2023/1/12/jwt-best-practices/) is ready.
