### ISSUE TITLE
Remove kiali component

### ISSUE THREAD

**Issue by a-thaler** [kyma-project/kyma#16391]
**Description**
After kiali got deprecated and three releases are over it gets time to remove it.

**Criterias:**
- delete resources folder
- remove component from all component lists
- remove third-party-image
- remove prow jobs and manual test cases
- remove docu
- Prepare release notes and migration script
- keep the tutorial and links to the tutorial

**Reasons**

**Attachments**

https://github.com/kyma-project/kyma/issues/15412

**Comment by chrkl** [comment]
The following changes have been made:
- Removed the Kiali component from the Kyma repository
- Removed Kiali from the documentation
- Removed the third-party image and related Prow jobs
- Added a migration guide with a script to remove all Kiali related resources
