### ISSUE TITLE
Requesting OAuth token is performed without server's certificate chain verification

### ISSUE THREAD

**Issue by akgalwas** [kyma-project/kyma#1639]
**Description**

OAuth token is obtained with tls.Config.InsecureSkipVerify property set to true. 

**Expected result**

There should be command line argument specifying the value of tls.Config.InsecureSkipVerify property used when getting OAuth token to allow the user to decide whether certificate verification should be done. The existing skipVerify command line option is used for configuring ReverseProxy so probably we should add a new one for better flexibility.

**Comment by lszymik** [comment]
Hello @akgalwas,

There is an environment variable in Proxy service which is controlling if the proxy should skip SSL certificate verification. 

Maybe we just need to reuse it?

**Comment by Disper** [comment]
I've learned from @akgalwas that the issue is still valid.
