### ISSUE TITLE
Deprecate tracing component

### ISSUE THREAD

**Issue by a-thaler** [kyma-project/kyma#16390]
**Description**
As part of https://github.com/kyma-project/kyma/issues/15852 the tracing component needs to get deprecated. For that the documentation needs to be either deprecated or replaced with the tutorial. Furthermore we need proper release notes.

**Criterias**
- Every occurence of Jaeger in the docu (incl diagrams) are touched and
  - either marked as deprecated
  - or removed/replaced with a link
- Deprecation notes are referencing the related release note

**Reasons**

**Attachments**

**Comment by chrkl** [comment]
Documentation related to Jaeger has been removed or marked as deprecated with #16575.
