### ISSUE TITLE
Failing pipeline: Error: cannot get jaeger trace

### ISSUE THREAD

**Issue by Tomasz-Smelcerz-SAP** [kyma-project/kyma#16430]
**Description**

[kyma-upgrade-gardener-kyma2-to-main-reconciler-main](https://status.build.kyma-project.io/job-history/gs/kyma-prow-logs/logs/kyma-upgrade-gardener-kyma2-to-main-reconciler-main) and [kyma-upgrade-k3d-kyma2-to-main](https://status.build.kyma-project.io/job-history/gs/kyma-prow-logs/logs/kyma-upgrade-k3d-kyma2-to-main) are failing since yesterday due to Tracing tests failures.

**Expected result**

The pipeline runs the tests without errors
**Actual result**

You can observe this in the logs:

```
19 passing (2m)
  1 failing

  1) Upgrade test tests
       Tracing Tests:
         with Nats backend
           in-cluster structured event should have correct tracing spans:
     Error: cannot get jaeger trace
404: Not Found: {"data":null,"total":0,"limit":0,"offset":0,"errors":[{"code":404,"msg":"trace not found"}]}
      at convertAxiosError (utils/index.js:116:10)
      at getJaegerTrace (tracing/client.js:23:11)
      at processTicksAndRejections (internal/process/task_queues.js:95:5)
      at async checkTrace (test/fixtures/commerce-mock/index.js:326:20)
      at async checkInClusterEventTracing (test/fixtures/commerce-mock/index.js:322:3)
      at async Context.<anonymous> (tracing/index.js:30:9)
```

**Steps to reproduce**

**Troubleshooting**
n/a

**Comment by rakesh-garimella** [comment]
should be fixed via: https://github.com/kyma-project/test-infra/pull/6638

**Comment by rakesh-garimella** [comment]
The issue has been resolved so closing the issue.
