### ISSUE TITLE
http protocol as a trusted issuer in APIRule not possible

### ISSUE THREAD

**Issue by martinfrick** [kyma-project/kyma#16463]
**Description**

I'm facing an issue trying to provide an "http" url as a trusted_issuer in an APIRule. Per definition of the Custom Resource "**apirules.gateway.kyma-project.io**" only "https" and "file" are allowed.

trusted_issuers:
 type: array
 items:
   type: string
   pattern: '^(https://|file://).*$'

Still, for my scenario which deals with multitenant SaaS applications, the token issuer is "**http**://sap-provisioning.localhost:8080/uaa/oauth/token" when it arrives in my application as a subscription callback. This cannot be changed in a SAP BTP scenario. A similar process is also described in the official [SAP-samples tutorial](https://github.com/SAP-samples/kyma-runtime-extension-samples/blob/main/saas-provisioning/README.md#deploy-the-sample) where it is suggested to provide the following value to the trusted_issuers. 

**Issuer: http://sap-provisioning.localhost:8080/uaa/oauth/token**

Can you please check if that limitation to https and file can be changed to support such SaaS related scenarios on SAP BTP using APIRules?

Thanks Martin

**Comment by strekm** [comment]
https://github.com/kyma-project/api-gateway/pull/418
