### ISSUE TITLE
Update testing tooling to support sending legacy events and creating v1alpha2 subscriptions

### ISSUE THREAD

**Issue by friedrichwilken** [kyma-project/kyma#16469]
- [x] Update the test-tooling for eventing to support sending legacy events and creating v1alpha2 subscriptions.
- [x] Update the docs; look for recent name changes (`loadtester` -> `loadtest`)
- [x] Run Loadtest for every scenario
  - cloudevent / legacy event dispatching 
  - on EventMesh / NATS

**Comment by k15r** [comment]
- [ ] configure subscription version
- [ ] configure event-format
- [ ] send legacy event (to legacy endpoint)
- [ ] local dev setup?
