### ISSUE TITLE
Release channel information for users

### ISSUE THREAD

**Issue by pbochynski** [kyma-project/kyma#16479]
**Description**
Make sure users are aware of the release channels used in their clusters and the consequences of using beta channel modules in production deployments. That information should be available in:
- [x] Kyma dashboard cluster overview
- [ ] ~~BTP cockpit (based on Kyma Environment Broker instance labels), [task](https://github.com/kyma-project/control-plane/issues/2379)~~

**Reasons**

Release channels introduced in [the modularization concept] give users more control over the update process and introduce a way to try new features before in the early phase. Even though all module releases fulfill product standards those released in the beta channel cannot be offered with the same level of stability and there is no guarantee that issues will be resolved as quickly as for the regular channel. Users should be aware (warned) that they have beta modules enabled in their clusters and they can expect that the support for such clusters is based on the best effort.

**Attachments**

**Comment by valentinvieriu** [comment]
We first need to implement https://github.com/kyma-project/busola/issues/2246 so that we can easily add this functionality as an extension.

**Comment by pbochynski** [comment]
Kyma Dashboard notification is a better place enough and modules are enabled there so the warning can be displayed before the module is enabled. Information in the BTP cockpit can be dropped.

**Comment by pbochynski** [comment]
It is already implemented
