### ISSUE TITLE
Update documentation of Eventing/Subscription in Serverless docs

### ISSUE THREAD

**Issue by mfaizanse** [kyma-project/kyma#16491]
Kyma Eventing will soon release the new Subscription CRD `v1alpha2` version which has different `spec` format for subscribing to events. See docs from this [PR](https://github.com/kyma-project/kyma/pull/16340) for more information.

There are some documents in Serverless component, which needs to be updated to use Subscription CRD `v1alpha2`:
- [Set asynchronous communication between Functions](https://kyma-project.io/docs/kyma/latest/03-tutorials/00-serverless/svls-11-set-asynchronous-connection-of-functions/)
- [Function configuration file](https://kyma-project.io/docs/kyma/latest/05-technical-reference/svls-06-function-configuration-file/)

**Tasks:**
- [ ] Check if Serverless / Kyma CLI needs to do any internal code changes to support the new Subscription CRD `v1alpha2`. Since `kyma init function` is generating some `config.yaml` file, Serverless needs to check this.
- [ ] Update the Serverless documents.

**Comment by friedrichwilken** [comment]
@muralov can you give a status update here, please?

**Comment by muralov** [comment]
here is their [PR-16931](https://github.com/kyma-project/kyma/pull/16931). Hence, they are almost done.

**Comment by friedrichwilken** [comment]
blocked until aforementioned prs are merged

**Comment by muralov** [comment]
closing as the above PRs are merged and saw documentation is updated too.
