### ISSUE TITLE
Cannot create subscription v1alpha2 from function > configuration tab in Busola

### ISSUE THREAD

**Issue by mfaizanse** [kyma-project/kyma#16501]
**Steps:**
1. Create a function using busola and go to `configuration` tab.
![image](https://user-images.githubusercontent.com/9897945/210748709-b45d93b5-a2ae-44bd-8ccf-30a73013ed5a.png)

2. Create a subscription.
![image](https://user-images.githubusercontent.com/9897945/210748515-3762e09f-56e6-4980-899c-784838f54841.png)

3. Click on `create`. The following error will appear:
![image](https://user-images.githubusercontent.com/9897945/210748626-ca675565-98b4-4bb7-97fa-10a43a180bf7.png)

**Hint:**
We need to update the Subscription CRD version in Function Busola extension.

**Comment by mfaizanse** [comment]
According to this [ticket](https://github.com/kyma-project/kyma/issues/16444), it is currently not possible. Either we can remove the subscription from Functions view, or wait for Busola to support this.

If we remove then we also need to update out docs.

**Comment by muralov** [comment]
we need to check once more. According to the [ticket](https://github.com/kyma-project/kyma/issues/16444) it is fixed.

**Comment by friedrichwilken** [comment]
update: this issue is still relevant.

**Comment by friedrichwilken** [comment]
we need to talk to the Busola team and as them to change the subscription version in the function extension.

**Comment by friedrichwilken** [comment]
With the next release of Kyma (`v2.12`) the Function gage will temporarily lose the "Create Subscription" button and for and one will only be able to create Subscriptions from the Subscription page. Eventually, after v1alpha1 will be removed after 6 months, the button will come back and one will be able to create Subscriptions from the Function page again. 

If you take a look at the first picture, you can see that the same happened with the "Create API Rule" button.
