### ISSUE TITLE
Upgrade Kyma 2.9.3 to 2.10.0-rc1 breaks Eventing

### ISSUE THREAD

**Issue by marcobebway** [kyma-project/kyma#16529]
**Description**

While testing 2.10.0-rc1 we discovered that upgrading Kyma 2.9.3 to 2.10.0-rc1 breaks Eventing.

**Expected result**

Eventing (control-plane and data-plane) should be working before and after the upgrade.

**Actual result**

Eventing (control-plane and data-plane) is broken after the upgrade.

**Steps to reproduce**

- Provision Kyma 2.9.3.
- Create Eventing infra.
- Verify Eventing (it should be working).
- Upgrade to Kyma 2.10.0-rc1.
- Verify Eventing (it is not working).

**Troubleshooting**

- NATS health endpoints reported that JetStream is not healthy.
- Restarting all NATS pods fixed the issue.
- Maybe we need to restart the Eventing controller and Publisher (but that is not confirmed to fix the issue).
- After upgrade EPP reports `{"level":"ERROR","timestamp":"2023-01-11T11:09:50Z","caller":"handler/handler.go:287","message":"publishing target on backend not found : cannot send to stream, nats: no response from stream","context":{}}`.

**Notes**

- NATS improved their health endpoints (see [charts](https://github.com/nats-io/k8s/tree/main/helm/charts/nats)). This could help self-heal JetStream when it goes down. We have a [ticket](https://github.com/kyma-project/kyma/issues/15046) for this.

**Comment by mfaizanse** [comment]
The potential fix for this issue is in NATS `v2.9.11`, but we cannot upgrade the NATS `v2.9.11` until we check this version for stability. So for now, we are reverting back the NATS to `v2.9.6`.
