### ISSUE TITLE
Execute Manual Tests for New CRD Thoroughly

### ISSUE THREAD

**Issue by muralov** [kyma-project/kyma#16544]
Manual testing :
  - test all new possible permutations: 
     - for (legacy, cloudevent)
        test dispatching to eventmesh and jetstream
        with subscriptions in standard and exact mode 
     - Test also with varkes (aka commerce mock)
     - Find missing scenarios in the automated tests and create a followup ticket
   - validate monitoring and tracing for each scenario

**Comment by muralov** [comment]
Test cases

JetStream:
  - [ ] CE, JS, exact
  - [ ]  CE, JS, standard
  - [ ] Legacy, JS, exact
  - [ ] Legacy, JS, standard
  
Event Mesh:
  - [ ] CE, EM, exact
  - [ ] CE, EM, standard
  - [ ] Legacy, EM, exact
  - [ ] Legacy, EM, standard

Other tests
- [ ] Commerce Mock 
- [ ] Monitoring
- [ ] Tracing

**Comment by muralov** [comment]
Issues found:
- https://github.com/kyma-project/kyma/issues/16599
- https://github.com/kyma-project/kyma/issues/16591
- https://github.com/kyma-project/kyma/issues/16619

Note: Monitoring is tested only with in-cluster eventing.

**Comment by k15r** [comment]
first iteration of tests has been completed. Follow up tasks have been defined
