### ISSUE TITLE
Prepare keda-manager developer's guide 

### ISSUE THREAD

**Issue by m00g3n** [kyma-project/kyma#16556]
**Description**

Create a guide for `keda-manager` developer 

**AC:**

1. It should cover the following topics
- modularisation requirements (what/where/why)
- module and ci/cd architecture
- project layout

2. It should be a reference on how to create a `kyma-module`

**Comment by kwiatekus** [comment]
moved here https://github.com/kyma-project/keda-manager/issues/84
