### ISSUE TITLE
Investigate if overriding ProtocolSettings and WebhookAuth makes sense for eventing

### ISSUE THREAD

**Issue by raypinto** [kyma-project/kyma#16559]
**Description**

Currently we have default ProtocolSettings and WebhookSAuth values while using EventMesh. If overrides are provided as config values, we apply them.

The question is: Can we really provide override credentials since we manage the webhook and create the credentials ourselves? What is the real usecase for this?

**Expected output**

- [ ] Investigate if we should really allow overriding ProtocolSettings and WebhookAuth Values and state the reason here for documentation purposes.
  - [ ] If not, cleanup the overriding logic and config validation for the same.
- [x] https://github.com/kyma-project/kyma/issues/15506

**Comment by k15r** [comment]
this is gone with v1alpha2
