### ISSUE TITLE
Kyma CLI returns error regarding the used image when provisioning on gardener

### ISSUE THREAD

**Issue by friedrichwilken** [kyma-project/kyma#16564]
**Description**

Kyma CLI (v2.9.3) will return an error if used to provision a cluster:
```
$ kyma provision gardener gcp -n myname -s mysecret -p myproject -c ~/mycredential.yaml
```
with the error looking like this:
```
- Validating flags
X Provisioning Gardener(GCP) cluster
Error: unable to provision gardener cluster: shoots.core.gardener.cloud "myname" is forbidden: [spec.provider.workers[0].machine.image: Invalid value: core.ShootMachineImage{Name:"gardenlinux", ProviderConfig:(*runtime.RawExtension)(nil), Version:"576.9.0"}: machine image '&{gardenlinux nil 576.9.0}' does not support CPU architecture 'amd64' or is expired, valid machine images are: [machineImage(gardenlinux:934.2.0) machineImage(gardenlinux:934.1.0) machineImage(gardenlinux:934.0.0) machineImage(gardenlinux:912.0.0) machineImage(gardenlinux:576.12.0) machineImage(gardenlinux:576.11.0) machineImage(gardenlinux:576.10.0)]]
```

It looks like the prow-jobs run into [the same issues](https://status.build.kyma-project.io/view/gs/kyma-prow-logs/pr-logs/pull/kyma-project_kyma/16524/pre-main-kyma-gardener-gcp-eventing/1614893712762998784).

**Expected result**

Provision without error.

**Actual result**

**Steps to reproduce**

See the aforementioned command line input.

**Troubleshooting**

**Comment by halamix2** [comment]
Prowjobs are using `kyma provision gardener` command
CLI uses hardcoded Gardener Linux version 576.9.0, e.g. https://github.dev/kyma-project/cli/blob/main/cmd/kyma/provision/gardener/aws/cmd_test.go#L139

**Comment by jakobmoellersap** [comment]
The main issue is that even with scraping there is no easy way to determine the new latest stable for gardener. Instead the newest release is almost always flagged as preview. Thus I just created a bump job for now. If there are ideas on how to always automatically get latest stable to bump, I am happy for input.

**Comment by jakobmoellersap** [comment]
CLI 2.10.0 contains updated defaults and is propagated to unstable and stable CLI binaries. All jobs should be unblocked.

**Comment by friedrichwilken** [comment]
Thank you, @jakobmoellersap. :)
