### ISSUE TITLE
Remove tracing component

### ISSUE THREAD

**Issue by a-thaler** [kyma-project/kyma#16584]
**Description**
After jaeger got deprecated and three releases are over it gets time to remove it.

**Criterias:**
- kyma repo cleanup
  - delete resources folder
  - remove usage of global.tracing.enabled setting
  - remove component from all component lists
- 3party repo cleanup
  - remove folder/module in third-party-image repo
  - remove prow jobs
- Surroundings
  - remove/adjust docu
  - Prepare release notes and migration script
  - Remove entry in SKR feature matrix
  - keep the tutorial and links to the tutorial
  - verify tutorial once more
- Tests
  - replace jaeger deployment in integration tests
  - remove manual test cases
  - verify periodic jobs for healthyness

**Reasons**

**Attachments**

https://github.com/kyma-project/kyma/issues/15852

**Comment by rakesh-garimella** [comment]
Removing from components.yaml in control-plane: https://github.com/kyma-project/control-plane/pull/2708

**Comment by rakesh-garimella** [comment]
```
kyma repo cleanup
[x]  delete resources folder
[x]  remove usage of global.tracing.enabled setting
[x]  remove component from all component lists
3party repo cleanup
  [x] remove folder/module in third-party-image repo
  [x] remove prow jobs
Surroundings
  [] remove/adjust docu (PR in review)
  [x] Prepare release notes and migration script
  [x] Remove entry in SKR feature matrix
  [x] keep the tutorial and links to the tutorial
  [x] verify tutorial once more
Tests
[x] replace jaeger deployment in integration tests
[x] remove manual test cases
[] verify periodic jobs for healthyness (in Progress)
```
