### ISSUE TITLE
Service Name is not Prepended to the Sink in Busola function Subscription UI

### ISSUE THREAD

**Issue by muralov** [kyma-project/kyma#16619]
**Description**

Service name not prepended to the sink in Busola function Subscription UI

**Expected result**

service name is prepended if it is selected or typed

**Actual result**

actual result:
![image](https://user-images.githubusercontent.com/13185122/213467181-1dbccc38-0d6d-442a-a9f2-9d669d7edce4.png)

**Steps to reproduce**

1. Install Kyma with new CRD enabled
1. Create a function with Busola
2. Create Subscription for the function with Busola
3. Select service name from drop-down or type it

**Comment by raypinto** [comment]
Question: Can we make the service field only as a drop down and not a free text?

**Comment by muralov** [comment]
closing as it is duplicate
