### ISSUE TITLE
[TB: 2d] Find Missing Scenarios in the Automated Tests for New CRD

### ISSUE THREAD

**Issue by muralov** [kyma-project/kyma#16624]
**Description**

Find missing scenarios in the automated tests for new CRD. Accordingly create issues. 
- [x] Find missing test scenarios in the automated tests for new CRD.
- [x] Create an issue or issues for the missing cases

**Reasons**
To automate the manual tests missing in the automated tests

**Attachements**
- Here are the [manual tests scenarios](https://github.com/kyma-project/kyma/issues/16544#issuecomment-1378837339) 
- Here are the [issues](https://github.com/kyma-project/kyma/issues/16544#issuecomment-1397066943) in which you find detailed steps

**Follow-up:**
- [ ] https://github.com/kyma-project/kyma/issues/16651

**Comment by k15r** [comment]
- [ ] create a matrix (existing tests, required tests)
- [ ] involve factors 
  - source
  - event format
  - event type
  - backend
  - (un)clean 
  - upgrade
  - ...

**Comment by mfaizanse** [comment]
Manually tested event types:
v1alpha1:
sap.kyma.custom.noapp.order.created.v1
sap.kyma.custom.test-app.order.created.v2
sap.kyma.custom.test-app.o!r-d-e#r.c*r(e)a/ted.v3
sap.kyma.custom.test-app.or-der.crea-ted.one.two.three.v4

v1alpha2:
o!r-d-e#r.c*r(e)a/ted.v6
order.created.one.two.three.four.v7

**Comment by mfaizanse** [comment]
Results are gathered in this ticket: https://github.com/kyma-project/kyma/issues/16651
