### ISSUE TITLE
Implement Publish API based on Knative eventing

### ISSUE THREAD

**Issue by abbi-gaurav** [kyma-project/kyma#1662]
### Description
To built Kyma eventing on top of Knative eventing, we need to have an implementation of the Publish API that is using Knative abstractions.

### AC
- [x] There is code merged in for the publish' (publish based on Knative).
- [x] Prow pipeline to create and release the image.
- [x] DoD applied
- [x] Manual verification done (replace the image in publish helm and the publish API works)

**Comment by marcobebway** [comment]
I verified the publish app locally with the following steps:
- Start kyma with the knative feature flag provided.
- Update knative-eventing controller and webhook versions to be `https://console.cloud.google.com/gcr/images/knative-releases/GLOBAL/github.com/knative/eventing/cmd/controller@sha256:3486cb9d337b829907532e78c8098b6680fbe3aa10a0aa81e7db327bb8980640/details?tab=info` and `http://gcr.io/knative-releases/github.com/knative/eventing/cmd/webhook@sha256:0c8e6180481663045088cebea41cfbf92ef590da748b92bed77a8c0dc2539bff` respectively.
- Deploy nats-streaming server and provisioner
- Deploy the knative-publish app.
- Send publish requests to the knative-publish app.
- Check the nats-dispatcher app logs and knative-publish app logs to make sure that the publish request was handled successfully.

**Comment by marcobebway** [comment]
We agreed to not update the apps binaries in this ticket, as It should be done as part of this one https://github.com/kyma-project/kyma/issues/2282.
