### ISSUE TITLE
Allow setting Read_from_Head in fluent-bit INPUT section

### ISSUE THREAD

**Issue by CrawX** [kyma-project/kyma#16645]
**Description**
Currently, the [Read_from_Head](https://docs.fluentbit.io/manual/pipeline/inputs/tail#config) parameter of the fluent-bit tail plugin is left at its default value (`false`). Kyma should provide a way to change that value, eg via the `LogPipeline` CRD or even set it to `true` by default.

**Reasons**
Our managed Kyma cluster was recently updated and all nodes (and therefore all pods) were restarted. We are now missing some logs, presumably because our services were running before fluent-bit was started. When `Read_from_Head` is not set, the content of existing log files is read from the tail, not from head. Logs that have been written before fluent-bit is started are therefore ignored.

**Attachments**
The `INPUT` section seems to be configured [here](https://github.com/kyma-project/kyma/blob/main/components/telemetry-operator/internal/resources/logpipeline/resources.go#L301) and looks like its fully static right now.

**Comment by chrkl** [comment]
@CrawX thanks for reporting this. Setting the `Read_from_Head` flag seem to make sense. We will evaluate if that might have any negative impact and then decide how to continue with this.
