### ISSUE TITLE
Implement missing Scenarios in Eventing fast-integration tests

### ISSUE THREAD

**Issue by mfaizanse** [kyma-project/kyma#16651]
**Pre-requisite:**
- [x] https://github.com/kyma-project/kyma/issues/16624

Subtasks:
- [x] #15578 
- [x] #16738
- [x] https://github.com/kyma-project/kyma/issues/16649

## Subscription v1alpha2 CRD Tests: (All backends)

| Case | Subscription Type | CE or Legacy | Example | Coverage |
| --- | --- | --- | --- | --- |
| Clean event type with clean source. | Standard | Cloud Events + Legacy Events | Source: noapp , Type: order.created.v1 | Covered in FI tests |
| Clean event type with unclean source. | Standard | Cloud Events + Legacy Events | Source: test-app , Type: order.created.v1 | Not covered |
| Unclean event type with unclean source. | Standard | Cloud Events + Legacy Events | Source: test-app , Type: Order-äöüÄÖÜβ.Final.C-r-e-a-t-e-d.v1 | Will be covered in: https://github.com/kyma-project/kyma/issues/16738 |
| High number of segments in event type. | Standard | Cloud Events + Legacy Events | Source: test-app , Type: or-der.crea-ted.one.two.three.four.v4 | Not covered |
| Invalid CE source should return error. | Standard | — | Source: s%ourc%e | Covered in unit tests in EC+EPP |
| A valid fully qualified event type should work with EventMesh in Exact mode. | Exact | — | Type: sap.kyma.custom.noapp.order.updated.v1 | Will be covered in: https://github.com/kyma-project/kyma/issues/16738 |

## Subscription v1alpha1 CRD: (All backends)

<aside>
💡 These scenarios should still work after upgrade to Subscription v1alpha2 CRD.

</aside>

| Case | CE or Legacy | Example | Coverage |
| --- | --- | --- | --- |
| Clean event type with clean source. | Cloud Events + Legacy Events | Type: sap.kyma.custom.noapp.order.created.v1 | Covered in FI tests |
| Clean event type with unclean source. | Cloud Events + Legacy Events | Type: sap.kyma.custom.test-app.order.created.v1 | Not covered |
| Unclean event type with unclean source. | Cloud Events + Legacy Events | Type: sap.kyma.custom.no-app.New.Some-Other.Order-äöüÄÖÜβ.Final.C-r-e-a-t-e-d.v1 | Not covered |
| High number of segments in event type. | Cloud Events + Legacy Events | Type: sap.kyma.custom.test-app.or-der.crea-ted.one.two.three.four.v4 | Not covered |

## Eventing Upgrade Tests:

| Case | Example | Coverage |
| --- | --- | --- |
| Keep active publisher and subscribers to test NATS upgrade | — | Not covered. https://github.com/kyma-project/kyma/issues/16649 |
| NATS pods healthy. | /healthz returns HTTP 200 OK | Not covered |
| NATS stream was not re-created by the upgrade. | Note stream creation timestamps before and after upgrade, and compare them. | Covered in FI tests |
| NATS consumers do not get re-created by the upgrade. | Note consumers creation timestamps before and after upgrade, and compare them. | Will be covered: https://github.com/kyma-project/kyma/issues/16738 |
| All existing subscriptions (v1alpha1 + v1alpha2) work. | Published events are received by the sink | Covered in FI tests |
| NATS events are not lost after upgrade. | Undelivered events on NATS should not be lost after the upgrade | Not covered. https://github.com/kyma-project/kyma/issues/15578 |
| Backend switching works. | Between NATS and EventMesh | Covered in FI tests |
| Monitoring works. | — | Covered in FI tests |
| Tracing works (OSS only). | — | Covered in FI tests |

**Comment by grischperl** [comment]
Leaving this closed, as pre-requisites and subtasks are all marked as closed.
