### ISSUE TITLE
Issues with svls-11-set-asynchronous-connection-of-functions.md

### ISSUE THREAD

**Issue by ArthurPerry** [kyma-project/kyma#16708]
**Description**
‘
(https://github.com/kyma-project/kyma/blob/main/docs/03-tutorials/00-serverless/svls-11-set-asynchronous-connection-of-functions.md)

This documentation has issues with the receiver function configuration.  

When I try to add the subscriptions section to my receiver-function.yaml I get the following error:
`error validating data: ValidationError(Function.spec): unknown field "subscriptions" in io.kyma-project.serverless.v1alpha2.Function.spec; if you choose to ignore these errors, turn validation off with --validate=false`

Also the sample yaml contains `filer` instead of `filter`

**Area**

* Serverless Functions

**Reasons**

The Function CRD does not conform to the sample YAML.  We still need to configure a separate Subscription instance.

**Assignees**

@kyma-project/technical-writers

**Attachments**

**Comment by grego952** [comment]
Fixed with https://github.com/kyma-project/kyma/pull/16931
If the issue persists, please reopen the issue.
