### ISSUE TITLE
Fluent Bit prints error on startup

### ISSUE THREAD

**Issue by a-thaler** [kyma-project/kyma#16733]
**Description**
Since the upgrade to fluentbit 2.0.x, it prints an error on startup:
```
[2023/02/03 15:14:36] [error] [/src/fluent-bit/src/config_format/flb_cf_fluentbit.c:290 errno=2] No such file or directory
[2023/02/03 15:14:36] [error] file=/fluent-bit/etc/parsers.conf
[2023/02/03 15:14:36] [error] [/src/fluent-bit/src/config_format/flb_cf_fluentbit.c:290 errno=2] No such file or directory
[2023/02/03 15:14:36] [error] file=/fluent-bit/etc/dynamic-parsers/parsers.conf
```

The files are missing in case no LogParser is defined. It seems that functionality is not affected.

I recommend to refactor the parser generation logic in general to also avoid the initContainer at all. That was required when fluentbit was not managed by the telemetry operator.

**Criterias**
- No error on startup
- One well-defined parsers.conf for the dynamic parsers generated out of LogParser definitions. If there is no parser, the file is empty, but always present
- One well-defined file with static parser config
- No initContainer anymore
- Upgrade to initContainer-less version is tested once (no initContainer after upgrade)
- Have a env test assuring that logParsers end up in the related configmap

**Comment by rakesh-garimella** [comment]
Fixed the error logs of missing parser config file[here](https://github.com/kyma-project/kyma/pull/16767)

**Comment by rakesh-garimella** [comment]
The errors have been fixed and init container has been removed. Additionally tests coverage has been improved by adding tests for logparser controllers.
