### ISSUE TITLE
fix subscription creation via kyma-cli for v1alpha1 with validating webhook

### ISSUE THREAD

**Issue by k15r** [kyma-project/kyma#16739]
** Description **

Create a function with embedded subscription and v1alpha2 is enabled on the cluster.
Validation webhook fails and the subscription cannot be created

**Expected**
v1alpha1 subscription gets created and will be converted to v1alpha2

**Comment by muralov** [comment]
closing as it is not reproducible anymore

**Comment by muralov** [comment]
closing as it is not reproducible anymore
