### ISSUE TITLE
[Telemetry Operator] NetworkPolicy for fluentbit managed by operator

### ISSUE THREAD

**Issue by a-thaler** [kyma-project/kyma#16754]
**Description**
The networkPolicy for fluentbit is currently provisioned by the operator helm chart. If it is needed, it should be managed by the operator itself as it belongs to the fluentbit setup.

**Criterias**
- policy is removed from the helm chart
- policy gets deployed/undeployed dynamically together with the daemonset
- env test assures that resource gets created

**Comment by rakesh-garimella** [comment]
The network policy helm chart has been removed.

**Comment by a-thaler** [comment]
I hope you removed only the specific resource, not the whole chart :P
