### ISSUE TITLE
Adjust the Get Started docs to modular approach

### ISSUE THREAD

**Issue by grego952** [kyma-project/kyma#16778]
**Description**

**Requirements**
- [x] - Update [Quick Install](https://kyma-project.io/docs/kyma/latest/02-get-started/01-quick-install/) section
- [x] - elaborate if/how user should enable relevant modules
- [x] - link to another document explaining modular Kyma and listing all modules (probably provided with https://github.com/kyma-project/kyma/issues/17210 ?)
**Area**

**Reasons**

**Assignees**

@kyma-project/technical-writers

**Attachments**

**Comment by pbochynski** [comment]
The installation guide should reflect the transition phase from components to modules. It should be clear that you install all the components that are not yet modularized with `kyma deploy` command and the rest with operator(manager) deployment and applying module configuration (as described in the decision record: https://github.com/kyma-project/community/issues/792)

**Comment by mmitoraj** [comment]
An update of the Quick Install guide will be covered with the [Add information on modular Kyma PR](https://github.com/kyma-project/kyma/pull/17454).
