### ISSUE TITLE
Non-descriptive Readme.md, with closed-door url

### ISSUE THREAD

**Issue by DubbaThony** [kyma-project/kyma#16787]
**Description**

When entering github page first thing informing users what repository is about is README.md. 
Here, in Kyma project, I am refered to external websites to figure it out. 
This readme dosen't make the judgement of usability for given purpose easier for people intrested in project, 
rather quite the opposite. 
After reading readme.md I still didn't learn what kyma project is capable of. 
I get that in general it's a repository about some toolkit for cloud projects around kubernetes, with few features named, like event support etc, but still this dosen't get me at glance what tools are provided. Im not saying that this readme need to be redcarpeting, but copy-paste of [main page of kyma documentation](https://kyma-project.io/docs/kyma/latest/) into readme.md would help significantly - still it dosen't tell me exactly what capabilities are, but gives me some idea what the project is. I would suggest adding that content into readme.md and moving contribution related stuff into `CONTRIBUTING.md` 

Some sections of readme seem like they should belong in `CONTRIBUTING.md` 

Another issue is that readme.md file contains URL to github enterprise, which seems weird in a FOSS project.

**Area**

Readme of repository

**Reasons**

README should be enough to quickly understand scope of functionality provided by the project.

**Assignees**

n/a

**Attachments**
n/a

**Comment by tobiscr** [comment]
@NHingerl : could TWs take this issue?

**Comment by grego952** [comment]
Hi @DubbaThony 
Thank you for all your suggestions.
We will work on upgrading the main README.md file.
In the meantime, the URL to the GitHub enterprise was fixed with [this PR](https://github.com/kyma-project/kyma/pull/16815).

**Comment by grego952** [comment]
Hi @DubbaThony 
Can you take a look at the above PR and tell me what you think about the introduced changes?

**Comment by DubbaThony** [comment]
The readme is significantly improved in this PR. It definitively closes this issue.

**Comment by grego952** [comment]
Great! Thanks a lot :)
