### ISSUE TITLE
Improve Deleting Dangling Consumers

### ISSUE THREAD

**Issue by muralov** [kyma-project/kyma#16793]
**Description**
We have experienced that there were some dangling consumer although the EC cleans them on the startup. 
There is an assumption that they cannot be cleaned during upgrade where NATS is not 100% up-and-running. 

**Expected result**

no dangling consumers

**Actual result**

There are still some dangling consumers

**Steps to reproduce**

/to-be-done

**Comment by muralov** [comment]
one solution could to wait until NATS is 100% before cleanup and controller startup.

**Comment by k15r** [comment]
could not reproduce
