### ISSUE TITLE
create NATS CRD for NATS-manager (discuss with team)

### ISSUE THREAD

**Issue by k15r** [kyma-project/kyma#16825]
required configuration fields:
- no of cluster nodes
- pvc size / stream size in memory
- limits / requests

inspired by values.yaml (nats upstream) 
- check https://docs.nats.io/running-a-nats-service/configuration#variables

**Comment by k15r** [comment]
Can we make pvc size immutable? Means it could be set once

**Comment by mfaizanse** [comment]
Proposal added!
