### ISSUE TITLE
`kyma-upgrade-gardener-kyma2-minor-versions` - Cannot deploy eventing

### ISSUE THREAD

**Issue by jeremyharisch** [kyma-project/kyma#16841]
**Description**
The `kyma-upgrade-gardener-kyma2-minor-versions` pipeline has several failed runs due to the eventing component. It cannot be deployed and reached context deadline.

Please have a look at the logs: https://status.build.kyma-project.io/job-history/gs/kyma-prow-logs/logs/kyma-upgrade-gardener-kyma2-minor-versions

**Comment by k15r** [comment]
i see, that the cluster here uses kubernetes 1.21. Is this actually a still supported k8s version?
the problem is related to PodSecurityPolicies / PodSecurityAdmission which prevent the eventing controller to start.

**Comment by khlifi411** [comment]
Closing as upgrading the k8s cluster version fixed the issue.
