### ISSUE TITLE
check infrastructure setup used by front runner projects

### ISSUE THREAD

**Issue by k15r** [kyma-project/kyma#16842]
Gather knowledge about existing implementations for tooling for modular kyma:
- pipeline tooling
- integration with github
- which types of tests are executed and how are they executed
- build pipelines

**Comment by mfaizanse** [comment]
- https://github.com/kyma-project/keda-manager
- https://github.com/kyma-project/telemetry-manager

**Comment by mfaizanse** [comment]
- What test infrastructure are you using for the build jobs for the xx-operator?
- What  test infrastructure  are you using for pre-main jobs of PRs to your xx-operator?
- Do you have any CI/CD pipelines for testing your xx-operator with different versions of your component (upgrade etc.)?
    - If yes, what kind of tests your are running? unit-tests, integration-tests, component tests etc.?
    - If yes, what test infrastructure are you using for these pipelines? (e.g. prow, spinnaker, ArgoCD, github actions ????)
- Do you have any CI/CD pipelines for release of your xx-operator and the your component (upgrade etc.)?
    - If yes, what test infrastructure are you using for these pipelines? (e.g. prow, spinnaker, ArgoCD, github actions ????)

**Comment by mfaizanse** [comment]
## Keda Manager
- What test infrastructure are you using for the build jobs for the keda-operator?
    - Yes, we use only Prow.
- What test infrastructure are you using for pre-main jobs of PRs to your keda-operator?
    - Yes, we use only Prow, the [README.md](https://github.com/kyma-project/keda-manager) covers all the jobs that we have.
        - PR: https://github.com/kyma-project/keda-manager/pull/100
    - The jobs are executed either on PR or merge to `keda-manager’s` main branch.
        - The main difference is with `artifact-registry` and `docker-repository` that we are using to store OCI images and docker images.
    - We have 2 kind of tests:
        - Based on [envtest](https://book.kubebuilder.io/reference/envtest.html] (coming from `kubebuilder`) - checking create/update/delete of Keda CRD that we manage with `keda-manager`.
    - Smoke integration test performed on k3d (just a simple check agains `module-manager` and `lifecycle-manager`).
- Do you have any CI/CD pipelines for testing your keda-operator with different channels of your component (upgrade etc.)?
    - We are working on a upgrade tests ([issue](https://github.com/kyma-project/keda-manager/issues/83)).
    - Besides the 3 jobs described in the ticket we also plan to add one more to test upgrade between channels (atm there is only 1 channel).
- Do you have any CI/CD pipelines for release and automated release-testing of your keda-operator with different channels of KEDA (upgrade etc.)?
    - The release process is manual, we create a PR to `kyma-project` in [this folder](https://github.com/kyma-project/kyma/tree/main/modules).
- Are all CI/CDs are based on prow?
    - Right now, all the CI/CD pipelines are based on prow. We also have plans to experiment with the tekton (when Neighbours will ship it).

**Comment by mfaizanse** [comment]
## Telemetry Manager

- Currently telemetry manager plan to use prow for now for all CI/CD.
- For CI/CD, they are still in planning phase.
