### ISSUE TITLE
kyma 2.11 does not clean up pod preset

### ISSUE THREAD

**Issue by johgoe** [kyma-project/kyma#16862]
**Description**

After upgrading to 2.11 there are still pod running for pod preset. I guess there should be a migration guide to clean up the resources of 
https://github.com/kyma-project/kyma/commit/b388bd49bcbef33d7be996fa2335748b17ecbd25#diff-1f9cedf7c37281a8779fdfe855f5e50caa73fe00b5973f721c44b971d41411db

**Comment by PK85** [comment]
@wozniakjan please provide such migration guide, see [example](https://github.com/kyma-project/kyma/blob/main/docs/assets/2.10-2.11-cleanup-kiali.sh)

**Comment by johgoe** [comment]
The script may look like this:

```
#!/usr/bin/env bash

kubectl delete mutatingwebhookconfiguration cluster-essentials-pod-preset-webhook
kubectl delete -n kyma-system secrets cluster-essentials-pod-preset-webhook-cert
kubectl delete -n kyma-system services cluster-essentials-pod-preset-webhook
kubectl delete -n kyma-system deployments.apps cluster-essentials-pod-preset-webhook
kubectl delete clusterrolebindings.rbac.authorization.k8s.io cluster-essentials-pod-preset-webhook
kubectl delete clusterroles.rbac.authorization.k8s.io cluster-essentials-pod-preset-webhook
kubectl delete -n kyma-system serviceaccounts cluster-essentials-pod-preset-webhook 
```

**Comment by wozniakjan** [comment]
thanks @johgoe, PR with script and guide available for review https://github.com/kyma-project/kyma/pull/16867

**Comment by wozniakjan** [comment]
> Check with @IwonaLanger on how to publish that on kyma-project.io

published https://kyma-project.io/docs/kyma/main/migration-guide-2.11-2.12

**Comment by wozniakjan** [comment]
looks like I messed that up and it is supposed to go to https://github.com/kyma-project/kyma/blob/release-2.10/docs/migration-guide-2.9-2.10.md

**Comment by szwedm** [comment]
Closing the issue. Migration guide will be available in kyma-project.io.
