### ISSUE TITLE
Sub validator controller connectivity instability

### ISSUE THREAD

**Issue by Abd4llA** [kyma-project/kyma#1687]
It was found on some cluster that the sub-validator stopped reacting to new EventActivations creations. The cluster was initially working fine, that symptom showed up after about 4 days. 

After deeper investigation, other controllers in Kyma were working fine, restarting istio pilot didn't help, however kubelet logs were not available on that cluster.

When sub-validator pod was deleted, the new one worked fine.

Cluster: a faros provisioned 0.5rc2 cluster.

**Comment by Abd4llA** [comment]
@radufa actually it was working, Sayan was just not using the correct link from Kyma console which goes to the authentication proxy but was accessing the UI directly. We validated that.

**Comment by abbi-gaurav** [comment]
subscription controller is being rewritten using runtime controller for Knative integration.
This task is no longer valid.
