### ISSUE TITLE
Manager deployable with kustomize

### ISSUE THREAD

**Issue by a-thaler** [kyma-project/kyma#16909]
**Description**
As part of https://github.com/kyma-project/kyma/issues/16301 the Telemetry Manager will be deployed in future on base of kustomize files mainly generated by the underlying kube-builder framework. The files will be part of the repository so that the repo is self-contained. Integration tests will be based on them only.
The first step in that direction is to have kustomize files in place and create the skeleton for the new integration tests which are already deploying the manager and verifying the deployment itself

**Criteria**
- the operator can be deployed to a k8s cluster on base of the kustomize files located in the repo (no dependency to kyma-repo)
- the result of a deployment should be equal to a current kyma telemetry module deployment
- an automated integration test verifies that the deployment succeeds and that all relevant resources are in place
- an automated integration test verifies that a removal succeeds and that all relevant resources are removed

**Comment by chrkl** [comment]
The listed PRs did the following changes:
- Move the creation of missing RBAC to the operator
- Restore customise manifests from the kubebuilder project
- Add new end-to-end test suite and created prow job
- Describe new workflows in README

Follow up tasks:
- Improve lifecycle of the webhook configuration
- Cleanup naming in manifest files, depending on requirements for Kyma module
