### ISSUE TITLE
Service Binding failing for GCP service

### ISSUE THREAD

**Issue by brendandobbs** [kyma-project/kyma#1691]
**Description**

Creating a service binding for a GCP service (Spanner) fails. 

Cluster version is 0.5 rc

**Expected result**

Service binding + usage is successfully created with using both the CLI and UI.

**Actual result**

Creating fails. The error message on the binding is the following:

`Failed - ServiceBroker returned failure; bind operation will not be retried: Status: 422; ErrorMessage: <nil>; Description: This request requires client support for asynchronous service operations.; ResponseError: <nil> @ 2018-11-15 23:03:53 +0000 UTC `

**Steps to reproduce**

1. Provision an instance of the Spanner using kubectl ([spanner-instance.txt](https://github.com/kyma-project/kyma/files/2588582/spanner-instance.txt)) or svcat
2. Create a binding using the UI to a lambda function 

The binding will immediately fail. See screenshot below...

![service-binding-failure](https://user-images.githubusercontent.com/5688693/48611847-1a876780-e97f-11e8-939e-d6e66074acd1.png)

**Troubleshooting**

**Comment by PK85** [comment]
@michal-hudy please check if it is the same issue like with SI

**Comment by pkosiec** [comment]
@PK85 The bindingCreateParameter form renders correctly, and all values as passed to UI API Layer:
![screen shot 2018-11-16 at 10 35 46](https://user-images.githubusercontent.com/7155799/48613226-6d671c00-e98b-11e8-82a5-e6709d78572c.png)

**Comment by PK85** [comment]
I've check an error message and it is about that for ServiceBinding communication between SC and Broker Async communication is required, see: https://github.com/openservicebrokerapi/servicebroker/blob/master/spec.md#error-codes

**Comment by PK85** [comment]
Workaround:
- set featureGate service-catalog-controller-manager deployment:
```
         “--feature-gates”,
         “AsyncBindingOperations=true” **
```
- then sync broker, svcat sync gcp-broker

**Comment by brendandobbs** [comment]
to sync the broker: `svcat sync broker gcp-broker --scope cluster`
