### ISSUE TITLE
[Test Case] - Test connectivity_proxy deployment

### ISSUE THREAD

**Issue by koala7659** [kyma-project/kyma#16997]
**Description**

Perform manual test scenario where connectivity_proxy is manually deployed on the Kyma cluster according to the [description in documentation](https://help.sap.com/docs/BTP/65de2977205c403bbc107264b8eccf4b/0c035010a9d64cc8a02d872829c7fa75.html): 

**Expected result**
Connectivity-proxy should be up and running on the SKR cluster

**Comment by tobiscr** [comment]
Closing it as CP is migrated to modularized solution in Feb24.
