### ISSUE TITLE
kyma cli - can not remove only one component

### ISSUE THREAD

**Issue by gabber78** [kyma-project/kyma#17010]
**Description**

Wanted to remove Kiali component (only) from Kyma with the kyma cli using the following command:

kyma undeploy --component kiali  --profile production --concurrency 8 

```
kyma version
Kyma CLI version: 2.11.2
Kyma cluster version: 2.11.2


Client Version: v1.26.1
Kustomize Version: v4.5.7
Server Version: v1.24.9-gke.3200

```

**Expected result**

Removed Kiali componen from Kyma .

**Actual result**

The kyma undeploy --component command is buggy, for first it parsed all the PVC-s on kyma-system and tried to delete them (it didn't succeed because of the pods were still running). After we fixed the  install and tried to run it again (now on a working cluster), it once again tried to delete the PVCs. After deleting these to see if the CLI can proceed, it started removing the rest of the kyma-namespace components.

**Steps to reproduce**

kyma undeploy --component kiali  --profile production --concurrency 8 

**Troubleshooting**

Described above.

**Comment by janmedrek** [comment]
This feature is already implemented with the Modularization approach.
