### ISSUE TITLE
Failing upgrade test pipelines on prometheus tests

### ISSUE THREAD

**Issue by lindnerby** [kyma-project/kyma#17030]
**Description**

The pipelines [kyma-upgrade-gardener-kyma2-to-main-reconciler-main](https://status.build.kyma-project.io/job-history/gs/kyma-prow-logs/logs/kyma-upgrade-gardener-kyma2-to-main-reconciler-main) and [kyma-upgrade-k3d-kyma2-to-main](https://status.build.kyma-project.io/job-history/gs/kyma-prow-logs/logs/kyma-upgrade-k3d-kyma2-to-main) are failing consistently when running upgrade integration tests on step of asserting scrape pool targets for prometheus. Example run logs: 
* https://storage.googleapis.com/kyma-prow-logs/logs/kyma-upgrade-gardener-kyma2-to-main-reconciler-main/1633709389539971072/build-log.txt
* https://status.build.kyma-project.io/view/gs/kyma-prow-logs/logs/kyma-upgrade-k3d-kyma2-to-main/1633377108606586880

**Expected result**
Should succeed.

**Actual result**
Fails with:
```
  1) Upgrade test tests
       Prometheus Tests:
         Prometheus scrape pools should have a target:
     AssertionError: Following scrape pools have no targets: kyma-system/api-gateway/0: expected [ 'kyma-system/api-gateway/0' ] to be empty
      at Object.assertScrapePoolTargetsExist (monitoring/prometheus.js:74:10)
      at async Context.<anonymous> (monitoring/index.js:48:7)
```

**Comment by ruanxin** [comment]
this error appears in [kyma-upgrade-gardener-kyma2-minor-versions](https://status.build.kyma-project.io/view/gs/kyma-prow-logs/logs/kyma-upgrade-gardener-kyma2-minor-versions/1635913736403292160) again, and also in pre-main-reconciler-cli-kyma-prev-to-last-release-upgrade-k3d which blocked [reconciler PR](https://github.com/kyma-incubator/reconciler/pull/1311) to be merged.

**Comment by tobiscr** [comment]
same here ... https://github.com/kyma-incubator/reconciler/pull/1312
