### ISSUE TITLE
Post Release Job for Kyma is failing

### ISSUE THREAD

**Issue by triffer** [kyma-project/kyma#17066]
**Description**

The [Post Release job for Kyma](https://github.com/kyma-project/test-infra/blob/8dfce5f0b716b15cd764db6a3852161a14493001/templates/data/kyma-release-data.yaml#L50) is failing with the following error:
```
ERROR: (gcloud.compute.instances.create) argument --labels: Bad value [release-2.12]: Only hyphens (-), underscores (_), lowercase characters, and numbers are allowed. International characters are allowed.
Usage: gcloud compute instances create INSTANCE_NAMES [INSTANCE_NAMES ...] [optional flags]
```

**Expected result**

Job won't fail on infrastructure setup.

**Comment by kasiakepka** [comment]
The issue is resolved.
