### ISSUE TITLE
Design proposal for Eventing CRD

### ISSUE THREAD

**Issue by k15r** [kyma-project/kyma#17111]
This CR will allow the user to decide which backend to use for eventing.

## Acceptance ##
- backend type
- backend configuration 
  - EventMesh:
    - secret to use for EventMesh
    - secret to use for Webhook Authentication

**Comment by muralov** [comment]
here is the proposal https://github.tools.sap/skydivingtunas/proposals/blob/eventing-manager-proposal/eventing-modularization/eventing-crd.md
