### ISSUE TITLE
improved fluentbit retry handling

### ISSUE THREAD

**Issue by a-thaler** [kyma-project/kyma#17113]
**Description**
In case of an error with the log export, fluentbit will start buffer and retry log delivery. The current retry settings are very low so that a buffer probably cannot run full at all.

**Goal**
Come up with meaningful retry settings so that the buffer gets used and messages are getting dropped only if the buffer is exhausted. Assure relevant metrics are viszualized in the dashboard

**Criterias**
- logs retried and buffered till a meaningful exit criteria is met (like buffer exhausted)
- all relevant settings for the retry and scheduling are configured explicit
- log drops are visualized in the related dashboards
- provide documentation of the limitations

**Comment by chrkl** [comment]
The linked PRs set Fluent Bit's retry limit to unlimited. Consequently, Fluent Bit will retry on errors until a record drops out of the file system buffer. Fluent Bit's output metrics do not reflect records that dropped out of the buffer before reaching the output stage, so the indicator for log drops is a file system buffer that is operating at its limit while continuing reading logs.

The [documentation](https://kyma-project.io/docs/kyma/latest/01-overview/main-areas/telemetry/telemetry-02-logs/#buffer-limits) about buffer limits already covers this behaviour sufficiently.

We decided against explicitly configuring related default settings to potentially consume future upstream changes.

**Comment by chrkl** [comment]
The attached Grafana dashboard screenshot shows the retry behaviour before and after the change.
![Image](https://user-images.githubusercontent.com/318416/229112285-6b91f191-3afb-4d4f-aa54-fda10c050dc0.png)
