### ISSUE TITLE
Verify the API Exposure tutorial

### ISSUE THREAD

**Issue by nataliasitko** [kyma-project/kyma#17123]
**Description**

According to the feedback from the Gardener team, the fourth step of the [Set up a custom domain for a workload](https://kyma-project.io/docs/kyma/latest/03-tutorials/00-api-exposure/apix-02-setup-custom-domain-for-workload/) tutorial is wrong and not needed, as it requires a certificate from Let's Encrypt staging. Such certificates are not valid. To get Let's Encrypt certificates, you can use the default issuer provided by Gardener. 

**Area**

* API Exposure

**Reasons**

* We should verify if the tutorial is correct

**Assignees**

@kyma-project/technical-writers

**Comment by nataliasitko** [comment]
The tutorial is updated: https://kyma-project.io/docs/kyma/main/03-tutorials/00-api-exposure/apix-02-setup-custom-domain-for-workload/

**Comment by ECasio** [comment]
Hi @nataliasitko,

I know you closed this but where do I find the "Kyma domain" ? That part in the tutorial is somehow missing for me (absolute beginner)
