### ISSUE TITLE
[Telemetry Manager] Do not delete module until all resources are deleted

### ISSUE THREAD

**Issue by a-thaler** [kyma-project/kyma#17162]
**Description**
A module should not be able to get deleted if there are still resources managed by the module. Assure that the deletion will be blocked till all resources are deleted. See also serverless as an example

**Criterias:**
- when a module deletion request gets triggered and there are pipeline resources left, the module status should indicate the problem and the deletion should be pending till all resources are cleaned

**Comment by chrkl** [comment]
The linked PR will remove the finalizer from the Telemetry resource only if no pipelines are left and by that block the module deletion.
