### ISSUE TITLE
Eventing pods request much more CPU and memory than they need

### ISSUE THREAD

**Issue by pbochynski** [kyma-project/kyma#17168]
**Description**

The default installation of eventing requests a lot of resources:
- publisher proxy: 410m CPU and 448Mi memory x 2 pods
- controller: 410m CPU and 704Mi memory x 1 pod
- nats: 400m CPU and 576Mi memory x 3 pods

What gives together: **2,43 CPU and 3,33 GB memory** 
The actual usage of eventing pods in the idle cluster is: **0.015 CPU and 0.35 GB** 

Could you adjust requests settings to allow better cluster resources utilization, please?

**Acceptance**
- [x] combine settings used in MPS-Config and kyma/production profile and make them as low as possible
- [x] validate using loadtester that with minimal setting eventing still comes up and is able to run a low workload (10eps)

**Comment by pbochynski** [comment]
Still valid.

**Comment by k15r** [comment]
production profile states:
```
controller:
  resources:
    limits:
      cpu: 1000m
      memory: 512Mi
    requests:
      cpu: 10m
      memory: 256Mi
  publisherProxy:
    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 10m
        memory: 256Mi

nats:
    resources:
      limits:
        cpu: 500m
        memory: 1Gi
      requests:
        cpu: 10m
        memory: 512Mi
    logging:
      debug: false
      trace: false
```

**Comment by mfaizanse** [comment]
@k15r There is a [PR](https://github.com/kyma-project/kyma/pull/17651/files), which is even increasing the request resources for eventing.

**Comment by marcobebway** [comment]
On SKRs, we reduced the Eventing **requested** resources as follows:

EC(1 replica):
- CPU: **40m**
- MEM: **64Mi**

EPP(sum of 2 replicas):
- CPU: **80m** (2 * 40m)
- MEM: **128Mi** (2 * 64Mi)

NATS(sum of 3 replicas):
- CPU: **120m** (3 * 40m)
- MEM: **192Mi** (3 * 64Mi)

Total:
- CPU: **240m** (6 * 40m)
- MEM: **384Mi** (6 * 64Mi)

**Comment by marcobebway** [comment]
OSS Production:

https://github.com/kyma-project/kyma/blob/35a75e206717e6f0733c34e7b061c4a86860973e/resources/eventing/profile-production.yaml#L8-L51

OSS Evaluation

https://github.com/kyma-project/kyma/blob/35a75e206717e6f0733c34e7b061c4a86860973e/resources/eventing/profile-evaluation.yaml#L8-L51
