### ISSUE TITLE
nodejs18 serverless runtime not available with kyma release 2.12.0

### ISSUE THREAD

**Issue by ptesny** [kyma-project/kyma#17173]
nodejs18 serverless runtime not available with kyma release 2.12.0 with either managed or OS kyma with busola.
nodejs18 can be only applied with kubectl or by editing the deployment yaml of function.

<img width="432" alt="image" src="https://user-images.githubusercontent.com/52403733/227782752-d14a257a-e0c8-40db-ab11-f6e8ebe7227f.png">
if trying to force nodejs18 manually that does not work either:

<img width="769" alt="image" src="https://user-images.githubusercontent.com/52403733/227782835-4e6f414c-2f79-4a18-b3af-a23092460790.png">

**Comment by kwiatekus** [comment]
Will be fixed after [this](https://github.com/kyma-project/kyma-dashboard/pull/126) is merged

**Comment by kwiatekus** [comment]
This was fixed in the UI configuration
