### ISSUE TITLE
Give overview on current Kyma structure and future modular approach

### ISSUE THREAD

**Issue by jacekon** [kyma-project/kyma#17210]
**Description**
Explain the current Kyma structure and the future modularized.
Simplify as discussed with @IwonaLanger @valentinvieriu 

**AC**
- [x] Provide the general description of the modular approach to Kyma

- [x] Provide a list of Kyma modules

- [x] Explain how to enable/disable a module

**Reasons**
To explain the transitory state we will have from the 1st of May.

**Assignees**

@kyma-project/technical-writers

**Attachments**

**Comment by jacekon** [comment]
as discussed let's merge the '[overview](https://kyma-project.io/docs/kyma/latest/01-overview/)' and '[main areas](https://kyma-project.io/docs/kyma/latest/01-overview/main-areas/)' pages.

**Comment by IwonaLanger** [comment]
Closing with [Add information on modular Kyma #17454](https://github.com/kyma-project/kyma/pull/17454)
