### ISSUE TITLE
[Telemetry] Support for multiple pipelines - performance and limitation evaluation

### ISSUE THREAD

**Issue by a-thaler** [kyma-project/kyma#17233]
**Description**
As part of https://github.com/kyma-project/kyma/issues/17223 we need to understand the impact of modelling the multiple pipelines features using multiple otel-collector pipelines. Also, new resource limits need to be determined

**Criterias**
- Understand the impact of using multiple pipeline definitions in a otel-collector config, using the same receivers but different outputs
  - what if one pipeline is blocked and the related buffer is full, will ingestion be rejected? Will the second pipeline starve?
  - is that behaviour meeting our expectations
  - If not, check the sources for a potential solution
- What is the resource consumption impact, it is just doubled (increasing linear to the amount of pipelines)? What is the ratio?
- What would be the impact of keeping current limitations but supporting 2 pipelines, how could that be achieved
  - Should we increase the resources for the one instance or maybe have more replicas?

**Reasons**

**Attachments**

**Comment by rakesh-garimella** [comment]
The result from the research has been added here: https://github.com/kyma-project/community/pull/778
