### ISSUE TITLE
Change component from kubeless-test-client to kubeless-integration

### ISSUE THREAD

**Issue by strekm** [kyma-project/kyma#1723]
Atm there's no Jenkins pipeline for tests/kubeless-test-client. Once Jenkins will detect changes in kyma/test/kubeless-test-client it will fail to find tests/kubeless-test-client job

**Comment by rakesh-garimella** [comment]
This is fixed by reverting the commit: https://github.wdf.sap.corp/SAP-CP-Extension-Factory/cont-integration/pull/308
