### ISSUE TITLE
serverless controller not reliable due to aging

### ISSUE THREAD

**Issue by ptesny** [kyma-project/kyma#17250]
Yesterday I decide to move all my in-cluster function based workloads to nodejs18; 
All these 10-12 functions are git repo based so eventually all the rebuilds were triggered by a single commit; 

As a result there were build job errors and the builds were super slow. Plenty of resources on the cluster.

After I restarted the serverless controller deployment the build job errors cleared and all functions were rebuilt super fast.

Thus it seems  to me the serverless controller has an aging problem; Anyway once restarted the function builds go way faster ; 

Are you planning to add like a periodic auto-restart feature to the serverless controller ? 

Typically these workloads are unmanned and should not require any manual intervention to run....

**Comment by kwiatekus** [comment]
@ptesny can you paste some of those build errors?
That would help us a lot

**Comment by ptesny** [comment]
@kwiatekus , I have not kept the error logs; the errors were thrown by the build jobs; and once I restarted the serverless controller's deployment all the builds resumed and completed... 
As I have explained, a single commit has triggered a rebuild of a dozen of functions...this means five jobs have been spawned...and the 5-6 others were queued... maybe this is sth you could try out on your side ?

**Comment by ptesny** [comment]
@kwiatekus , I get the `repo fetcher errors` quite often after committing a change to a github repo; I'm using **SSH** with github repo and the error is `while cloning repository: SSH could not read data. SSH error waiting on socket`; and a function job fails...after some time it is retried and depending on the serverless controller health, the job will succeed; 
As aforementioned a single gi repo commit triggers a dozen of function builds...typically there is one or two jobs failed with the above error and the others do well....(still base  on the serverless controller health)

**Comment by pPrecel** [comment]
@ptesny we can't reproduce this issue. The best way to prove your doubts would be to get us into your cluster if the situation occurs one more time. So please inform us before you would restart the controller's pod.

To double-check that we did everything right with the reproduction process can you share with us a little info about the cluster?

1. environment (k3d/gardener/...)?
2. how many resources did you gave to the cluster?
3. how old is this cluster?
4. did you hibernate it?
5. kyma version?
6. how often do you commit to the function's code-base? Or how often do you edit/create functions on this cluster?

**Comment by pPrecel** [comment]
I've tested the scenario on a gardener cluster with 12 git functions authenticated by the SSH key. I've pushed one change to the GitHub repo and checked if everything were ready. And all funcs were ready.
