### ISSUE TITLE
Failing `nightly-main-reconciler-e2e` on reconciling `eventing`

### ISSUE THREAD

**Issue by khlifi411** [kyma-project/kyma#17292]
**Description**
The pipeline [nightly-main-reconciler-e2e](https://status.build.kyma-project.io/job-history/gs/kyma-prow-logs/logs/nightly-main-reconciler-e2e) is failing consistently on eventing reconciler.

**Expected result**
Eventing component reconciliation should succeed.

**Actual result**
Eventing component reconciliation is timing out.
```log
{"level":"DEBUG","time":"2023-04-12T11:17:31.083Z","message":"Bookkeeper evaluated reconciliation (schedulingID:6f8ec1bc-f300-4f00-bb65-6fec5dcd0ba5--fe9212c8-fa21-42b1-8e93-32f615558728) for cluster '6f8ec1bc-f300-4f00-bb65-6fec5dcd0ba5' to cluster status 'error': Done=istio[2],cluster-users[3],tracing[3],istio-resources[3],CRDs[1],cluster-essentials[2],ory[3],logging[3],certificates[2],monitoring[3],telemetry[3],serverless[3],application-connector[3],api-gateway[3] / Error=eventing[3][error: context deadline exceeded] / New= / Running="}
{"level":"DEBUG","time":"2023-04-12T11:17:31.083Z","message":"BookkeeperTask markOrphanOperation: found operations which are orphan: []"}
{"level":"DEBUG","time":"2023-04-12T11:17:31.086Z","message":"BookkeeperTask finishOperation: reconciliation for cluster with runtimeID '6f8ec1bc-f300-4f00-bb65-6fec5dcd0ba5' and clusterConfig '1' failed but reconciliation will be retried (count of applied retries: 24)"}
{"level":"DEBUG","time":"2023-04-12T11:17:31.087Z","message":"Worker pool is checking for processable operations (max parallel ops per cluster: 25)"}
{"level":"DEBUG","time":"2023-04-12T11:17:31.093Z","message":"Finishing reconciliation for cluster '6f8ec1bc-f300-4f00-bb65-6fec5dcd0ba5' succeeded (schedulingID:6f8ec1bc-f300-4f00-bb65-6fec5dcd0ba5--fe9212c8-fa21-42b1-8e93-32f615558728/clusterVersion:1/configVersion:1): new cluster status is 'reconcile_error_retryable'"}
{"level":"DEBUG","time":"2023-04-12T11:17:31.095Z","message":"BookkeeperTask finishOperation: updated cluster '6f8ec1bc-f300-4f00-bb65-6fec5dcd0ba5' to status 'reconcile_error_retryable' (schedulingID:6f8ec1bc-f300-4f00-bb65-6fec5dcd0ba5--fe9212c8-fa21-42b1-8e93-32f615558728)"}
```

**Failing Run link**:
https://status.build.kyma-project.io/view/gs/kyma-prow-logs/logs/nightly-main-reconciler-e2e/1646105885509947392

**Comment by ruanxin** [comment]
appear again in recent logs
https://status.build.kyma-project.io/view/gs/kyma-prow-logs/logs/nightly-main-reconciler-e2e/1661296075731898368
https://status.build.kyma-project.io/view/gs/kyma-prow-logs/logs/nightly-main-reconciler-e2e/1661265876411748352

**Comment by Tomasz-Smelcerz-SAP** [comment]
The same problem in `nightly-main-reconciler-e2e` again:
- https://status.build.kyma-project.io/view/gs/kyma-prow-logs/logs/nightly-main-reconciler-e2e/1663651503048495104
- https://status.build.kyma-project.io/view/gs/kyma-prow-logs/logs/nightly-main-reconciler-e2e/1663621303682207744
- https://status.build.kyma-project.io/view/gs/kyma-prow-logs/logs/nightly-main-reconciler-e2e/1663591104307531776
- https://status.build.kyma-project.io/view/gs/kyma-prow-logs/logs/nightly-main-reconciler-e2e/1663681702267981824

**Comment by grischperl** [comment]
I'll keep an eye on this to check if the image bump helped stabilize the test.
