### ISSUE TITLE
Move Kyma examples to separate document type 

### ISSUE THREAD

**Issue by pkosiec** [kyma-project/kyma#1730]
**Description**

Move `Examples` topic to separate document type.

**Reasons**
Separate document type will increase visibility of the content.

**Attachments**
![screen shot 2018-11-20 at 13 50 47](https://user-images.githubusercontent.com/7155799/48774778-6f064c00-eccb-11e8-8af0-0fd12ea080d5.png)

**Comment by kazydek** [comment]
Document was moved and the doc image was updated.
