### ISSUE TITLE
[Telemetry] mTLS support for trace and metric gateway ingestion

### ISSUE THREAD

**Issue by a-thaler** [kyma-project/kyma#17315]
**Description**
The trace and metric gateway being provided by the telemetry module is not leveraging istio and with that does not support TLS nor mTLS for pushing traces/metrics.
The problem of that situation is that the traffic is not encrypted and the data could be tampered (not a high impact probably, however in combination with other attacks it might become serious), so at least TLS should be provided.

Managing certificates should be avoided as it brings complexity, so instead the gateway should leverage Istio if available, so that all istio-fied workloads could easily push traces using mTLS.

**Criterias**
- users do not need to place any resources for being able to push traces to the gateway leveraging mTLS for istio-fied workload
- telemetry module still works having no istio available, disabling an existing istio should be handled graceful
- spans for the communication to the gateways itself are not recorded for client and server side envoys by filtering them out by the trace gateway
- The communication from the metrics-agent to the metrics-gateway is using mTLS if istio is enabled
- It will be possible to dispatch data to in-cluster backends leveraging mTLS
- Extend the istio trace test to run a workload and backend with and without sidecar

**Implementation details**
- The telemetry-manager already detects if istio is available or not. All activities need to be based on that condition
- For the trace and metric gateway a peerAuthentication resource should be generated if the related gateway is active. The peerAuthentication sets the TLS mode to permissive. To keep the dependency to the istio libraries minimal, the [istio api package](https://github.com/istio/api) gets used without the related [client-go package](https://github.com/istio/client-go)
- For the trace and metric gateway a istio sidecar injection label gets generated on the pod template being active for incoming and outgoing traffic, metrics port might be excluded for system metrics scraping
- The metrics-agent already has a sidecar active having excluded all outgoing traffic. These needs to be adjusted by activating outgoing traffic on the OTLP ports, so that data gets send to the gateway leveraging mTLS

**Comment by a-thaler** [comment]
The issue is still on our radar. As part of https://github.com/kyma-project/kyma/issues/13079 we will need to deal with the istio dependency problem of the module and most probably the result can be re-used for tracing as well.

**Comment by a-thaler** [comment]
Summarized having the collector istiofied will result into following challenges:
- non-istiofied workloads need to be supported -> requires permissive peerauthentication
- istio envoy span reporting does not work on istiofied target ports -> exclude istio reporting from interception
- the source IP gets lost, with that no resource attribute processing is possible anymore -> using [TPROXY](https://istio.io/latest/docs/reference/config/istio.mesh.v1alpha1/#ProxyConfig-InboundInterceptionMode) mode of envoy fixes the problem

Actions left to do:
- as we will need to keep the dedicated ports for istio reporting which are not getting intercepted, already add new OTLP receivers for non-istiofied traffic and expose them via the internal service as standard OTLP ports, enrich the internal service with OTLP endpoints (aditional to the opencensus ports) as we want to switch to OTLP as soon as possible
- clarify with the istio team potential problems with the TPROXY mode, then configure it
- add tests for the resource attribute enrichment

**Comment by rakesh-garimella** [comment]
- The metric gateway and the trace collector has been moved into istio service mesh
- The required ports have been excluded additionally inbound interception mode with TPROXY enabled
- The e2e tests have been implemented
- Improved tests to test k8s attributes.
