### ISSUE TITLE
Automate CRD documentation

### ISSUE THREAD

**Issue by mmitoraj** [kyma-project/kyma#17347]
**Description**

Kyma documentation in the **Technical Reference** section focuses on [Kyma Custom Resources](https://kyma-project.io/docs/kyma/latest/05-technical-reference/00-custom-resources/). The documents include tables listing all the possible parameters of a given resource together with their descriptions. As the parameters and CRDs change, the documentation may easily become out-of-date and difficult to maintain. Huskies came up with the idea to auto-generate the content of the tables. For example, see the auto-generated table for the [Telemetry - LogPipeline CR parameters](https://kyma-project.io/docs/kyma/latest/05-technical-reference/00-custom-resources/telemetry-01-logpipeline/#custom-resource-parameters) CR. The solution could be improved, adjusted, and implemented for all CRs descriptions. 

Steps:

1. [x] Ask @a-thaler to explain the mechanism so that other teams could confirm if the solution fits their use cases and requirements
2. [x] Discuss with @kyma-project/technical-writers if the solution meets Kyma documentation requirements
3. [x] Contact POs to consult if auto-generating the tables' content with their teams' CRDs description is possible
4. [x] Improve and adjust the mechanism if needed
5. [ ] Automate the docu creation

**Area**

Area | Custom resource
-- | --
Application Connectivity | Application,  CompassConnection
API Gateway | APIRule
Eventing | Subscription, EventingBackend
Istio | Istio
Serverless | Function, GitRepository
Telemetry | LogPipeline, LogParser, TracePipeline

**Reasons**

Up-to-date documentation.

**Assignees**

@mmitoraj 
@a-thaler 

**Related issues**
#17421 #17380

**Comment by a-thaler** [comment]
- every domain need to provide good and complete descriptions on the CRD attributes
- prepare your MD files by removing the relevant tables and replacing them with the placeholders as described [here](https://github.com/kyma-project/kyma/tree/main/hack/table-gen)
- add new mappings for your CRDs to that [Makefile](https://github.com/kyma-project/kyma/blob/main/hack/table-gen/Makefile), defining to map which CRD to which file
- when providing a new CRD version to the kyma folder, execute first the "make generate" command
- a prow job will remind you if you forgot the previous step as it will execute the same make target and check the git status afterwards

**Comment by mmitoraj** [comment]
Dear All,

To drive the topic forward, we would need your and your teams' engagement at that point. I created a table listing Kyma CRDs. **Please:**
- check if documentation for your CRDs can be automated as in the example provided in the issue description
- add your ideas on top so that the process works for your use case
- estimate your team's effort for the task and create an issue for it

_Hints:_ 
The parameters description is mostly there in the documentation; however, it needs to be reviewed and moved to the specification files. 
**CAUTION:** The CRDs may require updating.  

Please ask any questions you may have.

Kyma CRDs per teams:

CRD | Team | Contact Person |
---|-------|---|
apirules.gateway.kyma-project.io |  Goats | @strekm 
istios.operator.kyma-project.io | Goats | @strekm 
applications.applicationconnector.kyma-project.io | Framefrogs | @Disper 
compassconnections.compass.kyma-project.io | Framefrogs | @Disper 
functions.serverless.kyma-project.io | Otters | @kwiatekus 
gitrepositories.serverless.kyma-project.io | Otters | @kwiatekus 
eventingbackends.eventing.kyma-project.io | Skydiving Tunas | @k15r 
subscriptions.eventing.kyma-project.io | Skydiving Tunas | @k15r 
tracepipelines.telemetry.kyma-project.io | Huskies | @a-thaler 
logparsers.telemetry.kyma-project.io | Huskies | @a-thaler 
logpipelines.telemetry.kyma-project.io | Huskies | @a-thaler

**Comment by a-thaler** [comment]
I'm all in, let me know when we should do what

**Comment by k15r** [comment]
Great idea, we're in

**Comment by mmitoraj** [comment]
**AIs** from today's synch:
- Create a ticket for each team to provide/update their CRDs attributes description [@strekm, @k15r  @kwiatekus @VOID404, @a-thaler]
- Prepare the .md files by removing existing tables and adding placeholders once the descriptions are ready and the makefile is updated [@mmitoraj]
- Consider improvements, such as adding the **Mandatory** column and the possibility to hide certain fields
-  Schedule a meeting in 2 weeks' time [@mmitoraj]

**Comment by strekm** [comment]
@a-thaler @k15r so far CRD is fetched from kyma repo. i'm assuming that for modularisation it will be possible to fetch it from different repo, right?

**Comment by a-thaler** [comment]
There will be no central website repo where the content gets copied to, instead the idea is that the website gets rendered directly with the content from the different repos. So you would need to render/generate the md files in your repo. So you would need a custom automation in your repo. Not sure yet how we want to share the tooling for that, maybe we can place it centrally in the kyma repo and you load it as part of your module automisation from remote?

**Comment by k15r** [comment]
With essentially all code moving out of the kyma repository it might make sense to have a dedicated repository for the crd-documentation tooling. As the generation itself is a single line command which could be easily forged into a reusable tekton pipeline step or also a github action

**Comment by mmitoraj** [comment]
@VOID404 It seems like the documentation Application CR is the last one to automate. Could you let me know what is needed to complete the task? Do you need any assistance with that one? Thank you in advance.

**Comment by Disper** [comment]
Hi @mmitoraj,
we don't need assistance and @kyma-project/framefrog part is already pretty advanced, however we have two high risk topics on the managed part on our plates right now and we have to fully focus on them.
Right now I believe that we should be able to jump back to this topic somewhere in June.

**Comment by mmitoraj** [comment]
@Disper Hi Michał, can we expect the task to be taken up soon?

**Comment by Disper** [comment]
Hi @mmitoraj,
I'll make sure that we will pick it up next 2-week sprint that starts on Thursday.

**Comment by Disper** [comment]
@mmitoraj,
we've discussed the topic today and while there is a chance that will be finishing that in the upcoming sprint, we can't guarantee it due to some internal incidents and one external one that appeared and we have to focus on. 

As team @kyma-project/framefrog is the only one lagging behind, should we maybe take over the assignment of this task and close it when it will be done?

**Comment by mmitoraj** [comment]
@Disper, yes, team Framefrog is the only one left. That is a good idea for you to take over the assignment. Let me know if you need any help. Thank you/
