### ISSUE TITLE
Enable `atleastOnceDuringUpgrade` in Eventing fast-integration tests

### ISSUE THREAD

**Issue by mfaizanse** [kyma-project/kyma#17368]
**Pre-requisites:**
- [x] https://github.com/kyma-project/kyma/issues/17367

**Description:**

The `atleastOnceDuringUpgrade` tests were disabled because of flakiness as part of this issue. Once we get rid of serverless, enabled the `atleastOnceDuringUpgrade`.

**Comment by k15r** [comment]
fi-tests do not exist anymore
