### ISSUE TITLE
Remove fast integration / perf jobs from kyma

### ISSUE THREAD

**Issue by mfaizanse** [kyma-project/kyma#17367]
## Description

with all components changed into modules the fast integration jobs are not necessary anymore. Remove the fast integration jobs and all their use on test-infra

## Acceptance
- [x] get approval from remaining teams first 
- [x] `fast integration` is not used anymore on prow 
- [x] `perf` is not used anymore on prow
- [x] its code is gone

**Comment by k15r** [comment]
https://github.com/kyma-project/kyma/pull/18443
