### ISSUE TITLE
[Telemetry] new scalability profile for multiple trace/metric pipelines

### ISSUE THREAD

**Issue by a-thaler** [kyma-project/kyma#17377]
**Description**
As part of https://github.com/kyma-project/kyma/issues/17223 investigations were done to understand how multiple pipelines would interfere each other. The results are documented [here](https://github.com/kyma-project/community/pull/778)
Now a new setup should be proposed which will outline a new base setup and how an additional pipeline will change the resource setup.

Following assumptions are defined:
- horizontal scaling is desired for the future and should be respected in the new profile. As automatic scaling requires the chance to limit/disable the auto-scaling to save-guard resources, and as there is no user-facing configuration option yet, there will be no autoscaling provided.
- the base setup should be based on 2 instances with node anti-affinities to cover HA requirements
- the base setup should cover current limitations for 1 pipeline, not more, especially the memory limitier should not kick-in by design in a unhealthy pipeline situation
- Every further pipeline will cause a reconfiguration of the instance resources, so that at least one pipeline can be in an unhealthy state without interfering the other pipelines
- the max amount of pipelines is limited to 3

**Criterias**
- the new base setup is implemented including dynamic adjustment of the resource limits
- the HA setup is in place
- the resource adjustment for any further pipeline is documented
- the new settings are verified

**Reasons**

**Attachments**

**Comment by chrkl** [comment]
PR https://github.com/kyma-project/telemetry-manager/pull/227 introduces the following changes for the Otel collector settings:
- Resource settings consist of a fixed part and a part that is scaled per pipeline. The settings were chosen in a way that no samples are dropped by the memory limiter and a throughput of 1500 samples/s is reached.
- In the case of multiple pipelines, the output queue capacity is divided by the pipeline count. This is necessary to not hit the memory limiter. The base value was reduced to ensure this also in the case of a pipeline backend outage.
- The replica count for the otel collectors was increased to 2 to improve availability. PodAntiAffinities were added to prefer scheduling the replicas to different availability zones, or at least different nodes.
- Session affinity was enabled for the OTLP services to support stateful processors in future.

PR https://github.com/kyma-project/kyma/pull/17724 removed the pipeline restriction from the Helm chart and adjusted integration tests to respect this change.
