### ISSUE TITLE
update monitoring components to latest golang versions

### ISSUE THREAD

**Issue by a-thaler** [kyma-project/kyma#17378]
**Description**

The monitoring components are using outdated golang versions and need to be updated. For the prometheus domain newer releases are available and an update will help here. For the other components, no recent updates are published and most probably a re-build should happen.

**Tasks**
- Introduce custom build for:
  - node-exporter
  - jimmidyson-configmap-reloader
  - alertmanager
- Update versions of:
  - prometheus
  - prometheus-operator + CRD
  - prometheus-operator-config-reloader
 
**Criterias**
- a new golang version is used for all the images used in the monitoring component

**Comment by rakesh-garimella** [comment]
Prometheus images have been bumper [here](https://github.com/kyma-project/kyma/pull/17439). After the bump security vulnerabilities are still being reported for the Prometheus image. As per [discussion](https://github.com/prometheus/prometheus/issues/12276#issuecomment-1520453608) next version of the Prometheus should fix it and they would release it soon. If the release does not happen we might need to build our own image.

**Comment by rakesh-garimella** [comment]
The images of alertmanager and jimmydyson are built by us. They have been built with latest golang version. The Pomethus images have been updated.
