### ISSUE TITLE
Document the Telemetry Module

### ISSUE THREAD

**Issue by NHingerl** [kyma-project/kyma#17468]
Let's apply the [module doc template](https://github.com/kyma-project/kyma/issues/16421) to Telemetry.

**Description**
For the new modularization approach, we need documentation that is common for all the modules, e.g. general description (landing page), getting started, module configuration, etc. 

**AC**
- [x] Your audience is the end-user so the documentation must be written for them (not for the team that builds this module, or other SAP teams that wish to build a module, not for SRE, etc)
- [x] The documentation must be consumable by the kyma-project.io home page (split into several information types/md files)
- [x] Create a docs folder following the standard structure proposed in -> [Propose a standard structure for each module docs folder](https://github.com/kyma-project/kyma/issues/16775)
- [x] In each module's documentation include:
  - [x]  General description of the functionality (if the module is mandatory, mention it!)
  - [ ]  Getting Started - instructions on how to use the module. The module docs must mention the prerequisite that the module must be enabled. They must also include instructions on how to install/enable a module.
  - [x] Module configuration
  - [x] Instructional documents (currently called "dev tutorials" and "operational guides") - must be isolated, i.e. no dependencies on other tutorials or modules. An example.
  - [x] If needed, troubleshooting
  - [ ] Instructions on how to give feedback

**Reasons**

Our docs should be consistent, and consumable by the website

**Assignees**

@NHingerl 

**Attachments**

**Comment by a-thaler** [comment]
Docu was added

**Comment by a-thaler** [comment]
Can you be more concrete on what you are missing with some concrete action items so that we can come up with a more specific task list?

**Comment by a-thaler** [comment]
We don't describe how to enable the module yet, is that needed? Isn't there some umbrella docu explaining that? Guides will be added afterwards step-by-step and not handled in this ticket.
instructions on giving feedback I wouldn't know to answer, can you help here?

**Comment by NHingerl** [comment]
- Initially we planned to create an umbrella doc both for OS and SKR, but PB says this doesn't make sense for OS: https://github.com/kyma-project/community/issues/792#issuecomment-1576846974

- For tutorials, don't we already have some instructions? I'd consider any instructions "tutorials". But regardless, adding them later is fine with me.

- For feedback, I think a general pointer what users should do (create a GH issue? ping us in Slack/Teams) is fine. If Kyma doesn't plan that customers to get in touch with specific dev teams, we should just provide an umbrella doc for Feedback.

**Comment by a-thaler** [comment]
I vote for an umbrella feedback doc. If you read it within the repo scope you anyway know how to provide feedback (Issues/PRs)
New guides are already in creation, existing ones we will be migrated later
