### ISSUE TITLE
Document the Eventing + NATS module

### ISSUE THREAD

**Issue by NHingerl** [kyma-project/kyma#17474]
Let's apply the [module doc template](https://github.com/kyma-project/kyma/issues/16421) to Eventing and NATS manager.

**Description**
For the new modularization approach, we need documentation that is common for all the modules, e.g. general description (landing page), getting started, module configuration, etc. 

👁️ **SEE https://github.com/kyma-project/nats-manager/issues/79 and https://github.com/kyma-project/eventing-manager/issues/184** 👁️

**Reasons**

Our docs should be consistent, and consumable by the website

**Assignees**

@NHingerl 

**Attachments**

**Comment by NHingerl** [comment]
https://github.com/kyma-project/nats-manager/pull/93

**Comment by NHingerl** [comment]
For the Eventing module, we've got the following action items:

- [ ] Update the docs in the module repository (https://github.com/kyma-project/eventing-manager/pull/198)
- [ ] Update the `index.html` file (https://github.com/kyma-project/kyma/pull/18375)
- [ ] Remove the component docs from `kyma` repo
- [ ] Add the module doc to the `_sidebar.md` file in the `kyma` repo
- [ ] Publish the OS release note
- [ ] Unhide and publish the SKR release note ([rough draft](https://help.sap.com/whats-new/f0d108472a9347d99053658d05ae23e2?Component=Kyma%20Runtime&Valid_as_Of=2023-11-10%3A2023-11-10&locale=en-US&state=DRAFT) is prepared, needs review. Once it's good to publish, remove internal flag and request publication)

**Comment by k15r** [comment]
followup task https://github.com/kyma-project/kyma/issues/18427 was created, everything else is already done
