### ISSUE TITLE
[Telemetry] Missing nodeSelector field in deployment

### ISSUE THREAD

**Issue by ankhax** [kyma-project/kyma#17615]
**Description**

In resources/telemetry/charts/operator/templates/deployment.yaml is missing nodeSelector field, so applied nodeSelector doesn't work.

Kubernetes version doesn't matter. Issue is relevant from Kyma 2.10 version.

**Expected result**

nodeSelector is applied without issue.

**Actual result**

nodeSelector is not applied.

**Steps to reproduce**

Apply nodeSelector via CR.

**Troubleshooting**

Insert 

```yaml
nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }
```

in line 92 in resources/telemetry/charts/operator/templates/deployment.yaml

**Comment by a-thaler** [comment]
As mentioned, the helm chart has no future as we will remove it very soon. Please switch to a kustomize based installation of the module, see also https://github.com/kyma-project/telemetry-manager/blob/main/docs/contributor/installation.md
Will close the issue, feel free to re-open if you think something is missing
