### ISSUE TITLE
[Telemetry] Unrecoverable logs kept in buffer for ever

### ISSUE THREAD

**Issue by a-thaler** [kyma-project/kyma#17662]
**Description**

The log agent (fluenbit) of the telemetry logging feature is using a buffer at the output based on the node file system. It is configured to retry unlimited times (using an exponential backoff).
The supported "http" output is treating all requests as successfull if there is a 2xx response. Otherwise it will be treated as failed, no further differentiation is implemented/configurable. With that, also unrecoverable responses will be re-tried, for example a 400 having a bad syntax or a 4xx having a too big message. These logs will potentially stay forever in the buffer (till the buffer gets wiped out by moving to a different node) and the buffer grow to it's limit until the logs get discarded.

As in general the setup works fine as all healthy logs will be processed and retried even, but logs will potentially stay for a very long time in the buffer without being recognized at all. To enable the user to recognize an actual problem, the best would be to give up after some time, so that the actual "drop" counter for the exporter gets increased and can raise an alert.

**Idea**
Switch the unlimited retry setting to a moderate value like 3 days and have it documented as limitation. In future, have the value configurable via the module spec.

**Effect**
All stays as before, but a log message will be treated as unsuccessful after a certain amount of time and causes a "drop" metric when being removed from the buffer. Users can track the buffer size to detect problems, but also can track the "drop" counters to identify rare problems which are not filling up a buffer fully.

**Comment by chrkl** [comment]
The Fluent Bit retry limit was set to 300. This should drop logs after retrying for approximately 3.5 days.
