### ISSUE TITLE
Adjust lambda implementation to consume changes in the subscription CRD

### ISSUE THREAD

**Issue by abbi-gaurav** [kyma-project/kyma#1769]
### Description
The susbcription CRD domain will be changed from 
`subscriptions.eventing.kyma.cx` ---> `subscriptions.eventing.kyma-project.io`

The lambda code needs to consume that.
See Issue #407 
PR #1624 and #1642

### AC:
- [ ] The lambda APIs are using the changed subscription CRD

**Comment by rakesh-garimella** [comment]
One can fetch the changes to UI from: `https://github.com/rakesh-garimella/console.gi`t and branch:` fix-eventing-domain`. @montaro  Please try it out once you have fixed the issues.
