### ISSUE TITLE
All reviews of documentations for modularization  

### ISSUE THREAD

**Issue by jacekon** [kyma-project/kyma#17708]
**Here's the list of outstanding review tasks across all Kyma documentation**
 - [x] Keda module - [Keda module OS documentation](https://kyma-docs.netlify.app//?basePath=https://raw.githubusercontent.com/kyma-project/keda-manager/main/&homepage=docs/user/README.md&sidebar=true&loadSidebar=docs/user/_sidebar.md&browser-tab-title=Keda%20module%20Documentation#/docs/user/README)
 - [x] BTP Operator - [BTP Operator module OS documentation](https://kyma-docs.netlify.app//?basePath=https://raw.githubusercontent.com/kyma-project/btp-manager/main/docs/user/&homepage=README.md&sidebar=true&loadSidebar=_sidebar.md&browser-tab-title=BTP%20Operator%20Documentation#/)
 - [x] Istio - [Istio module documentation PR](https://github.com/kyma-project/istio/pull/170)
 - [x] Serverless [Serverless module documentation](https://kyma-project.io/#/serverless-manager/user/README)
 - [x] Telemetry https://github.com/kyma-project/telemetry-manager/issues/271
 - [x] Eventing
 - [x] NATS
 - [x] Application Connector
 - [x] API Gateway

**Comment by mmitoraj** [comment]
Closing as the last module was already released.
