### ISSUE TITLE
Allow trusted domain settings for kyma dashboard. Possibility to embed busola in an iframe.

### ISSUE THREAD

**Issue by ptesny** [kyma-project/kyma#17735]
When trying to use kyma dashboard from an iframe we typically get the following error message:

```
Refused to display 'https://dashboard.kyma.cloud.sap/' in a frame because it set 'X-Frame-Options' to 'deny'.
```
<img width="499" alt="image" src="https://github.com/kyma-project/kyma/assets/52403733/a292fc83-2d31-4caa-972c-f37f90179e48">

Possible solutions:
a. instead of setting `X-Frame-Options: deny` busola would rather set the header to sameorigin: `X-Frame-Options: sameorigin`
b. open the busola backed to allow for trusted origins (domain) the same way BTP cockpit does it on a sub-account level

<img width="1255" alt="image" src="https://github.com/kyma-project/kyma/assets/52403733/37951132-8407-4797-a7e2-ef552bb50cb6">

PS.
https://www.keycdn.com/blog/x-frame-options

**Comment by valentinvieriu** [comment]
This is a security topic. We will not enable this in our app.
You are free to run your own version of Busola, and then decide what domains to allow
