### ISSUE TITLE
Fix Eventing controller logic to detect secret changes

### ISSUE THREAD

**Issue by marcobebway** [kyma-project/kyma#17749]
**Description**

As per this [logic](https://github.com/kyma-project/kyma/blob/a6d77e18431c42fa1ecb397256b3fabd3f896828/components/eventing-controller/controllers/backend/reconciler.go#L328-L330), the Eventing controller reports that the secret is changed during the controller startup which is not always true. As a side effect of that, the Eventing controller invokes the active backend to [stop](https://github.com/kyma-project/kyma/blob/a6d77e18431c42fa1ecb397256b3fabd3f896828/components/eventing-controller/controllers/backend/reconciler.go#L336) and do cleanup which is not desired.

**Steps to reproduce**

1. Switch the Eventing backend to EventMesh.
2. Create a Kyma subscription.
3. Check the creation time of the EvenMesh webhook.
4. Restart the Eventing controller.
5. Check the creation time of the EvenMesh webhook (notice it is changed).

**Acceptance criteria**

- [x] The bug is fixed.

**Comment by mfaizanse** [comment]
**Before:**
![image](https://github.com/kyma-project/kyma/assets/9897945/a3f0f616-fae9-4027-9ac3-9b8a6c23cdb8)
