### ISSUE TITLE
Links update after removal of the `main-areas` navigation node

### ISSUE THREAD

**Issue by mmitoraj** [kyma-project/kyma#17805]
**Description**

After the removal of the `main-areas` navigation node on kyma-project.io, the links to the `kyma-project.io` website could be broken. 

AC:
- [ ] Talk to the Neighbors about the `governance` jobs (if they work as expected and should detect the broken links)
- [x] Check links in the OS kyma-project repositories (for example using the search feature in the VSC)
- [x]  Fix broken links

**Area**

**Reasons**

Broken links in the documentation.

**Assignees**

@kyma-project/technical-writers

**Attachments**

**Comment by nataliasitko** [comment]
All broken links in `kyma-project` have been fixed.
The `governance` jobs detected all broken links caused by `main-areas` removal. The `The specified anchor doesn't exist` errors that they also started to display are not related to this issue but to a bug found in MILV.

**Comment by nataliasitko** [comment]
All broken links in `kyma-project` have been fixed.
The `governance` jobs detected all broken links caused by `main-areas` removal. The `The specified anchor doesn't exist` errors that they also started displaying are not related to this issue but to a bug found in MILV.
