### ISSUE TITLE
Update Tracing documentation

### ISSUE THREAD

**Issue by abbi-gaurav** [kyma-project/kyma#1780]
* Move the [README.md](https://github.com/kyma-project/kyma/tree/master/resources/jaeger) content to 
[tracing docs](https://github.com/kyma-project/kyma/blob/master/docs/tracing/docs)

* Keep minimal content in the [README.md](https://github.com/kyma-project/kyma/tree/master/resources/jaeger)
  * see [example](https://github.com/kyma-project/kyma/tree/master/resources/application-connector) 

Once the documentation is updated, update the [example-tracing](https://github.com/kyma-project/examples/tree/master/example-tracing)

**Comment by bszwarc** [comment]
I would additionally improve the following aspects of tracing docs:

- remove a part of Jaeger-related information from the Overview doc and put it in the new Jaeger details doc
- improve the wording in http-headers documentation (and moved it down in the hierarchy, after jaeger doc)
- rename the trace-comparison doc to details-trace-comparison and change one of the headings there from H1 to H2 as we use H1 for titles only.

**Comment by bszwarc** [comment]
I also added a separate document about distributed tracing.
