### ISSUE TITLE
Tests are failing due to monitoring deployment failure

### ISSUE THREAD

**Issue by nesmabadr** [kyma-project/kyma#17826]
**Description**

This [upgrade](https://status.build.kyma-project.io/view/gs/kyma-prow-logs/logs/kyma-upgrade-gardener-kyma2-to-main-reconciler-main/1679762829684510720) test is failing due to `monitoring` deployment failure

**Expected result**

Test should pass

**Actual result**

> Deployed Components: 11/12
> Could not deploy the following components:
> - monitoring
> 
> cannot patch "monitoring-prometheus-node-exporter" with kind Service: Service "monitoring-prometheus-node-exporter" is invalid: spec.ports[1].name: Duplicate value: "http-metrics"

**Comment by a-thaler** [comment]
Probably related to https://github.com/kyma-project/kyma/pull/17821

**Comment by rakesh-garimella** [comment]
The upgrade of kyma should work again
