### ISSUE TITLE
Cleanup SKR related source code in Eventing fast-integration tests

### ISSUE THREAD

**Issue by mfaizanse** [kyma-project/kyma#17879]
As a result of this [PR](https://github.com/kyma-project/kyma/pull/17831), eventing is now codeowners of SKR related codebase.

But, as we are not using the SKR related code in Eventing fast-integration tests, we can remove the code related to SKR provisioning/de-provisioning, commerceMock stuff etc.

**Comment by grischperl** [comment]
This issue can be closed as fast-integration tests are no longer in use.
