### ISSUE TITLE
Allow securing specific resources in GraphQL

### ISSUE THREAD

**Issue by kubadz** [kyma-project/kyma#1789]
After removing the old not working envoy filter in PR #1594 we need to add back the functionality it provided. That will allow the user to secure specific resources in GraphQL.

TODO:
* Add envoy filter rewriting resources from query to the custom header
* Update the readme in ui-api chart

**Comment by sjanota** [comment]
## Review notes:
### Follow ups:
* Check if works for groups. Document if it is not.

@kubadz @piotrmsc @pbochynski

**Comment by kubadz** [comment]
** Follow up:**
The solution doesn't work for groups because Istio in version 1.0.x doesn't support `groups` claim as the list of strings, but only support single string values. In our case the groups claim is always a list of strings.
Istio already handled that problem and proper PRs ([istio/proxy#1896](https://github.com/istio/proxy/pull/1896) [istio/istio#7747](https://github.com/istio/istio/pull/7747) [istio/proxy#1925](https://github.com/istio/proxy/pull/1925)) are already merged to master but are not merged into the release-1.0 branch, so there probably won't be any 1.0.x version with support of group claims. However, these PRs are already merged into the release-1.1 branch so it is almost sure that there will be such support in Istio 1.1.
