### ISSUE TITLE
Monitoring of monitoring chart

### ISSUE THREAD

**Issue by lilitgh** [kyma-project/kyma#1794]
**Description**
13 components in monitoring chart 

- Check the dashboard https://grafana.com/dashboards/3662
- Check alerts we already have in  monitoring folder  e.g. `monitoring/charts/prometheus/*.rules*` 
   - Do not revisite all alerts, they should be fine...
   - Remove alerts which are red for no reason
   - Check if something is missing
- Grafana dashboard

AC:
Metrics are visible in Grafana and we have alerts in place

**Comment by a-thaler** [comment]
Fixed by https://github.com/kyma-project/kyma/issues/6124

Metrics are exposed, alerts in place, dashboard available
