### ISSUE TITLE
FI tests sending cloudevents in structured mode to EventMesh fails

### ISSUE THREAD

**Issue by k15r** [kyma-project/kyma#17940]
The tests were skipped as part of https://github.com/kyma-project/kyma/issues/17930.
At the moment tests which send events in structured mode to the eventmesh backup fail. 

**Acceptance**
- [x] fix the test
- [x] reenable the test

**Comment by friedrichwilken** [comment]
- [ ] question: does this happen on local/gardener clusters too?

**Comment by marcobebway** [comment]
> * [ ]  question: does this happen on local/gardener clusters too?

Yes

**Comment by friedrichwilken** [comment]
fi tests on k3d:

```
  1) Eventing tests
       with BEB backend
         Cloud Events [binary] with v1alpha1 subscription should be delivered to eventing-sink :
     Error: Fetching published event responded with error: AssertionError: expected false to equal true
```

**Comment by friedrichwilken** [comment]
SKR cluster
```
1) Eventing tests
       with BEB backend
         Cloud Events [structured] with v1alpha1 subscription should be delivered to eventing-sink :
     Error: undefined: Request failed with status code 500
```

**Comment by friedrichwilken** [comment]
I forgot to export an `EventMesh` secret and the error did non appear, so it looks to be connected to `EventMesh`. I repeated the test two times and all three times the test passed without an error. I finally exported the `EventMesh` secret and three times in a row the test failed.
