### ISSUE TITLE
Monitoring of logging component

### ISSUE THREAD

**Issue by lilitgh** [kyma-project/kyma#1795]
**Description**
Monitoring should be available for logging components.

Follow RED (https://www.weave.works/blog/the-red-method-key-metrics-for-microservices-architecture/)
- Monitor Loki
- Monitor PVC
- Grafana dashboard is configured

AC:
- The recommended metrics of Loki and Promtail are exported to Prometheus, see https://github.com/grafana/loki/blob/master/docs/operations.md#observability
- The recommended alert rules are configured, see https://github.com/grafana/loki/blob/master/docs/operations.md#observability
- A Grafana dashboard is available for monitoring the logging components

**Comment by clebs** [comment]
Added custom metrics for Loki and a new Grafana dashboard:
#4206 

Custom metrics for promtail will be done in a separate issue as it presents additional challenges:
#4214

**Comment by a-thaler** [comment]
Still the dashboard needs to be improved so that the two metrics are shown in a more meaningful way.
Please add alert rules if appropriate.
