### ISSUE TITLE
Kyma install fails.  panic: failed to connect to NATS JetStream

### ISSUE THREAD

**Issue by venkas01** [kyma-project/kyma#17974]
I am trying to install Kyma , not sure if i am using the correct versions etc .. 
Can you please help.

**************************************************
**OS:**
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.3 LTS
Release:        22.04
Codename:       jammy

**Kubernetes:**
Client Version: v1.26.1
Kustomize Version: v4.5.7
Server Version: v1.26.1

**Kyma:**
Kyma CLI version: 2.17.0
Kyma cluster version: 2.17.0
***************************************************

**kyma deploy**
- Detecting Environment
X A Kyma installation was found. Current and target version are equal: 2.17.0
? Do you want to proceed with the upgrade to '2.17.0'? Type [y/N]: y
- Using Kyma from the workspace directory: /home/.kyma/sources/2.17.0
- Initial setup
Deploying Kyma
- Component 'CRDs' deployed
- Component 'certificates' deployed
- Component 'cluster-essentials' deployed
- Component 'istio' deployed
- Component 'api-gateway' deployed
- Component 'cluster-users' deployed
X Component 'ory' failed
context deadline exceeded

X Component 'eventing' failed
context deadline exceeded

X Deploying Kyma

Deployed Components: 6/8
Could not deploy the following components:
- ory
- eventing

***************************************************
**kubectl get pods -n kyma-system**
NAME                                          READY   STATUS             RESTARTS         AGE
api-gateway-77bd76b97d-ftqzp                  1/1     Running            0                115m
**api-gateway-init-z27cm                        0/1     Completed          0                115m**
central-application-gateway-7df8f8c9d-fvkq9   2/2     Running            0                128m
central-application-gateway-7df8f8c9d-kt6cn   2/2     Running            0                128m
**eventing-controller-6b79968998-vzkng          1/2     CrashLoopBackOff   14 (4m59s ago)   52m**
**eventing-controller-cert-handler-zvffm        0/1     Completed          0                128m**
**eventing-nats-0                               0/3     Pending            0                53m**
ory-hydra-57c7ff9fbf-bdjlp                    0/2     Init:1/3           0                53m
ory-hydra-maester-9f9654bfd-rx6gq             2/2     Running            0                128m
ory-oathkeeper-5578d7b5bc-52jf2               3/3     Running            0                128m
ory-postgresql-0                              0/2     Pending            0                128m
serverless-ctrl-mngr-76d8d4574b-dlffd         1/1     Running            0                101m
**serverless-docker-registry-84f99677b5-fqzlg   0/1     Pending            0                101m**
serverless-webhook-svc-579f8467f9-2996x       1/1     Running            1 (101m ago)     101m
telemetry-operator-6989bc8d5f-nb4c4           1/1     Running            0                128m
***************************************************
**kubectl logs eventing-nats-0  -n kyma-system**
Defaulted container "config-reloader" out of: config-reloader, metrics, nats
**k8s-control: kubectl logs eventing-nats-0 -c nats -n kyma-system**
**k8s-control: kubectl logs eventing-nats-0 -c config-reloader -n kyma-system**
**k8s-control:kubectl logs eventing-nats-0 -c nats -n kyma-system**
***************************************************
**kubectl logs eventing-controller-6b79968998-vzkng  -n kyma-system**
{"level":"INFO","timestamp":"2023-08-13T12:23:02Z","logger":"controller-runtime.metrics","caller":"metrics/listener.go:44","message":"Metrics server is starting to listen","context":{"addr":":8080"}}
{"level":"INFO","timestamp":"2023-08-13T12:23:02Z","logger":"jetstream-subscription-manager","caller":"jetstream/jetstream.go:89","message":"initialized JetStream subscription manager","context":{}}
{"level":"INFO","timestamp":"2023-08-13T12:23:02Z","logger":"setup","caller":"eventing-controller/main.go:101","message":"Starting the webhook server","context":{}}
{"level":"INFO","timestamp":"2023-08-13T12:23:02Z","logger":"controller-runtime.builder","caller":"builder/webhook.go:139","message":"skip registering a mutating webhook, object does not implement admission.Defaulter or WithDefaulter wasn't called","context":{"GVK":"eventing.kyma-project.io/v1alpha1, Kind=Subscription"}}
{"level":"INFO","timestamp":"2023-08-13T12:23:02Z","logger":"controller-runtime.builder","caller":"builder/webhook.go:168","message":"skip registering a validating webhook, object does not implement admission.Validator or WithValidator wasn't called","context":{"GVK":"eventing.kyma-project.io/v1alpha1, Kind=Subscription"}}
{"level":"INFO","timestamp":"2023-08-13T12:23:02Z","logger":"controller-runtime.webhook","caller":"webhook/server.go:148","message":"Registering webhook","context":{"path":"/convert"}}
{"level":"INFO","timestamp":"2023-08-13T12:23:02Z","logger":"controller-runtime.builder","caller":"builder/webhook.go:184","message":"Conversion webhook enabled","context":{"GVK":"eventing.kyma-project.io/v1alpha1, Kind=Subscription"}}
{"level":"INFO","timestamp":"2023-08-13T12:23:02Z","logger":"controller-runtime.builder","caller":"builder/webhook.go:124","message":"Registering a mutating webhook","context":{"GVK":"eventing.kyma-project.io/v1alpha2, Kind=Subscription","path":"/mutate-eventing-kyma-project-io-v1alpha2-subscription"}}
{"level":"INFO","timestamp":"2023-08-13T12:23:02Z","logger":"controller-runtime.webhook","caller":"webhook/server.go:148","message":"Registering webhook","context":{"path":"/mutate-eventing-kyma-project-io-v1alpha2-subscription"}}
{"level":"INFO","timestamp":"2023-08-13T12:23:02Z","logger":"controller-runtime.builder","caller":"builder/webhook.go:153","message":"Registering a validating webhook","context":{"GVK":"eventing.kyma-project.io/v1alpha2, Kind=Subscription","path":"/validate-eventing-kyma-project-io-v1alpha2-subscription"}}
{"level":"INFO","timestamp":"2023-08-13T12:23:02Z","logger":"controller-runtime.webhook","caller":"webhook/server.go:148","message":"Registering webhook","context":{"path":"/validate-eventing-kyma-project-io-v1alpha2-subscription"}}
{"level":"INFO","timestamp":"2023-08-13T12:23:02Z","logger":"controller-runtime.builder","caller":"builder/webhook.go:184","message":"Conversion webhook enabled","context":{"GVK":"eventing.kyma-project.io/v1alpha2, Kind=Subscription"}}
{"level":"INFO","timestamp":"2023-08-13T12:23:02Z","caller":"eventing-controller/main.go:129","message":"start controller manager","context":{"options":"--max-reconnects=10 --metrics-addr=:8080 --reconnect-wait=3s --reconcile-period=10m0s --health-probe-bind-addr=:8081 --ready-check-endpoint=readyz health-check-endpoint=healthz APP_LOG_FORMAT=json APP_LOG_LEVEL=info"}}
{"level":"INFO","timestamp":"2023-08-13T12:23:02Z","logger":"controller-runtime.webhook.webhooks","caller":"webhook/server.go:216","message":"Starting webhook server","context":{}}
{"level":"INFO","timestamp":"2023-08-13T12:23:02Z","caller":"manager/internal.go:366","message":"Starting server","context":{"kind":"health probe","addr":"[::]:8081"}}
{"level":"INFO","timestamp":"2023-08-13T12:23:02Z","caller":"manager/internal.go:366","message":"Starting server","context":{"path":"/metrics","kind":"metrics","addr":"[::]:8080"}}
{"level":"INFO","timestamp":"2023-08-13T12:23:02Z","caller":"controller/controller.go:185","message":"Starting EventSource","context":{"controller":"secret","controllerGroup":"","controllerKind":"Secret","source":"kind source: *v1.Secret"}}
{"level":"INFO","timestamp":"2023-08-13T12:23:02Z","caller":"controller/controller.go:185","message":"Starting EventSource","context":{"controller":"secret","controllerGroup":"","controllerKind":"Secret","source":"kind source: *v1alpha1.EventingBackend"}}
{"level":"INFO","timestamp":"2023-08-13T12:23:02Z","caller":"controller/controller.go:185","message":"Starting EventSource","context":{"controller":"secret","controllerGroup":"","controllerKind":"Secret","source":"kind source: *v1.Deployment"}}
{"level":"INFO","timestamp":"2023-08-13T12:23:02Z","caller":"controller/controller.go:193","message":"Starting Controller","context":{"controller":"secret","controllerGroup":"","controllerKind":"Secret"}}
{"level":"INFO","timestamp":"2023-08-13T12:23:02Z","logger":"controller-runtime.certwatcher","caller":"certwatcher/certwatcher.go:131","message":"Updated current TLS certificate","context":{}}
{"level":"INFO","timestamp":"2023-08-13T12:23:02Z","logger":"controller-runtime.webhook","caller":"webhook/server.go:270","message":"Serving webhook server","context":{"host":"","port":9443}}
{"level":"INFO","timestamp":"2023-08-13T12:23:02Z","logger":"controller-runtime.certwatcher","caller":"certwatcher/certwatcher.go:85","message":"Starting certificate watcher","context":{}}
{"level":"INFO","timestamp":"2023-08-13T12:23:02Z","caller":"controller/controller.go:227","message":"Starting workers","context":{"controller":"secret","controllerGroup":"","controllerKind":"Secret","worker count":1}}
{"level":"ERROR","timestamp":"2023-08-13T12:23:02Z","caller":"jetstream/reconciler.go:64","message":"Failed to start reconciler","context":{"name":"jetstream-subscription-reconciler","error":"failed to connect to NATS JetStream: %!w(<nil>)"}}
{"level":"INFO","timestamp":"2023-08-13T12:23:02Z","caller":"controller/controller.go:117","message":"Observed a panic in reconciler: failed to connect to NATS JetStream: %!w(<nil>)","context":{"controller":"secret","controllerGroup":"","controllerKind":"Secret","Secret":{"name":"any","namespace":"kyma-system"},"namespace":"kyma-system","name":"any","reconcileID":"052115d2-4925-4c2f-a1a2-ad741cb41ef5"}}
**panic: failed to connect to NATS JetStream: %!w(<nil>) [recovered]
        panic: failed to connect to NATS JetStream: %!w(<nil>)**

goroutine 305 [running]:
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile.func1()
        /go/src/github.com/kyma-project/kyma/components/eventing-controller/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:118 +0x1f4
panic({0x17841c0, 0xc0005356e0})
        /usr/local/go/src/runtime/panic.go:884 +0x213
github.com/kyma-project/kyma/components/eventing-controller/controllers/subscription/jetstream.NewReconciler({0x1bf40b8?, 0xc0002f71d0}, {0x1bfa790?, 0xc0002d3d10}, {0x1bf6708?, 0xc00030e900}, 0xc000536750, {0x1bf3540?, 0xc000714640}, {0x1be2800, ...}, ...)
        /go/src/github.com/kyma-project/kyma/components/eventing-controller/controllers/subscription/jetstream/reconciler.go:65 +0x42c
github.com/kyma-project/kyma/components/eventing-controller/pkg/subscriptionmanager/jetstream.(*SubscriptionManager).Start(0xc000026000, {0xc0003fa140?, 0x2?, 0x1627ea6?}, 0x6?)
        /go/src/github.com/kyma-project/kyma/components/eventing-controller/pkg/subscriptionmanager/jetstream/jetstream.go:108 +0x4c9
github.com/kyma-project/kyma/components/eventing-controller/controllers/backend.(*Reconciler).startNATSController(0xc000100c00)
        /go/src/github.com/kyma-project/kyma/components/eventing-controller/controllers/backend/reconciler.go:873 +0x70
github.com/kyma-project/kyma/components/eventing-controller/controllers/backend.(*Reconciler).reconcileNATSBackend(0xc000100c00, {0x1bf4160, 0xc00012c840}, 0xc000187c28)
        /go/src/github.com/kyma-project/kyma/components/eventing-controller/controllers/backend/reconciler.go:209 +0x2bd
github.com/kyma-project/kyma/components/eventing-controller/controllers/backend.(*Reconciler).Reconcile(0xc000100c00, {0x1bf4160, 0xc00012c840}, {{{0xc00012c840?, 0x0?}, {0xc0004c1d38?, 0x40e147?}}})
        /go/src/github.com/kyma-project/kyma/components/eventing-controller/controllers/backend/reconciler.go:183 +0x1f7
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile(0x1bf40b8?, {0x1bf4160?, 0xc00012c840?}, {{{0xc000546020?, 0x18b6880?}, {0x197acf6?, 0xc000742e20?}}})
        /go/src/github.com/kyma-project/kyma/components/eventing-controller/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:121 +0xc8
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc000372aa0, {0x1bf40b8, 0xc00030c190}, {0x17db240?, 0xc0005340a0?})
        /go/src/github.com/kyma-project/kyma/components/eventing-controller/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:320 +0x327
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc000372aa0, {0x1bf40b8, 0xc00030c190})
        /go/src/github.com/kyma-project/kyma/components/eventing-controller/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:273 +0x1d9
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2()
        /go/src/github.com/kyma-project/kyma/components/eventing-controller/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:234 +0x85
created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2
        /go/src/github.com/kyma-project/kyma/components/eventing-controller/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:230 +0x587

**Comment by mfaizanse** [comment]
Eventing is modularised. https://github.com/kyma-project/eventing-manager
