### ISSUE TITLE
Monitoring piaserver-proxy

### ISSUE THREAD

**Issue by Disper** [kyma-project/kyma#1799]
Confirm these statements before you submit the issue:

- [x] I have searched open and closed issues for duplicates.
- [x] I have read the contributing guidelines.
---

**Description**

Authorization-proxy should provide monitoring metrics (metrics, alerting, dashboard), which currently is missing.

Monitoring Documentation:

- Metrics: https://github.com/kyma-project/examples/tree/master/monitoring-custom-metrics
- Dashboards: https://github.com/kyma-project/kyma/tree/master/resources/core/charts/monitoring/charts/grafana#making-a-dashboard-part-of-kyma-installation

Optional:
- Alerting: https://github.com/kyma-project/examples/tree/master/monitoring-alert-rules

**Comment by piotrmsc** [comment]
Postponed due to #1800 which will be done first

**Comment by piotrmsc** [comment]
## Update

Goal for this task :

- Grafana dashboard for apiserver proxy showing : 
-> Requests/s
-> Requests/s grouped by status code
-> Latency
-> Network I/O

Alerts are out of scope for now. Application-specific metrics will be added as a follow up
