### ISSUE TITLE
job: pre-main-control-plane-reconciler-e2e-latest-release keep failing

### ISSUE THREAD

**Issue by medmes** [kyma-project/kyma#17998]
**Description**
The idea behind this pipeline is to install and test Reconciler end-to-end flow on a real Gardener cluster, therefore the following  prow job

:`pre-main-control-plane-reconciler-e2e-latest-release` keep failing since `11 Aug 2023` with:

```
/home/prow/go/src/github.com/kyma-project/control-plane/tools/reconciler /home/prow/go/src/github.com/kyma-project/control-plane
Calling reconciler by using JSON template './e2e-test/template-kyma-main.json' as payload
tar: can't remove old file tmp: Is a directory
command terminated with exit code 1
AN ERROR OCCURED! Take a look at preceding log entries.
Deprovision cluster: "grdfnmeps"
shoot.core.gardener.cloud/grdfnmeps annotated
shoot.core.gardener.cloud "grdfnmeps" deleted
Job is finished (exit status: 1)
```

**Link to the job:**
https://status.build.kyma-project.io/job-history/gs/kyma-prow-logs/pr-logs/directory/pre-main-control-plane-reconciler-e2e-latest-release

**Expected result**
- The Setup test environment **step** is working.
- Prow jobs are back to normal.

**Related PR**
https://github.com/kyma-project/test-infra/pull/8720

**Comment by medmes** [comment]
Debug test-infra PR: https://github.com/kyma-project/test-infra/pull/8720

**Comment by ruanxin** [comment]
notes:

1. This pipeline is flaky, the error regarding `tar: can't remove old file tmp: Is a directory` can't be reproduced in Jptester.
2. We should fix the tar error, current decision, not use `kubectl cp` to copy file into pod, but use tar combined with `kubectl exec`
