### ISSUE TITLE
Monitoring guidelines for controllers on base of namespace-controller

### ISSUE THREAD

**Issue by Disper** [kyma-project/kyma#1800]
**Description**
Controllers written in golanhg have several characteristics important for monitoring in order to assure a healthy operation.
The goal of this issue is
- to define which metrics are relevant for golang controllers (incl. and [USE](http://www.brendangregg.com/usemethod.html) metrics), see also https://github.wdf.sap.corp/SAP-CP-Extension-Factory/community/blob/master/sig-and-wg/sig-production/investigations/nfr_components.md - have these metrics exposed for the namespace-controller
- to define relevant alert rules on base of that metrics
- activate relevant alert rules for metrics of namespace-controller
- have relevant metrics summarized in a grafana dashboard
- have a document explaining others how to apply the same for a golang controller, located here: https://github.com/kyma-project/community/tree/master/guidelines
- reflect the results also in #346

Golang applications should expose golang specific metrics like amount of goroutines, to detect problems of the application in a pro-active manner. See controllers of the service catalog which are already exposing several metrics.
Golang controllers are using the kubernetes client which might expose relevant metrics like queue size or last sync time..

Monitoring Documentation:
- Metrics: https://github.com/kyma-project/examples/tree/master/monitoring-custom-metrics
- Dashboards: https://github.com/kyma-project/kyma/tree/master/resources/monitoring/charts/grafana#making-a-dashboard-part-of-kyma-installation
- Alerting: https://github.com/kyma-project/examples/tree/master/monitoring-alert-rules

**Comment by piotrmsc** [comment]
Talk with Gophers about golang specific metrics such as gorutines

**Comment by piotrmsc** [comment]
Implement metrics for CPU/RAM rules provided by automatix,  consider creating proposal list for go-specific metrics. Talk with Gophers, they already use sth in the service catalog

**Comment by kfurgol** [comment]
Info from Automatix:

1. Kyma allows creating custom metrics, using the Prometheus client (check example https://github.com/kyma-project/examples/blob/master/monitoring-custom-metrics/main.go).
2. The suggested way to get metrics: our monitoring which includes Prometheus, allows access to kube-state-metrics (https://github.com/kubernetes/kube-state-metrics), and we should get them directly from there.
Example: https://github.com/kyma-project/kyma/blob/master/resources/monitoring/charts/exporter-kube-state/templates/kube-state-metrics.rules.yaml

**Comment by mszostok** [comment]
Currently, in service catalog all metrics are provided from generic K8S API Server.

From Gopher perspective, we can say that most valuable are CPU, Memory, Garbage Collector invocations, and numbers of goroutines.

In case of controller IMO is worth to have:
- the length of the working queue (we will know if the controller should be scaled up)
- the number of reconcile errors 
- the single reconcile time

You can check the knative pkg cause they already have lib for that, see: https://github.com/knative/pkg/tree/master/metrics

and also take in mind that Kubebuilder already providing all that stuff which I mention above it gives you of-the-box, see https://book.kubebuilder.io/beyond_basics/controller_metrics.html
