### ISSUE TITLE
EnvironmentMapping doesnt' work with namespace starting with digit

### ISSUE THREAD

**Issue by mszostok** [kyma-project/kyma#1801]
**Description**

The `EnvironmentMapping` does not work if the Namespace starting with a digit. The problem is that we have regexp https://github.com/kyma-project/kyma/blob/master/components/remote-environment-broker/internal/broker/broker_service.go#L19 which not allow doing that. Because of that, the registered ServiceBroker cannot be synced.

```
{"level":"error","log":{"message":"misconfiguration, broker is running as a namespace-scoped, but cannot extract namespace from requesturl:reb-ns-for-33tm4xcw.kyma-integration.svc.cluster.local does not match pattern reb-ns-for-([a-z][a-z0-9-]*)\\.","service":"OSBContextMiddleware","time":"2018-11-26T08:44:47.504Z"}}
```
**Expected result**

EnvironmentMapping works with all possible namespace names.

**Steps to reproduce**

Create Namespace starting with the digit and then created the EnvironmentMapping between this Namespace and some RemoteEnvironment.

**Comment by jasiu001** [comment]
The issue does not occur anymore. It is possible to create `ApplicationMapping` with digits at the beginning.
<img width="1547" alt="Screen Shot 2019-05-23 at 09 07 45" src="https://user-images.githubusercontent.com/10399074/58233864-74595780-7d3d-11e9-81bd-07de29863ecd.png">
<img width="842" alt="Screen Shot 2019-05-23 at 09 27 23" src="https://user-images.githubusercontent.com/10399074/58233878-7de2bf80-7d3d-11e9-86a0-c67610c8e041.png">

Method `GetNsFromBrokerURL` in which the [regexp rule](https://github.com/kyma-project/kyma/blob/master/components/application-broker/internal/broker/broker_service.go#L19) was applied is not used anymore.
