### ISSUE TITLE
Links to kyma-project.io/blog/ are redirected to a useless target

### ISSUE THREAD

**Issue by NHingerl** [kyma-project/kyma#18023]
**Description**

Links to [kyma-project.io/blog/](http://kyma-project.io/blog/) seem to be redirected to https://community.sap.com/topics/kyma?lng=en&tab=content , which makes no sense at all.

**Expected result**

Redirect to the blog post files in GitHub.

**Actual result**

Redirection to https://community.sap.com/topics/kyma?lng=en&tab=content , which does not have the required content.

**Steps to reproduce**

**Troubleshooting**

**Comment by valentinvieriu** [comment]
Please feel free to change the redirect to any location you think would work. This was an initial proposal that was agreed upon in the PO round.

**Comment by mmitoraj** [comment]
Redirect updated.
