### ISSUE TITLE
Navigation shows section headlines BELOW sub-doc titles

### ISSUE THREAD

**Issue by NHingerl** [kyma-project/kyma#18082]
**Description**

It's confusing that in the navigation, the “child doc” entries are _above_ the headlines that come from the parent doc.
For example, in [Get Started](https://kyma-project.io/#/02-get-started/README), the “Prerequisites” and “Steps” really shouldn’t come **_below_** the instructions.

<img width="436" alt="image" src="https://github.com/kyma-project/kyma/assets/76950046/acf99ca4-d548-450d-8733-adafd291ee31">

**Expected result**

The parent doc headlines come **_above_** the titles of child documents.

**Actual result**

The parent doc headlines come **_below_** the titles of child documents.

**Steps to reproduce**

For example, click the "Get Started" node on https://kyma-project.io/#/

**Troubleshooting**

**Comment by pbochynski** [comment]
Docsify can renders sidebar from _sidebar.md and from current document headers (up to the subMaxLevel value). I think it cannot change the order. 
But we can ignore those headers in the sidebar:
https://docsify.js.org/#/more-pages?id=ignoring-subheaders
Another way to do that is to make these headers on level 3 (## -> ###)
Anyway mixing _sidecar.md with the current document headers is not the best idea (in my opinion).

**Comment by NHingerl** [comment]
Thank you! 
Considering we have some very long documents with many sub-headlines, we must find a way to display those in a navigation. Otherwise our users will suffer death by scrolling. 
If not in the left-hand navigation, then we need a right-hand navigation like we had before.

**Comment by NHingerl** [comment]
Thanks for the quick solution @pbochynski! 
Together with Gosia, we agreed that we manually comment out such headlines for docs that are mainly navigation nodes, like you did in PR 18084.
We will not comment out the h2 headlines for documents that have more content. For those it is good if the headlines remain displayed in the navigation. 
We will also not demote h2 headlines to h3 just to hide them from navigation, because that would result in inconsistencies how the pages look.
