### ISSUE TITLE
`kyma-upgrade-k3d-kyma2-to-main` / `kyma-upgrade-gardener-kyma2-to-main-reconciler-main` failing due `serverless` cannot be deployed

### ISSUE THREAD

**Issue by jeremyharisch** [kyma-project/kyma#18113]
**Description**

The pipelines `kyma-upgrade-k3d-kyma2-to-main` and `kyma-upgrade-k3d-kyma2-to-main` are failing due to servless cannot be deployed with main branch.

Pipeline History:
-  [ kyma-upgrade-k3d-kyma2-to-main](https://status.build.kyma-project.io/job-history/gs/kyma-prow-logs/logs/kyma-upgrade-k3d-kyma2-to-main) 
- [kyma-upgrade-gardener-kyma2-to-main-reconciler-main](https://status.build.kyma-project.io/job-history/gs/kyma-prow-logs/logs/kyma-upgrade-gardener-kyma2-to-main-reconciler-main)

Fails since Sep 01 14:02:28

**Comment by dbadura** [comment]
Can we get more logs about installation.

**Comment by kwiatekus** [comment]
Fixed by https://github.com/kyma-project/kyma/pull/18115/files
