### ISSUE TITLE
Governance job: migration to Markdown link check

### ISSUE THREAD

**Issue by mmitoraj** [kyma-project/kyma#18189]
**Description**

We decided to use the Markdown link check from the GitHub Actions marketplace to verify valid hyperlinks in our documentation. The owners of the listed below repos need to migrate to the new tool.

Once the repos have the  Markdown link check workflow-enabled, supported by Neighbours, we need to clean up the old governance jobs and eventually, get rid of all [milv.config.yaml](https://github.com/kyma-project/kyma/issues/milv.config.yaml) files.

See the list of the affected repositories.

- [x] [github.com/kyma-project/kyma](https://github.com/kyma-project/kyma/) @kyma-project/technical-writers 
- [x] [github.com/kyma-project/examples](https://github.com/kyma-project/examples) @Huskies
- [x] [github.com/kyma-project/test-infra](https://github.com/kyma-project/test-infra) @Neighbors
- [x] [github.com/kyma-project/telemetry-manager](https://github.com/kyma-project/telemetry-manager) @Huskies
- [x] [github.com/kyma-project/directory-size-exporter](https://github.com/kyma-project/directory-size-exporter) @Huskies
- [x] [github.com/kyma-project/busola](https://github.com/kyma-project/busola) @kyma-project/hasselhoff 
- [x] [github.com/kyma-project/community](https://github.com/kyma-project/community) @kyma-project/technical-writers 

> **NOTE:** All `/kyma-project` repos, especially module repos, must use the tool to verify links in documentation to improve product quality.

**Reasons**

Update the 

**Attachments**

Guidelines: [Enable Markdown link check](https://github.com/kyma-project/community/blob/main/docs/guidelines/repository-guidelines/01-new-repository-settings.md#enable-markdown-link-check)

**Related issues** 

- https://github.com/kyma-project/test-infra/issues/8889
- https://github.com/kyma-project/infrastructure-manager/issues/34

**Comment by mmitoraj** [comment]
Hi @valentinvieriu, please take a look at the issue tracking migration from the milv tool to the Mardown link check. Could you roughly estimate when `/busola` would be ready with that?

**Comment by halamix2** [comment]
Busola and test-infra are done:
- https://github.com/kyma-project/busola/pull/2591
- https://github.com/kyma-project/test-infra/pull/8953

**Comment by IwonaLanger** [comment]
BTP Manager: https://github.com/kyma-project/btp-manager/pull/386
KEB: https://github.com/kyma-project/kyma-environment-broker/pull/75
