### ISSUE TITLE
Rename Remote Environment to Application

### ISSUE THREAD

**Issue by jasiu001** [kyma-project/kyma#1819]
Remote Environment CRD should be renamed to Application, this requires changes in following components:
- `components/remote-environment-broker`
- `tests/ui-api-layer-acceptance-tests`
- `tests/acceptance`

Following components should be renamed:
- Remote Environment Broker - Application Broker
- EnvironmentMapping -> ApplicationMapping
- Renaming prow-jobs

Rename only documentation in components. The general documentation under `/kyma/docs` will be changed by Tomasz Papiernik.

**Comment by mszostok** [comment]
Executing Step 1:
Rename the RemoteEnvironmentBroker to ApplicationBroker. Take care of the prow jobs and documentation.

**Comment by mszostok** [comment]
The commit with renaming EnvironmentMapping -> ApplicationMapping was pushed to this PR https://github.com/kyma-project/kyma/pull/1997

**Comment by mszostok** [comment]
## Responsibilities for renaming in components
- components/application-broker - (@adamwalach)
- tests/acceptance - (@adamwalach)
- components/ui-api-layer - (@mszostok)
- tests/ui-api-layer-acceptance-tests - (@mszostok)
