### ISSUE TITLE
Provide tooling for automated Kyma lifecycle and subscription management

### ISSUE THREAD

**Issue by varbanv** [kyma-project/kyma#18198]
## Description
Users should be able to fully automate Kyma related tasks in their CI/CD pipelines. This starts with Kyma instance provisioning, includes deployment of necessary artifacts and test executions, and ends with Kyma instance removal and associated service instance cleanup. All of this should not require much additional effort from the end user and should be as easy as possible to configure.

### Problem
Right now, users can automate the Kyma instance creation using the new Terraform provider, the cloud orchestrator tools, or the btpcli directly, however, the next step of accessing the cluster requires user interaction. 

And finally, there are a number of scenarios that could prevent a cluster from being deleted and would require user interaction to complete. 
While the second and third problems can be solved with some coding and additional resources, we want to provide ease-of-use in order to improve the perception and adoption of Kyma.

### Benefits
**For customers:**
- speed up development and release cycles
- implement best practices around CI/CD 
- reduce configuration drift
- reduce dependency on long-living Kyma instances
- reduce cost by only using Kyma instances when needed
Example usecase [scenario](https://github.com/kyma-project/kyma/issues/18666) that should be possible to run in automated way 

**For us:**
 - increase adoption
 - enable customers to treat Kyma instances as disposable assets and reduce risk
 - enable users to reduce cost
 
### Proposed solution
Design and implement a new set of kyma CLI commands that helps developers who use managed kyma runtimes within BTP ecosystem with development of their CAP applications. CLI commands should be designed with automation flow in mind (No user context should be required),

The commands should cover:
 - automated lifecycle management of kyma runtime lifecycle (provisioning, deprovisioning)
 - getting access to freshly created cluster
 - attaching BTP service instances to kyma runtimes via service manager
 - eliminating manual actions (i.e mapping hana instance, establishing trust for custom IAS tenant, etc..)
 
## Acceptance criteria

- [x] Users can create a Kyma instance and access it without any user interaction.
  - [ ] ~https://github.com/kyma-project/kyma/issues/18305~
  - [x] https://github.com/kyma-project/cli/issues/2093
  - [x] https://github.com/kyma-project/cli/issues/2115
- [x] Users can completely remove an existing Kyma instance without any user interaction, even if there are modules "stuck" in deletion.
  - [x] https://github.com/kyma-project/infrastructure-manager/issues/103 - KIM dependant
  - otherwise,  this could be done via btp cli subaccount force deletionsubaccount  
- [ ] Documentation and guides that cover the full end-to-end CI/CD scenario
  - https://help.sap.com/docs/btp/btp-developers-guide-internal/terraform-module-for-kyma?locale=en-US&state=DRAFT&version=Internal

## Attachments

[Idea for assisted kyma provisioning](https://github.tools.sap/kyma/backlog/issues/5576)

**Comment by Disper** [comment]
What would be the exact/examples of scenarios around provisioning?

**Comment by kwiatekus** [comment]
Similar request to log into kyma in headless mode
https://github.tools.sap/kyma/backlog/issues/2518

**Comment by kwiatekus** [comment]
https://github.tools.sap/kyma/backlog/issues/2660#issuecomment-2104608

**Comment by pbochynski** [comment]
It should be possible with https://github.com/kyma-project/kyma/issues/18305

**Comment by kwiatekus** [comment]
> What would be the exact/examples of scenarios around provisioning?


Additional [config](https://github.com/gardener/gardener-extension-shoot-oidc-service/blob/master/docs/usage/openidconnects.md) should be collected from user and sent to KEB. Further on, provisioner uses this data to deploy the OICD config object  and enable the shoot-oidc-service extension.
(https://github.com/gardener/gardener-extension-shoot-oidc-service/blob/master/docs/usage/openidconnects.md#register-openid-connect-provider-in-shoot-clusters)

**Comment by kwiatekus** [comment]
Provisioning kyma runtime via BTP CLI
https://blogs.sap.com/2022/02/24/creating-sap-btp-kyma-runtime-via-the-sap-btp-cli/

Cloud orchestrator:
https://pages.github.tools.sap/cloud-orchestration/

**Comment by kwiatekus** [comment]
Another approach would be to [implement OSB's `create_binding` API on the KEB side](https://github.com/kyma-project/kyma-environment-broker/issues/284), so that after kyma instance is created one could immediately create binding and use the binding data to access kyma runtime.
This has strong benefits:
 - complies with OSB specification and with UX around other BTP services (i.e create instance of hana, create binding to access it)
 - doesn't require additional OIDC config for simple use cases for short-living disposable kyma runtime (exactly for CI/CD flows)

**Comment by kwiatekus** [comment]
For users to be able to deploy their code w/o additional subscription (in the DEV mode) we aim to separate deocker-regisrty into separate DEV module to be used also outside of serverless usage 
https://github.com/kyma-project/kyma/issues/18555#issuecomment-2068633912

**Comment by kwiatekus** [comment]
Status update about new kyma CLI command prototypes supporting the automated scenario can be tracked here:
https://github.com/kyma-project/cli/issues/1942#issuecomment-2068619233

**Comment by kwiatekus** [comment]
Customizable OIDC configurations (required for this epic) are being discussed within 
https://github.com/kyma-project/infrastructure-manager/issues/134

**Comment by kwiatekus** [comment]
We also develop a kyma cli command that helps creating a serviceaccount based kubeconfig 
https://github.com/kyma-project/cli/issues/2036

**Comment by tobiscr** [comment]
Plan is to have a working KIM version on DEV latest on end of July 2024

**Comment by kwiatekus** [comment]
We have synced with @tobiscr : The latest estimate for KIM delivery on prod is end of August 2024.

We could start testing the e2e provisioning (with additional oidc) via kyma cli on DEV only after necessary integration of KEB to KIM is implemented on DEV. @kyma-project/gopher PTAL
https://github.com/kyma-project/kyma-environment-broker/issues/423#issuecomment-2194680153

**Comment by kwiatekus** [comment]
Status update 15.07.2024
 - we have planned additional work related to building the kyma cli binary using SAP hyperspace - to ensure compliant binary. (@kyma-project/otters ). We will try out the template for pipelines designed for go code and hope 🤞 there will be no complications.
 - the work on KIM side is on going
 - the work on KEB side was refined and planned

**Comment by kwiatekus** [comment]
Status update 29.07.2024

- @ptesny has came up with (and [documented](https://gist.github.com/ptesny/14f49f49e0fbe2a3143700ce707ee76b#11-access-sap-btp-kyma-adoption-global-account-with-btp-cli)) a recipe how to use custom SAP IAS tenant for automated BTP platform resources creation (incl kyma runtime) and getting access to the newly provisioned cluster in automated scenario
- @otters are working on a [template](https://github.tools.sap/otters/kyma-automation-demo) for CI pipeline for automated application integration tests that run on automatically created kyma runtime in btp environment 
- @otters are aiming to use btp terraform provider for managing btp resources in creating test resources

**Comment by kwiatekus** [comment]
Status update 26.08.2024

@kyma-project/otters team continue working on the example repository that contains:
 - [x] `*.tf` (terraform manifests) for all necessary btp resources that need to be provisioned for an automated test scenario
 - [x] make targets for provisioning resources, building and deploying sample application, testing sample application 
 - [ ] (currently in progress) definition for ADO pipeline (integrated with hyperspace tooling) 

Once the pipeline is in place we want to document the sample repo as a working recipe for managing kyma lifecycle in the CI scenario. We estimate that we need extra week.

New delivery date: 06.09.2024

**Comment by kwiatekus** [comment]
Status update 03.09.2024

 - a sample demonstration hyperspace pipeline running integration test of [sample app](https://github.tools.sap/otters/kyma-automation-demo/) is ready.
 - (in progress) providing a dedicated reusable terraform module (not a kyma module!)  - https://github.com/kyma-project/terraform-module/issues/1

New delivery date: 13.09.2024

**Comment by kwiatekus** [comment]
status update 09.09.2024
 - demo hyperspace pipeline is using extracted terraform module
 - polishing [new terraform module](https://github.com/kyma-project/terraform-module) : 
   - stability and [automated CI](https://github.com/kyma-project/terraform-module/pull/10)
   - usage examples

**Comment by kwiatekus** [comment]
Status update 04.10.2024

Working with technical writers on the documentation (as part of btp development guides)
https://help.sap.com/docs/btp/btp-developers-guide-internal/terraform-module-for-kyma?locale=en-US&state=DRAFT&version=Internal

**Comment by kwiatekus** [comment]
Status update 21.10.2024

 - [x] public documentation - simply [documenting](https://github.com/kyma-project/terraform-module/?tab=readme-ov-file#how-to-use-the-terraform-module-for-kyma) the usage of tf module
 - [ ] internal documentation (in progress)

**Comment by kwiatekus** [comment]
Status update 04.11.2024

[documentation on help portal](https://help.sap.com/docs/btp/btp-developers-guide-internal/terraform-module-for-kyma?locale=en-US&state=DRAFT&version=Internal) is in review

**Comment by kwiatekus** [comment]
The epic is delivered:

What is the tooling itself?
 - [Terraform module for kyma](https://github.com/kyma-project/terraform-module) 
Where is it Documented?
 - [SAP BTP Developer's Guide](https://help.sap.com/docs/btp/btp-developers-guide/terraforming-kyma-runtimes?locale=en-US&state=DRAFT&version=Cloud)
Is there an example pipeline?
 - [sample bookstore app](https://github.tools.sap/kyma/ci-automation-demo) comes with hyperspace pipeline
