### ISSUE TITLE
`kyma-upgrade-gardener-kyma2-to-main-reconciler-main` pipeline failed with `Function lastorder responded with error`

### ISSUE THREAD

**Issue by ruanxin** [kyma-project/kyma#18193]
**Description**

The fast-integration test in `kyma-upgrade-gardener-kyma2-to-main-reconciler-main` failed since `Sep 15 20:04:32`.
https://status.build.kyma-project.io/view/gs/kyma-prow-logs/logs/kyma-upgrade-gardener-kyma2-to-main-reconciler-main/1702744196982509568

Related code in kyma: https://github.com/kyma-project/kyma/blob/ed708914527947cb8c3052aa7ca2f5a23dc88a5d/tests/fast-integration/upgrade-test/upgrade-test-tests.js#L47

**Expected result**

fast-integration test passed all run

**Actual result**

```
  21 passing (3m)
  1 failing

  1) Upgrade test tests
       function should be reachable through secured API Rule:
     Error: Function lastorder responded with error
401: Unauthorized: {"error":{"code":401,"status":"Unauthorized","request":"b301f85c-f3f7-905e-a8fc-ae6cbf3c5881","message":"The request could not be authorized"}}
      at convertAxiosError (utils/index.js:126:10)
      at /home/prow/go/src/github.com/kyma-project/kyma/main/tests/fast-integration/test/fixtures/commerce-mock/index.js:142:11
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      at async checkFunctionResponse (test/fixtures/commerce-mock/index.js:135:15)
      at async Context.<anonymous> (upgrade-test/upgrade-test-tests.js:48:5)
```

**Comment by ruanxin** [comment]
@kyma-project/otters can you have a check if this belongs to your domain?

**Comment by kwiatekus** [comment]
I believe its a flakiness/problem in the api-gateway.
the function is up, but http response (401) suggests problem in api rule config/reconiciliation 
@kyma-project/goat please help

**Comment by barchw** [comment]
Looks like the test is using OAuth2Client from Hydra:
https://github.com/kyma-project/kyma/blob/575d77952dc35e177f604cc67abda68c6bc7dfa0/tests/fast-integration/test/fixtures/commerce-mock/lastorder-function.yaml#L173
Hydra got removed from Kyma resources, so this will no longer work

**Comment by kwiatekus** [comment]
@barchw shouldn't the testbed be adjusted correspondingly ?

**Comment by jeremyharisch** [comment]
Seems to be fixed
