### ISSUE TITLE
401 Unauthorized or 403 Forbidden - follow-up

### ISSUE THREAD

**Issue by nataliasitko** [kyma-project/kyma#18216]
Rework the [401 Unauthorized or 403 Forbidden](https://github.com/kyma-project/kyma/blob/release-2.18/docs/04-operation-guides/troubleshooting/api-exposure/apix-01-cannot-connect-to-service/apix-01-02-401-unauthorized-403-forbidden.md) troubleshooting guide so that it is written in a more general way and does not reference Hydra.

**Comment by strekm** [comment]
https://github.com/kyma-project/api-gateway/pull/620
