### ISSUE TITLE
Telemetry component fails to install in e2e-reconciler pipelines

### ISSUE THREAD

**Issue by Tomasz-Smelcerz-SAP** [kyma-project/kyma#18241]
**Description**

The `telemetry` component fails frequently in two pipelines:
- nightly-main-reconciler-e2e
- pre-main-control-plane-reconciler-e2e

The error looks as follows:
```
{"level":"DEBUG","time":"2023-09-27T05:25:25.050Z","message":"Bookkeeper evaluated reconciliation (schedulingID:6f8ec1bc-f300-4f00-bb65-6fec5dcd0ba5--58ecc90c-a5ad-4509-aba1-1ff253199d07) for cluster '6f8ec1bc-f300-4f00-bb65-6fec5dcd0ba5' to cluster status 'reconciling': Done=cluster-essentials[2],istio[2],CRDs[1],certificates[2],eventing[3],application-connector[3],monitoring[3],api-gateway[3],istio-resources[3],ory[3],cluster-users[3],serverless[3] / Error= / New= / Running=telemetry[3][error: Failed to get manifest for component 'telemetry' in Kyma version 'main': failed helm client render: loader failed to load helm chart: stat /tmp/reconciler/main/resources/telemetry: no such file or directory]"}
```
Example jobs:

- https://storage.googleapis.com/kyma-prow-logs/logs/nightly-main-reconciler-e2e/1706896652385652736/build-log.txt
- https://storage.googleapis.com/kyma-prow-logs/logs/nightly-main-reconciler-e2e/1706866452792872960/build-log.txt
- https://storage.googleapis.com/kyma-prow-logs/pr-logs/pull/kyma-project_control-plane/3086/pre-main-control-plane-reconciler-e2e/1706944162319831040/build-log.txt
- https://storage.googleapis.com/kyma-prow-logs/pr-logs/pull/kyma-project_control-plane/3041/pre-main-control-plane-reconciler-e2e/1706928429078679552/build-log.txt

**Expected result**
The `telemetry` component succeeds to install

**Actual result**
The `telemetry` component fails to install

**Steps to reproduce**
n/a

**Troubleshooting**
n/a

**Comment by a-thaler** [comment]
Not valid anymore, telemetry is modularized and not part of such pipeline anymore
