### ISSUE TITLE
Functions under Workloads has been removed

### ISSUE THREAD

**Issue by Albert9801** [kyma-project/kyma#18263]
Hi support team

My question would be: how to deploy a function if the Functions tab under Workloads does not exists anymore after the new release? 
I did not found a documentation about this topic.

Kindly ask you to help out with this problem.

Best Regards
Albert

![Screenshot 2023-10-03 122947](https://github.com/kyma-project/kyma/assets/80950003/3ea4eef5-c8c3-4622-9b33-17fc70a7d4c6)

**Comment by kwiatekus** [comment]
@Albert9801 Serverless has become an optional module.
Please make sure serverless is enabled and refresh the browser window
