### ISSUE TITLE
`kyma-upgrade-gardener-kyma2-minor-versions` pipeline is failing due to failure in fetching serverless resource metadata

### ISSUE THREAD

**Issue by nesmabadr** [kyma-project/kyma#18285]
**Description**

`kyma-upgrade-gardener-kyma2-minor-versions` pipeline is failing with the following error:

`Failed to fetch resource metadata for serverless.kyma-project.io/v1alpha2/Function: HTTP request failed`

Pipeline logs: 
https://status.build.kyma-project.io/view/gs/kyma-prow-logs/logs/kyma-upgrade-gardener-kyma2-minor-versions/1712015213886181376

**Expected result**

Pipeline should succeed.

**Actual result**

Pipeline is failing since October 9th

**Comment by kwiatekus** [comment]
Hi.
Serverless in no longer part of kyma. It is no longer installed with kyma
( see the [PR](https://github.com/kyma-project/kyma/pull/18271)).

No kyma tests should rely on CRDs installed by serverless module.
Redirecting to maintainers of `upgrade-test/upgrade-test-prep.js`

The script is executed by the makefile here -> https://github.com/kyma-project/kyma/blob/main/tests/fast-integration/Makefile#L22C16-L22C16
It looks like eventing tests use Function CRs in the test fixtures.
@kyma-project/eventing please drop this dependency in the tests. Short term mitigation could be to ensure that serverless is installed in your test scenario [by applying serverless operator and Serverless CR
](https://github.com/kyma-project/serverless-manager#install)
