### ISSUE TITLE
Fix `eventing_epp_requests_duration_milliseconds` metric

### ISSUE THREAD

**Issue by k15r** [kyma-project/kyma#18286]
Description

EPP exposes a metric `eventing_epp_requests_duration_milliseconds`. It states that its unit is milliseconds, unfortunately the values it records are in fractions of seconds. 

Acceptance
- the metric is renamed to eventing_epp_requests_duration_seconds
- the buckets used by the metric are adjusted accordingly
- the documenation is updated

Development: 
Currently this metric is recorded using promhttps HandlerInstrumentation:
https://github.com/kyma-project/kyma/blob/270f870c29234b3ed66fb07a8afa7d8e4af93453/components/event-publisher-proxy/pkg/metrics/collector.go#L169

**Comment by ebensom** [comment]
Please define these buckets for the metric:

```
0.001, 0.002, 0.004, 0.008, 0.016, 0.032, 0.050, 0.075, 0.1, 0.15, 0.02, 0.25, 0.3, 0.35, 0.4, 0.45, 0.5, 0.6, 0.7, 0.8, 0.9, 1, 1.5, 2, 5, 10
```
