### ISSUE TITLE
do not deploy EPP unless NATS is found (in nats mode)

### ISSUE THREAD

**Issue by k15r** [kyma-project/kyma#18298]
## Description

With NATS configured as active eventing BAckend and no nats being available in the cluster (NATS module disabled) we do not want to deploy the EPP as it will fail the readiness check.

EPP deployment gets created in this function: https://github.com/kyma-project/kyma/blob/e2526c1d965c8b83b35b633c8e40bf317a1db3f6/components/eventing-controller/controllers/backend/reconciler.go#L645

**Comment by friedrichwilken** [comment]
what happens after this fix?
- no nats at all, then kyma main 
	- ec is runnin
	 - eventing-backend is not ready
	- no epp
	- but epp services (epp, health and metrics)
 - now, deploy nats(-module) on the cluster
	```
	kyma alpha enable module nats -c fast -n kyma-system
	```
	 - nats pods are ready
	 - ec is still running
	 - eventing-backend is ready
	 - epp is ready
	 - epp service is still there
  - now, disable nats(-module) again
	```
	kyma alpha disable module nats -c fast -n kyma-system
	```
	  - no nats pods
	  - ec is running
	  - epp is ready
	  - eventing-backend is ready
