### ISSUE TITLE
Cors settings in API rules

### ISSUE THREAD

**Issue by rohitrajt43** [kyma-project/kyma#18309]
**Description**
We are having issues while trying to access an API due to CORs. On debugging, we found that the API rule which is used to expose this service creates a virtual service automatically with default CORs policies which is blocking the request. After reading through different forums, we found that we can patch the corresponding virtualservice manually. We tried this and it works for us. But we noticed that this virtualservice gets updated back to the default cors policies. 

**Expected result**
Ability to set cors policies on our virtualservices consistently without getting overridden.

**Actual result**
The cors polices are overridden and the API call from our application to the service fails. 

Please let us know any workarounds or a way to consistently set the CORs policies in our virtualservices without it being overridden.

**Comment by strekm** [comment]
hello @rohitrajt43 mentioned VirtualService is managed by api-gateway module and should not be modified. The module will reconcile it to default settings. 
Atm there is no possibility to configure CORS on APIRule. In api-gateway module backlog there is feature request that you can track: https://github.com/kyma-project/api-gateway/issues/705
