### ISSUE TITLE
Unify CRs' descriptions in Busola

### ISSUE THREAD

**Issue by nataliasitko** [kyma-project/kyma#18321]
**Description**

There are multiple versions of a CR description in Busola. TWs should agree on one version and use it for all the modules.

Use the following versions (to be discussed):

| status | current description | updated description | link to the code |
|:---|---|---|---|
|<ul><li> [x] </li></ul> | [Istio CR](https://github.com/kyma-project/istio/blob/main/config/samples/operator_v1alpha2_istio.yaml) describes the Istio module | [Istio custom resource](https://github.com/kyma-project/istio/blob/main/config/samples/operator_v1alpha2_istio.yaml) configures the Istio module. | https://github.com/kyma-project/istio/blob/main/config/ui-extensions/istios/general#L14 |
|<ul><li> [x] </li></ul> | [Keda CR](https://github.com/kyma-project/keda-manager/blob/main/docs/user/01-20-configuration.md) configures keda installation. | [Keda custom resource](https://github.com/kyma-project/keda-manager/blob/main/docs/user/01-20-configuration.md) configures the Keda module.| https://github.com/kyma-project/istio/blob/main/config/ui-extensions/istios/general#L14 |
|<ul><li> [x] </li></ul> | [Kyma Custom Resource](https://github.com/kyma-project/lifecycle-manager/blob/main/docs/technical-reference/api/kyma-cr.md) represents Kyma installation in a cluster. | [Kyma custom resource](https://github.com/kyma-project/lifecycle-manager/blob/main/docs/technical-reference/api/kyma-cr.md) represents Kyma installation in a cluster.| https://github.com/kyma-project/kyma-dashboard/blob/main/extensions/kyma/kyma.yaml#L120 |
|<ul><li> [ ] </li></ul> ❗ | [ModuleTemplate Custom Resource](https://github.com/kyma-project/lifecycle-manager/blob/main/docs/technical-reference/api/moduleTemplate-cr.md) contains modules' metadata with links to their images and manifests. | [ModuleTemplate custom resource](https://github.com/kyma-project/lifecycle-manager/blob/main/docs/technical-reference/api/moduleTemplate-cr.md) contains modules' metadata with links to their images and manifests.| https://github.com/kyma-project/kyma-dashboard/blob/main/extensions/kyma/moduleTemplate.yaml#L48 |
|<ul><li> [x] </li></ul> | [NATS CR](https://github.com/kyma-project/nats-manager/blob/main/config/samples/default.yaml) specifies NATS module. | [NATS custom resource](https://github.com/kyma-project/nats-manager/blob/main/config/samples/default.yaml) configures the NATS module.| https://github.com/kyma-project/nats-manager/blob/main/config/ui-extensions/nats/general#L14 |
|<ul><li> [x] </li></ul> | [Serverless CR](https://github.com/kyma-project/serverless-manager/blob/main/config/samples/default_serverless_cr.yaml) specifies serverless module. | [Serverless custom resource](https://github.com/kyma-project/serverless-manager/blob/main/config/samples/default_serverless_cr.yaml) configures the Serverless module.| https://github.com/kyma-project/serverless-manager/blob/main/config/operator/ui-extensions/serverless/general#L14 |
|<ul><li> [x] </li></ul> | The [Telemetry](https://kyma-project.io/#/telemetry-manager/user/resources/01-telemetry) resource configures the telemetry module. <br>_(the link leads to the website)_| [Telemetry custom resource](https://github.com/kyma-project/telemetry-manager/tree/main/config/samples) configures the Telemetry module.| https://github.com/kyma-project/telemetry-manager/blob/main/config/busola/telemetry_busola_extension_cm.yaml#L110 |
|<ul><li> [x] </li></ul> | See the description of the [APIGateway custom resource](https://github.com/kyma-project/api-gateway/blob/main/config/samples/operator_v1alpha1_apigateway.yaml). | [APIGateway custom resource](https://github.com/kyma-project/api-gateway/blob/main/config/samples/operator_v1alpha1_apigateway.yaml) configures the API Gateway module.| https://github.com/kyma-project/api-gateway/blob/main/config/ui-extensions/apigateways/general#L14 |
|<ul><li> [x] </li></ul> | | [ApplicationConnector custom resource](https://kyma-project.io/#/application-connector-manager/user/resources/06-30-application-connector) configures the Application Connector module. |
|<ul><li> [x] </li></ul> | | [Eventing custom resource](https://kyma-project.io/#/eventing-manager/user/02-configuration) configures the Eventing module. | 

**Area**
* UI

**Reasons**

- improve the user experience, ensure consistency in the user interface texts

**Assignees**

@kyma-project/technical-writers

**Attachments**

<img width="1591" alt="Screenshot 2023-10-19 at 14 24 07" src="https://github.com/kyma-project/kyma/assets/80401180/e6d9fdf1-94c5-4e9d-b97e-6ef3380b0871">

**Comment by NHingerl** [comment]
I like the proposal!

**Comment by mmitoraj** [comment]
[Kyma custom resource](https://github.com/kyma-project/lifecycle-manager/blob/main/docs/technical-reference/api/kyma-cr.md) represents Kyma installation in a cluster. -change to [Kyma custom resource](https://github.com/kyma-project/lifecycle-manager/blob/main/docs/technical-reference/api/kyma-cr.md) configures your Kyma modules

**Comment by mmitoraj** [comment]
[ModuleTemplate Custom Resource](https://github.com/kyma-project/kyma-dashboard/blob/main/extensions/kyma/moduleTemplate.yaml#L48) - file not found

**Comment by mmitoraj** [comment]
In the new CRs' descriptions, we link to the kyma-project.io user documentation about each resource.
