### ISSUE TITLE
Credentials form allows empty value in mandatory "select" field

### ISSUE THREAD

**Issue by adamwalach** [kyma-project/kyma#1833]
**Description**

The "Create credentials" form for BigQuery service has the "Roles" field marked as mandatory:
![screen shot 2018-11-27 at 11 20 39](https://user-images.githubusercontent.com/8530211/49080206-2b6b8f00-f243-11e8-82a4-dec9ff79a814.png)
But I am able to submit the form even with empty selection on this field. The creation process fails shortly after the submit because this field is required:
![screen shot 2018-11-27 at 13 45 40](https://user-images.githubusercontent.com/8530211/49082703-c156e800-f24a-11e8-9c21-2734c67d472b.png)

**Expected result**

The submit action should fail with a proper error message just like it does when other types of mandatory fields are empty

**Actual result**

Submit action of the form works and the creation process fails on next step

**Steps to reproduce**

Create new BigQuery service (from the GCP Broker Bundle) and try to add new credentials

**Comment by akucharska** [comment]
When an array property is marked as required, an empty array is considered valid. If array needs to be populated, you can specify the minimum number of items using the minItems property.

```
const schema = {
  type: "array",
  minItems: 1,
  title: "A multiple-choice list",
  items: {
    type: "string",
    enum: ["foo", "bar", "fuzz", "qux"],
  },
  uniqueItems: true
}
```

**Comment by PK85** [comment]
Closing as we remove that broker from Kyma.
