### ISSUE TITLE
'Service Binding' form in Lambdas section does not support any additional parameters

### ISSUE THREAD

**Issue by adamwalach** [kyma-project/kyma#1835]
**Description**

The 'Service Binding' form in the 'Lambdas' section doesn't show any parameters when the 'Create new secret for the binding' checkbox is  selected:
![screen shot 2018-11-27 at 14 11 47](https://user-images.githubusercontent.com/8530211/49083946-645d3100-f24e-11e8-9a4f-264d1fbd1d98.png)

**Expected result**

When I am creating new credentials from the 'Service instances' view the form properly shows input parameters required by a given service:
![screen shot 2018-11-27 at 14 14 04](https://user-images.githubusercontent.com/8530211/49084123-dd5c8880-f24e-11e8-9529-e0ee88db1e48.png)

**Actual result**

Since no parameters are passed the creation of new secret fails

**Steps to reproduce**

Create new 'Service instance' that requires any parameters for creating new credentials.
Create new Lambda and try to use the 'Create Service Binding' action to add a new secret

**Comment by kwiatekus** [comment]
We are in process of rewriting lambda UI to react. The same component for service binding will be used in lambda UI
