### ISSUE TITLE
Remove Application Connector From Monolit Kyma

### ISSUE THREAD

**Issue by koala7659** [kyma-project/kyma#18360]
**Acceptance criteria**

- [x] Central Gateway charts removed
- [x] Central Application connectivity Validator charts removed
- [x] Installation files removed
- [x] Runtime overrides removed

Deadline: Kyma 2.20 release cutoff 30.10.2022

Updated dealine: Release 2.21

**Comment by koala7659** [comment]
PR for Kyma: https://github.com/kyma-project/kyma/pull/18367

**Comment by grego952** [comment]
PR for documentation: https://github.com/kyma-project/kyma/issues/18368

**Comment by Disper** [comment]
Related PR https://github.com/kyma-project/kyma/pull/18373

**Comment by mvshao** [comment]
Done
