### ISSUE TITLE
Improve kyma-project.io UI

### ISSUE THREAD

**Issue by mmitoraj** [kyma-project/kyma#18381]
**Description**

The kyma-project.io website is now a very basic one when it comes to its UI. It lacks some features that would make it more user-friendly and better-looking.

Let's use some time to investigate [Docsify plugins](https://docsify.js.org/#/awesome) and implement those that could be useful for our users.

- [x] https://github.com/jperasmus/docsify-copy-code - copy-code plugin
- [x] https://github.com/imyelo/docsify-pagination#readme - pagination plugin
- [ ] ?

**Area**

* documentation

**Reasons**

More user-friendly docu

**Assignees**

@kyma-project/technical-writers

**Attachments**

**Comment by nataliasitko** [comment]
Docsify allows for using red and blue notes. You just add `!> **CAUTION**` or `?> **NOTE**` and it’s rendered like in the screenshots. In my opinion, it looks really nice.
<img width="400" alt="Screenshot 2023-12-29 at 12 43 24" src="https://github.com/kyma-project/kyma/assets/80401180/3a337b87-7e3d-4a0c-883a-cc2a797503b3" /> <img width="400" alt="Screenshot 2023-12-29 at 12 54 25" src="https://github.com/kyma-project/kyma/assets/80401180/94e2f904-64ab-4f3c-9479-621080509c08">
Unfortunately, there are no green notes available for tips (we rarely use them anyway), and when you add two notes one after another, they’re not indented correctly (a workaround would be to join such notes)
<img width="400" alt="Screenshot 2023-12-29 at 12 45 01" src="https://github.com/kyma-project/kyma/assets/80401180/c273d77e-33a9-4181-a6c0-b911d81735f2" /> <img width="400" alt="Screenshot 2023-12-29 at 12 36 03" src="https://github.com/kyma-project/kyma/assets/80401180/7d4693e2-055f-4be2-a2d9-39673e7e4649">

**Comment by nataliasitko** [comment]
Some additional ideas to be discussed:
- [ ] [Google Analytics](https://angry-swanson-b4e47b.netlify.app/plugins?id=google-analytics) or investigate other analytics options; first: check legal requirements
- [ ] I was wondering if we could use a shade of blue in UIs that matches the one used in the Kyma logo. It would create better contrast and make UIs more noticeable in dark mode 
- [ ] Find out if that's possible to make the pagination and statements stick to the bottom of a page, even when there's only little text
- [ ] Beautify cautions and warnings: use the Docsify solution (see the [comment](https://github.com/kyma-project/kyma/issues/18381#issuecomment-1871993093)) or the [Flexible Alerts plugin](https://github.com/fzankl/docsify-plugin-flexible-alerts) (even nicer, but I haven't tested it yet)
- [ ] [Edit on GitHub](https://angry-swanson-b4e47b.netlify.app/plugins?id=edit-on-github)
- [ ] Add [Page not found](https://angry-swanson-b4e47b.netlify.app/configuration?id=notfoundpage) with a link to Kyma Home

**Comment by NHingerl** [comment]
> I was wondering if we could use a shade of blue in UIs that matches the one used in the Kyma logo. It might create better contrast and make UIs more noticeable in dark mode

![Image](https://github.com/kyma-project/kyma/assets/76950046/bca77b5d-9c74-4db2-a0c4-09341c240173)
