### ISSUE TITLE
Commerce Mock not ready: Pipelines are failing

### ISSUE THREAD

**Issue by jeremyharisch** [kyma-project/kyma#18404]
**Description**
The pipeline `kyma-upgrade-gardener-kyma2-minor-versions` is failing since the CommerceMock test is failing with the following:

```yaml
  1) Upgrade test preparation
       CommerceMock test fixture should be ready:
     Error: Waiting for deployment central-application-gateway timeout (90000 ms)
      at Timeout._onTimeout (utils/index.js:345:20)
      at listOnTimeout (node:internal/timers:559:17)
      at processTimers (node:internal/timers:502:7)
```
Links:
- https://status.build.kyma-project.io/view/gs/kyma-prow-logs/logs/kyma-upgrade-gardener-kyma2-minor-versions/1722524523942645760
- https://storage.googleapis.com/kyma-prow-logs/logs/kyma-upgrade-gardener-kyma2-minor-versions/1722886917541859328
- https://status.build.kyma-project.io/view/gs/kyma-prow-logs/logs/kyma-upgrade-gardener-kyma2-minor-versions/1722162129944973312

**Expected result**
Commerce Mock should be ready.

**Actual result**
CommerceMock is not ready.

**Steps to reproduce**

**Troubleshooting**

**Comment by ruanxin** [comment]
the decision is remove this prow job https://github.com/kyma-project/test-infra/pull/9327
