### ISSUE TITLE
move EPP out of kyma into the eventing-manager and setup pipelines / cleanup old pipelines

### ISSUE THREAD

**Issue by k15r** [kyma-project/kyma#18439]
## Description

move code related to EPP to `kyma-project/eventing-publisher-proxy`. 

## Acceptance
- [x] move code (keeping its history) 
- [x] make sure it still builds
- [x] update all dependencies for the old repository and eventing-controller to the new repository and eventing-manager
- [x] setup security scanning
  - [x] setup sec-scanner-config.yaml
  - [x] ensure the repository gets scanned
- [x] update documentation

**Comment by mfaizanse** [comment]
Follow-up issue: https://github.com/kyma-project/eventing-publisher-proxy/issues/27

**Comment by mfaizanse** [comment]
New scan for EPP got created: https://github.tools.sap/kyma/security-scans-modular/issues/11236
