### ISSUE TITLE
Add links to troubleshooting sections in modules documents in the general Kyma Troubleshooting doc

### ISSUE THREAD

**Issue by grego952** [kyma-project/kyma#18551]
**Description**
Let's add the links to troubleshooting sections in the module repos in the general [Kyma Troubleshooting](https://kyma-project.io/#/04-operation-guides/troubleshooting/README) doc. This way, users will have an easy access to the given troubleshooting section.

**Area**
* Documentation

**Reasons**
Users have easy access to the required troubleshooting section

**Assignees**
@mmitoraj 

**Attachments**

**Comment by mmitoraj** [comment]
Done
