### ISSUE TITLE
Release Kyma 0.6 using prow

### ISSUE THREAD

**Issue by PK85** [kyma-project/kyma#1859]
AC:
- execution and coordination of the Kyma 0.6.0 release
- find and familiarise with current release processes
- Document whole process in Kyma project how to release (with conjunction to prow release technical documentation)
- create pre-release branch already on 7-10.01.2018
- final date of the release: 0.6 Cairo - 14.01.2019

See blogpost about 0.6: 
- https://kyma-project.io/blog

**Comment by PavelPavlov46** [comment]
could you please loop in @jose-cortina & me in the process? There are already multiple initiatives arround this topic and we would like to try to merge them in one place ?

**Comment by jasiu001** [comment]
According to blog post about release the main feature to appear are:

1. Knative integration
2. Prow integration
3. Renaming:
    Environment --> Namespace
    Remote Environment --> Application

    For Environments, the changes will be limited to the
      * Console UI
      * Environment Controller name
      * Related documentation
    The Remote Environment renaming
      * CRD names
      * Console UI
      * Documentation
      * Remote Environment Controller
4. Switching Console UI to Luigi framework
5. Unifying the acceptance tests code base. Additionally, delivery of tools for testing the Service Catalog UI.
6. Extending the UI-API Layer (GraphQL) with an authorization concept

Current tasks status is available [here](https://app.zenhub.com/workspaces/kyma---all-repositories-5b6d5985084045741e744dea/reports?report=release&release=5c015e1eda763f3a7c15abef)

Current release process can be find at this [link](https://wiki.hybris.com/pages/viewpage.action?spaceKey=ysf&title=Automated+Kyma+Release)

**Comment by jasiu001** [comment]
Release process on prow is availabe [here](https://github.com/kyma-project/test-infra/blob/master/docs/prow/release-process.md)
