### ISSUE TITLE
Can not install istio component by kyma

### ISSUE THREAD

**Issue by zongqichen** [kyma-project/kyma#18602]
**Description**

When I try to install Compass by [kyma](https://github.com/kyma-incubator/compass/blob/main/installation/scripts/install-kyma.sh#L49), there is error appeared:
```
- Using Kyma from the workspace directory: /root/.kyma/sources/2.13.1
Deploying Kyma
- Component 'CRDs' deployed
- Component 'certificates' deployed
- Component 'cluster-essentials' deployed
X Component 'istio' failed. Retrying...
no matches for kind "IstioOperator" in version "install.istio.io/v1alpha1"
```

```
k3d version v5.6.0
k3s version v1.27.4-k3s1 (default)
```

**Expected result**

Istio can be found and installed
**Actual result**
```
X Component 'istio' failed. Retrying...
no matches for kind "IstioOperator" in version "install.istio.io/v1alpha1"
```

**Steps to reproduce**

Execute this script can reproduce the issue [run.sh](https://github.com/kyma-incubator/compass/blob/main/installation/cmd/run.sh)

**Troubleshooting**

- I try different kyma version from 2.13.1 to 2.20.0, it doesn't help. 
- If I install istio directly, it works:
 ```
kubectl label namespace kyma-system istio-injection=enabled --overwrite
kubectl apply -f https://github.com/kyma-project/istio/releases/latest/download/istio-manager.yaml
kubectl apply -f https://github.com/kyma-project/istio/releases/latest/download/istio-default-cr.yaml
```

**Comment by strekm** [comment]
hello there, Kyma got modularised since versions you mention here. Installation method you mention here is proper way of installation istio module. you can refer to istio docu https://github.com/kyma-project/istio
