### ISSUE TITLE
Migrate from `kyma provision k3d` into `k3d cluster create`

### ISSUE THREAD

**Issue by kwiatekus** [kyma-project/kyma#18652]
**Description**

 - Update [docs](https://github.com/search?q=org%3Akyma-project+%22kyma+provision+k3d%22+language%3AMarkdown&type=code&l=Markdown) : `kyma provision k3d` should not be recommended anymore
 - Update shell scripts using [`kyma provision k3d`](https://github.com/search?q=org%3Akyma-project+%22kyma+provision+k3d%22+language%3AShell+&type=code). Replace `kyma provision k3d` with `k3d cluster create` + `kubectl create ns kyma-system`

**Reason**
https://github.com/kyma-project/cli/issues/2051

**Comment by halamix2** [comment]
```bash
k3d registry create kyma-registry --port 5001

k3d cluster create kyma --kubeconfig-switch-context -p 80:80@loadbalancer -p 443:443@loadbalancer --registry-use kyma-registry
kubectl create ns kyma-system
```
Is closer in terms of replicating the `kyma provision k3d` functionality
