### ISSUE TITLE
Implement Library concept and provide utils for acceptance testing

### ISSUE THREAD

**Issue by mszostok** [kyma-project/kyma#1868]
**Description**

In Kyma project we have an agreement to introduce common libraries. The proposal was discussed and accepted. 

**Now is time to kick-off and first implementation!**

AC:
- [x] the `common` pkg folder is created in [kyma](https://github.com/kyma-project/kyma) repository with strong CODEOWNERS
- [ ] all projects under the [kyma-project/kyma/tests](https://github.com/kyma-project/kyma/tree/master/tests) are analyzed and common logic is identified 
- [ ] common logic from [kyma-project/kyma/tests](https://github.com/kyma-project/kyma/tree/master/tests) is unified by testing utils which follows all restrictions (see below section) to be in kyma libraries
- [ ] testing utils from kyma libraries are used in all projects under [kyma-project/kyma/tests](https://github.com/kyma-project/kyma/tree/master/tests)
- [ ] The first implementation of kyma libraries are announced. The Kyma developers are encouraged to analyze their projects and extract common logic to kyma libraries which can be used by others.

> **NOTE**: Restrictions
Libraries must be well-tested. Tests must be executed with the `-count 100` flag to ensure stability and with the `-race` flag to detect all race conditions. 
+Each library must contain good documentation. It is also highly recommended that each library has the [Example Test](https://blog.golang.org/examples) similar to this [one](https://github.com/mszostok/kyma/blob/libs/common/http/client_example_test.go#L13).

**Reasons**

Please see [this](https://github.com/kyma-project/community/issues/142) proposal for more information

**Comment by sjanota** [comment]
This issue is partially blocking my PR with common ingress gateway client for tests #1947. I'm giving a try to creating `common` package. Expect a PR soon.

**Comment by jasiu001** [comment]
**First Step**
Find and update all test parts which can be replaced by `FuncAtMost()` test in `/acceptance/pkg/repeat/repeat.go`

| test | user |
| ---- | ---- |
| acceptance | |
| api-controller-acceptance-test | @jasiu001  |
| application-operator-tests | |
| application-registry-tests | |
| connector-service-tests | |
| event-bus | |
| gateway-tests | |
| knative-serving-acceptance | |
| kubeless | |
| kubeless-integration | |
| logging | |
| test-logging-monitoring | |
| test-namespace-controller | |
| ui-api-layer-acceptance-tests | |

**Comment by sjanota** [comment]
Instead of using custom solution I suggest using existing package (there are plenty of them). I have used [avast/retry-go](https://github.com/avast/retry-go) in api-controller-acceptance and knative-serving-acceptance.

**Comment by PK85** [comment]
Library has not been provided, cause there is an opensource version that can be used. Ticket contains nice analysis about existing tests that could be used for further followups.
