### ISSUE TITLE
Bundles supports OSB API contract + test bundle implementation

### ISSUE THREAD

**Issue by PK85** [kyma-project/kyma#1870]
**Description**

We need to apply all OSB API specific into bundle configuration.

**Reasons**

Enable all options from OSB API.

AC:
- input parameters schema for service bindings
- support all parameters from classes and plans, bindings
- add index-testing.yaml which contains first bundle called something like testing-0.1.0
  - contains simple deployment that will be used in test for binding to.
  - has two plans, one simple with just manadatory attributes and one expanded with all options set (also input parameters for SI and SB)

**Comment by mszostok** [comment]
Helpful links about our custom additional parameters used in Service Catalog view
- https://github.com/kyma-project/kyma/blob/master/docs/service-catalog/docs/060-ui-overview.md
- https://github.com/kyma-project/kyma/blob/master/docs/service-catalog/docs/061-ui-catalog.md
- https://github.com/kyma-project/kyma/blob/master/docs/service-catalog/docs/062-ui-instances.md
