### ISSUE TITLE
Adapt kyma installation for xip.io domain

### ISSUE THREAD

**Issue by piotrmsc** [kyma-project/kyma#1871]
**Description**

As a part of publishing Kyma to GCP Marketplace, we need to have bit different approach for installing kyma from Marketplace. During installation, we have to obtain load balancer ip address and override the domain to consist of {loadbalancerIP}.xip.io. So for example console is available under `https://console.{loadbalancerIP}.xip.io`. With xip.io we do not need to make entries do DNS.

This change should be applied only when installation from Marketplace is triggered(helm feature toggle in the values.yaml).
Additionally, self-signed TLS cert should be generated for given domain.
Create a separate step in the installation phase which will override certs used in istio patch.

AC: 

- kyma can be installed under xip.ip domain on self-signed cert only (via helm feature toggle) 

**Reasons**
Must have to enable kyma on GCP Marketplace

**Attachments**

**Comment by sjanota** [comment]
I don't think patch direction is the right one. On one hand we are leaving bash scripts behind and don't allow creation of new ones (#1785), but istio-kyma-patch is nothing more than a bash script. If we are going in this direction we need to refine this component to make it more stable, tested and bulletproof. And rewrite it from bash.

**Comment by pbochynski** [comment]
I would do it in separate step. It should not be part of istio patch. The new component would check if domain is set - if not it is set to the ingresIP.xip.io and self signed cert is issued.

**Comment by Tomasz-Smelcerz-SAP** [comment]
Additional informations:
- No interactions with external resource providers (IP, DNS), everything is in-cluster.
- IP Address is taken from the cluster (kubectl get ingress ... ?)
- Additional component that is launched after istio and injects IP, DNS and self-signed certs as overrides for subsequent steps
- Additional config for this kind of installation.
- Consider where to put this additional config. kyma-incubator ?
- Create a README (simple-installation.md) that documents the steps. Installation is one step!

How to prove it works (Demo):
- Provision a fresh GKE cluster (or any other with IPs that are public, not minikube!)
- kubectl apply -f simple-installation.yaml
- wait ...
- get IP address from the cluster
- visit: https://console.{loadbalancerIP}.xip.io
- Install
