### ISSUE TITLE
Open Source Kyma on Ubuntu?

### ISSUE THREAD

**Issue by Darshan-Movilitas** [kyma-project/kyma#18725]
Dear Kyma Team,

I am wondering if we can install Kyma on Ubuntu System or not. I have tried open source Kyma on my local PC (Windows), and it has been successful.

Thank you,
Darshan Pithadiya

**Comment by a-thaler** [comment]
Hi @Darshan-Movilitas ,
Kyma is a set of modules to be installed on a kubernetes cluster. For local installation we recommend to use K3D as kubernetes cluster, furthermore you need kubectl. Both tools are available for Linux as well, which is the only prerequisite, see also https://kyma-project.io/#/02-get-started/01-quick-install

Do you have some concrete doubts? How have you installed it on windows?

**Comment by Darshan-Movilitas** [comment]
Hi, @a-thaler ,

I have installed it using exactly the same steps as above (using K3D). On an extra note, I also installed Docker. 
It is just before I try on my virtual box Ubuntu machine that I need to know.

**Comment by a-thaler** [comment]
ok, thanks for the explanation. So yes, on linux it should work as well as the required tooling is supported on linux. @kyma-project/technical-writers can you maybe add docker as a indirect prerequisite of k3d as it indeed requires quite some additional steps.
