### ISSUE TITLE
Guideline for kyma grafana dashboards

### ISSUE THREAD

**Issue by a-thaler** [kyma-project/kyma#1872]
Analyze the existing dashboards and discuss with the teams on what data is still missing and make a proposal on what dashboards kyma should bundle out of the box

Proposal should cover:
- naming convention
- type of boards we want to have and what they should provide
- concrete proposal for existing dashboards
- follow-up tickets created

**Comment by suleymanakbas91** [comment]
do we still need this? @a-thaler

**Comment by a-thaler** [comment]
Became invalid with the recent refactorings. General guideline will be provided by https://github.com/kyma-project/kyma/issues/6674
