### ISSUE TITLE
Update the documentation to reflect the current K8s APIs

### ISSUE THREAD

**Issue by AribaOpensource** [kyma-project/kyma#18738]
**Description**

Updating the PVC backup documentation to reflect the latest K8s APIs
**back-up-kyma**

**Reasons**

Outdated documentation which will not work on latest Kyma clusters. Refer to https://kyma-project.io/#/04-operation-guides/operations/10-backup-kyma?id=create-a-periodic-snapshot-job
Here the K8s API version referred as `v1beta1` which is not the current API version of current Kyma clusters.

**Assignees**

@kyma-project/technical-writers

**Attachments**

**Comment by a-thaler** [comment]
Thanks a lot for the feedback, indeed that docu was not updated for a long time. @mmitoraj Can you take care of that.

**Comment by mmitoraj** [comment]
Resolved. Please see https://github.com/kyma-project/kyma/pull/18739.
