### ISSUE TITLE
btpmanager docs link to 404

### ISSUE THREAD

**Issue by sleungcy** [kyma-project/kyma#18747]
**Description**

The tutorial links under the documentation page https://kyma-project.io/#/btp-manager/user/tutorials/README is leading to 404.

**Area**

* SAP Btp operator module
* 
**Reasons**

The tutorial links under the btp operator module are leading to 404 page not found errors.

**Assignees**

@kyma-project/technical-writers

**Attachments**

<img width="1117" alt="image" src="https://github.com/user-attachments/assets/015848dd-35a7-429b-ab02-4603a96835d1">

**Comment by IwonaLanger** [comment]
@sleungcy Thank you for reporting this. The links have been fixed. Please see the updated SAP BTP Operator documentation here: https://kyma-project.io/#/btp-manager/user/README.
