### ISSUE TITLE
Using Velero

### ISSUE THREAD

**Issue by luizcarlospedrosogomes** [kyma-project/kyma#18741]
How to use Velero to backup a postgres database (statefull)?

**Comment by a-thaler** [comment]
Hi @luizcarlospedrosogomes ,
I don't see that there should be a guide as part of the Kyma documentation. While Kyma recommends Velero as one solution for backups, a specific guide for Velero in combination with Postgres should be the duty of Veleros documentation. A quick search revealed some existing community guides, for example https://medium.com/@onlypiyushjain/explore-velero-for-backup-restore-postgres-sql-running-in-kubernetes-9f596e31f413.

Will close the issue

**Comment by luizcarlospedrosogomes** [comment]
@a-thaler  is being uncooperative.
