### ISSUE TITLE
Upgrade to Istio 1.1

### ISSUE THREAD

**Issue by piotrmsc** [kyma-project/kyma#1876]
Application connector needs istio 1.1 functionality, once istio will release new version we should upgrade it.

AC:

- Kyma running smoothly in all environments
- Monitoring working (all dashboards including istio ones)
- Tracing working
- check how knative will work on 1.1 and gather information if something requires bigger changes

**Comment by sjanota** [comment]
I think that this epic should also mention our integration with Knative.
