### ISSUE TITLE
Default alert rule fires for completed jobs

### ISSUE THREAD

**Issue by a-thaler** [kyma-project/kyma#1890]
The default active alert rule about not running system pods is firing for pods being in "Completed" state. As documentation an backup jobs are in that state often, a filter was added to exclude that pods by naming convention. Unfortunately, they are different pods like for testing which are not excluded and are firing now.

Please fix the rule by removing the filtering by name and instead assure that completed pods are excluded.

**Comment by Tomasz-Smelcerz-SAP** [comment]
An alert from a completed job's pod is flooding slack:
```
[FIRING:1] SystemPodNotRunning kube-state application-connector-ingress-loadbalancer-migration-gff5r (application-connector-ingress-loadbalancer-migration kube-state-metrics 10.28.2.23:8080 kyma-system monitoring-exporter-kube-state critical) (nightly.build.kyma-project.io)
@channel
kyma-system/application-connector-ingress-loadbalancer-migration-gff5r is not running
```
