### ISSUE TITLE
'Provision Service Class' form does not support regex validation

### ISSUE THREAD

**Issue by adamwalach** [kyma-project/kyma#1891]
**Description**

On the "Provision Service Class" form for "Google Cloud Storage" 
<img width="905" alt="screen shot 2018-12-03 at 09 04 40" src="https://user-images.githubusercontent.com/8530211/49364985-d9fd4d00-f6e5-11e8-9421-25f26a3f3b36.png">

the "Bucket ID" field has in the definition additional properties for validation:
<img width="605" alt="screen shot 2018-12-03 at 09 29 32" src="https://user-images.githubusercontent.com/8530211/49364646-141a1f00-f6e5-11e8-94fb-f4dd42906dc8.png">

Properties: maxLength, minLength and pattern are not supported. I was able to submit the form with values that were two characters long or contained only "/" characters

**Expected result**

The submit action should fail with a proper error message just like it does when mandatory fields are empty.

**Actual result**

Submit action of the form works and the creation process fails in next step

**Steps to reproduce**

Create new "Google Cloud Storage" service (from the GCP Broker Bundle) and try to provide incorrect values in the form.

Specification: [GoogleCloudStorage.json.zip](https://github.com/kyma-project/kyma/files/2638838/GoogleCloudStorage.json.zip)

**Comment by PK85** [comment]
ServiceBinding form as well

**Comment by derberg** [comment]
We need to clarify where fix the issue
- gcp broker and the schema definition?
- react schema lib and its dependencies?
- kyma itself

Some investigation is needed

**Comment by aerfio** [comment]
Hopefully this PR will take care of this issue: https://github.com/mozilla-services/react-jsonschema-form/pull/1130
