### ISSUE TITLE
Design install strategy for kyma event-bus on top of knative eventing

### ISSUE THREAD

**Issue by abbi-gaurav** [kyma-project/kyma#1912]
**Description**
To enable Kyma-eventing based on knative-eventing via a switch, we should define an install strategy about how this should be handled during an install.

There will some additional items to install such as
* Knative eventing
* A NATS Streaming based `ClusterChannelProvisioner`
* others..

Additionally, there might be implications on the way we currently install NATS Streaming.

> Hint: Please synchronise with team goat first  to understand how the switch works.

We need to identify any blockers based on the current switch based approach.

**AC**
* There is a proposal for the installation changes with the flow clearly documented to enable kyma eventing based on knative eventing.

Timebox - 4d

**Comment by abbi-gaurav** [comment]
Discussed the initial proposal with @marcobebway.
Following options were suggested:
* Should we consider using one NATS Streaming chart for both with and without knative-eventing?
* Should we consider moving event bus outside `core` to simplify flag based installation?
  * Have `event-bus` and `event-bus-knative` as two separate charts instead of using if conditions inside the charts?

**Comment by abbi-gaurav** [comment]
Another question to answer would be:
* If there is a non-nats provisioner, e.g. EMS based or google pubsub based, how would the installation accomodate this possibility?

**Comment by marcobebway** [comment]
@abbi-gaurav I updated the proposal accordingly. Please have a look.

**Comment by abbi-gaurav** [comment]
LGTM.
As discussed in the wg-knative, we will wait for the review from the working group that will be until  10-01-2018.
