### ISSUE TITLE
Update Kyma installation to integrate knative eventing

### ISSUE THREAD

**Issue by abbi-gaurav** [kyma-project/kyma#1915]
**Description**
The installation of Kyma should be updated to have the possibility to installation a version of kyma-eventing that is based on knative eventing.

>Note: This is driven by a feature flag.
If the feature flag is set to true, kyma eventing is based on knative eventing
else, the current flavor should be installed.

**AC**
* Kyma installation supports switching to knative eventing based on feature flag

**Comment by lilitgh** [comment]
Duplicate of #2188
