### ISSUE TITLE
Non deterministic installation.

### ISSUE THREAD

**Issue by mwilczek-net** [kyma-project/kyma#1921]
**Description**

Would be nice if local installation will be more deterministic. Especially sad is:

> Check if the STATUS column shows Running for all Pods. If any of the Pods that you require do not start successfully, perform the installation again.

**Nice to have**

Would be nice to have more deterministic installation. Or if it's problem with one (or more) dependency, please mention somewhere links to proper documentation section of problematic project or to bug reported for that project.

**Comment by tomekpapiernik** [comment]
The ultimate indicator of Kyma being installed successfully is the `is-installed.sh` script and its output. The documentation will be refactored to put more emphasis on this script, which will make the entire thing binary. The script says "Kyma is installed"? You're all good. You get an error message? Reinstall.

**Comment by piotrmsc** [comment]
Please mention that if the error is repeatable we can help you on slack or via GitHub issue
