### ISSUE TITLE
Compatibillity with minikube >= 0.28.2 not only = 0.28.2

### ISSUE THREAD

**Issue by mwilczek-net** [kyma-project/kyma#1923]
**Description**

Would be nice to be able to use newer versions of minikube, not only 0.28.2.

**Reasons**

Makes life easier (easier installation, easier reusing minikube for other project, etc.)

**Comment by piotrmsc** [comment]
We should delete version check here https://github.com/kyma-project/kyma/blob/master/installation/scripts/minikube.sh#L126 and instead, check if the provided version is different with our default and make a warning in the shell. 

- [ ] Check version deleted
- [ ] Warning displayed if you use different version then configured
