### ISSUE TITLE
Fix typo in documentation

### ISSUE THREAD

**Issue by tgorgol** [kyma-project/kyma#1932]
**Description**

In Kyma's documentation installation section, under the header "Access the Kyma console" there seems to be a typo related to unclosed code blocks.
 

**Expected result**

Correctly formatted documentation content.

**Actual result**
![Screen Shot 2018-12-05 at 13.05.52.png](https://images.zenhubusercontent.com/5c0683341a6a4c6bf4b30dab/d2628972-1085-46e2-bd9a-d5f1dccb2e3f)

**Steps to reproduce**
Go to https://kyma-project.io/docs/root/kyma#installation-installation and search for "Access the Kyma console".

**Troubleshooting**
There seems to be a typo related to unclosed code blocks.

**Comment by kazydek** [comment]
The issue was fixed and the doc image was upgraded.
