### ISSUE TITLE
Restore Windows support in 031-gs-local-installation.md

### ISSUE THREAD

**Issue by jakkab** [kyma-project/kyma#1938]
**Description**

Windows support was removed as a result of #1136 (PR #1161).

**Reasons**

Provide minimal support for Windows.

**Comment by bszwarc** [comment]
It's this doc: https://kyma-project.io/docs/root/kyma/#installation-install-kyma-locally. 
I checked what was removed in the PR, and the scripts for Windows are still available. However, the documentation based on scripts will be deprecated soon, so I don't know if there is much sense reworking it, as Kyma CLI takes over - if it does support Windows, we can mention it in the doc.
The documentation for the new installation guide featuring Kyma CLI is here: https://github.com/kyma-project/kyma/pull/4117

**Comment by joek** [comment]
Close this ticket as it will be invalid soon.
