### ISSUE TITLE
Knative contribution - make NATSS provisioner production ready

### ISSUE THREAD

**Issue by radufa** [kyma-project/kyma#1940]
This is the following step on Knative contribution after Kyma#1894 was finished and its related PR was merged.
It should make NATSS provisioner production ready, solve the reviewer comments and enhance the code coverage.

See:
https://knative.slack.com/archives/C9JP909F0/p1544081989104800
https://github.com/knative/eventing/pull/624

**Comment by abbi-gaurav** [comment]
The changes should be handled incrementally with smaller improvements. Having a generic task with undefined scope is not required.
