### ISSUE TITLE
Horizontal autoscaler for apiserver-proxy

### ISSUE THREAD

**Issue by piotrmsc** [kyma-project/kyma#1977]
**Description**
Currently, for cluster env we have hardcoded number of replicas in the apiserver-proxy which makes it idle when traffic is low. This can be improved by creating horizontal autoscaler.
Current setup [here](https://github.com/kyma-project/kyma/blob/master/resources/core/charts/apiserver-proxy/templates/deployment.yaml#L7)

**Reasons**

Hardcoded number of replicas is a bit pointless, it should be more generic. However, the autoscaler should be created only for the cluster env, on minikube we should stay with one replica.

Acceptance criteria:
- Horizontal autoscaler created for cluster environments only, minikube stays with 1 replica
- Use memory as a target metric  - `targetAverageUtilization` for example `50%`.
- Set max number of replicas, for example `3`
- Hardcoded number of replicas is deleted
- Documentation updated to reflect the current state of implementation ([this](https://kyma-project.io/docs/master/root/kyma#installation-install-kyma-locally-from-the-release-enable-horizontal-pod-autoscaler-hpa-) doc + check if there are any other references to HPA)

**Attachments**

**Comment by marouan-abbessi** [comment]
@piotrmsc you mentioned as one of the  acceptance criteria to use memory as a target metric , however if I am not mistaken, HPA based on memory is not feasible as of yet, as adding or removing pods would not trigger every pod to reduce memory consumption because this concern is related to the process that runs in the container itself .

**Comment by Demonsthere** [comment]
@marouan-abbessi @piotrmsc I have implemented the HPA on the basis of memory percentage usage (mean of current memory used divided by memory limits defined). Wether or not this metric is feasible is a matter of discussion, as from our tests this app is not heavy on cpu consumption but on memory consumption comparing it to other deployments running on kyma: 

```
NAME                               CPU(cores)   MEMORY(bytes)
apiserver-proxy-68d6d664fc-fr4tg   4m           41Mi
logging-oklog-0                                                   130m         10Mi
```

An alternative solution would be to develop a custom metric, which would need to be done as a followup task, as we would need to research what metrics we can get, and what we can calculate.
