### ISSUE TITLE
kubectl exec results in an error with console using kubeconfig

### ISSUE THREAD

**Issue by piotrmsc** [kyma-project/kyma#1989]
**Description**
When you download kubeconfig from the console and use it in the kubectl with exec, kubectl return an error with 403. 

Affected components: apiserver-proxy, RBAC

**Expected result**

User can execute `kubectl exec` command

**Actual result**

Error returned:
`Use 'kubectl describe pod/test-dan-re-proxy-service-7f66f5745d-pdb2v -n kyma-integration' to see all of the containers in this pod.
Error from server:` 

Giving bigger permissions (I have used cluster-admin role) does not solve 403 issue.
I'm not sure if it comes when trying to upgrade connection to WS

**Steps to reproduce**

Fetch kubeconfig from the console and execute kubectl exec command

**Troubleshooting**

**Comment by djumalin** [comment]
Hi, does anyone have any updates, estimations on this issue?

**Comment by piotrmsc** [comment]
Hi! no fixed dates yet but we will dig into this soon!

**Comment by tomekpapiernik** [comment]
K O P Y T K O

**Comment by tomekpapiernik** [comment]
kopytko 2: the hoof strikes back

**Comment by tomekpapiernik** [comment]
I love my PO <3

**Comment by sjanota** [comment]
Here's what we've found so far:
1. kubectl uses SPDY for some commands (like exec or port-forward)
2. apiserver-proxy does not support SPDY
3. Envoy does not support SPDY 

The plan is to:
1. Implement SPDY proxy in apiserver-proxy
2. Expose apiserver-proxy directly, without istio on secured port. Old path (unsecured) must also work as console is using it to access some resources.
3. When xip.io integration is enabled we need to generate new key and cert and propagate it to both apiserver-proxy and configrations-generator.
4. configurations-generator must be aware of new domain where apiserver-proxy is exposed.
