### ISSUE TITLE
Missing UI API Layer acceptance tests for Remote Environment queries

### ISSUE THREAD

**Issue by pkosiec** [kyma-project/kyma#1990]
**Description**

Queries for Remote Environments are not tested in UI API Layer acceptance tests.

Write acceptance tests for the following queries:
- [ ] `remoteEnvironment(name: String!): RemoteEnvironment`
- [ ] `remoteEnvironments(environment: String, first: Int, offset: Int): [RemoteEnvironment!]!`
- [ ] `connectorService(remoteEnvironment: String!): ConnectorService!`

**Comment by pkosiec** [comment]
Still valid

**Comment by derberg** [comment]
Doesn't seem like those queries exist
