### ISSUE TITLE
Unable to deploy APIs using yaml specs

### ISSUE THREAD

**Issue by joshianish** [kyma-project/kyma#200]
Confirm these statements before you submit the issue:

- [X] I have searched open and closed issues for duplicates.
- [X] I have read the contributing guidelines.
---

**Description**

I tried deploying the below yaml specs locally
```shell
apiVersion: v1
kind: Service
metadata:
  name: mkt-kyma
  namespace: stage
  labels:
    application: mkt-kyma
  annotations:
    auth.istio.io/8080: NONE
spec:
  ports:
  - name: http
    port: 8080
  type: NodePort
  selector:
    application: mkt-kyma
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mkt-kyma
  namespace: stage
  annotations:
    sidecar.istio.io/inject: "true"
spec:
  replicas: 1
  template:
    metadata:
      labels:
        application: mkt-kyma
    spec:
      containers:
      - image: acjoshi/mkt-kyma
        imagePullPolicy: Always
        name: mkt-kyma
        ports:
        - name: http
          containerPort: 8080
---
apiVersion: gateway.kyma.cx/v1alpha2
kind: Api
metadata:
  name: mkt-kyma
spec:
  hostname: playsdk.kyma.local
  service:
    name: mkt-kyma
    port: 8080
```
Unfortunately  https://playsdk.kyma.local doesn't exposes the API as expected

MacOsx, minikube deployment

**Expected result**

I'd like to see the docker image exposed via the API gateway

**Actual result**

i get an error saying: **playsdk.kyma.local is currently unable to handle this request.
HTTP ERROR 503**
**Steps to reproduce**

Just Deploy the yaml specs from Kyma Console and ensure the stage namespace is available

**Troubleshooting**

1) i tried getting inside the container using kubectl exec and ran the curl command on http://localhost:8080 to check if the application is running in the kubernetes pod which was created by kyma, i get the expected results
2) i added the host entry playsdk.kyma.local 

Regards,
Anish Joshi

**Comment by pbochynski** [comment]
I think the problem is that you have sidecar annotation in the wrong place. Look at the example:
https://github.com/kyma-project/examples/blob/c9913f44b57eec42ef8acc851de43bd0368c7e1a/gateway/service/deployment.yaml#L16-L27
The sidecar annotation is in the spec section.

Please check if pod with your service has 2 containers - one with your application and second with istio-proxy. If you have only one then your service doesn't have a sidecar and is not reachable from the gateway.

**Comment by joshianish** [comment]
Hi Piotr,

Thanks, it works now, is this a recent adjustment to the API spec, 'because i've been using this arrangement for quite sometime, however i'm not sure if the sidecar was present or not. 

Regards,
Anish

**Comment by pbochynski** [comment]
It is the change istio introduced some time ago (probably in version 0.6 or 0.8).
