### ISSUE TITLE
Consistent labelling for kyma-installer and tiller yaml

### ISSUE THREAD

**Issue by a-thaler** [kyma-project/kyma#2049]
For installation of kyma you need to apply the tiller.yaml and the configuration yamls for the installer.

To easily delete everything without keeping that yaml files stored, it will be perfect if all resources are labeled consistently. So you can delete the resources using the label selector. Furthermore, you can check for existence easily.

As an example, the kyma-installer namespace resource itself has no label at all currently.

AC:
- The resources of the configuration files provided as part of a release (see release [0.6.1](https://github.com/kyma-project/kyma/releases/tag/0.6.1) should be labeled so that:
  - the application they belong to can be easily identified
  - they can be searched for by using a selector
  - they can be deleted by using a selector
- see also kubernetes [label recommendations] (https://kubernetes.io/docs/concepts/overview/working-with-objects/common-labels/#labels)
- think of Kyma-CLI which applies the configuration files and need to clean them up later as part of an uninstall

**Comment by piotrmsc** [comment]
@a-thaler please provide acceptance criteria
