### ISSUE TITLE
kyma-installer shows wrong status while uninstallation

### ISSUE THREAD

**Issue by a-thaler** [kyma-project/kyma#2054]
I installed Kyma in version 0.5.0 using the local configuration.
At uninstallation using the kyma-installer, the status message of the installation resource is like that: `Deprovisioning Azure Broker resources`
That status stays all the time till the end of uninstallation.

It should update the status according to the real uninstallation status, the same way as in installation.

By the way, the azure broker is not installed even.

**Comment by a-thaler** [comment]
Still valid, please consider to fix it as the uninstallation feels buggy with that.

**Comment by derberg** [comment]
It is wrong now as uninstallation was/is not supported, but will be https://github.com/kyma-project/kyma/issues/2054
