### ISSUE TITLE
Refactor exec.Command() to use client-go to talk to kube-api server

### ISSUE THREAD

**Issue by sayanh** [kyma-project/kyma#2058]
**Description**

`exec.Command()` is used in the following tests:
- tools/load-test 
- tests/kubeless
- tests/kubeless-int

Assess whether accessing kube-api server using `client-go` is a better approach or not.

@mszostok, since you are leading the commons refactoring, will it make sense to refactor the use of client-go in commons to make it available for all components, tests and tools in Kyma.

**Comment by joek** [comment]
I think it the exec thing is working fine. There is no particular reason to change it.
