### ISSUE TITLE
Describe minimal recommended cluster configuration

### ISSUE THREAD

**Issue by tomekpapiernik** [kyma-project/kyma#2060]
**Description**

Add information about the minimal recommended cluster configuration for a Kyma cluster. 

**Reasons**

Such information is not included in the documentation. This topic has been recently discussed on Slack -> [CLICK](https://kyma-community.slack.com/archives/CD2HJ0E78/p1545047218051400).

**Comment by piotrmsc** [comment]
Duplicate https://github.com/kyma-project/kyma/issues/2101
