### ISSUE TITLE
Istio: enable default sidecar injection

### ISSUE THREAD

**Issue by piotrmsc** [kyma-project/kyma#2073]
**Description**

Enable default sidecar injection in the namespaces by enabling it via override : https://github.com/kyma-project/kyma/blob/master/resources/istio/values.yaml#L331
If the set up requires enabling policy then enable it in the overrides as well and ensure it's enabled in the istio patch. Remember that `kube-system` and `istio-system` should be labeled with istio injectio disabled annotation.

**Reasons**

Increase adoption of service mesh functionality by ensuring sidecar injection is possible within a given namespace. Users will not have to label any namespace but of course, will have the option to disable it by adding a label to the namespace.

**Attachments**

Acceptance criteria:

- The documentation is updated regarding sidecar injection
- Injection is ensured in `istio-kyma-patch`
- Documentation is updated :
   https://github.com/kyma-project/kyma/tree/master/components/istio-kyma-patch
   https://github.com/kyma-project/kyma/blob/master/docs/service-mesh/docs/010-istio-patch.md
   https://github.com/kyma-project/kyma/blob/master/docs/service-mesh/docs/005-details-sidecar-proxy-injection.md

**Comment by Tomasz-Smelcerz-SAP** [comment]
In addition, "knative-build" and "knative-eventing" namespaces should also be excluded from sidecar injection.
Consider adding a parametrized list of excluded namespaces as a configuration value to the namespace controller to increase the transparency of the solution.

**Comment by jakkab** [comment]
@Tomasz-Smelcerz-SAP sidecar injection in knative namespaces has been discussed with @radufa. It will remain enabled for eventing and serving, but disabled for build.
