### ISSUE TITLE
Application Description Field should be optional

### ISSUE THREAD

**Issue by obadrawi** [kyma-project/kyma#2089]
When creating a new Application you need to provide a name and a description but in testing scenarios, you don't want to provide a description every time, please could you make it optional

**Comment by kwiatekus** [comment]
The description field is required in the application CRD and in ui-api-layer.
Requires changes in the CRD and ui-api-layer.

**Comment by Szymongib** [comment]
@kwiatekus The description field is not required on CRD and I also do not think it is required in ui-api-layer. I have enabled a create button in UI manually and I managed to create Application without a description. 

Is there some case that something stops working that I am not aware of?

**Comment by derberg** [comment]
first it must be changed in CRD
