### ISSUE TITLE
Document minimal requirements for Kyma installation

### ISSUE THREAD

**Issue by SeriousSem** [kyma-project/kyma#2101]
**Description**

Trying to install Kyma in environment with insufficient resources leads to failures. To prevent such failures users must ensure that resource quota in clusters/local environment meets Kyma installation requirements. For that users must have possibility to get familiar with all Kyma installation requirements before installation starts. As for now these requirements are not listed anywhere.

Insufficient resources, for example, may lead to failures like:

> "{"ResourceType":"compute.beta.address","ResourceErrorCode":"QUOTA_EXCEEDED"
,"ResourceErrorMessage":"Quota 'STATIC_ADDRESSES' exceeded. Limit: 1.0 in
\ region europe-west1."}"

Information about requirements should be documented and publicly available.

**Comment by piotrmsc** [comment]
Right now we have removed RQ from namespaces, however, we should describe minimal machines both for GKE and Azure on which kyma can be installed.

**Comment by piotrmsc** [comment]
Please also refer to : https://docs.microsoft.com/en-us/azure/virtual-machines/windows/sizes-memory#dsv2-series-11-15
https://cloud.google.com/compute/docs/machine-types

**Comment by SeriousSem** [comment]
The failure described in this issue points to problems that occur when amount of resources required by Kyma exceed the quota available in the installation environment. 
Though the recommended machine types are documented now, other resource requirements, like static IP adresses, networks etc still missing in the documentation. Could it also be added? 
For the sake of visibility and clarity could it also be documented in a table manner?

**Comment by ormos** [comment]
From my perspective it is a valid request, that we add the other requirements to the list in the documentation.

**Comment by evilyeti** [comment]
What about the Kyma installer actually checking the prerequisites prior ot kicking off the installation? Having documentation is one part, but that does not "fix" the problem by itself.

**Comment by piotrmsc** [comment]
Kyma installer will not check resources available in the cloud provider because it is cloud provider agnostic and should remain this way. 
For sure we can add information such as  number of loadbalancers created etc.

**Comment by NHingerl** [comment]
Clarify K2.0 situation - it's probably documented now.
