### ISSUE TITLE
Support latest minikube and k8s

### ISSUE THREAD

**Issue by k15r** [kyma-project/kyma#2102]
**Description**

installing kyma using the latest minikube (0.31.0) on newer k8s (1.13.1) fails. The installer should be updated to support these up-to-date versions.

**Reasons**

on a mac its quite convenient to use brew to install 
kubernetes-cli and minikube.

using brew results in other versions than the ones currently required by kyma

**Comment by piotrmsc** [comment]
Duplicate of https://github.com/kyma-project/kyma/issues/1923
