### ISSUE TITLE
MetaDataUrl and EventsUrl are not precise in the certificate response

### ISSUE THREAD

**Issue by mcansimsek** [kyma-project/kyma#212]
Confirm these statements before you submit the issue:

- [x] I have searched open and closed issues for duplicates.
- [x] I have read the contributing guidelines.
---

**Description**
After installing Kyma successfully on the local machine, I retrieved a certificate from Kyma. However, metaDataUrl and eventsUrl endpoints are not reachable, because the port was not specified. They are accessible after defining the port. They should be represented including the port in the response while retrieving the certificate. 

![image](https://user-images.githubusercontent.com/15628751/44263921-05d0f180-a221-11e8-9617-11c76d840eb4.png)

**Comment by lszymik** [comment]
Thank you for reporting it. We will look into it.

**Comment by lszymik** [comment]
This will be resolved by migration to Istio 1.1.
