### ISSUE TITLE
Use vendored mockery in UI API Layer unit tests

### ISSUE THREAD

**Issue by pkosiec** [kyma-project/kyma#2125]
**Description**

Currently we use `mockery` for generating mock implementations for interfaces. For example:

```go
//go:generate mockery -name=gqlBackendModuleConverter -output=automock -outpkg=automock -case=underscore
```

Unfortunately, we don't mention anywhere that developer has to have this tool installed globally. This should be fixed with using vendored mockery, similiarly as we did it with gqlgen tool.

This issue also applies to
- Asset store controller manager
- Asset upload service

**Comment by kwiatekus** [comment]
already done
