### ISSUE TITLE
/v1/events Service returns json as content type text/plain

### ISSUE THREAD

**Issue by akrausesap** [kyma-project/kyma#215]
Confirm these statements before you submit the issue:

- [X] I have searched open and closed issues for duplicates.
- [X] I have read the contributing guidelines.
---

**Description**

Dear Colleagues, 
the /v1/events API of the Application Connector returns content "type text/plain; charset=utf-8" for the following content: {"event-id":"a1832d05-3892-472f-87b3-ad0e0ccb5220"}

It should be application/json.

Cluster is playground.

Cheers

Andreas

**Expected result**

Content Type application/json.

**Actual result**

Content Type text/plain; charset=utf-8

**Steps to reproduce**

Call /v1/events API of the Application Connector

**Troubleshooting**

Ignore the Response (as Spring Boot does not do deserialization as expected)

**Comment by abbi-gaurav** [comment]
@akrausesap as discussed offline with colleagues, could you please confirm If you are seeing this problem while publishing an event?

**Comment by abbi-gaurav** [comment]
Confirmed that this is indeed an issue when publishing an event.
```bash
$ echo '{"event-type" : "order.created", "event-type-version" : "v1", "event-time" : "2018-05-02T22:08:41+00:00", "data" : {"orderCode" : "1234"}}'|http POST https://gateway.kyma.local:${NODE_PORT}/ec-default/v1/events --cert=generated.pem --verify=no
HTTP/1.1 200 OK
Connection: keep-alive
Content-Length: 52
Content-Type: text/plain; charset=utf-8
Date: Mon, 20 Aug 2018 14:12:46 GMT
Server: nginx/1.15.2
Strict-Transport-Security: max-age=15724800; includeSubDomains

{
    "event-id": "e54be00c-b573-4d14-b9f7-f6fae12031b1"
}
```
