### ISSUE TITLE
Lambda function goes down for sometime after serving a request

### ISSUE THREAD

**Issue by ektajhasapcom** [kyma-project/kyma#2161]
Hi Team,

I have a created a lambda function which is triggered based on some events but it goes down for some time after serving every request.

I get the below response:
Message: upstream connect error or disconnect/reset before headers
Status code: 503 Service Unavailable

![image](https://user-images.githubusercontent.com/42619694/50684835-40dc9180-1017-11e9-8196-bb3504824ada.png)

Thanks & Regards,
Ekta Jha

**Comment by rakesh-garimella** [comment]
Hi Ekta
Can you please paste the output from `kubectl -n <namespace> logs <function pod name>` ?

**Comment by ektajhasapcom** [comment]
Hi Rakesh,

I don't have much info in my logs. It just works for fine the first request and then throws some errors internally for some functions in the lambda function for the next request. But if I wait for around 10 seconds then again everything works fine.

![image](https://user-images.githubusercontent.com/42619694/50824312-8dd1a800-1336-11e9-9f76-667abacef1d3.png)

Thanks & Regards,
Ekta Jha

**Comment by ektajhasapcom** [comment]
Hi Rakesh,

Please find the snippet of my code mentioned below:

var rimraf = require('rimraf');
var copydir = require('copy-dir');
var fs = require('node-fs');
const httpRequest = require('request-promise-native');
var exec = require('child-process-promise').exec;
var randomString = require('random-string');

module.exports = { main: function (event, context) {
     return generateVDM(event.data.metaDataUrls);
  } 
}

async function generateVDM(metaDataUrls) {
    
   var nprmcData = 'XXXXXXXXXXX';
   await writeToFile('/home/node/.npmrc', nprmcData);

   await createFile('/kubeless/edmx');
   await fs.mkdir('/kubeless/s4sdk');
   await fs.mkdir('/kubeless/s4sdk/s4sdk-vdm');
   await rimraf('/kubeless/s4sdk/s4sdk-vdm/*-service', function () {
        console.log('Deleted all service folders!');
   });
   
   await getEDMXFile(metaDataUrls);
   await executeCommands('node /kubeless/node_modules/s4sdk-generator/dist/generator.js /kubeless/edmx /kubeless/s4sdk/s4sdk-vdm /kubeless/tsconfig.json');
   await executeCommands('npm config set registry ' + `${process.env.NPM_REGISTRY}`);
   await createPackageJson('0.0.1');
   await executeCommands('npm --prefix /kubeless/s4sdk/s4sdk-vdm install /kubeless/s4sdk/s4sdk-vdm');
   await executeCommands('npm publish -f --registry ' + `${process.env.NPM_REGISTRY}` + ' /kubeless/s4sdk/s4sdk-vdm');
   
   return "VDM Generated!";
}

async function getEDMXFile(metaDataUrls) {
   writeToFile('/kubeless/tsconfig.json', '');
   await fetchAllMetadataDetailsParallely(metaDataUrls);
}

async function fetchSingleMetadataDetails(metaDataEndpoint) {
    var url = `${process.env.GATEWAY_URL}` + metaDataEndpoint;
    res = await httpRequest({url: url})
    fileName = '/kubeless/edmx/' + 'Edmx_' + randomString() + '.edmx';
    await writeToFile(fileName, res);
}

/*function to fetch the details of the different metadata urls in parallel.*/
async function fetchAllMetadataDetailsParallely(metaDataUrls) {
  var metaDataUrlArray = metaDataUrls.split(',');
  let singleMetadataDetailsPromises = [];
  for (var metaDataEndpoint of metaDataUrlArray) {
    let promise = fetchSingleMetadataDetails(metaDataEndpoint);
    singleMetadataDetailsPromises.push(promise);
  }
  let allMetadataDetails = await Promise.all(singleMetadataDetailsPromises);
}

function writeToFile(fileName, fileData) {
    fs.writeFile(fileName, fileData, (err) => {  
                    // throws an error, you could also catch it here
                    if (err) throw err;
    });
}

async function executeCommands(cmd) {
    await exec(cmd).then(function (result) {
        console.log('stdout: ', result.stdout);
        console.log('stderr: ', result.stderr);
    })
    .catch(function (err) {
        console.error('ERROR: ', err);
    });
}

async function createFile(fileName) {
   await rimraf(fileName, function () {
        console.log('Directory deleted!');
   });
   await fs.mkdir(fileName);
}

async function createPackageJson(versionNumber) {
    
    var stream = fs.createWriteStream("/kubeless/s4sdk/s4sdk-vdm/package.json");
    stream.once('open', function(fd) {
        stream.write("{\n");
        XXXXXXXXXXXXXXXXXXX
        stream.end();
    });
}

Few codes I have replaced with XXXXXXX.

Thanks & Regards,
Ekta Jha

**Comment by rakesh-garimella** [comment]
Hi Ekta

The problem here looks like you are writing a file at path: 
```js
fileName = '/kubeless/edmx/' + 'Edmx_' + randomString() + '.edmx';
await writeToFile(fileName, res);
```

But the directory `edmx/` does not exist. you might want to change the code here. Hence it fails with the error msg `Error: ENOENT: no such file or directory, open .....`
```js
await createFile('/kubeless/edmx');
```
to 
```js
await fs.mkdir('/kubeless/edmx');
```


regards
Rakesh

**Comment by ektajhasapcom** [comment]
Hi Rakesh,
I have given a try by replacing the createfile function with the below code. But still I get the same issue.
It works for the first request and then it goes down for some time and again it starts working after around 10 seconds. 

   await rimraf('/kubeless/edmx', function () {
        console.log('Directory deleted!');
   });
   await fs.mkdir('/kubeless/edmx')

Best Regards,
Ekta Jha

**Comment by ektajhasapcom** [comment]
Hi Rakesh,

If I make a call to the lambda function immediately after the first call then the command "await fs.mkdir('/kubeless/edmx')" doesn't work. And if I wait for around 10 seconds and then make a call to the lambda function it works.
I have no idea what can be the issue. 

Thanks & Regards,
Ekta Jha
