### ISSUE TITLE
Rename environments to namespaces under api-controller domain in ui-api-layer

### ISSUE THREAD

**Issue by piotrmsc** [kyma-project/kyma#2163]
As a part of renaming environments to namespaces, we have to update namespaces in api-controller domain in ui-api-layer as well.
Take a look at https://github.com/kyma-project/kyma/tree/master/components/ui-api-layer/internal/domain/apicontroller. We are referencing environments when listing APIs for exmaple.

Tests if necessary should be updated as well.

We have to keep in sync with console ui and others : service-catalog, kubeless.

AC:
- code renamed for api-controller domain
- tests refactored

Progress:
- [x] New argument on apis query
- [x] Unit tests for new functionality and backwards compatibility
- [x] Integration tests for new functionality and backwards compatibility
- [x] Images bump

**Comment by sjanota** [comment]
`ui-api-layer-acceptance` is not testing query `apis` in any way. I think in this case adding these scenarios is way too much effort as unit tests cover this pretty well. I'll skip integration tests for this endpoint.
