### ISSUE TITLE
Application proxy readme contains remote env. references. 

### ISSUE THREAD

**Issue by tomekpapiernik** [kyma-project/kyma#2169]
**Description**

The `components/application-proxy/README.md` document contains references to "Remote Environments".

**Expected result**

All "Remote Environments" references are replaced with the new name for this item - "Application".

**Actual result**

The old name for this item is still used in this document.

**Comment by lszymik** [comment]
There are indeed a couple of references in that document: https://github.com/kyma-project/kyma/tree/master/components/application-gateway
I will add it to the next sprint.
