### ISSUE TITLE
Wrong numeration of files in documentation

### ISSUE THREAD

**Issue by magicmatatjahu** [kyma-project/kyma#2175]
**Description**
Some files in the documentation have bad numbers. Look **Steps to reproduce** section.

**Steps to reproduce**

Go to https://kyma-project.io/docs/components/security#details-update-tls-certificate and see that this doc is under **Custom Resources** group of docs. This is probably caused by numeration of [this](https://github.com/kyma-project/kyma/blob/master/docs/security/docs/020-update-tls-certificates.md) file. All docs in **Custom Resources** have 11-12 numeration and described doc has 20.

**NOTE**: While repairing the numbering, it would be necessary to review the entire documentation in search of the wrong order of the docs.

**Comment by kazydek** [comment]
As part of this task also one more thing needs to be corrected. The [Overview](https://github.com/kyma-project/kyma/blob/master/docs/service-brokers/docs/001-overview-service-brokers.md) document for the Service Brokers has the **Type** metadata missing which causes Overview doc type duplication on the website.
![image](https://user-images.githubusercontent.com/40655785/50757311-2ac11200-125f-11e9-9d8b-d1243cdd848f.png)

**Comment by kazydek** [comment]
Corrected, it is just awaiting the doc image update.

**Comment by kazydek** [comment]
The doc image has been updated.
