### ISSUE TITLE
Enable deployment of publish served by Knative eventing

### ISSUE THREAD

**Issue by abbi-gaurav** [kyma-project/kyma#2189]
* Create helm charts
* Verify deployment on minikube and cluster installation.

* A service account with Knative channel object read needs to be added. (Get, List)

>Hint: Update the event service to use different publish URL based on the Knative flag.

**AC:**
* Publish served by Knative eventing is deployed when Kyma is installed with feature flag
* It should be possible to publish an event via the gateway.
* Verify on local and cluster installation.

**Comment by marcobebway** [comment]
The publish-knative app is deployed when Kyma is installed with the **knative** feature flag.
I verified using minikube that the publish flow from the event-service works correctly.
I was not able to verify on the cluster, as the build jobs does not install kyma on top of knative. The option to have knative is in the pipeline, but it does not work unfortunately.
