### ISSUE TITLE
Browser cache needs to be cleared before opening console after kyma restart

### ISSUE THREAD

**Issue by kwiatekus** [kyma-project/kyma#2203]
**Description**

After kyma restart, dex is starting fresh and regenerates new signing keys.
When user wants to open console, he sees an error in the browser console, because the key that were previously cached by the browser do not match with the new keys at dex.

<img width="1660" alt="screen shot 2019-01-09 at 09 44 40" src="https://user-images.githubusercontent.com/6783567/50901022-3ce5b080-1417-11e9-9806-e9dc6df542d3.png">

**Workaround**
Clear browser cache

**Steps to reproduce**

 - restart kyma
 - open console.kyma.local w/o clearing browser cache ()

**Comment by piotrmsc** [comment]
Create a PR to dex with a possibility to disable caching (https://github.com/dexidp/dex/blob/0d3edf24568dbbc696b4fbf3f79c4412ddae0b53/server/handlers.go#L82:2)

Describe the motivation in the PR - like the situation we currently have

**Comment by piotrmsc** [comment]
Sending request with Cache-Control disabled does not change the situation, dex still responds with cache set.

**Comment by piotrmsc** [comment]
Discussed with @kwiatekus, does not occur, closing it
