### ISSUE TITLE
Upgradeability

### ISSUE THREAD

**Issue by pbochynski** [kyma-project/kyma#2209]
The kyma installation should be upgradeable. To ensure that quality it should be tested in CI/CD. The goal is that starting from release 0.7 we can upgrade all kyma components using kyma installer.

Acceptance criteria:
- CI pipeline is created that installs the latest release, upgrades it to master branch, and run tests
- all components are upgradeable (green status of the pipeline above)

**Comment by piotrmsc** [comment]
Do we want to make an upgrade from 0.5 to 0.6 in this pipeline or test 'upgrade' aka update 0.6 to 0.6?

**Comment by sjanota** [comment]
Does it include data migration in case of CRD changes?

**Comment by pbochynski** [comment]
Clarifications:
1. We test an upgrade from 0.6 to master branch
2. The goal is to discover situations where the contract is changed and we really need data migration. It is out of scope to prepare any data migration - it will become the scope of the story which introduces backward incompatible change. We start with the upgrade from release 0.6 to master which contains pretty much the same code - no real change.

**Comment by PK85** [comment]
About further plans and actions:
- we will officially support kyma upgrade from 0.7 to 0.8
