### ISSUE TITLE
Provide Azure Broker installation at runtime

### ISSUE THREAD

**Issue by PK85** [kyma-project/kyma#2217]
**Description**

Provide Azure Broker installation at runtime. 

**Reasons**

Allow Kyma users to integrate broker in an easy way with all steps needed described in a documentation of the service class.

**Acceptance Criteria**
- Make a bundle same as we did for Google Cloud Platform Broker.
  - Make Azure Broker installed and registered in a given namespace.
  - Make documentation for Azure Broker (besides how to install bundle, update documentation pointing where is provided documentation how to activate broker service classes)
- Make sure all Azure Broker classes are well documented.
- Sync between Kyma AB and official Azure Broker repository, upgrade azure broker version if available
- Remove Azure Broker component from Kyma, remove all current installation code. 
- Contribute to Azure Broker as make Service Plans schemas better.
  - Missing titles for properties and enums in Service Plans' JSON schema are fixed in Azure Broker repository.
- in a meantime refactor GCP Broker Provider documentation and move "how to get secret" section into Overview.

**Attachments**

- Kyma GCP Broker documentation, see: https://github.com/kyma-project/kyma/blob/master/docs/service-brokers/docs/003-overview-gcp-broker.md
- https://github.com/Azure/open-service-broker-azure/issues/651

**Comment by piotrmiskiewicz** [comment]
| Subtask | PRs | 
|---------|-----|
|Create AB bundle | |
|Class documentation| |
|Remove AB from Kyma, use new bundle version| |
|Docs in Kyma about AB| |
|Enhance service plans in AB| |
|Update GCP broker docs| |
