### ISSUE TITLE
Rename environments to namespaces in the documentation

### ISSUE THREAD

**Issue by piotrmsc** [kyma-project/kyma#2223]
Documentation mentions `environments` which should be renamed to `namespaces`.

Exmaple places of occurance:

- namespace-controller component README

Acceptance criteria:

- Documentation does not refer to `environments` anymore instead uses `namespaces`

**Comment by tomekpapiernik** [comment]
The entire public documentation (kyma/docs) contains references to "Environments" which must be updated.
