### ISSUE TITLE
Unify backend and frontend naming in docs

### ISSUE THREAD

**Issue by kazydek** [kyma-project/kyma#2225]
**Description**
Update any instances of these words into either `frontend` or `backend`:
- `front end`
- `front-end`
- `back end`
- `back-end`

Change it in all `*.md` documents in the `kyma` repository and other repositories.

**Reasons**
Unify the naming convention with content guidelines.

**Comment by MAKOSCAFEE** [comment]
Hi, @kazydek I can help to work on this issue.
