### ISSUE TITLE
Integrate basic log ui to console

### ISSUE THREAD

**Issue by a-thaler** [kyma-project/kyma#2237]
We want a nice UI integrated to the console to reduce the barrier of debuggability. It should be a really quick thing to see recent logs of a pod.

AC:
- Deployment
   - new UI component will be located in console repository
   - UI component will be bundled with the logging component
- console Integration
   - console handles nicely situation where logging component is not installed
   - Navigation has a new node to show log view for the namespace 
- log frame
   - pre-filters namespace/pod
   - shows latest log or logs recent time frames
   - supports filtering by regexp

**Comment by jesusreal** [comment]
PRs in a nutshell:
Kyma: https://github.com/kyma-project/kyma/pull/2514
Console: https://github.com/kyma-project/console/pull/543
Test-infra (I): https://github.com/kyma-project/test-infra/pull/587
Test-infra (after folder renamings):

**Comment by pekura** [comment]
Console code merged to master.

**Comment by a-thaler** [comment]
The UI will be ready and integrated for 0.8 release but not deployed by default in consequence of the blocking bug.

**Comment by jesusreal** [comment]
Remaining action items:
- Enable logging microfrontend once blocking ticket is merged
- Add logging UI tests to UI tests execution in https://github.com/kyma-project/console/blob/master/tests/package.json

**Comment by a-thaler** [comment]
Looks nice, thank you :)
