### ISSUE TITLE
Display Function Controller deployment status

### ISSUE THREAD

**Issue by joek** [kyma-project/kyma#2250]
**Description**
As a Function Developer I like to know the status of my deployment to check if a deployment was successful. 

AC:
- Display the following status: DEPLOYING, UPDATING, RUNNING and ERROR
- Give Additional details about the status in a Description field

**Reasons**
AS a developer I need feedback if my deployment is working like expected to fix it if it is not working.

Hint: Something to start with: https://kubernetes.io/docs/tasks/access-kubernetes-api/custom-resources/custom-resource-definitions/#additional-printer-columns

**Comment by rakesh-garimella** [comment]
Some thing to start with: https://kubernetes.io/docs/tasks/access-kubernetes-api/custom-resources/custom-resource-definitions/#additional-printer-columns

**Comment by Abd4llA** [comment]
Fixed and available in Kyma 1.5 function controller.
