### ISSUE TITLE
Monitor Knative Function Controller

### ISSUE THREAD

**Issue by joek** [kyma-project/kyma#2251]
As a operator I like to know if my function controller is working like expected to react on issues.

AC:
- Monitoring for Functions
  - Running Functions
  - Deploying Functions
  - Deployment errors

**Comment by sayanh** [comment]
Some references:
DestinationRule: https://github.com/kyma-project/kyma/blob/master/resources/event-bus/charts/publish-knative/templates/destination-rule.yaml

ServiceMonitor: https://github.com/kyma-project/kyma/blob/master/resources/event-bus/charts/publish-knative/templates/service-monitor.yaml

A sample controller for metrics: https://github.com/kyma-project/kyma/pull/3820/files
