### ISSUE TITLE
Overridden GATEWAY_URL env variable in case of multiple service bindings

### ISSUE THREAD

**Issue by joshianish** [kyma-project/kyma#226]
Confirm these statements before you submit the issue:

- [X] I have searched open and closed issues for duplicates.
- [X] I have read the contributing guidelines.
---

**Description**

ServiceBindingUsage in deployments.

When i bind 2 service instances (which exposes GATEWAY_URL env variable) to any deployment the aforementioned env variable get overridden by the latter one.

Local Kyma installation sourced up via master branch

**Expected result**

I'd like to access the gateway urls exposed via both the service instances within the deployment Pods

**Actual result**

GATEWAY_URL env variable get overridden by the latter binding.

**Steps to reproduce**

1) Create two Service Catalog entries using https://gateway.kyma.local/hmc-default/v1/metadata/services pointing to 2 different destinations or APIs
2) Create a Service Instance and Bind it to any deployment inside your kyma installation for convenience please use the below deployment.yaml file

```shell
apiVersion: v1
kind: Service
metadata:
  name: sampleonkyma
  labels:
    application: sampleonkyma
  annotations:
    auth.istio.io/8080: NONE
spec:
  ports:
  - name: http
    port: 8080
  type: NodePort
  selector:
    application: sampleonkyma
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: sampleonkyma
spec:
  replicas: 1
  template:
    metadata:
      labels:
        application: sampleonkyma
      annotations:
        sidecar.istio.io/inject: "true"
    spec:
      containers:
      - image: acjoshi/kymagateway
        imagePullPolicy: Always
        name: sampleonkyma
        ports:
        - name: http
          containerPort: 8080
---
apiVersion: gateway.kyma.cx/v1alpha2
kind: Api
metadata:
  name: sampleonkyma
spec:
  hostname: appongateway.kyma.local
  service:
    name: sampleonkyma
    port: 8080

```

Try to read env variable from the "sampleonkyma" container

or execute "curl https://appongateway.kyma.local/hello/getGatewayURL"

**Troubleshooting**

**Comment by PK85** [comment]
hello @joshianish,

From CLI we already allow to prefix environment values by ServiceBindingUsage custom resource, see example:
https://github.com/kyma-project/kyma/blob/master/components/binding-usage-controller/docs/example.md#example

That feature will be exposed in UI in upcoming weeks.

Cheers, PK

**Comment by PK85** [comment]
duplicated by: https://github.com/kyma-project/kyma/issues/466
