### ISSUE TITLE
Migrate nats-streaming helm chart to kyma/resources

### ISSUE THREAD

**Issue by abbi-gaurav** [kyma-project/kyma#2266]
**Description**
To enable installation of Knative eventing and use nats-streaming based provisioner, the common dependency `nats-streaming` should be moved to a separate chart.

This will enable `nats-streaming` to be installed for both with and without Knative-eventing installations.

Refer https://github.com/kyma-project/community/issues/166 for the detailed design.

Note:
* Install nats-streaming in `natss` namespace
* Namespace should be created as a part of the helm chart (check `helm upgrade` should work).
* Namespace has istio-injection enabled.
* `publish` and `push` have been modified to discover nats-streaming.
* Update the installers to install nats-streaming for both local and cluster installations

**AC**
- [x] nats-streaming is deployed as a separate chart
- [x] All the installation scripts have been updated accordingly.

**Comment by montaro** [comment]
@abbi-gaurav CC: @marcobebway What's meant by 
> Namespace should be created as a part of the helm chart (check helm upgrade should work).
? Do you mean upgrading a running Kyma installation?

**Comment by abbi-gaurav** [comment]
@montaro Could you please confirm:
* if the part of do the istio label injection will be deleted as a part of  #2073?
* Any SA required for the tiller?
