### ISSUE TITLE
Upload nats-streaming provisioner images to gcr

### ISSUE THREAD

**Issue by abbi-gaurav** [kyma-project/kyma#2267]
**Description**
To enable installation on Kyma based on Knative serving and eventing, we need to have the nats-streaming-provisioner images available in the public docker registry.

>Hint : Refer [Kafka provisioner](https://console.cloud.google.com/gcr/images/knative-releases/GLOBAL/github.com/knative/eventing/pkg/provisioners/kafka?gcrImageListsize=30)

**Hint**
* Manually publish the images to kyma - gcr.
* Check with @pkosiec 
* How to access the generated image?

Image Names:
* event-bus-knative-natss-controller
* event-bus-knative-natss-dispatcher
* Tag should be the Knative eventing version from which image is created.

**AC** 
- [x] nats-streaming provisioner images are available in the public docker registry for [Kyma](https://console.cloud.google.com/gcr/images/kyma-project/EU).
  * controller
  * dispatcher
- [x] There is a document detailing out the steps needed to be performed to upload the images.

**Comment by suleymanakbas91** [comment]
Using `ko`, it is not possible to change the image name, but we can change the path. That's why Radu and I decided to go with the following images:
- `eu.gcr.io/kyma-project/event-bus/knative/natss/controller:release-03`
- `eu.gcr.io/kyma-project/event-bus/knative/natss/dispatcher:release-03`
