### ISSUE TITLE
Review Heptio Ark Setup and prepare backup Guideline

### ISSUE THREAD

**Issue by joek** [kyma-project/kyma#2272]
As a kyma developer I need to know how to integrate my resources into the backup process and testing.

AC:
- How to backup and restore resources in ark

**Comment by venturasr** [comment]
Testing backup & restore on azure ondemand cluster:

After check out that the ark server was created I ran a test.

1.- A lambda function was created on console ui. Also a service and servicebinding.
2.- The backup was created using the ark binary locally and the kubecofig of the cluster, with success status as a result.
3.- The namespace was deleted. 
4.- The restore was created using the ark binary locally and the kubecofig of the cluster, with completed status as a result. However there was an error. And the namespace and the resurces were not restored.
5.- A revision of the ark server log in the cluster did not provide any information of the error.

A secret is created in namespace, kyma-installer kyma/installation/resources/ark-secret.yaml.tpl
      
Findings about the plugin:
- Current plugins only support to restore `owner references` and serviceinstances
- New plugins needs to be added under [`/tools/ark-plugins/internal/plugins`](https://github.com/kyma-project/kyma/tree/master/tools/ark-plugins/internal/plugins)
- Think about how automate the execution of backups or add new backup item actions to the plugins, so far only ark cli is the current way of doing it.

Conclusion:
Some assistance from Michal to findout were the data is stored in Azure and if the current configuration in the right one.

Also we need to improve the plugin to include the resources to be backedup such as normal kubernetes objects and kymas's , example inserviceinstance, servicebinding, servicebindingusage, function, subscription, api, eventactivation.

**Comment by joek** [comment]
Documentation looks good so far.

**Comment by venturasr** [comment]
PR: https://github.com/kyma-project/kyma/pull/2365
