### ISSUE TITLE
Description of the installation process on gcp is not clear

### ISSUE THREAD

**Issue by adamwalach** [kyma-project/kyma#2273]
**Description**

In the documentation for the installation process in GCP (https://github.com/kyma-project/kyma/blob/master/docs/kyma/docs/032-inst-gke-installation.md#dns-setup) we have:
```
export DOMAIN={YOUR_SUBDOMAIN}
export DNS_NAME={YOUR_DOMAIN}.
export PROJECT={YOUR_GOOGLE_PROJECT}
export DNS_ZONE={YOUR_DNS_ZONE}
```
The value for `DOMAIN` is hard to guess. We suggest that this is a subdomain, but in our scripts SUBDOMAIN usually means just the prefix: https://github.com/kyma-project/test-infra/blob/master/prow/scripts/cluster-integration/kyma-gke-integration.sh#L245. 
To make it easier we should provide an example:
```
export DOMAIN={YOUR_SUBDOMAIN} #my-kyma-cluster.example.com
export DNS_NAME={YOUR_DNS_NAME}.  #example.com.
export PROJECT={YOUR_GOOGLE_PROJECT} 
export DNS_ZONE={YOUR_DNS_ZONE} #example-com
```
and change `DNS_NAME` to `YOUR_DNS_NAME`.
Additionally, the DNS_ZONE "must begin with a letter, end with a letter or digit, and only contain lowercase letters, digits or dashes", so the suggested value containing dash is needed as well.

**Expected result**

The description should clearly suggest what kind of value is expected

**Actual result**

The SUBDOMAIN may suggest that only the cluster name is required

**Comment by adamwalach** [comment]
Now we have a similar documentation about AKS. We should align both docs. Most important changes that should be made in the GCP documentation:
- move the section with env variables to the prerequisites section
- change the inline placeholders like "YOUR_EMAIL" to environment variables and add description how to set it (when we have a multiline command it's easy to miss the placeholder)
- all environment variables that are used in more than one section (step) should be mentioned in the prerequisites (it is difficult to determine what is needed to run a given command cause you have to check all previous steps - maybe a variable was set there)
-

**Comment by atakanyenel** [comment]
Another issue I found: installation to gke still refers to `--cluster-version 1.10.7` but that cluster version is not supported by GKE. I referred to AKS installation which defines cluster-version as 1.10.9 , but that version is also not supported by GKE.  

There is currently no documentation for the right parameters for a cluster in GKE.

**Comment by lszymik** [comment]
It is already done.
