### ISSUE TITLE
Support istio-certificate management using cert-manager

### ISSUE THREAD

**Issue by nexus49** [kyma-project/kyma#2293]
**Description**
To be able to have certificates automatically renewed it would be great if one could use https://github.com/jetstack/cert-manager to keep the `istio-ingressgateway-certs` certificates up2date.

Currently this secret is set by the `istio-kyma-patch` chart as part of the installer and the secret value is overwritten on install/update.

It would be great if it would be possible to adjust the installer to not overwrite this secret whenever it runs.

**Comment by nexus49** [comment]
Please add this ticket to next weeks planning.

**Comment by piotrmsc** [comment]
We will address handling of the tls certs globally in  the https://github.com/kyma-project/kyma/issues/2604
