### ISSUE TITLE
Integrate EventActivation controller with Kyma Subscription

### ISSUE THREAD

**Issue by abbi-gaurav** [kyma-project/kyma#2299]
* Creation of Subscription
  * Check if EventActivation present
  * Update the status of Kyma Subscriptions (set the EventActivation status to true).

* Creation of EventActivation
  * Update the status of Kyma Subscriptions (set the EventActivation status to true).

* Deletion of EventActivation
  * Update the status of Kyma Subscriptions (set the EventActivation status to false).

**AC**
- [x] EventActivation controller updates the status of Kyma Subscription  on its creation
- [x] EventActivation controller reacts on the EventActivation resource create and delete and updates the Kyma Subscription.
- [ ] ~~There are tests written to verify the controller behavior.~~

**Comment by abbi-gaurav** [comment]
While testing the [e2e scenario](https://github.com/kyma-incubator/examples/tree/master/kyma-local-e2e-scenario), discovered that the event-activation controller only reacted after restarting the subscription-controller pod.

I believe this needs to be investigated.

**Comment by abbi-gaurav** [comment]
The missing tests will be written as a part of #2301

**Comment by radufa** [comment]
See also https://github.com/kyma-project/kyma/pull/3118

**Comment by radufa** [comment]
The following manual tests were done:

1. create kyma-subscritption in "default" namespace
2. create eventactivation for this subscription in "default" namespace
Subscription controller reacts:
   3. it creates a knative-subscription in "kyma-system" namespace
   4. it creates a knative channel in "kyma-system" namespace

1 delete the kyma-subscription in "default" namespace
Subscription controller reacts:
   2. deletes the knative-subscription 
   3. deletes the channel subscription (cause the channel has an empty list of subscribers)

It was tested also if the first two steps are done in a different order:
1. create an eventactivation in "default" namespace
2. create a kyma-subscription in the "default" namespace
