### ISSUE TITLE
Enable deployment of subscription controller

### ISSUE THREAD

**Issue by abbi-gaurav** [kyma-project/kyma#2302]
* Create Helm charts
* Verify deployment on local and cluster installation

**AC**
- [x] Helm chart is created under `resources/event-bus/charts`.
- [x] Subscription controller is deployed when Kyma is installed with Knative flag.
- [x] The subscription controller is deployed as one replica instance.

**Comment by marcobebway** [comment]
I added the helm chart for the **subscription-controller-knative** deployment, and tested it both locally and on a GKE cluster. Also verified that it is installed only in case the **knative** feature flag is provided to the kyma installer.
