### ISSUE TITLE
Implement client certificate flow for connected applications and runtimes

### ISSUE THREAD

**Issue by lszymik** [kyma-project/kyma#2304]
**Description**

The goal of that task is to implement the flow of requesting connection URL and signing the client certificate using the newly designed API for central Connector service.

**Acceptance criteria**

-  The token with connection URL is requested using new endpoint and information about the tenant, group, and application in the headers.
- The information about `T,G,A` is stored in the cache
- The CSR is created and then signed with the Root CA
- The client certificate has all information about `T,G,A` encrypted in subject field
- The client certificate lifetime is configurable and can be set to even 5 minutes

**Comment by akgalwas** [comment]
Implementing proper CName generation and handling has been postponed to the following issues: https://github.com/kyma-project/kyma/issues/2493 and https://github.com/kyma-project/kyma/issues/2578.
