### ISSUE TITLE
Implement the GetInfo endpoint for connected applications and clusters

### ISSUE THREAD

**Issue by lszymik** [kyma-project/kyma#2309]
**Description**

The goal of that task is to implement the endpoint which returns information for the connected application and connected Kyma clusters. 

There is `management/info` described in the Central Connector service proposal: https://github.com/kyma-project/community/pull/160

The handling of the info returned together with CSR info must be updated in the scope as well.

**Reasons**

A connected application must have the possibility to get information about Kyma cluster endpoints, certificate information and more

**Acceptance criteria**

- The information about runtime URLs returned together with the CSR info for applications
- The information about  runtime URLs returned for the application (application is identified based on the client certificate)
- The above addresses are returned based on provided headers
- The information is also returned to the runtime

- The documentation created
- No breaking changes in the code
- Functionality covered with all required tests (unit, acceptance) - also for cases for central Connector service (the headers must be treated with higher priority)
- Follow up ticket created for extending E2E tests

**Comment by Disper** [comment]
We assume no common name validation at getinfo endpoint.

**Comment by franpog859** [comment]
See the implementation #2664 
See the charts and bump #2683 
See the follow up issue for documentation #2625
