### ISSUE TITLE
Create a procedure for rotation of Root CA certificate in central Connector Service

### ISSUE THREAD

**Issue by lszymik** [kyma-project/kyma#2315]
**Description**

The Root CA certificate needs to be rotated from time to time.

**Reasons**

It is due to security.

**Acceptance criteria**

- Procedure for rotation of Root CA created

**Comment by janmedrek** [comment]
To ensure that both certificates can validate incoming requests we need to disable NGINX SSL chain autocompletion, PR #2875 handles that.
