### ISSUE TITLE
Missing requirement for kubernetes version in the docs

### ISSUE THREAD

**Issue by piotrmsc** [kyma-project/kyma#2316]
**Description**

If you'd like to install kyma from the release and follow the instruction: https://kyma-project.io/docs/root/kyma#installation-install-kyma-on-a-gke-cluster
You have now information what is the minimal kubernetes version required for given release.
At github release there's no information either https://github.com/kyma-project/kyma/releases

**Expected result**

In the docs there's a requirement describing minimal kubnernetes version like it's done with minikube here https://kyma-project.io/docs/root/kyma#installation-install-kyma-locally-from-the-release

**Actual result**

**Steps to reproduce**

**Troubleshooting**

**Comment by tomekpapiernik** [comment]
Kubernetes version 1.12 added to cluster installation prereqs. in PR #2795
