### ISSUE TITLE
Gateway passes a configurable request body along the Oauth token request

### ISSUE THREAD

**Issue by vigneshkrish7** [kyma-project/kyma#2334]
Hi All,

We have a use case related to CEC integration where the oauth Authorization token require a tenantid to be passed in the body to get the specific tenants JWT token request.Currently in the registrationfile.json API we are unable to pass the body and get the token. Can this feature be added?

Sample JSON

"targetUrl": "https://sap-cec-servecwdf-dev-businesspartner-odata.cfapps.sap.hana.ondemand.com/businesspartner.xsodata/BusinessPartner",
       "spec": {
           "swagger": "2.0",
           "info": {
               "description": "API that allows creating of BP in cec"
           }
       },
       "credentials": {
           "oauth": {
             "url": "https://sap-cec-servecwdf-dev-cpaas-sctoken.cfapps.sap.hana.ondemand.com/v1/security/access-token",
             "clientId": "clientid",
             "clientSecret": "clientpassword"
         }
   }

**Postman Request:
Oauth Token Request URL**
https://sap-cec-servecwdf-dev-cpaas-sctoken.cfapps.sap.hana.ondemand.com/v1/security/access-token
Authorization :Basic 
Body : {tenantid:xyz}
Method:Post

**Description**

**Reasons**

**Attachments**

**Comment by mavraakhtar7** [comment]
Hello, 

I am working on core systems integration. Even we have this requirement to pass a body along with OAuth request. 

**Postman Request:**
**Oauth Token Request URL**
https://eu.coresuite.com/api/oauth2/v1/token
Authorization: Basic
Content-Type: application/x-www-form-urlencoded
Body: grant_type=password&username=autoscheduler_kyma_poc_eu&password=kyma2018
Method: Post

**Comment by mavraakhtar7** [comment]
Hello,

I am working on core systems integration. Even we have this requirement to pass a body along with OAuth request.

**Postman Request:**
**Oauth Token Request URL**
https://{baseurl}/api/oauth2/v1/token
Authorization: Basic
Content-Type: application/x-www-form-urlencoded
Body: grant_type=password&username={user}&password={password}
Method: Post

**Comment by janmedrek** [comment]
This functionality will be implemented by https://github.com/kyma-project/kyma/issues/6346
