### ISSUE TITLE
Improve event flow requirements doc

### ISSUE THREAD

**Issue by tomekpapiernik** [kyma-project/kyma#2341]
**Description**

[This](https://github.com/kyma-project/kyma/blob/master/docs/event-bus/docs/03-02-event-flow-requirements.md) document contains information about the Subscription CR. 

Move this information to the [dedicated CR document](https://github.com/kyma-project/kyma/blob/master/docs/event-bus/docs/06-01-subscription.md) and get rid of duplicate content (if any). 

Also
- improve the diagram
- improve consistency & wording

**Expected result**

CR-related information is aggregated in a [dedicated CR document](https://github.com/kyma-project/kyma/blob/master/docs/event-bus/docs/06-01-subscription.md). No information is duplicated and repeats between documents.

**Actual result**
 
CR information is present in a wrong doc. type. Possible content duplication.

**Comment by bszwarc** [comment]
To do:
- [ ] move information to the [dedicated CR doc](https://github.com/kyma-project/kyma/blob/master/docs/event-bus/docs/06-01-subscription.md)
- [ ] improve the diagram
- [ ] improve consistency & wording

**Comment by bszwarc** [comment]
Done.
