### ISSUE TITLE
Improvements to test clean up

### ISSUE THREAD

**Issue by akgalwas** [kyma-project/kyma#2360]
**Description**
Test clean up is not properly cleaning up Service Catalog resources. The correct way to make proper clean up is implemented in Application Binding Test (https://github.com/kyma-project/kyma/blob/master/tests/acceptance/application/suite/app_testsuite.go#L202-L210)

**Expected result**
Test should clean up all created resources.

**Actual result**
Service Instances are not deleted when the test is finished.

**Comment by derberg** [comment]
Please provide more details as it is really not clear what is the issue. So far description says something like that the issue is with the test not the underlying functionality
