### ISSUE TITLE
Test service is not cleaned after serving tests

### ISSUE THREAD

**Issue by sjanota** [kyma-project/kyma#2372]
**Description**

In Kyma there are knative-serving acceptance tests run to check if serving is running properly. There is test service defined in chart tests. Helm does not support removing anything else then pods, which causes service to stay even after tests.
 
One way to fix that would be to move creation and removal of service to code.

**Expected result**
Test service is removed after tests

**Actual result**
Test service is left

**Steps to reproduce**

Install Kyma with Knative and run tests.

**Troubleshooting**

**Comment by k15r** [comment]
fixed in the latest knative-serving-tests
