### ISSUE TITLE
Authorization doesn't work if a Lambda is exposed on APIs page

### ISSUE THREAD

**Issue by mcansimsek** [kyma-project/kyma#238]
Confirm these statements before you submit the issue:

- [x] I have searched open and closed issues for duplicates.
- [x] I have read the contributing guidelines.
---

**Description**
I exposed a lambda using the "Create API" button on APIs page. I checked the "Secure API" checkbox. 
However, the response code is "200 OK" when I call the API. 

![image](https://user-images.githubusercontent.com/15628751/44461332-b455a780-a610-11e8-8ed0-41893a9ab702.png)
![image](https://user-images.githubusercontent.com/15628751/44461347-c59eb400-a610-11e8-92a6-69aa32e06100.png)
![image](https://user-images.githubusercontent.com/15628751/44461359-d18a7600-a610-11e8-95c2-a2af15c2a150.png)
![image](https://user-images.githubusercontent.com/15628751/44461379-e535dc80-a610-11e8-9a90-fb21abe8b870.png)

On the other hand, authorization is working if I expose a lambda by selecting "HTTP - Endpoint" as a function trigger. 

**Steps to reproduce**
*Create lambda
*Expose the lambda as a secured API on APIs page 
*Call endpoint without token

**Comment by pbochynski** [comment]
I checked the issue on the release 0.4.1 and it works.
