### ISSUE TITLE
Incomplete steps in the xip.io documentation

### ISSUE THREAD

**Issue by adamwalach** [kyma-project/kyma#2403]
**Description**

The installation steps for xip.io on GKE are not complete. According to the [Installation](https://kyma-project.io/docs/root/kyma#installation-install-kyma-on-a-gke-cluster-with-wildcard-dns)  section user should:
- follow [this](https://kyma-project.io/docs/root/kyma#installation-install-kyma-on-a-gke-cluster-prepare-the-gke-cluster) section to prepare your cluster.
- create a yaml configuration file (dynamic or manual ip)
- follow [these](https://kyma-project.io/docs/root/kyma#installation-install-kyma-on-a-gke-cluster-deploy-kyma) instructions to install Kyma using the configuration file you prepared.

This will not work cause we are missing the step about building custom image.

The other issue is that according to my knowledge the flow with xip.io suppose to be a quick way to install a Kyma cluster. We could omit the step about building an image and suggest to use a version from release.

**Expected result**

As a user I'd like to install Kyma with enabled xip.io domain based on the steps described in the documentation

**Actual result**

The installation fails because version of Kyma is not set

**Steps to reproduce**

Follow the steps from documentation

**Troubleshooting**
In the my-kyma.yaml I changed
```
image: eu.gcr.io/kyma-project/develop/installer:30bf314d
```
to
```
image: eu.gcr.io/kyma-project/kyma-installer:0.6.1
```

**Comment by atakanyenel** [comment]
**This is a very important issue.** We will be using xip solution to deploy kyma from GKE marketplace & we need a deployment file that can be easily reproducible by the users. @adamwalach 's solution works but it should be documented.
