### ISSUE TITLE
Investigate upgradability issues for Event-Bus

### ISSUE THREAD

**Issue by radufa** [kyma-project/kyma#2436]
The creation of tasks should be done during the time spent for release 0.7 and the implementation, inclusive tests should be finished in Kyma release 0.8
1 td was planned for release 0.7 to make the analyses and create the tasks.

The general goal is that upgrading Event-Bus or one of its components (Event-Bus components, NATS Streaming, Knative/Eveting) should work:
- without client disruptions (blue-green deployment)
- without data loss
- without overriding custom configurations.

Event-Bus should provide “before upgrade” and “after upgrade” which will be integrated into CI 

**AC**
- [x] Any required tasks have been created.

Timebox - 3d

**Comment by radufa** [comment]
Issues related:
- Graceful shutdown and restart for NATSS provisioner:
https://app.zenhub.com/workspaces/kyma---all-repositories-5b6d5985084045741e744dea/issues/kyma-project/kyma/2607

**Comment by suleymanakbas91** [comment]
I applied these upgrade steps from Mateusz:

Here is the script which is used on CI (https://github.com/kyma-project/test-infra/blob/master/prow/scripts/cluster-integration/kyma-gke-upgrade.sh)

To make your testing environment same as on CI you need to follow the official installation of Kyma 0.6.1 release on GKE
- https://github.com/kyma-project/kyma/releases/tag/0.6.1

Then execute `docker build -t {IMAGE_NAME}:{IMAGE_TAG} -f tools/kyma-installer/kyma.Dockerfile .`, push this image to docker hub or gcr,

Next you need to remove the Installer CR
```
kubectl patch Installation kyma-installation -n default --patch '{"metadata":{"finalizers":null}}' --type=merge
kubectl delete Installation -n default kyma-installation
```
And apply new installer deployment and  installer CR from your local sources
 
```
cd installation

./scripts/concat-yamls.sh ./resources/installer.yaml ./resources/installer-cr.yaml.tpl \
                                          | sed -e 's;image: eu.gcr.io/kyma-project/.*/installer:.*$;'"${IMAGE_NAME}:${IMAGE_TAG};" \
                                          | sed -e "s/__VERSION__/0.0.1/g" \
                                          | sed -e "s/__.*__//g" \
                                          | kubectl apply -f-

kubectl label installation/kyma-installation action=install
```

However, it gets an error in the beginning and never reaches the step where our components are upgraded. It stuck in `Processing component cluster-essentials` phase and gets `Helm upgrade error: rpc error: code = Unknown desc = no CustomResourceDefinition with the name "clustermicrofrontends.ui.kyma-project.io" found`.

**Comment by radufa** [comment]
Test general planned test scenario for the investigation was:

•	deploy 0.6.1 release to a cluster 
•	create test objects/resources, verify that Event-Bus components work 
•	upgrade Event-Bus components 
•	verify that the test objects/resources still exists and that the upgraded Event-Bus still works 
•	log eventually found issues 

It was not finished, see the comments added by @suleymanakbas91
