### ISSUE TITLE
Event-Bus should support graceful shutdown for its http servers.

### ISSUE THREAD

**Issue by radufa** [kyma-project/kyma#2438]
As a part of the upgradability requirements for Event-Bus, the HTTP server used in Event-Bus components should support “graceful server shutdown”. 
Till now this is partially implemented only in Publish (version without Knative).

See also: 
https://medium.com/over-engineering/graceful-shutdown-with-go-http-servers-and-kubernetes-rolling-updates-6697e7db17cf

**AC**
- [ ] Graceful shutdown is implemented for publish-knative and events-service for handling HTTP requests.

**Comment by marcobebway** [comment]
I created two pull requests, one for the knative-publish app https://github.com/kyma-project/kyma/pull/2936, and another for the event-service https://github.com/kyma-project/kyma/pull/2939.

Once they are merged, another pull request is needed to update both event-bus and event-service deployments in kyma.

**Comment by marcobebway** [comment]
Update the event-bus and event-service versions is done here #3006.
