### ISSUE TITLE
Inconsistency in fetch token functionality

### ISSUE THREAD

**Issue by lszymik** [kyma-project/kyma#244]
Confirm these statements before you submit the issue:

- [x] I have searched open and closed issues for duplicates.
- [x] I have read the contributing guidelines.
---

**Description**

I have a lambda which is exposed over secured HTTP. I am fetching the token using `Fetch token` functionality in UI. The token is presented without the prefix `Bearer`.

The same functionality available in Service UI is returning token with the prefix `Bearer`.

**Expected result**

I would like to have the same experience using both functionalities for getting a token.

**Steps to reproduce**

- Create a lambda which is exposed
- Use the `Fetch Token` functionality

**Comment by joek** [comment]
Is fixed
