### ISSUE TITLE
event bus e2e test takes too long

### ISSUE THREAD

**Issue by piotrmiskiewicz** [kyma-project/kyma#2440]
**Description**

The event bus e2e tests contains time.Sleep(30 seconds) which makes the test time consuming.
If the process is taking time we must trying to check if it is done (retry loop). 
We must not use time.Sleep with big duration (more than few sec.). We have to use retry loop instead.

**Reasons**

Test takes too much time. Every CI build we are waiting and waiting. The 30 sec sleep is a bad pattern.

**Comment by abbi-gaurav** [comment]
We need to revisit is after migrating to Knative.

**Comment by Abd4llA** [comment]
Sleeps were removed, will close until it pops up again. (hopefully not :P )
