### ISSUE TITLE
Applying Kyma installation yaml fails on AKS

### ISSUE THREAD

**Issue by adamwalach** [kyma-project/kyma#2445]
**Description**

When I install Kyma on a AKS cluster I get an error during execution of `kubectl apply -f my-kyma.yaml` command:
```
kubectl apply -f my-kyma.yaml
namespace "kyma-installer" created
limitrange "kyma-default" created
resourcequota "kyma-default" created
customresourcedefinition.apiextensions.k8s.io "installations.installer.kyma-project.io" configured
customresourcedefinition.apiextensions.k8s.io "releases.release.kyma-project.io" created
serviceaccount "kyma-installer" created
deployment.extensions "kyma-installer" created
clusterrole.rbac.authorization.k8s.io "kyma-installer-reader" created
clusterrolebinding.rbac.authorization.k8s.io "kyma-installer" created
secret "application-connector-certificate-overrides" created
configmap "cluster-certificate-overrides" created
configmap "installation-config-overrides" created
configmap "monitoring-config-overrides" created
configmap "connector-service-overrides" created
configmap "core-overrides" created
configmap "istio-overrides" created
configmap "service-catalog-overrides" created
configmap "knative-overrides" created
Error from server (MethodNotAllowed): error when creating "my-kyma.yaml": the server does not allow this method on the requested resource (post installations.installer.kyma-project.io)
```

Reason: CRD is created before CR but when CR is installed CRD is not yet ready.

**Steps to reproduce**

This error occurs in 50% of cases. I followed this tutorial:
https://github.com/kyma-project/kyma/blob/master/docs/kyma/docs/04-05-aks-installation.md

**Troubleshooting**

To mitigate the issue I had to execute the `kubectl apply` command once again.

**Comment by piotrmsc** [comment]
In the release 1.2 we have changed a bit the installation procedure. `my-kyma` file is no longer present, cluster config files on which `sed` was executed was removed. Detailed docu here: https://kyma-project.io/docs/root/kyma/#installation-install-kyma-on-a-cluster. I didn't observe new failures. However, if it fails again with the same behavior please reopen :)
