### ISSUE TITLE
Add integration test for istio-injection

### ISSUE THREAD

**Issue by Tomasz-Smelcerz-SAP** [kyma-project/kyma#2447]
**Description**

Add an integration test for Istio injection default policy.
The test should verify the default behavior: create a Namespace, create a Pod, sidecar should be injected.

**Reasons**

We need such a test because default sidecar injection is a core feature of Kyma necessary for global mTLS to work.

**Comment by kfurgol** [comment]
@Tomasz-Smelcerz-SAP  Please adjust issue template

**Comment by Tomasz-Smelcerz-SAP** [comment]
@kfurgol Template updated.

**Comment by piotrmsc** [comment]
## Write test that will cover the following scenarios :

- Sidecar is not injected if there is a disabling label on namespace
- Sidecar is not injected if there is no label on namespace but there is a disabling label on deployment
- Sidecar is injected

**Comment by piotrmsc** [comment]
@muralov volunteered to work on this

**Comment by muralov** [comment]
currently, I am working on this task.

**Comment by piotrmsc** [comment]
We have contribution PR here for this test https://github.com/kyma-project/kyma/pull/6785
:)
