### ISSUE TITLE
Delete the istio-injection labeler Job

### ISSUE THREAD

**Issue by montaro** [kyma-project/kyma#2448]
**Description**
Remove the istio-injection labeler Job from [NATS Streaming](https://github.com/kyma-project/kyma/blob/master/resources/nats-streaming/templates/istio-label-injection.yaml) as this will no longer be required as istio sidecar will be enabled by default. 

**AC**
- [x] Sidecar injection job has been removed

**Comment by marcobebway** [comment]
This is done as part of https://github.com/kyma-project/kyma/pull/2491.

**Comment by marcobebway** [comment]
Job is deleted and tested on the nightly cluster.
