### ISSUE TITLE
Check upgradability of various components from 0.7->0.8

### ISSUE THREAD

**Issue by rakesh-garimella** [kyma-project/kyma#2454]
**Description**

Since kyma release 0.7 is officially supported we need to check upgradability for following components
* Grafana (with sqlite3)
* Prometheus
* Kubeless

**Comment by joek** [comment]
A final check has to be done as soon as the upgrade process is in place. In general there is no upgrade on one of the 3rd party components planned. So there is no extra effort needed.

As Lambda UI is simply displaying the information from kubeless a extra test for lambda UI is not needed.
