### ISSUE TITLE
Investigate upgradability issues in namespaces-controller

### ISSUE THREAD

**Issue by Tomasz-Smelcerz-SAP** [kyma-project/kyma#2477]
Description: Starting from 0.7 release we need to support upgradability. We need to make sure the upgrade process will work in case of non-breaking changes.

Test scenario:

- deploy 0.6.1 release to a cluster
- create test objects/resources, verify component works
- upgrade component according to the upgrade instructions
- verify test objects and upgraded component still works
- log issues found

**Comment by Demonsthere** [comment]
Test scenario:
**Before upgrade**
- Create a new namespace using the UI
- Check created roles, policies, annotations

**After upgrade**
- Verify if the created ns exist and has the same objects as before
- Create a new ns, check roles, policies, etc.
