### ISSUE TITLE
Investigate upgradability issues in apiserver-proxy

### ISSUE THREAD

**Issue by Tomasz-Smelcerz-SAP** [kyma-project/kyma#2478]
Description: Starting from 0.7 release we need to support upgradability. We need to make sure the upgrade process will work in case of non-breaking changes.

Test scenario:

- deploy 0.6.1 release to a cluster
- create test objects/resources, verify component works
- upgrade component according to the upgrade instructions
- verify test objects and upgraded component still works
- log issues found

**Comment by tomekpapiernik** [comment]
kopytko

**Comment by tomekpapiernik** [comment]
@piotrmsc hellO!
