### ISSUE TITLE
Investigate upgradability issues in api-controller

### ISSUE THREAD

**Issue by Tomasz-Smelcerz-SAP** [kyma-project/kyma#2479]
Description: Starting from 0.7 release we need to support upgradability. We need to make sure the upgrade process will work in case of non-breaking changes.

Test scenario:

- deploy 0.6.1 release to a cluster
- create test objects/resources, verify component works
- upgrade component according to the upgrade instructions
- verify test objects and upgraded component still works
- log issues found

**Comment by sjanota** [comment]
I've created two deployments with related services and APIs pointing at them. One of them had authentication enabled and the other one disabled. Both APIs were working as expected before and after upgrade. I'd say that api-controller can be safely upgraded.
