### ISSUE TITLE
Investigate upgadability issues in istio-kyma-patch

### ISSUE THREAD

**Issue by Tomasz-Smelcerz-SAP** [kyma-project/kyma#2482]
Description: Starting from 0.7 release we need to support upgradability. We need to make sure the upgrade process will work in case of non-breaking changes.

Test scenario:

- deploy 0.6.1 release to a cluster
- create test objects/resources, verify component works
- upgrade component according to the upgrade instructions
- verify test objects and upgraded component still works
- log issues found

**Comment by Demonsthere** [comment]
The job is executed as `"helm.sh/hook": post-install` which is omitted during upgrade

**Comment by Morriz** [comment]
I still see that the patch is NOT idempotent. It even tries to deploy multiple `istio-ingressgateway` instances, which wont work. The istio part of the installer always gets stuck afterwards and no changes can be applied...
