### ISSUE TITLE
Improve ui-api-layer acceptance tests resiliency

### ISSUE THREAD

**Issue by tgorgol** [kyma-project/kyma#2484]
**Description**

There are cases when tests get interrupted unexpectedly or it is quicker to abort tests early when it is noticed that some of them fail. At the moment, if the tests are aborted, testing namespaces are left behind and have to be manually deleted (for example using kubectl), before starting new tests.

**Expected result**

Acceptance tests should check for existing test namespaces, that might be left over after interrupted test runs, before creating them. In case of find existing namespace it should be deleted to cleanup before performing new tests.

**Actual result**

Tests can not create new namespace with the same name and fail.

**Steps to reproduce**

Interrupt tests after test namespace was created and try rerunning tests.

**Comment by derberg** [comment]
looks old and not quite importnat if noone took care of it since January
