### ISSUE TITLE
Broken link in github docs.

### ISSUE THREAD

**Issue by rakesh-garimella** [kyma-project/kyma#2487]
**Description**

The links on this page: https://github.com/kyma-project/kyma/blob/master/docs/kyma/docs/04-01-overview.md are broken. They dont redirect to right location. However when browsed through https://kyma-project.io/docs/master/root/kyma#installation-overview the links work fine.

**Expected result**

Links in github should also work.

**Comment by bszwarc** [comment]
I fixed the broken link (one was actually broken).
The reason for the links appearing to be broken in github is that we changed the linking pattern, so they work on the kyma-project.io site. 
The linking works fine there (you can check it: https://kyma-project.io/docs/master/root/kyma#installation-overview , apart from the last one - this was the fixed one) and we don't have to write where to look for information as we did in the past.
Hopefully, the github issue also will be resolved.
