### ISSUE TITLE
Support for only once provisioned bundles in UI

### ISSUE THREAD

**Issue by PK85** [kyma-project/kyma#2489]
**Description**

Support for only once provisioned bundles in Service Catalog UI. Already implemented in the Helm Broker, this ticket is about supporting that in UI.

-  Service Class Details:
  - Button `Add to your Namespace` should be renamed to `Add` and in case of classes with `provisionOnlyOnce` metadata label, the button label should be `Add once` (and if class was already provisioned, disable button)
  - In case of `provisionOnlyOnce` classes, there should be a note panel with information about the fact that class can be provisioned only once
- Service Catalog list of classes:
  - Remove `provisionOnlyOnce` label from the catalog card
  - right top corner of the card should indicate information of how many instances of a given class exist, also in case of `provisionOnlyOnce` classes, there is a permanent indicator with grey background that the class can be provisioned only once and with blue background if it is already provisioned. Make sure different text appears in tooltips in different cases
- help/tool tip text to be checked with @kazydek. For sure do not write `provided` as in designs, but `provisioned`

**Reasons**

bundle which is marked with **provisionOnlyOnce** flag, can be provisioned once in a given namespace and UI must indicate it

**Attachments**

![screen shot 2019-02-18 at 12 53 23](https://user-images.githubusercontent.com/6995927/52968016-46feb580-33ac-11e9-94c6-3f24eec3674b.png)

![screen shot 2019-02-18 at 12 53 40](https://user-images.githubusercontent.com/6995927/52968026-4cf49680-33ac-11e9-981d-85075b9cbb0a.png)

![screen shot 2019-02-18 at 12 53 49](https://user-images.githubusercontent.com/6995927/52968035-5251e100-33ac-11e9-99ba-52cd92a8f193.png)

**Comment by derberg** [comment]
So far backend supports `activated` attribute on clusterServiceClasses and serviceClasses queries

```
{
  clusterServiceClasses {
    displayName
    activated
  }
}
```

after provisioning one class it returns:
```
{
  "data": {
    "clusterServiceClasses": [
      {
        "displayName": "Azure Service Broker",
        "activated": false
      },
      {
        "displayName": "Redis",
        "activated": true
      },
      {
        "displayName": "Google Cloud Platform Service Broker",
        "activated": false
      },
      {
        "displayName": "Testing bundle",
        "activated": false
      }
    ]
  }
}
```

unfortunately for best user experience in UI, this boolean value is not enough. We want to display to the user, that tries to provision the class one more time, information about the created instance, a link to it, so we need to add a new attribute called `instances` that returns names of all the instances created from a given service class. This would be nice generic solution that could be reused in different contexts.

query
```
{
  clusterServiceClasses {
    displayName
    instances
  }
}
```

would return:
```
{
  "data": {
    "clusterServiceClasses": [
      {
        "displayName": "Azure Service Broker",
        "instances": ["redis-gleeful-opportunity","redis-dupa"]
      },
      {
        "displayName": "Redis",
        "instances": true
      },
      {
        "displayName": "Google Cloud Platform Service Broker",
        "instances": []
      },
      {
        "displayName": "Testing bundle",
        "instances": []
      }
    ]
  }
}
```
