### ISSUE TITLE
Propose new Common Name convention

### ISSUE THREAD

**Issue by Szymongib** [kyma-project/kyma#2493]
**Description**

While registering Application with Connector Service the `Common Name` of the certificate is set to name of the Application. We need to extend it with the Group name and Tenant name and also come up with some convention of the `Common Name` for the Runtime API.

**Acceptances**
- Propose proper convention of the `Common Name` returned by Connector Service
- Extend it with Group and Tenant for both Application API and Runtime API

**Comment by lszymik** [comment]
There is no time for extended proposal, therefore, we will go with a simple convention:
`tenant;group,application`
