### ISSUE TITLE
Consistent Kyma test naming

### ISSUE THREAD

**Issue by a-thaler** [kyma-project/kyma#2504]
Introduce a guide on how to name Kyma tests and apply the guide to the existing tests as outlined in proposal kyma-project/community#191

Actions:
- Have a readme in the _tests_ folder explaining the naming convention
- Link the readme in the developer guide
- Migrate _kubeless-integration_ to _e2e_ project containing e2e scenarios on a per package level resulting in one test suite to be executed.
- All folders will stay in the root _tests_ folder but will be renamed according to the following table:

| old folder | new folder | renamed/extracted | moved to folder| area |
|------------|------------|---------|--------|---|
| acceptance | integration/dex | ✅ | ✅ | security |
| acceptance | integration/service-catalog | ❌ | ❌ | service-catalog |
| acceptance | integration/application-controller | ❌ | ❌| application-connector |
|apiserver-proxy-tests|integration/apiserver-proxy| ❌ | ✅ | service-mesh |
|api-controller-acceptance-tests|integration/api-controller| ❌ | ✅ | service-mesh |
|application-operator-tests|integration/application-operator| ❌ | ❌ | application-connector |
|application-registry-tests|integration/application-registry|❌ | ❌| application-connector |
|asset-store|integration/asset-store|✅ | ❌| asset-store |
|connector-service-tests|integration/connector-service| ❌| ❌ | application-connector |
|cluster-users-test|integration/cluster-users|✅ | ✅|installation?|
|event-bus|integration/event-bus| ✅ | ❌ | - |
|gateway-tests|integration/event-service|✅|✅| knative-eventing |
|knative-serving-acceptance|contract/knative-serving|✅ |❌| - |
|kubeless-integration|e2e/kubeless|❌|✅| serverless |
|kubeless|integration/kubeless|✅|❌| - |
|logging|integration/logging|✅|✅| - |
|test-namespace-controller|integration/namespace-controller|✅(skipped, will be deleted)|✅| service-mesh |
|test-logging-monitoring|integration/monitoring|✅|✅| monitoring |
|ui-api-layer-acceptance-tests|integration/console-backend-service|✅|❌|console|

**Comment by derberg** [comment]
All the sub tickets were closed
