### ISSUE TITLE
Improve UX experience in E2E Application Connector Test

### ISSUE THREAD

**Issue by lszymik** [kyma-project/kyma#2523]
**Description**

There are potential improvements which might increase the usability of the E2E tests:

- Please add the short description of tests functionality. Everyone who is reading the README.MD file should know what is tested. It might be the bullet-point list, e.g. - Creating test lambda, - Invoking test lambda etc.
- Do we need to have `SAVEPATH` variable? Are we expecting to read something from it? If no, maybe we can store temporary data in the temporary directory? Each OS has a default location for temp file and it can be accessible with JAVA API
- Do we need to have `NODEPORT`? Maybe it can be read using Kubectl?
- Do we need to have `DOMAIN`? Maybe we can read it with `kc -n kyma-installer get cm installation-config-overrides.... `
- Maybe we should hint user how to open test results?

**Reasons**

The easiest it will be to use these tests the more chances we have that developers will use it.

**Acceptance criteria**

- Recommendation implemented or rejected and reason provided
- Documentation explaining the basic details of tests in README.MD file

**Comment by derberg** [comment]
seems to be old and invalid
