### ISSUE TITLE
leftovers after deleting lambda function and api

### ISSUE THREAD

**Issue by PavelPavlov46** [kyma-project/kyma#2550]
**Description**
Using Kyma 0.6.1 I've created a new Lambda function and exposed it via Kyma API. After that I deleted the Lambda function, which deleted also the Kyma API.

**Expected result**

I expect that all related custom resources in the cluster are cleaned up.

**Actual result**
Running kubectl -n dev get virtualservices shows me the Istio virtual service object is still in my system.

**Steps to reproduce**
0. Get the intial set of objects in your system.
1. Create new Lambda function.
2. Expose it using Kyma API
3. Delete the Lambda function
4. Check for left over objects in the system like Istio virtualservice

**Troubleshooting**

Service deleted manually.

**Comment by rakesh-garimella** [comment]
@PavelPavlov46  Could you please share the logs from `api-controller` ?

**Comment by rakesh-garimella** [comment]
@joek  Please have a look here how the desired behavior should be ?

**Comment by piotrmsc** [comment]
@PavelPavlov46 so journey1 works but problem is with journey2? in journey2 you delete k8s service from the console, right?

**Comment by PavelPavlov46** [comment]
Hey @piotrmsc , yes journey 1 is okay, the question we have is for journey 2. And yes, the API and VirtualService are kept after deleting the Kubernetes Service from the Kyma Console. The question is, if this is expected behaviour or not, because it is not consistent with the behaviour of journey 1. I don't see it as super-critical - just expected it to work the other way arround. Could be also user error/wrong expectation on my side.

**Comment by piotrmsc** [comment]
ok, then in case of journey 2 currently we do not have any info when k8s service is deleted. We have to considers using finalizers.
I will assign this issue to backlog, as this is a good improvement we could provide in the api-controller ;)

**Comment by piotrmsc** [comment]
We are creating new API gateway and garbage collection will be there already in place.
