### ISSUE TITLE
Uninstallation leaves resources

### ISSUE THREAD

**Issue by Demonsthere** [kyma-project/kyma#2554]
**Description**

Uninstalling kyma leaves some resources, which causes the next installation to fail. 
Resources in question:
- `resourcequotas "kyma-default" already exists`

**Expected result**
Uninstallation of kyma leaves the cluster in a clean state

**Actual result**
There are leftovers that block next installation

**Steps to reproduce**

**Troubleshooting**

**Comment by sjanota** [comment]
Closing as duplicate of #1826
