### ISSUE TITLE
Migrate Kyma components to Go 1.11 and Dep 0.5

### ISSUE THREAD

**Issue by michal-hudy** [kyma-project/kyma#2592]
**Description**

Migrate Kyma components to Go 1.11 and Dep 0.5

**Reasons**

Go in version 1.11 is already available for some time and it would be good to update the Kyma components. Buildpack that contains Go `1.11.4` and Dep `0.5.0` is already available: http://eu.gcr.io/kyma-project/test-infra/buildpack-golang:v20190116-69aa0a1

**Attachments**

https://github.com/kyma-project/community/pull/185

**Comment by michal-hudy** [comment]
Please take in mind that new Kubebuilder is using go modules instead of Dep.

**Comment by kwiatekus** [comment]
Duplicates #5481
