### ISSUE TITLE
Create makefile template for Kyma components

### ISSUE THREAD

**Issue by michal-hudy** [kyma-project/kyma#2594]
**Description**

Create a makefile template that will be referenced by makefiles defined in Kyma components. Example of such template is described here: https://github.com/kyma-project/community/pull/185/files

**Reasons**

To simplify the maintenance of makefiles, and unification of targets and validations we should prepare makefile template that will be referenced by makefiles defined in components.

**Attachments**

https://github.com/kyma-project/community/pull/185

**Comment by kwiatekus** [comment]
Duplicates #5481
