### ISSUE TITLE
Reference template makefile in Kyma components

### ISSUE THREAD

**Issue by michal-hudy** [kyma-project/kyma#2595]
**Description**

To have one source of makefile targets and unified validation in Kyma components, the makefile defined in the Kyma component needs to reference the template makefile.

**Reasons**

To improve development experience of Kyma components we should unify makefile targets and validations across Kyma components.

**Attachments**

https://github.com/kyma-project/community/pull/185

**Comment by michal-hudy** [comment]
It is still valid

**Comment by sjanota** [comment]
The progress is tracked here: https://github.com/kyma-project/kyma/issues/5481
