### ISSUE TITLE
Enable monitoring for event bus services

### ISSUE THREAD

**Issue by abbi-gaurav** [kyma-project/kyma#2601]
* event-service
* publish-knative

Refer 
* https://github.com/kyma-project/community/blob/master/guidelines/add-monitoring-to-component-docs.md
* https://github.com/kyma-project/kyma/issues/1916

**AC**
- [x] Functional Monitoring dashboards have been created for event-service and publish-knative
- [ ] Standard alerts for the APIs have been created based on the guidelines.

**Comment by montaro** [comment]
@abbi-gaurav @marcobebway  Where exactly can the monitoring get injected for the `event-service`, I can see its image is injected in the `application-operator`, should the monitoring enabled for the `application-operator` instead?

**Comment by abbi-gaurav** [comment]
@montaro please check with automatix.
