### ISSUE TITLE
Enable monitoring for event bus controllers

### ISSUE THREAD

**Issue by abbi-gaurav** [kyma-project/kyma#2602]
Refer 
* https://github.com/kyma-project/community/blob/master/guidelines/add-monitoring-to-component-docs.md
* https://github.com/kyma-project/kyma/issues/1800

**AC**
- [ ] Monitoring is enabled for subscription-controller (knative)
- [ ] Standard alerts for the controllers have been created based on the guidelines.

**Comment by montaro** [comment]
Subscription Controller pod organically has the Pod metrics monitors
![image.png](https://images.zenhubusercontent.com/5b865e0b83bd076dd89c9034/acbb27ed-4f10-46ae-9895-d555aa589215)
Is that enough? because there are no RED metrics for it? @abbi-gaurav
