### ISSUE TITLE
Monitoring for nats streaming

### ISSUE THREAD

**Issue by abbi-gaurav** [kyma-project/kyma#2603]
The NFRs for event bus components have been discussed internally. They will be used as a  reference.

Refer: 
https://github.com/kyma-project/kyma/issues/1879
https://github.com/kyma-project/kyma/issues/1817
https://github.com/kyma-project/kyma/issues/1818
https://github.com/kyma-project/kyma/issues/376

**Comment by marcobebway** [comment]
Initial pull request to enable monitoring for nats-streaming on grafan UI is here: https://github.com/kyma-project/kyma/pull/3077.

**Comment by marcobebway** [comment]
Initial pull request to enable monitoring for nats-streaming on grafana is here: https://github.com/kyma-project/kyma/pull/3077.
