### ISSUE TITLE
Graceful shutdown and restart for NATSS controller

### ISSUE THREAD

**Issue by radufa** [kyma-project/kyma#2605]
**Description**
As a part of the upgradability requirements for Event-Bus, the NATSS provisioner should be made upgradable without downtime (blue-green deployment). This needs to be done for both controller and dispatcher.

Note:
* Controller reacts on the lifecycle of Knative channels and subscriptions
* On receiving a KILL SIGNAL, The controller 
  * should stop acting on new events.
  * finish handling of existing events. 

**AC**
- [ ] Graceful logic has been implemented for the controller. The behavior is visible via the logs.

**Comment by Abd4llA** [comment]
This will probably need to take place on the new NATSStreaming CRD Controller. Provisioner is gone.
