### ISSUE TITLE
CI pipeline - Kyma on AKS

### ISSUE THREAD

**Issue by PK85** [kyma-project/kyma#2608]
**Description**
Last time we have checked, adjusted kyma and documented installation on AKS, see [issue](https://github.com/kyma-project/kyma/issues/2233). This issue is about providing AKS installation as a nightly plan:
- AKS is stable enough
- Kyma is still able to be installed 

**Acceptance Criteria**
- we should go with new subscriptions created in Azure only for that case. They will be only for internal use and we will see nicely costs.
- enable AKS cluster installation and cleanup
- provide nightly pipeline and notifications (clearly separate GKE and AKS notifications). Assure same commit on GKE and AKS nightly.

**Comment by jasiu001** [comment]
Reffering to this [issue](https://github.com/kyma-project/kyma/issues/2873) all notification about errors directly come from cluster  are disabled. 
The right note is added to [code](https://github.com/kyma-project/test-infra/blob/master/prow/jobs/kyma/kyma-integration.yaml#L532).
After bump version of `prometheus-operator` the value of `KYMA_ALERTS_CHANNEL` can be restore to its proper value.

**Comment by PK85** [comment]
New issue should be tracked, https://github.com/kyma-project/kyma/issues/2926 to solve notification issue
