### ISSUE TITLE
Support for additional headers and query parameters in App Registry and Proxy service

### ISSUE THREAD

**Issue by lszymik** [kyma-project/kyma#2617]
**Description**

There are the various systems which require additional headers. A good example is a support for `X-ApplicationKey` header.

The headers might be sent with calls to authorization endpoint and/or might be sent with calls to registered API.

**Reasons**

There are APIs which are protected with additional headers, not always according to standards.

**Acceptance criteria**

- The API for adding headers and query parameters to auth endpoint and API added.
- The functionality implemented and tests provided.
- The documentation updated.

**Recommendation**

```
...
"api": {
    "targetUrl": "https://honeybadgers-testing.hybris.com/rest/v2",
    "credentials": {
      "basic": {
        "username": "user",
        "password": "pass"
      },
      "headers" : {
          "X-Application-Key" : "1234"
      },
      "queryParameters" : {
          "q1" : "value"
      }
    },
    "headers" : {
          "X-Application-Key" : "1234"
      },
      "queryParameters" : {
          "q2" : "value"
      }
      ...
```

Highlights:
- If any query parameter or a header is also sent as a call to the proxy, then it has a higher priority
- Also in case of `Authorization` headers - client credentials flow

**Comment by brendandobbs** [comment]
@lszymik , will it also be possible to use headers and query parameters without providing credentials? In some cases the headers with be providing parameters for authentication so the crendentials are not needed.

**Comment by lszymik** [comment]
@brendandobbs , yes we will also have support for headers and query parameters without credentials.
