### ISSUE TITLE
Proxy service with additional authentication capabilities

### ISSUE THREAD

**Issue by lszymik** [kyma-project/kyma#2618]
**Description**

The integration with various systems is crucial for Application Connectivity capability in Kyma project. There is a need to support additional authentication methods in Application Connector - Proxy service.

The scope of the epic is to provide the support for:
- OAuth client credential grant flow
- Additional headers and query parameters for calls to an authentication server or connected API

**Reasons**

Increasing the support of security mechanism

**Attachments**

- Features implemented
- Delivery with documentation
- Everything tested accordingly

**Comment by akrausesap** [comment]
Hi Lukasz,
please also add support for query parameters.
Regards
Andreas

**Comment by lszymik** [comment]
Hello @akrausesap ,
Yes, it is captured in 2617 which is also in the same Epic. I missed it in overview description.
I will update immediately.

Thanks a lot for spotting it.
Cheers
Lukasz

**Comment by lszymik** [comment]
The scope is limited for 0.8 release. There will be only support for OAuth implemented (client id and client secret in Authorization header)
