### ISSUE TITLE
Review the 99 percentile threshold for alerts (weekly cluster)

### ISSUE THREAD

**Issue by y-kkamil** [kyma-project/kyma#2622]
**Description**

Currently, the ci-force slack channel is being bombarded with ```APIServerLatencyHigh apiserver (https 35.246.243.33:443 default 0.99 pods namespace kubernetes critical POST) 
the API server has a 99th percentile latency of 8 seconds for POST pods```-like messages all the time, even though the cluster is working properly. It's probably due to the fact that the rule triggering alert might be too sensitive.

**Reasons**

As discussed with @sayanh, the threshold might be revisited, to decrease the number of unnecessary alerts cluttering the channel up.

**Attachments**

![screen shot 2019-02-06 at 13 49 38](https://user-images.githubusercontent.com/13983249/52342641-4104ee00-2a16-11e9-966d-9bec368c56db.png)

**Comment by aszecowka** [comment]
@joek I was trying to find a Grafana dashboard to see that there were 8 seconds of latency for making POST on pods but I was not able to find it, can you guide me where should I look for?

**Comment by aszecowka** [comment]
I found out another issue:
On cluster we have 3 nodes , one of them was not ready, and following notifcation was sent:

<img width="626" alt="screenshot 2019-02-08 at 08 49 50" src="https://user-images.githubusercontent.com/476407/52465705-d53e9480-2b7f-11e9-8e0e-af9cac3c2960.png">

```
kubectl get nodes
NAME                                    STATUS     ROLES    AGE   VERSION
gke-weekly-default-pool-5ed122dd-4wpl   Ready      <none>   2d    v1.11.6-gke.6
gke-weekly-default-pool-5ed122dd-brtn   NotReady   <none>   2h    v1.11.6-gke.6
gke-weekly-default-pool-5ed122dd-l563   Ready      <none>   2d    v1.11.6-gke.6
```

**Comment by joek** [comment]
@aszecowka I will check which dashboard (or if we have to build one).

For the nodes issue we have to check with gcp if we can do anything about it. If required we can increase the timeout but a NotReady Node is an issue we have to react on I would suppose.

**Comment by aszecowka** [comment]
@joek I forgot to mention that the message is invalid that 2% of nodes are not ready, should be rather 33%

**Comment by joek** [comment]
@aszecowka Should probably be >2% of nodes.

**Comment by sayanh** [comment]
This a follow up task on API Server latency https://github.com/kyma-project/kyma/issues/2829
