### ISSUE TITLE
Documentation for central Connector Service

### ISSUE THREAD

**Issue by lszymik** [kyma-project/kyma#2625]
**Description**

The central Connector service proposed here https://github.com/kyma-project/community/pull/160

**Reasons**

- The changes and enhancement must be documented
- The scope includes also the procedures which are required (like certificate rotation)

**Comment by akgalwas** [comment]
I think we should cover the following topics:
- general architecture : one global cluster with Connector Service deployed and separate clusters with Kyma installed
- using management/info with differentiating the case Kyma cluster in up or not yet ready
-  client certificate renewal
- client certificate revocation

**Comment by tomekpapiernik** [comment]
Remember about the `GetInfo` endpoint.
