### ISSUE TITLE
Externalize component specific config outside of the tests

### ISSUE THREAD

**Issue by marcobebway** [kyma-project/kyma#2627]
**Description**

Currently, if we want to configure our tests differently, we would have to release new docker images, and then update our deployments to include the new produced tests docker images. Instead, we can externalize any component specific config outside of the tests and expose them via helm charts.

**Reasons**

This should make configuration related changes easier and quicker as changes in helm charts will directly be reflected in the test deployments without the need to reproduce new docker images.

**Example**

In the [test-kubeless.go](https://github.com/kyma-project/kyma/blob/master/tests/kubeless-integration/test-kubeless.go) file, the function **publishEvent** is internally using a hardcoded publish url. And changing that URL requires releasing a new docker image for the test, and then update kyma tests the new image tag.

https://github.com/kyma-project/kyma/blob/22589819ce93a729e73c32500d9fedaf83625058/tests/kubeless-integration/test-kubeless.go#L387

**Comment by Abd4llA** [comment]
Test will be deprecated with Kubeless deprecation.
