### ISSUE TITLE
Inject configuration required for tests via helm charts

### ISSUE THREAD

**Issue by marcobebway** [kyma-project/kyma#2628]
**Description**

Currently, in the [e2e-tester.go](https://github.com/kyma-project/kyma/blob/master/tests/event-bus/e2e-tester/e2e-tester.go) we are expecting some configuration params for the tests, but in our helm deployment we are not using them, which make us release new docker image if we changed these configurations.

**Reasons**

This should make configuration related changes easier and quicker as changes in helm charts will directly be reflected in the test deployments without the need to reproduce new docker images.

**Example**

In the e2e-tester.go file, the test expects the **publish-event-uri** argument to be passed to it, but it is not used in the test deployment chart **test-e2e-tester.yaml**, which makes the tests to always use the default hardcoded url value.

**Comment by Abd4llA** [comment]
Fixed
