### ISSUE TITLE
Stability checker sends message with incorrect kubectl command

### ISSUE THREAD

**Issue by aszecowka** [kyma-project/kyma#2630]
Stability checkers sends slack notification that contains command which shows how to display pretty-printed logs from test executions:
```
kubectl exec -n kyma-system stability-checker-5ff4d74b98-kddww -- logs-printer --ids=9f3ec0b1-dce6-4e12-a78c-30f0cc6b5259
```
Unfortunately, when a developer uses `kubeconfig` downloaded from Kyma console this command will fail - `kubectl exec` requires port forward and `kubeconfig` downloaded from the console forbid it.

Instead of using `kubectl exec ... logs-printer` we can suggest fetching logs using `kubectl logs` and pipe it to `jq` to format it, and filter by test executions id's

**Comment by jasiu001** [comment]
Command which can replace `exec` could be:
```
kubectl logs kyma-system stability-checker-5ff4d74b98-kddww stability-checker | jq -s '.[]| select(.log."test-run-id" == "9f3ec0b1-dce6-4e12-a78c-30f0cc6b5259")' | jq -r '.log.time + " " + .log.message'
```
