### ISSUE TITLE
Create a test runner for acceptance tests that replace helm test

### ISSUE THREAD

**Issue by aszecowka** [kyma-project/kyma#2639]
Currently, we use helm test for running acceptance tests. Such an approach has many drawbacks. Running integration tests on GKE takes in average 23 minutes. Locally it takes 18 minutes. There is no easy way to run tests selectively. There is no easy way to run only failed tests. There is a possibility to run tests concurrently, but we cannot limit the number of running test pods at the same time. 

Because Helm test has a very limited number of features, we should create a library for running acceptance tests. Such a library eventually should have the following features:
- execute all tests
- execute only a subset of tests. For example, I want to run only tests for Service Catalog. This can be especially useful for local development.
allow executing tests concurrently. Concurrency level (number of tests executed concurrently) should be configurable. Thanks to that IMO we can reduce test execution time twice or even threefold. It means that every developer can save 10-15 minutes on every PR that requires running integration tests.
- allow retrying only failed tests. Flaky tests are an everyday reality. Definitely, we should strive to improve tests and make them stable, but we should accept that they will exist. IMO it will be beneficial to retry only failed tests automatically on Prow integration jobs. Thanks to that, PR author does not have to retrigger tests manually, a new cluster does not have to be provisioned etc.
- allow running given test many times. This can be helpful when a developer adds a new test and he/she needs to validate if a test is stable or he wants to reproduce a problem that sometimes occurs on CI.
- there is a CLI that allows easily create test executions

**Acceptance Criteria**
- In the first iteration we should provide the same functionality as helm test provided:
  - executing all tests
  - providing logs from tests
- inform sig-production about a concept and current status
- in case of success and full transparency merge into master
- check all places where testing.sh is used (for example stability checker)
- CLI support stretch

Library probably should be placed in the kyma-incubator.

**Comment by PK85** [comment]
Things to consider:
- define CRDs, decide how to register them
- helm chart, new module
- how to store logs, find a way how to manage pods termination (logs aspect)
- 

-

**Comment by aszecowka** [comment]
Tasks: 
[ ] bootstrap project according to kyma project structure: https://github.com/kyma-project/community/blob/master/guidelines/internal-guidelines/repository-template/README.md
@aszecowka 
[ ] Define prowjobs
[ ] Define CRDs
[ ] Implement the simplest solution
