### ISSUE TITLE
Service-Catalog does not refresh authorization data from a secret

### ISSUE THREAD

**Issue by piotrmiskiewicz** [kyma-project/kyma#2641]
**Description**

The broker controller in the Service-Catalog does not refresh sedcret with authorization data (for example basic auth). This may cause an error, when the secret with credentials is changing, for example in GCP broker 

**Expected result**

Service Catalog refreshes authorization data when it is changed

**Actual result**

Service Catalog does not refresh authorization data from time.

**Steps to reproduce**

Install service broker with basic auth stored in a secret. Provide wrong credentials, then update the secret with valid credentials. Service Catalog still cannot fetch the catalog.

Related: https://github.com/kubernetes-incubator/service-catalog/issues/2563

**Comment by PK85** [comment]
Issue has been fixed.
