### ISSUE TITLE
Attach kyma dependencies to kyma releases/pre-releases

### ISSUE THREAD

**Issue by nexus49** [kyma-project/kyma#2644]
Background
To be able to provision a kyma environment with the corresponding dependencies of a respective kyma version it is required to understand the needed version of certain components. 

Examples for components are kubernetes version, helm/tiller versions

Proposal
To be able to consume and prepare such component versions automatically it would be helpful to attach a file to the release that describes these version constraints on a certain release.

A version should be defined in a way that future patch versions can also be accepted if supported.

For example:

requirements.yaml
```
kubernetes: 1.10
tiller: 2.10.0
```

**Comment by nexus49** [comment]
I think it could be an idea to start with the following dictionary:

```
"latest": picks the latest version
"X": picks the highest valid  minor version
"1.X": picks the highest valid  patch version
"1.X.Y": picks the exact minor and patch version 
```

**Comment by piotrmsc** [comment]
Comment from @nexus49 : 
``` kubernetes please leave out the patch version, as gke deprecates patch version relatively quickly```

**Comment by piotrmsc** [comment]
Additionally the file should be present in the sources (in the same format),  kyma cli may use it in the future.
Requirements should be attached as a file to github release. Documentation will be covered in https://github.com/kyma-project/kyma/issues/2316

**Comment by sjanota** [comment]
I suggest using same style as [npm does](https://semver.org/). There are plenty of libraries to help, like the one in go: https://github.com/Masterminds/semver
