### ISSUE TITLE
Enable Grafana for Loki

### ISSUE THREAD

**Issue by a-thaler** [kyma-project/kyma#2650]
Correlation of metrics with logs is a brand new feature of grafana 6.0 introducing Loki as a data source for logs, see also the new explore section: http://docs.grafana.org/features/explore/

Loki is supported only with grafana 6 and we need to update the bundled version.

AC:
- kyma monitoring module bundles a grafana version >= 6.0.0-beta1
- explore section is enabled
- Loki is enabled as logging datasource so that logs of a pod work out of the box
- If kyma logging module is not installed, grafana will not crash
- everything works as before, especially bundled dashboard configurations and servicemonitor definitions#
- To Demo Display logs as part of Lambda Dashboard

**Comment by rakesh-garimella** [comment]
We need to have this issue resolved to be able to use loki with security: https://github.com/kyma-project/kyma/issues/2623

**Comment by rakesh-garimella** [comment]
We need to resolve the istio authorization rule issues that being handled by #2623. @hisarbalik  is currently looking into it. Once its resolved we need to add grafana into authorization rule so that it can access Loki service.
