### ISSUE TITLE
Provide an local upload service for asset store

### ISSUE THREAD

**Issue by derberg** [kyma-project/kyma#2653]
**Description**

- provide simple upload service as asset store feature
- it cannot be accessed from outside of the cluster
- it should be possible to send a file as multipart with REST
- it should be possible to specify if upload is private or public
- upload service should have `system` buckets, private and public that are added by default without usage of Bucket CRD:  `temp-pub-hash` + `temp-priv-hash`
- prepare charts/subcharts
- docs with swagger

**Reasons**

- for development reason you would like to have a temp upload service so you do not have to host files for asset store externally
- there are use cases for application connector, that it has to fetch some spec for us and store in temporary location as original files is hidden behind authorization

**Comment by mjasinski5** [comment]
To finish this task, this bug: https://github.com/kyma-project/kyma/issues/2560 needs to be resolved.

**Comment by sjanota** [comment]
@mjasinski5 #2560 is not a bug per se, it's rather lack of documentation (see [comment](https://github.com/kyma-project/kyma/issues/2560#issuecomment-463593023)). Do you still find it as a blocker?

**Comment by michal-hudy** [comment]
@sjanota I have read the comment added by @Demonsthere, so now it looks like it is not a blocker 😄
