### ISSUE TITLE
Cluster-wide resources in Asset Store

### ISSUE THREAD

**Issue by derberg** [kyma-project/kyma#2655]
**Description**

* have ClusterAsset and ClusterBucket
* bucket name should consist of CR name and generated hash to assure uniqueness of buckets in setup of GCS where buckets are unique globally
* of course these CRDs play only with each other, not possible to have an Asset that is stored in ClusterBucket or ClusterAsset that is stored in the Bucket
* I suggest the bucket name for ClusterAsset is simply a name of CR, we do not need specific pattern for name like in case of namespace version of Bucket CR
* you probably need to have some `blacklist` of reserved buckets here because of the `system` buckets https://github.com/kyma-project/kyma/issues/2653. Other solution would be to have some specific prefix for the `system` buckets, but this is also not perfect solution, not bulletproof anyway as we have legacy `content` bucket that still has to work. So better have configurable (env driven) list of blacklist buckets and controller could nicely inform user that specific bucket fails as the name is not allowed (long term we could have some nice ValidationWebhook admission controller that would not even allow CR creation -> but I don't think it is really a must) 
* docs

**Reasons**

* there are use cases where you need to have a cluster wide assets https://github.com/kyma-project/community/blob/master/sig-and-wg/sig-core/proposals/new-architecture-docs.md

**Comment by mjasinski5** [comment]
To finish this task, this bug: https://github.com/kyma-project/kyma/issues/2560 needs to be resolved.

**Comment by sjanota** [comment]
@mjasinski5 #2560 is not a bug per se, it's rather lack of documentation (see [comment](https://github.com/kyma-project/kyma/issues/2560#issuecomment-463593023)). Do you still find it as a blocker?

**Comment by michal-hudy** [comment]
@sjanota I have read the comment added by @Demonsthere, so now it looks like it is not a blocker 😄
