### ISSUE TITLE
Write a blogpost about links

### ISSUE THREAD

**Issue by mjasinski5** [kyma-project/kyma#2686]
AC:
- write a technical blog post in https://kyma-project.io/blog that explains:
  - how we made kyma-project organization a `broken links free` org
  - what tools do we use here
  - how we solve issued of:
    - broken links in product documentation
    - relative vs absolute
    - broken links in readme
    - pipeline setup strategy to not annoy PR creators (what we check on PR level and what on nightly builds)

**Comment by derberg** [comment]
Not valid for now
