### ISSUE TITLE
Enable graphql subscriptions in ui-api-layer for a number of types

### ISSUE THREAD

**Issue by derberg** [kyma-project/kyma#269]
Confirm these statements before you submit the issue:

- [x] I have searched open and closed issues for duplicates.
- [x] I have read the contributing guidelines.
---

**Description**

- Make sure `serviceInstanceEvent` works
- Once https://github.com/kyma-project/kyma/pull/180 is completed we need to add one parameter to UI API Virtual Service definition: `websocketUpgrade: true`
- Add 2 new subscriptions for ServiceBinding and ServiceBindingUsage that we will use in views where these resources are listed and their statuses exposed, in the ServiceInstance details view
- Acceptance tests for subscriptions

**Reasons**

Backed must support websockets to enable UI to do realtime updates of changes in the resources, like their status changes

**Comment by mjasinski5** [comment]
Review: @pkosiec @akucharska
