### ISSUE TITLE
Apply Fiori Fundamentals to component renderers using generic list

### ISSUE THREAD

**Issue by marynaKhromova** [kyma-project/kyma#2691]
Update console core components that use renderers from generic list. 
- plain list component (uses .fd-panel-grid)
- plain table component (uses .fd-table)

**Comment by parostatkiem** [comment]
Already done by https://github.com/jesusreal/console/pull/52

**Comment by maxmarkus** [comment]
Nope, it is about the opposite side .. all the component renderers, that need to be updated to the new generic-list dom structure.

**Comment by parostatkiem** [comment]
After contacting @marynaKhromova it looks like this task is just about tables in *details* view, e.g. Services details.

**Comment by parostatkiem** [comment]
PR: https://github.com/jesusreal/console/pull/57
