### ISSUE TITLE
API-controller: Extend validationStatus with error description

### ISSUE THREAD

**Issue by jakkab** [kyma-project/kyma#2693]
**Description**

Transform ValidationStatus (type statusCode int) into a struct with two fields: statusCode and error description.

Result of #1518 

**Reasons**

Better error handling and logging.

**Comment by piotrmsc** [comment]
I think we should change current status in API CR. Instead of keeping status code (which is not meaningful) we should have flag indicating an error and a description. If the status code is used somewhere internally, it should remain internal.

**Comment by piotrmsc** [comment]
New gateway controller is developed with status codes and descriptions in place. Closing this issue
