### ISSUE TITLE
API-controller: introduce a blacklist of K8s services

### ISSUE THREAD

**Issue by jakkab** [kyma-project/kyma#2694]
**Description**

We should have a blacklist of K8s services.

**Reasons**

API-controller should not create APIs for some services (e.g. `kubernetes`).

**Comment by piotrmsc** [comment]
Provide list of blacklisted services in env in format : "service.namespace" ie. "kubernetes.default"

**Comment by piotrmsc** [comment]
@strekm Where I can read about it? https://kyma-project.io/docs/components/api-gateway/#overview-overview does not mention what is blacklisted by default
