### ISSUE TITLE
Local installation only works on macOS

### ISSUE THREAD

**Issue by musse** [kyma-project/kyma#27]
Confirm these statements before you submit the issue:

- [x] I have searched open and closed issues for duplicates.
- [x] I have read the contributing guidelines.
---

**Description**
Local installation [requires the Hyperkit driver for Minikube](https://github.com/kyma-project/kyma/blob/master/docs/kyma/docs/031-gs-local-installation.md#prerequisites), which is [only supported on macOS](https://github.com/kubernetes/minikube#requirements).

OS: Ubuntu 16.04
Minikube version: 0.28.0

**Expected result**

I expect the local installation script to work with at least one Minikube driver supported on Linux.

**Actual result**

```
$ cmd/run.sh 

################################################################################
# Minikube setup with driver hyperkit
################################################################################

Parsing DEX TLS certificate secret...
Saving DEX TLS certificate in the container file: /home/username/.minikube/files/dex-ca.crt...
DEX TLS certificate saved in the container: /home/username/.minikube/files/dex-ca.crt
Starting local Kubernetes v1.10.0 cluster...
Starting VM...
F0726 10:27:51.645246   28633 cluster.go:212] Unsupported driver: hyperkit
```

**Steps to reproduce**

Run local installation script on Linux.

**Comment by musse** [comment]
@dongsupark did you manage to get Kyma running on Linux? If yes, could you please share your environment (distro, kubectl and minikube version, minikube start flags)?

**Comment by dongsupark** [comment]
@musse Yes I installed Kyma on Linux, and it seems to work.

* Distro: Fedora 28
* kubectl v1.10.0
* minikube v0.28.0
  * there's no start flag given
  * vm driver: Virtualbox
* ~/.minikube/config/config.json:
```
{
    "WantReportError": true,
    "cpus": 4,
    "memory": 4096,
    "registry": true
}
```
