### ISSUE TITLE
Create list of all ServiceCatalog api-server custom features

### ISSUE THREAD

**Issue by mszostok** [kyma-project/kyma#2703]
**Description**

We need to remove the Service Catalog `api-server` and replace it with the CRD 
functionality. To do that we need to check the api-server and find all customization. Create a list of them and prepare scenario how they can be addressed by the CRD concept.

Create follow-up tickets for all found customization, like replacing the api-server plugins with proper mutation/validation webhooks.

All restrictions should be documented (e.g. requirement of using the K8s in version 1.11 or higher) and discussed if it's acceptable or not.

Here we also should have the Service Catalog without api-server which is supporting basic scenarios.

**AC**
- all customization of Service Catalog api-server are detected
- follow-up tickets for implementing found customization with CRDs are defined
- Service Catalog is working with CRD with minimal scope

**Comment by mszostok** [comment]
### Findings

- api-server is using [TableConvertor](https://github.com/kubernetes-incubator/service-catalog/blob/master/pkg/registry/servicecatalog/binding/storage.go#L143) for printing custom columns on `kubectl get`.
  ```
  $ kc get serviceinstances
  NAME      CLASS                       PLAN      STATUS    AGE
  redis     ClusterServiceClass/redis   micro     Ready     4h
  ```
  This can be replaced with the [additional-printer-columns](https://kubernetes.io/docs/tasks/access-kubernetes-api/custom-resources/custom-resource-definitions/#additional-printer-columns) defined on CRD. There can be only one problem with the **STATUS** column, read [this](https://github.com/kubernetes/kubernetes/issues/67268) and [this](https://github.com/jetstack/cert-manager/pull/1194) to find more info.

- controller-manager is using the [status-subresource](https://kubernetes.io/docs/tasks/access-kubernetes-api/custom-resources/custom-resource-definitions/#status-subresource) on all ServiceCatalog resources. This can be resolved by adding
  ```
  subresources:
    status: {}
  ```
  to do CRD definition. This [functionality](https://kubernetes.io/docs/concepts/extend-kubernetes/api-extension/custom-resources/#advanced-features-and-flexibility) requiries k8s at least in version 1.11. Currently this feature is in beta. Current desing status can be found in [this](https://github.com/kubernetes/enhancements/issues/571) issue.

- controller-manager is using the `FieldSelector`. This future is not supported for CRD. You can query only by `name` and `namespace`. [Here](https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apiextensions-apiserver/pkg/apiserver/customresource_handler_test.go#L40) is the k8s tests documenting that contract. 

  > Using a field selector to look up a single object in a list is _extremely_ inefficient today. We'd likely need a way to build indexes before supporting that query pattern across all objects (especially across namespaces)

  source: [Issue about generic fieldSelector](https://github.com/kubernetes/kubernetes/issues/1362#issuecomment-359655892)

  Based on that comment, maybe the `FieldSelector` should be replaced with proper indexer for particular informer. Or if we do not want to do that, then we can use the `LabelSelector` and decorate the resource with additional labels, e.g.:

  `service-catalog.k8s.io/spec.clusterServiceBrokerName`: **helm-broker**

  It's redundant because you have this information under spec and also in labels but e.g. [Prow is using this approach](https://github.com/kubernetes/test-infra/blob/master/prow/pod-utils/decorate/podspec.go#L77).

**Comment by MHBauer** [comment]
I shouted some things out in a Svc-Cat meeting. Can't find the recording. Were there any other questions? @jberkhahn
