### ISSUE TITLE
Add Prow badge

### ISSUE THREAD

**Issue by mjasinski5** [kyma-project/kyma#2718]
**Description**
Add Prow badge to the Kyma repository.

**Reasons**
It would be really nice to have prow CI status badge in Kyma. Unfortunately according to this issue: https://github.com/kubernetes/test-infra/issues/9628 its not possile ATM as the badge is bugged and doestn show the status properly.

**Attachments**

**Comment by crabtree** [comment]
@mjasinski5 isn't it a duplicate for https://github.com/kyma-project/test-infra/issues/355

**Comment by mjasinski5** [comment]
yes it is indeed 👍 I will close this one!
