### ISSUE TITLE
Tutorial how to register a broker in the service catalog is flaky one

### ISSUE THREAD

**Issue by PK85** [kyma-project/kyma#2720]
see: https://kyma-project.io/docs/master/components/service-catalog#tutorials-register-a-broker-in-the-service-catalog

Issue is that first point with service catalog checkout has a master version, that every day could be refactored, buggy etc.

ToDo:
- checkout service catalog, and use one of the official tag. Check if everything works. Something like:
```
git fetch --all --tags --prune
git checkout tags/v0.1.38 -b v0.1.38
```

**Comment by klaudiagrz** [comment]
Moreover, I've added my comment to the already existing [issue](https://github.com/kubernetes-incubator/service-catalog/issues/2535#issuecomment-466493662) in the Service Catalog. I got a reply that the UPS broker is currently broken and will be fixed in the upcoming release.
