### ISSUE TITLE
Investigate tests for ServiceCatalog

### ISSUE THREAD

**Issue by adamwalach** [kyma-project/kyma#2731]
**Description**

During migration to CRD we need a way to quickly verify multiple data flows/check if we broke compatibility with the old implementation

**AC**
- check how to run tests that are currently present in SC (if there are any non-unit tests that we can reuse)
- ensure that we can fully test whole SC functionality (ver 0.1.40)

**Comment by piotrmiskiewicz** [comment]
## E2E tests

The service-catalog provides e2e tests. the command:
```
go test -o bin/e2e.test -c ./test/e2e
```
builds a binary with the test, then you could run it:
KUBECONFIG=~/.kube/config SERVICECATALOGCONFIG=~/.kube/config ./bin/e2e.test

In my environment I need to remove `alsologtostderr` flag from Pod definition in `test/e2e/util.go` - needs investigate.

**Comment by adamwalach** [comment]
Tested on master
* these are green:
  **make test-unit** 0.69s user 2.91s system 0% cpu 6:56.71 total
  **make test-integration**  2.81s user 4.02s system 0% cpu 26:27.73 total
* e2e tests fail
```Summarizing 2 Failures:
[Fail] [service-catalog] walkthrough [It] Runs through the walkthrough
/Users/i326884/go/src/github.com/kubernetes-incubator/service-catalog/test/e2e/walkthrough.go:127

[Fail] [service-catalog] ClusterServiceBroker [It] should become ready
/Users/i326884/go/src/github.com/kubernetes-incubator/service-catalog/test/e2e/broker.go:95

Ran 3 of 3 Specs in 374.808 seconds
FAIL! -- 1 Passed | 2 Failed | 0 Pending | 0 Skipped --- FAIL: TestE2E (374.81s)
FAIL
KUBECONFIG=~/.kube/minikube SERVICECATALOGCONFIG=~/.kube/minikube   
```
`KUBECONFIG=~/.kube/minikube SERVICECATALOGCONFIG=~/.kube/minikube ./bin/e2e.test 0.41s user 0.24s system 0% cpu 6:14.83 total`
