### ISSUE TITLE
Command to get cluster-certificate not working

### ISSUE THREAD

**Issue by arifC** [kyma-project/kyma#2752]
**Description**
One step in the setup of Kyma on GKE is to add the cluster-certificate to the trusted certs (see https://kyma-project.io/docs/root/kyma#installation-install-kyma-on-a-gke-cluster-with-wildcard-dns-add-the-xip-io-self-signed-certificate-to-your-os-trusted-certificates). The jsonpath in the provided command doesn't work.

`tmpfile=$(mktemp /tmp/temp-cert.XXXXXX) && kubectl get configmap cluster-certificate-overrides -n kyma-installer -o jsonpath='{.data.global.tlsCrt}' | base64 --decode > $tmpfile && sudo security add-trusted-cert -d -r trustRoot -k /Library/Keychains/System.keychain $tmpfile && rm $tmpfile`

I reproduced it on several GKE clusters using Kyma 0.7.0.

**Expected result**
The output of the following command should be the encoded TLS certificate: `kubectl get configmap cluster-certificate-overrides -n kyma-installer -o jsonpath='{.data.global.tlsCrt}'`

**Actual result**
The output is empty.

**Steps to reproduce**
Execute `kubectl get configmap cluster-certificate-overrides -n kyma-installer -o jsonpath='{.data.global.tlsCrt}'` in a GKE cluster with Kyma 0.7.0 installed.

**Troubleshooting**
The dot in the "global.tlsCrt" apparently needs to be escaped.
`kubectl get configmap cluster-certificate-overrides -n kyma-installer -o jsonpath='{.data.global\.tlsCrt}'`

**Comment by adamwalach** [comment]
Thanks for reporting that! This issue is caused by incorrect formatting on kyma-project.io. Markdown files on github have the escape characters in place https://github.com/kyma-project/kyma/blob/master/docs/kyma/docs/04-07-aks-xip.io-domain.md. Your ticket is still valid, I just wanted to clarify the root cause :)

**Comment by derberg** [comment]
@adamwalach is this https://github.com/kyma-project/website/issues/180 the ticket that fixes it? or you created some different issue?

**Comment by piotrmsc** [comment]
Docu have been updated in the linked issue
