### ISSUE TITLE
Enhance GetInfo endpoint to return Application identifier

### ISSUE THREAD

**Issue by akgalwas** [kyma-project/kyma#2753]
**Description**

GetInfo endpoint should be enhanced to include application identifier. 

**Reasons**

In case the external application establishes two connections to Kyma (so that there are two client certificates), there is a need to identify those connections. Application identifier can be extracted from certificate's subject but providing it as a part of GetInfo is easier for the external application and ensures less coupling.

**Comment by pbarbier** [comment]
Please include Application Display name as well
