### ISSUE TITLE
Make docs about GraphQL security official

### ISSUE THREAD

**Issue by derberg** [kyma-project/kyma#277]
Confirm these statements before you submit the issue:

- [x] I have searched open and closed issues for duplicates.
- [x] I have read the contributing guidelines.
---

**Description**

[This](https://github.com/kyma-project/kyma/blob/master/resources/core/charts/ui-api/README.md)
should most probably go [here](https://github.com/kyma-project/kyma/tree/master/docs/authorization-and-authentication/docs) as we need clear security documentation. We would also probably need some general section about this in the overarching kyma docs

 other ideas? I'm all ears

**Reason**

Security applied on graphql layer that serves as catalog ui backend must be visible in official docs set

**Comment by piotrmsc** [comment]
Update: While working on a #2147 mentioned document can be deleted or it's content replaced with new security mechanism described.

Document should:

- Describe how authorization and authentication is done in `core-ui`
- What RBAC roles are required for specific resources
- How to add a new role to secure access to the resource
- **not** mention envoy filter and **istio** RBAC (ServiceRole&Binding) as it will no longer be used
