### ISSUE TITLE
Introduce categories in kyma CRD and add guideline

### ISSUE THREAD

**Issue by pbochynski** [kyma-project/kyma#2780]
**Description**
Add categories `all` and `kyma` to Custome Resource Definitions.
See details: https://kubernetes.io/docs/tasks/access-kubernetes-api/custom-resources/custom-resource-definitions/#categories

Enhance the CRD guide with that requirement

**Reasons**

Different Custom Resources can be returned with single `kubectl get {category}` command if they belong to the same category. If kyma resources will belong to `all` category user can list APIs, bindings, etc using just one command `kubectl get all`. If we additionally add kyma CRDs to `kyma` category user can quickly get all kyma resources with `kubectl get kyma`

**Comment by derberg** [comment]
Please help in prioritizing the issue and decide if it is important to focus on it now

**Comment by Disper** [comment]
The issue is still valid.
Consulted with @pbochynski . It's a good practice and something nice to have but it's not critical.

**Comment by pbochynski** [comment]
After rethinking I think we should not introduce kyma category for our CRD. Kyma utilizes a lot of external CRD (ory, prometheus, istio, etc) and such category would not serve any purpose.
