### ISSUE TITLE
Replace PrepareForCreate with AdmissionWebhooks in SC

### ISSUE THREAD

**Issue by adamwalach** [kyma-project/kyma#2784]
**Description**

Api-server uses the [PrepareForCreate](https://github.com/kubernetes-incubator/service-catalog/blob/7fec2384506143b88910f575913f5fdbe1601d7f/pkg/registry/servicecatalog/instance/strategy.go#L108) for adjusting newly created resource.
We have to implement this functionality using the [MutatingAdmissionWebhook](https://kubernetes.io/docs/reference/access-authn-authz/admission-controllers/#mutatingadmissionwebhook)

**Assumptions:**
* minimal version of K8S:  1.9

**AC:**
* define a template for creating webhooks (where do we keep the source, is it a separated from service manager?)
* as a first implementation move the PrepareForCreate functionality to admission webhooks
* provide a way to deploy the webhook server

**Comment by mszostok** [comment]
## Proposed implementation



```
.
├── CONTRIBUTING.md
├── bin
├── build
├── charts
│   ├── catalog
│   │   ├── Chart.yaml
│   │   ├── README.md
│   │   ├── templates
│   │   │   ├── _helpers.tpl
│   │   │   ├── webhook-deployment.yaml                 # The webhook deployment, uses binary from /cmd/webhook/main.go
│   │   │   ├── webhook-service.yaml                    # The webhook svc
│   │   │   ├── webhook-config.yaml                     # The webhook registration in K8s API Server
│   │   │   ├── controller-manager-deployment.yaml
│   │   │   ├── etcd-pvc.yaml
│   │   │   ├── rbac.yaml
│   │   │   └── serviceaccounts.yaml
│   │   └── values.yaml
│   ├── ...
│   └── ups-broker
├── cmd
│   ├── webhook             # The webhook server
│   ├── apiserver
│   ├── controller-manager
│   ├── healthcheck
│   ├── service-catalog
│   └── svcat
├── contrib
├── pkg
│   ├── webhook             # source code for webhook implementation
│   ├── api
│   ├── apis
│   ├── apiserver
│   ├── client
│   ├── controller
│   ├── features
│   ├── filter
│   ├── hyperkube
│   ├── kubernetes
│   ├── svcat
│   ├── version
│   ├── ...
│   └── version.go
├── test
└── ....
└── vendor
```


For the webhook implementation you can check the [kubebuilder approach](https://book.kubebuilder.io/beyond_basics/sample_webhook.html).

Wehbooks should be splited by domain and have their own struct. We shouldn't not follow the Service Catalog pattern used for controller which are tightly coupled and all things are defined in one big struct.

**Comment by mszostok** [comment]
- Skeleton implementation
- Replace api-server with webhook server
- Implement rest `PrepareForCreate` functions + test coverage
- Documentation
