### ISSUE TITLE
Fetching OData Metadata fails

### ISSUE THREAD

**Issue by akrausesap** [kyma-project/kyma#2787]
**Description**

Dear Colleagues,

fetching OData Metadata fails. Registration API Call looks as follows:
```
"api": {
        "targetUrl": "https://elt-demo.apimanagement.eu2.hana.ondemand.com:443/v1/proxy_c4c_noauth",
        "credentials": {
            "basic": {
    			"username": "secret",
    			"password": "secret"
    		}
        },
        "SpecificationUrl": "https://elt-demo.apimanagement.eu2.hana.ondemand.com:443/v1/proxy_c4c_noauth/sap/byd/odata/v1/c4codata/$metadata",
    	"ApiType": "OData"
}
```
Error is:
```
{
    "code": 502,
    "error": "Determining API spec for service with ID 8b337519-92d7-4e97-acf3-a6f7f5ec1056 failed, Fetching API spec from https://my306768.vlab.sapbydesign.com/sap/byd/odata/v1/c4codata/$metadata failed, Get https://my306768.vlab.sapbydesign.com/sap/byd/odata/v1/c4codata/$metadata: x509: failed to load system roots and no roots provided"
}
```
My release is 0.7

Thanks

Andreas

**Expected result**

Metadata is fetched (including basic auth)

**Actual result**

See above

**Steps to reproduce**

Post provided API Registration to Application Registry

**Troubleshooting**

N/A

**Comment by lszymik** [comment]
We need to investigate it and see what can we do with it.
In the first phase please treat it as spike and we will discuss what to do with it later. Because we have a limited amount of time.

**Comment by lszymik** [comment]
We can start with something very simple, add the SKIP_SSL_VERIFY flag to the App Registry.

**Comment by lszymik** [comment]
There will be a follow-up ticket for supporting basic auth credentials in case of fetching API protected by credentials.
Workaround is:
- Use the basic auth credentials encoded in URL `https://user:password@elt-demo.apimanagement`

**Comment by lszymik** [comment]
Follup-up created: https://github.com/kyma-project/kyma/issues/3069
