### ISSUE TITLE
Implement external application integration test

### ISSUE THREAD

**Issue by akgalwas** [kyma-project/kyma#2789]
**Description**

Implement test exercising the following scenario:
- create application
- create lambda function
- bind lambda function to event
- send event and verify lambda has been triggered  

**Reasons**

The primary goal of this test is ensuring that the core functionalities work after Kyma upgrade. The test must be integrated with other tests ensuring upgradeability.

**Comment by sayanh** [comment]
Is this still valid? @sjanota After you introduced, `core-test-external-solution` IMO this is already taken care of.
