### ISSUE TITLE
Replace TableConvertor with AdditionalPrinterColumns in SC

### ISSUE THREAD

**Issue by adamwalach** [kyma-project/kyma#2790]
**Description**

Api-server is using [TableConvertor](https://github.com/kubernetes-incubator/service-catalog/blob/master/pkg/registry/servicecatalog/binding/storage.go#L143) for printing custom columns on `kubectl get`.

```
$ kc get serviceinstances
NAME      CLASS                       PLAN      STATUS    AGE
redis     ClusterServiceClass/redis   micro     Ready     4h
```
There can be field which needs to define the function to be resolved for a particular value e.g. [**STATUS**](https://github.com/kubernetes-incubator/service-catalog/blob/master/pkg/registry/servicecatalog/instance/storage.go#L157) or [**CLASS**](https://github.com/kubernetes-incubator/service-catalog/blob/master/pkg/registry/servicecatalog/instance/storage.go#L170-L177) columns.
   Some issues from community: [here](https://github.com/kubernetes/kubernetes/issues/67268) and [here](https://github.com/jetstack/cert-manager/pull/1194).

**Assumptions:**
* k8s in version 1.11

**AC**:
- TableConvertor replaced with the [additional-printer-columns](https://kubernetes.io/docs/tasks/access-kubernetes-api/custom-resources/custom-resource-definitions/#additional-printer-columns) defined on CRD.
- STATUS, CLASS and other dynamic columns should be still supported

**Comment by mszostok** [comment]
Remember about DoD:
- execute `make verify` and it **MUST** end without error
- execute `make test-unit` and it **MUST** end without error
- execute `make format`
- check if your changes need to be applied also for `svcat`. If yes then modify it and then test it also manually. HINT: Create a binary:
  ```
  make svcat
  ```
  generated binary will be placed in `bin/svcat/svcat`
- finally, always generate a new image and update tag in chart
- finally, test service catalog by installing chart and walkthrough happy path flow both for **namespace-scope and cluster-wide brokers.** Happy path means creating and deleting all objects.

**Comment by adamwalach** [comment]
Additional columns work pretty good
![Screen Shot 2019-04-18 at 15 08 22](https://user-images.githubusercontent.com/8530211/56409136-f86c7b00-6277-11e9-95a2-8fac1381c924.png)

The only downside is that they are not show when you add the "-w" argument to kubectl command
There is an issue for that: https://github.com/kubernetes/kubernetes/issues/66538

**Comment by adamwalach** [comment]
In order to print additional columns I had to extend implementation of SC controller.

New columns: `Status` for
- ServiceBroker
- ClusterServiceBroker
- Binding

New columns: `Status`, `ServicePlan`, `ServiceClass` for
- Instance

No changes:
- ServiceClass
- ServicePlan
- ClusterServiceClass
- ClusterServicePlan
