### ISSUE TITLE
Dex date is in the past after hibernation

### ISSUE THREAD

**Issue by maxmarkus** [kyma-project/kyma#2805]
When putting my laptop with a running cluster into hibernation and trying to log in next day into console, I am getting `exp is in the past` from dex access token response. If I check the date in the dex pod, it is hours in the past. 
Piotr suggested to delete the pods, so they get recreated. I deleted dex, the pods got recreated. Unfortunately it still shows the error. 

Expected behavior: 
- dex should be in sync with local time after hibernation

**Comment by pbochynski** [comment]
Can you check what is the system date inside the minikube cluster? You can just deploy simple container `kubectl run -i --tty busybox --image=busybox -- sh` and check current date with commad `date`.
If the date is wrong it is probably minikube problem. You can try to stop and start minikube to fix it. See: https://kyma-project.io/docs/root/kyma#installation-install-kyma-locally-from-the-release-stop-and-restart-kyma-without-reinstalling

**Comment by PK85** [comment]
solution for that issue is:
```
minikube ssh -- docker run -i --rm --privileged --pid=host debian nsenter -t 1 -m -u -n -i date -u $(date -u +%m%d%H%M%Y)
```
Which set current time of your local machine into minikube. Will add a PR with update for https://kyma-project.io/docs/root/kyma#installation-install-kyma-locally-from-the-release-troubleshooting soon or later.
