### ISSUE TITLE
Unstable test-core-core-ui-api-acceptance test [ErrorFetchingCatalog]

### ISSUE THREAD

**Issue by mszostok** [kyma-project/kyma#2815]
**Description**

Stability Checker reporting that *test-core-core-ui-api-acceptance* is failing on our nightly/weekly clusters. The problem is that the sample broker cannot be registered, see logs:

```
2019/02/19 20:53:31 [{Ready False 2019-02-19 20:48:32 +0000 UTC ErrorFetchingCatalog Error fetching catalog.Error getting broker catalog: Status: 404; ErrorMessage: <nil>; Description: <nil>; ResponseError: unexpected end of JSON input}]
2019/02/19 20:53:31 [{Ready False 2019-02-19 20:48:32 +0000 UTC ErrorFetchingCatalog Error fetching catalog.Error getting broker catalog: Status: 404; ErrorMessage: <nil>; Description: <nil>; ResponseError: unexpected end of JSON input}]
2019/02/19 20:53:32 Cleaning up...
2019/02/19 20:53:32 while uninstalling ServiceBroker: servicebrokers.servicecatalog.k8s.io "ups-broker" not found
2019/02/19 20:53:32 while setup: while waiting for ClusterServiceBroker registration: Waiting for resource failed in given timeout 300.000000 second(s): [{Ready False 2019-02-19 20:48:32 +0000 UTC ErrorFetchingCatalog Error fetching catalog.Error getting broker catalog: Status: 404; ErrorMessage: <nil>; Description: <nil>; ResponseError: unexpected end of JSON input}]
Setting exit status to 1
```

other failed job:
[status.build.kyma-project.io/view/gcs/kyma-prow-logs/logs/post-master-kyma-integration/1096400427529801728](https://status.build.kyma-project.io/view/gcs/kyma-prow-logs/logs/post-master-kyma-integration/1096400427529801728)

**Expected result**

Tests are more stable and test output is more readable

**Actual result**
Tests failing from time to time and the test logs are too verbose. We can see the same entry
```
2019/02/19 20:53:31 [{Ready False 2019-02-19 20:48:32 +0000 UTC ErrorFetchingCatalog Error fetching catalog.Error getting broker catalog: Status: 404; ErrorMessage: <nil>; Description: <nil>; ResponseError: unexpected end of JSON input}]
```
is logged every second during 5minutes. It should be replaced with simple log after 5min with last error which occurred

**Comment by pkosiec** [comment]
It's hard to investigate what's the reason of this issue. I would suggest the following workaround: instead of using UPS Broker (and registering, deregistering it for servicecatalog and servicecatalogaddons domains), we could use Helm Broker Test bundle, similarly to UI Tests.
