### ISSUE TITLE
Rename application-proxy to application-gateway

### ISSUE THREAD

**Issue by pbochynski** [kyma-project/kyma#2819]
**Description**
Application Proxy component should be renamed to Application Gateway.

**Reasons**
There is a plan to develop Application Proxy component which will be deployed aside the external system (application) which will manage secure connection from the application to Kyma Cluster. Application Gateway is a better name for the component that routes traffic from Kyma Cluster to the external application.

**Comment by tomekpapiernik** [comment]
The renaming effort must include all mentions in documentation and diagrams.
