### ISSUE TITLE
Make graphana related docs part of official Kyma documentation

### ISSUE THREAD

**Issue by derberg** [kyma-project/kyma#282]
Confirm these statements before you submit the issue:

- [x] I have searched open and closed issues for duplicates.
- [x] I have read the contributing guidelines.
---

**Description**

Make sure content from:
  - https://github.com/kyma-project/kyma/tree/master/resources/core/charts/monitoring/charts/grafana
  - https://github.com/kyma-project/kyma/tree/master/resources/core/charts/monitoring/charts/alert-rules
  - https://github.com/kyma-project/kyma/tree/master/resources/core/charts/monitoring/charts/alertmanager

is actually a part of https://github.com/kyma-project/kyma/tree/master/docs/monitoring/docs

**Reasons**

There are details that should be well described and visible to Kyma users so they know how to operate Kyma components and also expose their own metrics

**Comment by joek** [comment]
This is not working, as the user would have access to kyma-system namespace. As soon as we have a stragy for end users to add their own alerts, we will add dedicated documentation.
