### ISSUE TITLE
More detailed dashboard/alert rule for API Server Latency

### ISSUE THREAD

**Issue by sayanh** [kyma-project/kyma#2829]
**Description**

Right now, the dashboard `Kubernetes Control Plane Status` which has this rule:
```sum by(verb) (rate(apiserver_latency_seconds:quantile[5m]) >= 0)```
IMO this is not enough and we need to understand a trend for 55th, 90th, 95th - ile as well.

Alerting based on 99th-ile is also not enough and we need to get more data for 55th, 90th, 95th-ile to fire alert.

This is follow up of #2622.

**Comment by pbochynski** [comment]
@piotrmsc Please check if it is still valid.

**Comment by pbochynski** [comment]
We have other dashboards for api server. Please reopen if you think it is still required.
