### ISSUE TITLE
New Remote Environment does never appear as serving

### ISSUE THREAD

**Issue by akrausesap** [kyma-project/kyma#283]
Confirm these statements before you submit the issue:

- [X] I have searched open and closed issues for duplicates.
- [X] I have read the contributing guidelines.
---

**Description**

Dear Colleagues,

after creating a new environment (according to https://kyma-project.io/docs/latest/components/application-connector#details-deploy-a-new-application-connector) the Remote environment always is in status not serving. This can only be resolved by restarting pod core-ui-api-* in namespace kyma-system. Please fix this.

Thanks

Andreas

**Expected result**

Environment appears as serving w/o restart

**Actual result**

Environment appears as not serving

**Steps to reproduce**

Deploy new remote environment via helm

**Troubleshooting**

restart core-ui-api-*

**Comment by aszecowka** [comment]
In ui-api-layer there is an assumption, that every service with label 'remoteEnvironment' has a port with name 'ext-api-port'.
Currently, when we list all services with this label:
```kubectl get -oyaml services --all-namespaces -l remoteEnvironment```
we see that part of services have port name 'ext-api-port', but others have 'http-api-port' which cause that our algorithm is not deterministic.

**Comment by lszymik** [comment]
We need to change the port names to `http-api-port`. Otherwise, the tracing functionality will not work.
