### ISSUE TITLE
Enable examples to be consumable through the service catalog

### ISSUE THREAD

**Issue by derberg** [kyma-project/kyma#2832]
**Description**

I want to be able to enable in Kyma local/cluster the examples bundle and I want to be able to provision them in a runtime.

Details:
- have a new bundle in https://github.com/kyma-project/bundles exposed as a separate index, for example `index-examples.yaml`, so they are always released (https://github.com/kyma-project/bundles/releases) like the default `index` and optional `index-testing`
- new examples bundle provides all configured examples as service classes consumable in the Service Catalog UI. So you can imagine that once you add the bundle to Helm broker, in the Catalog you will see service classes like for example `Tracing example` that once it is provisioned it creates all the resources needed to see tracing in action
- we need clear definition of example that should be embedded as a bundle:
  - is it any?
  - is it still example or maybe showcase?
  - some specific criterias?
  - helm chart is a must
  - namespace independent
- clear explanation documentation how to provide such example/showcase and what are the rules
- we need one working example that we can already use after this task and promote the solution. It is up to you to decide if you reuse one of existing Kyma examples or create a totally new one that you think will be supper cool as a starter
- each service class must have clear documentation that later we can display in the service catalog in the context of the specific service, so the user can learn from it: 
  - what resources is the class creating during provisioning
  - detailed purpose of showcase and how you can extend it and play with it
  - what secrets are created and returned with ServiceBinding
  - what plans are available and their purpose
- decide/recommend if we just reuse existing examples or we actually need to always have dedicated showcases only. So if it makes sense and it is possible to still be able to use the example the old school with `helm install` etc.

Hints:
- for development reasons, to be able to play with bundle and make sure it works you need to publish it, release it. So we suggest you fork and use our travis setup instruction that can help you automating the publishing of release on your fork -> https://github.com/kyma-project/bundles/blob/master/docs/getting-started.md

**Reasons**

At the moment the only way to learn Kyma with `hands-on` experience is to follow examples https://github.com/kyma-project/examples. There are cases though where you want to quickly set up example to just play with the functionality that it enables, so you just want to take what it gives with no customizations and maybe just extend it. This requires a lot of manual work and would be nice to have such showcase examples as part of the catalog, so you can easily quickly run the examples.

**Comment by kautsig** [comment]
@derberg as discussed on slack, I can take this over.

**Comment by derberg** [comment]
@kautsig interesting, I can't do that if you are not in the org. Let us leave it as it is and I'll consult with others how to best proceed in such cases

**Comment by a-thaler** [comment]
is duplicating https://github.com/kyma-project/examples/issues/57, I closed the other ticket

**Comment by derberg** [comment]
we have a first example of how it could look like, a showcase scenario with lambda and binding in one addon https://github.com/kyma-incubator/github-slack-connectors/tree/master/addons/azurecommentsanalytics-1.0.0

**Comment by PK85** [comment]
@derberg Could we close that issue? No hands to work on that since one year.
