### ISSUE TITLE
Investigate the service catalog defaults and migrate to CRDs if needed

### ISSUE THREAD

**Issue by mszostok** [kyma-project/kyma#2837]
**Description**

The Service Catalog api-server uses the [defaults](https://github.com/kubernetes-incubator/service-catalog/blob/7fec2384506143b88910f575913f5fdbe1601d7f/pkg/apis/servicecatalog/v1beta1/defaults.go). Those defaults are generated by [defaulter-gen](https://github.com/kubernetes/code-generator/tree/master/cmd/defaulter-gen). For now, I do not know how they are used. Maybe they will work as they are or maybe we will need to implement it in mutating webhook.

**AC:**
- we know how api-server defaults are used and if needed is replaced with CRDs functionality.

**Comment by mszostok** [comment]
See also our doc about CRD: https://github.com/kyma-project/community/blob/master/guidelines/coding-standards/helm.md

**Comment by piotrmiskiewicz** [comment]
Defaults mentioned in the description can be applied by the client app which uses (imports) the API. The sequence of the code can looks like:
```
func init() {

	_ = v1beta1.AddToScheme(runtimeScheme)

}

func useDefaults() {
// some code
runtimeScheme.Default(obj)

}
```

The original API server executes the `Default` method after every call to a webhook.
On the other hand we do not see any advantage to use defaults and other ways to have default values. All of them can be in one place - in prepare for create webhook.

The webhook which applies defaults could looks like:
```
func (whsvr *WebhookServer) mutate(ar *v1beta1.AdmissionReview) *v1beta1.AdmissionResponse {
	req := ar.Request

	obj, err := runtimeScheme.New(schema.GroupVersionKind{
		Group: req.Kind.Group,
		Kind: req.Kind.Kind,
		Version: req.Kind.Version,
	})
	if err != nil {
		glog.Errorf("Could not create obj: %v", err)
		return &v1beta1.AdmissionResponse{
			Result: &metav1.Status{
				Message: err.Error(),
			},
		}
	}
	glog.Infof("Object %+v", obj)

	defaulter.Default(obj)

	glog.Infof("After defaults applied to gvk: %+v", obj)

	return &v1beta1.AdmissionResponse{
		Allowed: true,
	}
}
```

**Comment by piotrmiskiewicz** [comment]
The main question is can we migrate all defaults to the webhoow and remove defaults as it is now?

**Comment by mszostok** [comment]
### About your approach with webhook
Baase on your snippet I assume that `defaulter.Default(obj)` is applying defaults by its own.  I do not think that it is a good approach. Mutating webhook should return patch in AdmissionResponse and main api-server should apply final obj into etcd. What's more if u want to apply default to obj in etcd, then who it can be achieved on CREATE action when this obj is not yet in etcd?

### My questions
- where those defaults are used in Service Catalog?
  [This](https://github.com/kubernetes-incubator/service-catalog/blob/master/pkg/apis/servicecatalog/v1beta1/defaults.go) is the only place where defaults are used?
- how new defaults can be added using this `defaulter-gen` tool?


#### My suggestion
If defaults are used only it two places:
```go
	if spec.RelistBehavior == "" {
		spec.RelistBehavior = ServiceBrokerRelistBehaviorDuration
	}
```
and
```go
	// If not specified, make the SecretName default to the binding name
	if binding.Spec.SecretName == "" {
		binding.Spec.SecretName = binding.Name
	}
```

and if adding new defaults using `defaulter-gen` tool is not super simplified for developer

then my suggestion is to remove the `defaulter-gen` approach totally and inline those statements directly in webhooks.

**Comment by piotrmiskiewicz** [comment]
The defaulter-gen tool *scans for top level types and generate efficient defaulters for an entire object from the sum of the SetDefault_XXX methods contained in the object tree.* More about it in the [tool description](https://github.com/kubernetes/code-generator/blob/master/cmd/defaulter-gen/main.go). So the way to use it is implement *SetDefault_* methods and run defaulter-gen tool.
