### ISSUE TITLE
CSRF token support in Application Gateway

### ISSUE THREAD

**Issue by pbochynski** [kyma-project/kyma#2852]
**Description**

Some applications use CSRF tokens to protect their resources. Application Gateway should fetch & cache such token and use it for requests.
Add a configuration that will enable CRSF token handling and provides necessary parameters (token fetch request params, token header name, etc)

**Reasons**

Kyma developer should not handle CRSF tokens in own code. 

**Attachments**

- https://github.com/OWASP/CheatSheetSeries/blob/master/cheatsheets/Cross-Site_Request_Forgery_Prevention_Cheat_Sheet.md

**Comment by piotrmsc** [comment]
1. Fetching a token : 
- Set ** 'X-csrf-token': 'fetch'** request header 
- Store token and cookie from the token response headers ('x-csrf-token', 'set-cookie')

2. Call upstream service with a token
based on step 1, set following request headers : 
- **'X-csrf-token': '$TOKEN'** 
- ** 'cookie' : $COOKIE' 

Handling CSRF token is optional, enabled while registering API via CR.

**Comment by Szymongib** [comment]
Consider adding a new authorization type `BasicWithCSRF` by extending the existing type `Basic`. Note that the `AuthenticationUrl` should be provided.

**Comment by jakkab** [comment]
@Szymongib I have spoken with @piotrmsc and apparently the implementation needs to be more generic: we should be able to extend each authentication strategy (basic, oauth, certificate) with CSRF token.

**Comment by lszymik** [comment]
Hello @strekm , @jakkab , @akgalwas Do we have more detailed documentation somewhere. I am looking for an explanation of how it works in the Gateway service.

**Comment by Disper** [comment]
@lszymik It's not yet documented.
