### ISSUE TITLE
AKS: Apiserver is not reachable for prometheus-operator

### ISSUE THREAD

**Issue by jasiu001** [kyma-project/kyma#2873]
**Introduction**

Kyma on AKS generates every 10 minutes alert notifications about impossibility of sending a query to apiserver:
`No API servers are reachable or all have disappeared from service discovery`
Part responsible for this query is in this [file](https://github.com/kyma-project/kyma/blob/master/resources/monitoring/charts/exporter-kubernetes/templates/kubernetes.rules.yaml#L83)
Prometheus shows apiserver is down:
![Screen Shot 2019-02-26 at 13.56.50.png](https://images.zenhubusercontent.com/5bb751f458d3b92dfedf44c9/22dcb40f-cf8b-4c9c-8f17-51ce940c938f)

**Issue**

According to this [issue](https://github.com/coreos/prometheus-operator/issues/1522) problem occurs on AKS cluster.
This [PR](https://github.com/helm/charts/pull/10963/files) should fix the problem, unfortunately chart prometheus operator in Kyma is in 0.19 version, PR is available in ver 0.26 (actual version of chart is 0.29).
I suggest bump the version of kubernetes operator to resolve the AKS problem.

On GKE issue does not occur

**Comment by sayanh** [comment]
Turns out, there is a tight coupling between prometheus operator and other components in the monitoring chart. We will upgrade the whole stack of monitoring in this [story](https://github.com/kyma-project/kyma/issues/2926) for the coming release.
