### ISSUE TITLE
ServiceCatalog client libraries need to be updated

### ISSUE THREAD

**Issue by adamwalach** [kyma-project/kyma#2876]
**Description**

Follow up from https://github.com/kyma-project/kyma/issues/1737
Our components use very old ServiceCatalog client in version [0.1.28](https://github.com/kyma-project/kyma/blob/master/components/binding-usage-controller/Gopkg.toml#L52)
I tried to update client libraries to the newest SC (as part of #1737) but I faced issues with dependencies during the upgrade. SC needs newest version of K8S libraries and our code is not fully compatible with that. 

You can easily find components that have old version of SC by searching for `version = "=v0.1.28"`:
- components/application-broker
- components/binding-usage-controller
- components/helm-broker
- components/installer
- components/ui-api-layer
- tests/acceptance
- tests/ui-api-layer-acceptance-tests

**Comment by jasiu001** [comment]
Rename all imports with ServiceCatalog from `kubernetes-incubator` to `kubernetes-sigs`

**Comment by mszostok** [comment]
will be automatically implemented when we will switch into Service Catalog CRD impl
