### ISSUE TITLE
Replace satori go.uuid library in application-registry

### ISSUE THREAD

**Issue by piotrmsc** [kyma-project/kyma#2884]
**Description**
As a part of code scanning, tool reported usage of https://github.com/satori/go.uuid with high vulnerability of insecure randomness [see here](https://app.snyk.io/org/kyma-project/project/ddb5a37a-56b8-4002-9ea8-7b4f749d46d2/history/a97dbd19-a2fe-41f0-bcb8-8304ddb5b153)
We have to change it to https://github.com/gofrs/uuid which is a new version of old go uuid with fixed problem. Additionally, satori lib is deprecated [see here](https://github.com/satori/go.uuid/issues/84)

**Expected result**
We are using gofrs uuid library instead of satori go.uuid

**Actual result**
satori go.uuid is used.

**Steps to reproduce**

**Troubleshooting**

**Comment by lszymik** [comment]
Hello @franpog859,
Would you be so kind and can you check also the usage of the satori/go.uuid in tests? 

It comes to our attention that we are still using that library in a couple of places. Maybe you can clean-up all of them and then other teams will just do a quick review.

Thank you in advance.
Cheers.

**Comment by franpog859** [comment]
Library replacement in all files I found `satori/go.uuid` is already merged. After merging PR with images bump the issue will be finished
