### ISSUE TITLE
Replace satori go.uuid library in event-bus

### ISSUE THREAD

**Issue by piotrmsc** [kyma-project/kyma#2885]
**Description**
As a part of code scanning, tool reported usage of https://github.com/satori/go.uuid with high vulnerability of insecure randomness [see here](https://app.snyk.io/org/kyma-project/project/f46632e8-e7e9-4b15-a5b3-8e3a8ebe3805/history/6d50c34f-d8e2-44ae-8218-2f08d3f8bb05)
We have to change it to https://github.com/gofrs/uuid which is a new version of old go uuid with fixed problem. Additionally, satori lib is deprecated [see here](https://github.com/satori/go.uuid/issues/84)

**Expected result**
We are using gofrs uuid library instead of satori go.uuid

**Actual result**
satori go.uuid is used.

**Steps to reproduce**

**Troubleshooting**

**Comment by abbi-gaurav** [comment]
We can possibly do this change in one of the current task that involves changing the event bus code.

Assigning it to @suleymanakbas91

**Comment by piotrmsc** [comment]
@abbi-gaurav awesome!
