### ISSUE TITLE
Helm broker should properly handle OSBA contract convention for metadata atribute

### ISSUE THREAD

**Issue by derberg** [kyma-project/kyma#289]
Confirm these statements before you submit the issue:

- [x] I have searched open and closed issues for duplicates.
- [x] I have read the contributing guidelines.
---

**Description**

OSBA provides the following convention for imageUrl: https://github.com/openservicebrokerapi/servicebroker/blob/31bf79dd3b6573d8959940c01e4460ac33d33cb5/profile.md#service-metadata-fields

We should use that one in Helm Broker, and not expect ui-api-layer component reads both, imageUrl and imageURL for example.

**Expected result**

metadata.imageUrl
metadata.documentationUrl

**Actual result**

metadata.imageURL 
metadata.documentationURL

**Comment by mszostok** [comment]
The`supportURL` was also changed to `supportUrl`
