### ISSUE TITLE
Cleanup kyma RBAC roles 

### ISSUE THREAD

**Issue by piotrmsc** [kyma-project/kyma#2896]
**Description**

We have introduced kyma developer role in https://github.com/kyma-project/kyma/issues/2557.
However, we still need to clean up a few things and improve our documentation.

What needs to be done :
- namespace-controller does not create kyma-admin and kyma-reader roles in the namespace like it does [here](https://github.com/kyma-project/kyma/blob/master/components/namespace-controller/internal/controller/controller.go#L113)
- check if apigroups can contain a wildcard in the names like "*.kyma-project.io" if so, then replace it for those roles - checked, cannot be simplified with wildcard.
- update our documentation - create a matrix in the security overview section, describing which roles are present in the kyma, what privileges they provide. Additionally, delete section regarding **kyma-admin** and **kyma-reader** roles being created in the namespaces by the NS controller.
- apply the aggregate rule for cluster kyma-admin and kyma-reader if possible

**Reasons**
Namespace controller creates roles which are not needed anymore, admin will be able to create bindings in the console directly like with kyma-developer. Moreover, created roles by the NS controller give too high privileges -  does not reflect kyma-admin and viewer cluster roles.
Documentation will fully cover authorization roles used in kyma, currently it is mixed.

**Attachments**

**Comment by kazydek** [comment]
We need to have one place where all Kyma access roles as collected and well-described.

Currently, some of them are here: https://kyma-project.io/docs/master/components/security#tutorials-manage-static-users-in-dex-bind-a-user-to-a-role-or-a-clusterrole
And some of them are here: https://kyma-project.io/docs/master/components/security/#overview-overview

I leave that up to you whether you prefer to move them to the overview doc or create a separate doc for that (but would definitely opt for that ;) ). Preferably that should be a table with the access matrix describing what permissions the given role provides to the user. It should be also clearly stated if the role is cluster-wide or a namespace-wide.
