### ISSUE TITLE
Components in installer proposal

### ISSUE THREAD

**Issue by strekm** [kyma-project/kyma#292]
Confirm these statements before you submit the issue:

- [ ] I have searched open and closed issues for duplicates.
- [ ] I have read the contributing guidelines.
---

**Description**

Changes required:

- move components list from installer config-map to installation CR
- extend components list to support more descriptive installation steps

- componentName - required
- releaseName - default=componentName
- namespace - required
- stepType [helm, kubectl-apply, kubectl-patch]- default=helm

- installer will not support bash scripts execution
- installer will not support dependencies, if your component relies on another component then you need to handle dependency checking yourself (init containers)

**Comment by jakkab** [comment]
moved to kyma-project/community#34
