### ISSUE TITLE
Event bus components are specify HTTP protocol instead of NATS protocol

### ISSUE THREAD

**Issue by abbi-gaurav** [kyma-project/kyma#2922]
**Description**
To connect to the NATS Client, event bus components (publish, push) need to specify a NATS URL.
Until recently it was of the form `nats://<service>:<port>`

With some [recent changes](https://github.com/kyma-project/kyma/pull/2359), it was wrongly changed to have `http://<service>:<port>`.

This should be corrected.

**AC**
- [ ] All components connecting to NATS Streaming should use `nats://` protocol

**Comment by PavelPavlov46** [comment]
hey @abbi-gaurav , I will chnage that in the deployment charts, as part of the nats basic auth change.

**Comment by PavelPavlov46** [comment]
@abbi-gaurav , could you please confirm the changes delivered with https://github.com/kyma-project/kyma/commit/f84291ea9273c2b030abce7c323bda142c6c4354 meet your expectations and I can close this issue.
