### ISSUE TITLE
Upgrade Prometheus / Grafana to latest version

### ISSUE THREAD

**Issue by joek** [kyma-project/kyma#2926]
**Description**
Upgrade Prometheus and Grafana to the latest version. Make sure the upgrade from 0.8 is working. 

**Reasons**
Grafana is providing new features we like to use. E.g. loki UI integration and a changed login behaviour.

**Comment by sayanh** [comment]
Fixes this [issue](https://github.com/kyma-project/kyma/issues/2873)

**Comment by MarkDordoy** [comment]
Do you know when this might be completed?

**Comment by joek** [comment]
It is completed
