### ISSUE TITLE
Switch App registry to use the asset store and upload service.

### ISSUE THREAD

**Issue by lszymik** [kyma-project/kyma#2927]
**Description**

There is a new component - Asset store - which can be used to store the API and Event catalog documentation and specification.

It is valuable to migrate to it and use the Upload service. 

**Reasons**

- We will achieve better architecture with the new possibilities offered by the Asset store.
- We will increase the solution security as there will be no need to store Minio credentials anymore.

**Prerequisites**

- Asset store and Upload service offer provide buckets because customers are using API which might be proprietary ones.

**Acceptance**

- All assets send to App Registry are stored in the Asset Store (inline specs and specUrls)
- Both XML and JSON OData specifications are supported
- Prerequisites are met
- Documentation, architecture diagram, updated

**Comment by derberg** [comment]
just to make sure you do not create Asset CR, you should create DocsTopic CR

**Comment by akgalwas** [comment]
The follow-up story: #3394
