### ISSUE TITLE
Support uninstallation for kyma in the installer

### ISSUE THREAD

**Issue by piotrmsc** [kyma-project/kyma#2942]
**Description**

Currently, it is possible to trigger uninstallation of kyma via kyma-installer using action label on the installation CR. However, it does not work officially and as expected. For example, see here https://github.com/kyma-project/kyma/issues/1826. Kyma installer should support this action properly, by invoking `helm delete` (with probably `--purge` option) on all resources installed by the installer. Documentation should be updated as well and cover this topic fully - users should know how to uninstall kyma to be able to install it again without the need to delete the cluster.

Uninstallation should be triggered using the same CR used for installation. Handling of multiple CRs with installation kind will be handled in the future.

Installer should report releases that failed to uninstall (preferably in installation CR).

Unfortunately, it is not possible to label releases so we  have to accept resources provided in the CR and delete it, without checking if it belongs to kyma. Kyma installer (or operator is more accurate name) will be able to uninstall any chart in the cluster. At least for now.

**Reasons**

It's is beneficial to have a full install/upgrade/uninstall flow supported. 

**Attachments**

**Comment by derberg** [comment]
Very good issue, I like it as now in GCP if you install Kyma through marketplace, it is not possible to uninstall without whole cluster deletion

**Comment by Demonsthere** [comment]
From what I can see purge is enabled by default in the installer [already](https://github.com/kyma-project/kyma/blob/master/components/installer/pkg/kymahelm/kyma-helm-client.go#L136)

**Comment by rufreakde** [comment]
> 

this link is broken?
