### ISSUE TITLE
Event bus tests are not  run as a part of CI

### ISSUE THREAD

**Issue by abbi-gaurav** [kyma-project/kyma#2964]
**Description**
After recent migration of event-bus chart outside the core, the event-bus tests no longer run as a part of the ci.

Refer: 
- https://github.com/kyma-project/kyma/pull/2945
- https://storage.googleapis.com/kyma-prow-logs/pr-logs/pull/kyma-project_kyma/2945/pre-master-kyma-integration/1102495090711990272/build-log.txt

The reason seems to be the missing entry in https://github.com/kyma-project/kyma/blob/master/installation/scripts/testing.sh

**AC**
- [ ] event-bus tests are run as  a part of ci

**Comment by marcobebway** [comment]
As agreed, we will run the **event-bus** tests only if the knative feature flag is not provided to the kyma installer.
