### ISSUE TITLE
Outdated information in "Monitoring" tutorial

### ISSUE THREAD

**Issue by tomekpapiernik** [kyma-project/kyma#2966]
**Description**

[This](https://kyma-project.io/docs/components/monitoring/#tutorials-tutorials) document contains information about enabling Istio sidecar injection. This information is outdated as sidecar injection is now a default behavior of Istio in Kyma. 

**To do**

The contents of the [Configure Istio](https://kyma-project.io/docs/components/monitoring/#tutorials-expose-custom-metrics-in-kyma-configure-istio) paragraph should be adjusted to reflect the current state of implementation.

**Comment by a-thaler** [comment]
fixed in related PR
