### ISSUE TITLE
Non-permissive licenses in kyma dependencies

### ISSUE THREAD

**Issue by jose-cortina** [kyma-project/kyma#2970]
**Description**

In kyma there are libraries reported by FOSSA which use some version of the GPL license which is not permissive and must be avoided. This causes a license failure in FOSSA.

The libraries reported by FOSSA with GPL licenses are:
https://github.com/aws/aws-sdk-go
https://github.com/gobuffalo/buffalo-plugins
https://github.com/spf13/cobra
https://github.com/docker/docker
https://github.com/heketi/heketi
https://github.com/rkt/rkt
https://github.com/rtfd/sphinx_rtd_theme

**Expected result**

All libraries used have a valid and permissive license.

**Actual result**

Libraries with non-permissive licenses are used.

Please refer to https://app.fossa.io/projects/git%2Bgithub.com%2Fkyma-project%2Fkyma/refs/branch/master/10105a9ef95840e691a1845a8dac627b4973c225/issues/licensing?filter=policy_flag

**Comment by pkosiec** [comment]
Looks like we have a lot of false positives, which we can ignore. I did an investigation for the following packages:

**buffalo-plugins**

False positive. The dependency have been always MIT: [https://github.com/gobuffalo/buffalo-plugins/commits/master/LICENSE](https://github.com/gobuffalo/buffalo-plugins/commits/master/LICENSE)

**cobra**

False positive. The dependency have been always MIT: [https://github.com/spf13/cobra/commits/master/LICENSE.txt](https://github.com/spf13/cobra/commits/master/LICENSE.txt)

**sphinx-rtd-theme**

False positive. The dependency have been always MIT: [https://github.com/rtfd/sphinx_rtd_theme/commits/master/LICENSE](https://github.com/rtfd/sphinx_rtd_theme/commits/master/LICENSE)

**aws-sdk-go**

False positive. The dependency have been always Apache 2.0:
https://github.com/aws/aws-sdk-go/commits/master/LICENSE.txt

**docker** / **moby**

False positive. The dependency have been always Apache 2.0:
https://github.com/moby/moby/blob/master/LICENSE

**Comment by jose-cortina** [comment]
**slack-test** license has been created but not yet merged: https://github.com/lusis/slack-test/pull/4/files so this can be ignored.

**thrift** does include parts licensed under the LGPL-2.1 license, as shown in FOSSA scan:

https://github.com/apache/thrift/blob/master/debian/copyright
https://github.com/apache/thrift/blob/master/doc/licenses/lgpl-2.1.txt

**Comment by pbochynski** [comment]
@jose-cortina Can you exclude false positives verified by you and Paweł (in this ticket and in fossa app)?
The only 3 items left (heketi, gossip, systemutils) are kubernetes dependencies. We cannot avoid dependency to kubernetes, so the question is what we can/should do. Please propose some action.

**Comment by pkosiec** [comment]
@jose-cortina 
> slack-test license has been created but not yet merged: https://github.com/lusis/slack-test/pull/4/files so this can be ignored.

Not really, because the PR has not been created by library author.

> thrift does include parts licensed under the LGPL-2.1 license, as shown in FOSSA scan:

Right. Sorry, my bad - I updated the list.

**Comment by jose-cortina** [comment]
Waiting for a reply form the licensing team... stay tuned ;-)

**Comment by jose-cortina** [comment]
slack-test LICENSE has been merged in the meantime, so that no further issues remain.
