### ISSUE TITLE
Service Catalog namespace-scoped resources documentation

### ISSUE THREAD

**Issue by polskikiel** [kyma-project/kyma#298]
**Description**
After implementing Service Catalog's namespaced-resources in Kyma, we must create documentation about it.

**Acceptance criteria**
- Kyma workflow with a new namespaced-resources is described.
- New architecture diagrams for Service Catalog in Kyma(?)

**Comment by kazydek** [comment]
This PR is ready for the review: https://github.com/kyma-project/kyma/pull/1102/files.

**Comment by pkosiec** [comment]
Review: @pkosiec @michal-hudy

**Comment by kazydek** [comment]
Related to PR: https://github.com/kyma-project/kyma/pull/1102 that has been already merged. The docu is waiting for the release.
