### ISSUE TITLE
Dex monitoring and alerting

### ISSUE THREAD

**Issue by Abd4llA** [kyma-project/kyma#2983]
**Description**

Enable alerting and grafana dashboard entries for Dex. Suggestion to use [RED](https://www.weave.works/blog/the-red-method-key-metrics-for-microservices-architecture/) method.

**Reasons**
- Dex is a key component in Kyma, we need to know when it's suffering.
- This will ease the support and operations for Kyma by providing visibility into a key Kyma component.

**Acceptance Criteria**
- Alerts are configured for Dex.
- There is a dashboard for Dex on Grafana that is enabled on default cluster installation.
- Dex metrics are exposed following [RED](https://www.weave.works/blog/the-red-method-key-metrics-for-microservices-architecture/) method.

**Comment by pbochynski** [comment]
Please use the issue template and provide description, reasons and acceptance criteria.

**Comment by piotrmsc** [comment]
PR with metrics and charts is here https://github.com/kyma-project/kyma/pull/6041

Alerting is postponed.
