### ISSUE TITLE
Monitoring and alerting for backing services and open source services

### ISSUE THREAD

**Issue by Abd4llA** [kyma-project/kyma#2984]
**Description**

Kyma uses many backing services and open source components and to increase Kyma's observability we need to setup monitoring and alerting for those components and integrate it with Kyma's Prometheus and Grafana dashboard.
 
**Monitoring Documentation**
- [Metrics](https://github.com/kyma-project/examples/tree/master/monitoring-custom-metrics)
- [Alerting](https://github.com/kyma-project/examples/tree/master/monitoring-alert-rules)
- [Dashboards](https://github.com/kyma-project/kyma/tree/master/resources/monitoring/charts/grafana#making-a-dashboard-part-of-kyma-installation)

**Comment by lszymik** [comment]
We are closing as there is no progress.
