### ISSUE TITLE
Dynamic configurable monitoring and alerting support for Kyma components

### ISSUE THREAD

**Issue by Abd4llA** [kyma-project/kyma#2985]
**Description**
Explore the idea of introducing a set of labels for Kyma components that enable and disable alerts rules and dashboards based on various criteria and provide a proposal if applicable.

**Reasons**
- Kyma includes a number of different components that can be generically categorized into a few categories (controllers, RESTful service..etc) and so they share common monitoring and alerting profile.
- If applicable, will reduce significantly the amount of work needed to enable monitoring and alerting.

**Comment by lszymik** [comment]
There is no progress. We are closing it.

**Comment by Abd4llA** [comment]
Still relevant, would like to continue on it
