### ISSUE TITLE
Ensure that input to Central Connector service is sanitized and properly handled in client certificates

### ISSUE THREAD

**Issue by lszymik** [kyma-project/kyma#2991]
**Description**

It is a follow-up of our discussion that we need to:

- Verify the information provided in headers to Connector service
- Ensure that the URL is properly built without risk of the attack
- Define the final form of the CN field in the certificate subject
- Apply Nginx-Ingress validation rule for it

**Acceptance criteria**

- Tenant, Group and Application name verified in the same way how Management Plane is doing it.
- The URL which contains above fields is properly build without the security risk.
- The final definition of CN field applied, the tenant, group and application fields are separated.
- Nginx is validating that CN field.

**Comment by akgalwas** [comment]
After discussions we agreed that the set of valid characters will be comprised of lowercase alphanumerics and '-' character.

**Comment by janmedrek** [comment]
We've already set up structure of CN field, NGINX was removed as well.
