### ISSUE TITLE
Verify istio and Jaeger monitoring and alerting

### ISSUE THREAD

**Issue by Abd4llA** [kyma-project/kyma#3000]
**Description**
Istio and Jaeger come with their [telemetry tools](https://istio.io/docs/tasks/telemetry/using-istio-dashboard/). We need to verify that behaviour within Kyma and the possibility of integrating that with the Kyma prometheus and graphana dashboard.

**Reasons**
- Istio is an essential foundation component in Kyma, we need to know when it's suffering.
- This will ease the support and operations for Kyma by providing visibility into a key Kyma component.

**Acceptance Criteria**
- Verifying prometheus and graphana are working for istio and Jaeger.
- Istio and Jaeger have alerts rules configured.
- [stretch goal] Istio and Jaeger send their metrics to Kyma prometheus and graphana.

**Comment by pbochynski** [comment]
Please use the issue template and provide description, reasons and acceptance criteria.

**Comment by lszymik** [comment]
No progress, we are closing it.
