### ISSUE TITLE
Verify Knative telemetry 

### ISSUE THREAD

**Issue by Abd4llA** [kyma-project/kyma#3001]
**Description**
Knative comes with its own [telemetry tools](https://github.com/knative/docs/blob/master/serving/installing-logging-metrics-traces.md). We need to verify that behaviour within Kyma and the possibility of integrating that with the Kyma prometheus and graphana dashboard.

**Reasons**
- Knative is an essential foundation component in Kyma, we need to know when it's suffering.
- This will ease the support and operations for Kyma by providing visibility into a key Kyma component.

**Acceptance Criteria**
- Verifying prometheus and graphana are working for knative.
- [stretch goal] Knative have alerts rules configured.
- [stretch goal] Knative send its metrics to Kyma prometheus and graphana.

**Comment by pbochynski** [comment]
Please use the issue template and provide description, reasons and acceptance criteria.

**Comment by lszymik** [comment]
We are closing it as there is no progress.
