### ISSUE TITLE
The registered API specification must be stored in the file with a proper extension.

### ISSUE THREAD

**Issue by lszymik** [kyma-project/kyma#3010]
**Description**

If the registered specification of API has the XML format than filename must have the extension `.xml`. Otherwise, the extension name must be `.json`.

**Reasons**

It is required by the OData rendering tooling.

**Acceptance criteria**
- The file extension is determined by the format
- The discovery of a specification type is minimal - it is enough to check the first character of the file `<` or `{` :)

**Comment by Disper** [comment]
Will be fixed in #2927
