### ISSUE TITLE
Assure backup/restore configuration works as expected

### ISSUE THREAD

**Issue by PK85** [kyma-project/kyma#3012]
**Description**

Check if backup/restore configuration works as expected for gophers scope.

Details, here: https://github.com/kyma-project/kyma/issues/2994

AC:
- Prepare EventActivation then test if exists
- Prepare ApplicationMapping then test if exists
- Preapre UsageKind then test if exists
- reuse prepare test for ServiceCatalog, HelmBroker,  ApplicationBroker domain from upgrade
- Assure that all tests work as expected. If needed, apply required fixes into a backup/restore configuration

**Comment by PK85** [comment]
@polskikiel Please please describe all issues what doesn't work in backup/restore procedure.

**Comment by polskikiel** [comment]
We can restore HB ServiceInstances doing the following steps: 
- create necessary resources in some namespace and create a backup
- after backup is successful we have to delete that namespace and also delete the HB's etcd and its PV.
- with that fix: https://github.com/kyma-project/kyma/pull/3346, the restore will be executed correctly.

Why we can't restore ServiceCatalog etcd?
- after deleting SC's etcd - the apiserver becomes unavailable and the namespace deletion is blocked.
- we can delete SC's APIservice to unblock namespace deletion but the SC part won't be restored by ARK.
