### ISSUE TITLE
Update Kyma installation to install Knative by default

### ISSUE THREAD

**Issue by abbi-gaurav** [kyma-project/kyma#3017]
> **NOTE**
- **keep the non-knative deploy as a feature flag**

- **Ensure upgradability can be supported**

**[2019-03-25]**
What is expected of upgradability?
* Post 0.9 Kyma will get installed with Knative as default.
* Imagine a customer having 0.8 Kyma release running. Now when they upgrade to 0.9, they should not see any issues. e.g. with a Kyma subscription created with 0.8. It should still work after upgrading to 0.9.

How to simulate the upgrade from 0.8 to 0.9 (or your branch or wherever your changes), you need to check with gophers.

>**Note:** The Upgrade should be verified on a cluster. 

**Pending Items**
- Fix upgradability (delete volume during upgrade).
  - > **Note**: This action is only for any lower release to 0.9. For 0.9 to higher, no volume will be deleted.
- Fix GKE installation issue
- Fix configmaps, secrets

**AC**
- [ ] The default installation of Kyma should install Knative serving, Knative eventing and components build on top of Knative by default

**Comment by montaro** [comment]
@abbi-gaurav Please, provide some information about 

- What's meant by *ensure upgradability can be supported*
- By having knative components installed by default, is this exclusively means having what's installed when we use `--knative` now, installed by default, or is there any more requirements to be installed/added in the default installation?

**Comment by abbi-gaurav** [comment]
@montaro here's what it means

* Post 0.9 Kyma will get installed with Knative as default.
* Imagine a customer having 0.8 Kyma release running. Now when they upgrade to 0.9, they should not see any issues. e.g. with a Kyma subscription created with 0.8. It should still work after upgrading to 0.9.

How to simulate the upgrade from 0.8 to 0.9 (or your branch or wherever your changes), you need to check with gophers.

**Comment by montaro** [comment]
> @montaro here's what it means
> 
>     * Post 0.9 Kyma will get installed with Knative as default.
Yes. I mean, whatever is installed now with `--knative` should be installed by default, or is there any charts need to be installed in addition?

**Comment by abbi-gaurav** [comment]
Here is the documentation link that could be helpful https://kyma-project.io/docs/master/root/kyma/#installation-update-kyma

**Comment by radufa** [comment]
Tested on Linux and Windows. A small, already corrected issue was found on Windows for "-disable-knative" installation

**Comment by abbi-gaurav** [comment]
Currently, PR #3403 is stuck on the CI test failures.

```
RUNNING: test-logging-logging
FAILED: test-logging-logging, run `kubectl logs test-logging-logging --namespace kyma-system` for more info
Error: 1 test(s) failed
```

There has been a ticket created #3435 for the same.
