### ISSUE TITLE
Enable using a different messaging middleware instead of NATSS

### ISSUE THREAD

**Issue by abbi-gaurav** [kyma-project/kyma#3018]
**Description**
As an operator, I want to configure a default messaging middleware that my Kyma cluster should use for eventing.

https://github.com/kyma-project/community/blob/master/sig-and-wg/sig-core/proposals/knative-eventing-default-pubsub.md

> Note: The changes made by the operator should not get lost on an upgrade of the Kyma version.

**Note**
- configure NATS Streaming as the default provisioner OOTB
- update event bus to start creating channels with default provisioner

**AC**
- [x] It should be possible to configure a default messaging middleware(e.g. Google PubSub) other than NATS Streaming

**Comment by sayanh** [comment]
@abbi-gaurav Please find the final documentation here https://kyma-project.io/docs/master/components/event-bus/#tutorials-configure-default-clusterchannelprovisioner
