### ISSUE TITLE
Consistent naming for eventing production components

### ISSUE THREAD

**Issue by abbi-gaurav** [kyma-project/kyma#3024]
>Note:
The names need to be discussed with @a-thaler 

This might involve changes in

* publish-knative
* subscription-controller-knative

Refer to driving topic https://github.com/kyma-project/kyma/issues/2502

**AC**
- [ ] The eventing production components have been renamed consistently.

**Comment by sayanh** [comment]
@anishj0shi Just found this https://github.com/kyma-project/kyma/pull/4940/files will have an impact in this story

**Comment by sayanh** [comment]
@anishj0shi Just found this https://github.com/kyma-project/kyma/pull/4940/files will have an impact on this story

**Comment by anishj0shi** [comment]
@sayanh not really, its just a schema definition for values.yaml, we do not touch values.yaml of the event-bus Helm-chart and there's no schema defined for the subcharts. we could probably take that.

**Comment by sayanh** [comment]
@anishj0shi Are you sure? I was referring to things like: https://github.com/kyma-project/kyma/pull/4940/files#diff-cb1cb3989a11d1ed1772f967c6f80b5cR10 and https://github.com/kyma-project/kyma/pull/4940/files#diff-cb1cb3989a11d1ed1772f967c6f80b5cR43

**Comment by anishj0shi** [comment]
> @anishj0shi Are you sure? I was referring to things like: https://github.com/kyma-project/kyma/pull/4940/files#diff-cb1cb3989a11d1ed1772f967c6f80b5cR10 and https://github.com/kyma-project/kyma/pull/4940/files#diff-cb1cb3989a11d1ed1772f967c6f80b5cR43

yea, that seems to be schema for this https://github.com/kyma-project/kyma/blob/master/resources/event-bus/values.yaml#L23 and https://github.com/kyma-project/kyma/blob/master/resources/event-bus/values.yaml#L44

**Comment by sayanh** [comment]
And with the new naming convention, `subscriptionControllerKnative` and `publishKnative` are not valid. Right?

**Comment by anishj0shi** [comment]
yea, i should probably update the reference variable names as well.

**Comment by anishj0shi** [comment]
@sayanh Also FYI 
> https://github.com/kyma-project/kyma/pull/4940#issuecomment-514198618
