### ISSUE TITLE
Add tests to verify eventing works post backup and restore

### ISSUE THREAD

**Issue by abbi-gaurav** [kyma-project/kyma#3025]
**Description**
On doing a restore, there are tests to verify that Kyma eventing works with pre-restore subscriptions.

Refer to the epic details for description #2994.

The tests are written and verified against Knative

Tests are run in a GKE cluster which needs to be installed.

**AC**
- [x] There are tests that verify that created Kyma subscriptions are restored and usable.

**Comment by sayanh** [comment]
Instructions on how to test: https://github.com/kyma-project/kyma/issues/4157#issuecomment-496850896

**Comment by marcobebway** [comment]
There is a cluster to test event-bus backup [here](http://35.246.221.4/?job=event-bus-kyma-gke-end-to-end-test-backup-restore).

The verification is not complete yet, and the backup test fails with the following error:
```
TestResources() failed with: Cannot get Kyma subscription, name: test-sub
```
