### ISSUE TITLE
HELM is not usable through Kyma generated kubeconfig

### ISSUE THREAD

**Issue by akrausesap** [kyma-project/kyma#3027]
Dear Colleagues,

when using a kyma generated kubeconfig file, helm becomes unusable and yields the following error for the following command:

```helm install --name first-mongo --set "podAnnotations.sidecar\.istio\.io/inject='false',persistence.size=2Gi" stable/mongodb --namespace personservice```

Result: 
```Error: forwarding ports: error upgrading connection:```

When using a native kubeconfig file with admin rights it works. This behaviour to me seems 0.7 specific.

Best Regards

Andreas

**Comment by pbochynski** [comment]
Port forwarding never worked with the kubeconfig downloaded from UI. This kubeconfig is configured with api-server proxy which doesn't support SPDY protocol. But there is a good news - the support for SPDY was added to resolve issue #1989. It is already merged to master.

**Comment by akrausesap** [comment]
Thanks! wasn‘t aware those are correlated. Master means 0.8?

This is quite important for running a training on our clusters 😉

Am 12.03.2019 um 14:33 schrieb Piotr <notifications@github.com<mailto:notifications@github.com>>:


Port forwarding never worked with the kubeconfig downloaded from UI. This kubeconfig is configured with api-server proxy which doesn't support SPDY protocol. But there is a good news - the support for SPDY was added to resolve issue #1989<https://github.com/kyma-project/kyma/issues/1989>. It is already merged to master.
