### ISSUE TITLE
Not able to install Kyma in minikube

### ISSUE THREAD

**Issue by aamol** [kyma-project/kyma#3030]
I am trying to install on a linux server with centos 7. I have installed minikube and now trying to install Kyma using the documentation available on https://kyma-project.io/docs/#installation-install-kyma-locally-from-the-release 

When I execute ./scripts/is-installed.sh statement it shows failure. I have tried the re-installation step multiple times but same issue. 

First time the installation failed in installing core component. But second time onwards it is failing after Overrides used for update of component istio-kyma-patch and the error coming is 

```
2019/03/07 03:30:00 Step error:  Details: Helm upgrade error: context deadline exceeded
2019/03/07 03:30:00 Error during install/update:  Details: Helm upgrade error: context deadline exceeded
E0307 03:30:00.115144       1 controller.go:286] Helm upgrade error: context deadline exceeded
2019/03/07 03:30:00 ######################################################################
2019/03/07 03:30:00 #### Retries does not seem to work. Manual action is recommended. ####
2019/03/07 03:30:00 ######################################################################
2019/03/07 03:30:00 Warning: Retry number 358 (sleeping for 60[s]).
2019/03/07 03:31:00 ---------------------------
2019/03/07 03:31:00 Get Kyma Sources
2019/03/07 03:31:00 ---------------------------
2019/03/07 03:31:00 Kyma sources available locally.
2019/03/07 03:31:00 Get Kyma Sources...DONE

```

Let me know if anymore information is required.
Kyma versio used : 0.7.0
Linux Centos 7

Also i am not able to join the slack channel

**Comment by sjanota** [comment]
Could you provide more logs? Especially important is the first error in core you mentioned.

**Comment by derberg** [comment]
@aamol Hey, I'd love to help you our with Slack. What issue you have exactly, how you try to sign up, what is not working, what errors?

**Comment by lszymik** [comment]
I have the same issue now. I would like to install the 0.7 release and I am getting always "Helm error: context deadline exceeded". I am using GCP.

**Comment by piotrmsc** [comment]
@aamol I will close this issue. If you find similar issues with the latest release feel free to create issue ;-)
