### ISSUE TITLE
Create upgrade framework based on backup/restore one

### ISSUE THREAD

**Issue by PK85** [kyma-project/kyma#3044]
**Description**

We need to provide basic framework by which all components could be tested in two phases:
- prepareData
- executeTest

AC:
- use as much as possible from backup/restore framework to keep it similar
- enable others to add their tests per component
- define where to provide tests
- integrate upgrade framework with existing prow update pipeline

**Comment by mszostok** [comment]
| Topic | PR |
|-------|----|
| Create backup/restore component with bussines logic       |    |
| Define release/check prow jobs for backup/restore component     |    |
| Adjust upgrade pipeline      |    |
