### ISSUE TITLE
Assure that Service Catalog works as expected after upgrade

### ISSUE THREAD

**Issue by PK85** [kyma-project/kyma#3045]
Description

Check if Service Catalog works as expected when Kyma is updated to the newer version.

AC:
HelmBroker:
- Prepare
  - create redis (SI) and example deployment with redis client for Helm Broker
  - add a key to redis
  - create SB, SBU to deployment
- Test
  - check deployment and redis env variables
  - call redis
  - delete SBU, and check if deployment has no env variables
  - delete SB, 
  - delete SI,
  - call redis and fail, not found

ApplicationBroker:
- Prepare
  - create Application with one API and Events
  - create example deployment
  - ApplicationMapping to test namespace
  - SI for API
  - SI for Events
  - SB, to SBU of API and Events to example deployment
- Test
  - Check if EventActivation exists
  - Check if example deployment has GATEWAY_URL
  - delete SBU for API and check if example deplo has not GATEWAY_URL
  - delete SB for API
  - delete SI for API, Events
  - check if EventActivation is deleted
  - delete ApplicationMapping, Service Classes should be gone

Assure that all tests work as expected. If needed, apply required fixes into components configuration

**Comment by piotrmiskiewicz** [comment]
The testing scenario for the Helm-Broker:
Prepare Data:
 - create a Redis Service Instance
 - create a deployment which prints environment variables to standard output (env tester)
 - wait for the env tester to be ready
 - wait for the Redis instance to be ready
 - create binding and wait to be ready
 - create binding usage and wait to be ready
 - save a value in the Redis (get Redis credential, extract host, port and password, connect to Redis and execute command "SET")
Execute Test:
 - check if the env tester contains environment variable injected
 - check the Redis DB contains stored value
 - delete binding usage
 - check the env tester does not contain Redis environment variable
 - delete the binding
 - delete the Redis Service Instance
 - delete env tester deployment
 - check the Redis instance is removed
 - check all pods are removed
 - c
