### ISSUE TITLE
Prepare a proposal for dynamic configurable monitoring and alerting support for Kyma components

### ISSUE THREAD

**Issue by Abd4llA** [kyma-project/kyma#3052]
**Description**
Explore the idea of introducing a set of labels for Kyma components that enable and disable alerts rules and dashboards based on various criteria and provide a proposal if applicable. 

**Reasons**
- Kyma includes a number of different components that can be generically categorized into a few categories (controllers, RESTful service..etc) and so they share common monitoring and alerting profile.
- If applicable, will reduce significantly the amount of work needed to enable monitoring and alerting. 

**Acceptance Criteria**
- A proposal is created and reviewed.

**Comment by lszymik** [comment]
First, we need to make a proposal.
