### ISSUE TITLE
API specification should be fetched even if protected with credentials.

### ISSUE THREAD

**Issue by lszymik** [kyma-project/kyma#3069]
**Description**

Application Registry is able to fetch the specification of the API using `specificationUrl` field. We need to add the authentication methods to the setup and call. 

**Reasons**

There are cases where clients are integrating systems which are working with the private API. Not all system are following Open-API approach.

**Acceptance criteria**

- [ ] Technical solution discussed (fetch asset, if 401 or 403 then fetch with credentials which are added to specUrl, try to use credentials from the endpoint, ...)
- [ ] Fetching of a specification which is protected added to the metadata service.
- [ ] The API spec and documentation updated (please mention what is more important inline spec or specUrl because customers are frequently asking for it. Please also mention that after fetching private API it will be visible in Service Catalog UI).
- [ ] Functionality tested - might be a simple test.
- [ ] The same set of authentication method as for a proxy calls must be supported.
- [ ] Please also check the cost of supporting additional query parameters and headers with the calls to specUrl.

**Assumptions**

- The authentication storage code will be reused.
- The method for adding security to calls will be reused. It might be a new library which will be used by the Proxy service and Application Registry service
- The documentation must describe the cases what is taken in which order.

**What is also important**
- As soon as the development team will discuss internally possibility and cost of enhancement, it must be discussed during SIG meeting with @brendandobbs and @akrausesap. Just to double check that we will deliver really useful functionality

**Comment by Disper** [comment]
We should discuss how to pass credentials.

**Comment by brendandobbs** [comment]
"Please also check the cost of supporting additional query parameters and headers with the calls to specUrl." - this is actually really important. More and more we see different applications and services that custom headers/query params are used for accessing APIs and that includes fetching the spec.
