### ISSUE TITLE
Validate Upgrade Process for Monitoring Components

### ISSUE THREAD

**Issue by joek** [kyma-project/kyma#3072]
Description:

Validate the correct upgrade of monitoring components

AC:
- No data loss
- Dashboards are still working
- Custom Dashboards are still present
- Service Monitors are still collecting data

Reason:

Because... we should be able to upgrade?

**Comment by sayanh** [comment]
After applying,
```
helm upgrade monitoring monitoring/ --set global.isLocalEnv=false --set global.alertTools.credentials.victorOps.apikey="" --set global.alertTools.credentials.victorOps.routingkey="" --set global.alertTools.credentials.slack.channel="" --set global.alertTools.credentials.slack.apiurl="" --set global.domainName=atx-upgrade.kyma.online --set global.ingress.domainName=atx-upgrade.kyma.online --namespace=kyma-system --debug
```
The upgrade was smooth. The pods were healthy.
```
monitoring-exporter-kube-state-9d9f6875f-ndn4h   2/2     Running   0          87m
monitoring-exporter-node-dmtx9                   1/1     Running   0          87m
monitoring-exporter-node-l2mnc                   1/1     Running   0          87m
monitoring-exporter-node-qprzz                   1/1     Running   0          87m
monitoring-grafana-0                             2/2     Running   0          73m
prometheus-monitoring-0   3/3     Running   1          73m
```

The data is not there in the following dashboards:
Kubernetes / Persistent Volumes
Kubernetes / USE Method / Cluster
Kubernetes / USE Method / Node
Ark
Istio Service Dashboard
Istio Galley Dashboard
Istio Pilot Dashboard


Alerts in configmap are missing:
resources/monitoring/charts/alert-rules/templates/alert-rules-configmap.yaml

**Comment by sayanh** [comment]
Checklist:
- [ ] No data loss 
- [ ]  Dashboards are still working
- [ ]  Custom Dashboards are still present
- [ ] Service Monitors are still collecting data
