### ISSUE TITLE
Spike: Migration of Monitoring components from Kyma 0.7 to 0.8

### ISSUE THREAD

**Issue by joek** [kyma-project/kyma#3073]
Test Upgrade of Monitoring Components to identify tasks and challanges.

Components:
- Prometheus
- Grafana
- Prometheus-Operator

**Comment by rakesh-garimella** [comment]
Changes for Prom Upgrade
1. *Installation of CRDs:* We will use`get-crd-job`
2. *Prometheusrules:* We need to migrate all the alert rules to Prometheus rules
3. *Alert Rules:* They have been re ordered (all have been moved to prometheus/rules)
    Lots of missing metrics:
    scheduler_e2e_scheduling_latency_microseconds
    kubernetes rules are different
    API server alerts have been removed.
    K8s storage.
4. We will not add Pod Security Policy and Pod Disruption Policy as they are not affect cluster wide pod deployments .
5. We would need grafana service account.
6. Alert manager alerts every 10mins if previous alert was delivered successfully.
