### ISSUE TITLE
Support for API Metadata Access (OData/Open API) in bound Lambda / Deployment

### ISSUE THREAD

**Issue by akrausesap** [kyma-project/kyma#3103]
**Description**

Dear Colleagues,

In order to generate OData/Open API language specific clients, access to the metadata is required. As it is stored in Mino it should also be made available to bound Lambdas and Deployments in a standard fashion.

Thanks

Andreas
 

**Reasons**

Generate language specific clients to increase extension developer productivity

**Attachments**

N/A

**Comment by PK85** [comment]
@derberg please elaborate from where ApplicationBroker could get such information to put that to SB later on.

**Comment by derberg** [comment]
afaik Application CR contains a list of service classes that later on are visible in the Service Catalog. These classes have unique name, and the same name is used to create ClusterDocsTopic that later on create Asset that contains the link to the spec

So grab from application name of the service, check if there is ClusterDocsTopic with the same name, and what sources it has and check Assets created by this ClusterDocsTopic and grab the links and do with them whatever you want :)

**Comment by derberg** [comment]
but to have clean architecture maybe you should not have this knowledge at all and the Application CR should already have those links in it. Just an opinion

**Comment by pbochynski** [comment]
I think the issue is not valid anymore. Lambda should not fetch API spec in the runtime (with every invocation). If you need to build a client it should be done in the design time - I can imagine some plugin to the IDE (or lambda editor) that generates a client.
