### ISSUE TITLE
Add OKLog to kyma

### ISSUE THREAD

**Issue by joek** [kyma-project/kyma#313]
As a administrator I expect logs to be stored at a central place for a longer time.
 

Tools: OKLog, logspout

Retention Period: 7Days

AC:

- All logs are stored in OKLog
- Log is tested with custom integration test 
- Have Alerts for disk (80%) and memory (90%)

**Comment by sayanh** [comment]
Subtasks:
- [ ] Helm charts for local installation 
- [ ] Test client for logging setup
- [ ] Configure alerts
- [ ] Documentation
- [ ] Tune cluster build with logging installation

**Comment by sayanh** [comment]
Known issues to fix:

- [ ] Probable memory request limit as oklog goes to `Crashbackloop` after few minutes of deployment
- [ ] `failed to create fsnotify watcher: too many open files%`

**Comment by sayanh** [comment]
- [ ] Add namespace and pod information to the logstream to oklog

**Comment by rakesh-garimella** [comment]
Documentation has been fixed via following PR: https://github.com/kyma-project/kyma/pull/924
