### ISSUE TITLE
Connector Service Test should remove test certificates from revocation list once it is completed

### ISSUE THREAD

**Issue by akgalwas** [kyma-project/kyma#3163]
**Description**

Connector Service Test exercises revocation in the following way:
- Creates a new certificate
- Revokes the newly created certificate

As a result revocation list gets bigger after each tests run. We should remove items from revocation list after test completed.

**Reasons**

The test should clean up the cluster after completion.

**Comment by janmedrek** [comment]
Connector service will be rewritten to implement GraphQL API, tests will be changed as well.
