### ISSUE TITLE
Add support for cluster wide catalog resources

### ISSUE THREAD

**Issue by derberg** [kyma-project/kyma#318]
Confirm these statements before you submit the issue:

- [x] I have searched open and closed issues for duplicates.
- [x] I have read the contributing guidelines.
---

**Description**

- [x] Add to ui-api-layer query to support for ClusterServiceBrokers and ClusterServiceClasses
- [x] Add 2 new subscription for ServiceBrokers and ClusterServiceBrokers that will be used when listing ServiceBrokers and their status, the namespaced ones and the cluster ones.
- [x] Update UI for catalog and brokers to use new resources. We will be back for websockets for service brokers view once we actually implement it.
- [x] present possible solution to the team and discuss it 

**Reasons**

To support in UI namespaced Service Catalog

**Comment by pkosiec** [comment]
Review: @michal-hudy @magicmatatjahu
