### ISSUE TITLE
Add a Bash script that enables sub-components

### ISSUE THREAD

**Issue by jakkab** [kyma-project/kyma#319]
AC:
- manage-component.sh consumes two parameters: name of a sub-component and a boolean;
- it creates a file called 'components.yaml' and saves the provided values;
- if the file already exists, the script appends the values;
- 'components.yaml' should not be checked into git (add to .gitignore).

**Comment by strekm** [comment]
components.yaml shoulg be not checked-in (add to gitignore)

**Comment by jakkab** [comment]
@strekm AC updated;
