### ISSUE TITLE
Application Broker does not remove Services when namespace with Mapping is removed

### ISSUE THREAD

**Issue by aszecowka** [kyma-project/kyma#3192]
On a weekly cluster, where Stability Checker is executed, there are 121 Services in `kyma-integration` namespace. Most of them have following name pattern: 
- `ab-ns-for-svc-test-ns-2rctp` or 
- `ab-ns-for-test-acc-ns-broker-zcb9`.
Services with name pattern `ab-ns-for-test-acc-ns-broker` are created as a result of the `TestServiceCatalogContainsABServiceClasses` (`kyma/tests/acceptance/servicecatalog/servicecatalog_test.go`). 
At the end of the test, a testing namespace is removed. Removing namespace cause removing Application Mapping, and on that event, Mapping Controller (`kyma/components/application-broker/internal/mapping/controller`) is triggered. 
There is a method:
`ensureNsBrokerNotRegisteredIfNoMappingsOrSync`
which at the beginning check if broker in the given namespace exists, if not, we exit from the function with no error. 
But, when removing namespace, we don't have any gurantees that mapping will be removed before broker. So in our test, we remove namespace, then k8s removes at the beginning broker, then mapping and our controller forgets to remove Services.

**Comment by PK85** [comment]
one of the solution: provice ownerReference in k8s service to ServiceBroker instance, when removed problem is gone.
