### ISSUE TITLE
Extend asset store official docs with info on how to setup minio gateway

### ISSUE THREAD

**Issue by derberg** [kyma-project/kyma#3199]
**Description**

- make it clear in docs (if not yet done) that Kyma starts with Asset Store in Minio standalone setup because of batteries-included rule in Kyma.
- make it clear we recommend that for production use  (if not yet done) we say minio gateway is the way to go
- have a document that explains what to do after installation to make sure Minio is switched to gateway
- make it clear that we do not offer a scalable configuration of minio as a storage in Kyma cluster, you can use minio as storage for development but for production you should switch to minio gateway mode. Input is already here https://github.com/kyma-project/kyma/tree/master/resources/assetstore#change-minio-to-the-google-cloud-storage-gcs-gateway-mode

**Reasons**

We recommend to use Asset Store with minio in gateway mode, we need to have good docs for it in main docs

**Comment by mmitoraj** [comment]
Info included in the 1st, ,2nd and 4th dots of the issue description were actually already included in the official docs on kyma-project.io. See https://kyma-project.io/docs/components/asset-store/#details-minio-and-minio-gateway

**Comment by derberg** [comment]
make it also clear in the docs that we do not support migration of content that is already stored in minio and then user switches to minio gateway. Also technically check what actually happends with files that are already in minio and then minio is kicked to use gateway
