### ISSUE TITLE
Console Backend Service tests failed because pod was not deleted

### ISSUE THREAD

**Issue by michal-hudy** [kyma-project/kyma#3203]
**Description**

During testing queries/mutations for pods, test failed while waiting for pod deletion. It was not deleted in 60s.

**Expected result**

Pod should be deleted.

**Actual result**

Sometimes pod is not deleted.

**Steps to reproduce**

https://status.build.kyma-project.io/view/gcs/kyma-prow-logs/logs/post-master-kyma-integration/1106567048978239490

**Troubleshooting**

**Comment by lszymik** [comment]
The issue was solved.
