### ISSUE TITLE
Improve console backend service acceptance tests logging

### ISSUE THREAD

**Issue by tgorgol** [kyma-project/kyma#3216]
**Description**

Improve console backend service acceptance tests by logging more useful information about cause of failed tests, such as:
- Kubernetes resource (eg. Pod) status in case of timeout during deletion of said resource

**Reasons**

Often when acceptance tests fail on CI it is hard to tell what might be the cause and it's not possible to access test Kubernetes cluster to check state/logs of containers inside it. Having more detailed logs would greatly improve troubleshooting.

**Comment by derberg** [comment]
Confirmed with @tgorgol that this one can be closed
