### ISSUE TITLE
Remove temporary job after release 0.9

### ISSUE THREAD

**Issue by Demonsthere** [kyma-project/kyma#3242]
**Description**

The job introduced in https://github.com/kyma-project/kyma/pull/3225 is required only for a seamless upgrade. However, after release 0.9 it won't be needed anymore, and can be deleted. 

**Reasons**

As we were forced to move a resource from one chart to another, an upgrade job was required. Once the resource is a part of a new release, the job can be deleted. 

**Attachments**

**Comment by lszymik** [comment]
@Demonsthere 
Can you please apply labels, milestone and description.

Thanks.

**Comment by piotrmsc** [comment]
We should remove nginx migration job as well
