### ISSUE TITLE
Kyma installation from a release documentation bug

### ISSUE THREAD

**Issue by montaro** [kyma-project/kyma#3262]
In https://kyma-project.io/docs/master/root/kyma/#installation-install-kyma-locally-from-the-release, the documentation states: 
> Wait until the `kube-dns` Pod is ready. Run this script to setup Tiller:

However `kube-dns` pod will not run anymore

**Comment by klaudiagrz** [comment]
I guess we can close this issue, as the installation document has been totally restructured.
@tomekpapiernik what do you think?

**Comment by tomekpapiernik** [comment]
Yes, this is no longer a problem.
