### ISSUE TITLE
Incorrect event schema examples

### ISSUE THREAD

**Issue by pbochynski** [kyma-project/kyma#3273]
**Description**
In the Service Catalog event schema contains double attribute names.

**Expected result**
```
{
    "orderCode": "76272727",
    "orderStatus": "CHECKED_INVALID"
}
```

**Actual result**
```
{
  "orderCode": {
    "orderCode": "76272727"
  },
  "orderStatus": {
    "orderStatus": "CHECKED_INVALID"
  }
}
```

**Steps to reproduce**
Register SAP Commerce events, bind it to some namespace and open it in the Service Catalog.

**Comment by derberg** [comment]
This is what I see with latest version of the asyncapi from commerce application that I know

<img width="973" alt="Screen Shot 2019-03-21 at 11 22 57" src="https://user-images.githubusercontent.com/6995927/54746143-b6461000-4bcb-11e9-92ed-5e643aa52341.png">

**Comment by derberg** [comment]
We can do to much here
the error is probably comming from

**Comment by derberg** [comment]
@pbochynski I would close it as invalid, or am I missing something?

**Comment by pbochynski** [comment]
Yes - it is not bug in the kyma. It is problem with the specification we got.
