### ISSUE TITLE
Create a websocket enabled VirtualService 

### ISSUE THREAD

**Issue by brendandobbs** [kyma-project/kyma#3275]
**Description**

To support websockets the VirtualService needs to be configured with `websocketUpgrade=true`. See this example https://github.com/istio/istio/blob/master/samples/websockets/route.yaml

We could allow for the developer to decide if they want a websocket connection when they create an Api CR (websocket checkbox?)

**Comment by piotrmsc** [comment]
We should support it on API CR level and enable setting it in the console (UI).
The property name can have the same name  "websocketUpgrade"

**Comment by piotrmsc** [comment]
Istio enabled it by default and with the latest upgrade, it works OOTB
