### ISSUE TITLE
Improve readme in backup-restore-test

### ISSUE THREAD

**Issue by polskikiel** [kyma-project/kyma#3287]
**Description**

Usage section in this readme:  `kyma/tests/end-to-end/backup-restore-test/backup-restore.md` is inadequate. It should have information on how setup cluster with all required components and secrets to develop this test locally.

**Reasons**

The actual description of the usage section looks like this...
```
Use the following command to run the test:

helm install deploy/chart/backup-test --namespace end-to-end --name backup-test
helm test backup-test
```
...and every developer has to contrive what he needs, to run this test properly.

**Solution**

- Cluster setup needs ARK deployment with secrets to azure (how to get them?).
- Instead of `helm test backup-test` user can use `go test ./... -count=1 -timeout=45m`
- Helm broker test needs to be run with telepresence.

**Comment by joek** [comment]
@polskikiel have you figured out what to do? Maybe you can simply add the information and create a pull request.

**Comment by polskikiel** [comment]
@joek I've updated ticket with all necessary information for a Technical Writer to do this task.

**Comment by bszwarc** [comment]
I'm gonna work on this - @polskikiel , if you have any questions let me know.

**Comment by bszwarc** [comment]
Goal: 
- create a proper README.md file replacing [this](https://github.com/kyma-project/kyma/blob/master/tests/end-to-end/backup-restore-test/backup-restore.md) document.
- improve the file by adding information from https://github.com/kyma-project/kyma/tree/master/resources/ark and https://github.com/kyma-project/kyma/tree/master/docs/backup/docs 

Questions: where to put internal instructions - TBD

Follow up: 
- improve the rest of the backup docs (separate task)
