### ISSUE TITLE
Namespace controller does not delete resourcequotas if a namespace is modified

### ISSUE THREAD

**Issue by jakkab** [kyma-project/kyma#3314]
**Description**

Namespace controller does not delete resourcequotas when the "env=true" label is removed from a namespace.

**Expected result**

Namespace controller deletes the "kyma-default" resourcequota when the "env=true" label is removed from a namespace.

**Actual result**

Resourcequota is still there.

**Steps to reproduce**

```
kc create ns my-namespace
kc label ns my-namespace env=true (resourcequota is created here)
kc label ns my-namespace env=false (resourcequotra should be deleted here)
kc get resourcequota -n my-namespace kyma-default (still here)

**Comment by piotrmsc** [comment]
with this PR https://github.com/kyma-project/kyma/pull/4383 namespace controller have been removed from resources and is no longer installed (code cleanup still needs to be done). So now it is no longer valid as the component is not installed
