### ISSUE TITLE
Istio Ingress Performance

### ISSUE THREAD

**Issue by phoenix086** [kyma-project/kyma#3319]
**Description**
During load testing of kyma with wrk (https://github.com/wg/wrk) we faced some performance downsides when using istio sidecar/istio ingress. Find the results in this gdoc: https://docs.google.com/document/d/1h78Wi_nyXQLDrWq5LpoqAI6WbJTWkEaCvjIqoNI0JOg/edit?usp=sharing. The testcases tested different setups and its impacts on the performance.

- Kyma Cluster 0.8 deployed on GCP
- App: simple GOlang service with 1 GET endpoint that is just returning its input, no dependency to other resources
- wrk was executed on a VM in another GCP cluster (other geolocation in europe)

**Expected result**
We expected some performance impacts when using istio but not that serious ones. Some issues could be resolved (see test results), one is still there.

**Steps to reproduce**

build/deploy this sample app:

https://github.com/phoenix086/kyma-go-sampleapp

**Comment by piotrmsc** [comment]
CC @hisarbalik

**Comment by lszymik** [comment]
@piotrmsc Can you check it and maybe ask @hisarbalik and/or @a-thaler

**Comment by strekm** [comment]
addressed in https://github.com/kyma-project/kyma/issues/6646
