### ISSUE TITLE
Make 0.9 Kyma release

### ISSUE THREAD

**Issue by derberg** [kyma-project/kyma#3330]
**Description**

- prepare release jobs
- communicate how release will be done, and also communicate clearly each stage of release. Whole communication should be done on `kyma-community` workspace in `general` room
  - 1.04 prepare release branch
  - 3.04 prepare RC1
  - 5.04 prepare RC2
  - 8.04 release 0.9

**Comment by jose-cortina** [comment]
Release process and dates agreed with @derberg
