### ISSUE TITLE
API Registration: If specificationurl is not resolvable, we get 502 and no error message

### ISSUE THREAD

**Issue by pbarbier** [kyma-project/kyma#3335]
Description

When registering an API to kyma we specify its api spec via the specificationUrl attribute.
If we provide an url that is not reachable by Kyma (local server not seen on the internet or firewall blocking it) then we get a HTTP 502 code as error response with an empty response body

We'd need the response body to contain a human readable error message concise enough to explain the API spec is unreachable

Reasons

Right now the Commerce user gets an error code but has no hint about what is the problem

**Comment by Maladie** [comment]
I have checked with the following curl (url in specificationUrl does not exist):
`curl -X POST https://gateway.kyma.local:32513/test-app/v1/metadata/services --cert generated.crt --key generated.key -k -d'{
    "provider": "SAP Hybris",
    "name": "test-proxy-no-auth",
    "description": "httpbin.org",
    "api": {
        "targetUrl": "https://httpbin.org",
        "specificationUrl": "http://sometesturl.test"
    }
}'`

It returned response with the following error message:
`{"code":502,"error":"Determining API spec for service with ID ea6d629c-cf98-42d2-ba36-793597144bd6 failed, Fetching API spec from http://sometesturl.test failed, Get http://sometesturl.test: dial tcp: lookup sometesturl.test on 10.96.0.10:53: no such host"}`

Could you please check if problem still persists? If yes, please provide steps to reproduce the issue.
