### ISSUE TITLE
Document command to check Kyma version before update

### ISSUE THREAD

**Issue by arifC** [kyma-project/kyma#3338]
**Description**
Before updating Kyma to a newer version some users might want to check their current version. It would be helpful if the instructions at https://kyma-project.io/docs/root/kyma/#installation-update-kyma include a command to check the current version. I propose using this one but there might be shorter/better ways as well:

`kubectl -n kyma-installer get deploy kyma-installer -o  jsonpath='{.spec.template.spec.containers[].image}' `

The output looks like this:

`'eu.gcr.io/kyma-project/kyma-installer:0.8.1'`

**Reasons**
Especially when updating Kyma it might be helpful to have a command in the documentation to quickly check the version. Otherwise, every user has to find an own way to check the Kyma version.

**Comment by tomekpapiernik** [comment]
Consider creating an issue that would request adding version information to Console UI.
