### ISSUE TITLE
Fix reconnectivity issue for NATS Streaming controller and dispatcher

### ISSUE THREAD

**Issue by abbi-gaurav** [kyma-project/kyma#3339]
The fix for the re-connectivity is available in master branch for Knative eventing.

**To reproduce**
- Delete NATS Streaming pod
- NATS Streaming controller and dispatcher will fail to connect.

**AC**
- [x] NATS controller and dispatcher should be able to reconnect to NATS Streaming

**Comment by suleymanakbas91** [comment]
I created test images from this PR [#106](https://github.com/kyma-incubator/eventing/pull/106) and used them in a local cluster. They include the security fix, but also re-connection fix and configurable URL and cluster-id feature. I can confirm that the e2e scenario is working even after deleting the nats streaming pod several times.
