### ISSUE TITLE
Add shortcuts to close in-page popups on kyma dashboard

### ISSUE THREAD

**Issue by tehcyx** [kyma-project/kyma#3348]
**Description**
When any link in the kyma dashboard opens an in-page popup (or Lightbox) it is not possible to close these unless you interact with any buttons on the UI. It would be nice if I could cancel any actions by clicking next to the popup into the darkened background or press 'ESC' to close these.
A sample would be "+ Create Application" on this path: https://console.kyma.local/home/cmf-apps
"Connect Application" on this path: https://console.kyma.local/home/cmf-apps/details/<app-name>
"+ Create Binding" on the same path as above. And many more.

**Reasons**
I'd consider it easier to navigate.

**Comment by derberg** [comment]
This is already implemented and will be available in 1.4
