### ISSUE TITLE
Move common logic from Asset Store to commons

### ISSUE THREAD

**Issue by pkosiec** [kyma-project/kyma#3361]
**Description**

- Move common logic from Asset Upload Service and Asset Metadata Service to commons
- Move waiter, signal, etc. packages from Console Backend Module to commons

**Reasons**

DRY.

Similiar to #3238

**Comment by derberg** [comment]
Not valid anymore, we move asset store away from kyma repo

**Comment by derberg** [comment]
AssetStore got refactored and moved away from Kyma repo, so no use of commons is planned
