### ISSUE TITLE
Luigi error while logging in after install

### ISSUE THREAD

**Issue by nderraugh** [kyma-project/kyma#3362]
**Description**
A Luigi error shows up during login after installation when launching the dashboard 

Kyma version: 0.8.1
minikube version: v0.33.0
on mac os x 10.14
Chrome, Firefox and Safari.

**Expected result**
Entering username and password after `open https://console.kyma.local/` results in successful login to Kyma console.

**Actual result**
`Ups.. Looks like Luigi was not configured. Please use Luigi.setConfig(config) function to configure Luigi.`.  The site can't be reached.

**Steps to reproduce**
Followed the installation instructions [here](https://kyma-project.io/docs/root/kyma/#installation-install-kyma-locally-from-the-release) and [here](https://github.com/kyma-project/kyma/releases/tag/0.8.1) and then tried to access the console as indicated [here](https://kyma-project.io/docs/root/kyma/#installation-install-kyma-locally-from-the-release-access-the-kyma-console) I then get the error. 

**Troubleshooting**
Adding ui-api.kyma.local to /etc/hosts seems to work.

**Comment by hardl** [comment]
It seems there is some issue with the renaming from ui-api.* to console-backend.*

**Comment by pkosiec** [comment]
Hey @hardl, the UI API Layer has been indeed renamed to Console Backend Service, but it has been done just on our master branch. Branches `release-0.8` and down should be OK

**Comment by pkosiec** [comment]
Hi @nderraugh, did you run the installation script from `master` branch with values from 0.8.1 release? Because sources for installation scripts on release 0.8.1 look good.

**Comment by nderraugh** [comment]
Ah, yeah, I missed that.  I tried again from the https://github.com/kyma-project/kyma/tree/release-0.8 branch.  No problems.   Thanks.
