### ISSUE TITLE
The Application Connector returns Internal Server Errors when there is no subscriber for an event (Knative)

### ISSUE THREAD

**Issue by JoergBastian** [kyma-project/kyma#3369]
**Description**

In a Knative installation the application connector returns a 500 Internal Server Error when an event is being published for which there is no subscriber (e. g. by a lambda) registered. 

This is caused by the event-bus publishing component. Since there is no subscriber also no channel has been created for the event.

Kyma version: Latest Kyma master (f09ca1a) installed with Knative

The event-bus-publish-pods write to the log:
```
cannot find the knative channel '[event-topic]' in namespace 'kyma-system'
publish message failed: &{500 internal_server_error Some unexpected internal error occurred, please contact support.  []}
```

**Expected result**

A 20x success response is returned to the connected application. If there is no subscriber for the event, the event does not have to be processed, but an Internal Server Error still suggests that something did not work as expected.

**Actual result**

The event bus returns a 500 Internal Server Error to the client, suggesting something unexpected happend:
```
{"status":500,"type":"internal_server_error","message":"Some unexpected internal error occurred, please contact support."}
```

**Steps to reproduce**

Connect an application through the Application Connector and trigger an event there is no lambda or other subscriber for.
Alternatively, trigger an event like in this example: https://github.com/kyma-project/examples/tree/master/event-subscription/service

**Details**

The error is thrown in the file [/components/event-bus/cmd/event-bus-publish-knative/publisher/publisher.go](https://github.com/kyma-project/kyma/blob/master/components/event-bus/cmd/event-bus-publish-knative/publisher/publisher.go#L55), l. 55.

**Comment by abbi-gaurav** [comment]
Fixed with #3454.
