### ISSUE TITLE
The Application Gateway should remove the x-forwarded-proto header

### ISSUE THREAD

**Issue by lszymik** [kyma-project/kyma#3370]
**Description**

The Application Gateway should remove the header `x-forwarded-proto` while proxying calls to a connected application. 

**Expected result**

The `x-forwarded-proto` is not forwarded.

**Actual result**

The header `x-forwarded-proto` is forwarded and some connected applications are rejecting calls.

**Steps to reproduce**

- The header `x-forwarded-proto` is not being sent.
- The information about headers being removed places in README.MD and Kyma documentation.

**Comment by akrausesap** [comment]
Envoy adds some other headers that are meant for Loadbalancer to Server communication (see https://www.envoyproxy.io/docs/envoy/latest/configuration/http_conn_man/headers#x-forwarded-proto). I suggest to remove at least:
