### ISSUE TITLE
apiserver-proxy does not handle upstream CORS 

### ISSUE THREAD

**Issue by sjanota** [kyma-project/kyma#3383]
**Description**

There are implementations of apiserver that provide their own CORS headers. apiserver-proxy does not take it into account and adds CORS to response anyway. In such scenario it may happen that Access-Control-Allow-Origin header will contain two values, one set by upstream apiserver and second set by apiserver-proxy. Browser will reject further requests to apiserver-proxy as two values in this header are forbidden. 

This problem was first observed two days ago on some AKS clusters

**Expected result**

You are able to work with console.

**Actual result**

Console is not working/

**Steps to reproduce**

Easiest to reproduce is to spin AKS cluster with old Jenkins instance.

**Troubleshooting**

In browser you can see that POST requests are rejected by browser as they contain malformed Access-Control-Allow-Origin header in response. In apiserver-proxy logs it is easy to see that upstream sends its own CORS headers that are then forwarded downstream

**Comment by rakesh-garimella** [comment]
@sjanota @piotrmsc  do we have workaround for this issue

**Comment by piotrmsc** [comment]
Remove cors headers from upstream
