### ISSUE TITLE
Adjust Application Registry to take into account recent changes in documentation management.

### ISSUE THREAD

**Issue by akgalwas** [kyma-project/kyma#3394]
**Description**

Adjust the implementation to the recent changes in the area of documentation management:
- update code handling Docs Topic CR
- replace content.json file with a zip containing markdown files

**Reasons**
- Docs Topic CR is currently being redesigned.
- The way of rendering documentation has been changed.

**Comment by janmedrek** [comment]
Please include following changes (if not done in previous task):
- parametrisation of `specRequestTimeout` in asset store-related services
- removing obsolete download client from `components/application-registry/internal/metadata/specification/service.go`

**Comment by akgalwas** [comment]
Mind that the current implementation uses public bucket. We need to change that for private.

**Comment by akgalwas** [comment]
First we need to design a new approach to registering documentation in App Registry API.
