### ISSUE TITLE
Authorization server in Kyma

### ISSUE THREAD

**Issue by piotrmsc** [kyma-project/kyma#3397]
**Description**

Currently, Kyma supports only API authentication and does not offer authorization. Authentication is covered by istio policy which relies on id tokens validation. API Gateway lacks the feature of applying authorization to an exposed API. Internal communication can be covered with istio RBAC rules but it cannot be applied for incoming requests from external services/applications. For developers creating for example lambdas and exposing them to the public internet, it is beneficial to allow service to service communication with autn and authz in place. Moreover, it's not possible to fetch token in service to service without the context of the user.

Solutions to investigate :
- OAuth2 server (https://github.com/ory/hydra)
- OPA (https://www.openpolicyagent.org/)
- Integration with istio one of the solutions
- ...

**Reasons**

Enrich API gateway functionality with authZ capabilities. Allow fetching tokens without the context of the user.

**Attachments**

**Comment by Demonsthere** [comment]
Hydra does not have an official helm chart currently, however this seems to be in the works: https://github.com/helm/charts/pull/12845

**Comment by Tomasz-Smelcerz-SAP** [comment]
There's a question about token validation. Hydra exposes an endpoint /oauth2/introspect for this purpose. We have to call it somehow. Possible options to evaluate:
- Direct call from the target service/lambd code
- Stand-alone proxy. There's one provided by ORY. Should work, but how to integrate it with a lambda is unknown 
- Envoy proxy filter mechanism. We don't know if it works and how to configure it.
