### ISSUE TITLE
Application connector tests failing (post-master-kyma-integration)

### ISSUE THREAD

**Issue by jesusreal** [kyma-project/kyma#3407]
**Description**
Application connector tests failing on _post-master-kyma-integration_ job: https://status.build.kyma-project.io/view/gcs/kyma-prow-logs/logs/post-master-kyma-integration/1111243665184919552. 
```
suite.go:166: --------------------------------------------End of logs from test-operator-app-test-qhm6-event-service-acceptance test--------------------------------------------
suite.go:123: operator-app-test-qhm6 tests failed
suite.go:124: Application tests failed
suite.go:76: Cleaning up...
FAIL
```

**Expected result**
Tests run successfully

**Actual result**
Tests are failing

**Comment by Szymongib** [comment]
Duplicate of #3430
