### ISSUE TITLE
GQL subscriptions don't support directives in console backend service

### ISSUE THREAD

**Issue by tgorgol** [kyma-project/kyma#3412]
**Description**

At the moment gqlgen subscriptions don't support directives ([related issue on gqlgen repo](https://github.com/99designs/gqlgen/issues/259)), which means we are left only with authentication, and no authorization of subscription requests. We should figure out a way to authorize subscription requests as well.

Related task: #3062 

**Expected result**

While handling subscription requests by console backend service, authorization directive should be executed and check if user has sufficient permissions to access specific resource.

**Actual result**

Authorization directive is skipped and resolver is executed instead.

**Steps to reproduce**

Try subscribing to any event that should be protected by `@HasAccess` directive as a user without sufficient permissions.

**Comment by derberg** [comment]
For the time being, we will disable subscription for secrets to mitigate security issue

**Comment by mmitoraj** [comment]
It may be dependent from https://github.com/99designs/gqlgen/issues/259. @michal-hudy is investigating the issue.

**Comment by michal-hudy** [comment]
Latest version `0.9.1` of `gqlgen` doesn't work with our schema, because of https://github.com/99designs/gqlgen/issues/785. Version `0.9.1` contains a potential fix for subscriptions.

**Comment by michal-hudy** [comment]
Since version `0.9.0` mandatory fields are pointers. We will need to make lots of changes because of that - https://github.com/99designs/gqlgen/issues/375

**Comment by sergio-oss** [comment]
@kwiatekus still applicable ?

**Comment by kwiatekus** [comment]
Unfortunatelly yes.

**Comment by kwiatekus** [comment]
The linked issue on gqlgen was fixed. But migration is requiread as the new version introduces breaking changes.
We will add it to 1.12 release. Still, would need to be accepted for now.

**Comment by sergio-oss** [comment]
what is the exact impact ? how do we use subscriptions ?

**Comment by kwiatekus** [comment]
we query data from gql (querries are authorized) and subscribe to changes on the data that was initally fetched.
For example:
1) Query for pods in a namespace-> display pods on the view (requires GET, LIST for pods). Permissions are checked  
2.) Subscribe to changes (new pods, deleted pods) -> changes reflected live in the UI ( required WATCH for  pods)  - this WATCH permission is not checked, as authz check is realized via @hasAccess directive that doesnt work for subscriptions.

Impact is low, as subscription and query require read access on the same resources.
Subscription follows a query operation.
So once subscription is performed, we already know that user has permissions to read a given resource

**Comment by kwiatekus** [comment]
We have [bumped gqlgen](https://github.com/kyma-project/kyma/pull/8620) to version 0.11.3.
This version includes the bugfix for the problem of [unsupported directives](https://github.com/99designs/gqlgen/issues/259).
With that change, the access to subscriptions is verified and protected via our `@HasAccess` directive.
