### ISSUE TITLE
Local installation on Mac fails

### ISSUE THREAD

**Issue by msethi80** [kyma-project/kyma#3413]
Confirm these statements before you submit the issue:

  I have searched open and closed issues for duplicates.
  I have read the contributing guidelines.

**Description**

I am installing Kyma locally on Mac, the current version being 0.8.2. 
I followed the process as mentioned on the page "https://kyma-project.io/docs/root/kyma/#installation-install-kyma-locally-from-the-release" with the correct versions of the various Pre-Requisite components. 
But the installation fails while trying to process the "core" component. I have retried thrice  but the error remains the same. 
The error in the console is : "kyma installation error, description: Processing component core
to fetch the logs from the installer execute: kubectl logs -n kyma-installer kyma-installer-64f5f96dc5-m5qp7".                               

The log file shows the following issues : 
"019/03/28 06:45:58 Step error:  Details: Helm install error: rpc error: code = Unknown desc = Job failed: DeadlineExceeded
2019/03/28 06:45:58 Error during install/update:  Details: Helm install error: rpc error: code = Unknown desc = Job failed: DeadlineExceeded
E0328 06:45:58.974309       1 controller.go:286] Helm install error: rpc error: code = Unknown desc = Job failed: DeadlineExceeded
2019/03/28 06:45:58 Warning: Retry number 1 (sleeping for 10[s])."

**Expected result**

Local installation is completed and accessible.

**Actual result**

Installation fails to process the "core" component during installation

**Steps to reproduce**

- Fresh installation of all tools (Kubernetes, minikube, hyperkit driver)
Pre-Requisites installed :

- Minikube 0.33.0
- kubectl 1.12.0
- Helm 2.10.0
- jq

Virtualization:

- Hyperkit driver

- Kyma release used  -  0.8.2

- Get the installation from the master branch of Kyma from repository

**Troubleshooting**

I tried by removing all components and reinstalling minikube but end result was the same.

**Comment by lszymik** [comment]
We are assuming that it is already fixed. Please re-open if you still see issues with it.
