### ISSUE TITLE
Insufficient quota in GKE cluster

### ISSUE THREAD

**Issue by jesusreal** [kyma-project/kyma#3414]
**Description**
Postsubmit jobs are currently failing. Due to insufficient resource quota in GKE, cluster cannot be created.
```
154 | ERROR: (gcloud.container.clusters.create) ResponseError: code=403, message=Insufficient project quota to satisfy request: resource "FIREWALLS": request requires '3.0' and is short '3.0'. project has a quota of '500.0' with '0.0' available. View and manage quotas at https://console.cloud.google.com/iam-admin/quotas?usage=USED&project=sap-kyma-prow.
```

**Expected result**
There are enough resources available to create the cluster

**Actual result**
The cluster cannot be created since there are not enough resources available

**Steps to reproduce**
Rerun any of the kyma postsubmit jobs from here https://status.build.kyma-project.io/?repo=kyma-project%2Fkyma&type=postsubmit

**Troubleshooting**

Prow logs:
- [post-master-kyma-gke-upgrade](https://status.build.kyma-project.io/view/gcs/kyma-prow-logs/logs/post-master-kyma-gke-upgrade/1111288083862523904) 
- [post-master-kyma-gke-central-connector](https://status.build.kyma-project.io/view/gcs/kyma-prow-logs/logs/post-master-kyma-gke-central-connector/1111288083858329602)
- [post-master-kyma-gke-integration](https://status.build.kyma-project.io/view/gcs/kyma-prow-logs/logs/post-master-kyma-gke-integration/1111288083858329601)

**Comment by lszymik** [comment]
Hello @jesusreal ,

Can you please provide more detailed description of that issue and apply our agreed templated.
Thank you very much.

Lukasz

**Comment by jesusreal** [comment]
@lszymik thanks for your comment. Done.

**Comment by jesusreal** [comment]
Currently jobs are failing but due to a different reason. Cluster is created.

**Comment by mmitoraj** [comment]
Just FYI, I had a similar issue yesterday, I guess `Insufficient project quota to satisfy request: resource "FIREWALLS": request requires '3.0' and is short '1.0'. project has a quota of '500.0' with '2.0' available. View and manage quotas at https://console.cloud.google.com/iam-admin/quotas?usage=USED&project=sap-kyma-pr`. 

Thanks.

**Comment by Demonsthere** [comment]
This has been resolved with the new firewall cleaner: https://github.com/kyma-project/test-infra/issues/711
