### ISSUE TITLE
Provide the capability to dry run an upgrade

### ISSUE THREAD

**Issue by abbi-gaurav** [kyma-project/kyma#3423]
**Description**
The current upgrade process is complex and with any failures in the steps, one can reach a state where the cluster is unrecoverable.

To help the SREs and operators using Kyma, it should be possible to dry run an upgrade and fix any possible issues at the helm or other configuration levels.

**Comment by piotrmsc** [comment]
@abbi-gaurav any ideas how this could be done? helm offers `--dry-run` flag but it only renders charts, so more less only syntax can be checked and quoting https://helm.sh/docs/intro/getting_started/

>  It’s best not to assume that your chart will install just because --dry-run works.

Another question would be where to put output of `--dry-run` flag from helm ? It's a chart rendered with text error if sth is wrong but parsing this is well..

**Comment by abbi-gaurav** [comment]
duplicate of #6156
