### ISSUE TITLE
Documentation tutorial is broken

### ISSUE THREAD

**Issue by abbi-gaurav** [kyma-project/kyma#3424]
**Description**
The following tutorial 
https://kyma-project.io/docs/0.8/components/application-connector#tutorials-trigger-a-lambda-with-events
does not work as it tries to create a subscription with version `eventing.kyma.cx/v1alpha1"`.

This has been changed to `eventing.kyma-project.io/v1alpha1`.

The same change should reflect in all the tutorials.

**Comment by bszwarc** [comment]
This has been corrected starting with version 0.9 onwards - with the change reflected in all tutorials. We avoid adding changes to already existing release documentation by updating newer versions, as the users should be encouraged to merge to the most recent ones.
I think we may close this one.
