### ISSUE TITLE
Adresses resource cannot be created since it already exists (kyma-gke-nightly)

### ISSUE THREAD

**Issue by jesusreal** [kyma-project/kyma#3428]
**Description**
Last 5 builds for _kyma-gke-nightly_ failed with the following error:
```
#################################################################################################
# Reserve IP Address for Ingressgateway
#################################################################################################
Thu Mar 28 04:01:54 UTC 2019
ERROR: (gcloud.beta.compute.addresses.create) Could not fetch resource:
- The resource 'projects/sap-kyma-prow/regions/europe-west3/addresses/nightly' already exists
```

**Expected result**

- The resource 'projects/sap-kyma-prow/regions/europe-west3/addresses/nightly' does not exist yet and can be created

**Actual result**

- The resource 'projects/sap-kyma-prow/regions/europe-west3/addresses/nightly' already exists

**Steps to reproduce**

Rerun _kyma-gke-nightly_ from here https://status.build.kyma-project.io/?job=kyma-gke-nightly

**Troubleshooting**

Logs:
- https://status.build.kyma-project.io/view/gcs/kyma-prow-logs/logs/kyma-gke-nightly/1111115948149968898
- https://status.build.kyma-project.io/view/gcs/kyma-prow-logs/logs/kyma-gke-nightly/1111168670731603968
- https://status.build.kyma-project.io/view/gcs/kyma-prow-logs/logs/kyma-gke-nightly/1111356534023000064
- https://status.build.kyma-project.io/view/gcs/kyma-prow-logs/logs/kyma-gke-nightly/1111360434780246016
- https://status.build.kyma-project.io/view/gcs/kyma-prow-logs/logs/kyma-gke-nightly/1111478336728600578

**Comment by tehcyx** [comment]
We've manually resolved this for the moment and created some follow-up tasks to make sure this is not happening again in the future. We will work on these with high priority.

**Comment by tehcyx** [comment]
PR to resolve this: https://github.com/kyma-project/test-infra/pull/884

**Comment by dariadomagala** [comment]
This error occurred again, but this time it was not only nightly:

https://status.build.kyma-project.io/view/gcs/kyma-prow-logs/logs/kyma-gke-weekly/1165927116903026688
https://status.build.kyma-project.io/view/gcs/kyma-prow-logs/logs/kyma-gke-weekly/1165919690866823168
https://status.build.kyma-project.io/view/gcs/kyma-prow-logs/logs/kyma-gke-nightly/1166198781054554112
https://status.build.kyma-project.io/view/gcs/kyma-prow-logs/logs/kyma-gke-service-catalog-crd-periodic/1166213879076753408

**Comment by derberg** [comment]
old ticket and we do not see this behavior anymore, keeping closed, good job stalebot
