### ISSUE TITLE
Smoke tests for central Connector Service

### ISSUE THREAD

**Issue by lszymik** [kyma-project/kyma#3439]
**Description**

We need smoke tests that can be run outside of the Kyma cluster, those tests should check all central Connector Service functionalities and stability.

We would need to think regarding the pipeline and execution of those tests.

**Acceptance Criteria**

- A separate application 
- Tests requires kubeconfig

**Comment by lszymik** [comment]
Please note, that currently, we need to move it forward and implement a basic test which will evolve in upcoming iterations.

**Comment by Maladie** [comment]
We should be able to re-use Connector Service acceptance tests, but it may need some work to adapt them to Central CS. Testing pipeline should send notifications to Slack channel every time test fails and every time test passes after failing.

**Comment by janmedrek** [comment]
Tests were set up in central environment.
