### ISSUE TITLE
Define Kyma SLOs

### ISSUE THREAD

**Issue by Abd4llA** [kyma-project/kyma#3456]
## Description
Currently, we do not know the boundaries (SLO - Service Level Objectives) of a productive setup of kyma. For exampe, a typical production like cluster can handle a specific event throuhput which should not be stepped over as long as autoscaling is not ready. The maximum throughput number needs to be determined and documented in order to define supported usage of a cluster.

## Goal
To achieve that, we need

- (https://github.com/kyma-project/kyma/issues/3521) a reproducable performance test cluster setup that is like a productive setup
- (https://github.com/kyma-project/kyma/issues/3522) Provide a way to run tests against that performance test cluster using a central cluster with tooling for test result analysis ready
- test cases
  - to figure out current numbers for the SLO
  - which are reproducable
  - which can be executed continuously (optional)
  - which are located and developed in a consistent way 

## Details

A determined number states that the cluster can handle it without failures. The tests should assure the cluster health when testing the determine number by doing the following checks:
- No crashing pods or increased restarts in all namespaces.
- Kyma console is accessible and responsive.
- Kubectl is responsive. 
- No alerts for any pods.

Test cases

|Name | Test | What to measure? (SLIs) |Related components|
|-----|------|---------------------|------------------|
|(https://github.com/kyma-project/kyma/issues/3523)   API gateway latency with lambdas| Increase no of concurrent external requests sent to a lambda| Measure requests latency for 3 percentiles (75, 90, 99)  | API Gateway, Istio, Lamba pods|
|(https://github.com/kyma-project/kyma/issues/3523)   API gateway throughput with lambdas| Increase no of concurrent external requests sent to an internal service | Measure requests throughput | API Gateway, Istio, Lambda Pod|
|(https://github.com/kyma-project/kyma/issues/3524)   Events publishing latency| Increase no of concurrent published events sent from outside the cluster | Measure sending events latency from outside the cluster for 3 percentiles (75, 90, 99), not checking actual delivery|  istio,application-event-service, event-publish|
|(https://github.com/kyma-project/kyma/issues/3524)   Events publishing throughput| Increase no of concurrent external requests sent from outside the cluster | Measure sending events throughput, not checking actual delivery| istio,application-event-service, event-publish|
|(https://github.com/kyma-project/kyma/issues/3576)   Max number of Application API registrations | Increase no of APIs created for an application | Measure latency of service class retrieval | application-registry, istio, service catalog|

## Reasons
We want to provide for our customers a guide that explains what are the default Kyma SLOs for different cluster sizes.

**Comment by joek** [comment]
`Maximum no of lambda`: In terms of lambda this is probably the least interesting metric. More interesting is how many requrest we can get through per lambda type (t-shirt size) with fast, midrage and slow code.

The maximum number of lambdas is pretty much limited by the number of pods / deployments we can create and how much the other components e.g. api gateway can do.

**Comment by lszymik** [comment]
@Abd4llA Can you handle it?
