### ISSUE TITLE
Installation on GKE cluster - check if the documentation is up-to-date

### ISSUE THREAD

**Issue by tomekpapiernik** [kyma-project/kyma#3461]
**Description**

The documentation that describes the process of installing Kyma on managed clusters is very important and often referenced in discussions. These documents have been restructured and tweaked a number of times by different contributors. 

We should have a developer proof-read the document describing the process of installing Kyma on a GKE cluster and check if: 

- all prerequisites are up to date
- all commands are valid
- all steps are necessary - maybe there's a way to simplify the doc? merge some commands into a single call? 
- there is anything else we could do to make this document easier to work with

The aforementioned points should be investigated by a developer familiar with the installation process. If the developer identifies items that could be improved, he should team up with a technical writer to introduce the necessary changes. 

Additionally, please work on this related issue when handling this task: #2752 

**Reasons**

The documentation describing cluster installation has been updated numerous times by many different contributors and is often discussed by the community. As it's one of the most important documents in Kyma, we should make sure it's up-to-date and easy to follow. The TWs need the help of developers to properly verify all of the instructions found in these documents.

**Comment by tomekpapiernik** [comment]
Related issue: #2752

**Comment by sjanota** [comment]
Notes: 
* Docker hub account is needed only on installation from sources
* Any region is valid, not only europe-west1
* For Tiller installation RELEASE_TAG is not defined. Later it is exported as LATEST
* LATEST is not the best name. It should be called KYMA_VERSION or similar 
* DOMAIN -> DNS_SUBDOMAIN
* PROJECT -> GCP_PROJECT
* state that "Delegate the management of your domain to Google Cloud DNS" needs to be done only once
* YOUR_EMAIL_HERE - export
* YOUR_DOCKER_LOGIN - export
* "Using the latest GitHub release" 5 -> my-kyma.yaml, not my_kyma.yaml
* "Access the cluster" is strange, why not simply console.{domain} ?

**Comment by sjanota** [comment]
It's waiting until #3823 is finished
