### ISSUE TITLE
Installation on AKS cluster - check if the documentation is up-to-date

### ISSUE THREAD

**Issue by tomekpapiernik** [kyma-project/kyma#3462]
**Description**

The documentation that describes the process of installing Kyma on managed clusters is very important and often referenced in discussions. These documents have been restructured and tweaked a number of times by different contributors. 

We should have a developer proof-read the document describing the process of installing Kyma on an AKS cluster and check if: 

- all prerequisites are up to date
- all commands are valid
- all steps are necessary - maybe there's a way to simplify the doc? merge some commands into a single call? 
- there is anything else we could do to make this document easier to work with

The aforementioned points should be investigated by a developer familiar with the installation process. If the developer identifies items that could be improved, he should team up with a technical writer to introduce the necessary changes. 

**Reasons**

The documentation describing cluster installation has been updated numerous times by many different contributors and is often discussed by the community. As it's one of the most important documents in Kyma, we should make sure it's up-to-date and easy to follow. The TWs need the help of developers to properly verify all of the instructions found in these documents.

**Comment by tomekpapiernik** [comment]
Important: the manual doesn't describe how to spin up an Azure cluster and install Tiller. 
Please make the structure parallel to the GKE installation document.

**Comment by PK85** [comment]
@tomekpapiernik could you verify that by your own and in case of issues Adam W. will help?
Cheers, PK

**Comment by tomekpapiernik** [comment]
> @tomekpapiernik could you verify that by your own and in case of issues Adam W. will help?
> Cheers, PK

@PK85 No, have your team handle that. @klaudiagrz can help your devs.  
You can reference the task that [focuses on GKE](https://github.com/kyma-project/kyma/pull/3938). There will be quite a few improvements and as the structure of both instructions is parallel you can easily port the updates to the AKS-land.

**Comment by atakanyenel** [comment]
I encountered a problem while doing installation to azure. The `az aks create ` command uses a kubernetes version that is not supported by azure anymore. The version used by GKE docu is not available in aks, so kubernetes version is basically randomed by user.

**Comment by rakesh-garimella** [comment]
@tomekpapiernik docs in the Azure installation in kyma-project.io are outdated. The kuberentes version is different from what we have for GKE also the size of nodes is wrong. We are recommending bigger nodes for GKE. I think this can be handled here too.

**Comment by jakkab** [comment]
Kyma documentation is now up-to-date.
