### ISSUE TITLE
Allign e2e test interfaces

### ISSUE THREAD

**Issue by sjanota** [kyma-project/kyma#3466]
**Description**
We have two e2e tests that are doing pretty much same thing:
 * upgrade
 * backup'n'restore

Both tests have very similar flow:
1. Create test resources
2. Test if they are ok
3. Do something with cluster
4. Test if resources are back online

The tests only differ in the "something" they are doing. From test case perspective both flows are exactly the same. Despite the above they are implemented as completely independent components with very similar interfaces.

We should align those tests to use one interface and single suite of cases. The resulting interface should lean towards UpgradeTest as it has much wider set of arguments with missing methods added and extended to be consistent. A suggestion would look like this:
```go
type UpgradeTest interface {
	CreateResources(stop <-chan struct{}, log logrus.FieldLogger, namespace string) error
	TestResources(stop <-chan struct{}, log logrus.FieldLogger, namespace string) error
	DeleteResources(stop <-chan struct{}, log logrus.FieldLogger, namespace string) error
}
```
but it's just a suggestion.

**Reasons**
Having two implementations for same thing increases maintenance effort and makes it unclear what are the differences between those tests. This is especially crucial as it is codebase shared by all contributors. 

**Attachments**
* [UpgradeTest interface](https://github.com/kyma-project/kyma/blob/master/tests/end-to-end/upgrade/internal/runner/api.go#L7)
* [BackupTest interface](https://github.com/kyma-project/kyma/blob/master/tests/end-to-end/backup-restore-test/backupe2e/backuptest.go#L3)

**Acceptance criteria**
 - [ ] Common interface is defined and used by both e2e tests
 - [ ] Test cases are external to both e2e tests
 - [ ] There is a documentation along the test cases which describes what tests there are and how to write them
    * It states clearly that implementations must be stateless
  - [ ] E2e tests use the test cases to test Kyma behaviour

**Glossary**
_E2E test_  - component which tests how Kyma must behave as a whole. For now there are upgrade and backup'n'restore tests
_Test case_ - an implementation of the provided interface which describes how to test a smaller piece of Kyma, like component or CRD

**Comment by pbochynski** [comment]
When you do alignment please bear in mind that in case of backup the "do something" step should be "trigger backup, destroy the cluster, set up a new cluster and trigger restore procedure". In case of upgrade "do something" means "trigger update and monitor if the user workload is running without downtime".
The big difference between upgrade and backup is that the 4th step is running on **different clusters**. Please consider this factor when you plan the unification. Having the same interfaces is one thing but test execution implementation can be completely different.

**Comment by sjanota** [comment]
Yes, I completely agree, that from runner perspective the "do something" is not a small thing. My point is that from case implementation there is not difference what happens to the cluster in the meanwhile. We need to state it clearly that this interface must be stateless, as it may be recreated between calls.
