### ISSUE TITLE
Upgrade failed

### ISSUE THREAD

**Issue by akrausesap** [kyma-project/kyma#3467]
**Description**

Dear Colleagues,

I was upgrading a 0.7.0 cluster to 0.8.2. I planned on performing the following steps:

* Upgrade 0.7.0 to 0.8.0
* Upgrade 0.8.0 to 0.8.1
* Upgrade 0.8.1 to 0.8.2

However my upgrade from 0.8.0 to 0.8.1 fails with the below error message:

```
2019/04/01 07:40:41 Step error:  Details: Helm install error: rpc error: code = Unknown desc = a release named cluster-essentials already exists.
Run: helm ls --all cluster-essentials; to check the status of the release
Or run: helm del --purge cluster-essentials; to delete it
2019/04/01 07:40:42 Error during install/update:  Details: Helm install error: rpc error: code = Unknown desc = a release named cluster-essentials already exists.
Run: helm ls --all cluster-essentials; to check the status of the release
Or run: helm del --purge cluster-essentials; to delete it
```

The full log is attached:

[helm_status.txt](https://github.com/kyma-project/kyma/files/3028232/helm_status.txt)
[installer_logs.txt](https://github.com/kyma-project/kyma/files/3028233/installer_logs.txt)

Cheers

Andreas

**Expected result**

Cluster upgrades

**Actual result**

Cluster upgrade fails with error

**Steps to reproduce**

* Upgrade 0.7.0 to 0.8.0
* Upgrade 0.8.0 to 0.8.1

**Troubleshooting**

**Comment by derberg** [comment]
the issue is about old unsupported versions
