### ISSUE TITLE
Support upgrade via a generated deployment file instead of multiple manual steps.

### ISSUE THREAD

**Issue by abbi-gaurav** [kyma-project/kyma#3475]
**Description**
To improve productivity and developer experience, we should remove the complex manual steps for an upgrade.

e.g. 
Doing `kubectl edit installation kyma-installation` and manually adding/removing the components is quite cumbersome and error-prone. The manual editing can cause errors thus leading to a situation where one has to restart the whole cycle of install on GKE cluster, set up for the upgrade and then do the upgrade.

**Comment by Disper** [comment]
@abbi-gaurav Could you elaborate more on that?

**Comment by Disper** [comment]
@abbi-gaurav we're closing it as there was no feedback since April. 
Please re-open it if it's still valid.
