### ISSUE TITLE
Reevaluate and propose an improved testing approach for acceptance tests to have a stable CI

### ISSUE THREAD

**Issue by abbi-gaurav** [kyma-project/kyma#3482]
**Description**
At present, tests in the CI are quite flaky. 

This causes around 15-20% extra time to get a feature added to the product apart from development time. Most of the issues arise due to timeouts. Since K8S is all about eventual consistency, it happens sometimes that the expected state for verification is not reached within timeout thus failing the tests.

**Comment by sjanota** [comment]
Closing in favour of #2993
