### ISSUE TITLE
test core kubeless int is failing

### ISSUE THREAD

**Issue by sayanh** [kyma-project/kyma#3483]
**Description**

Service binding fails to work.

Logs are here:
https://status.build.kyma-project.io/view/gcs/kyma-prow-logs/logs/post-master-kyma-gke-upgrade/1112623871892131841

**Expected result**

**Actual result**

**Steps to reproduce**

**Troubleshooting**

**Comment by rakesh-garimella** [comment]
it looks like the `use-<sbuID>` label is not injected.

**Comment by mszostok** [comment]
Its looks like ServiceBindingUsage controller didn't receive the event about the creation of the ServiceBindingUsage CR, so in test you created an SBU but it wasn't processed by controller so the label was not injected.
Right now I do not know why the informers failed in logs we cannot see anything about the failure. 

log:
```
{"level":"debug","log":{"message":"Starting reconcile ServiceBindingUsage add process of ServiceBindingUsage \"helmbrokerupgradetest/redis-bu\"","service":"controller:service-binding-usage","time":"2019-04-01T08:26:15.209Z"}}
{"level":"debug","log":{"message":"Reconcile ServiceBindingUsage add process of \"helmbrokerupgradetest/redis-bu\" completed","service":"controller:service-binding-usage","time":"2019-04-01T08:26:16.591Z"}}
```

as you can see controller logged `redis-bu` as the last process item after that controller didnt receive any event

**Comment by sayanh** [comment]
Functions with events fails to work as well. Following are the runs:
https://status.build.kyma-project.io/view/gcs/kyma-prow-logs/logs/post-master-kyma-gke-upgrade/1113400491892543490
https://status.build.kyma-project.io/view/gcs/kyma-prow-logs/logs/post-master-kyma-gke-integration/1113362992633745408

`test-event-bus-tester` failed in those runs.
https://github.com/kyma-project/kyma/issues/3554

**Comment by lszymik** [comment]
We are closing. If it is still valid please re-open.
