### ISSUE TITLE
test-core-core-ui-acceptance is failing

### ISSUE THREAD

**Issue by sayanh** [kyma-project/kyma#3484]
**Description**

`test-core-core-ui-acceptance` is failing in `post-master-kyma-gke-upgrade` job.
Please find the logs below:
https://storage.googleapis.com/kyma-prow-logs/logs/post-master-kyma-gke-upgrade/1112616070029512704/build-log.txt

https://status.build.kyma-project.io/view/gcs/kyma-prow-logs/logs/post-master-kyma-gke-central-connector/1112659229627387907

https://status.build.kyma-project.io/view/gcs/kyma-prow-logs/logs/post-master-kyma-gke-integration/1113024734989127682

**Comment by sayanh** [comment]
Turns out this the change in folder structure for `/var/log/pods` in GKE 1.12.6 is causing the issue. The test was fine with GKE 1.12.5. As there is no control over the minor versions of k8s in [here](https://github.com/kyma-project/test-infra/blob/master/prow/scripts/cluster-integration/helpers/provision-gke-cluster.sh#L38), the issue started happening recently. It is also found that k8s version for aks is 1.11 as in [here](https://github.com/kyma-project/test-infra/blob/master/prow/scripts/cluster-integration/kyma-aks-long-lasting.sh#L55)  which needs to be revisited.

**Comment by kwiatekus** [comment]
another failure here:
https://status.build.kyma-project.io/log?job=pre-rel09-kyma-integration&id=1115162479987527680

**Comment by pkosiec** [comment]
I can see multiple issues in the logs:

- Docs UI problem is already resolved
- Problem with failing UI tests is resolved as well in https://github.com/kyma-project/kyma/pull/3694
- The only problematic test is the `lambda-ui` test, which fails from time to time. I would suggest improving resiliency with retries.

**Comment by kwiatekus** [comment]
@pkosiec We found a fail in doc UI:
https://status.build.kyma-project.io/log?job=post-master-kyma-gke-upgrade&id=1121298912620056576

**Comment by dariadomagala** [comment]
@pkosiec Could you please confirm if this Docs UI fix also fixes https://github.com/kyma-project/kyma/issues/3861 or is it still valid ?

**Comment by pkosiec** [comment]
@dariadomagala Yes, I believe so.
