### ISSUE TITLE
ServiceBindingUsage controller didn't receive events from Informers

### ISSUE THREAD

**Issue by mszostok** [kyma-project/kyma#3487]
**Description**

Its looks like ServiceBindingUsage controller didn't receive the event about the creation of the ServiceBindingUsage CR, so when someone will create an SBU then it's not processed by the controller and tests are failing.

Right now I do not know why the informers are not working. In controller logs we cannot see anything about the failure. 

log:
```
{"level":"debug","log":{"message":"Starting reconcile ServiceBindingUsage add process of ServiceBindingUsage \"helmbrokerupgradetest/redis-bu\"","service":"controller:service-binding-usage","time":"2019-04-01T08:26:15.209Z"}}
{"level":"debug","log":{"message":"Reconcile ServiceBindingUsage add process of \"helmbrokerupgradetest/redis-bu\" completed","service":"controller:service-binding-usage","time":"2019-04-01T08:26:16.591Z"}}
```

as you can see controller logged `redis-bu` as the last process item after that controller didnt receive any event about the SBU.

source:
- https://status.build.kyma-project.io/view/gcs/kyma-prow-logs/logs/post-master-kyma-gke-upgrade/1112623871892131841

**Expected result**

After upgrade ServiceBindingUsage controller still processes the ServiceBindingUsage CRs. 

**Steps to reproduce**

It's hard to reproduce, we even do not know how often it's failing.
Maybe we will need to create our on-demand cluster and execute stress tests to detect the problem

**AC**
- Static code analyse first, maybe we do not handle error correctly
- Maybe try to write livenessProb to check if informer works
  - could be SBU creation in a loop, or
  - check informer goroutine if is alive
- Add go metrics about number of goroutine and expose in Grafana

**Comment by PK85** [comment]
Issue has been timboxed

**Comment by aszecowka** [comment]
maybe this is a similar isssue: https://github.com/kubernetes/kubernetes/issues/73089

**Comment by PK85** [comment]
Reestimated in new sprint to 2SP

**Comment by polskikiel** [comment]
This issue occurred on kyma `1.0` cluster and we were able to get logs from the ServiceBindingUsage Controller: [sbulogs.log](https://github.com/kyma-project/kyma/files/3201294/sbulogs.log)
