### ISSUE TITLE
test-core-core-console-backend-service fails

### ISSUE THREAD

**Issue by sayanh** [kyma-project/kyma#3508]
**Description**
test-core-core-console-backend-service keeps failing

Following runs are:
https://status.build.kyma-project.io/view/gcs/kyma-prow-logs/logs/post-master-kyma-gke-integration/1113029419691151360

**Expected result**

**Actual result**

**Steps to reproduce**

**Troubleshooting**

**Comment by sayanh** [comment]
Occurred once. Closing it for now and will monitor.

**Comment by sayanh** [comment]
Reopening:
https://status.build.kyma-project.io/view/gcs/kyma-prow-logs/logs/post-master-kyma-gke-central-connector/1113064905797275648

**Comment by mmitoraj** [comment]
I'm closing this issue as this is a duplicate of #3201.
