### ISSUE TITLE
New mixin dashboards in grafana are empty

### ISSUE THREAD

**Issue by rakesh-garimella** [kyma-project/kyma#3512]
**Description**

After updating the prometheus and grafana the mixin dashboards are empty.  A new object called `record` has been introduced and these are not returning any value into grafana dashboards. We need to investigate why ? Following are the dashboards
1.[ persistent-volume-usage.json](https://github.com/helm/charts/blob/master/stable/prometheus-operator/templates/grafana/dashboards/persistentvolumesusage.yaml)
2. [k8s-node-rsc-usage.json](https://github.com/helm/charts/blob/master/stable/prometheus-operator/templates/grafana/dashboards/k8s-node-rsrc-use.yaml)
3. [k8s-cluster-rsc-usage.json](https://github.com/helm/charts/blob/master/stable/prometheus-operator/templates/grafana/dashboards/k8s-cluster-rsrc-use.yaml)

**Comment by rakesh-garimella** [comment]
Related to: https://github.com/kyma-project/kyma/issues/3512

**Comment by a-thaler** [comment]
Will be fixed with https://github.com/kyma-project/kyma/issues/4520
