### ISSUE TITLE
Deletion of application has leftovers

### ISSUE THREAD

**Issue by a-thaler** [kyma-project/kyma#3515]
**Description**
Assumed you have an Application named "icke" with 10 APIs registered. Then also 10 kubernetes services will be created labeled with "app=icke" and 10 istio deniers labeled the same.

When deleting the Application resource, the services and deniers will stay and pollute the system. At some point it will even harm the cluster as the amount of kubernetes services will influence the istio side-car of pods.

**Expected result**

When deleting application "icke" I expect that all services and deniers labeled with "app=icke" get deleted

**Actual result**
The resources are still there

**Steps to reproduce**
Create an application, register at least one API, delete the application, check services with the specific label

**Troubleshooting**
Delete the services and deniers with that commands:
```
kubectl -n kyma-integration delete service -lapp=icke
kubectl -n kyma-integration delete denier -lapp=icke
```

**Comment by lszymik** [comment]
@a-thaler Do you see the same issue when deleting API from the App Registry endpoint? If you are deleting API manually, then you need first to delete the deniers and other stuff, which is managed by the App Registry.

Moreover, we will apply the changes mentioned here: https://github.com/kyma-project/kyma/issues/940 you will not be able to delete Application if it is in use.

We will definitely look into it. Thanks for reporting.

Cheers
Lukasz

**Comment by a-thaler** [comment]
@lszymik deleting the API via the API of registry will indeed cleanup the service and the denier. Unfortunately, that cannot be triggered from console and so it is not always possible as you need a connected app usually for that.

**Comment by Disper** [comment]
Consider using kubernetes' owner references
