### ISSUE TITLE
API specification management in Console UI

### ISSUE THREAD

**Issue by lszymik** [kyma-project/kyma#3517]
**Description**

The common case when working with the Application Connector is to register an API and provision service class to allow API consumption from services and lambda functions.

The registration process requires acquiring the client certificate and calling Application Registry endpoint externally.

To allow faster prototyping, we would like to have something like  Google Chrome CRX (https://fileinfo.com/extension/crx , https://blog.hunter.io/how-to-install-a-chrome-extension-without-using-the-chrome-web-store-31902c780034 )

**Reasons**

There must be a simple possibility to add API and use it inside Kyma.

**Acceptance Criteria**
- User can create API definition by uploading API specification (swagger file, async API spec)
- User can add/modify API definition and its elements (basic attributes like name, description, API spec, credentials)

**Things to be considered**

- There should be a possibility to register API with drag&drop (.json file/swagger)
- The wizard should be provided which will allow asking the user or reusing existing secrets with API credentials
- The API definition can be visualized in Application View
- The GraphQL layer should be provided for UI which should be based on https://github.com/kyma-incubator/compass/blob/bb163c86dc8ac435be6c177a11b4b4caf7bc8a07/components/director/internal/gqlschema/schema.graphql#L453-L485
- We can reuse API definition from E2E tests: https://github.com/lszymik/application-connector-e2e

**Comment by pbochynski** [comment]
Handled by Compass UI.
Epic: https://github.com/kyma-project/kyma/issues/4707
Issue: https://github.com/kyma-project/console/issues/1045
