### ISSUE TITLE
Define Application Connector SLOs

### ISSUE THREAD

**Issue by lszymik** [kyma-project/kyma#3518]
**Description**

One of the important goal of the Kyma release 1.1 is to define SLO for Kyma component. Please check the following Epic: https://github.com/kyma-project/kyma/issues/3456

**Reasons**
The first iteration with getting SLO for Application Connector must be done.

ACs:
- Create performance tests and add info to the epic's table

**Comment by a-thaler** [comment]
Covered by https://github.com/kyma-project/kyma/issues/3524, will close it
