### ISSUE TITLE
Provide a tool to provision Kyma cluster to be used for performance tests

### ISSUE THREAD

**Issue by Abd4llA** [kyma-project/kyma#3521]
## Description
Provide a method to setup performance test cluster on GCP  that represents a typical production environment and has monitoring/alerts and grafana enabled.

## Requirements
- Document how to setup such a cluster and its settings (from inside load test cluster)
- Assure that alerts which are spamming because of test run are disabled or improved
- Alerting is accessible (either slack or alertmanager access)
- Assure that in-cluster grafana dashboards are available in order to check the overall cluster health after test execution
- Any sources/docu should be located in test-infra repository
- Respect experience gained by others for a goo setup from beginning, so talk to the eventing team about how to configure eventing best for a good start, also check #3319 
- Always latest master
- Recreated once a week. **This requiremente will be manage by the issue:**  [#1014]( https://github.com/kyma-project/test-infra/issues/1014)

## Reasons
To be used to run performance tests.

**Comment by Abd4llA** [comment]
So since this is the "kyma cluster" which will be under test, and probably it will need to be started from the "central" performance tests environment. So questions:

1- Do we need the setup of this cluster to be unattended? "e.g. have a script that spins up this cluster?"
2- Do we need to store the "production environment config" somewhere? or change the default helm chart values for cluster setup? i.e the default case for which "isLocalEnv" is false.

**Comment by Abd4llA** [comment]
shouldn't the task title change to "provide a kyma cluster to be used for performance tests" ?

**Comment by pbochynski** [comment]
For the production profile use helm overrides: https://kyma-project.io/docs/0.9/root/kyma/#tutorials-helm-overrides-for-kyma-installation
Please don't create DNS entries for cluster and use default XIP dynamic DNS with self signed-ceritficates.

**Comment by venturasr** [comment]
> Evengers and Goats had specific production cluster configuration (istio resources and NATSS resources) 

For the Kyma cluster (production) there is not a concrete configuration to be used at this time:

* In a prior conversation with @strekm and @Demonsthere they mentioned that for Kyma in production no specific setup exist.
* @abbi-gaurav (Evengers ) suggests that each team should execute their performance test and base of the results it is possible to have a better idea of what needs to be adjusted in Kyma cluster for production. 

So the performance test would help to identify what needs to be adjusted/changed. And as the Kyma cluster is base on master, a second step might be to improve the tools mentioned in this issue to change the setup.

**Comment by venturasr** [comment]
Related PR: https://github.com/kyma-project/test-infra/pull/899
