### ISSUE TITLE
API gateway latency and throughput tests based on lambdas

### ISSUE THREAD

**Issue by Abd4llA** [kyma-project/kyma#3523]
## Description
We need test cases to test the "external request throughput and latency to a lambda". We need to have the test cases executed and analyzed ones so that we know the possible maximum assuming the performance test cluster setup.

## Requirements
Provide the following tests for **three** different lambda types: fast, midrange and slow code

|Name | Test | What to measure? (SLIs) | Related components|
|-----|------|---------------------|------------------|
|  API gateway latency with lambdas| Increase no of concurrent external requests sent to a lambda| Measure requests latency for 3 percentiles (75, 90, 99)  | API Gateway, Istio, Lamba pods|
|  API gateway throughput with lambdas| Increase no of concurrent external requests sent to an internal service | Measure requests throughput | API Gateway, Istio, Lambda Pod|

- Run the tests against a cluster setup as provided by https://github.com/kyma-project/kyma/issues/3521
- Use the test runner setup and framework as provided by https://github.com/kyma-project/kyma/issues/3522
- Locate the test case sources as described here: https://github.com/kyma-project/kyma/issues/3522

## Reasons
To find out Kyma SLOs, to have performance test suite available

## AC
- Write test as explained above
- Document the implementation steps for other kyma teams

**Comment by a-thaler** [comment]
https://github.com/kyma-project/console/issues/729 was transformed into this issue
