### ISSUE TITLE
Testing max no of subscriptions

### ISSUE THREAD

**Issue by Abd4llA** [kyma-project/kyma#3525]
**Description**

Provide the following tests

|Name | Test | What to measure? (SLIs) | How to observe? |Related components|
|-----|------|---------------------|-----------------|------------------|
|Max no. of subscriptions| 1. Publish 10000 events per second with 10 concurrent requests and increase no of events subscriptions | Events propagation latency |Grafana & alerts| API Gateway, Envoy, kubeproxy|

**Reasons**

To find out Kyma SLOs

**Comment by a-thaler** [comment]
We decided to not test that aspect for now but focus on few but very important aspects first. Will close it and decouple from https://github.com/kyma-project/kyma/issues/3456
