### ISSUE TITLE
Testing max no of lambdas

### ISSUE THREAD

**Issue by Abd4llA** [kyma-project/kyma#3526]
**Description**

Provide the following tests

|Name | Test | What to measure? (SLIs) | How to observe? |Related components|
|-----|------|---------------------|-----------------|------------------|
|Maximum no of responsive lambda with Http trigger| Create a fixed number of lambdas and check if they are responsive | Time till lambda has successful response and latency of response |Time between deployment and first successful response, Latency of that responce| API controller, Kubeless, Istio|

**Reasons**
To figure out Kyma SLO

**Comment by a-thaler** [comment]
We decided to not test the increase of lambda creation for now but rather focus on the lambda performance. So will close the ticket and decouple it from https://github.com/kyma-project/kyma/issues/3456
