### ISSUE TITLE
Add dashboard for custom metrics Event Bus subscription controller

### ISSUE THREAD

**Issue by abbi-gaurav** [kyma-project/kyma#3529]
**Description**
Apart from Istio metrics, there are other indicators that can provide assistance to operators to troubleshoot issues.
The chart has a template for the namespace.

As discussed with the team, the following charts will be created in the new dashboard.

- [ ] Number of Kyma Subscriptions vs Number of Knative Subscriptions
- [ ] Number of Inactive Kyma Subscriptions
- [ ] Number of Inactive Knative Subscriptions

**AC**
- [ ] The dashboard is available as a part of Kyma deployment.

**Comment by Abd4llA** [comment]
Will no longer be valid after migration to `Knative Eventing Broker`
