### ISSUE TITLE
Api-controller enable mtls on apis depending on feature flag

### ISSUE THREAD

**Issue by kfurgol** [kyma-project/kyma#3541]
**Description**

When mTLS will be enabled cluster-wide, api-controler should add mtls to ApiSpec depending on feature flag.

**Expected result**
Apis created by api-controller have policy with object depending on feature flag:
```
peers:
- mtls
```

**Actual result**
Apis created by api-controller don't have policy with object
```
peers:
- mtls
```

**Steps to reproduce**
Create api with policy

**Comment by piotrmsc** [comment]
@kfurgol @Tomasz-Smelcerz-SAP  Please update  docu describing API gateway crd and api controller docu
