### ISSUE TITLE
Implement tracing for the event publish flow

### ISSUE THREAD

**Issue by abbi-gaurav** [kyma-project/kyma#355]
### Goal

User is able to trace events from EC to Lambda and see it in the tracing dashboard

Details:
 * Current behavior in publish is to reuse the trace if it already exists or else create a new one.
 * It could happen there are some incompatibilities with nginx-ingress tracing and open-tracing. Those should be fixed as a part of this ticket.

Tasks:
 * Set up the wormhole gateway for the incoming call to publish events
 * Make the call to publish the events.
 * Identify the tracing integration.
 * Fix/verify the issues with the tracing flow. There could be incompatibility between trace-id generated by Envoy (64 bit) and the one OT creates (128 bit).

 

AC:
 * The user is able to see the event publish and lambda trigger details in the tracing UI

**Comment by Abd4llA** [comment]
Verify nginx tracing as well which is related to #351

**Comment by marcobebway** [comment]
Regarding #351, verified that nginx trace spans are visible.

There is still an issue with duplicate generated `span-id` which confuses the tracing engine.

<img width="1437" alt="duplicate-span-id" src="https://user-images.githubusercontent.com/24314423/45298530-136c5500-b509-11e8-8aa1-389730b17219.png">

**Comment by marcobebway** [comment]
I created an issue for envoy team to fix the duplicate `SpanID` issue [here](https://github.com/envoyproxy/envoy/issues/4397).

**Comment by marcobebway** [comment]
I created an issue for envoy team to fix the duplicate `SpanID` issue [here](https://github.com/envoyproxy/envoy/issues/4397).

**Comment by abbi-gaurav** [comment]
Post update to Istio 1.1, the issue with breaking spans has been fixed.
