### ISSUE TITLE
test-event-bus-tester fails

### ISSUE THREAD

**Issue by sayanh** [kyma-project/kyma#3554]
**Description**

test-event-bus-tester fails

Some of the failed runs are:
https://status.build.kyma-project.io/view/gcs/kyma-prow-logs/logs/post-master-kyma-gke-upgrade/1113400491892543490
https://status.build.kyma-project.io/view/gcs/kyma-prow-logs/logs/post-master-kyma-gke-integration/1113362992633745408

**Expected result**

**Actual result**

**Steps to reproduce**

**Troubleshooting**

**Comment by suleymanakbas91** [comment]
Looks like other failed tests interfered with the event bus tests. We don't observe the issue anywhere else.
