### ISSUE TITLE
Print gql request logs in cbs acceptance tests only when test function fails

### ISSUE THREAD

**Issue by tgorgol** [kyma-project/kyma#3555]
**Description**

Right now, in CBS acceptance tests network traffic related to graphql client requests (such as request headers, variables, queries and responses) is logged every time server returns an error. This solution works fine as long as the server is expected to not return errors. For example, in case of testing authorization directives, where we often want the server to return authorization errors, CBS logs get cluttered with requests with errors related to unauthorized access which are actually expected in those scenarios.

Proposed solution is to defer printing request logs until the end of test function and print them only if the test function failed.

**Reasons**

Printing logs only if the test function failed would remove clutter caused by requests that are expected to result in error (for example when we want to make sure that specific user has no permission to create a resource).

**Comment by kwiatekus** [comment]
This ticket doesn't look like a high priority.
If you need it, please reopen
