### ISSUE TITLE
Update Eventing Architecture

### ISSUE THREAD

**Issue by bszwarc** [kyma-project/kyma#3563]
Architecture documentation needs to be updated: https://github.com/kyma-project/kyma/blob/master/docs/event-bus/docs/02-01-event-bus.md 

to include the Kyma-Knative integration part.

Reference ![IMG_1632.jpg](https://images.zenhubusercontent.com/5b9a2f6a2df36e0aa911ecbd/42d8cacc-14fc-4e07-b8f6-5e1306479b8f)

**Comment by abbi-gaurav** [comment]
**Flow**

## Prerequistite set up

* An external solution is integrated to Kyma

* The external solution has registered events which it can send to Kyma

* The application representing the external solution is bound to the namespace.

* The events have been added to the namespace from the event catalong

## Event flow

### Configuration
* A developer configures a lambda or a serverless app to be triggered by an event from an external solution
  > NOTE: In case of lambda a kyma subscription is automatically created while in case of a microservice, developer needs to create one.

* The `subscription-controller-knative` reacts on the creation of Kyma subscription. After verifying the event activation, it creates a `Knative channel` and a `Knative subscription`.

* The `natss-controller` reacts on the creation of `Knative channel` and creates the required K8S and Istio services.

* The `natss-dispatcher` reacts on the creation of `Knative channel` and creates the NATS Streaming subscription.

### Runtime (Event Flow)

* The external application sends an event to the application connector.

* The Application Connector enriches the Event with the details of its source.
  > **NOTE:** There is always one dedicated instance of the Application Connector for every instance of an external solution connected to Kyma.

* The Application Connector makes a REST API call to `publish-knative` and sends the enriched Event.

* `publish-knative`  forwards the event to the  relevant `kantive-channel` service url which is inferred based on `source id` , `event type` and `event type version`

* The event is forwarded by istio to the `natss-dispatcher`.

* `natss-dispatcher` stores the event in the NATS Streaming.

* NATS Streaming stores the Event in the Persistence storage volume to ensure the data is not lost if the NATS Streaming crashes.

* The event is picked up by the `nats-dispatcher` and dispatched to the configured lambda or the microservice URL as an HTTP POST request.
