### ISSUE TITLE
Application API registration load test

### ISSUE THREAD

**Issue by a-thaler** [kyma-project/kyma#3576]
## Description

Currently, there is a limitation of the amount of APIs registered to an application. We need to figure out the current amount of APIs a cluster can handle and analyze the reasons for that limitation.

## Reasons
There should be no limit, the design of the software should be scalable.

## Goal
Run the stress mock against a production like cluster with different settings and **figure out** the current limit.
https://github.com/kyma-incubator/varkes/tree/master/examples/stress-mock

Figure out why there is a limit and propose action items to follow up.

**Comment by atakanyenel** [comment]
Current limit of registered APIs is **475** services. After this number, Kyma stops registering new services and returns the response `{"code":500,"error":"Internal error."}`. Even though registration fails , there is no error on the console and Kyma renders services correctly both in the catalog and in the application list view. 

The grafana output is as follows:
![stress-8](https://user-images.githubusercontent.com/7947572/59421061-46ac7f00-8dce-11e9-9414-002880f62d00.png)

The first peak until 10:30 refers to a different test with 400 service and works normally. The difference between 400 & 450 services can be seen.

The tests are using 1 thread. With multiple threads, kyma starts to give `upstream connect error or disconnect/reset before headers` error and Nginx throws `Gateway Time-out`. This doesn't stop Kyma from registering services though, it still registers them in the background but the user is not aware of it.

The cluster parameters are like this:
- GKE version: 1.12.7-gke.17
- Node size : 5
- Node type: n1-standart-2 (2 vCPUs, 7.5 GB memory)
- Boot disk size per node: 100 GB
- KYMA version : 1.0.0

To clean up after the test, just deleting the services is not enough. Also the following script has to be executed:
```bash

# For application with name "m" and environment "stress"
kubectl -n kyma-integration delete deniers -lapp=m
kubectl -n kyma-integration delete services -lapp=m
kubectl delete serviceclasses -n stress--all
```
