### ISSUE TITLE
Rename gateway-tests to gateway-event-tests

### ISSUE THREAD

**Issue by abbi-gaurav** [kyma-project/kyma#360]
Gateway-test project contains acceptance tests for Events API. It should be renamed since it tests Event Gateway component

**Comment by abbi-gaurav** [comment]
Align with gateway-team on the naming.

**Comment by akgalwas** [comment]
Currently the naming is inconsistent : folder name is "gateway-tests", application name in Jenkins file is "gateway-acceptance-tests", pod name in the chart is "test-{{.Release.Name }}-event-service-acceptance".  Make sure to rename in all the mentioned places.

**Comment by abbi-gaurav** [comment]
The smoke tests need to be redesigned post Knative adoption
