### ISSUE TITLE
apiserver-proxy test fails on dex network problem

### ISSUE THREAD

**Issue by sjanota** [kyma-project/kyma#3607]
**Description**
apiserver-proxy tests are failing if there is a problem with dex connection. As network conditions are unpredictable it shouldn't fail that fast, but apply couple of retries. 

**Expected result**
apiserver-proxy tests are resilient to changing network conditions

**Actual result**
apiserver-proxy fails randomly

**Steps to reproduce**
Random

**Troubleshooting**

**Comment by sayanh** [comment]
Failed run:
https://status.build.kyma-project.io/view/gcs/kyma-prow-logs/logs/post-master-kyma-integration/1114137475728543744

**Comment by Disper** [comment]
Failed again: https://status.build.kyma-project.io/view/gcs/kyma-prow-logs/logs/post-master-kyma-integration/1117775692407246848
