### ISSUE TITLE
Review new AsyncAPI 2.0

### ISSUE THREAD

**Issue by derberg** [kyma-project/kyma#3615]
**Description**

- take specs we are now getting from one of the integrated applications (there apis are not yet open sources unfortunately...soon though) and manually rewrite to AsyncAPI 2 to identify differences and amount of changes that are on the way, especially how we will now identify the event types
- take a look on https://github.com/asyncapi/parser and https://github.com/asyncapi/parser-nodejs that we will use in future for parsing the spec, give AsyncAPI guys feedback if you see some things can be improved, contribute if needed, but join their slack first and talk to them, they are nice people ;) Remember these are only official parsers and as you can see they are focused on server side parsing. Suggest what we do in future with client side components, how we use what asyncapi gives, what is the best and most reasonable. Of course keep in mind parser or course is also a validator
- estimate how much time have to spend on refactoring the react component to support natively 2.0. What additional effort we have to put in the playground that is about to be converted into a official asyncapi editor
- we need to support Kyma users with parsing 1.0 to 2.0, we can use Asset Store and have a mutator doing that during registration, how much time it can take (knowing we are not at the moment happy with how mutation and validation webhooks work. Keep in mind we also need to provide not only mutation service to rewrite, but also validation service to validate ;)
- at the end, if needed, provide feedback to AsyncAPI squad (@fmvilas ) in such issue https://github.com/asyncapi/asyncapi/issues/new?assignees=&labels=v2.0.0+review&template=review.md&title=%5B2.0.0+REVIEW%5D+
- take a look on this proposal from knative and see if our current events registry (the graphql query for returning events for a give namespace) has anything to do with the proposal https://github.com/knative/eventing/blob/a5e4762cd6537e52eebe1a1e432e77fa55877865/docs/registry/README.md

**Reasons**

We depend on AsyncAPI, we are also AsyncAPI contributors, we need to clearly know what we will have to start implementing in 1.2 release schedule, which starts middle of May

**Comment by derberg** [comment]
as of 0.6 Knative there is an event registry. EventType CR https://github.com/knative/eventing/blob/master/config/300-eventtype.yaml is created so far whenever https://github.com/knative/eventing/blob/master/config/300-cronjobsource.yaml or https://github.com/knative/eventing/blob/master/config/300-apiserversource.yaml is created. The EventType contains info about event including schema.

**Comment by derberg** [comment]
Unknowns:
- if EventType spec.schema is URI pointing to the schema:
  - validate reasoning, why schema cannot be part of the resource, shouldn't it be? so you are 100% sure it is idempotent? I assume the schema stored under URI can be change.
  - where is it, can we (alert: stupid question) link to asyncapi to specific event type schema?
  - if Knative focuses on CloudEvents, how a sample URI would look like, where would the schema be?

**Comment by derberg** [comment]
Glossary before below:
- Channel is what in Knative is understood as EventType

AsyncAPI biggest changes basing on streetlight example https://github.com/asyncapi/asyncapi/blob/master/examples/next/streetlights.yml and comparison with existing asyncapi registered in our system https://raw.githubusercontent.com/SAP/xf-application-mocks/master/commerce-mock/apis/events.yaml. Below is just a list of stuff we are affected by, there are more changes of course:
- `topics` become `channels`
- mandatory `id` urn like attribute is required. We will somehow have to generate it for each registered application
- the payload becomes a nested object of a `message`, in channel details

example 2.0.0 of AsyncApi for EC with few `channels` checked with https://playground.asyncapi.io/?utm_source=editor&utm_medium=editor-topbar&utm_campaign=playground
```
asyncapi: '2.0.0-rc1'
id: 'urn:com:ec:stage:server'
info:
  title: ec-all-events
  version: v1
  description: EC Events v1
channels:
  customer.created.v1:
    subscribe:
      summary: Customer Register Event v2
      message:
        payload:
          type: object
          required:
          - storeUid
          - customerId
          - customerUid
          properties:
            customerUid:
              type: string
              example: adam@hybris.com
              description: Email of a Customer
              title: Customer uid
            storeUid:
              type: string
              example: 4caad296
              description: Unique id of a Store
              title: StoreUid
            customerId:
              type: string
              example: 0ed118f9474e
              description: Unique id of a Customer
              title: Customer uid
  quote.orderplaced.v1:
    subscribe:
      summary: Order Placed for Quote Event v1
      message:
        payload:
          type: object
          required:
          - quoteCode
          - orderCode
          properties:
            quoteCode:
              type: string
              example: '76272727'
              description: Code of Quote
              title: Quote Code
            orderCode:
              type: string
              example: '76272727'
              description: Code of Order
              title: Order Code
  quote.expiresoonevent.v1:
    subscribe:
      summary: Quote Expiring Soon Event v1
      message:
        payload:
          type: object
          required:
          - quoteCode
          - quoteUserUid
          - quoteUserType
          - storeUid
          - customerUid
          properties:
            customerUid:
              type: string
              example: adam@hybris.com
              description: Email Address of Customer
              title: Customer ID
            storeUid:
              type: string
              example: 4caad296
              description: ID of the Store (BaseStore)
              title: Store ID
            quoteCode:
              type: string
              example: '76272727'
              description: Code of Quote
              title: Quote Code
            quoteUserUid:
              type: string
              example: adam@hybris.com
              description: ID Of User Canceling Quote
              title: ID Of User
            quoteUserType:
              type: string
              example: BUYER
              description: User Type
              title: User Type
```

**Comment by fmvilas** [comment]
You may want to skip the `id` attribute as we may make it optional in the end: https://github.com/asyncapi/asyncapi/issues/219.

**Comment by magicmatatjahu** [comment]
I checked new version of AsyncAPI from developer point of view, so:
- asyncapi core team create [converter](https://github.com/asyncapi/converter) from 1.* versions to 2.0.0-rc. This tool is running on backend (in Node), but it is also not very extensive, so rewrite to native browser it will not cause problems, but it has [missing features](https://github.com/asyncapi/converter#known-missing-features) - so I smell contribution ;-)
- If we rewrite converter for support browser, we will be able to easily rewrite our React component to new version without looking at the old implementation (I think that backward compatibility is unnecessary).
- [parser and validator](https://github.com/asyncapi/parser) - not extensive golang program (in the main part of the program), but with some logic with [`parsing`] (https://github.com/asyncapi/parser/blob/master/pkg/models/models.go) types, but I think that is also will not be a problem. Of course If we will check some shortages, we be able to contribution.

**Comment by derberg** [comment]
Provided feedback for AsyncAPI -> https://github.com/asyncapi/asyncapi/issues/221. FYI @fmvilas 

Summary from the research aka things to do:
- Provide validation and conversion services in Kyma with contribution of go converter to asyncapi org ->  https://github.com/kyma-project/kyma/issues/4385
- In UI component focus to support latest version only as anyway we will internally have a 1->2 converter:
  - Do not support 1.0 in react component if it is so easy to convert as there will be go converter from us and also there is one provided in asyncapi in node.js. Others solutions should be provided only if community says it is needed
  - how we approach parsing though? now asyncapi supports message schema specification to be provided not only in json schema but also protobuf and avro. This means parsing is not that easy as in previous version, that we could just take official asyncapi json schema and that is it. The official parser is written in go and we cannot use it in a simple way as our design is always client side for UI, no server side rendering except of simple HTTP server. We need to check WebAssembly like here https://brightinventions.pl/blog/using-wasm-with-react/ as it doesn't look like WebAssembly is just a crazy experiment but at the end a solution that has large gaming community. It is not experimental anymore https://webassembly.org/roadmap/ and has good support and is not officially documented https://developer.mozilla.org/en-US/docs/WebAssembly#Browser_compatibility -> https://github.com/asyncapi/asyncapi-react/issues/47
- We should not try to invent event registry on our own in Kyma but contribute directly to Knative and extend initial proposal for EventType CR. We only need to talk with other Kyma fellas how we do that, because we do not fully use Knative atm, and this is a strong requirement. We also need to alight how we approach Knative sources with our Kyma application registration and sourcing of events. This is all needed so we clearly know at what stage we will generate EventType CRs. For sure though we want to treat AsyncAPI as a source information for EventType generation -> Proposal must be created first

**Comment by derberg** [comment]
One more thing for the review and comment https://github.com/kyma-project/kyma/issues/3615#issuecomment-494177711
After clarification on an AsyncAPI community call, one more thing changes, 
what we knew in AsyncAPI 1.0 as subscribe/publish now reversed the meaning. So in AsyncAPI 1.0 focus of the spec was that it is for a consumer, so the consumer knows to what topics he can subscribe. With 2.0 it is opposit, so focus is on application, producer, so the producer specifies to which topics it subscribes and publish. 

so for us 
```
quote.orderplaced.v1:
    subscribe:
```
changes into
```
quote.orderplaced.v1:
    publish:
```
