### ISSUE TITLE
Improve docs structure and documentation charts setup

### ISSUE THREAD

**Issue by derberg** [kyma-project/kyma#3617]
**Description**

- improve docs structure in kyma/docs and get rid of docs-config.json.
- prepare logic for delivering documentation in website with new structure. Don't forget about support older version of kyma.
- update filters in existing docs topics CRs
- consider splitting current documentation subchart that now is in docs chart in core directory. At the end docstopics for application connector should be created only if application connector is installed. Consult with @PK85 that works on 2nd modularization phase if it makes sense to do it now, or should that be done in this 2nd phase

**Reasons**

With the introduction of Headless CMS we have to do some cleanup in minio and solve issues that could not be solved with the previous solution

**Comment by kazydek** [comment]
When creating the tutorial make sure you contact @polskikiel for details on the already documented example of adding docs for service classes that he worked on.
