### ISSUE TITLE
Tests related to hostAliases fail on Minikube and kyma-integration job

### ISSUE THREAD

**Issue by sayanh** [kyma-project/kyma#3622]
**Description**

```
--- FAIL: TestAssetStore (181.70s)
testsuite.go:97: Creating buckets...
testsuite.go:101: Waiting for ready buckets...
testsuite.go:105: Uploading test files...
testsuite.go:113: Creating assets...
testsuite.go:117: Waiting for ready assets...
testsuite.go:313:
Expected error:
<*errors.withStack | 0xc0003712c0>: {
error: {
cause: {
s: "waiting for resource failed in given timeout 180.000000 second(s)",
},
msg: "while waiting for ready Asset resources",
},
stack: [0xe59681, 0xe5f44e, 0xe5ec65, 0xe9b048, 0x4f691f, 0x45b461],
}
while waiting for ready Asset resources: waiting for resource failed in given timeout 180.000000 second(s)
not to have occurred
```

test-assetstore-assetstore-integration keeps failing

Failed runs are:

https://status.build.kyma-project.io/view/gcs/kyma-prow-logs/logs/post-master-kyma-integration/1114137475728543744
https://status.build.kyma-project.io/view/gcs/kyma-prow-logs/logs/post-master-kyma-integration/1113417855728095235
https://status.build.kyma-project.io/view/gcs/kyma-prow-logs/logs/post-master-kyma-integration/1114176610078035970

**Comment by pkosiec** [comment]
After adding some additional logging, here are my findings:

Asset status, which doesn't change:

```
2019/04/12 10:53:32 Asset test-asset-store/test-bar.yaml status: {CommonAssetStatus:{Phase:Failed Message:Asset content pulling failed due to error Get https://minio.kyma.local/system-public-1b55jtobopk70/1eb0rha/bar.yaml: read tcp 172.17.0.36:39574->10.164.0.96:443: read: connection reset by peer Reason:PullingFailed AssetRef:{BaseURL: Files:[]} LastHeartbeatTime:2019-04-12 10:53:31 +0000 UTC ObservedGeneration:1}}
```


Full logs:
https://storage.googleapis.com/kyma-prow-logs/pr-logs/pull/kyma-project_kyma/3694/pre-master-kyma-integration/1116650027893133315/build-log.txt

**Comment by pkosiec** [comment]
The error happens very often, but not always - `minikubeIP` on root on VM, where all tests passed returns correct IP. Looks like it is also not related to DNS, as we have `connection reset` or `connection closed` error on all tests.

**Comment by tgorgol** [comment]
I checked `pre-master-kyma-integration` and `post-master-kyma-integration` jobs logs and prepared a list of failed runs with timestamps. Seems like this problem started occuring way earlier than we suspected but it was much more rare.

timestamp | job
--- | ---
`2019-03-08T19:46:27.998370252Z` | pre-integration/1104103064442245120
`2019-03-14T09:54:14.778909768Z` | post-integration/1106128159364878337
`2019-03-19T13:29:07.022919393Z` | pre-integration/1107994703623622657
`2019-03-19T14:30:56.092686196Z` | pre-integration/1108010180097871873
`2019-03-29T11:20:38.944001431Z` | pre-integration/1111585165999607811
`2019-04-01T05:58:53.439899143Z` | pre-integration/1112592287906402306
`2019-04-01T08:32:34.072313918Z` | pre-integration/1112630539719806978
`2019-04-01T12:03:56.523613431Z` | pre-integration/1112683514785959938
`2019-04-01T13:32:40.256097011Z` | pre-integration/1112706416600158210
`2019-04-01T13:34:56.17166643Z` | pre-integration/1112706794343370755
`2019-04-03T08:47:17.007729628Z` | pre-integration/1113358338285899776
`2019-04-03T09:30:38.485682097Z` | pre-integration/1113369537161465857
`2019-04-03T09:55:04.348608483Z` | pre-integration/1113376079923384320
`2019-04-03T10:07:09.87550311Z` | pre-integration/1113378722603339776
`2019-04-03T11:38:27.769986371Z` | pre-integration/1113402127562051584
`2019-04-03T12:30:02.288546997Z` | pre-integration/1113415088833826817
`2019-04-03T12:42:41.37357175Z` | post-integration/1113417855728095235
`2019-04-03T13:50:48.851244458Z` | pre-integration/1113434843682705411
`2019-04-03T15:10:02.123422693Z` | pre-integration/1113454726889869313
`2019-04-03T16:18:53.294934166Z` | pre-integration/1113472468481216512
`2019-04-03T16:54:05.285347708Z` | pre-integration/1113481024106401792
`2019-04-03T18:32:37.408354091Z` | pre-integration/1113506440309379074
`2019-04-03T19:26:41.932993388Z` | pre-integration/1113519904188796928
`2019-04-03T19:30:59.105116349Z` | pre-integration/1113521161456586754
`2019-04-03T20:08:54.177573027Z` | pre-integration/1113529843682643968
`2019-04-04T05:54:07.457287654Z` | pre-integration/1113677944460414976
`2019-04-04T06:17:36.446068846Z` | pre-integration/1113683229618999296
`2019-04-04T06:53:21.370433197Z` | pre-integration/1113692164019195904
`2019-04-04T10:20:31.051725047Z` | pre-integration/1113744383796056064
`2019-04-04T11:17:36.866551069Z` | pre-integration/1113758854467817473
`2019-04-04T12:36:47.208496067Z` | pre-integration/1113778484884279297
`2019-04-04T12:44:37.063168195Z` | pre-integration/1113781127622955008
`2019-04-04T13:49:00.170054456Z` | pre-integration/1113797107052974080
`2019-04-04T14:07:13.870595774Z` | pre-integration/1113801511630016512
`2019-04-04T14:35:35.909527192Z` | pre-integration/1113808935120277505
`2019-04-04T15:00:50.881227461Z` | pre-integration/1113815478813331456
`2019-04-04T15:39:30.776164081Z` | pre-integration/1113825042275241984
`2019-04-04T16:15:57.141870565Z` | pre-integration/1113834352883535873
`2019-04-04T19:53:08.837494489Z` | pre-integration/1113888332040900609
`2019-04-04T20:13:18.77924212Z` | pre-integration/1113894245904683011
`2019-04-04T20:31:15.892004615Z` | pre-integration/1113898524388364288
`2019-04-05T06:04:58.008629791Z` | pre-integration/1114043226865537026
`2019-04-05T08:06:39.919336946Z` | pre-integration/1114072923930365952
`2019-04-05T08:59:15.725773382Z` | pre-integration/1114086766052118529
`2019-04-05T09:09:30.461749821Z` | pre-integration/1114088905814052864
`2019-04-05T11:34:11.287104258Z` | pre-integration/1114126026868264960
`2019-04-05T11:56:10.544078721Z` | pre-integration/1114131184218017795
`2019-04-05T12:22:43.036009502Z` | post-integration/1114137475728543744
`2019-04-05T14:58:41.798378145Z` | post-integration/1114176610078035970
`2019-04-05T15:07:20.338276232Z` | pre-integration/1114178998574780417
`2019-04-05T18:25:33.501977149Z` | post-integration/1114229455938654208
`2019-04-08T06:36:06.653105241Z` | pre-integration/1115137942747090944
`2019-04-08T06:36:38.270611464Z` | pre-integration/1115137565029044225
`2019-04-08T10:13:29.668525794Z` | pre-integration/1115192175047479297
`2019-04-08T11:28:57.380729803Z` | pre-integration/1115211680112971778
`2019-04-08T12:48:49.112535036Z` | pre-integration/1115231685701537793
`2019-04-08T17:35:40.368605889Z` | pre-integration/1115304036833169409
`2019-04-08T18:37:06.196649521Z` | post-integration/1115318758907318273
`2019-04-09T07:44:33.307602848Z` | pre-integration/1115516941302239233
`2019-04-09T07:56:08.60636299Z` | pre-integration/1115520588274733057
`2019-04-09T10:07:41.786434179Z` | pre-integration/1115553431075950592
`2019-04-09T11:05:04.159792101Z` | pre-integration/1115567397898555392
`2019-04-09T13:32:02.397633071Z` | pre-integration/1115604894007431168
`2019-04-09T15:10:18.301494802Z` | pre-integration/1115629807032340480
`2019-04-09T21:56:14.204145024Z` | pre-integration/1115731854104727553
`2019-04-10T06:50:44.861089193Z` | post-integration/1115865736716226561
`2019-04-10T09:21:47.954117413Z` | pre-integration/1115904366969098240
`2019-04-10T09:58:56.627288791Z` | pre-integration/1115913805495275522
`2019-04-10T10:49:21.480991432Z` | pre-integration/1115926008805986306
`2019-04-10T11:54:28.99080048Z` | pre-integration/1115942493590917122
`2019-04-11T08:58:50.727008735Z` | pre-integration/1116261090565558272
`2019-04-11T10:46:47.223255991Z` | post-integration/1116288269496094721
`2019-04-11T11:17:44.280669928Z` | pre-integration/1116296197183639554
`2019-04-11T13:02:02.846583017Z` | post-integration/1116321740906041344
`2019-04-11T19:59:03.688489848Z` | pre-integration/1116427057954295809
`2019-04-11T21:52:12.364433477Z` | pre-integration/1116455243572318208
`2019-04-12T07:34:30.284051784Z` | pre-integration/1116601835096903680
`2019-04-12T10:43:55.904636681Z` | pre-integration/1116650027893133315
`2019-04-12T12:12:53.75812011Z` | pre-integration/1116671544077062148
`2019-04-12T13:47:22.425952596Z` | post-integration/1116696079480393729
`2019-04-14T16:22:12.860838557Z` | pre-integration/1117459735566618624
`2019-04-15T13:17:31.683112907Z` | post-integration/1117775692407246848
`2019-04-15T14:25:05.666223794Z` | pre-integration/1117792553521909761
`2019-04-15T22:19:56.627358215Z` | pre-integration/1117911461813817345
`2019-04-16T07:57:18.529310761Z` | post-integration/1118057046554447873
`2019-04-16T09:17:07.917552955Z` | pre-integration/1118077180018954240
