### ISSUE TITLE
test-core-core-acceptance is failing

### ISSUE THREAD

**Issue by sayanh** [kyma-project/kyma#3623]
**Description**

test-core-core-acceptance is failing
```
=== RUN TestSpec
x
Failures:
* /go/src/github.com/kyma-project/kyma/tests/acceptance/dex/dex_test.go
Line 125:
Expected: nil
Actual: 'Post https://dex.kyma.local/auth: dial tcp 10.99.75.152:443: connect: connection refused'
```

https://status.build.kyma-project.io/view/gcs/kyma-prow-logs/logs/post-master-kyma-integration/1114137475728543744
https://status.build.kyma-project.io/view/gcs/kyma-prow-logs/logs/post-master-kyma-integration/1113417855728095235
https://status.build.kyma-project.io/view/gcs/kyma-prow-logs/logs/post-master-kyma-integration/1114176610078035970

**Expected result**

**Actual result**

**Steps to reproduce**

**Troubleshooting**

**Comment by Disper** [comment]
Another failed run: https://status.build.kyma-project.io/view/gcs/kyma-prow-logs/logs/post-master-kyma-integration/1117775692407246848

**Comment by sjanota** [comment]
A possible solution kyma-project/test-infra#907

**Comment by piotrmsc** [comment]
duplicate of https://github.com/kyma-project/kyma/issues/3622, in this task team will deliver improvements to tests such as http client with retires. Root cause of connection refused will be covered in 3622
