### ISSUE TITLE
Prepare a list of metrics for monitoring eventing to support troubleshooting

### ISSUE THREAD

**Issue by abbi-gaurav** [kyma-project/kyma#3626]
**Description**
Identify the metrics that should help understand an operator or support person to troubleshoot the issues when business flows configured with an event trigger is broken or the business flow is not getting triggered with eventing as expected.

Refer to Kubernetes metrics if they can be used. (https://github.com/kubernetes/kube-state-metrics)

**AC**
- [ ] Prepare a proposal document that describes all the metrics relevant for event troubleshooting.

**Comment by montaro** [comment]
Suggested Metrics

**Publish App**
-
- events in
- events in per sec
- events in per source ID
- events in per source ID per sec
- events in per event type
- events in per event type per sec
- succeeded events
- succeeded events per sec
- ignored events
- ignored events per sec
- failed events
- failed events per sec
- average time
- average time 99%
- subscriptions
- event activations

**Push App**
-
- events in
- events in per sec
- pushed messages
- pushed messages per sec
- failed pushed messages
- failed pushed messages per sec
- consumers

**Comment by abbi-gaurav** [comment]
@montaro, a couple of comments 

* Could you please create a document as a proposal and add it to https://github.com/kyma-project/community/tree/master/sig-and-wg/sig-core/proposals
* Please ensure that we are not duplicating the metrics available from Istio.
* The metrics publish, push and event bus are mostly focused on the throughput, latency. I do not see metrics that can help to troubleshoot with event delivery. This is the main focus of this task as mentioned in the description. Imagine, if a lambda is not receiving an `order.created` event of version `v1` from an application `sample-production`, what kind of metrics would be helpful.

**Comment by montaro** [comment]
@abbi-gaurav 
1- Will move the proposal to the advised destination
2- I can say that istio metrics are a  supplementary metrics here and the only duplication maybe only the number of requests and the request duration which I prefer to have them as part of the app-specific metrics
3- Maybe the **Alerts** would help in this kind of trubleshooting. Alerting should be discussed as a seprate story

**Comment by abbi-gaurav** [comment]
@montaro  As discussed during the review, the alerting would be built on top of the metrics that can identify problems with event delivery. So please bring out the list of the metrics that can help with a simple question. `Why my lambda is not getting triggered with "order.created" event from "ec-default" application?`. Please use the eventing expertise to see in what all situations this could happen and derive metrics from there.

**Comment by montaro** [comment]
@abbi-gaurav Please check the latest proposed list of metrics. The main update is to give the ability to filter `FAILED` `SUCCEEDED` `IGNORED` messages by `source-id` and/or `event-type` and/or `event-type-version`. as well as reporting the errors.

I believe the metrics dashboard is a troubleshooting enablement tool but needs to be supported by 
- Logging aggregation system
- Error reporting tool like `Airbrake` for example

CC: @suleymanakbas91
