### ISSUE TITLE
Display metrics for ignored published events in Grafana

### ISSUE THREAD

**Issue by abbi-gaurav** [kyma-project/kyma#3627]
> Note: Add the  templating variables for application, event type, and event type version

**AC**
- [x] There is a dashboard available OOTB with Kyma installation that displays ignored published events in a Grafana dashboard.

**Comment by montaro** [comment]
![image](https://user-images.githubusercontent.com/531945/56654924-9f468200-6691-11e9-8969-5f0e0bfde22f.png)
@abbi-gaurav Please check
