### ISSUE TITLE
kyma patch not idempotent

### ISSUE THREAD

**Issue by Morriz** [kyma-project/kyma#3638]
after modifying the installation to start "lite" packages, the installer deploys an extra istio-ingressgateway. I get one extra every time.

**Comment by kfurgol** [comment]
@Morriz Please use our templates when creating issue

**Comment by pbochynski** [comment]
High-quality issues are usually fixed quickly. Please add more details in the sections:

**Description**

**Expected result**

**Actual result**

**Steps to reproduce**

**Comment by Morriz** [comment]
I can't deduce why or when an extra gateway gets added. Because it happened after the patch phase I thought it was the patch doing it. I might be right but can't say for sure.

**Comment by piotrmsc** [comment]
Hi, istio kyma patch does not create a new ingress, it patches existing instance to use hostport on a minikube, however, istio comes with autoscaling for gateways which in case of ingress does not make sense on a minikube. I have created an issue for that #3829 after that you shouldn't get confused anymore.
