### ISSUE TITLE
Subscriptions updates are not honoured in event bus

### ISSUE THREAD

**Issue by abbi-gaurav** [kyma-project/kyma#365]
## Description
When updating a subscription spec but not changing the name, the updates are not honored or reflected.

Note: Check the functionality of `subscription validator` to make sure it won't get affected.

Hint:
* Update could be achieved by deleting old and creating new NATS Streaming subscription.
* Validatior should check the subscription resource and update the status flag accordingly.
* One idea to verify the update is to change the endpoint of the subscription

## AC:

- [x] An update to the Subscription K8S Custom Resource is reflected in the NATS Subscription.
- [x] The event activation status is retained.
- [x] There should be integration tests to ensure update is honored.
- [x] Event bus functionality is verified using the event bus example.
- [x] Since current update can result in loss of events under certain scenarios, the same should be documented.

**Comment by radufa** [comment]
The unit and acceptance tests are green.
The PR was manually tested.
The integration tests, as required by AC, should be still written.

**Comment by abbi-gaurav** [comment]
The integration test should verify that for the update
-  NATS Streaming subscription is deleted.
- New NATS Streaming subscription is created.

**Comment by abbi-gaurav** [comment]
As @montaro is on vacation, @marcobebway will take over this.

**Comment by abbi-gaurav** [comment]
As discussed, I will take over this task and explore what are the possible challenges in mocking or using the controller APIs from @montaro.

@montaro will take over #365 since this is commited for MS10 and is the sprint goal.

**Comment by abbi-gaurav** [comment]
The code has been merged.
Left is:
* Update deployment configurations
* Add documentation

**Comment by marcobebway** [comment]
Documentation and deployment is completed.

@abbi-gaurav, I assume you already did the AC item "**Event bus functionality is verified using the event bus example**" as part of your pull request. If so, please make sure to mark this item as checked.

**Comment by abbi-gaurav** [comment]
@marcobebway I verified using the integration tests. The verification using the Kyma runtime is still pending.
Moving it back to **To Do**

**Comment by marcobebway** [comment]
- Verified kyma acceptance tests are green.
- Verified event-subscription example is working correctly.
