### ISSUE TITLE
Enable secure access for K8S dashboard

### ISSUE THREAD

**Issue by abbi-gaurav** [kyma-project/kyma#366]
We are currently bundling the K8S dashboard but not exposing it as no security concept is in place.
After we enabled the JaegerUI, we can adopt the same concept for K8S dashboard and finally link it in console even.

### Jester Input
- A different security context for K8S dashboard should be created.
- The deployment to which sidecar should be applied needs to be figured out.

### AC
- [ ] The access to K8S dashboard is secure.

**Comment by radufa** [comment]
About securing Kubernetes dashboard using "keycloak-proxy": 
https://itnext.io/protect-kubernetes-dashboard-with-openid-connect-104b9e75e39c

**Comment by abbi-gaurav** [comment]
Please sync with @radufa about this task.

**Comment by abbi-gaurav** [comment]
After having the discussion with @piotrmsc, we both share the same concern to not have default access for the cluster-admin privileges.

We have decided to park this PR and have the Istio RBAC implemented later on.
When it will happen will depend upon the capacity of both teams.

**Comment by radufa** [comment]
We have to wait with the usage of Istio RBACs till the results of the investigation for a general solution for "authorization" will be finished (currently done by  @piotrmsc).

**Comment by montaro** [comment]
@abbi-gaurav @radufa This means that until we get to the working istio RBAC auth. working, the dashboard will be exposed insecurely? i.e. The proxy will not be merged?!

**Comment by abbi-gaurav** [comment]
@montaro We will not merge the helm charts. So until there is a clear authorization model in place, K8S Dashboard will not be accessible.

The subsequent work will be built on top of effort done so far.

**Comment by abbi-gaurav** [comment]
Closing this issue and the dashboard access for minikube is handled separately.
