### ISSUE TITLE
kyma-cli could be bundled and should correspond with the release

### ISSUE THREAD

**Issue by Morriz** [kyma-project/kyma#3660]
I think all the install instructions/cli bins/commands should be included with this repo.

So we can always safely rely on a valid client cli/server combo, and don't have to follow a readme with instructions that involve executing remote manifests.

I suggest making the updated kyma-cli part of definition of done for a release...

Just my 2 cents ;)

**Comment by a-thaler** [comment]
Hi @Morriz,

thanks for your feedback. Our plan is to make the Kyma-CLI an official kyma project and use it as the default way of installing kyma, referencing it in all documentation. The current idea is to still keep it in a separate repository but align it from a release perspective.

Please https://github.com/kyma-project/kyma/issues/3005, is that covering your thoughts and can I close the ticket here as a duplicate?

**Comment by Morriz** [comment]
Of course, I can add my comments there. Thanks!
