### ISSUE TITLE
installer osx stops on wrong sed call

### ISSUE THREAD

**Issue by Morriz** [kyma-project/kyma#3663]
I know this is a dupe of #380 but I am opening a seperate one here as that one was closed with "wontfix". Seriously? Please fix this problem by implementing reliable tooling in containers. It's not so hard to use busybox to replace text in buffers, so please.
Like I commented in the other issue: it's rather unnecessary to still use host os binaries. Docker was supposed to fix our cross platform woes ;)

**Comment by kfurgol** [comment]
@Morriz Please use our templates when creating issue

**Comment by pbochynski** [comment]
We are going to replace shell scripts with kyma-cli: https://github.com/kyma-project/kyma/issues/3005

**Comment by a-thaler** [comment]
With release 1.2 now the minikube installation got replaced by the CLI officially, the script is deprecated and will not be fixed
