### ISSUE TITLE
Change event bus to use single identifier for data partitioning

### ISSUE THREAD

**Issue by abbi-gaurav** [kyma-project/kyma#367]
### Goal

Simplify data partitioning and consumption based on customer feedback. 

As decided in the *Agreed Solution* RE name will be used instead of multiple source fields.
 * source-namespace
 * source-environment
 * source-type

The name of the new single identifier will be "sourceId" as decided:
![image.png](https://images.zenhubusercontent.com/5b96325ec171d136082e990f/a385b6f0-23fb-4e19-b371-67c2c9cffb90)

AC:
 * Event Bus data partitioning logic has been changed to use RE name
 * The event bus functionality is not impacted.
 * The tracing tags have been changed accordingly.
 * The reference documentation for event bus and tracing has been changed.
* The name of the variable is configurable in the helm charts.

**Comment by abbi-gaurav** [comment]
This is a dependency for the framefrogs.

**Comment by marcobebway** [comment]
PR related to this issue is: https://github.com/kyma-project/kyma/pull/715.
