### ISSUE TITLE
Remove/refactor kyma-admin-base role

### ISSUE THREAD

**Issue by Tomasz-Smelcerz-SAP** [kyma-project/kyma#3672]
**Description**

Remove `kyma-admin-base` role if possible. If not, refactor it so that it doesn't use any wildcards (`*`) and it's scope is minimal.
This is a follow-up to: #3438 

**Reasons**

For `kyma-admin` we aim to inherit as much as possible from built-in k8s `admin` role using the aggregation mechanism.
At the moment `kyma-admin` aggregates `kyma-admin-base` legacy role that uses wildcards: `*` for resources and verbs.
Unfortunately, some checks in UI asserts that admin user has a wildcard (`*`) in permissions, so we can't get rid of this now.
The flawed UI logic is to be fixed here: https://github.com/kyma-project/console/issues/758.

See also: #3438

**Comment by Demonsthere** [comment]
Implemented by #4980
