### ISSUE TITLE
Monitor events sending functionality 

### ISSUE THREAD

**Issue by abbi-gaurav** [kyma-project/kyma#369]
Event Gateway component is not integrated with Prometheus.

Acceptance criteria:
 * Monitoring added in Event Gateway
 * Dashboards in Grafana created

Note: in the first step we should start with something simple like response times and response codes.

**Comment by abbi-gaurav** [comment]
@abbi-gaurav create a proposal for metrics first.

**Comment by abbi-gaurav** [comment]
This is a placeholder for collecting the ideas about what kind of metrics could be helpful.
We are in the transition of removing the event service. Due to this task, we won't be adding any metrics to the event service.

Assigning to @lszymik for tracking purpose.

**Comment by lszymik** [comment]
It will be added after move to Istio 1.1

**Comment by abbi-gaurav** [comment]
Dashboard for event-service has been created and available in Kyma deployment.

![Screenshot 2019-05-02 at 13.10.46.png](https://images.zenhubusercontent.com/5b83ad9b79c9991fcdb9a287/ebbf7a60-e61e-4aa3-9575-c6ad6a5937b6)
