### ISSUE TITLE
Improve Backup Tests

### ISSUE THREAD

**Issue by joek** [kyma-project/kyma#3699]
**Description**

As a user I like to restore my kyma system into a new kubernetes cluster to react on desaster cases.

AC:
- Backup should be restored to a new Kubernetes Cluster on the same Infrastructure provider

**Reasons**

Currently the restore is running on the same cluster, which is not representing the disaster usecase.

**Comment by a-thaler** [comment]
Duplicate of https://github.com/kyma-project/kyma/issues/4500
