### ISSUE TITLE
Provide documentation details for using Kyma for synchronous and asynchronous use cases

### ISSUE THREAD

**Issue by abbi-gaurav** [kyma-project/kyma#3704]
**Description**

It seems current Kyma documentation and architecture only focuses on the event based integrations which only serves asynchronous scenarios. This causes confusions as community and customers then try to implement synchronous use cases such as integrating a SPA with Kyma for the real-time synchronous and customized view using event-based integration via the enterprise application. This will lead to customers building unnecessary complexity and also not getting expected performance.

There should be a documentation section providing clear details about synchronous vs asynchronous use cases and guidelines to implement them.

**Comment by pbochynski** [comment]
To work on this guide we need to support better in-cluster messaging:
- possibility to add a new type of event that a microservice can publish (event catalog decoupled from application connector)
- easy way to publish and subscribe to events in a microservice
