### ISSUE TITLE
Improve naming of metadata in tracing

### ISSUE THREAD

**Issue by abbi-gaurav** [kyma-project/kyma#371]
### Goal
Based on feedback from Bucki and other stakeholders, we need to improve the naming of general and event tracing. The developer should be able to get an idea where his code flow has reached. The naming should map to Kyma components so that the developer does not get confused.

**Details**

* push                                     ===> `event-delivery-service`
* envoy push                          ===> `event-http-dispatcher-service`

* Operation names as mentioned in the document should also be changed for the above services.
 

Reference:
 * https://kubernetes.github.io/ingress-nginx/user-guide/third-party-addons/opentracing/
 * https://github.com/kubernetes/ingress-nginx/issues/2260

### AC
- [x] The service names have been changed as specified in the details.
- [x] Setting the names is configurable.
- [x] The changes are verified in the tracing UI.

**Comment by lszymik** [comment]
It must be done.
