### ISSUE TITLE
Refactor pkg/apis/servicecatalog/validation package

### ISSUE THREAD

**Issue by piotrmiskiewicz** [kyma-project/kyma#3711]
Currently, validation webhooks uses validation methods which validates all parts of the object for example ValidateServiceBinding (validates Spec and Status). Webhook validations should only check the main part of the object or Status (in separate validationmethod).

Consider creating new  (or renaming existing ones) validation method like ValidateServiceBindingSpec.
Be aware of the change in internalValidateServiceInstance method - it was modified by removing status validation. Consider revert this change if the method will still exists

**Comment by PK85** [comment]
ToDo:
- add a comment in SC fork what needs to be done
