### ISSUE TITLE
UI component for Service Binding not lined up properly

### ISSUE THREAD

**Issue by tehcyx** [kyma-project/kyma#3729]
**Description**
![image](https://user-images.githubusercontent.com/917785/56157507-87298100-5f74-11e9-879f-57d0e32a085c.png)
As you can see in the screenshot, the GATEWAY_URL variable name is slightly below the instances name. This seems to be happening due to the table in table UI element. Maybe it can opt to not adding a table if there's only one variable to display?

**Expected result**
One variable to be aligned with instance name in one line

**Actual result**
Variable name misaligned due to table in table.

**Steps to reproduce**
Create a lambda with a service binding that only has one environment variable exposed.

**Troubleshooting**
Code generated for this bug to show:
```
<tbody _ngcontent-c21=""><!----><tr _ngcontent-c21=""><td _ngcontent-c21=""> daniel-s-service-7f402-distant-boss </td><td _ngcontent-c21=""><table _ngcontent-c21=""><tbody _ngcontent-c21=""><!----><tr _ngcontent-c21="" data-index="0"><!----><td _ngcontent-c21="" class="y-fd-table--col-12 y-word-break"> GATEWAY_URL </td><!----></tr></tbody></table></td><td _ngcontent-c21="" class="fd-has-float-right"><button _ngcontent-c21="" fd-button="" class="fd-button fd-button--compact sap-icon--delete fd-button--light"></button></td></tr></tbody>
```

**Comment by Wawrzyn321** [comment]
Issue no longer persists. Checked on Chrome 77, Firefox 69 and Safari 12.1.1.
![image.png](https://images.zenhubusercontent.com/5cf77c0350ef43023a228d1d/c952b6fd-267c-48de-8f96-339b2b3ffb6f)

**Comment by Wawrzyn321** [comment]
If the issue persists, this view is to be rewritten to React JS anyway.
