### ISSUE TITLE
Cannot use kubectl port-forward when using generated kubeconfig from the console

### ISSUE THREAD

**Issue by piotrmsc** [kyma-project/kyma#373]
Confirm these statements before you submit the issue:

- [ ] I have searched open and closed issues for duplicates.
- [ ] I have read the contributing guidelines.
---

**Description**

When a user downloads kubeconfig from the console admin section, he is unable to use kubectl port-forward. Since generated kubeconfig points to apiserver proxy, probably problem is in the proxy which does not allow connection upgrade.

**Expected result**

After downloading kubeconfig from the console, I'm able to use kubectl port-forward without an error.

**Actual result**

In current situation using `kubectl port-forward` results in error `error: error upgrading connection: Upgrade request required`

**Steps to reproduce**

**Troubleshooting**

**Comment by mszostok** [comment]
Still valid problem
