### ISSUE TITLE
test-core-core-ui-acceptance is failing

### ISSUE THREAD

**Issue by Disper** [kyma-project/kyma#3742]
**Description**

Some basic logs are available here: https://storage.googleapis.com/kyma-prow-logs/logs/post-master-kyma-gke-integration/1118057298732781568/build-log.txt . 

**Expected result**

Test test-core-core-ui-acceptance succeeded

**Actual result**

Test test-core-core-ui-acceptance fails

**Troubleshooting**

It's hard to find the cause due to limited logs info. Please add in comments any new findings. 
https://storage.googleapis.com/kyma-prow-logs/logs/post-master-kyma-gke-integration/1118057298732781568/build-log.txt

**Comment by sjanota** [comment]
It looks like the test took a little bit too long. `helm test` failed, but when script tried to access logs the test has already finished successfully. Closing this one as it gives us no information regarding the delay. Let's track it in different issue if it occurs again.
