### ISSUE TITLE
Application Connector Documentation: create Connectivity Guidelines section.

### ISSUE THREAD

**Issue by akgalwas** [kyma-project/kyma#3744]
**Description**

We need to have separate chapter containing information for developers implementing Kyma integration. The chapter should contain guidelines describing how the software integrating with Kyma should be designed.  
Topics to be covered:
- What data should be stored in external application's data model
- Certificate rotation rotation: guidelines for implementing job that renews certificate (it should mention private key rotation)
- Certificate revocation
- Document can be created as tutorial

Topics should reference code examples (ideally in different languages).
**Reasons**

Information important for developers implementing Kyma integration is distributed in various documents. Some information is included in architecture description, some in tutorials/guides. What we need is the single place where all important knowledge is gathered.

**Comment by janmedrek** [comment]
With the shift to the Compass being responsible for Kyma connectivity, we will continue the work in this ticket: https://github.com/kyma-incubator/compass/issues/628
