### ISSUE TITLE
Monitor all existing Kyma components

### ISSUE THREAD

**Issue by abbi-gaurav** [kyma-project/kyma#376]
As an administrator (e.g. SRE Team) I need insights (metrics) and alerts of all kyma components to ensure a stable environment and investigate critical situations.

Analysis of components by the teams: 
https://github.wdf.sap.corp/SAP-CP-Extension-Factory/community/blob/master/sig-and-wg/sig-production/investigations/nfr_components.md

Preparation epic resulting in guidelines for controller/ui/services:
#1879

Monitoring Documentation:
- [Metrics](https://github.com/kyma-project/examples/tree/master/monitoring-custom-metrics)
- [Alerting](https://github.com/kyma-project/examples/tree/master/monitoring-alert-rules)
- [Dashboards](https://github.com/kyma-project/kyma/tree/master/resources/monitoring/charts/grafana#making-a-dashboard-part-of-kyma-installation)

AC:
All Kyma Components the team is maintaining and which will stay in mid-term future are monitored
- Metrics exposed and documented
- alerts are configured - part of the alert is a short description, whats wrong and how to fix it (or an link to the documentation) to bring the product support in a position to react on the problem without knowing the details
- grafana dashboards are configured
- Make the steps part of your DoD

**Comment by joek** [comment]
Still in progress :-(

**Comment by clebs** [comment]
Discussed with teams having open issues in this epic.
We agreed that each team can add monitoring capabilities to their components at their own pace following the standards ([RED metrics](https://www.weave.works/blog/the-red-method-key-metrics-for-microservices-architecture/) and [USE metrics](http://www.brendangregg.com/usemethod.html))
A joint epic makes no sense anymore, therefore closing this issue.
