### ISSUE TITLE
TestAssetStore does not cleanup testing resources if test fails

### ISSUE THREAD

**Issue by aszecowka** [kyma-project/kyma#3761]
```
func TestAssetStore(t *testing.T) {
	g := gomega.NewGomegaWithT(t)

	cfg, err := loadConfig("APP")
	failOnError(g, err)

	restConfig, err := newRestClientConfig(cfg.KubeconfigPath)
	failOnError(g, err)

	testSuite, err := testsuite.New(restConfig, cfg.Test, t, g)
	failOnError(g, err)

	testSuite.Run()

	testSuite.Cleanup()
}
```
Internally, gomega is used, and if some assertion fails, the next steps are not executed; in our case failing assertion happens in `Run` step and `Cleanup` is not executed.

**Comment by derberg** [comment]
@michal-hudy can you please verify if this is still the case?

**Comment by michal-hudy** [comment]
Resources are left for investigation, but tests on start are removing old resources, so issue can be closed.
