### ISSUE TITLE
CRD are not removed when the Service Catalog chart is uninstalled

### ISSUE THREAD

**Issue by mszostok** [kyma-project/kyma#3763]
**Description**

In Service Catalog we are installing the CRD using the [crd-install](https://github.com/helm/helm/blob/master/docs/charts_hooks.md#defining-a-crd-with-the-crd-install-hook) hook which generates such problems:

- installed CRDS are not deleted when someone is deleting the Hem Release
- installed CRDs are not updated when someone is executing the Helm Upgrade action

To have the backward compatibility we need to remove only the CRDs and CRs without triggering the deletion flow (going through controller-manager)

AC: 

- when triggering `helm delete` the CRDs and CRs are deleted without triggering the deletion flow
- when executing `helm upgrade` then CRDs are also updated. 

------

### Details and background

The problem with the CRDs are much more complicated.
When you delete CRDs then Kubernetes is deleting also the CRs but when CRs have finalizers and the controller who takes care about removing those finalizers is already remove then we have orphaned resources. **The CRDs are never deleted because the CRs are never released (finalizers are not removed).**

Additionally:
- we need to decide if user really wants to delete the underlying CRs or not. 
- we need to decide what to do If the CRs could not be deleted? Should we force deletion or not? Should we trigger deletion via controller or not? and so on and so forth.

please be familiar with this issue: https://github.com/helm/helm/issues/4863

**Comment by mszostok** [comment]
## Tech details
- both the webhook server and controller manager are waiting for CRDs (readiness probe)
- CRDs are part of the helm release
- we have a pre-delete hook
  - scale down controller-manager
  - remove the CRDs
  - remove the finalizers from not delete CRs

**Comment by PK85** [comment]
Reestimated to 5SP (new sprint)
