### ISSUE TITLE
I can create service Instances without filling required fields

### ISSUE THREAD

**Issue by atakanyenel** [kyma-project/kyma#3766]
**Description**
I have an external bundle registered to service catalog. I have required fields. In the create instance wizard, I can click the `create Instance` button without filling the required fields.

Kyma version is from PR-3475
**Expected result**
 I was expecting create Instance button to be disabled until I entered all the required info.

**Actual result**
The required values are replaced with empty string and instance created.

**Steps to reproduce**
- `kubectl create configmap testing-repo-url -n kyma-system --from-literal=URLs=https://github.com/atakanyenel/bundles/releases/download/0.5.0/index.yaml`

- `kubectl label configmap testing-repo-url -n kyma-system helm-broker-repo=true`

- Go to service catalog, click newly added instances,click add once and create instance without filling required fields.

![Capture](https://user-images.githubusercontent.com/7947572/56284761-bf1bfa00-6115-11e9-93a5-9007c33ab7a5.PNG)

**Troubleshooting**

**Comment by aerfio** [comment]
note to self - remember abot test!

**Comment by derberg** [comment]
- extend scope with extending testing bundle https://github.com/kyma-project/bundles/blob/master/bundles/testing-0.0.1/plans/full/create-instance-schema.json with field where string is validated against a given regex
- make sure in UI tests we test required field and regex (talk to bundle repo owners to release new testing bundle)

**Comment by aerfio** [comment]
Blocked by https://github.com/kyma-project/bundles/issues/79 <- once it's merged we'll make new release at `bundles` repo and add tests for docs
