### ISSUE TITLE
Update to knative eventing v0.5.0

### ISSUE THREAD

**Issue by abbi-gaurav** [kyma-project/kyma#3771]
To stay in sync, we should update the knative eventing and nats provisioner to the same version as being done in the serving PR https://github.com/kyma-project/kyma/pull/3579.

The person working on this task can align with @JoergBastian

>Note: Kyma eventing code that interacts with knative also should be updated to use new knative versions.

**AC**
- [ ] knative eventing and NATSS CCP have been upgraded to v0.5.0

**Comment by suleymanakbas91** [comment]
@abbi-gaurav Shall we consider upgrading to `v0.5.1` instead as in [this PR](https://github.com/kyma-project/kyma/pull/3579)?
