### ISSUE TITLE
Local installation fails on OSX

### ISSUE THREAD

**Issue by stephan-beutel-sap** [kyma-project/kyma#380]
Confirm these statements before you submit the issue:

- [x] I have searched open and closed issues for duplicates.
- [x] I have read the contributing guidelines.
---

**Description**

With a complete fresh setup, the local installation fails with an error when trying to set the entries in the hosts file.

The complete output of the cmr/run.sh:
`MACBOOK:installation sbeutel$ cmd/run.sh
################################################################################
# Minikube setup with driver hyperkit
################################################################################
Starting local Kubernetes v1.10.0 cluster...
Starting VM...
Getting VM IP address...
WARNING: The localkube bootstrapper is now deprecated and support for it
will be removed in a future release. Please consider switching to the kubeadm bootstrapper, which
is intended to replace the localkube bootstrapper. To disable this message, run
[minikube config set ShowBootstrapperDeprecationNotification false]
Moving files into cluster...
Setting up certs...
Connecting to cluster...
Setting up kubeconfig...
Starting cluster components...
Kubectl is now configured to use the cluster.
Loading cached images from config file.
Waiting for minikube to be up...
Keep calm, there are 15 possibilities and so far it is attempt number 1
No resources found.
Keep calm, there are 15 possibilities and so far it is attempt number 2
Minikube is up
Minikube IP address: 192.168.64.7
Adding apiserver.kyma.local console.kyma.local catalog.kyma.local instances.kyma.local dex.kyma.local docs.kyma.local lambdas-ui.kyma.local ui-api.kyma.local minio.kyma.local jaeger.kyma.local grafana.kyma.local  configurations-generator.kyma.local gateway.kyma.local connector-service.kyma.local to /etc/hosts on Minikube
127.0.0.1 apiserver.kyma.local console.kyma.local catalog.kyma.local instances.kyma.local dex.kyma.local docs.kyma.local lambdas-ui.kyma.local ui-api.kyma.local minio.kyma.local jaeger.kyma.local grafana.kyma.local  configurations-generator.kyma.local gateway.kyma.local connector-service.kyma.local
Password:
sed: can't read /kyma.local/d: No such file or directory`

Actual checkout from Kyma repo
minikube version: v0.28.2
kubernetes version: Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.2", GitCommit:"bb9ffb1654d4a729bb4cec18ff088eacc153c239", GitTreeState:"clean", BuildDate:"2018-08-08T16:31:10Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"darwin/amd64"}
OSX 10.13.6

**Expected result**

Local installation is completed and accessable.

**Actual result**

Local installation fails while trying to set the entries in the hosts file.

**Steps to reproduce**

- Fresh installation of all tools (Kubernetes, minikube, hyperkit driver) in the recent version
- checkout actual Kyma from repository
- run cmd/run.sh

**Troubleshooting**

no clue what to do/try out to solve this.

**Comment by stephan-beutel-sap** [comment]
After some more investigation, I found the problem.
I installed gnuutils on my OSX, which changes the sed command. Inside the scripts only the uname is checked. So on OSX the sed syntax changes which causes the installer to fail.

Probably there should be a check included to use the right sed command, not only by uname.

**Comment by nderraugh** [comment]
I also encountered this.  Too bad a check/warning can't be added.
`which sed`:
`/usr/bin/sed` vs. `/usr/local/opt/gnu-sed/libexec/gnubin/sed`

**Comment by Morriz** [comment]
any updates if this will be fixed? how are we to proceed otherwise?

**Comment by Morriz** [comment]
Please reopen this. No need to rely on host OS, as we can use docker. This is obviously a bad decision when offering containerized software.
