### ISSUE TITLE
CBS tests failed while waiting for ClusterDocsTopic ready

### ISSUE THREAD

**Issue by tgorgol** [kyma-project/kyma#3815]
**Description**

Console backend service acceptance tests fail while waiting for ClusterDocsTopic ready.

```
--- FAIL: TestClusterDocsTopicsQueries (360.61s)
    clusterdocstopic_test.go:85: Create clusterDocsTopic example-cluster-docs-topic-1
    clusterdocstopic_test.go:56: Check subscription event of clusterDocsTopic example-cluster-docs-topic-1 created
    clusterdocstopic_test.go:85: Create clusterDocsTopic example-cluster-docs-topic-3
    clusterdocstopic_test.go:85: Create clusterDocsTopic example-cluster-docs-topic-2
    clusterdocstopic_test.go:91: Wait for clusterDocsTopic example-cluster-docs-topic-1 Ready
    require.go:794: 
        	Error Trace:	clusterdocstopic_test.go:93
        	            				clusterdocstopic_test.go:65
        	Error:      	Received unexpected error:
        	            	waiting for resource failed in given timeout 360.000000 second(s)
        	Test:       	TestClusterDocsTopicsQueries
FAIL
```

**Expected result**

ClusterDocsTopic should be in ready state or the tests shouldn't timeout.

**Actual result**

Tests timeout.

**Steps to reproduce**

Failed jobs:
1. https://status.build.kyma-project.io/view/gcs/kyma-prow-logs/pr-logs/pull/kyma-project_kyma/3754/pre-master-kyma-integration/1119251799170093057
2. https://status.build.kyma-project.io/view/gcs/kyma-prow-logs/pr-logs/pull/kyma-project_kyma/3754/pre-master-kyma-integration/1119224494687260673
3. https://status.build.kyma-project.io/view/gcs/kyma-prow-logs/pr-logs/pull/kyma-project_kyma/3754/pre-master-kyma-gke-integration/1119224494687260674
4. https://status.build.kyma-project.io/view/gcs/kyma-prow-logs/pr-logs/pull/kyma-project_kyma/3754/pre-master-kyma-gke-integration/1119251799170093058
5. https://status.build.kyma-project.io/view/gcs/kyma-prow-logs/pr-logs/pull/kyma-project_kyma/3821/pre-master-kyma-gke-integration/1120635416895033346

**Comment by derberg** [comment]
not valid anymore
