### ISSUE TITLE
Create Istio configuration patch process

### ISSUE THREAD

**Issue by piotrmsc** [kyma-project/kyma#382]
Confirm these statements before you submit the issue:

- [x] I have searched open and closed issues for duplicates.
- [x] I have read the contributing guidelines.
---

**Description**
* It should be possible to install istio from raw istio charts and then apply kyma with created istio patch.
* Copy official ISTIO 1.0.2 charts and add additional step to install istio patch in the installer.

Hint:
Consider creating a job which will do the patch triggered by installer

**Reasons**

We want to allow adaptation of Kyma with knative.

**Comment by sjanota** [comment]
After adding new step to installer and bumping istio to 1.0.2 previously working patch got broken. I'm working now on making it green again.
