### ISSUE TITLE
Improve Asset Store performance

### ISSUE THREAD

**Issue by michal-hudy** [kyma-project/kyma#3831]
**Description**

Processing Assets by Asset Store works slowly because we are processing large files (for example Kyma sources). Kubebuilder has ability to scaling controllers to many threads - we should enable it.

Please consider also uploading files to Minio in multiple workers.

**Reasons**

Improve performance of the Asset Store.

**Attachments**

**Comment by m00g3n** [comment]
Setup | mean | std | max | min | 25% | 50% | 75%
-- | -- | -- | -- | -- | -- | -- | --
cpu300m_mem128Mi_rec3_assets30 | 171.775716 | 4.483668 | 182.007164 | 166.939571 | 168.452605 | 170.174112 | 173.316536
cpu300m_mem256Mi_rec3_assets30 | 123.871729 | 6.123934 | 122.134079 | 112.976212 | 122.134079 | 122.903079 | 127.876449
cpu300m_mem512Mi_rec3_assets30 | 119.303909 | 4.099631 | 133.795255 | 114.415521 | 117.008802 | 118.469089 | 119.75415
cpu600m_mem128Mi_rec3_assets30 | 95.106682 | 6.238015 | 106.695423 | 83.106774 | 93.079077 | 94.789672 | 96.550103
cpu600m_mem256Mi_rec3_assets30 | 74.377285 | 4.130129 | 80.630973 | 67.005229 | 72.395471 | 73.694314 | 78.28612
cpu600m_mem512Mi_rec3_assets30 | 72.25913 | 5.770005 | 87.981252 | 62.836799 | 69.909335 | 71.804669 | 73.006834
cpu900m_mem128Mi_rec3_assets30 | 72.235723 | 5.314121 | 81.940007 | 64.918206 | 69.340824 | 70.518952 | 75.774245
cpu900m_mem256Mi_rec3_assets30 | 64.559275 | 7.394188 | 75.330198 | 56.80547 | 57.992597 | 62.613424 | 71.395429
cpu900m_mem512Mi_rec3_assets30 | 62.124858 | 3.207966 | 66.646909 | 55.410425 | 60.593685 | 62.246555 | 63.900672

**Comment by derberg** [comment]
@m00g3n I'm missing info about current setting, that with current cpu500 and memory256 we are able to get a performance that handles 30 assets with package of size 8MB in Xseconds
