### ISSUE TITLE
Remove old content bucket from minio

### ISSUE THREAD

**Issue by derberg** [kyma-project/kyma#3836]
**Description**

- create a new migration script that removes the content bucket and explain clearly in RN or as a separate migration guide what does that mean, and how to migrate this data if they want to keep it for future (only if others managed to migrate brokers and service classes docs)
- prow jobs for docker images with documentation - remove
- remove docs builder from tools

**Reasons**

With the introduction of Headless CMS we have to do some cleanup in minio and solve issues that could not be solved with the previous solution

**Comment by pkosiec** [comment]
Docs job removal is done here: https://github.com/kyma-project/test-infra/pull/970
