### ISSUE TITLE
Replace hostNetwork with hostAliases in Console Backend Service

### ISSUE THREAD

**Issue by Szymongib** [kyma-project/kyma#3841]
**Description**

Istio Sidecar is not injected to `console-backend-service` on Minikube because it uses `spec.hostNetwork`. It can be replaced with `spec.hostAliases` to stop preventing sidecar injection. 

**Reasons**

To secure communication between `console-backend-service` and `connector-service` Istio sidecar is required (issue #2982).

**Comment by derberg** [comment]
@Szymongib could you elaborate a bit more here, how local Minikube issue correlates with https://github.com/kyma-project/kyma/issues/2982 that I guess is a cluster/production related issue

**Comment by derberg** [comment]
Some details here https://kyma-community.slack.com/archives/CD172NFCJ/p1557122032068500?thread_ts=1556738591.005700&cid=CD172NFCJ
