### ISSUE TITLE
Recurring timeouts on application-connector-ingress

### ISSUE THREAD

**Issue by Demonsthere** [kyma-project/kyma#3842]
**Description**

On several instances (both pre and post) jobs started failing due to timeouts caused by `application-connector-ingress`. Please investigate

**Troubleshooting**

- https://status.build.kyma-project.io/view/gcs/kyma-prow-logs/pr-logs/pull/kyma-project_kyma/3839/pre-master-kyma-gke-integration/1121025492305055747
- https://status.build.kyma-project.io/view/gcs/kyma-prow-logs/pr-logs/pull/kyma-project_kyma/3839/pre-master-kyma-gke-central-connector/1121025492309250049
- https://status.build.kyma-project.io/view/gcs/kyma-prow-logs/logs/post-master-kyma-gke-central-connector/1121022341447421954

**Comment by Szymongib** [comment]
All failures occurred around the same time which correlates with manual removal of IP addresses (as we hit the quota). 

From logs, we can see that IP address reserved by the job was deleted manually while it was running, which caused that the Load Balancer could not be created, which resulted in Nginx Ingress not reaching `Ready` state.
