### ISSUE TITLE
Bind only selected Service Classes to the namespace

### ISSUE THREAD

**Issue by pbochynski** [kyma-project/kyma#3843]
**Description**
The application can register many service classes (APIs & Events). It should be possible for the administrator to select only those classes that should or can be enabled in the given namespace. 
There should be still a possibility to register all service classes to the namespace (current behaviour). In this case, it is expected that also service classes added after binding is done eventually will be available in the namespace.

**Reasons**
Service classes are tied to credentials/authorizations, hence it will be beneficial to offer more granular options to enable APIs/credentials to developers in a given namespace. 

**AC**
- UI/UX designs provided
- keep possibility to register all service classes to the namespace (current behaviour)
- select only those classes that should or can be enabled in the given namespace
  - ApplicationMapping CRD needs be extended with serviceClassIds attribute
  - UI and console-backend-service needs to list the serviceClassIds from Application CR and then allow to pass some of them to ApplicationMapping CR
- service classes added after binding is done eventually will be available in the namespace.
- all services option marked then updated of the application is always taken into account
- if 2 services added, application update causes only deletetion

**UI/UX views**

<img width="1084" alt="Screen Shot 2019-05-10 at 10 53 33" src="https://user-images.githubusercontent.com/9609118/57515035-04e17200-7312-11e9-8fa7-6fed5f1ee742.png">
<img width="1081" alt="Screen Shot 2019-05-10 at 10 55 26" src="https://user-images.githubusercontent.com/9609118/57515098-25a9c780-7312-11e9-96a2-1f41063e479d.png">
<img width="1079" alt="Screen Shot 2019-05-10 at 10 56 06" src="https://user-images.githubusercontent.com/9609118/57515189-52f67580-7312-11e9-89c9-2f8d82c65974.png">
<img width="1076" alt="Screen Shot 2019-05-10 at 10 57 37" src="https://user-images.githubusercontent.com/9609118/57515268-7e796000-7312-11e9-95a0-1926d61f40d8.png">
<img width="1079" alt="Screen Shot 2019-05-10 at 10 58 34" src="https://user-images.githubusercontent.com/9609118/57515322-a10b7900-7312-11e9-9155-15f515a4dc3d.png">

**Comment by piotrmiskiewicz** [comment]
Define ApplicationMapping struct: https://github.com/kyma-project/kyma/pull/4114

**Comment by jasiu001** [comment]
**New features in console backend service**

To handle new functionality by graphQL, two queries were modified and one mutation was added.

**enableApplication**

```
mutation ($namespace: String!, $application: String!, $all: Boolean, $services: [ApplicationMappingService]) {
  enableApplication(namespace: $namespace, application: $application, allServices: $all, services: $services) {
    namespace
    application
    allServices
    services
  }
}
```

`enableApplication` got two new parameters:
  - `allServices` (bool) which informs, user chose all services or select specific services
     (mark all services on the list is not equal to allServices as `true`)
  - `services` (array) collection of objects with, for now, one parameter `id` e.g.
  ```
  "services":[
    {"id":"ac031e8c-9aa4-4cb7-8999-0d358726ffaa"},
    {"id":"48ab05bf-9aa4-4cb7-8999-0d3587265ac3"}
  ]
  ```
This two fields are not required, which gives us backward compatibility. If `allServices` is not send
it will be mark as `true` by default.
If `allServices` will be set to `true` and `services` are not be emtpy then its value will be skipped.

**overloadApplication**
```
mutation ($namespace: String!, $application: String!, $all: Boolean, $services: [ApplicationMappingService]) {
  overloadApplication(namespace: $namespace, application: $application, allServices: $all, services: $services) {
    namespace
    application
    allServices
    services
  }
}
```

`overloadApplication` is similar to `enableApplication` but is used to update `ApplicationMapping` status

**application**

```
query Application($name: String!) {
    application(name: $name) {
      description labels name enabledInNamespaces status services {
        id
        displayName entries {
          type __typename
        } __typename
      } __typename
    	enabledMappingServices {
        namespace
        allServices
        services {
          id
          exist
          displayName
        }
      }
    }
  }
```
- `application` got extra field `enabledMappingServices` with information about `services` enabled in specific namespace.
- Each `service` has id, name and field `exist` which informs concrete service still exist in `Application`. If `service` exist in `ApplicationMapping` but not exist in `Application` (`exist: false`) then name shouldn't be display to user but the id should be send to backand service (e.g. during update `overloadApplication` operation)
- `enabledInNamespaces` field is not remove to gives us backward compatibility.
