### ISSUE TITLE
Provide support for data events in Kyma eventing

### ISSUE THREAD

**Issue by abbi-gaurav** [kyma-project/kyma#3854]
**Description**
The current Kyma eventing model semantics fits better for business events which contain minimalistic data such as object-ids and then the serverless pulls the data from the application.

There could be other scenarios where the application would like to send data events that contain the full object e.g. a `purchase order`. Such events can be used to synchronize among various applications connected via Kyma. In such scenarios, we will need additional semantics that fits with data events such as `correlation-ids` and other business metadata (possibly as headers) that might be required by the receiver to identify the source and other domain information.

**Comment by pbochynski** [comment]
@Abd4llA Please verify it is really done.

**Comment by anishj0shi** [comment]
with cloud events, an eventing data can be anything a sender wants. and the data field and the extension fields as per cloud events spec 1.0 is pretty extensive.
