### ISSUE TITLE
Provide support for in-cluster events

### ISSUE THREAD

**Issue by abbi-gaurav** [kyma-project/kyma#3855]
**Description**
As a developer, I should be able to define and generate internal events to trigger asynchronous business workflows.

At present, the eventing in Kyma is tightly coupled with the aspect of events being sent by an external solution. e.g. `source-id` which identifies the external solution is used as a part of publishing an event in Kyma.

For events generated inside Kyma, the following open questions or design details needs to be answered:

* How the origin of the internal event is identified? (events originated from the Kyma environments???)
* How the event schema will be published?
* How the event schema will be made available to the developers?
* Do we need concepts such as event activation for internal events?

**Comment by anishj0shi** [comment]
https://github.com/kyma-project/kyma/issues/3961#issuecomment-635218177
