### ISSUE TITLE
Enable sending custom extension headers in Kyma eventing

### ISSUE THREAD

**Issue by abbi-gaurav** [kyma-project/kyma#3856]
**Description**
* Kyma eventing by default should forward all the headers with the CloudEvents Extension prefix.

The prefix is : `ce-`

Refer : https://github.com/cloudevents/spec/blob/master/http-transport-binding.md#31-binary-content-mode

In case the headers have the same name as the one used by kyma eventing e.g. `CE-Event-type`, the precedence should be given to the one derived from the payload.

e.g. a header of the form  `ce-my-company-passportid` should be delivered to the consumer or the lambda.

Note: Headers are case-insensitive

**AC**
- [x] Headers sent with `ce-` prefix while publishing an event are delivered to Knative eventing and lambda.

**Comment by abbi-gaurav** [comment]
Sending `CE-` headers from an application to Kyma is not getting delivered to Lambda.

e.g. I sent `Ce-Corr-Id:123` but I do not see it in lambda logs

### event sent
```
echo '{"event-type" : "order.created", "event-type-version" : "v1", "event-time" : "2018-05-02T22:08:41+00:00", "data" : {"orderCode" : "expect-ce"}}'|curl -X POST -d @- https://gateway.${KYMA_DOMAIN}/${APP_NAME}/v1/events --header "Ce-Corr-Id: 123" --cert generated.pem -k

{"event-id":"f1832d5b-ec98-4036-96bc-cd1fd012f135","status":"published","reason":"Message successfully published to the channel"}
```

### Lambda logs
I do not see the header `Ce-Corr-Id`
```
{ orderCode: 'expect-ce' }
{ host: 'test.workshop:8080',
  'user-agent': 'Go-http-client/1.1',
  'content-length': '25',
  'ce-event-id': 'f1832d5b-ec98-4036-96bc-cd1fd012f135',
  'ce-event-time': '2018-05-02T22:08:41+00:00',
  'ce-event-type': 'order.created',
  'ce-event-type-version': 'v1',
  'ce-knativehistory': 'kcugjcrgxkoijubwl6mqm5247x6yfsaag.kyma-system.channels.cluster.local',
  'ce-source-id': 'test-ce-extension-headers',
  'content-type': 'application/json',
  'x-b3-flags': '0',
  'x-request-id': '35a4464d-beb4-4f47-af28-7bdcb48b5926',
  'accept-encoding': 'gzip',
  'x-forwarded-proto': 'http',
  'x-forwarded-client-cert': 'By=spiffe://cluster.local/ns/workshop/sa/default;Hash=70e9e941d05ddaaf4e85c25b9cc11298f9d9d0838115cded5ac7157d5fee32bf;Subject="";URI=spiffe://cluster.local/ns/knative-eventing/sa/natss-dispatcher',
  'x-b3-traceid': '79fe87d19d91f544',
  'x-b3-spanid': 'f9030af02f066fab',
  'x-b3-parentspanid': 'ee20e541f95f51f0',
  'x-b3-sampled': '1' }
```

**Comment by marcobebway** [comment]
I updated the event-service image as part of this PR: kyma-project/kyma#4384.

I verified that **ce-** headers are forwarded from an external application to lambda.
