### ISSUE TITLE
Recurring fails on test-core-core-ui-acceptance

### ISSUE THREAD

**Issue by Demonsthere** [kyma-project/kyma#3861]
**Description**

Over the last few days there have been several instances in which `test-core-core-ui-acceptance` and only them failed.  The errors in the logs are `net::ERR_ABORTED` and `net::ERR_UNKNOWN_URL_SCHEME`
**Expected result**

**Troubleshooting**

Example failed builds
- https://status.build.kyma-project.io/view/gcs/kyma-prow-logs/logs/post-master-kyma-gke-upgrade/1121298912620056576
- https://status.build.kyma-project.io/view/gcs/kyma-prow-logs/logs/post-master-kyma-gke-central-connector/1121329111545942019

**Comment by dariadomagala** [comment]
Already fixed
