### ISSUE TITLE
Refactor chart files for Headless CMS

### ISSUE THREAD

**Issue by kazydek** [kyma-project/kyma#3885]
**Description**

Replace hardcoded values in templates with placeholders in CMS [templates](https://github.com/kyma-project/kyma/blob/master/resources/cms/charts/cms-controller-manager/templates/webhook-config-map.yaml#L14) (check if there are any other such examples) and move them to the given `values.yaml` file.

Create a configuration document that includes the list of values from the `values.yaml` file that are recommended for configuration. Rely on the configuration template (ask one of the TWs for the advice). 

**Reasons**

Each component should have a configuration document that guides the user which values in charts can be modified safely.

**Comment by derberg** [comment]
we need to do it while moving headless cms outside the kyma repo

**Comment by derberg** [comment]
closing for now as a lot has changed in charts, new Rafter took over asset store and charts were heavily reworked.
