### ISSUE TITLE
Upgrade tiller to 2.13

### ISSUE THREAD

**Issue by sayanh** [kyma-project/kyma#3887]
**Description**

Few helm hooks don't work in v2.10. E.g. `crd-install` (Details are [here](https://github.com/helm/helm/issues/5054) )

**Reasons**

These issues are resolved in [v2.13.1](https://github.com/helm/helm/releases/tag/v2.13.1)

**Comment by kubadz** [comment]
@sayanh Is that still an important and urgent issue for you? Because we are planning to upgrade helm to the version 3.0 as soon as it will be released and stable. Will it be ok for you to wait until then?

**Comment by kubadz** [comment]
Agreed in a private conversation to close this issue.
