### ISSUE TITLE
Unstable nightly cluster AKS

### ISSUE THREAD

**Issue by Demonsthere** [kyma-project/kyma#3888]
**Description**

Errors happening in the nightly aks cluster:
- Replicas are not updated and available for deployment /hb-redis-micro-a48a1298-6817-11e9-9d32-0ae458d436a9-redis
- Replicas are not updated and available for deployment /test-hello
- Replicas are not updated and available for deployment /test-event
- No API servers are reachable or all have disappeared from service discovery

**Comment by derberg** [comment]
@Demonsthere please provide some more details. What actually is an issue and who and how can fix that? For now it is hard to assign any specific milestone to it

**Comment by Demonsthere** [comment]
Deprecated problem, can be closed now.
