### ISSUE TITLE
Installation steps for GKE fail

### ISSUE THREAD

**Issue by suleymanakbas91** [kyma-project/kyma#3893]
**Description**

When I follow the installation steps for GKE, in the phase of [preparing installation config file](https://kyma-project.io/docs/master/root/kyma/#using-your-own-image), I use the following command to prepare the deployment file (because I have a cluster with version 1.12.6-gke.X and above):

```
(cat installation/resources/installer.yaml ; echo "---" ; cat installation/resources/installer-config-cluster.yaml.tpl ; echo "---" ; cat installation/resources/installer-cr-cluster.yaml.tpl) | sed -e "s/__PROMTAIL_CONFIG_NAME__/promtail-k8s-1-14.yaml/g" | sed -e "s/__DOMAIN__/$DOMAIN/g" |sed -e "s/__TLS_CERT__/$TLS_CERT/g" | sed -e "s/__TLS_KEY__/$TLS_KEY/g" | sed -e "s/__.*__//g" > my-kyma.yaml
```

This creates a problematic file that is blocking the installation: 

![Screenshot 2019-04-29 at 14 31 16](https://user-images.githubusercontent.com/5543238/56896300-9e479300-6a8b-11e9-952e-de66c0969d15.png)

**Comment by adamwalach** [comment]
Fixed by #3901
