### ISSUE TITLE
Simplify cluster installation process

### ISSUE THREAD

**Issue by piotrmsc** [kyma-project/kyma#3932]
**Description**

Currently, in order to install kyma on a cluster you have to execute commands which basically replace placeholders in configuration yaml with empty string values. Additionally, you have a different command for k8s < 1.12.6 and  > 1.12.6 for promtail. We should stick to the newer k8s versions.
Take a look for example [here](https://kyma-project.io/docs/root/kyma/#prepare-the-installation-configuration-file) step 4.
To simplify this process, all placeholders can be moved to chart values as empty strings. 
Our installation documentation should describe how to create a configmap with an override for example with own domain and TLS certificate instead of describing how to export variable and execute cat& sed commands.

Additionally, we can label installation CR with action install directly in the yaml file. This way no additional steps is required to trigger installation.

**Reasons**

Kyma should be easy to install without any sed&cat commands, just pure kubectly apply.

**Attachments**

**Comment by Tomasz-Smelcerz-SAP** [comment]
See also: https://github.com/kyma-project/test-infra/issues/1024
