### ISSUE TITLE
Service Instance Binding Prefix issues

### ISSUE THREAD

**Issue by brendandobbs** [kyma-project/kyma#3937]
**Description**

Service Instance Binding from the Lambda function using a prefix results in a env variable that looks like this: occ-GATEWAY_URL. 

Accessing the variable like this from nodejs fails because of the hyphen : process.env.occ-GATEWAY_URL.

It's a minor issue but can we use another character as the separator (e.g. '_') to make it easier for developers.

Also, when creating the binding from the Service Instance, no separator is added between the prefix and GATEWAY_URL (e.g. occGATEWAY_URL).

**Expected result**

* Creating the Service Binding from the Lambda or the Service Instance gives the same result
* The env variable name can easily be accessed in nodejs (and other programming languages by avoiding using any special characters.

**Comment by pbochynski** [comment]
Please copy the solution from service instance view and apply it in the Lambda UI.
