### ISSUE TITLE
Backup tests for Loki

### ISSUE THREAD

**Issue by a-thaler** [kyma-project/kyma#3944]
**Description**
Have a test which assures that the backup and restore functionality of kyma will reveal Loki in an operational state and the log data is still accessible

**Reasons**
We need to assure that a restore will recover log data

**Suggestion**
*Pre backup*
Set up a service listening for HTTP requests with log output
Make a HTTP call to that service
Retrieve the logs and keep them in-memory for later comparison

*Post restore*
Retrieve the logs and compare them with the kept ones

AC:
There is a test to verify logging works post restore

**Comment by suleymanakbas91** [comment]
There is no way to keep anything in memory now as we have two separate executions in two different clusters before and after the restore.

**Comment by suleymanakbas91** [comment]
Not valid any more.
