### ISSUE TITLE
Monitoring for tracing chart

### ISSUE THREAD

**Issue by a-thaler** [kyma-project/kyma#3946]
**Description**
Assure that we have good metrics and alerts in place to detect problems with jaeger.

Monitoring Documentation:
- [Metrics](https://github.com/kyma-project/examples/tree/master/monitoring-custom-metrics)
- [Alerting](https://github.com/kyma-project/examples/tree/master/monitoring-alert-rules)
- [Dashboards](https://github.com/kyma-project/kyma/tree/master/resources/monitoring/charts/grafana#making-a-dashboard-part-of-kyma-installation)

AC:
Metrics are visible in Grafana and we have alerts in place

**Comment by suleymanakbas91** [comment]
Implemented by https://github.com/kyma-project/kyma/pull/7964.
