### ISSUE TITLE
Ensure lambdas are automatically listed in Jaeger dropdown to easily access traces related to the lambda.

### ISSUE THREAD

**Issue by tricky42** [kyma-project/kyma#3953]
**Description**
If you create a lambda right now in Kyma it will not automatically be listed in the Services dropdown in Jaeger (although the number of services is increased). You can manually add a label app=<fct-name> to the lambda, but this is an unnecessary step for the user and it is although not documented so users wont know about it.

**Current Situation**
Currently, istio is configuring the envoy (istio-proxy) to use the "app" label of a pod as service name for tracing. If there is no label provided it will use the static name "istio-proxy". As the lambda pods are not labeled with "app", the lambda name is not used.

Acceptance Criteria:
- creating a lambda and triggering it should
  - list the lambda automatically in the Jaeger services dropdown
  - the lambdas name can be found in the related trace
  - no additional step required by user

**Comment by a-thaler** [comment]
We brainstormed on the solution for the topic and we had this:

**conclusion**
- Istio will improve over time to provide better ways, but currently, there is no way that the service name gets derived automatically from pod metadata. It is fully based on the app label.
- When writing an application (based on Deployment) it is the developers responsibility to put the app label, same should be for functions.
- Same should be for functions, if you write a function manifest you need to add the app label.
- When using the UI to create applications, then you want to get things done with few clicks and maybe use the result as a starting point even for later development. Here some transparent magic should apply

**Action Items**
- Ensure that all examples are using the app label everywhere
- Improve the UI to put the app label transparently to the initial set of labels for a lambda

**Comment by tricky42** [comment]
Hi guys, 

cant we find a way to handle such cases more efficiently. I am 100% sure that the actual implementation of #4194 doesn't require a lot of time. But just in processing the request we now already spend 24 day :(....

**Comment by a-thaler** [comment]
Done as planned, UI is adding the label automatically and all code samples are adjusted to have the label. Thanks for your patience.
