### ISSUE TITLE
Prepare a concept for supporting in-cluster events consumption

### ISSUE THREAD

**Issue by abbi-gaurav** [kyma-project/kyma#3961]
**Description**
As a developer, I should be able to use in-cluster events to create an asynchronous workflow for my business scenario.

Prepare a concept about what all is required in Kyma-eventing to provide a good developer experience when using in-cluster events.
The concept provides the technical architecture required to addresses the following story

* Who all can consume the event?
  * What will be the role of the event activation?
* How we can configure consumption of such in-cluster events?

> Some security notes:
* How to ensure the internal events does not override the events sent from an application?

**Comment by anishj0shi** [comment]
As of today, we don't officially support in-cluster eventing. we would think about it in future. For now. to have in-cluster eventing, we'd recommend using the knative broker-trigger model, (But at your own risk)
