### ISSUE TITLE
Cant save environment variables lambdas in uppercase in admin ui

### ISSUE THREAD

**Issue by GauSim** [kyma-project/kyma#397]
Confirm these statements before you submit the issue:

- [x] I have searched open and closed issues for duplicates.
- [x] I have read the contributing guidelines.
---

**Description**

in kyma admin when creating or editing an lambdas the UI does not let me save env vars in uppercase.
the ui tool-tip says: 

`INVALID VARIABLE NAME: MUST CONSIST OF ALPHANUMERIC CHARACTERS OR '_' AND NO SPACES (E.G. 'VARIABLE_NAME')` all in uppercase

**Expected result**

putting `VARIABLE_NAME` into the input field does not block the "add variable"-button

**Actual result**

"add variable"-button is blocked 
can not save env var, have to rename var to use solution 

see: 
https://image.ibb.co/gy6ovK/Screen_Shot_2018_08_31_at_17_57_31.png 

**Steps to reproduce**

1. create/edit lambdas
2. try to add VARIABLE_NAME as a env var

**Troubleshooting**

i guess UI regex is wrong

**Comment by joek** [comment]
This should be already fixed. You have to update your kyma to the latest version.
