### ISSUE TITLE
Add support for files creation in AssetStore with ConfigMap

### ISSUE THREAD

**Issue by derberg** [kyma-project/kyma#3976]
**Description**

- extend CRDs with support for ConfigMap referencing. Asset CR only for now
- If configmap has 3 keys, we create 3 files and save them to minio with name of the key, just as it works in case of referencing configmap in deployment
- proper documentation/tutorial/example - extend website example
- check if it makes sense to support it as `alternative` to source approach so that you do not have to provide a source but just a few ConfigMaps with assets. 

**Reasons**

Be more flexible for different use cases for Asset Store, like adding a config file to a website stored with Asset Store. User should be able to specify that specific assets should be enhanced with additional files defined with ConfigMap. This was a part of initial proposal https://github.com/kyma-project/community/blob/master/sig-and-wg/sig-core/proposals/asset-store-proposal.md#solution

**Comment by michal-hudy** [comment]
As I see support for ConfigMaps is not documented end example is not updated - so the issue is still valid.
