### ISSUE TITLE
MinIO in gateway mode sometimes responds with 403

### ISSUE THREAD

**Issue by tgorgol** [kyma-project/kyma#3983]
**Description**

MinIO in gateway mode sometimes responds with `403`, when requesting resource, after uploading asset to GCS. In kubernetes the asset is in `Ready` phase, and it is shown in storage browser on GCS. After some time (approximately 5 minutes) the responds "stabilise" and MinIO responds only with `200`.

Once the bug is fixed:
- make sure the prow job for testing Kyma with minio gateway mode is triggered automatically on any change in assetstore component and not only by comment in PR.
- remove dry-run flag from job that cleans buckets that were not cleaned during testing

**Expected result**

MinIO should always respond with `200` when the asset is ready.

**Actual result**

MinIO responds with either `200` or `403`, seemingly nondeterministically for about 5 minutes after uploading asset to GCS.

**Steps to reproduce**

Run asset store integration tests while MinIO is set up in GCS gateway mode.

**Comment by tgorgol** [comment]
After some investigating it seems that this problem is related to having more than 1 replica of minio pod. After reducing replicas number to 1 in minio deployment the problem stopped occurring.

Right now we have 4 minio pods active, and right after uploading an asset only one of those pods responds constantly with `200`, other pods respond constantly with `403` for some time (about 5 minutes) and then start responding with `200` as well.

I'm still not sure what causes the 403 response but my guess right now would be some issue with caching, maybe with how bucket policy is cached.

**Comment by m00g3n** [comment]
@nitish from minio team is analyzing the logs; we are waiting for the response from him

**Comment by m00g3n** [comment]
issue created: https://github.com/minio/minio/issues/7723

**Comment by m00g3n** [comment]
It was agreed, as a temporary solution, to change minio replica number from `4` to `1`.

**Comment by derberg** [comment]
fixed after upgrading to latest minio
