### ISSUE TITLE
Installer - allow to override default kyma configuration when using `installation/cmd/run.sh`

### ISSUE THREAD

**Issue by aszecowka** [kyma-project/kyma#3995]
When I want to modify default kyma configuration I have to create configmap with label `installer=overrides`.
But when I start kyma on minikube by executing `installation/cmd/run.sh` script it is not so easy to do this.
There a `configure-components.sh` script that allows me to do that, but:
- it is not documented
- it removes my custom configuration after applying it. Instead, this file for defining overrides should be added to the gitignore file. 

Currently, overrides can be defined in `components.env` file, consider renaming it.

**Comment by Disper** [comment]
@aszecowka please adjust the issue to the template

**Comment by derberg** [comment]
@a-thaler how does it look like with Kyma CLI? I would say this issue should not really be taken into account as CLI will remove those scripts, so maybe just let's have it as feature request for Kyma CLI?

**Comment by a-thaler** [comment]
I think it is a good idea to not invest here anymore but instead have a good solution provided by CLI, I created an epic for that: https://github.com/kyma-project/cli/issues/89

**Comment by tomekpapiernik** [comment]
Script deprectaed
