### ISSUE TITLE
Describe access to the Kyma started locally from the Java code

### ISSUE THREAD

**Issue by lszymik** [kyma-project/kyma#400]
Confirm these statements before you submit the issue:

- [x] I have searched open and closed issues for duplicates.
- [x] I have read the contributing guidelines.
---

**Description**

The Kyma documentation contains information about adding the local certificate to the trusted OS store. The connection from the Java or other languages to the Application Connector requires adding the same certificate to the Java Keystore or other storages, in case of the different languages.

This must be part of the Kyma installation and linked from the Application Connector docs or it must be part of the Application Connector docs.

**Reasons**

Without certificate loaded to the Java Keystore, the connection will be not possible and there will be no way of performing client certificate exchange or API registration.

**Attachments**

The following command might be used:

```
sudo <JAVA_HOME>/bin/keytool -import -alias “Kyma” -keystore <JAVA_HOME>/jre/lib/security/cacerts -file <KYMA_HOME>/installation/certs/workspace/raw/server.crt
```

The default Java Keystore password is `changeit`.

**Comment by tomekpapiernik** [comment]
As I am going on leave, @klaudiagrz agreed to take care of this issue.

**Comment by lszymik** [comment]
I would like to unduplicate that issue. We need to have now the description of how to add the certificate to the Java key store.
The #610 will have a much bigger scope.
