### ISSUE TITLE
Helm Broker and REB catalog endpoint error status code

### ISSUE THREAD

**Issue by piotrmiskiewicz** [kyma-project/kyma#401]
Confirm these statements before you submit the issue:

- [x] I have searched open and closed issues for duplicates.
- [x] I have read the contributing guidelines.
---

**Description**

Helm Broker and Remote Environment Broker implementation of 'catalog' endpoint returns HTTP 400 in case of any errors. The status code 400 Bad Request is misleading and should be changed to 5xx.
On the other hand, the service catalog implementation does not care about the status code.

**Comment by lszymik** [comment]
It is already fixed.
