### ISSUE TITLE
Adapt knative-serving test to domainName using xip.io 

### ISSUE THREAD

**Issue by sayanh** [kyma-project/kyma#4015]
**Description**

knative-serving test needs to be adapted to xip.io
Sample build: https://status.build.kyma-project.io/view/gcs/kyma-prow-logs/pr-logs/pull/kyma-project_kyma/3825/pre-master-kyma-xip-gke-central-connector/1126439669358137344

**Comment by Demonsthere** [comment]
This is a blocker for xip.io adaptation, please prioritise it .

**Comment by rakesh-garimella** [comment]
The problem we have here is serving tests are not working on `xip.io` domain. The istio ingress does not know about the function name and hence unable to route it to the right function (hence we get 404). This test however works fine on a static domain. We suspect `xip-patch` injects some info into istio and may be its missing something here (we are speculating here). We need to have a deeper understanding how routing works with xip.io and istio ingress together.

**Comment by Demonsthere** [comment]
No. All what `xip-patch` does is creating new overrides for the installer with domain name, certificate and key. Nothing remotely related to routing is happening here.

**Comment by joek** [comment]
@Demonsthere so you are telling me you are doing nothing, so why is the job still failing on clusters with xip-patch?

**Comment by joek** [comment]
Fixed
