### ISSUE TITLE
Configuration documents for Kyma components

### ISSUE THREAD

**Issue by kazydek** [kyma-project/kyma#4028]
**Description**

The purpose of this epic is to create configuration documents for all Kyma components - these documents should list and describe configurable parameters from `values.yaml` files in a given component's charts and sub-charts. 

- Create separate issues for configuration docs for all Kyma components.  
- Create documents based on the existing [template](https://github.com/kyma-project/community/blob/master/guidelines/templates/resources/configuration.md).
- Rely on the already created configuration documents for the [Asset Store component](https://kyma-project.io/docs/master/components/asset-store/#configuration-configuration):
   - Asset Store chart
   - Asset Store Metadata Service sub-chart
   - Asset Store Controller Manager sub-chart
   - Asset Store Upload Service sub-chart
   - Minio sub-chart

>**NOTE:** Every sub-chart should be described in a separate document.

**Reasons**

Have a set of configuration documents that describe which values from the given component's `values.yaml` files you can override.

**Comment by derberg** [comment]
This epic was a great job! a lot of valuable config docs were added
