### ISSUE TITLE
Add homebrew support to Kyma-CLI

### ISSUE THREAD

**Issue by a-thaler** [kyma-project/kyma#4037]
**Description**
Add a formulae for the Kyma-CLI to the official homebrew repository.

AC:
- "brew install kyma-cli" will install the CLI
- no further steps required
 
**Reasons**
Developers can install the CLI with the tool they know with one simple command

**Attachments**
- Kyma-CLI homebrew formula should full-fill official requirements of [core formula](https://docs.brew.sh/Acceptable-Formulae)
- A pull-request should be opened for git repo [homebrew/core](https://github.com/Homebrew/homebrew-core) according [this guide](https://docs.brew.sh/How-To-Open-a-Homebrew-Pull-Request)
- Formula created should follow [homebrew formula guidelines](https://docs.brew.sh/Formula-Cookbook)

**Comment by suleymanakbas91** [comment]
A PR has been created in homebrew/core: https://github.com/Homebrew/homebrew-core/pull/40389
