### ISSUE TITLE
Fix Prometheus and function tests for backup-restore

### ISSUE THREAD

**Issue by abbi-gaurav** [kyma-project/kyma#4039]
**AC**
- [x] Prometheus tests are green for back-up restore tests
- [x] Function tests are green for back-up restore tests

**Comment by sayanh** [comment]
Things to be done:
- [ ] Fix prometheus backup restore test
- [ ] Fix functions backup restore test
- [ ] Merge PR for test-infra (https://github.com/kyma-project/test-infra/pull/973)
- [ ] Merge PR for backup-restore test(https://github.com/kyma-project/kyma/pull/3783)
- [ ] Merge PR for upgrading Ark to Velero (https://github.com/kyma-project/kyma/pull/3840)

**Comment by sayanh** [comment]
@abbi-gaurav Please note the backup-restore job ran successfully today. Prow [link](https://status.build.kyma-project.io/?job=kyma-gke-end-to-end-test-backup-restore)
