### ISSUE TITLE
Release process for CLI

### ISSUE THREAD

**Issue by a-thaler** [kyma-project/kyma#4045]
**Description**
The Kyma CLI needs a technical solution for a repeatable release as well as an integration to the organizational release process of Kyma.

AC:
- For every release of CLI there is a new tag and release page available in the repository
- It is possible to create a patch release not based on latest master but on the latest release
- The binaries for a release are available as Github release attachments and the binaries are not created on a local machine
- A Github release is listing all changelogs and release notes
- A Kyma CLI release uses the version number of the related supported Kyma version
- The release process documentation of kyma is adjusted so that when the process finishes, there is a corresponding Kyma CLI release available

**Attachments**
- @pkosiec recommended to use https://goreleaser.com/
- https://github.com/kyma-project/test-infra/blob/master/prow/jobs/kyma/kyma-artifacts.yaml
- https://github.com/kyma-project/test-infra/blob/master/prow/jobs/kyma/kyma-github-release.yaml
- https://github.com/kyma-project/test-infra/blob/master/development/github-release.sh
- https://github.com/kyma-project/test-infra/blob/master/prow/scripts/build-kyma-artifacts.sh

**Comment by suleymanakbas91** [comment]
[`1.2.0-rc1`](https://github.com/kyma-project/cli/releases/tag/1.2.0-rc1) pre-release is created by **goreleaser** following the approach documented [here](https://github.com/kyma-project/community/blob/60cbd642c2d0efd072af6f946be1498b6d2d88f7/guidelines/releases/release-process.md).
