### ISSUE TITLE
Release requirements for CLI

### ISSUE THREAD

**Issue by a-thaler** [kyma-project/kyma#4046]
**Description**
In order to release the CLI the first time, specific requirements need to be fullfilled:
- do a threat modelling and assure that no critical issues are left
- integrate with a license scanning tool for dependencies
- integrate with a static code analysis tool for known security problems
- integrate automated static code analysis specific for golang
- integrate automated test execution

AC:
- all listed requirements are assured on a regular schedule

Details:
- threat modelling session is organized already
- for license scanning the fossa tool will be used as for kyma itself, contact @a-thaler for configuring of the tool
- for security scan "snyk" should be used, contact @kubadz for configuration

**Comment by clebs** [comment]
Threat modelling was conducted with the following issues to be solved:
- kyma-project/cli#69
- kyma-project/cli#71

There are no other foreseeable challenges on this topic.

**Comment by clebs** [comment]
The CLI repository has been integrated into FOSSA and all License issues have been solved.

**Comment by clebs** [comment]
CI jobs have been updated to run on the moved repository and are passing.

**Comment by clebs** [comment]
CLI has been added to SNyk for periodic and PR security scans:
https://app.snyk.io/org/kyma-project/project/0cbf5597-2330-4486-8c3a-b97715af6267

No vulnerabilities detected.

**Comment by a-thaler** [comment]
done
