### ISSUE TITLE
Create configuration documents for Application Connector

### ISSUE THREAD

**Issue by kazydek** [kyma-project/kyma#4052]
**Description**

Create configuration documents for the **Application Connector** component. 
These documents should list and describe configurable parameters from `values.yaml` files of these charts and their sub-charts:

- [`application-connector-helper`](https://github.com/kyma-project/kyma/tree/master/resources/application-connector-helper)
- [`application-connector-ingress`](https://github.com/kyma-project/kyma/tree/master/resources/application-connector-ingress)
- [`application-connector`](https://github.com/kyma-project/kyma/tree/master/resources/application-connector)

>**NOTE:** Every chart and sub-chart should be described in a separate document.

Make sure you:
- Create the documents based on the existing [template](https://github.com/kyma-project/community/blob/master/guidelines/templates/resources/configuration.md).
- Rely on the already created configuration documents for the [Asset Store](https://kyma-project.io/docs/master/components/asset-store/#configuration-configuration).

**Reasons**

Have a set of configuration documents that describe values from the Application Connector `values.yaml` files you can override.

**Attachments**
It relates to the epic #4028.

**Comment by mmitoraj** [comment]
* NO configuration docs required for the [application-connector-helper](https://github.com/kyma-project/kyma/tree/master/resources/application-connector-helper) as discussed and confirmed with @piotrmsc 
* NO configuration docs required for the [application-connector-ingress](https://github.com/kyma-project/kyma/tree/master/resources/application-connector-ingress) as discussed with @lszymik and confirmed with @pbochynski

**Comment by mmitoraj** [comment]
- NO configuration docs required for the application-connector main chart as discussed and confirmed with @akgalwas 
- NO configuration docs required for the application-broker sub-chart as discussed and confirmed with @polskikiel 
- NO configuration docs required for connection-token-handler sub-chart as discussed and confirmed with @akgalwas 

See also a follow-up ticket for the Framefrog Team - https://github.com/kyma-project/kyma/issues/4396.
