### ISSUE TITLE
Create configuration document for Backup

### ISSUE THREAD

**Issue by kazydek** [kyma-project/kyma#4053]
**Description**

Create a configuration document for the **Backup** component. 
This document should list and describe configurable parameters from the `values.yaml` file of this chart:

- [`velero`](https://github.com/kyma-project/kyma/tree/master/resources/velero)

Make sure you:
- Create the document based on the existing [template](https://github.com/kyma-project/community/blob/master/guidelines/templates/resources/configuration.md).
- Rely on the already created configuration documents for the [Asset Store](https://kyma-project.io/docs/master/components/asset-store/#configuration-configuration).

**Reasons**

Have a configuration document that describes which values from the Backup`values.yaml` file you can override.

**Attachments**
It relates to the epic #4028.

**Comment by kazydek** [comment]
Talked to @joek and he would need to confirm the configurable values with the team and get back to me on the Backup conf docs tomorrow.

**Comment by a-thaler** [comment]
```
global. volumeSnapshotLocation #put content of https://velero.io/docs/v1.0.0/api-types/volumesnapshotlocation/
global. backupStorageLocation # put content of https://velero.io/docs/v1.0.0/api-types/backupstoragelocation/
global. schedules.XXX
  schedule: "0 0 * * *"
  template: # put content of https://kyma-project.io/assets/docs/master/backup/docs/assets/system-backup.yaml
credentials:
  useSecret: true
  secretContents: {}
```

**Comment by kazydek** [comment]
@a-thaler I created a PR BackupStorageLocation and VolumeSnapshotLocation as discussed, but I have a few concerns and questions that I added to the PR.
