### ISSUE TITLE
Refactor chart files for Asset Store

### ISSUE THREAD

**Issue by kazydek** [kyma-project/kyma#4056]
**Description**

Review the charts and sub-charts for the Asset Store and check if any values can be moved from the templates to the respective `values.yaml` files. If you find such examples, replace these hardcoded values in templates with placeholders and move the values to the given `values.yaml` files.

Additionally, update the existing configuration documents for the [Asset Store](https://kyma-project.io/docs/master/components/asset-store/#configuration-configuration) and add any new configurable parameters to them. 

**Reasons**

Make sure all chart values are consistently placed in the `values.yaml` files.

**Comment by mmitoraj** [comment]
still valid

**Comment by mmitoraj** [comment]
still valid

**Comment by derberg** [comment]
closing for now as a lot has changed in charts, new Rafter took over asset store and charts were heavily reworked.
