### ISSUE TITLE
Support HA for publish and push

### ISSUE THREAD

**Issue by abbi-gaurav** [kyma-project/kyma#406]
### Goal

Ensure publish and push features of event bus can accommodate disturbances such as networking issues (due to istio or other reasons)  and others.

 

Publish:
 * Publish is a stateless app

Push:
 * Push is stateful in sense that for each Kyma subscription it will create NATS Streaming Sub on each pod which is a part of queue group.
 * When one pod goes down the other NATS Streaming Subscription will keep on working.
 * After the pod is restarted successfully, the subscription rejoins the queue group.

 

AC:
 * Push and Publish cluster deployments have been scaled to have 2 replicas. The change is not done for minikube/local deployment but only for cluster.
 * The number of replicas is configurable via {{values.yaml}}
 * The push behavior has been verified and logs attached in the comments.

**Comment by montaro** [comment]
Here is a screenshot from my terminals, sending an event to **2 Lambdas** having the same event subscription. 
The Event is received only once by each subscriber/Lambda.  
Killing a **Push** or **Publish** pod, the publish-subscribe is acting normally, single push, single consumption per subscriber/Lambda.
![image](https://user-images.githubusercontent.com/531945/45239504-c9575980-b2e5-11e8-9b53-ebcaaadea325.png)
