### ISSUE TITLE
NamespaceController test fails with velero

### ISSUE THREAD

**Issue by sayanh** [kyma-project/kyma#4064]
**Description**

Ark is upgraded to Velero as a part of this [issue](https://github.com/kyma-project/kyma/issues/3760). But NamespaceController tests keep failing with this set up. 

**Expected result**

Fix NamespaceController with Velero.
Related PRs: https://github.com/kyma-project/kyma/pull/3840
https://github.com/kyma-project/kyma/pull/3783
https://github.com/kyma-project/test-infra/pull/972/

[Get logs for failing tests PR](https://github.com/kyma-project/kyma/pull/4086)

**Comment by piotrmsc** [comment]
@sayanh can you point us test output where we can find what is exactly failing?

**Comment by sayanh** [comment]
[backup-restore.log](https://github.com/kyma-project/kyma/files/3187182/backup-restore.log)

**Comment by Tomasz-Smelcerz-SAP** [comment]
I have found this: ```Cluster:  error restoring /tmp/296090174/resources/persistentvolumes/cluster/pvc-71368f8d-7762-11e9-aef7-42010a9c01c1.json: persistentvolumes "pvc-71368f8d-7762-11e9-aef7-42010a9c01c1" is forbidden: error querying GC
     E PD volume gke-e2etest-prom-d9ffe-pvc-71368f8d-7762-11e9-aef7-42010a9c01c1: GCE persistent disk not found: diskName="gke-e2etest-prom-d9ffe-pvc-71368f8d-7762-11e9-aef7-42010a9c01c1" zone="europe-west3-a"``` In the log output. It looks like infrastructure issue. I don't think it's related to namespace-controller in any way.

**Comment by sayanh** [comment]
It is working now.
