### ISSUE TITLE
Adjust domain of subscriptions.eventing CRD to 'kyma-project.io'

### ISSUE THREAD

**Issue by abbi-gaurav** [kyma-project/kyma#407]
The CRD 'subscriptions.eventing.kyma.cx' is using kyma.cx as domain (group). As kyma.cx was intended to be used for the commercialization aspects of kyma.
 The official domain of kyma is kyma-project.io now, so all CRDs should get adjusted to it.

Prerequisite:
 * -Align with automatix before starting this task.-
 * See YSF-3178

Note:
 * The group will be changed from 
   * {{eventing.kyma.cx ---> eventing.kyma-project.io}}
 * The name will be changed from
   * {{subscriptions.eventing.kyma.cx ---> subscriptions.eventing.kyma-project.io}}

Workflow
 * Do the code changes and regenerate the code
 * Push the changes to the master
 * Get the new image generated
 * Helm chart changes
   * Change the CRD and use the new image.
   * Align with automatix to get their changes.
 * Push to master.

 

AC:
 - group name is adjusted in the CRD
 - all usage is adjusted
 - documentation and examples are adjusted
 - The [e2e flow](https://github.com/kyma-incubator/examples/tree/master/kyma-local-e2e-scenario) with lambda and gateway integration is working after the changes.

**Comment by abbi-gaurav** [comment]
@montaro I do not see the following done
* Subscription CRD not changed [link](https://github.com/kyma-project/kyma/blob/master/resources/cluster-essentials/templates/eventing-subscription.crd.yaml)
* examples still show the old subscription custom resource `kyma-project/examples`
* Has the e2e flow been verified?

Could you please add comments regarding the acceptance criteria?

**Comment by montaro** [comment]
@abbi-gaurav 
- The PR waiting for the second review round approval
- I reviewed the `examples` PR https://github.com/kyma-project/examples/pull/79, but it's not merged yet
- The e2e low test locally and in a cluster was verified by Sayan

**Comment by montaro** [comment]
@abbi-gaurav All A.C. are achieved now.
