### ISSUE TITLE
Create configuration documents for Service Mesh

### ISSUE THREAD

**Issue by kazydek** [kyma-project/kyma#4073]
**Description**

Create configuration documents for the **Service Mesh** component. 
These documents should list and describe configurable parameters from `values.yaml` files of these charts and their sub-charts:

- [`istio-init`](https://github.com/kyma-project/kyma/tree/master/resources/istio-init)
- [`istio-kyma-patch`](https://github.com/kyma-project/kyma/tree/master/resources/istio-kyma-patch)
- [`istio`](https://github.com/kyma-project/kyma/tree/master/resources/istio)

>**NOTE:** Every chart and sub-chart should be described in a separate document.

Make sure you:
- Create the documents based on the existing [template](https://github.com/kyma-project/community/blob/master/guidelines/templates/resources/configuration.md).
- Rely on the already created configuration documents for the [Asset Store](https://kyma-project.io/docs/master/components/asset-store/#configuration-configuration).

**Reasons**

Have a set of configuration documents that describe values from the Service Mesh `values.yaml` files you can override.

**Attachments**
It relates to the epic #4028.

**Comment by kazydek** [comment]
All Istio charts should not be configured. We are responsible for the configuration of Istio we deliver so if any value gets changes, the configuration may be changed to the point where the component stops working and it would be difficult to detect the case of this problem.

Goats are planning to prepare the tool for checking compatibility with the Istio the customers bring.

What's more, Goats are planning to remove the `istio-kyma-patch` chart in the release 1.3 - it was used for overriding configuration of out Istio delivered with Kyma. After removing it, any changes that will be made to Istio configuration will be included directly in the Istio charts.

**Comment by derberg** [comment]
I understand we do not want user to modify anything, shouldn't we then provide a doc with clear information that we provide a given istion configuration and we do not recommend to make any changes, etc?

Because now in each component we will have config docs and in service mesh not. So I don't have a strong opinion on that, just have doubts and checking what you think about it

**Comment by kazydek** [comment]
As discussed, I added a general note to the configuration docs where I mentioned that you can only override values exposed in the separate configuration documents, meaning that you cannot configure values that are not documented - that's would cover the doubts :)
