### ISSUE TITLE
Create configuration documents for Tracing

### ISSUE THREAD

**Issue by kazydek** [kyma-project/kyma#4077]
**Description**

Create a configuration document for the **Tracing** component. 
This document should list and describe configurable parameters from the `values.yaml` file of this chart:

- [`jaeger`](https://github.com/kyma-project/kyma/tree/master/resources/jaeger)

Make sure you:
- Create the document based on the existing [template](https://github.com/kyma-project/community/blob/master/guidelines/templates/resources/configuration.md).
- Rely on the already created configuration documents for the [Asset Store](https://kyma-project.io/docs/master/components/asset-store/#configuration-configuration).

**Reasons**

Have a configuration document that describes which values from the Tracing `values.yaml` file you can override.

**Attachments**
It relates to the epic #4028.

**Comment by a-thaler** [comment]
Typical configuration options are:
- jaeger.memory.maxTraces: "40000" to limit the amount of traces to store, old ones will be evicted
- resources.limits.memory: "512M" to limit the storage size. In case the average size of a trace is bigger than usual the maxTraces might be too big for the storage and the pod might crash. Then you need to increase the memory limits.
