### ISSUE TITLE
Create configuration documents for Logging

### ISSUE THREAD

**Issue by kazydek** [kyma-project/kyma#4078]
**Description**

Create configuration documents for the **Logging** component. 
These documents should list and describe configurable parameters from `values.yaml` files of these charts and their sub-charts:

- [`logging`](https://github.com/kyma-project/kyma/tree/master/resources/logging)

>**NOTE:** Every chart and sub-chart should be described in a separate document.

Make sure you:
- Create the documents based on the existing [template](https://github.com/kyma-project/community/blob/master/guidelines/templates/resources/configuration.md).
- Rely on the already created configuration documents for the [Asset Store](https://kyma-project.io/docs/master/components/asset-store/#configuration-configuration).

**Reasons**

Have a set of configuration documents that describe values from the Logging `values.yaml` files you can override.

**Attachments**
It relates to the epic #4028.

**Comment by a-thaler** [comment]
The current configuration is all about the persistence for the log chunks and index data. That is explained a bit in existing documentation: https://kyma-project.io/docs/master/components/logging/#details-storage-configuration
Unfortunately, that docu is not based on installer configuration and should be transformed.

By default the configuration is using boltDB and filesystem, both based on a PersitentVolumeClaim, the volume can be enabled and configured by
  persistence:
    enabled: true
    accessModes:
      - ReadWriteOnce
    size: 10Gi
    storageClassName: ""
Usually here you would tweak the size attribute.

If you want to change the persistence to GCS for example, you would disable "persistence.enabled: false" and set these options:
  config:
    schema_config:
      configs:
      - from: 0
        store: gcs
        object_store: gsc
        schema: v9
        index:
          prefix: index_
          period: 168h
  config:
    storage_config:
      gcs:
        bucket_name: <YOUR_GCS_BUCKETNAME>
        project: <BIG_TABLE_PROJECT_ID>
        instance: <BIG_TABLE_INSTANCE_ID>
        grpc_client_config: <YOUR_CLIENT_SETTINGS>

@hisarbalik can help you to double-check the settings

I realized that in the current docu it says "storage_configs" where it should be "storage_config"

**Comment by kazydek** [comment]
Contacted @hisarbalik and I am waiting for the input to the doc.
