### ISSUE TITLE
Create configuration document for Kyma

### ISSUE THREAD

**Issue by kazydek** [kyma-project/kyma#4081]
**Description**

Create configuration documents for Kyma. 
These documents should list and describe configurable parameters from `values.yaml` files of these charts and their sub-charts:

- [`testing`](https://github.com/kyma-project/kyma/tree/master/resources/testing)
- [`xip-patch`](https://github.com/kyma-project/kyma/tree/master/resources/xip-patch)

>**NOTE:** Every chart and sub-chart should be described in a separate document.

Make sure you:
- Create the documents based on the existing [template](https://github.com/kyma-project/community/blob/master/guidelines/templates/resources/configuration.md).
- Rely on the already created configuration documents for the [Asset Store](https://kyma-project.io/docs/master/components/asset-store/#configuration-configuration).

**Reasons**

Have a set of configuration documents that describe values from the Kyma general `values.yaml` files you can override.

**Attachments**
It relates to the epic #4028.

**Comment by mmitoraj** [comment]
- NO configurable parameters in [`testing`](https://github.com/kyma-project/kyma/tree/master/resources/testing) - discussed and confirmed with both @PK85 and @aszecowka 
- [`xip-patch`](https://github.com/kyma-project/kyma/tree/master/resources/xip-patch)
