### ISSUE TITLE
Binding is left over after deleting ServiceInstance

### ISSUE THREAD

**Issue by brendandobbs** [kyma-project/kyma#4089]
**Description**

I deleted a ServiceInstance (named service-api-instance) I had already before a demo so I could show the process of provisioning and binding the service during the demo. Provisioning the new ServiceInstance failed with the following error :

`Provision call failed: Forbidden provisioning instance [096f3959-7577-11e9-a8cf-625c719c150d] for application [name: sap-field-service-management, id: 2b969440-0445-4fcc-b181-7e2cc82e37ec] in namespace: [demo]. Reason: [already activated]`

kubectl shows that there is only the new instance (service-api-e803b-creamy-teach)

kubectl get ServiceInstances

| NAME                            |                              CLASS                                     |               PLAN   |   STATUS   | AGE|
|--------|--------|----------|---------|----------|
| gcp-service-broker-inborn-tune              |                  ClusterServiceClass/gcp-service-broker      |             default |  Ready  |  1d|
| sap-field-service-management-events-a0831-plaintive-average  |  ServiceClass/sap-field-service-management-events-a0831  | default  | Ready   |  1d|
| service-api-e803b-creamy-teach          |                      ServiceClass/service-api-e803b |                           default  |  Failed  | 1d|

There are no ServiceBindingUsages

`kubectl get ServiceBindingUsages
No resources found.`

svcat shows only the new instance

svcat get instances

|                        NAME         |                      NAMESPACE      |   CLASS     |      PLAN    |  STATUS  |
|--------|-------|---------|--------|----------|
|  gcp-service-broker-inborn-tune        |                        demo   |    gcp-service-broker  | default  | Ready|   
|  sap-field-service-management-events-a0831-plaintive-average |  demo |   |   |Ready   |
|  service-api-e803b-creamy-teach      |                          demo                |       |     |                Failed|

svcat shows that there are 2 bindings for the old service instance (service-api-instance)

svcat get bindings

|     NAME   |   NAMESPACE     |    INSTANCE    |     STATUS  |
|------|-------|---------|---------|
|  wbcxwdhhis  | demo    |    service-api-instance |  Ready   |
|  xgmwlbvere  | demo     |   service-api-instance  | Ready  |

**Expected result**

ServiceInstance should be provisioned after deleting a previously created instance of the same service class.

**Actual result**

Provisioning fails.

.

**Comment by PK85** [comment]
Hello @brendandobbs 
question, have you deleted SI finalizer, then SI itself. It could cause exactly that issue.

**Comment by brendandobbs** [comment]
Thanks @PK85 , probably I did forget to delete the SI before the finalizer. As we no longer have the original error that prevented the provisioning and it's not easy to reproduce it, we can close this.
