### ISSUE TITLE
Prepare a concept for kind of getting started / learning materials for Kyma

### ISSUE THREAD

**Issue by derberg** [kyma-project/kyma#4095]
**Description**

That are many aspects we need to first take into account and not postpone for later to have good quality from the beginning.

1. Come up with a place where we want to have the guides and what will be the visual representation
2. Come up with a name and decide if we want to have different levels of difficulty. It would be nice maybe to continue known naming introduced by [Kelsey Hightower](https://github.com/kelseyhightower/kubernetes-the-hard-way), so `Kyma the easy way` and `Kyma the hard way`. We can also copy from https://developers.sap.com/tutorial-navigator.html?tag=tutorial:type/mission the idea of Missions-Groups-Tutorials. Or best would be to have a tree with branches, the flow is based on waves concept, that you can take different paths with a ship, easy way and hard way.
3. Come up with a framework to build such guides, is it just like it is now, you first need to get Kyma on your own or maybe we should use [Katacoda](https://www.katacoda.com) like k8s https://kubernetes.io/docs/tutorials/hello-minikube/ and example source https://github.com/katacoda-scenarios/kubernetes-scenarios/blob/master/helm-package-manager/step1.md
4. How do we test those guides to make sure they always work with the latest version and also during any maintenance development. We need this from the very beginning as later there will never be enough time to update missing tests and maintenance will be a hell
5. Very important to have a clear decision on what would be our high-level scenario, what would be a high-level use case that we would base on. In other words, Kyma is mainly about the extensibility of external application, and this will be the initial starting point, you first need to connect something and know how to do that too later start extending Kyma. Maybe we could provide official Slack or GitHub connectors into Kyma and base the whole guides flow on the extensibility of one of those applications. These would make training clear to most people that know these apps and for sure have in mind ideas how they could extend them.

**Reasons**

- There is no single path for Kyma community to go through and learn Kyma. There are different bits and pieces in different locations but we need to have one frame to organize that.

**Comment by abbi-gaurav** [comment]
We could also refer 
* https://istio.io/docs/tasks/traffic-management/
* https://github.com/knative/docs/tree/master/docs/serving/samples

**Comment by jcawley5** [comment]
Looking into if we can get some usage statistics for the sap tutorial navigator.  Either way I think there should be a sap focused area, blogs or tutorial nav content, to include the cockpit and suite connectivity.

**Comment by derberg** [comment]
Maybe the tutorials/guides for each step should be consumable through the catalog as we want for examples https://github.com/kyma-project/kyma/issues/2832 or maybe official examples should be merged with the new guides approach?

**Comment by derberg** [comment]
@jcawley5 we need to remember that official Kyma guides cannot be SAP specific as Kyma is donated to any kind of community. This is why I do not want to base them on SAP specific scenario/application extensibility, and instead on GitHub/Slack to attract a wider audience. 

Kyma specific thing related to SAP offering should rather go to SAP owned domains as they are specific for SAP only, so developers.sap.com for example

**Comment by jcawley5** [comment]
Yes of course, just thinking what ways we can serve both channels at the same time.

**Comment by kazydek** [comment]
1. Document sources for the Getting Started guides in Kyma can be located under the `docs` folder. Their names will include the group number they belong to and the tutorial number which the doc should have in a given group. For example, you will have `G1-T1-install-kyma.md`. The guides will be rendered in a separate view on the Kyma website. See their visual representation below:
![GettingStartedGuides](https://user-images.githubusercontent.com/40655785/60252533-ac1e6680-98ca-11e9-87fb-f34b1293855a.png)

See the tutorial descriptions in the attached spreadsheet:
[Getting Started - Kyma.xlsx](https://github.com/kyma-project/kyma/files/3333775/Getting.Started.-.Kyma.xlsx)

2. At this point, we do not plan to provide different levels of difficulty for particular tutorials but that can change in the future. We are introducing the idea of Missions-Groups-Tutorials where you embark on the full Kyma journey (mission) that explains all main Kyma features and functionalities. You finish it by completing all tutorials that are segregated into groups, depending on the topic they concern. Apart from that, you should be also able to complete every tutorial (or a set of them) separately, downloading the required configuration package beforehand. 
3. Let’s use [Katacoda](https://kubernetes.io/docs/tutorials/hello-minikube/) like in k8s. See an example source [here](https://github.com/katacoda-scenarios/kubernetes-scenarios/blob/master/helm-package-manager/step1.md).

**Comment by derberg** [comment]
Katacoda rocks!:
- You can use it for free, at least the website doesn't say anything about pricing. We can have org account and provide scripts as kyma like kubernetes -> https://katacoda.com/kubernetes.
- creation of tutorials is simplified because of CLI https://www.katacoda.com/cli
- It supports a lot of different environments, so we can even have an environment that is a Minikube on which we could install Kyma -> https://katacoda.com/docs/scenarios/environments
- installation of kyma will be lengthy but we simply need to improve it, linkerd is also starting with installation https://www.katacoda.com/mhausenblas/scenarios/linkerd2
- Multiple layouts are supported, https://katacoda.com/docs/scenarios/layouts
  - we could even display console UI in an iframe if needed. Good example is this jenkins tutorial where you can even access jenkins UI https://katacoda.com/courses/jenkins/build-docker-images
  - we could even have a file editor like in this example https://katacoda.com/courses/docker/create-nginx-static-web-server
- docs are a bit outdated and not fully up to date. I could not find an official jsonschema for the index.json that will be hard to have nice scenario validation on a PR level

Kyma example:
- source https://github.com/derberg/kyma-on-katacoda
- play with it https://katacoda.com/derberg

**CURRENT BLOCKER**:
Kyma requires minimum 8GB memory allocated for Minikube, Katacoda environment has only 2GB

**Comment by derberg** [comment]
Regarding the consistent story behind a set of learning materials. We will have a team working on connectors of known applications like github, twitter, zenhub and slack (2 of those for sure) and they will enable use to provide widely understood scenarios that will make explaining Kyma much easier. Code will be here https://github.com/kyma-incubator/hack-showcase

**Comment by derberg** [comment]
For now, the initial concept is defined and I'm in contact with Katacoda's founder to check out if technical limits we encountered are "fixable"

**Comment by abbi-gaurav** [comment]
A thought for the deep dive flow. We could also provide the option for a developer to specify a running Kyma cluster. This subsequent steps will then run against the pointed cluster. This has the additional benefit of having logging, tracing and monitoring also available to the developer.

**Comment by derberg** [comment]
@abbi-gaurav awesome idea, environment for tutorial has kubectl, so user can pass his kubeconfig for his cluster, we just need to have nice instructions for him/her

**Comment by michal-hudy** [comment]
Together with @kazydek we discussed it a little bit. During the discussion, we decided that the `examples` repository will be replaced with tutorials. There will be a separate section with tutorials on https://kyma-project.io page with basic and advanced content. Basic tutorials we will also try to put on https://katacoda.com, but firstly, we need to verify if Kyma Lite works on such a platform.

**Comment by michal-hudy** [comment]
Unfortunately, Kyma is still too heavy to run on Katacoda. The biggest Katacoda environment has ~2,5GB memory, where the lightest Kyma (without UI) that I was able to run had ~3GB. The 2,5GB memory in Katacoda is a memory assigned to a machine, so cluster (e.g. Minikube) will have only ~2 that need to be shared between the control plane and Kyma. So Kyma should use at max ~1GB as we need also a space for a workload (for example functions, services, etc.).

**Comment by BenHall** [comment]
@michal-hudy Thank you for investigating Katacoda. On our free platform we do limit the memory usage. However, we have options available for those w ith additional resource requirements. When we previously discussed (https://github.com/kyma-project/kyma/issues/4095#issuecomment-508366977) we increased the memory and it worked as expected.  If you could drop me an email (ben@katacoda) then I can go into more details.

**Comment by kazydek** [comment]
**Getting Started** will follow the current doc structure and use the existing examples, mocks, and templates. They will show the steps both in  **UI** and **kubectl**.

---
type: Getting Started
---

Tutorials:

1. Overview explaining the whole flow and what you achieve by completing the full set of GS docs (a microservice with an external database that is accessible on an external endpoint and receives events from an external mock application).
2. Deploy a sample `http-db-service` microservice.

> For this we will correct, modify, and extract tutorials for deploying a service [locally](https://kyma-project.io/docs/#tutorials-sample-service-deployment-on-local) and on a [cluster](https://kyma-project.io/docs/#tutorials-sample-service-deployment-on-a-cluster). We will make one guide out of those two.

3. Expose the service through an `APIRule` (unsecured endpoint, `GET` and `POST` methods) and show that both methods work. After testing the `POST` method and sending a sample order, delete the Service Pod. After Pod restarts, show that the order details are gone proving that the service uses an in-memory database.

> Link to API Gateway [tutorials](https://kyma-project.io/docs/components/api-gateway/#tutorials-expose-and-secure-a-service) which describe how you can secure the exposed service. 

4. Provision the Redis service through an Addon (`micro` plan) - an alternative, external database that we will use to store data from the Pods.
5. Create an instance of the Redis service.
6. Bind the instance to `http-db-service` and show that it uses the new database now and data are not lost upon Pod restart. 
7. Deploy SAP Marketing Cloud - mock that will send events to our service.
8. Set an Event Trigger for `http-db-service` and prove that the Service receives them.

For this to work, the [`http-sb-service`](https://github.com/kyma-project/examples/blob/master/http-db-service/README.md) will need to be rewritten - it now has an in-memory database that can be only changed to an external MSSQL instance. We need to change it to work with Redis instead. It would also need to work with events from the SAP Marketing Cloud - Mock.  @hudymi will modify this example.

## Follow up tasks:
- Add the new Getting Started doc type to the optional doc types in the [content strategy](https://kyma-project.io/community/guidelines/content/#content-strategy-content-strategy-optional).
- Possibly adjust the Serverless [tutorial](https://kyma-project.io/docs/components/serverless/#tutorials-bind-a-service-instance-to-a-function) showing the use of the Redis database in Functions - it now only shows that you can retrieve The credentials to the Redis service but does not how we could actually use this database for Functions. 
- We use a mock app and Addons functionality here. Perhaps we could reuse somehow our existing [Application Connector tutorials](https://kyma-project.io/docs/components/application-connector/#tutorials-create-a-new-application) in the GS docs as well in the future.

**Comment by kazydek** [comment]
In the end, we decided that the [Getting started guides](https://kyma-project.io/docs/master/root/getting-started/) will be based on a new [`orders-service`](https://github.com/kyma-project/examples/tree/master/orders-service) example that includes a sample microservice and Function that work with a default in-memory storage and an external Redis database. See the guides for details of the flow and other apps/samples used in them.
