### ISSUE TITLE
Only few traces are shown in Jaeger

### ISSUE THREAD

**Issue by a-thaler** [kyma-project/kyma#4103]
**Description**
The current setting of istio-pilot is defining the trace sampling rate with a 1.0 where 100 is a maximum. With that only 1 out of 100 requests will be send to jaeger for trace recording. So showing traces for simple demo setups is nearly impossible.

**Expected result**
A moderate trace rate should be send to jaeger in order to support debugging. Minimum should be prominent documentation on how to setup a demo/development cluster having a high sampling rate.

See traceSampling setting in Kyma 0.8 at https://github.com/kyma-project/kyma/blob/release-0.8/resources/istio/values.yaml where it was at 100.

**Actual result**
Only few (1 out of 100) traces get send to jaeger. See current traceSampling setting at https://github.com/kyma-project/kyma/blob/master/resources/istio/charts/pilot/values.yaml

**Steps to reproduce**
Create a lambda exposed via HTTP and call it. With a high probability, you will not find the trace in jaeger.

**Troubleshooting**
```
kubectl -n istio-system edit deploy istio-pilot
```
and set traceSampling to for example 100.0. Be aware of potential performance/instability impacts on istio when using such high number.

**Comment by jcawley5** [comment]
Can this please be tagged to be included in the documentation?

**Comment by a-thaler** [comment]
Yes, you are right, will trigger documentation of it

**Comment by a-thaler** [comment]
FYI: The setting is also part of values.yaml in kyma/resources/istio/charts/pilot chart, with that it can be configured already at installation time with overwrite: traceSampling

**Comment by bszwarc** [comment]
Done.

**Comment by a-thaler** [comment]
We still want to do some performance investigations and optimize the current setting if possible.

**Comment by derberg** [comment]
I think we need to make sure there is a clear docu that mentions this value https://github.com/kyma-project/kyma/blob/58c85663e587766791675385f2e2fc0091f08d22/resources/istio/charts/pilot/values.yaml#L12 and explains how you can override it before installation. How to do it in runtime (https://kyma-project.io/docs/master/components/tracing/#troubleshooting-basic-troubleshooting) is not enough, user would like to also know how to configure it before installation, what are the configuration parameters here, that they are available as overrides.

**Comment by derberg** [comment]
also regarding the troubleshooting document, the instruction could be much more useful. User knows he needs to edit deployment, but what variable he actually needs to change? he can only guess it is `PILOT_TRACE_SAMPLING`. why not having a one-liner that dev can copy/paste to a terminal, `kubectl set env -n istio-system deployment/istio-pilot PILOT_TRACE_SAMPLING=100` should work, but you need to doublecheck.

**Comment by a-thaler** [comment]
Having the sampling rate to such a small value is fine in my oppinion, we have a follow-up to figure out a better value for development clusters.
However, the current documentation is really bad and must be improved. I fully agree with @derberg , we need to improve the troubleshooting guide to explain it step by step (currently not even the proper key to modify is mentioned).
Furthermore we must document how to configure it as override at installation time

**Comment by bszwarc** [comment]
@a-thaler, for now there is a problem with overrides -> applying override results in an error, already reported https://github.com/kyma-project/kyma/issues/7249. 
We can still stick to changing the value by means of variable export for now and wait for the solution. Also, the approach for handling istio installation and config will change soon -> we would like to wait for that too.

**Comment by a-thaler** [comment]
Could you maybe add the old way as well, by changing the resource at runtime with the edit command? For debugging and development I prefer this as I usually have a kyma cluster ready and want to test. Only then I realize that the sampling rate must be adjusted and I don't want to do the installer way. 
For the override, there is really no simplified version available focussing on the actual value to change? Looks like the structure can change easily with next istio upgrade ..

**Comment by bszwarc** [comment]
@piotrmsc,  can you comment on that? Is it still valid to edit the `istio-pilot` deployment and change the value for the environment variable?  (as in here: https://istio.io/docs/tasks/observability/distributed-tracing/overview/#trace-sampling) 
In the previous comment, there was a line `Furthermore we must document how to configure it as override at installation time` -> so that's the override for now :) It may change of course, but I would say that is the proper way to do it for now 🤔

**Comment by a-thaler** [comment]
I think both options are valid. The override we need to provision a cluster having the setting already active. The other is to change the setting afterwards for debugging reasons.

**Comment by piotrmsc** [comment]
With new overrides via IstioControlPlane you can set this parameter only in a way @bszwarc has done it. Old overrides aka helm overrides (structure) are deprecated and will be removed and it should not be used. When it comes to `kubectl edit` ofc it can be done this way, in the end it's similar operation as both set env in the deployment. Should the `kubectl edit` be part of troubleshooting? From operations POV it can if it resolves identified issue quickly. From docu POV should we document such operations? IMO we should clearly document the configurations available for tracing, what default profiles provide and what are its limitations :)

**Comment by bszwarc** [comment]
Ok, lets put the information there - @a-thaler - I would just add the link to official Istio docs: https://istio.io/docs/tasks/observability/distributed-tracing/overview/#trace-sampling

**Comment by a-thaler** [comment]
A link will be fine
