### ISSUE TITLE
Remove unused code from the namespaces resolver in console-backend-service

### ISSUE THREAD

**Issue by dariadomagala** [kyma-project/kyma#4120]
**Description**

Using console-backend-service it is possible to query all namespaces (non-system ones) or namespaces connected to a specific application. Investigate if this query for namespaces filtered by application name is used anywhere (or is there any use case to use it in the future). If not, remove it.

**Reasons**

Currently we have a piece of code in console-backend-service that looks like it's not used anywhere, additionally it's not tested at all. If we're not planning to use it, we should remove it for code quality and testability. 

**Attachments**

Clean this file:
https://github.com/kyma-project/kyma/blob/master/components/console-backend-service/internal/domain/k8s/namespace_resolver.go

**Comment by kwiatekus** [comment]
Already done
