### ISSUE TITLE
Dispatching an event takes time(sometimes after every 2nd publish)

### ISSUE THREAD

**Issue by sayanh** [kyma-project/kyma#4125]
**Description**

It is observed that consecutive events are not sent to the subscribers. Something blocks the dispatching of events. May be after 2nd publish, 1st and 2nd events both get dispatched to the consumer.

Sample example used: https://github.com/kyma-project/examples/tree/master/event-subscription/service

Kyma version used: 1.1.0-rc2  

**Expected result**

After each publish, events should be pushed to the consumer instantaneously.

**Actual result**

Investigation needed.

**Steps to reproduce**

Use this example: https://github.com/kyma-project/examples/tree/master/event-subscription/service

**Comment by sayanh** [comment]
Probably this is due to natss database resource is taking a lot of time to get created. We are depending on the status of subscriptions.kyma-eventing.io but this status doesn't check whether natss DB resource is created or not. IMO it should check that before it is really `ready`.

**Comment by Abd4llA** [comment]
No longer happening. Symptoms disappeared (thank god :D )
