### ISSUE TITLE
Default cors policy in API Gateway

### ISSUE THREAD

**Issue by piotrmsc** [kyma-project/kyma#4127]
**Description**

Currenty API controller does not set any cors policy in created virtualservice. This blocks calls made from console to for example lambda. 
We have to set for now default cors policy with allowed origin pointing to kyma domain and allowed methods to \*. Allowed headers should have *Authorization* or \* if supported.In the future, We will make it configurable in the API cr.

Reference doc : https://istio.io/docs/reference/config/networking/v1alpha3/virtual-service/#CorsPolicy

**Reasons**
Enable call made from ui to exposed APIs

**Attachments**

**Comment by kubadz** [comment]
Istio doesn't support wildcard subdomains, it means that we are not able to allow all origins pointing to kyma domain and we would have to allow both console and all microfrontends UIs. I set it to `*` for now, but it is easy to change just by changing one entry in values file.
Istio also doesn't support `*` in methods allowed, so we have to list all methods we want.
