### ISSUE TITLE
Ability to deploy Kyma with valid certificate through GCP Marketplace

### ISSUE THREAD

**Issue by michal-hudy** [kyma-project/kyma#4132]
**Description**

When Kyma is deployed from **GCP Marketplace** it should be configurated with valid certificate instead of self-signed. Unfortunately, it is not possible to generate a valid cert for xip.io domain with Let's encrypt. We can consider a similar solution as proposed here: https://content.pivotal.io/blog/sslip-io-a-valid-ssl-certificate-for-every-ip-address

Also, it would be nice if the user will have an ability to configure his domain with a certificate.

**Reasons**

Have a better experience when Kyma is deployed from GCP Marketplace.

**Attachments**

https://content.pivotal.io/blog/sslip-io-a-valid-ssl-certificate-for-every-ip-address
https://letsencrypt.org
http://xip.io

**Comment by derberg** [comment]
moved to https://github.com/kyma-incubator/marketplaces/issues/2
