### ISSUE TITLE
Think of a way to improve the setup of testbed for performance scripts

### ISSUE THREAD

**Issue by rakesh-garimella** [kyma-project/kyma#4137]
**Description**

Currently we are using `setup.sh` for setting up all the pre-requisites(eg. Deploying lambdas etc.) before we start a test. For complex scenarios this might not be enough. We need to identify these complex scenarios and come to a consensus for the best way to improve it.

**Comment by nachtmaar** [comment]
Another idea: 
The [k6 test-lifecycle](https://docs.k6.io/docs/test-life-cycle) mentions a `setup` and `teardown` method. This way each k6 script could have independent setup and teardown. However, we need to check if we can execute shell commands to execute e.g. `kubectl`.

**Comment by pbochynski** [comment]
Please reopen if you want to continue work on it.
