### ISSUE TITLE
Identify the production grade setup for various components.

### ISSUE THREAD

**Issue by rakesh-garimella** [kyma-project/kyma#4139]
**Description**

Provide a production profile for Kyma provisioning and installation.
The **installation profile** contains overrides for Kyma components with production configuration (CPU/memory/replicas).
The **provisioning profile** contains minimal cluster configuration (node types, number of nodes) able to run the installation profile.

**Reasoning** 
Applying a production profile guarantees a decent performance, stability, and usability for standard use cases. Consider these common-sense recommendations for finding out proper settings.
- number of requests/second handled by the component - hundreds or more for end-user facing components (UI, APIs), tens or more for administrative operations (depends on operation type)
- config verified for a longer period (day/week) with no crashes / out of memory / out of disk space events for test load,
- stateful components with resilient configuration (no in-memory storage, disk storage with limits/ rolling strategies)
- useful data retention (weeks or more  for logs/metrics)

**Acceptance criteria**
- The production profile can be applied for provisioning and installation from kyma-cli
- The production profile is the default for provisioner in compass
- The documentation is provided for profile usage (and how to override it)
- Key performance indicators values for essential scenarios (number of events processed, API gateway requests per second, number of lambdas that can be deployed, number of applications/APIs registered) for the profile
- Scaling up documentation is provided - how to go beyond the numbers provided above, e.g. adding even more memory to istio-proxy can improve service mesh throughput.

**Comment by derberg** [comment]
@piotrmsc please discuss with @pbochynski

**Comment by pbochynski** [comment]
We need to verify the production profile on nightly builds.

**Comment by piotrmsc** [comment]
https://github.com/kyma-project/kyma/issues/6646 Istio
https://github.com/kyma-project/kyma/issues/6611 Ory

**Comment by a-thaler** [comment]
https://github.com/kyma-project/test-infra/issues/1998 Nightly

**Comment by a-thaler** [comment]
The official production profile got introduced and several components are contributing to it already. Now it is just a matter to provide profiles case by case, will close the eipc.
