### ISSUE TITLE
Test the Application Connector setup with Istio 1.0 deployed from Helm chart

### ISSUE THREAD

**Issue by lszymik** [kyma-project/kyma#414]
Confirm these statements before you submit the issue:

- [x] I have searched open and closed issues for duplicates.
- [x] I have read the contributing guidelines.
---

**Description**

We need to test if a client certificate validation will work with Istio 1.0 deployed from Helm Chart in Kyma cluster.

Acceptance:
- Install Istio 1.0 on an empty cluster with Helm chart.
- Check if a client certificate is working, if not - compare configuration with Istio deployed from yaml files.
- Try to verify CName with an envoy filter
- Share results with a team deploying Istio to Kyma

**Reasons**

We want to use Istio as the Application Connector gateway with client certificate validation.

**Comment by janmedrek** [comment]
It seems like any Istio installation done with Helm is not compatible with EnvoyFilters, created issue here:
https://github.com/istio/istio/issues/8616

**Comment by janmedrek** [comment]
Issue was created here: https://github.com/istio/istio/issues/8616
