### ISSUE TITLE
Application Registry should validate API and event specs

### ISSUE THREAD

**Issue by akgalwas** [kyma-project/kyma#4146]
**Description**

Application Registry should make use of Asset Store functionality to validate specifications provided by the user in the registration process. Validation errors in specifications shouldn't prevent from registering services, however, the status of verification needs to be stored so that it could reviewed by the user. 

**Reasons**

The user needs to be able to see the validation report so that they could perform appropriate fixes to the specifications.

**Comment by janmedrek** [comment]
This will be done on Rafter side, closing the issue.
