### ISSUE TITLE
Provide troubleshooting setup for the components w.r.t backup-restore tests

### ISSUE THREAD

**Issue by sayanh** [kyma-project/kyma#4157]
**Description**
Create Prow jobs for each test separately. This is a temporary workaround.

>NOTE: Having a single job for all the tests is not feasible since after the failure the job at present does not proceed. Once all tests are fixed, we should need only one job.

Provide the jobs for the following tests:
// appBrokerTest, err := NewAppBrokerTest()
	
// helmBrokerTest, err := NewHelmBrokerTest()
	
// scAddonsTest, err := NewServiceCatalogAddonsTest()
	
// myNamespaceControllerTest, err := NewNamespaceControllerTestFromEnv()
	
// apiControllerTest, err := NewApiControllerTestFromEnv()
	
// myMicroFrontendTest, err := NewMicrofrontendTest()
	
// myAssetStoreTest, err := NewAssetStoreTest(t)
	
// myCmsTest, err := NewCmsTest(t)

**AC**
- [x] Prow jobs with respective component teams are shared.
- [x] Any required troubleshooting documentation to followed is also shared.

**Comment by sayanh** [comment]
- [ ] (appbroker)https://github.com/kyma-project/kyma/issues/4274
- [ ] (appbroker)https://github.com/kyma-project/kyma/issues/4274
- [ ] (appbroker)https://github.com/kyma-project/kyma/issues/4274
- [ ] (appbroker)https://github.com/kyma-project/kyma/issues/4274

**Comment by sayanh** [comment]
**Troubleshoot guideline**
- Prow [link](http://35.246.221.4/)
- There are jobs created for each failing test(see [here](https://github.com/kyma-project/kyma/issues/4157#issuecomment-496788588) ) in back-restore test suite. E.g 
  - microfrontend test - `mft-kyma-gke-end-to-end-test-backup-restore`
  - helmbroker test - `helmbroker-kyma-gke-end-to-end-test-backup-restore`
  - appbroker test - `appbroker-kyma-gke-end-to-end-test-backup-restore`

- There is 1 PR and 1 fork involved for each test:
  - Core test related changes. E.g. for microfrontend test this [PR](https://github.com/kyma-project/kyma/pull/4271) does it.
  - Image related changes E.g. for microfrontend test this [PR](https://github.com/sayanh/kyma/tree/enable-microfrontend-test-image-bump) does it.

How can we fix a test and run it?
Make changes in test:
- Changes should be made in a PR (E.g. [this](https://github.com/kyma-project/kyma/pull/4271)) which creates the image for backup-restore test

Trigger a job:

**First approach**

- Log in to the prow cluster
```
gcloud container clusters get-credentials atx-prow2 --zone=europe-west3-a --project=kyma-project
```

- You may trigger a job in 2 ways:
  - Change cron time for that particular job in configmap `job-config` using `kubectl edit cm job-config`. Be careful to not break the indentation. Debugging can be done by getting logs from the `horologium` component. ```kubectl logs horologium-5879bb5c49-x7p46 horologium -f```

May be the **second approach** is better.

- Go to prow [ui](http://35.246.221.4/)
- Click the rerunning button for your job and copy the `kubectl create` script
- Log in to the prow cluster:
```
gcloud container clusters get-credentials atx-prow2 --zone=europe-west3-a --project=kyma-project
```
- Paste the `kubectl create` script to create the job. Before hitting return, please replace `https` with `http`

**Comment by abbi-gaurav** [comment]
Assigning it to huskies based on Sayan's comments

```
I’m done with the setup and everything other teams need… still helmbroker and appbroker tests are failing … IMO this ticket can stay open until the tests are fixed and if this moves to the next sprint then maybe @huskies can support the concerned teams ....it should be having 0 SP
```

**Comment by a-thaler** [comment]
Tests are working again
