### ISSUE TITLE
Migrate Prometheus restore process to velero plugins 

### ISSUE THREAD

**Issue by sayanh** [kyma-project/kyma#4166]
**Description**

Right now Prometheus restore process has special requirements:
- After restore process, prometheus resource needs to be recreated from the existing resource(delete Prometheus CR and create). 

This mechanism is already applied in the backuprestore test.

Ideally, this mechanism should be part of the velero-plugins.

The test should just back and restore in a stupid way.

AC:
- Move the prometheus restore logic to velero plugins.

**Reasons**

Cause it is cleaner.

**Comment by lszymik** [comment]
Hello @sayanh ,
That issue is in Automatix backlog, can you please add labels. Of course, if it does make sense.

Cheers
Lukasz
