### ISSUE TITLE
Installation on Windows fails due to not able to determine installer image

### ISSUE THREAD

**Issue by crabtree** [kyma-project/kyma#4172]
**Description**

The script `extract-kyma-installer-image.ps1` should provide installer image tag that should be used to build kyma-installer. It does this based on installer-local.yaml file. Due to recent changes in this file, it does not find the correct line.

**Comment by tomekpapiernik** [comment]
@lszymik as @crabtree assigned this to himself I think it should be part of Framefrog backlog ;)
