### ISSUE TITLE
Move velero-plugins from tools to components

### ISSUE THREAD

**Issue by sayanh** [kyma-project/kyma#4177]
**Description**

As mentioned [here](https://github.com/kyma-project/kyma/issues/2502) and [here](https://github.com/kyma-project/kyma/pull/3783#issuecomment-494543833), it is imperative to move the velero-plugins to components rather than keeping in tools.

**Reasons**

Better structuring and align with [this](https://github.com/kyma-project/kyma/issues/2502)

**Comment by suleymanakbas91** [comment]
As there are not used anymore, we can even delete them.
