### ISSUE TITLE
Subscription properties max_inflight and push_request_timeout_ms are not applied post Knative eventing migration

### ISSUE THREAD

**Issue by abbi-gaurav** [kyma-project/kyma#4180]
**Description**
As a developer, I expect available configuration for delivery behavior (Kyma Subscription) is applied.

Post migrating to Knative eventing, the functionality and behavior to dispatch the events to serverless are controlled by the Knative eventing internals.

The two fields `max_inflight` and `push_request_timeout_ms` were added when Kyma eventing was having its own dispatch mechanism. At present, they are not in sync with the Knative eventing semantics.

[2019-06-11]
Decided with the team to remove the configuration. The configuration first will be done at the Knative level and then bring it to Kyma eventing.

>NOTE: Contact Hasselhoff to update the lambda UI.

**AC**
- [x] `max_inflight` and `push_request_timeout_ms` are removed from the Kyma Subscription
- [x] Kyma Subscription should still work in a backward compatible manner.
- [x] Add required fields constraint for the mandatory fields

**Comment by marcobebway** [comment]
Verified all PRs on a cluster using the E2E [test](https://github.com/kyma-incubator/examples/tree/master/kyma-local-e2e-scenario).

![trace-list](https://user-images.githubusercontent.com/24314423/60348643-4ca28280-99c0-11e9-9338-deb9894f8565.png)
![trace-details](https://user-images.githubusercontent.com/24314423/60348652-52986380-99c0-11e9-939f-db1641b26a11.png)
