### ISSUE TITLE
Remove unused apps from event-bus

### ISSUE THREAD

**Issue by sayanh** [kyma-project/kyma#4185]
Following apps are obsolete now:
https://github.com/kyma-project/kyma/blob/master/components/event-bus/Makefile#L46
https://github.com/kyma-project/kyma/blob/master/components/event-bus/Makefile#L48
https://github.com/kyma-project/kyma/blob/master/components/event-bus/Makefile#L44

**Comment by Abd4llA** [comment]
Already solved
