### ISSUE TITLE
Add app label for lambdas created via UI

### ISSUE THREAD

**Issue by a-thaler** [kyma-project/kyma#4194]
**Description**
See https://github.com/kyma-project/kyma/issues/3953 for the motivation.
When creating a lambda via UI the app label should be added to the list of labels automatically. It should be transparent to the user and still removable.

**Reasons**
Many kubernetes tooling is based on the label and to have them work as expected it should be used always.

**Comment by tricky42** [comment]
Can we please check that this gets its way into the next release?
