### ISSUE TITLE
Cleanup installation documentation

### ISSUE THREAD

**Issue by Tomasz-Smelcerz-SAP** [kyma-project/kyma#4208]
**Description**
Current version of installation documentation (simplified) still labels installation CR and contains commands with old overrides.
This is because at the time when the documents were modified, latest Kyma release - 1.1.0 - still required such steps.
Now, for the next release, Kyma sources contain all necessary improvements, so this additional steps are no longer required.
We can further cleanup the documentation.

**Acceptance Criteria:**
Cleanup cluster installation documents:
- remove explicit labeling of Installation CR
- remove override for `cluster-users.users.adminGroup`
- remove override for `global.logging.promtail.config.name` - if possible

After these changes section 6. of the file **04-03-cluster-installation.md** - **6. Install custom installation overrides for GKE** - should be empty, and we can remove it.

**Comment by tomekpapiernik** [comment]
invalid
