### ISSUE TITLE
User configuration of Velero

### ISSUE THREAD

**Issue by sayanh** [kyma-project/kyma#4212]
**Description**

It is clear that [simplifying installation process](https://github.com/kyma-project/kyma/issues/3932) will enable user to create the override configmaps or secrets based on the need. This applies for velero-secrets(installation/resources/velero-secret.yaml.tpl) as well. We need to figure out how an user installing Kyma using Faros or by himself using CLI will be configuring Velero secrets.

Tasks to do:
- Remove `sed`as part of https://github.com/kyma-project/test-infra/blob/master/prow/scripts/cluster-integration/kyma-gke-end-to-end-test.sh#L201 and create the secret with `installer=overrides` label for installer to use while installing `velero` chart.

- Add relevant document  

**Reasons**

See #4118

**Comment by sayanh** [comment]
This is not valid as the user configurations are already documented [here](https://kyma-project.io/docs/components/backup/).

**Comment by clebs** [comment]
Closing this issue, configuration of velero is already properly documented in Kyma's official documentation.
