### ISSUE TITLE
Monitoring for promtail

### ISSUE THREAD

**Issue by clebs** [kyma-project/kyma#4214]
As a followup issue for #1795, we want to add custom metrics monitoring and visualization for promtail.
AC:
- Promtail metrics are scraped by prometheus
- Metrics are visible in the Logging grafana dashboard.

**Comment by suleymanakbas91** [comment]
Not needed anymore as promtail will be deleted anyway, right? @a-thaler

**Comment by suleymanakbas91** [comment]
Promtail has been removed by https://github.com/kyma-project/kyma/pull/6808.
