### ISSUE TITLE
Investigate Load Test Findings: Function Queueing

### ISSUE THREAD

**Issue by nachtmaar** [kyma-project/kyma#4226]
**Description**

While working on #4156 we figured out that there are pending function calls even after the k6 load-test is finished.
We need to investigate what is happening here and discuss if this is expected behaviour.
- 

**Expected result**
After k6 load-test is finished, no lambdas are called anymore. There are no new Get requests in the log of the function pod.

**Actual result**

Even after k6 load test is finished, get requests can be seen in the function pod:

```
::ffff:127.0.0.1 - - [27/May/2019:08:55:51 +0000] "GET / HTTP/1.1" 200 - "-" "k6/0.24.0 (https://k6.io/)"
```

**Steps to reproduce**

See this link for [An introduction on Kyma performance testing](https://github.com/kyma-project/kyma/blob/master/tests/perf)

Use the following k6 config:

```bash
export let options = {
    ...
    { duration: "240s", target: 2 ** 10 },
  ],
```

```bash
# setup resources
./prerequisites/serverless/setup.sh
# trigger load test
k6 run --out influxdb=http://localhost:8086/myk6db components/serverless/perf-test-serverless.js
# check log that new get requests are still printed
kubectl -n serverless logs -f pod/size-s-7f8f88cc99-grbt7 size-s
```

**Troubleshooting**

**Comment by joek** [comment]
This behaviour is expected. K6 is not proper draining left over calls after he finishes the test run. The function is still solving the old requests which are opened during the test run.

Due to the nature of nodejs, we have to investigate how certain actions inside a function are influencing the load behaviour.
