### ISSUE TITLE
Improve document about adding bundles to helm broker through configmap

### ISSUE THREAD

**Issue by derberg** [kyma-project/kyma#4234]
**Description**

- add missing title
- either make https://github.com/kyma-project/kyma/blob/master/docs/helm-broker/03-03-create-bundles-repo.md a tutorial or make https://github.com/kyma-project/kyma/blob/master/docs/helm-broker/08-01-configure-hb.md a normal details doc. Now it looks strange that the only tutorial for HB starts with user already having bundles repo
- point about creating configmap shows 2 ways of doing it, if it is really that important I suggest using tabs here
- point about kyma installation is unnecessary, move it to prerequisites or remove it entirely as configmap configuration will work in any environment

**Expected result**

Straightforward instruction about configuration

**Actual result**

missing title, some unnecessary steps

**Steps to reproduce**

Document https://github.com/kyma-project/kyma/blob/master/docs/helm-broker/08-01-configure-hb.md has no title and displays wrong.

**Comment by klaudiagrz** [comment]
This issue is going to be fixed in [this](#4620 ) PR.

**Comment by klaudiagrz** [comment]
Now we implement the CRDs feature instead of ConfigMaps and so the tutorial document was also completely changed. As suggested, I converted it into the details document.
