### ISSUE TITLE
Request fails (403) when CSRF token expires

### ISSUE THREAD

**Issue by brendandobbs** [kyma-project/kyma#4238]
**Description**

When the CSRF token expires (calling an OData endpoint) we see a 403 exception in the logs for the Lambda function

`Function failed to execute: StatusCodeError: 403 - "CSRF token validation failed"
    at new StatusCodeError (/kubeless/node_modules/request-promise-core/lib/errors.js:32:15)
    at Request.plumbing.callback (/kubeless/node_modules/request-promise-core/lib/plumbing.js:104:33)
    at Request.RP$callback [as _callback] (/kubeless/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at Request.self.callback (/kubeless/node_modules/request/request.js:185:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (/kubeless/node_modules/request/request.js:1161:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (/kubeless/node_modules/request/request.js:1083:12)`

The app gateway appears shows the follow (suggests that the token is being refreshed)...

`time="2019-05-28T06:17:53Z" level=info msg="Modified request url : 'https://my300011.s4hana.ondemand.com/sap/opu/odata/sap/API_MKT_CONTACT_SRV/MarketingPermissions?$filter=PermissionUUID%20eq%20guid%27FA163E0B-249B-1EE9-9EDC-9FC51FCF79AD%27&$top=1', schema : 'https', path : '/sap/opu/odata/sap/API_MKT_CONTACT_SRV/MarketingPermissions'"
time="2019-05-28T06:17:53Z" level=info msg="Request from service with id 5c9d5f96-1e0e-4ac4-8f52-b4e85ae121ed failed with 403 status, invalidating proxy and retrying."
time="2019-05-28T06:17:53Z" level=info msg="Invalidating token for endpoint: https://my300011.s4hana.ondemand.com/sap/opu/odata/sap/API_MKT_CONTACT_SRV;v=0002"
time="2019-05-28T06:17:53Z" level=info msg="CSRF Token not found in cache, fetching (Endpoint: https://my300011.s4hana.ondemand.com/sap/opu/odata/sap/API_MKT_CONTACT_SRV;v=0002)"
` 
The next time we call the OData endpoint the call is successful so the token is in fact refreshed.

**Expected result**

The CSRF token refresh should be handled transparently.

**Actual result**

Error when the token expires.

**Comment by lszymik** [comment]
Kindly please review that issue and decide what we can do to get it done. Please check with other teams which were involved in development. Maybe it is already a known issue or they have some hints about how to check and fix it quickly.

**Comment by franpog859** [comment]
Hey, @brendandobbs ! Could you provide us more information about the request? What kind of authenticate method did you use? How is the service API configured? Could you also provide us some environment where we can see this case? The tests covering this scenario with BasicAuth and CSRF token are added to the suite in [this PR](https://github.com/kyma-project/kyma/pull/4546). Everything looks fine there and I couldn't reproduce the bug

**Comment by brendandobbs** [comment]
Hi @franpog859, I was calling a Marketing Cloud API using Basic Auth. The cluster I was using has since been deprovisioned. I'll setup the scenario again and leave it running for a couple of days to see if I can reproduce it.

**Comment by brendandobbs** [comment]
Hi @franpog859 , I sent you the details of the cluster on slack where you can see the logs for the error.

Thanks,
Brendan

**Comment by franpog859** [comment]
Hey, @brendandobbs ! After the consultation we decided to close this issue
I added the acceptance test covering the scenario with BasicAuth and CSRF token [here](https://github.com/kyma-project/kyma/pull/4546). We also checked the Application Gateway in your environment and it seems to work as expected (it uses new CSRF token on the retry)
To minimize the impact of other resources please, provide us a minimal environment with only CSRF server and simple resources reproducing your scenario. If the bug still occures, reopen this issue

**Comment by Szymongib** [comment]
We have found some issues with CSRF related Cookies which might have caused the problem. The fix was merged #4948 and it will take effect after merging #4546.

@brendandobbs, if you will have a chance, please verify if it fixed the issue and let us know.
