### ISSUE TITLE
Connector service API should be rendered in kyma-project.io

### ISSUE THREAD

**Issue by pbochynski** [kyma-project/kyma#4239]
**Description**
The connector API is available to download:
https://kyma-project.io/assets/docs/1.1/application-connector/docs/assets/connectorapi.yaml
But should be rendered in the documentation (in the cluster and on kyma-project.io)

**Reasons**
We render external APIs specificartions in service catalog. We should be able to render our own API spec.

**Comment by magicmatatjahu** [comment]
@pbochynski We (core-and-supporting team) have a plan to show `yaml` and `json` files in modal, so please wait to one month (max) for implementation.

**Comment by pbochynski** [comment]
It depends on how big the modal is and how you fit the content into it. From my experience API specs tend to be long and wide, and I don't want to scroll in both directions. I would like to have an option to open it in the new tab/window.

**Comment by derberg** [comment]
- remember about guidelines for internal content providers
  - how to add OpenAPI for given docstopic to make sure it is rendered inside kyma-project
  - content strategy - API type (like https://kyma-project.io/docs/components/application-connector/#api-api) - clarify (probably to be removed)

**Comment by derberg** [comment]
published https://kyma-project.io/docs/master/components/application-connector/specifications/connectorapi/
