### ISSUE TITLE
Run compass components as a part of Kyma

### ISSUE THREAD

**Issue by PK85** [kyma-project/kyma#4242]
**AC**
- investigate and select proper namespace for installation
- compass as a part of Kyma:
  - Compass and Runtime in one Kyma cluster
  - Compass is an expertimental module, by default not activated (commented out in installer-config yaml)
- add documentation into Kyma project (investigate if we can already use compass repo as a source)
  - describe what module is about
  - point by links to the kyma-incubator/compass docs
- provide script to run Kyma (from master as well) with compass enabled (we need to use compass chart from Kyma)

**Comment by pkosiec** [comment]
> add documentation into Kyma project (investigate if we can already use compass repo as a source)
describe what module is about
> point by links to the kyma-incubator/compass docs

As discussed with @derberg, we will paste the paragraph https://github.com/pkosiec/compass/tree/rework-install-script#kyma-installation-with-compass-module-enabled to release notes. For now we won't create any docs in Kyma docs.
