### ISSUE TITLE
Document application-connector installation overrides

### ISSUE THREAD

**Issue by Tomasz-Smelcerz-SAP** [kyma-project/kyma#4245]
**application-connector** installation overrides used in our existing Kyma installation procedures must be documented.

The documentation should be added to the **application connector** component configuration documentation.

**Acceptance Criteria:**
Add documentation for the following overrides:
- global.applicationConnectorCa
- global.applicationConnectorCaKey

See also:
- #4244

**Comment by pbochynski** [comment]
It is implemented.
Docu: https://kyma-project.io/docs/components/application-connector/#configuration-application-connectivity-certs-setup-job
