### ISSUE TITLE
Use the term "Upgrade" instead of "Update"

### ISSUE THREAD

**Issue by ormos** [kyma-project/kyma#4248]
**Description**

Please use the term "Upgrade" instead of "Update" for the process of switching to a new release of Kyma

**Reasons**

In the Linux and K8S community, the term "Upgrade" is used when switching to a more recent release of a software/system/platform.  That should be done in the documentation but also in the UI and CLI related areas.

**Attachments**

https://kyma-project.io/docs/root/kyma/#installation-update-kyma

**Comment by Demonsthere** [comment]
There already exists a task for unifying the upgrade documentation in all kyma. Duplicate.

**Comment by piotrmsc** [comment]
https://github.com/kyma-project/kyma/issues/4281
