### ISSUE TITLE
Consistent keyboard handling for all modal UI dialogs

### ISSUE THREAD

**Issue by ormos** [kyma-project/kyma#4249]
**Description**

The behavior of different Kyma console dialogs varies when using the keyboard. Some modal dialog windows can be closed via < ESC > or accepted via < RETURN > on others dialogs this is not working. 
Also the initial input focus is not always set correctly to the first natural input field. Or in other cases, the switching via < TAB > is not working correctly.

**AC**

< ESC > - should always close a modal dialog with CANCEL action 
< RETURN > - should always close a modal dialog with OK/ACCEPT action
Initial input focus should be set to the first natural input field.
The < TAB > key should move the input focus to the next enabled input field
< SPACE > should trigger the button if having the current input focus

**Comment by kwiatekus** [comment]
Dependant on https://github.com/SAP/luigi/issues/577

**Comment by kwiatekus** [comment]
Related issues : 
https://github.com/kyma-project/console/issues/1023
https://github.com/kyma-project/console/issues/1035
https://github.com/kyma-project/console/issues/1034

**Comment by kwiatekus** [comment]
We treat those guidelines as acceptance criteria for all new changes in the UI.
And therefore, we plan to introduce those usability improvements gradually with every new/changed ui component.
