### ISSUE TITLE
Document monitoring installation overrides

### ISSUE THREAD

**Issue by Tomasz-Smelcerz-SAP** [kyma-project/kyma#4253]
**monitoring** installation overrides used in our existing Kyma installation procedures must be documented.

The documentation should be added to the **monitoring** component configuration documentation.

**Acceptance Criteria:**
Add documentation for the following overrides:
- global.alertTools.credentials.slack.apiurl
- global.alertTools.credentials.slack.channel
- global.alertTools.credentials.victorOps.routingkey
- global.alertTools.credentials.victorOps.apikey

See also:
- #4244

**Comment by a-thaler** [comment]
Fixed in https://github.com/kyma-project/kyma/issues/4080
