### ISSUE TITLE
Document Istio installation overrides

### ISSUE THREAD

**Issue by Tomasz-Smelcerz-SAP** [kyma-project/kyma#4254]
**Istio** Installation overrides used in our existing Kyma installation procedures must be documented.

The documentation should be added to the **Istio** component configuration documentation.

**Acceptance Criteria:**
Add documentation for the following overrides:
- global.loadBalancerIP
- gateways.istio-ingressgateway.loadBalancerIP
- global.proxy.excludeIPRanges

See also:
- #4244

**Comment by piotrmsc** [comment]
We will not document istio, as we do not want to let users modify our istio. We will document what we modify in comparison to pure istio in #4230
