### ISSUE TITLE
WebSocket support in API Gateway

### ISSUE THREAD

**Issue by piotrmsc** [kyma-project/kyma#4275]
**Description**

Users are also creating APIs that allows communication over websocket. API gateway should support that as well and console UI should allow to set it in the API view.

API CR should be extended with "websocketUpgrade" property with value "true/false".
Documentation for API controller and API Gateway should cover this change as well.
Additionally, we should think of some example for that.

**Reasons**

Enable WebSocket APIs in the kyma

**Attachments**

**Comment by Tomasz-Smelcerz-SAP** [comment]
Support for websockets is enabled by default in Istio from version 1.0: https://godoc.org/istio.io/api/networking/v1alpha3#HTTPRoute

I have verified it for both HTTP (ws) and HTTPS (wss) protocols in Kyma 1.2, web sockets are working out-of-the-box.
