### ISSUE TITLE
Document Kyma Upgrade 

### ISSUE THREAD

**Issue by piotrmsc** [kyma-project/kyma#4281]
**Description**
We have described how to [update](https://kyma-project.io/docs/root/kyma/#installation-update-kyma) kyma pretty well, however, we do not document how to upgrade kyma and how to upgrade from for example version  0.9 to 1.2.

Sometimes we have migration guides in releases for operations that cannot be automated between releases and are described in github release notes, users should be aware of that (currently it is not described). 

You cannot upgrade directly from 0.9 to 1.2, you have to follow "step by step" upgrade (0.9 -> 1.0 -> 1.1 -> 1.2) which should be described.

Additionally, we can mention the difference between update and upgrade and add a toggle in update docu between "local deployment" and "cluster deployment"

Criteria:

- New document created with type installation
- Difference between update and upgrade in terms of kyma described
- Upgrade procedure is described including upgrade between patch and minor or even major (step by step flow)
- Mention no direct downgrade but point to  backup and restore

**Reasons**

Users do not know how to perform upgrade in the kyma.

**Attachments**

**Comment by derberg** [comment]
We also miss information like:
- what upgrade really means, what is upgraded, 
  - what happens with my resources created using kyma features
  - what happens with my resources created using kubernetes features (what if kubernetes version requires a bump)
  - are we assuring migration of CRs from one version to another
  - are we assuring upgrade is seamless and all components are available all the time during upgrade
- what technically happens in the installer, there is not clear and direct docs that explains that installer is a dummy helm charts operator that installs all components provided as helm charts one by one, and that the same happens in upgrade mode, that at the end it is helm install and helm upgrade but we have installer to make installation easier. There is just a doc like this one https://kyma-project.io/docs/root/kyma/#details-charts-manage-dependencies-with-init-containers but it is really old as it still refers to some old decision record from Kyma beginnings
- how are we assuring upgrade works well between versions
