### ISSUE TITLE
Acceptance tests can be run in parallel with others

### ISSUE THREAD

**Issue by sjanota** [kyma-project/kyma#4285]
**Description**

It should be possible to run acceptance tests in parallel with other Kyma tests. We need to verify if it is possible now and change the test if necessary. Then its TestDefinition should be modified to enable concurrency.

**Reasons**

One way to make the Kyma test suite faster is to run tests in parallel. 

**Acceptance Criteria**
- [ ] concurrency is enabled in acceptance test and it is stable on CI

**Comment by PK85** [comment]
Timeboxed to 5 SP

**Comment by jasiu001** [comment]
**Existing tests**

| Pass with `core` test | TestDefinitions | disableConcurrency | comments |
| --- | --- | --- | --- |
| true | knative-serving | false | although the test has concurrency enabled running itself failed |
| true | application-connector | true | |
| true | application-operator | true | |
| true | connection-token-handler | true | |
| true | assetstore | true | |
| true | **core** | **false** * | |
| true | core-api-controller | false |  |
| true | core-apiserver-proxy | false | |
| true | core-cluster-users | false | |
| true | core-console | true | the test has a temporary error not connected with `core` test |
| true | core-console-backend-service | true | |
| true | core-kubeless | false | |
| true | core-test-external-solution | false | although the test has concurrency enabled running itself failed |
| true | dex-connection | false | |
| true | dex-integration | false | |
| true | event-bus | false | |

_* changed in upcoming PR_

The **Core** test was run concurrently with all tests regardless of whether the default is enabled or not. None of the tests affects the behavior of `core` and `core` does not affect any other test hence the test can be run concurrently.
