### ISSUE TITLE
apiserver-proxy tests can be run in parallel with others

### ISSUE THREAD

**Issue by sjanota** [kyma-project/kyma#4287]
**Description**

It should be possible to run apiserver-proxy tests in parallel with other Kyma tests. We need to verify if it is possible now and change the test if necessary. Then its TestDefinition should be modified to enable concurrency.

**Reasons**

One way to make the Kyma test suite faster is to run tests in parallel. 

**Acceptance Criteria**
- [ ] concurrency is enabled in apiserver-proxy test and it is stable on CI

**Comment by Demonsthere** [comment]
Implemented by #4847
