### ISSUE TITLE
console-backend-service tests can be run in parallel with others

### ISSUE THREAD

**Issue by sjanota** [kyma-project/kyma#4296]
**Description**

It should be possible to run console-backend-service tests in parallel with other Kyma tests. We need to verify if it is possible now and change the test if necessary. Then its TestDefinition should be modified to enable concurrency.

**Reasons**

One way to make the Kyma test suite faster is to run tests in parallel. 

**Acceptance Criteria**
- [ ] concurrency is enabled in console-backend-service test and it is stable on CI

**Comment by kwiatekus** [comment]
We tried it. it failed. Its big effort but low gain
