### ISSUE TITLE
event-bus tests can be run in parallel with others

### ISSUE THREAD

**Issue by sjanota** [kyma-project/kyma#4297]
**Description**

It should be possible to run event-bus tests in parallel with other Kyma tests. We need to verify if it is possible now and change the test if necessary. Then its TestDefinition should be modified to enable concurrency.

**Reasons**

One way to make the Kyma test suite faster is to run tests in parallel. 

**Acceptance Criteria**
- [ ] concurrency is enabled in event-bus test and it is stable on CI

**Comment by sayanh** [comment]
[Integration](https://status.build.kyma-project.io/view/gcs/kyma-prow-logs/pr-logs/pull/kyma-project_kyma/4923/pre-master-kyma-gke-integration/1152287108103147520) and [upgrade](https://status.build.kyma-project.io/view/gcs/kyma-prow-logs/pr-logs/pull/kyma-project_kyma/4923/pre-master-kyma-gke-upgrade/1152177764313337856) jobs are working fine after parallelizing the tests. But there is a dependency on this [PR](https://github.com/kyma-project/kyma/pull/4893) and it is better to continue on this after it is merged.
