### ISSUE TITLE
gateway tests can be run in parallel with others

### ISSUE THREAD

**Issue by sjanota** [kyma-project/kyma#4298]
**Description**

It should be possible to run gateway tests in parallel with other Kyma tests. We need to verify if it is possible now and change the test if necessary. Then its TestDefinition should be modified to enable concurrency.

**Reasons**

One way to make the Kyma test suite faster is to run tests in parallel. 

**Acceptance Criteria**
- [ ] concurrency is enabled in gateway test and it is stable on CI

**Comment by k15r** [comment]
The event-service (previously known as gateway) tests are not executed on their own. They are only executed as part of the application-operator tests. So as long as the application-operator tests can be executed concurrently we have this ticket covered.
