### ISSUE TITLE
namespace-controller tests can be run in parallel with others

### ISSUE THREAD

**Issue by sjanota** [kyma-project/kyma#4303]
**Description**

It should be possible to run namespace-controller tests in parallel with other Kyma tests. We need to verify if it is possible now and change the test if necessary. Then its TestDefinition should be modified to enable concurrency.

**Reasons**

One way to make the Kyma test suite faster is to run tests in parallel. 

**Acceptance Criteria**
- [ ] concurrency is enabled in namespace-controller test and it is stable on CI

**Comment by piotrmsc** [comment]
Namespace controller will be removed from kyma, currently, it is deleted from components, including tests https://github.com/kyma-project/kyma/pull/4383
