### ISSUE TITLE
Document etcdBackup installation overrides

### ISSUE THREAD

**Issue by Tomasz-Smelcerz-SAP** [kyma-project/kyma#4308]
**etcdBackup** installation overrides used in our existing Kyma installation procedures must be documented.

The documentation should be added to the relevant component configuration documentation.

**Acceptance Criteria:**
Add documentation for the following overrides:
- global.etcdBackup.containerName
- global.etcdBackup.enabled

See also:
- #4244

**Comment by PK85** [comment]
We need to remove that documentation, as we use velero now.

**Comment by mszostok** [comment]
As agreed, this documentation is not needed anymore and all stuff connected with the backup will be removed in that issue: https://github.com/kyma-project/kyma/issues/4313
