### ISSUE TITLE
Support deploying resources to Kyma via URL

### ISSUE THREAD

**Issue by abbi-gaurav** [kyma-project/kyma#4309]
**Description**
At present, it is possible to deploy K8S resources by browsing a file. It would be nice to deploy the resources via a URL.

**Comment by kwiatekus** [comment]
I didn't find a dedicated k8s API endpoint to create a resource from file.
So it looks like we would need to download the file to the js client (optionally, load the content to the json editor) and follow our current approach.

**Comment by sjanota** [comment]
I believe it's also how `kubectl` is doing it.

**Comment by kwiatekus** [comment]
Its a nice feature, Agree. However not a priority.
Users can always run `kubectl apply -f` via CLI
