### ISSUE TITLE
Service Binding on knative Functions

### ISSUE THREAD

**Issue by joek** [kyma-project/kyma#4316]
**Description**

Add a list of service bindings and binding parameters to the knative function crd. Create ServiceBinding and ServiceBindingUsage based on the list.

**Reasons**

As a function developer I like to consume Services. They should be part of the CRD as the binding might need some extra work, when the function is deployed outside of kyma on a 3rd party system

**Comment by michal-hudy** [comment]
It will be implemented under this issue that covers also UI and has more details: #7017
