### ISSUE TITLE
Triggers in Knative Funciton Controller

### ISSUE THREAD

**Issue by joek** [kyma-project/kyma#4317]
**Description**
Add a attribute for generic triggers into the function CRD and extend the controller to create the related objects for events and api.

**Reasons**

As a function developer I like to trigger my functions based on events and http requests. Maybe other trigger types will be added later like cron jobs. The solution should be as flexible to wire up triggers in a 3rd party solution too.

**Comment by michal-hudy** [comment]
Triggers will not be implemented as a Function Controller functionality. It is separated CRD and the user will explicitly create it and manage it.
