### ISSUE TITLE
Spike - Acquire and share knowledge for the event consumption flow.

### ISSUE THREAD

**Issue by abbi-gaurav** [kyma-project/kyma#4319]
**Description**
To improve team expertise on the eventing topic, this will be the first of the series of tasks to understand the flow. This will target the event consumption flow.

Some of the questions (but not limited) we need to answer:
- What all configurations need to be done? What does it mean technically or behind the scenes?
- How events are dispatched?
- How various controllers involved interact? How their reconcile loops behave?
- How failures and scenarios such as pods restarting are handled?
- How various custom resources involved go through various lifecycle stages?
- How the custom resources reach eventual consistency?

**AC**
- [ ] A deep dive technical documentation of the event consumption flow.
- [ ] A organized session with the team to share the knowledge
- [ ] Identify any gaps or issues while acquiring knowledge and add to the backlog.

**Comment by Abd4llA** [comment]
Will be looked after using a different approach.
