### ISSUE TITLE
Integrate Knative Serving and Tekton

### ISSUE THREAD

**Issue by joek** [kyma-project/kyma#4324]
**Description**

We need to integrate knative serving and build into examples, testing and installation.

**Reasons**

Kyma is based on knative ;-)

**Task**

- Make build a module
- Add / review tests for kantive build and serving
- Add / review knative documentation
- Create examples for serving and build
- Backup / Upgradebility Tests
- Add a comment on top of the documentation, that the feature is experimental

**Comment by michal-hudy** [comment]
It is already implemented
