### ISSUE TITLE
Define the guidelines to write controllers in Kyma

### ISSUE THREAD

**Issue by mszostok** [kyma-project/kyma#4327]
**Description**

To be able to define guidelines for Kyma developers to write controllers, we need to get an understanding and comparison between various approaches that are being adopted by different Kyma teams.

Some teams are using Kubebuilder since it removes a lot of boilerplate and does a lot of code generation.

Others consider using the runtime-controller as a better alternative based on their Knative experience.

Some of the criteria (but not limited) to use for comparison

* Stability of the project
* Backward compatibility
* Ease of development (more than one controller in the same project)
* Dependency on tools
* Ease of writing tests
* Stability of tests
* Ease of tweaking (logger levels etc.)
* How the workflow looks like if the CRD is not in the same project?
* Ease of incremental changes
* QoS
  * Graceful shutdown

In Kyma we have also components which have a dual function, e.g. components are both the ServiceBroker and Controller. We need to document how to deal with such cases.

**AC**
- [ ] There is a detailed comparison between different approaches using various aspects defined above. 
- [ ] We have a final agreement which approach should be used
- [ ] We have a decision if only the new controller should be written in a chosen approach or the old one should be rewritten

**Comment by lilitgh** [comment]
Discussion is moved to public github https://github.com/kyma-project/kyma/issues/4327

**Comment by suleymanakbas91** [comment]
Some more options to think of: https://twitter.com/alexellisuk/status/1132755044313522176?s=20

**Comment by antoineco** [comment]
Don't close!

**Comment by antoineco** [comment]
> Some teams are using Kubebuilder [...] Others consider using the runtime-controller as a better alternative based on their Knative experience.

2 comments regarding this (besides the typo "runtime-controller" -> "controller-runtime"):
- Knative abandoned controller-runtime in favour of their [own utils](https://github.com/knative/pkg/tree/master/controller) for writing controllers. They wanted to remain closer to client-go's building blocks if I'm not mistaken, c.f. the reference [sample-controller](https://github.com/kubernetes/sample-controller) repo).
- Kubebuilder is mostly a toolkit that scaffolds code for CRs and controllers. The generated code doesn't use any kubebuilder specific code, but rather controller-runtime's libraries. Interestingly, RedHat's Operator SDK also converged towards controller-runtime.

Somebody wrote a comparison between `controller-runtime` (part of kubebuilder) and Knative's helpers about a week ago: 
📝 [controller-runtime VS knative/pkg for operator](https://medium.com/@vincenthou/kubernetes-operator-journey-ep4-controller-runtime-vs-knative-pkg-for-operator-b71468b23a37)

**Comment by mszostok** [comment]
Few cents from my side:
- https://docs.google.com/document/d/1iHzO4mcZNA-1XaMj3XUPwcqZ0UefIG7AdY9buLd9Hi0/edit#heading=h.iq6li8qnzwa8

-

**Comment by mszostok** [comment]
Few cents from my side:
- Probably the future of the Operator SDK will be changed, check this doc: https://docs.google.com/document/d/1iHzO4mcZNA-1XaMj3XUPwcqZ0UefIG7AdY9buLd9Hi0/edit#heading=h.iq6li8qnzwa8
- the operator SDK and kubebuilder uses under the hood the [controller runtime](https://github.com/kubernetes-sigs/controller-runtime) and [controller tools](https://github.com/kubernetes-sigs/controller-tools) libs

so... because the future of the operator SDK is quite undefined IMO is really risky to go with it.
What's more, IMO going with kubebuilder or Operator SDK is too much opinionated. Also they sometimes changing the architecture significantly. Check the diff between kubebuilder v1 and kubebuilder v2. Such thing, causing a lot of problems with upgrading to a newer version (@michal-hudy  can probably confirm that it was quite hard and also new layout do not fit well to our use-cases and best practices). Additionally using the new features is always postponed e.g. kubebuilder is always behind the controller-runtime features.

### Kubebuiler:

  **pros:**
  - creates a boilerplate and scaffold the package structure
  - it's not a copy-paste pattern, you bootstrapping it with CLI with given args

  **cons:**
  - it's opinionated and sometimes layout does not fit well to our use-cases and best practices
  - the, check the version v1 and v2.
  - kubebuilder is always behind the controller-runtime features.


  **Sum:**
    It will be good if we plan to have several controllers components, so it will be easy to generate and always have the same structure. But it's always a risk because we depend on their architecture.

### Operator SDK:
- just wait for its future, IMO right now it's not a way to go.


### Reuse Knative:
- IMO it will be quite problematic because we will need to agree with all their changes because it is their own component. Additionally, adding our own customization will be quite hard.

### Doing own skeleton and reusing the [controller runtime](https://github.com/kubernetes-sigs/controller-runtime) and [controller tools](https://github.com/kubernetes-sigs/controller-tools)

  **pros:**
  - we are always up to date to new features
  - we do not need to take care of low-level implementation
  - we have enough freedom to create our own layout which will fit to our use-cases and best practices 

  **cons:**
  - we need to write our own skeleton for boostraping the controller-manager and maintain it
  - we need to know the underhood libs (controller-runtimes and controller-tools)

**Sum:**

This solution gives us quite a lot of freedom where we close enough to the k8s but far enough to do not cause additional problems. Dealing with low-level error handling, timeouts, retries, etc.
The controller libs sit under the kubernetes-sigs repo and are maintained by the guys from the sig-api-machiner (same guys who also owns the main api-server), so it's a quite safe option to invest our time.

_opinions are my own_
