### ISSUE TITLE
List uninstallation leftovers

### ISSUE THREAD

**Issue by piotrmsc** [kyma-project/kyma#4340]
**Description**

Collect all resources (CRDs, Deployments etc) that needs to be manually deleted after triggering kyma uninstallation, done here: https://github.com/kyma-project/kyma/issues/2942.

Documentation should list those resources. Based on the list, respectively follow-ups will be created 
to find out if it can be deleted by fixing chart or it has to be manually deleted.

For sure crds from knative and istio are not deleted, as well as namespaces are left untached.
I've attached a list with all crds that left left on a minikube (on cluster env can be more crds related to monitoring,tracing, logging etc).

Right now trying to install kyma again fails with presence of crds, for example
`  - component: knative-serving
    log: 'Helm install error: rpc error: code = Unknown desc = customresourcedefinitions.apiextensions.k8s.io
      "clusteringresses.networking.internal.knative.dev" already exists'`

--

**Reasons**
Find out what needs to be manually deleted after uninstalling kyma using installer.

**Attachments**

[leftover-crds.txt](https://github.com/kyma-project/kyma/files/3247295/leftover-crds.txt)

**Comment by jakkab** [comment]
Deleting all CRDs (except `installation.installer.kyma-project.io`) and all custom Namespaces (again, excluding `kyma-installer`) seems to do the trick in local scenarios.

**Comment by jakkab** [comment]
It is possible to reinstall Kyma on cluster, too. I've encounter a couple of issues, though:
- jeager kcproxy container init fails;
- some tests won't pass.
Further investigation required.

**Comment by jakkab** [comment]
For xip.io domain: deleting the configmaps with the domain from previous installation (net-global-overrides and application-connector-overrides) solves the issue. Our patches (xip, certhelper) don't update existing configmaps, so the domain remains unchanged, which caused the problem.

**Comment by jakkab** [comment]
Full list of resources to delete before reinstallation: 
[resources_to_delete.txt](https://github.com/kyma-project/kyma/files/3338970/resources_to_delete.txt)
