### ISSUE TITLE
Can't install kyma to local minikube on macOS

### ISSUE THREAD

**Issue by ChristineTham** [kyma-project/kyma#4347]
When I try to install kyma (master branch) on minikube using macOS the installation terminates with error message.

$ ./cmd/run.sh --vm-driver vmwarefusion --password ****

################################################################################
# Minikube setup with driver vmwarefusion
################################################################################

Your minikube is in 1.0.1. Your version is newer than the supported version of minikube (v0.33.0)
Your kubectl version is v1.14.1. Supported versions of kubectl are from 1.11.* to 1.13.*
Minikube is already initialized
Do you want to remove previous minikube cluster [y/N]: y
🔥  Deleting "minikube" from vmwarefusion ...
💔  The "minikube" cluster has been deleted.
😄  minikube v1.0.1 on darwin (amd64)
🤹  Downloading Kubernetes v1.12.5 images in the background ...
⚠️  The vmwarefusion driver is deprecated and support for it will be removed in a future release.
				Please consider switching to the new vmware unified driver, which is intended to replace the vmwarefusion driver.
				See https://github.com/kubernetes/minikube/blob/master/docs/drivers.md#vmware-unified-driver for more information.
				To disable this message, run [minikube config set WantShowDriverDeprecationNotification false]
🔥  Creating vmwarefusion VM (CPUs=4, Memory=8192MB, Disk=30000MB) ...
📶  "minikube" IP address is 172.16.0.213
🐳  Configuring Docker as the container runtime ...
🐳  Version of container runtime is 18.06.3-ce
⌛  Waiting for image downloads to complete ...
✨  Preparing Kubernetes environment ...
    ▪ apiserver.authorization-mode=RBAC
    ▪ apiserver.cors-allowed-origins=http://*
    ▪ apiserver.enable-admission-plugins=DefaultStorageClass,LimitRanger,MutatingAdmissionWebhook,NamespaceExists,NamespaceLifecycle,ResourceQuota,ServiceAccount,ValidatingAdmissionWebhook
🚜  Pulling images required by Kubernetes v1.12.5 ...
🚀  Launching Kubernetes v1.12.5 using kubeadm ... 
⌛  Waiting for pods: apiserver proxy etcd scheduler controller dns
🔑  Configuring cluster permissions ...
🤔  Verifying component health .....
💗  kubectl is now configured to use "minikube"
🏄  Done! Thank you for using minikube!
Waiting for minikube to be up...
Keep calm, there are 15 possibilities and so far it is attempt number 1
Minikube is up
✅  metrics-server was successfully enabled
Minikube IP address: 172.16.0.213
Adding apiserver.kyma.local console.kyma.local catalog.kyma.local instances.kyma.local brokers.kyma.local dex.kyma.local docs.kyma.local add-ons.kyma.local lambdas-ui.kyma.local console-backend.kyma.local minio.kyma.local jaeger.kyma.local grafana.kyma.local log-ui.kyma.local loki.kyma.local configurations-generator.kyma.local gateway.kyma.local connector-service.kyma.local oauth2.kyma.local oauth2-admin.kyma.local oauth2-login-consent.kyma.local oathkeeper-proxy.kyma.local oathkeeper-api-server.kyma.local kiali.kyma.local to /etc/hosts on Minikube
127.0.0.1 apiserver.kyma.local console.kyma.local catalog.kyma.local instances.kyma.local brokers.kyma.local dex.kyma.local docs.kyma.local add-ons.kyma.local lambdas-ui.kyma.local console-backend.kyma.local minio.kyma.local jaeger.kyma.local grafana.kyma.local log-ui.kyma.local loki.kyma.local configurations-generator.kyma.local gateway.kyma.local connector-service.kyma.local oauth2.kyma.local oauth2-admin.kyma.local oauth2-login-consent.kyma.local oathkeeper-proxy.kyma.local oathkeeper-api-server.kyma.local kiali.kyma.local
Password:
Adding apiserver.kyma.local console.kyma.local catalog.kyma.local instances.kyma.local brokers.kyma.local dex.kyma.local docs.kyma.local add-ons.kyma.local lambdas-ui.kyma.local console-backend.kyma.local minio.kyma.local jaeger.kyma.local grafana.kyma.local log-ui.kyma.local loki.kyma.local configurations-generator.kyma.local gateway.kyma.local connector-service.kyma.local oauth2.kyma.local oauth2-admin.kyma.local oauth2-login-consent.kyma.local oathkeeper-proxy.kyma.local oathkeeper-api-server.kyma.local kiali.kyma.local to /etc/hosts on localhost
Domain added to /etc/hosts
fs.inotify.max_user_instances = 524288
fs.inotify.max_user_instances is increased
clusterrolebinding.rbac.authorization.k8s.io/default-sa-cluster-admin created

################################################################################
# Kyma-Installer build
################################################################################

~/github/kyma ~/github/kyma/installation
Sending build context to Docker daemon  3.735MB
Step 1/5 : ARG INSTALLER_VERSION="0fdc80dd"
Step 2/5 : ARG INSTALLER_DIR=eu.gcr.io/kyma-project/develop
Step 3/5 : FROM $INSTALLER_DIR/installer:$INSTALLER_VERSION
0fdc80dd: Pulling from kyma-project/develop/installer
c87736221ed0: Pull complete 
c21e27b31eb8: Pull complete 
e88f29256805: Pull complete 
fc38b7d0810f: Pull complete 
Digest: sha256:a0a6b443885e3d80e62a64a8cc3d35bd2fe908e069a3c43ba062e4c5a3983d0d
Status: Downloaded newer image for eu.gcr.io/kyma-project/develop/installer:0fdc80dd
 ---> 91a4c907816f
Step 4/5 : LABEL source="git@github.com:kyma-project/kyma.git"
 ---> Running in da96fe89bef2
Removing intermediate container da96fe89bef2
 ---> 954750b7fedf
Step 5/5 : COPY /resources /kyma/injected/resources
 ---> 6c1cd091c0ed
Successfully built 6c1cd091c0ed
Successfully tagged eu.gcr.io/kyma-project/develop/kyma-installer:63f27f76
~/github/kyma/installation

################################################################################
# Kyma Installer setup
################################################################################

clusterrolebinding.rbac.authorization.k8s.io/default-sa-cluster-admin unchanged
kube-dns is deployed...
coredns-576cbf47c7-598x4 is running...
coredns-576cbf47c7-9qjcn is running...
kubedns endpoint IP assigned
- Installing Tiller...
serviceaccount/tiller created
clusterrolebinding.rbac.authorization.k8s.io/tiller-cluster-admin created
deployment.extensions/tiller-deploy created
service/tiller-deploy created
serviceaccount/tiller-certs-sa created
rolebinding.rbac.authorization.k8s.io/tiller-certs created
role.rbac.authorization.k8s.io/tiller-certs-installer created
job.batch/tiller-certs-job created
tiller is deployed...
tiller-deploy-84b8bd8c54-crrfr is not running -  waiting 5s... MountVolume.SetUp failed for volume "tiller-certs" : secret "tiller-secret" not found
tiller-deploy-84b8bd8c54-crrfr is not running -  waiting 5s... MountVolume.SetUp failed for volume "tiller-certs" : secret "tiller-secret" not found
tiller-deploy-84b8bd8c54-crrfr is not running -  waiting 5s... MountVolume.SetUp failed for volume "tiller-certs" : secret "tiller-secret" not found
tiller-deploy-84b8bd8c54-crrfr is not running -  waiting 5s... MountVolume.SetUp failed for volume "tiller-certs" : secret "tiller-secret" not found
tiller-deploy-84b8bd8c54-crrfr is not running -  waiting 5s... pulling image "eu.gcr.io/kyma-project/alpine-net:0.2.74"
tiller-deploy-84b8bd8c54-crrfr is not running -  waiting 5s... pulling image "gcr.io/kubernetes-helm/tiller:v2.10.0"
tiller-deploy-84b8bd8c54-crrfr is not running -  waiting 5s... pulling image "gcr.io/kubernetes-helm/tiller:v2.10.0"
tiller-deploy-84b8bd8c54-crrfr is not running -  waiting 5s... Started container
tiller-deploy-84b8bd8c54-crrfr is running...

Creating installation combo yaml

Configuring sub-components

Starting installation!
namespace/kyma-installer created
limitrange/kyma-default created
customresourcedefinition.apiextensions.k8s.io/installations.installer.kyma-project.io created
customresourcedefinition.apiextensions.k8s.io/releases.release.kyma-project.io created
serviceaccount/helm-certs-job-sa created
rolebinding.rbac.authorization.k8s.io/helm-certs-rolebinding created
rolebinding.rbac.authorization.k8s.io/helm-certs-rolebinding created
role.rbac.authorization.k8s.io/helm-certs-getter created
role.rbac.authorization.k8s.io/helm-certs-setter created
job.batch/helm-certs-job created
serviceaccount/kyma-installer created
deployment.extensions/kyma-installer created
clusterrole.rbac.authorization.k8s.io/kyma-installer-reader created
clusterrolebinding.rbac.authorization.k8s.io/kyma-installer created
secret/application-connector-certificate-overrides created
configmap/cluster-certificate-overrides created
configmap/installation-config-overrides created
configmap/istio-overrides created
configmap/service-catalog-overrides created
configmap/helm-broker-overrides created
configmap/knative-serving-overrides created
configmap/assetstore-overrides created
configmap/core-overrides created
configmap/application-connector-overrides created
configmap/intallation-logging-overrides created
error: unable to recognize "STDIN": no matches for kind "Installation" in version "installer.kyma-project.io/v1alpha1"

Refer to above console log.
minikube 1.0.1
kubectl 1.14.1
kyma master (post 1.1.0)
browser n/a
OS macOS 10.14.5

**Expected result**

Successful installation

**Actual result**

Terminated installation

error: unable to recognize "STDIN": no matches for kind "Installation" in version "installer.kyma-project.io/v1alpha1"

**Steps to reproduce**

**Troubleshooting**

$ cd installation
$ sudo security add-trusted-cert -d -r trustRoot -k /Library/Keychains/System.keychain certs/workspace/raw/server.crt
$  ./cmd/run.sh --vm-driver vmwarefusion --password ****

**Comment by dariusz-smolarek-enginiety** [comment]
Hi, @ChristineTham. It looks like you have invalid versions of minikube and kubectl installed:
```
Your minikube is in 1.0.1. Your version is newer than the supported version of minikube (v0.33.0)
Your kubectl version is v1.14.1. Supported versions of kubectl are from 1.11.* to 1.13.*
```

I also had this issue and downgrading to proper versions solved installation problems

**Comment by tomekpapiernik** [comment]
@ChristineTham The supported VM driver for MacOS is [Hyperkit](https://github.com/kubernetes/minikube/blob/master/docs/drivers.md#hyperkit-driver). It's listed as one of installation prerequisites in our documentation. Please switch your driver first. Newer Minikube version shouldn't be a problem (I'm using 0.35 myself), similar to kubectl.

**Comment by ChristineTham** [comment]
Thank you @dariusz-smolarek-enginiety and @tomekpapiernik. I can't find a version of Minikube 0.33 to download and for various reasons don't want to install Hyperkit. I will try installing Kyma on a cloud cluster and see if I have better success. I did try installing 1.0.0 on Google Cloud but ran into some issues because I didn't register a domain name.

**Comment by piotrmsc** [comment]
Please reopen if you have problems with cluster setup :)
