### ISSUE TITLE
Application connector URL can not be loaded in console

### ISSUE THREAD

**Issue by p4p4** [kyma-project/kyma#4359]
**Description**
Kyma version 1.1
K8s cluster: in Azure Cloud

After a fresh installation of Kyma I created an Application and tried to connect it. When clicking "Connect Application" I got an error `GraphQL error: internal error` instead of the URL to connect the application:
![Selection_801](https://user-images.githubusercontent.com/1523187/58808124-ab6f1900-8619-11e9-9523-07ea89ee3349.png)

The issue was resolved by deleting the following pod:
`core-console-backend-service`

 
**Expected result**

URL to connect should be shown
![Selection_805](https://user-images.githubusercontent.com/1523187/58809028-7237a880-861b-11e9-8e83-9f3d9be6b32f.png)

**Actual result**

 `GraphQL error: internal error`

**Steps to reproduce**
1. install Kyma 1.1
2. create application
3. wait till it is "Serving"
4. click "connect application" 

**Troubleshooting**

delete pod `core-console-backend-service`

**Comment by kwiatekus** [comment]
Cannot reproduce on the latest kyma 1.4 version.
