### ISSUE TITLE
Performance test lambda function size L and XL

### ISSUE THREAD

**Issue by nachtmaar** [kyma-project/kyma#4368]
**Description**
- 

At the moment only lambda function size S and M are tested in the performance tests.
The performance cluster does not have enough resources to run all minimum replicas of all lambdas deployed at the same time.

This is a follow up issue of #4198 #4156

**Reasons**
The current lambda performance test does not cover all function sizes. To get a more realistic picture on lambda performance, we need to test function size L and XL too.

**Attachments**

[Script deploying the functions](https://github.com/kyma-project/kyma/blob/master/tests/perf/prerequisites/serverless/setup.sh#L23)

**How to Solve**
From my point of view, we can do 2 things: 
- Either increase resources in performance-cluster to have all lambda deployed simultaneously 
- or deploy only one function at a time

**Comment by michal-hudy** [comment]
Hm.... lambdas performance is really related to the lambda source code, not the architecture.
