### ISSUE TITLE
Enrich details view of the classes

### ISSUE THREAD

**Issue by derberg** [kyma-project/kyma#437]
Confirm these statements before you submit the issue:

- [x] I have searched open and closed issues for duplicates.
- [x] I have read the contributing guidelines.
---

**Description**

- display tags related to the class, but without making them clickable at the moment
- in General Information display `metadata.longDescription` description as main info and fallback to `description` to support all [OSBA attributes](https://github.com/openservicebrokerapi/servicebroker/blob/master/profile.md#service-metadata)
- update OSBA contract docs with changes in display
- update redis class from helm broker to contain longDescription

**Reasons**

- To give user overview of tags related to the class once he opens it
- To be as much compliant with OSBA as possible. We have cases with longDescription provided

**Attachments**

tags style
![screen shot 2018-09-04 at 08 52 54](https://user-images.githubusercontent.com/6995927/45014769-f541b900-b01f-11e8-8c18-9037ca8c053e.png)

**Comment by magicmatatjahu** [comment]
PR:
https://github.com/kyma-project/kyma/pull/460
https://github.com/kyma-project/console/pull/82

Reviewers: @mjasinski5 @akucharska @michal-hudy
