### ISSUE TITLE
Increase resources for pod executing k6 performance tests

### ISSUE THREAD

**Issue by nachtmaar** [kyma-project/kyma#4370]
**Description**

We should increase the resources for the pod running the k6 scripts. When defining too many [virtual users in k6](https://docs.k6.io/docs/running-k6) the k6 process get's killed.
The problem appears when defining a lot of virtual users in this [k6 script](https://github.com/kyma-project/kyma/blob/master/tests/perf/components/serverless/perf-test-serverless.js#L19).

**Reasons**

When doing load testing one wants to figure out the maximum throughput/performance. This is only possible if the executing load-tester is not limited in terms of resources such as CPU and RAM. We have a whole k8s cluster on GCP for load testing. We should allow to use nearly all of the cluster resources.

**Attachments**

**Comment by adamwalach** [comment]
Performance environment is no longer in use
