### ISSUE TITLE
Add non-blocking lambda performance test

### ISSUE THREAD

**Issue by nachtmaar** [kyma-project/kyma#4371]
**Description**
Add a non-blocking lambda performance test.

**Reasons**
We have [a performance test](https://github.com/kyma-project/kyma/blob/master/tests/perf/prerequisites/serverless/function-size-s.yaml#L27) which blocks the CPU for a specified amount of time to produce heavy CPU load such that the autoscaler kicks in and creates more replicas for the function.
There should be another test case, there the nodejs server performance can be evaluated
in terms of how many concurrent functions can be handled.

**Attachments**

**Implementation Ideas**

Use futures inside the lambda function to have many concurrent function calls.

**Comment by michal-hudy** [comment]
Hm.... lambdas performance is really related to the lambda source code, not the architecture.
