### ISSUE TITLE
Remove istio kyma patch

### ISSUE THREAD

**Issue by piotrmsc** [kyma-project/kyma#4380]
**Description**
As we cannot patch all variants of installed istio, we want to get rid of istio kyma patch and move applied patches to chart values directly.

The goal is remove istio kyma-patch from kyma and test-infra repository. 
This should be done after #4252 

Should be moved to charts directly. This includes :

- [ ] Removed from components
- [ ] Removed from resources

- [ ] Prow jobs updated

- [ ] Documentation does not mention istio kyma patch
- [ ] Checks done in istio kyma patch converted to TestDefinition
- [ ] Remove helm releases during upgrade

**Reasons**

Patching existing istio instance with custom config is risky and we cannot ensure it will always work as expected and will not break existing setup in someone's cluster with already running applications.

**Attachments**

**Comment by Demonsthere** [comment]
Will be updated after move to Istio Operator mode of installation
