### ISSUE TITLE
Provide a v2 API to publish events that conforms to CloudEvents specification

### ISSUE THREAD

**Issue by abbi-gaurav** [kyma-project/kyma#4389]
### Description

* An application can send events to Kyma that conform to Cloud Events specification.
* A developer can implement a microservice and generate internal events in Kyma that conform to Cloud Events specification.

As requested by Ralf, we should follow v0.3 specification.

> NOTE:

* Provide support for batch-based API if SDK supports batching else use a single event structured mode.

**AC**

- [x] There is a v2 API to send events from external and internal that conforms to cloud event specification.
- [x] It is possible to use a cloud event sdk to send events to Kyma. This is demonstrated by an example added to kyma-project/examples repository.
- [x] The current API version should still work for external and internal events

**Comment by Abd4llA** [comment]
@montaro do we need documentation here? also how do the charts change currently? i.e how do we have the new version enabled by default?
