### ISSUE TITLE
The Service Catalog is switched to new CRD implementation

### ISSUE THREAD

**Issue by mszostok** [kyma-project/kyma#4391]
**Description**

Some time ago we create the PR with CRDs to upstream Service Catalog repo. 
PR: https://github.com/kubernetes-sigs/service-catalog/pull/2630

We need to fix all problems found during the review/conflicts with the master branch.

<details><summary>[Click] Already done:</summary>
<p>
- resolve problem: the Makefile is updated and still contains the references to api-server instead of webhook server (2MD) #4475 
- resolve problem: the e2e tests are sometimes failing (not deterministic). Problem is that we moved the status initialization into controller logic. Sometimes assertion is before the controller process the CR. (1MD) #4474 
-  resolve problem: Service Catalog repo was moved under kubernetes-sigs org, so we need to rename the imports (1MD) #4469 
</p>
</details>

---

**AC:** 
- The Service Catalog documentation is updated (4MD) #4481 

- Update release process with capability of releasing the CRD from master and api-server bugfixing (3MD) #4480

- Merge tests refactor into master (2MD) https://github.com/kyma-project/kyma/issues/5210

- Configure and introduce crd and api-server release strategies in Service Catalog repo (1MD) https://github.com/kyma-project/kyma/issues/5217

- Merge CRD to master + create PR with migration tool (3MD) https://github.com/kyma-project/kyma/issues/5212

- Add upgrade test pipeline for Service Catalog upstream repo (2MD) https://github.com/kyma-project/kyma/issues/5216

- Remove the api-server source code from the service catalog (1MD) #4482

**Comment by PK85** [comment]
Set to 40SP, but its about 30.
