### ISSUE TITLE
Renumber Troubleshooting docs and update content guidelines

### ISSUE THREAD

**Issue by kazydek** [kyma-project/kyma#4398]
**Description**

- Renumber all **Troubleshooting** document types from 14 to 10, for example:

- [`14-01-overview.md`](https://github.com/kyma-project/kyma/blob/master/docs/kyma/14-01-overview.md) -> `10-01-overview.md`

- Update this excerpt from the [content strategy](https://github.com/kyma-project/community/blob/master/guidelines/content-guidelines/content-strategy.md#obligatory) to mention and describe the **Troubleshooting type** instead. Leave the number:
```
Operational Guide (10) - Use it to describe how to operate the component. Explain all details needed for the component troubleshooting.
```

**Reasons**

The Content Quality representatives decided to replace the **Operational Guide** document type (that was numbered as 10 in the content-strategy doc) with **Troubleshooting** as we do not have use cases for it in Kyma documentation.

**Comment by mmitoraj** [comment]
Already solved within https://github.com/kyma-project/community/issues/298
