### ISSUE TITLE
Commerce Events definition is not being rendered correctly in the Service Catalog 

### ISSUE THREAD

**Issue by brendandobbs** [kyma-project/kyma#4400]
**Description**

This issue came up in the hackathon, it appears all clusters are experiencing this issue. In the Service Catalog, the EC Events service class is not rendering the event definition.

See this screenshot.....

![image](https://user-images.githubusercontent.com/5688693/58974163-b2349200-87b9-11e9-8488-a65e3c400db0.png)

The UI is making a call to return the spec and it returns what looks like a valid events definition.

![image](https://user-images.githubusercontent.com/5688693/58974282-f6c02d80-87b9-11e9-994a-0efdcd43b4c5.png)

**Expected result**

Events are rendered correctly.

**Actual result**

No events are registered.

**Comment by derberg** [comment]
Fixed with 1.6, now if spec is invalid nothing shows in UI, and on the ClusterDocsTopic you can see the status and reason of failure
