### ISSUE TITLE
Application Broker doesn't work correctly in given namespace with invalid applicationMapping 

### ISSUE THREAD

**Issue by PK85** [kyma-project/kyma#4402]
**Description**
Looks that if ApplicationMapping has not existing name in application scope, then new correct ApplicationMappings are not taken. Service Catalog has no Service Classes.

**How to reproduce**
- create example Application with API Service, add AM, check if classes exists
- then delete Application (describe how SC catalog looks like)
- then add new Application with new API Service, add mapping, check if SC catalog see those classes

**AC**
- Application Broker must work even AM points to not existing Application name.

**Comment by mszostok** [comment]
## Tested scenario

1. Register Application **App1**
2. Bind **App1** to `qa` namespace
3. Remove the **App1** (ApplicationMapping stays as orphan obj)
    _1. NOTE: The Service Classes were removed from Service Catalog because there were no instances for them.
    2. NOTE: The application broker does not report anything in the logs_
4. Register Application **App2**
5. Bind  **App2** to `qa` namespace
    1. NOTE: Service Classes were added to Service Catalog
6. Register Application **App3**
7. Bind **App3** to `stage` namespace
    1. NOTE: Service Classes were visible in Service Catalog
8. Restart the application broker
    1. NOTE: in logs we had such entries:
        ```
			{"level":"error","log":{"message":"Error processing \"qa/ec-prod\" (will retry): cannot get AccessLabel from Application: \"ec-prod\": while getting application with name: \"ec-prod\": element not found","service":"labeler:controller","time":"2019-06-06T10:50:00.515Z"}}
		```
    2. NOTE: but the Service Classes were still visible in the Service Catalog view
9. Remove the **App2** (ApplicationMapping stays as orphan obj)
    1. NOTE: At that point the Service Catalog still has the Service Classes.
    2. NOTE: The application broker does not report anything in the logs
10. Bind **App4** both to `stage` and `qa` namespace
    1. NOTE: one more time all the classes were visible in the service catalog



Scenario were executed both on Minikube and GKE Cluster. Results were the same.

**Comment by polskikiel** [comment]
I've also tested it and everything works. I tried to create a selective environment mapping with one good and one wrong ID. One ServiceClass was created - according to assumptions.
