### ISSUE TITLE
The ServiceBindingUsagePrefixing test is failing 

### ISSUE THREAD

**Issue by polskikiel** [kyma-project/kyma#4409]
**Description**

The ServiceBindingUsagePrefixing test is failing when it tries to assert if the environment variables were injected into the test pod with status `503`.

```
Waiting for function failed in given timeout 2m0s. Function was executed 120 times. Last error: while getting envs from [http://acc-test-env-tester.svc-test-ns-4bn5d.svc.cluster.local/envs], received unexpected status code [got: 503, expected: 200]
```

It looks like the problem can be caused by istio.

**Comment by mszostok** [comment]
will be fixed in https://github.com/kyma-project/kyma/issues/5375
