### ISSUE TITLE
Unordered lists do not render in toggles in the the Console UI docs

### ISSUE THREAD

**Issue by kazydek** [kyma-project/kyma#4426]
Unordered lists do not render in toggles in the the Console UI docs:

**Description**

![image](https://user-images.githubusercontent.com/40655785/59089527-a99fa100-890a-11e9-9297-5884b5d70f99.png)

**Expected result**

![image](https://user-images.githubusercontent.com/40655785/59089540-b45a3600-890a-11e9-9f74-2254571f725f.png)

**Comment by derberg** [comment]
already fixed in 1.3
