### ISSUE TITLE
Proposal: Overrides in different deployment scenarios

### ISSUE THREAD

**Issue by Tomasz-Smelcerz-SAP** [kyma-project/kyma#443]
Our overrides approach is generic, but we don't handle different deployment scenarios very well.
We need clean and easy to maintain mechanism, that allows for different scenarios, e.g.:
- local deployment
- cluster deployment
- commercial deployment (an extension for custom clusters with additional features etc.)

The goal is to keep overrides for each scenario as small as possible.
Taking the above example: "local" overrides should be minimal (probably empty?), "cluster" should be an extension of "local", "commercial" should be an extension of "cluster", etc.
Probably the mechanism should be generic enough so that users can provide several different deployment scenarios that build on each other, extending the previous one in a controlled way.

Acceptance Critera:
- Provide a proposal by creating a draft for end-user documentation about how to configure overrides for different deployment scenarios.

**Comment by Tomasz-Smelcerz-SAP** [comment]
Proposal: https://github.com/kyma-project/kyma/compare/master...Tomasz-Smelcerz-SAP:generic-overrides?expand=1#diff-4c13f9db2a91e136f1682348349876b8

**Comment by strekm** [comment]
looks good to me

**Comment by pbochynski** [comment]
The issue is solved by separate combo yamls (cluster / minikube)
