### ISSUE TITLE
Support for GraphQL API documentation

### ISSUE THREAD

**Issue by giovannidegani** [kyma-project/kyma#4431]
**Description**

I would love to be able to use Kyma as platform to write and deploy GitHub Probot apps.Having support for the GraphQL API of GitHub would also be great as that are some enterprise/AD integration features that are only available there.

**Reasons**

Extending GitHub with some extra functionality can be extremely useful, especially within an Enterprise context we could integrate GitHub better with several tools internally and SaaS to provide a better developer experience and transparency for a development organization.

Some scenarios:

All of those are thinking in the context of a Private Organization in GitHub that have several teams.

- Building of Self-Service tools that could allow Teams to request external collaborators to be added to their repositories, but at the same improving the governance of that so that a central admin team could approve those requests and have visibility on it.
- Seamless Integrate GitHub with MS Teams and extend the inner-source and cooperation between the development teams 
- Create tools that could look deeper on how teams are running their repositories in a private organization and centrally suggest improvements and adherence to standards.

**Comment by derberg** [comment]
Hey Giovanni, thanks a lot for that issue. I think we talked on our slack channel. I love the idea of integrating GitHub with Kyma.

Is explicit GraphQL support needed? I mean I did one GitHub app few month ago and at the end I had to sometimes use their REST v3 as not everything was available in GraphQL API. Of course awesome to support GraphQL, I do not question it, but would it be a must for, let's say, first integration?

**Comment by giovannidegani** [comment]
Hey Lukasz, yep we talk over slack briefly, one of my first scenarios is actually interacting with this API
https://developer.github.com/v4/object/externalidentity/ for external identity in GitHub, but that is only available in the GraphQL API, but I agree also that a first version without GraphQL support can also have a lot value for a lot of people.

**Comment by lszymik** [comment]
Hello,

We have added it to the backlog where the most suitable team will start with the investigation of the details.

Cheers
Lukasz

**Comment by derberg** [comment]
@giovannidegani fyi we work on a showcase to check how such integration could be done. There is a team that has an incubating project for that https://github.com/kyma-incubator/hack-showcase. They started at the beginning of July. Please take a look at what they already have, maybe you have some feedback already.

**Comment by giovannidegani** [comment]
Thanks, I just returned from vacation, will try to catch up to this in the next weeks.

**Comment by giovannidegani** [comment]
@derberg Thanks a lot! This looks awesome! We are ramping up github usage in my org, I just need to free up some time and start playing around with it. :)

**Comment by pbochynski** [comment]
With the deprecation of API Registry this feature won't be implemented in Kyma Application Connector. The API Spec management was transferred to the new project: https://github.com/kyma-incubator/compass.
