### ISSUE TITLE
Test Login with ConfigurationGenerator created config using kubectl

### ISSUE THREAD

**Issue by Disper** [kyma-project/kyma#4433]
**Description**

**Reasons**
Making sure that logging works with ConfigurationGenerator using kubectl.

**Attachments**

**Comment by piotrmsc** [comment]
We can extend `apiserver-proxy-tests` which are already fetching a token, downloading kubeconfig from config generator and invoke kubectl exec, we can add there more operations like `kubectl get ns` `kubectl create sth` etc.
