### ISSUE TITLE
Automatise upgrade test

### ISSUE THREAD

**Issue by Disper** [kyma-project/kyma#4435]
**Description**
We need a pipeline that will perform an upgrade from the previous release to a current RC. 

**Reasons**
W have to assure that upgrading from previous version to latest one works correctly.

**Attachments**

**Comment by kubadz** [comment]
Upgrading works. The only two problems I came across are:
* issue with logging-promtail (already fixed and will be cherry-picked to rc2 [#4466])
* knative-tests not passing on xip (#4015)

**Comment by jakkab** [comment]
implemented in https://github.com/kyma-project/test-infra/pull/1698
