### ISSUE TITLE
Component renaming - configuration generator

### ISSUE THREAD

**Issue by piotrmsc** [kyma-project/kyma#4438]
**Description**

As a part of #2502 we have to rename our configurations generator to iam-kubeconfig-service.

- Have a readme in the components folder explaining the naming convention for components
- Link the readme in the developer guide if necessary
- Documentation updated
- Vendor changes applied including changes in prow jobs

**Reasons**

**Attachments**

**Comment by strekm** [comment]
- [ ] Create a new component
- [ ] Create Prow job for the new component
- [ ] Update charts
- [ ] Remove Prow job for the old component
- [ ] Remove the old component
- [ ] Update docu
