### ISSUE TITLE
Move and rename gateway tests

### ISSUE THREAD

**Issue by piotrmsc** [kyma-project/kyma#4444]
**Description**

As a part of #2504 we have to move cluster users tests :
`tests/gateway-tests` -> `tests/integration/gateway`

Have a readme in the tests folder explaining the naming convention
Link the readme in the developer guide
Update octopus config if necessary and prow jobs

**Note**
Consider #4712 and align on the name first

**Reasons**

**Attachments**

**Comment by Demonsthere** [comment]
It seems that this tests are not ours and not connected to the istio gateway:

```
 # Event Service Tests
/tests/gateway-tests/ @montaro @abbi-gaurav @marcobebway @radufa @sayanh
```

**Comment by Demonsthere** [comment]
Moving to Evengers Backlock

**Comment by Abd4llA** [comment]
Some work was already done based on old consistency requirements. 
#4709

**Comment by sayanh** [comment]
Gateway tests have been renamed to https://github.com/kyma-project/kyma/tree/master/tests/integration/event-service
