### ISSUE TITLE
Code snippets render incorrectly

### ISSUE THREAD

**Issue by kazydek** [kyma-project/kyma#4446]
**Description**

Could you investigate why code snippets sometimes render incorrectly both in the Console UI and on the website, like in [installation docs](https://kyma-project.io/docs/master/root/kyma/#installation-install-kyma-on-a-cluster--provider-installation--gke--install-kyma)?

Website:

![image](https://user-images.githubusercontent.com/40655785/59177697-2033dd00-8b5d-11e9-8fce-1b3935930c4f.png)

Console UI docs:

![image](https://user-images.githubusercontent.com/40655785/59182134-3fd10280-8b69-11e9-8054-d1b0ee6b204b.png)

**Expected result**
![image](https://user-images.githubusercontent.com/40655785/59177844-9c2e2500-8b5d-11e9-9efd-847e25c24b2b.png)

**Comment by derberg** [comment]
Fixed in the UI
