### ISSUE TITLE
Execute Kyma 1.3 Release

### ISSUE THREAD

**Issue by PK85** [kyma-project/kyma#4447]
**AC**
- execute the 1.3 Release 
- enhance the release process and tooling
  - https://github.com/kyma-project/community/issues/265
  - https://github.com/kyma-project/community/issues/294

Guidelines: https://github.com/kyma-project/community/tree/master/guidelines/releases

**Comment by adamwalach** [comment]
Release plan:
- On Monday (1.07.2019) we will send reminder to teams about planned RC1 release: the RC1 branch will be created at 9:00 on Friday (5.07.2019)
- also on Monday we will define jobs in test-infra according to https://github.com/kyma-project/community/blob/master/guidelines/releases/release-process.md#define-release-jobs
- on Wednesday (3.07.2019) we will create RC0 to test the process (this release will not be visible anywhere)

**Comment by adamwalach** [comment]
Relevant issues:
* Timeout on ClusterTestSuite - https://github.com/kyma-incubator/octopus/issues/29
* Could not resolve github - https://github.com/kyma-project/test-infra/issues/1198
