### ISSUE TITLE
kyma-config-cluster.yaml not found

### ISSUE THREAD

**Issue by budanm** [kyma-project/kyma#4451]
**Description**
Kyma Version : 1.2.0-rc1

Setting up Kyma on Kubernetes GKE following the instruction on the home page of kyma
https://kyma-project.io/docs/root/kyma/#installation-install-kyma-on-a-cluster.

However, as per step 4 of the installation instruction wehave to download kyma-config-cluster.yaml
The command :
wget https://github.com/kyma-project/kyma/releases/download/$KYMA_VERSION/kyma-config-cluster.yaml

**Expected result**

The file kyma-config-cluster.yaml should be downloaded

**Actual result**

Instead we get a response 404

**Steps to reproduce**

Execute wget https://github.com/kyma-project/kyma/releases/download/$KYMA_VERSION/kyma-config-cluster.yaml

on GKE command shell
**Troubleshooting**

**Comment by Tomasz-Smelcerz-SAP** [comment]
Installation procedure is different for 1.2. Please use docs available at: https://kyma-project.io/docs/1.2
