### ISSUE TITLE
Update Service Catalog Chart

### ISSUE THREAD

**Issue by piotrmiskiewicz** [kyma-project/kyma#4459]
Add migration tool execution to the chart, run the migration tool only if previous SC version has api-server

**Comment by jasiu001** [comment]
When migration tool will be fully completed then upgrade test from [here](https://github.com/kyma-incubator/service-catalog/pull/26) should be run to ensure tool and upgrade test works correctly.

**Comment by polskikiel** [comment]
I ran the upgrade test mentioned by @jasiu001 and found a bug in the migration tool. It is fixed in this kyma-incubator/service-catalog#31 PR. After that fix, the test is still failing because there is probably a bug in the `test broker`.
