### ISSUE TITLE
Block API-Server

### ISSUE THREAD

**Issue by piotrmiskiewicz** [kyma-project/kyma#4462]
block API-Server mutations operation before backup (probably by webhook functionality)

**Comment by adamwalach** [comment]
I did the full implementation here: https://github.com/adamwalach/service-catalog/tree/crds-migration-readonly-with-certs
It works properly when it's triggered on "normal" crds - webhook is triggered and it rejects changes with a proper message which is delivered to a client. 
But in case of using additional apiserver we get a wrong error massage: 
```
Error from server (InternalError): error when creating "contrib/examples/walkthrough/test-broker/test-servicebroker.yaml": Internal error occurred: failed calling webhook "validating.reject-changes.servicecatalog.k8s.io": webhook does not accept v1beta1 AdmissionReviewRequest
```
The webhook is in fact not triggered at all. 
In case of migration procedure we always have a scenario where apiserver is present (thats why we do the migration) so we have to accept the limitation of not having a custom error message. 
It also makes the final solution a lot simpler cause we don't need anything beside `ValidatingWebhookConfiguration` - the service and a webhook are not be triggered at all.
