### ISSUE TITLE
SPIKE: Helm rollback to previous release

### ISSUE THREAD

**Issue by piotrmiskiewicz** [kyma-project/kyma#4463]
The rollback must restore all resources
see helm rollback hook

**Comment by polskikiel** [comment]
My investigations so far: 

When I upgrade SC apiserver version to webhooks and then I run `helm rollback catalog 0`.
The rollback fails with message: 
```
Error: no APIService with the name "v1beta1.servicecatalog.k8s.io" found
```
But the rollback goes on and restores Apiserver but the webhook server still exists.
