### ISSUE TITLE
Service Binding Variables

### ISSUE THREAD

**Issue by akrausesap** [kyma-project/kyma#447]
Confirm these statements before you submit the issue:

- [x] I have searched open and closed issues for duplicates.
- [x] I have read the contributing guidelines.
---

**Description**

Dear Colleagues,

In order to simplify working with Backing Services in Frameworks like Spring Boot, it would be great if the Binding between Deployment and Backing Service would be a little more flexible in terms of Environment Variables. Basically 2 things would be good:

1. Enable Mapping to Custom Environment Variable names (which are mandated by programming language, e.g. Spring Boot) https://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-external-config.html (see system properties: "If you use environment variables rather than system properties, most operating systems disallow period-separated key names, but you can use underscores instead (for example, SPRING_CONFIG_NAME instead of spring.config.name).")
2. Provide a cloud Foundry like VCAP variable (https://docs.run.pivotal.io/devguide/deploy-apps/environment-variable.html#VCAP-SERVICES) which is also automatically interpreted by many languages 

This is already discussed with PK.

Cheers

Andreas

**Reasons**

Better Developer Productivity / Easier usage

**Attachments**

N/A

**Comment by piotrmiskiewicz** [comment]
Consider mapping variables in the Pod/Deployment configuration, see doc: https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.10/#envvar-v1-core
