### ISSUE TITLE
Provision RC clusters in a separate GKE location

### ISSUE THREAD

**Issue by jakkab** [kyma-project/kyma#4476]
**Description**

RC clusters are provisioned in the `europe-west3` location that is available for all users. If the location is overloaded, the release post-submit job fails to run Kyma due to exceeded quotas. Consider provisioning RC clusters in a dedicated location. 

**Reasons**

We should avoid delaying releases.

**Comment by kasiakepka** [comment]
This issue is fixed here: https://github.com/kyma-project/test-infra/pull/1164
Clusters are created in random zones `europe-west3-a/b/c`, it is possible to create RC cluster in a different region if necessary.
