### ISSUE TITLE
Component test for tracing module missing

### ISSUE THREAD

**Issue by a-thaler** [kyma-project/kyma#4477]
**Description**
There is no component test for tracing at all, so manual testing is required for every release.
Add a test assuring at least basic tracing functionality, like service-to-service traces

**Reasons**
Automated confidence

**Comment by clebs** [comment]
The testing of tracing will be done in #5225 as part of the `core-test-external-solution`.

It is better than having a new test from scratch because we can take advantage of the traces generated by the previous stages of the test. Therefore closing this issue in favor of #5225
