### ISSUE TITLE
Filter lambda logs for health check

### ISSUE THREAD

**Issue by a-thaler** [kyma-project/kyma#4478]
**Description**

Filter the health check logging for lambdas **by default**. The logs are mostly filled up with these entries and makes it really hard to debug. Wit the update to Loki 0.1.0 it should be possible to define a negation regexp to exlude the logs in the query
```
2019-06-06T06:51:24.440715871Z | ::1 - - [06/Jun/2019:06:51:24 +0000] "GET /healthz HTTP/1.1" 200 2 "-" "curl/7.52.1"
-- | --
```

User should still be able to enable health check logs in the UI

**Reasons**
Better debugging experience

**Comment by kwiatekus** [comment]
Apply a negative filter in the regexp parameter, somthing like:
`regexp=!~healtz`

**Comment by kwiatekus** [comment]
Blocked, because  negative filtering via regexp parameter still doesnt work in loki

**Comment by kwiatekus** [comment]
For now, please just skip rendering health check logs in the UI
