### ISSUE TITLE
Release process should work both for the master branch and dedicated api-server branch

### ISSUE THREAD

**Issue by mszostok** [kyma-project/kyma#4480]
**Description**

The release process should work both for the master and dedicated api-server branch.

The release is done by the Travis job. The current release process is documented here: https://github.com/kubernetes-sigs/service-catalog/wiki/Release-Process

**AC**
- release process for CRD only from master is working
- release process for the dedicated api-server branch is working

**Comment by adamwalach** [comment]
## Description
Release process creates three types of artifacts:
- docker images
- svcat binaries
- helm chart

<details><summary>docker images</summary>
<p>
They are created for multiple platforms (amd64, arm, arm64, ppc64le, s390x) and for the following components: user-broker, test-broker, service-catalog.

#### Commits
For every commit on master branch we produce two images (for every platform and component) with following tags:
- canary 
- last_release-commit_nr-commit_id (ie: v0.2.5-1-gc8406fe)
  It is computed in Makefile: 
  ```
  VERSION ?= $(shell git describe --tags --always --abbrev=7 --dirty)
  ```
  According to the manual: 'This command finds the most recent tag that is reachable from a commit'
#### Release
For every release we produce two images (for every platform and component) with following tags:
- latest
- release name (ie: v0.2.6)
</details>

<details><summary>svcat binaries</summary>
<p>
Svcat binaries are created for multiple platforms (darwin, linux, windows).

#### Commits
For every commit on master branch we produce two binaries (for every platform):
- canary 
- last_release-commit_nr-commit_id (ie: v0.2.5-1-gc8406fe)

#### Release
For every release we produce two binaries (for every platform) with following tags:
- latest
- release name (ie: v0.2.6)
</details>

<details><summary>helm chart</summary>
For every release we produce helm charts for the following components: healthcheck, user-broker, test-broker, service-catalog. Chart version is hardcoded in Chart.yaml - it has to be manually changed before every release
</details>

## Urls
URLs used currently by SC:
- https://quay.io/repository/kubernetes-service-catalog/
- svcat binary: https://download.svcat.sh/cli/latest/darwin/amd64/svcat
- helm chart: https://svc-catalog-charts.storage.googleapis.com/

URLs used for testing:
- https://quay.io/repository/kyma-service-catalog/
- svcat binary: https://kymaservicecatalog.blob.core.windows.net/cli/canary-apiserver/darwin/amd64/svcat
- helm chart: https://kyma-service-catalog.storage.googleapis.com/index.yaml
