### ISSUE TITLE
Document the CRD implementation in the Service Catalog documentation

### ISSUE THREAD

**Issue by mszostok** [kyma-project/kyma#4481]
**Description**

The Service Catalog documentation (https://svc-cat.io/docs/) should be updated and contains information about the CRD implementation, e.g:
  - add information about api-server support for 9 months, only bugfixing available 
  - add required diagrams
  - briefly describe the webhook architecture
  - ...decide if sth else should be documented

Basically, we should provide more or less the same documentation coverage that was for the api-server.

---
_NOTE: was estimated to 4MD_

**Comment by adamwalach** [comment]
On the main k8s site there is also a section about service catalog: https://kubernetes.io/docs/tasks/service-catalog/install-service-catalog-using-helm/
I don't know yet how to update it
