### ISSUE TITLE
AddonsConfiguration Repository controller and syncer namespace aware

### ISSUE THREAD

**Issue by piotrmiskiewicz** [kyma-project/kyma#4488]
Create new controller which tracks AddonsConfiguration resources. All syncing logic must be namespace aware

AC:
 - ServiceBroker created/deleted when it is needed
 - new syncer (or syncers) which are (Cluster)AddonsConfiguration aware

**Comment by mszostok** [comment]
Malformed repos to test: 
- https://github.com/mszostok/bundles/releases/download/latest/index.yaml
  problems: 
     - validation: `"Could not load bundle: while loading bundle and charts for bundle [redis] and version [0.0.3]: while mapping buffered files to form: bundle does not contains any plans, please check if bundle contains \"plans\" directory`
     - fetching: `Could not load bundle: while reading bundle archive for name [gcp-service-broker-not-exists] and version [0.0.2]: got http error: status=404`



-
