### ISSUE TITLE
Switch to (Cluster)AddonsConfiguration

### ISSUE THREAD

**Issue by piotrmiskiewicz** [kyma-project/kyma#4492]
AC:
 - Enable AddonsConfigration logic (use code created in tasks: #4488 and #4492)
 - Create a default ClusterAddonsConfigurationj in the Helm Broker chart
 - changes in the chart must be done with console-backend-changes
 - make sure that when helm-broker release is deployed then all bundles are already available in the SC
 - new CRDs support "managed:true/false" label, and UI will be able to display additional capabilities (like information that AC is mananged and after upgrade AD will be restored)
e.g. app.kubernetes.io/managed-by : kyma 
   - descrtibe that label in our documentation

**Comment by piotrmiskiewicz** [comment]
update chart with the migration job done in #4491

**Comment by mszostok** [comment]
In https://github.com/kyma-project/kyma/pull/4770 PR, I've added commented code which needs to be enabled

search for comments with:
`https://github.com/kyma-project/kyma/issues/4492`
