### ISSUE TITLE
console-backend-service changes

### ISSUE THREAD

**Issue by piotrmiskiewicz** [kyma-project/kyma#4493]
Use (Cluster)AddonsConfiguration instead of ConfigMaps.
Task should be merged and version bumped with final changes in helm broker chart.

Consider a feature flag which allows us to merge changes to master but release the feature with Helm-Broker changes.

**Comment by mszostok** [comment]
Here is the PR which removes the old implementation:
https://github.com/kyma-project/kyma/pull/4791

**When reviewing select No Whitespaces That will simplify the review process!**
