### ISSUE TITLE
Integrate Knative Serving and Build

### ISSUE THREAD

**Issue by joek** [kyma-project/kyma#4496]
**Description**

Knative Serving and Build should be integrated as modules into kyma.

**Reasons**

We like to leverage knative

**Note**
Due to a design problem, we will currently use the docker registry provided by the user. 

**AC**

- Make Knative build a module.
- Add / review tests for knative build and serving that uses the user provided docker registry.
- Add / review knative documentation (make sure everything is marked as experimental).

**Comment by joek** [comment]
AC:
- Make build a module
- Add / review tests for kantive build and serving
- Add / review knative documentation (make sure everything is marked as experimental)

**Comment by bszwarc** [comment]
We will also need to add proper documentation for these two modules.
