### ISSUE TITLE
Backup and Upgradebility test for Knative Serving and Tekton

### ISSUE THREAD

**Issue by joek** [kyma-project/kyma#4498]
**Description**

Implement Backup and Upgradebility test for knative serving and build.

**Reasons**

We need to backup and upgrade.

**Comment by Abd4llA** [comment]
@joek can you explain a bit why it's blocked?

**Comment by rakesh-garimella** [comment]
We need to have knative build and serving part of master for this story to be finished. Also we need some example to test backup and upgradability.

@Abd4llA  Do we need upgradability tests since we dont have a stable api for serving and also build might move to tekton in future..

**Comment by rakesh-garimella** [comment]
here are the branches already: https://github.com/rakesh-garimella/kyma/tree/backup-serving-test
and for upgrade test: https://github.com/rakesh-garimella/kyma/commits/serving-upgrade
