### ISSUE TITLE
Prepare presentation how we extended service catalog for SC team

### ISSUE THREAD

**Issue by PK85** [kyma-project/kyma#451]
I've talked to SC team, and they are eager to use one of their weekly call to see our solution we built around a service catalog. A goal is to make sure that we are aligned with SC team roadmap, and maybe move our functionality to SC github.

AC:
- Prepare demo with SBU and UK, showing full automation of credentials injection
- Explain why we use separate CRDs
- SC team want to migrate solution to CDRs in the future, explain that SBU and UK could be already provided as CRDs as a first part already migarted

**Comment by PK85** [comment]
@mszostok 
We need to rethink the idea about the labels injection which are currently being done by the Binding Usage Controller. This behavior may be too complex to be in a core implementation in a Service Catalog.

**Comment by PK85** [comment]
Presentation description:

E2E walkthrough from provisioning a service class to injecting configuration/credentials into any resource:
- all based on CRDs and PodPreset functionality
- all operations available by CLI and UI
- documentation

General documentation:
- https://github.com/kyma-project/kyma/blob/master/docs/service-catalog/docs/012-details-provisioning-and-binding.md#provisioning-and-binding-flow
- https://github.com/kyma-project/kyma/blob/master/docs/service-catalog/docs/012-details-provisioning-and-binding.md#bind-with-other-resources

Binding usage Controller docs, architecture, examples:
- https://github.com/kyma-project/kyma/tree/master/components/binding-usage-controller/docs

**Comment by mszostok** [comment]
as a next point, we can also add information about the prefixing injected variables

**Comment by mszostok** [comment]
With @PK85 we presented the ServiceBindingUsage concepts during the **Kubernetes SIG Service Catalog** meeting handled _on September 10, 2018_. We will add a link to the recording immediately when it appears on YT.

We need to discuss concept further with Carolyn Van Slyck, Jay Boyd, and Jeff Peeler and then create some proposal.
