### ISSUE TITLE
Improve Kyma local installation guide (CLI & Scripts)

### ISSUE THREAD

**Issue by bszwarc** [kyma-project/kyma#4510]
**Description** 

We have introduced Kyma CLI as a tool to use when installing Kyma locally. However, we have also kept the already existing documentation on how to perform the installation using scripts. 
As a result,  the website lists randomly placed topics which can be misleading for the readers:

![2019-06-12_10-41-56.png](https://images.zenhubusercontent.com/5b9a2f6a2df36e0aa911ecbd/d7cda5ef-29ea-4fbb-9d83-dc898588438f)

It shouldn't be this way. If we want to keep both installation ways, we need to restructure our docs. I also think we should include some information about Kyma CLI. I suggest the following structure:

* Overview
 * Install Kyma locally 
   * CLI / Scripts (toggle)
 * Reinstall Kyma 
   * CLI / Scripts (toggle)

**Question 1**: we should mention Kyma CLI (what it is + link to README) - we can do it in a separate topic on Kyma CLI in our docs OR mention it in installation guide(s)
**Concern 1**: once the scripts are removed, we will need to adjust the docs again. 

**Reason**

Documentation is misleading - it says `install locally` then `install locally (scripts)` without explaining why (apart from a small note). Additionally, documents are not in order which makes it even more confusing.

**Comment by a-thaler** [comment]
Maybe there is a way to exclude the deprecated script from navigation?

**Comment by bszwarc** [comment]
Even if it would be possible - the content will still be there, available to the user when scrolling. This will be even more confusing - imagine reading about local installation using Kyma CLI, and then a `script` topic appears. 
So either get rid of them completely or structurize them using toggles to indicate CLI is the primary way and Scripts are an alternative.

**Comment by bszwarc** [comment]
Ok after a content SIG discussion, the outcome is as follows:
- leave scripts as legacy
- remove installation /reinstallation documentation (only) with 1.3 to avoid confusion.
- add more info about Kyma CLI if necessary

**Comment by derberg** [comment]
If something is deprecated, it should not be visible in documentation. Users should just be notified through release notes and announcement of next releases that given functionality is deprecated and going to be decommissioned at some point of time. There is no good argument to really display docs for deprecated functionality.

**Comment by bszwarc** [comment]
+1, removing these documents for 1.3.

**Comment by derberg** [comment]
It is more to cleanup:
- I think https://kyma-project.io/docs/master/root/kyma/#installation-local-installation-scripts-deep-dive should be removed
- you need to review all the other docs and clean up from `is-installed.sh` or anything like that, to make sure we are really covering kyma cli for local

**Comment by tomekpapiernik** [comment]
I'll handle this and remove the 3 docs that talk about the scripts. I am not aware of a way to trigger anything similar to the `is-installed` script in the CLI, so I'll have to leave a reference to this script until we can get installation status info in the CLI.
