### ISSUE TITLE
Application / Namespace Binding inconsistent

### ISSUE THREAD

**Issue by akrausesap** [kyma-project/kyma#4519]
**Description**

Dear Colleagues,
the value for bound applications differs between the master / overview and the detail page. This is observed in the 1.2-rc1 release.

![bound_applications2](https://user-images.githubusercontent.com/40229965/59351376-96cc0880-8d1e-11e9-9b97-8e8d29dfd168.png)

![bound_applications](https://user-images.githubusercontent.com/40229965/59351381-9895cc00-8d1e-11e9-8e49-0e636c70368e.png)

Regards

Andreas
**Expected result**

No difference

**Actual result**

there is one :-)

**Steps to reproduce**

Create an application and bind it

**Troubleshooting**

N/A

**Comment by kwiatekus** [comment]
Duplicates https://github.com/kyma-project/console/issues/940
