### ISSUE TITLE
Basic updated and restructured prometheus-operator chart

### ISSUE THREAD

**Issue by a-thaler** [kyma-project/kyma#4520]
**Description**
The current monitoring module is based on this deprecated prometheus-operator chart: https://github.com/coreos/prometheus-operator/tree/release-0.29/helm, having the prometheus-operator itself extracted in a dedicated module.

To keep up with the latest fixes and improvements, we should update to the latest version located here: https://github.com/helm/charts/tree/master/stable/prometheus-operator
The chart got fully re-structured and we need to adapt to it. Furthermore, there is no reason anymore to keep the operator as an isolated module as the CRDs got moved into the cluster-essentials.

In this ticket the old charts should bbe replaced with the new chart, but the focus should be on having the basich chart working, without any customizations and validation for other modules. IN the follow-up all modules will be validated and restructured.

Items:
- [x]  Update the monitoring chart to latest structure and version
- [x] Update the CRDs in cluster-essentials (assure they are NOT in monitoring chart) and add missing ones
- [x] Remove prometheus-operator module as it is now part of monitoring module
- [x] Check that all exporters are still deployed (having more might be fine)
- [x] Check that prometheus is collecting the metrics of the exporters
- [x] Check that prometheus-dashboard is accessible from internal
- [x] Check that you can browse metrics in grafana
- [x] Check that the alertmanagaer is working and the dashboard is accessible from internal
- [ ] Make prometheus part of the service mesh and add `mTLS` to prometheus if possible. Related issues: #5235 #5555
- [x] Assure Grafana Single-Sign-On integration is working without login page
- [x] Assure an upgrade is working
- [x] Check if a dynamic dashboard configuration is now possible (one configmap per dashboard, grafana picks up all) and adjust the documentation/examples
- [x] Assure Slack/VictorOps alerting is working as before
- [x] Assure that monitoring of all monitoring related pods is working
- [x] Check that kiali is showing istio temetry data

**Reasons**
Get rid of dedicated prometheus-operator module, update to latest version, adopt new simplified structure to have cleaner code base

**Comment by Morriz** [comment]
Can we get more traction on this? I have been using stable/prometheus-operator helm chart for almost a year now and it has a way better ootb dashboard experience.

**Comment by igor-karpukhin** [comment]
Moved back to the backlog since modifications to original files makes it too hard to upgrade the actual components like Grafana, Prometheus, etc. Also, new files structure is completely different than the old one we currently have. We need a way to keep our modifications like SSO, istio-injection, etc. away from the original files of components since we'll run into the same problem again and again.

**Comment by a-thaler** [comment]
Basic version is working and resides in a fork for now.
All customization and final merge of the fork will be done in https://github.com/kyma-project/kyma/issues/6124
