### ISSUE TITLE
Application Certificates can be used across multiple clusters

### ISSUE THREAD

**Issue by sbgreene1307** [kyma-project/kyma#4522]
**Description**

When configuring external applications to send events, you must generate a certificate to be used when sending events. In order to generate this cert, we used the [one-click-integration.sh](https://github.com/janmedrek/one-click-integration-script) script. This certificate can be used when sending events to different CLUSTERS. 

GKE Cluster
Kyma:  1.0.0
Kubernetes:
```
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.0", GitCommit:"0ed33881dc4355495f623c6f22e7dd0b7632b7c0", GitTreeState:"clean", BuildDate:"2018-09-27T17:05:32Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"12+", GitVersion:"v1.12.7-gke.10", GitCommit:"8d9b8641e72cf7c96efa61421e87f96387242ba1", GitTreeState:"clean", BuildDate:"2019-04-12T22:59:24Z", GoVersion:"go1.10.8b4", Compiler:"gc", Platform:"linux/amd64"}
```

**Expected result**

Certificates cannot be used across different clusters for sending events

**Actual result**

Using a debian:stretch docker image and adding the .pem file generated by the one-click-integration.sh, I can issue curl requests to different clusters to send events.

**Steps to reproduce**
1. Add an application to both clusters using the same application name.
1. Use the one-click-integration.sh to generate a pem file for sending the event-catalog for both clusters. 
1. Build and run this Dockerfile
1. Curl the event endpoint with verbose flag
1. See the TLS handshake is successful and both requests result in "Event Ignored" responses. 

Dockerfile for testing:
```
FROM debian:stretch

RUN apt-get update && \
    apt-get -y install curl

ADD ./pemfile.pem pemfile.pem

CMD ["/bin/bash"]
```

```
# add pem file to current dir
docker build -t testing .
docker run -it --name testing testing

root@44444444444:/# echo '{"event-type": "cart.created", "event-type-version": "v1", "event-time": "2019-04-15T14:00:00+00:00", "data": {"foo": "bar"}}' | curl -X POST -d @- https://gateway.${FIRST_DOMAIN}:443/${APP_NAME}/v1/events --cert pemfile.pem -k -v

root@44444444444:/# echo '{"event-type": "product.created", "event-type-version": "v1", "event-time": "2019-04-15T14:00:00+00:00", "data": {"foo": "bar"}}' | curl -X POST -d @- https://gateway.${SECOND_DOMAIN}:443/${APP_NAME}/v1/events --cert pemfile.pem -k -v
```

**UPDATE**
I was also able to use certs from one cluster to register an event catalog on a new cluster. I only created the application in the new cluster and never generated certificates for it.

**Comment by Szymongib** [comment]
Should be resolved by #4724
