### ISSUE TITLE
Update Service-Catalog to v0.1.31 

### ISSUE THREAD

**Issue by aszecowka** [kyma-project/kyma#453]
We create some issues for Service-Catalog:
https://github.com/kubernetes-incubator/service-catalog/issues/2306
https://github.com/kubernetes-incubator/service-catalog/issues/2291
https://github.com/kubernetes-incubator/service-catalog/issues/2276

and PRs:
https://github.com/kubernetes-incubator/service-catalog/pull/2333
https://github.com/kubernetes-incubator/service-catalog/pull/2337

Update ServiceCatalog if new version released, additionally:
- check if above issues have been solved and released

**Comment by mszostok** [comment]
#### Status on Sept, 11:
- the newest release: **v0.1.31**
- only the defaultRelistInterval was fixed for ns scoped brokers ([issue]( https://github.com/kubernetes-incubator/service-catalog/issues/2306)) and available in the newest release
