### ISSUE TITLE
Update markdown-documents.md re: using quotation marks in metadata

### ISSUE THREAD

**Issue by mmitoraj** [kyma-project/kyma#4532]
**Description**

It occurs that it is ok to use quotations marks in the title and type metadata in Markdown documents. If you want to use quotation marks, you just need to do it in the proper way. Update the [markdown-documents.md](https://github.com/kyma-project/kyma/blob/master/docs/headless-cms/03-03-markdown-documents.md) wiuth the following information:

Using quotation marks in the title and type metadata. 

```
- OK -> title: Overview doc 
- OK -> title: "Overview doc" 
- Ok -> title: '"Overview" doc' 
- Ok -> title: \"Overview" doc
- Wrong -> title: "Overview" doc 

```

**Reasons**

Updated documentation.

**Comment by derberg** [comment]
Please take a look on my comment in PR, in my opinion there is an error in merged changes

**Comment by mmitoraj** [comment]
@derberg Fixed.
