### ISSUE TITLE
Enable dex connector configuration via UI

### ISSUE THREAD

**Issue by joek** [kyma-project/kyma#4537]
**Description**

As a Administrator I need to setup the IdP used by kyma for authentication. This should be as simple as possible using the UI.

**Reasons**

People setting up Kyma (espacial in a as a service offering) don't have to be kubernetes specialists and are confused by kubectl.

This ticket is based on end customer feedback

**Comment by piotrmsc** [comment]
@joek Console allows to register new IDPs - in the console it is called "IDP Presets". Take a look at attached screenshot, do you require any additional view?

**Comment by joek** [comment]
I am talking about the second thing. Maintaining the dex connectors. Our customers will probably not use github or facebook but there are more "professional" solutions out there ;-)

**Comment by piotrmsc** [comment]
Ok, I have adjusted the title accordingly :) I have asked about this feature  in the dex repo, see here :  https://github.com/dexidp/dex/issues/1472

**Comment by piotrmsc** [comment]
After latest changes we do not want to expose dex configuration via UI. Dex will remain a system component for admins of kyma.
