### ISSUE TITLE
remove not used references to istio-ingress-certs secret name

### ISSUE THREAD

**Issue by strekm** [kyma-project/kyma#454]
global.istio.tls.secterName: "istio-ingress-certs", previously was hardcoded in installer. During refactoring i noticed that reference is not used (thus can be removed from installer) but instead hardcoded string is used across charts. Please verify if it's needed and remove if unnecessary.

**Comment by pbochynski** [comment]
@sjanota Can you fix it as a part of work in #1000 ?

**Comment by sjanota** [comment]
@pbochynski Yes, I can do it
