### ISSUE TITLE
Add option to skip TLS verification while fetching API specification

### ISSUE THREAD

**Issue by johnkbarrow** [kyma-project/kyma#4549]
**Description**

Add an option to allow the skipping of TLS verification by the application registry when fetching API specifications

**Reasons**

A number of customer and partner developers typically run Commerce Cloud locally. The local instance is protected by a self-signed SSL cert, which fails the verification done by the application registry when trying to pair the two systems together.
The Application Connector already has a --skipVerfiy flag that allows the verification of the cert to be skipped; it would be very very helpful if there was a similar flag on the application registry

**Attachments**

**Comment by lszymik** [comment]
Hello,

Did you tried with the following flag
```
insecureAssetDownload := flag.Bool("insecureAssetDownload", false, "Flag for skipping certificate verification for asset download. ")
```?

It is the flag for `application-registry` service.

**Comment by johnkbarrow** [comment]
Hi @lszymik - I believe this is by default set to true and doesn't help in the situation described.

For reference, @Szymongib created a custom image of the application-registry _hereszymongib/application-registry:skip-verify-on-spec-fetch_ that introduced a _--insecureSpecificationDownload=true_ flag as per https://kyma-community.slack.com/archives/CD0K2NSQZ/p1559212579022400?thread_ts=1558607844.013800&cid=CD0K2NSQZ

**Comment by lszymik** [comment]
@johnkbarrow Sorry, I was wrong.
Indeed the flag is not working for that use case.
