### ISSUE TITLE
Config docs api-controller

### ISSUE THREAD

**Issue by strekm** [kyma-project/kyma#4558]
Description

Create configuration documents for the Service Mesh component.
These documents should list and describe configurable parameters from values.yaml file of API Controller.

Make sure you:

Create the documents based on the existing [template](https://github.com/kyma-project/community/blob/master/guidelines/templates/resources/configuration.md).
Rely on the already created configuration documents for the [Asset Store](https://kyma-project.io/docs/master/components/asset-store/#configuration-configuration).
Reasons

Have a set of configuration documents that describe values from the API Controller. values.yaml files you can override.

Attachments
It relates to the epic #4028.

**Comment by derberg** [comment]
According to https://github.com/kyma-project/kyma/issues/4062#issuecomment-497257713 there was nothing to do with api-controller so removing this task from this epic https://github.com/kyma-project/kyma/issues/4028. Of course, it is not blocking you from documenting your component ;)

**Comment by piotrmsc** [comment]
API controller is deprecated and it's planned to be removed.
