### ISSUE TITLE
Implement test for connecting Kyma Runtime to the Central Kyma

### ISSUE THREAD

**Issue by Szymongib** [kyma-project/kyma#4592]
**Description**

Implement the test for the scenario of connecting Kyma Runtime to the Central Kyma.

The test should verify that:
- Connectivity Certs Controller correctly fetches certificates from the Central Connector Service
- Application certificate generated by the Central Connector Service is accepted both on the Central Kyma as well as in the Kyma Runtime

**Reasons**

This test scenario should be automated.

**Comment by janmedrek** [comment]
This scenario is not longer supported (1.12 and forward).
