### ISSUE TITLE
Prepare a working flow to demonstrate the in cluster events concept

### ISSUE THREAD

**Issue by abbi-gaurav** [kyma-project/kyma#4619]
**Description**

As a stakeholder, I should be able to understand the concept presented in #4506 to support in-cluster events by referring to a working flow. Additionally, it should help us clarify how the User Interface would look like for the in-cluster events.

**AC**
- [ ] There is a working instruction set to demonstrate the concept of in-cluster events.
- [ ] There is documentation to provide alignment with various Kyma/Knative objects and how they are used.

**Comment by anishj0shi** [comment]
As of today, we don't officially support in-cluster eventing. we would think about it in future. For now. to have in-cluster eventing, we'd recommend using the knative broker-trigger model, (But at your own risk)
