### ISSUE TITLE
Sort out installation scripts 

### ISSUE THREAD

**Issue by jakkab** [kyma-project/kyma#4645]
**Description**

Some scripts are not used anymore (extract-installer-version.sh, fetch-components-versions.sh, upload-versions.sh, perhaps more).

Investigate the 'installer' image in `installer.yaml` - we might not need to change it when bumping images.

**Reasons**

Simplifying Kyma dir

**Comment by piotrmsc** [comment]
With installer image removal make sure release process does not break

**Comment by jakkab** [comment]
see also #4798

**Comment by jakkab** [comment]
There's no need to change the image in [installer.yaml](https://github.com/kyma-project/kyma/blob/master/installation/resources/installer.yaml). The file is always seded with correct values.
