### ISSUE TITLE
Api-controller acceptance tests namespace cleanup broken

### ISSUE THREAD

**Issue by Tomasz-Smelcerz-SAP** [kyma-project/kyma#4655]
**Description**
The test first tries to create the namespace, then **defers** namespace delete.
If the namespace already exists, namespace creation fails and the code never reaches the line with deferred namespace deletion.
Once the namespace is not cleaned up properly in the  cluster, it will be never cleaned up, because namespace creation fails with "namespace already exists" error.
This happened in a weekly cluster. It can happen again, it's enough to terminate test pod during the run.

**Expected result**
Namespace cleanup is executed even if namespace creation failed.

**Actual result**

Test fails on namespace creation because the namespace already exists. Namespace is not cleaned up. The same happens on next test execution.

**Steps to reproduce**

Manually create a namespace: api-controller-tests, then execute the test.

**Troubleshooting**
Remove the namespace manually. Not always possible on a cluster (lack of permissions).

**Comment by piotrmsc** [comment]
Unfortunately, pr does not solve the problem, I have left my comment in the merged PR
