### ISSUE TITLE
Prepare backend for changes in binding flow

### ISSUE THREAD

**Issue by derberg** [kyma-project/kyma#466]
Confirm these statements before you submit the issue:

- [x] I have searched open and closed issues for duplicates.
- [x] I have read the contributing guidelines.
---

**Description**

- make sure we have query for ServiceBindingUsages and are able to fetch the following information in the context:
  - name of the usage
  - bound application/resource and its kind
  - name of service binding used by the usage
  - secret of the service binding
  - status type and message
- make sure we have query for ServiceBindings and are able to fetch the following information in the context:
  - name of the binding
  - secret
  - status type and message
  - extra para
  - get also a total number servicebindings that failed (red) or have issue (yellow). This could also be done server side, no need to have such counter logic client side
- make sure we can fetch not only [plan's](https://github.com/openservicebrokerapi/servicebroker/blob/master/spec.md#plan-object) schemas.service_isntance but also **schemas.service_binding**
- make sure we have mutation for ServiceBinding so we are able to create a binding, providing also custom parameters if such are provided
  - response from the server should contain the name of the newly created servicebinding
  - name generation is handled server side
- make sure we have mutation for ServiceBindingUsage so we are able to create a binding usage
  - response from the server should contain the name of the newly created usage
  - name generation is handled server side
  - setting prefix is possible
- make sure we can query for all resources of a given kind defined by UsageKind, in namespace context. So that we can for example get names of all available Deployments, and Functions and more, if defined. So if new UsageKind Configuration is defined, I can query for all its resources and list them. The querying will not be triggered from UI as it is now, that first you specify kind, but query will fetch all kinds and its resources at the same time.

The subscription part to enable UI to display those details using websockets is handled here https://github.com/kyma-project/kyma/issues/269

**Reasons**

- enable UI for development
- split of view of usages vs bindings

**Attachments**

Below attachments are for reference to show what details are needed in the UI

<img width="1102" alt="screen shot 2018-09-04 at 19 21 08" src="https://user-images.githubusercontent.com/6995927/45047051-3fef1f80-b078-11e8-8174-358345249154.png">

<img width="1105" alt="screen shot 2018-09-04 at 19 20 53" src="https://user-images.githubusercontent.com/6995927/45047060-467d9700-b078-11e8-87a9-be33f419fe49.png">

<img width="687" alt="screen shot 2018-09-04 at 19 30 40" src="https://user-images.githubusercontent.com/6995927/45047372-2bf7ed80-b079-11e8-85a5-3c9e17fb7df3.png">

<img width="1115" alt="screen shot 2018-09-04 at 19 32 23" src="https://user-images.githubusercontent.com/6995927/45047430-4c27ac80-b079-11e8-94d4-d3dc1f0ce5ef.png">

<img width="647" alt="screen shot 2018-09-04 at 19 37 18" src="https://user-images.githubusercontent.com/6995927/45047669-015a6480-b07a-11e8-8425-ee06b64d2a09.png">

**Comment by PK85** [comment]
about SBU and SB name generation, consider:
- use prefix which is a service instance name
- k8s generatedName vs docker container default naming

**Comment by piotrmiskiewicz** [comment]
- [x] ServiceBindingUsage query
- [ ] ServiceBindings query, needs metrics (total number of failed etc.) and extra para
- [ ] ServicePlan needs schemas.service_binding
- [ ] mutation for ServiceBinding so we are able to create a binding, providing also **custom parameters** if such are provided, **name generation is handled server side**
- [ ] mutation for ServiceBindingUsage so we are able to create a binding usage, **name generation is handled server side**, **setting prefix is possible**
- [ ] query for all resources (of every UsageKind) in namespace context.

**Comment by piotrmiskiewicz** [comment]
Both SB and SBU can have generated name (if name is not provided in the input). The generated format is: randomword-randomword

**Comment by piotrmiskiewicz** [comment]
Needs to be done:
1. follow up task: remove query usageKindResources (can be done after ui console changes)
2. add displayName (invent name) in bindableResources query
3. Field serviceBindings/serviceBindings should be changed to serviceBindings/Items
4. Add extra binding params to the serviceBinding response
