### ISSUE TITLE
Backup-restore test fails by lack of redis class

### ISSUE THREAD

**Issue by polskikiel** [kyma-project/kyma#4660]
**Description**

Helm broker test fails in the backup tests because of the lack of the redis ClusterServiceClass which is deleted at the beggining of the tests because of the helm install error.

Error reason:
```
Testing bundles injected
Running cleanup
Error: release: "backup-test" not found
FAILED cleaning release. This might be because the release hasn't been installed yet
configmap "testing-bundles-repos" deleted
Testing bundles removed
NAME: backup-test
```

Error message:
```
time="2019-06-25T05:26:35Z" level=info msg="Waiting for redis instance to be ready" test=helm-broker
"status\": {\n \"conditions\": [\n {\n \"type\": \"Ready\",\n \"status\": \"False\",\n \"lastTransitionTime\": \"2019-06-25T05:26:24Z\",\n \"reason\": \"ReferencesNonexistentServiceClass\",\n \"message\": \"The instance references a ClusterServiceClass that does not exist. References a non-existent ClusterServiceClass {ClusterServiceClassExternalName:\\\"redis\\\"} or there is more than one (found: 0)\"\n }\n ]
```

**Expected result**

Redis ClusterServiceClass exist 

**Actual result**

Redis ClusterServiceClass doesn't exist

**Comment by suleymanakbas91** [comment]
The issue's been fixed by #4652. The job is green again: https://status.build.kyma-project.io/view/gcs/kyma-prow-logs/logs/kyma-gke-end-to-end-test-backup-restore/1145920154991857666
