### ISSUE TITLE
AKS documentation out of date

### ISSUE THREAD

**Issue by tehcyx** [kyma-project/kyma#4669]
**Description**

The documentation is out of sync, what I read in the installation part is:

> Install Kyma on an Azure Kubernetes Service (AKS) cluster.
> 
> Prerequisites
> Microsoft Azure
> Kubernetes 1.12 or higher
> Tiller 2.10.0 or higher
> Docker
> Docker Hub account
> az

But then below it says:

> Create an AKS cluster. Run:
> ```
> az aks create \
>   --resource-group $RS_GROUP \
>   --name $CLUSTER_NAME \
>   --node-vm-size "Standard_DS2_v2" \
>   --kubernetes-version 1.10.9 \
>   --enable-addons "monitoring,http_application_routing" \
>   --generate-ssh-keys
> ```

Clearly the kubernetes version is not correct, I've seen in the below linked related issue that the vm-size might also be a problem.

**Related issue**
https://github.com/kyma-project/kyma/issues/3462

**Comment by tomekpapiernik** [comment]
Hi @tehcyx, the AKS flow have been updated recently. Kubernetes version is updated to 1.12 and machine type is `Standard_D4_v3` now. 

See [this](https://kyma-project.io/docs/root/kyma/#installation-install-kyma-on-a-cluster) doc to see the changes.
