### ISSUE TITLE
Additional Environment Variables for Application Connector

### ISSUE THREAD

**Issue by akrausesap** [kyma-project/kyma#4680]
**Description**

During application metadata registration it should be possible to register additional values that should be passed to the service upon binding to the instance through additional environment variables (on top of the `GATEWAY_URL`). 

**Reasons**

This enables to pass sensible defaults for path variables and payloads that should be used. On top of the defaulted headers and query parameters this simplifies API consumption.

**Comment by jasiu001** [comment]
We need more details about what kind of environments should be injected. Contact with frogs and discuss implementation.
