### ISSUE TITLE
Non-deterministic failing test [Azure]

### ISSUE THREAD

**Issue by Demonsthere** [kyma-project/kyma#4719]
**Description**

In some cases the octopus tests fails with an error log like this: 

```
Test summary
Test status: test-api-controller-acceptance - Succeeded
Test status: test-dex-integration - Running
Test status: application-operator-tests - NotYetScheduled
Test status: application-connector-tests - NotYetScheduled
```
This means that the test that is running is blocking the queue -> the pod containing the test is never killed because some process inside did not complete. 
This can happen if the test process is not killed properly, or if the test uses a istio sidecar, and the sidecar process is not killed after the test. 

To handle this we have a kill-switch mechanism for the istio process, which seems to be failing in some cases (race condition?). This seems to be happening more often on Azure than GKE and needs to be investigated. 

**Expected result**
Istio-proxy process is killed after the test is done

**Actual result**
Istio-proxy persists causing a never killed pod and never ending test

**Steps to reproduce**

**Troubleshooting**

**Comment by Demonsthere** [comment]
Interesting find: running `kubectl get pod -n kyma-system -o yaml | grep shareProcessNamespace | wc -l` on GKE produces a positive number, and on AKS it is 0. The flag `shareProcessNamespace` is missing in pod definitions on AKS.

**Comment by Demonsthere** [comment]
This issue requires a non signal based method of killing isito-proxy after the main container is done. This is being developed [here](https://github.com/istio/istio/issues/15041) and [here](https://github.com/istio/istio/pull/15320). We are currently blocked by this.

**Comment by piotrmsc** [comment]
Latest istio release 1.2.3 does not have /quitquitquit handler in pilot-agent yet.

**Comment by Tomasz-Smelcerz-SAP** [comment]
Tests that are not capable of using /quitquitquit endpoint at the moment:

Because there's no `curl` in the image:
- resources/application-connector/charts/connector-service/templates/tests/test.yaml
- resources/assetstore/templates/tests/test.yaml
- resources/core/charts/console-backend-service/templates/tests/test.yaml
- resources/core/charts/kubeless/templates/tests/test.yaml
- resources/dex/templates/tests/test-integration.yaml
- resources/service-catalog/templates/tests/test.yaml

Because of `manager` container (will not work in Azure):
- resources/core/charts/console/templates/test/test.yaml
- resources/core/templates/tests/test-external-solution.yaml
- resources/event-bus/templates/tests/test.yaml
- tests/end-to-end/upgrade/chart/upgrade/templates/pod.yaml

**Comment by Tomasz-Smelcerz-SAP** [comment]
For resources/core/charts/console/templates/test/test.yaml the Dockerfile location is: `https://github.com/kyma-project/console/blob/master/tests/Dockerfile` and it looks like adding curl is very easy.

**Comment by Tomasz-Smelcerz-SAP** [comment]
For `resources/core/templates/tests/test-external-solution.yaml` the Dockerfile location is: `tests/end-to-end/external-solution-integration/Dockerfile`.
This is `FROM alpine:3.10` and it looks like adding curl is very easy.
The problem again is, the entrypoint is defined in the Dockerfile, we can't add curl just by extending a shell command line.

**Comment by colunira** [comment]
For `resources/application-connector/charts/connector-service/templates/tests/test.yaml` the Dockerfile location is: `/tests/connector-service-tests/Dockerfile`
This is `FROM alpine:3.10`. Although no `apk-get` is done adding curl should be easy.

**Comment by Tomasz-Smelcerz-SAP** [comment]
For `resources/event-bus/templates/tests/test.yaml` the Dockerfile location is: `tests/event-bus/e2e-tester/Dockerfile`
This is multi-step Dockerfile, but the final image is `FROM scratch` and the entrypoint is defined directly in Dockerfile, making it harder to combine with curl...

**Comment by colunira** [comment]
For `` the Dockerfile location is `tests/asset-store/Dockerfile`. 
It's from `alpine:3.8`. 
Adding curl should be easy again.

**Comment by Tomasz-Smelcerz-SAP** [comment]
For `tests/end-to-end/upgrade/chart/upgrade/templates/pod.yaml` the Dockerfile location is `tests/end-to-end/upgrade/Dockerfile`. The image contains curl. I am removing manager container, this looks like `done` :)

**Comment by colunira** [comment]
For `resources/core/charts/console-backend-service/templates/tests/test.yaml` the Dockerfile location is: `tests/console-backend-service/Dockerfile`. It's from `alpine:3.8. Adding curl should be easy.

**Comment by Tomasz-Smelcerz-SAP** [comment]
For `resources/service-catalog/templates/tests/test.yaml` the Dockerfile location is:

**Comment by colunira** [comment]
For `resources/core/charts/kubeless/templates/tests/test.yaml` the Dockerfile location is: `tests/kubeless/Dockerfile`. It' from `alpine:3.8`. Adding curl should be easy.

**Comment by colunira** [comment]
For `resources/dex/templates/tests/test-integration.yaml` the Dockerfile location is: `tests/integration/dex/Dockerfile`. It's from `alpine:3.10`. Adding curl should be easy.
