### ISSUE TITLE
Backup/Restore does not work

### ISSUE THREAD

**Issue by suleymanakbas91** [kyma-project/kyma#4725]
**Description**
I follow [this document](https://kyma-project.io/docs/components/backup) to create a backup and then restore from this backup in another cluster. It fails in the restore phase:

```
Errors:
  Velero:     <none>
  Cluster:  error waiting on in-cluster persistentvolume pvc-31b17191-9bf6-11e9-bba3-42010a9c0103: error looking up namespace name for in-cluster PV pvc-31b17191-9bf6-11e9-bba3-42010a9c0103: key claimRef not found
            error waiting on in-cluster persistentvolume pvc-3cc9b527-9bf6-11e9-bba3-42010a9c0103: error looking up namespace name for in-cluster PV pvc-3cc9b527-9bf6-11e9-bba3-42010a9c0103: key claimRef not found
            error waiting on in-cluster persistentvolume pvc-4b94ed1b-9bf6-11e9-bba3-42010a9c0103: error looking up namespace name for in-cluster PV pvc-4b94ed1b-9bf6-11e9-bba3-42010a9c0103: key claimRef not found
            error waiting on in-cluster persistentvolume pvc-62eab38d-9bf6-11e9-bba3-42010a9c0103: error looking up namespace name for in-cluster PV pvc-62eab38d-9bf6-11e9-bba3-42010a9c0103: key claimRef not found
```

The problem is that documentation says: `Restoring a Kyma cluster requires a fresh Kyma installation with the same version you want to restore with`, which already deploys PVCs, and they immediately bind to newly created PVs. Then, Velero also restores the PVs from backup. These PVs from backup do not bind to any of the PVCs because they are already bounded. 

**Expected result**

I can take a backup of my cluster and then I can restore from this backup in another cluster.

**Steps to reproduce**

Follow the document explaining how to create a backup and restore from it: https://kyma-project.io/docs/components/backup

**Comment by a-thaler** [comment]
Will be fixed by https://github.com/kyma-project/kyma/issues/4834

**Comment by suleymanakbas91** [comment]
We changed the way of taking a backup and restoring Kyma. It's already documented and merged. I'm closing this bug as following the documentation leads you to achieve this now.
