### ISSUE TITLE
Adjust domain of idppresets.ui to 'kyma-project.io

### ISSUE THREAD

**Issue by piotrmsc** [kyma-project/kyma#473]
Confirm these statements before you submit the issue:

- [ ] I have searched open and closed issues for duplicates.
- [ ] I have read the contributing guidelines.
---

**Description**

The CRD 'idppresets.ui.kyma.cx' is using kyma.cx as domain (group). As kyma.cx was intended to be used for the commercialization aspects of kyma.
The official domain of kyma is kyma-project.io now, so all CRDs should get adjusted to it.

**Reasons**

The official domain of kyma is kyma-project.io now, so all CRDs should get adjusted to it.

- group name is adjusted in the CRD: idppresets.authentication.kyma-project.io
- all usage is adjusted
- ~~documentation and examples are adjusted~~

**Attachments**

**Comment by pbochynski** [comment]
Please rename the api group to idppresets.authentication.kyma-project.io
