### ISSUE TITLE
DNS fails to resolve xip.io addresses occasionally

### ISSUE THREAD

**Issue by m00g3n** [kyma-project/kyma#4733]
**Description**

DNS fails to resolve xip.io addresses occasionally

**Expected result**

xip.io addresses should be resolved

**Actual result**

```
Err: {
    Err: "no such host",
    Name: "minio.34.90.190.186.xip.io",
    Server: "10.15.240.10:53",
    IsTimeout: false,
    IsTemporary: false,
},
```

or

```
Request POST https://console-backend.34.90.212.109.xip.io/graphql failed with message : net::ERR_NAME_NOT_RESOLVED
```

**Comment by kubadz** [comment]
Hi. xip.io sometimes has a downtime. Please note that it is a free solution hosted by some company to ease the process of development for them and for others.
That said, I wouldn't recommend using it on "production". Instead, you should probably use your own domain. If that solution is not feasible for you, I would recommend making your system more resilient to such problems related to external services e.g. by increasing the number of retries for operations your application perform.
