### ISSUE TITLE
Move PersistentVolumeClaim from chart to migration tool

### ISSUE THREAD

**Issue by jasiu001** [kyma-project/kyma#4740]
**Description**
Migration tool used during upgrade ServiceCatalog from version 0.2.x ("apiserver version") to 0.3.x ("webhook version") requires PersistentVolumeClaim to store data between versions. 
PVC is not removed after upgrade in case of user wants to restore data from it.

For now PVC is create by helm process and is created always no matter migration will launch or not (decision about launch migration process is made inside migration tool) it causes errors when upgrade is made even between versions 0.3.x.
`Pre-migration` jobs gets error about exists already PVC.

**Solution**
Move create PVC to migration tool code. Delete action is not necessary, because PVC after migration should be removed by user manually what is describe in documentation. 

**Additional problem** *
During upgrade SC chart between version 0.3.x, pods `webhook` and `controller manager` are rebuild, they shouldn't be, check why it occurs.

**AC**
- move creating PVC to migration tool
- add RBAC for creating PVC to chart
- remove PVC from chart
- bump migration tool image
- remove PVC from Kyma chart
- find solution for *"Additional problem"

**Comment by mszostok** [comment]
please provide comment for **"Additional problem"**

**Comment by jasiu001** [comment]
The cause why `webhook` pod is reset is field `releaseRevision: "{{ .Release.Revision }}"` in `spec.template.metadata.label` which is increase in every update process, the reason of this functionality is mounting new certs (from `service-catalog-webhook-cert` secret) generating every update.
