### ISSUE TITLE
Improve api controller acceptance tests

### ISSUE THREAD

**Issue by piotrmsc** [kyma-project/kyma#475]
Confirm these statements before you submit the issue:

- [ ] I have searched open and closed issues for duplicates.
- [ ] I have read the contributing guidelines.
---

**Description**

Currently, api-controller tests are sometimes failing because of 503 responses returned from the request made to created test app in the first step of our tests. It happens when a cluster is under heavy load and is not able to create the pod quickly. In that case the logs are not clear.

We should improve our tests perhaps by waiting for the pod of the tested app to be running before executing rest of the test cases.
**Reasons**

**Attachments**

**Comment by sjanota** [comment]
The plan is to make those tests lighter and do not use real app when its not necessary. We will split tests into two parts:
1. Integration scenarios which are testing interiors of api-controller and doesn't need to start real pod. They will check if resulting virtual service and policy exists and contains all expected data.

2. e2e scenarios will create real app and check two scenarios:
* api works with auth
* api works without auth

We can further bulletproof second group by checking if pod is alive.
