### ISSUE TITLE
Scalability of KNATIVE Publisher

### ISSUE THREAD

**Issue by akrausesap** [kyma-project/kyma#4754]
**Description**

Dear Colleagues,

for a custom event Gateway I was performing some scalability tests. During these tests I found out that with Kyma 1.2.2 standard setup the maximum event inbound rate is around 5-10 per second. After that the `event-bus-publish-knative-*-*` pods start crashing with OOM errors.

![2019-07-03_14-07-52](https://user-images.githubusercontent.com/40229965/60590394-27d15500-9d9c-11e9-87fc-72aa56c90f8f.png)

Should you require the entire test setup and further details please let me know.

Regards

Andreas

**Expected result**

Higher sustained throughput

**Actual result**

Throughput plateaus at 5-10 events per second

**Steps to reproduce**

Initiate loadtest for the http://event-bus-publish.kyma-system.svc.cluster.local:8080/v1/events endpoint.

**Troubleshooting**

N/A

**Comment by abbi-gaurav** [comment]
Did some quick testing today and it seems to point out that the publish and nats-dispatcher might have a memory leak that could be contributing to the problem at hand.

My test scenario was pretty simple.

**1st run**
request per second = 10 with a concurrency of 10. It failed with OOM after around 30 minutes.

**2nd run**
request per second = 8 with a concurrency of 8. The memory build up keeps on happening. I stopped after around 25 minutes to see if the GC cleans up. a very little memory was released.

Here are the snapshots.

Publish app which points to a memory leak.
![Screenshot 2019-07-10 at 17 20 26](https://user-images.githubusercontent.com/4436741/60981957-959af500-a337-11e9-9906-163dce100100.png)

Nats dispatcher.
The memory footprint is small but there is a continuous build up.
![Screenshot 2019-07-10 at 17 21 22](https://user-images.githubusercontent.com/4436741/60982056-bb27fe80-a337-11e9-8532-98362a83dc66.png)

Event service
Memory footprint is really small. Whatever buildup happened during the run was released.
![Screenshot 2019-07-10 at 17 21 11](https://user-images.githubusercontent.com/4436741/60982158-e3176200-a337-11e9-94c2-d4f844c8fc9a.png)

**Comment by abbi-gaurav** [comment]
I used [npm package loadtest](https://www.npmjs.com/package/loadtest) for simulating the load. It was the same originally used by @akrausesap (thanks for that).

**Comment by montaro** [comment]
The problem in the `knative-lib`, specifically in the `sendMessage()` where we actually publish a message to a knative channel, we used to create/initialize a new HTTP Client per message and we never close the Idle connections.
In my solution I created a singleton HTTP client per application and close the idle connections after sending the message.
Now, sending `1K` requests with concurrency factor = `10` happens with memory overhead only `3MB`

**Comment by tricky42** [comment]
It would be great if we validate the change with the same load script used by @abbi-gaurav. This might be now a bit overhead, but in general it would be good practice as it documents nicely and visually the fix / improvement. Especially as @abbi-gaurav also found a build up in the NATS dispatcher, which havent been address / investigated, or?
