### ISSUE TITLE
Velero does not get installed while installing Kyma 

### ISSUE THREAD

**Issue by suleymanakbas91** [kyma-project/kyma#4755]
**Description**

Even though I install a full version of Kyma on GKE, Velero does not get installed. 

**Expected result**

Velero is installed on the cluster for the backups.

**Steps to reproduce**

Install Kyma 1.2.2 on GKE following the installation guide. Check for Velero Pod.

**Comment by a-thaler** [comment]
Will be fixed by https://github.com/kyma-project/kyma/issues/4835
