### ISSUE TITLE
Forbid deletion of services which have ServiceInstance

### ISSUE THREAD

**Issue by djumalin** [kyma-project/kyma#4777]
**Description**

Deletion of of services which have ServiceInstance via /metadata/services leads to instability.
You will not be able to delete namespace from kyma console

**Reasons**

Reason is finalizer which cannot be fulfilled: ServiceInstance will have invalid link to ServiceClass.

Kyma 1.2

I think it make sence to forbit deletion of services which are used in ServiceInstaces in application-connector api.

**Comment by janmedrek** [comment]
The work is continued in the epic: #4639
