### ISSUE TITLE
Remove existing GCP Service Broker addon

### ISSUE THREAD

**Issue by PK85** [kyma-project/kyma#4782]
**AC**
- remove GCP Service Broker addon from bundles repository
- do not remove kyma-project.io documentation cause that one will be updated by issue: https://github.com/kyma-project/bundles/issues/94
- remove the gcp-broker-provider tool: https://github.com/kyma-project/kyma/tree/master/tools/gcp-broker-provider
- mention the fact in the release notes (pass to PK)
  - link to notification from Google
  - mention, that before upgrade to new kyma version, consider cleanup of SB and SI from GCP SB
    - if already upgarded, then we can add short documentation abbout how to cleanup SI and SB (of course without deleting from GCP itself)

**Comment by piotrmiskiewicz** [comment]
https://cloud.google.com/kubernetes-engine/docs/concepts/google-cloud-platform-service-broker

**Comment by piotrmiskiewicz** [comment]
### Removed Google Cloud Platform Service Broker addon.

Google Cloud Platform Service Broker addon is removed in favour of *GCP Config Connector*.

(reason and the link) 
You can still manage existing GCP service instances using Service Catalog until November 5, 2019. On and after that time, you will be able to manage instances using Google Cloud Platform Console.
Consider cleaning up not needed GCP service bindings, service instances and removal Google Cloud Platform Service Broker instances.
If you need a new instance of GCP service, please provision *GCP Config Connector* and use its service classes.

Please note that the charges incurred by the remaining resources created through the Google Cloud Platform Service Broker will continue to accrue.
