### ISSUE TITLE
Confusing architecture documentation for tracing

### ISSUE THREAD

**Issue by pkosiec** [kyma-project/kyma#4790]
**Description**

Tracing architecture in Kyma is quite confusing. Jaeger is backward-compatible with Zipkin. On our architecture diagram (https://kyma-project.io/docs/components/tracing#architecture-architecture) we can see "Zipkin Kubernetes Service", which apparently is a service backed with Jaeger pod.

There is also the following section:

> **Store traces**
> Traces are stored in Jaeger in the following way:
> 1. A Kyma user configures the application to propagate the correct HTTP headers for the outbound calls.
> 2. Envoy passes the trace details to the Zipkin Kubernetes service. This service acts as a facade receiving the trace and span details.
> 3. The Zipkin service forwards the tracing information to Jaeger Deployment, allowing it to process them.

It should be clarified, what exactly is Zipkin Kubernetes Service.

**Comment by a-thaler** [comment]
Thanks for pointing it out, it must be fixed.

Here are the topics I see to improve:
**Diagram**
- Add persistence used by jaeger deployment
- Make components more consistent in what they represent. Add stereotypes everywhere, add "istio-proxy" to "envoy"
- Improve the kcproxy flow, currently it is visualized in a confusing way. At the end it will call dex for token verification, not the istio-gateway
- double check the service names

**Request Traces**
- rename to **Query Traces**
- update diagram and add kcproxy
- update description with clear focus. kcproxy flow, usage of service

**Store Traces**
- Rename to **Collect Traces**
- Improve description and make clear that the "Zipkin" service is a service of the jaeger chart

**Search traces by tags**
Nothing to do with architecture, move to different section

**Comment by a-thaler** [comment]
We improved and corrected the documentation
