### ISSUE TITLE
Delete local installation scripts

### ISSUE THREAD

**Issue by a-thaler** [kyma-project/kyma#4798]
**Description**
As the scripts for local kyma installation are deprecated for a while it is time to clean them up.
Search for any usage in kyma and test-infra repo and replace usage by CLI.
Delete the scripts, mainly: run.sh, minikube.sh, installer.sh

**Reasons**
Clean code and consistency

**Comment by clebs** [comment]
This issue will be closed and instead it will be split in 2 phases:
1. Replace bash scripts for Kyma CLI in one Prow job: #5182
2. Migrate all Prow jobs to Kyma CLI and delete unused scripts: #5183
