### ISSUE TITLE
Application Connector should support  adding additional headers and query parameters to OAuth token calls

### ISSUE THREAD

**Issue by akgalwas** [kyma-project/kyma#4799]
**Description**

Additional headers and query parameters are supported for target API calls and specification fetching. Additional headers and query parameters should be supported for OAuth calls as well.

[Here](https://github.com/kyma-project/kyma/issues/6445) is a follow up for the Compass Runtime Agent part of this issue

**Acceptance Criteria**

- OAuth calls support additional headers and query parameters if provided
- Additional headers and query parameters for OAuth calls are documented in Kyma Docs

**Comment by jcawley5** [comment]
Have a use case this is blocking.  Any updates on the progress of the request?

**Comment by janmedrek** [comment]
Hello @jcawley5, we have included this ticket in the scope the next release - you can expect it to be present in 1.9. :)
