### ISSUE TITLE
Function controller integration proposal

### ISSUE THREAD

**Issue by Abd4llA** [kyma-project/kyma#4801]
**Description**

A proposal document for integrating the new function controller needs to be created that clearly gives a design of integrating Kyma Function controller as an experimental module which replaces Kubeless when installed. It should also clearly lists needed changes to all different Kyma components.

**Reasons**
- Providing a clear picture of the Function controller integration.
- Helping in better planning different changes related to different Kyma components.

**Note**
- The proposal should provide a solution for a clear migration path

**AC**
- The proposal should clearly address the UI and GraphQL required changes.
- The proposal should give an answer to whether we can have co-existing Kubeless and Knative Serving functions while the module is experimental
- The proposal clearly states problems and recommendations to achieve having a production ready Kyma with a Knative Serving only functions.
- The proposal will state next suggestion work.

**Comment by k15r** [comment]
By "replaces" you mean:
either install kubeless or install the new knative based function controller?

If so, then this will require us to make kubeless a module. Currently kubeless is installed as part of the core.
