### ISSUE TITLE
Migrate Knative Eventing to use v0.3 of CloudEvents

### ISSUE THREAD

**Issue by Abd4llA** [kyma-project/kyma#4808]
**Description**
With CloudEvents v0.3 officially out, we need to update the usage of CloudEvents go SDK in Knative eventing to use v0.3. 

Knative issue: [Eventing#1471](https://github.com/knative/eventing/issues/1471)

**Comment by anishj0shi** [comment]
#https://github.com/knative/eventing/pull/1535 Raise PR with proposed Changes

**Comment by anishj0shi** [comment]
#https://github.com/knative/test-infra/issues/1137 A bug in knative test-infra reported which seems to be a problem in running the e2e-test script, this scripts throws while creating test cluster on GKE

**Comment by anishj0shi** [comment]
https://github.com/knative/eventing/pull/1535 PR Merged
