### ISSUE TITLE
Update Knative docs due to eventing channel provisioners deprecation in release 0.7

### ISSUE THREAD

**Issue by Abd4llA** [kyma-project/kyma#4811]
**Description**
Due to the deprecation of provisioner in Knative Eventing 0.7, a couple of doc pages need to be updated.

Knative issue: [Eventing#1453](https://github.com/knative/eventing/issues/1453)

**Comment by nachtmaar** [comment]
Knative PRs: 
- https://github.com/knative/docs/pull/1629
- https://github.com/knative/eventing/pull/1605/files
