### ISSUE TITLE
Implement knative function sizes

### ISSUE THREAD

**Issue by nachtmaar** [kyma-project/kyma#4823]
**Description**

Implement the different function sizes such as `S, M, L, XL`. The current knative controller does not treat them differently.

**Reasons**
The kubeless function controller treats the functions differently in terms of [cpu and memory resources](https://github.com/kyma-project/kyma/blob/master/tests/perf/prerequisites/serverless/function-size-s.yaml#L17) as well as [autoscaling](https://github.com/kyma-project/kyma/blob/master/tests/perf/prerequisites/serverless/function-size-s.yaml#L40).

**Attachments**

Follow up of https://github.com/kyma-incubator/runtime/pull/7

**Comment by k15r** [comment]
It has been decided that users will be able to apply knative-serving autoscaling annotations onto the function to achieve this functionality
