### ISSUE TITLE
Perform function controller validation in webhook

### ISSUE THREAD

**Issue by nachtmaar** [kyma-project/kyma#4826]
**Description**

- Perform validation logic from function controller also in webhook.
- Moreover, only get the function controller's config map when necessary.

**Reasons**

Performing the function controller validation logic in webhook improves user experience because the webhook provides user feedback if there is any problem. The controller in contrast will only log errors which cannot be seen until the user does a `kubectl logs ...` which is actually not good user feedback.

The function controller does a couple of things for each Reconcile request which is unnecessary:
- `r.getFunctionControllerConfiguration(fnConfig)` // get config map => improvement: do not get on each request, e.g. via watch on config map
- `runtimeUtil.New(fnConfig)` // validates config map -> improvement: perform validation also in webhook

**Attachments**

Follow up of https://github.com/kyma-incubator/runtime/pull/7

**Comment by rakesh-garimella** [comment]
fixed via: #5327
