### ISSUE TITLE
Validate function runtimes from ConfigMap

### ISSUE THREAD

**Issue by nachtmaar** [kyma-project/kyma#4828]
**Description**
Validate function runtimes from ConfigMap instead of using hardcoded values.

**Reasons**
The supported function runtimes are currently hardcoded in the [webhook](https://github.com/kyma-incubator/runtime/blob/master/pkg/webhook/default_server/function/mutating/function_create_handler.go#L34). The function controller however takes the supported runtimes from a config map (see [here](https://github.com/kyma-incubator/runtime/blob/master/pkg/utils/controller_utils.go#L37))

The webhook should get the supported runtimes from the ConfigMap too.

**Attachments**

[Mutation of Function Runtime](https://github.com/kyma-incubator/runtime/blob/master/pkg/webhook/default_server/function/mutating/function_create_handler.go#L61)
[Validation of Function Runtime](https://github.com/kyma-incubator/runtime/blob/master/pkg/webhook/default_server/function/mutating/function_create_handler.go#L87)

**Comment by rakesh-garimella** [comment]
Fixed via: #5327
