### ISSUE TITLE
We should be able to identify namespaces with lambdas in Grafana

### ISSUE THREAD

**Issue by rakesh-garimella** [kyma-project/kyma#4844]
**Description**

Since removal of `env` label we dont know which namespaces have lambdas deployed. There should be a way to identify them like adding a label to the namespace.
**Reasons**

When showing lambdas on Grafana dashboards we should know which namespaces have lambdas in them. This would enable developer to easily find dashboard for his/her lambda

Also we should take into account for users who are deploying lambdas from cli into different namespaces.

Some hints:

May be we can show non-system namespaces.  But then we also show non-system namespaces with no lambdas. IMO we should show only namespaces with lambdas present

**Comment by a-thaler** [comment]
already solved, the lambda dashboard is showing namespaces with lambdas only
