### ISSUE TITLE
Remove load-test in favor of lambda performance test

### ISSUE THREAD

**Issue by nachtmaar** [kyma-project/kyma#4850]
**Description**

Remove [load-test](https://github.com/kyma-project/kyma/tree/master/tools/load-test) in favor of [lambda performance test](https://github.com/kyma-project/kyma/tree/master/tests/perf/prerequisites/serverless).

There is a `load-test`  which checks that the horizontal pod autoscaler of lambdas works. The test is reporting to a Slack channel.

We recently introduced performance tests. There is a performance test which tests the performance of lambdas under high CPU load. The test is increasing the number of requests to the lambda over time and is also using a horizontal pod autoscaler. So it does the same thing as the `load-test`.
Moreover, we plan to add assertions to performance-tests to ensure that performance is not dropping.
The performance test results are posted to the `kyma-perf-results` channel

Items:
- remove folder from kyma project
- remove prow job
- remove slack schannel
- check for any leftovers in GCP project

**Reasons**
Consistency, Efforts, Money

**Comment by a-thaler** [comment]
Removed code from test-infra and kyma, archived slack channel
