### ISSUE TITLE
Memory and CPU consumption optimization in Service Management area

### ISSUE THREAD

**Issue by PK85** [kyma-project/kyma#4859]
**AC**
- check all service management components what CPU and memory is assigned
- adjust to lower values if possible

**Comment by jasiu001** [comment]
### Analysis
Below analysis shows memory and CPU usage statistics for three components. Statistics are made for unloaded work and with the simulation of the network traffic. Network traffic simulation were made on minikube.

**Helm broker**
Helm broker component uses two containers: broker and addons configuration controller.
Statistics with no any traffic come from nightly cluster (period time 5h)

Memory (sterile condition):
<img width="1809" alt="helm-broker-container-memory" src="https://user-images.githubusercontent.com/10399074/61858911-589e3900-aec7-11e9-9f4f-f88c0270572d.png">

CPU (sterile condition):
<img width="1815" alt="helm-broker-container-cpu" src="https://user-images.githubusercontent.com/10399074/61858947-7075bd00-aec7-11e9-98e6-22bafe1c884b.png">

To simulate traffic, about 24 ServiceInstance were creted plus some Bindings in time period less than 10 min

Memory:
<img width="1814" alt="broker-memory" src="https://user-images.githubusercontent.com/10399074/61859108-c185b100-aec7-11e9-8df4-c86422081ce3.png">
CPU:
<img width="1812" alt="broker-cpu" src="https://user-images.githubusercontent.com/10399074/61859130-ce0a0980-aec7-11e9-8ac0-c03f48b2555b.png">
