### ISSUE TITLE
Evaluate Kubeless components and tests resources consumptions

### ISSUE THREAD

**Issue by Abd4llA** [kyma-project/kyma#4866]
**Description**

In order to reduce the overall resources consumption of Kyma, we need to evaluate the resources consumption of Kubless components and Kubeless acceptance tests. 

**Note**
- Reach out to @a-thaler and/or @hisarbalik to align how to evaluate the resources and on-going situation. 
- Overall set release theme was that provisioning of a Kyma cluster + running acceptance tests should succeed within 18GB Memory and 3 VCPUs.

**AC**
- Evaluate all Kubeless components memory and CPU consumptions. 
- Evaluate all Kubeless acceptance tests memory and CPU consumptions
- If not possible, then reasons needs to be documented. 
- Evaluate the requests for the charts.
- If there are quick fixes then consider creating a PR or creating separate issues for big ones.
- Document findings per component and test.

**Comment by sayanh** [comment]
https://github.com/kyma-project/kyma/issues/4862

this for KPI definition
https://github.com/kyma-project/kyma/issues/4863
this is the resource optimization epic
https://github.com/kyma-project/kyma/issues/4865
and this is the test creation to measure KPI

**Comment by anishj0shi** [comment]
## Kubeless Resource Configuration
Currently kubeless helm resources do not define a resource configuration for kubeless components   Hence, there's no *resource* parameter introduced for *kubeless-function-controller*. But, as the kubeless-function-controller is deployed in **kyma-system** namespace, the **kyma-default** *LimitRange* kicks in and sets Memory Requests to *32Mi* and limits to *96Mi*

### Resource Consumption Study for kyma Serverless Components

**Comment by anishj0shi** [comment]
Hi @Abd4llA , Evaluation study for our serverless components can be found here https://github.com/kyma-project/kyma/issues/4866#issuecomment-523495500, There's no PR for tweaking resource consumption as the all the Custom Resources for our components are technically thirdy-party, let me know what do think about it.

**Comment by rakesh-garimella** [comment]
Fine by me.
