### ISSUE TITLE
Installation deadlock with istio sidecar injection

### ISSUE THREAD

**Issue by Fabian-K** [kyma-project/kyma#4870]
**Description**

I´m trying to install kyma 1.2.2 on a k8s cluster and the installation deadlocks during the installation of the istio component. The pods in the istio-system namespace don´t start as they are waiting for the istio-sidecar-injector to be present. Because also the istio-sidecar-injector itself is not starting -> the entire installation does not continue.

```
Events:
  Type     Reason        Age                   From                   Message
  ----     ------        ----                  ----                   -------
  Warning  FailedCreate  3m11s (x18 over 14m)  replicaset-controller  Error creating: Internal error occurred: failed calling admission webhook "sidecar-injector.istio.io": Post https://istio-sidecar-injector.istio-system.svc:443/inject?timeout=30s: no endpoints available for service "istio-sidecar-injector"
C02V26NQHTD6:kyma-at-kind d053397$ 
``` 

I can only continue the installation by manually labeling the istio-system namespace with `istio-injection=disabled`. As a result the sidecar-injector pod is created and the installation continues as expected. 

For the installation, I somehow follow https://kyma-project.io/docs/root/kyma/#installation-use-your-own-domain with the following adjustments:
- the certificate is not issued by letsencrypt (as it is issued by a different ca). Therefore I manually create a configmap with the overwrites for `global.domainName`, `global.tlsCrt` and `global.tlsKey`.

I use the following installation script:
```
export KYMA_VERSION=1.2.2
kubectl apply -f https://raw.githubusercontent.com/kyma-project/kyma/$KYMA_VERSION/installation/resources/tiller.yaml
kubectl create namespace kyma-installer
kubectl apply -f owndomain-overrides.yaml
kubectl apply -f https://github.com/kyma-project/kyma/releases/download/$KYMA_VERSION/kyma-installer-cluster.yaml

while true; do \
  kubectl -n default get installation/kyma-installation -o jsonpath="{'Status: '}{.status.state}{', description: '}{.status.description}"; echo; \
  sleep 5; \
done
```

owndomain-overrides.yaml
```
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    installer: overrides
  name: owndomain-overrides
  namespace: kyma-installer
data:
  global.domainName: <domain>
  global.tlsCrt: <encoded crt>
  global.tlsKey: <encoded key>
```

I was able to reproduce this issue now several times (always using new clusters). The cluster is onpremise, running k8s v1.12.7
```
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.9", GitCommit:"e09f5c40b55c91f681a46ee17f9bc447eeacee57", GitTreeState:"clean", BuildDate:"2019-05-27T16:08:57Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.7", GitCommit:"6f482974b76db3f1e0f5d24605a9d1d38fad9a2b", GitTreeState:"clean", BuildDate:"2019-03-25T02:41:57Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}
```

Thank you!

**Comment by Demonsthere** [comment]
Hello there,
istio-system should be labeled automatically by a job `kyma-ns-label` running in `istio-system` namespace. Can you check the status/logs from this job?

**Comment by Fabian-K** [comment]
That has the same issue, the pod is not created.
```
Name:           kyma-ns-label
Namespace:      istio-system
Selector:       controller-uid=e7bc7822-a31f-11e9-8bd8-428a61100bca
Labels:         controller-uid=e7bc7822-a31f-11e9-8bd8-428a61100bca
                job-name=kyma-ns-label
Annotations:    <none>
Parallelism:    1
Completions:    1
Pods Statuses:  0 Running / 0 Succeeded / 0 Failed
Pod Template:
  Labels:           controller-uid=e7bc7822-a31f-11e9-8bd8-428a61100bca
                    job-name=kyma-ns-label
  Service Account:  kyma-ns-label
  Containers:
   kyma-ns-label:
    Image:      eu.gcr.io/kyma-project/test-infra/alpine-kubectl:v20190325-ff66a3a
    Port:       <none>
    Host Port:  <none>
    Command:
      /bin/bash
      -c
      set -e
      echo "---> Setting label to istio-system"
      kubectl label namespace "istio-system" "istio-injection=disabled" --overwrite
      echo "---> Setting label to kube-system"
      kubectl label namespace "kube-system" "istio-injection=disabled" --overwrite
      
    Environment:  <none>
    Mounts:       <none>
  Volumes:        <none>
Events:
  Type     Reason        Age                    From            Message
  ----     ------        ----                   ----            -------
  Warning  FailedCreate  3m13s (x178 over 17h)  job-controller  Error creating: Internal error occurred: failed calling admission webhook "sidecar-injector.istio.io": Post https://istio-sidecar-injector.istio-system.svc:443/inject?timeout=30s: no endpoints available for service "istio-sidecar-injector"
```

**Comment by Demonsthere** [comment]
Hmm, it seems like you got a weird race condition here, and the Hook is deployed prior to the job which should label the namespace to not to use sidecars. Can you try adding the  istio annotation:

```yaml
annotations:
        sidecar.istio.io/inject: "false"
```

To this job definition? This should disable sidecar injector for this job, and allow it to label namespaces automatically. 
Still I would like to know why this situation keeps happening to you, as we didn't have such a problem before. Do you have some custom kubernetes configuration in place?

**Comment by Demonsthere** [comment]
By the way, if you need some more on-hand help with this or another issue, please come by our [Slack channel](https://join.slack.com/t/kyma-community/shared_invite/enQtNDAwNzE4Mjk2NDE3LTJhOTlmZjM5YzkwNmEzNmY3ZjE2MTU2OTMxOGE4ZDM0MmU4ZWRkZGJiODgzNmRmMTYxMDYwNjZiMDAwMTA2OWM)

**Comment by Demonsthere** [comment]
Error was already present in [istio before](https://github.com/istio/istio/issues/8182)
Istio guide for [injector verfication](https://istio.io/docs/ops/setup/webhook/#verify-dynamic-admission-webhook-prerequisites)
I have checked that the problem doesn't seem to be network relevant, and manual namespace labelling fixes the problem. This makes us think that there is a difference in k8s config between GKE and Openstack, that causes this. 
Webhook priority handling may be a culprit.

**Comment by Demonsthere** [comment]
We have moved the labeling to istio-init, which runs before istio itself. This should result in the namespaces being labeled before istio is even processed in helm, and avoid such deadlock situations.
