### ISSUE TITLE
Add an observability document under Kyma documentation

### ISSUE THREAD

**Issue by kazydek** [kyma-project/kyma#4882]
**Description**

Add an observability document under Kyma to describe in general how **Monitoring**, **Tracing**, and **Logging** works and is related to one another in Kyma. 
This can be a **Details** type of doc with an overview, diagram, and links to specific observability documents.

**Reasons**

Have a generic observability doc in Kyma doc with links to specific topics.

**Related issue(s)**

**Comment by bszwarc** [comment]
Still valid.

**Comment by a-thaler** [comment]
I don't see an urgent need for that at the moment.
