### ISSUE TITLE
Create a Dev/Prod mode option which configures tracing/logging accordingly

### ISSUE THREAD

**Issue by jcawley5** [kyma-project/kyma#4894]
Each application (jaeger/loki/prometheus etc ) configuration needs to be independently edited to enabled detailed tracing for development or performance optimization for production.

It would be great to have configuration switch that toggles the modes based on a best practice editable configuration.  Maybe the dev configuration should auto expire in some amount of time.

**Comment by a-thaler** [comment]
Good idea. Do you have some specific settings in mind which you need to configure always, like the traceSampling rate for istio?
I think we should introduce that in general, so that every component is supporting default configuration based on profiles.

**Comment by jcawley5** [comment]
I do not, it was the pilot trace sampling that inspired the thought.

**Comment by derberg** [comment]
the only setting that is the most important now is the `traceSampling` as it is causing a headache when you work on development and work includes tracing. Knowledge that you need to change `traceSampling` is known to few people only.

**Comment by a-thaler** [comment]
We already described in the documentation how to adjust the trace sampling rate. Enabling it by default might be nice for a real dev setup but we currently don't have such profile. We have production, default, local and soon evaluation. I think it should not be enabled in "default" as people tend to use it for non-dev scenarios as well. The local profile does not include tracing.
So maybe it is good enough for now. I will add another section on how to trace requests on demand by setting the sampled trace header.

**Comment by skhalash** [comment]
PR: https://github.com/kyma-project/kyma/pull/10091
