### ISSUE TITLE
Events are not dispatched if the lambda is exposed with enabled authentication

### ISSUE THREAD

**Issue by joek** [kyma-project/kyma#4908]
**Description**
Events are not dispatched if the lambda is exposed with enabled authentication. This is especially a problem if I like to use the Test tap in lambda UI.

**Expected result**

I can test lambdas in a secure way with working subscriptions.

**Actual result**

I can not test lambdas as I would need to expose them unauthenticated if I need working subscriptions at the same time.

**Steps to reproduce**

1. Expose Lambda using authentication
2. Subscribe to events
3. Check natss-dispatcher logs and see 401 errors on delivery.

**Troubleshooting**

Remove API Authentication and it is working.

**Comment by kwiatekus** [comment]
I dont thing its UI related issue.
@Abd4llA could you validate ?

**Comment by akrausesap** [comment]
this is caused by the fact that exposing lambda with authentication creates an istio authentication policy: [policies.authentication.istio.io](https://istio.io/docs/reference/config/security/istio.authentication.v1alpha1/)

```
apiVersion: authentication.istio.io/v1alpha1
kind: Policy
metadata:
  creationTimestamp: "2020-02-04T09:30:49Z"
  generation: 1
  labels:
    apiName: order
    apiNamespace: moments
    apiUid: 1cf5bd39-472d-11ea-9143-42010a9a0043
    apiVersion: "3031380"
    createdBy: api-controller
  name: order
  namespace: moments
  resourceVersion: "3031389"
  selfLink: /apis/authentication.istio.io/v1alpha1/namespaces/moments/policies/order
  uid: 07715c3c-4731-11ea-9143-42010a9a0043
spec:
  origins:
  - jwt:
      issuer: https://dex.compass-ak.cluster.extend.cx.cloud.sap
      jwksUri: http://dex-service.kyma-system.svc.cluster.local:5556/keys
  peers:
  - mtls: {}
  principalBinding: USE_ORIGIN
  targets:
  - name: order
```

This policy specified the requirement for jwt based authentication which the natss-dispatcher won't supply. Hence an unauthenticated response:

```
{"level":"info","ts":"2020-02-04T09:51:30.202Z","logger":"controller","caller":"channel/message_dispatcher.go:116","msg":"Dispatching message to http://order.moments:8080/"}
{"level":"error","ts":"2020-02-04T09:51:30.224Z","logger":"controller","caller":"dispatcher/dispatcher.go:276","msg":"Failed to dispatch message: ","error":"Unable to complete request unexpected HTTP response, expected 2xx, got 401","stacktrace":"knative.dev/eventing-contrib/natss/pkg/dispatcher.(*SubscriptionsSupervisor).subscribe.func1\n\t/home/prow/go/src/knative.dev/eventing-contrib/natss/pkg/dispatcher/dispatcher.go:276\nknative.dev/eventing-contrib/vendor/github.com/nats-io/go-nats-streaming.(*conn).processMsg\n\t/home/prow/go/src/knative.dev/eventing-contrib/vendor/github.com/nats-io/go-nats-streaming/stan.go:824\nknative.dev/eventing-contrib/vendor/github.com/nats-io/go-nats.(*Conn).waitForMsgs\n\t/home/prow/go/src/knative.dev/eventing-contrib/vendor/github.com/nats-io/go-nats/nats.go:2047"}
{"level":"info","ts":"2020-02-04T09:51:33.867Z","logger":"controller","caller":"channel/message_dispatcher.go:116","msg":"Dispatching message to http://order.moments:8080/"}
```

**Comment by michal-hudy** [comment]
As far as I know, events are not going through the exposed endpoints. Communication is internal. If the issue is still valid, please reopen it.
