### ISSUE TITLE
Monitoring for velero

### ISSUE THREAD

**Issue by a-thaler** [kyma-project/kyma#4916]
**Description**
Velero brings already a way to activate metrics and that should be enabled.

- Enable custom metrics of velero and the related service monitor.
- Check the velero documentation for a related grafana dashboard to be added to the monitoring chart.
- Check the velero documentation for meaningful alert rules and ad them if appropriate

**Reasons**
Detect unhealthy velero installations before customer will detect it

**Comment by suleymanakbas91** [comment]
I see that we already have a Grafana dashboard for Velero: https://github.com/kyma-project/kyma/blob/master/resources/monitoring/charts/grafana/dashboards/velero.json

**Comment by suleymanakbas91** [comment]
Metrics are already enabled by this [PR](https://github.com/kyma-project/kyma/pull/5245).
