### ISSUE TITLE
Documentation leftovers for velero

### ISSUE THREAD

**Issue by a-thaler** [kyma-project/kyma#4968]
**Description**
Add a troubleshooting section for restore documentation explaining how to deal with changed DNS/PublicIP scenario and explaining current velero bug workarounds

Add section to restore guide explaining the cleanup of the velero instance used for restore.

Move the "Install velero" section under the "Backup a Kyma cluster" section as it is not required for a restore

**Reasons**
It is missing

**Comment by bszwarc** [comment]
I would keep `Install Velero` doc as a separate tutorial - it would be at the end of our documentation, so we would have:

- Overview 
- Details 
  - Create backup 
  - Restore backup 
- Configuration
  - Velero chart config
- Tutorials 
   - Install Velero

That's the proper structure for it.
