### ISSUE TITLE
Evaluate Observability and Backup components resource consumptions

### ISSUE THREAD

**Issue by lilitgh** [kyma-project/kyma#4988]
**Description**

In order to optimize Kyma resources usage we need to evaluate resource consumptions of observability and backup components (logging, monitoring, tracing, kiali, velero)  .

**Reasons**
Optimize Kyma resources usage

**Comment by hisarbalik** [comment]
Logging, monitoring, and kiali has been optimized. Jaeger will be handlen in the issue #4542
