### ISSUE TITLE
Slack links are unusable

### ISSUE THREAD

**Issue by antoineco** [kyma-project/kyma#4991]
**Description**

* The "invitation" link in the header of the official doc is dead, redirects to a `This invite link is no longer active.` page.

<details>
 <summary>expand for screenshot</summary>

![dead_link](https://user-images.githubusercontent.com/3299086/61717487-76ea2480-ad61-11e9-8273-9d53c8878338.png)

</details>

* All other links within the docs redirect to https://kyma-community.slack.com, which essentially tell the user to `Contact the workspace administrator for an invitation` (WHO?)

<details>
 <summary>expand for screenshot</summary>

![admin_who](https://user-images.githubusercontent.com/3299086/61718149-a9e0e800-ad62-11e9-97d2-aef400c18cb3.png)

</details>

**Expected result**

As a user outside of SAP, I can join the Kyma community.

**Actual result**

As a user outside of SAP, I'm locked out of Kyma community without any obvious possibility to join.

**Steps to reproduce**

See description.

**Troubleshooting**

Ask my team members if that's expected (it's not).

**Comment by derberg** [comment]
new invite link
https://join.slack.com/t/kyma-community/shared_invite/enQtNjkxOTA0MzM4MjkwLTYyNGIzZTUwN2RmYjYzMTI3NmU5ZjZiNGFhOGY5MGJmYjAyMzI5ZDNmYmZjYTllZjJmNGY2YWVjMDFiMjgyYmU

we will soon update it everywhere and make sure http://slack.kyma-project.io also points to new link
