### ISSUE TITLE
Provide support for easy and quick development of add-ons

### ISSUE THREAD

**Issue by abbi-gaurav** [kyma-project/kyma#5000]
**Description**
As a connector developer, I would like to have a low entry barrier for creating an add-on to connect to my SAP application or a third-party system. Having a skeleton template with all the necessary files will help me focus on developing my logic for the connector and not worry about configuration or low-level details.

The current process is long, error-prone and a developer can end up spending the time of fixing add-on issues with configurations.

**Comment by abbi-gaurav** [comment]
It would be nice to have an experience similar to creating a new kubebuilder or helm project. Additionally, we can ask some input interactively and create the appropriate files.
More or less, there are few things which the new add-on requires or differs from others:
1. name
2. container image
3. description
4. api definition
5. event spec
6. env variables (which will be related to the image)
7. user input variables (like tokens/basic auth)
I suppose other parts could be automated or generated.

**Comment by abbi-gaurav** [comment]
I guess for the chart, we possibly need to see how does it differ for one add-on to another?
another thought, perhaps we should first understand what skill set is expected from a developer creating a chart. e.g. If I am a developer in an SAP Application and want to build/maintain/update a connector, what all should be known upfront? maybe if we start from this question, we can have better clarity about this whole experience.

**Comment by PK85** [comment]
thanks for you input. For me it looks like a new project called addons-sdk.

**Comment by PK85** [comment]
I've investigated that topic, and took below actions:
- addons connectors will be not needed soon. That means, we will allow:
- user to define applications providing specs, docs etc via Kyma UI, issue: https://github.com/kyma-project/kyma/issues/4707 
- Kyma we will support oAuth2 server by ORY: 
- Kyma EventsService (Only REST endpoint) will be renamed to EventGateway(REST + MQTT)
