### ISSUE TITLE
Check the storage mounted for Helm Broker (define size, e.g. 1GB)  

### ISSUE THREAD

**Issue by mszostok** [kyma-project/kyma#5009]
**Description**

Check the storage mounted for Helm Broker (define size, e.g. 1GB)  

**AC:**
- Storage, where bundles are downloaded/extracted, has defined size
- documentation about default storage size and info how to change that if required

**Comment by adamwalach** [comment]
Current state:
```
      - name: tmp-empty-dir
        emptyDir:
          medium: "Memory"
```
This configuration is not perfect cause it uses `medium: "Memory"`, and according to the [documentation](https://kubernetes.io/docs/concepts/storage/volumes/#emptydir) it causes that any files you write to this directory will count against your Container’s memory limit. 

Solution:
```
      - name: tmp-empty-dir
        emptyDir:
          sizeLimit: 1Gi
```
The sizeLimit is not a hard limit. As described [here](https://github.com/kubernetes/kubernetes/issues/63126?spm=a2c65.11461447.0.0.37da3505aMuOoz#issuecomment-387817170): "eviction manager keeps monitoring the disk space used by pod emptyDir volume and it will evict pods when the usage exceeds the limit.". It means that for a short period of time (several seconds) when the amount of consumed space exceeds the limit:
<img width="1029" alt="Screen Shot 2019-07-26 at 13 41 55" src="https://user-images.githubusercontent.com/8530211/61949474-4c8ba780-afab-11e9-8f6e-a2414593029c.png">
After the limit is exceeded pod changes its status to `evicted`:
<img width="1011" alt="Screen Shot 2019-07-26 at 13 42 29" src="https://user-images.githubusercontent.com/8530211/61949550-8361bd80-afab-11e9-8adc-95ec895dab96.png">
It is automatically recreated by a deployment (with empty /tmp directory).
