### ISSUE TITLE
Revisit resource consumption (memory and cpu) for Application Connector components

### ISSUE THREAD

**Issue by Disper** [kyma-project/kyma#5022]
**Description**

Identify and try to lower resource requests (cpu and memory) for components related to service mesh and security.
Components to check:
- application-registry 
- application-operator
- application-gateway
- connector-service
- connection-token-handler
- connectivity-certs-controller
- connectivity-certs-setup-job (not sure yet if it should be included)
- ... ? 

**Reason**
Consuming less resources in the clusters

**Attachments**

**Comment by janmedrek** [comment]
Application Connector will be greatly minified due to change to Compass, the components that will remain working in Kyma environment were already improved resource-wise.
