### ISSUE TITLE
Core-console tests take too long

### ISSUE THREAD

**Issue by sjanota** [kyma-project/kyma#5038]
**Description**
`core-console` integration tests should be stripped of all cases not required to be run on a cluster. Such cases should be checked along with unit tests when the container is being built.  

**Reasons**
`core-console` tests are the longest-running tests we have in our suite: around 9 minutes. In comparison next in the queue is CBS which takes around 5 minutes. Every minute we can win here will benefit us tens of times a day.

**Attachments**

**Comment by kwiatekus** [comment]
Already mitigating with:
https://github.com/kyma-project/kyma/issues/5015
https://github.com/kyma-project/console/issues/1340
