### ISSUE TITLE
Make publish-service URLs and subscriber image configurable in tests

### ISSUE THREAD

**Issue by sayanh** [kyma-project/kyma#5042]
**Description**

Publish-service URLs and subscriber image are hard-coded and should be configurable somehow:

https://github.com/kyma-project/kyma/blob/master/tests/end-to-end/upgrade/pkg/tests/event-bus/event_bus.go#L32
https://github.com/kyma-project/kyma/blob/master/tests/end-to-end/backup-restore-test/backupe2e/eventbus.go#L34

There are multiple ways to take care of this:
- flags
- env vars
- configmaps(over-engineered)

**Reasons**

**Attachments**

**Comment by anishj0shi** [comment]
As event mesh would have new tests, this issue is not applicable anymore
