### ISSUE TITLE
Double ServiceInstance on UI 

### ISSUE THREAD

**Issue by jasiu001** [kyma-project/kyma#5046]
When new ServiceInstance is added to Kyma (e.g. by kubectl) on Service Management -> Service Instances tab for some period of time created instance is visible in two tabs `Add-Ons` and `Services`, after some time entity disappears from `Services` tab.

The screenshot below does not shows the bug but the place where bug shows up
![Screen Shot 2019-07-26 at 10.51.01.png](https://images.zenhubusercontent.com/5bb751f458d3b92dfedf44c9/9410d05b-0412-4774-9fa1-3e65724d5688)

**Comment by kwiatekus** [comment]
@jasiu001 Could you attach a yaml file that would help us reproduce the issue?

**Comment by kwiatekus** [comment]
The following PR will fix the problem.
https://github.com/kyma-project/console/pull/1394

Closing
