### ISSUE TITLE
Cannot create two Instances in a row with chosen plan

### ISSUE THREAD

**Issue by jasiu001** [kyma-project/kyma#5048]
During an attempt to creating new ServiceInstance second time in the same tab cannot choose Plan.
1) Choose addon from Catalog which could be provisioned many times
![Screen Shot 2019-07-26 at 11.14.03.png](https://images.zenhubusercontent.com/5bb751f458d3b92dfedf44c9/66cf4613-7aa4-45b4-94e0-9b12c7a9089a)
2) Add instance
![Screen Shot 2019-07-26 at 11.14.17.png](https://images.zenhubusercontent.com/5bb751f458d3b92dfedf44c9/58e2da4a-71c2-4ad8-8109-22ef0d1987b0)
3) Try to add an instance again without left the tab, write the name, try to choose the plan
![Screen Shot 2019-07-26 at 11.17.20.png](https://images.zenhubusercontent.com/5bb751f458d3b92dfedf44c9/5fc1645a-b5f4-44ba-b882-04be38d060e6)

**Comment by kwiatekus** [comment]
Already fixed with Kyma 1.6-rc1
