### ISSUE TITLE
Remove nginx-controller

### ISSUE THREAD

**Issue by a-thaler** [kyma-project/kyma#5057]
**Description**
After we finally moved the connector bundle to use istio ingress and application-connector as well, it is time to remove the nginx-controller from kyma fully.

**Reasons**
There should be only one way of exposing services

**Subtasks**
- [x] Remove NGINX controller
- [ ] Run compatibility tests on created cluster (without NGINX)

**Comment by tomekpapiernik** [comment]
Remember to update the docs. [This tutorial](https://kyma-project.io/docs/components/application-connector#tutorials-rotate-the-root-ca-certificate-and-key-rotating-a-soon-to-expire-ca-certificate) mentions Nginx.
