### ISSUE TITLE
Provide flexibility to specify max replicas for a lambda

### ISSUE THREAD

**Issue by abbi-gaurav** [kyma-project/kyma#5059]
**Description**

As a developer, I should be able to have elastic scalability options when developing a lambda. I should be able to configure a value for a max replica value to which a certain size lambda can auto-scale base on resource usage and then scale down the load goes down.

**Comment by Abd4llA** [comment]
With the upcoming `Function Controller` this will be available and we'll need to expose it. 
Ref: https://knative.dev/docs/serving/configuring-the-autoscaler/#configuring-scale-bounds-minscale-and-maxscale

**Comment by michal-hudy** [comment]
https://github.com/kyma-project/kyma/issues/7363
