### ISSUE TITLE
Remove retries while talking to kube API server in tests

### ISSUE THREAD

**Issue by sayanh** [kyma-project/kyma#5062]
**Description**

Every call to API server is surrounded by a retry loop. E.g. 
https://github.com/kyma-project/kyma/blob/be8626802dcab6fcad7036a244ca2184c3ce6f80/tests/event-bus/e2e-tester/e2e-tester.go#L548

https://github.com/kyma-project/kyma/blob/be8626802dcab6fcad7036a244ca2184c3ce6f80/tests/event-bus/e2e-tester/e2e-tester.go#L593

This is not desirable. Understand why the API server is not reachable in between tests. What happens when API server is contacted for CRUD of resources? Is it under load? Which part of the connection from the test pod to API server is breaking?  Ideally, once a test pod is ready and able to talk to API server, all the subsequent calls should just work without retries. Investigate and fix the issue if needed.

**Comment by k15r** [comment]
Adding random thoughts here:

**Comment by Abd4llA** [comment]
Needs triaging for all components

**Comment by sayanh** [comment]
As discussed, I created this https://github.com/kyma-project/kyma/issues/6434 to have a smaller scope with a similar objective.
