### ISSUE TITLE
Make the upstream GCP Service Broker and Kyma addon production ready

### ISSUE THREAD

**Issue by piotrmiskiewicz** [kyma-project/kyma#5067]
**Description**

The Google Cloud Platform Servivce Broker should be production ready.
AC:
 * fix schemas: remove default values like `pcf-sb-${counter.next()}-${time.nano()}` from schemas https://github.com/kyma-project/kyma/issues/5393
 * add enum to schemas for field *Region* (and other fields if necessary) https://github.com/kyma-project/kyma/issues/5393
* split docs: https://github.com/GoogleCloudPlatform/gcp-service-broker/issues/497, https://github.com/kyma-project/kyma/issues/5394
* allow users to specify external MySQL for the broker (wat?)
* resolved ticked (too short column in the internal storage) https://github.com/GoogleCloudPlatform/gcp-service-broker/issues/500
* add the Addon to the default index.yaml
* check if the broker's documentation is displayed correctly

risk:
- fix and add enums to schemas, if they merge our PR?

**Comment by mszostok** [comment]
| TODO                                                                                                                                                                                                           | Issue                                              |
|----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|----------------------------------------------------|
| fix schemas: remove default values like pcf-sb-${counter.next()}-${time.nano()} from schemas #5393 <br> add enum to schemas for field Region (and other fields if necessary) #5393                               | https://github.com/kyma-project/kyma/issues/5393   |
| split docs: GoogleCloudPlatform/gcp-service-broker#497, #5394                                                                                                                                                  | <https://github.com/kyma-project/kyma/issues/5394> |
| allow users to specify external MySQL for the broker                                                                                                                                                           | (wat?)                                             |
| resolved ticked (too short column in the internal storage) GoogleCloudPlatform/gcp-service-broker#500 <br> add the Addon to the default index.yaml <br> check if the broker's documentation is displayed correctly | <https://github.com/kyma-project/kyma/issues/5395> |
