### ISSUE TITLE
rename knative-function-controller -> function-controller and fn-config configmap

### ISSUE THREAD

**Issue by k15r** [kyma-project/kyma#5075]
**Description**

the main configmap for the knative-function-controller is currently called `fn-config`.
Rename it to `function-controller-config`

**Reasons**

Users might not directly find the correct configmap to update the knative-function-controller. Other controllers use a similar name for their main configmaps

**Attachments**

**Comment by rakesh-garimella** [comment]
Fixed via: #4924
