### ISSUE TITLE
Update components to latest k8s version

### ISSUE THREAD

**Issue by piotrmsc** [kyma-project/kyma#5078]
**Description**

We need to upgrade k8s version in our components and also update our charts. However, this needs to be aligned with k8s upgrade of minikube and cluster(handeled by wookies).
Example, Deployments have new api group now.

All our components should have charts and code deps updated:
- [x] api-controller
- [x] apiserver-proxy
- [x] kyma-operator
- [x] kubeconfig-iam-service
- [x] dex-static-user-configurer

 

**Reasons**
Be up to date with k8s upgrades, we also have a sec issue in api-controller using old k8s client version which has a sec vulnerability. 

**Attachments**

**Comment by jakkab** [comment]
see #5079

**Comment by derberg** [comment]
Removed from epic https://github.com/kyma-project/kyma/issues/5077 as it is not related
