### ISSUE TITLE
Upgrade k8s.io/client-go in idppresets

### ISSUE THREAD

**Issue by jakkab** [kyma-project/kyma#5081]
**Description**

Upgrade k8s.io/client-go to kubernetes-1.12.5, kubernetes-1.13.1, kubernetes-1.14.0, or higher

**Reasons**

Keeping our components up to date.

**Comment by derberg** [comment]
@jakkab please adjust to follow the template https://github.com/kyma-project/kyma/issues/new?template=security-vulnerability.md. At least add the CVSS assessment and proper security label please

**Comment by derberg** [comment]
You know what, I do not want to waste your time as we are getting ready for 1.4 release. Let me do that for ya.

**Risk assessment**
[AV:N/AC:H/PR:N/UI:N/S:U/C:H/I:H/A:H](https://www.first.org/cvss/calculator/3.0#CVSS:3.0/AV:N/AC:H/PR:N/UI:N/S:U/C:H/I:H/A:H)

**Comment by akucharska** [comment]
Update client-go version in cbs will be possible after update of the following components:
- kyma/common/microfrontend-client
- kyma/components/service-binding-usage-controller
- kyma/components/application-broker
- kyma/components/api-controller
- kubernetes-incubator/service-catalog
- kubeless/kubeless/

**Comment by derberg** [comment]
Removed from epic https://github.com/kyma-project/kyma/issues/5077 as it is not related
