### ISSUE TITLE
Upgrade k8s.io/client-go in asset-store-controller-manager

### ISSUE THREAD

**Issue by jakkab** [kyma-project/kyma#5082]
**Description**

Upgrade k8s.io/client-go to kubernetes-1.12.5, kubernetes-1.13.1, kubernetes-1.14.0, or higher

**Reasons**

Keeping our components up to date.

**Comment by derberg** [comment]
@jakkab please adjust to follow the template https://github.com/kyma-project/kyma/issues/new?template=security-vulnerability.md. At least add the CVSS assessment and proper security label please

**Comment by derberg** [comment]
You know what, I do not want to waste your time as we are getting ready for 1.4 release. Let me do that for ya.

**Risk assessment**
[AV:N/AC:H/PR:N/UI:N/S:U/C:H/I:H/A:H](https://www.first.org/cvss/calculator/3.0#CVSS:3.0/AV:N/AC:H/PR:N/UI:N/S:U/C:H/I:H/A:H)

**Comment by derberg** [comment]
Removed from epic https://github.com/kyma-project/kyma/issues/5077 as it is not related

**Comment by derberg** [comment]
Not a security issue, as https://github.com/kubernetes/kubernetes/issues/71411 is related to upgrade of cluster version, and not the go-client in controllers. Removing security labels

**Comment by michal-hudy** [comment]
Fixed by https://github.com/kyma-project/kyma/pull/5465
