### ISSUE TITLE
Expose metrics in hcms and asset store

### ISSUE THREAD

**Issue by derberg** [kyma-project/kyma#5085]
**Description**

- expose metrics on /metrics endpoint (so servicemonitor can point to it) in all controllers and services
- for controllers have standard metrics from kubebuilder + the extra one we need to measure SLO and get alerts
- for service have standard metrics - if we defined them in Kyma already
- nice an awesome dashboard, separate for asset store, and separate for hcms
- document what metrics do we expose (reference docs), and maybe something like this for tracing would make sense (templates are stretched) and just mention we enabled tracing

_Stretch:_
- have tracing enabled so I can see time spent on asset between fetching and uploading to minio, to measure which step is a bottleneck in performance. Make sure sampling is set to 100 in performance cluster (check if possible)
- have sidecars where needed for tracing if needed

**Reasons**

Have metrics for controllers and services to be able to see how solution behaves and if the load handling matches the defined SLO

**Comment by derberg** [comment]
AssetStore
- asset store controller
- upload service
- metadata service

hCMS
- cms controller
- asyncapi service

**Comment by aerfio** [comment]
In followup, see if those metrics could be imported from istio, and not from our custom implemented metrics
