### ISSUE TITLE
Make long running clusters stable

### ISSUE THREAD

**Issue by piotrmiskiewicz** [kyma-project/kyma#5086]
Currently, we are running GKE nightly and weekly, and AKS nightly clusters. In these clusters we are running `testing.sh` periodically to be sure the Kyma is stable. As we see, cluster which is running more than 24 hours, has problems. The goal is to make such cluster stable.
First, we need to check and remove old ClusterTestSuites (CTS "holds" testing pods which reserves resources).
Next problem is the CPU load on a weekly Node (growing up to about 80%):

![Screen Shot 2019-07-30 at 10.51.06 AM.png](https://images.zenhubusercontent.com/5b8f8be40e23a90b8f9c40b3/42048881-680f-47e7-8b69-d26e79fcbd4a)

**Comment by Disper** [comment]
Number of cts after 2 days since the weekly was created. 
```
➜  ~ kubectl get cts
E0731 09:10:22.572746   10441 round_trippers.go:169] CancelRequest not implemented by *gcp.conditionalTransport
NAME                             AGE
testsuite-all-2019-07-30-04-47   1d
testsuite-all-2019-07-30-11-50   19h
testsuite-all-2019-07-30-13-00   18h
testsuite-all-2019-07-30-14-10   17h
testsuite-all-2019-07-30-17-40   13h
testsuite-all-2019-07-30-20-53   10h
testsuite-all-2019-07-30-23-08   8h
testsuite-all-2019-07-31-00-21   6h
testsuite-all-2019-07-31-01-29   5h
testsuite-all-2019-07-31-03-27   3h
testsuite-all-2019-07-31-04-48   2h
```

The current state of the cluster is that it's not stable. It's hard to connect to it.

**Comment by piotrmiskiewicz** [comment]
The PR #5128 makes the cluster stable. Currently the VM CPU is about 60 - 80%, but still we need to check, what is consuming the CPU.

**Comment by pbochynski** [comment]
Related issue: https://github.com/kyma-project/kyma/issues/5404

**Comment by pbochynski** [comment]
Please reopen if the problem still persists.
