### ISSUE TITLE
Upgrade logging to Kubernetes 1.15

### ISSUE THREAD

**Issue by clebs** [kyma-project/kyma#5095]
**Description**
Upgrade the logging component to the Kubernetes 1.15 Kubernetes API:
- Remove usage of deprecated and removed APIs.
- Update remaining APIs to the new verison

**Reasons**
- Kyma overall upgrade to Kubernetes 1.15

**Comment by suleymanakbas91** [comment]
There is nothing to upgrade for logging components.
