### ISSUE TITLE
Add support for remote addon repositories: Mercurial, S3, GCS

### ISSUE THREAD

**Issue by mszostok** [kyma-project/kyma#5102]
**Description**

The [go-getter](https://github.com/hashicorp/go-getter) lib is used in Helm Broker to fetch addons from the remote servers. Currently, only HTTP/HTTPS and Git repositories are supported.

In this task, we should add support for:
- Mercurial, 
- S3, 
- GCS

Additionally, change the Addon UI schema validator to allow us to change the allowed schemas in an easy way. Currently, it's hardcoded [here](https://github.com/kyma-project/console/blob/38e96d29dfba62173d4ba1991c1f093527f8b04f/add-ons/src/services/Urls.service.ts#L21-L28) in console. Contact person @magicmatatjahu 

---
[Stretch] Consider adding support also for GitLab detector, same as they have for [Github](https://github.com/hashicorp/go-getter/blob/master/detect_github.go), so user will be able to set URL as `gitlab.com/kyma-project/addons` instead of `git::https://gitlab.com/kyma-project/addons.git`
 

**AC**

- each repository option is well tested (unit and integration tests)
- each repository option is well-documentation (documentation available on kyma-project.io)
- Addon UI is configurable and we can set easily which repository schemas are currently supported (e.g. "git::", "s3::", "gcs::", "github.com/" etc)

**Comment by adamwalach** [comment]
Changing the Addon UI:

- Kyma: https://github.com/kyma-project/kyma/compare/master...adamwalach:change-url-validator-in-helm-broker?expand=1

- Console: https://github.com/kyma-project/console/compare/master...adamwalach:change-schema-validator?expand=1

**Comment by adamwalach** [comment]
GCS tests fail:
I tried to use the following URL: - url: gcs::https://www.googleapis.com/storage/v1/bucket/helm-broker-addons//index-testing.yaml
But I can't find in the go-getter docs any description how to provide credentials in the url. This comment: https://github.com/golang/oauth2/blob/master/google/default.go#L61 suggests that 
creds can be taken from file.

**Comment by mszostok** [comment]
- remote totally the GCS implementation 
- add integration test for S3
- add documentation for `hg` and S3

**Comment by PK85** [comment]
Missing docs for mercurial
