### ISSUE TITLE
knative-function-controller AdmissionWebhook  should load config from cluster

### ISSUE THREAD

**Issue by k15r** [kyma-project/kyma#5112]
**Description**

The mutating/validatingAdmissionWebhooks of the knative-function-controller should load the valid runtimes and default values from the cluster.

**Reasons**

Currently those settings are hard coded, so modifying those values will require a code change whereas it should only be a configuration change

**Attachments**

**Comment by rakesh-garimella** [comment]
Fixed via: kyma-project/kyma#5327
