### ISSUE TITLE
Simplify and make more readable Addon structures in Helm Broker

### ISSUE THREAD

**Issue by mszostok** [kyma-project/kyma#5115]
**Description**

#### 1st Problem
We should try to clean-up Addons structures in Helm Broker to have that more readable.

Directory layout:
```
└── internal
    ├── addon
    │   ├── dto.go #  1st Addon struct
    │   └── dto_test.go
    ├── controller
    │   ├── addons
	│   │   ├── addon.go #  2st Addon struct
	│   │   ├── addon_test.go
    │   ├── addonsconfiguration_controller.go
    │   └── addonsconfiguration_controller_test.go
    ├── model.go #  3st Addon struct
    └── model_test.go
```

when you check the 2s Addon struct then it looks like that:
```go
// AddonController is a wrapper for Addon element with extra fields like URL, addon or charts
type AddonController struct {
	ID            string
	URL           string
	Addon         v1alpha1.Addon
	CompleteAddon *internal.Addon
	Charts        []*chart.Chart
}
```

you can see that we have struct called Addon, which has two fields Addon and Complete Addon, so it is an addon for addon about addon :D

#### 2nd Problem

Right now we have two controllers. They have exactly the same logic. We should try to unify that business logic by extracting that to some commons which can be used by both solutions.

- [addonsconfiguration_controller](https://github.com/kyma-project/kyma/blob/master/components/helm-broker/internal/controller/addonsconfiguration_controller.go)
- [clusteraddonsconfiguration_controller](https://github.com/kyma-project/kyma/blob/master/components/helm-broker/internal/controller/clusteraddonsconfiguration_controller.go)

**AC**

- Addons structures/models are well-defined and easy to understand
- Duplicate logic from controllers is extracted and tested
- create a proposal for two above issues (5SP for that), meet with a team and discuss

**Comment by polskikiel** [comment]
Actual layout:
```
└── internal
    ├── addon
    │   ├── dto.go #  1st Addon struct
    │   └── dto_test.go
    ├── controller
    │   ├── addons
	│   │   ├── addon.go #  2st Addon struct
	│   │   ├── addon_test.go
    │   ├── addonsconfiguration_controller.go
    │   └── addonsconfiguration_controller_test.go
    ├── model.go #  3st Addon struct
    └── model_test.go
```
Proposed layout:
```
└── internal
    ├── addon
    ├── controller
    │   ├── repository
	│   │   ├── repository_entry.go
	│   │   ├── repository_entry_test.go
    │   ├── addonsconfiguration_controller.go
    │   └── addonsconfiguration_controller_test.go
    ├── model.go #  Addon and AddonWithChart structs
    └── model_test.go
```
