### ISSUE TITLE
Provide access to Istio/Knative functionality via Kyma UI

### ISSUE THREAD

**Issue by johnkbarrow** [kyma-project/kyma#5119]
**Description**

The functionality provided by Istio and Knative is extremely powerful, but leveraging many of the capabilities currently require modifying configurations "under the covers". Having the ability to modify configurations via the Kyma UI would be very powerful.
**Reasons**

Being able to do complicated traffic routing and canary deployments for lambdas and microservices is a really powerful feature provided by Istio. Similarly, being able to scale-to-zero with Knative. It would be great to be able to do these things via the Kyma UI for the lambdas and microservices deployed within Kyma, without having to go "under the covers" to manipulate onfigurations.
**Attachments**

https://istio.io/docs/examples/bookinfo/
https://github.com/knative/serving/blob/master/docs/scaling/DEVELOPMENT.md

**Comment by derberg** [comment]
@kwiatekus @piotrmsc @Abd4llA 
Would be awesome guys to have your input here, from backend and also UI perspective. @johnkbarrow joined our Core SIG today and we advised him that the best platform to discuss such a roadmap element is github issue as it gives you time for longer discussion when sometimes you have to consult others before you answer.

@clebs I guess Kiali is not addressing the Istion part, the UI is rather for different things or?

**Comment by piotrmsc** [comment]
Thx for your feedback @johnkbarrow :) 

It is 100% valid and if you take a look at our vision for API Gateway here https://kyma-project.io/roadmap/
You can see that traffic management, failure prevention is on our roadmap :) 

For sure ther might be a question when? well... next 2 releases we will focus on delivering Oauth2 capabilities in the Gateway but we have this in mind for sure ;-)

From APi Gateway POV lambda is also an API so I suspect most of the work will be done in gateway area and in the UI but  for sure we will be in touch with @Abd4llA

**Comment by michal-hudy** [comment]
Currently, it is possible to define scaling for serverless in the UI, so I'm removing `serverless` label.

**Comment by piotrmsc** [comment]
I will need to close this one since knative was removed from kyma..
