### ISSUE TITLE
Document Knative Eventing

### ISSUE THREAD

**Issue by rakesh-garimella** [kyma-project/kyma#5126]
Description

We should have a proper documentation for knative eventing such that it can be incorporated in the kyma website.

This docu should be put under Event Bus, we don't need separate component documentation for it.

For Knative Eventing, we can probably reuse some Knative documentation and write how this functionality is incorporated as Kyma module.
* Provide the overview of the module
* Describe how it fits into Kyma - is there any additional configuration needed to make it work? If so, what the user needs to do?
* How does it work with the current event bus settings?

**Comment by sayanh** [comment]
Pointers from @bszwarc 
Following areas need improvement:
- Overview
- Add Knative details in the event-bus context with the links and not repeat things
- Outdated details https://kyma-project.io/docs/components/event-bus/#details-basic-concepts
- Toggle header details for v1 and v2 publish service in [here](https://kyma-project.io/docs/components/event-bus/#details-service-programming-model-event-metadata)

In general, break PRs for easy approval process

**Comment by sayanh** [comment]
> Toggle header details for v1 and v2 publish service in [here](https://kyma-project.io/docs/components/event-bus/#details-service-programming-model-event-metadata)

This is not valid as it refers to the event delivery. Since event-bus is cloud events compliant, the headers remain same(CE compliant) irrespective of the version of the publish service API used. I created this [PR](https://github.com/kyma-project/kyma/pull/5374) to make it more explicit.

**Comment by marcobebway** [comment]
@sayanh please remove the section related to the **push** application [here](https://github.com/kyma-project/kyma/blob/master/docs/event-bus/03-01-concepts.md) as it is no longer exist.

**Comment by sayanh** [comment]
@marcobebway https://github.com/kyma-project/kyma/pull/5407 fixes this.
