### ISSUE TITLE
Document Function Controller

### ISSUE THREAD

**Issue by rakesh-garimella** [kyma-project/kyma#5129]
**Description**

We should have proper documentation for Function Controller such that it can be incorporated in the Kyma website.

It doesn't necessarily have to follow the regular component structure as (as I imagine) it will fall under the Event Bus documentation - if it still is Event Bus. 

We should for sure have:
* an overview of the function controller 
* ~~some technical details if needed, explaining how the function controller fits into the eventing architecture~~ https://github.com/kyma-project/kyma/issues/5129#issuecomment-527133975
* documentation for the Function CR

**Comment by sayanh** [comment]
Depends on: https://github.com/kyma-project/kyma/issues/4803

**Comment by rakesh-garimella** [comment]
> some technical details if needed, explaining how the function controller fits into the eventing architecture
This is not valid as function-controller is not invoked by events.
