### ISSUE TITLE
Improve asyncapi parser used in AsyncApi validation and conversion service

### ISSUE THREAD

**Issue by derberg** [kyma-project/kyma#5134]
**Description**

- missing features are out of scope, just make sure adding functionality for parsing avro or protobuf will not cause major refactor of the parser. Explain in documentation where someone can add missing features.
- improve current state and make sure architecture supports future improvements, like integrating avro or protobuf parsers for the messages payload, or custom extensions
- make sure referencing of local files also works, from any location (doesn't work in the current version)
- make it clear in documentation how and where to contribute missing features because we will limit our contribution to parts that we need atm
- error handling - have a kind of leveling of errors so I can decide which error fails and which error just brings a warning, so later with a flag I can decide when the parser should faile, how sensitive it should be. Probably better to not do it in parser but on the service side that will use the parser.
- new parser running in conversion/validation service of the asset store

**Reasons**

First version of the parser created by community is a great work but need some improvements and solve some workarounds, like dereferencing. We need to make sure that the parser is written properly as it runs inside our service and can cause memory leaks.

**Attachments**

- https://github.com/asyncapi/parser

**Comment by mmitoraj** [comment]
PR -> https://github.com/asyncapi/parser/pull/42
