### ISSUE TITLE
Add documentation linting

### ISSUE THREAD

**Issue by aerfio** [kyma-project/kyma#5135]
**Description**

Right now developers maintaining documentation-component have agreement with technical writers that they write docs that display nicely in github and theirs IDEs. This is a bit problematic, because we are using react-markdown library almost everywhere, and some things do not display the same way as in github. Examples: 
![image](https://user-images.githubusercontent.com/17271979/62275118-8f350000-b441-11e9-89cb-85a831912fca.png) taken from [here](https://kyma-project.io/docs/components/application-connector/#tutorials-trigger-a-lambda-with-events-steps)

![image](https://user-images.githubusercontent.com/17271979/62275333-023e7680-b442-11e9-999a-f6838c3412b8.png)
[here](https://kyma-project.io/docs/root/kyma/#installation-use-your-own-kyma-installer-image)

![image](https://user-images.githubusercontent.com/17271979/62275957-48e0a080-b443-11e9-94f6-1e98946e70e8.png) (useless white space)

et cetera. All of those examples above render nicely in github.

One idea is to introduce prowjob with [markdown linter](https://github.com/DavidAnson/markdownlint) with our custom set of rules that will help TW's with their job, without devs explicit ingerence. 

Other solution would be to somehow make website build on kyma repo when markdowns get changed, TWs could see their changes right away.

**Reasons**

In order to have satisfying user experience we need to render documentation without any problems.

**Attachments**

**Comment by derberg** [comment]
First goal is to find autoformater for markdown linting. Without a tool that can format markdown automatically, we cannot go further with this task and need to find some other solution.

**Comment by magicmatatjahu** [comment]
I made small investigation in free time and found several libraries/tools:
- https://github.com/DavidWells/markdown-magic - tool to generating content from comments. As I see, there is no auto formatting function, but we can write our own plugin for that.
- https://github.com/DavidAnson/markdownlint - known tool, but there is not auto formatting functionality (maybe contribution?)
- https://github.com/sumnow/markdown-formatter - vsc extension with formatting, but there is no node package, so we would have to contributing or write own node based on that.

Whatever we decide, I merged PRs with preview on docs and community, and probably at the moment this is enough to browse markdowns for bad syntax.

I leave decision to @derberg, close issue or make follow task.

**Comment by derberg** [comment]
@magicmatatjahu what about the CLI for `markdownlint` https://github.com/igorshubovych/markdownlint-cli ? looks like it has a `--fix` flag

**Comment by aerfio** [comment]
As for Go: Hugo uses https://github.com/russross/blackfriday, which probably has some validation built in; also have a look at https://github.com/russross/blackfriday#other-renderers, https://github.com/shurcooL/markdownfmt#alternatives

**Comment by michal-hudy** [comment]
I think the preview is enough for now.
