### ISSUE TITLE
Helm Broker component has own repository in the kyma-project organization

### ISSUE THREAD

**Issue by PK85** [kyma-project/kyma#5136]
**Description**

Extract Helm Broker component into separate repository under github kyma-project organization.

**AC**
- documentation for kyma-project.io stays for now in kyma repository itself
- create main README.md about helm broker
  - mention all prerequisites, like Service-Catalog required
- create helm chart that installs just Helm-Broker and registers it to SC (make it optional to register to SC)
- make addons documentation feature as optional in helm broker (Headless CMS required)
- version of the HB in Kyma HB chart will be provided by "hand"
- remove helm-broker from kyma/components
- think how to copy git history, if possible (1MD timebox) (see comment below)
- new release pipelines created, old ones deleted (keep ability to create a patch for previous versions)

**Comment by adamwalach** [comment]
Looks like preserving git history is [quite easy](https://help.github.com/en/articles/splitting-a-subfolder-out-into-a-new-repository):
```
# in kyma repo:
git filter-branch --prune-empty --subdirectory-filter components/helm-broker  master
```
result: https://github.com/adamwalach/helm-broker-test
