### ISSUE TITLE
Support authentication methods for AddonsConfigurations

### ISSUE THREAD

**Issue by PK85** [kyma-project/kyma#5139]
**Description**
Enable AddonsConfiguration CR to add https/git repository with credentials for them.

**Technical Proposal**
Check this documentation for tech proposal: https://github.com/kyma-project/helm-broker/blob/master/docs/proposals/addon-git-support.md#future-implementations

**AC**
- templating for filling the AddonsConfiguration/ClusterAddonsConfiguration URL from Secret is working
- solution is well-tested
- solution is well-documented
- check only the https/git auth in a real scenario (rest out-of-scope)

**Comment by mszostok** [comment]
info about auth: https://github.com/kyma-project/helm-broker/blob/master/docs/proposals/addon-git-support.md#future-implementations
