### ISSUE TITLE
Update requirements for chart README.md docs in the CONTRIBUTING.md document

### ISSUE THREAD

**Issue by kazydek** [kyma-project/kyma#5140]
**Description**

Since we have decided not to adjust the imported `README.md` documents to our chart template and use it only for our in-house developed charts, we need to clearly state that in the [`CONTRIBUTING.md`](https://github.com/kyma-project/kyma/blob/master/CONTRIBUTING.md#contribution-rules) document where it says now that all chart README.md docs should follow the template.

**Comment by a-thaler** [comment]
@derberg  which backlog it should go?

**Comment by PK85** [comment]
@derberg decide to close that one. No action so far
