### ISSUE TITLE
Have support for arbitrary environment variables in knative function controller.

### ISSUE THREAD

**Issue by rakesh-garimella** [kyma-project/kyma#5144]
**Description**

We should have support for injection of user-defined arbitrary environment variables into the knative service using knative-function-controller.

**Reasons**

As users might want some environment variables for following reasons:
* Access private npm registries (this would be required for knative-build)
* Provide environment variables to the lambda code.

**Note** Align on the Function CRD API first.

**AC**
* A user can define env vars in `Function` object that gets propagated to the Ksvc object.
* There is a documentation for this feature in README.

**Comment by michal-hudy** [comment]
Already implemented
