### ISSUE TITLE
UI component for rendering JSONschema as reference documentation 

### ISSUE THREAD

**Issue by derberg** [kyma-project/kyma#5145]
**Description**

- new component as part of https://github.com/kyma-incubator/documentation-component
- it should be possible to add custom static text to the generated part that will be visible on all other sites
- follow fiori3, consult Lidia
- support in all UIs?
- support in hcms?

**Reasons**

Writing additional reference docs manually is a waste of time and disrespect to Technical Writers and Developers. Reference docs are hard to maintain and are already provided as contracts in different forms, crds, api specs, schemas. TW and Dev should make sure that those are up to date, and additional documentation in the documentation portal should be autogenerated.

**Comment by michal-hudy** [comment]
Currently not a priority
