### ISSUE TITLE
Provide a proper docker registry authentication model in Kyma for the function controller

### ISSUE THREAD

**Issue by rakesh-garimella** [kyma-project/kyma#5146]
**Description**

When using the knative-function-controller, we need to have a service account with credentials to the docker registry where the image could be pushed. We need to figure out a solution here, since during the installation of kyma a user cant pass the credentials. We have to tackle following issues:

* How to pass the docker credentials.
* How to handle the service account that is needed for Tekton, should it be present in every namespace that user creates.
* Service account is also needed for knative service to pull the image build for lambda.

**AC**

* A proposal for the authentication model
* Update Function Controller and Kyma charts to implement agreed upon proposal.

**Comment by rakesh-garimella** [comment]
we can put the function object in the function namespace and the configmap with function code can be placed in the build namespace? We should have unique name for the configmap.

**Comment by Abd4llA** [comment]
Probably needs a more concrete proposal specially after refactoring to Tekton?

**Comment by michal-hudy** [comment]
We decided to not use external docker registry, rather use Rafter as a storege
