### ISSUE TITLE
Knative function controller should be able to handle the service binding usage labels

### ISSUE THREAD

**Issue by rakesh-garimella** [kyma-project/kyma#5153]
**Description**
knative controller should be able to handle Service binding usage labels coming from `UsageKind` when user binds service to the lambda and it should be able to push the labels to the pods.

**AC**
* Using `ServiceBinding` with a Kyma function ends up with ENV VARs getting injected inside the function pod. 
* FunctionController can set proper labels to the Ksvc podtemplate from the `UsageKind`
* FunctionController preserves and honours existing labels.

**Comment by michal-hudy** [comment]
Already implemented
