### ISSUE TITLE
Document backup custom resources separately

### ISSUE THREAD

**Issue by suleymanakbas91** [kyma-project/kyma#5158]
**Description**

Follow up for https://github.com/kyma-project/kyma/pull/5151. Custom resources for backup are documented inside backup tutorials. We should document them in a separate document.

**Comment by bszwarc** [comment]
This task was addressed by this PR: https://github.com/kyma-project/cli/pull/231

**Comment by bszwarc** [comment]
In my opinion, there is no need to document it separately. 
We document Kyma CRDs (based on the specific template) and sample resources. This is a CR based on Velero's CRD (https://velero.io/docs/v1.1.0/api-types/backup/), so I would just link to it. 
There is no point in adding a separate doc to copy-paste the Velero documentation.
