### ISSUE TITLE
Update k8s version in application connectivity area

### ISSUE THREAD

**Issue by pbochynski** [kyma-project/kyma#5160]
**Description**

We need to upgrade k8s version in our components and also update our charts. 
 

**Reasons**
Be up to date with k8s upgrades, we also have a sec issue in api-controller using old k8s client version which has a sec vulnerability. 

**Attachments**

**Comment by Szymongib** [comment]
There is an issue with Helm upgrade while changing the API group of for example Deployment to `apps/v1` and adding the `selector` (which is required in this API group and was not required previously). Helm shows the following error: `Invalid value: v1.LabelSelector{MatchLabels:map[string]string{"app":"connection-token-handler", "release":"application-connector"}, MatchExpressions:[]v1.LabelSelectorRequirement(nil)}: field is immutable` which is a problem considering Kyma upgrade strategy.

**Comment by derberg** [comment]
Removed from epic https://github.com/kyma-project/kyma/issues/5077 as it is not related
