### ISSUE TITLE
GATEWAY_URL is not accessible to the lambda runtime environment

### ISSUE THREAD

**Issue by abbi-gaurav** [kyma-project/kyma#5163]
**Description**
I am doing the service binding with a lambda. and using the `baseURL = process.env['GATEWAY_URL'];` to get the URL. It comes as `undefined`. I also tried with adding a prefix, but the same problem.
I can see the credential clearly present.

![Screenshot 2019-08-01 at 11 59 52](https://user-images.githubusercontent.com/4436741/62307768-7b5ebd80-b484-11e9-9a8a-1473db827542.png)

Only after restarting the pod, `service-catalog-addons-service-binding-usage-controller--*`, The GATEWAY_URL environment variable was injected to the lambda runtime.

**Expected result**
Able to call application APIs from a lambda without restarting any system pods.

**Actual result**
Need to restart a system pod. The current behavior is unstable and bad user experience. Spent around 2 hours struggling with this issue.

**Comment by jasiu001** [comment]
Duplicated of [#3847](https://github.com/kyma-project/kyma/issues/3487)

Resolved in [#4004 PR](https://github.com/kyma-project/kyma/pull/4004) by adding extra liveness probe which checks the correct operation of the SBU controller.
