### ISSUE TITLE
Odata apis are URL encoded by Kyma causing the API call to fail

### ISSUE THREAD

**Issue by abbi-gaurav** [kyma-project/kyma#5164]
**Description**
I am seeing problems when making the Odata API via the application gateway.

It seems the URLs of the format `${gateway-url}/Object('some-id')` are getting encoded into `https://<my.tenant>.com/Object%28%27some-id%27%29`. This causes the api call to fail with 404. 

I confirmed that this encoding is being done by the application gateway by making a direct call to the application from the same lambda which works fine.

**Expected Result**
Able to call Odata APIs from the lambda code.

**Actual result**

Call fails with possibly application gateway doing a URL encoding.

```
time="2019-08-01T14:00:59Z" level=info msg="Modified request url : 'https://<my-tenant>/sap/c4c/odata/v1/c4codataapi/CorporateAccountCollection%28%2700163E7841DC1ED9ACD99799567445B8%27%29?$select=CurrentDefaultAddressUUID,Name,CountryCodeText,HouseNumber,Street,StreetPostalCode,City', schema : 'https', path : '/sap/c4c/odata/v1/c4codataapi/CorporateAccountCollection('00163E7841DC1ED9ACD99799567445B8')'"
```

**Comment by crabtree** [comment]
@abbi-gaurav I try to reproduce the issue but with no success. I tried to run the gateway as a standalone component and did not observe the described behavior. 

Could you please provide additional details that will help to reproduce your issue:
- kyma version
- which version of node js do you use to define your lambda
- what functions/libraries do you use to call the OData API (is it nodejs http client or some third party library like axios)

**Comment by abbi-gaurav** [comment]
@crabtree , here are the details.
* Kyma version - 1.1
* nodejs8
* axios


When I directly provide the url to axios of the form `https://<my-tenant>.com/('object-id')`, it works fine.
When I use `http://<gateway-url>/('object-id')`, it fails with 404.
Due to this, I suspect if client could be the culprit.

**Comment by akrausesap** [comment]
@crabtree : here is the result of a debugging session:

the proxy works as expected (w/o escaping **'** ) if the target url is registered as follows: `https://<my.tenant>.com``

as soon as the registration turn into `https://<my.tenant>.com/mybasepath` there is some behind the scenes magic happening.

Namely makeProxy's (https://github.com/kyma-project/kyma/blob/master/components/application-gateway/internal/proxy/proxyfactory.go) director function starts to manipulate `req.URL.Path` in a way that it is not a valid representation of `req.URL.RawPath` anymore (due to the call by reference nature of director). Hence later it will be rewritten by the escape function of URL and fully escaped which it wont be in the initial case.

Hypothesis is that this behaviour can be avoided by manipulating both  `req.URL.Path` and `req.URL.RawPath`in a consistent form

**Comment by abbi-gaurav** [comment]
@crabtree, here is the code demonstrating the different behaviors explained by Andreas.

```go
package main

import (
	"log"
	"net/url"
	"strings"
)

func main() {
	createProxyPath("https://my.pre-1908-c4c.com", "/baseurl/api('some-id')")
	createProxyPath("https://my.1908-c4c/baseurl", "/api('some-id')")
}

func createProxyPath(targetURLString, requestURLString string) {
	requestURL, err := url.Parse(requestURLString)
	targetURL, err := url.Parse(targetURLString)
	if err != nil {
		log.Fatal(err)
	}

	requestURL.Scheme = targetURL.Scheme
	requestURL.Host = targetURL.Host
	requestURL.Host = targetURL.Host

	requestURL.Path = joinPaths(targetURL.Path, requestURL.Path)

	log.Printf("url is %s\n", requestURL.String())

}

func joinPaths(a, b string) string {
	if b == "" {
		return a
	}

	aslash := strings.HasSuffix(a, "/")
	bslash := strings.HasPrefix(b, "/")
	switch {
	case aslash && bslash:
		return a + b[1:]
	case !aslash && !bslash:
		return a + "/" + b
	}
	return a + b
}
```

the logs
```
2019/08/06 14:39:30 url is https://my.pre-1908-c4c.com/baseurl/api('some-id')
2019/08/06 14:39:30 url is https://my.1908-c4c/baseurl/api%28%27some-id%27%29
```

It seems this behavior was always present in Kyma, it has only manifested after 1908 c4c where the application registration also has the path in the registration url.

**Comment by crabtree** [comment]
Thanks @akrausesap and @abbi-gaurav the fix on the way.
