### ISSUE TITLE
Verify that Kubeless controller to works on Kubernetes 1.15

### ISSUE THREAD

**Issue by Abd4llA** [kyma-project/kyma#5169]
**Description**

Verify that Kubeless controller works on 1.15 and update Kubeless version if needed to have it running on Kubernetes 1.15.

**AC**

- Kubeless controller is running successfully on a Kyma cluster with Kubernetes 1.15 when Kyma is installed.

**Comment by rakesh-garimella** [comment]
The acceptance tests on minikube with k8s version 1.15 ran successfully so this issue can be closed.
