### ISSUE TITLE
Verify that Knative Eventing, Serving & Build work on Kubernetes 1.15

### ISSUE THREAD

**Issue by Abd4llA** [kyma-project/kyma#5170]
**Description**

Verify that Knative components work on 1.15 and update if needed to have it running on Kubernetes 1.15.

**AC**

- Knative Eventing is running successfully on a Kyma cluster with Kubernetes 1.15 when Kyma is installed. 
- Knative Serving is running successfully on a Kyma cluster with Kubernetes 1.15 when Kyma is installed. 
- Knative Build is running successfully on a Kyma cluster with Kubernetes 1.15 when Kyma is installed.

**Comment by rakesh-garimella** [comment]
The accceptance tests on minikube with k8s 1.15 ran successfully. So this issue can be closed.
