### ISSUE TITLE
Upgrade function controller to Kubernetes 1.15

### ISSUE THREAD

**Issue by Abd4llA** [kyma-project/kyma#5171]
**Description**

Upgrade function controller Kubernetes 1.15.

**AC**

- Function controller is running successfully on a Kyma cluster with Kubernetes 1.15 when Kyma is installed.

**Comment by derberg** [comment]
Removed from epic https://github.com/kyma-project/kyma/issues/5077 as it is not related

**Comment by michal-hudy** [comment]
Done.
