### ISSUE TITLE
Use Kyma CLI in kyma integration job

### ISSUE THREAD

**Issue by clebs** [kyma-project/kyma#5182]
**Description**
Replace script logic for the default kyma integration job (gke) to CLI where possible.

- provision gke
- install kyma
- test
- job must pass as before

Furthermore, adjust the existing Kyma CLI integration job to also provision GKE based on CLI

**Reasons**
Kickstart the replacement of  bash scripts in the whole CI infrastructure and verify its viability on a first job before a full replacement.

**Comment by lilitgh** [comment]
Will be tackled in https://github.com/kyma-project/kyma/issues/5183
