### ISSUE TITLE
allow installer to update single package with label

### ISSUE THREAD

**Issue by Morriz** [kyma-project/kyma#5187]
Please don't make us wait for the installer to traverse all its charts when we just need an override on a single chart.

I propose to use two labels:
`k label installation/kyma-installation action=install,chart=logging --overwrite`

**Comment by jakkab** [comment]
Hi @Morriz, thank you for the request. The installation process is about to undergo fundamental restructuring, but you're welcome to prepare a pull request. As a workaround, I suggest reducing the list of Kyma components in CR so that it contains only the ones you need to update.

**Comment by Morriz** [comment]
I get it. That will probably take a long time though, seeing that flux is still to be reviewed.
