### ISSUE TITLE
Configure and introduce crd and api-server release strategies in Service Catalog repo

### ISSUE THREAD

**Issue by mszostok** [kyma-project/kyma#5217]
**Description**

The Service Catalog upstream repo is configured and use release strategies provided from this issue: https://github.com/kyma-project/kyma/issues/4480

**AC**
- move last api-server version from master to separate branch
- release process works both for master and separate api-server branch
- documentation about releasing is up to date

**Comment by adamwalach** [comment]
After the `v0.2` branch is created and CRDs are merged to master we can update wiki.
Edit: https://github.com/kubernetes-sigs/service-catalog/wiki/All-About-Releases
apply changes from this PR: https://github.com/awalach-org/service-catalog.wiki-clone/pull/1

**Comment by mszostok** [comment]
Change the migration script https://github.com/kyma-incubator/service-catalog/pull/43/files#diff-88a381029982980083a0b15f17e1a0dcR70 when service catalog api-server will be released as the `catalog-v2`.
