### ISSUE TITLE
Improve Cloud Events example

### ISSUE THREAD

**Issue by bszwarc** [kyma-project/kyma#5223]
**Description**

The Cloud Events example should be improved to match the examples template.
Example: https://github.com/kyma-incubator/examples/tree/76b7c6e0283ae6f5cec020d90f7a5c92d7e2f32f/cloud-events-e2e-scenario
Template: https://github.com/kyma-project/community/blob/master/guidelines/templates/resources/example_README.md

**Reasons**

Examples should follow the template, even if in Kyma incubator.

**Comment by alexandra-simeonova** [comment]
The Cloud Events and Microservice Events examples were edited to be more consistent with the template and existing examples on the Kyma website. PR: 
https://github.com/kyma-incubator/examples/pull/27

**Comment by bszwarc** [comment]
Closing this one, done months ago :)
