### ISSUE TITLE
Add a test to check E2E tracing results

### ISSUE THREAD

**Issue by sayanh** [kyma-project/kyma#5225]
**Description**

As a follow up to this https://github.com/kyma-project/kyma/issues/4376, the tracing part of this story is not tested. Add a test in `core-test-external-solution` to check tracing results in Jaegar.

**Reasons**

Right now, testing Jaeger is a manual procedure. 

** Workaround **
- Set "PILOT_TRACE_SAMPLING" of deployment "istio-pilot" to "100"
- Deploy a mock
- pair mock to an application and register events and APIs
- Bind the application to a namespace and create service instances accordingly
- Write a lambda listening for an event and calling the API and propagating the trace headers
- Go to the mock and send corresponding event
- See that traces are nice in jaeger

**Comment by pbochynski** [comment]
Please ensure that tracing test covers basic integeration/extensibility scenario:
event coming from application, through our knative-eventing and natss, to lambda which calls application API through application gateway.

**Comment by a-thaler** [comment]
Will be covered by https://github.com/kyma-project/kyma/issues/9631 for now
