### ISSUE TITLE
Compass Runtime Agent should use Application name as a CR name

### ISSUE THREAD

**Issue by Szymongib** [kyma-project/kyma#5227]
**Description**

For now, Compass Runtime Agent uses the Application ID as a name of the Custom Resource. As now the name is guaranteed to be valid Kubernetes name so we can start using it as a name of the CR.

Acceptance:
- Application Name used as a name of CR
- Tests adjusted accordingly

**Comment by janmedrek** [comment]
We also need to remove `app-` prefix in services deployed by Application Operator, it broke contract with some of the connectors and also may influence maximum length of application name.
