### ISSUE TITLE
update event-bus helm chart's json schema

### ISSUE THREAD

**Issue by anishj0shi** [kyma-project/kyma#5250]
https://github.com/kyma-project/kyma/blob/79a10466b7487abaa3bf36cd020c6e9651640261/resources/event-bus/values.schema.json#L10

https://github.com/kyma-project/kyma/blob/79a10466b7487abaa3bf36cd020c6e9651640261/resources/event-bus/values.schema.json#L43

- The above objects have been refactored, their schemas have to be updated as well. 
- some parameters mentioned in values.yaml are not part of this schema, lets introduce them as the schema validation might be mandatory as soon as we start using helm 3

Some Reference:
https://github.com/helm/community/blob/master/helm-v3/001-charts.md#schematized-values-files

**Comment by Abd4llA** [comment]
Will be looked after when Kyma updates to Helm 3
