### ISSUE TITLE
Create periodic job that tests Kyma against kubernetes 1.15

### ISSUE THREAD

**Issue by michal-hudy** [kyma-project/kyma#5252]
**Description**

Create periodic jobs that run once 24h and checks Kyma against 1.15: 
 - job for minikube on 1.15
 - job for GKE on 1.13
 - job for AKS on 1.13

**Reasons**

We support 1.12 and should support 1.15 asap so the move to 1.16 is easier as it brings some important changes - https://kubernetes.io/blog/2019/07/18/api-deprecations-in-1-16/

**Attachments**

#5077

**Comment by derberg** [comment]
Decided together with other maintainers that this is not needed feature
