### ISSUE TITLE
Unable to upgrade k8s to 1.12.6

### ISSUE THREAD

**Issue by rakesh-garimella** [kyma-project/kyma#5257]
**Description**
For my backup and upgrade tests #4498 I need to have k8s 1.12.6. However after updating the version I have following failures in cms controller:

```
# github.com/kyma-project/kyma/tests/end-to-end/upgrade/vendor/github.com/kyma-project/kyma/components/cms-controller-manager/pkg/apis/cms/v1alpha1
vendor/github.com/kyma-project/kyma/components/cms-controller-manager/pkg/apis/cms/v1alpha1/register.go:21:19: undefined: scheme.Builder
# github.com/kyma-project/kyma/tests/end-to-end/upgrade/vendor/github.com/kyma-project/kyma/components/asset-store-controller-manager/pkg/apis/assetstore/v1alpha2
vendor/github.com/kyma-project/kyma/components/asset-store-controller-manager/pkg/apis/assetstore/v1alpha2/register.go:21:19: undefined: scheme.Builder
```

**Comment by michal-hudy** [comment]
I see that it will require more changes, as CMS and Asset Store is based on Kubebuilder. The new version of `controller-runtime` provided lots of breaking changes so if we will migrate to `controller-runtime` v2 we will lose compatibility with Kubebuilder v1 that we are using.

For us better will be migrating to new Kubebuilder (v2) as it is already in beta phase (like controller-runtime)

@derberg what do you think?

**Comment by michal-hudy** [comment]
We agreed with @derberg that we will migrate Asset Store and CMS to new kubebuilder
