### ISSUE TITLE
Use apis.URL in SubscriberSpec.URI in knative/eventing

### ISSUE THREAD

**Issue by sayanh** [kyma-project/kyma#5262]
**Description**

More details are [here](https://github.com/knative/eventing/issues/1498)

**Comment by sayanh** [comment]
[PR](https://github.com/knative/eventing/pull/1691) is created

**Comment by anishj0shi** [comment]
This issue is not valid anymore.  knative eventing has updated subscriber reference to a duck type called **Destination**
