### ISSUE TITLE
Monitoring of Application Gateway

### ISSUE THREAD

**Issue by lszymik** [kyma-project/kyma#527]
**Description**

Application Gateway is a component that is not yet integrated with Prometheus.

**Acceptance criteria:**
- Metrics introduced to the Application Gateway and exposed to Prometheus
  - Metric for tracking internal errors on our side
  - Metric for tracking total response time (our side + proxy target)
  - Metric for tracking response time of external service (proxy target)
- Grafana dashboard for Application Gateway created
- Helm charts updated for Application Gateway
  - ServiceMonitor created
  - Service added for Prometheus metrics

**Stretch Goals:**
- Consider aggregating all Application Connector dashboards into one sub-directory in Grafana.

**Reasons**

The monitoring functionality should be available in the whole Application Connector, not only a part of it.

**Comment by janmedrek** [comment]
We are doing major refactors in Application Gateway, this will be covered in: https://github.com/kyma-project/kyma/issues/10361
