### ISSUE TITLE
Upgrade breaks when helm-certs-job definition is updated

### ISSUE THREAD

**Issue by mwieczorek** [kyma-project/kyma#5272]
**Description**
During upgrade procedure (at least in pre-master-kyma-gke-upgrade job) `installer.yaml`  is applied once again. 
`installer.yaml` contains `helm-certs-job-sa` job definition. Jobs definitions are not mutable. So in case we'd like to change something in the mentioned job in `installer.yaml` - upgrade is broken.
Example: https://github.com/kyma-project/kyma/pull/5264

**Expected result**

New version of kyma can contain modified `helm-certs-job` definition and upgrade passes.

**Actual result**

**Steps to reproduce**

**Troubleshooting**

**Comment by Demonsthere** [comment]
Hi there, since the workaround has been merged, can we close this? Or are some additional actions required?

**Comment by mwieczorek** [comment]
Workaround was applied because such solution (better one) like https://github.com/kyma-project/kyma/pull/5264 won't work. 
And this ticket is more general. 

Basically, you cannot change anything in that job definition (f.e. prow upgrade job will fail). And I guess nothing is set in stone forever. 

So IMO we should not close it.

cc @PK85 (as it will have an impact on compass long-living clusters too)

**Comment by Demonsthere** [comment]
Idea of solution:
Add a cleaner job to cluster-essentials (or other helm chart that runs first), that will remove the job definitions of the cert jobs. 

This is required as the cert jobs are not helm managed, and don't have access to hooks.

**Comment by colunira** [comment]
Issue has been fixed in https://github.com/kyma-project/kyma/pull/7262
