### ISSUE TITLE
Queries & Mutations for API Gateway in CBS

### ISSUE THREAD

**Issue by piotrmsc** [kyma-project/kyma#5297]
**Description**

With new API Gateway #5084 we need to provide all necessary queries and mutations in console backend service (CBS) that will allow listing, fetching by id, creating, updating and deleting new APIs. 

AC:
- Define schemas, queries, mutations
- Implement CRUD + list
- Apply RBAC check (@HassAccess annotations)
- Provide tests ```/tests/console-backend-service/internal/domain/```

**Reasons**

When we provide queries & mutations UI will be unblocked with creating views for new APIs.

**Attachments**

**Comment by kwiatekus** [comment]
Please make sure gql subscriptions are also implemented as we need them to support web-socker connection from the UI
