### ISSUE TITLE
TestServiceBindingUsagePrefixing is unable to get K8S API Server

### ISSUE THREAD

**Issue by piotrmiskiewicz** [kyma-project/kyma#5311]
**Description**
The test TestServiceBindingUsagePrefixing is failing, see:
```
=== RUN TestServiceBindingUsagePrefixing
--- FAIL: TestServiceBindingUsagePrefixing (0.00s)
assertions.go:247: Error Trace:    binding_usage_test.go:263
binding_usage_test.go:60
Error: Received unexpected error:
Post https://10.51.240.1:443/api/v1/namespaces: dial tcp 10.51.240.1:443: connect: connection refused
Test: TestServiceBindingUsagePrefixing
```

**Comment by kubadz** [comment]
The jobs on which the error occured:
https://status.build.kyma-project.io/view/gcs/kyma-prow-logs/logs/post-master-kyma-gke-integration/1161231419117146113
https://status.build.kyma-project.io/view/gcs/kyma-prow-logs/logs/post-master-kyma-gke-integration/1161201219646001152
https://status.build.kyma-project.io/view/gcs/kyma-prow-logs/logs/post-master-kyma-gke-integration/1161232049424568321

**Comment by mszostok** [comment]
will be addressed in: https://github.com/kyma-project/kyma/issues/5375
