### ISSUE TITLE
Runtime Agent must support yaml specs

### ISSUE THREAD

**Issue by akgalwas** [kyma-project/kyma#5317]
**Description**

Application Registry and the Runtime Agent incorrectly  handle YAML API specs.

Kyma Console is able to display specs in the following standards:
- OpenAPI (JSON or YAML)
- OData (XML)

The Console determines the format of specification by checking the extension of a file downloaded from Asset Store. 
Application Registry and the Runtime Agent must provide correct file extension when uploading the file to Asset Store. 

**Expected result**

Specification in YAML format must be displayed in Kyma Console.

**Actual result**
When user provides an API specification in YAML format, the file uploaded to Asset Store have ".json" extension and is not displayed in Console.

**Steps to reproduce**

**Runtime Agent**
1. Register service containing API/EventAPI spec in YAML format using the Director.
2. Wait until the Runtime Agent synchronises.
3. Go to Kyma Console. Find the newly registered service in catalog. Notice the specification is not displayed.

**Troubleshooting**

You can see what the spec file extension is by examining ClusterDocsTopic resource corresponding to a registered service.

**Comment by janmedrek** [comment]
Since we are moving to Compass-based App Connectivity the Application Registry part was dropped.

**Comment by janmedrek** [comment]
As Runtime Agent will be shifting its responsibilities soon and this issue is not blocking we have decided to drop this issue.
