### ISSUE TITLE
Proposal on injecting environment specific parameters as env variables

### ISSUE THREAD

**Issue by akrausesap** [kyma-project/kyma#5332]
**Description**

Dear colleagues,

proposal is to inject these “fixed” values as environment variables into the deployment/function upon binding. The values shall be collected upon Metadata registration. All available values and their significance should be included in the Documentation and Ideally linked to the Open API specification (visually). This process should be optional for applications and not break compatibility.

Cheers

Andreas

**Reasons**

The aim of the Kyma application connectivity is to simplify consumption of application APIs for extension developers. Sometimes these APIs expect values to be encoded in the path or the payload that are static in the context of the use case (e.g. commerce store ID, Qualtrics directory ID, etc.). However these values change between environments (dev, stage, prod) and potentially even scenarios. The Application Gateway component handles every aspect of API consumption in the context of Authorization, CSRF Tokens and static prefixing of Headers and Query Parameters in (reverse) proxy mode. However for payload and path manipulations different mechanisms are required. 

**Attachments**

N/A

**Comment by PK85** [comment]
Nice idea, with Application Broker quite easy to implement. 

Right now we go into direction of using ServiceManager for application connectivity and in that case we cannot influence Service Instance creation. Closing for now.
