### ISSUE TITLE
Function webhook not working when in same namespace as controller

### ISSUE THREAD

**Issue by nachtmaar** [kyma-project/kyma#5336]
**Description**

* Deploy a function in the default namespace => webhook does not work
* Deploy a function in the namespace of the function controller => webhook works

**Comment by rakesh-garimella** [comment]
Currently it works when we are deploying via helm. But when using the development flow its broken.

**Comment by k15r** [comment]
For whatever reason after changing the deploy step to use `ko` i cannot reproduce the error.
