### ISSUE TITLE
Knative Services exposed via Istio return 503 after being scaled down to 0

### ISSUE THREAD

**Issue by rakesh-garimella** [kyma-project/kyma#5352]
**Description**
Sometimes the knative service exposed via istio envoy is returning 503 `upstream connect error or disconnect/reset before headers. reset reason: connection failure%`. This happens occasionally even when the function pod is up and running.

**Expected result**
The function should return properly

**Actual result**
```
* Rebuilt URL to: http://sample.serverless-system.34.76.171.216.xip.io/
*   Trying 34.76.171.216...
* TCP_NODELAY set
* Connected to sample.serverless-system.34.76.171.216.xip.io (34.76.171.216) port 80 (#0)
> GET / HTTP/1.1
> Host: sample.serverless-system.34.76.171.216.xip.io
> User-Agent: curl/7.54.0
> Accept: */*
>
< HTTP/1.1 301 Moved Permanently
< location: https://sample.serverless-system.34.76.171.216.xip.io/
< date: Mon, 19 Aug 2019 13:13:07 GMT
< server: istio-envoy
< content-length: 0
<
* Connection #0 to host sample.serverless-system.34.76.171.216.xip.io left intact
* Issue another request to this URL: 'https://sample.serverless-system.34.76.171.216.xip.io/'
*   Trying 34.76.171.216...
* TCP_NODELAY set
* Connected to sample.serverless-system.34.76.171.216.xip.io (34.76.171.216) port 443 (#1)
* ALPN, offering h2
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/cert.pem
  CApath: none
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Client hello (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS change cipher, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-CHACHA20-POLY1305
* ALPN, server accepted to use h2
* Server certificate:
*  subject: CN=34.76.171.216.xip.io
*  start date: Aug  6 13:12:30 2019 GMT
*  expire date: Sep  5 13:12:30 2019 GMT
*  issuer: CN=34.76.171.216.xip.io
*  SSL certificate verify result: self signed certificate (18), continuing anyway.
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Using Stream ID: 1 (easy handle 0x7fe05a00d600)
> GET / HTTP/2
> Host: sample.serverless-system.34.76.171.216.xip.io
> User-Agent: curl/7.54.0
> Accept: */*
>
* Connection state changed (MAX_CONCURRENT_STREAMS updated)!
< HTTP/2 503
< content-length: 91
< content-type: text/plain
< date: Mon, 19 Aug 2019 13:13:07 GMT
< server: istio-envoy
<
* Connection #1 to host sample.serverless-system.34.76.171.216.xip.io left intact
upstream connect error or disconnect/reset before headers. reset reason: connection failure%
```

**Workaround**

Restart the ingress-gateway pod

`kubectl delete pod -l app=istio-ingressgateway -n istio-system`

**Steps to reproduce**

Deploy `function-controller` in `serverless-controller` namespace.
apply following
```cat<<EOF | kubectl -n serverless-controller apply -f -
apiVersion: serverless.kyma-project.io/v1alpha1
kind: Function
metadata:
  name: sample
  labels:
    foo: bar
spec:
  function: |
    module.exports = {
        main: function(event, context) {
          return 'Hello World'
        }
      }
  functionContentType: "plaintext"
  size: "L"
  runtime: "nodejs8"
EOF
```

**Comment by Tomasz-Smelcerz-SAP** [comment]
I have found an issue in Istio that looks similar: https://github.com/istio/istio/issues/13205
Perhaps playing with "Idle timeout" parameter will help, but this requires investigation.
I am adding this to our backlog.

**Comment by davyodom** [comment]
There are other related Istio issues too https://github.com/istio/istio/issues/16074 .  We've been seeing this and similar problems a lot in various different places, not just the ingress-gateway.  Paul will add more detail here soon, he's been doing quite a bit of research into the problem already.

**Comment by ph721** [comment]
So what are we are seeing is that periodically calls between services in the cluster are failing mTLS due to SSL issues. 

The following are an example logs from the istio-proxy from the calling service:

```
[2019-08-20 20:16:19.159][27][debug][router] [external/envoy/source/common/router/router.cc:332] [C8977][S10986393737205311332] cluster 'outbound|80||df-58ab30f3-c35c-11e9-955f-ce4d1b047f47-f6bpn.kyma-system.svc.cluster.local' match for URL '/'
[2019-08-20 20:16:19.159][27][debug][router] [external/envoy/source/common/router/router.cc:393] [C8977][S10986393737205311332] router decoding headers:
':authority', 'df-58ab30f3-c35c-11e9-955f-ce4d1b047f47.kyma-system.svc.cluster.local'
':path', '/'
':method', 'POST'
':scheme', 'https'
'user-agent', 'Go-http-client/1.1'
'content-length', '89'
'content-type', 'application/json'
'accept-encoding', 'gzip'
'x-forwarded-proto', 'http'
'x-request-id', 'c34c41da-959f-4087-9557-a62a42177b69'
'x-envoy-decorator-operation', 'df-58ab30f3-c35c-11e9-955f-ce4d1b047f47-f6bpn.kyma-system.svc.cluster.local:80/*'
'x-istio-attributes', 'CmkKGGRlc3RpbmF0aW9uLnNlcnZpY2UuaG9zdBJNEktkZi01OGFiMzBmMy1jMzVjLTExZTktOTU1Zi1jZTRkMWIwNDdmNDctZjZicG4ua3ltYS1zeXN0ZW0uc3ZjLmNsdXN0ZXIubG9jYWwKZwoXZGVzdGluYXRpb24uc2VydmljZS51aWQSTBJKaXN0aW86Ly9reW1hLXN5c3RlbS9zZXJ2aWNlcy9kZi01OGFiMzBmMy1jMzVjLTExZTktOTU1Zi1jZTRkMWIwNDdmNDctZjZicG4KSwoYZGVzdGluYXRpb24uc2VydmljZS5uYW1lEi8SLWRmLTU4YWIzMGYzLWMzNWMtMTFlOS05NTVmLWNlNGQxYjA0N2Y0Ny1mNmJwbgouCh1kZXN0aW5hdGlvbi5zZXJ2aWNlLm5hbWVzcGFjZRINEgtreW1hLXN5c3RlbQpoCgpzb3VyY2UudWlkEloSWGt1YmVybmV0ZXM6Ly9kZi01OGFiMzBmMy1jMzVjLTExZTktOTU1Zi1jZTRkMWIwNDdmNDctLXN0YWdlLWRpc3BhdGNoLTZiNDljcWIua3ltYS1zeXN0ZW0='
'x-envoy-expected-rq-timeout-ms', '600000'
'x-b3-traceid', 'b4c851c9a869112f959d7a12a67a6572'
'x-b3-spanid', '959d7a12a67a6572'
'x-b3-sampled', '0'
'knative-serving-namespace', 'kyma-system'
'knative-serving-revision', 'df-58ab30f3-c35c-11e9-955f-ce4d1b047f47-f6bpn'

[2019-08-20 20:16:19.159][27][debug][pool] [external/envoy/source/common/http/http1/conn_pool.cc:88] creating a new connection
[2019-08-20 20:16:19.159][27][debug][client] [external/envoy/source/common/http/codec_client.cc:26] [C8978] connecting
[2019-08-20 20:16:19.159][27][debug][connection] [external/envoy/source/common/network/connection_impl.cc:702] [C8978] connecting to 10.244.2.13:8012
[2019-08-20 20:16:19.159][27][debug][connection] [external/envoy/source/common/network/connection_impl.cc:711] [C8978] connection in progress
[2019-08-20 20:16:19.159][27][debug][pool] [external/envoy/source/common/http/conn_pool_base.cc:20] queueing request due to no available connections
[2019-08-20 20:16:19.159][27][debug][filter] [src/envoy/http/mixer/filter.cc:102] Called Mixer::Filter : decodeData (89, false)
[2019-08-20 20:16:19.159][27][debug][http] [external/envoy/source/common/http/conn_manager_impl.cc:1062] [C8977][S10986393737205311332] request end stream
[2019-08-20 20:16:19.159][27][debug][filter] [src/envoy/http/mixer/filter.cc:102] Called Mixer::Filter : decodeData (0, true)
[2019-08-20 20:16:19.160][27][debug][connection] [external/envoy/source/common/network/connection_impl.cc:550] [C8978] connected
[2019-08-20 20:16:19.160][27][debug][connection] [external/envoy/source/extensions/transport_sockets/tls/ssl_socket.cc:168] [C8978] handshake error: 2
[2019-08-20 20:16:19.162][27][debug][connection] [external/envoy/source/extensions/transport_sockets/tls/ssl_socket.cc:168] [C8978] handshake error: 1
[2019-08-20 20:16:19.162][27][debug][connection] [external/envoy/source/extensions/transport_sockets/tls/ssl_socket.cc:201] [C8978] TLS error: 268435581:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED
[2019-08-20 20:16:19.162][27][debug][connection] [external/envoy/source/common/network/connection_impl.cc:188] [C8978] closing socket: 0
[2019-08-20 20:16:19.162][27][debug][client] [external/envoy/source/common/http/codec_client.cc:82] [C8978] disconnect. resetting 0 pending requests
[2019-08-20 20:16:19.162][27][debug][pool] [external/envoy/source/common/http/http1/conn_pool.cc:129] [C8978] client disconnected, failure reason: TLS error: 268435581:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED
[2019-08-20 20:16:19.162][27][debug][pool] [external/envoy/source/common/http/http1/conn_pool.cc:164] [C8978] purge pending, failure reason: TLS error: 268435581:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED
[2019-08-20 20:16:19.162][27][debug][router] [external/envoy/source/common/router/router.cc:671] [C8977][S10986393737205311332] upstream reset: reset reason connection failure
```

The receiving service istio-proxy doesn't have any logs related to the call.

Killing the pods will often fix the situation for a while.

**Comment by ph721** [comment]
It appears that these issues may be known issues in knative serving.  It looks like the 0.8.x releases fix a lot of 503 related connection issues:

https://github.com/knative/serving/issues/4752

https://github.com/knative/serving/issues/4281

**Comment by sayanh** [comment]
May be solving this https://github.com/kyma-project/kyma/issues/5130 first helps here.

**Comment by k15r** [comment]
during debugging we figured out that:
- you do not have to start the istio gateway, restarting the service-pod is enough. the problem seems to be that the health-check fails which causes some component (istio, the queue-proxy) not send any traffic to the service
- funny effect: service works for the first few seconds, then it fails with the 503, later it works again, as knative-serving scaled to zero, and on the first request it works again as knative-serving starts a new pod

**Comment by tuchengyuan** [comment]
> during debugging we figured out that:
> 
> * you do not have to start the istio gateway, restarting the service-pod is enough. the problem seems to be that the health-check fails which causes some component (istio, the queue-proxy) not send any traffic to the service
> * funny effect: service works for the first few seconds, then it fails with the 503, later it works again, as knative-serving scaled to zero, and on the first request it works again as knative-serving starts a new pod

Same here! And I also find some error message (podautoscaler reason: NoTraffic) as the following

kubectl get knative-internal
NAME                                                           READY   REASON
podautoscaler.autoscaling.internal.knative.dev/helloworld-v1   False   NoTraffic

NAME                                                     AGE
image.caching.internal.knative.dev/helloworld-v1-cache   10m

NAME                                                                                        READY   REASON
clusteringress.networking.internal.knative.dev/route-23db4cbf-d20f-11e9-89ad-080027d22ee3   True    

NAME                                                              SERVICENAME     PRIVATESERVICENAME   READY     REASON
serverlessservice.networking.internal.knative.dev/helloworld-v1   helloworld-v1   helloworld-v1-priv   Unknown   NoHealthyBackends

kubectl get podautoscaler -o yaml
apiVersion: v1
items:
- apiVersion: autoscaling.internal.knative.dev/v1alpha1
  kind: PodAutoscaler
  metadata:
    annotations:
      autoscaling.knative.dev/class: kpa.autoscaling.knative.dev
      autoscaling.knative.dev/metric: concurrency
    creationTimestamp: "2019-09-08T08:03:28Z"
    generation: 1
    labels:
      app: helloworld-v1
      serving.knative.dev/configuration: helloworld
      serving.knative.dev/configurationGeneration: "1"
      serving.knative.dev/revision: helloworld-v1
      serving.knative.dev/revisionUID: 23db63cb-d20f-11e9-89ad-080027d22ee3
      serving.knative.dev/service: helloworld
    name: helloworld-v1
    namespace: default
    ownerReferences:
    - apiVersion: serving.knative.dev/v1alpha1
      blockOwnerDeletion: true
      controller: true
      kind: Revision
      name: helloworld-v1
      uid: 23db63cb-d20f-11e9-89ad-080027d22ee3
    resourceVersion: "51806"
    selfLink: /apis/autoscaling.internal.knative.dev/v1alpha1/namespaces/default/podautoscalers/helloworld-v1
    uid: 23f62b12-d20f-11e9-89ad-080027d22ee3
  spec:
    ProtocolType: http1
    scaleTargetRef:
      apiVersion: apps/v1
      kind: Deployment
      name: helloworld-v1-deployment
    serviceName: ""
  status:
    conditions:
    - lastTransitionTime: "2019-09-08T08:04:54Z"
      message: The target is not receiving traffic.
      reason: NoTraffic
      status: "False"
      type: Active
    - lastTransitionTime: "2019-09-08T08:04:54Z"
      message: The target is not receiving traffic.
      reason: NoTraffic
      status: "False"
      type: Ready
    observedGeneration: 1
    serviceName: helloworld-v1
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""

**Comment by tuchengyuan** [comment]
I found a workaround by setting "autoscaling.knative.dev/class" to "hpa.autoscaling.knative.dev"
now 503 errors gone!

apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: sleepingservice
  namespace: default
spec:
  template:
    metadata:
      annotations:
        # Default: Knative concurrency-based autoscaling with 
        # 100 requests in-flight per pod.
        #autoscaling.knative.dev/class:  kpa.autoscaling.knative.dev
        #autoscaling.knative.dev/metric: concurrency
        # Changed target to 1 to showcase autoscaling
        autoscaling.knative.dev/target: "1"

        # Alternative: Kubernetes CPU-based autoscaling.
        autoscaling.knative.dev/class:  hpa.autoscaling.knative.dev
        autoscaling.knative.dev/metric: cpu
        
        # Disable scale to zero with a minScale of 1.
        autoscaling.knative.dev/minScale: "1"
        # Limit max scaling to 5 pods.
        autoscaling.knative.dev/maxScale: "5"
    spec:
      containers:
        # Replace {username} with your actual DockerHub
        - image: docker.io/{username}/sleepingservice:v1

**Comment by k15r** [comment]
i had some length debugging session with Matt and Nghia. It seems this issue is somehow related to our istio setup. Long story short: there needs to be some documentation created in knative on how to get knative-serving up with an mTLS enabled mesh.

**Comment by gustavovalverde** [comment]
@k15r did you find any workaround to make this work istio and mTLS?

**Comment by k15r** [comment]
@gustavovalverde no, i could not find any workaround that uses the normal autoscaler, yet. Lets see if upgrading to 0.9 fixes it for our setup.

**Comment by michal-hudy** [comment]
@Abd4llA I know that you had some discussion with Knative guys. Do you have any updates?

**Comment by Abd4llA** [comment]
There seems to be a working config that might fix this issue https://github.com/knative/serving/pull/6245 . We will give it a try next release

**Comment by michal-hudy** [comment]
With the current configuration problem no longer exist.

**Comment by Gupta-Amrit** [comment]
@hudymi I am also facing the same issue with kyma 1.17.1. Could you, please, let us know on which version it was fixed ?

**Comment by hudymi** [comment]
Honestly, don't know what is the current implementation of Kyma as I'm not working on this project for almost 1 year. As I remember it is no longer using knative, so it might be related to the current implementation based on something else. 

If I recall correctly it was working fine with Kyma 1.13 (https://kyma-project.io/blog/2020/5/29/release-notes-113), but take in mind that with release 1.14 Kyma dropped usage of knative in serverless.

@kwiatekus could you help here?

**Comment by somaya10** [comment]
We are also seeing the 503s with the activator complaining about `error roundtripping http://x.x.x.x:80/healthz: context deadline exceeded"`. At this point we see no errors in the istio-ingressgateway and no other errors apart from ```1 leaderelection.go:360] Failed to update lock: Operation cannot be fulfilled on leases.coordination.k8s.io "autoscaler-bucket-00-of-01": the object has been modified; please apply your changes to the latest version and try again``` in the autoscaler.
Any leads on how we can dig further?
