### ISSUE TITLE
github.com/golang/lint/golint is mirrored

### ISSUE THREAD

**Issue by magicmatatjahu** [kyma-project/kyma#5362]
**Description**

At this moment `github.com/golang/lint/golint` package is mirrored, and had changed path to `golang.org/x/lint/golint`. In kyma and on other repos we use old version, so we must fix to new, because each job which use `golint` is broken.

Please check example commit, how to fix it: https://github.com/kyma-project/test-infra/commit/7f4913d6864684fbbaa9cce7fc72c138107ecf8a

**Comment by mmitoraj** [comment]
Fixed.
