### ISSUE TITLE
Document an overview for metrics

### ISSUE THREAD

**Issue by bszwarc** [kyma-project/kyma#5387]
**Description**

Create a general **Metrics** topic (type: details) here: https://kyma-project.io/docs/master/components/monitoring/#details-details.
This document should include the following information:
* Information that we collect metrics in Kyma - per component/component type 
* Where to find metrics -   it can be the link to https://kyma-project.io/docs/master/components/monitoring/#architecture-architecture-related-resources or maybe we should just include explicit information that it is always the `metrics` endpoint.
* What metrics are collected:
   * Standard metrics - we can mention the ones available out of the box for each component (CPU Usage, Memory Usage, and so on) 
   * Custom metrics - defined for each component and available out of the box (**to check** if they are really available and configured) - here we would have links to particular **Metrics** topics for each component (if existing, can be added later when docu is ready).
* Links to other useful topics - Grafana dashboard, exposing custom metrics tutorial

**Reasons**
We need a general topic which introduces the metrics topic.

**Comment by mmitoraj** [comment]
- General info that could be added to the doc: `Metrics in Kyma are collected from Pods by Prometheus, and exposed on the `/metrics` endpoint. The metrics allow you to check the current status of a service. You can use the status for further analysis.`
- a PR with drafts of the Asset Store metrics and performance docs -> https://github.com/kyma-project/kyma/pull/5347

**Comment by kazydek** [comment]
This task is no longer needed.
