### ISSUE TITLE
GCP Broker schemas are rendered properly in Service Catalog UI

### ISSUE THREAD

**Issue by mszostok** [kyma-project/kyma#5393]
**Description**

We need to fix schemas, e.g.:
- remove default values like `pcf-sb-${counter.next()}-${time.nano()}` _(check all schemas: provisioning, binding etc)_
- ~add enum to schemas for field Region (and other fields if necessary)~ withdraw, see [PR](https://github.com/GoogleCloudPlatform/gcp-service-broker/pull/525)

**AC**
Create PR to upstream GCP Service Broker which includes:
- create new custom field (e.g. `x-google-generate-expression`) for input variables schema
- move all default values like `pcf-sb-${counter.next()}-${time.nano()}` to the new fields
- delete all default values from the scheme for generating values, remove validation/mandatory rules if exist
- investigate where values from schema are generated on the backend, if in GCP broker then switch field from which values are generated
(for more details see [issue](https://github.com/GoogleCloudPlatform/gcp-service-broker/issues/526) )

**Comment by jasiu001** [comment]
PR with enum for regions/zones are available [here](https://github.com/GoogleCloudPlatform/gcp-service-broker/pull/525)

New issue with question about removing default values from GCP broker you can find [here](https://github.com/GoogleCloudPlatform/gcp-service-broker/issues/526)

**Comment by piotrmiskiewicz** [comment]
Expressions in the default values are not visible in the JSON schema, done by the PR: https://github.com/GoogleCloudPlatform/gcp-service-broker/pull/533
