### ISSUE TITLE
Update GCP Broker in Kyma repo

### ISSUE THREAD

**Issue by mszostok** [kyma-project/kyma#5395]
**Description**
This is the final task of the https://github.com/kyma-project/kyma/issues/5067 epic. 
Finally, we need to just update the GCP Broker in Kyma repo.

**AC**
- and job in helm chart for waiting until docs upload is completed, in the same way as we have in Azure: https://github.com/kyma-project/addons/tree/master/addons/azure-service-broker-0.0.1/chart/azure-service-broker/templates/docu
- check if the broker's documentation is displayed correctly, 
- use broker image with resolved ticked (too short column in the internal storage) GoogleCloudPlatform/gcp-service-broker#500
- update Kyma documentation (remove info about preview)
- add the Addon to the default index.yaml

**Comment by piotrmiskiewicz** [comment]
Update Kyma doc about the broker: https://github.com/kyma-project/kyma/pull/5644

**Comment by piotrmiskiewicz** [comment]
update addons: https://github.com/kyma-project/kyma/pull/5644

**Comment by piotrmiskiewicz** [comment]
blocked by: https://github.com/kyma-project/console/issues/684
