### ISSUE TITLE
We need to clean up orphaned disks after perfromance test run is finished.

### ISSUE THREAD

**Issue by rakesh-garimella** [kyma-project/kyma#5403]
**Description**

After the performance test run we delete kyma cluster but it leaves behind orphaned disks, we need to clean them in periodic fashion

**Comment by derberg** [comment]
There is not enough information in the issue

**Comment by nachtmaar** [comment]
**Background**:

Each performance test run (initiated by the load-generating cluster), will create a new gke cluster.

Further readme: [Kyma Performance Test Introduction](https://github.com/kyma-project/kyma/tree/master/tests/perf)

**How**:
After a performance test run, the k8s cluster is deleted, but probably not the disk.
I guess the logic needs to be added to [this script]
(https://github.com/kyma-project/test-infra/blob/4f9a46c0985c51f987c5c05ae7d144e77d59ceaa/performance-tools/performance-cluster/runner.sh#L137)

Please note that there is another issue, that sometimes even the cluster does not get deleted correctly (see [this](https://github.com/kyma-project/kyma/issues/6535) ticket)
