### ISSUE TITLE
Application Connector tests don't clean up all resources created

### ISSUE THREAD

**Issue by akgalwas** [kyma-project/kyma#5404]
**Description**

It was observed on long running clusters that not all resources created by Application Connectivity tests are removed.   

**Expected result**

It is important that tests remove all allocated resources.

**Actual result**

Some applications were not removed after test is complete.

**Steps to reproduce**

Described behaviour was observed on weekly clusters.

**Troubleshooting**

We need to:
- review Application Connector tests to make sure they remove applications after test is finished
- observe memory and CPU consumption on long running clusters (in case of high node resources consumption test pods may be killed and cleaning code is not executed)

**Comment by janmedrek** [comment]
We would need to verify if this still persists after the switch to compass-based App Connectivity
