### ISSUE TITLE
Tests should be executed only if TestingAddons is properly registered in Helm Broker

### ISSUE THREAD

**Issue by mszostok** [kyma-project/kyma#5413]
**Description**

Modify the [injectTestingAddons](
https://github.com/kyma-project/kyma/blob/b1efcb84c4e9814ae6eb01df9da9664421124f27/installation/scripts/testing-common.sh#L208) function to block test execution until the TestingAddons is registered in Helm Broker.

We should do that by waiting for **ready** phase on ClusterAddonsConfiguration.

**AC**
- tests are executed only if TestingAddons is properly registered in Helm Broker.

**Comment by rakesh-garimella** [comment]
related to this: https://github.com/kyma-project/kyma/issues/5412
