### ISSUE TITLE
Implement autoscaling of functions in function controller

### ISSUE THREAD

**Issue by rakesh-garimella** [kyma-project/kyma#5444]
**Description**

We should leverage the autoscaling provided by knative serving and implement it in our function controllers.

An easy way can be pass on the annotations from function object to serving.
references
https://knative.dev/docs/serving/configuring-the-autoscaler/
https://knative.dev/docs/serving/samples/autoscale-go/index.html

**Reasons**
Everybody wants autoscaling.

**Comment by michal-hudy** [comment]
https://github.com/kyma-project/kyma/issues/7363
