### ISSUE TITLE
There are no tests related to xip based clusters

### ISSUE THREAD

**Issue by mwieczorek** [kyma-project/kyma#5450]
**Description**

In case of changes to xip-patch component a bug may sneak out. F.e. #5390 made an issue with creating clusters with xip based domains (reverted in #5448). It wasn't caught in the presubbmit tests.
xip is in official installation docs so it's good to test if it's working, and not wait a few days before someone will catch it manually.

**Expected result**

Tests are run (presubmit or at least postsubmit).

**Actual result**

No tests are run

**Steps to reproduce**

**Troubleshooting**

**Comment by Demonsthere** [comment]
This is a known problem, as the current state of tests in kyma doesn't allow us to use xip due to poor network resiliency in our tests.

**Comment by tomekpapiernik** [comment]
This issue is covered by https://github.com/kyma-project/test-infra/issues/362
