### ISSUE TITLE
Kyma Local installation failed with Timeout reached

### ISSUE THREAD

**Issue by swarnadeepsaha** [kyma-project/kyma#5451]
**Description**
Local installation of Kyma failing.
Error: Timeout reached while waiting for installation to complete

I am following the steps mentioned here:
https://kyma-project.io/docs/#installation-install-kyma-locally

but, kyma installation always ended up with timed out error.

All other components are successfully installed.
install kyma is always ended up with timeout error 

**Expected result**
Installation Successful 

**Actual result**

  Installing Kyma in version '1.4.1'
- Installation source checked
- Tiller deployed
- Kyma Installer deployed
- Helm configured
- Kyma Installer is installing Kyma
- Waiting for installation to start
- install component cluster-essentials
! install component istio failed, which may be OK. Will retry later...
  To fetch the error logs from the installer, run: kubectl get installation kyma-installation -o go-template --template='{{- range .status.errorLog }}{{printf "%s:\n %s\n" .component .log}}{{- end}}'
  To fetch the application logs from the installer, run: kubectl logs -n kyma-installer -l name=kyma-installer
- install component testing
- install component cluster-essentials
- install component testing
- install component istio-init
X install component istio
Error: Timeout reached while waiting for installation to complete

**Steps to reproduce**
Follow the steps here:
https://kyma-project.io/docs/#installation-install-kyma-locally
 
at the end run: install kyma

**Troubleshooting**
Tried different version of the component in two different version of ubuntu(16.04.04 and 18.04.03)
Also followed the steps mentioned here:
https://kyma-project.io/docs/#troubleshooting-troubleshooting

**Comment by kubadz** [comment]
Hi. Can you please share the full log from installation next time? I have a few suspicions, but I need to know if the timeout occured directly after Istio installation or if there were other logs between. 
Istio always fails at the first time, and that is why the installation started again. But the timeout is set to a quite long time, which is enough for the whole Kyma installation, even with errors. There is however a possibility that with a very slow internet connection or very little resources (CPU, RAM), that time is not enough. I would recommend running minikube with more resources if that is available for you. If not, you can always change the timeout. If you install Kyma from Kyma CLI, you can use `--timeout` flag to adjust it.

**Comment by kubadz** [comment]
As there are no responses I guess that you already was able to run Kyma successfully. 
I am closing the issue for now. If the problem still occurs please let me know and I will reopen it.
