### ISSUE TITLE
Prow job to block release if PR images are present

### ISSUE THREAD

**Issue by sjanota** [kyma-project/kyma#5454]
**Description**
There should be a Prow job to check if Kyma uses `PR-*` images on the release branch. If they are the job must faile; It must be a required check before PR to release branch can be merged.

**Acceptance criteria**
- [x] Guard job is created
- [x] Integration jobs on release branch depend on it
- [ ] Release process docs are updated

**Reasons**
We are changing the release process so components won't be built on the release branch. Because we want to keep the "One PR" functionality we need to make sure that PR images won't get released.

**Comment by derberg** [comment]
@sjanota @crabtree guys what is the status of this one, isn't it done already?

**Comment by crabtree** [comment]
It is already done.
