### ISSUE TITLE
Move RELEASE_VERSION to Kyma repository

### ISSUE THREAD

**Issue by sjanota** [kyma-project/kyma#5457]
**Description**
`RELEASE_VERSION` file should reside in Kyma repository instead of test-infra.

**Acceptance criteria**
- [ ] `RELEASE_VERSION` file is in Kyma repository
- [ ] Release process docs are updated to reflect that change

**Reasons**
It's one of the dependencies needed to remove release branches from the test-infra repository. Also, it is confusing what value should be on what branch. moving it to Kyma will resolve a lot of confusion.

**Comment by kasiakepka** [comment]
Assignign to tooling milestone for now
