### ISSUE TITLE
Script to use official images in place of PR images

### ISSUE THREAD

**Issue by sjanota** [kyma-project/kyma#5458]
**Description**
There should be a script to replace all PR images in charts to their counterparts built from the master branch.

**Acceptance criteria**
- [ ] There is a tool (script or go program) available in test-infra
- [ ] The tool is able to replace all PR images with images from master
- [ ] Release master needs to commit the changes, thus approve it
- [ ] Release process docs are changed to reflect that change

**Reason** 
If there are any PR images on the release branch they need to be manually changed to images built from the master. It is manual work that can be fairly easily automated.

**Comment by pkosiec** [comment]
I'm pasting my idea from https://github.com/kyma-project/community/issues/339, how it could work:

1. Update post-master jobs for all components, to not only build images with commit hashes, but also tag them with a tag like `post-PR-XXX`.

The script/ Go program could work like this:
1. Find all occurrences for PR-XXX
1. Construct image path eu.gcr.io/kyma-project/component-name:post-PR-XXX
1. Use Docker registry API to get all tags for a given image
1. Pick commit hash tag and put it in the `values.yaml` files

**Comment by derberg** [comment]
@lilitgh hey, you removed WIP but my comment was not answered

**Comment by sjanota** [comment]
The release process is OK now without putting the effort in this script. Closing it for now. If you find it relevant someday, please reopen.
