### ISSUE TITLE
REB: Provisioning 2 the same service instances in the same namespace ends up with errors in logs

### ISSUE THREAD

**Issue by aszecowka** [kyma-project/kyma#546]
**Description**

Provisioning 2 Service Instances which refers to the same class ends up with an error:

```
{"level":"info","log":{"message":"started handling request","method":"PUT","remote":"172.17.0.43:43010","request":"/v2/service_instances/4e6cbcf8-b1d6-11e8-ab30-0242ac11002c?accepts_incomplete=true","time":"2018-09-06T13:11:11.748Z"}}
{"level":"warning","log":{"message":"Server responds with error: [HTTP 400]: [while inserting instance to storage: element already exists] []","service":"broker:server","time":"2018-09-06T13:11:11.748Z"}}
```

Also please check if it is possible to provision service instance, remove it, and again provision.

Issue was solved by adding remote environment mapping. But UI has wrong status which says:
```
Error provisioning ServiceInstance of ClusterServiceClass (K8S: "1be3f3e2-877e-45ed-a6df-b7816eab2e1d" ExternalName: "ec-ycommercewebservices-v2-cc88c") at ClusterServiceBroker "core-remote-environment-broker": Status: 400; ErrorMessage: while inserting instance to storage: element already exists; Description: ; ResponseError: <nil>
```
and logs from SC:
```
{"level":"info","log":{"action":"getLastOperation","instance:id":"2b8c4766-b1d1-11e8-a20a-8e991afadd5d","message":"action response","operation:id":"01CPQE0H4P28KRN6M23P3KWGAP","resp:operation:desc":"Forbidden provisioning instance [2b8c4766-b1d1-11e8-a20a-8e991afadd5d] for remote environment [id: 18cd5ed0-26d6-403e-a482-12bcd3ae216e] in namespace: [stage]. Reason: [EnvironmentMapping does not exist in the [stage] namespace]","resp:operation:state":"failed","service":"broker:server","time":"2018-09-06T12:35:21.286Z"}}
```

See how it was solved in HelmBroker: https://github.com/kyma-project/kyma/pull/2573 
Additional option to check:
* check ServiceCatalog responseCodes for lastOperation, check what we return in such a case in application-broker
* check if we can clear a cache when lastOperation permanently says fail. If SC will ask again return proper status code.

**Acceptance Criteria**
- apply a fix
- check orphanMitigation, how long/many times will be in progress, check how to configureOrphanMitigation
- document how orphanMitigation works in case of second not allowed instance

**Comment by PK85** [comment]
ok, issue was solved by adding remote environment mapping. But UI status says:
```
Error provisioning ServiceInstance of ClusterServiceClass (K8S: "1be3f3e2-877e-45ed-a6df-b7816eab2e1d" ExternalName: "ec-ycommercewebservices-v2-cc88c") at ClusterServiceBroker "core-remote-environment-broker": Status: 400; ErrorMessage: while inserting instance to storage: element already exists; Description: ; ResponseError: <nil>
```

and logs from SC:
```
{"level":"info","log":{"action":"getLastOperation","instance:id":"2b8c4766-b1d1-11e8-a20a-8e991afadd5d","message":"action response","operation:id":"01CPQE0H4P28KRN6M23P3KWGAP","resp:operation:desc":"Forbidden provisioning instance [2b8c4766-b1d1-11e8-a20a-8e991afadd5d] for remote environment [id: 18cd5ed0-26d6-403e-a482-12bcd3ae216e] in namespace: [stage]. Reason: [EnvironmentMapping does not exist in the [stage] namespace]","resp:operation:state":"failed","service":"broker:server","time":"2018-09-06T12:35:21.286Z"}}
```

**Comment by PK85** [comment]
two options to check:
- check ServiceCatalog responseCodes for lastOperation, check what we return in such a case in helm-broker
- check if we can clear a cache when lastOperation permanently says fail. If SC will ask again return proper status code.

**Comment by adamwalach** [comment]
In the meantime ServiceCatalog changed the orphan mitigation:
https://github.com/kubernetes-incubator/service-catalog/pull/2520

**Comment by adamwalach** [comment]
The issue in ApplicationBroker was a bit different than in HelmBroker. The `isDeprovisioned` [function](https://github.com/kyma-project/kyma/blob/release-0.7/components/application-broker/internal/broker/state.go#L64) was checking for any successful deprovision operation (and there can be some from previous provision/deprovision cycles) for a given instance. It happens because SC keeps the same InstanceID during the retry operation. In the fixed version we check the status only of the last operation.

**Comment by adamwalach** [comment]
* check ServiceCatalog responseCodes for lastOperation, check what we return in such a case in application-broker
**>** in [lastOperation handler](https://github.com/kyma-project/kyma/blob/release-0.6/components/application-broker/internal/broker/server.go#L295) we respond with code 200, only in case of an error (ie. could not find the operation) we return codes 4XX.
 
TODO
* check if we can clear a cache when lastOperation permanently says fail. If SC will ask again return proper status code.

**Acceptance Criteria**

* apply a fix
* check orphanMitigation, how long/many times will be in progress, check how to configureOrphanMitigation
* document how orphanMitigation works in case of second not allowed instance
