### ISSUE TITLE
Test coverage metrics

### ISSUE THREAD

**Issue by clebs** [kyma-project/kyma#5474]
**Description**
Coverage from unit and end to end tests needs to be generated and stored so that we can see the quality of our code and see its evolution.

**Acceptance**
- Test coverage is periodically measured by CI/CD.
- Coverage data is stored in the quality metrics storage with an appropriate format.
- Coverage data is queryable.

**Related issues**
#5473

**Comment by clebs** [comment]
Coverage data will be stored and queriable after #5473.

**Comment by franpog859** [comment]
Hey! Printing test coverage introduced in [this PR](https://github.com/kyma-project/kyma/pull/5568) lefts the `cover.out` file not removed if the tests failed. I suggest to delete them in this case or add a line to the `.gitignore` file.

To reproduce it, go to for example [this file](https://github.com/kyma-project/kyma/blob/master/components/compass-runtime-agent/internal/kyma/service_test.go) and add a line
```go
require.True(t, false)
```
somewhere in the test and run [`before-commit.sh` script](https://github.com/kyma-project/kyma/blob/master/components/compass-runtime-agent/before-commit.sh)

**Comment by lilitgh** [comment]
@franpog859, thanks for reporting this. I created a bug for this issue (https://github.com/kyma-project/kyma/issues/5715) and I am closing this one again.
