### ISSUE TITLE
All Kyma components use generic prow job

### ISSUE THREAD

**Issue by sjanota** [kyma-project/kyma#5481]
**Description**
All Kyma components must be adjusted so they:
- expose a make target `release`
- use common makefile whenever possible
- use docker to vendor build process dependencies
- are built using generic prow job with docker only

A migration guide below explains those steps in detail.

**Acceptance criteria**
- [ ] All Kyma components are built using a generic job.
- [ ] Release process docs are adjusted to mention that those components don't have to be released anymore. 

**Reasons**
This will greatly decrease the number of checks we have on CI as there will be only 2 jobs per component instead of 5. 

**Migration Guide**
1. Create a PR to test-infra with a new optional job for the component and merge it. Example: https://github.com/kyma-project/test-infra/pull/1472. Run this command to generate jobs:
```
go run development/tools/cmd/rendertemplates/main.go --config templates/config.yaml
```
2. Create a PR with the refactoring of a component:
   * remove before-commit.sh
   * Adapt Makefile to use `./scripts/go-dep.mk` or other generic makefile. 
   * By default `test`, `check-fmt` and `check-imports` targets are run on CI. If you need any additional checks, add `verify:: target1 target2` to your Makefile. If those checks are not yet implemented in generic makefile add them.
   * If you're missing a tool in a buildpack and there is a high chance it will be used elsewhere **in the same version** go ahead and add it to buildapck.

   Example: https://github.com/kyma-project/kyma/pull/5628
3. When everything is green create the second PR to test-infra, where the old job is marked deprecated, and a new one is required. Merge it. Example: https://github.com/kyma-project/test-infra/pull/1507
4. Rerun all tests on the PR with Makefile. When they are green merge it.

**Comment by sjanota** [comment]
**Migration Guide**
1. Create a PR to test-infra with a new optional job for the component and merge it. Example: https://github.com/kyma-project/test-infra/pull/1472
2. Create a PR with refactoring of a component:
  * remove before-commit.sh
  * Adapt Makefile to use `./scripts/go-dep.mk` or other generic makefile. Example: https://github.com/sjanota/kyma/pull/7
3. When everything is green create the second PR to test-infra, where the old job is marked deprecated, and new one is required. Merge it.
4. Rerun all tests on the PR with Makefile. When they are green merge it.

**Comment by dbadura** [comment]
Hi,
I merged this PR with readme to generic makefile and changed the location of the makefile.
https://github.com/kyma-project/kyma/pull/6047
