### ISSUE TITLE
Test stability metrics

### ISSUE THREAD

**Issue by clebs** [kyma-project/kyma#5484]
**Description**
Collecting information on the stability of tests will give valuable insights on the robustness of our code and uncover hard to find bugs.

**Acceptance**
- Gather information on successful and failed tests periodically.
- Test stability data is queryable.

**Related issues**
#5473

**Comment by derberg** [comment]
@clebs looking on all the other activities in this area, is this one still valid?

**Comment by michal-hudy** [comment]
Is this still needed? We can track integration tests in TestGrid: https://testgrid.k8s.io/kyma-postsubmit. In my opinion this issue can be closed, @clebs?

**Comment by lilitgh** [comment]
We can close it, also confirmed with @clebs.
