### ISSUE TITLE
Hydroform implementation

### ISSUE THREAD

**Issue by clebs** [kyma-project/kyma#5492]
**Description**
Implement the provisioning API following the design described in the proposal on the community repository.

**Acceptance**
- Provisioing API is implemented following specs.
- GKE clusters can be provisioned/deprovisioned using the API.
- Provisioning API is built and tested in our CI/CD.

**Comment by suleymanakbas91** [comment]
The repo has been created: https://github.com/kyma-incubator/hydroform

**Comment by iancrowther** [comment]
I have a look at ```design described in the proposal on the community repository``` and could not see any designs.  

Are these private?
