### ISSUE TITLE
Provision application-gateway with --skipVerify=true

### ISSUE THREAD

**Issue by johnkbarrow** [kyma-project/kyma#5509]
**Description**
You can override the --skipVerify flag for an application gateway instance once the Application has been created with a kubectl patch. It would be nice if this flag could be set to true when you create the Application.

**Reasons**
You need to set --skipVerify=true if you want to connect a local SAP Commerce Cloud instance with a local Kyma instance.
See https://www.sap.com/cxworks/article/468901527/Working_with_Local_Instances_of_SAP_Commerce_Cloud_and_Project_Kyma

**Attachments**

**Comment by ralikio** [comment]
Feature implemented and merged in https://github.com/kyma-project/kyma/pull/10289.
