### ISSUE TITLE
Upgrade Process is overwriting custom Dex Configuration

### ISSUE THREAD

**Issue by joek** [kyma-project/kyma#5515]
**Description**

When I am adjusting the dex configuration to configure e.g. another authentication provider, the configuration is overwritten during upgrade.

**Expected result**
The Configuration should stay as it is.

**Actual result**

Configuration is overwritten.
For what ever reason it seems the certificate is overwritten too.

**Steps to reproduce**

Install Kyma cluster via SAP CX Cockpit and run upgrade to next version.

**Troubleshooting**

Backup files first, run upgrade, restore.
Have not found any possibility to configure dex via installer.

**Comment by Tomasz-Smelcerz-SAP** [comment]
@joek How do you adjust dex configuration? By manually editing dex-config ConfigMap, or the chart template before Kyma installation?

**Comment by joek** [comment]
@Tomasz-Smelcerz-SAP I will provide you the related faros step which is doing it. (because I don't have a clue)... Beside that, some customers will adjust the dex config manual to add new clients or provide their own IAS tenant.

**Comment by Demonsthere** [comment]
Current manual workaround:
- Before upgrade make a backup of the current dex-configmap
- Perform the kyma upgrade
- Update the re-generated configmap with your desired values (`kubectl edit`)
- Restart dex pod

In the meanwhile, we will work on expanding the upgrade process to be more resilient in such cases

**Comment by Demonsthere** [comment]
Our recommendation: we have merged a new mechanism in dex which will allow putting more config as values. Using this, we can define connectors and clients as overrides, ad re-use them during upgrade.
However, as this will be released with the new version of kyma, please for now use
`helm rollback dex` as a fix. This will rollback dex to the previous version.

**Comment by Demonsthere** [comment]
@joek Do you think this can be closed now?

**Comment by joek** [comment]
Awesome!!
