### ISSUE TITLE
Use upstream Service Catalog 0.3.0 (CRD only) in Kyma

### ISSUE THREAD

**Issue by PK85** [kyma-project/kyma#5524]
**Description**

Use upstream Service Catalog 0.3.0 (CRD only) in Kyma.

**Reasons**

Finally no ETCD and API-Server in Kyma for Service Catalog component

**AC**

- Kyma has updated and cleanuped chart.
- update service-catalog clients in all components that users SC (appBroker, SBU, CBS)
- adjust kyma-project documentation (if we mentioned there etcd/api-server things)

**Comment by adamwalach** [comment]
Components:
- Application Broker - https://github.com/kyma-project/kyma/pull/5687
- Service Binding Usage Controller - https://github.com/kyma-project/kyma/pull/5693
- Console Backend Service
   - Removed Kubeless (requires older version of k8s than we can support) - is not really neded anymore. 
   I encountered this issue: https://github.com/kyma-project/test-infra/issues/1502
   -
