### ISSUE TITLE
Adjust components to Kubernetes 1.16

### ISSUE THREAD

**Issue by michal-hudy** [kyma-project/kyma#5530]
**Description**

With Kubernetes 1.16 some resources are removed (https://kubernetes.io/blog/2019/07/18/api-deprecations-in-1-16/), so some adjustments are needed in Kyma, as deprecated APIs are used.

Here is a list of needed changes:

do tasks from proposal too https://github.com/kyma-project/community/pull/357/files

### Installer
  - Deployment: `extensions/v1beta1` -> `apps/v1`
    - installation/resources/installer-local.yaml
    - installation/resources/installer.yaml
    - installation/resources/tiller.yaml

### Application Connector Ingress
  - DaemonSet: `extensions/v1beta1` -> `apps/v1`
    - resources/application-connector-ingress/charts/nginx-ingress/templates/controller-daemonset.yaml
  - Deployment: `extensions/v1beta1`, `apps/v1beta1` -> `apps/v1`
    - resources/application-connector-ingress/charts/nginx-ingress/templates/controller-deployment.yaml
    - resources/application-connector-ingress/charts/nginx-ingress/templates/default-backend-deployment.yaml
    - resources/application-connector-ingress/charts/nginx-ingress/templates/controller-hpa.yaml
  - PodSecurityPolicy: `extensions/v1beta1` -> `policy/v1beta1`
    - resources/application-connector-ingress/charts/nginx-ingress/templates/podsecuritypolicy.yaml

### Application Connector
  - Deployment: `extensions/v1beta1` -> `apps/v1`
    - resources/application-connector/charts/application-broker/templates/deployment.yaml

### Asset Store
  - Deployment: `extensions/v1beta1`, `apps/v1beta1`, `apps/v1beta2` -> `apps/v1`
    - resources/assetstore/charts/asset-metadata-service/templates/deployment.yaml
    - resources/assetstore/charts/asset-upload-service/templates/deployment.yaml
    - resources/assetstore/charts/minio/templates/deployment.yaml
  - StatefulSet `apps/v1beta1` -> `apps/v1`
    - resources/assetstore/charts/minio/templates/statefulset.yaml
  - Ingress: `extensions/v1beta1` -> `networking.k8s.io/v1beta1`
    - resources/assetstore/charts/minio/templates/ingress.yaml

### CMS
  - Deployment: `extensions/v1beta1` -> `apps/v1`
    - resources/cms/charts/cms-asyncapi-service/templates/deployment.yaml

### Compass
  - Deployment: `apps/v1beta2` -> `apps/v1`
    - resources/compass/charts/cockpit/templates/deployment.yaml
    - resources/compass/charts/director/templates/deployment.yaml
    - resources/compass/charts/gateway/templates/deployment.yaml
    - resources/compass/charts/healthchecker/templates/deployment.yaml
  - StatefulSet:
    - resources/compass/charts/postgresql/templates/statefulset-slaves.yaml
    - resources/compass/charts/postgresql/templates/statefulset.yaml
    - resources/nats-streaming/templates/statefulset.yaml

### Console Backend Service
  - Deployment: `extensions/v1beta1`, `apps/v1beta1` -> `apps/v1`
    - resources/core/charts/console-backend-service/templates/deployment.yaml
    - components/console-backend-service/contrib/examples/service-catalog-test-data.yaml

### Console
  - Deployment: `extensions/v1beta1` -> `apps/v1`
    - resources/core/charts/console/templates/deployment.yaml

### Content UI
  - Deployment: `extensions/v1beta1` -> `apps/v1`
    - resources/core/charts/docs/charts/content-ui/templates/deployment.yaml

### Lambdas UI
  - Deployment: `extensions/v1beta1` -> `apps/v1`
    - resources/core/charts/kubeless/charts/lambdas-ui/templates/deployment.yaml

### Prometheus Operator
  - Deployment: `apps/v1beta1` -> `apps/v1`
    - resources/prometheus-operator/templates/deployment.yaml

### Kubeless
  - Deployment: `apps/v1beta1` -> `apps/v1`
    - resources/core/charts/kubeless/templates/kubeless-controller-deployment.yaml

### Addons UI
  - Deployment: `extensions/v1beta1` -> `apps/v1`
    - resources/helm-broker/charts/addons-ui/templates/deployment.yaml

### Helm Broker
  - Deployment: `extensions/v1beta1` -> `apps/v1`
    - resources/helm-broker/templates/deploy.yaml

### Istio
  - Ingress: `extensions/v1beta1` -> `networking.k8s.io/v1beta1`
    - resources/istio/charts/grafana/templates/ingress.yaml
    - resources/istio/charts/kiali/templates/ingress.yaml
    - resources/istio/charts/prometheus/templates/ingress.yaml
    - resources/istio/charts/tracing/templates/ingress.yaml

### Jaeger
  - Deployment: `extensions/v1beta1` -> `apps/v1`
    - resources/jaeger/templates/deployment.yaml

### Kiali
  - Deployment: `extensions/v1beta1` -> `apps/v1`
    - resources/kiali/templates/deployment.yaml

### Logging
  - Deployment: `extensions/v1beta1` -> `apps/v1`
    - resources/logging/charts/log-ui/templates/deployment.yaml

### Monitoring
  - Deployment: `extensions/v1beta1` -> `apps/v1`
    - resources/monitoring/charts/exporter-kube-state/templates/deployment.yaml
  - DaemonSet: `extensions/v1beta1` -> `apps/v1`
    - resources/monitoring/charts/exporter-node/templates/daemonset.yaml

### Ory
  - Ingress: `extensions/v1beta1` -> `networking.k8s.io/v1beta1`
    - resources/ory/charts/hydra/templates/ingress-admin.yaml
    - resources/ory/charts/hydra/templates/ingress-public.yaml
    - resources/ory/charts/oathkeeper/templates/ingress-api.yaml
    - resources/ory/charts/oathkeeper/templates/ingress-proxy.yaml

### Service Catalog Addons
  - Deployment: `extensions/v1beta1` -> `apps/v1`
    - resources/service-catalog-addons/charts/service-binding-usage-controller/templates/deployment.yaml
    - resources/service-catalog-addons/charts/service-catalog-ui/templates/deployment.yaml

### Service Catalog
  - Deployment: `extensions/v1beta1` -> `apps/v1`
    - resources/service-catalog/charts/catalog-crds/templates/controller-manager-deployment.yaml
    - resources/service-catalog/charts/catalog/templates/apiserver-deployment.yaml
    - resources/service-catalog/charts/catalog/templates/controller-manager-deployment.yaml

### Service Binding Usage
  - Deployment: `apps/v1beta1` -> `apps/v1`
    - components/service-binding-usage-controller/examples/deploy/redis-client.yaml

### Event Bus Tests
  - Deployment: `extensions/v1beta1` -> `apps/v1`
    - tests/perf/prerequisites/event-bus/event-subscriber.yaml

### Performance Tests
  - Deployment: `extensions/v1beta1`, `apps/v1beta1` -> `apps/v1`
    - tests/perf/prerequisites/examples/example.yaml
    - tests/perf/prerequisites/serverless/function-size-l.yaml
    - tests/perf/prerequisites/serverless/function-size-m.yaml
    - tests/perf/prerequisites/serverless/function-size-s.yaml
    - tests/perf/prerequisites/serverless/function-size-xl.yaml
    - tools/load-test/k8syaml/function.yaml

**Reasons**

**Attachments**

**Comment by michal-hudy** [comment]
Update for official MinIO chart: https://github.com/helm/charts/pull/17072

**Comment by derberg** [comment]
@michal-hudy discussed with @a-thaler 
Prometheus is already done
Jaeger and Kiali, I close tickets for now, for this epic we will make changes directly in our copies of the chart and in future once there is some more work in those charts needed, they will be upgraded to latest versions.
