### ISSUE TITLE
Improve experience of rendering of large specifications of connected applications

### ISSUE THREAD

**Issue by derberg** [kyma-project/kyma#5533]
**Description**

- recognize the size of the spec before it is rendered in the UI
- have proper handling in UI and tests for the future
- make sure docs have all the info
- make sure hcms shares proper info in custom resources

**Reasons**

Depending on the integration, different APIs are designed differently and some of them can be really large. Good example from OData is that [this XML](https://github.com/SAP/xf-application-mocks/blob/master/c4c-mock/apis/API_SRV.xml) is 2MB large and has over 20k of lines. But this is not the case with OData only, it is possible to have very large specs even for Open API, like [this one](https://tripletex.no/v2/swagger.json) around 500KB.

We need to make sure the UI works no matter of the size of the spec:
- we can take the approach of GitHub like [here](https://github.com/SAP/xf-application-mocks/blob/master/c4c-mock/apis/API_SRV.xml), so not render because of the size and give link to raw data.
- or try to handle everything with proper spinner and loading

**Comment by derberg** [comment]
My point of view on the subject:
- https://github.com/kyma-incubator/documentation-component/ should not care about this kind of issue. 
  - It should make sure it is written well and handles all without errors
  - it should provide proper pluggability that during integration you can, for example, decide that all the components should be collapsed and not expanded, or that you recognize the size of file upfront and instead of rendering spec you display an error you want
- in console I would go with GitHub approach first, and make sure headless cms stores information about the size of the spec. We only need to agree on the size

**Comment by aerfio** [comment]
I agree with @derberg

From your comment
>that all the components should be collapsed and not expanded

I conclude that we'd like some kind of flag/props for our components to make them render with collapsed/expanded state on mount, yeah?

And considering size of specs - if we decide on showing such large spec we definitely have to find a way to show some kind of spinner/loading animation.

Maybe we can have separate flag for this functionality as well, I mean loading/showing spec-size like github

**Comment by kwiatekus** [comment]
The spec rendering will be part of control-plane UI.
We will not invest in this issue.
