### ISSUE TITLE
Adapt dev docs on Prow to reflect templates

### ISSUE THREAD

**Issue by sjanota** [kyma-project/kyma#5563]
**Description**
`test-infra` documentation got out of sync when templates were introduced. They must be revisited to add new information and remove sections no longer valid. 

**Reasons**
Templates are not as simple as raw jobs and developers need clarification on how to develop and use them.

**Comment by kazydek** [comment]
Doc changes include: 
- README.md for the Render Templates tool used to generate files (jobs) using templates
