### ISSUE TITLE
Compass-agent-configuration job should not run on standalone compass cluster

### ISSUE THREAD

**Issue by mwieczorek** [kyma-project/kyma#5566]
**Description**

By default a job defined here: https://github.com/kyma-project/kyma/blob/master/resources/compass/templates/agent-configuration-job.yaml is run even on 'compass-only' (managed service) cluster. (confirmed with @pkosiec )
It should be possible to turn it off in helm values file (so also in overrides).

cc @PK85 (as author of https://github.com/kyma-project/kyma/pull/5218)

**Expected result**

**Actual result**

**Steps to reproduce**

**Troubleshooting**

**Comment by PK85** [comment]
We need to add a flag, compass-only and if true then job is skipped from chart
