### ISSUE TITLE
Secure API doesn't work as expected for microservices

### ISSUE THREAD

**Issue by mcansimsek** [kyma-project/kyma#5576]
Hi,

I deployed a microservice on Kyma and I exposed it via API with secure option. I didn't change the default IDP and JWKS URL. I can access the API without any authentication. 

On the other hand, Secure API is working for lambdas. 

Thanks,
Mustafa Can

**Comment by mcansimsek** [comment]
Hi @piotrmsc 

I provided API definition, virtual service definition, logs of api controller, policy definition and logs of istio sidecar container below :)

[api.txt](https://github.com/kyma-project/kyma/files/3609298/api.txt)
[virtualservice.txt](https://github.com/kyma-project/kyma/files/3609303/virtualservice.txt)
[logs-apicontroller.txt](https://github.com/kyma-project/kyma/files/3609309/logs-apicontroller.txt)
[policy.txt](https://github.com/kyma-project/kyma/files/3609318/policy.txt)
[logs-istio-sidecar-container.txt](https://github.com/kyma-project/kyma/files/3609328/logs-istio-sidecar-container.txt)

**Comment by piotrmsc** [comment]
Ok, here everything looks good. Have you tried to restart your application? And maybe you can join our publickslack and we could have a discuss there as well (quicker)

**Comment by piotrmsc** [comment]
Update: 
API is working, confirmed by @mcansimsek .

Problem was with incorrect k8s service definition (not named port). It resulted in envoy not having filter with JWKS config inlined. Without that it was not validating JWT.

More about port naming can be found here : 
https://github.com/kyma-project/kyma/issues/5576

I'm closing this issue as it is not related to api controller.
