### ISSUE TITLE
Clean AddonsConfigurations deprecated URLs field in CBS

### ISSUE THREAD

**Issue by polskikiel** [kyma-project/kyma#5587]
**Description**

In the Console Backend Service we have a deprecated implementation in `servicecatalogaddons/(cluster)addonsconfigurations` which use `URLs` input parameter.

After Console migrate to the `repository` field we need to clean CBS from our deprecated implementation.

**Comment by mszostok** [comment]
@polskikiel please link issue created by UI team so we will know when to remove that thing

**Comment by polskikiel** [comment]
TODO after this issue is done: https://github.com/kyma-project/console/issues/1256
