### ISSUE TITLE
Create instructions for updating SSL certificate

### ISSUE THREAD

**Issue by tomekpapiernik** [kyma-project/kyma#5599]
**Description**

In the current setup, the Kyma SSL cert. expires after 30 days. There's no documentation that shows how to update an expired certificate - either `xip.io` wildcard or an user-provided one.

**Reasons**

People might be running Kyma deployments that are over 1 month old. This issue came up in the community as well -> [click](https://kyma-community.slack.com/archives/CD1C94ZKP/p1568103971006900)

**Attachments**

None

**Comment by kubadz** [comment]
I described one possible way to do that [here](https://kyma-community.slack.com/archives/CD1C94ZKP/p1568123657009400?thread_ts=1568103971.006900&cid=CD1C94ZKP). We may use it to create a proper troubleshooting guide in Kyma docs.

**Comment by tomekpapiernik** [comment]
Check if the described procedure updates certs. in all components. There's a chance one will have to restart the components that do not "notice" the new certificate automatically.

**Comment by Gupta-Amrit** [comment]
Hi @kubadz I followed this steps(https://kyma-project.io/docs/components/security#tutorials-update-tls-certificate-steps) and its working fine. But is there any way to extend the self signed certificate expiry date from 30 days to 1 year ?
