### ISSUE TITLE
Knative Controller Infinite Update When Multiple Subscriptions Per Channel

### ISSUE THREAD

**Issue by tminke** [kyma-project/kyma#5603]
**Description**

Creating multiple Knative Subscriptions for a single Channel, will result in the NATSS dispatcher / controller (and really all controllers) to be endlessly notified of changes and thus performing reconciliation.  Have verified this on the standard Kyma/Knative NATSS controller and our own custom controller on both Kyma 1.3 (GCP) and Kyma 1.4 (Azure) clusters.

The controllers are spinning because the Knative Channels are constantly being **updated** so that the order of the **channel.spec.subscribable.subscribers** changes.  It is obviously very inefficient to have the controller constantly consuming CPU unnecessarily.

**Expected result**

As it was in earlier versions of Kyma the Knative controllers should not be endlessly detecting changes to the Knative Channel.

**Actual result**

Knative controllers (NATSS, etc) perform constant / endless / unnecessary reconciliation because the Knative Channel is constantly being updated.

**Steps to reproduce**

Create a Knative Channel and then 2 or 3 Subscriptions for the channel and tail the logs of the Knative NATSS controller/dispatcher.  See the endless reconciliation scroll by.

**Troubleshooting**

Largely we've been avoiding creating multiple subscribers or just dealing with the excessive CPU consumption.

**Comment by Abd4llA** [comment]
@montaro can you please check if it's still happening after #5526 ?

**Comment by tminke** [comment]
Confirmed that this is no longer an issue in Kyma 1.6 with our custom Knative Eventing Channel/Controller - OK to close.

**Comment by Abd4llA** [comment]
Was fixed
