### ISSUE TITLE
Provide set of CRs for Compass Integraton

### ISSUE THREAD

**Issue by Demonsthere** [kyma-project/kyma#5609]
**Description**

Provide a set of CRs for (temporary) manual integration. This CRs should be divided in sets, each representing one required auth scenario. 
Required scenarios:
- Certificate
- OAUTH Token
- JWT Token

**Comment by kubadz** [comment]
Two of the mentioned scenarios (OAUTH Token
and JWT Token) were enabled in PR: https://github.com/kyma-project/kyma/pull/5643, whereas scenario for securing Compass using Certificates was enabled in PR: https://github.com/kyma-project/kyma/pull/5604.
