### ISSUE TITLE
Provide documentation for subcomponents management mechanism

### ISSUE THREAD

**Issue by crabtree** [kyma-project/kyma#562]
There is mechanism that handles enabling/disabling subcomponents. Provide some detailed description how it works and how to use it on local and cluster runs.

**Comment by jakkab** [comment]
### Disable and enable core components

  It is up to the user to decide which sub-components will be installed as parts of the `core` release. By default, most of the core components are enabled. To specify whether to install a core component, use the [`manage-component.sh`](../../installation/scripts/manage-component.sh) script before triggering the Kyma installation. The script consumes two parameters:

  - name of the core component
  - a Boolean value that determines whether the component should be installed (true) or not (false)

  Example:

  To enable the `Azure Broker` component, run the following command:
  ```
  ./manage-component.sh azure-broker true
  ```

  Alternatively, to disable the component, run
  ```
  ./manage-component.sh azure-broker false
  ```
