### ISSUE TITLE
Add global test coverage percentage

### ISSUE THREAD

**Issue by clebs** [kyma-project/kyma#5626]
**Description**
Currently, each Kyma component is being measured for test coverage individually. While this is a valuable metric, we should also be able to see the coverage for the whole Kyma codebase.

**Related issues**
This issue is a follow up of #5474

**Comment by derberg** [comment]
Please specify exactly what has to be done and where

**Comment by clebs** [comment]
Hi @derberg,

we need to change how go test is running on Prow. Currently each component is go tested individually, that is why now we have "per component" coverage.
We have to make it so that all components are tested with one single go test command, that way we will get a single coveage percentage for the whole repository.

**Comment by clebs** [comment]
After re-discussing the value of having global test coverage, we decided that per component coverage is more valuable to developers and teams and therefore we are closing this issue.
