### ISSUE TITLE
Loki crashes repeatedly under load

### ISSUE THREAD

**Issue by davyodom** [kyma-project/kyma#5627]
When running some load tests, Loki crashes due to OOM errors repeatedly.  It is not clear in any documentation what is the expected load that the default configuration of Loki can handle, and what approach should be taken to scale Loki.  This was running against Kyma 1.4.

**Comment by derberg** [comment]
@hisarbalik can you please take a look on https://github.com/kyma-project/kyma/issues/5700 as it seams like related/duplicated

**Comment by a-thaler** [comment]
We configured a proper data retention policy and increased memeory.
