### ISSUE TITLE
Application Operator tests fails on local deployment

### ISSUE THREAD

**Issue by Szymongib** [kyma-project/kyma#5637]
**Description**

Application Operator and Application Connector tests fail on local deployment.
There are timeouts on Application installation. The most probable cause is the lack of resources on Minikube.

Acceptance:
- investigate the issue
- fix or disable tests on local deployment

**Comment by metacons** [comment]
I found a temporary solution, 
once you run provision, stop minikube and increase graphics driver
then run provision again will fix temporary
