### ISSUE TITLE
Refactor acceptance tests

### ISSUE THREAD

**Issue by polskikiel** [kyma-project/kyma#5639]
AC:
- remove application-test
- create and use a helper, which skips test(s) on demand, hint: you can use testing.T.Name() method
- improve reports by displaying proper custom resources in case of test failure (for example ApplicationMapping, ClusterServiceClasses, ClusterServiceBroker, ServiceInstance etc.)

**Comment by piotrmiskiewicz** [comment]
Proposed AC:
 - remove application-test
 - create and use a helper, which skips test(s) on demand, hint: you can use testing.T.Name() method
 - when a test is failing, improve report by displaying proper custom resources (for example ApplicationMapping, ClusterServiceClasses, ClusterServiceBroker, ServiceInstance etc.)
