### ISSUE TITLE
Functions do not react to lifecycle events (Pod delete)

### ISSUE THREAD

**Issue by antoineco** [kyma-project/kyma#5640]
**Description**

Kyma 1.5.0

Functions created by the Function Controller do not return upon reception of a termination event. As a result, a Pod won't be deleted until we reach the limit of the grace period, which is pretty long (`terminationGracePeriodSeconds: 300` by default).

We may want to check what the `preStop` hook injected by Knative Serving does:
```yaml
lifecycle:
  preStop:
    httpGet:
      path: /wait-for-drain
      port: 8022
      scheme: HTTP
```

Only tested with the `nodejs8` runtime.

**Expected result**

The user container returns immediately upon reception of the lifecycle event (Pod deletion).

**Actual result**

It takes Pods 300 sec to get deleted.

**Steps to reproduce**

- Enable the Knative Build component
- Deploy the controller according to [those instructions](https://github.com/kyma-project/kyma/blob/master/components/function-controller/README.md)
- Delete the Pod corresponding to the created demo function (something similar to `demo-6np7k-deployment-58946d5f45-ccpkg`)

**Troubleshooting**

The sources for the ` queue-proxy` container that handles the `/wait-for-drain` preStop endpoint is here: https://github.com/knative/serving/tree/release-0.6/cmd/queue.
I haven't looked into the details yet.

**Comment by michal-hudy** [comment]
It will be fixed with migration to pure Kubernetes resources as a part of https://github.com/kyma-project/kyma/issues/8356
