### ISSUE TITLE
Document how to define microfrontends

### ISSUE THREAD

**Issue by kwiatekus** [kyma-project/kyma#565]
**Description**

 Collect documentation input around the topic : 

- explain CRD and how to use it (Microfrontends & ClusterMicrofrontends)
- explain luigi-client API - (linkManager + init context) - perfect solution would be to link to the existing luigi-client documentation.
- test if the input is comprehensible - test it with test user. (i.e Agnieszka)

**Comment by derberg** [comment]
Remember to follow https://github.com/kyma-project/community/blob/master/guidelines/content-guidelines/content-strategy.md

This is new component and should be listed here https://kyma-project.io/docs/latest/root/kyma#details-components and have individual page like https://kyma-project.io/docs/latest/components/monitoring

From my point of view the entry point is not the Microfrontend but the Console itself. And they when explaining arch of the console you start mentioning its extensibility and how to use it. 

Long term we need example here https://github.com/kyma-project/examples but you need to talk to @a-thaler  about that as I don't know what are his plans for examples
