### ISSUE TITLE
Migrate to the latest Prometheus Operator chart that is compatible with Kubernetes 1.16 

### ISSUE THREAD

**Issue by michal-hudy** [kyma-project/kyma#5654]
**Description**

Migrate to the latest Prometheus Operator chart that is compatible with Kubernetes 1.16 

**Reasons**

Make Kyma compatible with Kubernetes 1.16

**Attachments**

https://kubernetes.io/blog/2019/07/18/api-deprecations-in-1-16/

**Comment by suleymanakbas91** [comment]
Implemented by https://github.com/kyma-project/kyma/pull/6176
