### ISSUE TITLE
Migrate to the latest Jaeger chart that is compatible with Kubernetes 1.16

### ISSUE THREAD

**Issue by michal-hudy** [kyma-project/kyma#5655]
**Description**

Migrate to the latest Jaeger chart that is compatible with Kubernetes 1.16

**Reasons**

Make Kyma compatible with Kubernetes 1.16

**Attachments**

https://kubernetes.io/blog/2019/07/18/api-deprecations-in-1-16/

**Comment by michal-hudy** [comment]
Still valid

**Comment by derberg** [comment]
Closing after discussion with @a-thaler - https://github.com/kyma-project/kyma/issues/5530#issuecomment-563271304
