### ISSUE TITLE
Minimal performance cluster setup for AKS

### ISSUE THREAD

**Issue by hisarbalik** [kyma-project/kyma#5660]
**Description**
Have a performance test setup with AKS additional to GKE executing the same test suite.

For that, the existing prow job should trigger after execution of the GKE based test suite the same suite on base of AKS, collecting the results and making them accessible.

- Adjust prow job to trigger also AKS based test execution
- Provision AKS with Kyma with the help of Kyma-CLI/Hydroform. Functionality not covered by CLI yet can stay as bash script
- Execute test suite
- Deprevision the cluster

Extend existing performance test documentation by the new features

**Comment by pbochynski** [comment]
The AKS setup is not a priority for now. We can come back to that topic later.
