### ISSUE TITLE
Refactor the Remote Environment Custom Resource

### ISSUE THREAD

**Issue by lszymik** [kyma-project/kyma#567]
**Description**

The Remote Environment Custom Resource must be extended with new fields, old fields must be removed in order to introduce improvements in Remote Environment handlings.

**Reasons**

There are several reasons to do it:
- The Application Connector modularization
- Improvements in the Remote Environments separation
- Improvements in Service Catalog UX

**Acceptance criteria**
- Add the labels to the Remote Environment definition according to the proposal: https://github.com/kyma-project/community/blob/master/sig-and-wg/sig-core/proposals/remote-environment-creation.md.
- Remove the `source` fields which will be replaced by RE name in Eventbus.
- The fields `identifier` introduces to the service class registration. That fields will be used as an internal identifier of the registered API.
- Add fields to the service definition in RE: 
```
labels 
      { 
        showcase: true
        local: true
        connected-app: ec-prod
       }
```
- Remote Environment client must be re-generated.
- The CRD group must also be changed `remoteenvironment.kyma.cx` is not valid anymore. @PK85 kindle please link your ticket here :)

**Comment by PK85** [comment]
@lszymik please see: https://github.com/kyma-project/kyma/issues/723
and adjust your ticket a bit.
