### ISSUE TITLE
Function Controller does not retry failed container image builds

### ISSUE THREAD

**Issue by antoineco** [kyma-project/kyma#5671]
**Description**

Upon failure of a container image build, the Function controller does not retry unless the corresponding Function **source code** is updated by the user. This does not always make sense, since build failures can occur for multiple reasons, including:
* A bad controller configuration (bad/missing Dockerfile)
* Expired container registry credentials
* Unavailable container registry
* ...

**Expected result**

Updating non-source Function fields (e.g. runtime, size) or any object related to a Function (e.g. Dockerfile `ConfigMap`, container registry `Secret`) causes a _re-creation_ of the corresponding  Tekton `TaskRun` (image build) if that `TaskRun` was previously failed.

_(side effect: the Function's Knative Service automatically picks-up as soon as the image becomes available in the container registry.)_

**Actual result**

A failed `TaskRun` remains failed until the actual Function source code changes.

**Steps to reproduce**

Scenario 1

1. Set invalid values inside the `Secret` holding your registry credentials.
2. Create a `Function`.
3. Wait until the build `TaskRun` fails ("invalid credentials").
4. Set valid credentials in the `Secret` from 1.
5. Observe that the `Function` remains in error condition forever.

Scenario 2

1. Insert a breaking typo inside a Dockerfile `ConfigMap`.
2. Create a Function using that runtime/Dockerfile.
3. Wait until the build `TaskRun` fails.
4. Fix the typo in the Dockerfile `ConfigMap` from 1.
5. Observe that the `Function` remains in error condition forever.

ping @Abd4llA, discussed quickly today

**Comment by michal-hudy** [comment]
There are plenty of reasons why the build can fail. User is able to trigger build when needed
