### ISSUE TITLE
Function Controller should record Kubernetes events related to Function objects

### ISSUE THREAD

**Issue by antoineco** [kyma-project/kyma#5672]
**Description**

When something relevant happens to a `Function` object, the controller should record a Kubernetes event associated to that `Function` for easier consumption by technical users.

Example of events:
* the Function was created/updated
* something important happened to the Function status ("transitioned from "serving" to "building"")
* an object related to the Function has changed ("acknowledged a change to runtime Dockerfile used by Function")
* the Function has been scaled
* ...

**Expected result**

See above.

**Actual result**

All relevant logs are currently sent to the controller's stdout only, and the information about all Functions are mixed/difficult to consume without log management and well crafted filters.

**Steps to reproduce**

1. Create a Function.
2. Describe that function using `kubectl`.
3. Observe that it doesn't have any associated events.

ping @Abd4llA, discussed quickly today

**Comment by michal-hudy** [comment]
Already done
