### ISSUE TITLE
Add conditions to Function resource

### ISSUE THREAD

**Issue by antoineco** [kyma-project/kyma#5673]
**Description**

from @k15r (in https://github.com/kyma-project/kyma/pull/5652#discussion_r325131660)
_we should change the status resource to allow multiple conditions. then we could have functions in status building and simultaneously serving._

**Reasons**

Provide more detailed insights about the state of a Function object at a given time.

**Notes**

Our current approach to determining the condition of a Function is sub-optimal, because scattered across the main reconciliation logic.
Core Kubernetes controllers set status by observation at the _end_ of the reconciliation. Once everything has been synchronized, a full object status is computed by observing the current state of the world (ideally from informers cache for speed), and the controller determines whether a status update is necessary.
With that approach it's easy to reason about the status computation and the outcome is more predictable.

**Comment by sayanh** [comment]
It is observed that, although the function invocation works, the status is in `Error`.
```
➜ k get function -n funcs demo
NAME   SIZE   RUNTIME   AGE   STATUS
demo   S      nodejs8   22h   Error

➜ curl -kD- "https://${FN_DOMAIN}"
HTTP/2 200
access-control-allow-origin: *
content-length: 11
date: Thu, 19 Sep 2019 12:44:14 GMT
x-powered-by: Express
content-type: text/plain; charset=utf-8
x-envoy-upstream-service-time: 16
server: istio-envoy

Hello World%
```
As per @antoineco,
> Because when your build fails, the status is immediately set to error
