### ISSUE TITLE
Come up with a proper logic for creating Knative Channel name

### ISSUE THREAD

**Issue by anishj0shi** [kyma-project/kyma#5677]
when a kyma subscription is created, the subscription controller creates a knative channel based on event source, event-type and eventType Version, as a result an encoded string is created and trucated to 25 chars, as a result of this truncation we might end up with a channel name containing special characters like **-** in the end and the Knatice Channel will not be created

```
apiVersion: messaging.knative.dev/v1alpha1
kind: Channel
metadata:
  name: foo-
EOF
The Channel "foo-" is invalid: metadata.name: Invalid value: "foo-": a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')
```

we need to come up with a logic where we still use the same data to create channel name and avoid  these special characters at the end.

Proposal from @sayanh : make channel names alphanumeric

Proposal from @antoineco  : use generateName instead of name, and pass a prefix. Names are guaranteed to be unique and compliant when using that metadata field.

**Comment by antoineco** [comment]
Why not delegating it to Kubernetes? You could use `generateName` instead of `name`, and pass a prefix. Names are guaranteed to be unique and compliant when using that metadata field.

**Comment by anishj0shi** [comment]
> Why not delegating it to Kubernetes? You could use `generateName` instead of `name`, and pass a prefix. Names are guaranteed to be unique and compliant when using that metadata field.

Let's try this
