### ISSUE TITLE
Incorrect Documention for Event Sample

### ISSUE THREAD

**Issue by ormos** [kyma-project/kyma#5690]
**Description**

The yaml-file provide in the documentation example at https://kyma-project.io/docs/components/application-connector/#tutorials-trigger-a-lambda-with-events-steps ist wrong. The file shown there is an AsyncAPI-Spec while the text is talking in Step 1 and Step 2about a service instance

**Expected result**

**Actual result**

**Steps to reproduce**

**Troubleshooting**

**Comment by pbochynski** [comment]
The AsyncAPI Spec is defined in the service you register using metadata service in app connector. This first step refers to the previous tutorial how to register service that exposes the event:  https://kyma-project.io/docs/components/application-connector#tutorials-register-a-service
And in the second and third step you have to create service instance which produces the event. It is required to enable event in the namespace.

So technically the documentation is correct, but I think it is not easy to read and it could be improved. My suggestion: use [varkes](https://github.com/kyma-incubator/varkes) to configure application (register service with async api) and trigger the event

**Comment by ormos** [comment]
Ah ok - but it is really difficult to understand. At least I was not getting it, and I assume other readers will also struggle.
