### ISSUE TITLE
Error in lambda function log viewer

### ISSUE THREAD

**Issue by brendandobbs** [kyma-project/kyma#5700]
**Description**

When opening the log viewer from the lambda function I sometimes get the following error 

![image](https://user-images.githubusercontent.com/5688693/65260447-4a9f1a00-dafe-11e9-9cbf-f3cf059378b7.png)

This is one of the calls that is failing with a 503 - 

https://loki.xxxxx.cluster.extend.cx.cloud.sap/api/prom/query?query=%7Bnamespace%3D%22qualtricsdemo%22%2C%20function%3D%22send-survey-after-order-creation-function%22%2C%20container_name%3D%22send-survey-after-order-creation-function%22%2C%20container_name%20!%3D%20%22istio-proxy%

Cluster version is 1.5

**Comment by a-thaler** [comment]
Will be fixed by #5627
