### ISSUE TITLE
Restructure Compass documents

### ISSUE THREAD

**Issue by klaudiagrz** [kyma-project/kyma#5714]
Restructure Compass installation doc that describes how to enable Compass in Kyma: 

- Move the `Run Compass in Kyma` section from Overview to the Installation doc
- Adjust diagrams and sections in the Installation doc
- Update the Overview document and make it more concise

**Comment by iancrowther** [comment]
was there a PR for this?

**Comment by klaudiagrz** [comment]
@iancrowther Yup, it's here:
https://github.com/kyma-project/kyma/pull/5698
