### ISSUE TITLE
Add a tutorial on how to use Compass in Kyma

### ISSUE THREAD

**Issue by klaudiagrz** [kyma-project/kyma#5717]
**Description**

Provide an E2E use-case scenario on how to enable Compass in Kyma and how to use it.

**Tutorial script**
- activate compass and compass-runtime-agent modules, install Kyma, or
  - activate modules and update kyma (point to docs how to update)
- open Kyma, navigate to compass UI
- compass UI
  - create new app (added to DEFAULT scenario by default)
  - add API spec (contact team to get API spec)
  - add Event spec (contact team to get API spec)
  - assign DEFAULT SCNEARIO to existing runtime
- runtime UI applications view
  - see that app is registered, two services available
  - add mapping to given namespace
  - go to SC and 2 service classes should be available
- cleanup:
  - remove mapping to namespace from runtime UI
  - compass UI, remove DEFAULT scenarion from runtime
  - go to runtime UI, see that application is removed

**AC:**
- create tutorial

**Comment by PK85** [comment]
SP: 3
