### ISSUE TITLE
Create automated test for external brokers 

### ISSUE THREAD

**Issue by polskikiel** [kyma-project/kyma#5739]
**Description**

It's a follow-up for the ticket: https://github.com/kyma-project/kyma/issues/4352, in which we have created a **testing script** which helps us to test our external brokers' providers.

**In this task** we must fully automate the testing approach by using the **testing script** in the pipeline. 

We must choose when to execute the tests (periodically or ondemand) to ensure working brokers for the release.

*Until this task is done we must test that **testing script** scenario before each release.*

**Comment by pbochynski** [comment]
It is automated now.

**Comment by PK85** [comment]
do not implement
