### ISSUE TITLE
Use generic Prow Jobs for Compass components

### ISSUE THREAD

**Issue by pkosiec** [kyma-project/kyma#5746]
**Description**
Update Compass components to use generic Prow jobs:
- Director
- Gateway
- Connector
- Runtime Provisioner
- Schema migrator
- Healthchecker

**Reasons**
This will greatly decrease the number of checks we have on CI as there will be only 2 jobs per component instead of 5. 

**Migration Guide**
1. Create a PR to test-infra with a new optional job for the component and merge it. Example: https://github.com/kyma-project/test-infra/pull/1472
2. Create a PR with the refactoring of a component:
   * remove before-commit.sh
   * Adapt Makefile to use `./scripts/go-dep.mk` or other generic makefile. 
   * By default `test`, `check-fmt` and `check-imports` targets are run on CI. If you need any additional checks, add `verify:: target1 target2` to your Makefile. If those checks are not yet implemented in generic makefile add them.
   * If you're missing a tool in a buildpack and there is a high chance it will be used elsewhere **in the same version** go ahead and add it to buildapck.

   Example: https://github.com/kyma-project/kyma/pull/5628
3. When everything is green create the second PR to test-infra, where the old job is marked deprecated, and a new one is required. Merge it. Example: https://github.com/kyma-project/test-infra/pull/1507
4. Rerun all tests on the PR with Makefile. When they are green merge it.

**Related issues**

See also https://github.com/kyma-project/kyma/issues/5481

**Comment by aszecowka** [comment]
- the same changes for e2e tests
