### ISSUE TITLE
Improve local monitoring installation

### ISSUE THREAD

**Issue by kazydek** [kyma-project/kyma#5748]
**Description**

While working on metrics for the Asset Store and Headless CPU, Wookiees found out that installing monitoring locally through CLI with default CPU and memory settings is not possible as the installation fails on the monitoring module due to timeout.

Raising default values to those below helped and the `monitoring` and `prometheus-operator` modules were successfully installed: 
`kyma provision minikube --memory 12000 --cpu 6`

However, that is not a solution that can be used by everyone due to physical memory restrictions. This makes the local monitoring installation accessible:
- only after CPU and memory increase 
- to few ppl  

Could you look into it and propose a solution to it? Maybe create some "light" monitoring package?

>**NOTE:** Any change would also need to be reflected in docs as currently we are not informing that there is any issue with monitoring local installation with default CPU and memory. 

**Reasons**

Installing monitoring locally through CLI should be possible with default or lower than the current CPU and memory requirements.

**Attachments**

Attaching installer logs (not sure if that is of help, however)
[installation-error.log](https://github.com/kyma-project/kyma/files/3647051/installation-error.log)

**Comment by a-thaler** [comment]
I don't see that we can find a "light" profile as prometheus will require at least 1GB with the current amount of servicemonitors.
That's why it is included from kyma "light" profile fully and I think we need to live with that.
However, I agree that we should document how to get it running locally (if you have enough resources)

**Comment by a-thaler** [comment]
It will be fixed by https://github.com/kyma-project/kyma/issues/6674
