### ISSUE TITLE
Update FunctionController to support a GitHub repo as a source for the function code

### ISSUE THREAD

**Issue by Abd4llA** [kyma-project/kyma#5753]
**Description**

Update FunctionController to support changes as proposed by #5752 to allow for providing a GitHub repo as source code.

**AC**
* `Function Controller` can take a Github repo and path to deploy the source from.
* Proper documentation in place in the `Function Controller` chart README

**Comment by k15r** [comment]
do we need to implement a webhook for github, or is it ok if the function only gets built once (during creation of the function)?

**Comment by michal-hudy** [comment]
As we are not sure how the GitOps will be implemented - generally for Kyma or only for Functions - I'm closing this issue

GitOps: https://github.com/kyma-project/kyma/issues/5752
