### ISSUE TITLE
GitOps support for Kyma Functions

### ISSUE THREAD

**Issue by Abd4llA** [kyma-project/kyma#5754]
**Description**

With the importance of GitOps operating model, we want to support deploy Kyma functions from a GitHub repo that acts as the source of truth for the Kyma function. 

**Reasons**

* GitOps is a modern and efficient operating model that has a huge adoption. 
* Providing a more mainstreamed development workflow for serverless developers.

**Comment by hwinkel** [comment]
Is this based on Github or on Git. Github would limt the source of trues to a provider rather then git technology.
