### ISSUE TITLE
Kyma Lite on Google Marketplace

### ISSUE THREAD

**Issue by pbochynski** [kyma-project/kyma#5758]
**Description**
Prepare smaller configuration for Google Marketplace. If it is possible to have 2 plans (regular / lite) it would be great.

**Reasons**
Free Google account has quota for 8 CPU. Current cluster configuration required for Kyma is set to 12 CPU. It is not possible to start a Kyma cluster using a free account. 

**Attachments**

**Comment by brendandobbs** [comment]
I think there is also a limitation of having only one static IP address for a free/trial account so maybe we also need to remove the nginx gateway.

**Comment by michal-hudy** [comment]
@pbochynski As we are not working actively on support for GCP Marketplace, I'm would like to close this issue. We will rather focus on improvements related to Kyma installation, so probably the marketplace will be not needed. Also, the new WG around installation has started recently 😄

What do you think?

**Comment by pbochynski** [comment]
Agree - what we need is simple Kyma helm chart / yaml that installs kyma-operator without complex prerequisites.
