### ISSUE TITLE
Use generic prow job for kyma-operator and service-mesh/security components

### ISSUE THREAD

**Issue by piotrmsc** [kyma-project/kyma#5763]
**Description**

Details in epic: #5481

Our components need to be adjusted to use generic prow job.
Components list :

- [x] kyma-operator -> @strekm
- [x] api-controller (old) -> @strekm
- [x] iam-kubeconfig-service -> @strekm 
- [x] apiserver-proxy -> @jakkab 
- [x] dex-static-user-configurer-> @Tomasz-Smelcerz-SAP 
- [x] xip jobs -> @strekm
- [x] istio patch -> @jakkab 
- [x] tests/integration/dex -> @strekm
- [x] tests/integration/api-controller -> @kubadz 
- [x] tests/integration/apiserver-proxy -> @jakkab 
- [x] tests/integration/cluster-users -> @jakkab 

Components marked with `(?)` are to be verified, basically go and non go jobs/ applications should be adjusted. Jobs that do not have scripts inside are out of scope.

**Notice** new api gateway is part of incubator and under this epic we should gather info if there are any plans to support gomodules which we use already in api gateway.

Migration guide (the procedure) is describe in the mentioned epic as a comment.

**Reasons**

**Attachments**

**Comment by Tomasz-Smelcerz-SAP** [comment]
About no-golang jobs (e.g. bash only): As explained by @sjanota , we should use the generic prow-job, but our own Makefile that contains the `make release` target.

**Comment by jakkab** [comment]
@piotrmsc please review and close.
