### ISSUE TITLE
GKE installation docs use the Kyma CLI

### ISSUE THREAD

**Issue by clebs** [kyma-project/kyma#5787]
**Description**
The Kyma CLI is now the standard for installing Kyma and is able to install kyma on any cluster. Therefore we want to update the Kyma Docs on how to install Kyma on GKE to use the CLI.

**Reasons**
- Get rid of old scripts
- Standarize the CLI

**Comment by a-thaler** [comment]
Covered by https://github.com/kyma-project/kyma/issues/8190
