### ISSUE TITLE
Support for "client credentials plugin" in Kubectl and Kyma

### ISSUE THREAD

**Issue by ormos** [kyma-project/kyma#5792]
**Description**

To improve the overall security and access management to a Kyma cluster, also for the CLI based access via kubctl or kyma-cli we should support the same authentication configuration like when using the Kyma console.

**Reasons**

Right now you can download a static kubeconfig file from the Kyma console allowing an user to use kubectl with the related cluster. The cert in that kubeconfig are static an when expired these need to be manually updated. 

With the support of "client credential plugin" that error-prone process can be optimized, redirecting the user from the CLI to an authentication flow in a browser and updating the cert or optionally a bearer token in the kubeconfig automatically.

The implementation can be done in the kyma-cli, so that a user only needs to have one additional local binary installed aside kubectl.

The azure AKS offering supports a similar functionality already today.

This might also improve the compliance to different customer company security policies. 

**Attachments**

https://kubernetes.io/docs/reference/access-authn-authz/authentication/#client-go-credential-plugins

An example of an OIC plugin can be found here: https://github.com/int128/kubelogin

**Comment by muneendra-yeddala** [comment]
Hi,
Any plans to address this issue. 8 hours validity of token is sort of not allowing us to automate the workload deployments and other configurations through kubectl.

Thanks

**Comment by IObert** [comment]
Hi @muneendra-yeddala,
maybe this tutorial can help you: <https://developers.sap.com/tutorials/kyma-create-service-account.html>

**Comment by kwiatekus** [comment]
With kyma 2.0 we plan not to interfere with k8s authentication / authorisation mechanisms. No more static users will be there and kubeconfig will not be generated by in-house kyma components.
Access will be based on user owned kubeconfig files.
See details here https://github.com/kyma-project/kyma/issues/11337
