### ISSUE TITLE
Acceptance tests for api-gateway

### ISSUE THREAD

**Issue by strekm** [kyma-project/kyma#5795]
**Description**

Implement acceptance tests for the api-gateway controller to cover the following scenarios:

- [x] - Expose service without access strategy (plain access)
- [x] - Expose service with JWT/Oauth2 access strategy on whole service
- [x] - Expose service with JWT && Oauth2 on separate paths
- [x] - Expose without access strategy next update to JWT/Oatuh2 access strategy (whole service)
- [x] - Expose without access strategy next update to JWT/Oauth2 access strategy (on path)
- [x] - Expose with JWT/Oauth2 access strategy next update to give plain access 
- [x] - Create ApiRule next delete it

**Comment by piotrmsc** [comment]
Create assertions for 200,403 & 401 so calls with token, with token without required scopes and without token

**Comment by Demonsthere** [comment]
ToDo: Bump image for the tests
