### ISSUE TITLE
Pagination in the list of pods (console UI) doesn't work

### ISSUE THREAD

**Issue by brendandobbs** [kyma-project/kyma#5813]
**Description**

In the 'kyma-system' namespace I have a list of pods that spans 2 pages however I am not able to access to second page.

**Expected result**

Pagination should be working 

**Actual result**

Only the first page is accessible.

**Steps to reproduce**

Goto https://console.<my cluster>.cluster.extend.cx.cloud.sap/home/namespaces/kyma-system/pods

**Comment by kwiatekus** [comment]
Fixed in 1.6-rc1
