### ISSUE TITLE
Fix and re-enable flaky CBS  tests

### ISSUE THREAD

**Issue by kwiatekus** [kyma-project/kyma#5817]
**Description**

Some flaky tests were skipped :
 - `TestClusterServicePlanService_FindByExternalNameForClass`
 - `TestAddonsConfigurationService_ListAddonsConfigurations`
 - `TestResourceQuotaService_ListStatefulSets`

 They need to be fixed and reenabled

**Comment by mszostok** [comment]
This issue was fixed 14days ago here: https://github.com/kyma-project/kyma/pull/5820

we just forgot to close that issue.
