### ISSUE TITLE
Grafana dashboards do not fit inside configmap

### ISSUE THREAD

**Issue by aerfio** [kyma-project/kyma#5830]
**Description**

While working https://github.com/kyma-project/kyma/pull/5680 PR I had to add more dashboards (json files inside `resources/monitoring/charts/grafana/dashboards`), which resulted in error during installation: `Helm install error: rpc error: code = Unknown desc = release monitoring failed: ConfigMap "monitoring-grafana" is invalid: []: Too long: must have at most 1048576 characters`

**Expected result**

We can put as many dashboards as we need there

**Actual result**

Kyma crashes during installation

**Steps to reproduce**

Create some more dashboards there and try to install Kyma with them

**Troubleshooting**
I've minified jsons in dashboards folder, which is only temporary fix

**Comment by suleymanakbas91** [comment]
Fixed by https://github.com/kyma-project/kyma/pull/6176
