### ISSUE TITLE
Frequent 503 errors requiring pod restarts

### ISSUE THREAD

**Issue by davyodom** [kyma-project/kyma#5845]
**Description**

Fairly frequently when sending events, we see 503 errors, likely due to Istio config not being updated on pods. (This does not include any knative serving services like the similar existing ticket) We see this between various pods in the cluster and most frequently have to restart the following pods...

* istio-system
    * istio-ingressgateway
    * (or sometimes everything in istio-system)
* kyma-system
    * application-connector-ingress-nginx-ingress-controller
    * event-bus-event-publish-service
*kyma-integration
    * {app}-event-service

Kyma 1.4 manually deployed to Azure

**Expected result**

503s should not occur or should resolve very quickly after pod startup

**Actual result**

503s never resolved without manual pod deletion

**Steps to reproduce**

Seems to happen more reliably under pod creation load 

**Troubleshooting**

Manual deletion of pods to resolve issue

**Comment by Demonsthere** [comment]
Hi @davyodom we are aware of the issues with the older version of kyma, due to an error with istio. Please try the new 1.8 release, which should be much more stable regarding the 503 errors. 
Cheers :)
