### ISSUE TITLE
Service catalog pods restart continuously 

### ISSUE THREAD

**Issue by davyodom** [kyma-project/kyma#5846]
**Description**

Service catalog pods are unstable and restart regularly.  In particular the following, although all others including the etcd cluster restart regularly as well with frequent leader cycling

* service-catalog-controller-manager 
* service-catalog-apiserver

Kyma 1.4 manually deployed to azure

**Expected result**

Stable pods

**Actual result**

Pods restart continuously

**Steps to reproduce**

**Troubleshooting**

For example :

service-catalog-controller-manager 
  Last State:     Terminated
      Reason:       OOMKilled
      Exit Code:    137
      Started:      Tue, 01 Oct 2019 07:54:15 -0600
      Finished:     Tue, 01 Oct 2019 12:27:39 -0600
    Ready:          True
    Restart Count:  60

service-catalog-apiserver
    Last State:     Terminated
      Reason:       Error
      Exit Code:    255
      Started:      Thu, 19 Sep 2019 16:14:13 -0600
      Finished:     Thu, 19 Sep 2019 16:14:44 -0600
    Ready:          True
    Restart Count:  5

**Comment by PK85** [comment]
Please use 1.6, we already removed api-server end etcd components form ServiceCatalog

**Comment by davyodom** [comment]
Thanks for the update, we'll be updating to 1.6 and testing soon
