### ISSUE TITLE
Prometheus configuration documentation

### ISSUE THREAD

**Issue by davyodom** [kyma-project/kyma#5847]
**Description**

Prometheus is provisioned with quite low amounts of disk.  This fills up very quickly, and then prometheus gets into a broken state and needs the persistent volume to be wiped out and recreated.  It is not clear in Kyma what expectations are regarding manually configuring prometheus to be ready for any real production workloads.

**Reasons**

Monitoring should be reliable in the cluster, and operators should know what needs to be adjusted, when, and how.

**Attachments**

**Comment by derberg** [comment]
@davyodom hello, can you please take a look at https://kyma-project.io/docs/components/monitoring/#configuration-prometheus-sub-chart
you mean you expect some more configuration guides?

**Comment by davyodom** [comment]
It's good the property for volume size is listed here, but this is buried fairly deep in the docs. Also, this also only addresses knowing configuration a priori at installation time, not adjusting it in a running cluster.

I would hope to eventually see some kind of documentation on a higher level of what configuration is expected to change if someone is trying to run in production at scale.  It's hard for a customer with a working prototype which is fine with the default configuration to know everything that is going to break when they run it with real load in production. Best if it doesn't have to be a trial and error discovery process of breaking components one by one and then figuring out how to fix or scale them.

**Comment by derberg** [comment]
@davyodom could you help us out here and specify what exactly would you expect to have in such a document? Current defaults is Kyma that runs on CI, is able to handle week-long testing of stability. Do I get it right that you would like us to also provide a `prod` config where we tell the user that if he is done playing and want to use it on production, he should for example increase Prometheus storage from 4 to 50 (Prometheus recommended in their yaml files)? Please clarify and suggest as much as possible

**Comment by davyodom** [comment]
I know it's a hard thing to quantify exactly, but I would like to see something like "If you are running more than 'x' workload in a cluster, you should modify the configuration of Prometheus as follows:  Increase disk space from 4g (50g suggested for large workloads) during installation by adding this property to an override file, or editing the stateful set () in this way on a running cluster.  Resource requests should also be increased in the following way, etc."  It's not kyma's job to duplicate all prometheus documentation, but providing a 'prod' installation manifest and adequate documentation would be very beneficial for operators trying to run Kyma beyond prototypes.

**Comment by derberg** [comment]
@davyodom thanks a lot for clarification, now it makes much more sense. I do agree that even though Prometheus is a tool that is not owned by Kyma devs, it is integrated in Kyma and we should make clear recommendations. 
@a-thaler I think it somehow touches the topic we discussed today, so checking the performance of the tools we use + having clear documentation (and builds that validate) that explains current performance with default Kyma. Another topic is to not only say how Kyma behaves in default config but also how to tune it, what settings to change to get more out of it but of course for higher price :)

**Comment by Sallyan** [comment]
The kyma component Prometheus is quite different with standard Prometheus. 
For example it uses separate config file and it is stored in secret prometheus-monitoring. 
In my case, i am trying to modify the prometheus.yaml config file but cannot achieve 
In the monitoring templates, i don't find the spec of prometheus secret. 
And i tried to delete secret prometheus-monitoring and create new one with my required configurations. 
it will create another original same secret automatically. 
I am wondering how could i do prometheus configuration like adding scrape settings?
Anyone could help or guide on this?
Thanks, 
Sally

**Comment by a-thaler** [comment]
@Sallyan we recently updated the monitoring chart to latest prometheus-operator trying to limit custom changes a lot, see also https://github.com/kyma-project/kyma/issues/6124. That changes are available with Kyma 1.9. With 1.10 we improved the stability even more.
Can you be more specific about which kyma version you are using. Are you aware of the configuration options available by https://github.com/kyma-project/kyma/blob/master/resources/monitoring/values.yaml? And how to configure them as installer configuration (https://kyma-project.io/docs/root/kyma/#configuration-helm-overrides-for-kyma-installation)?
Please create a dedicated ticket if you still think you cannot configure the monitoring stack as you need or write us via the public slack channel (https://kyma-community.slack.com/archives/CD28K7YMV)

**Comment by Sallyan** [comment]
Hi @a-thaler  Thanks for the response. 
i raised dedicated ticket for my issue. Please see https://github.com/kyma-project/kyma/issues/7304

Thanks, 
Sally

**Comment by bszwarc** [comment]
@a-thaler , I looked into the ticket and Prometheus configuration and also to what we have in our documentation so far.
I can see that this PR: https://github.com/kyma-project/kyma/pull/7309/files#diff-36ea24c083a451c0d26fd76a526e7566 includes production and local settings, so I would recommend the following documentation to it:

* Document it as a production profile, similar to what we have .e.g for OAuth2 https://kyma-project.io/docs/components/security#configuration-o-auth2-server-production-profile - with more details on the configuration.
* Document just the values (like here: https://kyma-project.io/docs/components/security#configuration-o-auth2-server-production-profile-persistence) and how to apply the override. We can also mention Minikube settings - as on Minikube, the override is installed by default. 
* Documentation should be either way placed somewhere here: https://kyma-project.io/docs/components/monitoring/#configuration-configuration.

I suggest I start from documenting the values, and we then decide to add something more to it.

**Comment by a-thaler** [comment]
yep, what I miss is somehow that guideline on "What are the values in case I need to adjust retention time" or "What are the values if I add 10 more metrics"

**Comment by a-thaler** [comment]
Profiles are introduced and documented
