### ISSUE TITLE
Environments readme.md changes

### ISSUE THREAD

**Issue by jakkab** [kyma-project/kyma#585]
Fix these Toad documentation bugs: 

![Screen Shot 2018-07-10 at 12.56.46.png](https://images.zenhubusercontent.com/5b8661c11dd32d2cc7723799/5f00a960-88db-41a5-b2c7-0bed91c56630)![Screen Shot 2018-07-10 at 12.58.12.png](https://images.zenhubusercontent.com/5b8661c11dd32d2cc7723799/fe5a5e97-8d23-4480-8aa7-dd410852e4c1)

**Comment by Tomasz-Smelcerz-SAP** [comment]
This issue is about changing word "might" to "can".

**Comment by tomekpapiernik** [comment]
Outdated, this document looks completely different now.
