### ISSUE TITLE
ko-fy controllers/services in Kyma

### ISSUE THREAD

**Issue by sayanh** [kyma-project/kyma#5862]
**Description**

ko-fy the controllers/services(non-serverless components) in Kyma. This can accelerate the development process significantly. Knative does it. Serverless components will be ko-fied here https://github.com/kyma-project/kyma/issues/5861.

**Reasons**

Current development process is really slow. After each code change, one needs to push to git and create a (draft)PR and expect the CI to build an image. Then this image needs to be used in Kyma to test out the changes. Or one needs to manually build the image, push it to a registry, change in Kyma and kill the pods. All these can be achieved by [ko](https://github.com/google/ko).

**Comment by derberg** [comment]
@sayanh please put description or close the ticket. We should not create tickets for tickets

**Comment by sayanh** [comment]
@derberg I added more description to the issue. Please let me know if you have any questions.

**Comment by derberg** [comment]
@sayanh I'm lacking knowledge and experience with ko to have any opinion here so hope on one of the meetings you can do a deep dive with others. Without it, it will be hard to buy in people.

Anyway thanks for updating ticket. At least it is clear now what `ko-fy` means, you basically mean  `start using ko`. I suggest to update title ;) but this is just suggestion, not expectation
