### ISSUE TITLE
Write a tool to ease developing tests

### ISSUE THREAD

**Issue by sayanh** [kyma-project/kyma#5863]
**Description**

Running `testing.sh` and enabling and deleting `TestDefinitions` can be tedious. ko can be used to ease the process but we do still want to have the benefits of testing.sh e.g. grepping logs, cleanup etc. So write a tool which will do the following:
- Can run the test in the cluster from the source
- Can grep logs 
- Can cleanup

Bottom line is to make the iteration smooth and fast.

**Comment by a-thaler** [comment]
Please have a look at the Kyma-CLI test command https://github.com/kyma-project/cli/blob/master/docs/gen-docs/kyma_test.md. I think it fits all requirements.
