### ISSUE TITLE
ServiceClasses not created in namespace

### ISSUE THREAD

**Issue by brendandobbs** [kyma-project/kyma#5866]
**Description**

Sometimes when binding an application to a namespace, the Service Classes are not created in the Service Catalog for that namespace.

This was observed on a number of Kyma 1.5 clusters.

Deleting the 3 application-* pods in the kyma-integration pods usually fixes this issue. Sometimes this is not enough in which case deleting also the service-catalog-controller-manager and service-catalog-apiserver pod in the 'kyma-integration' namespace should work

**Steps to reproduce**

1. Register an application with services
2. Bind the application to the namespace
3. Goto the Service Catalog and look for the newly created service classes

**Comment by jasiu001** [comment]
I cannot reproduce the issue. I created several applications with two services both, and bind them to many namespaces. Everything works fine. Could you describe more specifically the application and their services? Do you have any logs from `application-broker`, `service ` or ServiceCatalog `controller-manager`?
