### ISSUE TITLE
Compass test failing on `post-master-kyma-gke-compass-integration`

### ISSUE THREAD

**Issue by pkosiec** [kyma-project/kyma#5868]
**Description**

Director tests in `post-master-kyma-gke-compass-integration` pipeline sometimes fail because of `connection refused` error:

```
Post http://compass-director.compass-system.svc.cluster.local:3000/graphql: dial tcp 10.11.243.90:3000: connect: connection refused
```

Check Director logs in stackdriver.

**Logs**

https://storage.googleapis.com/kyma-prow-logs/logs/post-master-kyma-gke-compass-integration/1179363998747856896/build-log.txt
https://storage.googleapis.com/kyma-prow-logs/logs/post-master-kyma-gke-compass-integration/1179404137935147008/build-log.txt
https://storage.googleapis.com/kyma-prow-logs/logs/post-master-kyma-gke-compass-integration/1178995446626914305/build-log.txt
https://status.build.kyma-project.io/view/gcs/kyma-prow-logs/logs/post-master-kyma-gke-compass-integration/1178780654943342593

...

**Comment by pkosiec** [comment]
Another logs from @michal-hudy PR:
https://status.build.kyma-project.io/view/gcs/kyma-prow-logs/pr-logs/pull/kyma-project_kyma/5896/pre-master-kyma-gke-compass-integration/1182214672078606336

**Comment by michal-hudy** [comment]
And another one, this time with `connection refused`:
https://status.build.kyma-project.io/view/gcs/kyma-prow-logs/pr-logs/pull/kyma-project_kyma/5896/pre-master-kyma-gke-compass-integration/1182239209105133568

**Comment by pkosiec** [comment]
See if this is related: https://github.com/kyma-project/kyma/issues/5868
