### ISSUE TITLE
Kyma local installation from sources doesn't work

### ISSUE THREAD

**Issue by pbochynski** [kyma-project/kyma#5881]
**Description**
The command to install kyma from sources doesn't work. 
```
kyma install --local --src-path ./

Error: unknown flag: --local
``` 

**Expected result**

Installation starts.

**Actual result**
```
Error: unknown flag: --local
```

**Steps to reproduce**

Execute command:
```
kyma install --local --src-path ./
```

**Comment by a-thaler** [comment]
Thanks for the feedback, I fixed it
