### ISSUE TITLE
Kyma local installation gets stuck

### ISSUE THREAD

**Issue by liuhegui** [kyma-project/kyma#5885]
**Description**
OS: ubuntu 1804 on VM
minicube version: 1.0.1
kubectl version: 1.13.*
Kyma CLI version: 1.5.0

Step:
kyma provision minikube       --success
kyma install                             --stuck in "- Installation source checked"
kyma install --source local --src-path ./kyma  --stuck in "- Installation source checked"

**Comment by iancrowther** [comment]
what version of helm are you using?

**Comment by liuhegui** [comment]
> what version of helm are you using?

helm version: v2.11.0

**Comment by liuhegui** [comment]
For helm version:
Client: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}
Error: could not find tiller

When executing second command, there is no output.

**Comment by iancrowther** [comment]
It appears there is no tiller installed on the provisioned cluster.

try ```helm init``` and see if that un-sticks you

**Comment by liuhegui** [comment]
After init helm, I got result by executing helm version:
Client: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}
Error: could not find a ready tiller pod

When I tried to install kyma, I got issue instead of stuck (now I tried to install kyma 1.2.0) :
- Requirements verified
  Installing Kyma in version '1.2.0'
X Installing Tiller
Error: Failed executing kubectl 'kubectl get pods -n kube-system -l name=tiller -o jsonpath='{.items[*].metadata.name}'' command  with output '''Unable to connect to the server: dial tcp 172.16.16.128:8443: connect: network is unreachable
' and error message 'exit status 1'
Failed executing kubectl 'kubectl get pods -n kube-system -l name=tiller -o jsonpath='{.items[*].metadata.name}'' command  with output '''Unable to connect to the server: dial tcp 172.16.16.128:8443: connect: network is unreachable
' and error message 'exit status 1'

But if I manually executed the command 'kubectl 'kubectl get pods -n kube-system -l name=tiller -o jsonpath='{.items[*].metadata.name}'', I got
tiller-deploy-xxxxxxx-xxxx

**Comment by iancrowther** [comment]
so were passed the tiller issue

**Comment by liuhegui** [comment]
Hi Ian,

I made a mistake to close the issue. Now I re-opened it. Thanks. I still have issue

**Comment by suleymanakbas91** [comment]
If `Installation source checked` was printed, that phase has already been completed. So, I believe it was stuck in the `Installing Tiller` phase. 

@liuhegui  After running `kyma provision minikube`, could you test if you can see the nodes by running `kubectl get nodes`?

**Comment by liuhegui** [comment]
Hi Akbas,

Yes, I got this when I executed kubectl get nodes:

NAME       STATUS   ROLES    AGE   VERSION
minikube   Ready    master   54s   v1.12.5

**Comment by suleymanakbas91** [comment]
It could be that kubectl and kyma see different kubeconfig files. We already fixed it with a recent commit, but it is not included in 1.5.0. Can you please check if `KUBECONFIG` environment variable points to the correct kubeconfig file?

**Comment by liuhegui** [comment]
Hi Akbas,

Thanks. I didn't set KUBECONFIG. I think I should wait for your new release.

**Comment by liuhegui** [comment]
@suleymanakbas91 , I installed kyma with --kubeconfig, still got same issue.

**Comment by suleymanakbas91** [comment]
Hi again @liuhegui, as we released the new version (1.6.0), could you please test if it works for you with this release?

**Comment by suleymanakbas91** [comment]
This should be fixed by the new release. If it persists, please re-open this issue.
