### ISSUE TITLE
Add documentation for Loki custom metrics 

### ISSUE THREAD

**Issue by bszwarc** [kyma-project/kyma#5906]
**Description**

As a follow up for our monitoring documentation improvements, we have introduced a document type called `metrics` to be able to document any custom metrics that we have. The template for this doc type is currently in progress, but you can already see some examples created for Asset Store and Headless CMS:

* https://kyma-project.io/docs/1.6/components/asset-store/#metrics-metrics
* https://kyma-project.io/docs/1.6/components/headless-cms/#metrics-metrics

We should have a similar doc for Loki. We can base it on information introduced in this PR: https://github.com/kyma-project/kyma/pull/4206.

See also #1795
**Reasons**

Metrics should be documented for all components.

**Comment by a-thaler** [comment]
We still have no metrics available for Loki, so there is no meaning in documenting them
