### ISSUE TITLE
Enable core-cluster-users test

### ISSUE THREAD

**Issue by aerfio** [kyma-project/kyma#5910]
**Description**

As we agreed in https://github.com/kyma-project/community/issues/369 we are turning off flaky tests in [this](https://github.com/kyma-project/kyma/pull/5901) PR, and `core-cluster-users` is one of them. This needs to be re-enabled.

**Comment by Demonsthere** [comment]
I have reenabled the tests to do some research, and it seems that the cause of the errors is in flaky connections to the kubernetes api-server. The tests themselves are not faulty, but rely on connections to dex, which fail due to timeouts

**Comment by aerfio** [comment]
Whoops, I missed this issue when I was copy pasting 😭

**Update after quality SIG meeting:**

During the meeting it was discussed that disabling whole test suite is too much most of the time, as only few tests inside are really unstable. It was proposed that a person on duty on CI-Force should have an easy way to disable one particular test by regexp or some other mechanism.

**Comment by Demonsthere** [comment]
Tests are reenabled by #5929 and #6017

**Comment by Demonsthere** [comment]
Tests have been merged, can we close this?
