### ISSUE TITLE
Enable kiali test

### ISSUE THREAD

**Issue by aerfio** [kyma-project/kyma#5911]
**Description**

As we agreed in https://github.com/kyma-project/community/issues/369 we are turning off flaky tests in [this](https://github.com/kyma-project/kyma/pull/5901) PR, and `kiali` is one of them. This needs to be re-enabled.

**Comment by a-thaler** [comment]
The test case you can find here: https://github.com/kyma-project/kyma/blob/master/resources/kiali/templates/tests/test.yaml

It is a simple curl call of the external kiali URL, so probably it is related to a general cluster not beeing ready problem..

**Comment by aerfio** [comment]
**Update after quality SIG meeting:**

During the meeting it was discussed that disabling whole test suite is too much most of the time, as only few tests inside are really unstable. It was proposed that a person on duty on CI-Force should have an easy way to disable one particular test by regexp or some other mechanism.

**Comment by a-thaler** [comment]
We will wait for the results of https://github.com/kyma-project/kyma/issues/5910
