### ISSUE TITLE
Enable assetstore test

### ISSUE THREAD

**Issue by aerfio** [kyma-project/kyma#5913]
**Description**

As we agreed in https://github.com/kyma-project/community/issues/369 we are turning off flaky tests in [this](https://github.com/kyma-project/kyma/pull/5901) PR, and `assetstore` is one of them. This needs to be re-enabled.

**Comment by aerfio** [comment]
https://status.build.kyma-project.io/view/gcs/kyma-prow-logs/logs/post-master-kyma-integration/1181197578197274624 here is an example of failing build

**Comment by aerfio** [comment]
**Update after quality SIG meeting:**

During the meeting it was discussed that disabling whole test suite is too much most of the time, as only few tests inside are really unstable. It was proposed that a person on duty on CI-Force should have an easy way to disable one particular test by regexp or some other mechanism.

**Comment by michal-hudy** [comment]
A small change of plans. We will be not ready with Rafter before release 1.7, so we will fix this test ASAP.

**Comment by m00g3n** [comment]
```
```

**Comment by m00g3n** [comment]
The `pre-master-kyma-gke-upgrade` is failing with timeout while upgrading `knative-eventing`.
We need to wait for a fix.

https://sap-cx.slack.com/archives/CPA131JJH/p1571650531000900
https://sap-cx.slack.com/archives/CPA131JJH/p1571658715003700

![image.png](https://images.zenhubusercontent.com/5c7942937063e223386f44c9/a3ee556d-aa0b-44b3-b85f-c7cd3cc9eeb5)
  
![image.png](https://images.zenhubusercontent.com/5c7942937063e223386f44c9/1a46cd7c-e590-4b86-8086-d10b6ebb5cc1)
