### ISSUE TITLE
Enable application-connector test

### ISSUE THREAD

**Issue by aerfio** [kyma-project/kyma#5919]
**Description**

As we agreed in https://github.com/kyma-project/community/issues/369 we are turning off flaky tests in [this](https://github.com/kyma-project/kyma/pull/5901) PR, and `application-connector` is one of them. This needs to be re-enabled.

**Comment by aerfio** [comment]
**Update after quality SIG meeting:**

During the meeting it was discussed that disabling whole test suite is too much most of the time, as only few tests inside are really unstable. It was proposed that a person on duty on CI-Force should have an easy way to disable one particular test by regexp or some other mechanism.

**Comment by franpog859** [comment]
The test was reenabled in [this PR](https://github.com/kyma-project/kyma/pull/5858). I'm closing the issue
