### ISSUE TITLE
Enable dex static users to be optional

### ISSUE THREAD

**Issue by Demonsthere** [kyma-project/kyma#5924]
**Description**
As an admin deploying kyma somewhere I would like to have the option to disable the static users and leave only some connector settings.
The option to set an override for dex (`dex.staticUsers.enabled`) that will enable/disable passwordDB, static users and the init container would be great

**Reasons**
Right now if I enable some extra connectors in dex, I still have the static users present, and even if I remove them manually, upgrading dex will restore them. 

**Attachments**

**Comment by piotrmsc** [comment]
done in #5955
