### ISSUE TITLE
Knative eventing mesh alpha

### ISSUE THREAD

**Issue by Abd4llA** [kyma-project/kyma#5927]
**Description**

With Knative being more adopted in Kyma, we need to replace Event Bus with Knative Broker Trigger. The plan is: 

- In one release we deprecate Kyma Subscriptions and other CRDs that're no longer needed.
- In following release we remove Event Bus completely.

Tasks:

- [x] Proposal for architecture of the integration and needed modifications.
  - Which component creates EventActivation object?
  - What are other use cases of EventActivation?
  - Can we get rid of EventActivation?
  - Tracing and metrics experience?
- [x] Implementation
  - [x] Application Operator
  - [x] EventSource Controller
  - [x] Http Source receive adapter
  - [x] Application Broker
  - [x] Kyma Console
  - [x] Documentation

![knative_eventing_mesh_alpha](https://user-images.githubusercontent.com/1930204/72155437-7139d700-33b3-11ea-8032-253214c4d6ff.png)

**Comment by sayanh** [comment]
The critical issues which will retain tracing functionalities are:
- Cloud events refactor for Natss https://github.com/knative/eventing-contrib/issues/598
- Install Jaegar using operator (nice to have)
- Tracing through NatssChannel https://github.com/knative/eventing-contrib/issues/564
- E2E test- trace through Broker https://github.com/knative/eventing/issues/1766
- Tracing through the Broker - incoming request has a Trace ID https://github.com/knative/eventing/issues/1756

**Metrics**
- Broker filter/ingress metrics available (e.g. which events are getting filtered out or being used)
  - Meaningful dashboards need to be built out of the available metrics
