### ISSUE TITLE
Investigate changes in backup which caused failures on nightly cluster

### ISSUE THREAD

**Issue by lilitgh** [kyma-project/kyma#5941]
**Description**
Backup nightly is failing for some time, find out why it is failing. 
https://status.build.kyma-project.io/?job=kyma-gke-backup-nightly

**Comment by suleymanakbas91** [comment]
As a result, we'll enable the restore plugins back. Here is the issue to follow that: https://github.com/kyma-project/kyma/issues/5899

**Comment by a-thaler** [comment]
Problems figured out, plan is stable and follow actions defined, will close
