### ISSUE TITLE
Backup restore for Event Bus fails

### ISSUE THREAD

**Issue by sayanh** [kyma-project/kyma#5942]
**Description**

Backup restore for Event Bus fails here:
https://storage.googleapis.com/kyma-prow-logs/logs/kyma-gke-backup-nightly/1181796650318827522/build-log.txt

**Expected result**

**Actual result**

**Steps to reproduce**

**Troubleshooting**

**Comment by suleymanakbas91** [comment]
Event bus test has been disabled from the end-to-end backup scenario until it is fixed.

**Comment by k15r** [comment]
The problem:

During restore the owner references on channels created by nats-channels do not get updated to the correct values, but these owner references just get removed.
```bash
k get service -n kyma-system -l messaging.knative.dev/role=natss-channel
```

options for the fix:
* create a velero plugin that adds valid owner references on the restored services 
* don't backup these services at all, as the controller creates them if they cannot be found (maybe using `velero.io/exclude-from-backup`)
* use hooks to delete the service after restore [check here](https://velero.io/docs/v1.1.0/hooks/)

**Comment by montaro** [comment]
The `velero.io/exclude-from-backup` labeling option is not supported in the version we use of Velero 1.0.0

**Comment by montaro** [comment]
Option #2 doesn't look like a valid option because:
1. The hooks are for backup only, and we need a `post.restore` hook to delete the service after creation.
2. This requires a living a `kubectl` container to execute the commands

**Comment by montaro** [comment]
Option # 1 
I created a [plugin](https://github.com/kyma-project/kyma/pull/6050) to search for the corresponding NATS Channel and set the Owner Ref of the Service with the right value.
The problem is that backup tests never finish because Velero fails to restore for unknow reason yet.
Example: https://status.build.kyma-project.io/log?id=1187302077185921024&job=pre-master-kyma-gke-backup

**Comment by antoineco** [comment]
ref #6050
