### ISSUE TITLE
Enable core-console test

### ISSUE THREAD

**Issue by aerfio** [kyma-project/kyma#5949]
**Description**

As we agreed in https://github.com/kyma-project/community/issues/369 we are turning off flaky tests in PR {link to proper PR} , and `core-console` test suite has some unstable test in it. They should be re-enabled asap.

**Comment by dariadomagala** [comment]
Examples:

`Waiting for consoleapp.html frame attached timed out after 10000 ms`
https://status.build.kyma-project.io/view/gcs/kyma-prow-logs/logs/post-master-kyma-gke-integration/1181914681497882625
https://status.build.kyma-project.io/view/gcs/kyma-prow-logs/logs/post-master-kyma-gke-integration/1181847737285480449
`Node is detached from document`
https://status.build.kyma-project.io/view/gcs/kyma-prow-logs/logs/post-master-kyma-gke-integration/1181860068673458177

**Comment by aerfio** [comment]
**Update after quality SIG meeting:**

During the meeting it was discussed that disabling whole test suite is too much most of the time, as only few tests inside are really unstable. It was proposed that a person on duty on CI-Force should have an easy way to disable one particular test by regexp or some other mechanism.

**Comment by kwiatekus** [comment]
Console basic UI test will be replaced by enzyme ui tests.
Please test also namespace deletion
