### ISSUE TITLE
Add IBM Cloud to list of remote clusters

### ISSUE THREAD

**Issue by iancrowther** [kyma-project/kyma#5961]
**Description**

I essentially followed the steps for GKE to get Kyma running with IBM cloud.  It won't take much effort to update the docs

**Reasons**

Broadens the project appeal

**Attachments**

**Comment by piotrmsc** [comment]
@iancrowther could you provide a PR to installation docs how to install it on IBM cloud?

**Comment by iancrowther** [comment]
as soon as it's working, im update my draft PR with the steps.

**Comment by iancrowther** [comment]
FYI - am also talking with folks at IBM to resolve

**Comment by mmitoraj** [comment]
This is a link to the draft PR: https://github.com/kyma-project/kyma/pull/5964/.

**Comment by iancrowther** [comment]
@piotrmsc  @mmitoraj - PR updated
