### ISSUE TITLE
Kyma-installer tries to install release even if it is already in deployed status

### ISSUE THREAD

**Issue by mwieczorek** [kyma-project/kyma#5962]
**Description**

We have a cluster with installed `cluster-essentials` release:

```
$ helm ls   

NAME              	REVISION	UPDATED                 	STATUS  	CHART                        	APP VERSION	NAMESPACE
cluster-essentials	1226    	Thu Oct 10 09:50:24 2019	DEPLOYED	kyma-cluster-essentials-0.0.1	           	kyma-system
compass           	1       	Mon Sep 30 16:20:56 2019	DEPLOYED	compass-0.1.0                	           	compass-system
dex               	62      	Thu Oct  3 07:14:28 2019	DEPLOYED	dex-0.0.2                    	v2.9.0     	kyma-system
istio             	974     	Thu Oct  3 13:50:11 2019	DEPLOYED	istio-1.2.4                  	1.2.4      	istio-system
istio-init        	1032    	Wed Oct  9 22:08:32 2019	DEPLOYED	istio-init-1.2.4             	1.2.4      	istio-system
istio-kyma-patch  	62      	Thu Oct  3 07:13:14 2019	DEPLOYED	istio-kyma-patch-1.0.0       	1.0.0      	istio-system
ory               	1       	Mon Sep 30 14:37:37 2019	DEPLOYED	ory-0.1.0                    	1.0        	kyma-system
testing           	1188    	Thu Oct 10 09:51:06 2019	DEPLOYED	testing-0.0.1                	           	kyma-system
xip-patch         	61      	Thu Oct  3 07:12:25 2019	DEPLOYED	xip-patch-1.0.0              	1.0.0      	kyma-installer
```

But in kyma-installer (and in tiller logs) we can see errors like:
```
failed install prepare step: a release named cluster-essentials already exists.
```

Kyma installed from master (1a596aee commit). 'compass-only' mode - https://github.com/kyma-project/kyma/blob/master/installation/resources/installer-cr-cluster-compass.yaml.tpl

**Expected result**

Kyma-installer installs release correctly

**Actual result**

Installation is failing in the first step (cluster-essentials).

**Steps to reproduce**

**Troubleshooting**

**Comment by mwieczorek** [comment]
Further troubleshooting:

We checked the code how installer is listing releases: https://github.com/kyma-project/kyma/blob/master/components/kyma-operator/pkg/kymahelm/kyma-helm-client.go#L46

And I run similar command with helm cli and that gives different results (indeed cluster-essentials is not on the list):
```
$ helm list --deleted --deleting --deployed --failed --pending 

NAME            	REVISION	UPDATED                 	STATUS         	CHART                 	APP VERSION	NAMESPACE
istio           	992     	Thu Oct  3 23:45:21 2019	PENDING_UPGRADE	istio-1.2.4           	1.2.4      	istio-system
istio-init      	1032    	Wed Oct  9 22:08:32 2019	DEPLOYED       	istio-init-1.2.4      	1.2.4      	istio-system
istio-kyma-patch	62      	Thu Oct  3 07:13:14 2019	DEPLOYED       	istio-kyma-patch-1.0.0	1.0.0      	istio-system
ory             	49      	Thu Oct  3 07:15:09 2019	PENDING_UPGRADE	ory-0.1.0             	1.0        	kyma-system
```

**Comment by piotrmsc** [comment]
Thanks for sharing, looks like the difference of what helm client and helm go client returns might be the cause. We will check that.

**Comment by piotrmsc** [comment]
Small update from my side. We have changed the retry mechanism in the installer, now it retries only failed release, does not start from the beginning. We have to list releases before taking an action like install upgrade and skipping deployed release will block kyma update scenarios.

**Comment by colunira** [comment]
Hello, @mwieczorek 
Listing Helm releases and their statuses works properly. About `failed install prepare step: a release named cluster-essentials already exists.` - we will take care of it soon, follow this issue to keep on track:  https://github.com/kyma-project/kyma/issues/7629
