### ISSUE TITLE
Provisioning Google Cloud storage fails when using uppercase characters

### ISSUE THREAD

**Issue by brendandobbs** [kyma-project/kyma#5970]
**Description**

According to the GCP documentation.....
"Bucket names must contain only lowercase letters, numbers, dashes (-), underscores (_), and dots (.). Names containing dots require verification"

However the Service Class shows the following 

"The string must match the regular expression ^[A-Za-z0-9_\.]+$."

Using uppercase characters fails with
```
  Warning  ProvisionCallFailed               113s (x10 over 10m)  service-catalog-controller-manager  Error provisioning ServiceInstance of ServiceClass (K8S: "nagduan/b9e4332e-b42b-4680-bda5-ea1506797474" ExternalName: "google-storage") at ClusterServiceBroker "hb-google-cloud-platform-service-broker-default-e2076-gcp-servi": Status: 500; ErrorMessage: <nil>; Description: Error creating new bucket: googleapi: Error 400: Invalid bucket name: 'sapteched_2019_BNC_AMBA', invalid; ResponseError: <nil>
```

I think we should update the Service Class documentation and provide some regex validation if it's possible.

**Comment by mszostok** [comment]
Hi @brendandobbs,

thanks for reporting that issue, just FYI: We are not owning the GCP broker. Source code is under Google org: https://github.com/GoogleCloudPlatform/gcp-service-broker but we created a PR with fixing this regex and once it will be merged we will update our image in Kyma

---
After merging [this](https://github.com/GoogleCloudPlatform/gcp-service-broker/pull/544) PR, we need to update the  GCP broker in Kyma

**Comment by mszostok** [comment]
still waiting, now for this PR to be merged: https://github.com/GoogleCloudPlatform/gcp-service-broker/pull/546
