### ISSUE TITLE
Naming Checks for Application Creation UI

### ISSUE THREAD

**Issue by akrausesap** [kyma-project/kyma#5971]
**Description**

When creating an application in Kyma I can provide characters in the name that are illegal in Kubernetes: e.g. "test.123" is a valid name in the application ui:

![2019-10-10_14-22-06](https://user-images.githubusercontent.com/40229965/66568290-6fb90280-eb69-11e9-94f6-a96c903840e0.png)

**Expected result**

Validation prevents creation of object

**Actual result**

Object is created
[test.123.yaml.txt](https://github.com/kyma-project/kyma/files/3712507/test.123.yaml.txt)

**Steps to reproduce**
Create Application test.123

**Troubleshooting**

use Kubernetes compliant name

**Comment by kwiatekus** [comment]
Error msg gives us a hint about proper validation regexp:
`regex used for validation is '[a-z]([-a-z0-9]*[a-z0-9])?')`

Please make sure the same regexp is used in the console backend service

**Comment by akucharska** [comment]
Resolved in https://github.com/kyma-project/console/pull/1830
