### ISSUE TITLE
Oathkeeper is not proxying requests - invalid configuration

### ISSUE THREAD

**Issue by Szymongib** [kyma-project/kyma#5974]
**Description**

After bumping up version of Oathkeeper it is not forwarding requests to `compass-gateway-mtls` subdomain.
In the logs there is the following message:
```Invalid mutator requested" access_url="http://compass-gateway-mtls.gkecompint-pr-5966-9fxcy09p3k.a.build.kyma-project.io/director/graphql" authorization_handler=id_token error="mutator matching this route is misconfigured or disabled" granted=false reason_id=invalid_mutation_handler```

The issue is causing the `pre-master-kyma-gke-compass-integration` pipeline to fail.

**Expected result**

**Actual result**

**Steps to reproduce**

**Troubleshooting**

**Comment by derberg** [comment]
Triaged with support of @piotrmsc

**Comment by kubadz** [comment]
To not cause any pipeline to fail I reverted the changes to the latest stable version.
We will now investigate the issue thoroughly.

**Comment by kubadz** [comment]
The issue for Oathkeeper can be found [here](https://github.com/ory/oathkeeper/issues/276).
