### ISSUE TITLE
Expose timeout as configurable variable in Kyma Operator

### ISSUE THREAD

**Issue by hudymi** [kyma-project/kyma#5994]
**Description**

It should be possible to configure timeouts in Kyma Operator, so I would expect that timeout on Tiller communication, chart installation/upgrade and others are exposed as configurable variables.

**Reasons**

As this something that is impacted by the environment, so it should be configurable instead of having it hardcoded in sources.

**Attachments**

**Comment by piotrmsc** [comment]
We have removed using tiller and now we have a task for doing a unified lib for install/upgrade with new design which we want to share between installer and cli, therefore I will close this one. Configurable timeouts should be part of that library https://github.com/kyma-project/kyma/issues/9347
