### ISSUE TITLE
dex-integration tests are failing in post-master prow jobs

### ISSUE THREAD

**Issue by anishj0shi** [kyma-project/kyma#6005]
w.r.t https://status.build.kyma-project.io/view/gcs/kyma-prow-logs/logs/post-master-kyma-integration/1183996285925986304

End of testing 'oct-tp-testsuite-all-2019-10-15-06-59-dex-integration-0'
Testing 'oct-tp-testsuite-all-2019-10-15-06-59-dex-integration-1' from namespace 'kyma-system'
'oct-tp-testsuite-all-2019-10-15-06-59-dex-integration-1' has Failed status
Fetching logs from 'oct-tp-testsuite-all-2019-10-15-06-59-dex-integration-1' with options tailLimit=2000 and bytesLimit=500000
TESTING start
Run dex tests
=== RUN TestSpec
x
Failures:
* /go/src/github.com/kyma-project/kyma/tests/integration/dex/dex/dex_test.go
Line 74:
Expected: nil
Actual: 'All attempts fail:
#1: Post https://dex.kyma.local/auth: EOF
#2: Post https://dex.kyma.local/auth: EOF
#3: Post https://dex.kyma.local/auth: EOF
#4: Post https://dex.kyma.local/auth: EOF
#5: Post https://dex.kyma.local/auth: EOF
#6: Post https://dex.kyma.local/auth: EOF
#7: Post https://dex.kyma.local/auth: EOF
#8: Post https://dex.kyma.local/auth: EOF
#9: Post https://dex.kyma.local/auth: EOF
#10: Post https://dex.kyma.local/auth: EOF'

**Comment by Demonsthere** [comment]
Hi there, as discussed, this problem occurred once on a post-commit pipeline. Please update this issue once it has been spotted several times on a long-standing cluster (nightly/weekly), so we can have some sort of statistics available. 
For now, I am removing the `critical` and `test-failing` labels

**Comment by piotrmsc** [comment]
@anishj0shi is it still failing?

**Comment by anishj0shi** [comment]
Hi @piotrmsc it failed today twice:
https://sap-cx.slack.com/archives/CBMPTMCV9/p1571393488213400

**Comment by piotrmsc** [comment]
Don't have access to logs but we observed  that sometimes istio ingress does not "react" on provided k8s secret. This results in EOF from client pov but under the hood it's not possible to establish ssl connection. Open SSL connect fails, server does not present any data.

But problem is it fails in non deterministic way and looking on stability checker not that often. For now we are waiting for istio 1.3.4 which will contain fix in SDS that is blocking us with upgrade to 1.3. IMO stability of ingress gateway should be improved after that.

**Comment by akucharska** [comment]
This also failed several times on my PR causing every other gql test to fail:
https://status.build.kyma-project.io/view/gcs/kyma-prow-logs/pr-logs/pull/kyma-project_kyma/6084/pre-master-kyma-integration/1186564838516592640

**Comment by polskikiel** [comment]
Added `test-failing` and `priority/critical` labels due to often fails on post-master jobs: https://status.build.kyma-project.io/view/gcs/kyma-prow-logs/logs/post-master-kyma-integration/1189873140927303680
https://status.build.kyma-project.io/view/gcs/kyma-prow-logs/logs/post-master-kyma-integration/1189787576685301760

**Comment by strekm** [comment]
I set up GKE cluster w/ kyma 1.8.0 installed. dex-integration tests passed 3 times in a row. Also, I did not notice any fails on Prow
