### ISSUE TITLE
Ui-api-layer tests fail on the cluster after DEX SCI integration

### ISSUE THREAD

**Issue by aszecowka** [kyma-project/kyma#602]
**Description**
- CI has access to proper credentials that ui-api-layer should use, so just use them :)
- Make ui-api-layer configurable for credentials in use and best use by default those values https://github.com/kyma-project/kyma/blob/master/resources/core/values.yaml#L30
- There are different flows depending if you are getting token for a static user or some specific IDP, so make sure tests support both cases. Depending on a given condition that is already used here https://github.com/kyma-project/kyma/blob/master/tests/acceptance/dex/dex_test.go#L46. But of course do not skip tests on cluster

**Reason**
Ui-api-layer tests fail during stability checking because of wrong credentials

**Comment by derberg** [comment]
After discussing with @PK85 we agreed that for now we can skip this test on stability check until we do not do stability check on static users. This is kind of dependent on #197 

We will come back to the ticket in 4 weeks once other important priorities are fulfilled.

**Comment by derberg** [comment]
/remind me to check this issue in 4 weeks

**Comment by derberg** [comment]
/remind me to check this issue in 4 weeks

**Comment by derberg** [comment]
long term stability testing should not require testing kyma that is already integrated with some identity provider. This will no longer be a valid issue
