### ISSUE TITLE
Improve API Gateway v2 documentation

### ISSUE THREAD

**Issue by colunira** [kyma-project/kyma#6030]
**Description**

I have noticed some mistakes in API Gateway v2 documentation during testing it.

**Reasons**

In [sample custom resource](https://kyma-project.io/docs/master/components/api-gateway-v2#custom-resource-api-rule-sample-custom-resource) table with possible parameters:
- Not all Oathkeeper authenticators are supported in `spec.rules.accessStrategies`. There should be a list of supported ones.

In [example](https://kyma-project.io/docs/master/components/api-gateway-v2#tutorials-expose-and-secure-a-service-deploy-expose-and-secure-the-sample-resources):
- Link to example httpbin service CR points to master, while it could point to release. 
- Path to example lambda CR is relative and misleading - the root is in the documentation, not in the main Kyma directory. It could be solved in the same way as httpbin service link.
- There is a typo in lambda name in the APIRule - `labmda`
- Wrong `-proxy` suffix is added to both services name (httpbin and lambda) in APIRule

Additionally:
- There is an issue with specifying rules on overlapping paths with the same method. There should be a note or a warning informing about that.

**Comment by tomekpapiernik** [comment]
> Link to example httpbin service CR points to master, while it could point to release.
What does it change? It's a sample from Istio, I think it's fine to link to master in this case.
