### ISSUE TITLE
Add support for MQTT and HTTP event services in Application CRD

### ISSUE THREAD

**Issue by Abd4llA** [kyma-project/kyma#6034]
**Description**
As an output of #5756 , we need to add support in `Application` CRD for different kind of Event services, specifically we need mqtt and http kinds added as a property to the CRD.

**NOTE**
The metadata API needs to be updated with the oauth details and MQTT URL and we need to figure out where to do that.

**Workflow**

1. Application CR is created with services: mqtt
2. Application operator
    1. Establishes oauth credentials with the API gateway
    2. Updates Application object with new info
    3. Creates a new MQTT Event Source object

**Estimate:** 15 pts

**AC**

* There is support for MQTT and HTTP events in `Application` CRD
* Kyma spins up MQTT Event Sources and/or event service deployments based on the proper property in `Application` CRD.
* The application connector workflow works as expected for both http and mqtt applications.

**Comment by anishj0shi** [comment]
We will not support MQTT for kyma-eventing.
