### ISSUE TITLE
Create a dashboard that shows requests to API server

### ISSUE THREAD

**Issue by michal-hudy** [kyma-project/kyma#6035]
**Description**

Create a Grafana dashboard that will display metrics about communication with API Server. That dashboard should group communication by component.

AC:
 - Chart with communication with API server grouped by component
 - Chart with requests grouped by type (same as in Kubernetes Control Plane Status dashboard) with the ability to filter per component.
 - Table with TOP 10 components

Stretch: Create a similar dashboard in Stackdriver if the integration will be ready (https://github.com/kyma-project/test-infra/issues/1623)

**Reasons**

It looks like we are killing the API server, so we need to identify the components/tests that we need to improve. Without proper data, it is not possible.

**Attachments**

https://blog.freshtracks.io/a-deep-dive-into-kubernetes-metrics-part-4-the-kubernetes-api-server-72f1e1210770

**Comment by piotrmsc** [comment]
PR https://github.com/kyma-project/kyma/pull/6079
