### ISSUE TITLE
Adapt Makefiles of Event Bus, Event Service and Function Controller to the unified Makefile agreement

### ISSUE THREAD

**Issue by Abd4llA** [kyma-project/kyma#6054]
**Description**
All Kyma components must be adjusted so they:
- expose a make target `release`
- use common makefile whenever possible
- use docker to vendor build process dependencies
- are built using generic prow job with docker only

A migration guide below explains those steps in detail.

**Reasons**
This will greatly decrease the number of checks we have on CI as there will be only 2 jobs per component instead of 5. 

**Migration Guide**
1. Create a PR to test-infra with a new optional job for the component and merge it. Example: https://github.com/kyma-project/test-infra/pull/1472. Run this command to generate jobs:
```
go run development/tools/cmd/rendertemplates/main.go --config templates/config.yaml
```
2. Create a PR with the refactoring of a component:
   * remove before-commit.sh
   * Adapt Makefile to use `./scripts/go-dep.mk` or other generic makefile. 
   * By default `test`, `check-fmt` and `check-imports` targets are run on CI. If you need any additional checks, add `verify:: target1 target2` to your Makefile. If those checks are not yet implemented in generic makefile add them.
   * If you're missing a tool in a buildpack and there is a high chance it will be used elsewhere **in the same version** go ahead and add it to buildapck.

   Example: https://github.com/kyma-project/kyma/pull/5628
3. When everything is green create the second PR to test-infra, where the old job is marked deprecated, and a new one is required. Merge it. Example: https://github.com/kyma-project/test-infra/pull/1507
4. Rerun all tests on the PR with Makefile. When they are green merge it.

**Acceptance criteria**
- [ ] Following components are built using a generic job.
  - [x] Event Bus
  - [x] Event Service
  - [x] Function Controller
  - [x] Event Bus tests
  - [ ] Function Controller
  - [x] Kubeless nodejs images
  - [x] Kubeless tests
  - [x] E2e Kubeless tests
- [ ] Release process docs are adjusted to mention that those components don't have to be released anymore.

**Comment by sayanh** [comment]
Update:
- Working on event-service component and tests in pr #6104
- component/event-service image is created
- `dep status` fails for tests/integration/event-service
