### ISSUE TITLE
Notification about Limit Range exceeded

### ISSUE THREAD

**Issue by PK85** [kyma-project/kyma#606]
AC:
- user knows that LimitRange was exceeded

see how we did it for resourceQuotas:
- https://github.com/kyma-project/kyma/issues/461

**Comment by polskikiel** [comment]
The cases you should consider:
- Check all resources in the Environment if any of their `limits.memory` or `limits.cpu` limits aren't exceeding the biggest `max.memory` or `max.cpu` limit from the LimitRange. Remember - `max.memory` and `max.cpu` can be specified only per Pod.
In that case you should see condition as follows: 
```
{
      "lastTransitionTime": "2018-09-14T12:27:30Z",
      "lastUpdateTime": "2018-09-14T12:27:30Z",
      "message": "pods \"redis-client-f75c864fc-tjdr2\" is forbidden: maximum memory usage per Container is 1Mi, but limit is 500Mi.",
      "reason": "FailedCreate",
      "status": "True",
      "type": "ReplicaFailure"
 }

```
- Same for `min.cpu` and `min.memory`

- The Environment has ResourceQuota which specifies `limits.memory` and `requests.memory` limits, there is no LimitRange in the Environment. In this case, every new Pod without specified resources limits will end up with failure with such a condition: 
```
{
      "lastTransitionTime": "2018-09-14T11:21:24Z",
      "lastUpdateTime": "2018-09-14T11:21:24Z",
      "message": "pods \"redis-client-6d75bbc666-mdd79\" is forbidden: failed quota: kyma-default: must specify limits.memory,requests.memory",
      "reason": "FailedCreate",
      "status": "True",
      "type": "ReplicaFailure"
}
```
We should make possible to see conditions in easy way on UI or check if each resource in our Environment have proper limits specified, if no, then we should warn the user.
