### ISSUE TITLE
Adjust CRDs domain to  'kyma-project.io'

### ISSUE THREAD

**Issue by PK85** [kyma-project/kyma#607]
CRDs:
- Adjust domain of usagekinds.servicecatalog CRD to 'kyma-project.io'
- Adjust domain of servicebindingusages.servicecatalog CRD to 'kyma-project.io'

AC:
- group name is adjusted in the CRD
- all usage is adjusted
- documentation and examples are adjusted (examples repository as well)

**Comment by polskikiel** [comment]
I decided to separate the renaming process into **3 steps**.
Each step is blocked by the previous one.

1. Rename BUC and regenerate its client.
#2071 (in progress)
2. Rename and align kyma revision in gopkg.toml in ui-api, acceptance, docs in all related repos.
#2104 (blocked)
3. Bump all the images, adjust RBAC roles, adjust CRDs and examples.
