### ISSUE TITLE
Update logging diagram

### ISSUE THREAD

**Issue by a-thaler** [kyma-project/kyma#6074]
**Description**
The logging architecture diagram talks about a "Loki" Deployment, not a StatefulSet. Please double-check full document and update it

**Reasons**
Documentation should reflect the truth :)

**Comment by a-thaler** [comment]
You documented nicely the co-existence of promtail and fluentbit. Unfortunately the current setup will not work with fluentbit as it will not stream to Loki. So we should not document it for now.

**Comment by bszwarc** [comment]
@a-thaler, I will correct it in the next PR :)
