### ISSUE TITLE
Use multi-stage builds and from scratch in dockerfiles in all service-management components

### ISSUE THREAD

**Issue by PK85** [kyma-project/kyma#6076]
**Description**

Use multi-stage builds and from scratch in `Dockerfile`'s in all service-management components.
All `debugging` tools should be available on-demand as a sidecars, `Debug sidecar`.

**Reasons**

Eliminate binary vulnerabilities.

**Components**
- ApplicationBroker https://github.com/kyma-project/kyma/pull/6316
- HelmBroker https://github.com/kyma-project/kyma/pull/6316
- ServiceBindingUsageController https://github.com/kyma-project/kyma/pull/6316
- PodPresetController 
- test/service-catalog https://github.com/kyma-project/kyma/pull/6316
- octopus https://github.com/kyma-incubator/octopus/pull/38
- service-catalog-tester https://github.com/kyma-incubator/service-catalog-tester/pull/13

**Comment by mszostok** [comment]
Here is example how to do it:https://github.tools.sap/gophers-team/kyma-environment-service-broker/blob/ac4d02ab378b2b5daa7ddea707052cd0d9e78082/Dockerfile

**Comment by Tomasz-Smelcerz-SAP** [comment]
Please ensure that service catalog tests image contains curl as well as some shell (e.g. busybox).
This is necessary to invoke curl *after* test finishes, regardless of test outcome: success, failure, crash. See #4719 for details.

**Comment by polskikiel** [comment]
**Update**
I've changed the base image to scratch in our components, but 2 images are still built from the `alpine:3.10`:
- `service-catalog-test`- requires a shell and curl to terminate istio sidecar after the test. We don't bother about binary vulnerabilities in the tests.
- `helm-controller` - requires a shell (executes `eval(ssh_agent -s)`), curl was exchanged to the health-check-proxy solution, so the binary vulnerability is removed.
