### ISSUE TITLE
Event Signatures in Catalog not reflecting updates

### ISSUE THREAD

**Issue by akrausesap** [kyma-project/kyma#6080]
**Description**

When event metadata is updated in the application registry for an existing Service Class these changes are not visible in the UI. However when binding events to a Lambda/Deployment they are visible.

**Expected result**

Event Catalog shows current version of Event metadata in catalog

**Actual result**

Outdated version is shown in Catalog

**Steps to reproduce**
On Kyma 1.5: 

1. Register Events for an application and bind application to a namespace
2. Explore the event service class in the ui
3. Update registered events
4. Refresh catalog display

**Troubleshooting**

Clear Cache

**Comment by janmedrek** [comment]
Parking this issue, for now, we will create a new simplified design of Application Connectivity area: https://github.com/kyma-project/kyma/issues/9127

Hoping this will address this issue

**Comment by janmedrek** [comment]
Closing as #9127 will solve this
