### ISSUE TITLE
Remove tiller-secrets as part of tiller.yaml rollback

### ISSUE THREAD

**Issue by iancrowther** [kyma-project/kyma#6093]
**Description**

Add a check to tiller.yaml to delete the generated tiller-secrets as part of any rollback.

**Reasons**

As its a generated resource, it's not automatically deleted.

**Attachments**

**Comment by iancrowther** [comment]
cc' @piotrmsc

**Comment by piotrmsc** [comment]
We will remove tiller completely as we now run on helm3
