### ISSUE TITLE
Provide detailed explanation how to integrate solutions with the Kyma running on Minikube

### ISSUE THREAD

**Issue by lszymik** [kyma-project/kyma#610]
**Description**

It is the common case that people are developing using the Kyma on local Minikube and solution which is also started on the local machine. We need to provide a detailed description of how to do it with information about certificate handling, establishing a connection to local OIDC providers, etc.

**Reasons**

The Kyma running on a local machine is an important part of the developer experience.

**Comment by tomekpapiernik** [comment]
1. Investigate if such an integration is possible.
2. Provide a list of points that must be covered - a clear list of AC.

**Comment by lszymik** [comment]
Currently, we are not going to extend that area of documentation.
