### ISSUE TITLE
Prepare content that will be used as an intro to Kyma on docs ui and kyma website and other pages

### ISSUE THREAD

**Issue by derberg** [kyma-project/kyma#611]
**Description**

- this new content will be used in `docs` view inside the console, in kyma-project.io/docs, in kyma-project.io and possible in other pages as well
- review what we already have on kyma-project.io, kyma repo overview and official kyma docs overview and details and unify messaging there
- Address the following topic:
  - key, most important features that makes Kyma so unique
    - Serverless
    - Application Connector
    - Service Catalog
  - would be awesome to have some nice diagram that shows that some monolith application communicated something into kyma, processes it with serverless and enhances it by consuming some services provisioned using the catalog. Something that shows Monolith --app connector--> Kyma(Serverless) <--Service Catalog-- AWS/Azure/GCP/SAP SCP
  - what Kyma has to do with Knative
  - why those key features are so great in kyma? because of out of the box monitoring and tracing, cli supported by console UI, security, service mesh
  - why I need Kyma if at the end 90% of it consists of other open source project. Because those 10% that glue it all together makes a difference
  - expose the most important documents, like installation guide for local and cluster
- this content must be consulted with as many people working on kyma vision and roadmap as possible
  

**Reasons**

At this moment it is not really clear enough and hard to find good explanation of what Kyma is and how it fits the cloud native world.

**Comment by derberg** [comment]
we need to have this topic and answer included in these docs https://kyma-community.slack.com/archives/CBP7LKRPS/p1537357663000100

**Comment by kazydek** [comment]
Related PR: https://github.com/kazydek/test_repository/pull/2
