### ISSUE TITLE
Knative documentation on Kyma

### ISSUE THREAD

**Issue by Abd4llA** [kyma-project/kyma#6115]
**Description**

In order to position ourselves as a native provider of Knative, we need to have proper documentation about Knative that are around the following themes

- What is Kyma's vision of Knative adoption.
- How each component is using Knative (Event Bus, Function Controller, etc)
- Roadmap of Kyma adopting Knative
- Promotional section for Knative
- Use cases of using Knative 
- Blogs focused on Knative usage that uses Kyma as the distribution providing Knative

**Reasons**

1. To position Kyma as a strong adopter/k8s distribution that includes Knative
1. To help our customers fully leverage Knative

**Comment by michal-hudy** [comment]
It is already documented that we are using Knative https://kyma-project.io/docs/master/components/serverless-v2/ and I don't see a point in creating a special overview of how the Knative is used in Kyma. The component that using it just should have a description how it is used and that's all.
