### ISSUE TITLE
FluentBit as the standard log collector

### ISSUE THREAD

**Issue by a-thaler** [kyma-project/kyma#6121]
**Description**
FluentBit supports a lot of log collector systems and will be much more flexible than promtail. With Loki 0.4.0 it is supporting fluentBit official. So give it a try and see if it works with Loki, if yes, replace promtail fully

Actions:
- [x] Add a release process to https://github.com/kyma-incubator/fluentbit and use the docker image produced there
- [x] Integrate fluentbit to the logging chart
- [x] Assure that is serving Loki by default
- [x] Assure that the setup is stable (survives weekly cluster)
- [x] Fluentbit configuration can be passed by installer
- [x] Promtail is removed
- [x] Documentation is adjusted
- [x] Loki can be disabled (incl. UI) so that you can use logging chart only with external systems

**Reasons**
Provide a broader variety of integrations to other log systems, do not maintain two kind of agents

**Attachments**
https://github.com/grafana/loki/pull/847.

**Comment by suleymanakbas91** [comment]
To disable loki, set the following values:
- `.Values.loki.enabled=false` on logging/values.yaml
- `.Values.conf.Output.loki.enabled=false` on logging/fluentbit/values.yaml
