### ISSUE TITLE
Insufficient Logging in Application Connector

### ISSUE THREAD

**Issue by janmedrek** [kyma-project/kyma#614]
Priority: Medium
Easiness of attack: No attack
Impact: Moderate

Allegedly, Application Connector logs requests that it passes through to remote environments. 
However, it does not log incoming events yet. Ant it does not log requests to the registration api.

Risk:
Application Connector is one of the first touch-points for incoming requests from the Internet, i.e. from remote environments. Failure to log incoming requests or errors will make it hard to debug integration problems. It will also make us blind towards certain types of attacks.

Suggested Mitigation:

Log incoming events
Log registration api requests, in particular changes that they trigger
Log connection errors related to incomming traffic
Log errors in communication with Event Bus (Publish Service) and minio (specs, docs, etc.)

**Comment by lszymik** [comment]
This issue must be handled on the next backlog refinement.

**Comment by lszymik** [comment]
The desired level of logging has been achieved. The rest depends on the central logging pipeline.
