### ISSUE TITLE
Enable Cascading delete for ServiceInstances in Kyma

### ISSUE THREAD

**Issue by PK85** [kyma-project/kyma#6140]
**Description**
When Service Catalog will be released with cascading delete then we can activate that option in Kyma itself.

**AC**
- activate that functionality

**Comment by mszostok** [comment]
PR with cascade deletion was merged: https://github.com/kubernetes-sigs/service-catalog/pull/2711

we can enable and test that in Kyma using this image tag `v0.3.0-beta.2-3-gb6afbc9` and enabling that in Kyma Helm Chart via feature flag
