### ISSUE TITLE
go-jsonhash: Old library with no LICENSE file

### ISSUE THREAD

**Issue by jose-cortina** [kyma-project/kyma#6142]
**Description**

This library is included in the helm-broker and cli, and was last updated in June 2016 (https://github.com/komkom/go-jsonhash)

The library is reported by [FOSSA](https://app.fossa.com/projects/git%2Bgithub.com%2Fkyma-project%2Fkyma/refs/branch/master/78f6ad19112c28e3cd7489341398c14d81f7acb3/issues/licensing?filter=unlicensed_dependency&revisionScanId=1351913) as it has no LICENSE file.

Evaluate the use of the library and find a suitable replacement to remove this dependency.

https://github.com/search?q=org%3Akyma-project+go-jsonhash&type=Code

**Expected result**

There are no libraries without a license.

**Actual result**

Three libraries reported with no license.

**Comment by jasiu001** [comment]
The `https://github.com/komkom/go-jsonhash` library is used in one place in `internal/broker/provision.go` file (plus test files), one time, one method. 
Method hashes request parameters using standard go libraries, the library is not complicated, it could be replaced by our implementation. After that, the library can be removed.

**Comment by PK85** [comment]
@polskikiel as we discussed. In case customer has upgraded a cluster, make sure service instances created before the upgrade, works as before.

Take into account that can resend SI creation with the same id.
