### ISSUE TITLE
docutils contains GPL-3.0 licensed content

### ISSUE THREAD

**Issue by jose-cortina** [kyma-project/kyma#6143]
**Description**

As reported by [FOSSA](https://app.fossa.com/projects/git%2Bgithub.com%2Fkyma-project%2Fkyma/refs/branch/master/78f6ad19112c28e3cd7489341398c14d81f7acb3/issues/licensing?revisionScanId=1351913&status=active) the [docutils](http://docutils.sourceforge.net) library is included in the helm-broker (through github.com/SpectoLabs/hoverfly).

This library contains a file `tools/editors/emacs/rst.el` licensed under GPL-3.0.

As this license is restrictive, the library has to be replaced or this particular file removed from the code included in Kyma so that we comply with IP regulations.

**Comment by piotrmiskiewicz** [comment]
The **docutils** lib is used in the **hoverly** to generate docs. It is not used in Helm-Broker. The `vendor` folder does not contain the `tools/editors/emacs/rst.el` file. The reference to the `docutil` is in python requirements file: https://github.com/SpectoLabs/hoverfly/blob/master/docs/requirements.txt

**Comment by pbochynski** [comment]
@jose-cortina Please reopen if the answer from @piotrmiskiewicz is not sufficient.
