### ISSUE TITLE
Update Application Operator to support Knative events mesh

### ISSUE THREAD

**Issue by Abd4llA** [kyma-project/kyma#6149]
**Description**
In order to start introducing the new Knative eventing mesh, Application Operator needs to:

1. Create a new `HttpSource` object. (OwnerRef ? Consider Application object)
1. Preserves the old behavior of creating `EventService` deployment.
1. Make sure there is a validator handling the new end point.

![knative_brokers_co_exist_arch](https://user-images.githubusercontent.com/1930204/67859229-5decce80-fb1b-11e9-8864-a0397847643f.png)

**AC**

1. The application operator behaves as described above.
1. The old behavior is still preserved. 
1. Documentations are updated.

**Comment by k15r** [comment]
1. would it make sense to deploy the validator using a `knative service`? Benefits: scale to zero if not used
1. currently everything gets deployed using helm charts. Should we deploy the required parts for the new event mesh using the normal controller pattern?

**Comment by sayanh** [comment]
Options:
- Get local gateway working with ksvc
- Use a k8s svc to point to ksvc pods
