### ISSUE TITLE
can't create accessible endpoint by following api gateway v2 guideline

### ISSUE THREAD

**Issue by MingZhang-PS** [kyma-project/kyma#6154]
**Description**
I am trying to expose a lambda function to be an oauth2 scope protected API, by following https://kyma-project.io/docs/1.6/components/api-gateway-v2#tutorials-expose-and-secure-a-service-deploy-expose-and-secure-the-sample-resources
However, at the last step, when I am trying to access `curl -ik https://lambda-proxy.$DOMAIN/lambda`, exception happens.
I pretty sure that variable $DOMAIN is set properly. So it must be some issue when defining APIRule in gateway. 

Kubernetes version: v1.14.7
cluster: sc-pa-04
provIder: gke
Kyma version: 1.6

**Expected result**
It shall give me HTTP 401 error, since I am accessing an endpoint without token

**Actual result**
It gives me HTTP 404 error

**Troubleshooting**
Some suspect errors:
1. in the doc, the service is named as "labmda-proxy", however, it asks us to  `curl -ik https://lambda-proxy.$DOMAIN/lambda`. So "labmda-proxy" is a typo in the guide?
2. why the service is named as "labmda-**proxy**", it is not the service name (no _-proxy_ as postfix) which created automatically after generating a lambda function
3. why the host is named as "labmda-proxy.kyma.local"? why the namespace is hardcode as "kyma"?

**Comment by MingZhang-PS** [comment]
Hi expert
How can I get the permission to launch a Pull request? I have found the document issue and correct solution

**Comment by tomekpapiernik** [comment]
Hi @MingZhang-PS !
We recently updated the tutorial you mentioned. Please check it out on master and let us know if you see any other issues. Thanks!

https://kyma-project.io/docs/master/components/api-gateway-v2/#tutorials-tutorials

**Comment by MingZhang-PS** [comment]
OK, thank you for the document fixing:-)
