### ISSUE TITLE
[TB] Investigate and document Knative Serving workflow and objects

### ISSUE THREAD

**Issue by Abd4llA** [kyma-project/kyma#6155]
**Description**

To better understand API Controller needed changes to expose Knative services, we need to understand how Knative Serving works under the hood and which objects it creates specifically for Istio.

This issue will unblock #4922

**Timebox** 1 day

**AC**

1. A documentation showing.
    1. Which K8s objects does Knative Serving create.
    1. How does Knative Serving expose a ksvc

**Comment by k15r** [comment]
these are all the objects created when you create a new service
[after_default_clean.yaml.txt](https://github.com/kyma-project/kyma/files/3789063/after_default_clean.yaml.txt)
