### ISSUE TITLE
Perform a sanity check to ensure successful upgrades

### ISSUE THREAD

**Issue by abbi-gaurav** [kyma-project/kyma#6156]
**Description**
When upgrading Kyma from one version to another, many times customers ran into issues that the upgrading job fails for various reasons.
e.g with 1.5 to 1.6, the job fails at the service catalog component in case there are some orphan resources related to service catalog e.g. binding or usage or others.

**Reasons**

Providing a sanity check capability pre-upgrade will inform the user about possible orphan or uncleaned resources in the kyma cluster that could potentially cause the upgrade to fail.

Then the user can take conscious actions to first do a cleanup. As a next step, such a feature can be automated and made a part of the upgrade itself.

**Attachments**

**Comment by jakkab** [comment]
@abbi-gaurav we are going to deliver a release-to-release upgrade pipeline in https://github.com/kyma-project/test-infra/issues/1671.

**Comment by mszostok** [comment]
FYI: the dedicated sanity check script for the Service Catalog will be added in this issue: https://github.com/kyma-project/kyma/issues/6157

**Comment by abbi-gaurav** [comment]
@pbochynski Experiencing from the latest customer challenges with upgrades, I believe having a pre-check can be a lot helpful to ensure upgrades do not mess up the cluster.

**Comment by piotrmsc** [comment]
In general feature request sound reasonable, with current kyma-operator and helm I don't see how it could be done. Helm `--dry-run` flag allows to validate syntax but will not tell if it's going to fail because for example resource already exists.

I delete the stale label as we will now start working on installation, redesigning the process, components etc.

**Comment by piotrmsc** [comment]
In helm 3 dry-run works pretty much the same, it will be added as part of https://github.com/kyma-project/kyma/issues/9347
But it does not provide full sanity checks. Sanity checks are component specific, operator does not know about component state. For sure healthchecks should be in the component charts. Also maybe some quick test script that will not leave any new resources on cluster etc.
