### ISSUE TITLE
Implement an `ApplicationSource` CloudEvents 1.0 http adapter 

### ISSUE THREAD

**Issue by Abd4llA** [kyma-project/kyma#6159]
**Description** 

We need to create the adapter which will be deployed by the `ApplicationSource` controller. This adapter does the following :

1. It is configured with the correct Event Source in order to enrich the events.
1. It receives CloudEvents 1.0 events and sends it to its companion `Channel`.

![knative_brokers_co_exist_arch](https://user-images.githubusercontent.com/1930204/67859262-70670800-fb1b-11e9-91c4-e8eb88d4410e.png)

**Breakdown**
Work left starting 11.11.2019
- [x] Updating `EventSource` controller for integration with the adapter.
- [x] Documentation

**AC**
1. There is an ApplicationSource adapter which gets created by the `ApplicationSource` controller.
1. The ApplicationSource adapter behaves as described above.
1. Documentations are updated.

**Comment by antoineco** [comment]
The following fields should be added to the `HTTPSource` spec as part of this implementation.

```
type HTTPSourceSpec struct {
    SourceID string
    // optional
    MaxRequestSize int
}
```

**Comment by k15r** [comment]
`SourceID` should be renamed to `Source` as this is also the name of the field in the cloudevents specification.
Also it would be nice it we could limit the string to be a valid URI (same type as required by cloudevents spec)

**Comment by nachtmaar** [comment]
Open question: Do we expect that there is always a `eventtypeversion` set in the cloudevent? It might be required by the trigger to filter events based on eventtypeversion. eventype is required by the spec, eventtypeversion however is an optional extension. 
The current implementation with event-service ensures that the eventtypeversion exists.

The combination of eventtypeversion and eventype is used in the UI to filter on events, e.g. `v1.order_created` vs v`2.order_created`. 

If we want to rely on `eventtypeversion` for the lambda trigger, then we should validate it inside the adapter.

**Comment by nachtmaar** [comment]
As discussed with @Abd4llA and @bszwarc, developer document is delivered. Existing documentation (how eventing in kyma works) will be done in a separate ticket, since it is part of the whole broker/trigger epic.
