### ISSUE TITLE
event-bus-subscription-controller fails to remove finalizer when other finalizers exist

### ISSUE THREAD

**Issue by tminke** [kyma-project/kyma#6162]
**Description**
We have implemented a custom Kafka Knative Channel implementation that includes a Controller which watches the Knative Subscriptions created by Kyma (from a Kyma Subscription).  Following K8S CRD best practices, this Controller adds a finalizer to the Knative Subscription and removes it upon deletion.  This Controller work fine regardless of their being other finalizers/controllers watching the Subscription.  

The Kyma event-bus-subscription-controller however does not seem to be able to handle the case where other finalizers/controllers are involved.  From tailing the logs, and having developed our controller, it appears that the Kyma event-bus-subscription-controller is not requeue-ing the reconciliation when it fails to remove the subscription from the finalizer, and/or is not expecting there to be other finalizers and is treating the finalizers map as it's own (instead of just updating it's finalizer).

This is being seen on Kyma 1.6 running in an Azure K8S cluster (v1.14) using a custom Kafka Channel implementation.

**Expected result**
When deleting a Kyma Subscription the corresponding Knative Subscription should be deleted (have it's finalizer removed) even when other finalizers are present.

**Actual result**
There is a race condition in that it sometimes works (when our controller finishes removing it's finalizer prior to the event-bus-subscription-controller attempting reconciliation) but cannot remove it's finalizer when they interleave with each other.  Note that our controller is able to handle the interleaving by reloading the subscription prior to modifying and requeueing upon failure, etc.  This might take a couple reconciliation cycles to settle out but works as expected in the end.

**Steps to reproduce**
1. Tail the logs of the event-bus-subscription-controller
2. Add another finalizer and watching controller to the Knative Subscription created by the event-bus-subscription-controller.
3. Delete the Kyma Subscription
4. Notice that the Knative Subscription is not deleted (again - sometimes works based on the timing of things) and that the event-bus-subscription-controller log describes the inability to remove the finalizer.

Attached is a event-bus-subscription-controller log capture which shows the problem...
[Kyma-SubscriptionController-Bug.txt](https://github.com/kyma-project/kyma/files/3784707/Kyma-SubscriptionController-Bug.txt)

**Troubleshooting**
Have tailed the logs and run many permutations of this.

**Comment by tminke** [comment]
Have confirmed that this is still happening in Kyma 1.8.   From the `event-bus-subscription-controller` logs...
```
"error":"Operation cannot be fulfilled on subscriptions.eventing.kyma-project.io \"df-ee0874be-17a2-11ea-8676-f607fc4263a4\": the object has been modified; please apply your changes to the latest version and try again"
```

**Comment by nachtmaar** [comment]
The same bug appeared in event-bus test and showed up in the nightly stability-checker tests.
Sometimes the knative subscription could not be removed because the finalizer was not removed properly.

It will be solved by https://github.com/kyma-project/kyma/pull/6266

**Comment by nachtmaar** [comment]
@tminke can you confirm that the bug still exists after the PR linked above has been merged? This requires an installation from Kyma master.

**Comment by nachtmaar** [comment]
@tminke Can you give a status update ?

**Comment by travis-minke-sap** [comment]
Assuming with the demise of the event-bus (we've moved to the event-mesh) that this is no longer an issue and can be closed.  Thanks!
