### ISSUE TITLE
Upgrade k8s.io/client-go in application-broker

### ISSUE THREAD

**Issue by PK85** [kyma-project/kyma#6174]
**Description**
Proposed mitigation

Upgrade to version kubernetes 1.12.3, kubernetes 1.10.11, kubernetes 1.11.5, kubernetes 1.13.0 or greater

**Risk assessment**
AV:N/AC:H/PR:N/UI:N/S:U/C:H/I:H/A:H 8.1 High

**Comment by jasiu001** [comment]
Application broker uses `client-go` version `kubernetes-1.15.0`.
Version bump was made 24 September 2019, Application broker image bump in Kyma was made 30 September 2019.
