### ISSUE TITLE
Fix or disable monitoring test

### ISSUE THREAD

**Issue by polskikiel** [kyma-project/kyma#6187]
**Description**

Monitoring test failed on `nightly` cluster. It should be fixed or disabled.

Logs: 
```
09:58:43 Waiting for the pods to be READY!!
09:58:48 Timed out: pods are still unready!!
```

It looks like `prometheus-monitoring-0` pod was unstable. 

**Expected result**

Monitoring test pass everytime on nightly or weekly cluster

**Actual result**

Fails sometimes

**Comment by lilitgh** [comment]
Monitoring test is disabled for now https://github.com/kyma-project/kyma/issues/6216.
To enable it, first https://github.com/kyma-project/kyma/issues/4520 story need to be finished
