### ISSUE TITLE
Reevaluate Knative tracing

### ISSUE THREAD

**Issue by marcobebway** [kyma-project/kyma#6199]
**Description**
We need to reevaluate the whole tracing experience in Knative Eventing and figure out if there are any feature gaps or any blockers to switch away from Event Bus in Kyma to a fully Knative Eventing mesh.

Ref: `https://github.com/knative/docs/pull/1663#issuecomment-542936319`.

**Comment by anishj0shi** [comment]
Tracing In General needs a revisit at conceptual level.
