### ISSUE TITLE
Tracing does not work from publish-service to subscriber

### ISSUE THREAD

**Issue by sayanh** [kyma-project/kyma#6226]
**Description**

Trace spans are not available from publish service to subscriber.

**Expected result**

Complete trace spans should be available from event-service to subscriber.

**Steps to reproduce**

Change istio trace sampling to 100% and create an event. Check in jaeger for trace spans.

Kyma versions: 1.6+

**Comment by k15r** [comment]
Will be included in kyma patch 1.7.1
