### ISSUE TITLE
Restarting of natss dispatcher rendered channels unready

### ISSUE THREAD

**Issue by sayanh** [kyma-project/kyma#6233]
**Description**

Whenever natss dispatcher pod was restarted, the channels became unready hence knative subscriptions got unready followed by kyma subscriptions. This is not desired. The reconciliation loop should get the subscriptions ready eventually which is not happening.

Observed in Kyma 1.6, 1.7

**How to reproduce**
1. Create a working subscription.
1. Verify normal eventing flow works.
1. Delete natss dispatcher pod . Now the bug starts showing.

**Comment by joek** [comment]
This is an pretty importent bug, on 5 out of 10 clusters we faced the issue resulting in 500 in Application connector.

**Comment by sayanh** [comment]
The probable reason for this is Natss dispatcher does not reconcile channels which are `Ready` after bootstrapping. The corresponding Knative subscriptions remain `Unready` with `message: 'Subscription not marked by Channel as Ready: [No Connection to NATSS]'`.

**Comment by nachtmaar** [comment]
Workaround when having a broken channel/subscription:

There is one `reconciliation` round `missing` on the `NatssChannel`. This round can be triggered by changing the NatssChannel, e.g. putting a label on it:

```bash
kubectl annotate natsschannels.messaging.knative.dev -n kyma-system ordercrea-lndjh foo=bar
```

**Comment by sayanh** [comment]
As discussed with @jose-cortina, we will fix it in Kyma 1.8 and not as a patch in Kyma 1.7. Hence removing `critical` tag as well.

**Comment by k15r** [comment]
fixed in knative-eventing
now we need to update the resources

**Comment by k15r** [comment]
this patch needs to be added to eventing-contrib as well. But to do this we need to create proper tests for it.  This will be tracked on a new ticket

**Comment by nachtmaar** [comment]
The PR for the knative fix: https://github.com/knative/eventing/pulls?q=is%3Apr+is%3Aclosed
