### ISSUE TITLE
Make sure function pods are labelled with  "function" label

### ISSUE THREAD

**Issue by kwiatekus** [kyma-project/kyma#6243]
**Description**

We have realised that it is possible  to inspect logs from the function, as the logs from the function's pod are indexed by loki out of the box. However, the logs are not  accessible via dedicated *function* log label. So what that means, user would not find the logs when browsing for function logs.

But the good news here is that the only thing required to fix that is to make sure that the function pods are correctly labelled in their metadata, i.e `function={function_name}`. If I do it manually, I can use log UI to browse function logs.

**Reasons**

Fixing the correct label is a low hanging fruit which will help us build more advanced prototype for the function controller UI. (as we want to include function logs in the dedicated "splitView" panel).

**Attachments**

<img width="1302" alt="Screen Shot 2019-11-08 at 08 38 30" src="https://user-images.githubusercontent.com/6783567/68468331-17ccf480-0218-11ea-8eb3-2f4c98d080c5.png">
<img width="498" alt="Screen Shot 2019-11-08 at 08 39 06" src="https://user-images.githubusercontent.com/6783567/68468344-1e5b6c00-0218-11ea-8870-a16ee9f95ded.png">

**Comment by michal-hudy** [comment]
Already fixed
