### ISSUE TITLE
Application is in NOT_SERVING state and Application Deployments are missing

### ISSUE THREAD

**Issue by Szymongib** [kyma-project/kyma#6246]
**Description**

There is an issue in Release 1.5, that the Application might end up in `NOT_SERVING` state and the Application Deployments are missing completely.

The issue is caused by application-migration job, which might fail and the Application Operator is not able to recreate the Application Helm release.

**Workaround solution**

The workaround for the issue is to delete the Helm release connected to the Application, by running:
```
helm delete --purge {APPLICATION_NAME} --tls
``` 

The issue might then occur for the same Application (if the Application Operator pod restarts). To prevent that all resources related to the migration job should be deleted:
```
kubectl -n kyma-integration delete job {APPLICATION_NAME}-migration-job
kubectl -n kyma-integration delete sa {APPLICATION_NAME}-migration-job
kubectl -n kyma-integration delete role {APPLICATION_NAME}-migration-job
kubectl -n kyma-integration delete rolebinding {APPLICATION_NAME}-migration-job
```

**Comment by brendandobbs** [comment]
Before deleting the application chart you will need to download the tiller certs
https://kyma-project.io/docs/components/security/#details-tls-in-tiller-add-certificates-to-helm-home
