### ISSUE TITLE
Readiness probe fails on new Knative Service

### ISSUE THREAD

**Issue by Abd4llA** [kyma-project/kyma#6282]
**Description**

When creating a new Knative Service in Kyma, the service revision never becomes ready because readiness probe fails.

More precisely, the port 8022 of the `queue-proxy` container (injected by Knative) seems unreachable.

**Expected result**

A revision becomes ready.

**Actual result**

A revision never gets ready because the readiness probe fails.

**Steps to reproduce**

TBD
**Troubleshooting**

TBD

**Comment by antoineco** [comment]
Fixed by #6345. Closing.
