### ISSUE TITLE
Create a helm chart for the new event-source controller

### ISSUE THREAD

**Issue by k15r** [kyma-project/kyma#6288]
**Description**

The new event-source controller needs to be installed using the kyma installer. This means we require a helm chart for it

**Reasons**

No helm chart, no event-source

**Acceptance Criteria**
* install event source
* install test definitions

PR: #6296
Other: kyma-project/test-infra#1745

**Comment by antoineco** [comment]
We also need to think about the release process. Our adapters (well, adapter, singular) need to be built as well, and their image should be references by the controller.
