### ISSUE TITLE
Add missing OS to the instruction on adding certificates

### ISSUE THREAD

**Issue by kazydek** [kyma-project/kyma#6289]
**Description**

Based on instructions on adding certificated to your Kyma installation through [Marketplace](https://github.com/kyma-incubator/marketplaces/blob/master/google-cloud/manifest/application.yaml) check if you can update [Kyma official docs](https://kyma-project.io/docs/#troubleshooting-console-access-network-error) for Windows and/or Linux.

**Comment by piotrmsc** [comment]
@kazydek I think it's still valid?
