### ISSUE TITLE
Create a simple Rafter tutorial 

### ISSUE THREAD

**Issue by kazydek** [kyma-project/kyma#6292]
**Description**

Create a simple tutorial on how to run Rafter on your own and how to create a simple Asset CR.

**Issue(s)**
This is a follow up of https://github.com/kyma-project/kyma/issues/5897

**Comment by kazydek** [comment]
Check out these sample Rafter tutorials for inspiration - perhaps some of the scenarios could be used or improved:
Katacoda tutorials: https://katacoda.com/rafter/scenarios/rafter
Source: https://github.com/derberg/rafter-on-katacoda

**Comment by mmitoraj** [comment]
Instead of adding another simple tutorial, we will link to those on Katacoda. The task here is to improve the Katacoda tutorials and move them to Rafter.

**Comment by mmitoraj** [comment]
PR: https://github.com/derberg/rafter-on-katacoda/pull/1
