### ISSUE TITLE
Publish-service pod OOMs out

### ISSUE THREAD

**Issue by sayanh** [kyma-project/kyma#6299]
**Description**

It is observed that memory consumption for publish-service pod increases overtime with traffic of 1 event per second.

Following are the concerns:
- 32Mi is too low a memory limit for publish service.
- Although memory limit is increased to 64Mi the publish-service OOMs out as the memory usage gets built with time. Probably a memory leak, need to figure.

**Comment by phamilton** [comment]
We had to increase the limits to "128Mi" during recent performance tests we ran to avoid OOM.  It appeared to be stable at that level.
