### ISSUE TITLE
API Gateway v2 tutorial - APIRule incorrect

### ISSUE THREAD

**Issue by jcawley5** [kyma-project/kyma#6300]
Related to steps at
https://kyma-project.io/docs/components/api-gateway-v2#tutorials-expose-and-secure-a-service-deploy-expose-and-secure-the-sample-resources

For the step 2: Expose the service and secure it by creating an APIRule CR:

The **spec.service.name** should be **httpbin** not **httpbin-proxy**

**Comment by tomekpapiernik** [comment]
Hi @jcawley5 ! We noticed that some time ago and the names have been changed. You'll see the changes on master. They'll be released with Kyma 1.8. 

Thanks for letting us know. I'm closing this issue now as it's resolved already.
