### ISSUE TITLE
Improve tests for natss-channel-dispatcher

### ISSUE THREAD

**Issue by k15r** [kyma-project/kyma#6310]
**Description**

So far our test code coverage for the natss-channel-dispatcher is far from optimal. In order to fix #6233 on eventing-contrib:master we need to improve our test coverage for said module.

**Reasons**

As we use natss-channel-dispatcher in kyma we should to make sure its test coverage is up to our standards.

**Attachments**

**Comment by nachtmaar** [comment]
The code coverage of natss disptacher reconciler has been increases from 0 ---> 83% here: https://github.com/knative/eventing-contrib/pull/824

**Comment by nachtmaar** [comment]
@k15r can we close it?

**Comment by nachtmaar** [comment]
Gonna close. @k15r you can reopen it in case we missed a file ;)
