### ISSUE TITLE
Document the Knative Mesh (Alpha) 

### ISSUE THREAD

**Issue by bszwarc** [kyma-project/kyma#6312]
**Description**

We are introducing a new Broker / Trigger concept, which needs to be documented properly.

Goal
1. The user is aware of two ways eventing uses to work:
 -> current solution -> Event Bus
 -> new solution -> Broker/ Trigger 
2. Both solutions are included in Eventing architecture with links to all necessary resources. 
3. The benefits of the new solution are described. 
4. The user can enable the new solution and start using it.

To document:
The doc needs to tell people what is the eventing mesh and what we want to achieve through it. What needs to be documented:
## Overview
* what does the mesh do? 
* a high-level description/diagram
* explain the broker/trigger mechanism
	 
## Mesh concepts
* knative elements (Broker / Trigger)
* event sources - controller and adapters + HTTP Source 

## Event flow
* Here we can use the diagram from: https://github.com/kyma-project/kyma/issues/6148 enriched with information about the Application Operator and ApplicationSources. 

**Affected, but already existing elements:**  
	- Application Broker: https://github.com/kyma-project/kyma/issues/6148 (documentation already done) 
	- Application Operator: https://github.com/kyma-project/kyma/issues/6149  (documentation not done yet,  may be done in a separate PR) 
	
**New Items** 
* Event sources: https://github.com/kyma-project/kyma/tree/master/components/event-sources which deploy the event sources controller 
* HTTP Source: https://github.com/kyma-project/kyma/tree/master/components/event-sources/adapter/http  
* HTTP Source CR [kyma/300-httpsource-crd.yaml at master · kyma-project/kyma · GitHub](https://github.com/kyma-project/kyma/blob/master/components/event-sources/config/300-httpsource-crd.yaml)) 

**Reasons**
New feature must be documented.

**Comment by marcobebway** [comment]
The Application Broker documentation changes is done in this pull request: https://github.com/kyma-project/kyma/pull/6454.

**Comment by marcobebway** [comment]
The Application Broker documentation changes are done in this pull request: https://github.com/kyma-project/kyma/pull/6454.
