### ISSUE TITLE
implement probe functionality for our binaries

### ISSUE THREAD

**Issue by k15r** [kyma-project/kyma#6317]
**Description**

in order to make our readiness-checks work in istio/mtls we often rely on curl for readiness checks.
In such a case the check is configured as a command that just calls curl to try to reach the /health endpoint.

As we use `ko` more and more in our workflow it is a common problem that the default ko baseimage (distroless) doesn't come with curl.

A solution to this problem can be found when you check the queue-proxy that comes with knative-serving.

Here they implemented a curl-like functionality right into the binary of the queue.

With a similar functionality in our binaries the readiness-check could be changed from `curl localhost/healthz` to `name-of-our-binary -probe`
Running in `probe` mode just starts a go-http-client that does a GET on the health-endpoint and exits accordingly. Or it could directly execute the health-check ...

Benefits: 
* no need for curl in the container
* baseimage could even be scratch

downside:
* needs to be implemented

**Attachments**

**Comment by anishj0shi** [comment]
This issue was fixed by updating the relevant istio configurations. and now we dont use curl in our alpine images.
