### ISSUE TITLE
Error when trying to create a name space with disabled istio sidecar injection...

### ISSUE THREAD

**Issue by tricky42** [kyma-project/kyma#6324]
Steps to reproduce:

1. In Kyma Console open the Namespace selector in the top right header bar and select "New Namespace"
2. Enter a name, check "Disable side-car injection" (see first screenshot)
<img width="720" alt="Screen Shot 2019-11-20 at 21 52 42" src="https://user-images.githubusercontent.com/402282/69277473-9e9eab80-0be0-11ea-875e-f1cbfbcb47c4.png">

3. Click "Create"

**Result:** Error Message and the Namespace doesnt get created! (see second screenshot)
<img width="501" alt="Screen Shot 2019-11-20 at 21 52 53" src="https://user-images.githubusercontent.com/402282/69277472-9e9eab80-0be0-11ea-9f12-5e721b9aa32d.png">

**Comment by kwiatekus** [comment]
Already fixed
