### ISSUE TITLE
APIRule should require specifying .spec.rules

### ISSUE THREAD

**Issue by kubadz** [kyma-project/kyma#6337]
**Description**

Currently, the `.spec.rules` field in the APIRule validation schema is not required. However, not providing it leads to a validation error in api-gateway component. As there is no such case where rules should not be provided (there are appropriate rules to skip authentication), the validation schema should require `.spec.rules` to be defined and contain at least one element.

**Expected result**

The validation schema should require `.spec.rules` to be defined and contain at least one element.

**Actual result**

The `.spec.rules` field in the APIRule validation schema is not required.

**Steps to reproduce**

**Troubleshooting**

**Comment by piotrmsc** [comment]
Review docu and apply changes if required
