### ISSUE TITLE
Console UI falls into infinite login loop when graphql query returns 401

### ISSUE THREAD

**Issue by pbochynski** [kyma-project/kyma#635]
**Description**
When some graphql resource returns 401 response console can go into infinite loop.

**Expected result**
If the user was reauthenticated in the last minute console should not trigger next authentication and just display error for not available resources.

**Actual result**

 It looks like after successful login some resource returns 401 login action is performed again. 

**Steps to reproduce**

In my case it was failing query to remote environments:
```
{"query":"query RemoteEnvironment($environment: String!){\n      remoteEnvironments(environment: $environment) {\n        name\n      }\n    }","variables":{"environment":"production"}}
```

**Comment by kwiatekus** [comment]
We want to limit the amount of auth redirects in  the amount of time:
-  use `id_token_stored_at` timestamp from session storage 
- at 401 interception, inspect the `id_token_stored_at` timestamp and measure if it current date is younger than the timestamp + 10 sec . If yes -> redirect to error page, if no -> new automatic auth starts

**Comment by pbochynski** [comment]
What is the status? It is a critical issue - please give it more pressure.
