### ISSUE TITLE
Application resource in not_serving state, gateway not responding/serving requests

### ISSUE THREAD

**Issue by PadmaB** [kyma-project/kyma#6354]
**Description**

While trying to create an Application resource, it results in *not_serving* status.
Connect Application results in GraphQL error
Gateway doesn't seem to be serving requests

Environment setup:
Kubernetes cluster [version 1.14.8] on *Gardener* [GCP]
Kyma version 1.6

**Steps to reproduce**

1. Open the console UI
2. Create an Application resource, results in not_serving status
3. Upon clicking *Connect Application* shows *GraphQL error: internal error*

**Troubleshooting**

Couldn't solve the issue following the trouble-shooting guide at https://kyma-project.io/docs/#troubleshooting-basic-troubleshooting

**Comment by PadmaB** [comment]
Some additional information:
The test run on the cluster failed

> Name:		test-783529443
Concurrency:	1
MaxRetries:	1
StartTime:	2019-11-22 22:15:13 +0530 IST
EndTime:	2019-11-23 00:06:02 +0530 IST
Condition:	Failed
Completed:	16/16
  core                          Failed
  core-console-backend-service  Failed
  core-kubeless                 Failed
  dex-integration               Succeeded
  kiali                         Succeeded
  logging                       Failed
  core-api-controller           Succeeded
  core-apiserver-proxy          Failed
  core-cluster-users            Succeeded
  core-console                  Failed
  core-test-external-solution   Failed
  event-bus                     Failed
  assetstore                    Succeeded
  dex-connection                Succeeded
  e2e-kubeless                  Failed
  monitoring                    Failed
Rerun failed tests: kyma test run core core-console-backend-service core-kubeless logging core-apiserver-proxy core-console core-test-external-solution event-bus e2e-kubeless monitoring

Also kindly note, the kubernetes cluster is scheduled to hibernate everyday

**Comment by PadmaB** [comment]
Any updates on this issue? Meanwhile, I could get the kyma installation up and running on GKE cluster, but would like to know how to get the same setup on a Gardener cluster?
Also, looks like the below issue is related
https://github.com/kyma-project/kyma/issues/6431

**Comment by janmedrek** [comment]
Hey, I was not able to reproduce this issue in any of the newer Kyma versions, please let us know if gateway fails again - we will debug and track down possible causes.
