### ISSUE TITLE
Introduce new version alert in Kyma Console and CLI

### ISSUE THREAD

**Issue by evilyeti** [kyma-project/kyma#6373]
**Description**

Introduce a machine-readable (preferably JSON) resource somewhere on the Kyma website, allowing for automated check for new Kyma version releases and linking to release notes.  
 
**Reasons**

Having a message in both the Kyma Console and CLI, showing that there is a new version released and encouraging users to upgrade their installation will drive forward the adoption of new versions and will eliminate the attack surface of old versions out there in the ecosystem. The indication in the Console should glow _RED_ in case there are known security vulnerabilities in the currently running version, which can be determined client-side by parsing the JSON structure.

This should be really low-hanging fruit, as the new version release job can produce the output and the only thing required would be for Console and CLI to read it. 

**Attachments**

Potential mock
![new_verison](https://user-images.githubusercontent.com/2768924/69472510-76af7380-0dab-11ea-9948-d1d179ab89f7.png)

**Comment by evilyeti** [comment]
fyi: @pbochynski @derberg

**Comment by derberg** [comment]
Would be great to store it in some container that could grab information about number of downloads.

**Comment by pbochynski** [comment]
@varbanv Please consider labeling resources created in the cluster with the Kyma version. Can you create an issue for that and link it here?
