### ISSUE TITLE
Events fail for some of the subscriptions

### ISSUE THREAD

**Issue by sayanh** [kyma-project/kyma#6396]
**Description**

When there are more than one subscriptions for a subscriber, and one subscription causes 500 in subscriber, then the good subscription doesn't work at all.
E.g. Subscription A(200) and B(500), events for subscription A does not work as well.
BTW both the subscriptions were ready in all respect.

**Comment by p4p4** [comment]
Kyma Version is 1.7

**Comment by sayanh** [comment]
The day before yesterday I was too hasty in saying that I could reproduce the issue. My bad, sorry!

What was actually happening was, some of the logs were missing in my `k log` and `stern` but that did not mean the events did not reach the subscriber. 

So my setup was: one subscriber(a lambda) had 3 subscriptions. For 2 events, I was throwing error hence an HTTP 500 in the dispatcher. Meaning dispatcher would retry for those events.

Later I did find those events in the subscriber. Bottom line is, the good events did flow to the subscriber although dispatcher goes crazy while retrying the failed events.
What’s happening now:
The continuous bombardment of events(500/200 mixed) causes the memory usage for dispatcher to explode. As a result the dispatcher gets evicted but so far I think I saw the events reaching the subscriber(both good and bad).
```k get po -n knative-eventing -l messaging.knative.dev/role=dispatcher
NAME                                   READY   STATUS    RESTARTS   AGE
natss-ch-dispatcher-5cdc749595-6z4q5   0/2     Evicted   0          13h
natss-ch-dispatcher-5cdc749595-7xxmk   2/2     Running   0          59m
natss-ch-dispatcher-5cdc749595-8zgq5   0/2     Evicted   0          16h
natss-ch-dispatcher-5cdc749595-cml66   0/2     Evicted   0          20h
natss-ch-dispatcher-5cdc749595-drdx2   0/2     Evicted   0          42h
natss-ch-dispatcher-5cdc749595-g9tc6   0/2     Evicted   0          4h3m
natss-ch-dispatcher-5cdc749595-mcr4q   0/2     Evicted   0          7h6m
natss-ch-dispatcher-5cdc749595-mhz7x   0/2     Evicted   0          10h
natss-ch-dispatcher-5cdc749595-zcwxk   0/2     Evicted   0          30h
```
The reason for eviction(for 1 pod and the pattern is true for all others) was:
```
  message: 'The node was low on resource: memory. Container dispatcher was using 11251372Ki,
    which exceeds its request of 0. '
```

Not sure how else can I reproduce this issue.
