### ISSUE TITLE
Fix natss-dispatcher reconcile bug on Knative master and 0.10

### ISSUE THREAD

**Issue by Abd4llA** [kyma-project/kyma#6397]
**Description**

In NATSS Dispatcher a bug was found in `reconcile` and fixed in knative/eventing#2196 , the fix was created for 0.8 and we need it on master and 0.10.

**AC**
- `natss-dispatcher` reconcile on master and 0.10 return proper errors as in knative/eventing#2196
- There is a patch release for Knative Eventing 0.10

**Comment by marcobebway** [comment]
The two PRs to fix it on master and 0.10.0 are here:
- `https://github.com/knative/eventing-contrib/pull/763`.
- `https://github.com/knative/eventing-contrib/pull/764`.
