### ISSUE TITLE
Order the components according to the installation process

### ISSUE THREAD

**Issue by mmitoraj** [kyma-project/kyma#6399]
**Description**

The list of Kyma components that are or are not installed in particular Kyma versions seems to be ordered randomly. See [this](https://kyma-project.io/docs/master/root/kyma#installation-overview) doc. Order the components in a way that reflects the sequence of the installation process. To see which component is installed first, second, and so on, see the following files:
- [cluster installation](https://github.com/kyma-project/kyma/blob/master/installation/resources/installer-cr-cluster.yaml.tpl)
- [Kyma Lite](https://github.com/kyma-project/kyma/blob/master/installation/resources/installer-cr.yaml.tpl)

**Reasons**

Updated documentation.

**Comment by michal-hudy** [comment]
It is already fixed.
