### ISSUE TITLE
Istio mixer spans are missing in some of the traces

### ISSUE THREAD

**Issue by sayanh** [kyma-project/kyma#6403]
**Description**

It is found that the istio mixer spans are missing in some of the traces. E.g
Trace without istio-mixer spans
<img width="1575" alt="Screenshot 2019-11-26 at 10 34 52" src="https://user-images.githubusercontent.com/5954057/69617444-85f72100-1038-11ea-963b-f6631fe76216.png">

Vs
Trace with istio-mixer
<img width="1696" alt="Screenshot 2019-11-26 at 10 35 08" src="https://user-images.githubusercontent.com/5954057/69617500-9909f100-1038-11ea-939d-5df0c20c632b.png">

**Expected result**

Isito-mixer spans should be there in all the traces.

**Troubleshooting**

No such steps to reproduce this. While creating multiple traces, there should be some traces with out istio-mixer spans.

**Comment by a-thaler** [comment]
Reading this [article](https://istio.io/faq/distributed-tracing/#why-mixer-spans) it looks like that there is cached information which gets refreshed sometimes only and with that you see the traces sometimes only.

I will check if we indeed can just disable them fully. If it looks good I will create a ticket for that.
