### ISSUE TITLE
Lambda Dashboard and Istio Dashboards are empty

### ISSUE THREAD

**Issue by pbochynski** [kyma-project/kyma#642]
**Description**
I created some lambda fuction with http trigger and invoked it several times. Then I opened Grafana and tried to find some information about it using predefined Lambda Dashboard and Istio Dashboard. Both dashboards don't show any traffic. Actually only Pods dashboard contains some information about my lambda. 

**Expected result**
See the number of requests for my lambda on both dashboards

**Actual result**

<img width="1344" alt="screen shot 2018-09-12 at 11 28 49" src="https://user-images.githubusercontent.com/191769/45416010-2f920280-b67f-11e8-8865-cd970af5724b.png">

**Steps to reproduce**

Create lambda, expose it by http trigger and make some calls to it. Then navigate to Grafana and open Lambda Dashboard, select the namespace and the service.

**Comment by joek** [comment]
Please update the istio dashbaords too.

**Comment by akrausesap** [comment]
Hi, had the same issue again. Reason is istio service monitor (`kubectl get servicemonitor istio-mesh -n kyma-system`) points to the wrong prometheus instance (core instead of monitoring). The behaviour  can be observed in release 0.6.1.
Regards
Andreas
