### ISSUE TITLE
Deletion of Knative CRDs fails when Kyma CLI tries to uninstall Kyma

### ISSUE THREAD

**Issue by sayanh** [kyma-project/kyma#6427]
Knative-eventing CRDs fail to get deleted in the uninstall process by Kyma CLI.

More info is here: https://status.build.kyma-project.io/view/gcs/kyma-prow-logs/logs/kyma-cli-integration-gke/1199478006200930304

**Comment by k15r** [comment]
Observation 1: works fine on a blank kyma cluster (means just kyma installed and directly uninstalled)

**Comment by k15r** [comment]
For now this ticket will be closed until it has been decided if we really need the uninstallation functionality. The tests have already been disabled
