### ISSUE TITLE
Screen titles not available

### ISSUE THREAD

**Issue by jose-cortina** [kyma-project/kyma#6430]
**Description**

Kyma shows no title in the browser, resulting from an empty `<title>` attribute in the HTML head. From an accessibility perspective, it is expected that the title is available and context-dependent, meaning that the title should reflect the current status of the application.

**Expected result**

Title is shown in the browser

**Actual result**

`<title></title>`

**AC**

 - title should reflect the current page (top level nav nodes). I.e `Kyma - Namespaces`, `Kyma - Catalog`
 - title should reflect configured `cluster.headerTitle` [docu](https://kyma-project.io/docs/components/console/#configuration-configuration) I.e `Acme - Namespaces`, `Acme - Catalog`

**Comment by jose-cortina** [comment]
@kwiatekus Can you please confirm if this will be in for the 1.14 release?

**Comment by jose-cortina** [comment]
@kwiatekus Please ensure this is in 1.16

**Comment by kwiatekus** [comment]
Fixed
