### ISSUE TITLE
console-backend throws "invalid bearer token" on a new 1.8.0-rc2 installation

### ISSUE THREAD

**Issue by antoineco** [kyma-project/kyma#6436]
**Description**

After a new Kyma 1.8.0-rc2 installation, my browser (Firefox 70.0.1) throws the following errors repeatedly:
```
Firefox can’t establish a connection to the server at wss://console-backend.35.189.119.218.xip.io/graphql.    main.48ba6c6d475f9fae697a.js:1:1160344
```

and the following errors are printed in the console-backend service:

```
E1127 13:00:06.672454       1 middleware.go:39] Unable to authenticate the request due to an error: invalid bearer token
```

This prevents some actions like the creations of Namespaces.

**Steps to reproduce**

1. Create cluster
2. ` kubectl apply -f https://raw.githubusercontent.com/kyma-project/kyma/1.8.0-rc2/installation/resources/tiller.yaml`
3. `kubectl apply -f https://github.com/kyma-project/kyma/releases/download/1.8.0-rc2/kyma-installer-cluster.yaml`
4. Open the console, navigate, create an app, create a Namespace, ...

**Troubleshooting**

1. Deleting the `core-console-backend-service` Pod doesn't solve the problem.
2. Logging out and in again doesn't solve the problem.

**Comment by kwiatekus** [comment]
Root cause documented here:
https://github.com/kyma-project/console/issues/1425
