### ISSUE TITLE
Support additional headers and query parameters in CSRF calls from Application Connector

### ISSUE THREAD

**Issue by franpog859** [kyma-project/kyma#6438]
**Description**

Additional headers and query parameters in CSRF calls from Application Connector should be supported. These additional parameters are already implemented for Target API

[There](https://github.com/kyma-project/kyma/issues/4799) is a similar issue for OAuth calls. It may be helpful while estimating the task and while implementation!

**Reasons**

There is no reason why we should not support these additional parameters also for CSRF calls

**Acceptance Criteria**

- CSRF calls support additional headers and query parameters if provided
- Additional headers and query parameters for CSRF calls are documented in Kyma Docs

**Comment by janmedrek** [comment]
This will be deprecated as we are aiming at switching to Compass based App Connectivity
