### ISSUE TITLE
kyma uninstaller fails removing azure-service-broker

### ISSUE THREAD

**Issue by k15r** [kyma-project/kyma#6439]
**Description**

If a `ServiceInstance.servicecatalog.k8s.io/v1beta1` object exists in the cluster and its spec does not specify a `ClusterServiceClassRef` the uninstaller fails with a nil-pointer dereference error.

the issue seems to be originated here:
https://github.com/kyma-project/kyma/blob/96294eca50c29adbb908b5136ede188c6259fa7a/components/kyma-operator/pkg/steps/azure-deprovisioner.go#L267 ... a nil check should suffice.

**Expected result**

uninstallation should work

**Actual result**

uninstallation looks as if it would be stuck (if you use kyma-cli to uninstall kyma)

**Steps to reproduce**

install a serviceinstance that does not specify the field `ClusterServiceClassRef`

**Troubleshooting**

**Comment by piotrmsc** [comment]
Kyma cli drops support of uninstalling kyma, I want to completely get rid of this custom code.
