### ISSUE TITLE
Compass Runtime Agent supports Applications and Runtimes with additional request parameters in OAuth calls

### ISSUE THREAD

**Issue by franpog859** [kyma-project/kyma#6445]
**Description**

Compass Runtime Agent should support additional headers and query parameters in OAuth token calls for Runtimes and Applications

**Reasons**

Compass Runtime Agent should be able to maintain Runtimes and Application with the parameters in OAuth calls, as a follow up for [this issue](https://github.com/kyma-project/kyma/issues/4799) where the parameters were provided

**Acceptance Criteria**

- Compass Runtime Agent supports Runtimes and Applications with additional headers and query parameters in OAuth token calls
- Compass Runtime Agent action related to the additional headers and query parameters in OAuth token calls is documented in Kyma Docs

**Comment by crabtree** [comment]
Please keep in mind that those additional parameters can be also specified for Basic auth calls.
