### ISSUE TITLE
Adapt chart READMEs as per guidelines

### ISSUE THREAD

**Issue by joek** [kyma-project/kyma#645]
Klaudia Grzondziel pointed out the READMEs for the subcharts don't follow the guidelines.
Details are here: https://github.com/kyma-project/kyma/pull/93#pullrequestreview-146783916
Each chart should follow: https://github.com/kyma-project/community/blob/master/guidelines/templates/resources/chart_README.md

She also proposed, "You can add more sections in Details using H3 but do not use smaller headings. Also remember not to overuse them"

**Comment by derberg** [comment]
you sure it is `good first issue`

**Comment by derberg** [comment]
@joek this is a cleanup task that should be addressed. We should not expect community to do cleanup for us.

**Comment by bszwarc** [comment]
Alertmanager and alerting rules info pointed out in this doc was extracted to official documentation & tutorials. READMEs were updated accordingly. I'm closing this one.
