### ISSUE TITLE
Kyma installation on IBM Cloud is not possible

### ISSUE THREAD

**Issue by mmitoraj** [kyma-project/kyma#6451]
**Description**

Kyma installation on IBM Cloud stucks on the `logging` component. When you run `kubectl -n kyma-system log logging-0 -c logging`, you get the following error:
```
level=error ts=2019-11-28T14:10:42.73650216Z caller=log.go:141 msg="error initializing bucket client" err="mkdir /data/loki: permission denied"
```

On IBM Cloud cloud the default storage class is `ibmc-file-bronze`:
```
storage-logging-0                  Bound    pvc-a5d8a198-11e4-11ea-88bd-9665834f7821   20Gi       RWO            ibmc-file-bronze   35m
```

A similar problem is described in [this](https://github.com/coreos/prometheus-operator/issues/9660) issue.

**Expected result**

Kyma can be installed on IBM Cloud.

**Steps to reproduce**

Create a cluster on IBM Cloud and install Kyma on it. See [this](https://github.com/kyma-project/kyma/pull/5964/files#diff-c88c2410db75eda7745566cef0696907) document for guidelines.

**Comment by iancrowther** [comment]
https://cloud.ibm.com/docs/containers?topic=containers-security

“Every worker node is set up with security and access policies that are enforced by AppArmor External link icon profiles that are loaded into the worker node during bootstrapping. AppArmor profiles cannot be changed by the user or owner of the machine.”

Can we use an Apparmor profile in your pod security policy as annotation?

**Comment by mmitoraj** [comment]
@hisarbalik, please see the above comment ⬆️

**Comment by a-thaler** [comment]
The logging component is not an essential feature and can be disabled at installation for now, so for me it is not a blocker for the overall story.
However, will be great if we can fix it. Unfortunately, @hisarbalik went on vacation, so I triggered @k15r to have a look and come up with some ideas.

**Comment by hisarbalik** [comment]
> https://cloud.ibm.com/docs/containers?topic=containers-security
> 
> “Every worker node is set up with security and access policies that are enforced by AppArmor External link icon profiles that are loaded into the worker node during bootstrapping. AppArmor profiles cannot be changed by the user or owner of the machine.”
> 
> Can we use an Apparmor profile in your pod security policy as annotation?

Sure you can use it, just edit PodSecurityPolicy ```logging-loki``` and add profile configured in your cluster as annotation. Here is the kubernetes doc about AppArmor annotation on PodSecurityPolicy https://kubernetes.io/docs/concepts/policy/pod-security-policy/#apparmor

**Comment by PK85** [comment]
We will not spend time on it in upcoming months. Closed.
