### ISSUE TITLE
Create a Proposal of E2E Metrics Tests 

### ISSUE THREAD

**Issue by sayanh** [kyma-project/kyma#6457]
**Description**

There need to be E2E tests for event-mesh metrics. But this needs to be solved at kyma level. Let's try to create a proposal to evaluate the right way to test metrics for a given component and roll it out in the community repo.

**Reasons**

To prevent regression, automated tests for  metrics should be part of the E2E test. pipeline. (Avoid Broken DASHBOARDS!!!)

**AC** 
- Create a proposal to evaluate the right technique to test Metrics Test.

**Comment by nachtmaar** [comment]
@sayanh Can you add more information here? What should the e2e test exactly do? That are the steps required for manual testing?

**Comment by nachtmaar** [comment]
I would say:
Test that there are metrics at the following dashboards and that they make sense:
- Kyma / Event Bus
- Kyma / Event Bus / Subscription

**Comment by k15r** [comment]
closing for now, will recreate an issue for this improvement if we still think this is required in the future
