### ISSUE TITLE
Allow registering APIs and Events for a misconfigured or invalid specification URL for APIs

### ISSUE THREAD

**Issue by abbi-gaurav** [kyma-project/kyma#6469]
**Description**
It could possibly happen that the API spec gets broken with a certain version update of an external application e.g. (C4C). In that case, currently, it would not be possible to register APIs or Events to try out some scenarios and move forward. The customer will have to wait until the issue is fixed which can then take weeks or months.

We should be more accommodating in such cases and perhaps allow APIs and Events to be registered while responding with a warning message that API specification needs to be corrected.

**Comment by derberg** [comment]
@PK85 can you please have a look, this would have to be addressed in compass, I presume.

**Comment by PK85** [comment]
@abbi-gaurav do you mean compass registration or already API usage in the Kyma?

**Comment by pbochynski** [comment]
Closed due to inactivity.
