### ISSUE TITLE
100k+ duplicate events causing the delay of new events

### ISSUE THREAD

**Issue by sayanh** [kyma-project/kyma#6481]
![image (1).png](https://images.zenhubusercontent.com/5b7e7c8108da7624d8ea9774/77eb5ec6-2ce1-47c8-a5f9-a2171b73f99d)

**Comment by p4p4** [comment]
we tried restarting natss-dispatcher pods (no success) - as a workaround we deleted and recreated the subscriptions - this causes event-loss, but new events at least are delivered again.

**Comment by sayanh** [comment]
After an extended investigation, it is found that NATSS streaming keeps sending a dispatch request to NATSS dispatcher although NATSS dispatcher ACKed after adding the verbose logs [here](https://github.com/sayanh/eventing/tree/investigate-dispatcher-perf).

It is also found that the dependencies in NATSS dispatcher are really old. We want to solve [this](https://github.com/kyma-project/kyma/issues/6547) to ensure that NATSS client is not the culprit.

A far fetched gut feeling also tells me to upgrade NATSS streaming server in Kyma. Issue is [here](https://github.com/kyma-project/kyma/issues/5462).


Right now, the plan is to solve [this](https://github.com/kyma-project/kyma/issues/6547) and proceed further in investigation.

**Comment by anishj0shi** [comment]
Natschannel is not a production grade messaging system. we recommend using a managed messaging system for your production cluster, something like Azure event-hub, GCP pub/sub, or anything supported by knative 0.12' eventing contrib: https://github.com/knative/eventing-contrib
