### ISSUE TITLE
Add automated check for detecting not versioned addons repo on Kyma releases

### ISSUE THREAD

**Issue by mszostok** [kyma-project/kyma#6492]
**Description**

Currently, we have a bug that in Kyma release 1.8 because we are using the addons repository from the latest tag instead of the released version, see: https://github.com/kyma-project/kyma/blob/release-1.8/resources/helm-broker/templates/default-addons-cfg.yaml#L11

We need to add CI check for detecting such URLs which will be executed on each release branch. As a result, we will be informed and such situation will not occur in the future.

**AC:**
- automated check on each release branch for detecting addons repo URL which is not versioned.

**Comment by pbochynski** [comment]
Closed due to inactivity. We put helm-broker on hold for a while.
