### ISSUE TITLE
PVC resizing for prometheus not effective after kyma 1.8 upgrade

### ISSUE THREAD

**Issue by a-thaler** [kyma-project/kyma#6506]
**Description**
In Kyma 1.8 the size of the prometheus persistent volume was increased, see https://github.com/kyma-project/kyma/issues/6094. Unfortunately the upgrade procedure from 1.7 to 1.8 will not auto-resize the volume as it is not supported for statefulSets  (https://github.com/kubernetes/enhancements/issues/661). With that manual steps are needed to apply the new size.
This steps must be documented as part of the migration guide for kyma .18

**Expected result**
Upgrade will succeed after automated procedure + execution of migration guide 

**Actual result**
Does not succeed, PVC stay at 4GB insteasd of 10GB and prometheus will run into disk size problems

**Steps to reproduce**

**Troubleshooting**

see also https://kyma-community.slack.com/archives/CD28K7YMV/p1575380730023800?thread_ts=1575027364.016800&cid=CD28K7YMV

**Comment by bszwarc** [comment]
The migration guide needs to be added under `kyma/docs/migration-guides` and merged to the release branch for 1.8. 
It must be also referenced in the Release Notes for 1.8.

**Comment by suleymanakbas91** [comment]
Manuel steps:
- Delete the Prometheus PVC (this will get stuck until the Prometheus Pod is terminated)
- Delete the Prometheus Pod from another shell (now there shouldn't be any PVC or PV left associated with Prometheus)
- Delete the Prometheus Statefulset (this will trigger the creation of a new PVC and PV with the new storage size)

**Comment by bszwarc** [comment]
PR: https://github.com/kyma-project/kyma/issues/6506

It needs to be merged by the administrator.

**Comment by bszwarc** [comment]
Link to migration guide in Release Notes 1.8 added here: https://github.com/kyma-project/website/pull/503
