### ISSUE TITLE
Performance Cluster Creation Fails

### ISSUE THREAD

**Issue by nachtmaar** [kyma-project/kyma#6535]
**Description**

Performance Cluster under load creation fails periodically on ci-force with the following message:

**Expected result**

Every day 
* a new performance under load cluster is created
* performance tests are executed against the cluster under load

**Actual result**

Performance cluster under load creation fails periodically on ci-force with the following message:

```
Test Run: Failure 
Date: Thu Dec  5 14:24:50 UTC 2019 
Revision:  
Reason: Cluster Creation Failed
```

**Steps to reproduce**

As soon as an problem appears during a performance test, the whole performance test suite will stop and no cleanup actions will be done, see this [issue](https://github.com/kyma-project/test-infra/issues/1106).

```shell
$ k logs -n perf-test k6-runner-1575554400-rqvsc|tail
.++++
........................................................................................................................++++
e is 65537 (0x010001)

Creating CSR

Sending CSR
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (6) Could not resolve host: connector-service.35.198.136.47.xip.io
```

Then the following batch job will fail while trying to create a cluster:

```shell
$ k logs -n perf-test k6-runner-1575554400-jxnbk
ERROR: (gcloud.container.clusters.create) ResponseError: code=409, message=Already exists: projects/sap-se-kyma-perf/zones/europe-west3-a/clusters/perf-kyma.
```

**Troubleshooting**

The deletion of the cluster under-load only happens, when the performance test suite was successful. As soon as an error occurs, the [cleanup code](https://github.com/kyma-project/test-infra/blob/master/performance-tools/performance-cluster/runner.sh#L137) is never executed. It is only executed when the test suite was successful. 

We should either:
1. add a signal handler to the test suite bash script to delete the cluster under load in any case
1. delete the cluster under load before trying to create a new cluster under load

**Manual workaround:**

```shell
$ gcloud container clusters delete --project sap-se-kyma-perf perf-kyma
```

**Comment by pbochynski** [comment]
We should rethink how we proceed with performance tests. In the POs group we are not able to come to the conclusion. We need to decide if we want to keep dedicated performance infrastructure (long running) or we switch to test performance with load generator inside the cluster.
