### ISSUE TITLE
Use stan.go and nats.go in natss dispatcher

### ISSUE THREAD

**Issue by sayanh** [kyma-project/kyma#6547]
**Description**

- Use https://github.com/nats-io/stan.go instead of github.com/nats-io/go-nats-streaming in natss dispatcher as it is deprecated.
- Use https://github.com/nats-io/nats.go instead of https://github.com/nats-io/go-nats in natss dispatcher as it is deprecated.

**AC**

- NATSS Channel upstream dependencies are updated and merged on master
- Gets released is created for Knative Eventing 0.10 and 0.11

**Comment by k15r** [comment]
atm i cannot figure out a way to make this work. Some dependencies of `nats-streaming-server` have already been migrated to go-mod and use its semantic versioning import feature (.../v2/...) . This cannot be resolved using go dep.

With nats-streaming-server in an older version we get a resource collision in protobuf.
