### ISSUE TITLE
Do not trace istio-mixer calls

### ISSUE THREAD

**Issue by a-thaler** [kyma-project/kyma#6549]
**Description**
Any istio-proxy can cause istio-mixer calls quite polluting an e2e-trace and having not much value to the debugging person. Furthermore the calls are happening quite indeterministic as data is cached and only requested sometimes.

Instead we should disable this traces by default to simplify, see also https://istio.io/faq/distributed-tracing/#why-mixer-spans

**Reasons**
Simplify life of end-user, reduce amount of trace data

**Attachments**

**Comment by rakesh-garimella** [comment]
With istio-1.5 we see no istio-mixer traces. We see only relevant component traces which help with debuggability (like istio-ingressgateway) So closing this issue
