### ISSUE TITLE
prometheus keeps restarting

### ISSUE THREAD

**Issue by jcawley5** [kyma-project/kyma#6561]
**Description**
Occurring in 1.7 - pod keeps restarting with error

opening storage failed: read WAL: backfill checkpoint: read records: corruption in segment /prometheus/wal/checkpoint.000138/00000000 at 39911424: unexpected first record, dropping bugger

**Comment by a-thaler** [comment]
Hi @jcawley5,

thanks for your feedback. Indeed we had serious problems with the prometheus setup, mainly not having configured proper retention periods causing full disks and with that crashes similar to that.

In 1.8 we configured the retention proper and with 1.9 we refactored the full monitoring chart by using the latest upstream version and setting better defaults. See also https://kyma-project.io/blog/2020/1/9/release-notes-19#monitoring and #4520 #6124
