### ISSUE TITLE
Helm-broker monitoring target is not up on time

### ISSUE THREAD

**Issue by a-thaler** [kyma-project/kyma#6579]
**Description**
The monitoring endpoint for the helm-broker is not up and running after starting the helm-broker and having RUNNING status. It takes more than 10min till it is reachable.

Target name: kyma-system/helm-broker/0
<img width="1653" alt="Screenshot 2019-12-10 at 13 28 07" src="https://user-images.githubusercontent.com/7479371/70529677-70621b00-1b51-11ea-9092-375f920b2f22.png">

The targets of the controller and etcd are always fine
**Expected result**
After the broker is running the metric endpoint is available

**Actual result**
Often it is not available and it will take time till it gets

**Steps to reproduce**

**Troubleshooting**

**Comment by mszostok** [comment]
info how to access the dashboard: 
export prometheus service
```
kubectl port-forward prometheus-monitoring-prometheus-0 9090
```

got to: http://localhost:9090/targets

![Screen Shot 2019-12-10 at 13 55 38](https://user-images.githubusercontent.com/17568639/70531285-e74ce300-1b54-11ea-8cad-b77b79bfcc8e.png)
