### ISSUE TITLE
api-controller does not create API virtual service

### ISSUE THREAD

**Issue by sjanota** [kyma-project/kyma#661]
**Description**

Sometimes (observed on Jenkins integration test) api-controller does not receive event from api-server (or at least the event is not logged). Because of that related VirtualService is not created and calls to related pod fail. Result is failing api-controller and kubeless tests.

**Expected result**
When API is created in kubernetes relate virtual service should be created

**Actual result**
virtual service is not created

**Steps to reproduce**
Random. Skim through failed Jenkins integrations and you'll find one.

**Troubleshooting**
 - [x] @sjanota Merge PR for api-controller with better logging: #734
 - [ ] Monitor resource usage during failed test runs
 - [ ] Preserve container with failed tests and check if required resources have been created after some time.
 - [x] @sjanota Try to reproduce the problem using same script as Jenkins - `installation/cmd/ci.run.sh --non-interactive --exit-on-test-fail`

**Comment by sjanota** [comment]
We have been trying to reproduce the problem locally on several developer machines without success. We also have left tests running in a loop for 3 days on Azure cluster and none of the runs failed. I suggest the problem is with overloaded Jenkins and not with the service itself.

**Comment by sjanota** [comment]
I have added some ideas to Troubleshooting section how we can approach debugging. @Abd4llA @aszecowka Please, let's continue here. 
1. If you have any idea what else we could check add it to checklist.
1. If you know someone who might, let them know about this issue.
1. When you're picking a bullet to check add your name in front of it, so we're not repeating each others work.

**Comment by aszecowka** [comment]
Please try to reproduce this problem with running Docker in Docker, in the same way as Jenkins is doing. In Jenkinsfile there is the following line:
```
 sh "installation/cmd/ci.run.sh --non-interactive --exit-on-test-fail"
```

**Comment by sjanota** [comment]
@aszecowka Can you explain exactly what do you mean by "Docker in Docker"? kyma-on-minikube is run next to Jenkins by the same docker daemon or there is additional docker daemon within Jenkins container and tests are run by it?

**Comment by sjanota** [comment]
I was able to reproduce the problem once using ci.run.sh. Unfortunately container got deleted before I was able to investigate further.

**Comment by sjanota** [comment]
Hey, here are my findings:
1. I was able to reproduce the issue locally using command @aszecowka suggested. I confirm, that api-controller never receives message from apiserver regarding created apis, thus virtual services are also not created. Time does not matter virtual services were still absent after an hour.
2. Load on the container was incredibly high: 15 minutes average equal 16 (4 times higher then should be) and up to 30 in 1 minute average. `dmesg` also showed that process `mixs` was killed several times by oom killer. I have no idea what this proces is nor does, but it showes that this machine is lacking memory too.
3. I've found issue on kubernetes github (kubernetes/kubernetes#65012) which describes simillar symptomps, but I was not able to confirm if this is the case.

I'm not able to spare more time on this one. Someone else to dive in and look at it from other perspective.

**Comment by sjanota** [comment]
The problem can be reproduced only in this specific environment. However, after several days of fighting with it I cannot tell why this problem occurs for sure. As Prow migration is in progress and docker in docker testing will soon be history. I'm closing this issue for now. Please reopen if it becomes problem once again on Prow.

**Comment by aszecowka** [comment]
maybe this mysterious component is https://istio.io/docs/reference/commands/mixs/ ?

**Comment by kautsig** [comment]
I also stumbled across this. A temporary workaround, which worked for me, is to delete the api controller pod and recreate the api resource.

**Comment by sjanota** [comment]
@kautsig We were also able to workaround it by deleting api-controller pod. Recreate of api was not necessary however.

**Comment by kautsig** [comment]
@sjanota you are right, I assumed this would be necessary and did it right away without waiting for the restarted api controller to reconcile the state.

**Comment by sjanota** [comment]
Additional input from @aszecowka :
* In your contoller you miss calling WaitForCacheSync
* you should not create new goroutine here: `go internalInformerFactory.Start(stop)`
* event handlers should be defined before starting informer factory
* UpdateFunc is called on updates, but also on every resync. So if you want to detect objects which we * missed on AddFunc (which can be a case in current case) you should refactor your code.

I'll try to apply those changes and see if it helps when I have a moment.
