### ISSUE TITLE
System kyma kubeconfig

### ISSUE THREAD

**Issue by piotrmsc** [kyma-project/kyma#6610]
**Description**

Developing applications in kyma should be possible with integrating CI/CD. CI/CD requires externall access to kyma cluster. Currently kyma kubeconfig is designed for such access, however, it contains user token. In CI/CD there's no context of the user. Therefore it should be possible to fetch something like system kubeconfig that will provide access to cluster with access_tokens fetch via client credentials or service accounts.

**Reasons**

Give access to CI/CD to perform actions in kyma cluster

**Attachments**

**Comment by jalonsoa** [comment]
Hi !
  any news on this issue ? If we integrate the development process into a kyma cluster, we need that developers can acces to the k8s cluster, so we need an automatic refresh of the kubeconfig file (or the token access inside this file).

  The GKE aproch is interesting, use the gloud tool to refresh the access-token. Could we use kyma cli to update the access-token in same way ??

- name: gke_{gcloud-account}_europe-west1_{cluster-name}
  user:
    auth-provider:
      config:
        access-token: {acces-token}
        cmd-args: config config-helper --format=json
        cmd-path: /bin/gcloud
        expiry: "2020-02-11T14:59:15Z"
        expiry-key: '{.credential.token_expiry}'
        token-key: '{.credential.access_token}'
      name: gcp

**Comment by piotrmsc** [comment]
Hi @jalonsoa sorry, your reply got lost in all my notifications...
In general we want to provide refresh tokens in kyma and oidc-login plugin https://github.com/int128/kubelogin for kubeconfig.

So users that download kyma kubeconfig will have refreshing in place and automatic token issuing and it's a subject of  #5773 . And yes, it will look like gcp, however, oidc-login automatically issues it for you (authorization code grant with dex, in this case, is automatically initialized).

In this issue I meant system kubeconfigs for access without context of the user.
So if you have a CI/CD but not an gitOps approach, you would like to dynamically push sth to the cluster. For that we need to support authentication of system applications (system2system communication) in apiserver-proxy.

Btw maybe you'd like to contribute?;-)
