### ISSUE TITLE
NATSS dispatcher resource issues

### ISSUE THREAD

**Issue by p4p4** [kyma-project/kyma#6616]
**Description**
NATSS dispatcher CPU and memory usage steadily increase (memory leak?)
At some point the dispatcher doesn't manage to dispatch events any more.
A restart resolves the problem, but causes many duplicate events then (see https://github.com/kyma-project/kyma/issues/6481) 

before restart:
![image (49)](https://user-images.githubusercontent.com/1523187/70795045-44d47000-1d9f-11ea-9e48-89e5ea548748.png)

after restart:
![image (50)](https://user-images.githubusercontent.com/1523187/70795060-4b62e780-1d9f-11ea-9b32-9caab6e90471.png)

Note that:

- before restart. it peaked at 1GB RAM and 12 CPU cores (12.000% CPU) :warning: 
- after restart, memory seems ok with 50MB RAM, but CPU is also steadily increasing.. so it will happen again.

**Expected result**
CPU and memory limits stay constant

**Actual result**

**Steps to reproduce**

just wait and see how resources are increasing

**Troubleshooting**

Restart pod

**Comment by p4p4** [comment]
as a temporary workaround I did set some resource limits at the natss-ch-dispatcher deployment
```
        resources:
          limits:
            cpu: "1"
            memory: 512Mi
```
with that the pod will be killed and restarted once in a while I hope.

**Comment by p4p4** [comment]
unfortunately limits are not being respected 

![image](https://user-images.githubusercontent.com/1523187/71253608-b759c880-2328-11ea-9487-a962ba1af595.png)

**Comment by montaro** [comment]
Hello, @p4p4 Thanks for reporting this bug with informative data!
Do you have any numbers about the number of subscriptions at any given point? The frequency of sending events?

**Comment by montaro** [comment]
Steps to reproduce:
1- Deploying a Kyma Cluster
2- Applying this example https://github.com/kyma-project/examples/tree/master/event-subscription/lambda
3- Duplicating the subscription to be 10 subscriptions to the same event type and version
4- Flooding the system with events to the desired event type and version
5- watching the monitors:
![image](https://user-images.githubusercontent.com/531945/71737360-b9a54200-2e53-11ea-85c5-ade17e50b769.png)
It shows that the memory usage for the dispatcher container is building up and never goes down

**Comment by montaro** [comment]
Debugging:
Using `pprof` Go tool, I'm blaming the NATS Go-Client because of the different heap profiles over time shows that 94%+ is consumed by the `nats.go processMsg()`
![image](https://user-images.githubusercontent.com/531945/71737552-43eda600-2e54-11ea-9753-805f0327c394.png)
![image](https://user-images.githubusercontent.com/531945/71737575-54058580-2e54-11ea-8bc2-4137ff2f13de.png)
![image](https://user-images.githubusercontent.com/531945/71737593-64b5fb80-2e54-11ea-822a-19424035be57.png)

**Comment by p4p4** [comment]
Hi @montaro 

> Hello, @p4p4 Thanks for reporting this bug with informative data!
> Do you have any numbers about the number of subscriptions at any given point? The frequency of sending events?

we have 67 subscriptions:
```
k get subscriptions.eventing.kyma-project.io --all-namespaces | wc -l 
67
```

and ~500 events per hour (actual number might vary)

**Comment by montaro** [comment]
We came to the same conclusion as mentioned here https://github.com/kyma-project/kyma/issues/6481#issuecomment-563978409
As soon as we got the NATS-Clients + the NATS Server upgraded then we'd be at least able to remove the third party blockers.
Will block this ticket for now.

**Comment by p4p4** [comment]
Thanks @montaro for the update. With the resource limit being set we had today after ~1 Month again the issue that no events were dispatched any more until we restatred the dispatcher.
Events stoppped at ~16:15 on January 14th

I grabbed the logs before the restart
[natss-dispatcher.zip](https://github.com/kyma-project/kyma/files/4063771/natss-dispatcher.zip)

**Comment by pbochynski** [comment]
Closed due to inactivity.
