### ISSUE TITLE
Change Service type NodePort to ClusterIP in Helm-Broker and Service Catalog

### ISSUE THREAD

**Issue by piotrmiskiewicz** [kyma-project/kyma#6621]
**Description**

Helm-Broker and Service-Catalog webhook services has type NodePort which must be changed to ClusterIP.

See: https://kubernetes.io/docs/concepts/services-networking/service/#type-nodeport
https://www.ibm.com/support/knowledgecenter/SSSHTQ/omnibus/helms/all_helms/wip/reference/hlm_upgrading_service_type_change.html

**Comment by aszecowka** [comment]
On one pipeline I got following error: 

>   Helm install error: rpc error: code = Unknown desc = release service-catalog failed: Service "service-catalog-catalog-webhook" is invalid: spec.ports[0].nodePort: Invalid value: 30441: provided port is already allocated

**Comment by mszostok** [comment]
We got 3 failures in last 3 days:
- https://status.build.kyma-project.io/view/gcs/kyma-prow-logs/logs/post-master-kyma-integration/1239548487213780993
- https://status.build.kyma-project.io/view/gcs/kyma-prow-logs/logs/post-master-kyma-gke-upgrade/1238160464454619137
- https://status.build.kyma-project.io/view/gcs/kyma-prow-logs/logs/post-master-kyma-gke-integration/1238402937194024962

**Comment by Ressetkk** [comment]
There was one failure today: https://status.build.kyma-project.io/view/gcs/kyma-prow-logs/logs/post-master-kyma-gke-upgrade/1240984069190193152

**Comment by mszostok** [comment]
by changing only the type from `NodePort` to `ClusterIP` we get such error:
```
UPGRADE FAILED
Error: Service "test-svc" is invalid: spec.ports[0].nodePort: Forbidden: may not be used when `type` is 'ClusterIP'
Error: UPGRADE FAILED: Service "test-svc" is invalid: spec.ports[0].nodePort: Forbidden: may not be used when `type` is 'ClusterIP'
```

to fix that problem we just need to set the **nodePort** to `null` when using `ClusterIP` type
