### ISSUE TITLE
Re-design and implement e2e kubeless tests

### ISSUE THREAD

**Issue by anishj0shi** [kyma-project/kyma#6630]
Current Implementation of end to end kubeless integration tests have been failing due to unknown reasons on nightly aks cluster. 

**Test Result**
https://sap-cx.slack.com/archives/CBMPTMCV9/p1576464951024600

**AC**
Lets re-implement the test using client-go and figure out the root cause of the intermittent issue and be consistent with our testing methodology.

**Comment by michal-hudy** [comment]
@anishj0shi is this needed as we are removing `kubeless`?

**Comment by anishj0shi** [comment]
Hey @michal-hudy 

if we are getting rid of kubeless, then we dont need this. This issue was merely to make this test more consistent with the other e2e tests.

**Comment by michal-hudy** [comment]
Ok, so I'm closing it
