### ISSUE TITLE
Re-design (e2e)s api-controller tests

### ISSUE THREAD

**Issue by magicmatatjahu** [kyma-project/kyma#6643]
**Description**

Current Implementation of e2e upgrade tests of `api-controller` have a dependency of `api-controller` e2e backup. This causes problems with bumping dependencies in upgrade tests, for example: if you want update deps of some kubernetes libs, then probably you firstly must update they in backup tests (usually you will have a problem with deprecated api in kubernetes libs or worst with some api from Kyma, like switching to v1.16 of k8s api).

**Reasons**

Upgrade tests of `api-controller` use as deps e2e backup tests, so maintenance is harder, especially if you want update deps.

**Attachments**

See current implementation of upgrade tests of `api-controller`: https://github.com/kyma-project/kyma/blob/master/tests/end-to-end/upgrade/pkg/tests/api-controller/test.go

**Comment by piotrmsc** [comment]
@magicmatatjahu api-controller is deprecated, those tests will be removed with controller itself ;-) New features are not added to api-controller since API gateway v2 was released.

**Comment by strekm** [comment]
api-controller was deleted
