### ISSUE TITLE
Steps to update TLS certificate wrongly documented (tried with version 1.5 and 1.6)

### ISSUE THREAD

**Issue by abbi-gaurav** [kyma-project/kyma#6651]
**Description**

When following the [tutorial](https://kyma-project.io/docs/1.7/components/security#tutorials-update-tls-certificate-steps), steps to update the various secrets are not correctly mentioned.

1. No such secret as `istio-ingress-gateway-certs`

```shell
kc get secrets --all-namespaces |grep istio-ingressgateway-certs #returns nothing
```

1. The wrong secret name `ingress-tls-cert`. For updating the `gateway.<domain>`, one needs to update the `application-connector-certs` in istio-integration namespace, not any secret in kyma-integration namespace.

**Expected result**

Following the tutorial step-by-step, one should be able to update the TLS certificates.

**Actual result**

Steps are wrongly documented which leads to error and getting invalid cert errors. Only after trial and error, figured out the actual secrets to be updated.

**Steps to reproduce**

* Have a cluster where the certificate has expired.
* Follow tutorial steps to update the certificate.

**Comment by Demonsthere** [comment]
Hi there,
Could you try to use the current documentation (1.10) instead?

**Comment by Disper** [comment]
@abbi-gaurav I will ask again as in previous question we didn't use a mention.
Could you try to use the current documentation (1.10) instead?

**Comment by abbi-gaurav** [comment]
@Disper, the challenge here I see is if the customer for some reason not yet upgraded to the version with the correct documentation,  he will not be able to update following the documentation. I can still live with fixes being made available in newer versions, but perhaps we need to revisit if the same can be applied to documentation.

**Comment by janmedrek** [comment]
We are not supporting such old releases, the correct guide is available in more up-to-date versions of our docs. I would say reaching back to 1.5 or 1.6 and backporting documentation changes would be a big overhead for the dev team.

For any further issues, we are happy to help ad-hoc, you can reach us via the Slack workspace. :)
