### ISSUE TITLE
Missing backup strategy for NATS Streaming data

### ISSUE THREAD

**Issue by Abd4llA** [kyma-project/kyma#671]
Easiness of attack: No attack
Impact: Moderate

NATS Streaming mounts a filesystem that it uses to store events. The data on this filesystem is never backed up.

Risk:
In case of data loss, some of the event data may get dropped. Consequently, kdelivery guarantees might be missed.
In case of data corruption, e.g. during a software upgrade, there is no way to roll-back without data loss.

Suggested Mitigation:
Implement frequent backups of the NATS Streaming data.
Make sure that backups don't contain corrupt data, due to concurrent write operations by NATS streaming. (Might require some sort of synchronization.)
Test backup recovery!

**Comment by abbi-gaurav** [comment]
@derberg could we ensure that the security issues are not marked by the stale bot?

**Comment by derberg** [comment]
@abbi-gaurav technically it is possible. But should we really do that? should we do it for all the issues or only critical ones? stale bot nicely reminds us every 60days we have such a security tickets that must be addressed, if we do not address it within 60 days, ignore them with stale bot, how can we assure actually fix?

**Comment by radufa** [comment]
After a short discussion with PB, cause NATS- Streaming will not be made "production-ready" now, the backup and restore of NATS-Streaming volume will be postponed.

**Comment by abbi-gaurav** [comment]
The events will not be backed up. The Kyma subscriptions will be backed. This is already covered as a part of backing up customer namespaces.
