### ISSUE TITLE
API Server Proxy Certs Job fails randomly on Gardener clusters

### ISSUE THREAD

**Issue by Szymongib** [kyma-project/kyma#6712]
**Description**

When installing Kyma on the Gardener cluster on Azure the installation hangs sometimes on the `core` component. The issue is that the `apiserver-proxy-certs-job` is failing randomly and some pods hang in Init state. 

**Steps to reproduce**

Kyma version: 1.8.0
Kubernetes version: 1.15.4

The issue seems to occur randomly when installing Kyma on Gardener with Azure provider.

**Troubleshooting**

**Comment by derberg** [comment]
@Szymongib please check who is a code owner for failing part and assign to him/them milestone

**Comment by piotrmsc** [comment]
@Szymongib can you provide logs from this job?
