### ISSUE TITLE
Application connector is not able to talk to some Applications due to tls error

### ISSUE THREAD

**Issue by joek** [kyma-project/kyma#6721]
**Description**

Connecting to some Applications application connector is not able to establish the TLS connection:

```
time="2019-12-20T12:57:56Z" level=error msg="Creating new service failed, Determining API spec for service with ID 79f14a40-1485-4d2f-998c-850ddc11677a failed, Fetching API spec from <URL> failed, Get <URL>: local error: tls: unexpected message" application=test
```

The same error happens in the App Gateway too.

**Expected result**

Connection is working

**Actual result**

No communication possible.

**Comment by janmedrek** [comment]
This was the issue introduced by protocol misalignment after update of Go version, it is already fixed on a master branch.

**Comment by janmedrek** [comment]
The workaround for this issue is updating image versions of Application Registry and Application Gateway, the versions to use can be found in this commit: https://github.com/kyma-project/kyma/commit/dd00bf893b5a43fe1d28ecccad0da75adbd24676
