### ISSUE TITLE
Disable Istio mixer spans in tracing

### ISSUE THREAD

**Issue by abbi-gaurav** [kyma-project/kyma#6723]
**Description**

In tracing, we also see spans related to istio-mixer. They do not provide or are used for any troubleshooting. Rather they are more of a noise in the traces.

We should consider disabling them.
Refer: https://istio.io/faq/distributed-tracing/#why-mixer-spans

**Comment by a-thaler** [comment]
Duplicates https://github.com/kyma-project/kyma/issues/6549
