### ISSUE TITLE
NATS Streaming is not highly available

### ISSUE THREAD

**Issue by Abd4llA** [kyma-project/kyma#673]
Easiness of attack: Complex
Impact: Significant

NATS Streaming is not configured to scale horizontally. Also, no liveliness probes are implemented.

Risk:
This makes NATS Streaming prone to DoS, or to accidental overload. Impacts availability of event processing.

Suggested Mitigation:
Configure NATS to run in a scaleable cluster configuration.
This may require additional communication between cluster nodes. Ensure that such communication channels are secure.

**Comment by abbi-gaurav** [comment]
Duplicate of #1011
