### ISSUE TITLE
Migrate Function Controller to Kubebuilder 2

### ISSUE THREAD

**Issue by michal-hudy** [kyma-project/kyma#6738]
**Description**

Migrate Function Controller to Kubebuilder 2 as it is compatible with Kubernetes 1.16 and provides a bunch of functionalities like controller scaling etc.

**Reasons**

Compatibility with Kubernetes 1.16, better resources management and performance.

**Attachments**

**Comment by m00g3n** [comment]
As agreed compatibility with kubernetes 1.16 is not in the scope of this task.
