### ISSUE TITLE
Sub-Validation app is not scalable

### ISSUE THREAD

**Issue by Abd4llA** [kyma-project/kyma#674]
Easiness of attack: Advanced
Impact: Moderate

The Sub-Validation app is designed to run as a singleton instance. It cannot be scaled horizontally.

Risk:
In case of frequent changes to subscriptions and event-activations, the Sub-Validation app could become a bottleneck. This could further increase the temporal gap between defining subscriptions/event-activations and putting them into production. Also see #675 .

Suggested Mitigation:
Improve Sub-Validation app, so it can be scaled horizontally. This might require adjustments to processing logic, in order to prevent race conditions.

**Comment by abbi-gaurav** [comment]
The app is no longer deployed.
