### ISSUE TITLE
CBS tests fails during upgrade between 1.8.0 and 1.9.0-rc1

### ISSUE THREAD

**Issue by kubadz** [kyma-project/kyma#6740]
**Description**

The issue occurred during the run of post-kyma-release-upgrade job after releasing Kyma 1.9.0-rc1 [(link)](https://status.build.kyma-project.io/view/gcs/kyma-prow-logs/logs/post-kyma-release-upgrade/1209084432984576000).

According to [release guidelines point 7](https://github.com/kyma-project/community/blob/master/guidelines/releases-guidelines/02-kyma-release-process.md#kyma-projectkyma):
> If the upgrade process requires any additional actions, the pipeline is likely to fail. In such case, the owners of the components concerned are responsible for running manual tests or modifying the pipeline.

**Expected result**

The test is passing.

**Actual result**

The test failed with log:
```
2019/12/23 13:08:30 Error while cleanup after failed setup for servicecatalog: while deleting ServiceBroker: servicebrokers.servicecatalog.k8s.io "ns-helm-broker" not found
2019/12/23 13:08:30 while setup for module servicecatalog: while injecting the addons configuration: while waiting for cluster addons configuration to be ready: timeout waiting to get AddonsConfiguration ready /testing-addons-cbs: {Failed 2019-12-23 13:03:35 +0000 UTC 1 [{https://github.com/kyma-project/addons/releases/download/0.8.0/index-testing.yaml Failed   [{redis 0.0.3 Failed ConflictWithAlreadyRegisteredAddon An addon with the same ID is already registered: [ConfigurationName: testing-addons, url: https://github.com/kyma-project/addons/releases/download/0.9.0/index-testing.yaml, addons: redis:0.0.3]} {testing 0.0.1 Failed ConflictWithAlreadyRegisteredAddon An addon with the same ID is already registered: [ConfigurationName: testing-addons, url: https://github.com/kyma-project/addons/releases/download/0.9.0/index-testing.yaml, addons: testing:0.0.1]}]}]}
Setting exit status to 1
2019/12/23 13:08:35 Querying BackendModule custom resources...
2019/12/23 13:08:37 Setting up tests...
2019/12/23 13:08:37 Cleaning up...
2019/12/23 13:08:38 while setup for module servicecatalogaddons: while injecting the addons configuration: while creating addons configuration: clusteraddonsconfigurations.addons.kyma-project.io "testing-addons-cbs" already exists
Setting exit status to 1
```

**Steps to reproduce**

1. create a cluster with Kyma in version 1.8.0
2. upgrade to 1.9.0-rc1
3. run tests

**Troubleshooting**

**Comment by kwiatekus** [comment]
This problem is reproducible. Exactly the same problem encountered with second re-run:
https://status.build.kyma-project.io/view/gcs/kyma-prow-logs/logs/post-kyma-release-upgrade/1211596219931955200
