### ISSUE TITLE
Event Bus services might process XML by accident

### ISSUE THREAD

**Issue by Abd4llA** [kyma-project/kyma#676]
Easiness of attack: Advanced
Impact: Moderate

Event Bus components (in particular Publish service, Push app, Sub-Validation app, NATS Server) are not designed to process XML that they receive over public interfaces. It mostly uses JSON instead. However, some frameworks that perform parsing, unmarshaling, and/or data binding are extremely tolerant when it comes to the data formats that they accept.

Risk:
If Event Bus processes XML by accident, it may be prone to related attacks such as XML eXternal Entity injection (XXE) or XML bombs. Similar risks may arise from other data formats.

Suggested Mitigation:
Make sure that all components that receive data from a client or a server only process the intended data format. In particular, make sure that they will not perform XML parsing, even if the request or response meta-data indicate XML contents.
Don't rely on the names of frameworks or libraries - even software with JSON in their name might silently fall-back to XML parsing if it deems it appropriate. Add tests to prove that XML will be rejected without parsing!

**Comment by lszymik** [comment]
We are not doing any processing. We are just storing an event as it is.
