### ISSUE TITLE
Upgrade Event Bus to Knative Eventing mesh

### ISSUE THREAD

**Issue by Abd4llA** [kyma-project/kyma#6763]
**Description**
Kyma 1.11 is planned to have only Knative Eventing mesh. An upgrade scenario needs to be planned and needed upgrade scripts and jobs be prepared so that customers with Kyma 1.10 can upgrade to 1.11 safely. An investigation is done in #6795

**AC**
- old resources (Kyma subscriptions and event activations) replaced with Knative channels, brokers and triggers, 
- users don't have to reconfigure their lambdas to be triggered with the same event using Knative triggers

**Comment by pbochynski** [comment]
Acceptance criteria for migration script:
- old resources (Kyma subscriptions and event activations) replaced with Knative channels, brokers and triggers, 
- users don't have to reconfigure their lambdas to be triggered with the same event using Knative triggers
