### ISSUE TITLE
High-privileges OS user in Event Bus containers

### ISSUE THREAD

**Issue by Abd4llA** [kyma-project/kyma#677]
Easiness of attack: Very Complex
Impact: Severe

Individual software components of the Event Bus are isolated inside Docker containers, but they run as the root user.

Risk:
In case of a vulnerability of the component and a vulnerability or misconfiguration of the underlying Docker engine, attackers could elevate their privileges and gain full access to the underlying host.

Suggested mitigation:
When running software inside containers, drop privileges and run as a non-root user.
This may require adjustments to the Dockerfile that is used to build the respective image.

Ideas:

    First define what all privileges are required for various containers.
    Identify where the changes can be made (Dockerfile / K8S deployment).
    How it should be solved for NATS Streaming?

AC:

    Event bus containers are running as non-root user process. Only necessary privileges should be granted.

**Comment by pbochynski** [comment]
Can we extend the scope of the task to all kyma components? Once the solution is found it can be applied it in all dockerfiles.

**Comment by sergio-oss** [comment]
@anishj0shi I guess this will not be applicable anymore ?

**Comment by anishj0shi** [comment]
event-bus is deprecated and purged in current master version
