### ISSUE TITLE
Event Bus services may disclose internal information

### ISSUE THREAD

**Issue by Abd4llA** [kyma-project/kyma#678]
Easiness of attack: No attack
Impact: Moderate

This may or may not concern all service that comprise the Event Bus and expose an external API, e.g. via HTTP. In particular this may concern the Publish service and NATS Streaming.

Risk:
Often, HTTP implementations reveal too much information to clients. Attackers can use that to learn about their target and plan further attacks. Information that should not be exposed include:

    Exact software versions (sometimes seen in the HTTP server header, or in error messages)
    Technical error messages (often passed through from library errors/exceptions)
    Stack-traces
    ...

Suggested mitigation:

    Double-check if frameworks or application code might reveal such information by accident.
    Remove unnecessary information from API responses.
    Use custom error messages in API responses, and only reveal necessary details.
    Replace default error pages (e.g. for HTTP 4xx and 5xx responses) by custom ones. (Don't use HTML error pages - instead use the data format that is used for successful HTTP responses, e.g. JSON.)
    Make sure that HTTP server does not expose any filesystem directories. (Yes, some HTTP frameworks do that by default.)
    Consider logging internal information rather than putting it into API responses.
    ...

Suggested work:

    Browse through all event-bus components
    Check success and failure paths
    Check the logs, HTTP response headers
    Review error messages
    Check the response body and headers for the probe endpoints.

AC:

    No internal information is disclosed from event-bus APIs
    All necessary fixes have been implemented and deployed to kyma nightly cluster.

**Comment by abbi-gaurav** [comment]
There is no internal information disclosed in the response than expected from the API behavior.
