### ISSUE TITLE
Disable operation permissions in kyma system namespaces for kyma roles

### ISSUE THREAD

**Issue by piotrmsc** [kyma-project/kyma#6784]
**Description**

Provide a mechanism for disabling permissions in kyma system namespaces (kyma-system, istio-system, kyma-installer) for roles (kyma developer& viewer) leaving permissions to other namespaces at the same time.

Users should have admin or developer access to namespaces they create, however, only `kyma-admin` should be cluster role with permissions to manage resources in kyma system namespaces and other.

This should be automated, working dynamically, without any additional steps to do. It should work the same way for namespaces created in kyma console as well as via kubectl.

There should be something like namespace admin cluster role which should be bound automatically for given group of users.

**Reasons**

Current authorization model defines kyma admin, kyma developer and kyma viewer role, where last two are roles and first is a cluster role. Kyma admin gives access to kyma resources as well as k8s resources across all namespaces which is too permissive for scenarios where kyma is installed for and given to customers.

**Attachments**

**Comment by colunira** [comment]
To create a namespace controller using kubebuilder run the command: `kubebuilder create api --version v1 --kind Namespace --group "core"`
