### ISSUE TITLE
Knative Eventing mesh dashboard  - delivery

### ISSUE THREAD

**Issue by Abd4llA** [kyma-project/kyma#6787]
**Description**
We need a dashboard that shows the eventing delivery status of all Knative Eventing mesh related components. Initially, we want to monitor HTTP Status codes (2XX, 4XX, 5XX..etc) for following pods
* Validator
* HttpSource (event_count)
* HttpSource Channel pod (producer pods for Kafka)
* Broker Channel pod
* Filter pods
* Subscriber (lambda)

**AC**
- Kyma includes the mentioned dashboard changes
- In case of missing metrics, proper issues are created for them

**Comment by montaro** [comment]
@Abd4llA Should we add the Broker-Ingress metrics as well?
https://github.com/knative/eventing/blob/master/docs/metrics.md#broker
