### ISSUE TITLE
Deletion of a knative Broker does not delete the underlying Natsschannel

### ISSUE THREAD

**Issue by anishj0shi** [kyma-project/kyma#6792]
During External Solution Test Cleanup, there's a step where the test runner cleans up the namespace, this particular step is suspend due to a dangling CR NATSChannel, which somehow has a finaliser that prevents this CR from deletion and as a consequence the Namespace is stuck to **Terminating** Step.

**AC**
The NatssChannel reconciler needs to remove the finaliser if there's a deletion timestamp.

**Comment by nachtmaar** [comment]
The `finalizer` on the `NatssChannel` is set by the natsschannel dispatcher [here](https://github.com/knative/eventing-contrib/blob/25356c5324b24548f8ce8a2c996e3afc3bc73a2c/natss/pkg/reconciler/dispatcher/natsschannel.go#L155).
Its purpose is to delete the natss subscription then the channel gets deleted, see [here](https://github.com/knative/eventing-contrib/blob/25356c5324b24548f8ce8a2c996e3afc3bc73a2c/natss/pkg/reconciler/dispatcher/natsschannel.go#L144).
