### ISSUE TITLE
Event bus deletion and upgrade investigation

### ISSUE THREAD

**Issue by Abd4llA** [kyma-project/kyma#6795]
**Description**
Investigate how to delete Event Bus chart, objects and trigger upgrade script which will be implemented in #6763

**Note**
- Check if we can delete Event Bus related object during deleting Event Bus chart (any hook for deletion in the chart?)

**AC**
1. Investigation is documented properly.

**Comment by antoineco** [comment]
### Expectation

At the end of the Kyma upgrade, the user is left with an event mesh that has feature parity with the previous Kyma version, without the need for any manual configuration and without message loss.

### Logical steps

1. Replicate existing eventing components onto the new event mesh, for each Kyma application.
    For the duration of the update, each application can technically support both event meshes, old and new.
2. Deploy compatibility layer (_to be defined_)
    Messages sent to legacy APIs get routed to the new event mesh.
3. Drain legacy message channels
    In-flight messages must be delivered before the old event mesh gets shut down.
4. Purge old event mesh

### Technical considerations

* **The update logic for _step 1_ needs to be hooked into an existing component, but the event mesh encompasses multiple components.**
    Proposed action: consolidate all custom update steps into update hooks at the level of the `knative-eventing` component, which all other components depend on.
* **The Kyma operator does not currently uninstall components which are no longer required.**
    Proposed action: implement custom logic at the end of the operator's reconciliation to purge the `event-mesh` chart, since this will not be supported anymore moving forward.

**Comment by antoineco** [comment]
### Expectation

At the end of the Kyma upgrade, the user is left with an event mesh that has feature parity with the previous Kyma version, without the need for any manual configuration and without message loss.

### Logical steps

1. **Replicate existing eventing components onto the new event mesh, for each Kyma application.**
    For the duration of the update, each application can technically support both event meshes, old and new.
2. **Deploy compatibility layer** (_to be defined_)
    Messages sent to legacy APIs get routed to the new event mesh.
3. **Drain legacy message channels**
    In-flight messages sent to legacy APIs must be delivered before the old event mesh gets shut down.
4. **Purge old event mesh**

### Technical considerations

* **The update logic for _step 1_ needs to be hooked into an existing component, but the event mesh encompasses multiple components.**
    Proposed action: consolidate all custom update steps into update hooks at the level of the `knative-eventing` component, which all other components depend on.
* **The Kyma operator does not currently uninstall components which are no longer required.**
    Proposed action: implement custom logic at the end of the operator's reconciliation to purge the `event-mesh` chart, since this will not be supported anymore moving forward.

**Comment by antoineco** [comment]
### Expectation

At the end of the Kyma upgrade, the user is left with an event mesh that has feature parity with the previous Kyma version, without the need for any manual configuration and without message loss.

### Logical steps

1. **Replicate existing eventing components onto the new event mesh, for each Kyma application.**
    For the duration of the update, each application can technically support both event meshes, old and new.
2. **Deploy compatibility layer** (_to be defined_)
    Messages sent to legacy APIs get routed to the new event mesh.
3. **Drain legacy message channels**
    In-flight messages sent to legacy APIs must be delivered before the old event mesh gets shut down.
4. **Purge old event mesh**
    Includes both control (chart) and data (API objects) planes.

### Technical considerations

* **The update logic for _step 1_ needs to be hooked into an existing component, but the event mesh encompasses multiple components.**
    Proposed action: consolidate all custom update steps into update hooks at the level of the `knative-eventing` component, which all other components depend on.
* **The Kyma operator does not currently uninstall components which are no longer required.**
    Proposed action: implement custom logic at the end of the operator's reconciliation to purge the `event-mesh` chart, since this will not be supported anymore moving forward.
* **Old API objects need to be removed before their respective CRDs are de-registered from the cluster.**
    This must happen before uninstalling the chart.

**Comment by anishj0shi** [comment]
> Purge old event mesh

You mean **Event Bus**

- if kyma-installer does not  remove the chart,  How do you propose deleting the event-bus helm chart?
-  If you delete event-bus, does it make sense to have a future of event-service in this proposal? in terms of what would you do with the event service, as it would point to an non-existing handler (Publish Service)
- Any details about the helm hooks required to be introduced or updated?

Do you have a flow in your mind, can you , maybe, give a diagrammatic representation  about your proposal?

**Comment by antoineco** [comment]
Yes, by "old event mesh" I mean the component currently called `even-bus`. The naming is not very relevant here, since we don't have a component called `event-mesh`. Besides, why is one a "bus" and the other one a "mesh

**Comment by antoineco** [comment]
Yes, by "old event mesh" I mean the component currently called `even-bus`. The naming is not very relevant here, since we don't have a component called `event-mesh`. (Besides, why is one a "bus" and the other one a "mesh"? Same architecture.)

1. I proposed something, last title point 2.
2. I need more input from you since I don't know about that component.
3. Will add this, good suggestion.
4. Will add this, good suggestion.

**Comment by k15r** [comment]
can we put this information into git in order not to lose it?

**Comment by k15r** [comment]
currently we focused purely on the kyma-installer and its helm charts.
we have the additional helm charts that get installed using application-operator. These install 
event-service, validator and some other components per application.
In case of an upgrade those helm charts also need to be modified in such a way, that they remove unnecessary components.

**Comment by antoineco** [comment]
> we have the additional helm charts that get installed using application-operator
Exactly why I preferred to remain general instead of just saying "event bus". I will include more details in the diagram, thanks for pointing it out. 
> can we put this information into git in order not to lose it?
The outcome of this little exploration will be stored together with the code related to it as part of #6763. Meanwhile, I'll send a dummy PR with a markdown document so we can comment on it easier than via GitHub comments.
