### ISSUE TITLE
Publish service or NATS Streaming Server might leak event payloads into logs

### ISSUE THREAD

**Issue by Abd4llA** [kyma-project/kyma#680]
Easiness of attack: Complex
Impact: Significant

Both the Publish service and the NATS Server (or NATS Streaming?) support configuration switches that enable HTTP request logging or event logging that would include the payload.

Risk:
Event payloads may contain confidential application data that must not end up in logs.

Suggested mitigation:
Add documentation that event payload logging MUST be disabled it in production.
Consider adding log messages that warn users about misconfiguration.

 

AC:

    Event payload is not logged for any positive or negative scenarios of Event Bus.
    Traces are not containing the event payload.
    The verification is confirmed by a comment in the task.

**Comment by abbi-gaurav** [comment]
The logs are not printing the event payload.
