### ISSUE TITLE
Events are not delivered to a lambda configured with an event trigger

### ISSUE THREAD

**Issue by abbi-gaurav** [kyma-project/kyma#6813]
**Description**

After creating the event trigger for lambda, the expected behavior is to have lambda triggered when an event is sent from the external system. This was not happening.

On joint investigation with @anishj0shi, it was discovered that the `Kyma Subscription` status was `Not Ready`. 

As a workaround, we have to delete the
1. Knative subscription
2. Deselect the event trigger for the lambda (remove Kyma Subscription).
3. Create the trigger again.

**Impact**
* Business transactions/scenarios using event triggers will not work.

**Comment by anishj0shi** [comment]
kyma eventing is now switched to event-mesh. and the lifecycles the old *kyma-subscriptons* will not be maintained
