### ISSUE TITLE
Unable to delete clusterservicebrokers.servicecatalog.k8s.io CRD

### ISSUE THREAD

**Issue by Maladie** [kyma-project/kyma#6838]
**Description**

While trying to deprovision Gardener(GCP) cluster with Kyma installed, it returns the following error: 

> Flow "Shoot cluster deletion" encountered task errors: [task "Cleaning extended API groups" failed: 1 error occurred:
retry failed with context deadline exceeded, last error: remaining objects are still present: [*v1beta1.CustomResourceDefinition /clusterservicebrokers.servicecatalog.k8s.io]

Also, the clusterservicebrokers.servicecatalog.k8s.io CRD can't be removed manually

**Expected result**

clusterservicebrokers.servicecatalog.k8s.io CRD deleted, cluster deprovisioned successfully

**Actual result**

Cluster deprovisioning fails due to persisting resources.

**Steps to reproduce**

1. Provision cluster on Gardener and install Kyma.
2. Try to deprovision the cluster

**Comment by PK85** [comment]
@Maladie how do you deprovision Kyma environment? 
Steps:
- uninstall Kyma, then
- delete cluster
?

**Comment by Maladie** [comment]
@PK85 Not really, I simply tried to delete cluster. Uninstalling Kyma first fixed the problem. Thanks.
