### ISSUE TITLE
Unable to delete installations.installer.kyma-project.io CRD

### ISSUE THREAD

**Issue by Maladie** [kyma-project/kyma#6840]
**Description**

While trying to deprovision Gardener(GCP) cluster with Kyma installed, it returns the following error: 

> Flow "Shoot cluster deletion" encountered task errors: [task "Cleaning extended API groups" failed: 1 error occurred:
retry failed with context deadline exceeded, last error: remaining objects are still present: [*v1beta1.CustomResourceDefinition /installations.installer.kyma-project.io]

Also, installations.installer.kyma-project.io CRD can't be removed manually

**Expected result**

installations.installer.kyma-project.io CRD deleted, cluster deprovisioned successfully

**Actual result**

Cluster deprovisioning fails due to persisting resources.

**Steps to reproduce**

1. Provision cluster on Gardener and install Kyma.
2. Try to deprovision the cluster

**Comment by tehcyx** [comment]
Running into the same problem today.

```
Cleaning extended API groups
Last Errors
task "Cleaning extended API groups" failed: 1 error occurred:
	* retry failed with context deadline exceeded, last error: remaining objects are still present: [*v1beta1.CustomResourceDefinition /installations.installer.kyma-project.io]
```

On the cluster a
```bash
$ kubectl delete installation/kyma-installation
installation.installer.kyma-project.io "kyma-installation" deleted
```
just hangs and doesn't complete.

**Comment by valentinvieriu** [comment]
I can confirm that this situation also happen with Kyma 1.12
This makes testing quickly a Kyma installation quite expensive, as it takes quite a long time for Gardener to force kill the cluster.

**Comment by trinoy** [comment]
I am facing the same issue with Kyma 1.12. Any way to resolve it?

**Comment by Demonsthere** [comment]
This behaviour is caused by the finalizer on the kyma resources, to fix that, delete the resources by hand (kubectl), which should free the process. 
We will update the docu to include this situation and link to this issue. 
Cheers

**Comment by Tomasz-Smelcerz-SAP** [comment]
The installation CR can be deleted once the finalizer on it is removed.
Troubleshooting guides are extended with information about removing finalizer: #9483
