### ISSUE TITLE
Prometheus running out-of-memory

### ISSUE THREAD

**Issue by hisarbalik** [kyma-project/kyma#6860]
Prometheus instances on the weekly cluster running after a while out-of-memory. Increasing of pod memory doesn't help to solve problem, some heap profiling shown after re-start of prometheus, prometheus load metric data in the memory and after hitting 2G limit prometheus run out-of-memory

**Comment by a-thaler** [comment]
We reduced the amount of metrics and timeseries by whitelisting the metrics scraped from istio components. Furthermore limits on querying were applied. With that the memory consumption is much more stable.
