### ISSUE TITLE
unify container image names

### ISSUE THREAD

**Issue by k15r** [kyma-project/kyma#6866]
**Description**

Image names used throughout kyma should follow a consistent naming convention. This was agreed upon in https://github.com/kyma-project/community/blob/master/collaboration/sig-core/proposals/image-name-consolidation.md

In order to implement this proposal the following steps shall be implemented:

1. move tests according to https://github.com/kyma-project/kyma/issues/2504
1. create  jobs on github.com/kyma-project/test-infra to build tests from their new location
1. update ```Makefiles``` for components and tests to follow the new naming pattern
1. update image references in all helm-charts across the entire kyma repository

**Comment by pbochynski** [comment]
@k15r Are you going to work on that?

**Comment by k15r** [comment]
I still believe this change would be beneficial for kyma. I cannot implement it at the moment though, as we have other more critical changes to implement.

**Comment by k15r** [comment]
inactivitiy shows that this is not a needed change. will close the issue
