### ISSUE TITLE
Events failing in natts-dispatcher 

### ISSUE THREAD

**Issue by brendandobbs** [kyma-project/kyma#6897]
**Description**

On a newly provisioned 1.9 cluster we saw events failing to be processed by the natts-dispatcher. The events with commerce from Commerce (1905). 

The dispatcher shows the following in the logs...

`{"level":"info","ts":"2020-01-16T10:11:11.720Z","logger":"controller","caller":"channel/message_receiver.go:148","msg":"Could not extract channel","error":"Invalid HostName:\"ordercrea-tgw4r-kn-channel.kyma-system.svc.cluster.local\". HostName not found in any of the watched natss channels"}`

**Troubleshooting**

Restarting the natts dispatcher fixes the issue

**Comment by anishj0shi** [comment]
Hi @brendandobbs is this issue still valid?
