### ISSUE TITLE
Backup-restore tests dependency management is broken

### ISSUE THREAD

**Issue by Tomasz-Smelcerz-SAP** [kyma-project/kyma#6906]
**Description**

Backup tests (/tests/end-to-end/backup) is a single golang project that has a single dependency to Kyma. Currently, it's set to 1.8 although we're working on 1.10
An attempt to bump dependency to the latest version (code from kyma/master) fails, some projects are already refactored and even `dep ensure` fails.
The problem is: How can I introduce a new backup test? This test depends on, say, clientset from some component, similar to existing tests. The component is not in release 1.8, it's on master and will be a part of release 1.10
But I can't introduce this dependency - this will break the build because of fixed dependency on version 1.8.

**Reasons**
The improvements should address the following:

1) I don't want to spend my time on keeping all existing tests  "up to date" with changes on master every time I want to add/refactor/improve tests for my component.

2) Test project structure must provide the ability to introduce changes independently for every component.

3) Do we know what we are actually testing? We run backup tests against the latest release (1.9) using code based on version 1.8. Who knows what are the consequences? Are there false positives? Missing important parts? Are all the new features tested?

**Summary**
I don't have any solution ready. 
For the start of discussion: I think those tests should be much closer to components, i.e: in the same golang project as the component. Then we have an exact match between component version and test version - the git commit. It also forces developers to keep the tests up to date with changes in component's - assuming we build the tests along with the component.

**Comment by k15r** [comment]
it will be fixed here: https://github.com/kyma-project/kyma/pull/6893

but we need to find a generic solution to always bump the kyma-project/kyma dependendy to latest...

**Comment by suleymanakbas91** [comment]
Not valid any more.
