### ISSUE TITLE
Console sometimes has a problem with connection to minio due by CORS

### ISSUE THREAD

**Issue by magicmatatjahu** [kyma-project/kyma#6907]
**Description**

Probably by upgrade istio to 1.4, `console-ui` has a problem with connection to minio due by CORS. It is not deterministic. Sometimes works, sometimes not.

AC:
- investigate where is a problem (probably problem is with VirtualService of minio) and resolve.
- Write small tests (probably best place will be Rafter Integration tests) with simple curl to minio to appropriate file to avoid and check future problems of connection.

**Expected result**

Connection between `console-ui` and `minio` always works.

**Actual result**

Connection between `console-ui` and `minio` sometimes doesn't work.

**Steps to reproduce**

Provision cluster from master revision, login to console, go to some serviceclass details or documentation view and you have a big probability than you cannot fetch documentation from minio, due by CORS.

**Comment by michal-hudy** [comment]
It doesn't work because:
 - CORS is not defined in VirtualService
 - Service port name is not prefixed with the protocol (http)
