### ISSUE TITLE
Add a note to the installation guide for AKS CNI configuration

### ISSUE THREAD

**Issue by brendandobbs** [kyma-project/kyma#6933]
**Description**

Azure AKS provides 2 network plugins, kubenet and CNI. Kubenet is the default however some of our customers are choosing CNI because they have some specific networking requirements that can't be met with kubenet.

The default maximum pods for kubenet is 110 and for CNI it's 30. With a maximum of 30 the cluster is unstable and nothing can be deployed.

Can we update the installation guide to either have a note to set the max pods parameter (--max-nodes) for CNI networking or to keep it simple, just change the example cli command to explicitly set the pods per node
e.g.
`az aks create --resource-group $RS_GROUP --name $CLUSTER_NAME --node-vm-size "Standard_D4_v3" --kubernetes-version 1.14.6 --enable-addons "monitoring,http_application_routing"  --generate-ssh-keys --max-pods 110`

Installation guide - 
https://kyma-project.io/docs/#installation-install-kyma-on-a-cluster-prepare-the-cluster
Azure CLI - https://docs.microsoft.com/en-us/cli/azure/aks?view=azure-cli-latest#az-aks-create
AKS container limits - https://github.com/MicrosoftDocs/azure-docs/blob/master/includes/container-service-limits.md

**Comment by strekm** [comment]
@brendandobbs thanks for reporting. Unfortunately at the moment, we do not support CNI network plugins. We would need time to test it and have it covered with our Prow pipelines.

**Comment by brendandobbs** [comment]
Hi @strekm, regardless can't we update the kyma documentation? We don't need to say that CNI is officially supported, just to be aware that the max-pods will need to be increased.

**Comment by PK85** [comment]
PR has been merged, ticket right now has been closed
