### ISSUE TITLE
Dangling subscriptions cause the upgrade from 1.8 to 1.9 stuck endlessly

### ISSUE THREAD

**Issue by himanshu-sv** [kyma-project/kyma#6940]
**Description**

On upgrading the kyma cluster  from 1.8 to 1.9, dangling subscriptions in the kyma-system namespace cause the upgrade to get stuck endlessly.  In this particular case, these were subscription objects of the lambdas from a deleted namespace.
They have to be manually deleted which then allows the up-gradation to proceed. 

**Expected result**
The cluster should get upgraded seamlessly.

**Actual result**

The upgrade process is stuck. 

**Steps to reproduce**
1. Create a namespace
2. Create a lambda with a subscription
3. Delete the lambda and the namespace.
4. Try upgrading the cluster from 1.8 to 1.9

**Comment by pbochynski** [comment]
Is there a way to modify the pre-upgrade job that detects such subscriptions and tries to delete them or at least reports that fact?

**Comment by anishj0shi** [comment]
Hey @pbochynski , this issue with the reconciler was fixed in 1.9 : https://github.com/kyma-project/kyma/pull/6266. for 1.8 we decided to have a troubleshooting guide, as this is a corner case. ref #6983

**Comment by evilyeti** [comment]
In addition, looking at the description above - it seems as if the subscription deletion is not initiated when the lambda got deleted, or do I miss something? cc: @Abd4llA

**Comment by anishj0shi** [comment]
Hi @himanshu-sv 
This issue is now addressed as a documentation change.  we have updated our troubleshooting guide to address this problem, https://github.com/kyma-project/kyma/pull/7061 
Documentation link: https://kyma-project.io/docs/master/components/event-bus/#troubleshooting-troubleshooting-knative-eventing-upgrade
