### ISSUE TITLE
AKS Nightly fails on Istio installation

### ISSUE THREAD

**Issue by strekm** [kyma-project/kyma#6942]
**Description**

Since few days AKS Nightly timeouts on Istio installation. Looks like Istio specific CRD are not registered. https://storage.googleapis.com/kyma-prow-logs/logs/kyma-aks-nightly/1218020186175574017/build-log.txt

**Expected result**

Istio should be installed.

**Actual result**

Installation fails. Kyma is not installed.

**Comment by Demonsthere** [comment]
Helm related issue:
- https://github.com/helm/helm/issues/6361
- https://github.com/helm/helm/pull/7196

**Comment by Demonsthere** [comment]
Source of the error for blocked istio installation: https://github.com/kyma-project/test-infra/blob/master/prow/scripts/cluster-integration/kyma-aks-long-lasting.sh#L264 
The override is wrong and missing the mask part. 
On the other hand, it seems the override was not working correctly in istio previously, and may not be needed at all now.
