### ISSUE TITLE
kyma-garderner-azure-integration fails in knative-eventing installation

### ISSUE THREAD

**Issue by sayanh** [kyma-project/kyma#6950]
**Description**

knative-eventing installation fails as in here 

**Expected result**

**Actual result**

Installation is stuck in knative-eventing.
Gardener installs Kyma 1.8 meaning Knative-eventing 0.8
Error in installer:
```
Description: 'Release "knative-eventing" failed: Internal error occurred: failed
    calling webhook "pilot.validation.istio.io": Post https://istio-galley.istio-system.svc:443/admitpilot?timeout=30s:
    read tcp 192.168.123.6:49384->100.96.0.17:443: read: connection timed out'
```
kubernetes version 1.15.*

**Steps to reproduce**
Install kyma using Gardener on Azure

**Troubleshooting**

https://storage.googleapis.com/kyma-prow-logs/logs/kyma-gardener-azure-integration/1219937821947596800/build-log.txt

**Comment by sayanh** [comment]
Last shows, knative-eventing is through but fails at natss-streaming
https://storage.googleapis.com/kyma-prow-logs/logs/kyma-gardener-azure-integration/1220300206512279552/build-log.txt

**Comment by sayanh** [comment]
Turns out, installation of natss-streaming flaky. On this occasion https://storage.googleapis.com/kyma-prow-logs/logs/kyma-gardener-azure-integration/1221024983535325184/build-log.txt the installation worked.

**Comment by nachtmaar** [comment]
See discussion here: https://github.com/kyma-project/kyma/issues/6876

Going to close it cc: @sayanh
