### ISSUE TITLE
Register service via metadata url fails if application has a certain name

### ISSUE THREAD

**Issue by tehcyx** [kyma-project/kyma#6955]
**Description**
Using kyma 1.8.0 if I create an application with a certain name (e.g. v0.0.1, v0.1.1-hello-world), the metadata url to register APIs and Events will always return a 404. This seems it is related to how the URL looks:
`https://gateway.<my-ip>.xip.io/v0.0.1/v1/metadata/services`

It actually seems, that if the name is `v1` the call succeeds.

The UI does not restrict these names and therefor registering APIs and Events is not possible.

**Expected result**
UI should restrict using names that clash or register API and Events call should not end in a 404.

**Actual result**
Calling metadata URL returns a 404

**Steps to reproduce**
Go to `https://console.<my-ip>.xip.io/home/cmf-apps`, create an application with name `v0.0.1`, connect application and then try to register API/Events.

**Troubleshooting**
Using different names for the application will work. Not sure if this problem is related only to 1.8.0 installs or also affecting prior and later versions.

**Comment by janmedrek** [comment]
With the shift to Compass based Application Connectivity Metadata Service will be deprecated. As the issue is not critical this will not be worked on.
