### ISSUE TITLE
Proper port names required for Helm broker.

### ISSUE THREAD

**Issue by rakesh-garimella** [kyma-project/kyma#6965]
**Description**
Proper naming is required for the http ports as this prevents the metrics being scraped by the service monitor.

For example:

`helm-broker` service uses port name as `http-metrics` which is also used in `addon-controller-metrics` thus the scraping is broken.

**Expected result**
kyma-system/helm-broker is shown up and the metrics are scraped properly
**Actual result**
`kyma-system/helm-broker` is shown `down`.

**Steps to reproduce**

It can be seen on a vanilla kyma installation with prometheus.

**Comment by klaudiagrz** [comment]
Already fixed:
https://github.com/kyma-project/kyma/blob/master/resources/helm-broker/templates/extras/metrics.yaml
