### ISSUE TITLE
Kyma update documentation misses compatible K8S version

### ISSUE THREAD

**Issue by abbi-gaurav** [kyma-project/kyma#6969]
**Description**

While updating a long-running Kyma cluster (K8S version  1.14.x), Kyma version 1.8, I ran into issues when updating Kyma to 1.9. It would be helpful if the update section describes the required K8S version.

IMHO It would not be the right expectation for the user to always look at the installation docs and then do an update since for updates you do not need to follow any installation steps.

**Comment by michal-hudy** [comment]
@a-thaler what do you think? 😄

**Comment by Demonsthere** [comment]
@a-thaler ping
