### ISSUE TITLE
Kyma upgrade to 1.9 fails for older clusters

### ISSUE THREAD

**Issue by abbi-gaurav** [kyma-project/kyma#6979]
## Description
I have a Kyma cluster that is 153 days old. While updating from 1.8 to 1.9, the upgrade fails with the following error.

```
kc -n kyma-system logs -f rafter-migration-terminator-9zqh9
fetch http://dl-cdn.alpinelinux.org/alpine/v3.10/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.10/community/x86_64/APKINDEX.tar.gz
OK: 35 MiB in 33 packages
(1/1) Installing deps (20200124.101037)
OK: 35 MiB in 34 packages
(1/1) Installing openssl (1.1.1d-r2)
Executing busybox-1.30.1-r2.trigger
OK: 36 MiB in 35 packages
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  7164  100  7164    0     0  16699      0 --:--:-- --:--:-- --:--:-- 16699
Helm v2.10.0 is available. Changing from version v2.16.1.
Downloading https://get.helm.sh/helm-v2.10.0-linux-amd64.tar.gz
Preparing to install helm and tiller into /usr/local/bin
helm installed into /usr/local/bin/helm
info: tiller binary was not found in this release; skipping tiller installation
Run 'helm init' to configure helm.
No resources found
error: no matching resources found
No resources found
error: no matching resources found
Error: incompatible versions client[v2.10.0] server[v2.9.1]
```

It seems that the cluster has tiller version `v2.9.1` and the migration workload expects `v2.10.0`. 
The same scenario is also valid for a customer cluster.

## Expected results
Kyma upgrades seamlessly from 1.8 to 1.9

**Comment by magicmatatjahu** [comment]
Please run this command: https://kyma-project.io/blog/2020/1/9/release-notes-19/#tiller There (in deployment) is 2.16.1 tiller version, but as I know 2.10.0 client is compatible with 2.16.1 tiller. If it won't work, please update tiller's version manually running this command:

``` bash
kubectl edit deployment -n kube-system tiller-deploy
```

and changing version `2.9.1` to `2.10.0`.

**Comment by abbi-gaurav** [comment]
The issue here is that the update instructions are not self-contained. It should be ensured that a customer updating the cluster via the update instructions should have all the steps correctly listed. One should not expect them to go through all the release notes. The same issue was experienced by customers while upgrading Kyma

**Comment by jakkab** [comment]
Release 1.9 is missing the migration guide: https://github.com/kyma-project/kyma/issues/7052

**Comment by pbochynski** [comment]
Closing this one. Follow the linked issue: https://github.com/kyma-project/kyma/issues/7052
