### ISSUE TITLE
Add a Troubleshooting Guide for an intermittent upgrade issue

### ISSUE THREAD

**Issue by anishj0shi** [kyma-project/kyma#6983]
w.r.t #6940 
During the upgrade process from 1.8 to 1.9 it was observed that the pre-upgrade job of knative-eventing was stuck at this line.
https://github.com/kyma-project/kyma/blob/75ace9a15a79f49adb575a729612e687224af1ef/resources/knative-eventing/charts/knative-eventing/templates/pre-upgrade-job.yaml#L58

This was because the knative eventing CRs were not deleted due to a finaliser added by the kyma event-bus-subscription-controller. 

*AC*
We need to have a troubleshooting guide which can help out end user to find such Dangling Knative Subscriptions and remove the finalisers to unblock upgrade process

**Comment by bszwarc** [comment]
@anishj0shi, 
I would put this troubleshooting guide among the existing guides here: https://kyma-project.io/docs/components/event-bus/#troubleshooting-troubleshooting.
So the best way is to add a separate document here: https://github.com/kyma-project/kyma/tree/master/docs/event-bus. 
According to the naming convention, I would call it 10-03-troubleshooting-upgrade (or something similar,  the most important part is that it starts with `10-03` which means that the document is the third one of the `troubleshooting` type.
Use this template to provide the content: https://github.com/kyma-project/community/blob/master/guidelines/templates/resources/troubleshooting.md (it's not very exhaustive, but don't forget about the metadata) :) 
Let me know if you need some help on that :)
