### ISSUE TITLE
Improve Function CR status messages

### ISSUE THREAD

**Issue by aerfio** [kyma-project/kyma#6986]
**Description**

Improve status messages on Function CR, in case of error  - right now if anything bad happens (e.g Tekton build fails, or we somehow create fn that bypases webhooks) the only thing we see is status `ERROR`

**Reasons**

We should provide clear reason as to why certain parts of our system are in specific state, not only to have easier development, but also to provide users with rich info about product they use

**Attachments**

**Comment by michal-hudy** [comment]
I think it is currently improved, @aerfio ?

**Comment by aerfio** [comment]
Yeah, it is better now @michal-hudy, I'll close it now
