### ISSUE TITLE
Migrate function-controller webhooks from the form used in Kubebuilder 1 to Kubebuilder 2

### ISSUE THREAD

**Issue by aerfio** [kyma-project/kyma#6990]
**Description**
Relevant after #5646 is merged

Kubebuilder 2 changed the way webhooks are organized, which is outliined in official Kubebuilder book [here](https://book.kubebuilder.io/cronjob-tutorial/webhook-implementation.html) and in controller-runtime examples [here](https://github.com/kubernetes-sigs/controller-runtime/blob/master/examples/README.md). What we have right now is basically old scaffold from kubebuilder 1 adapted to work somehow (as I understand this is old, alternate path) with newer version of `controller-runtime` lib. Newer examples diverge from kubebuilder 1 examples, like here: https://godoc.org/github.com/kubernetes-sigs/controller-runtime/pkg/builder#example-Builder

Moreover even though our webhook is validating _and_ mutating, it is declared as one mutating webhook.

While migrating it should be split into two parts (and by that I mean implementing admission.Defaulter and admission.Validator and adding proper kubebuilder markers, and updating `config/webhook` folder (hint: just generate empty kubebuilder project, add webhooks to it and then copy its `config/webhooks`))

**Reasons**

Changing architecture to prefered way enables us to use examples and methods that are actively maintained, thus improving our workflow and in result fun-controller

**Attachments**

**Comment by michal-hudy** [comment]
Function controller don't have webhooks currently
