### ISSUE TITLE
Concept for performance test storage

### ISSUE THREAD

**Issue by pbochynski** [kyma-project/kyma#6995]
**Description**
Evaluate alternative approaches to store performance metrics for a longer period. One example could be the way we deal with [test coverage](https://datastudio.google.com/u/0/reporting/1TmjzxgO8yTGVdG5kQ0Y-99M-bBysfyTR/page/0jS9)

**Reasons**
The current setup is composed of a performance test cluster (long-living) that spins cluster under load. The results of performance tests should be stored and easy to analyze without big infrastructure cost and maintenance effort. 

**Attachments**

- Alternative performance test approach: https://youtu.be/1OYAGp26YEs
- Issues with the current setup: 
    - https://github.com/kyma-project/kyma/issues/4136
    - https://github.com/kyma-project/kyma/issues/6535

**Comment by kasiakepka** [comment]
This issue is tracked here https://github.com/kyma-project/test-infra/issues/2021
