### ISSUE TITLE
Upgrade istio to 1.4.3

### ISSUE THREAD

**Issue by sayanh** [kyma-project/kyma#7009]
**Description**

It is found that Istio Mixer creates too many watches, overloading kube-apiserver hence a cluster in GKE becomes unavailable. A reply from GCP support was this:
```
Hello Ahmed, 
We investigated this issue and the root cause is that Open Source Istio Mixer creates too many watches, overloading kube-apiserver. It led to master unavailability and eventually repairing process. 
This bug was fixed in Open Source Istio 1.4.3 [1]. So upgrading to newest version should definitely fix this issue. 
Let me know if you have some additional questions. 
Kind regards, 
Tomasz
```
More information can be found here: https://istio.io/news/releases/1.4.x/announcing-1.4.3/ 

Hence istio needs to be upgraded to 1.4.3 from 1.4.2.

**Comment by piotrmsc** [comment]
Invalid, done already in https://github.com/kyma-project/kyma/pull/6837 8 days ago
