### ISSUE TITLE
Make Function Controller an optional Kyma component

### ISSUE THREAD

**Issue by michal-hudy** [kyma-project/kyma#7016]
**Description**

Currently, the installation of a Function Controller requires multiple manual steps. As it must be integrated with Kyma so it must be possible to install it by Kyma Operator. To achieve that Function Controller chart must be added to installation CRs and be properly configured.

AC:
 - The default configuration should point to the internal Docker registry
 - All dependencies are installed - Knative Serving, Tekton, Docker
 - Support for external Docker registries (in such case internal shouldn't be installed)
 - Lambdas should work at least in one namespace (not system namespace)
 - Installation documentation updated (overrides, how to enable etc.)

Tekton:
 - As a separate namespace - `tekton-system`

Internal docker:
 - Namespace TBD
 - Available only in cluster

Stretch:
 - Ability to deploy lambadas in any namespace

**Reasons**

As Function Controller must work with Kyma it should be possible to install it together with other components.

**Attachments**

**Comment by michal-hudy** [comment]
- Tekton (newest) as a separate chart in its system namespace. 
 - In the case of docker registry decide.

**Comment by magicmatatjahu** [comment]
Tekton Pipelines by default is installed in `tekton-pipelines` namespace from official sources, so in my PR I also will install Tekton in mentioned namespace, not in `tekton-system`.
