### ISSUE TITLE
Inappropriate response to the query at URL `/director /graphql`

### ISSUE THREAD

**Issue by jasiu001** [kyma-project/kyma#7018]
**Description**
Request on URL `/director /graphql` with query:
```
query getURL ($id: ID!) {
  runtime(id: $id) {
    id
    labels(key: "runtime/console_url")
    status{
        condition
    }
  }
}
```
returns an example of the response:
```
{
    "data": {
        "runtime": {
            "id": "dcaa820d-91ef-4b8d-bcaf-3af40d4b26a9",
            "labels": {
                "runtime/console_url": "http://adamtubyl.com",
                "scenarios": [
                    "DEFAULT"
                ]
            },
            "status": {
                "condition": "INITIAL"
            }
        }
    }
}
```
**Expected results**
The response should contain one label specified in the request.

**Comment by PK85** [comment]
This ticket is invalid today. We changed labels from `/` to `_`

**Comment by pkosiec** [comment]
The issue is still valid, I could reproduce it on latest master on Compass repo:
It's valid both for Applications and Runtimes (query for single entity and multiple ones).

**Comment by pbochynski** [comment]
Can you please move the issue to Compass repository?

**Comment by PK85** [comment]
Invalid
