### ISSUE TITLE
Update cluster instruction with handling versions.env file

### ISSUE THREAD

**Issue by Tomasz-Smelcerz-SAP** [kyma-project/kyma#702]
Describe what needs to be done in order to provide versions of components as overrides (how to take values from versions.env and make them overrides for Installer)

This docu should describe how to download the file and turn it into overrides ConfigMap.

Details can be found in local-config.sh

**Comment by crabtree** [comment]
Mechanism of dynamic versioning now does not require versions.env file. Implementation details and readme merged in #978
