### ISSUE TITLE
Update Knative Eventing mesh dashboard - delivery with Kafka channel metrics

### ISSUE THREAD

**Issue by montaro** [kyma-project/kyma#7027]
**Description**

According to https://github.com/kyma-project/kyma/issues/6787, we need to add the Kafka channel metrics to the Knative Eventing mesh dashboard - delivery

**AC**
- Delivery Dashboard enabled for kafka-dispatcher**
- One Delivery Dashboard for both Natss and kafka dispatchers? 

** -> name unknown

**Comment by k15r** [comment]
will not be implemented due to removal of knative
