### ISSUE TITLE
Compass as default component in Kyma Runtime

### ISSUE THREAD

**Issue by PK85** [kyma-project/kyma#7035]
**AC**
- enable compass and compass-agent component as default modules in Kyma runtime
- take care about prow pipelines cleanup - remove `gke-compass-kyma-integration` job
- move `compass` repository to `kyma-project` preserving whole git history
- take care about adding simple tests for upgrade (release->PR) and backup/restore (release->PR) tests suites:
  
Upgrade test scenario:
- before upgrade:
   - create another tenant for the particular test purpose
  - register integration system, ask for IS credentials, create app, generate credentials for app, make a call for compass (use `viewer` query just to test auth/authz)
- after upgrade:
  - make a call for compass  (use `viewer` query just to test auth/authz) - do it as the Application and as the IS
  - do a proper cleanup
 
- create another job for commit-to-commit compass management plane upgrade (master->PR) 
   - use the same script from the upgrade release->PR; parammetrize the script for using different base other than last release
   - run on change compass, ory, istio, dex;

- what about tests for backup/restore? For now we don't consider any custom tests for that

**Comment by pkosiec** [comment]
See previous task for logs about compass upgrade: https://github.com/kyma-incubator/compass/issues/431

**Comment by pkosiec** [comment]
We have also to adjust e2e and e2e-event-mesh tests for new mapping in Service Catalog (App -> ServiceClass, Package -> ServicePlan).

**Comment by pkosiec** [comment]
After all we don't want to enable compass in Kyma by default. We need to think about other solution in other tasks.
