### ISSUE TITLE
Api-Gateway doubles Oathkeeper rules when restoring a namespace from backup

### ISSUE THREAD

**Issue by Tomasz-Smelcerz-SAP** [kyma-project/kyma#7038]
**Description**

There is a reproducible bug in Api-Gateway leads to creation of multiple Oathkeeper rules.
Because Oathkeeper does not allow for multiple rules matching a single request, this effectively disables target upstream service. Oathkeeper rejects requests with 500 error code in that case.

The Api-Gateway controller creates a Rule (`Rules/oathkeeper.ory.sh`) when the user creates an instance of ApiRule (`ApiRule/gateway.kyma-project.io`). Both CR instances are in the same namespace.
When the namespace such namespace is restored from backup, the following happens:
1) The Rule is restored. The oathkeeper-maester controller registers it in Oathkeeper database
2) The ApiRule is restored. Api-Gateway is processing the ApiRule. It creates **another** Rule with different name, but the same data as the existing Rule restored from backup.
3) The oathkeeper-maester controller is triggered after creation of another Rule and registers it in the Oathkeeper database.
4) There are two rules with different names and the same attributes in the Oathkeeper database.

**Expected result**

The Api-Gateway should not create another rule if there's an existing one.

**Actual result**

As described

**Steps to reproduce**

Create a simple ApiRule that results in creation of the Oathkeeper Rule. Backup the namespace, then restore it from backup.

**Troubleshooting**

If it happens, remove redundant rule manually.

**Comment by piotrmsc** [comment]
1. Check if we can configure oder and try to set oathkeeper rules and istio virtual services first
2. If not do not backup oathkeeper rules and  istio vs
3. Alternative handling in the code
