### ISSUE TITLE
Document how to install kyma with istio preinstalled

### ISSUE THREAD

**Issue by Disper** [kyma-project/kyma#704]
Provide a manual how to configure kyma installer to use preinstalled istio charts. The document should contain step by step procedure for cluster and minikube:
- install istio from official charts
- modify installer configuration (CRD)
- deploy installer and config maps
- start installation
- verify installation

**Comment by piotrmsc** [comment]
- Add comment about supported istio version
- Describe how to install using the release (both on a cluster and locally). If it requires changing the installer config, it should be properly explained
- Describe how to verify the installation
