### ISSUE TITLE
Kyma 1.9 release doesn't contain the migration guide 

### ISSUE THREAD

**Issue by himanshu-sv** [kyma-project/kyma#7052]
As mentioned at - https://kyma-project.io/docs/#installation-upgrade-kyma
the kyma release should contain the migration guide at https://github.com/kyma-project/kyma/tree/release-1.9/docs.
 Currently, the tiller upgrade is only mentioned in the release notes and not in the migration guide.
This can be potentially confusing to users and lead to issues.

**Comment by piotrmsc** [comment]
@himanshu-sv in https://github.com/kyma-project/kyma/pull/7100 we have added an additional note in upgrade docs to always uses tiller from release. When it comes to creating directory in 1.9 release I have talked with @kazydek and this topic will be discussed by TWs. As it's manual step not always aligned.
