### ISSUE TITLE
Application Broker calls MPS via Agent to request and delete credentials

### ISSUE THREAD

**Issue by PK85** [kyma-project/kyma#7062]
**Description**

Application Broker calls MPS via Agent to request and delete credentials for given api-package

**Reasons**

We need credentials per request for service instances of Application API.

**AC**
- extends credentials to contain a type of credentials, credentials + GATEWAY_URL. It will be up to user if he wants to go thru gateway or call application directly.
- adjust GATEWAY_URL value in connection with requirements of refactored gateway. Gateway is deployed in the same namespace where service binding was created and works with secret provided by service catalog
- do a call to agent proxy for requesting and deleting credentials requests
-

**Comment by mszostok** [comment]
**Raw diagram**
<p align="center">
  <img src="https://user-images.githubusercontent.com/17568639/73759752-acd67f80-476c-11ea-84e9-3201b6517027.png" alt="drawing" width="400px" />

</p>


**NOTES:**
- Sync with Frog team about GATEWAY_URL pattern
- Sync with Frog team about the Agent Proxy
- Sync with X-Team about the Director API graphql mutations for Auth

**Additional AC:** 
- add documentation

**Comment by mszostok** [comment]
**Question:**
Generate the Auths per instance or per binding?

**Comment by mszostok** [comment]
fetch additional info about auth like req headers etc. 

sync with @Szymongib

**Comment by mszostok** [comment]
Call to Director:

```graphql
query getPackage($appID: ID!, $pkgID: ID!) {
  application(id: $appID) {
    package(id: $pkgID) {
      instanceAuths {
        context
        auth {
          additionalHeaders # wolanie API
          additionalQueryParams
          requestAuth {
            csrf {
              tokenEndpointURL # wolanie po CSRF token
            }
          }
          credential {
            __typename
            ... on OAuthCredentialData {
              clientId
              clientSecret
              url
            }
            
            ... on BasicCredentialData {
              username
              password
            }
          }
        }
        status {
          condition
          timestamp
          message
          reason
        }
      }
    }
  }
}

```

**Comment by mszostok** [comment]
new agreement about the GATAWAY URL 

App Broker consume such env variable `GATAWAY_BASE_URL_FORMAT=http://[NAMESPACE]-some-hardcoded-name/` and then inject for lambda such env `{API_NAME}_GATEWAY_URL=<rendered_gateway_base_url>/secret/<secret_name>/api/<api_name>`
