### ISSUE TITLE
CI job to provision Kyma and Azure Event Hubs namespace 

### ISSUE THREAD

**Issue by Abd4llA** [kyma-project/kyma#7064]
**Description**

A CI job is deploying Kyma on Azure needs to provision an Azure Event Hubs namespace and configure Kyma installation correctly with:

-  Knative-kafka channel chart overrides.
- Default channel overrides.

**AC**
- There is a script to provision an Azure Event Hubs namespace and retrieve the connection string and secrets.
- `kyma-gardener-azure-integration` job provisions Kyma with Knative-Kafka channel as default channel.

**Comment by nachtmaar** [comment]
Rough idea:
- Find out how to install a custom component and use installation-override with kyma cli 
- Modify script to provision Azure EventsHubs Namespace and output installation-override
- Integrate into ci job [here](https://github.com/kyma-project/test-infra/blob/f335c0767a59990495a2f0be7f4273b844cf8c1c/prow/scripts/cluster-integration/kyma-gardener-integration.sh#L136)

**Comment by sayanh** [comment]
Blocked by: https://github.com/kyma-incubator/terraform-provider-gardener/issues/34
