### ISSUE TITLE
Eventing performance test spike

### ISSUE THREAD

**Issue by Abd4llA** [kyma-project/kyma#7067]
**Description**

Run eventing performance tests inside Kyma for testing latency and throughput end to end using our gatling tests. Tests should run with internal subscriber. 

Timebox: 1 Day

**AC**
- There is a documentation of how to run the performance tests.
- Evaluate if Gatling is the right solution for our bigger performance issue

**Comment by montaro** [comment]
# To run the performance test you basically need to:

- Clone the `c4f-konduit-core` in your GOPATH
- `git clone git@github.wdf.sap.corp:cx/c4f-konduit-core.git`
- run `.../c4f-konduit-core/hack/connect-to-cluster.sh`
- Choose the cluster you wanna connect to
- Clone the `c4f-konduit-tools` in your GOPATH
- `git clone git@github.wdf.sap.corp:cx/c4f-konduit-tools.git`
- Build the test image
- `cd .../c4f-konduit-tools/benchmarking`
- `make docker-build`
- Push the docker image to your docker hub
- `docker tag konduit.docker.repositories.sap.ondemand.com/com.sap.c4konduit/benchmarking:latest montaro/benchmarking:latest`
- `docker push montaro/benchmarking:latest`
- Change the image value in `benchmarking/config/helm/benchmark-kyma-gatling/values.yaml`
to be like:
`dockerRepositoryUrl: montaro`
- Install Kyma with your own domain
- Create a new `benchmark` namespace
- `Kyma --> Namespaces --> +New Namespace`
- Create new `konduit-benchmark-app` application
- `Kyma --> Integration --> Applications --> +Create Application`
- Install the [one-click-integration-script](https://github.com/janmedrek/one-click-integration-script)
- Get application token
- `Kyma --> Integration --> Applications --> konduit-benchmark-app --> Connect Application --> Copy to Clipboard`
- `one-click-integration.sh -u <token>`
- for convenience, move the pem file to the events directory
- `mv generated.pem .../c4f-konduit-tools/benchmarking/src/events/konduit-benchmark-app.pem`
- Register events with Kyma event catalog (replace KYMA_DOMAIN with the kyma cluster domain)
- `cd .../c4f-konduit-tools/benchmarking/src/events`
- ```curl -X POST -H "Content-Type: application/json" -d @./konduit-benchmark-app-events.json https://gateway.[KYMA_DOMAIN]:443/konduit-benchmark-app/v1/metadata/services --cert konduit-benchmark-app.pem -k -v```
- Publish Java Keystore Secret to Kubernetes
- `cd .../c4f-konduit-tools/benchmarking/scripts`
- `./refresh-java-keystore.sh`
- Run the test
- `./run-benchmark-kyma.sh -g CLUSTER-NAME -k CLUSTER-NAME -t 60 -s medium -d`
- Watch the output to get the path to the Gatling report website
- Enjoy!

**Comment by montaro** [comment]
![image](https://user-images.githubusercontent.com/531945/81459069-42cfdb00-919e-11ea-9eca-b5a3fa45b64a.png)
![image](https://user-images.githubusercontent.com/531945/81459074-482d2580-919e-11ea-88d1-a5cc25be3e05.png)
![image](https://user-images.githubusercontent.com/531945/81459079-4ebb9d00-919e-11ea-87ce-9777ddbd048b.png)

**Comment by nachtmaar** [comment]
@montaro Can you paste the e2e delay time here as well?

**Comment by montaro** [comment]
The lambda logs for running the performance tests show a linear increase in the event E2E duration
8 users & lambda XS:
Starting from Duration: `735ms`
Ends with `46524ms`

16 users & lambda XS:
Start: `1986ms`
End Duration: `50843ms`

8 users & lambda Size M
Start: Duration: `839ms`
End: Duration: `54677ms`
