### ISSUE TITLE
Move authorization proxy to kyma components

### ISSUE THREAD

**Issue by pbochynski** [kyma-project/kyma#707]
**Description**
Apiserver related changes were rejected by code owners of kube rbac proxy project (https://github.com/brancz/kube-rbac-proxy).
Therefore we have to move the code to kyma components.

**TODO**
- ensure the minimal requirements are fulfilled (pipeline, tests, etc)
- update authorization proxy proposal to enable selective authorization (avoid double authorization for calls to apiserver)
- mention in the documentation that the code is based on open source project

**Comment by piotrmsc** [comment]
Status update : Docu PR created, PR with dynamic versioning created
