### ISSUE TITLE
Refactor Event Service to forward events to HttpSourceAdapter

### ISSUE THREAD

**Issue by Abd4llA** [kyma-project/kyma#7091]
**Description**

In Kyma 1.11 Knative Eventing mesh is going to be the default event routing infrastructure which introduces `/events` endpoint and only supports CloudEvents 1.0. To keep supporting external applications that uses `/v1` endpoint, Event Service needs to keep serving the endpoint with legacy protocol and forward CloudEvents 1.0 to the Knative Eventing mesh.

**AC**
- Kyma serves both `/events` and `/v1/events` endpoints only through Knative Eventing mesh.

**Comment by marcobebway** [comment]
@Abd4llA, What about the `/v2/events` endpoint? I suggest that we retire it and return **301** with a redirect location to the application's HTTP adapter endpoint, what do you think?

**Comment by Abd4llA** [comment]
Yes that's a good solution.
