### ISSUE TITLE
[TIMEBOXED] Upgrade to Knative Eventing 0.12.0

### ISSUE THREAD

**Issue by Abd4llA** [kyma-project/kyma#7092]
** Description ** 
Upgrade Knative Eventing in Kyma to 0.12 and figure out if there are upgrade problems and further work needs to be done. Validate that Knative-Kafka channel is also working with 0.12 or create further issues for needed work.

Timebox: 3 days

** AC **
- Either Knative Eventing mesh is upgraded to 0.12.
- OR there are issues for further needed work .

**Comment by sayanh** [comment]
@antoineco Did we validate knative-kafka(with `latest` tagged images) works with Knative-eventing 0.12 charts? Point 2 in this [comment](https://github.com/kyma-project/kyma/pull/7260#pullrequestreview-363988708). Unfortunately, right now, there is no CI job which checks this.
