### ISSUE TITLE
Cloud Provider - Kyma Runtime queries

### ISSUE THREAD

**Issue by GITHENR** [kyma-project/kyma#7097]
Hello All,

We have decided to go with Azure cloud for extension development using Kyma. However our cloud provider is having below queries. Can someone help me to address these.

•	VM instance type and OS (whether Windows or free Linux) and number of VMs
•	Storage type (standard HDD or SSD or premium SSD)
•	Number of disks and disk size per VM
•	Disk type (managed or unmanaged disks)
•	Data transfer (Outbound from Azure DC)
•	Any other resources or used which is a paid one (such as container, DB, Web Apps, server less computing, functions, etc.) along with the details

**Comment by jakkab** [comment]
Hello @GITHENR, thank you for your question! As far as Azure is concerned, we support installation on AKS. Take a look at the official [documentation](https://kyma-project.io/docs/#installation-install-kyma-on-a-cluster) for further reference.
