### ISSUE TITLE
Backup for gardener on azure

### ISSUE THREAD

**Issue by a-thaler** [kyma-project/kyma#7102]
**Description**
Verify if backup and restore is working on a azure based gardener cluster.

Actions:
- Figure out the appropriate backup configuration (based on velero azure plugin?)
- Do an e2e test
- Document configuration on public kyma docu

**Reasons**
Gardener on Azure is a cluster setup supported by kyma, so backup/restore must work

**Attachments**

**Comment by suleymanakbas91** [comment]
Backup on Gardener Azure works as same as backup on AKS.
