### ISSUE TITLE
Limit PromQL query execution and optimize kyma queries

### ISSUE THREAD

**Issue by a-thaler** [kyma-project/kyma#7105]
**Description**
Queries which will take long are usually incorporating many timeseries and are loading a lot of data into memory. That's why they take long. That kind of queries will affect the memory footpront of prometheus and can cause instabilities.

We should limit the amount of time a query can take, furthermore the concurrency of queries must be limited to a fixed number.

Actions:
- optimize current settings on query timeout and concurrent queries
- introduce a proper maxSampling setting
- check our queries for complex ones and either improve or maybe drop them

**Reasons**
The memory footprint is too big for the value we gain out of it and without limits the memory can increase uncontrolled.

**Attachments**

**Comment by hisarbalik** [comment]
Query timeout and concurrent queries already configured, to configure maxSampling with a reliable value first we have to reduce amount of time-series collected with prometheus, which handled in the ticket #7036

**Comment by a-thaler** [comment]
SystemPodNotRunning alert rule got improved
