### ISSUE TITLE
Connection error when connecting instantly after client certificate generation

### ISSUE THREAD

**Issue by a-thaler** [kyma-project/kyma#7110]
**Description**
When doing the pairing process with a kyma runtime at some point you as the connecting application will [receive the client certificate](https://kyma-project.io/docs/components/application-connector/#tutorials-get-the-client-certificate-generate-a-csr-and-send-it-to-kyma). The following steps you should [query the info endpoint](https://kyma-project.io/docs/components/application-connector/#tutorials-get-the-client-certificate-call-the-metadata-endpoint) already using that certificate.
When you have a slow behaving cluster it seems that the certificate details might be not in place yet on server side for doing that call and you will receive either:

`Error: write EPROTO 139889540537192:error:14094415:SSL routines:ssl3_read_bytes:sslv3 alert certificate expired:../deps/openssl/openssl/ssl/record/rec_layer_s3.c:1536:SSL alert number 45`

or

`Error: Socket hang up`

That kind of exceptions are really misleading and it took me ages till I realized that I need to wait (actually I'm just re-trying till it succeeds).

Please check that situation and assure that at least a reasonable response gets returned indicating a status code and message.

Environment:
- Kyma 1.8
- Gardener on Azure
- Machine Type: Standard_A4_v2

**Expected result**
An error response indicating the problem, not a network exception

**Actual result**

A socket exception/SSL exception providing no details on the actual problem and is even providing an irritating message

**Steps to reproduce**
Have a Gardener on Azure cluster with Kyma installed. Deploy the SAP Commerce Cloud Mock from that addons: `github.com/sap/xf-addons//addons/index.yaml?ref=latest`

Connect it to the cluster and check the logs of the mock, you should encounter a line like:
```
info: [request-promise-retry] Encountered error Error: write EPROTO 140157565414248:error:14094415:SSL routines:ssl3_read_bytes:sslv3 alert certificate expired:../deps/openssl/openssl/ssl/record/rec_layer_s3.c:1536:SSL alert number 45
 for GET request to https://gateway.kyma.icke.berlin.shoot.canary.k8s-hana.ondemand.com/v1/applications/management/info, retry count 5
```

The connection will be established successful as the mock is doing retries now, still it will print the exception as info log.

The mock is retrying a maximum of 5 times with a delay of 1 second. I saw 2 retries maximum for now.

**Troubleshooting**
Just wait and re-try.

**Comment by janmedrek** [comment]
Hey @a-thaler, the `Standard_A4_v2` nodes have half of the memory of the ones mentioned in the [official docs](https://kyma-project.io/docs/#installation-install-kyma-on-a-cluster).

I am worried there is no clear way for us to handle this error in our components as it's only tied to resources available in the cluster. This can also be connected with Istio not propagating changes quickly enough but that's just a wild guess.

Please feel free to reopen this issue if you encounter such an error again.

**Comment by rufreakde** [comment]
We encountered this issue as well today.
