### ISSUE TITLE
Some Grafana panels not working 

### ISSUE THREAD

**Issue by suleymanakbas91** [kyma-project/kyma#7116]
**Description**

Some of the Grafana dashboard panels are errored with `query processing would load too many samples into memory in query execution`.

![Screenshot 2020-02-05 at 10 24 32](https://user-images.githubusercontent.com/5543238/73830455-0094a780-4805-11ea-8770-3c5bb2042139.png)

**Comment by a-thaler** [comment]
Looks like we configured a too restrictive limit on the amount of maximum of loaded samples. We removed the limit for now and must re-evaluate a better value.
