### ISSUE TITLE
Creating an API via compass is missing various authentication schemes

### ISSUE THREAD

**Issue by abbi-gaurav** [kyma-project/kyma#7139]
**Description**
Only supported are following

![Screenshot 2020-02-05 at 14 23 39](https://user-images.githubusercontent.com/4436741/73950099-a62a4280-48fb-11ea-9745-45b167f3b117.png)

### Missing
* ~Basic Authentication~ done
* Customer Headers such as `api-keys`

**Comment by abbi-gaurav** [comment]
@natasab, could you please help in getting this prioritise as it is being requested by one of the customers.

**Comment by kwiatekus** [comment]
Hi @abbi-gaurav.

This ticket was iceboxed for a while as new APi packaging structure was investigated by compass team.

Together with compass team, we are completely redesigning the way how APIs are defined.
APIs will be defined in packages and default credentials will be defined per package.
We do it to enable integration scenarios with complex  integration systems.

At the moment, api packages are already supported in compass API. Our main focus currently is to enable the new new structure in the UI

We will include Basic Authentication in the new structure.
Custom headers would work only when going along with OAuth or Basic. It is not supported by compass API as authentication method on its own:
https://github.com/kyma-incubator/compass/blob/master/components/director/pkg/graphql/schema.graphql#L192

**Comment by abbi-gaurav** [comment]
Hi @kwiatekus,
many customers use systems (both SAP and non-SAP) that are authenticated only by custom headers (e.g. api-keys). It would break all such integrations if custom headers by itself are not supported.

**Comment by kwiatekus** [comment]
Compass UI supports now Oauth and Basic.
@PK85 Is it possible to support custom headers authorisation for API packages?

**Comment by kwiatekus** [comment]
Compass UI will extracted from console repo and maintained by new codeowners

**Comment by pbochynski** [comment]
Please create the ticket in the compass repository.
