### ISSUE TITLE
Evaluate tracing for the event delivery flow coming through the EventService compatibility layer

### ISSUE THREAD

**Issue by marcobebway** [kyma-project/kyma#7189]
The EventService compatibility layer was updated to forward events coming through the `/v1/events` gateway to the Application's HTTP adapter.

For the time being the tracing is not working as expected for the event delivery flow through the EventService compatibility layer from Gateway / EventService [the source] to Subscriber [the sink]

AC:
- Evaluation of the tracing is done and as an output of that the necessary tickets are created.

**Comment by k15r** [comment]
#8288
