### ISSUE TITLE
Kyma upgrade fails on tiller-certs-job image upgrade

### ISSUE THREAD

**Issue by colunira** [kyma-project/kyma#7196]
**Description**
We need to upgrade the Alpine image of tiller-certs-job in tiller.yaml, but the field image is immutable in jobs and the job isn't deleted upon completion, so upgrade of Kyma fails.

**Expected result**
- tiller-certs-job runs on Alpine 3.10 after Kyma upgrade

**Actual result**
- Kyma upgrade cannot be performed

**Steps to reproduce**
Try to upgrade Kyma with tiller-certs-job with new image

**Comment by colunira** [comment]
Same happens for `helm-certs-job` in `installer.yaml`

**Comment by Tomasz-Smelcerz-SAP** [comment]
Installation jobs for tiller-secret and helm-secret was changed to init-containers in tiller and installer pods. The logic was updated so that certs are not generated if already exist - this is necessary for upgrade scenarios. Alpine images used in init-containers were upgraded.
