### ISSUE TITLE
Tracing over unencrypted channels

### ISSUE THREAD

**Issue by devguyio** [kyma-project/kyma#720]
Easiness of attack: Advanced
Impact: Moderate

Multiple service and apps submit tracing data to Jaeger. Mostly this is mediated by istio. Tracing data is submitted via the zipkin protocol, over unencrypted channels.

Risk:

Attackers who have gained access to the k8s environment (or the underlying network) can eavesdrop on all tracing data. If confidential data occurs in some tracing data (e.g. from HTTP headers or URLs) attackers can eavesdrop on it. Otherwise, they can still gain information about the setup of that cluster, which may help them plan further attacks.

Suggested Mitigation:

Ideally, introduce TLS encryption for tracing data.

If that is not feasible, make sure that traces do not contain confidential data. Add respective documentation.

**Comment by clebs** [comment]
Trcing is not using TLS at the moment, reopening the issue.

**Comment by sergio-oss** [comment]
@Abd4llA still applicable ? do traces contain personal data ?

**Comment by suleymanakbas91** [comment]
We went through all the traces on an end-to-end scenario and couldn't find any confidential information in the traces.

**Comment by suleymanakbas91** [comment]
We also added a warning to the documentation not to send any sensitive information on the traces: https://github.com/kyma-project/kyma/commit/4290c39541367f2e74627b4cbe529f7e431d3fc3.
