### ISSUE TITLE
Change minikube bootstrapper from localkube to kubeadm

### ISSUE THREAD

**Issue by Abd4llA** [kyma-project/kyma#721]
Kyma for minikube currently makes use of localkube boostrapper. Localkube boostrapper has been deprecated and will be removed in future minikube release (see [PR #2911](https://github.com/kubernetes/minikube/pull/2911) ). Users are supposed to migrate to kubeadm as bootstrapper.
This issue tracks Kyma for minikube migration from localkube to kubeadm boostrapper.

**Comment by Abd4llA** [comment]
Comment from @sslavic 

> One approach I tried was to put certs in ~/.minikube/files/var/lib/localkube/certs/, expecting they would get copied on the VM on path /var/lib/localkube/certs/ which is accessible to api server Docker container running in VM. This trick worked on Mac, but fails on Windows because files do not get copied consistently as expected (even when same vm driver is used) to root but instead end up nested to /home/docker directory, and also directory structure gets flattened [see minikube#2768](https://github.com/kubernetes/minikube/issues/2768#issuecomment-408834883)
> 
> Alternative ideas how to proceed:
> 
>   -  fix the problematic bug/inconsistency in minikube [minikube#2768](https://github.com/kubernetes/minikube/issues/2768#issuecomment-408834883)
>    - for Windows (or other OS too) run minikube in Docker
>    - evaluate using Docker for Mac and Docker for Windows, as replacement for minikube
>    - drop Windows support
>    - drop problematic features (dex) for local/minikube setup
>       -  extreme case being to drop local platform startup mode completely
>

**Comment by Abd4llA** [comment]
Comment from @sslavic 

> Consulted with @pbochynski on how to proceed. He's driving a proposal for new Kyma authorization design which would remove OIDC configuration and make it easier to switch minikube to kubeadm. If proposal goes through, then this issue to move minikube from localkube to kubeadm might become just subtask or follow up task to removing OIDC configuration.

**Comment by abbi-gaurav** [comment]
This issue is still valid. Hence reopening

**Comment by Disper** [comment]
It's no longer actual https://github.com/kyma-project/kyma/blob/master/installation/scripts/minikube.sh#L217
