### ISSUE TITLE
Adjust App Registry acceptance tests for Connectivity Adapter

### ISSUE THREAD

**Issue by pkosiec** [kyma-project/kyma#7229]
**Description**
- Reuse application registry and app connector acceptance tests, which test various cases
- Sync with corresponding team about reusing logic from App Connector acceptance tests

**Comment by kjaksik** [comment]
App registry tests cover cases that check if kubernetes resources are created and if we can access the endpoints provided by the api. We can skip the resource part and focus on [these](https://github.com/kyma-project/kyma/tree/master/tests/application-registry-tests/test/apitests) tests

**Comment by PK85** [comment]
Application connectivity will change soon to use System Broker without CR in the Runtime. Closing.
