### ISSUE TITLE
Refactor remote environment source functionality

### ISSUE THREAD

**Issue by PK85** [kyma-project/kyma#723]
AC:
- Rename api.groups of RemoteEnvironment, EnvironmentMapping and EventActivation
  - Adjust domain of **remoteenvironments.applicationconnector.kyma-project.io**
  - Adjust domain of **eventactivations.applicationconnector.kyma-project.io**
  - Adjust domain of **environmentmappings.applicationconnector.kyma-project.io**
    - group name is adjusted in the CRD
    - all usage is adjusted
    - documentation and examples are adjusted
- RE changes:
  - Remove source attribute. Use *RemoteEnvironment name* for EventActivation creation as **sourceId** field
  - Add **name** and **description** attribute per service
- add per every service ability to provide labels and put them into *serviceClass metadata* (related issue, see: https://github.com/kyma-project/console/issues/127). They will be displayed via ui-api-layer by convention, just three fields will be displayed.
```
labels:
        //helmbroker case
        showcase: true
        //helmbroker case
        local: true
        //RE case
        connected-app: ec-prod
```
- documentation and examples are adjusted

**Comment by PK85** [comment]
We will do one PR for all components changes, continue work with https://github.com/kyma-project/kyma/pull/715

**Comment by mszostok** [comment]
- [ ] REB client and business logic update @mszostok
- [ ] REB acceptance test and example update @piotrmiskiewicz 
- [ ] UI-API-Layer update
- [ ] REB documentation update
