### ISSUE TITLE
Create EDP client

### ISSUE THREAD

**Issue by jasiu001** [kyma-project/kyma#7231]
*AC*
- create a client to communicate between KEB and EDP with all necessary methods to create customer account
- create clients tests

**Comment by klaudiagrz** [comment]
Waiting for the Framefrog team to deliver the `dataStream` schema, which will be sent to EDP.

**Comment by jasiu001** [comment]
Waiting for Andre Russ to deliver the dataStream schema, which will be sent to EDP.

**Comment by PK85** [comment]
Invalid.  Close.
