### ISSUE TITLE
Knative Eventing mesh migration guide

### ISSUE THREAD

**Issue by Abd4llA** [kyma-project/kyma#7236]
**Description**

We need a migration guide for Kyma 1.11 that describes:

1. General overview of the upgrade logic (Application having HttpSource, Legacy EventService, Triggers, etc)
1. Troubleshooting guide of (application-connector, event-bus, etc)
1. How to validate if the upgrade was successful. 

**AC**

1. Kyma 1.11 release notes includes above mentioned migration guide.

**Comment by bszwarc** [comment]
The migration guide should be added under docs/migration-guides/1.10-1.11.md 
Is the troubleshooting guide valid only for the migration guide or applicable in general? If in general, we should have a regular troubleshooting guide.

**Comment by anishj0shi** [comment]
https://github.com/kyma-project/kyma/pull/7570#discussion_r392711125
