### ISSUE TITLE
Integrate Knative Event Registry in Kyma

### ISSUE THREAD

**Issue by hudymi** [kyma-project/kyma#7254]
**Description**

With a full migration to Knative Eventing, we should also change the way how events are registered in Kyma. Currently, AsyncAPI schema is stored in MinIO during the creation of Service Class that represents Application. That schema is later parsed by UI and displayed for Service Class/Instance. For that moment everything looks good.

The problem starts when the user would like to subscribe to a particular event, he needs to know what Events are available in a namespace. The current solution is looking for an `EventActivation` CR and pulls proper AsyncAPI spec from MinIO. Such an approach is implemented in CBS, requires special logic and unnecessary calls MinIO, mapping Service Instance to Service Class, etc. Also, it is not possible to list all available events in the namespace with `kubectl`.

Solution for that would be replacing `EventActivation` CR with `EventType` CR from Knative that contains name of the event and its schema. `EventType` contains also the name of the broker, so it will be possible to use multiple brokers instead of hardcoded `default`.

I would propose such flow:

1. When a Service Class with events is registered in Kyma, its AsyncAPI schema is stored in MinIO (like in current solution)
2. When a Service Instance is created, the `EventType` resource is created that contains:
   - name of the event
   - description (used in UI for example)
   - source
   - name of the broker
   - schema of the event
   - `metadata.ownerReferences` that points to the Service Instance
3. If `EventType` already exists, then the `metadata.ownerReferences` should be updated.

Thanks to that, MinIO is only used for storing the whole AsyncAPI schema as a reference that is later used by Application Broker for the creation of `EventType` CRs. `metadata.ownerReferences` is used by Garbage Collector, for removing `EventTypes` that are not associated with Service Instances.

**Reasons**

 - Pure Knative solution
 - Ability to list available events in the namespace with `kubectl`
 - No Kyma specific CR like `EventActivation`
 - Less logic in CBS
 - Less calls to MinIO
 - Better user experience
 - No hardcoded broker in Lambdas
 - Ability to use multiple brokers in namespace

**Attachments**

https://knative.dev/docs/eventing/event-registry/

**Comment by anishj0shi** [comment]
As Eventing solution needs to be revamped. We wont be using event-registry for event-catalog.
