### ISSUE TITLE
Backup/Restore tests should cover 'external-end-to-end' scenario

### ISSUE THREAD

**Issue by k15r** [kyma-project/kyma#7277]
**Description**

Currently our backup / restore test jobs focus on individual components only. 
e.g. Event-Bus sends events only internally

Imho it would make a lot of sense to implement (or refactor) a test similar to core-external-solution:
- connect an external application to kyma
- install a lambda (or any other subscriber)
- create a trigger that routes a specific event to the subscriber
- have the subscriber communicate back to the sender (or any other connected external service)

This test should setup everything before backup/restore and verify that the external solution still works after restoration of the cluster

**Reasons**

Proof that kyma still works after disaster recovery or help us improve the documentation with steps required to really get back to a running cluster in case of an outage.

**Comment by pbochynski** [comment]
It should be tested also with upgrades.

**Comment by anishj0shi** [comment]
> It should be tested also with upgrades.
Upgrade scenario will be addressed by : https://github.com/kyma-project/kyma/issues/7512

**Comment by anishj0shi** [comment]
Move to Sprint_15

**Comment by anishj0shi** [comment]
This can't be implemented in the foreseeable future. Hence Closing this issue. However upgrade test covering core-test-external-solution is in progres. more information can be tracked on issue #7512
