### ISSUE TITLE
Oathkeeper occasionally returns 503 status code

### ISSUE THREAD

**Issue by pkosiec** [kyma-project/kyma#7295]
**Description**

During CI/CD pipelines, sometimes all tests that call Director via Oathkeeper fail. We use hydrator, which also calls Director, and Director logs don't contain anything related to the requests, which means it's not a problem of the deployment itself.  
It's also worth noting that we wait for Director to be ready before running the tests, so we're confident Director is up and running.

Example logs:
https://storage.googleapis.com/kyma-prow-logs/logs/post-master-compass-integration/1230460144895135744/build-log.txt

The issue started to occur recently. The [Oathkeeper upgrade](https://github.com/kyma-project/kyma/commit/d9a987696cb99db9fe99dce153da554d62270b4e#diff-230c1c399c9b2212fff57135273fc774) might be a possible reason.

**Comment by pkosiec** [comment]
I've edited the issue because I'm not sure if the logs provided by @Szymongib are about the same issue. There is 401 error included, while we observed 503 status code.

```
time="2020-02-19T10:37:04Z" level=error msg="An error occurred while handling a request" code=401 debug= details="map[]" error="The request could not be authorized" reason= request-id=31d44fb9-f86f-400c-b06f-eb4af2b35a75 status=401 trace="Stack trace: \ngithub.com/ory/oathkeeper/proxy.(*RequestHandler).HandleRequest\n\t/home/circleci/project/proxy/request_handler.go:241\ngithub.com/ory/oathkeeper/proxy.(*Proxy).Director\n\t/home/circleci/project/proxy/proxy.go:134\nnet/http/httputil.(*ReverseProxy).ServeHTTP\n\t/usr/local/go/src/net/http/httputil/reverseproxy.go:206\ngithub.com/urfave/negroni.Wrap.func1\n\t/go/pkg/mod/github.com/urfave/negroni@v1.0.0/negroni.go:46\ngithub.com/urfave/negroni.HandlerFunc.ServeHTTP\n\t/go/pkg/mod/github.com/urfave/negroni@v1.0.0/negroni.go:29\ngithub.com/urfave/negroni.middleware.ServeHTTP\n\t/go/pkg/mod/github.com/urfave/negroni@v1.0.0/negroni.go:38\ngithub.com/ory/x/reqlog.(*Middleware).ServeHTTP\n\t/go/pkg/mod/github.com/ory/x@v0.0.91/reqlog/middleware.go:140\ngithub.com/urfave/negroni.middleware.ServeHTTP\n\t/go/pkg/mod/github.com/urfave/negroni@v1.0.0/negroni.go:38\ngithub.com/ory/x/metricsx.(*Service).ServeHTTP\n\t/go/pkg/mod/github.com/ory/x@v0.0.91/metricsx/middleware.go:261\ngithub.com/urfave/negroni.middleware.ServeHTTP\n\t/go/pkg/mod/github.com/urfave/negroni@v1.0.0/negroni.go:38\ngithub.com/urfave/negroni.(*Negroni).ServeHTTP\n\t/go/pkg/mod/github.com/urfave/negroni@v1.0.0/negroni.go:96\nnet/http.serverHandler.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2802\nnet/http.(*conn).serve\n\t/usr/local/go/src/net/http/server.go:1890\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1357" writer=JSON
```

**Comment by piotrmsc** [comment]
@pkosiec do you still have this problem? I remember we were checking a similar issue that was happening due to installer constantly re-trying installation/upgrade.

**Comment by pkosiec** [comment]
@piotrmsc yes, this is a different issue. However, I will close this issue for now, as we don't have more details about it - we need to gather more traces what's wrong. It turned out that logs that @Szymongib provided are related to the issue we were checking.

We need to check when the issue occurs. The truth is that while running integration tests, we do wait for Director to be ready, but not for OathKeeper, which can cause 503 status codes. We will handle it on our side, and then we can come back to you with more details, if the issue is still valid.
