### ISSUE TITLE
Cannot customize configuration for Prometheus

### ISSUE THREAD

**Issue by Sallyan** [kyma-project/kyma#7304]
**Kyma Version: 1.8**
**Issue description:** 
we have Prometheus Blackbox-exporter installed for website monitoring, and it needs to edit the prometheus config to appending kind of following configuration. 
  - job_name: 'blackbox'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
        - http://localhost:8080
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: localhost:9115

Prometheus stack in kyma is using separate config. 
      --config.file=/etc/prometheus/config_out/prometheus.env.yaml
And the prometheus file is stored in secret, i cannot find the resource spec here, https://github.com/kyma-project/kyma/tree/master/resources/monitoring/templates/prometheus
**Tried solution:** 
1. as cannot know how the secret is created, try to delete the secret and create new one with my required configuration. 
Result: prometheus secret will be created new one with default config after deletion 
2. Overrides for kyma-installation
the prometheus config append content is kind of list. it is not easy to be added by overrides configmap.

**Comment by a-thaler** [comment]
Hi @Sallyan , we are using the prometheus-operator chart for the monitoring stack. So the simplest will be to bundle a ServiceMonitor resource together with blackbox-exporter, then there is no need to touch the config at all. See also our [tutorial](https://kyma-project.io/docs/components/monitoring/#tutorials-observe-application-metrics).
Will close the ticket for now. Let me know if you think the answer will not solve your problem.
