### ISSUE TITLE
Redesign graphql contract for ServiceBindingUsage CR in CBS

### ISSUE THREAD

**Issue by magicmatatjahu** [kyma-project/kyma#7307]
**Description**

At the moment we have contract for ServiceBindingUsage CR like this:

```graphql
serviceBindingUsage(name: String!, namespace: String!): ServiceBindingUsage @HasAccess(attributes: {resource: "servicebindingusages", verb: "get", apiGroup: "servicecatalog.kyma-project.io", apiVersion: "v1alpha1", namespaceArg: "namespace", nameArg: "name"})
```

Developer cannot fetch ServiceBindingUsages related to namespace or related only to some kind of resource (option with name will be the best) - there is no query for ServiceBindingUsages resources in namespace! So my proposition is create query something like this (with type `ServiceBindingUsagesQueryOptions`)

```graphql
serviceBindingUsages(namespace: String!, options: ServiceBindingUsagesQueryOptions)

type ServiceBindingUsagesQueryOptions {
  resourceRef {
    kind
    name
  }
}
```

to fetch all ServiceBindingUsages related to kind and name of resource.

Also subscriptions must have form:

```graphql
serviceBindingUsageEvent(namespace: String!, options: ServiceBindingUsageEventOptions)

type ServiceBindingUsageEventOptions {
  resourceRef {
    kind
    name
  }
}
```

to connect only for events of bindingUsages bound to appropriate resource.

**Reasons**

For having easier connection with Kyma console.

**Comment by kwiatekus** [comment]
This was resolved within https://github.com/kyma-project/kyma/pull/8001
