### ISSUE TITLE
Fluent-Bit collector doesn't work after loki disabled

### ISSUE THREAD

**Issue by hisarbalik** [kyma-project/kyma#7323]
**Description**

Log management loki is optional, after disabling loki installation for deployment log collector fluent-bit doesn't work any more because of no other output for fluent-bit available except loki. 

**Expected result**
Fluent-bit should start up and run without loki deployment.

**Actual result**

Fluent-bit in constant crash-loop without loki because of missing output configuration.

https://github.com/kyma-incubator/compass/pull/869

**Comment by a-thaler** [comment]
There must be at least one output for fluent-bit defined, if not you could just not deploy the chart
