### ISSUE TITLE
Enable Functions in all namespaces

### ISSUE THREAD

**Issue by michal-hudy** [kyma-project/kyma#7364]
**Description**

In general, it must be possible to deploy lambda in every namespace. Currently, it is not possible, as Docker credentials and runtimes definitions are not passed to namespaces.

Secrets:
 - Every namespace should have secrets to Docker Repository (without system)
 - Changes on source secret (that one in kyma-system) should be propagated to all namespaces
 - Recreate secret if someone removes is accidentally

Runtimes:
 - In general there are two options:
   - Same as secretes - pass to all namespaces
   - Download it from `kyma-system` during build phase - create a step?
 - Choose the simplest one 😄 

 - remove hardcoded namespace from Function Controller Chart

**Reasons**

Enable lambdas in all namespaces

**Attachments**

**Comment by aerfio** [comment]
Please check that the secret/cm/sa are propagated correctly after upgrade, and that new login/password pair is generated (if not, then we'll have to look back at #7390)

**Comment by michal-hudy** [comment]
I have noticed that the `ServiceAccount` and `Secret` with certs for accessing Kubernetes API is also copied. It shouldn't be. It should be only in `kyma-system` namespace.

To namespaces, we should only copy the secrets needed for Docker Registry, and access to Docker Registry should be on a separate `ServiceAccount` - even in `kyma-system` namespace.

**Comment by michal-hudy** [comment]
Also, I would recommend the generation of secret names in namespaces, instead of hardcoded names.

**Comment by michal-hudy** [comment]
Ok, checked. This secret with certs is generated during creation of SA.
