### ISSUE TITLE
Single /v1/events handler per cluster

### ISSUE THREAD

**Issue by pbochynski** [kyma-project/kyma#7366]
**Description**
All the incoming events should be handled by one instance of  event service deployed in kyma-integration namespace. The event URL returned to the application should be constructed this way:
```
event-service/{app-name}/v1/events
```

**Reasons**
The application operator creates a new instance of event service for each application. All instances are deployed in kyma-integration namespace and their only function is forwarding events from incoming HTTP requests to event bus / event mesh. The only difference is the name of the service (app name prefix) and source parameter (which is the app name). But event source (app name) can be extracted from the first path parameter, as the URL is constructed as:
```
{app-name}-event-service/{app-name}/v1/events
```
The only reason I can find to keep multiple event-service instances existed a long time ago when client certificates used for accessing event service were validated by Nginx component per application. But this argument is not valid anymore. 

One instance of event-service will make the solution much simpler and lightweight. 

**Attachments**

**Comment by anishj0shi** [comment]
The Event Service Compatibility layer was designed to support applications which are already paired to kyma-eventing at /{app-name}/v1/events

At the time of evaluation we observed that the event-service was always created per application, so to ensure backward compatibility per application pairing, we decided to enhance the existing component rather then creating a new one.

Also, a minor information:
The Compatibility layer is just not a proxy which forwards the event to the new mesh, it converts the legacy event payload to a relevant cloudevent(Currently, Cloudevent v1) and then propagates it to the new eventing mesh. Plus it also supports the contractual obligation of supporting */{app-name}/v1/events/subscribed* to fetch the subscriptions created for the application's events.

/cc @pbochynski

**Comment by sayanh** [comment]
Lets, recap what event-service does,
- converts custom events to CE and sends it to event-mesh(HTTP source adaptor for the linked application)(compatibility layer)
- `/subscribed` endpoint gives back the list of subscriptions in the cluster for an application. Now sure who uses this end-point
- accepts events in custom format(v1) and sends to publish service(will be deprecated soon)

Ideally, event-service should not be needed at all if and only if the connected applications sending events follow cloud events specification. Scoping out the generic logic of event-service into one service per Kyma cluster will still be an another work-around, IMO. I see `compatibility` layer as a short-term solution to convert custom event format to CE. What do you think?

If the applications never send cloud events then this compatibility layer can be scoped into a separate service per Kyma cluster as @pbochynski said. But the question is: is this the way forward?

**Comment by anishj0shi** [comment]
@sayanh 
> accepts events in custom format(v1) and sends to publish service(will be deprecated soon)

it will not be deprecated soon, it's completely gone, now we convert the request to Cloud event and propagate it tot he application's event mesh.

> Ideally, event-service should not be needed at all 

I completely agree to this, but we have to ensure backward compatibility to already paired applications as of now, but we need to ensure if the current users are willing to make a modification in their messaging contracts, if they do, then we get rid of event-service , for good! But if not, we need to check the possibility of one event-service per kyma cluster which does the following:

- converts custom events to CE and sends it to event-mesh(HTTP source adaptor for the linked application)(compatibility layer)
- has /subscribed endpoint which gives back the list of subscriptions in the cluster for an application. Not sure who uses this end-point

**Comment by pbochynski** [comment]
@anishj0shi , @sayanh from your comments I see that the improvement with one event service instance per cluster is feasible and looks like low hanging fruit. Switching it off completely would require migrating all the clients to the CloudEvents specification. My proposal is:
- refactor the solution to use one event service for all applications
- deprecate the previous message format 
- in the future bypass event service, and forward events directly to HTTP source adapter.

**Comment by k15r** [comment]
#### Potential problems
`Autoscaling`: currently event-service is not autoscaled. With more applications using one event-service we put more load on a single instance. Autoscaling might be necessary for event-service. 

#### Configuration Update
either : reconfigure event-service for every new application (watch application crs)
or: just allow all applications (might lead to security issues)

#### Authorization Policies
with strict mode enabled we need to reconfigure istio for every new application. Might lead to event loss (trigger resend of events?)

#### Talking about low hanging fruits 
HTTP-Adapter comes to mind
it is already autoscaled using knative-serving, it is a bit dumber than event-service (it just adds some metadata to the event and forwards it)

**Comment by k15r** [comment]
The new event publishing proxy provides the functionality of the previous event service. It is implemented in a way that only one instance is needed
