### ISSUE TITLE
Switch to Serverless v2 by default

### ISSUE THREAD

**Issue by michal-hudy** [kyma-project/kyma#7367]
**Description**

As all features are going to be ready its time to remove the old solution and migrate to the new one. To make it successful few things needs to be done:
 - All function created with Kubeless solution must be migrated to new Function CR
   - Events trigger, exposure, and bindings migrated too
 - Kubeless is removed from the cluster and its CRs
 - Serverless v2 is installed by default
 - Old UI is replaced by new UI
 - Documentation updated - old Serverless removed, new `Serverless v2` renamed to `Serverless`
 - Rename `knative-service` UsageKind CR to `function` <- replace old UsageKind used by kubeless Function to new used by new Function CR

**Reasons**

Bye, bye Kubeless

**Attachments**

**Comment by aerfio** [comment]
During last step, which is uncommenting function-controller in installer-*.yaml's please consider if we really need to have pipeline on minikube, reasons explained https://github.com/kyma-project/kyma/issues/7370#issuecomment-599214403

**Comment by Disper** [comment]
Please remember about removing kubeless tests as well.

**Comment by aerfio** [comment]
Remember to sync about APIs

**Comment by michal-hudy** [comment]
TODO:
 - Migration guide
 - Enable function-controller by default (rename chart to serverless)
 - Remove old documentation (check examples)
 - Rename `knative-service` UsageKind CR to function <- replace old UsageKind used by kubeless Function to new used by new Function CR
 - Grafana (2 dashboards).....

We can enable backend without waiting for frontend :smile:
