### ISSUE TITLE
Generate password for Docker Registry during instalation

### ISSUE THREAD

**Issue by michal-hudy** [kyma-project/kyma#7369]
**Description**

Password for Docker Registry should be generated with every installation/upgrade of Docker Registry

 - Generate a password in secret (same mechanism as for MinIO)
 - Generate user for Docker registry 
 - Init container for Docker Registry that will generate proper format for Registry container

**Reasons**

Security

**Attachments**

**Comment by aerfio** [comment]
to generate htpasswd use: `docker run --entrypoint htpasswd registry:2 -Bbn user password > ./htpasswd` - taken from https://github.com/helm/charts/tree/master/stable/docker-registry (on the bottom of the README.md)
