### ISSUE TITLE
Remove ReadOnlyAPIDataVolumes=false from docs

### ISSUE THREAD

**Issue by mwieczorek** [kyma-project/kyma#737]
**Description**
Feature gate ReadOnlyAPIDataVolumes=false should be removed from docs (https://github.com/kyma-project/kyma/blame/master/docs/kyma/docs/032-gs-cluster-installation.md#L36).

**Reasons**

This feature gate won't be supported in next k8s versions.
It should be tested first if cluster installation is ok without the feature gate, and if any errors new issues for affected components should be created.

**Attachments**

**Comment by derberg** [comment]
@mwieczorek looks like invalid to me, cluster guide is removed and the GKE one doesn't need `ReadOnlyAPIDataVolumes`

**Comment by mwieczorek** [comment]
So I guess the image version was changed to new one which has a fix for that. So I'll close it.
