### ISSUE TITLE
Upgrade velero to 1.3.1

### ISSUE THREAD

**Issue by a-thaler** [kyma-project/kyma#7372]
**Description**

With latest beta version of velero the problems with CRDs should be solved finally. Please upgrade and check if problems are solved. If yes, it is worth to upgrade to the beta version even as it will improve so much the overall situation.
The problem we currently have is related to the warning here: https://kyma-project.io/docs/components/backup/#tutorial-restore-a-kyma-cluster-steps
As the restore order cannot be fixed the restore must be done in several phases, like first restoring all CRDs, then restoring istio, then the rest. And even then you might to repeat a restore phase.
The overall restore status can be "partially failed" at the end which is very misleading.

The hope is that this behaviour got improved a lot.

**Reasons**

Usability of restore

**Attachments**

**Comment by suleymanakbas91** [comment]
We can't upgrade, because exclude resources logic does not work on Velero 1.3.1. [Here](https://github.com/vmware-tanzu/velero/issues/2374) I created an issue.

**Comment by suleymanakbas91** [comment]
Not valid anymore.
