### ISSUE TITLE
Create/enhance integration job to install kyma with strictAuthMode

### ISSUE THREAD

**Issue by sayanh** [kyma-project/kyma#7374]
**Description**

With this issue https://github.com/kyma-project/kyma/issues/7240, we introduced AuthorizationPolicy for the application connector component. But this is not enabled by default. There needs to be an override set that enables strict Authorization mode. Currently, this is no integration job that does this. The goal of this issue is to create/enhance integration jobs which will install Kyma in strict auth mode and then run the test suite to make sure we are good.

**AC**
- Replication of all the existing prow jobs with enable strictAuthMode
- Mark the above jobs as optional and once they are green, modified the existing tests and removed the replicated jobs
- If they are not green, create follow up issues.

**Comment by anishj0shi** [comment]
authorization policies will be enabled by default. Issue is invalid
