### ISSUE TITLE
Reflect HttpSource status to Application

### ISSUE THREAD

**Issue by nachtmaar** [kyma-project/kyma#7378]
**Description**

With the introduction of the event-mesh, we introduced the HttpSource CR. The status of it is based on the [sink and the istio policy](https://github.com/nachtmaar/kyma/blob/bb5810fdb969035617bb0fd70f0d1d1d91bea58b/components/event-sources/reconciler/httpsource/reconcile.go#L416).
We check the readiness of the HttpSource in multiple places of Kyma:
- core-test-external-solution-event-bus
- core-test-external-solution-event-mesh
- core-test-external-solution-compass
- ... maybe more ...

These tests have in common that they all create an Application. So instead of checking the Application and the HttpSource for the ready status, we should only check the status of the Application.
That means we have to piggyback the status of the HttpSource to the Application CR.

**Reasons**
- Status of Application CR is not complete, there is only the "Deployed" status atm
- If the HttpSource is not ready, the status will still be "Deployed", but it could be that the event-mesh might not work. 

**Attachments**

**Comment by anishj0shi** [comment]
This feature can't be implemented right now, As the entire application connectivity concept is under a redesigning phase. we shall visit this, once we have a clear picture on Application connector component's features
