### ISSUE TITLE
Prometheus not correctly scrape kubelets, kube-scheduler, kube-controller-manager

### ISSUE THREAD

**Issue by Sallyan** [kyma-project/kyma#7380]
**Kyma Version: 1.8**

**Description**
serviceMonitors for kubelets, kube-scheduler, kube-controller-manager are created, but target is showing as zero. 

**Expected result**
kubelets, kube-scheduler, kube-controller-manager metrics are scraped in Prometheus and could see all targets up

**Steps to reproduce**
1. create Configmap for monitoring overrides with below data
`  kubelet.serviceMonitor.https: "true"
  kubeControllerManager.enabled: "true" 
  kubeScheduler.enabled: "true"`

For exporter-kubelet, in the values.yaml kubelet.serviceMonitor.https is set with true. But the exporter-kubelets is still using http-metrics. 
2.  list the servicemonitors
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    chart: exporter-kube-scheduler-0.1.7
    component: kube-scheduler
    heritage: Tiller
    prometheus: monitoring
    release: monitoring
  name: monitoring-exporter-kube-scheduler
  namespace: kyma-system
spec:
  endpoints:
  - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
    interval: 30s
    port: http-metrics
  jobLabel: component
  namespaceSelector:
    matchNames:
    - kube-system
  selector:
    matchLabels:
      app: exporter-kube-scheduler
      component: kube-scheduler
3. check the service label
apiVersion: v1
kind: Service
metadata:
  labels:
    app: exporter-kube-scheduler
    chart: exporter-kube-scheduler-0.1.7
    component: kube-scheduler
    heritage: Tiller
    release: monitoring
  name: monitoring-exporter-kube-scheduler
  namespace: kube-system
spec:
  clusterIP: None
  ports:
  - name: http-metrics
    port: 10251
    protocol: TCP
    targetPort: 10251
  selector:
    k8s-app: kube-scheduler
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}

The serviceMonitors are selecting the correct metric service. But the prometheus target is not showing..
And for the exporter-kubelet, how to config it use https-metrics? as according to https://github.com/kyma-project/kyma/pull/1463 , http-metric is set as default.

**Comment by a-thaler** [comment]
Hi @Sallyan ,
for now we are supporting environments where the cluster is managed (GKE, AKS, Gardener) and with that we do not use that servicemonitors in our tests.
However, we are bundling them in the kyma monitoring chart as they are part of the upstream prometheus-operator chart and we would like to offer here the same convinience.

The monitoring stack got fully revamped (see https://github.com/kyma-project/kyma/issues/6124) with Kyma 1.10. Now it is in sync with the latest prometheus-operator chart structure. The servicemonitor definitions for the mentioned components have changed a lot and are now using the helm templating a lot. Also the mention https-metrics seemed to be configurable there.
So I recommend you to try it with Kyma 1.10 and if you have similar findings let's see how we can address them.
