### ISSUE TITLE
Get Rid of pre-upgrade hook from knative-eventing chart

### ISSUE THREAD

**Issue by antoineco** [kyma-project/kyma#7387]
**Description**

In Kyma 1.10, we created a few knative-eventing CRDs manually, [via the pre-upgrade hook](https://github.com/kyma-project/kyma/blob/release-1.10/resources/knative-eventing/charts/knative-eventing/templates/pre-upgrade-job.yaml#L76). This created issues with subsequent Helm upgrades (see #7347), which we tackled by [manually removing those CRDs](https://github.com/kyma-project/kyma/blob/0b8573a92ad22154c7922795127de852a3deb6c3/resources/knative-eventing/charts/knative-eventing/templates/pre-upgrade-job.yaml#L70-L73), and letting Helm re-create them.

While this procedure works, we should ensure this manual removal gets reverted after the Kyma 1.11 release. In other words, this step won't be necessary once all CRDs are installed and managed by Helm, as they should be.

Follow up to #7386

**Related**

#7347
#7386

**AC**
- Get Rid of pre-upgrade hook for knative-eventing chart, if possible.

**Comment by radufa** [comment]
The last two commits:
https://github.com/kyma-project/kyma/pull/7843
https://github.com/kyma-project/kyma/pull/7571
are not part of Kyma 1.11 release.

If this changes will be part of Kyma 1.12, then the "pre-upgrade hook" should be removed in the next following release ( 1.13 ).

**Comment by radufa** [comment]
After a short meeting, we have decided to ignore the last two commits and remove this "pre-upgrade hook".
