### ISSUE TITLE
Remove outdate code from Application Broker after full support of API Packages

### ISSUE THREAD

**Issue by mszostok** [kyma-project/kyma#7415]
**Description**

Support for API Package was implemented on feature flag. The old implementation needs to be removed when we will switch all components to support a new way for serving Application in Kyma.

**AC:**
- remove all outdated, code and tests from Application Broker component

**Comment by mszostok** [comment]
change the name for the Event Activation in documentation
https://kyma-project.io/docs/components/application-connector#custom-resource-event-activation

**Comment by PK85** [comment]
Closing that. We will rework Application Broker soon.
