### ISSUE TITLE
Document eventing related customer security measures

### ISSUE THREAD

**Issue by Abd4llA** [kyma-project/kyma#7424]
**Description**

Kyma customers needs to be aware of some eventing related security measures that they need to be aware of when handling events in serverless functions and services.

**Comment by k15r** [comment]
i guess this is about: 
- don't put personal / business-critical information in the request, but send and id plus a callback url
- request data is never encrypted (other than tls on the)

**Comment by bszwarc** [comment]
The documentation on events is here: https://help.sap.com/viewer/DRAFT/bbd9cc125b13462ab41f6d8c4529c04b/1/en-US/935e241ca726412597175bef2add8c57.html :)

**Comment by bszwarc** [comment]
What was documented for the security part with regards to Eventing
- Personal Data in Events: https://help.sap.com/viewer/DRAFT/bbd9cc125b13462ab41f6d8c4529c04b/1/en-US/935e241ca726412597175bef2add8c57.html
- Audit Logs: https://help.sap.com/viewer/DRAFT/bbd9cc125b13462ab41f6d8c4529c04b/1/en-US/1be599b74c9042b0b0b356598502b394.html + audit log writing and retrieval.

Why it is blocked?
We still don't know if it would be possible for the customer to write entries with sensitive data to the audit log. If not, we will need to document it differently and just state how the user can retrieve the logs.
Waiting for the decision on this one.

**Comment by bszwarc** [comment]
Final documentation is here: https://help.sap.com/viewer/DRAFT/bbd9cc125b13462ab41f6d8c4529c04b/1/en-US/ee08fdfc9af8483b924e9ea9827f3ded.html

Sergio is giving it a final look :)
