### ISSUE TITLE
Enable access and audit logs for Azure Event Hubs

### ISSUE THREAD

**Issue by Abd4llA** [kyma-project/kyma#7426]
**Description**

We need to enable access and audit logs for Azure Event Hubs.

**AC**

1. Azure Event Hubs access logs are enabled
1. Azure Event Hubs audit logs are enabled
1. Documentation is updated

**Comment by anishj0shi** [comment]
We have the following measures w.r.t this issue:
- For Managed Kyma, Creation of Trigger is sent to audit logs. so we will know, who has registered a callback to an event.
- Documentation is updated mentioning, that event  data will not be logged, Hence, not to send personal data in the eventing system.
