### ISSUE TITLE
Support environment variables in Serverless v2

### ISSUE THREAD

**Issue by michal-hudy** [kyma-project/kyma#7444]
**Description**

Users should be able to define environment variables on functions. It should be possible to define it in UI and on Function CR.

Also, if env overlaps env
- injected by binding usages -> read Secrets created by ServiceBinding
- ~~injected internally by function-controller (think how to propagate hardcoded envs to console)
 it should be highlighted in UI.~~

![image](https://user-images.githubusercontent.com/26445970/75780440-a3383b80-5d5b-11ea-9d84-233d102b740f.png)

**Reasons**

Ability to inject environment variables

**Comment by magicmatatjahu** [comment]
We also have to think about injecting env variables from secret and configMap -> probably modal will be the best option for creating new (or updating old) vars.

**Comment by michal-hudy** [comment]
@magicmatatjahu yes, but not in the scope of this task

**Comment by magicmatatjahu** [comment]
> injected internally by function-controller (think how to propagate hardcoded envs to console)
> it should be highlighted in UI.

I think that storage common envs for KNative Service and under the hood for Pod of Function, we can do in configMap. We already have a graphql query for that, so this point should be easy, but firstly we must storage this envs in configMap, not have hardcoded in controller.

**Comment by michal-hudy** [comment]
@magicmatatjahu let's ignore ENV injected by function-controller for now. Currently, please focus only on SB env.






Please, stop editing my issues, use comments 😄

**Comment by michal-hudy** [comment]
TODO:
 - Describe that values from resources and fields are not supported
