### ISSUE TITLE
Refactor event-service informer

### ISSUE THREAD

**Issue by sayanh** [kyma-project/kyma#7449]
**Description**

https://github.com/kyma-project/kyma/blob/master/components/event-service/internal/events/subscribed/events.go#L45

needs to be ruled out by an informer sync timeout and the app needs to fail fast if the informers are not synced. Without the informer sync timeout, the informer sync may fail but the app will still run and will be non functional.

Reference:
https://github.com/kyma-project/kyma/blob/master/components/event-bus/internal/knative/util/kn-eventing.go#L170

**Comment by montaro** [comment]
Reference link is not available anymore

**Comment by montaro** [comment]
Reference:
```
// waitForInformersSyncOrDie blocks until all informer caches are synced, or panics after a timeout.
func waitForInformersSyncOrDie(f evinformers.SharedInformerFactory) {
	ctx, cancel := context.WithTimeout(context.Background(), informerSyncTimeout)
	defer cancel()

	err := hasSynced(ctx, f.WaitForCacheSync)
	if err != nil {
		log.Fatalf("Error waiting for caches sync: %s", err)
	}
}
```
