### ISSUE TITLE
Enfroce client authorization to NATS Streaming Server

### ISSUE THREAD

**Issue by radufa** [kyma-project/kyma#745]
## Description
 Authenticated clients (i.e. members of the istio service mesh) should be authorized to a set of actions. This includes publishing and consuming events on arbitrary topics. All other non-authorized clients must be denied.

Note: Check available authorization options in NATS Streaming.

## A/C:
* There is a functional test that verifies allowing/denying clients based on authorization rules.
* Event Bust documentation is updated to reflect the authorization changes and how to authorize clients.
* Only Publish service and Push agent should be authorized. Ideally only for what they need.

**Comment by radufa** [comment]
A NATS Streaming server and a NATS Streaming clients must share the same "cluster_id" to establish a connection.
A client using a different "cluster_id" cannot connect to NATS Streaming server.

**Comment by abbi-gaurav** [comment]
Waiting on feedback from Jester.

**Comment by abbi-gaurav** [comment]
This issue has been fixed.
