### ISSUE TITLE
Enable Application Registry and Connector Service metrics on Grafana

### ISSUE THREAD

**Issue by franpog859** [kyma-project/kyma#7478]
**Description**

Enable Application Registry and Connector Service metrics on Grafana

Take a look at [this PR](https://github.com/kyma-project/kyma/pull/7309) as there were introduced some changes to the metrics labeling

**Expected result**

There are Application Registry and Connector Service metrics on Grafana

**Actual result**

There are no Application Registry and Connector Service metrics on Grafana

**Steps to reproduce**

Provision the cluster with Kyma, go to Grafana and search for Application Registry or Connector Service metrics

**Comment by janmedrek** [comment]
Those components are deprecated and won't be further developed and supported.
