### ISSUE TITLE
Need documentation for compass mutation requestOneTimeTokenForRuntime

### ISSUE THREAD

**Issue by jcawley5** [kyma-project/kyma#7480]
Need steps documented that explain how to obtain a runtime token 

https://compass-gateway.{CLUSTER_DOMAIN}/director/graphql

mutation {
  result:   requestOneTimeTokenForRuntime(id: "RUNTIME_ID") {
    token
  }
}

**Comment by PK85** [comment]
duplicate by https://github.com/kyma-project/kyma/issues/7480
