### ISSUE TITLE
Add proper eventing audit logs when deployed on Gardener

### ISSUE THREAD

**Issue by Abd4llA** [kyma-project/kyma#7482]
**Description**

We need to make sure when Kyma is deployed on Gardener the following components are added to the K8s audit policy.

1. Any secrets used by the Knative channels

**AC**

1. Audit logs are enabled for the k8s objects above when deployed on Gardener

**Comment by anishj0shi** [comment]
As per the current Audit log policy, Any operation on Secrets and Creation of Knative Triggers will always be audited. Hence Closing this issue
