### ISSUE TITLE
Kyma installation issues on windows 10 

### ISSUE THREAD

**Issue by ektajhasapcom** [kyma-project/kyma#750]
Hi Team ,

I am trying to install kyma on my local windows machine using the command:

command:  .\cmd\run.ps1 -vm_driver virtualbox

But it is always getting stuck as below:

Configuring versions ...
Unable to connect to the server: Service Unavailable
Unable to connect to the server: Service Unavailable
apiVersion: "installer.kyma-project.io/v1alpha1"
kind: Installation
metadata:
  name: kyma-installation
  labels:
    action: install
  finalizers:
    - finalizer.installer.kyma-project.io
spec:
  version: "0.0.1"
  url: ""
  components:
    - name: "cluster-essentials"
      namespace: "kyma-system"
    - name: "istio"
      namespace: "istio-system"
    - name: "prometheus-operator"
      namespace: "kyma-system"
    - name: "provision-bundles"
    - name: "dex"
      namespace: "kyma-system"
    - name: "core"
      namespace: "kyma-system"
    - name: "remote-environments"
      namespace: "kyma-integration"
      release: "ec-default"
    - name: "remote-environments"
      namespace: "kyma-integration"
      release: "hmc-default"
Unable to connect to the server: Service Unavailable
Unable to connect to the server: Service Unavailable
Unable to connect to the server: Service Unavailable
Unable to connect to the server: Service Unavailable
tiller is not deployed - waiting 5s...
Unable to connect to the server: Service Unavailable
tiller is not deployed - waiting 5s...
Unable to connect to the server: Service Unavailable
tiller is not deployed - waiting 5s...
Unable to connect to the server: Service Unavailable
tiller is not deployed - waiting 5s...
Unable to connect to the server: Service Unavailable
tiller is not deployed - waiting 5s...
Unable to connect to the server: Service Unavailable
tiller is not deployed - waiting 5s...
Unable to connect to the server: Service Unavailable
tiller is not deployed - waiting 5s...
Unable to connect to the server: Service Unavailable
tiller is not deployed - waiting 5s...
Unable to connect to the server: Service Unavailable
tiller is not deployed - waiting 5s...

Could you please help me on this.

**Comment by crabtree** [comment]
Hi, can you try to run bare minikube using `minikube start --vm-driver=virtualbox` command. After successful start can you list for example running pods (`kubectl get po --all-namespaces`)?
