### ISSUE TITLE
Add max content length to Event Payload in publish and event-service

### ISSUE THREAD

**Issue by radufa** [kyma-project/kyma#751]
## Description
Application Connector caches full events, including their payloads, in memory before passing them through to the Event Bus' Publish service. While Event Bus enforces size constraints on events, Application Connector does not.

When processing events via HTTP API, enforce limits on payload sizes as early on as possible. E.g., if the HTTP request contains a Content-Length header check it before further processing. If the HTTP request uses chunked-content, count data (or chunks) and abort the request as soon as the limit is exceeded. Respond with an appropriate error.
Make sure the payload limit is in line with the one used defined by `publish` service.

### Hint
* Check if there is an OOB solution to enforce content length constraint for HTTP request payload.

## AC
* Event Service and Publish has a configurable max content length.
* Add default values for the local and cluster installation which are in sync with `publish` values.
* Two functional tests (content length and chunked transfer encoding) exists to verify the desired behavior.
* Update the documentation to reflect the new configuration.

**Comment by abbi-gaurav** [comment]
Moving it back to backlog to first do the refactoring.

**Comment by abbi-gaurav** [comment]
Came across this `go way` of doing it

```
r.Body = http.MaxBytesReader(w, r.Body, MaxFileSize) 
err := r.ParseForm()
if err != nil {
 // redirect or set error status code.
 return
}
```

https://stackoverflow.com/questions/28282370/is-it-advisable-to-further-limit-the-size-of-forms-when-using-golang
