### ISSUE TITLE
Documentation on how to use knative-eventing-kafka as a backbone for eventing

### ISSUE THREAD

**Issue by joek** [kyma-project/kyma#7526]
**Description**

As an kyma administrator I need some guidance how to use kafka as a eventing backbone instead of natss. Please provide some documentation how to replace the build in natss with a kafka as a service solution. 

**Reasons**

As a administrator of kyma I would like to leverage knative-eventing based on kafka in my kyma installation. This will improve the reliability and throughput of my eventing setup.

**Comment by bszwarc** [comment]
We discussed this topic with @sayanh - and it resulted in a minor change for now (regarding the installer file).
