### ISSUE TITLE
Refactor usage of test-infra/alpine-kubectl image in kyma charts

### ISSUE THREAD

**Issue by strekm** [kyma-project/kyma#7562]
**Description**

test-infra/alpine-kubectl is used widely in kyma charts. Updating its version means changes in many places resulting in huuuuge PR with a lot of reviews. It would be very nice to have it defined in one place e.g. defined as global kyma-installer override so it could be spread to all helm charts.

**Comment by pbochynski** [comment]
I think that moving image version to global overrides is against the principle we defined some time ago to put default values in charts and have slim overrides. We should work on the idea more. How it works with better modularity? Don't think this topic is ready to be implemented.

**Comment by strekm** [comment]
i think we can close it for now as it might resolve itself once we will work on modularisation
