### ISSUE TITLE
api-gateway test fails on 404 responses from test apps

### ISSUE THREAD

**Issue by kubadz** [kyma-project/kyma#7567]
**Description**

The issue appeared on one of the CI jobs: https://status.build.kyma-project.io/view/gcs/kyma-prow-logs/logs/post-master-kyma-gke-central-connector/1237362582256357376. The job failed because of 404 responses returned from httpbin applications, that are deployed for testing purposes.

**Expected result**

The test doesn't fail.

**Actual result**

The test fails with logs linked in the description.

**Steps to reproduce**

Not known.

**Troubleshooting**

In the api-gateway logs (not provided in the job linked above), there were no entries related to handling APIRules created during the test. However, there were entries of handling APIRules for Rafter, which are created before tests are run. Also, in Oathkeeper logs, there were no entries related to handing requests to httpbin pods. It suggests that api-gateway stopped working and the appropriate resources for Istio or Oathkeeper were not created.

**Comment by Disper** [comment]
Some logs which might be helpful:
- https://status.build.kyma-project.io/view/gcs/kyma-prow-logs/logs/kyma-integration-gardener-gcp/1253232452051144705 
- https://status.build.kyma-project.io/view/gcs/kyma-prow-logs/logs/kyma-integration-gardener-aws/1252598165677281281 
- https://status.build.kyma-project.io/view/gcs/kyma-prow-logs/logs/post-master-kyma-gke-upgrade/1253601524890734592
- from weekly cluster 
`--- FAIL: TestApiGatewayIntegration (65.96s)
Info
2020-04-23 11:21:58.668 CEST
require.go:794:
Info
2020-04-23 11:21:58.668 CEST
Error Trace: main_test.go:244
Info
2020-04-23 11:21:58.668 CEST
Error: Received unexpected error:
Info
2020-04-23 11:21:58.668 CEST
All attempts fail:
Info
2020-04-23 11:21:58.668 CEST
#1: oauth2: cannot fetch token: 401 Unauthorized
Info
2020-04-23 11:21:58.668 CEST
Response: {"error":"invalid_client","error_description":"Client authentication failed (e.g., unknown client, no client authentication included, or unsupported authentication method)","status_code":401}
Info
2020-04-23 11:21:58.668 CEST
#2: oauth2: cannot fetch token: 401 Unauthorized
Info
2020-04-23 11:21:58.668 CEST
Response: {"error":"invalid_client","error_description":"Client authentication failed (e.g., unknown client, no client authentication included, or unsupported authentication method)","status_code":401}
Info
2020-04-23 11:21:58.668 CEST
#3: oauth2: cannot fetch token: 401 Unauthorized
Info
2020-04-23 11:21:58.668 CEST
Response: {"error":"invalid_client","error_description":"Client authentication failed (e.g., unknown client, no client authentication included, or unsupported authentication method)","status_code":401}
Info
2020-04-23 11:21:58.668 CEST
Test: TestApiGatewayIntegration
Info
2020-04-23 11:21:58.668 CEST
main_test.go:330:
Info
2020-04-23 11:21:58.668 CEST
Error Trace: main_test.go:330
Info
2020-04-23 11:21:58.668 CEST
Error: Received unexpected error:
Info
2020-04-23 11:21:58.668 CEST
All attempts fail:
`
