### ISSUE TITLE
Error encountered while getting CRT

### ISSUE THREAD

**Issue by margauxcabrera** [kyma-project/kyma#759]
**Description**

While going through the Automatic connection configuration steps, an error was encountered in step 3 (making the call after creating the CSR):

Installation type: local (minikube - virtualbox)
OS: Windows 10 Home
App used: Postman and curl

**Expected result**

Response contains CRT

**Actual result**

{"code":500,"error":"Error while decoding pem block."}

**Steps to reproduce**

1. Generate key
openssl genrsa -des3 -out ec-default.key 4096
2. Generate crt
openssl req -new -x509 -days 365 -key ec-default.key -out ec-default.crt -config "C:\Program Files (x86)\GnuWin32\share\openssl.cnf"
3. Fetch Kyma URLs and CSR configuration
Request:
https://connector-service.kyma.local/v1/remoteenvironments/ec-default/info?token=Qa1n7ZLgY05AsOj59v5acD7tsaFTWbo8_cjF59-R0WflmTrB5Fau9FIKcSpzh_PB_waX7Yp0u7xa6vkS-xw8cA==
Response:
{
    "csrUrl": "https://connector-service.kyma.local/v1/remoteenvironments/ec-default/client-certs?token=lmgkMlGn_o1CNMGJ-aM3_qolQQBqtp-7uuUb6bDjNxVN7FXcD1vJFaWdV1glUOtX8KQXTjHJKVjSCKsRRthT6A==",
    "api": {
        "metadataUrl": "https://gateway.kyma.local/ec-default/v1/metadata/services",
        "eventsUrl": "https://gateway.kyma.local/ec-default/v1/events",
        "certificatesUrl": "https://connector-service.kyma.local/v1/remoteenvironments/ec-default"
    },
    "certificate": {
        "subject": "OU=OrgUnit,O=Organization,L=Waldorf,ST=Waldorf,C=DE,CN=ec-default",
        "extensions": "",
        "key-algorithm": "rsa2048"
    }
}
4. Create CSR
openssl req -new -out test.csr -key ec-default.key -config "C:\Program Files (x86)\GnuWin32\share\openssl.cnf" -subj "/OU=OrgUnit/O=Organization/L=Waldorf/ST=Waldorf/C=DE/CN=ec-stage"
5. Get crt
curl.exe -H "Content-Type: application/json" -d '{\"csr\":\"MIIEtDCCApwCAQAwbzEQMA4GA1UECxMHT3JnVW5pdDEVMBMGA1UEChMMT3JnYW5pemF0aW9uMRAwDgYDVQQHEwdXYWxkb3JmMRAwDgYDVQQIEwdXYWxkb3JmMQswCQYDVQQGEwJERTETMBEGA1UEAxMKZWM
tZGVmYXVsdDCCAiIwDQYJKoZIhvcNAQEBBQADggIPADCCAgoCggIBAMNNEkYaFiKURmk8RO9pAQnqg0DWzeOxayYEd9+J1l7qRF5omjR+kF97B/+bdNHvFZbXxFF+k91GFlH7kkxeQ8UV5bvFzbWPnzGwHMuOvg7Icxekq8iBGqGVEtg4YX7nLIAMNnL/pr6MrPyI2wsXBM/EIpURbcEQfTzkaS4xFnkDNooXDteMWBpG
5H5xGqX7rhjTWNLtf1XEUNL5VlNuLvXBAfXZq8an7jV6VRNplZIuImZB11YchnzwbFZA4InPdCQR8HSHd6LTbMYgf+f52xMIo5ul2fbYf4Kpxg//WnS5rRVwSo+eoO6qy43MYtLz7EiMAc1DUKC93/+t1lVhLdc/Rd2Nqz4DbAGzabjN/q3QzDTx/DAtSSKsYZ6Hujw9iAgzlufw7BGVdAptM/qbHQU65MbN6xXAOEwmr
jRKjvB3CePUSukDVw0//l94Imo44oFt1ebweK4keQctVtNCumwmtQnYSYQZYdJlCrF70vc+9SmakvnF0Pf/bhMyo7C2eqBwe+A4MgGz6j986lo9UiTqQbNJ6bzb7zqCxTVyPVFzebfobbseAMHWq/DSWd5Qd73pcQKW5CXJDO/Nym1eQHFSOZZUnTyUxvz+LpcEO3nZGa5CiAED3hvoDw5AXBRT1+fdxLjP/J2Acym2/r
3SwxpoQAJC2684JfRIwZcqA38RAgMBAAGgADANBgkqhkiG9w0BAQUFAAOCAgEAZUoJGi1WyMS3JvHuuxGqU/dTeyQLdZfOqPUPVG2JDQ9m5ACdCEVRYX6r1/pD3KBhK6q1S7Hl2BsGcqODDI/2BR0Iv6R5FzDAtKUBksqgxJlbUfiS+x1+UGK0/PaYloZ/YX1nn3mYmFV1Z3ZLBLJKMfdrcbAz+iIBueRL6LVvgNEruLI
7OU7pltcA8vXxxJ/pT4DphqRJpHxEMbXuOcKqOGEwldXXMcDU90toDQbVnz5Id0Vu87zAbt3YkV9BNpRP9POhJML5CD4B3znig5qnul+1PFPMKnjuB94hjtz0itJXfv7iPf60TFP5wlYmkXKb03r+1auSKzuJ/kfEgGNkjuE0ao5Xbc/+YmG5gUcUzgvA7p6txGJnCcD54FGRst7klCxu6Fu3dEo/qBwW+gzBE2WcDdmO
udEAldtEwWmLxHTLl+CsH43eMfjpSeNjILNSUnDGm5x1nNE67XN+HGYuY4/iAVjWvFfix1Rpi8jUxvNJ9GIV74vZGtMIK+0cTljHpvA+4bVj2ODtehCZ1v1J3GaJWZlt3uz46Z5gE4qDRLMVrNc/6K7aviuOmYJs8Ie+ttKt6bEdyhFXEZOD0ejf6QTtLOWmtIymjOrbWQrslnc+VFXwrrErw+PQwuCMz5BwyHqN8zTdd
a6l1wPKyhJX0T48mnyVH1bV\"}' https://connector-service.kyma.local/v1/remoteenvironments/ec-default/client-certs?token=ZabQjZ_woRTDEvwwcrJ38ePdeePqC05mPmHC9gPd8IALIxLTWJ2EmX_CMlXZr7VwbNTt_a8KLgAekuh14KhbkA==

**Troubleshooting**

1. Created a new remoteenvironment to verify but same thing happened.
2. Following the alternative steps in getting the configuration address URL, the following calls are unsuccesful:

`kubectl -n kyma-system get svc core-nginx-ingress-controller -o 'jsonpath={.spec.ports[?(@.port==443)].nodePort}'`
>31838

`curl.exe https://gateway.kyma.local:31838/ec-default/v1/metadata/services --cert ec-default.crt --key ec-default.key -k`
><html>
><head><title>400 No required SSL certificate was sent</title></head>
><body bgcolor="white">
><center><h1>400 Bad Request</h1></center>
><center>No required SSL certificate was sent</center>
><hr><center>nginx/1.15.2</center>
></body>
></html>

`curl.exe https://gateway.kyma.local:31838/ec-default/v1/events --cert ec-default.crt --key ec-default.key -k`
><html>
><head><title>400 No required SSL certificate was sent</title></head>
><body bgcolor="white">
><center><h1>400 Bad Request</h1></center>
><center>No required SSL certificate was sent</center>
><hr><center>nginx/1.15.2</center>
></body>
></html>

**Comment by lszymik** [comment]
Hello @margauxcabrera,

I have looked into it and I have spotted that
- The CSR CName must match the remote environment name ('ec-default' != 'ec-stage') This is not causing an issue, but the certificate will not work
- I was not able to decode the base64 version of the CSR. On my local machine, I have the CSR in such form:
```
-----BEGIN CERTIFICATE REQUEST-----
MIIEtDCCApwCAQAwbzEQMA4GA1UECwwHT3JnVW5pdDEVMBMGA1UECgwMT3JnYW5p
emF0aW9uMRAwDgYDVQQHDAdXYWxkb3JmMRAwDgYDVQQIDAdXYWxkb3JmMQswCQYD
VQQGEwJERTETMBEGA1UEAwwKZWMtZGVmYXVsdDCCAiIwDQYJKoZIhvcNAQEBBQAD
ggIPADCCAgoCggIBAKsuvE8FDFDI6xm4uBxTN/UQX/BUhrRRTcGGnmwSoOUiyKFH
bE0TrNOm97b7TRXBpL4xSA1H0mBuyDt9f83pmLIIc2YThX8MI7bhaCQorbTqM+QU
7xrbQ9h7BxXi2QxhrOeTTmrfOBZ4447RL7vhwkwGBEtjJsJLzdZc1iHUwkf4rqHR
i1H99bp4w6gGlIH7WfLgrpOGB7vkZBYU3kCY+4TXlRbc5twn4eUjFZVdHaBVRCb9
7+141+26JowAFruz4FXMZeHNEIzKR3DPa72x/BqiQ0Kpvz/kjE/DaR7rigMrBI6j
uEOQ08D/yrC1WomRugfdC29kM/5FrA8ccfas18nMbxpo3J0ZopMkKrF2mbJ146AW
Tzcg6jO7R+UI+0he1SiH0OJFjiCbsfUcea/42Z9nbFVpa8f7cFcSBsOGQY9Y9XYn
5yOiK1Y2zSXZR+Ci0ZervMLNCgBHyWT/4x3L1e1jDsNWAzwG4lwPnIXMvPJiTRdy
DIOqjfk+RrwWXZhYXAvsun/DjeR37EYypBNOwC5lEvL3w5T400vmznmVIk7cBzfk
3QkQjEwSgBXjfadvgXrd9VEtjEc++Hlv0HWXcG/H64jaTGN039US4eB49kH/J3oH
/Tky3uJlGYvy+UvHn9gjtLSQtBOVsjI1iq1qHkQUYyw+IEl/uk9gkKuqwVn1AgMB
AAGgADANBgkqhkiG9w0BAQsFAAOCAgEAU7B353ePx0MVtPyPIP7xKIY246pLwRyj
c4CzDk9MYaXvruuBlWliEmL1fwRsCrFtCGiF/6VzP5+Lko5/gaRhHTnBV1ZoSoU2
qRlumnbpZ4yQfz2yZRDB8KO+GP51OdCLim5PZzH69HX8kUZ9d3sy1R9ebicrPrfE
eEMwKQ2AsOLUGq4sTTXzWlITpaQsS7JYQMM/4OTa8q3MiGxz1IbrOXuPv1fLVFEV
SkIOWOA3R3z30ODP5+rlxpqs/7PapM35NL246gnugew5dHyhNXGvVx78BLy5rYGq
G8xJZ/WR+wT3bPNOu37FsI5grSqVHJuxVy4VSPVs17xxWlrixnOWYM40DenP7Ni4
DZM45SsSJVBZw6wjlZGhvVfUjEK91ymZJmnc2binXQdXY+9xoWpB3OvD2o1gu6cy
k/iRZxyfYQkl3ODdmb/Zs4eorxSycz6rcU8hDmhDX2yaY7GsF2XutB1+bq80v/GH
YUBQir3zepqu7+KEBWvvOq7gNLbqpDTjyayTJ6KSjBZ1lGLM/5n6hvPxvCx3wNOo
m8kshc9s6B5Zt6lPC9kcNSS/GtY8G3pZb0wehslmrhdnJB4/aI5IuuJ6pGwkNOWW
TDhrxkkFiYchI5cpwtOQCPOTyb8zzZ7tTc+FaDqpLvbxA94uz8TJBYzqebVbYyIu
RipDoUGuwFw=
-----END CERTIFICATE REQUEST-----
```

However as soon as I decode your CSR, I am getting some binary output:
```
0��0��0o10U
           OrgUnit10U

Organization10UWaldorf10Waldorf1
                                0	UDE10U
�0�defau*�H��0
��MF"�Fi<D�i	�@���k&w߉�^�D^h�4....
```

Can you please check how the base64 is working on Windows machine, maybe there is some additional encoding. I am using MacOS.

- The third issue is that the Connector Service is returning 500 response. We will fix it to return the 400 - Bad Request.

**Comment by margauxcabrera** [comment]
Hi @lszymik 

I must have pasted some of the items when I was testing it in the remote environment I have created. But I have stated correct in the requests and still got the same error. I'll look into the base64 encoding in Windows machine and let you know if I find anything.

Thanks!
