### ISSUE TITLE
Strict mtls settings for ingress gateway

### ISSUE THREAD

**Issue by piotrmsc** [kyma-project/kyma#7624]
**Description**

During istio installation we apply Destination Rule for ingress gateway with mtls set to `permissive`, take a look [here](https://github.com/kyma-project/kyma/blob/master/resources/istio/files/destination-rules.yaml). When we enabled strict mTLS mesh wide, this DR was created for testing pods. Currently, we need to check if it can be deleted, ingress will have strict mTLS settings.

**Reasons**

From a security perspective it should be aligned. We have mesh wide strict mTLS settings but ingress is set with permissive mode. 

**Attachments**

**Comment by Demonsthere** [comment]
https://github.com/kyma-project/kyma/pull/8010

**Comment by Demonsthere** [comment]
Results of the tasks:
- For cluster operations, we can safely remove the DR after an improvement in the `api-gateway` tests.  These tests, as well as `dex`, are using an outdated ingress client which is required for minikube ip address discovery. 
- As the `dex` tests are run only in the minikube environment, we have decided to leave the DR for minikube and switch the client for cluster operations
