### ISSUE TITLE
Create an End to End Tutorial for Using Event Mesh

### ISSUE THREAD

**Issue by anishj0shi** [kyma-project/kyma#7651]
Current Documentation needs a bit more work in terms end user's usability of the event-mesh. We need to have an end to end tutorial for event-mesh from an end user perspective.

**AC**
This Tutorial needs to cover the following:
-  Explanation on how to Create an Application from CR and an HTTPSource is created in the background
-  How a created serviceinstance of the above application will create a knative-broker.
- How to Create a knative Trigger 
- Publish Events on */events* with cloud event spec and */v1/events* with the old spec.

**Comment by bszwarc** [comment]
1. Explanation on how to Create an Application from CR and an HTTPSource is created in the background

Should we have a sample application for the sole purpose of this example? There was an `order-created` application created for compass, so maybe we can use this one (https://kyma-project.io/docs/components/compass/#tutorials-manage-your-applications-using-kyma-console-and-compass-u-is-prerequisites) for our purpose too.  Or if not we should have an application created for that. 

2. How a created serviceinstance of the above application will create a knative-broker.
Will this be created via UI or using kubectl? I would opt for kubectl (and we can also add the UI part in the tab if necessary). 

3. How to Create a knative Trigger - using kubectl as well (useful resource here: https://kyma-project.io/docs/master/components/serverless-v2/#tutorials-trigger-a-lambda-with-an-event

4.  Publish Events on /events with cloud event spec and /v1/events with the old spec. How exactly?

**Comment by bszwarc** [comment]
What still needs to be documented:

    we need a clear explanation what the Compatibility Layer is and how it works
    what is the difference between the old approach towards events - we can use this doc: https://kyma-project.io/docs/1.10/components/event-bus/#details-event-delivery (at least event payload and metadata sections) and the CloudEvents compatibility
    What I need is some input on these things :)
