### ISSUE TITLE
Test Kyma behavior with knative-kafka when reaching the namespace event hubs quota

### ISSUE THREAD

**Issue by Abd4llA** [kyma-project/kyma#7665]
**Description**

Azure Event Hub namespaces has a quota for Event Hubs. The behavior of Kyma that uses Knative-Kafka channel implementation is unknown when reaching that limit and we need to figure it out.

**AC**

- Kyma behavior when reaching the quota limit of Azure Event hubs is documented.

**Comment by montaro** [comment]
After consuming the quota, creating a new app will have a NOT READY Channel
```
❯ kubectl -n kyma-integration get kafkachannels.knativekafka.kyma-project.io test-app-7
NAME          READY   REASON        HOSTNAME    AGE
test-app-7    False   TopicFailed               6h21md
 ```
Provisioning a namespace with an Event Service, will have a NOT READY Broker and the Broker and Trigger pods won't be created
```
❯ kubectl -n test-ns5 get kafkachannels.knativekafka.kyma-project.io default-kne-trigger
NAME                  READY   REASON        HOSTNAME   AGE
default-kne-trigger   False   TopicFailed              21h
``` 
The knative-eventing-kafka-channel-controller

```
❯ kubectl -n knative-eventing logs -lapp.kubernetes.io/instance=knative-eventing-kafka -c channel-controller
...
"msg":"Failed To Create Topic (Results)","Controller":"kafka-channel-controller","Topic":"test-ns5.default-kne-trigger","error":"error code: 403, Details: SubCode=40300. The maximum number of resources of type EventHub has been reached or exceeded. Actual: 10, Max allowed: 10. For more information visit https://aka.ms/sbResourceMgrExceptions (Service Bus) or https://aka.ms/eventhubsarmexceptions (Event Hubs).
```

**Comment by marcobebway** [comment]
LGTM.

**Comment by k15r** [comment]
maybe we should put this information in our troubleshooting documentation for oncall?

**Comment by montaro** [comment]
@k15r thanks for the tip
https://cxwiki.sap.com/display/ysf/Group%3A+Eventing

**Comment by nachtmaar** [comment]
> Kyma behavior when reaching the quota limit of Azure Event hubs is documented.

@montaro The AC says the behaviour should be documented. I think it makes sense to have it in the public eventing documentation instead of only in a ticket. What do you think?
cc: @anishj0shi
