### ISSUE TITLE
Adjust upgrade tests for Application Operators for ApiPackages scenario

### ISSUE THREAD

**Issue by Maladie** [kyma-project/kyma#7669]
**Description**

As Application Operator will now deploy Gateways once per namespace based on Service Instance CRs, we  need to ensure smooth upgrade between future releases. To achieve that, some adjustments in existing upgrade tests are necessary.

**Acceptance criteria:**
- Tests are able to verify new implementation of Application Operator
- Tests are checking deployed Gateways and Event Services independently

**Comment by janmedrek** [comment]
Closing this due to redesign of App Connectivity area.
