### ISSUE TITLE
post-master-compass-integration: TestConnector tests fail when connecting to compass-director

### ISSUE THREAD

**Issue by Ressetkk** [kyma-project/kyma#7678]
**Description**
TestConnector, TestCompassAuth, TestDirectorPlaygroundAccess tests fail when connecting to the following paths:

* http://compass-director.compass-system.svc.cluster.local:3000/graphql
* https://compass-gateway.kyma.local/director/graphql

Te tests fail returning:
```
{"code":500,"error":"Failed to get application from Director: Post http://compass-director.compass-system.svc.cluster.local:3000/graphql: context deadline exceeded"}
...
Post https://compass-gateway.kyma.local/director/graphql: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
```

**Failing jobs**
https://status.build.kyma-project.io/view/gcs/kyma-prow-logs/logs/post-master-compass-integration/1240239792197734400
https://status.build.kyma-project.io/view/gcs/kyma-prow-logs/logs/post-master-compass-integration/1240268858602819584
https://status.build.kyma-project.io/view/gcs/kyma-prow-logs/logs/post-master-compass-integration/1240268984473882624

**Comment by Ressetkk** [comment]
Another failed job https://status.build.kyma-project.io/view/gcs/kyma-prow-logs/logs/post-master-compass-integration/1240365367671394304

**Comment by Ressetkk** [comment]
https://status.build.kyma-project.io/view/gcs/kyma-prow-logs/logs/post-master-compass-integration/1240946949142614016

**Comment by franpog859** [comment]
This is the same issue as [that one](https://github.com/kyma-incubator/compass/issues/1048). I'll close the [#1048](https://github.com/kyma-incubator/compass/issues/1048) then

**Description**

Connectivity Adapter tests are not quite stable. We can enhance their stability by adding request retries in them

Most of the times when the test fail it fails when calling Director:

```json
{"code":500,"error":"Failed to get application from Director: Post http://compass-director.compass-system.svc.cluster.local:3000/graphql: context deadline exceeded"}
```

**Acceptance Criteria**
- [ ] add request retries in Connectivity Adapter tests
