### ISSUE TITLE
Enhance documentation for logging

### ISSUE THREAD

**Issue by sayanh** [kyma-project/kyma#770]
**Description**
Add a architectural diagram for `020-architecture-logging.md`

**Reasons**

**Attachments**

**Comment by bszwarc** [comment]
Within this tasks I would also rework the documentation a bit.

**Comment by a-thaler** [comment]
This ticket was is related to the old setup with OKLog. In anyway, we already added a digram for the new setup with Loki, see https://github.com/kyma-project/kyma/pull/3220
