### ISSUE TITLE
Update knative-serving acceptance tests dependencies to mitigate security issues

### ISSUE THREAD

**Issue by aerfio** [kyma-project/kyma#7710]
**Description**

We had security issue detected in our knative-serving acceptance tests, and in a friendly matter bumped by friendly team: https://github.com/kyma-project/kyma/pull/7701. We need to ensure that we have safe dependencies in those tests now.

**Reasons**

Security mitigation. 

AC:
- bump dependencies to newest ones
- migrate to modules instead of dep
- check for any security issues in those tests

**Attachments**

**Comment by michal-hudy** [comment]
This test is currently disabled, as it is tested by Functions and Events tests.
