### ISSUE TITLE
Delete/update event-bus test components

### ISSUE THREAD

**Issue by anishj0shi** [kyma-project/kyma#7731]
Clean up event-bus test Components

**AC**
- [x] Remove Integration tests for event-bus
- [x] Update core-test-external-solution test, if needed.
- [ ] Check if there's a reference to event-bus publish-service in application operator test, update it if needed.
- [x] Check if Backup/Restore tests have event-bus references,  if yes, lets remove them
- [x] Check if Upgrade tests have event-bus references, if yes, lets remove them
- [x] Check if e2e-kubeless tests have event-bus references, if yes, lets remove them
- [x] Check and delete other references of event-bus components in test directory

**Comment by k15r** [comment]
kubeless will be removed in this PR: #7800
