### ISSUE TITLE
Lambda doesn't get triggered by the event if exposed via kyma API Object

### ISSUE THREAD

**Issue by anishj0shi** [kyma-project/kyma#7744]
It was observed that, if we create a lambda function and enable https with JWT authentication and event-trigger at the same time. the lambda function returns 401 Unauthorized to the eventing dispatchers.

Eventing dispatcher works on the cluster-local urls. does these urls also validate an incoming request for authentication?

**Comment by piotrmsc** [comment]
Hi!
To which API are you refering to? Old or new one?
Both APIs (old and new one) allows you to expose a service with authentication either on entire service or on selected endpoints(paths).

If you use old API authentication (regardless of selected option : entire service or endpoints) it works both for in-cluster and from externall (via ingress) communication. This authentication is ensured directly via envoy using Istio Policy.

In case of new API such authentication will work for requests from external  world(via ingress) only, and authentication is performed by oathkeeper.
