### ISSUE TITLE
Logging stress test

### ISSUE THREAD

**Issue by a-thaler** [kyma-project/kyma#7759]
**Description**
As a follow up of having a production profile, it must be assured that the profile works as expected.

For that, please test a setup with two dimensions:
- pods spamming with logs
- pods querying the log API

How setups with one dimension fixed and an increasing amount of the other dimension. Measure the latency of one dedicated query and the completeness of the logs for this query.

Furthermore, have a long running test over several days with a moderate load of the log dimension in order to watch the persistentVolume size and the memory footprint of the involved components

**Reasons**

**Attachments**

**Comment by a-thaler** [comment]
We talked about the results, still please document the key findings here to have it documented. How can we close a ticket having no comment and code changes. I saw plenty of grafana screenshots, let's just put them here with the main conclusions and everyone will understand why we think that the current setup is good enough.

**Comment by bszwarc** [comment]
I agree with @a-thaler, we can then use these results to add a clear recommendation for our users in the public doc.

**Comment by hisarbalik** [comment]
**Test cluster setup:**
3 Nodes each with 4 CPU and 15Gig memory

**Logging deployment:**
3 log collector fluent-bit deployed on each nodes with configuration CPU limit 100m and memory limit 128Mi
1 loki deployment as log storage and search service with configuration CPU limit 200m, memory limit 300Mi, 10Gi persistence volume and 24 hours as retention period

**Test scenario 1: Test log collection behavior**

- Test start with 10 active pod distributed over nodes, each generate approximately 4K log every second

- Test pods are scaled-up every 10 minutes with 10 additional pods

- Test runs 1 hour 

**Result test scenario 1:**
All 3 fluent-bit collector stay stable over time both memory and CPU resources with no restart
Loki server hit memory limit from 35 active pods on and running out of memory, CPU consumption stay stable over time


**Test scenario 2: Test log collection and query behavior**

- Test start with 10 active pod distributed over nodes, each generate approximately 4K log every second

- Test pods are scaled-up every 10 minutes with 10 additional pods

- Test runs 1 hour 

- Loki hits with 4 different queries every second during test execution time 

**Result test scenario 2:**
All 3 fluent-bit collector stay stable over time both memory and CPU resources with no restart
Loki server hit memory limit from 30 active pods on and running out of memory, CPU consumption hit limits after 30 minutes and log query result response time getting longer

**Test scenario 3: Test log collection, storage and retention behavior**

- Test start with 10 active pod distributed over nodes, each generate approximately 4K log every second

- Test pods are scaled-up every 10 minutes with 10 additional pods and stop at 30 pods

- Test runs 72 hours 

**Result test scenario 3:**
All 3 fluent-bit collector stay stable over time both memory and CPU resources with no restart
Loki server hit memory limit stay stable
Disk not run out of storage and only last 24 hours old log entries remains
