### ISSUE TITLE
Ensure that storage class is available on GKE

### ISSUE THREAD

**Issue by pbochynski** [kyma-project/kyma#777]
Installer expects storage class managed-standard to be present. In case of GKE such class is not defined. Adjust the configuration to enable installation on GKE. Consider:
- using default storage class
- define storage class in the installation (cluster-essentials)

If the solution requires installation parameter that defines cloud provider, please make sure GKE is the default.

**Comment by strekm** [comment]
we should not create any specific storage classes. Instead our charts should use default storage class or user overrides. Creation of storage class should disappear from any documentation and issues for chart owners should be created.
