### ISSUE TITLE
Switch Compass Runtime Agent to use config stored in secret

### ISSUE THREAD

**Issue by janmedrek** [kyma-project/kyma#7788]
**Description**

Currently, the configuration for Compass Runtime Agent that enables it to make a connection is stored. in Config Map, this is not the ideal solution since there are a one-time-token and tenant id's included. We should make it hidden by storing the whole config within a secret.

**Acceptance Criteria**
- Runtime Agent's config is stored in secret, not a config map

**Comment by sergio-oss** [comment]
To be planned for 1.13

**Comment by janmedrek** [comment]
Keep in mind upgrades of older clusters - Runtime Agents used configmaps and not secrets.
