### ISSUE TITLE
Kyma installation problems on Gardener and AKS

### ISSUE THREAD

**Issue by aerfio** [kyma-project/kyma#7789]
**Description**
Recently we were having problems with installing Kyma on gardener due to the fact that Tiller loses connection to apiserver. The problem is that we are putting a huge load on apiserver, and Gardener is then autoscaling it, which is the root cause of this situation. Unfortunately installer is usually not capable of recovering from it, trying to once again install particular component, which then fails with (example) message: 
```
! install component logging failed, which may be OK. Will retry later...
To fetch the error logs from the installer, run: kubectl get installation kyma-installation -o go-template --template='{{- range .status.errorLog }}{{printf "%s:\n %s\n" .component .log}}{{- end}}'
To fetch the application logs from the installer, run: kubectl logs -n kyma-installer -l name=kyma-installer
X install component logging
logging:
Helm install error: rpc error: code = Unknown desc = release logging failed: timed out waiting for the condition [%!s(int64=1)]
logging:
Helm install error: rpc error: code = Unknown desc = a release named logging already exists.
Run: helm ls --all logging; to check the status of the release
Or run: helm del --purge logging; to delete it [%!s(int64=5)]
```

Taken from https://status.build.kyma-project.io/view/gcs/kyma-prow-logs/logs/kyma-integration-gardener-gcp/1242723026152198144.

Approx a week ago it manifested by failing on knative componets, but during investigation it turned out that it happens because those components are near the beginning of installation. We have observed failing installation on many other components too, as I said in [this](https://github.com/kyma-project/kyma/issues/7629#issuecomment-600635720) comment. 

Since that time Gardener guys have introduced some hotfixes that improved the situation, but it still sometimes fail on installation, mainly on **logging** component: 
- https://status.build.kyma-project.io/view/gcs/kyma-prow-logs/logs/kyma-integration-gardener-gcp/1242723026152198144
- https://status.build.kyma-project.io/view/gcs/kyma-prow-logs/logs/kyma-integration-gardener-azure/1242405937910648832
- https://status.build.kyma-project.io/view/gcs/kyma-prow-logs/logs/kyma-integration-gardener-azure/1241681160937934848

One recommendation they provided was that we could upgrade our pipelines to use higher version of k8s, at least 1.16.7, so that [this](https://github.com/kubernetes/kubernetes/pull/88911) fix will be included, which unfortunately was not observed to help. 

We already have an issue created to improve installer https://github.com/kyma-project/kyma/issues/7629, and here is the issue which started all of this, where we had problems with knative installation and where we shared useful Tiller logs: https://github.com/kyma-incubator/compass/issues/980

As for **AKS**: it is only a speculation, but the issues observed on AKS, like here https://github.com/kyma-project/kyma/issues/7725 may have similar cause. It may also be caused by the fact that the azure is recently having problems with much higher traffic 😛 
 https://www.theregister.co.uk/2020/03/24/azure_seems_to_be_full/

**Comment by aerfio** [comment]
Fixes made on Gardener side: 
https://github.com/gardener/hvpa-controller/pull/63
https://github.com/gardener/gardener/pull/2069 <- just an image bump

**Comment by ggaurav10** [comment]
Setting the helm installation as "atomic" might be useful.
```
Usage:
  helm install [CHART] [flags]

Flags:
      --atomic                   if set, installation process purges chart on fail, also sets --wait flag
```

This can also be useful in case any upgrades are done:
```
Usage:
  helm upgrade [RELEASE] [CHART] [flags]

Flags:
      --atomic                   if set, upgrade process rolls back changes made in case of failed upgrade, also sets --wait flag
```

**Comment by aerfio** [comment]
During last week the only component that has been failing on `post-master` jobs was `logging`
cc @a-thaler

**Comment by clebs** [comment]
Hi @aerfio,
we identified this issue as part of a broader issue in the kyma installation process.
Here is the issue of the installation issue which should fix this:
https://github.com/kyma-project/kyma/issues/7629

Closing this issue in favor of the previously linked one.
