### ISSUE TITLE
Upgrade job keeps on failing on `test-e2e-upgrade-execute-tests` on post-master

### ISSUE THREAD

**Issue by aerfio** [kyma-project/kyma#7799]
**Description**
`test-e2e-upgrade-execute-tests` keeps on failing on ci, as mentioned in title, mainly on `HelmBrokerConflictUpgradeTest`. Logs in comments below

**Comment by aerfio** [comment]
https://status.build.kyma-project.io/view/gcs/kyma-prow-logs/logs/post-master-kyma-gke-upgrade/1242827841448448002

**Comment by aerfio** [comment]
https://status.build.kyma-project.io/view/gcs/kyma-prow-logs/logs/post-master-kyma-gke-upgrade/1242865716546244610

**Comment by aerfio** [comment]
https://status.build.kyma-project.io/view/gcs/kyma-prow-logs/logs/post-master-kyma-gke-upgrade/1242884590377373697

**Comment by aerfio** [comment]
https://status.build.kyma-project.io/view/gcs/kyma-prow-logs/logs/post-master-kyma-gke-upgrade/1242894027498459136

**Comment by PK85** [comment]
Timeboxed to 5SP
