### ISSUE TITLE
Kiali show error message "could not fetch data" in the UI

### ISSUE THREAD

**Issue by hisarbalik** [kyma-project/kyma#7821]
**Description**

Almost in every view in the Kiali UI pop-up error message "**Could not fetch data**" and not all request from UI to the back-end service are successfully 

**Expected result**

Kiali can fetch and show data in the corresponding view in the UI

**Actual result**

Kiali UI show an error message "**Could not fetch data**" in almost every UI view

**Steps to reproduce**

- Login to kyma console and click on left navigation area to link "**Service Mesh**"

- Use kyma console login credentials to login Kilai UI. 

- Click any navigation node on the left side of navigation bar

- Depend on view appear one or more error messages on right-top side of view

**Troubleshooting**

Problem seems to be time-out with k8s-API-Server, Kiali sending to many request for each view to the k8s-API-Server, when API-Server already overloaded with other requests, this run to time outs.

**Comment by bszwarc** [comment]
@a-thaler , @hisarbalik - does this qualify as a troubleshooting guide, or needs to be mentioned in the Release Notes for 1.12 as a known issue? Or it will be solved (hopefully) by then?

**Comment by a-thaler** [comment]
It should be mentioned for 1.11 release notes and hopefully will be fixed in 1.12

**Comment by a-thaler** [comment]
Fixed by #8132
