### ISSUE TITLE
Make the Application Connector documentation more clear

### ISSUE THREAD

**Issue by klaudiagrz** [kyma-project/kyma#783]
The current Application Connector documentation is a bit misleading. 
https://kyma-project.io/docs/latest/components/application-connector#details-deploy-a-new-application-connector

1. In the "Overview" section, there are Application Connector's components listed. In the next section, there are also some components but these from the "Application Connector components" section are totally different from the components listed in the "Overview" section. 

2. There is also some misleading information in the components' description. For example:
"Ingress-Gateway controller responsible for validating certificates and exposing multiple Application Connectors to the external world". This sentence implies that there are more Application Connectors. I bet it's not correct.

3. It would be also good to get rid of EC relations from the diagram (OCC, Extensions?).

4. I bet the "Consuming applications through the Service Catalog" section should be displayed higher as you have ServiceClasses mentioned earlier in the documentation.

5. In the "Install a Remote Environment on a local Kyma deployment" section, there is a sentence:
"To install a new Remote Environment on Minikube, provide the NodePort as shown in this example:" - I guess it's too much of a mental shortcut.

6. Is the "Work with Helm" section needed? Maybe we should just summarize in one sentence that the user can use Helm commands and provide the link to the Helm documentation?

7. All links in the "API" section are dead :(

**Comment by lszymik** [comment]
Thank you very much for your feedback. We will start improving documentation.
