### ISSUE TITLE
Monitoring stress test

### ISSUE THREAD

**Issue by a-thaler** [kyma-project/kyma#7847]
**Description**

As a follow up of having a production profile, it must be assured that the profile works as expected.

For that, please test a setup with two dimensions:

pods spamming with metrics (istio metrics mainly)
pods querying the prometheus API
How setups will behave with one dimension fixed and an increasing amount of the other dimension.?

Furthermore, have a long running test over several days with a moderate load of the metric dimension in order to watch the persistentVolume size and the memory footprint of the involved components
**Reasons**

**Attachments**

**Comment by hisarbalik** [comment]
**Test cluster setup:**
3 Nodes each with 4 CPU and 15Gig memory

**Monitoring deployment:**
Prometheus operator deployed with resource configuration 1500Mi memory, 600m CPU, and 10Gi storage. Retention policies configured for 1 day and max 2 GB

Prometheus query time-out configured 60 seconds 

Test scenario: 

Test application simulate aproximitely 3 millions API hits for 3 endpoints per day/per instance with 5% result http 5XX status and 5% http 4XX. Application also produce CPU and disk metrics with internal instrumentation logic to simulate real application behavior.

Test application deployed with 48 in-depended instances over 16 namepsaces, each namespace contains 3 instance of test application. 24 instances without istio enabled configuration over 8 namespaces and 24 instances without istio over 8 namespaces.

Test runs 96 hours and produces constantly metrics for simulated API calls, CPU, memory, and disk resources

**Result test scenario:**
Before test scenario deployment prometheus was with ~50K time series from default kyma components, after test scenario deployment time series amount increase ~80K.

Prometheus hit configured memory limit permanently during entire test time, prometheus stay over time stable and no pod restarts. Grafana charts was responsive and prometheus queries was successfully executed in configured time-out time frame. 

No metric scrape time-outs or scrape error observed.

**Conclusion:**
Stress test shown, with current default production profile (with 2Gi memory) of monitoring will stay stable with 48 active application producing constant metrics. Retention rules works as expected.
