### ISSUE TITLE
Enable function-controller tests on minikube

### ISSUE THREAD

**Issue by aerfio** [kyma-project/kyma#7853]
**Description**
_Everything below is assumed to be done while using kyma-cli_

Right now we do not run function-controller tests on minikube, due to two things:
- minikube has very little resources, and while building function there our tekton taskrun runs too long, causing it to timeout (probably due to too little resources)
- to have access to function you need to add it's host (the same as in apirule) to /etc/hosts file alongside other kyma redirects there 

Investigation must be made here whether it's even possible to run our tests on minikube - resources may be a show stopper, I'm the only fortunate one to have MBP with 32gb ram and i9 in our team and for some time I'm the only one capable of installing full kyma -> maybe building functions is just too much.

Next thing -> if we somehow speed up that build we need to access the function from outside. Here we have two options: add that function to `/etc/hosts` on host machine, or use magic spell like this:

```bash
FN_PORT="$(kubectl get svc istio-ingressgateway -n istio-system --output 'jsonpath={.spec.ports[?(@.port==80)].nodePort}')"
curl -v -L -H "Host: THAT_FN_HOST.kyma.local" http://$(minikube ip):${FN_PORT}
```

Taken from old fn-controller docs.

Unfortunately right now using curl like that leaves us with error like that 

```
*   Trying 192.168.64.192...
* TCP_NODELAY set
* Connected to 192.168.64.192 (192.168.64.192) port 30281 (#0)
> GET / HTTP/1.1
> Host: dupa.kyma.local
> User-Agent: curl/7.64.1
> Accept: */*
>
< HTTP/1.1 301 Moved Permanently
< location: https://dupa.kyma.local/
< date: Tue, 31 Mar 2020 09:10:03 GMT
< server: istio-envoy
< content-length: 0
<
* Connection #0 to host 192.168.64.192 left intact
* Issue another request to this URL: 'https://dupa.kyma.local/'
* Could not resolve host: dupa.kyma.local
* Closing connection 1
curl: (6) Could not resolve host: dupa.kyma.local
* Closing connection 0
```

**Reasons**
Minikube is our main development platform and Kyma should all work on all platforms.

**Attachments**

**Comment by aerfio** [comment]
**Fresh info from mhudy**
It doesn't work when installing Kyma from scripts, and we use them when installing on pipeline. So this is the root cause and needs to be investigated

**Comment by michal-hudy** [comment]
Take a look at `stub` domains in k8s

**Comment by michal-hudy** [comment]
Display related resources in case of timeout

**Comment by michal-hudy** [comment]
I would skip it for now and rather focus on the external docker registry, as the internal docker registry can be a problem: #8204, also this test can be really slow on minikube.

It is tested on GCP, AKS, and Gardener on every PR/master/release.
