### ISSUE TITLE
Enable GCP broker installation in Kyma

### ISSUE THREAD

**Issue by PK85** [kyma-project/kyma#786]
AC:
- check if GCP broker could be installed/uninstalled automatically
- check if GCP broker could be installed in many namespaces
- check if GCP broker could be registered in many namespaces ✓
- GCP Broker installation/deinstallation available in Kyma as a bundle with detailed instruction what needs to be done manually (e.g. input Secret)
  - register in a same namespace
- GCP Service Classes has documentation provided by us (same as Azure Service Classes)
- update documentation about supported brokers

**Comment by piotrmiskiewicz** [comment]
Current Service Catalog implementation performs refresh of a secret which holds auth credentials only when the broker reconciliation process is being executed. We need to consider update the secret - contribution to the Service Catalog

**Comment by mszostok** [comment]
- modify `sc` tool to support ns installation: @adamwalach 
  - fork to kyma-incubator
  - create PR to upstream
  - create tool realese and add sufficient documentation
  - check `sc` tool in case of install/uninstall
 
- create bundle 
  - create project under the kyma/tools directory with Dockerfile and installation helpers required to create a kyma bundle.
  - create a bundle in kyma/bundles 
  - add documentation how the bundle installation work

- add docs for GCP Service Classes under the `kyma/docs/service-brokers/`  and helm chart with docu instalation similiar to [this one](https://github.com/kyma-project/kyma/blob/master/resources/core/charts/azure-broker/templates/azure-service-classes-docu.yaml)

- update documentation about supported brokers

- investigate if we can be hardcoded to some version

**Comment by mszostok** [comment]
Issue found during testing: https://github.com/kubernetes-incubator/service-catalog/issues/2492

**Comment by adamwalach** [comment]
[serviceplans.zip](https://github.com/kyma-project/kyma/files/2594685/serviceplans.zip)

**Comment by mszostok** [comment]
Summary:

Merge PRs:
- [Add GCP Broker provider tool](https://github.com/kyma-project/kyma/pull/1649)
- [Add gcp-broker-provider helm chart](https://github.com/kyma-project/bundles/pull/33)
- [Add documentation for gcp-broker-provider](https://github.com/kyma-project/kyma/pull/1774)
- [Add documentation for GCP Service Classes](https://github.com/kyma-project/kyma/pull/1717)
- 
Found issues:
- [Catalog UI do not support GCP Broker schemas](https://github.com/kyma-project/kyma/issues/1648)
- Serivce Catalog - [Cannot delete ClusterServiceBroker/ServiceBroker when wrong auth is specified](https://github.com/kubernetes-incubator/service-catalog/issues/2492)
- [GCP broker bundle fails with 'PENDING_INSTALL' status on minikube cluster](https://github.com/kyma-project/kyma/issues/1842)
- [BackoffLimit doesn't work on minikube cluster](https://github.com/kyma-project/kyma/issues/1838)
- [Credentials form does not disappear after successful submit](https://github.com/kyma-project/kyma/issues/1837)
- ['Service Binding' form in Lambdas section does not support any additional parameters ](https://github.com/kyma-project/kyma/issues/1835)
- [Credentials form allows empty value in mandatory "select" field ](https://github.com/kyma-project/kyma/issues/1833)
- [Installation of GCP Broker bundle is permanently broken when secret is not present ](https://github.com/kyma-project/kyma/issues/1764)
- Add proper error handling for `sc` tool
