### ISSUE TITLE
Assure that logging and monitoring stack survive disk loss

### ISSUE THREAD

**Issue by a-thaler** [kyma-project/kyma#7860]
**Description**

The current assumption is that logging and monitoring will survive a disk loss having no backup in place. That scenario must be verified by once removing all the disks and seeing that the component survive and staying operational (losing historical data)

**Reasons**

**Attachments**

**Comment by suleymanakbas91** [comment]
It is not possible to delete a disk on Azure or on GKE when it is still being used by a cluster. Although I managed to detach a disk on GKE, it immediately re-attached to the cluster.
