### ISSUE TITLE
Gardener Upgrade from 1.10 to 1.11 fails (apiserver-proxy)

### ISSUE THREAD

**Issue by akrausesap** [kyma-project/kyma#7866]
**Description**

Fresh Gardener Cluster (1.16.8) fails to upgrade from Kyma 1.10 to Kyma 1.11.

**Expected result**

Upgrade works

**Actual result**

Upgrade fails (see attachments)
[dempoyment.txt](https://github.com/kyma-project/kyma/files/4414226/dempoyment.txt)
[kyma-installer-67879bf865-s2tl9.log](https://github.com/kyma-project/kyma/files/4414227/kyma-installer-67879bf865-s2tl9.log)

**Steps to reproduce**

1. Provision Gardener Cluster (1.16.8) with suggested config on Google through dashboard
2. Apply Kyma 1.11 installer

**Troubleshooting**

N/A

**Comment by abbi-gaurav** [comment]
Seeing the same errors when adding a new component to 1.10

I am also seeing the same error when adding a new component to a fresh 1.10 cluster. The same upgrade process is followed in this case also

```
2020/04/01 09:57:26 Step error:  Details: Helm install error: rpc error: code = Unknown desc = a release named logging already exists.
Run: helm ls —all logging; to check the status of the release
Or run: helm del —purge logging; to delete it
2020/04/01 09:57:26 Error during install/update:  Details: Helm install error: rpc error: code = Unknown desc = a release named logging already exists.
Run: helm ls —all logging; to check the status of the release
Or run: helm del —purge logging; to delete it
E0401 09:57:26.469796       1 controller.go:287] Helm install error: rpc error: code = Unknown desc = a release named logging already exists.
Run: helm ls —all logging; to check the status of the release
```

**Comment by piotrmsc** [comment]
After having an offline discussion here's a summary of what failed : the wildcard domain `kyma.oansmzj9w6.d046471-te.shoot.canary.k8s-hana.ondemand.com` was too long, when apiserver is being installed it has a separate certificate with separate domain `apisever.$domain` but the limit is 64 characters in total in Gardener (due to restrictions in ACME). We have described this in the Migration Guides. We are thinking of shorting the apiserver name,however, `api.$CLUSTER_DOMAIN` is already taken in Gardener.

**Comment by piotrmsc** [comment]
Errors like `release xxx already exists` are present when given release fails to install/upgrade (FAILED state) and tiller cannot then install it again. In such cases like with the logs, cluster operator needs to check why logging failed and perform cleanup manually. Currently we are thinking of possible changes in the kyma-operator, that aims to automate a little cleanup if possible, but this will not solve all of the cases. If you check installation CR `kubectl get installation/kyma-installation -o yaml` you will have `errorLog` property there, where all the errors from tiller that operator receives are saved. Check for the first one for component logging and we should have more info what caused the failure of logging.

**Comment by piotrmsc** [comment]
We are also still extending and updating our troubleshooting guides, but for the above error you can also go through like described here https://kyma-project.io/docs/#troubleshooting-common-installation-errors-installation-fails-without-an-apparent-reason
