### ISSUE TITLE
X-Forwarded-For handling in API Gateway v2

### ISSUE THREAD

**Issue by akrausesap** [kyma-project/kyma#7902]
**Description**

Dear Colleagues,

in API Gateway v2 the indirection from istio via the ory components cause that the host header is now set to the K8S internal service name. Furthermore the X-Forwarded-* headers are set to misleading values. This causes components that use these values to produce external host names to not function anymore. Below is a real sample of the headers:

{
   "host":"logger.personservice.svc.cluster.local:8080",
   "user-agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.122 Safari/537.36",
   "accept":"image/webp,image/apng,image/*,*/*;q=0.8",
   "accept-encoding":"gzip, deflate, br",
   "accept-language":"en-US,en;q=0.9",
   "cache-control":"no-cache",
   "certificate-data":"By=spiffe://cluster.local/ns/kyma-system/sa/oathkeeper-maester-account;Hash=0a7373aca126b0eff277e0e92cf4506450c17d745db97a724c6f8e15f85572fb;Subject=\"\";URI=spiffe://cluster.local/ns/istio-system/sa/istio-ingressgateway-service-account",
   "cookie":"_ga=GA1.2.1976884213.1550584065; rxVisitor=1583424650883EMG99P1EEMQIGV28522IC2H8F36RIN8S; dtLatC=1; dtSa=-; dtPC=15$350074451_535h-vGHPPPJDCJMDNMDORCTPANEMIMGEETJVN-0; dtCookie=v_4_srv_15_sn_727C6D32EA5EC2CA6BB0E09FD151CED8_perc_100000_ol_0_mul_1_app-3Aea7c4b59f27d43eb_1; rxvt=1584951910748|1584950045609",
   "dnt":"1",
   "pragma":"no-cache",
   "referer":"https://logger.{clusterhost}/",
   "sec-fetch-dest":"image",
   "sec-fetch-mode":"no-cors",
   "sec-fetch-site":"same-origin",
   "x-forwarded-for":"10.250.0.3, 127.0.0.1",
   "x-forwarded-proto":"https",
   "x-request-id":"c7bd09cd-8973-4c9f-a699-20a99a38387a",
   "content-length":"0",
   "x-forwarded-client-cert":"By=spiffe://cluster.local/ns/personservice/sa/default;Hash=de0fd670ff2214c09acb8ccc99e4ee724fde35e48217989d0134b60e78e4b3cd;Subject=\"\";URI=spiffe://cluster.local/ns/kyma-system/sa/oathkeeper-maester-account",
   "x-b3-traceid":"0dfdde37ff9924bfacf717d949c9ff8d",
   "x-b3-spanid":"161969ec2072d8fe",
   "x-b3-parentspanid":"7fee11bbbcb108c4",
   "x-b3-sampled":"0"
}

**Expected result**

"x-forwarded-for":"logger.{clusterhost}",
 "x-forwarded-proto":"https",

**Actual result**

   "x-forwarded-for":"10.250.0.3, 127.0.0.1",
   "x-forwarded-proto":"https",

**Steps to reproduce**

**Troubleshooting**

**Comment by c0d1ngm0nk3y** [comment]
But I think "x-forwarded-for" should contain an IP address and not a DNS name, right? But of course the IP address of the original request.

**Comment by strekm** [comment]
closing in favour of https://github.com/kyma-project/kyma/issues/15865
