### ISSUE TITLE
Remove Event-bus to Mesh Migration Script

### ISSUE THREAD

**Issue by anishj0shi** [kyma-project/kyma#7908]
The event-bus to mesh migration script was needed from kyma 1.10 --> 1.11.  Lets get rid of this script for 1.12. Also this script has protecode issues, so lets get remove it rather then maintaining it.

**AC**
- Remove the migration script from source.
- Cross verify, if already deleted via #7742

**Comment by sayanh** [comment]
Checklist:
- [ ] Verify migration component(go code, Dockerfile etc.) is removed
- [ ] Verify migration chart(pre-upgrade job) is removed
- [ ] Protecode scans are green
