### ISSUE TITLE
Make use of personservicekubernetes in official docs

### ISSUE THREAD

**Issue by derberg** [kyma-project/kyma#792]
**Description**

- take as much as possible from https://github.com/kyma-incubator/examples/tree/master/personservice to kyma/docs
- analyze current structure and propose how to fit it into our docs
- see what parts are rather explaining the feature before it is used -> decide if we take it into docs and then just use links in the scenario
- propose final structure and action points to leverage quality of our docs with content of this showcase
- screen shots should be replaced with CLI as much as possible
- decide what parts should go to examples repository and what to kyma/docs

it is not expected that this task ends up with personservice being moved from incubator to main kyma repo. 

**Reasons**

- https://github.com/kyma-incubator/examples/tree/master/personservice is great stuff that shows all kyma features. We need to take it over and help @akrausesap with future maintenance and then we also offer 🍕 and 🍺 
- at the moment our docs do not show things that this showcase shows

**Comment by kazydek** [comment]
I went through the whole example and added comments that are meant to simplify the steps and going through the whole scenario, in general. I have talked to @derberg and we agreed that the example will be moved to the `examples` repo, separate docs created from the main README.md doc, additional steps added, content proofread, and screenshots changed to CLI steps. Info on the end-to-end scenario will be added to the main README.md in the `kyma` repo in the Usage section. All of that will be done as part of a separate task.
