### ISSUE TITLE
E2E Tests for azure event-hub step. (Provisioning/De-provisioning)

### ISSUE THREAD

**Issue by anishj0shi** [kyma-project/kyma#7922]
We need to have an e2e test to validate a successful provisioning/de-provisioning Step

**Comment by radufa** [comment]
A first PR was created, which add the low level Eventing Kafka test. It should be started after provisioning of Kyma runtime on Azure and it should run on shouut cluster:
https://github.tools.sap/kyma/management-plane-docker/pull/5

**Comment by sayanh** [comment]
Following tests are impacted in the complete e2e-test for eventhub with regard to Compass:
- knative-eventing-kafka (already happening)
- compass-runtime-agent-external-solution (fine tuning needed)
- [e2e-provisioning-azure](https://github.com/kyma-project/kyma/blob/master/resources/compass/charts/kyma-environment-broker/templates/tests/e2e-provisioning-azure.yaml)
- [e2e-provisioning-gcp](https://github.com/kyma-project/kyma/blob/master/resources/compass/charts/kyma-environment-broker/templates/tests/e2e-provisioning-gcp.yaml)

**Comment by sayanh** [comment]
Update:
Enabling `compass-runtime-agent-external-solution` and/or `compass-runtime-agent-adapter-external-solution` is not possible at the moment due to the lack of the design with respect to Dex. This limits Kyma from talking to Compass when both are in different clusters.

Hence, this part is de-scoped from the issue.

**Comment by radufa** [comment]
The "knative-eventing-kafka" is started now on the E2E-Azure step of Spinnaker pipeline for compass-dev:
https://spinnaker.c4core.c.eu-nl-1.cloud.sap:9000/#/projects/kyma-management-plane/applications/kyma-management-plane/executions?pipeline=compass-dev
