### ISSUE TITLE
Cleanup old function revisions

### ISSUE THREAD

**Issue by michal-hudy** [kyma-project/kyma#7947]
**Description**

When lambda is not scaled to 0, the pods of old revisions are still deployed. As we are not supporting versioning, the old revisions shouldn't be deployed. Maybe this a matter of KNative Serving configuration https://github.com/knative/serving/blob/master/config/core/configmaps/gc.yaml, or old revisions needs to be removed in Function Controller.

In general:
 - Old revisions are removed as soon as new revision is served
 - If new revision is failing (is not served), then only older revisions than currently served are removed

**Reasons**

Resources management

**Attachments**

https://github.com/knative/serving/blob/master/config/core/configmaps/gc.yaml

**Comment by aerfio** [comment]
https://github.com/knative/serving/issues/2720

**Comment by michal-hudy** [comment]
The additional reason is when we remove old revision it will also remove k8s service, deployment, and other resources. Thanks to that we will have fewer resources in the cluster and other components that monitor resources will have a smaller load.
