### ISSUE TITLE
e2e-upgrade-test fails after retrying

### ISSUE THREAD

**Issue by franpog859** [kyma-project/kyma#7949]
**Description**

`e2e-upgrade-test` always fails on the second run. After the failure in the first run, there is a cleanup. In the `ApplicationOperatorUpgradeTest` there is a check of Event Service existence. After the cleanup, there is no Event Service anymore

**Expected result**

`e2e-upgrade-test` does not fail on the second run so there is no second run at all or the `ApplicationOperatorUpgradeTest` is modified

**Steps to reproduce**

We found it in [this log](https://status.build.kyma-project.io/view/gcs/kyma-prow-logs/logs/post-master-kyma-gke-upgrade/1247480248858054658). You can also rerun upgrade test and cross your fingers that it'll happen

**Comment by mszostok** [comment]
Gophers are only maintainers of the e2e upgrade test framework, so redirecting to Framefrog backlog :)

**Comment by janmedrek** [comment]
The issue did not occur since April, closing this issue.
