### ISSUE TITLE
Enable creation of AuthorizationPolicies out of the box

### ISSUE THREAD

**Issue by sayanh** [kyma-project/kyma#7955]
**Description**

Right now, the creation of AuthorizationPolicy is [disabled](https://github.com/kyma-project/kyma/blob/master/resources/application-connector/values.yaml#L11). In order to enable the security feature either one of the following steps can be done:
- Change the value [here](https://github.com/kyma-project/kyma/blob/master/resources/application-connector/values.yaml#L11) (Con: development environment will get very restricted)
- Pass `enabled` as an override to Kyma-installer (See https://github.com/kyma-incubator/compass/tree/master/docs/kyma-environment-broker)

**Reasons**

Security reasons

See https://github.com/kyma-project/kyma/issues/7240 for more details

**Comment by anishj0shi** [comment]
> Con: development environment will get very restricted

I'm fine with a restricted environment, because we do not support in-cluster event-dispatch. 
And If someone really needs to send events from a microservice inside the cluster. they should follow the application-connector flow. or we will support them in editing the existing authorization policy.

**Comment by anishj0shi** [comment]
We cannot enable istio Authorization Policy by default, as this causes unknown errors at the time of backup, We'll revisit this with Knative Open Policy at event-mesh level.
