### ISSUE TITLE
Service Binding Environment Variable Name

### ISSUE THREAD

**Issue by jcawley5** [kyma-project/kyma#8002]
When binding a service instance to a Lambda provided by a Compass API Package the Environment Variable Names are using a generated name, for example

SAMPLE_ORDER_API_MP_D091A576_3F21_4770_8FD0_454F460D7B95_GATEWAY_URL

which now forces me to change my code anytime the binding is recreated.  This assignment should be consistent to how it has worked before using a value of

GATEWAY_URL

**Comment by PK85** [comment]
Hello @jcawley5 

Right now Kyma has API-Packages where more than one API could be present. That means Service Instance == API-package and Service Binding needs to contain all URLs for those APIs.

What we will add in the future will be Service Binding Usage enhancement where user will be able to map env variables for example from:

occ-OCC-WEBSERVICES_1111-2222-3333-4444-5555-6666_GATWAY_URL -> GATEWAY_URL
And then Lambda will have always static environment variable key.

Cheers, PK

**Comment by PK85** [comment]
Closing, as we will use CMP System Broker and that issue will not exist.
