### ISSUE TITLE
Validate K8s 1.18 support

### ISSUE THREAD

**Issue by a-thaler** [kyma-project/kyma#8012]
**Description**
Test a kyma installation on K8s 1.18 and identify all potential problems. Create a follow up ticket with a list of action items to officially support k8s 1.18

**Reasons**
For the new backup strategy we need to have k8s 1.18 in place

**Attachments**
Found problems:
- installation artifacts: https://github.com/kyma-project/kyma/issues/8360
- prometheus crds: https://github.com/kyma-project/kyma/issues/8220
- service-catalog problems: https://github.com/kyma-project/kyma/issues/8218

**Comment by a-thaler** [comment]
Found https://github.com/kyma-project/kyma/issues/8218

**Comment by a-thaler** [comment]
And https://github.com/kyma-project/kyma/issues/8220

**Comment by kwiatekus** [comment]
No issues found in console UI ([besides service catalog](https://github.com/kyma-project/kyma/issues/8218))

**Comment by clebs** [comment]
Checked with all teams and no further issues were found on this topic.
