### ISSUE TITLE
Stabilize application-operator and application-connector tests

### ISSUE THREAD

**Issue by franpog859** [kyma-project/kyma#8019]
**Description**

Stabilize `application-operator` and `application-connector` tests on `nightly` and `weekly` clusters. The tests fail on about 10% of runs. It's not something critical because it does not happen on the PRs so it does not block the implementation process. It's important where it comes to the CI-force side, where the test owners are being pinged a lot

The issue probably concerns the clusters configuration. I assume so because it does not happen very often and does happen hardly ever on PRs

**Expected result**

`application-operator` and `application-connector` tests do not fail on `nightly` and `weekly` clusters

**Logs**
- https://status.build.kyma-project.io/view/gcs/kyma-prow-logs/logs/post-master-kyma-gke-upgrade/1253645692753154049
- https://status.build.kyma-project.io/view/gcs/kyma-prow-logs/logs/post-master-kyma-gke-central-connector/1253620022069170176

**Comment by franpog859** [comment]
@adamwalach said:
> Just wanted to mention that VMs used for weekly/nightly clusters are huge - we changed the configuration some time ago because it was even more unstable - right now on weekly we have 3 nodes with 12cpu/16GBram each.

I think it could help with the investigation process, thanks!

**Comment by franpog859** [comment]
Logs from CI:
- [1](https://status.build.kyma-project.io/view/gcs/kyma-prow-logs/logs/post-master-kyma-gke-central-connector/1265192557982257154)

**Comment by franpog859** [comment]
After [this PR](https://github.com/kyma-project/kyma/pull/8674) the tests should be more stable. I suggest to close this issue and reopen it whenever the problem occurs again. If so, please, add the link and the important log in the comment! 👋

**Comment by franpog859** [comment]
- operator failed with timeout - [logs](https://status.build.kyma-project.io/view/gcs/kyma-prow-logs/logs/post-master-kyma-gke-upgrade/1279029898043723776)

**Comment by franpog859** [comment]
Hey, @jakkab ! Feel free to add the logs with the errors in the comment. I'll help with fixing them

**Comment by koala7659** [comment]
The problem persists - [logs](https://status.build.kyma-project.io/view/gcs/kyma-prow-logs/pr-logs/pull/kyma-project_kyma/8995/pre-master-kyma-gke-upgrade/1283713706881978368)

**Comment by adamwalach** [comment]
post-master-kyma-gke-upgrade failed
https://status.build.kyma-project.io/view/gcs/kyma-prow-logs/logs/post-master-kyma-gke-upgrade/1287731447897001984

**Comment by adamwalach** [comment]
I checked logs in gcp (stackdriver) and it looks like this problem is quite common:
![Screenshot 2020-07-27 at 16 33 43](https://user-images.githubusercontent.com/8530211/88554815-3df52780-d027-11ea-8252-8e6fabde8de9.png)

**Comment by adamwalach** [comment]
Looks quite promising, there are no application-connector failures since the path was merged:
<img width="1312" alt="Screenshot 2020-07-29 at 10 36 56" src="https://user-images.githubusercontent.com/8530211/88777531-9b07ef00-d187-11ea-8224-aa691aa3ddf3.png">
