### ISSUE TITLE
Event sending fails if apiserver is unavailable

### ISSUE THREAD

**Issue by a-thaler** [kyma-project/kyma#8036]
**Description**
Assumed you have a working setup with a an application paired to your kyma runtime, sending events to the external facing event-service using client certificates.

When the apiserver is not reachable (as it is simply failing or scaling up/down or whatever) the event sending seems to be broken. It returns a 500 with a message like "TLS handshake timeout".
That should not be the case as the runtime part should not be affected by apiserver downtimes.

**Expected result**
Full e2e flow works when apiserver is down to assure operational continuity of the deployed applications

**Actual result**
E2e flow is broken by not being able to submit new events

**Steps to reproduce**
Hard to reproduce, I talked to the team managing the kubernetes environment to cause a downtime

**Troubleshooting**

**Comment by janmedrek** [comment]
I believe the issue is not only narrowed down to Application Connector only. We are validating incoming calls with certificates that are stored in cluster secrets, this is done by Istio.

Perhaps @piotrmsc can elaborate on that, is there any way to omit apiserver in the flow?

**Comment by piotrmsc** [comment]
@janmedrek it depends on how the event service works, if it applies custom resource then apiserver availability has impact. Can you link any docs how the flow works from external app pov? Then I will be able to tell bit more

**Comment by muralov** [comment]
@janmedrek are you working on this issue? I would like to take it unless you are working on it. If you wish to do it yourself, no problem. I have asked as it is marked stale.

**Comment by muralov** [comment]
as discussed with @janmedrek I have taken this issue and currently working on it.

**Comment by muralov** [comment]
Currently, caching tries to retrieve the resources (Application CRs) through KubeApi if it is unavailable in the cache. Not responding KubeApi is still problematic. However, better solution is to watch the resources and reactively fill them in a locale cache store where Application Connectivity Validator only reads the resources from the cache. This approach uses controller (w/ control loop) where data eventually be filled in the cache. I think, this makes the validator robuster.

After talking to @janmedrek I have drawn the following solution design: 
![image](https://user-images.githubusercontent.com/13185122/93132856-9fa44a80-f6d6-11ea-949d-51b1d24bfde4.png)

Alternatively, the cache store could remote cache like [Memcached](https://memcached.org/) if the overall resources size is higher.

**Comment by akgalwas** [comment]
@muralov The approach with controller is a good idea. As it comes to the cache I think that simple memory cache we used is more than enough. The cache in Validator contains one key (App name) and the value is an array (with one element I suppose).

**Comment by muralov** [comment]
@akgalwas regarding the cache store, yes, simple in-memory cache is meant in the solution design above. Sure, let's keep it simple.

**Comment by muralov** [comment]
I am about to create PR for the issue.
