### ISSUE TITLE
Multitenancy 

### ISSUE THREAD

**Issue by ektajhasapcom** [kyma-project/kyma#804]
Hi Team,

Could you please help me to understand how we can achieve multi tenancy using Kyma?

If we want to migrate our existing cloud applications we need to support multi tenancy as they all supports it.

Thanks & Regards,
Ekta Jha

**Comment by pbochynski** [comment]
There is no special support for multi-tenancy in Kyma. It is up to application developer to decide what pattern to use. You can have multitenancy on infrastructure layer (kubernetes cluster per customer), or on application layer (single instance but separate storage for customers).
