### ISSUE TITLE
Support for configurable extra script in fluent-bit chart

### ISSUE THREAD

**Issue by a-thaler** [kyma-project/kyma#8055]
**Description**
The logging chart provides a convenient option to bring in extra fluent-bit config via installer overrides. The option is called "conf.extra".

Unfortunately, not all configuration can be easily realized with that. There are border cases where a fluentbit plugin requires an additional file, like the "lua" plugin requiring a file containing the lua script.

Please introduce a way to provide an additional script/file which is not included as fluentbit config file but can be referenced in the conf.extra section

**Reasons**

Make it possible to have 3party logging integrations via installer overrides only

**Attachments**

**Comment by a-thaler** [comment]
Please describe how the final solution looks like. What overrides are now supported?

**Comment by rakesh-garimella** [comment]
We have added `script` under `conf` where users can pass their lua script as installer-overrides. However to be able to use the script one must set `script` under `FILTER` to `script.lua`
