### ISSUE TITLE
Enrich logs for 3party system with the cluster name

### ISSUE THREAD

**Issue by a-thaler** [kyma-project/kyma#8074]
**Description**
When having multiple kyma cluster pushing logs into a single system like elasticsearch, you need a way to differentiate the logs per cluster. A generic solution re-usable for multiple system is to introduce a new record keeping the cluster_name, configurable via installer overwrite.
So  

**Reasons**
Simple integration of 3party logging system via installer overrides only

**Attachments**

**Comment by a-thaler** [comment]
Please describe the realized solution. How can I enrich my logs with the cluster name?

**Comment by rakesh-garimella** [comment]
Now we have added installer overrides `record_modifier` where the user can enable it and set `key` and `value` for idetification. When the override is enabled the fluent-bit config is set appropriatelu
