### ISSUE TITLE
Tracing documentation improvements

### ISSUE THREAD

**Issue by bszwarc** [kyma-project/kyma#8075]
This is a follow-up task for https://github.com/kyma-project/kyma/issues/7690

What needs to be done:
- Improve Tracing chart documentation (former Jaeger chart): https://deploy-preview-8035--kyma-project-docs-preview.netlify.app/components/tracing/#configuration-jaeger-chart
- Describe the profiles - is the production profile still applicable? I couldn't find any info about it here: https://github.com/kyma-project/kyma/blob/master/installation/resources/installer-config-production.yaml.tpl
- Create a tutorial out of this: https://kyma-project.io/docs/1.13/components/tracing/#details-compare-traces (check if it's still valid)
- Update/simplify the architecture diagram: https://kyma-project.io/docs/1.13/components/tracing/#architecture-architecture (add visible steps)
- https://kyma-project.io/docs/1.13/components/tracing/#details-tracing - this should be renamed to make it a bit more meaningful, we can still have it as Jaeger as it describes the tool.
-

**Comment by a-thaler** [comment]
I have a first version of a new arch diagram. Somehow I cannot upload it here, please just contact me when docu gets improved

**Comment by bszwarc** [comment]
@a-thaler , can you send me the diagram? :D

**Comment by NHingerl** [comment]
I believe all items will be addressed in the K2.0 docu update:

- tracing chart replaced by link to values.yaml
- comparing traces is jaeger docu, not Kyma docu, thus not part of our docs
- profiles mentioned in Install Kyma doc and in Istio docs. not mentioned in tracing docs though.
- tracing architecture diagram is simplified and got numbered steps
- not sure what exactly should be made more meaningful in details-tracing, but generally we got rid of all the "details" docs and updated them in more meaningful ways.
