### ISSUE TITLE
add headerTitle and headerLogoUrl to be configurable in helm chart

### ISSUE THREAD

**Issue by hardl** [kyma-project/kyma#812]
so it can be customized during installation

properties should be added here: https://github.com/kyma-project/kyma/blob/master/resources/core/charts/console/templates/configmap.yaml

default values added to the cluster object here: https://github.com/kyma-project/kyma/blob/master/resources/core/charts/console/values.yaml

**Comment by kwiatekus** [comment]
How to review:
connect to a kyma via kubectl
```
kc delete configmap console-config -n kyma-system

kc apply -f my-configmap.yaml
```
