### ISSUE TITLE
Virtualservice generated by APIRule has warnings in kiali

### ISSUE THREAD

**Issue by a-thaler** [kyma-project/kyma#8135]
**Description**
Rafter and the serverless component are using the new APIRule resource. The generated VirtualService resource is causing a warning in kiali as for the single route destination a weight of 0 is assigned.

See screenshot:
<img width="660" alt="Screenshot 2020-04-21 at 20 33 14" src="https://user-images.githubusercontent.com/7479371/79900983-627daa00-840f-11ea-85e7-96f5833fe7b8.png">

**Expected result**
Kiali is not reporting a warning for the generated resources

**Actual result**
There are warnings indicating a misconfiguration

**Steps to reproduce**
Enable Kiali from kyma master branch and check the warnings for istio configs

**Troubleshooting**

**Comment by piotrmsc** [comment]
We can either remove this property from VS as it's not required or set it to 100.

Reference https://istio.io/docs/reference/config/networking/virtual-service/#HTTPRouteDestination
