### ISSUE TITLE
regular OOMKilled errors for istio-proxy containers of istio-ingressgateway pods under message load

### ISSUE THREAD

**Issue by eric-sap** [kyma-project/kyma#8162]
**Description**

When sending large quantities of events to the istio-ingressgateway, the pods regularly fail with an OOMKilled message on the istio-proxy container.  This is more frequent when sending at high speed (40+ msg/sec) but also happens a nontrivial amount of the time on an otherwise idle cluster with message rates as low as 3/sec and using only two sending threads.

Attached is a typical log of these failures over a 15-hour period.
[istio-ingressgateway_OOMKilled_info.txt](https://github.com/kyma-project/kyma/files/4518333/istio-ingressgateway_OOMKilled_info.txt)

kubectl version (azure):
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.11", GitCommit:"d94a81c724ea8e1ccc9002d89b7fe81d58f89ede", GitTreeState:"clean", BuildDate:"2020-03-12T21:08:59Z", GoVersion:"go1.12.17", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.10", GitCommit:"150f36044fe31bee3891b5a3fae69c17237e022c", GitTreeState:"clean", BuildDate:"2020-02-21T10:02:50Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}

kyma version:
Kyma CLI version: 1.11.1
Kyma cluster version: 1.11.1

The message sizes in these tests are very small (under 1Kb)

**Expected result**

No (or very few) gateway connection failures associated with OOM situations on the istio-proxy containers, regardless of incoming message rate.

**Actual result**

Most groups of 500-3000 test messages at various speeds pass 100%, but a sizable number (120/480 in a recent run) have gateway connection failures in groups of 5-25  that correlate with istio-proxy OOMKilled messages.  There are very occasional (1 out of every 10000 messages or so) gateway connection failures that do not correspond to any OOMKilled messages directly, but the groups of failures always do.

**Steps to reproduce**

Any method of sending messages should reproduce this, though it may take some time.  The OOMKilled events happen slightly less often than once an hour with the Kyma production config.

This bash script (if run from a cluster pod with, e.g. the tutum/curl image) is enough to trigger an OOMKilled event if run repeatedly (the curl %{http_code} will output "000" when a gateway connection failure occurs).  Tweak it for whichever cluster/certificate/event you are using:

```
sendMessage() {
  curlcmd=(-H "Content-Type: application/json" -H "cache-control: no-cache" -H "ce-id: 1234567" -H "ce-source: commerce" -H "ce-specversion: 1.0" -H "ce-type: product.created.v1" -d @- "https://gateway.dev3.agogos.ml/commerce/events" --cert certificate.pem -k --write-out %{http_code}. --silent)
  echo '{"productName": "cmt product name", "productDescription": "cmt product description"}' | curl "${curlcmd[@]}"
}

sendManyMessages() {
  for i in $(seq ${1})
  do
    sendMessage
  done
}

for i in $(seq 8)
do
  sendManyMessages 1000 &
done
wait
```

**Troubleshooting**

We have not changed the istio-proxy container memory settings directly as this is not something I believe a customer would be doing.  We are currently running with many different message rates and patterns to attempt to determine what causes the issue but so for it very much seems to be more of a "real time the pods are up while processing any message load" and less of a matter of the message count or rate.

**Comment by pbochynski** [comment]
Did you use a production profile for the cluster? 
https://kyma-project.io/docs/components/service-mesh/#configuration-service-mesh-production-profile-use-the-production-profile

**Comment by eric-sap** [comment]
The production profile was part of the requirements for this test, yes.  Unfortunately I cannot directly confirm the exact values at the moment as that particular cluster no longer exists.

**Comment by colunira** [comment]
We cannot provide a profile for every test case, the cluster operator should be responsible for adjusting the resources limits.
