### ISSUE TITLE
Refactor cluster-users tests

### ISSUE THREAD

**Issue by Demonsthere** [kyma-project/kyma#8168]
**Description**
- [x] Move the tests code (`sar-test.sh`) to the chart as a file, and mount it into the tests -> https://github.com/kyma-project/kyma/pull/8393
- [x] Use helm templating to insert required values in the test -> https://github.com/kyma-project/kyma/pull/8393
- [ ] Simplify the structure of the tests -> ToDo

**Reasons**
Currently, the logic for the tests is somehow split between the chart and the test code that is inside the `tests` directory. This causes each modification to be duplicated or reflected in those two places. We could unify that by moving the tests code to a configmap that is mounted in the tests pod

**Attachments**
- Followup to #8160

**Comment by strekm** [comment]
closing in favour of https://github.com/kyma-project/kyma/issues/11643
