### ISSUE TITLE
natss seems to ignore max_inflight setting for subscriptions

### ISSUE THREAD

**Issue by k15r** [kyma-project/kyma#8172]
**Description**

the `max_inflight` settings on a natss-subscription would allow to have multiple events in process on the subscription without waiting for an `ACK`

By default our natss subscriptions are set to `max_inflight=1024`. This should allow the subscriber to receive multiple events before responding to those messages. 
According to customer reports this is not the case and it behaves as if `max_inflight` would be set to `1`.

**Expected result**

- multiple events are sent to the subscriber

**Actual result**

- one event gets sent to the subscriber. This one needs to be `ACK`ed for the next to be sent

**Steps to reproduce**

**Troubleshooting**

**Comment by anishj0shi** [comment]
Nats-dispatcher related issues have to be raised in upstream organisation, knative/eventing-contrib.
