### ISSUE TITLE
APP Broker after restart is not triggering the interrupted provisioning/deprovisioning

### ISSUE THREAD

**Issue by mszostok** [kyma-project/kyma#8180]
**Description**

The App Broker after restart is not triggering the interrupted provisioning/deprovisioning. To fix that we can introduce similar process as already implemented in KEB, see: 
https://github.com/kyma-incubator/compass/blob/22072888dbd4e6774a28c282a9d7f716aaacb400/components/kyma-environment-broker/cmd/broker/main.go#L252-L255

**AC**
- App Broker retriggers not finished operations after pod restart

**Comment by PK85** [comment]
When done, patch kyma 1.12 and contact @adamwalach
