### ISSUE TITLE
Initial run of performance tests on event-mesh

### ISSUE THREAD

**Issue by sayanh** [kyma-project/kyma#8181]
**Description**

The objective is to execute a basic scenario of an event-flow from an application to a subscriber. And it must be executed at stress.

The load should be generated using Vegeta or Gatling.

**AC**
- Document the following:
  - Define Basic Target Environment Setup: like cluster configuration, etc
  - How to run the stress tests?
  - What kind of load can be generated using the tool? E.g. 200 events per minute
  - How much parallelism is achievable from the tool?
  - Finalize few setups to run these tests. E.g. 200 events per minute with concurrency: 5
  - Validate the results as in - are they sufficient to go forward in the epic?

**Comment by sayanh** [comment]
I took the following approach:
- The send-receive pod generates load and hits event-service internal cluster.local endpoint to send an event
- The event flows through the event mesh and ends up triggering a subscriber
- The subscriber adds a timestamp(as a header) to the event and sends it to the send-receive pod for aggregation in a synchronous call
- The send-receive pod gets the event in the aggregate endpoint
- Once the load generation is done, the aggregation layer of the send-receive pod is signaled
- Once receiving the done signal, the aggregation layer waits for a timeout(to let more and more events reach the sink) and when the timeout expires, it generates an aggregation report

Diagram: ![Uploading load-test-set-up.png…]()
Code: https://github.tools.sap/skydivingtunas/load-test-suite

**Take-aways:**
- Following metrics were calculated:
  - Total E2E latency from an event-source to a subscriber
  - Total events received(within a configurable timeout) in the sink
  - Parallelism is achieved using workers
  - Multiple scenarios can be executed by changing the env variables for load generator
- Vegeta is a nice tool to work with because
  - It is in the go ecosystem
  - Knative uses it which has solved a lot of problems already
- [Initial setup](https://github.tools.sap/skydivingtunas/load-test-suite/blob/test-run-with-vegeta/README.md) has a lot of manual steps as it involves SKR creation and application binding

- Following **tunings** can be done in the set-up:
  - The subscriber can send requests to the aggregator in an async fashion. This leads to a non-blocking call for the dispatcher(in turn event-mesh) to subscriber.
    - Con: Go routines may be light but are not free, so keep in mind that shouldn't turn out to be an overhead for the subscriber in processing the events which in turn can pull down the performance of the dispatcher
  - There is another alternative approach.
    - The subscriber can store the events in-memory from the dispatcher and return 200
    - Once the load generator is done sending events, it can then ask for the events from the subscriber and then aggregate followed by report generation.
    - Pros:
      - Faster(as the subscriber just stores in-memory and returns) and as it is a non-blocking call to the aggregator, it leads to less stress on the dispatcher IMO.
    - Cons:
      - The subscriber gets fatter with in-memory events and can result in being overhead of processing events from dispatcher.
      - At the end of the day, the subscriber should not be the bottleneck in load test experiments done on the event-mesh.

Further know-how needed before implementation:
- Aggregation layer needs a proper design
  - How metrics from Vegeta can be used to correlate metrics calculated end to end?
  - Exact metrics that need to be measured using Vegeta's [result channel](https://github.com/tsenart/vegeta/blob/master/lib/results.go#L26)?
  - How the metrics should be plotted? E.g. gnuplot, vegeta's plotting library?

**Comment by radufa** [comment]
Great! 
The test could also check the "event-id" so that if under load some events are lost, a more deeper analysis based on KN log files could be done.
In the first approach , the subscriber could be horizontally scaled to not slow down the dispatcher. Also having different "processes" for generator and aggregator, to not disturb each other, is the way to go IMO.
The second approach could be more complex if the subscriber must be scaled out...

**Comment by radufa** [comment]
Looking into the code, usually the "done" channel is the first parameter in the function call:
https://github.tools.sap/skydivingtunas/load-test-suite/blob/test-run-with-vegeta/cmd/send-receive/main.go#L42

**Comment by sayanh** [comment]
> The test could also check the "event-id" so that if under load some events are lost, a more deeper analysis based on KN log files could be done.

Sure, we could. We may wanna think about total events sent vs received(this is already happening in the code) and then analyze. Cause the number of events will be insane and debugging based on ids will not scale IMO.
