### ISSUE TITLE
Automate execution of performance tests

### ISSUE THREAD

**Issue by sayanh** [kyma-project/kyma#8182]
**Description**

Write scripts needed to do the following:

- Run the (containerized)tests inside the Kyma cluster for a start
- Run the scenarios designed earlier
- Get the results from the tool
- Attention should be given to Prometheus which might need a beefy PV because of the load
- Bonus: Repeat the above by sending events from outside the Kyma cluster

**AC**
- Have an automated and repeatable workflow of running the tests
- Results(dashboards/plots) of the tests can be accessed at any point in time

**Comment by k15r** [comment]
New eventing solution will require a new performance setup, closing for now
