### ISSUE TITLE
Understand the results of the performance tests

### ISSUE THREAD

**Issue by sayanh** [kyma-project/kyma#8183]
**Description**

Investigate the results of the performance tests.
Measure the following for the system:
- Throughput
- Latency
- Are we losing events? How many in %? Where are we losing? What happens to them?
- Utilization
  - Memory
  - CPU
  - Network
- Restarts of pods

**AC**
- Document the rationale behind the observations
- Create further issues to fix the problems found here

**Comment by k15r** [comment]
Closing for now. Current development to migrate towards updated eventing implementation will require new performance tests.
