### ISSUE TITLE
Use CLI in documentation for provision, installation and testing

### ISSUE THREAD

**Issue by a-thaler** [kyma-project/kyma#8190]
**Description**
As the CLI is in use for quite a while we should switch the official documentation to use the CLI for all common parts, mainly

- provision
- install
- testing

**Reasons**
Get rid of scripts and have a unified user experience

**Attachments**
Documents to touch at least:
- https://kyma-project.io/docs/#installation-use-your-own-kyma-installer-image
- https://kyma-project.io/docs/#details-testing-kyma
- https://kyma-project.io/docs/#installation-install-kyma-on-a-cluster
- https://kyma-project.io/docs/#installation-install-kyma-with-your-own-domain
- https://kyma-project.io/docs/#installation-reinstall-kyma not valid, make clear that you need to create a new cluster

For testing, please document as well that a kubeconfig not taken from kyma console is required, see kyma-project/cli#320

**Comment by bszwarc** [comment]
We should also think of having CLI as

**Comment by bszwarc** [comment]
Sorry for closing by mistake :D 
I just wanted to add that we should have some documentation about the CLI in the official docs.
