### ISSUE TITLE
Remove backup component

### ISSUE THREAD

**Issue by a-thaler** [kyma-project/kyma#8199]
**Description**
Remove the backup and backup-init component

Including
- resources folders
- e2e backup job + component related parts
- velero plugins component and jobs
- documentation

**Reasons**
Velero will be not supported anymore as integrated solution, so we must remove the related sources

**Attachments**

**Comment by suleymanakbas91** [comment]
I created one PR on test-infra and one on kyma to delete all backup related pieces. PR on kyma also introduces a simple document to explain how to install Velero and take a backup.
