### ISSUE TITLE
Manual on how to backup a cluster using velero

### ISSUE THREAD

**Issue by a-thaler** [kyma-project/kyma#8200]
**Description**
Velero is a nice tool and it has advantages as safety net. Whatever happens, you could restore single resource easily in a manual way. Just the automatic restore of a full kyma stack sounds unreasonable for now.
So let's have a guide on how to backup a cluster in a manual way in order to restore particular resources later.

Actions:
- have a step-by-step guide on
  - how to install and configure velero on a kyma cluster
  - how to create a manual backup

For sure the documentation can point to velero documentation if existent instead of writing it from scratch as long as it works on a typical kyma cluster.

**Reasons**

**Attachments**

**Comment by suleymanakbas91** [comment]
#8261 introduces a simple document to explain how to install Velero and take a backup.
