### ISSUE TITLE
Injecting pod labels in Function CR

### ISSUE THREAD

**Issue by michal-hudy** [kyma-project/kyma#8203]
**Description**

Add the ability to define Pod labels in Function CR. I'm not sure if we should support full PodSpec definition, for now maybe not - some investigation is needed. In UI it should be visible in the configuration as something advanced, by default Function CR labels should be propagated. Internal labels like `function-name`, `uuid` still must be propagated to Pod and override user-provided values.

If `.spec.template.metadata.labels` approach will be chosen, then resources management should also be moved to `.spec.template`... and old resourced deprecated (not removed).

**Reasons**

Some functionalities like Service Bindings are based on Pod labels that are injected. Currently, UsageKind points to Knative Serving, because it is not possible to define labels for Pods on Function CR. It is not good as we need to wait for Serving resource that can be replaced in the future or even removed in some cases.

**Comment by kazydek** [comment]
@magicmatatjahu - and pls update the [Function CR](https://kyma-project.io/docs/master/components/serverless/#custom-resource-custom-resource) definition in docs :)
