### ISSUE TITLE
Compass installation timeout caused by bugged KEB charts

### ISSUE THREAD

**Issue by franpog859** [kyma-project/kyma#8212]
**Description**

Installation timeout occurres while installing Compass in Kyma + Compass mode. The timout is caused by `"TBD"` values in KEB secrets in the charts

There is a workaround for installing Kyma + Compass - you can manually change the KEB deployment and set `replicas` to `0` (remove the KEB). There is no workaround for it in the `…kyma-gke-compass-provisioner-tests` job though. It fails everytime because of this issue

**Expected result**

Installation does not fail due to Compass installation timeout in Kyma + Compass mode

**Actual result**

It does fail

**Steps to reproduce**

Run `/test pre-master-kyma-gke-compass-provisioner-tests` on your PR and dive into the created cluster to see the failing installation or install Kyma + Compass on your own cluster/ minikube

**Comment by PK85** [comment]
I guess it's already fixed
