### ISSUE TITLE
Helm-broker and other service management components support for k8s 1.18

### ISSUE THREAD

**Issue by a-thaler** [kyma-project/kyma#8218]
**Description**
Helm-broker seems to not work with k8s1.18.
When configuring an addon, the status gets green but the addons will not get listed in the service-catalog. Seeing the logs of the helm-broker controller indicates a problem with K.1.18

```
{"level":"warning","log":{"message":"Creation of namespaced-broker for namespace [mocks] results in error: [ServiceBroker.servicecatalog.k8s.io \"helm-broker\" is invalid: metadata.managedFields.fieldsType: Invalid value: \"\": must be `FieldsV1`]. AlreadyExist errors will be ignored.","service":"broker-facade","time":"2020-04-24T09:15:33.538Z"}}
```

Most probably the go client needs to be updated in the service-catalog, see also https://github.com/kubedb/issues/issues/739

**Reasons**
Always try to support latest version

**AC**
- all service management components works with K8S 1.18

**Comment by mszostok** [comment]
PR to support k8s 1.18 on Service Catalog: https://github.com/kubernetes-sigs/service-catalog/pull/2796

**Comment by polskikiel** [comment]
Created follow-up story: #8779
