### ISSUE TITLE
On Apiserver pod deletion or crash the parent replicaset cannot setup the pod again

### ISSUE THREAD

**Issue by texhnolyze** [kyma-project/kyma#8232]
First off I wanna say I think kyma is a great project and I really have been enjoying working with it. So thanks for that guys :+1: 

**Description**
In a test environment we are running an old 1.5 kyma instance (so the issue might not apply anymore, but I'm not sure), which was installed manually and is running on azure.
I was updating kyma certificates manually (`kyma-gateway-certs`, `application-connector-certs` and lastly `apiserver-proxy-tls-cert`).
After the update the access the subdmains like e.g. "dex.domain", "console.domain" was working again, but in the web console ui there were errors and no cluster information was loading and I found out that the "apiserver.domain" url was still using the old certificates. 

So I assumed that the `apiserver-proxy` deployment/pods were not automatically updated on the `apiserver-proxy-tls-cert` secret change. 
So not thinking it through I ran `kubectl delete pod -n kyma-system apiserver-proxy-75748cbc97-2g2gg`

**Expected result**
I was expecting the pods to be created again using the updated `apiserver-proxy-tls-cert` secret as volume.

**Actual result**
The pods are not being created again and I do not even see them in the list as required when running `kubectl get pods --all-namespaces`.
Looking at the replicaset I get this:
```
kubectl describe replicaset -n kyma-system apiserver-proxy-75748cbc97
Name:           apiserver-proxy-75748cbc97
Namespace:      kyma-system
Selector:       app=apiserver-proxy,pod-template-hash=75748cbc97,tlsSecret=ingress-tls-cert
Labels:         app=apiserver-proxy
                pod-template-hash=75748cbc97
                tlsSecret=ingress-tls-cert
Annotations:    deployment.kubernetes.io/desired-replicas: 1
                deployment.kubernetes.io/max-replicas: 2
                deployment.kubernetes.io/revision: 3
                deployment.kubernetes.io/revision-history: 1
Controlled By:  Deployment/apiserver-proxy
Replicas:       0 current / 1 desired
Pods Status:    0 Running / 0 Waiting / 0 Succeeded / 0 Failed
Pod Template:
  Labels:           app=apiserver-proxy
                    pod-template-hash=75748cbc97
                    tlsSecret=ingress-tls-cert
  Annotations:      sidecar.istio.io/inject: true
                    traffic.sidecar.istio.io/excludeInboundPorts: 8443
  Service Account:  apiserver-proxy
  Containers:
   auth-proxy:
    Image:       eu.gcr.io/kyma-project/apiserver-proxy:1.3.0
    Ports:       8444/TCP, 9443/TCP
    Host Ports:  0/TCP, 0/TCP
    Args:
      --insecure-listen-address=0.0.0.0:8444
      --secure-listen-address=0.0.0.0:9443
      --tls-cert-file=/etc/tls-cert/tls.crt
      --tls-private-key-file=/etc/tls-cert/tls.key
      --upstream=https://kubernetes.default
      --logtostderr=true
      --v=10
      --oidc-issuer=https://dex.8a99e5f95b85429da378.westeurope.aksapp.io
      --oidc-clientID=kyma-client
      --oidc-ca-file=/etc/dex-tls-cert/tls.crt
      --cors-allow-origin=*
      --cors-allow-headers=authorization,content-type
      --cors-allow-methods=GET,POST,PUT,DELETE
    Limits:
      memory:  256Mi
    Requests:
      memory:     128Mi
    Environment:  <none>
    Mounts:
      /etc/dex-tls-cert/ from dex-tls-cert (rw)
      /etc/tls-cert/ from tls-cert (rw)
  Volumes:
   dex-tls-cert:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  ingress-tls-cert
    Optional:    false
   tls-cert:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  apiserver-proxy-tls-cert
    Optional:    false
Events:
  Type     Reason        Age                    From                   Message
  ----     ------        ----                   ----                   -------
  Warning  FailedCreate  2m15s (x3 over 5h18m)  replicaset-controller  Error creating: the server was unable to return a response in the time allotted, but may still be processing the request (post pods)
```
Given my limited understanding of kubernetes internals I assume the reason for this is, because the `apiserver-proxy` is used to access the apiserver, which is required to create its own pods again.
I'm also now unable to create any new pods via deployments and am unable to run `kubectl exec` etc.

Is my understanding of this correct? 
If so would that mean, that if the `apiserver-proxy` randomly crashes, we're in a deadlock, because it cannot "recreate" itself?
Is there any way for me to resolve my issue?

**Steps to reproduce**
On a version 1.5 kyma cluster delete the pods of the `apiserver-proxy` deployment in namespace `kyma-system`.
The pods will not be recreated successfully by the replicaset.

This is somewhat related to: https://github.com/kyma-project/kyma/issues/5745, which has fixed the issue leading to me producing this issue

**Comment by kubadz** [comment]
As you can see in [PR](https://github.com/kyma-project/kyma/pull/6095) linked to [#5745](https://github.com/kyma-project/kyma/issues/5745) the automatic reload of certificates in apiserver-proxy was merged on 24 Oct 2019, whereas the [release 1.5](https://github.com/kyma-project/kyma/tree/release-1.5) includes commits before 6 Sep 2019. So you should restart the `apiserver-proxy` manually, what you actually did. 

Answering to your question regarding `apiserver-proxy`. It only serves as a proxy to k8s apiserver for external services, that are not installed on the k8s cluster. It does mean that you won't be able to use kubectl with the kubeconfig fetched from the Console UI, when `apiserver-proxy` is down, but all in-cluster communication with k8s apiserver will work the same (especially controllers that are built into the k8s like `replicaset-controller`).

The problem you have doesn't look as something related to Kyma, but looks like something related directly to k8s. TBH I didn't see a similar problem before, but the message you have in `Events` suggest that there are some problems in connection between `replicaset-controller` and k8s apiserver or maybe (just guessing) that the apiserver is too busy to respond in a given timeout.
> Error creating: the server was unable to return a response in the time allotted, but may still be processing the request (post pods)

One thing that looks really weird to me, is that deleting a pod killed it before the next pod was created. As a deployment for `apiserver-proxy` exists, normally it would wait for the new pod to be up, before scaling down to 0 the old replicaset, what would remove the old apiserver-proxy pod. You should be able to see a more detailed description of what happened in `Event` section of `apiserver-proxy` deployment. You can provide the output here, so I can help you with debugging that.
```
kubectl describe deployment apiserver-proxy -n kyma-system
```

**Comment by texhnolyze** [comment]
Sorry for the late reply, I was on holidays last week. 
Thanks for the clear answer. In that case I do not undestand the issue at all. I had looked at the deployment before, but did not find anything in the `Event` section of the `apiserver-proxy` deployment:

```
kubectl describe deployment apiserver-proxy -n kyma-system

Use alias stupid: kddep apiserver-proxy -n kyma-system
Name:                   apiserver-proxy
Namespace:              kyma-system
CreationTimestamp:      Mon, 05 Aug 2019 17:57:02 +0200
Labels:                 app=apiserver-proxy
                        tlsSecret=ingress-tls-cert
Annotations:            deployment.kubernetes.io/revision: 3
Selector:               app=apiserver-proxy,tlsSecret=ingress-tls-cert
Replicas:               1 desired | 0 updated | 0 total | 0 available | 1 unavailable
StrategyType:           RollingUpdate
MinReadySeconds:        0
RollingUpdateStrategy:  1 max unavailable, 1 max surge
Pod Template:
  Labels:           app=apiserver-proxy
                    tlsSecret=ingress-tls-cert
  Annotations:      sidecar.istio.io/inject: true
                    traffic.sidecar.istio.io/excludeInboundPorts: 8443
  Service Account:  apiserver-proxy
  Containers:
   auth-proxy:
    Image:       eu.gcr.io/kyma-project/apiserver-proxy:1.3.0
    Ports:       8444/TCP, 9443/TCP
    Host Ports:  0/TCP, 0/TCP
    Args:
      --insecure-listen-address=0.0.0.0:8444
      --secure-listen-address=0.0.0.0:9443
      --tls-cert-file=/etc/tls-cert/tls.crt
      --tls-private-key-file=/etc/tls-cert/tls.key
      --upstream=https://kubernetes.default
      --logtostderr=true
      --v=10
      --oidc-issuer=https://dex.8a99e5f95b85429da378.westeurope.aksapp.io
      --oidc-clientID=kyma-client
      --oidc-ca-file=/etc/dex-tls-cert/tls.crt
      --cors-allow-origin=*
      --cors-allow-headers=authorization,content-type
      --cors-allow-methods=GET,POST,PUT,DELETE
    Limits:
      memory:  256Mi
    Requests:
      memory:     128Mi
    Environment:  <none>
    Mounts:
      /etc/dex-tls-cert/ from dex-tls-cert (rw)
      /etc/tls-cert/ from tls-cert (rw)
  Volumes:
   dex-tls-cert:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  ingress-tls-cert
    Optional:    false
   tls-cert:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  apiserver-proxy-tls-cert
    Optional:    false
Conditions:
  Type           Status  Reason
  ----           ------  ------
  Available      True    MinimumReplicasAvailable
OldReplicaSets:  apiserver-proxy-75748cbc97 (0/1 replicas created)
NewReplicaSet:   <none>
Events:          <none>
```

**Comment by Demonsthere** [comment]
Is this still valid, or can we close this?

**Comment by strekm** [comment]
closing this one due to inactivity. Be aware that apiserver-proxy componenet soon will be removed. please feel free to reopen if needed.
