### ISSUE TITLE
Proper documentation for Kiali component

### ISSUE THREAD

**Issue by a-thaler** [kyma-project/kyma#8244]
**Description**
At the moment Kiali is still documented as a sub-chart of istio/service-mesh based on outdated documentation.
https://kyma-project.io/docs/components/service-mesh/#configuration-kiali-chart
and https://kyma-project.io/docs/components/service-mesh/#overview-overview

Please introduce documentation for the standalone component having the typical sections like Overview, Architecture (with diagram), Configuration

Remove the old documentation

**Reasons**

**Attachments**

**Comment by clebs** [comment]
Kiali documentation has been moved to a separate component and expanded with the sections a component usually has.

**Comment by clebs** [comment]
The kiali documentation has been changed as follows:
- Created a new component section exclusive for Kiali.
- Added the typical sections for a component documentation (Overview, Architecture, Details, ...)
- Expanded the documentation to add more information on the sections in the previous point.
- Added diagrams for the architecture.
- All mentions of kiali on the istio documentation have been removed.
