### ISSUE TITLE
Monitoring tests fail because of misconfigured knative-serving pod monitor

### ISSUE THREAD

**Issue by aerfio** [kyma-project/kyma#8247]
**Description**

As in title, something is wrong with it causing monitoring tests to fail. We should either fix it or disable it for now

**Expected result**
Monitoring tests pass

**Actual result**
They do not 😞

**Comment by michal-hudy** [comment]
We should definitely fix it. As a temporary solution it has been disabled.

**Comment by michal-hudy** [comment]
I would close it, as we will not use knative serving that much, but as @anishj0shi team is still using it then I'm leaving that decision to him.
