### ISSUE TITLE
Remove logic that detect if SCI is enabled in UI API Acceptance Tests

### ISSUE THREAD

**Issue by michal-hudy** [kyma-project/kyma#825]
**Description**

Currently UI API Acceptance Tests skip tests execution when SCI is enabled. We provided such logic, because stability checker works on cluster with SCI enabled. When dynamic password generation will be implemented (#197) and stability checker will work on cluster without SCI then such logic will be useless and we should remove it.

To remove:
 - Injecting DEX configuration to tests: https://github.com/kyma-project/kyma/blob/master/resources/core/templates/tests/test-ui-api-acceptance.yaml
 - Logic responsible for reading DEX configuration and detecting if SCI is enabled: https://github.com/kyma-project/kyma/blob/master/tests/console-backend-service/internal/dex/dex.go

**Comment by michal-hudy** [comment]
/remind @derberg to check this issue in 4 weeks

**Comment by michal-hudy** [comment]
It should be also removed from UI Acceptance tests

**Comment by pkosiec** [comment]
Still valid.

**Comment by a-thaler** [comment]
I finally removed all findings, was more work than expected :)
