### ISSUE TITLE
Improve test for Serverless

### ISSUE THREAD

**Issue by michal-hudy** [kyma-project/kyma#8256]
**Description**

Tests are the easiest and fastest way to find potential issues during development. The serverless domain in Kyma integrates a couple of components. One thing is that we need to have a really good unit test coverage for them but also tests integration between them. We should focus not only on a happy path, but also on some corner cases.

**Reasons**

Speed up development and review process. Having a bulletproof solution.

**Comment by aerfio** [comment]
Closing this one as everything is already done.
