### ISSUE TITLE
Add more unit tests to the Serverless controller manager

### ISSUE THREAD

**Issue by pPrecel** [kyma-project/kyma#8262]
**Description**
Check all components and tests which use `function-controller`, improve existing and add missing unit tests. In the end, make sure that everything is stable and covers all scenarios.

**Comment by michal-hudy** [comment]
Generally, we need to improve our test coverage in Serverless Controller Manager. We need to focus not only on a happy path, but also on corner cases and error handling. It will be beneficial in the future, as Unit Tests are the fastest way to find potential bugs in logic.

**Comment by michal-hudy** [comment]
Epic: https://github.com/kyma-project/kyma/issues/8256
