### ISSUE TITLE
Improve new backup documentation

### ISSUE THREAD

**Issue by a-thaler** [kyma-project/kyma#8266]
**Description**
The new backup docu is here: https://kyma-project.io/docs/master/components/backup/#details-kyma-backup-strategy

It needs general improvements from technical writer perspective like writing key words as code blocks
Furthermore, the linked tickets in the Gardener section should be verified again and then documented proper as they seem to be fixed.

**Reasons**

**Attachments**

**Comment by suleymanakbas91** [comment]
Gardener part has been improved. Basha will distribute this doc into the relevant components and delete the backup module on a different issue.
