### ISSUE TITLE
System namespaces show/hide only after browser refresh in 1.11

### ISSUE THREAD

**Issue by mado0803** [kyma-project/kyma#8268]
**Description**

When I activate or deactivate the System Namespaces in 1.11 and then click again on the "Namespaces" menu entry, they still show up (or are still hidden). I need to manually refresh the browser to cause the expected change.

This was not the case in earlier versions.

**Expected result**

Depending on the actual settings in my user profile, the System Namespaces show or hide. Not only after a browser refresh.

**Actual result**

I need to refresh the browser to reflect the setting in my user profile.

**Steps to reproduce**

1. Click on your user icon
1. Open Settings
1. Change the "Show System Namespaces" item
1. Click on "Namespaces" in the menu (or any other item and then again "Namespaces")

**Troubleshooting**

Hit refresh in the browser.

**Comment by kwiatekus** [comment]
fix introduced https://github.com/kyma-project/console/pull/1959/files
Pending validation
