### ISSUE TITLE
Compass runtime agent adapter external solution test randomly fails with unexpected provision status

### ISSUE THREAD

**Issue by dbadura** [kyma-project/kyma#8297]
**Description**
Compass runtime agent adapter external solution test fails with `unexpected provision status` error while creating service instance `connectivity-adapter-e2e`.

This occurs randomly, for example, this happened on 29.04, 24.04 on `post-master` jobs.

**Expected result**

The `compass runtime agent adapter external solution test` doesn't fail randomly on `post-master` jobs.

**Actual result**

The test fails randomly. 

**Steps to reproduce**
Run this test several times in row and there is a chance that the test will fail.

Here are logs:
https://prow.k8s.io/view/gcs/kyma-prow-logs/logs/post-master-kyma-gke-compass-integration/1253600643659075584
https://prow.k8s.io/view/gcs/kyma-prow-logs/logs/post-master-kyma-gke-compass-integration/1253712130570457088
https://prow.k8s.io/view/gcs/kyma-prow-logs/logs/post-master-kyma-gke-compass-integration/1255373953136857089
**Troubleshooting**

1. Checked stability of this test on [test-grid](https://k8s-testgrid.appspot.com/kyma-postsubmit#post-master-kyma-gke-compass-integration&width=20)

**Comment by pbochynski** [comment]
@dbadura Can you provide some update here? Is it still failing?

**Comment by pbochynski** [comment]
Closed due to inacitvity. @dbadura thanks for updates ;-)
