### ISSUE TITLE
Dead link in the documentation overview

### ISSUE THREAD

**Issue by tehcyx** [kyma-project/kyma#8338]
**Description**
Navigating to the start page of the documentation (1.11): https://kyma-project.io/docs/ in the list of functionalities you'll find
> The messaging channel to receive Events, enrich them, and trigger business flows using lambdas or services (Event Bus, NATS)

where Event Bus is a link to `https://kyma-project.io/docs/components/event-bus/#overview-overview`, which ends in a 404 page for me.

**Expected result**
Correct component linked or link removed.

**Actual result**
link to a dead end.

**Comment by bszwarc** [comment]
It's already fixed on master - https://kyma-project.io/docs/master/root/kyma/#overview-in-a-nutshell - the Event Bus is now Eventing Mesh. The link was also fixed to point to the right doc.

**Comment by tehcyx** [comment]
Not for 1.11 though: https://kyma-project.io/docs/1.11/root/kyma/#overview-in-a-nutshell

**Comment by bszwarc** [comment]
@tehcyx Unfortunately, for now we cannot fix documentation for the already existing releases. If things change, we will update the link.
