### ISSUE TITLE
Links do not have descriptive text in documentation

### ISSUE THREAD

**Issue by magicmatatjahu** [kyma-project/kyma#8342]
**Description**

Some links in our documentation in `/docs` folder haven't descriptive text, but some generic like `read here`, `please read this document` etc. It cause smaller SEO metrics in tools like [Lighthouse](https://developers.google.com/web/tools/lighthouse). Please see below logs.

![image](https://user-images.githubusercontent.com/20404945/80913456-0b4bd380-8d45-11ea-8e85-8e715ede89d8.png)

We must change link content to more descriptive from `read this` to `follow tutorial for exposing Function` etc. depending on the context for better SEO of our kyma-project.io site.

**Comment by kazydek** [comment]
Update the [guidelines on links]( https://kyma-project.io/community/guidelines/content/#links-links) accordingly. 

Example:  
⛔️ "For more information, see **this** guide." or "Read more **here**."   
✅ "For more information, see the **installation guide**."
