### ISSUE TITLE
Upgrade knative-serving to 0.14(latest ATM)

### ISSUE THREAD

**Issue by sayanh** [kyma-project/kyma#8351]
**Description**

The objective is to upgrade knative-serving to 0.14([latest](https://github.com/knative/serving/releases/tag/v0.14.0), at the time of writing).

**Reasons**

This will solve: https://github.com/kyma-project/kyma/issues/8280

**Comment by michal-hudy** [comment]
Duplicate of https://github.com/kyma-project/kyma/issues/7854
