### ISSUE TITLE
Installation supports kubectl 1.18

### ISSUE THREAD

**Issue by a-thaler** [kyma-project/kyma#8360]
**Description**
When installing Kyma using kubectl 1.18 we are facing the issue of `Installation CR cannot be applied with error no matches for kind "Installation" in version "installer.kyma-project.io/v1alpha1"`

The installer.yaml from the kyma release page contains the installation CRD and the installation resource at the same time. Both applied with the same apply command was leading to non-deterministic problems before already, now being unsupported fully as the CRD must exist before a related resource can be applied.

Action Items:
1. Have separate files (tiller.yaml, kyma-installer.yaml and components.yaml) as proper release artifacts
2. Use Kyma CLI only for installation - including prow, spinnaker, documentation (https://github.com/kyma-project/kyma/issues/8190) etc.

**Reasons**
Remove any non-deterministic behavior and support future k8s versions

**Attachments**

**Summary of changes needed**

- [x] Hydroform
- [x] Adjust Kyma-cli
- [x] Prow
    - [x] Change go code to prevent publishing the release
    - [x] Update prow job to copy the different files to release bucket
    - [x] Update the release job: https://github.com/kyma-project/kyma/blob/master/installation/scripts/release-generate-kyma-installer-artifacts.sh
- [x] Update Documentation 

**Changes Needed on other components**
- Compass: https://github.com/kyma-incubator/compass/issues/1468

**Comment by Szymongib** [comment]
Hi,
I see you started to work on the second action item. I wanted to ask what about the first one?
> Have separate files (tiller.yaml, kyma-installer.yaml and components.yaml) as proper release artifacts

Is it skipped for now?
This will also impact the Compass Provisioner so we would like to know if we need to make any changes.

**Comment by a-thaler** [comment]
As we are using the CLI in the newest documentation for everything I'm thinking about removing the release artifacts fully as there should be no official usage of them anymore. Sure, that will impact provisioner as well and we must adjust the hydroform package and usage of it.

**Comment by rakesh-garimella** [comment]
Changes needed on mps are tracked via: https://github.com/kyma-incubator/compass/issues/1468

**Comment by rakesh-garimella** [comment]
PRs:

- Hydorform: https://github.com/kyma-incubator/hydroform/pull/117
- CLI: https://github.com/kyma-project/cli/pull/485

**Comment by rakesh-garimella** [comment]
We need to make the bucket containing release artifacts public if we want to stop publishing github releases: https://github.com/kyma-project/test-infra/issues/2562

**Comment by rakesh-garimella** [comment]
Waiting for release 1.14 to be out.

**Comment by rakesh-garimella** [comment]
Now we have adjusted various jobs such that we get following release artifacts:
```kyma-installer-cr-cluster.yaml
kyma-config-local.yaml
kyma-installer-cr-local.yaml
release-changelog.md
kyma-installer.yaml
```
