### ISSUE TITLE
Figure out uploading and getting documentation for namespaced Service Classes

### ISSUE THREAD

**Issue by pkosiec** [kyma-project/kyma#838]
Currently we generate and store on Minio something like `/service-class/{clusterServiceClassName}`. The thing is that these are ClusterServiceClasses and we haven't figured out, how to store documentation for ServiceClasses. Probably we need to have something like this:

`/cluster-service-class/{clusterServiceClassName}` 
`/service-class/{namespace}/{clusterServiceClassName}` 

Or we can store it in only one directory.

**Comment by derberg** [comment]
this is already implemented by https://github.com/kyma-project/console/issues/666 and other issues
