### ISSUE TITLE
Application Broker does not refresh services after update

### ISSUE THREAD

**Issue by polskikiel** [kyma-project/kyma#8380]
**Description**

Scenario:

1. Create an App with services
2. Create AppMapping for it
3. ServiceClasses should be available in Mapping's namespace
4. Edit App and remove any service

Ideas:
- Fix this bug: https://github.com/kyma-project/kyma/blob/master/components/application-broker/internal/syncer/controller.go#L214
- Check if app broker catalog returns proper services on catalog enpoint
- Check if Application was updated on storage
- Check if fetching services from an application on catalog endpoint works as expected.

**Expected result**

A proper ServiceClass or ServicePlan should be deleted.

**Actual result**

ServiceClasses / ServicePlans list is not updated.

**Comment by klaudiagrz** [comment]
Timeboxed to 13 SP.

**Comment by polskikiel** [comment]
I created a [PR](https://github.com/kubernetes-sigs/service-catalog/pull/2797) which fixes this story.

**Comment by PK85** [comment]
Closed as Kyma uses 0.3.0 SC now.
