### ISSUE TITLE
Verification of restrictions before saving function

### ISSUE THREAD

**Issue by michal-hudy** [kyma-project/kyma#8385]
**Description**

Before a function is saved we need to verify if all spec fields are valid. Some envs are restricted, pods labels need to follow `metadata.labels` restrictions etc. Validation must works in UI and also when the function is created/updated with `kubectl` (consider webhook, as it is working pretty nice with `kubectl`)

**Reasons**

Improve UX, give a proper feedback before the function is created/updated. Currently, the user will know about issues only when the job or service is created, so it is too late.

**Comment by kazydek** [comment]
We would also need to update [Serverless architecture diagram](https://kyma-project.io/docs/components/serverless/#architecture-architecture) and description to include the validation step.
