### ISSUE TITLE
API Rule UI only offers subset of methods

### ISSUE THREAD

**Issue by akrausesap** [kyma-project/kyma#8392]
**Description**

Dear Colleagues,

the API rule UI only offers the HTTP Verbs GET, PUT, POST, DELETE. However there are many more out there. The most prominent one being PATCH. 

It would be good to have an option to whitelist all verbs as well as an extensible list.

**Reasons**

This would allow to expose standard and complex REST APIs via the UI. Currently this is only possible via the cli

**Attachments**

**Comment by a-thaler** [comment]
A HEAD request might be common as well :)
