### ISSUE TITLE
Deprecate Connector Service and Application Registry API

### ISSUE THREAD

**Issue by pbochynski** [kyma-project/kyma#8416]
**Description**
The Connector Service and Application Connector are replaced by the Connector and Director components from [Compass](https://github.com/kyma-incubator/compass). There is also a new component - [Connectovity Adapter](https://github.com/kyma-incubator/compass/tree/master/components/connectivity-adapter) that ensures that the backward compatibility with Connector Service and Application Connector is preserved. 
The deprecation should cover:
- [x] mark APIs as deprecated
- [x] provide links to the new API and to the manual how to install compass
- [x] include deprecation note in the release notes

**Reasons**

Application connectivity area evolved into more centralized direction. We worked on the new component that is able to handle applications (systems) connections to multiple Kyma Runtimes without point to point integrations. We introduced more flexible and rich API that covers much more use cases.

**Comment by janmedrek** [comment]
Documentation PR in Kyma: https://github.com/kyma-project/kyma/pull/8425
