### ISSUE TITLE
Have a web based Kyma Installer configurator 

### ISSUE THREAD

**Issue by valentinvieriu** [kyma-project/kyma#8423]
**Description**

Build a web interface that will allow a user to configure granularly his Kyma installation, and also get contextual help while he(she) needs to chose a component for the Kyma installation.

**Reasons**

If we plan to have Kyma more modular, and allow people to install it as streamline as possible or as complex as they need, the cli will become quite hard to use and also will be quite hard to explain why would you need component A or B ( contextual help ). Using a web interface will allow us to track user needs, and create General Packages ( that fulfil certain needs)

**Attachments**

See examples
- [kurl](https://kurl.sh/)
- [gardener installer](https://gardener.cloud/installer/)

**Comment by a-thaler** [comment]
Is a nice idea to generate the component list and potential configuration options, so generating the full configuration.
Still it will be helpfull if you can pass the files to the CLI and it will take care of applying, showing status, doing local setup afterwards.

**Comment by piotrmsc** [comment]
I'm unassigning myself from it as I would prefer the UI parts to be done maybe by @kwiatekus as he owns UI domain part

**Comment by pbochynski** [comment]
We can address it with reconciler / Busola story when Bring Your Own Cluster (BYOC) model.
