### ISSUE TITLE
tiller-certhelper script does not handle errors

### ISSUE THREAD

**Issue by mszostok** [kyma-project/kyma#8447]
**Description**

The [tiller-certhelper](https://github.com/kyma-project/kyma/blob/master/installation/resources/tiller.yaml#L58-L131) script has a bug:

```
---> Generate CA
Generating RSA private key, 4096 bit long modulus (2 primes)
...........................++++
............................................................................++++
e is 65537 (0x010001)
---> Generate Tiller key
Generating RSA private key, 4096 bit long modulus (2 primes)
..++++
................................++++
e is 65537 (0x010001)
Signature ok
subject=C = PL, ST = Gliwice, L = Gliwice, O = Tiller Server, CN = tiller-server
Getting CA Private Key
---> Create secrets in k8s
error: unable to recognize "STDIN": Get https://100.64.0.1:443/api?timeout=32s: dial tcp 100.64.0.1:443: i/o timeout
tiller-secret configured.
```

as you can see from the above logs Secret was not created because of timeout on api server but in logs, we see that `tiller-secret configured.` and no error is returned. As a result, the tiller and kyma-installer were crashing.

**Expected result**

If an error occurred, the retry is executed

**Actual result**

If an error occurred, the operation is marked as succeeded

**Comment by piotrmsc** [comment]
Yup, looks 💯 valid, we need to have retries there and indeed fail. I think we also do not have `-e` there 🤔 In general we need to review error handling there
