### ISSUE TITLE
Upgrade Knative eventing and related components to 0.14*

### ISSUE THREAD

**Issue by sayanh** [kyma-project/kyma#8458]
Knative-serving charts are planned to be upgraded by PR #8508  we need to test this as soon as possible and decide that does it make sense to upgrade knative-eventing as well to be congruent with kantive-serving.

**AC**
- Investigate if upgrade is needed on the first place w.r.t #8508 (prior testing needed)
- if upgrade is required then Upgrade Knative eventing and related components to 0.14.* (knative-eventing-kafka)
- Check E2E Tracing 
- Check Eventing Dashboards

**Comment by nachtmaar** [comment]
I tested on a gardener backed knative-kafka enabled Kyma cluster based on [magicmatatjahu/update-knative-serving](https://github.com/kyma-project/kyma/pull/8508), commit `e516975a68e057d9a3327167d67e4dcf6bd4b16a`.

As far as I can see metrics and tracing are working as expected. See attached screenshots:

![screencapture-grafana-nils28458-kymatunas-shoot-canary-k8s-hana-ondemand-d-ab4f13a9892a76a4d21ce8c2444bf4e8-kyma-event-mesh-pods-2020-06-02-15_21_56](https://user-images.githubusercontent.com/8013145/83525459-4cbad480-a4e5-11ea-97d6-0feef6656cc0.png)
![screencapture-grafana-nils28458-kymatunas-shoot-canary-k8s-hana-ondemand-d-ab4f13a9892a76a4d21ce8c2444bf4e9-kyma-event-mesh-delivery-2020-06-02-15_21_34](https://user-images.githubusercontent.com/8013145/83525471-50e6f200-a4e5-11ea-876f-83247d9d09a4.png)
![screencapture-grafana-nils28458-kymatunas-shoot-canary-k8s-hana-ondemand-d-e2WkUxtWe-kyma-event-mesh-broker-trigger-2020-06-02-15_21_06](https://user-images.githubusercontent.com/8013145/83525474-517f8880-a4e5-11ea-819b-5b17cd3b15c1.png)
![screencapture-grafana-nils28458-kymatunas-shoot-canary-k8s-hana-ondemand-d-ycULeS8Zz-kyma-event-mesh-latency-2020-06-02-15_21_47](https://user-images.githubusercontent.com/8013145/83525477-52181f00-a4e5-11ea-9171-4ff789b3f1e4.png)
![screencapture-jaeger-nils28458-kymatunas-shoot-canary-k8s-hana-ondemand-trace-d393c3f3d475c2c86de9941802a06472-2020-06-02-15_22_10](https://user-images.githubusercontent.com/8013145/83525478-52b0b580-a4e5-11ea-9ce7-b8f41c4096ae.png)

**Comment by nachtmaar** [comment]
No upgrade is needed. Tracing/Metrics work as expected.
