### ISSUE TITLE
Improve upgrade tests to check if update works after creating a new release

### ISSUE THREAD

**Issue by hudymi** [kyma-project/kyma#8463]
**Description**

I'm creating this issue to start a discussion on how to improve `pre/post-master-kyma-gke-upgrade` job before we jump into implementation.

As for now, the test is working like that:
1. Install the latest release
2. Create resources
3. Upgrade to the master/PR
4. Execute tests, including verification of upgraded resources

And it is great, it helps us verify if it will be possible to upgrade from the previous release to the current version that is under development.

Unfortunately, it doesn't verify if it will possible to upgrade from the current version when it will be released. We have such a problem per 2-3 releases (last time it was a problem with the `serverless` chart). After releasing, all PRs are blocked, because upgrade no longer works.

For now, I see two ways how to solve that, but none of them is ideal.

- Extend `pre/post-master-kyma-gke-upgrade`
   1. Execute all steps from the test
   2. Upgrade again to the same revision
   3. Execute tests

- Create a new upgrade job
   1. Install Kyma from master(PR)/previous commit (master)
   2. Create resources
   3. Upgrade to the PR/commit
   4. Execute tests

Unfortunately, none of these solutions covers a problem with adding a new chart (when it didn't exist in the previous commit), or when there are no changes in the charts between revisions...

**Reasons**

Detect problems with the upgrade to the current version before releasing it.

**Comment by k15r** [comment]
Could you elaborate a bit what you mean with these two scenarios:

>Unfortunately, none of these solutions covers a problem with adding a new chart (when it didn't exist in the previous commit), or when there are no changes in the charts between revisions...

Imho we have multiple scenarios to cover:

| FROM |TO  | Covers | implemented |
| ------- | ----| -------|-------------|
| released version | master | customers, release -> next release | ✅|
| master | master + PR | developers, potential next release -> postrelease | ❌|
| master + PR | master + PR | developers, new chart introduced in PR | ❌|

As the 3rd step is basically just executing the entire upgrade test at once it could also be easily implemented that way: Install cluster with master+pr, execute prepare and evaluation phase after on another. As soon as the upgrade test is split into multiple test definitions as decided [here](https://github.com/kyma-project/community/pull/442) this will also be not very time consuming and can be run with every PR.

**Comment by anishj0shi** [comment]
Instead of having an enhanced upgrade job, it'd make more sense to introduce a periodic *Update* Job which would check the sanity of update process from the same version.

**Comment by magicmatatjahu** [comment]
@anishj0shi @k15r Will you handle that issue on 1.15 or 1.16 release? I think that is very important. After 1.14 release we had a problem with migration from helm2 to helm3 - in job's script we used the helm2 with old arguments, but we had installed Kyma with helm3 onboard, so master wasn't mergeable about 1-2 day(s). Issue: https://github.com/kyma-project/kyma/issues/9202

**Comment by kwiatekus** [comment]
Bear in mind changes planned with CRD handling:
https://github.com/kyma-project/kyma/issues/9454
