### ISSUE TITLE
Add the location of the installation artifacts to the upgrade section

### ISSUE THREAD

**Issue by bszwarc** [kyma-project/kyma#8465]
**Description**

Step 5 of the upgrade documentation: https://kyma-project.io/docs/1.12/root/kyma/#installation-upgrade-kyma-upgrade-kyma-to-a-newer-version says that you need to download the following files:

- kyma-config-local.yaml
- kyma-installer-local.yaml
- kyma-installer-cluster.yaml

Users don't know where to get these files from. They are listed for each [release](https://github.com/kyma-project/kyma/releases) in the `assets` section. As the download links point to specific files (for example: https://github.com/kyma-project/kyma/releases/download/1.12.0/kyma-config-local.yaml) we can either add the explicit links for each release, or add some generic information on where the user can find the files.
For example:
`To download the files, go to https://github.com/kyma-project/kyma/releases and scroll down to the **Assets** section`. 
I prefer the second approach, as it is easier to maintain.

**Comment by suleymanakbas91** [comment]
The issue is no longer valid as we adapted the documentation to use the CLI.
