### ISSUE TITLE
Documentation points to deprecated script.

### ISSUE THREAD

**Issue by dekiel** [kyma-project/kyma#8484]
Our public documentation under https://kyma-project.io/docs/#details-testing-kyma-tests-execution points to .../installation/scripts/testing.sh as a way to run all test.

To run all tests, use the testing.sh script located in the /installation/scripts/ directory. Internally, the ClusterTestSuite resource is defined. It fetches all TestDefinitions and executes them."

Whereas script says:
echo "The testing.sh script is deprecated and will be removed. Use Kyma CLI instead."

We should update documentation to point to Kyma CLI as a default way of running tests.

**Comment by a-thaler** [comment]
Duplicates https://github.com/kyma-project/kyma/issues/8190
