### ISSUE TITLE
"Instance Connection Name" nomenclature is inconsistent with Google's Usage & Docs

### ISSUE THREAD

**Issue by 24601** [kyma-project/kyma#8492]
**Description**

This issue describes a possible mix of user-error and vague documentation around a mismatch in what exactly is meant by "Instance Connection Name". Experienced users of Google Cloud SQL trained by Google's training materials, programs, or documentation (or simply using their UI and REST APIs) expect this value to be one thing, and Kyma expects a subset of this value in its configuration. Failure to do this results in a hard install failure that is difficult and troublesome to diagnose given cryptic error messages. A user skilled in both Cloud SQL and Kyma may still have trouble discerning this subtle yet important difference in vernacular. While it is unclear who is at "fault" or what is "broken" or to "blame" (or if anything really is), and Kyma is technically not wrong or incorrect, it is an issue that can be easily solved by clearing up documentation with a simple sentence or two. 

When using Google Cloud SQL as the persistent store for Ory/Hydra in the production configurations, configuring the desired Cloud SQL Instance requires setting the instance name of the Google Cloud SQL Instance so the Google Cloud SQL Proxy can connect to the appropriate instances. 

In Google's documentation & parlance, the "instance connection name" is a tuple/triplet style identifier following the GCP_PROJECT:GCP_REGION:INSTANCE_NAME format. Google's APIs and Cloud Console (web interface) provide and reference (as well as their attendant documentation) the "Instance Connection Name" as this _entire_ string. Kyma's documentation references the "Instance Connection Name" (or similar analogues such as the configuration item gcloud-sqlproxy.cloudsql.instance.instanceName).

https://github.com/kyma-project/kyma/blob/master/docs/security/05-05-production-profile.md#L94

However, Kyma's intent (and its expectation) in using this vernacular is to reference *only* the third element of the tuple/triplet of Google's definition/usage of the identifier. 

As this does not match Google (or the understanding of users familiar with Cloud SQL), it creates an ambiguity that results in a very frustrating and difficult to debug misconfiguration that presents itself as a bug at first until the user dives into the actual Helm chart to see that Kyma assembles this tuple/triplet on its own and intends/expects the user to provide the "Instance Connection Name" not in the format provided by the Google Cloud console, the REST API, or their other tooling, but having the leading two components of this identifier stripped. 

If the user does not do this, the Helm chart will fail as the Instance Connection Name is used in the service definition and is not a DNS-compatible name. This error is further problematic as it is directs the user further in the "is this a bug?" path as the Instance Connection Name is never intended to be a DNS name (let alone DNS safe) and presents itself as a bug rather than actual "user error".

I propose that the documentation be amended with a simple sentence or hint to clearly point out to the user that only the last third of this identifier (the balance of the string past, but not inclusive of the final colon) is what should be provided to the Kyma overrides/configurations for the instanceName property mentioned earlier. Suggesting further that failure to do so may result in cryptic errors such as DNS-name issues may help users who miss this initially and now find their installation in a partially failed, and confusing state. 

k8s 1.16.8-gke15
Kyma 1.12.0

**Expected result**
Kyma documentation provides a clue/hint that the user should provide a partial form of the Instance Connection Name, not the full string

**Actual result**
Kyma's documentation creates an ambiguous situation where the ory-gcloud-sqlproxy service deployment fails, causing the entire Ory update/install to fail. 

**Steps to reproduce**
Use a full Instance Connection Name in gcloud-sqlproxy.cloudsql.instance.instanceName, it will fail. 

**Troubleshooting**

**Comment by kazydek** [comment]
Already fixed with PR #8493
