### ISSUE TITLE
Oathkeeper-maester sporadically crashes 

### ISSUE THREAD

**Issue by ebensom** [kyma-project/kyma#8501]
**Description**
We have observed that the oathkeeper-maester container inside the ory-oathkeeper pod sporadically exits with code 2. At the time of exit, the following 2 error messages are logged within a few milliseconds:
```
log:W0517 02:59:21.569313 1 reflector.go:289] pkg/mod/k8s.io/client-go@v11.0.1-0.20190409021438-1a26190bd76a+incompatible/tools/cache/reflector.go:94: watch of *v1alpha1.Rule ended with: too old resource version: 53525169 (55967158)
log: exiting because of error: log: cannot create log: open /tmp/manager.ory-oathkeeper-6fddb67f8c-9rxh4.unknownuser.log.WARNING.20200517-025921.1: no such file or directory
```
Multiple (3) instances of oathkeeper-maester containers are running, as a sidercar in ory-aothkeeper pod.

**Expected result**
No crashes are observed.

**Actual result**
Crash happens once within 3 days.

**Steps to reproduce**
Unknown, but may be related to multiple replicas of oathkeeper-maester running.

**Troubleshooting**

**Comment by colunira** [comment]
The possible reason is using old k8s packages. I'm updating them. If the issue persists, we'll investigate further.

**Comment by piotrmsc** [comment]
if still occurs please re-open and ping :)
