### ISSUE TITLE
Migrate kyma-operator to helm 3

### ISSUE THREAD

**Issue by pbochynski** [kyma-project/kyma#8517]
**Description**
Refactor kyma-operator to use helm 3.

**Reasons**
A lot of security vulnerabilities are assigned to Tiller (helm 2 server-side component). The best way to deal with them is just to upgrade to "tillerless" helm 3.

**Related issues**
- https://github.com/kyma-project/kyma/issues/7933
- https://github.com/kyma-project/helm-broker/issues/66
- https://github.com/kyma-project/kyma/issues/6552

**Comment by piotrmsc** [comment]
Additionally we will need to :
- Update our prow jobs (remove tiller part)
- Update documentation (remove tiller part)

**Comment by piotrmsc** [comment]
@adamwalach I think prow part could be done on your side?
