### ISSUE TITLE
Support Uninstallation of Eventing Components

### ISSUE THREAD

**Issue by anishj0shi** [kyma-project/kyma#8526]
kyma-operator triggers the uninstallation by adding relevant labels. 

Helm delete should remove the installed charts. 

**AC**
- Purging of components should be supported and compliant with helm3 
```shell
helm delete <eventing_chart> #Should delete the CRs. present in the eventing charts
```
- The idea behind uninstallation of the eventing components is to give back the cluster in it's original shape. i.e All the resources present due to installation of eventing chart such as knative-eventing, knative-kafka, natss, etc should be cleaned up.
- if the component is uninstalled **helm ls** should not show it in the list and a consequent **helm install** should go smoothly.
- Knative-eventing namespace should be removed after uninstallation

**Comment by nachtmaar** [comment]
This ToDo is left after PR https://github.com/kyma-project/kyma/pull/8826
- [ ] add uninstall for nats namespace and knative-eventing namespace, hopefully in kyma-operator
