### ISSUE TITLE
Conform knative-eventing-kafka charts with helm3

### ISSUE THREAD

**Issue by anishj0shi** [kyma-project/kyma#8529]
Refactor knative-eventing-kafka chart to be compliant with Helm3

**AC**
Improve kyma components charts by:
- [x] make charts compatible with helm 3
- [x] fix errors in schemas
- [x] remove deprecated APIs
- [x] do not install resources in multiple namespaces within one chart
- [ ] move custom resource definitions to the first step (cluster-essentials)
- [x] each kyma chart can be installed by `helm template | kubectl apply -f -`

**Comment by sayanh** [comment]
Following item is out of scope:
> move custom resource definitions to the first step (cluster-essentials)
