### ISSUE TITLE
Knative kafka channel is not ready in gardener-azure job

### ISSUE THREAD

**Issue by sayanh** [kyma-project/kyma#8544]
**Description**

Turns out the Knative kafka channel is not ready multiple times in gardener-azure job
```
2020/05/19 11:37:58 created Kafka channel: test-kafka-channel
2020/05/19 11:37:58 found Kafka channel: test-kafka-channel with ready status: false
2020/05/19 11:37:58 [0] try failed: the Kafka channel is not ready
2020/05/19 11:38:03 found Kafka channel: test-kafka-channel with ready status: false
```

References:
https://storage.googleapis.com/kyma-prow-logs/logs/kyma-integration-gardener-azure/1263001873011445762/build-log.txt
https://storage.googleapis.com/kyma-prow-logs/logs/kyma-integration-gardener-azure/1262684766344318976/build-log.txt

Impacted tests:
- core-test-external-solution
- knative-eventing-kafka

**Comment by k15r** [comment]
cannot be reproduced since we switched to individual event hubs per job run https://github.com/kyma-project/test-infra/pull/2466
