### ISSUE TITLE
Support dynamic versioning and installation for Event-Bus and Event-Service

### ISSUE THREAD

**Issue by radufa** [kyma-project/kyma#855]
Dynamic versioning and installation of components in the pipeline was just merged.

You can see a detailed explanation here: https://github.wdf.sap.corp/d073003/community/blob/7d41321668c4f684b7c190682dff14d425f20401/sig-and-wg/sig-deploy-ci/proposals/dynamic-versioning.md

All teams please adapt the helm charts of your components to make use of the dynamic versions. If not done, both the pipeline and local installation will not have up to date components.

Follow the example here (line 25 has the relevant change):
https://github.com/kyma-project/kyma/blob/master/resources/core/charts/environments/templates/4-deployment.yaml

In components that have dashes (`-`), please replace them with underscores (`_`)

**Warning**  Please keep in mind that this is very important for CX Live and needs to be finished ASAP

## Components
1. event-bus charts and sub-charts
1. event-service
1. event bus e2e tests

AC:
- [ ] All helm charts are updated
- [ ] Installation on local is successful.
- [ ] Installation via pipeline is successful (malones on-demand cluster)

**Comment by abbi-gaurav** [comment]
Waiting for @pbochynski to come back for additional changes.

**Comment by abbi-gaurav** [comment]
After discussing with @crabtree it is confirmed that no further action is needed.
