### ISSUE TITLE
Kyma-operator refactoring after implementing advanced retries

### ISSUE THREAD

**Issue by strekm** [kyma-project/kyma#8576]
**Description**

Implement the following:

[r] means in review :)

- [x] refactor on error handling for install / upgrade step (maybe it could be extracted to the OnError method on step)
- [ ] ~~review kyma helm client to check when retry operation could be implemented~~
- [x] write tests for stepsfactory
- [x] write tests for installation
- [ ] improve logging on installation / upgrade error
- [x] implement wait method which actively checks if helm release was deleted / rollbacked 

**Reasons**

**Attachments**

**Comment by Tomasz-Smelcerz-SAP** [comment]
I am skipping 'review kyma helm client to check when retry operation could be implemented' to avoid conficts with ongoing migration to Helm3.

**Comment by Tomasz-Smelcerz-SAP** [comment]
This task is mostly done. Improvement in logging will be continued in #8517
