### ISSUE TITLE
Application Connector charts cleanup

### ISSUE THREAD

**Issue by janmedrek** [kyma-project/kyma#8577]
**Description**
Since we are moving to the Tiller-less environment we should get rid of all references and old values that are used in our charts.

**Acceptance Criteria**
- [x] Old values removed
- [ ] References to Tiller purged
- [x] Obsolete labels removed

**Comment by franpog859** [comment]
Hey! I did not clean the charts located in `components/application-operator/charts/` directory. It may slow down the important Helm 2 -> 3 migration which is being implemented in [this PR](https://github.com/kyma-project/kyma/pull/8417). I created [this follow-up issue](https://github.com/kyma-project/kyma/issues/8718) instead. It should be pretty straight forward this time
