### ISSUE TITLE
Helm3 support for logging component

### ISSUE THREAD

**Issue by a-thaler** [kyma-project/kyma#8601]
**Description**
Migrate the logging component to be helm3 compliant

AC:
- helm3 linting will not complain
- No helm2 specific labels applied to resources
- helm install works

**Reasons**
Support for Helm3 in Kyma

**Attachments**

**Comment by clebs** [comment]
The logging chart has been migrated to helm 3 except for 2 points that will be done later for all components:
- Change `apiversion` to v2 in `Chart.yaml`
- move `dependencies` block to `Chart.yaml`

That can be done once https://github.com/kyma-project/kyma/issues/8517 is finished and applied into the Prow jobs.

**Comment by rakesh-garimella** [comment]
While trying to install monitoring charts  using `helm install` I get following error(although `helm template` does not complain):
```bash
Error: rendered manifests contain a resource that already exists. Unable to continue with install: PodSecurityPolicy "monitoring-grafana" in namespace "" exists and cannot be imported into the current release: invalid ownership metadata; label validation error: key "app.kubernetes.io/managed-by" must equal "Helm": current value is "Tiller"; annotation validation error: missing key "meta.helm.sh/release-name": must be set to "monitoring"; annotation validation error: missing key "meta.helm.sh/release-namespace": must be set to "default"
```

may be we need such changes too here ?

**Comment by a-thaler** [comment]
@rakesh-garimella Was there a monitoring chart already installed before via helm2? Reading this link it sounds like you can use these annotations for migration purposes: https://github.com/helm/helm/pull/7649
Please figure out what the effect of these annotations and labels is and if that is the best practice for writing helm charts, then we can think of applying that consistently to all.
