### ISSUE TITLE
Helm3 support for monitoring component 

### ISSUE THREAD

**Issue by a-thaler** [kyma-project/kyma#8602]
**Description**
Migrate the logging component to be helm3 compliant

AC:
- helm3 linting will not complain
- No helm2 specific labels applied to resources
- helm install works

**Reasons**
Support for Helm3 in Kyma

**Attachments**

**Comment by rakesh-garimella** [comment]
Currently when we do `helm3 uninstall` then the CR created by patch are not deleted. So a `helm3 install` again would fail. To mitigate this we can use for now
```bash
k delete clusterrolebindings.rbac.authorization.k8s.io -n kyma-system monitoring-dns-patch  aks-kubelet-monitoring-kyma-patch
k delete clusterroles.rbac.authorization.k8s.io -n kyma-system aks-kubelet-monitoring-kyma-patch monitoring-dns-patch
k delete serviceaccounts -n kyma-system monitoring-dns-patch aks-kubelet-monitoring-kyma-patch
k delete configmaps -n kyma-system monitoring-dns-patch aks-kubelet-monitoring-kyma-patch
k delete jobs.batch -n kyma-system aks-kubelet-monitoring-kyma-patch 
```
