### ISSUE TITLE
Create install/update job for rafter custom resource definitions

### ISSUE THREAD

**Issue by m00g3n** [kyma-project/kyma#8609]
**Description**
Create install/update `Job` for `rafter` custom resource definitions in `cluster-essentials` chart, remove corresponding CRDs files from `cluster-essentials` chart.

List of `CRDs`:
- assets 
- clusterassetgroups 
- assetgroups 
- clusterbuckets 
- buckets
- clusterassets

**Reasons**

- in order to have more flexible solution we should not introduce dependency to `CRDs` in charts

**Attachments**
- https://github.com/kyma-project/kyma/issues/7933
- https://github.com/kyma-project/kyma/pull/8062

**Comment by pbochynski** [comment]
@m00g3n Is it done? PR is merged.
