### ISSUE TITLE
Build and release kyma-installer with embedded sources

### ISSUE THREAD

**Issue by pbochynski** [kyma-project/kyma#866]
**Description**
The image should be produced for every commit to master (later on also on release branch)
Tag image with branch and commit Id.

**Reasons**
Based on the proposal: https://github.com/kyma-project/community/pull/79

**To do:**
- [x] create script which extract installer version from installer.yaml -> @kfurgol 
- [x] create Dockerfile building kyma embedded with installer -> @strekm 
- [x] create Jenkinsfile for release based on installer image bundled with kyma sources -> @crabtree

**Comment by strekm** [comment]
- docker file should be dynamic (installer version)
- come up with proper name of released image (installer with kyma bundled)
- where to put all related files in context of kyma project (maybe release at root)

**Comment by strekm** [comment]
- create artefacts: local and cluster config with overrides and versions overrides (versions overrides should be part of both local and cluster yaml)

**Comment by kfurgol** [comment]
-create script which extract installer version
