### ISSUE TITLE
Document the installation process

### ISSUE THREAD

**Issue by kazydek** [kyma-project/kyma#8663]
**Description**

Since we are changing the installation approach ([#7933](https://github.com/kyma-project/kyma/issues/7933)), it would be uber-cool to finally have a document that describes the installation process, in its new shape now.

I would suggest a short doc of **Installation** type somewhere [here](https://kyma-project.io/docs/root/kyma/#installation-installation) (like "Installation process"), describing the Installer and the order of steps it performs to install Kyma (CRDs first, then charts synchronously).

**Comment by alexandra-simeonova** [comment]
The topic will be covered by this issue: https://github.com/kyma-project/kyma/issues/10355
