### ISSUE TITLE
Redesign of kyma-operator

### ISSUE THREAD

**Issue by pbochynski** [kyma-project/kyma#8664]
**Description**
Kyma-operator requires redesign (or even replacement) to fulfill the requirements:
- Work in declarative mode. The desired state of Kyma installation should be applied in the reconciliation loop. The current solution reacts to the action label and starts the one-time installation/uninstallation process.
- Kyma modules should be independent as much as possible. In particular: installation, upgrade and reconfiguration of a single component should be possible without touching other components.
- Installation should be much faster (~5 minutes is a goal). A parallel installation and upgrade should be possible.
- The configuration changes should be easy to apply and should not hide underlying implementation (in our case helm). There should be an easy way to merge default configuration with an environment-specific configuration and end-user configuration flexibly and predictably. Helm already supports merging multiple values files (rightmost has the highest priority), but kyma-operator uses its own mechanism that has a lot of limitations (e.g. only strings and booleans supported). 
- Installation/configuration can be triggered by the central control plane (managing multiple Kyma runtimes). Also, some components should be configured in the central place.

In the redesign work consider other solutions that emerged in the area since kyma-operator was established (e.g. helm-operator). 

**Acceptance criteria**
- working prototype 
- design description (diagrams are welcome)

**Reasons**
Kyma requires several open source components and delivers a list of own components that integrate them. The goal is to minimize the cloud-native developer's effort to install and configure all these tools and let them focus on business logic. Kyma should provide helpers and automation without increasing complexity and introducing too many concepts and abstractions.

**Comment by radufa** [comment]
An interesting aspect could be to "open" the new operator to the future applications running on top of Kyma (as a runtime), providing a kind of basis functionality for their custom installer. 
As an example for this direction to go, see: https://github.com/lightbend/akka-cluster-operator/blob/master/README.md

**Comment by m00g3n** [comment]
https://github.com/kyma-project/kyma/issues/8755

**Comment by muralov** [comment]
Hello, can I take this issue as a Kyma contributor?

**Comment by pbochynski** [comment]
After several PoCs the Installation Working Group decided to continue development of kyma-installer and do not proceed with helm-operator. The direction of development is to utilize and expose helm features as much as possible. In the first step, the library for parallel chart installation will be introduced. The library will be used directly in Kyma CLI and in kyma-installer. The library will support helm values files with proper hierarchy (priorities). See the follow up issue: https://github.com/kyma-project/kyma/issues/9347

**Comment by pbochynski** [comment]
> Hello, can I take this issue as a Kyma contributor?

@muralov I somehow missed your comment. Of course, your help is welcome. Please join [WG installation meeting](https://kyma-community.slack.com/files/UBWBML6US/F015F4XTD9T/kyma_installation_wg.ics) to discuss how would you like to contribute or just chat with us on [#installation](https://kyma-community.slack.com/archives/CD2HJ0E78) slack channel.
