### ISSUE TITLE
Create release branch and pre release in github

### ISSUE THREAD

**Issue by pbochynski** [kyma-project/kyma#867]
**Description**
First kyma release has to happen. The idea is to create it manually and then create tasks to automate some steps. 

**To do:**
- [x] Create branch 0.4 (branch name: release-0.4)
- [x] Create pre release 0.4
- [x] Publish kyma-deployment-local.yaml and kyma-deployment-cluster.yaml as release artifacts that contain:
    - [x] Versions.env as overrides - @kfurgol 
    - [x] Overrides as config maps
    - [x] Installer crd with components
    - [x] Installer deployment
- [x] Publish installation readme (minikube & GKE)

Acceptance Criteria
- About the kyma-deployment-local.yaml and kyma-deployment-cluster.yaml:
  - These files are not versioned
  - These files are generated, there must be a script for that
  - These files should contain as much as possible in terms of installation config values. We need to reduce number of steps necessary to install. Perfect case is that we need only single file with everything. If not possible, describe it in comments.

**Comment by uschulle18** [comment]
Please let us check first if we could additionally fix some bugs which would be important for our guys going to CX Live.

**Comment by pbochynski** [comment]
> Please let us check first if we could additionally fix some bugs which would be important for our guys going to CX Live.

We create a branch for release. If there is some issue we want to add we can do a cherry pick from master. So we don't have to wait for bug fixes.
