### ISSUE TITLE
Download of kubeconfig not possible in chrome (firefox works)

### ISSUE THREAD

**Issue by tm4g1x** [kyma-project/kyma#8683]
**Description**

Open Chrome and go to General Settings. Click on button "Download config". The download is not starting, but in Developer Console you receive a warning that download is not enabled. With Firefox it works without problems.

**Expected result**

Config file should be downloaded.

**Actual result**

Download does not start.

**Steps to reproduce**

Start Chrome --> Login to kyma  --> go to General settings --> Download config

![image](https://user-images.githubusercontent.com/24810353/83604407-66f0c300-a576-11ea-8b3a-ebf3c922d9f3.png)

**Troubleshooting**

Viewing developer console. Shows warning.

**Comment by kwiatekus** [comment]
Hi @tm4g1x. 
Fixed on master. Soon to be released with 1.14
kubeconfig download button was fixed and moved to the dropdown component in the top header.
![Screen Shot 2020-06-25 at 12 14 07](https://user-images.githubusercontent.com/6783567/85701340-94481100-b6dd-11ea-9941-7dea5ee11a3e.png)
