### ISSUE TITLE
Run integration tests on GKE cluster with self signed certificates and kyma.local domain

### ISSUE THREAD

**Issue by pbochynski** [kyma-project/kyma#870]
**Description**
CI should test pull requests on real cluster (GKE). But we can't issue new certificate and create DNS entry for every new pull request. The idea is to test it with self signed certificates and local DNS (or entries in /etc/hosts).

**Comment by piotrmsc** [comment]
Duplicate of https://github.com/kyma-project/test-infra/issues/20. Won't do
