### ISSUE TITLE
Cleanup not triggered for `kyma-integration-gardener-azure` and `pre-master-kyma-gardener-azure-integration` when job times out

### ISSUE THREAD

**Issue by nachtmaar** [kyma-project/kyma#8700]
**Description**

Cleanup not triggered [kyma-integration-gardener-azure](https://storage.googleapis.com/kyma-prow-logs/logs/kyma-integration-gardener-azure/1268437409322766336/build-log.txt) and [pre-master-kyma-gardener-azure-integration](https://storage.googleapis.com/kyma-prow-logs/pr-logs/pull/kyma-project_kyma/8687/pre-master-kyma-gardener-azure-integration/1268423064157163520/build-log.txt) when job times out.

**Expected result**
All creates resources are deleted at the end of the job.

**Actual result**
Gardener cluster and Azure EventHub still exist.

**Steps to reproduce**
Let the job timeout and check that the created still exist.

**Comment by pbochynski** [comment]
Please create azure clean up a prow job that removes Azure Events Hub instances that is running periodically.

**Comment by nachtmaar** [comment]
@pbochynski Isn't that just a workaround for the [cleanup](https://github.com/kyma-project/test-infra/blob/669ab9de56c62de301b904b202947870e95ed0b3/prow/scripts/cluster-integration/kyma-integration-gardener-azure.sh#L141) which is not executed properly? IMHO we should ensure that cleanup has enough time to run.

**Comment by k15r** [comment]
as we need to introduce unique names for azure namespaces for the presubmit jobs, fixing the cleanup issue properly (execute cleanup right in the job that creates the namespace) would make a lot of sense. otherwise we need to come up with logic that allows us to find namespaces that are not used anymore by any other running job.
