### ISSUE TITLE
Gardner unable to download kubeconfig file,CORS Issue

### ISSUE THREAD

**Issue by devikiran** [kyma-project/kyma#8715]
**Description**
Unable to download Kubeconfig of kyma cluster in any browser(chrome/firefox/safari).
browser developer console has error pointing to CORS issue

kyma-1.12.0
kubernetes-1.16.7

**Expected result**

KubeConfig file should be downloaded

**Actual result**

No action on browser,in the console errors related to CORS.

**Steps to reproduce**

Install kyma in gardner
login to kyma console
navigate to settings page(tap on top right corner settings icon)
click on the Download Config
<img width="1669" alt="Screenshot 2020-06-05 at 7 53 19 AM" src="https://user-images.githubusercontent.com/1721295/83830939-f8417000-a703-11ea-92f2-4750f26d2f07.png">

**Troubleshooting**

**Comment by akrausesap** [comment]
Download also fails in SKR version 1.13
<img width="1680" alt="Screen Shot 2020-07-09 at 15 15 15" src="https://user-images.githubusercontent.com/40229965/87044637-1d3f6c00-c1f7-11ea-99d9-391e18efb6bf.png">

**Comment by kwiatekus** [comment]
Hi @devikiran 
This issue was already fixed on master.

https://github.com/kyma-project/kyma/issues/8683#issuecomment-649448799
