### ISSUE TITLE
Enable monitoring config with kyma config overrides

### ISSUE THREAD

**Issue by hisarbalik** [kyma-project/kyma#8717]
**Description**

Not all configuration parameters of monitoring chart overridable with kyma installer config override mechanism. This limit the customisation of kyma cluster installation.

Since kyma config overrides support only string values, overriding complex data structures or list of data structures in yaml files not possible override with current charts.
 
**Reasons**

Current monitoring chart evaluating configuration parameter with functions mostly accepting only complex object structures which make configuration with kyma config-overrides not possible.

Instead of using such function, chart should use simple string evaluation functions to configure chart for individual cluster setup.

Example from monitoring grafana chart

```
{{- if .Values.notifiers }}
    {{- range $key, $value := .Values.notifiers }}
    {{ $key }}: |
  {{ toYaml $value | indent 4 }}
    {{- end -}}
  {{- end -}}
``` 
Code slice above expecting a list of complex data structure from configuration values, this will work with helm values.yaml but kyma config-overrides.

In this case, instead of using function ```range``` which expecting complex object list we can use function ```toYaml``` to evaluate values from kyma config-overrides.

**Comment by Tschis** [comment]
FYI this is also present in other places, not just monitoring. 
For example, setting up a different configuration for Loki output of Fluent-bit has the same issue.

What I want to do:
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: logging-overrides
  namespace: kyma-installer
  labels:
    kyma-project.io/installation: ""
    installer: overrides
    component: logging
data:
  fluent-bit.conf.Output.loki.config.labelMap: |-
    {
      "kubernetes": {
        "container_name": "container",
        "host": "node",
        "labels": {
          "app": "app",
          "function": "function",
          "release": "release"
        },
        "namespace_name": "namespace",
        "pod_name": "instance"
      },
      "stream": "stream",
      "logs": {
        "log": {
          "code": "log_code",
          "domain": "log_domain",
          "severity": "log_severity"
        }
      }
    }
```

But this is a JSON and therefore it also fails to parse in the `toPrettyJson` function of `/kyma/resources/logging/charts/fluentbit/templates/configmap.yaml`

**Comment by a-thaler** [comment]
Hi @Tschis, thanks for the feedback. It is a general problem across a lot of charts. I think we should not change all the charts, especially coming from an upstream chart like for loki or prometheus-operator as it will be hard to maintain. Instead, we should the way of how a kyma installation gets configured. It simply should support proper values.yaml files as input which gets applied properly to the internal helm command. Indeed, that gets discussed already in the installation working group, see also https://kyma-community.slack.com/archives/CD2HJ0E78
So I tend to rather wait for that changes instead of manipulating all the charts..

**Comment by Tschis** [comment]
Hi @a-thaler 
No problem, I don't want to imply any kind of preferred implementation, as long as a suitable solution is available :) 

Thanks for the work on it, hopefully we can have some answer soon 💪

**Comment by a-thaler** [comment]
Will be finally solved with the upcoming kyma 2 release by supporting fully values.yaml syntax of helm
