### ISSUE TITLE
Pod edit window alerts are not cleared after opening of the edit window for another pod

### ISSUE THREAD

**Issue by khodayar** [kyma-project/kyma#8725]
**Description**

In Kyma console  1.12.0, in PODs, if user edits a pod and gets and error Alert , the alert won't disappear from edit window until user navigates out of the pods view and comes back. Even the same alert is shown when user opens edit window for other pods.

Kyma version 1.12.0

**Expected result**

The alert disappears after re-opening edit window for the same or another pod
**Actual result**

User edits a pods and get an error alert, user closes the edit window (cancel) and opens edit window for another pod, the same alert is shown at the top of the edit window.
**Steps to reproduce**
Same as above

**Troubleshooting**

**Comment by kwiatekus** [comment]
Thank you for reporting @khodayar.
I noticed that the problem occurs if I click cancel. When I dismiss the modal by clicking on the backdrop, the error message is cleared
