### ISSUE TITLE
AppBrokerUpgradeTest failed with timeout

### ISSUE THREAD

**Issue by jasiu001** [kyma-project/kyma#8731]
**Description**

AppBrokerUpgradeTest failed couple times for last two weeks in the same place, on step 
["Waiting for events-service-id instance to be removed"](https://github.com/kyma-project/kyma/blob/be0b4f4e0aad9f15d38295938648decc0017d3d8/tests/end-to-end/upgrade/pkg/tests/service-catalog/base_flow.go#L282).
The timeout for this operation has already been increased (to 3 min) unfortunately the problem occurs again.
Additionally, there are no logs to find out what caused the error, e.g. ServiceInstants status.

**Expected result**

- AppBrokerUpgradeTest in step "Waiting for events-service-id instance to be removed" works less than 3 min, if an error occurs better logs are available.

**Comment by jasiu001** [comment]
I couldn't find the cause of the issue. PR [#9413](https://github.com/kyma-project/kyma/pull/9413) adds some extra logs from ServiceCatalog and improves displaying them. According to Test Grid last error occur 02.09 (twice) and since then error hasn't shown up (before 02.09 error occur many times: 28.08, 26.08, 25.08, 24.08...).

**Comment by pbochynski** [comment]
Closing as it seems to be fixed.
