### ISSUE TITLE
Improve monitoring tests to test the list of  targets

### ISSUE THREAD

**Issue by rakesh-garimella** [kyma-project/kyma#8736]
**Description**
Checking the list of available targets is tedious. We should improve the tests to validate the list of targets to be sure we have all the endpoints to scrape metrics. 

Currently in the tests we see if the targets are UP. But there can be a case when the targets are not being listed at all. Eg. `serviceMonitorSelectorNilUsesHelmValues` in values.yaml. If its set to `true` then prometheus would only list service monitors from the monitoring charts and other service monitors would be skipped. 

In order to avoid such a case we should have a list of all the service monitors we got under targets and should verify if these in our monitoring tests. As during Prometheus upgrade we can miss some during chart changes.

**Reasons**
This will ease the testing during prometheus upgrade process.

**Comment by a-thaler** [comment]
I don't get the problem and proposed solution, please describe it more specific.
Especially outline what really is missing in comparison the current monitoring test.

**Comment by rakesh-garimella** [comment]
So the issue is for example with `istio-mixer` and `istio-telemetry` service monitors. `istio-mixer` collects all the pods with target port `http-monitoring` which results in total of 7 pods (`istio-citadel`, `istio-galley`, istio-pilot x4,istio-telemetry port 15014) where as `istio-telemetry` collects pod with target port `prometheus` so only istio-telemetry port 42422 is listed

**Comment by rakesh-garimella** [comment]
This is not relevant anymore since we test for 0/0 targets.
