### ISSUE TITLE
The function has status running when Pod is initializing and is not ready

### ISSUE THREAD

**Issue by michal-hudy** [kyma-project/kyma#8765]
**Description**

When you update the function, its status should reflect the condition of it latest version. I have noted that when you update function, it is almost immediately in the running state, but when you check resources you will see that the old function is still served because the pods from the new one are for example in Init phase.

**Expected result**

The function has running state when it is fully switched to the newest version.

**Actual result**

The function has running state, but the old version is served.

**Steps to reproduce**

Create a function, and provide some updates

**Comment by aerfio** [comment]
- remember about autoscaling
- you can use the fact that the traffic should be redirected when old pods are terminated
