### ISSUE TITLE
Bump Application Broker to k8s 1.18

### ISSUE THREAD

**Issue by polskikiel** [kyma-project/kyma#8779]
**Description**

For now, we cannot migrate the application broker until its dependencies will also be updated.

~~Blocking dependencies:~~
- [~~application operator~~](https://github.com/kyma-project/kyma/blob/master/components/application-operator/go.mod#L21)
- [~~knative-eventing~~](https://github.com/knative/eventing/blob/master/go.mod#L34)

**edit**
It should be ready to update now

**Comment by a-thaler** [comment]
Please improve the description and verify if it is still valid

**Comment by pbochynski** [comment]
Is it done? Can you close it?
@janmedrek
