### ISSUE TITLE
Missing icons in navigation pane

### ISSUE THREAD

**Issue by m00g3n** [kyma-project/kyma#8796]
**Description**

Missing icons in navigation pane.

Kyma version: master, 0e2392ebc84fa7374ab9e0ff7346893114fc6596

**Expected result**
![image](https://user-images.githubusercontent.com/45931826/84644981-3b6bc200-af00-11ea-8dad-76efd5522694.png)

**Actual result**
![image](https://user-images.githubusercontent.com/45931826/84642561-ed08f400-aefc-11ea-8a87-5451c51ca95f.png)

**Steps to reproduce**
Unable to reproduce, it happen during jumping between function and application. 

**Troubleshooting**

**Comment by kwiatekus** [comment]
This should not happen anymore.
