### ISSUE TITLE
Console shows border of an empty element in namespace bindings under applications section or element is showing as empty.

### ISSUE THREAD

**Issue by m00g3n** [kyma-project/kyma#8798]
**Description**
Console shows border of an empty element in namespace bindings under applications section or element is showing as empty.

Kyma version: master, 0e2392e

**Expected result**
No border on empty element or element not empty.

**Actual result**
![image](https://user-images.githubusercontent.com/45931826/84646121-e335bf80-af01-11ea-80bd-232b014f4797.png)

**Steps to reproduce**
1. select namespace
2. click `Show All Applications`
3. Select application

**Troubleshooting**

**Comment by kwiatekus** [comment]
Must have been fixed on the way.
No longer an issue on the latest master
![Screen Shot 2020-09-15 at 12 07 32](https://user-images.githubusercontent.com/6783567/93197616-28110280-f74c-11ea-9d98-3ca982644027.png)
