### ISSUE TITLE
Kiali fails to read namespace list

### ISSUE THREAD

**Issue by m00g3n** [kyma-project/kyma#8800]
**Description**
Kiali fails to read namespace list.

Kyma version: master, 0e2392e

**Expected result**
No failures

**Actual result**

![image](https://user-images.githubusercontent.com/45931826/84648129-cfd82380-af04-11ea-9928-72e8103f7ccd.png)

![image](https://user-images.githubusercontent.com/45931826/84648146-d9fa2200-af04-11ea-919e-b3fb122d2449.png)

![image](https://user-images.githubusercontent.com/45931826/84648158-e2eaf380-af04-11ea-8b8a-a404526c3b90.png)

**Steps to reproduce**
1. Open Service-Mesh from Kyma Console

**Troubleshooting**

**Comment by a-thaler** [comment]
Works fine on nightly cluster https://kiali.nightly.a.build.kyma-project.io.
Can you please be more specific on how your setup looks like and how it is different from a regular installation via CLI.
Will close the ticket for now as I assume that the problem might be solved already on master, feel free to re-open if you can re-produce it
