### ISSUE TITLE
Eventing is not working in namespaces without istio side-car

### ISSUE THREAD

**Issue by m00g3n** [kyma-project/kyma#8804]
**Description**
When the namespace is created with kyma console, user may choose not to inject Istio side-car.
If this option is selected and user will create application and register events the eventing will not work. 

**Expected result**

- Either user should not be allowed to register events in namespace without side-car
- or eventing should work
- or user should be worn 
 

**Actual result**

Eventing will not work.

**Steps to reproduce**

1. Create namespace without Istio side-car
2. Create application
3. Register events
4. Trigger event  

**Troubleshooting**

**Comment by k15r** [comment]
With the knative based implementation of eventing in kyma being replaced it make no to little sense to change the eventing implementation itself to fix this. If a solution is still required i vote for a simple infomational popup in the UI that warns the user about the consequences of disabling istio injection in the namespace.
