### ISSUE TITLE
Change the remaining things from helm 2 to helm 3

### ISSUE THREAD

**Issue by sayanh** [kyma-project/kyma#8808]
**Description**

Some of the things which are missing from Helm 3 are as follows:
- Change apiVersion from v1 to v2
- Add dependencies instead of requirements

Impacted charts:
- knative-eventing
- knative-eventing-kafka
- event-sources

**Reasons**

Alignment with Helm3 is needed

**Comment by pbochynski** [comment]
Reopen if you still have something to do there.
