### ISSUE TITLE
Autoscaling is not working when cluster is deployed on AKS

### ISSUE THREAD

**Issue by michal-hudy** [kyma-project/kyma#8809]
**Description**

When the Kyma is deployed on AKS with a production profile, the HPA is not able to scale functions, even when it is using 100% CPU. According to events, HPA is not able to read metrics:
```
  Type     Reason                        Age                From                       Message
  ----     ------                        ----               ----                       -------
  Warning  FailedGetResourceMetric       13m (x3 over 14m)  horizontal-pod-autoscaler  unable to get metrics for resource cpu: no metrics returned from resource metrics API
  Warning  FailedComputeMetricsReplicas  13m (x3 over 14m)  horizontal-pod-autoscaler  Invalid metrics (1 invalid out of 1), last error was: failed to get cpu utilization: unable to get metrics for resource cpu: no metrics returned from resource metrics API
  Warning  FailedGetResourceMetric       12m (x6 over 14m)  horizontal-pod-autoscaler  did not receive metrics for any ready pods
  Warning  FailedComputeMetricsReplicas  12m (x6 over 14m)  horizontal-pod-autoscaler  Invalid metrics (1 invalid out of 1), last error was: failed to get cpu utilization: did not receive metrics for any ready pods
```

**Expected result**

Function is scaled under high load.

**Actual result**

The function is not scaled, even under high load:
![image](https://user-images.githubusercontent.com/26445970/84702794-7e0cb900-af57-11ea-9313-b2613cb17178.png)

**Steps to reproduce**

Expose the function with `allow` rule and execute performance tests:
```bash
ab -n 1000 -c 100 https://{ADDRESS_TO_EXPOSED_FUNCTION}
```

**Comment by michal-hudy** [comment]
It is looking like it doesn't work on other platforms too - for example, GKE.

**Comment by michal-hudy** [comment]
Ok, I have found the root cause of the problem. Deployment has selector that matches also pod created for the build's job. Because of that autoscaling is not working. As a quick solution, we can add a label with resource type and use it in deployment and service selectors.

**Comment by michal-hudy** [comment]
Another problem is that the HPA takes the sum of resources assigned to all containers in a pod, so Istio Sidecar is also taken into account. It is a problem when Kyma is deployed with a production profile - HPA thinks that CPU usage is really low because Istio Sidecar has a pretty big limit. So, we need to find a different autoscaler that can monitor a particular container in a pod.

**Comment by evilyeti** [comment]
For event triggers - we can explore [KEDA](https://github.com/kedacore/keda). 
For HTTP requests - it's a regression though. Isn't the clean container CPU usage available as a custom metric from the metric server? Although that's a corner case, as you can't generically say whether a container actually works fine in isolation from the other sidecars in the pod...

**Comment by michal-hudy** [comment]
So generally HPA is not supporting this (https://github.com/kubernetes/kubernetes/issues/86349), we need to check other autoscalers, but I will create a separate story for that.
