### ISSUE TITLE
Kyma uninstallation

### ISSUE THREAD

**Issue by pbochynski** [kyma-project/kyma#8816]
**Description**
Kyma components should be easily removable. Each module should uninstall cluster resources when the helm release is deleted. Requirements:
- [x] Custom Resource Definitions are deleted with cluster essentials module
- [x] namespaces are removed when the main module is deleted
- [x] the CI pipeline should test if there are leftovers after install -> delete sequence
- [x] the flow install -> delete -> install should work (pipeline) 

**Reasons**
Customers expect the k8s cluster can be easily deleted or reused after Kyma removal. Experimenting with Kyma without the necessity of creating and destroying k8s cluster also improves the developer's experience.

**Comment by strekm** [comment]
https://github.com/kyma-project/kyma/issues/10297
