### ISSUE TITLE
Document minimal set of components (or clarify that Kyma Lite is that)

### ISSUE THREAD

**Issue by toabi** [kyma-project/kyma#8825]
**Description**

After reading the documentation, it is not clear if Kyma Lite is the minimal set of components or if they can be reduced further.

**Reasons**

We like to mainly use Service Catalog and Helm Broker. We would probably not need all other components directly, but it's not clear if a deployment with less components would be possible.

**Comment by kazydek** [comment]
Will be handles as a part of https://github.com/kyma-project/kyma/issues/9224.

**Comment by klaudiagrz** [comment]
@kazydek There is also this Kyma Trial plan that should also be documented. Will this also be a part of #9224 ?

**Comment by kazydek** [comment]
@klaudiagrz as discussed, pls log a separate for documenting Kyma Trial plan and any other variants. What I meant here is that we should in general describe which components are absolutely necessary for Kyma to work, which are obligatory, and which are codependent. In my opinion, the way they can be combined together for different scenarios and uses is a separate thing.

**Comment by klaudiagrz** [comment]
I've just logged a separate issue to document Kyma Lite and Kyma Trial: https://github.com/kyma-project/kyma/issues/9253

**Comment by pbochynski** [comment]
We need to remove Kyma Lite.

**Comment by pbochynski** [comment]
The progress can be tracked here: #9224
