### ISSUE TITLE
Adjust Application Connector tests to new target scenario

### ISSUE THREAD

**Issue by Szymongib** [kyma-project/kyma#8855]
**Description**

Adjust Application Connector tests to new target scenarios and enable them.
Application Connector tests were disabled in #8854 due to their instability and the fact that they do not test the target scenario.
Tests should be adjusted to the new scenario or removed (if all cases already covered).

**Todos:**
- Remove duplicated tests scenarios
- Adjust the cases not covered by different tests
- Enable tests

**Comment by pbochynski** [comment]
Closed due to inactivity
