### ISSUE TITLE
Broken link and missing documentation on events subscription and eventActivation

### ISSUE THREAD

**Issue by yarivlifchuk** [kyma-project/kyma#8915]
**Description**
1. Broken link on event-subscription
https://github.com/kyma-project/examples/blob/master/event-subscription/service/README.md
2. Missing documentation on event-subscription and eventActivation.

Could not find how to retrieve sourceId in those CRDs.
Could not find examples of event-subscription and eventActivation.

**Comment by pbochynski** [comment]
@anishj0shi Please check this example

**Comment by anishj0shi** [comment]
These links are retired since Kyma 1.11.
If you need an e2e tutorial for consuming events. Please follow this tutorial: https://kyma-project.io/docs/components/serverless/#tutorials-tutorials
