### ISSUE TITLE
Kyma installation stuck on Installation source checked

### ISSUE THREAD

**Issue by kvaps** [kyma-project/kyma#8919]
**Description**

```
Kubernetes v1.18.4
Kyma CLI version: 1.13.0
Helm version: v3.2.4 (or v2.16.9)
```

```bash
# kyma  install -vvvvv
- Cluster info read
- Configurations validated
  Installing Kyma in version '1.13.0' 
- Installation source checked
```

**Expected result**

Installation is working

**Actual result**

Installation is stuck

**Steps to reproduce**

Run `kyma  install`

**Troubleshooting**

I've tried both helm2 and helm3 binaries with the same result.

**Comment by kvaps** [comment]
Fixed by:
```
kubectl -n kube-system create serviceaccount tiller

kubectl create clusterrolebinding tiller \
  --clusterrole=cluster-admin \
  --serviceaccount=kube-system:tiller

helm init --service-account tiller
```

Anyway I'm sure that more informative message required, also the [documentation](https://kyma-project.io/docs/root/kyma#installation-install-kyma-locally-install-kyma) says nothing, about the fact kyma depends on helm2 with tiler

**Comment by kvaps** [comment]
Got it!

Problem was in using wildcard record for my search domain in dns.

**Comment by kvaps** [comment]
Okay next stuck is dex:

```
- Cluster info read
- Configurations validated
  Installing Kyma in version '1.13.0' 
- Installation source checked
- Tiller deployed
- Installation files loaded
- Kyma Installer deployed
- Helm configured
- Kyma Installer is installing Kyma
- Waiting for installation to start
- install component cluster-essentials
- install component istio
- install component xip-patch
- install component istio-kyma-patch
- install component knative-serving-init
- install component knative-serving
- install component knative-eventing
- install component dex
```

**Comment by kvaps** [comment]
I installed csi-provisioner and volume was succefully provisioned, now istio blocking communication between pods for some resoin

**Comment by a-thaler** [comment]
Hi @kvaps, thanks for sharing your findings here. About your initial problems with tiller: these will be fixed as we are currently migrating the installer to helm3, getting rid of the tiller dependency.
In general I see that the output of the CLI needs to be improved and I already created a ticket for that: https://github.com/kyma-project/cli/issues/498

So does the installation finally succeeded for you and communication for new applications is blocked?

**Comment by kvaps** [comment]
No it isn't, I'm using [kube-router](https://github.com/cloudnativelabs/kube-router) CNI with [service-proxy](https://github.com/cloudnativelabs/kube-router#ipvslvs-based-service-proxy----run-service-proxy) mode for IPVS (in fact it fully replaces kube-proxy).

But kyma installation wasn't successful for me due to fact of istio-sidecar injector breaks my pod networking somehow.
Sorry, but I had no time to investigate this yet.

---

I can share my thoughts about installation process, if you want to. This is my own opinion, not a guide to action, but I have some experience and I think you would be interested to hear it. 🙂

I would like to have some standardized installation method, eg. Helm chart would be enough for describe whole deployment.
I think you don't need any special binaries or CRD's to manage Kyma installation lifecycle. 
Helm charts should fully fit into your needs. They can be easily included into single meta chart recursively. You can use the tags to enable or disable specific components, this is working out-of-box, easy to maintain and support.

I can append that I like how [wire-server](https://github.com/wireapp/wire-server-deploy) organized their deployment repo and very simple [docs](https://docs.wire.com/how-to/install/helm.html#how-to-install-wire-server-itself). I think this is very good example how it should be done.

I do not want to say that your method is bad, but I would prefer an helm chart for the kyma installation.
Thank you for your attention 🙂

**Comment by a-thaler** [comment]
Thanks for sharing your thoughts. I agree that the installation must be something more lightweight and easy to use. We are currently started discussions and investments around the installation topic, see also the regular meetings in https://kyma-community.slack.com/archives/CD2HJ0E78. Feel free to join or share your thoughts in a written form.

**Comment by colunira** [comment]
@kvaps, @a-thaler Can we close this issue?

**Comment by kvaps** [comment]
I have no option to check this right now.

Reopen issue if repeated
