### ISSUE TITLE
Stabilize kyma-gardener-azure jobs

### ISSUE THREAD

**Issue by franpog859** [kyma-project/kyma#8964]
**Description**

The success rate of the `pre-master-kyma-gardener-azure-integration`, `kyma-integration-gardener-azure` and `kyma-upgrade-gardener-azure` jobs oscillates on about 7% and that's super low
The `pre-master-...` job is optional so it doesn't block the PRs and therefore it's not super critical to stabilize it

**Expected result**

`...gardener-azure...` jobs are stable, the success rate is about 90% or more and it's marked as required in the CI

**Actual result**

They are not stable at all. Or you can say they are really stable but in the wrong way 

**Steps to reproduce**

Create a PR to the [Kyma repo](https://github.com/kyma-project/kyma) and look for the `pre-master-kyma-gardener-azure-integration` job failing

**Troubleshooting**

I found that the unstable components are for example: `console-backend`, `console-web`, `serverless`, `application-connector`, `application-operator`, `connection-token-handler`, `service-catalog`. I think one of the possible reasons could be the `--concurrency=5` I found in the `kyma-integration-gardener-azure` job

**Comment by pbochynski** [comment]
The issue can be closed after introducing [fast integration tests](https://github.com/kyma-project/kyma/issues/10050). There are new jobs for azure:
- https://status.build.kyma-project.io/job-history/kyma-prow-logs/logs/kyma-integration-evaluation-gardener-azure
- https://status.build.kyma-project.io/job-history/kyma-prow-logs/logs/kyma-integration-production-gardener-azure
