### ISSUE TITLE
Services are not available in Service Catalog

### ISSUE THREAD

**Issue by arvindtilotia** [kyma-project/kyma#8965]
1. After connecting my FSM company to Kyma through kyma connector. I am able to see below 10 services at application page.
![image](https://user-images.githubusercontent.com/45191955/86579709-4bc10b00-bf9b-11ea-8e41-55f417350b8d.png)

2. but when i go to service catalog page to start a service.. i dont find any services there. It was working around a month back when i last tested it. 
![image](https://user-images.githubusercontent.com/45191955/86580092-ddc91380-bf9b-11ea-8086-e9fc1fc23000.png)

**Comment by PK85** [comment]
Hello @arvindtilotia 

Please check runtime agent logs.

**Comment by arvindtilotia** [comment]
Hi 

This issue seems to be intermittent as when i tried after sometime everything worked fine.
version - 1.7.1
