### ISSUE TITLE
Adjust general Kyma content

### ISSUE THREAD

**Issue by derberg** [kyma-project/kyma#898]
**Description**

- in https://github.com/kyma-project/kyma/ readme, overview section just write 
   ```
   A flexible and easy way to connect and extend enterprise applications in a cloud-native world
   ```
   and link to kyma-project website
- modify existing overview doc from kyma/docs/kyma by removing it and replacing with https://github.com/kazydek/test_repository/blob/785d2ddf50b557fbf09a42553ce67f00541d7729/landing-page/landing-page.md#why-kyma. Each section must be a separate file with type `Overview` and title same as the header from existing document
 
**Reasons**

Implement result of https://github.com/kyma-project/kyma/issues/611

**Comment by kazydek** [comment]
While [this](https://github.com/kyma-project/kyma/pull/1162) PR was awaiting successful CI job build, the docu image was updated in [this](https://github.com/kyma-project/kyma/pull/1142) PR.
