### ISSUE TITLE
Kubelet grafana dashboard broken on AKS cluster

### ISSUE THREAD

**Issue by hisarbalik** [kyma-project/kyma#8983]
**Description**

Kubelet metrics are not visible on grafana kubelet dashboard. Metrics are scraped and stored correctly but the queries for dashboard are not valid.

**Expected result**

Kubelet dashboard visualize scraped metrics about kubelet and cluster.

**Actual result**

Kubelet dashboard charts are empty (showing no data)

**Troubleshooting**

It seems all queries are broken like query parameter **mertic_path** not exist, instead use query parameter **endpoint**

**Comment by a-thaler** [comment]
Probably will be fixed by https://github.com/kyma-project/kyma/issues/8979
