### ISSUE TITLE
Running kyma on kind-cluster

### ISSUE THREAD

**Issue by fabstu** [kyma-project/kyma#9005]
**Description**

I would like to run kyma on a local [Kubernetes/kind](https://github.com/kubernetes-sigs/kind) cluster. Kind is an alternative to minikube. Kind runs Kubernetes locally inside docker containers.

**Reasons**

It is the same use case as minikube. Kind is focused on deployment in docker containers and simple to use. Using it helps people having issues with minikube.

**Comment by pbochynski** [comment]
You can try k3s instead: https://github.com/kyma-incubator/local-kyma-k3d
