### ISSUE TITLE
Local instalation on minikube hangs on step `logging`

### ISSUE THREAD

**Issue by dbadura** [kyma-project/kyma#9008]
**Description**
Installing Logging in Compass hangs

When I execute [run.sh](https://github.com/kyma-incubator/compass/blob/master/installation/cmd/run.sh) the instalation on my local computer hangs on step `logging`.

Here are the logs:
```
» kubectl logs -n kyma-system logging-loki-0 loki
Could not initialize jaeger tracer: dial udp [::1]:6831: connect: cannot assign requested address
```

**Expected result**

Instatalation finishes successfully

**Actual result**
Instalation of logging hangs.

**Steps to reproduce**
Execute `run.sh` script.
I used following version of kyma:
```
kyma version
Kyma CLI version: stable
Kyma cluster version: master-5b367c59
``` 

MInikube version:
`1.6.6x` 

**Troubleshooting**

**Comment by a-thaler** [comment]
We were not able to reproduce it and no one else reported it. please re-open if it happens again and provide us more details on: which pods are not starting up and what is the error condition for the pod (reason attribute, exit code)
