### ISSUE TITLE
Sync Ory charts with ory/k8s repo

### ISSUE THREAD

**Issue by jakkab** [kyma-project/kyma#9020]
**Description**

Update Ory charts to reflect recent changes in the ory/k8s repo.

Caveats: 

- adopt the 'existing secret' mechanism (it should replace our custom logic, it is pretty similar anyways);
- find a way to access encryption keys (`.Values.hydra.hydra.config.secrets.system/cookie`) in our custom migration script (https://github.com/kyma-project/kyma/blob/master/resources/ory/files/secret-migration.sh). When Helm renders templates, those values are unset (see https://github.com/ory/k8s/blob/master/helm/charts/hydra/templates/_helpers.tpl#L107) to avoid saving unencrypted secrets to the Hydra configmap (encryption keys are part of the `config` tree in the values.yaml file).

Possible solutions:
- move the script to a dedicated subchart so that it gets rendered before the configmap in the Hydra chart unsets the values;
- ???

**Reasons**

Keeping Kyma up to date with ory/k8s repo to facilitate future updates.

**Comment by strekm** [comment]
need to push it to 1.20

**Comment by Tomasz-Smelcerz-SAP** [comment]
The latest release for `ory/k8s` containing ORY Helm charts is `v0.5.5`,  15 March 2021
This features:
- Hydra v1.8.5
-  Hydra-Maester v0.0.19
- Oathkeeper v0.38.5
- Oathkeeper-Maester v0.38.5

**Comment by Tomasz-Smelcerz-SAP** [comment]
Charts are synced. Closing the issue
