### ISSUE TITLE
Update fluentbit grafana dashboard and have recommend alert rule

### ISSUE THREAD

**Issue by a-thaler** [kyma-project/kyma#9029]
**Description**
Fluentbit has an official grafana dashboard now which should be bundled.
Furthermore it brings a recommended alert rule which as well should be configured out of the box as it will indicate a non-functional fluentbit configuration.
See https://docs.fluentbit.io/manual/administration/monitoring#dashboard-and-alerts

**Reasons**

Improve operations of fluentbit
**Attachments**

**Comment by suleymanakbas91** [comment]
Covered by https://github.com/kyma-project/kyma/issues/10110.
