### ISSUE TITLE
Disappearing ServiceBindingUsage 

### ISSUE THREAD

**Issue by brendandobbs** [kyma-project/kyma#903]
**Description**

The ServiceBindingUsage instances are somehow being removed for the Service Instances. No one has triggered the deleting of the ServiceBinding or ServiceBindingUsage from the UI.

I can see the ServiceBinding for the Service Instance is still there e.g.

`$ kubectl get ServiceBindings
NAME                                                AGE
azure-mysql-5-7-instance-binding                    17d
ec-all-events-new-instance-binding                  18d
ec-ycommercewebservices-v2-cc88c-instance-binding   18d
mbrribuffq                                          5d
`

However the ServiceBindingUsages are gone.....

`$ kubectl get ServiceBindingUsage
No resources found.`

Here is what you see in the UI.....

![missing-sbu2](https://user-images.githubusercontent.com/5688693/45955875-f5264f00-c008-11e8-887e-1eae597a32a6.png)

You can contact me directly for access to the specific cluster.

**Comment by PK85** [comment]
Hello Brendan,
to what have you bounded, lambda? When lambda is gone, also SBU is deleted.

**Comment by PK85** [comment]
Ok I found an issue, lambda UI causing deletion of all SBUs. Create two lambda bind them to one redis, remove one lambda, both SBUs are gone.
