### ISSUE TITLE
Update the document about Application CR

### ISSUE THREAD

**Issue by klaudiagrz** [kyma-project/kyma#9032]
**Description**

The document about the [Application CR](https://kyma-project.io/docs/master/components/application-connector#custom-resource-application) doesn't reflect the new approach (the Compass mode with API Packages). There are some fields that are no longer used in the new approach (e.g. **spec.accessLabel**) and there are also some new ones added. We need to have the Application CR documented for both legacy mode and the Compass mode, together with the complete fields descriptions. 

**Reasons**

Documentation must be up-to-date and reflect the current state.

**Related issues:**
https://github.com/kyma-project/kyma/issues/9033

**Comment by pbochynski** [comment]
We are going to refactor Application CR - see the issue https://github.com/kyma-project/kyma/issues/9127
