### ISSUE TITLE
Document legacy and Compass modes for Application Connector and its components

### ISSUE THREAD

**Issue by klaudiagrz** [kyma-project/kyma#9033]
**Description**

As we support both legacy mode and Compass mode, we need to document these two approaches, point out when do we use which approach, and what are the differences between them. It would be best to have the modes documented/mentioned in a visible place, for example in the Application Connector overview section. 

Also, since there are many differences depending on the approach, it would be a good idea to completely divide the documentation related to the legacy mode from the documentation related to the Compass mode. In such a case, we can have two separate topics for the Application Connector in the left navigation panel on the website (see the attachment). Such a separation would be more clear from the UX point of view. 

**Reasons**

For now, there is no overall document about the modes in which we use Application Connector and its components. There are only some mentions about the modes in the components' docs, which may be misleading for the users. 

**Attachments**

We can have two topics for the Application Connector in the left navigation panel: one for the legacy mode, and another one for the Compass mode.

![app-connector](https://user-images.githubusercontent.com/35192450/87432595-8143a500-c5e8-11ea-9aa1-3d2882a81762.png)

**Comment by klaudiagrz** [comment]
**AC:**
- [ ] Create separate documentation topics for both Application Connector modes
- [ ] Update the overview documents in both topics describing each mode in general
- [ ] Document how these components work in the Compass mode:
  - Connector Service
  - Application Gateway
  - Application Broker
- [ ] Document how these components work in the Compass mode:
  - Application
  - ApplicationMapping
  - EventActivation
  - TokenRequest
- [ ] Remove the Compass mode references from the legacy mode documentation

**Comment by janmedrek** [comment]
This will be handled in new App Connector 2.0 documentation: https://github.com/kyma-project/kyma/issues/11047
