### ISSUE TITLE
Update security section

### ISSUE THREAD

**Issue by piotrmsc** [kyma-project/kyma#9036]
**Description**

Documentation for the security domain is outdated and incomplete. It needs fresh update with couple of new items. 
Users don't exactly know how does user authentication and authorization works. What kind of token is used etc.

AC : 

- User authentication and authorization in kyma described
  - Dex explained with diagram showing flows including console, apiserver-proxy.
  - Token type described - we use JWT
  - Authorization based on RBAC explained, static bindings by email or groups mentioned
- User interaction with kyma resources explained
  - Kyma kubeconfig + apiserver-proxy explained with diagrams.  How does the kyma kubeconfig look like
  - How is apiserver-proxy exposed, external LB explained and mentioned in the diagram.
  - Cloud provider access aka admin god mode
- Authentication & Authorization in API Gateway
 - Does not need to be described here, can be linked to API Gateway component
- How we manage ingress TLS certificates explained
  - Where to look for it in the kyma
- Ingress and Egress traffic explained - link to service-mesh docs if already documented there.

  

**Reasons**

It is not straightforward and easy to read. We should redesign document and cover all the most important parts.

**Attachments**

**Comment by sergio-oss** [comment]
A couple of stories already define some potential improvement to docs (they are documented in SAP docs, but probably not in the Open Source):
https://github.tools.sap/kyma/backlog/issues/123
https://github.tools.sap/kyma/backlog/issues/70
https://github.tools.sap/kyma/backlog/issues/122

**Comment by pbochynski** [comment]
@piotrmsc @Demonsthere Any reason to keep it open?

**Comment by piotrmsc** [comment]
No, it's already done, closing it.
