### ISSUE TITLE
URL of API Rule can't be access immediately

### ISSUE THREAD

**Issue by MingZhang-PS** [kyma-project/kyma#9047]
**Description**

When I created an typical nginx app, I could see the deployment, service and APIRule were created successfully from Kyma console UI. 
However, when I clicked the URL of this APIRule from Kyma console UI, it shown error like "no healthy upstream" or HTTP 404.
I have to keep refreshing the web page, and the URL of the APIRule is accessible only after about 10 seconds later.

Kyma version: 1.12.0
Kyma Cluster: https://console.kongfu.kaka.shoot.canary.k8s-hana.ondemand.com/ (it is on GCP, and provisioned via Gardener)
Kubernetes version: 1.15.12
Browser: Chrome

My app deployment manifest is simple, just a nginx server
[nginx.yaml.TXT](https://github.com/kyma-project/kyma/files/4929167/nginx.yaml.TXT)

**Expected result**
I hope the API Rule visible only after the routing under istio is setup completely.

**Actual result**
The API rule appears on Kyma console UI even the routing underneath is not setup completely

**Steps to reproduce**
Click the "Deploy new resource" button in any namespace and select the [nginx.yaml.TXT](https://github.com/kyma-project/kyma/files/4929167/nginx.yaml.TXT)
![image](https://user-images.githubusercontent.com/20200532/87627204-c25ec500-c760-11ea-93e0-fa12311c91f9.png)

**Comment by pbochynski** [comment]
This is eventual consistency in Kybernetes. Service can be available later.
