### ISSUE TITLE
Remove Knative-Serving

### ISSUE THREAD

**Issue by anishj0shi** [kyma-project/kyma#9048]
with #9037 we'll switch the http-adapter's type from ksvc to *Deployment*. which makes knative-serving charts completely unused from kyma's perspective. To ensure we use as less resources as possible. We are proposing to remove knative-serving chart from kyma.

**AC**
- [x] Remove knative-serving charts
- [x] Provide cleanup script for removal of crds
- [ ] Remove references of ksvcs in test.
- [x] Documentation Update to Notify Removal of Knative-Serving charts and intimate on taking ksvcs backup.

**Comment by k15r** [comment]
I did an quick inventory check where serving is referenced:
- [ ] knative-serving-test
- [ ] components/application-operator/charts/application/templates/authorization-policy.yaml
- [ ] components/console-backend-service
- [ ] components/permission-controller/Makefile
- [ ] components/service-binding-usage-controller/examples/usage-kind/function.yaml
- [ ] resources/cluster-users
- [ ] knative-eventing: some clusterroles have permissions to watch ksvcs

**Comment by k15r** [comment]
it also seems that knative eventing internally uses some serving functionality, this should not be an issue for us, but it might be solved once we upgrade knative-eventing

**Comment by bszwarc** [comment]
I already added a migration guide placeholder here: https://github.com/kyma-project/kyma/tree/master/docs/migration-guides so we can add the necessary information prior to 1.16

**Comment by k15r** [comment]
Removing the references from the tests shall be tracked here: #9693
