### ISSUE TITLE
Dockerfile presets for functions 

### ISSUE THREAD

**Issue by kwiatekus** [kyma-project/kyma#9055]
**Description**

Allow developers to skip dockerfile definition for their lambda functions. 
Lambda Function developer should only specify the source of the function code (git repository) and select one of the languages (with versions), ie:
 - **nodejs 12**
 - **nodejs 10**
 - **nodejs 8**
 - python 3.8 
 - ...

For those three runtimes we should provide a dockerfile out of the box, so that developer doesnt need to care about it.
If the repository contains dockerfile, it should overwrite the predefined one.

**Reasons**

Convenience for true serverless DevX
"Just run my node/go/pyhton code, I don't care how exactly"

**Comment by kwiatekus** [comment]
Start with nodeJS support

**Comment by aerfio** [comment]
Things to do:
- add new field to spec, e.g. "runtime", which value has to equal to the name of configmap with proper labels
  - this has to be somehow validated by webhook at runtime
- discuss whether we really need to enable users to bring their custom dockerfiles -> it brings A LOT of complexity, besides it goes against the idea of serverless and managed runtime, and we cannot guarantee that we'd somehow not brake anything during upgrade etc
- add more points here

**Comment by aerfio** [comment]
After some internal discussions we've chosen to implement following runtimes for now:
- python 3.7.5
- nodejs 10
- nodejs 12

**Comment by aerfio** [comment]
Update: we need to use 3.8.5 due to security issues...
