### ISSUE TITLE
Application Gateway - requestTimeout and proxyTimeout parameters

### ISSUE THREAD

**Issue by VishnAndr** [kyma-project/kyma#9068]
**Description**
Request to expose **requestTimeout** and **proxyTimeout** parameters in application operator for application gateway component.
Or even better make it configurable in console UI on application level / namespace level.

**Reasons**

By default, the application gateway component is created with **requestTimeout** and **proxyTimeout** set as 10 seconds.

Sometimes an external (connected via application connector) system is not fast enough and can not process the request within 10 seconds interval.

An example is SAP Cloud for Customer system, where POST or PATCH operations may include synchronous execution of workflows, custom enhancement logic or external system calls.

**Attachments**

[Slack thread about the issue](https://kyma-community.slack.com/archives/CD0K2NSQZ/p1594886966112900)

**Workaround**
Directly edit `<appName>-application-gateway` deployment with
`$ kubectl edit deployment <appName>-application-gateway`
then change
.spec.template.spec.containers.args : 
        - --requestTimeout=10
        - --proxyTimeout=10
to the required values.

Or 
`$ kubectl get deployment <appName>-application-gateway -o yaml >> <appName>-application-gateway.yaml`
then change the same requestTimeout and proxyTimeout to the required values in the `<appName>-application-gateway.yaml` file
then apply the changes with
`$ kubectl apply -f  <appName>-application-gateway.yaml`

**Comment by VishnAndr** [comment]
Or maybe combine them into one parameter? I personally can't imagine the case where two separate parameters with different values would be required.

**Comment by ralikio** [comment]
We have just finished implementation of mechanism that allows to override helm configuration when creating application CRD.  The feature uses labels to provide new values for selected parameters. The details can be seen in the video attached to the description of https://github.com/kyma-project/kyma/pull/10289.

**Comment by VishnAndr** [comment]
@ralikio great!! Thank you! Is it going to be in 1.19 or 1.20?
