### ISSUE TITLE
Application Gateway - Retry should be optional

### ISSUE THREAD

**Issue by VishnAndr** [kyma-project/kyma#9069]
**Description**
Request to make the retry in the application gateway optional.

**Reasons**

If the call to the external system times out (execution time is more than **proxyTimeout**), the call fails with error message `context deadline exceeded` in the application gateway logs.
And immediately the retry starts again.

Such behaviour might not be desired in case of creation (POST) or update (PATCH) of an object in an external system.
Actually, if the creation or the update takes longer than the **proxyTimeout**, these retries will cause either multiple identical objects created or multiple updates happened in the target system. 
 
**Attachments**

- There was a Slack thread about the issue but the link is no longer working 

**Workaround**
Increase timeout parameters as described in the workaround in [Application Gateway - requestTimeout and proxyTimeout parameters](https://github.com/kyma-project/kyma/issues/9068) to avoid retries.

**Comment by VishnAndr** [comment]
Or maybe the retry should not happen at all? Leave it to the client to decide?

**Comment by VishnAndr** [comment]
Any progress through milestones?

**Comment by VishnAndr** [comment]
Not stale

**Comment by koala7659** [comment]
Closing as we migrate to new module architecture. We might want to include this feature into app-connector-module
