### ISSUE TITLE
Investigate why test-e2e-external-solution-evaluate-tests doesn't work and fix it

### ISSUE THREAD

**Issue by magicmatatjahu** [kyma-project/kyma#9081]
**Description**

At the moment we have a two upgrade tests: `e2e-upgrade-test`, which tests resources between releases (or release -> master), and also we have `test-e2e-external-solution`, which tests certificates between releases. The second currently is disabled on master, because it doesn't work at all and here are a example logs from job:

https://storage.googleapis.com/kyma-prow-logs/pr-logs/pull/kyma-project_kyma/9044/pre-master-kyma-gke-upgrade/1284000096215633920/build-log.txt

AC:
- investigate problem, fix it and enable the test.

**Steps to reproduce**

Enable `test-e2e-external-solution-evaluate-tests` test and you should see the errors like in mentioned logs.

> NOTE: The upgrade tests have not worked since work from 2 Jun, so probably we have a breaking changes in some parts of Kyma and by this, test is broken.

**Comment by pbochynski** [comment]
There is a new initiative to replace these tests with #10050
