### ISSUE TITLE
Helm broker timeout on connection to etcd

### ISSUE THREAD

**Issue by mwieczorek** [kyma-project/kyma#910]
**Description**
Helm broker should handle bad configuration of etcd url. Right now it looks like it has no timeout on connection to etcd and no information is in the logs about problems with connecting to etcd.

**Expected result**
- helm broker in logs provides information about failed (f.e. timeout) connection to etcd. 

It would be even better to 'fail fast' so check the connection to etcd on startup or even implement some 'health check' like in service catalog

**Actual result**
- no information about failed connection to etcd in logs. 

**Steps to reproduce**
- Put bad etcd url in helm-config-map
- try to create instance using class from helm broker

**Troubleshooting**

**Comment by lszymik** [comment]
There was already several improvements in that area. Please re-open if you still have such an issue.
