### ISSUE TITLE
Remove support for TLS 1.1

### ISSUE THREAD

**Issue by sergio-oss** [kyma-project/kyma#9103]
**Description**

TLS 1.1 is still supported and could potentially be vulnerable to some security vulnerabilities. TLS support in most common browsers and HTTP clients includes TLS 1.2+ support.

**Reasons**
In order to avoid potential security vulnerabilities, remove support for TLS 1.1. Only TLS 1.2+ should be supported

**Attachments**

None

**Comment by a-thaler** [comment]
@sergio-oss please use proper issue template in future when creating a ticket
