### ISSUE TITLE
Migrate to new Istio Authentication API in application-broker

### ISSUE THREAD

**Issue by kubadz** [kyma-project/kyma#9104]
**Description**

Application-broker uses Istio Policy, which is deprecated in Istio 1.5. Instead, it should use new Custom Resources: `PeerAuthentication` (for mtls configuration) and `RequestAuthentication` (for end-user-authentication). To ensure that upgrade won't break any configurations, existing old resources should also be migrated.

**Reasons**

Istio 1.5 introduces new Custom Resources: `PeerAuthentication` and `RequestAuthentication`, which are replacing the alpha version of the Authentication API (Policy CR). Usage of the old resources is deprecated and support for them will be removed from Istio in next releases.

**Comment by ksputo** [comment]
See:
- https://istio.io/latest/news/releases/1.5.x/announcing-1.5/upgrade-notes/#authentication-policy
- https://istio.io/v1.5/docs/tasks/security/authentication/authn-policy/

**Comment by sayanh** [comment]
The merging of #9419 is dependent on #8898 which needs time to be finalized. Hence this is blocked for now.
