### ISSUE TITLE
Migrate to new Istio Authentication API in event-sources

### ISSUE THREAD

**Issue by kubadz** [kyma-project/kyma#9105]
**Description**

Event-sources component uses Istio Policy, which is deprecated in Istio 1.5. Instead, it should use new Custom Resources: `PeerAuthentication` (for mtls configuration) and `RequestAuthentication` (for end-user-authentication). To ensure that upgrade won't break any configurations, existing old resources should also be migrated.

**Reasons**

Istio 1.5 introduces new Custom Resources: `PeerAuthentication` and `RequestAuthentication`, which are replacing the alpha version of the Authentication API (Policy CR). Usage of the old resources is deprecated and support for them will be removed from Istio in next releases.

**Attachments**

**Comment by k15r** [comment]
waiting for #8898 to be merged
