### ISSUE TITLE
jaeger virtual service gateway name not correct form

### ISSUE THREAD

**Issue by mikosa** [kyma-project/kyma#9172]
**Description**
The virtual service created for jaeger creates an error as the gateway name does not have the correct form
  - {{ .Values.global.istio.gateway.name }}.{{ .Values.global.istio.gateway.namespace }}.svc.cluster.local

https://github.com/kyma-project/kyma/blob/ebba2b677cd37658cef54db2bc9c87fa4019015e/resources/tracing/templates/kyma-additions/kcproxy-virtualservice.yaml#L11

**Expected result**

I expect the gateway name to be in the form
Gateway_name.Namespace

**Actual result**

**Steps to reproduce**

**Troubleshooting**

I am solving this by editing the vs manually

**Comment by mikosa** [comment]
https://github.com/kyma-project/kyma/pull/9173

**Comment by a-thaler** [comment]
@mikosa thanks for reporting the problem. I agree that jaeger is using the old notation and should be adjusted. However, the new notation is used already in dex and should be fine. Can you be more detailed on what errors you see where?

**Comment by mikosa** [comment]
you are right. I did not know that the format found in dex vs works.
I removed dex. 
so only Jaeger needs modifying :)
thank you

**Comment by a-thaler** [comment]
Fixed by using improved naming convention gateway_namespace/gateway_name
