### ISSUE TITLE
Create a dashboard to understand the CPU/memory usages for tests

### ISSUE THREAD

**Issue by sayanh** [kyma-project/kyma#9177]
**Description**

As a result https://github.com/kyma-project/kyma/issues/9059#issuecomment-668135631, it was observed the need to track the CPU/memory usages of the pods in the clusters while the tests are being executed. The metrics need to visualized in some sort of dashboard(may be test grid?).

I think we need to disable parallel execution of the tests to get metrics.

**Reasons**

This is to track the tests on their resource consumption.

**Comment by pbochynski** [comment]
Closed due to inactivity.
