### ISSUE TITLE
Profile test console-backend

### ISSUE THREAD

**Issue by sayanh** [kyma-project/kyma#9178]
**Description**

As a result of https://github.com/kyma-project/kyma/issues/9059#issuecomment-668135631, it is critical to understand the following with respect to the test:
- Why CPU usage of the cluster pods goes high?
- How much load API server is into during the test?
- Are the retries using exponential or constant backoff? Exponential backoffs should be the way to go easy on the kube API server.
- Are there any ways to fix it?

**Reasons**

It is important to understand why and whether the reasons are worth having it.

**Comment by kwiatekus** [comment]
> * How much load API server is into during the test?

We did an experiment and disabled console chart (console-web, console-backend) on prow jobs
https://github.com/kyma-project/kyma/pull/9294

In this setup CBS was disabled and therefore was not syncing with API server.
This made all the tests ( other than cbs tests and console tests) stable.

As a next step, we would like to separate tests that require console chart from those which doesnt.
We;d ike to install console chart (incl. cbs) only for test suites that require it.

**Comment by kwiatekus** [comment]
We found a lot of redundant tests and cleand them up:
https://github.com/kyma-project/kyma/pull/9848
