### ISSUE TITLE
Profile test core-test-external-solution 

### ISSUE THREAD

**Issue by sayanh** [kyma-project/kyma#9179]
**Description**

As a result of https://github.com/kyma-project/kyma/issues/9059#issuecomment-668135631, it is critical to understand the following with respect to the test:
- Why CPU usage of the cluster pods goes high?
- How much load API server is into during the test?
- Are the retries using exponential or constant backoff? Exponential backoffs should be the way to go easy on the kube API server.
- Are there any ways to fix it?

**Reasons**

It is important to understand why and whether the reasons are worth having it.

**AC**
- [ ] Evaluate which component consumes most resources
- [ ] On which step of core-test-external-solution API Server freaks out.
- [ ] Check if there are any linear retries, if yes, then make them exponential backoff.

**Comment by k15r** [comment]
Will reevaluate necessity  of this ticket after release 1.16

**Comment by anishj0shi** [comment]
core-test-external-solution is a stable test now. and the API Server issues were fixed by the pod-preset controller image update.
