### ISSUE TITLE
Profile test cluster-users

### ISSUE THREAD

**Issue by sayanh** [kyma-project/kyma#9184]
**Description**

As a result of https://github.com/kyma-project/kyma/issues/9059#issuecomment-668135631, it is critical to understand the following with respect to the test:
- Why CPU usage of the cluster pods goes high?
- How much load API server is into during the test?
- Are the retries using exponential or constant backoff? Exponential backoffs should be the way to go easy on the kube API server.
- Are there any ways to fix it?

**Reasons**

It is important to understand why and whether the reasons are worth having it.

**Comment by k15r** [comment]
One way to improve this test could be to not use 
`kubectl can-i` 
but create the `SelfSubjectAccessReview` Resources in one call:
e.g:
```kubectl create -f - -o yaml  << EOF
apiVersion: authorization.k8s.io/v1
kind: SelfSubjectAccessReview
spec:
  resourceAttributes:
    resource: configmaps
    verb: create
    namespace: dev
---
apiVersion: authorization.k8s.io/v1
kind: SelfSubjectAccessReview
spec:
  resourceAttributes:
    group: apps
    resource: deployments
    verb: create
    namespace: dev
EOF
```

That way we reduce the number of TLS handshakes to a minimum.


Downside of this approach is that we need to parse the returned `SelfSubjectAccessReview`.`Status`

For namespace specific rule inquiries we could use requests similar to this one:

```
kubectl -v 2  create -n kyma-system -f - -o yaml << EOF
apiVersion: authorization.k8s.io/v1
kind: SelfSubjectRulesReview
spec:
  namespace: "kyma-integration"
EOF
```

**Comment by piotrmsc** [comment]
@k15r this is already done by our proxy, also please note, that those tests communicate with proxy not with k8s apiserver directly. We will take a look.

**Comment by lilitgh** [comment]
won't be fixed as we moved to a new test framework
