### ISSUE TITLE
Remove LOG UI from Kyma installation in favour of deep-linking to grafana UI

### ISSUE THREAD

**Issue by kwiatekus** [kyma-project/kyma#9196]
**Description**

Remove LOG UI from Kyma installation in favour of deep-linking to grafana UI

**Reasons**

Grafana is well adopted industry standard for analytics and visualisation.
With clear focus, they keep extending features, i.e you can :
 - inspect logs from loki with syntax highlighting and better filtering
- co-relate metrics with logs,
- use jeager as data source and trace requests 

It clear that we would never come close to this feature set in log UI (its not our goal), therefore we might simply get rid of LOG UI and deep-link to grafana UI in the context of functions, pods.
This will spare us maintenance efforts and reduce potential attack vectors.

**AC**
 - Navigation node should show up only when grafana is available in runtime
 - Include a regression test that validates the link for new grafana versions
 - Link to Namespace Logs ( Grafana) from Namespace Details
 - Links should be configurable to make it easy to change to any other log provider system (i.e Kibana)
 

**Attachments**
![Screen Shot 2020-08-06 at 16 34 50](https://user-images.githubusercontent.com/6783567/89545428-a0a6aa00-d803-11ea-8e50-3ff912be78f0.png)

**Comment by sergio-oss** [comment]
How will the authentication work ? Currently they use different identity providers

**Comment by a-thaler** [comment]
@sergio-oss Grafana authentication points to dex for authentication, same as console
