### ISSUE TITLE
Potential import collision: import path should be "knative.dev/eventing", not "github.com/knative/eventing"

### ISSUE THREAD

**Issue by KateGo520** [kyma-project/kyma#9215]
## Background
I find that `knative.dev/eventing` and `github.com/knative/eventing` coexist in this repo：
https://github.com/kyma-project/kyma/blob/master/components/console-backend-service/go.mod （Line 24 & 61）
```
github.com/knative/eventing v0.13.1
knative.dev/eventing v0.13.1 // indirect
```
That’s because the `knative/eventing` has already renamed it’s import path from "github.com/knative/eventing" to "knative.dev/eventing". When you used the old path "github.com/knative/eventing" to import `knative/eventing`, go will reintroduces `knative/eventing` through the import statements "import knative.dev/eventing/…" in the go source file of `knative/eventing`.

https://github.com/knative/eventing/blob/v0.13.1/pkg/reconciler/eventtype/controller.go#L24
```
package eventtype
import (
	"knative.dev/pkg/logging"
	"knative.dev/eventing/pkg/apis/eventing/v1alpha1"
	"knative.dev/pkg/configmap"
	"knative.dev/pkg/controller"
	"knative.dev/pkg/tracker"
	brokerinformer "knative.dev/eventing/pkg/client/injection/informers/eventing/v1alpha1/broker"
	eventtypeinformer "knative.dev/eventing/pkg/client/injection/informers/eventing/v1alpha1/eventtype"
	eventtypereconciler "knative.dev/eventing/pkg/client/injection/reconciler/eventing/v1alpha1/eventtype"
)
…
```

The "knative.dev/eventing" and "github.com/knative/eventing" are the same repos. This will work in isolation, bring about potential risks and problems.

## Solution
Replace all the old import paths, change `"github.com/knative/eventing"` to `"knative.dev/eventing"`.
Where did you import it: https://github.com/kyma-project/kyma/search?p=2&q=%22github.com%2Fknative%2Feventing%22&unscoped_q=%22github.com%2Fknative%2Feventing%22

**Comment by KateGo520** [comment]
@magicmatatjahu  @dariadomagala  Could you help me review this issue? Thx :p

**Comment by aerfio** [comment]
Hey @KateGo520, thanks for pointing it out, I'll take care of this in #9251

**Comment by KateGo520** [comment]
Thanks for your efforts and feedback. @aerfio
