### ISSUE TITLE
Make kyma-gardener-azure-integration a required job

### ISSUE THREAD

**Issue by nachtmaar** [kyma-project/kyma#9217]
**Description**

As a Kyma developer I don't want that existing functionality breaks. For that reason, CI/CD should help us ensure our functionalities and quality.
Currently `kyma-gardener-azure-integration` is an optional job. It should be a required job, otherwise it will get ignored and knative-kafka related functionality might break. In order to make it required, we should ensure it is stable enough.

**AC**
- job succeeds 20 times in a row
- job is required and not optional anymore
- job is run as post-master as well

To be discussed: is the periodic one still required if there is a pre-master/post-master ?

**Comment by anishj0shi** [comment]
Duplicate #8964
