### ISSUE TITLE
Provide a basic search query that can be used to get the Gardener cluster logs from stack driver

### ISSUE THREAD

**Issue by marcobebway** [kyma-project/kyma#9218]
**Description**

As a follow-up to https://github.com/kyma-project/kyma/issues/8783, and to improve the developer experience, provide a basic search query that can be used to get the Gardener cluster logs from stack driver.

A basic search query could be:

```
jsonPayload.kubernetes.host:"shoot--kyma-prow--CLUSTER_NAME"
```

A more specific search query could be:
 
```
jsonPayload.kubernetes.labels."KEY":"VALUE"
jsonPayload.kubernetes.container_name="CONTAINER_NAME"
```

**Where to put the query**

- The prow job log.
- Channel notification.
- ...What else?

**Acceptance Criteria**

_TBD_

**Comment by nachtmaar** [comment]
@marcobebway It can be used for gke clusters as well. Stackdriver filters look a bit different however (atm).

**Comment by nachtmaar** [comment]
For aks based clusters me as a developer I want to have a basic search query for Azure logging solution

**Comment by nachtmaar** [comment]
[test-log-collector](
https://github.com/kyma-project/test-infra/tree/18f88b9d79c6dd9a55fdd723e80956b6a86055a8/development/test-log-collector) has a way to define the ownership (which team is responsible) for a particular test and send to a slack channel. Maybe we can use it.
