### ISSUE TITLE
Problems opening the kyma console on linux using the CLI

### ISSUE THREAD

**Issue by gpolito** [kyma-project/kyma#9220]
Hi Team,

I followed all steps described in this guide to install Kyma in a local env (Ubuntu 18.04.4 LTS): https://kyma-project.io/docs/#installation-install-kyma-locally. 
When I execute the `kyma console` command to open and access the Console UI, the browser shows this message: 
`Cannot fetch dex metadata`. 

Also, I see in the console these messages: 
`[0809/214911.684747:ERROR:nacl_helper_linux.cc(308)] NaCl helper process running without a sandbox!`
`Most likely you need to configure your SUID sandbox correctly`

Any Ideas? 
Thanks in advance.

**Comment by a-thaler** [comment]
Was the installation and the local setup successful? Please verify:
- the status attribute of `kubectl get installation kyma-installation -oyaml`
- your /etc/hosts file if there is an entry for your minikube IP

This log line you mentions, in which console it is printed? terminal or browser console or kyma console?

**Comment by gpolito** [comment]
Hi @a-thaler ,

Regarding your first item, this is the output:
```
$ kubectl get installation kyma-installation -oyaml
apiVersion: installer.kyma-project.io/v1alpha1
kind: Installation
metadata:
  creationTimestamp: "2020-08-10T17:27:06Z"
  finalizers:
  - finalizer.installer.kyma-project.io
  generation: 30
  labels:
    kyma-project.io/installation: ""
  name: kyma-installation
  namespace: default
  resourceVersion: "6955"
  selfLink: /apis/installer.kyma-project.io/v1alpha1/namespaces/default/installations/kyma-installation
  uid: ce0b1e60-030c-459f-aace-0c6c339fe8cd
spec:
  components:
  - name: cluster-essentials
    namespace: kyma-system
    release: ""
  - name: testing
    namespace: kyma-system
    release: ""
  - name: istio
    namespace: istio-system
    release: ""
  - name: xip-patch
    namespace: kyma-installer
    release: ""
  - name: istio-kyma-patch
    namespace: istio-system
    release: ""
  - name: knative-serving
    namespace: knative-serving
    release: ""
  - name: knative-eventing
    namespace: knative-eventing
    release: ""
  - name: dex
    namespace: kyma-system
    release: ""
  - name: ory
    namespace: kyma-system
    release: ""
  - name: api-gateway
    namespace: kyma-system
    release: ""
  - name: rafter
    namespace: kyma-system
    release: ""
  - name: service-catalog
    namespace: kyma-system
    release: ""
  - name: service-catalog-addons
    namespace: kyma-system
    release: ""
  - name: helm-broker
    namespace: kyma-system
    release: ""
  - name: nats-streaming
    namespace: natss
    release: ""
  - name: core
    namespace: kyma-system
    release: ""
  - name: cluster-users
    namespace: kyma-system
    release: ""
  - name: permission-controller
    namespace: kyma-system
    release: ""
  - name: apiserver-proxy
    namespace: kyma-system
    release: ""
  - name: iam-kubeconfig-service
    namespace: kyma-system
    release: ""
  - name: serverless
    namespace: kyma-system
    release: ""
  - name: knative-provisioner-natss
    namespace: knative-eventing
    release: ""
  - name: event-sources
    namespace: kyma-system
    release: ""
  - name: application-connector
    namespace: kyma-integration
    release: ""
  - name: console
    namespace: kyma-system
    release: ""
  url: __URL__
  version: __VERSION__
status:
  conditions:
  - lastProbeTime: "2020-08-10T17:50:43Z"
    lastTransitionTime: "2020-08-10T17:50:43Z"
    status: "True"
    type: Installed
  - lastProbeTime: "2020-08-10T17:50:43Z"
    lastTransitionTime: "2020-08-10T17:50:43Z"
    status: "False"
    type: Installing
  - lastProbeTime: "2020-08-10T17:50:43Z"
    lastTransitionTime: "2020-08-10T17:50:43Z"
    status: "False"
    type: InProgress
  - lastProbeTime: "2020-08-10T17:50:43Z"
    lastTransitionTime: "2020-08-10T17:27:38Z"
    status: "False"
    type: Error
  - lastProbeTime: "2020-08-10T17:50:43Z"
    lastTransitionTime: "2020-08-10T17:50:43Z"
    status: "False"
    type: Uninstalled
  description: Kyma installed
  errorLog: []
  state: Installed
  url: __URL__
  version: __VERSION__
```
Regarding the 2nd item, I found this line in the _/etc/hosts_ file:
``` 192.168.99.100 application-operator.kyma.local connector-service.kyma.local gateway.kyma.local apiserver.kyma.local console-backend.kyma.local console.kyma.local core-ui.kyma.local docs.kyma.local dex.kyma.local addons.kyma.local configurations-generator.kyma.local oauth2.kyma.local storage.kyma.local registry.kyma.local catalog.kyma.local ```

**Comment by a-thaler** [comment]
Thanks for the feedback, so it looks like the setup is fine. @kwiatekus @piotrmsc When the kyma console usually prints `Cannot fetch dex metadata`?

About your log line, so I guess you mean the output of the `kyma console` command. Seeing https://stackoverflow.com/questions/60544974/nacl-helper-process-running-without-a-sandbox-error-using-chrome-through-seleniu the CLI probably misses a flag for linux.

**Comment by gpolito** [comment]
Hi @a-thaler 

> About your log line, so I guess you mean the output of the kyma console command.

Yes.

This is my current installation:
```
$ minikube version
minikube version: v1.6.2
commit: 54f28ac5d3a815d1196cd5d57d707439ee4bb392

$ kyma version
Kyma CLI version: 1.14.0
Kyma cluster version: 1.14.0

$ docker -v
Docker version 19.03.12, build 48a66213fe
```

**Comment by piotrmsc** [comment]
@gpolito what do you get when you open in the browser `https://dex.kyma.local/keys` ?

**Comment by gpolito** [comment]
Hi @piotrmsc, I get this:

```
{
  "keys": [
    {
      "use": "sig",
      "kty": "RSA",
      "kid": "75090e66a68bb7ccab56b49966b7ecf38c02ce86",
      "alg": "RS256",
      "n": "t368XzDKCnR9o4AusJrxxr3JA-CXEMWoUPGs26aglhjk6Lp5VhVl2z6sdEes5uurZ7NvK2rhp7vwu8m2YwXDrfGG9Huvv3ynCWM3GPm3FHVL3JzaKZ8jvQx2uXcfwPVsnXjOpWfWjfKCjTKhhaxzue8SSUsz5Upo-GUdNhFIidg_CKuWxv2UTxdyaAwSE0MvL5zoYjdsK55O13ZS1-pfK5E8WRIX7bXMixODVhQVpVOO4F6phnXvQ-mOEiSAqRpgztLaW2BLTL2RnYVfYTue-56_ZTNV-bQP4ANj10515ZsiN3-ACYHDcx_6wzBspTKUEgVwFB5ZjhRq8uB-O6Sqqw",
      "e": "AQAB"
    }
  ]
}
```

**Comment by piotrmsc** [comment]
so you're able to connect to dex, in this case would be awesome if you open `https://console.kyma.local` and when you see this error check in browser developers tools what kind of error you have there or requests failing etc.
Also please check logs from dex pod in `kyma-system` to make sure there are no errors there as well

**Comment by gpolito** [comment]
Hi @piotrmiskiewicz & @a-thaler,

I was able to finally make it work. The issue was related with the kyma server certificate. 
I followed this instructions: https://kyma-project.io/docs/#troubleshooting-console-access-network-error. The only option that worked for me was to generate a root CA certificate and then create a new server certificate signed by this new CA (based on this https://stackoverflow.com/questions/7580508/getting-chrome-to-accept-self-signed-localhost-certificate).
I then downloaded the Kyma sources, updated these properties `global.tlsCrt` & `global.tlsKey` in this file: `kyma/installation/resources/installer-config-local.yaml.tpl`, and installed kyma from this local sources (`kyma install --source local --src-path <my-sources>`).

Thanks for you help. I think we can close this issue.

**Comment by a-thaler** [comment]
I would like to keep it open to fix the `kyma console` command problem on linux. Will rename the title.

**Comment by Genslus** [comment]
Hi, 
I am facing the exact same issue on my local installation (using Ubuntu 20.04.1 LTS). 
The error "Cannot fetch dex metadata" is present in Firefox as well as in Chrome. (Using the _kyma console_ command or open the url manually in the browser)

I got it working by accepting the certificate risk at: https://dex.kyma.local/keys -> after that I got to the login page of the Kyma Console without the "Cannot fetch dex metadata" error. 

But I guess I will face other issues since there seems to be a certificate problem. (I am pretty new to Kyma, Minikube, etc.)

**Comment by suleymanakbas91** [comment]
The error message printed on the output of the kyma console command comes from the internal command that we're running to open the browser. We could disable outputting from the internal command, but then the users won't see useful information about the problem. That's why we want to keep it enabled. 

As the original certificate issue has already been resolved, I'm closing the issue.
