### ISSUE TITLE
Remove Tiller form docs

### ISSUE THREAD

**Issue by kazydek** [kyma-project/kyma#9221]
**Description**
As Tiller is no longer used in Kyma (only in resources, but for a while only and can be already removed), we should remove any mention of it from all `*md` files in the `kyma` repo.

In case of any questions, contact @piotrmsc.

**Comment by piotrmsc** [comment]
FYI, I have created a PR to remove tiller from sources as a resource (I do not modify docs) https://github.com/kyma-project/kyma/pull/9244

**Comment by piotrmsc** [comment]
@kazydek I have talked with @superojla about and She can pick it up.

**Comment by superojla** [comment]
All mentions of Tiller and Helm2 in `*md` files were removed with this PR: https://github.com/kyma-project/kyma/pull/9274
