### ISSUE TITLE
Create a component dependency matrix in docs

### ISSUE THREAD

**Issue by kazydek** [kyma-project/kyma#9224]
**Description**

We write in docs that you can install a full (Kyma) or a light (Kyma Lite) version of Kyma. We also mention you can configure (add/remove) particular components. What we don't mention however, and is quite crucial to understand the customization part, is specific info for users as to which Kyma components are **obligatory**, which are **optional**, and which of them are **codependent**. Basically, what we need is a dependency matrix, preferably in the form of a table or diagram. 

In the light of the 1.16 release plans (Make Kyma runtime lighter - Kyma 2.0 direction), it seems like perfect timing to address this docu debt.

**Attachment(s)**
Such a doc would also address the feedback we received in this [blog post](https://blogs.sap.com/2020/06/22/kyma-hands-on-part-1/):

> According to the documentation, it seems there are some components that you can not disable without providing a replacement. However, I was not able to find which components are required and which components are optional.

**Issues**
See a very similar issue: https://github.com/kyma-project/kyma/issues/8825

**Comment by klaudiagrz** [comment]
There is a nice [SKR diagram](https://cxwiki.sap.com/pages/viewpage.action?pageId=547861312#SKRonAWS+GCP-Highlevelarchdiagram) prepared by @tobiscr that we can use as inspiration.

**Comment by mmitoraj** [comment]
@pbochynski Hi, would you consider that issue still valid for Kyma 2.0?

**Comment by pbochynski** [comment]
# Mandatory components
- cluster essentials
- istio
- certificates

# Components

| Component | Dependency to |   Required for |
|---|---|---|
|logging| | |
|tracing| | |
|kiali| | |
|monitoring| | |
|eventing| | |
|ory| | api-gateway|
|api-gateway| ory  | |
|cluster-users| | |
|serverless| | |
|application-connector| rafter, service-catalog (dependency will be removed soon)| |

# Deprecated components

| Component | Dependency to |   Required for |
|---|---|---|
|service-catalog| | |
|service-catalog-addons| | |
|rafter|  | |
|helm-broker| service-catalog| |

**Comment by NHingerl** [comment]
TBC: Situation for K2.0

**Comment by NHingerl** [comment]
Closing this issue as [discussed](https://sap-btp.slack.com/archives/C01KSGZA23C/p1639672002089600?thread_ts=1639670690.089300&cid=C01KSGZA23C) with @a-thaler: 

"There are only few [dependencies] left and we continue getting rid of it, so I assume it is not worth to document it anymore. The main dependency is anyway now modeled via the prerequisite in the components.yaml and with that transparent. In the Obs charts we have implicit dependencies like Kiali will not work without monitoring, but maybe we can see to document that proper in the Obs docu instead."
