### ISSUE TITLE
Initial Design Proposal Kyma Eventing Manager

### ISSUE THREAD

**Issue by anishj0shi** [kyma-project/kyma#9230]
The New Kyma Eventing Manager is platform agnostic component which would handle orchestration of the underlying eventing platform. From the end user perspective, we need to have a generic Subscription API and the new Kyma Eventing Manager should be capable to translate the Subscription Request into the underlying platform centric Subscription Resources.

**Basic Acceptance Criteria this Proposal should cover**
- Define a Generic Interface for creating Platform Agnostic resources. Some definite protocols this interface must declare should be : Create  Subscription Resources, Get Publishing URI, Get Subscription Status. On the basis of this interface a platform like Enterprise Messaging, dapr, etc should provide a corresponding implementation.
- Proposal should also cover the semantics of configuring the underlying platform. Hence, it should explain a mechanism to specify the platform in a declarative fashion.
- Furthermore, this proposal should cover the reactive mechanism of the above configuration in order to pick a dynamic platform centric implementation. 
- Proposal should cover the mechanism of publishing the events. When we talk about publishing. so basically we need to answer What's the best way to reach a publisher component (which is created by the platform ) where a workload can push cloudevents and at the same time, the current *event-service* should also be able to resolve and redirect the request to the underlying publisher of a topic
- One Absolute Requirement to the proposal is w.r.t event dispatching. The underlying Eventing platform should reach the subscriber directly without any **middleware** to ensure best performance

**Comment by pbochynski** [comment]
Just a question about bundled eventing solution. Is it going to be plain NATS? Right now we are pushing events (webhook) to functions or microservices. What would be the event flow for bundled solution? Client library bundled with serverless function and triggering it? What about microservices? Sidecar that subscribes topics and forwards events? What about **no middleware** principle?
