### ISSUE TITLE
Define a Generic Event Subscription API

### ISSUE THREAD

**Issue by anishj0shi** [kyma-project/kyma#9231]
To achieve Platform agnostic eventing, we need to declare a generic API, which acts as the 1st level interface for our user.
The first version of this CRD may have the following specification:

- **topic** - This field will correspond to the topic a workload is interested in.
- **subscriber** - corresponds to the sink of the event. I'd expect this to be an addressable duck type to support various types of subscribers.
- **subscriptionStatus** - should propagate the status of platform-specific Subscription Resource.
- **subscriberURL(ReadOnly)** - to check whether our reconciler was able to derive the subscriber reference.
- **publisherURL** - To tell the system that for a topic this URL would be the listener. so, anyone who wants within the system who wants to publish an event to the topic should dynamically push events to this URL.  

**AC**
- Define a Kyma CRD **Subscription** in YAML format in conformance to Open API Spec
- Derive as many fields as possible from [Cloudevent subscription spec](https://github.com/cloudevents/spec/blob/master/subscriptions-api.md)

**Comment by radufa** [comment]
The proposal together with some example was added to a new repo:
https://github.tools.sap/skydivingtunas/proposals
See there: 
https://github.tools.sap/skydivingtunas/proposals/tree/master/ev2/design-subscription-crd

**Comment by radufa** [comment]
This initial version was discussed and accepted by the team. 
It contains the Subscription CRD and samples  CR for different use cases.

**Comment by k15r** [comment]
PublisherURL field was removed after discussion with the team. Publishing does not fit well in the context of a subscription api
