### ISSUE TITLE
Kyma local installation fails on istio-install

### ISSUE THREAD

**Issue by sethim1980** [kyma-project/kyma#9241]
**Description**
Hi,  
I am a newbie to Kyma and was trying to install the latest version 1.14 but was facing issues so switched to 1.13 but here as well I am facing issues :
**Local Environment of my system:**
Laptop  - MacBook Pro with macOD Cataline 10.5.5
kyma-cli - 1.13
Docker - 19.03.5
Minikube - 1.6.2

When I try to provision minikube using "kyma provision minikube" I get the error of time out

Error: Executing 'minikube start --memory 8192 --cpus 4 --extra-config=apiserver.authorization-mode=RBAC --extra-config=apiserver.cors-allowed-origins='http://*' --extra-config=apiserver.enable-admission-plugins=DefaultStorageClass,LimitRanger,MutatingAdmissionWebhook,NamespaceExists,NamespaceLifecycle,ResourceQuota,ServiceAccount,ValidatingAdmissionWebhook --kubernetes-version=v1.16.3 --vm-driver hyperkit --disk-size 30g -b kubeadm' command with output '* minikube v1.6.2 on Darwin 10.15.5
* Selecting 'hyperkit' driver from user configuration (alternates: [virtualbox])
* Creating hyperkit VM (CPUs=4, Memory=8192MB, Disk=30000MB) ...
* Preparing Kubernetes v1.16.3 on Docker '19.03.5' ...
 - apiserver.authorization-mode=RBAC
 - apiserver.cors-allowed-origins='http://*'
 - apiserver.enable-admission-plugins=DefaultStorageClass,LimitRanger,MutatingAdmissionWebhook,NamespaceExists,NamespaceLifecycle,ResourceQuota,ServiceAccount,ValidatingAdmissionWebhook
* Pulling images ...
' timed out, try running the command manually or increasing timeout using the 'timeout' flag
I had to manually execute the following command to get it running :
minikube start --memory 8192 --cpus 4 --extra-config=apiserver.authorization-mode=RBAC --extra-config=apiserver.cors-allowed-origins='http://*' --extra-config=apiserver.enable-admission-plugins=DefaultStorageClass,LimitRanger,MutatingAdmissionWebhook,NamespaceExists,NamespaceLifecycle,ResourceQuota,ServiceAccount,ValidatingAdmissionWebhook --kubernetes-version=v1.16.3 --vm-driver hyperkit --disk-size 30g -b kubeadm

Now if I try "kyma provision minikube" again with the old instance, the minikube starts successfully.

Now when I am trying to install kyma using "kyma install" it hangs at the deployment of "istio" component
Can you please help me if I am missing something or in case any extra step need to be done.
**kubectl get pods  - A** shows

NAMESPACE       NAME                           READY  STATUS       RESTARTS  AGE
istio-system      istio-install-job-7g87p                 0/1   ImagePullBackOff  0     11m
kube-system      coredns-5644d7b6d9-4rsst                 1/1   Running      0     60m
kube-system      coredns-5644d7b6d9-mrdz8                 1/1   Running      0     60m
kube-system      etcd-minikube                      1/1   Running      0     59m
kube-system      kube-addon-manager-minikube               1/1   Running      0     59m
kube-system      kube-apiserver-minikube                 1/1   Running      0     60m
kube-system      kube-controller-manager-minikube             1/1   Running      0     59m
kube-system      kube-proxy-jssld                     1/1   Running      0     60m
kube-system      kube-scheduler-minikube                 1/1   Running      0     60m
kube-system      metrics-server-6754dbc9df-5xhp2             1/1   Running      0     60m
kube-system      storage-provisioner                   1/1   Running      0     60m
kube-system      tiller-deploy-7c7db7cdc6-v2mg6              1/1   Running      0     55m
kubernetes-dashboard  dashboard-metrics-scraper-7b64584c5c-ch9mh        1/1   Running      0     60m
kubernetes-dashboard  kubernetes-dashboard-79d9cd965-nw5xq           1/1   Running      0     60m
kyma-installer     kyma-installer-6459ff9d49-z9vwd             1/1   Running      0     50m
kyma-system      cluster-essentials-pod-preset-webhook-5c974cd4ff-wf62m  1/1   Running      0     48m
kyma-system      testing-octopus-0                    1/1   Running      0     47m

The  output of
**kubectl get installation kyma-installation -o go-template --template='{{- range .status.errorLog }}{{printf "%s:\n %s\n" .component .log}}{{- end}}'** shows :
istio:
 Helm install error: rpc error: code = Unknown desc = Job failed: DeadlineExceeded
Helm delete of istio was successfull
I
 tried to delete the namespace and also by deleting the minikube instance but the problem still remains

The output of **kubectl describe pod -n istio-system istio-install-job-7g87p**:
Name:     istio-install-job-7g87p
Namespace:  istio-system
Priority:   0
Node:     minikube/192.168.64.55
Start Time:  Thu, 13 Aug 2020 11:35:05 +0530
Labels:    controller-uid=20eac565-9a51-4acf-ba58-e044acac37ef
       job-name=istio-install-job
Annotations: <none>
Status:    Pending
IP:      172.17.0.11
IPs:
 IP:      172.17.0.11
Controlled By: Job/istio-install-job
Containers:
 installer:
  Container ID:  
  Image:     eu.gcr.io/kyma-project/istio-installer:ce7e3510
  Image ID:    
  Port:     <none>
  Host Port:   <none>
  Command:
   bash
   -c
   #!/bin/bash -e
   if [ -f "/etc/istio/overrides.yaml" ]; then
    #New way: just merge default IstioControlPlane definition with a user-provided one.
    yq merge -a -x /etc/istio/config.yaml /etc/istio/overrides.yaml > /etc/combo.yaml
    kubectl create cm "${CONFIGMAP_NAME}" -n "${NAMESPACE}" \
     --from-file /etc/istio/config.yaml \
     --from-file /etc/istio/overrides.yaml \
     --from-file /etc/combo.yaml \
     -o yaml --dry-run | kubectl replace -f -
    printf "istioctl manifest apply -f /etc/combo.yaml\n"
    istioctl manifest apply -f /etc/combo.yaml
   else
    #Old way: apply single-value Helm overrides using `istioctl --set "key=val"`
    overrides=$(kubectl get cm --all-namespaces -l "installer=overrides,component=istio" -o go-template --template='{{ range .items }}{{ range $key, $value := .data }}{{ if ne $key "kyma_istio_control_plane" }}{{ printf "%s: %s\n" $key . }}{{ end }}{{ end }}{{ end }}' )
    overrides_transformed=""
    if [ ! -z "$overrides" ]; then
     while IFS= read -r line; do
      key=$(echo "$line" | cut -d ':' -f 1)
      val=$(echo "$line" | cut -d ':' -f 2 | cut -d ' ' -f 2)
      case $key in
       pilot.resources* )
        new_key=$(echo "$key" | cut -d '.' -f 2-)
        key=$(echo "trafficManagement.components.pilot.k8s.$new_key")
        ;;
       mixer.loadshedding.mode* )
        key=$(echo "values.mixer.telemetry.loadshedding.mode")
        ;;
       mixer.telemetry.resources* )
        new_key=$(echo "$key" | cut -d '.' -f 3-)
        key=$(echo "telemetry.components.telemetry.k8s.$new_key")
        ;;
       mixer.policy.resources* )
        new_key=$(echo "$key" | cut -d '.' -f 3-)
        key=$(echo "policy.components.policy.k8s.$new_key")
        ;;
       gateways.istio-ingressgateway.resources* )
        new_key=$(echo "$key" | cut -d '.' -f 3-)
        key=$(echo "gateways.components.ingressGateway.k8s.$new_key")
        ;;
       gateways.istio-ingressgateway.autoscaleMin* )
        key=$(echo "gateways.components.ingressGateway.k8s.hpaSpec.minReplicas")
        ;;
       gateways.istio-ingressgateway.autoscaleMax*)
        key=$(echo "gateways.components.ingressGateway.k8s.hpaSpec.maxReplicas")
        ;;
       * )
        key=$(echo "values.$key")
        ;;
      esac
      if [ -z "$val" ]; then
       val=$(echo '""')
      fi
      overrides_transformed=$(printf "$overrides_transformed --set \"$key=$val\"")
     done <<< "$overrides"
    fi
    printf "istioctl manifest apply -f /etc/istio/config.yaml ${overrides_transformed}\n"
    istioctl manifest apply -f /etc/istio/config.yaml ${overrides_transformed}
   fi
   while [ "$(kubectl get po -n istio-system -l app=sidecarInjectorWebhook -o jsonpath='{ .items[0].status.phase}')" != "Running" ]
   do
    echo "sidecar injector still not running. Waiting..."
    sleep 1s
   done
   echo "sidecar injector is running"
   echo "patching api-server destination rule"
   kubectl patch destinationrules.networking.istio.io -n istio-system api-server --type merge --patch '{"spec": {"trafficPolicy": { "connectionPool" : { "tcp": {"connectTimeout": "30s"}}}}}'
   echo "Apply custom kyma manifests"
   kubectl apply -f /etc/manifests
  State:     Waiting
   Reason:    ImagePullBackOff
  Ready:     False
  Restart Count: 0
  Environment:
   NAMESPACE:    istio-system
   CONFIGMAP_NAME: kyma-istio-control-plane-config
  Mounts:
   /etc/istio/ from config (ro)
   /etc/manifests from manifests (ro)
   /var/run/secrets/kubernetes.io/serviceaccount from istio-job-token-cd5qj (ro)
Conditions:
 Type       Status
 Initialized    True 
 Ready       False 
 ContainersReady  False 
 PodScheduled   True 
Volumes:
 config:
  Type:   ConfigMap (a volume populated by a ConfigMap)
  Name:   kyma-istio-control-plane-config
  Optional: false
 manifests:
  Type:   ConfigMap (a volume populated by a ConfigMap)
  Name:   kyma-extra-manifests
  Optional: false
 istio-job-token-cd5qj:
  Type:    Secret (a volume populated by a Secret)
  SecretName: istio-job-token-cd5qj
  Optional:  false
QoS Class:    BestEffort
Node-Selectors: <none>
Tolerations:   node.kubernetes.io/not-ready:NoExecute for 300s
         node.kubernetes.io/unreachable:NoExecute for 300s
Events:
 Type   Reason   Age          From        Message
 ----   ------   ----          ----        -------
 Normal  Scheduled 8m59s         default-scheduler Successfully assigned istio-system/istio-install-job-7g87p to minikube
 Warning Failed   8m18s         kubelet, minikube Failed to pull image "eu.gcr.io/kyma-project/istio-installer:ce7e3510": rpc error: code = Unknown desc = Error response from daemon: Get https://eu.gcr.io/v2/: dial tcp: lookup eu.gcr.io on 192.168.64.1:53: read udp 192.168.64.55:43623->192.168.64.1:53: i/o timeout
 Warning Failed   7m23s         kubelet, minikube Failed to pull image "eu.gcr.io/kyma-project/istio-installer:ce7e3510": rpc error: code = Unknown desc = Error response from daemon: Get https://eu.gcr.io/v2/: dial tcp: lookup eu.gcr.io on 192.168.64.1:53: read udp 192.168.64.55:48696->192.168.64.1:53: i/o timeout
 Warning Failed   6m17s         kubelet, minikube Failed to pull image "eu.gcr.io/kyma-project/istio-installer:ce7e3510": rpc error: code = Unknown desc = Error response from daemon: Get https://eu.gcr.io/v2/: dial tcp: lookup eu.gcr.io on 192.168.64.1:53: read udp 192.168.64.55:55670->192.168.64.1:53: i/o timeout
 Normal  Pulling  5m28s (x4 over 8m58s) kubelet, minikube Pulling image "eu.gcr.io/kyma-project/istio-installer:ce7e3510"
 Warning Failed   4m48s (x4 over 8m18s) kubelet, minikube Error: ErrImagePull
 Warning Failed   4m48s         kubelet, minikube Failed to pull image "eu.gcr.io/kyma-project/istio-installer:ce7e3510": rpc error: code = Unknown desc = Error response from daemon: Get https://eu.gcr.io/v2/: dial tcp: lookup eu.gcr.io on 192.168.64.1:53: read udp 192.168.64.55:35214->192.168.64.1:53: i/o timeout
 Normal  BackOff  4m35s (x6 over 8m18s) kubelet, minikube Back-off pulling image "eu.gcr.io/kyma-project/istio-installer:ce7e3510"
 Warning Failed   3m54s (x9 over 8m18s) kubelet, minikube Error: ImagePullBackOff

**Expected result**

Kyma should install properly with Kyma CLI or script.

**Actual result**

Kyma local installation stops on istio-install

**Steps to reproduce**

After provisioning minikube when the kyma installation is started using "kyma install" then face this error

**Troubleshooting**

Tried to re-install kyma with Kyma CLI and deleting minikube before doing so.

**Comment by piotrmsc** [comment]
Istio installation failed because image could not be fetched from gcr. Can you check if you have and DNS service running on port 53 https://kyma-project.io/docs/#troubleshooting-failed-to-pull-image-error ?

**Comment by pbochynski** [comment]
Closed due to inactivity.
