### ISSUE TITLE
Migrate Application Connectivity Dep leftovers to Go Modules

### ISSUE THREAD

**Issue by franpog859** [kyma-project/kyma#9306]
**Description**

Migrate Application Connectivity Dep leftovers to Go Modules. This is a follow-up issue for [this PR](https://github.com/kyma-project/kyma/pull/9214)

**Reasons**

There are `application-connector-tests`, `compass-runtime-agent` tests and `application-registry-tests` which don't use the Go Modules. The whole project should be consistent and up to date with the Go standards so these three should be also migrated to Go Modules and the current Go version

Keep in mind that this is not a super critical issue

**Comment by janmedrek** [comment]
I'd suggest migrating only `compass-runtime-agent-tests` as other components are deprecated.

**Comment by pbochynski** [comment]
@dbadura @janmedrek Please have a look

**Comment by janmedrek** [comment]
https://github.com/kyma-project/kyma/commit/5b55dce85917dde97623db1c9466358308ca9869
