### ISSUE TITLE
Add Git source scenario to Serverless e2e tests

### ISSUE THREAD

**Issue by tgorgol** [kyma-project/kyma#9309]
**Description**

Extend Serverless E2E tests with a scenario that uses Function with `sourceType: git`. The basic scenario should clone the repository using the HTTP protocol, without authenticating, and test the follow-head functionality by committing changes to the tracked repository.

To avoid depending on external Git provider, we should think of a way to host in-cluster Git server (could be mocked), that can be used by tests.

**Reasons**

Functions with Git sources should also be tested in E2E tests.

**Comment by kwiatekus** [comment]
Done
