### ISSUE TITLE
Application Connector tutorial unable to hit the events endpoint

### ISSUE THREAD

**Issue by antheajung** [kyma-project/kyma#9316]
**Description**
One of the steps of the [Application Connector tutorial](https://kyma-project.io/docs/components/application-connector/#tutorials-tutorials) is to call the Application Registry and Event Service on a local deployment using crt and key. I was able to use the cert/key to call the `v1/metadata/services` endpoint but was not able to trigger the `v1/events` endpoint.

Specifically the following code throws `{"code":405,"error":"Method not allowed."}` error. 
```
curl https://gateway.kyma.local/{APP_NAME}/v1/events --cert {CERT_FILE_NAME}.crt --key {KEY_FILE_NAME}.key -k
```

This also breaks the [Trigger a Function with events](https://kyma-project.io/docs/components/application-connector/#tutorials-trigger-a-function-with-events) as it contains steps to send an event by curling the `v1/events` endpoint: `https://gateway.{CLUSTER_DOMAIN}/$APP_NAME/v1/events -k --cert {CERT_FILE_NAME}.crt --key {KEY_FILE_NAME}.key -d`

**Expected result**
Status 2xx

**Actual result**
```
{"code":405,"error":"Method not allowed."}
```

**Steps to reproduce**
Follow the steps of [Application Connector Tutorial](https://kyma-project.io/docs/components/application-connector/#tutorials-tutorials) until the [Call the Application Registry and Event Service on local deployment](https://kyma-project.io/docs/components/application-connector/#tutorials-get-the-client-certificate-call-the-application-registry-and-event-service-on-local-deployment)

**Comment by pbochynski** [comment]
@majakurcius Can you have a look?
