### ISSUE TITLE
Unified installer codebase

### ISSUE THREAD

**Issue by a-thaler** [kyma-project/kyma#9347]
**Description**
As follow up of https://github.com/kyma-project/kyma/issues/9072 we want to start having a standalone library for installing Kyma which can be used by the installer and the CLI.

The library should most likely be located in https://github.com/kyma-incubator/hydroform.

Following aspects should be covered in the first iteration:
- use plain helm client decoupled from existing installer code
- support installation
- support delete
- installation of charts is happening as parallel as possible having a configurable concurrent installation factor
- proper error handling - retry will re-install again
- configurable with Values.yaml hierarchies (multiple entries per component to support profiling + secret storage + customization) for example
- Have an experimental CLI command wrapping the library and make it usable via command line supporting values.yaml as configuration input

Potential features on top
- exponential retry policy
- Support `--dry-run` option

**Reasons**
Better local development experience. Show alternative solutions to the installation problem.

**Attachments**
https://github.com/kyma-project/kyma/issues/9072

**Comment by a-thaler** [comment]
Follow-up epic is https://github.tools.sap/kyma/backlog/issues/1045

**Comment by suleymanakbas91** [comment]
The library has been created [here](https://github.com/kyma-incubator/hydroform/tree/master/parallel-install) with the name "parallel-install".  The new CLI commands `kyma alpha install` and `kyma alpha uninstall` are being released in 1.18, which are using the new "parallel-install" library.
