### ISSUE TITLE
Recognise git tags as function code reference

### ISSUE THREAD

**Issue by kwiatekus** [kyma-project/kyma#9360]
**Description**

At the moment we allow referencing code by defining specific branch ( follow head) or specific commit (fixed). 
We should also allow referencing code versions for functions based on git tags 

**Reasons**

Git tags are important tool to mark points in codebase history.

**Attachments**

![image (18)](https://user-images.githubusercontent.com/6783567/92102534-06745a80-eddf-11ea-8bc9-86f559d1394d.png)

**Comment by kwiatekus** [comment]
We had no clean solution in mind so far.
Also - as people didnt request it so far, we are dropping it for now.
Let's reopen once required

**Comment by paschdan** [comment]
i would like this feature, at the moment we need to duplicate all our version tags with branches, thats not how git is supposed to be used..

**Comment by paschdan** [comment]
is this maybe already in 1.22 via #9134 ?

**Comment by paschdan** [comment]
ok, to answer my question, this is still not in, see 

https://github.com/kyma-project/kyma/blob/main/components/function-controller/internal/git/git.go#L45-L66

**Comment by paschdan** [comment]
@kwiatekus can this be reopened?
