### ISSUE TITLE
Fix spelling of Service in documentation to conform to guidelines

### ISSUE THREAD

**Issue by majakurcius** [kyma-project/kyma#9368]
**Description**
 
Check the documentation and correct the spelling of `Service` (the Kubernetes resource) and `service` (in general).

**Reason**

As per our [guidelines](https://github.com/kyma-project/community/blob/master/guidelines/content-guidelines/08-style-and-terminology.md#capitalized-terms), `Service`, when meant as a Kubernetes resource, should be capitalized.
Right now, our documentation has some inconsistencies in that regard, so it should be checked and corrected.

**Comment by pbochynski** [comment]
@majakurcius Is it closed on purpose or just stalebot did it?

**Comment by majakurcius** [comment]
> @majakurcius Is it closed on purpose or just stalebot did it?

It was the stalebot. Thanks, PB.
