### ISSUE TITLE
Eventing controller foundation work

### ISSUE THREAD

**Issue by anishj0shi** [kyma-project/kyma#9376]
As a kyma maintainer focusing on eventing, 
I want to have a framework for the new reconciler, so that I can add more functionality easily later

**AC**
- [x] new component folder in the kyma repository containing initial code
- [x] integration in our CI system using a prow job
- [x] initial code bootstrapped using kube builder
- [x] initial documentation

**Comment by sayanh** [comment]
- Bootstrap all resources using Kubebuilder
-Reconciliation includes CRUD of:
  - subscriptions of OEB
  - APIRule to expose workload
- Add a finalizer to ensure proper cleanup of subscriptions in OEB

Status
- Depends on the HTTP status codes of the REST calls to OEB for CRUD of OEB subscriptions.
- Depends on the status of the APIRule
