### ISSUE TITLE
Enable sending of events by optionally installing the event publisher proxy

### ISSUE THREAD

**Issue by anishj0shi** [kyma-project/kyma#9378]
As Matthew (cloud developer) 
I want to be able to send events to my Eventing solution as this is currently not officially supported by kyma and I want to be one of the first to try it out.

**AC**
- [x] A helm chart in the */resources* directory which has the Deployment as well as the necessary RBAC Custom Resources for the Cloud Event gateway proxy.
- [x] The installation of this component is optional and is disabled by default

**Comment by sayanh** [comment]
More info:
- Add  it to the `installer-cr-cluster.yaml.tpl`
