### ISSUE TITLE
Allow to create, update and delete remote environment thru ui-api-layer

### ISSUE THREAD

**Issue by PK85** [kyma-project/kyma#938]
The UI-API-Layer need to be extended with a possibility to manage the Remote Environments:

AC:
- Create a new Remote Environment with the following parameters
  - Name
  - Description
  - Labels as key-value pairs
- Update a Remote Environment
  - Description
  - Labels as key-value pairs
- Delete a Remote Environment

More details can be found here: https://github.com/kyma-project/community/blob/master/sig-and-wg/sig-core/proposals/remote-environment-creation.md

**Comment by PK85** [comment]
why ticket is in review and PR is already merged?

**Comment by polskikiel** [comment]
I have to bump images yet. Created PR: https://github.com/kyma-project/kyma/pull/1213
