### ISSUE TITLE
Installation on k8s 1.18 fails as podpreset webhook denies requests

### ISSUE THREAD

**Issue by a-thaler** [kyma-project/kyma#9390]
**Description**
I'm trying to install Kyma 1.15.1 on gardener using k8s 1.18. The installation hangs in the "testing" component which is the first component getting installed after "cluster-essentials". Here, the octopus pod cannot be scheduled because of

```
create Pod testing-octopus-0 in StatefulSet testing-octopus failed error: admission webhook "podpresets.settings.svcat.k8s.io" denied the request: no matches for kind "PodPreset" in version "settings.svcat.k8s.io/v1alpha1"
```

Checking the logs of the podpreset webhooks says:
```
I0908 07:20:15.641736       1 main.go:336] Entering mutatePods in mutating webhook
I0908 07:20:15.641976       1 main.go:353] Examining pod: testing-octopus-0
I0908 07:20:15.641998       1 main.go:357] Looking at pod annotations, found: map[kubernetes.io/psp:gardener.privileged sidecar.istio.io/inject:false]
E0908 07:20:15.642170       1 main.go:369] no matches for kind "PodPreset" in version "settings.svcat.k8s.io/v1alpha1" (has the CRD been loaded?)
I0908 07:20:56.654044       1 main.go:336] Entering mutatePods in mutating webhook
I0908 07:20:56.654477       1 main.go:353] Examining pod: testing-octopus-0
I0908 07:20:56.654500       1 main.go:357] Looking at pod annotations, found: map[kubernetes.io/psp:gardener.privileged sidecar.istio.io/inject:false]
E0908 07:20:56.654659       1 main.go:369] no matches for kind "PodPreset" in version "settings.svcat.k8s.io/v1alpha1" (has the CRD been loaded?)
```

**Expected result**

Installation succeeds

**Actual result**
Installation hangs

**Steps to reproduce**

**Troubleshooting**
It is working with k8s 1.16

**Comment by crabtree** [comment]
Looks like related to the podpreset-webhook. We could introduce change in our approach for client creation. Right now the client is created once on the component startup. I'd go with some goroutine that recreates the client when not in use or forces it to reload CRD.

**Comment by kjaksik** [comment]
We couldn't reproduce this issue on different k8s minor version and different Kyma versions. Might have been some kind of a race happening due to gardener infrastructure problems. For now it's working

**Comment by kjaksik** [comment]
It seems that it happened again on k8s 1.18 and 1.19 I'll investigate this
