### ISSUE TITLE
Prow build pipeline to install Kyma on k3d

### ISSUE THREAD

**Issue by koala7659** [kyma-project/kyma#9398]
The goal is to create prow build pipeline that installs Kyma on k3s/k3d. 

This will allow to replace Minikube in our build environment with more lightweight solution.  

For implementation we can consider two approaches:

1. Use our existing cli solution described at https://github.com/kyma-project/kyma/issues/8756. 
2. Use bash scripts available at https://github.com/kyma-incubator/local-kyma-k3d

Created pipeline could be based on one of existing build minikube pipelines, but should not be mandatory. 

The estimated time for implementation is 5 man days

**Comment by koala7659** [comment]
Current status:

PR to test-infra to evaluate k3d bash script in Draft
https://github.com/kyma-project/test-infra/pull/2855

PR to test-infra by Adam Walach to evaluate full kyma-cli solution 
https://github.com/kyma-project/test-infra/pull/2851

**Comment by pbochynski** [comment]
Closed due to inactivity. There are other tickets to handle k3s.
