### ISSUE TITLE
Implement k8s owner reference between Application and ApplicationMapping

### ISSUE THREAD

**Issue by PK85** [kyma-project/kyma#940]
**Description**
Possible ways of improving this should be discussed.

**Reasons**
When deleting application there are some leftovers which shouldn't be there.

**Comment by PK85** [comment]
Maybe, we should mark RE as going to be deleted and say that EM exists. Same as SC doing with SI and SB.

**Comment by lszymik** [comment]
The first part of that story is to collect information about what we have and what can be improved. I have collected feedback while creating E2E tests. 
There are a lot of possible improvements, let's start with the first steps.

**Comment by lszymik** [comment]
Acceptance criteria:
- Investigation of possibilities if we can block removal of Application if something is still referencing it (mapping)
- Plan follow-up actions

**Comment by franpog859** [comment]
We found a possibility to control Application removal if the Application Mapping exists:
1. In the Application Broker - mapping controller - add ownerReference to the Application Mapping if it does not exist 
2. In the Application Operator set finalizer for the Application and remove it when there is no Application Mapping for the Application

**Comment by franpog859** [comment]
Follow-up actions:
Create issue for deleting Application Mapping while deleting Application

Follow-up actions if we want to delete all Application leftovers:
Create an epic-issue
Create analogous issues for all resources like Application Mapping, Lambdas etc. (Application leftovers) to add ownerReference to the resource
Create issue to add finalizers to the Application Operator to control Application removal

**Comment by lszymik** [comment]
Hello,
From a business perspective, I am thinking about something like preventing accidental deletion of the whole setup.

I would like to have a solution to inform the user about Application is bound to one or many environments and therefore cannot be deleted. It might also display the whole list of dependencies, like an application is used in the lambda, etc.

The additional functionality, which might be added in parallel - allows removal of the application with deleting of all subelements. E.g. the force flag is added and then the administrator makes a conscious decision to delete everything.

What do you think about it?

**Comment by pbochynski** [comment]
The work is continued in the epic: https://github.com/kyma-project/kyma/issues/4639
