### ISSUE TITLE
Getting Started - lacking tips for minikube deployment

### ISSUE THREAD

**Issue by arturskorupa** [kyma-project/kyma#9418]
**Description**

Going through the Getting Started for External Applications fails on Minikube. There are two issues: 
* Commerce mock can't connect to Kyma urls (connector-service.kyma.local, gateway.kyma.local)
* Certificate validation has to be skipped

There's an error: 
`Error: getaddrinfo EAI_AGAIN connector-service.kyma.local connector-service.kyma.local:443`

and

`Error: unable to verify the first certificate`

It can be solved by [adding hostAliases](https://kubernetes.io/docs/concepts/services-networking/add-entries-to-pod-etc-hosts-with-host-aliases/) to commerce-mock deployment:

```
kubectl edit deployment commerce-mock
```

Then add the following to **spec.containers**:

```
hostAliases:
      - hostnames:
        - connector-service.kyma.local
        - gateway.kyma.local
        ip: 192.168.64.8
```

The certificate issue is solved by using an option "Insecure Connection" when connecting an application at Commerce Mock.

**Area**

Getting started guides / Connect an external application / Create the Application and retrieve a token

**Reasons**

We should add a tip to make configuration on Minikube possible to run.

**Assignees**

@kyma-project/technical-writers

**Comment by a-thaler** [comment]
Consider putting instructions to the https://github.com/SAP-samples/xf-application-mocks repo as well

Same for https://github.com/kyma-incubator/varkes/issues/233

**Comment by kazydek** [comment]
This was already fixed by @magicmatatjahu in https://github.com/kyma-project/kyma/pull/9432.
