### ISSUE TITLE
Add eventing controller metrics

### ISSUE THREAD

**Issue by k15r** [kyma-project/kyma#9452]
As a kyma cluster admin, 
I want to be able to retrieve metrics from the eventing controller 
so that I can identify and debug issues with the system more easily

**AC**
- [ ] common controller metrics are exposed
- [ ] dashboard exists to visualize the metrics
- [ ] metrics are scraped by monitoring system
- [ ] metrics requiring SRE action will trigger severity:critical alerts
- [ ] metrics that should be mentioned on the sre slack channer will trigger severity:warning alerts
- [ ] number of configured subscriptions is a metric

**Comment by nachtmaar** [comment]
Task List:

Hint: check if generic-dashboard from a-thaler is enough. Otherwise create own dashboard.

Add/Validate if the following metrics are exposed by the controller:
- [ ] go metrics
- [ ] reconciliation metrics

- [ ] Create dashboard
