### ISSUE TITLE
Failing kyma-cli integration

### ISSUE THREAD

**Issue by Demonsthere** [kyma-project/kyma#9460]
**Description**

The kyma-cli-integration tests are failing with the following error:

```
E0916 01:06:00.403361    5996 round_trippers.go:174] CancelRequest not implemented by *gcp.conditionalTransport
X install component tracing
Error: Timeout reached while waiting for installation to complete
```
 
The error looks like it might be cli or tracing related. Please investigate

**Expected result**

**Actual result**

**Steps to reproduce**

**Troubleshooting**
Some failed jobs:
- https://status.build.kyma-project.io/view/gcs/kyma-prow-logs/logs/kyma-cli-integration-gke/1305657881588142082
- https://status.build.kyma-project.io/view/gcs/kyma-prow-logs/logs/kyma-cli-integration-gke/1305774527917068288
- https://status.build.kyma-project.io/view/gcs/kyma-prow-logs/logs/kyma-cli-integration-gke/1306020272469446656

**Comment by suleymanakbas91** [comment]
Fixed by https://github.com/kyma-project/test-infra/commit/b28ea656f5eea31fedce6ba9959f088d5ccf77ce
