### ISSUE TITLE
SAP Commerce API fails to get registered with Kyma

### ISSUE THREAD

**Issue by sethim1980** [kyma-project/kyma#9468]
**Description**

SAP Commerce faila to register all events/APIs with Kyma

Kyma version installed locally : 1.13.0 
Local Environment of my system:
Laptop  - MacBook Pro with macOD Cataline 10.5.5
kyma-cli - 1.13
Docker - 19.03.5
Minikube - 1.6.2
SAP Commerce : 2005

**Expected result**

SAP Commerce connects sucesssfully to Kyma and all events and API's are registered in Kyma

**Actual result**

Only events are registered, all API's fail to get registered

**Steps to reproduce**

Local SAP Commerce & kyma running on the laptop.
Facing issues while trying to connect commerce instance to Kyma. While registering the application created in Kyma to Commerce system  the events are registered in Kyma but the API's fail.
All configurations done as well as installed the certificates on both the Java installation as well the SAP Commerce local certificate ydevelopers.jks.   

The output of minikube ssh -- ip route show is :

_default via 192.168.64.1 dev eth0 proto dhcp src 192.168.64.56 metric 1024 
172.17.0.0/16 dev docker0 proto kernel scope link src 172.17.0.1 
192.168.64.0/24 dev eth0 proto kernel scope link src 192.168.64.56 
192.168.64.1 dev eth0 proto dhcp scope link src 192.168.64.56 metric 1024_

The SAP Commerce HAC/backoffice is accessible using :

https://local-192-168-64-1.nip.io:9002/backoffice/login.zul
as well as through
https://192.168.64.1:9002/backoffice/login.zul

The /etc/hosts file have has the following entries added :

# Added by Docker Desktop
# To allow the same kube context to work on the host and the container:
127.0.0.1 kubernetes.docker.internal
# End of section
192.168.64.56 application-operator.kyma.local connector-service.kyma.local gateway.kyma.local apiserver.kyma.local console.kyma.local console-backend.kyma.local compass-mfs.kyma.local core-ui.kyma.local docs.kyma.local dex.kyma.local $

The following properties are added to the local.properties file of the SAP Commerce instance :

ccv2.services.api.url.0=https://local-192-168-64-1.nip.io:${tomcat.ssl.port} 
apiregistryservices.events.exporting=true
kymaintegrationservices.truststore.cacerts.path=${platformhome}/resources/devcerts/ydevelopers.jks
kymaintegrationservices.truststore.password=123456

**Troubleshooting**

All certificated checked

The response for **_kubectl -n kyma-integration logs -l app=application-registry -c application-registry_** is :

_time="2020-09-16T12:15:47Z" level=info msg="POST /commercedp/v1/metadata/services HTTP/1.1\r\nHost: application-registry-external-api:8081\r\nAccept: */*\r\nAccept-Encoding: gzip,deflate\r\nContent-Length: 466\r\nContent-Type: application/json\r\nUser-Agent: Apache-HttpClient/4.5.12 (Java/11.0.2)\r\nX-B3-Parentspanid: 406673bc8d41bc92\r\nX-B3-Sampled: 0\r\nX-B3-Spanid: 1f918884561639a6\r\nX-B3-Traceid: 68ca4f624fdb952bb6344d89fc808f7e\r\nX-Forwarded-Client-Cert: By=spiffe://cluster.local/ns/kyma-integration/sa/default;Hash=b230bb572b1fbb9f0697fb1777c100e2f095e3fcf1e6d639e2d6db0c47f97eac;Subject=\"\";URI=spiffe://cluster.local/ns/kyma-integration/sa/commercedp-connectivity-validator\r\nX-Forwarded-For: 192.168.64.1, 127.0.0.1\r\nX-Forwarded-Proto: https\r\nX-Request-Id: 3a951344-9c85-471b-a766-607840bc3e42\r\n\r\n" application=commercedp
time="2020-09-16T12:15:51Z" level=error msg="Creating new service failed, Determining API spec for service with ID 71aeecfe-5aa4-4a65-9966-ba118d8ab576 failed, Fetching API spec from https://local-192-168-64-1.nip.io:9002/previewwebservices/api-docs failed, Get https://local-192-168-64-1.nip.io:9002/previewwebservices/api-docs: dial tcp: lookup local-192-168-64-1.nip.io on 10.96.0.10:53: server misbehaving" application=commercedp
time="2020-09-16T12:15:52Z" level=info msg="POST /commercedp/v1/metadata/services HTTP/1.1\r\nHost: application-registry-external-api:8081\r\nAccept: */*\r\nAccept-Encoding: gzip,deflate\r\nContent-Length: 503\r\nContent-Type: application/json\r\nUser-Agent: Apache-HttpClient/4.5.12 (Java/11.0.2)\r\nX-B3-Parentspanid: 8e152a5d222f619c\r\nX-B3-Sampled: 0\r\nX-B3-Spanid: 20a67e4c9c812547\r\nX-B3-Traceid: dd41b406cd0be760b384038b558a9a96\r\nX-Forwarded-Client-Cert: By=spiffe://cluster.local/ns/kyma-integration/sa/default;Hash=b230bb572b1fbb9f0697fb1777c100e2f095e3fcf1e6d639e2d6db0c47f97eac;Subject=\"\";URI=spiffe://cluster.local/ns/kyma-integration/sa/commercedp-connectivity-validator\r\nX-Forwarded-For: 192.168.64.1, 127.0.0.1\r\nX-Forwarded-Proto: https\r\nX-Request-Id: 4426638b-19ae-41aa-a686-514d85dc1152\r\n\r\n" application=commercedp
time="2020-09-16T12:15:57Z" level=error msg="Creating new service failed, Determining API spec for service with ID 2165995d-ddb0-4470-af07-7ea8aec0f7b5 failed, Fetching API spec from https://local-192-168-64-1.nip.io:9002/adaptivesearchwebservices/api-docs failed, Get https://local-192-168-64-1.nip.io:9002/adaptivesearchwebservices/api-docs: dial tcp: lookup local-192-168-64-1.nip.io on 10.96.0.10:53: server misbehaving" application=commercedp
time="2020-09-16T12:15:57Z" level=info msg="POST /commercedp/v1/metadata/services HTTP/1.1\r\nHost: application-registry-external-api:8081\r\nAccept: */*\r\nAccept-Encoding: gzip,deflate\r\nContent-Length: 495\r\nContent-Type: application/json\r\nUser-Agent: Apache-HttpClient/4.5.12 (Java/11.0.2)\r\nX-B3-Parentspanid: c59e9a4901d12957\r\nX-B3-Sampled: 0\r\nX-B3-Spanid: 0fd4ea705c06aea3\r\nX-B3-Traceid: fc43398879625fe1ccc5effceab51564\r\nX-Forwarded-Client-Cert: By=spiffe://cluster.local/ns/kyma-integration/sa/default;Hash=b230bb572b1fbb9f0697fb1777c100e2f095e3fcf1e6d639e2d6db0c47f97eac;Subject=\"\";URI=spiffe://cluster.local/ns/kyma-integration/sa/commercedp-connectivity-validator\r\nX-Forwarded-For: 192.168.64.1, 127.0.0.1\r\nX-Forwarded-Proto: https\r\nX-Request-Id: 72115dba-4ada-4bcf-bc35-5ad5211c1cf3\r\n\r\n" application=commercedp
time="2020-09-16T12:16:01Z" level=error msg="Creating new service failed, Determining API spec for service with ID ae538be5-aa94-4c4b-a0f1-0bcc879139c6 failed, Fetching API spec from https://local-192-168-64-1.nip.io:9002/cmssmarteditwebservices/api-docs failed, Get https://local-192-168-64-1.nip.io:9002/cmssmarteditwebservices/api-docs: dial tcp: lookup local-192-168-64-1.nip.io on 10.96.0.10:53: server misbehaving" application=commercedp
time="2020-09-16T12:16:07Z" level=info msg="POST /commercedp/v1/metadata/services HTTP/1.1\r\nHost: application-registry-external-api:8081\r\nAccept: */*\r\nAccept-Encoding: gzip,deflate\r\nContent-Length: 478\r\nContent-Type: application/json\r\nUser-Agent: Apache-HttpClient/4.5.12 (Java/11.0.2)\r\nX-B3-Parentspanid: fb3487efa843c553\r\nX-B3-Sampled: 0\r\nX-B3-Spanid: 4bb7e00c6bafafa4\r\nX-B3-Traceid: a2050bc8672ddd5b3ac7e135c4c00a96\r\nX-Forwarded-Client-Cert: By=spiffe://cluster.local/ns/kyma-integration/sa/default;Hash=b230bb572b1fbb9f0697fb1777c100e2f095e3fcf1e6d639e2d6db0c47f97eac;Subject=\"\";URI=spiffe://cluster.local/ns/kyma-integration/sa/commercedp-connectivity-validator\r\nX-Forwarded-For: 192.168.64.1, 127.0.0.1\r\nX-Forwarded-Proto: https\r\nX-Request-Id: 9f8b22b1-e557-4df7-a105-ee405fd81b6b\r\n\r\n" application=commercedp
time="2020-09-16T12:16:11Z" level=error msg="Creating new service failed, Determining API spec for service with ID e653cc04-a212-4159-bd1a-32e8d3a1c3ca failed, Fetching API spec from https://local-192-168-64-1.nip.io:9002/smarteditwebservices/api-docs failed, Get https://local-192-168-64-1.nip.io:9002/smarteditwebservices/api-docs: dial tcp: lookup local-192-168-64-1.nip.io on 10.96.0.10:53: server misbehaving" application=commercedp
time="2020-09-16T12:16:11Z" level=info msg="POST /commercedp/v1/metadata/services HTTP/1.1\r\nHost: application-registry-external-api:8081\r\nAccept: */*\r\nAccept-Encoding: gzip,deflate\r\nContent-Length: 446\r\nContent-Type: application/json\r\nUser-Agent: Apache-HttpClient/4.5.12 (Java/11.0.2)\r\nX-B3-Parentspanid: 1c934792ccab9aff\r\nX-B3-Sampled: 0\r\nX-B3-Spanid: a66414225a91df98\r\nX-B3-Traceid: b48a135f64f29a39c7615d19791487ed\r\nX-Forwarded-Client-Cert: By=spiffe://cluster.local/ns/kyma-integration/sa/default;Hash=b230bb572b1fbb9f0697fb1777c100e2f095e3fcf1e6d639e2d6db0c47f97eac;Subject=\"\";URI=spiffe://cluster.local/ns/kyma-integration/sa/commercedp-connectivity-validator\r\nX-Forwarded-For: 192.168.64.1, 127.0.0.1\r\nX-Forwarded-Proto: https\r\nX-Request-Id: f49ee662-38fe-4a38-8ba5-62ad5917a761\r\n\r\n" application=commercedp
time="2020-09-16T12:16:13Z" level=error msg="Creating new service failed, Determining API spec for service with ID 5734a623-eb9f-4ae2-a3ff-19bb96207270 failed, Fetching API spec from https://local-192-168-64-1.nip.io:9002/cmswebservices/api-docs failed, Get https://local-192-168-64-1.nip.io:9002/cmswebservices/api-docs: dial tcp: lookup local-192-168-64-1.nip.io on 10.96.0.10:53: server misbehaving" application=commercedp_

**Comment by a-thaler** [comment]
Hi @sethim1980,

the problem is that kyma running on minikube cannot reach the API of commerce. That already shows up at registration time as here the responsible kyma component tries to fetch the api specification from the API endpoint in a first step. For event registration pushing the specification as part of the registration call, that's why it is not failing here.

Unfortunately, I don't know why the nip.io approach does not work here.

A not so nice solution might be to make your local application accessible from external and configure the external address, like in: https://github.com/kyma-incubator/examples/tree/master/tunnel

**Comment by sethim1980** [comment]
@a-thaler : Thanks for the response. I have 2 Commerce applications configured on Kyma first one points to a SAP Commerce 1905 (which was created earlier and is working) and the second one for SAP Commerce 2005 which is not working.
Can multiple applications cause an issue here. Only during registration we face this issue as the existing integration with 1905 works fine.
I have Kyma 1.13 installed on my system which uses Helm 2.16 and the solution which you shared requires Helm 3 & other components. So will this work with 2 Helm versions on the machine. 
Also I am a little new to the Kyma/Kubernetes world so can you please help me with the solution

**Comment by a-thaler** [comment]
The logs are clearly stating that the kyma component cannot reach the configured API endpoint. So even a succeeding registration will not help as your workload will also not be able to reach the API.

If the first commerce instance also based on the nip.io approach? Then you should be able to get the second instance running as well..
For debugging just "kubectl exec " a pod and try to curl the mentioned api-spec endpoint

You can use the helm3 client in parallel to helm2, that will work. But if the nip.io approach is working you should not go that route with the external exposure.

**Comment by sethim1980** [comment]
@a-thaler : 
The following link also mentioned a similar issue : 
https://kyma-community.slack.com/archives/CD0K2NSQZ/p1558607844013800

Here they disabled the verification for the API, is it possible that we can do that.

**Comment by janmedrek** [comment]
@sethim1980 you could give it a try - it would require changing `--insecureSpecDownload` value in Application Registry deployment in `kyma-integration` namespace to `true`. 

Not sure whether that will help with the `server misbehaving` issue, but worth trying as it is a simple action.

**Comment by sethim1980** [comment]
@janmedrek : I patched application registry using 
__kubectl -n kyma-integration patch deployment application-registry --type json -p='[{"op": "add", "path": "/spec/template/spec/containers/0/args/-", "value":"--insecureSpecDownload=true"}]'_
and then also patched application gateway using : 
_kubectl -n kyma-integration patch deployment <APPLICATION_NAME>-application-gateway --type json -p='[{"op": "add", "path": "/spec/template/spec/containers/0/args/-", "value":"--skipVerify=true"}]'_ 

Still the problem remains : 
_kubectl -n kyma-integration describe deployment application-registry_
shows : 
```
Name:                   application-registry
Namespace:              kyma-integration
CreationTimestamp:      Thu, 13 Aug 2020 12:55:52 +0530
Labels:                 app=application-registry
                        heritage=Tiller
                        release=application-connector
Annotations:            deployment.kubernetes.io/revision: 5
Selector:               app=application-registry,release=application-connector
Replicas:               1 desired | 1 updated | 1 total | 1 available | 0 unavailable
StrategyType:           RollingUpdate
MinReadySeconds:        0
RollingUpdateStrategy:  0 max unavailable, 25% max surge
Pod Template:
  Labels:       app=application-registry
                release=application-connector
  Annotations:  sidecar.istio.io/inject: true
  Containers:
   application-registry:
    Image:       eu.gcr.io/kyma-project/application-registry:35130f2e
    Ports:       8081/TCP, 9090/TCP
    Host Ports:  0/TCP, 0/TCP
    Args:
      /applicationregistry
      --proxyPort=8080
      --externalAPIPort=8081
      --uploadServiceURL=http://rafter-upload-service.kyma-system.svc.cluster.local:80
      --namespace=kyma-integration
      --requestTimeout=10
      --requestLogging=false
      --specRequestTimeout=20
      --rafterRequestTimeout=20
      --insecureAssetDownload=true
      --insecureSpecDownload=false
      --detailedErrorResponse=false
      --insecureSpecDownload=true
      --insecureSpecDownload=true
      --insecureSpecDownload=true
      --insecureSpecDownload=true
    Environment:  <none>
    Mounts:       <none>
  Volumes:        <none>
Conditions:
  Type           Status  Reason
  ----           ------  ------
  Available      True    MinimumReplicasAvailable
  Progressing    True    NewReplicaSetAvailable
OldReplicaSets:  <none>
NewReplicaSet:   application-registry-548cb8555d (1/1 replicas created)
Events:
  Type    Reason             Age   From                   Message
  ----    ------             ----  ----                   -------
  Normal  ScalingReplicaSet  14m   deployment-controller  Scaled up replica set application-registry-548cb8555d to 1
  Normal  ScalingReplicaSet  14m   deployment-controller  Scaled down replica set application-registry-89c646c5b to 0
```

**Comment by pbochynski** [comment]
I think you messed up the list of arguments:
```
      --insecureAssetDownload=true
      --insecureSpecDownload=false
      --detailedErrorResponse=false
      --insecureSpecDownload=true
      --insecureSpecDownload=true
      --insecureSpecDownload=true
      --insecureSpecDownload=true
```
You added the new argument several times - you should replace the existing one. Like in such example:
```
kubectl -n kyma-integration \
  patch deployment commerce-application-gateway --type=json \
  -p='[{"op": "replace", "path": "/spec/template/spec/containers/0/args/6", "value": "--skipVerify=true"}]'
```
I suggest you edit the deployment and fix it manually now (`kubectl -n kyma-integration edit deployment application-registry`).

**Comment by pbochynski** [comment]
Closed due to inactivity.
