### ISSUE TITLE
Add testing label to all the pods that are created during tests.

### ISSUE THREAD

**Issue by rakesh-garimella** [kyma-project/kyma#9469]
**Description**

After upgrade to istio-1.5 prometheus is using podmonitor to scrape the metrics from the application endpoints. Since podmonitor is dynamic in nature and every pod that is created on the cluster is listed as a new target this causes issues during tests. 

There are pods created during testing phase and then they are deleted. When these pods are up the monitoring test has them listed as targets and by the time it checks if this up the pods are deleted and hence targets are down so the monitoring test is failing on integration and upgrade tests. Currently as a workaround we are ignoring the pod names like here: https://github.com/kyma-project/kyma/pull/9467. This is not an elegant solution.

We already are ignoring the pods with label `testing.kyma-project.io/created-by-octopus: true` inside the podmonitor however this label is not present on all the pods that are created during tests. We should inject these labels into all the pods that created during tests.

We should renable the targets test on monitoring after fixing this.

A list with missing labels is following:

* Function tests
* Upgrade tests
* For Jobs on Compass which run after installation(think of different label here though.)

**Expected result**

Label `testing.kyma-project.io/created-by-octopus: true` is injected into all the pods. Once the labels has been added we should re-enable the targets testing on monitoring tests.

**Actual result**
Label is not present in all the pods created during testing.

**Comment by pbochynski** [comment]
We are switching our testing to fast-integration tests and we will not invest in octopus.
