### ISSUE TITLE
Current troubleshooting guide for event-mesh is invalid

### ISSUE THREAD

**Issue by k15r** [kyma-project/kyma#9518]
**Description**

**Area**

* Event Mesh

**Reasons**

The [troubleshooting guide](https://github.com/kyma-project/kyma/blob/master/docs/event-mesh/10-01-troubleshooting.md) still refers to knative-serving, but event-mesh and its event-sources do not depend on knative-serving anymore

**Assignees**

**Comment by technical-writers** [comment]
FYI - a number of Kyma project issues have been tagging our Github account (@technical-writers) as **Assignees**. 

Not sure what the intention is, but the @technical-writers Github account is not affiliated with the Kyma project (and if you were trying to tag someone specific, they may not have got the message) :)

**Comment by k15r** [comment]
Will be removed soon
