### ISSUE TITLE
usage-kind examples refer to function using knative-serving

### ISSUE THREAD

**Issue by k15r** [kyma-project/kyma#9519]
**Description**

as the function in kyma do not rely on knative-serving since the rewrite of the function controller all examples should be updated to the current way of deploying functions. see https://github.com/kyma-project/kyma/blob/master/docs/service-catalog/06-02-usage-kind.md

**Area**

* service catalog

**Assignees**

@technical-writers

**Attachments**

**Comment by PK85** [comment]
closing, usage-kinds will be removed soon
