### ISSUE TITLE
Namespace termination hangs in the console UI

### ISSUE THREAD

**Issue by kwiatekus** [kyma-project/kyma#9521]
**Description**

Namespace termination hangs in the console UI
**Expected result**

Namespace card is removed from the list view upon succesfull namespace removal

**Actual result**

Namespace gets deleted, but UI doesnt refelct that. The termination indicator stays until user refreshes the page
![Screen Shot 2020-09-24 at 09 45 44](https://user-images.githubusercontent.com/6783567/94116716-adcb3700-fe4b-11ea-8396-75c653109983.png)

**Steps to reproduce**

1. Log in to console ui as admin
2. Create a namespace
3. Delete the namespace on the list view

**Troubleshooting**

**Comment by arturskorupa** [comment]
Maybe it is somehow connected with https://github.com/kyma-project/kyma/issues/9522, but the later one is more serious problem because does not disappear on refresh.

**Comment by dariadomagala** [comment]
Add "watch" for namespaces list on SKRs (kyma-essentials?)
