### ISSUE TITLE
Namespace termination hangs forever

### ISSUE THREAD

**Issue by arturskorupa** [kyma-project/kyma#9522]
**Description**

Deleted namespace hung in Terminating status forever and still appears on the UI and in the ns list read with kubectl.

**Expected result**

Namespace is successfully deleted and dissapear from the UI and kubectl. 
In some exceptional scenarios it may stay terminating, but I definitely should have access to it, to proceed with manual deletion. 

**Actual result**

Deleted namespace is still present (Terminating) and I can do nothing to push it forward. Having the same access right as at the moment when I deleted the namespace, I can't access it any more to see what exactly hung. It looks like all rolebindings have been already removed from the namespace.

![image](https://user-images.githubusercontent.com/69588692/94118220-82494c00-fe4d-11ea-8a87-1d9515464142.png)

![image](https://user-images.githubusercontent.com/69588692/94118269-98efa300-fe4d-11ea-8214-17e3ddd56739.png)

**Steps to reproduce**

1. Create new namespace
2. Bind an application to it
3. Create some lambda
4. Delete namespace

**Troubleshooting**

**Comment by pbochynski** [comment]
Can you find which finalizer is responsible for it hanging?

**Comment by PK85** [comment]
@kwiatekus similar issue: https://github.tools.sap/kyma/backlog/issues/799, see comments

**Comment by Alexd-sap** [comment]
Same issue applies on Trial Kyma instances.

**Comment by valentinvieriu** [comment]
This is general k8s issue. Namespaces can hang for various reasons. With the new Kyma 2.x release you will have access to the whole cluster, and also can check the status of the namespace in the yaml for debugging
