### ISSUE TITLE
Add metrics for Event Publisher Proxy

### ISSUE THREAD

**Issue by nachtmaar** [kyma-project/kyma#9523]
As a kyma cluster admin, 
I want to be able to retrieve metrics from the event-publisher-proxy
so that I can identify and debug issues with the system more easily

**AC**
- [ ] go metrics are exposed
- [ ] dashboard exists to visualize the metrics
- [ ] metrics are scraped by monitoring system

**Comment by a-thaler** [comment]
When leveraging this https://github.com/kyma-project/kyma/pull/9486 you can skip the dashboard

**Comment by nachtmaar** [comment]
Task list:

- [ ] Find out a library to expose metrics
- [ ] Add go-runtime metrics to epp component
- [ ] Add metric for delay/latency and reflect http_status. Consider using istio metrics.
- [ ] Check if generic dashboard can be reused if not create own dashboard
