### ISSUE TITLE
Adapt service-catalog to 'allowPrivilegedContainers: false' policy

### ISSUE THREAD

**Issue by rafalpotempa** [kyma-project/kyma#9553]
**Description**

Kyma Runtime is going to be provisioned without allowance of PrivilegedContainers (`allowPrivilegedContainers: false`) so they cannot run in `root` mode.

**Implications**

We need to adjust nearly all components to be able to be created correctly during installation in order to setup a SKR with `allowPrivilegedContainers: false`.
We need to run manual tests of all components on that SKR.

All area that during investigation proven to encounter `missing 'runAsRoot'` error has to be adjusted in one of following ways:
- existing `PodSecuirtyPolicies` related to component now allow `Pods` to `RunAsRoot`
- `Containers` belonging to component affected by this change now don't need to `RunAsRoot`
- `ClusterRole` / `Role` connected with component now uses custom `PodSecurityPolicy`
- `ClusterRole` / `Role` connected with component  now uses `kyma.privileged` `PodSecurityPolicy`

**Affected resources**

- [ ] controller-manager
- [ ] webhook

> NOTE: Some additional resources may be affected in this area.

**Related Issue**

https://github.com/kyma-project/kyma/issues/9531

**Comment by ksputo** [comment]
Solution proposed in #9713 ; Won't be merged for now due to istio init container blocking the installation of component without `allowPrivilegeEscalation: true` flag. Reopen when istio problem is solved.
