### ISSUE TITLE
Provide guidance for scaling out Kyma extensions exposed via API rules

### ISSUE THREAD

**Issue by abbi-gaurav** [kyma-project/kyma#9559]
**Description**
As a customer, I should be able to refer to guidelines that can help me understand what all and by how much I need to scale various Kyma and my components to be able to handle a certain load and concurrency.

A typical Kyma extension that is exposed via an API Rule has normally the following flow

```
ingress --> ory --> lambda / serverless --> application-gateway --> external system
```
Since there are multiple components into play, when such a set up needs to be scaled, the customers would like to have some guidance how and by how much they should scale each and every component.

If the components are not scaled, the calling clients receive `503` errors which are not a good indication about where the problem lies.

There are already Horizontal Pod Autoscalers for ingress and ory. However no HPA for application gateway.

**Comment by janmedrek** [comment]
Application Gateway utilizes HPA from this release, no manual actions needed.

**Comment by piotrmsc** [comment]
If the hpa for app gateway was added then I think it can be closed. HPA for ingress & ory are already present.
