### ISSUE TITLE
Support of istio 1.7 in observability components

### ISSUE THREAD

**Issue by a-thaler** [kyma-project/kyma#9567]
**Description**

In https://github.com/kyma-project/kyma/issues/9556 the instio setup will be updated to 1.7. We need to assure that this upgrade works smoothly with the observability stack (loki, prometheus, grafana, kiali, jaeger)

[x] adopt changes done in istio metrics (setup istio with prometheus and compare scrape config to kyma scrape config)
[x] validate that upgrade is not increasing overall memory/disk footprint
[x] validate that a fresh installation has no increased overall memory/disk footprint
[x] validate grafana dashboards, kiali dashboards, jaeger traces
[x] Loki exposure via JWT verification
[x] Sampling rate for the traces in istio needs to be verified if it needs adjustment.
[x] Update readme for tracing overrides
[x] Check connection with application mocks
**Reasons**

**Attachments**

https://github.com/kyma-project/kyma/issues/9556

**Comment by rakesh-garimella** [comment]
[x] adopt changes done in istio metrics (setup istio with prometheus and compare scrape config to kyma scrape config)
  - With istio-1.7 the recommended changes is to use `prometheus.io` annotation into pods that could be used to scrape the pods. But this would not work in our case as we have to move away from `servicemonitors` and `podmonitors`
[ ] validate that upgrade is not increasing overall memory/disk footprint
[ ] validate that a fresh installation has no increased overall memory/disk footprint
[ ] validate grafana dashboards, kiali dashboards, jaeger traces
[ ] Loki exposure via JWT verification

**Comment by a-thaler** [comment]
Don't forget to update the tracing troubleshooting section: https://kyma-project.io/docs/components/tracing/#troubleshooting-troubleshooting

**Comment by rakesh-garimella** [comment]
Currently upgrade on istio-1.7 is broken as currently there is no check to prevent from upgrading from istio-1.7->istio-1.6. (Currently when we upgrade on istio-1.7 it fails as it tries to upgrade from istio-1.7->istio-1.6 and fails.)

**Comment by rakesh-garimella** [comment]
[] validate that upgrade is not increasing overall memory/disk footprint
[] validate that a fresh installation has no increased overall memory/disk footprint
After running fresh istio-1.7 installation with stability checker for ~18h
```
Memory:
prometheus-istio-server: 1.45GB
Prometheus: 1.5GB
CPU:
prometheus-istio-server: 0.16
Prometheus:0.26
TSDB:
prometheus-istio-server: 145k
Prometheus: 161k
Appended sample: 
prometheus-istio-server: 4549
Prometheus: 4811

[x] validate grafana dashboards, kiali dashboards, jaeger traces
[x] Loki exposure via JWT verification
[x] Sampling rate for the traces in istio needs to be verified if it needs adjustment.

**Comment by rakesh-garimella** [comment]
Currently blocked as unable to connect application mocks with kyma. The issue: https://github.com/kyma-project/kyma/issues/9795

**Comment by rakesh-garimella** [comment]
Remove unneeded relabelings this should reduce the load on memory of prometheus istio: https://github.com/kyma-project/kyma/pull/9821

**Comment by rakesh-garimella** [comment]
Delete istio pilot dashboards: https://github.com/kyma-project/kyma/pull/9838

**Comment by a-thaler** [comment]
Very unfortunate finding at the end: https://github.com/kyma-project/kyma/issues/9886
