### ISSUE TITLE
When eventing infrastructure in not ready, application connected in Kyma console should not be in green

### ISSUE THREAD

**Issue by sayanh** [kyma-project/kyma#9568]
**Description**

When an application(system in control plane) is connected to Kyma and the eventing infrastructure for the same is not ready, there is no feedback in the Console UI. It is assumed that the application is connected fine and eventing should also work. But this is not the case. The true status of an Application should count the status of the HTTPSource as well which should also be reflected in the UI.

**Reasons**

There is no feedback from the console UI about the readiness of the eventing infrastructure for the connected Applications. With no access to the system namespaces, debugging becomes really hard.

**Comment by pbochynski** [comment]
In the new eventing solution there is no eventing infrastructure created for each application. We can close it.
