### ISSUE TITLE
Application-connector chart installation fails

### ISSUE THREAD

**Issue by pbochynski** [kyma-project/kyma#9576]
**Description**
The installation of the application-connector chart frequently fails.

**Expected result**

The chart is installed without issues.

**Actual result**

```
Error: failed pre-install: 
warning: Hook pre-install application-connector/charts/application-broker/templates/subscription-migration.yaml failed: Internal error occurred: failed calling webhook 
"legacysinkbindings.webhook.sources.knative.dev": 
Post https://eventing-webhook.knative-eventing.svc:443/legacysinkbindings?timeout=10s: 
dial tcp 10.43.144.36:443: connect: connection refused
```

**Steps to reproduce**

Follow quick start guide from https://github.com/kyma-incubator/local-kyma-k3d

A similar issue was solved by @nachtmaar - please check if it is the same: https://github.com/kyma-incubator/local-kyma-k3d/issues/8

**Comment by k15r** [comment]
legacy sink bindings have been removed in 1.19.1
