### ISSUE TITLE
Eventing Trace has wrong order initially

### ISSUE THREAD

**Issue by nachtmaar** [kyma-project/kyma#9592]
**Description**

When checking the end-to-end trace from Istio-Ingressgateway to the event subscriber (lambda), it was discovered that the first traces are not in the correct order. The following traces however are ordered correctly.

**Expected result**

- Trace is starting with istio-ingressgateway
<img width="3120" alt="Screenshot 2020-09-30 at 16 27 28" src="https://user-images.githubusercontent.com/8013145/94698678-d797c880-0339-11eb-8f7e-a10678ce6562.png">

**Actual result**
- Trace is **not** starting with istio-ingressgateway

![image](https://user-images.githubusercontent.com/8013145/94698763-ec745c00-0339-11eb-9996-b03379dd4a49.png)

Some traces have warnings with the following pattern: `invalid parent span`.
See this image:
![screencapture-jaeger-gke-release-1-16-0-rc2-a-build-kyma-project-io-trace-ac05e2a7b69ce0b40c7ab8a0d3bd3c3b-2020-09-30-17_00_42](https://user-images.githubusercontent.com/8013145/94702921-9524ba80-033e-11eb-929e-7aef83c9532f.png)

**Steps to reproduce**
- Send events in regular interval (e.g. 1 second) and find the traces in Jaeger by selection `istio-ingressgateway` as service. Then click `Find traces`. 

**Troubleshooting**

**Comment by sayanh** [comment]
I could not reproduce the issue on a Kyma cluster with version [25085093b9534ed65ce93f098cdec6f8943c474e](https://github.com/kyma-project/kyma/commit/25085093b9534ed65ce93f098cdec6f8943c474e). The ordering looks good. Please refer to the screenshot for details.
<img width="1997" alt="Screenshot 2020-10-08 at 10 31 44" src="https://user-images.githubusercontent.com/5954057/95434604-be9ea100-0951-11eb-8b04-59b76c044d17.png">
