### ISSUE TITLE
kyma-upgrade-gardener-azure job cannot install istio chart

### ISSUE THREAD

**Issue by nachtmaar** [kyma-project/kyma#9594]
**Description**

`kyma-upgrade-gardener-azure job` prow job fails while installing istio chart.

```
+ kyma install --ci --source 1.15.1 -c installer-cr-azure-eventhubs.yaml.tpl -o installer-config-production.yaml.tpl -o installer-config-azure-eventhubs.yaml.tpl -o eventhubs-secret-overrides.yaml --timeout 90m
- Cluster type determined
  Installing Kyma in version '1.15.1' 
- Preparations done
- Waiting for installation to start
- install component cluster-essentials
! installation error occurred: install component istio, which may be OK. Will retry later...
  To fetch the error logs from the installer, run: kubectl get installation kyma-installation -o go-template --template='{{- range .status.errorLog }}{{printf "%s:\n %s\n" .component .log}}{{- end}}'
  To fetch the application logs from the installer, run: kubectl logs -n kyma-installer -l name=kyma-installer
X install component istio
! Installation error occurred while installing Kyma: installation error occurred: install component istio. Details: Installation errors: 
Component: istio, Log: Helm installation of release "istio" failed: failed post-install: job failed: BackoffLimitExceeded
Deleting release before retrying. 
 Helm delete of release "istio" failed with an error: uninstallation completed with 1 error(s): uninstall: Failed to purge the release: release: not found 

Component: istio, Log: Helm installation of release "istio" failed: create: failed to create: secrets "sh.helm.release.v1.istio.v1" is forbidden: unable to create new content in namespace istio-system because it is being terminated
Error: Timeout reached while waiting for installation to complete
[0;32m
```
> https://storage.googleapis.com/kyma-prow-logs/logs/kyma-upgrade-gardener-azure/1311108817714417664/build-log.txt

![image](https://user-images.githubusercontent.com/8013145/94713929-b50eab00-034b-11eb-8506-c62aef25a356.png)

**Expected result**

Istio get's installed correctly

**Actual result**

Installation of istio is failing

**Steps to reproduce**

Wait for next execution of the periodic job.

**Troubleshooting**

Good guess:
The file `installer-config-production.yaml.tpl` was changed by the [Istio 1.5 PR](https://github.com/kyma-project/kyma/commit/19e240cd79041e8f82b5f3c90e39bc64406f7b08#). Since the upgrade job is installing the latest released Kyma version, the change of the istio overrides are probably failing the istio installation.

Solution: Use `installer-config-production.yaml.tpl` from the latest released Kyma version instead of master. See code [here](https://github.com/kyma-project/test-infra/blob/b42c218da78b65aeaa4c031b7d0485ea89b03128/prow/scripts/cluster-integration/kyma-upgrade-gardener-azure.sh#L165
)

**Comment by Demonsthere** [comment]
Hi there, this could be related to https://github.com/kyma-project/test-infra/pull/2782, which was partially addressed by https://github.com/kyma-project/test-infra/pull/2794. How is the LoadBalancerIP set in your case? Are you using the IstioOperator, or the deprecated helm overrides?

**Comment by nachtmaar** [comment]
@Demonsthere unfortunately we do not have logs in the upgrade job until this ticket is tackled: <https://github.com/kyma-project/test-infra/issues/2674>

However, I was installing using the new config-production from master on current Kyma master. Since this is not a problem it has to be that the last released Kyma version doesn not understand the new overrides (new config-production) - which is ok.

If we look at the code, I think I know the exact problem, see comment in code
```go
    echo "Downlading production profile"
    curl -L --silent --fail --show-error "https://raw.githubusercontent.com/kyma-project/kyma/master/installation/resources/installer-config-production.yaml.tpl" \
        --output installer-config-production.yaml.tpl # <----------------- this should not be taken from master, I think this is the problem, just use the latest released kyma version of the file and it will be fixed
...
    (
    set -x
    kyma install \
        --ci \
        --source "${LAST_RELEASE_VERSION}" \
        -c installer-cr-azure-eventhubs.yaml.tpl \
        -o installer-config-production.yaml.tpl \
        -o installer-config-azure-eventhubs.yaml.tpl \
        -o "${EVENTHUB_SECRET_OVERRIDE_FILE}" \
        --timeout 90m
    )
```

**Comment by nachtmaar** [comment]
Logs are here: ```
2020/10/01 09:29:38 ---------------------------
2020/10/01 09:29:38 install component istio
2020/10/01 09:29:38 ---------------------------
2020/10/01 09:29:38 Get Kyma Sources
2020/10/01 09:29:38 Kyma sources available locally.
2020/10/01 09:29:38 Get Kyma Sources...DONE
2020/10/01 09:29:43 [debug] creating 1 resource(s)
2020/10/01 09:29:43 [debug] Starting delete for "kyma-ns-label" ServiceAccount
2020/10/01 09:29:43 [debug] serviceaccounts "kyma-ns-label" not found
2020/10/01 09:29:43 [debug] creating 1 resource(s)
2020/10/01 09:29:43 [debug] Starting delete for "kyma-ns-label" ClusterRole
2020/10/01 09:29:43 [debug] clusterroles.rbac.authorization.k8s.io "kyma-ns-label" not found
2020/10/01 09:29:43 [debug] creating 1 resource(s)
2020/10/01 09:29:43 [debug] Starting delete for "kyma-ns-label" ClusterRoleBinding
2020/10/01 09:29:43 [debug] clusterrolebindings.rbac.authorization.k8s.io "kyma-ns-label" not found
2020/10/01 09:29:43 [debug] creating 1 resource(s)
2020/10/01 09:29:44 [debug] Starting delete for "kyma-ns-label" Job
2020/10/01 09:29:44 [debug] jobs.batch "kyma-ns-label" not found
2020/10/01 09:29:44 [debug] creating 1 resource(s)
2020/10/01 09:29:44 [debug] Watching for changes to Job kyma-ns-label with timeout of 0s
2020/10/01 09:29:44 [debug] Add/Modify event for kyma-ns-label: ADDED
2020/10/01 09:29:44 [debug] kyma-ns-label: Jobs active: 0, jobs failed: 0, jobs succeeded: 0
2020/10/01 09:29:44 [debug] Add/Modify event for kyma-ns-label: MODIFIED
2020/10/01 09:29:44 [debug] kyma-ns-label: Jobs active: 1, jobs failed: 0, jobs succeeded: 0
2020/10/01 09:30:44 [debug] Add/Modify event for kyma-ns-label: MODIFIED
2020/10/01 09:30:44 [debug] kyma-ns-label: Jobs active: 1, jobs failed: 1, jobs succeeded: 0
2020/10/01 09:31:42 [debug] Add/Modify event for kyma-ns-label: MODIFIED
2020/10/01 09:31:42 [debug] Starting delete for "kyma-ns-label" Job
2020/10/01 09:31:42 [debug] creating 2 resource(s)
2020/10/01 09:31:42 [debug] beginning wait for 2 resources with timeout of 0s
2020/10/01 09:31:44 [debug] Starting delete for "istio-job" ServiceAccount
2020/10/01 09:31:44 [debug] serviceaccounts "istio-job" not found
2020/10/01 09:31:44 [debug] creating 1 resource(s)
2020/10/01 09:31:44 [debug] Starting delete for "istio-job" ClusterRole
2020/10/01 09:31:44 [debug] clusterroles.rbac.authorization.k8s.io "istio-job" not found
2020/10/01 09:31:44 [debug] creating 1 resource(s)
2020/10/01 09:31:44 [debug] Starting delete for "istio-job" ClusterRoleBinding
2020/10/01 09:31:44 [debug] clusterrolebindings.rbac.authorization.k8s.io "istio-job" not found
2020/10/01 09:31:44 [debug] creating 1 resource(s)
2020/10/01 09:31:44 [debug] Starting delete for "istio-install-job" Job
2020/10/01 09:31:44 [debug] jobs.batch "istio-install-job" not found
2020/10/01 09:31:44 [debug] creating 1 resource(s)
2020/10/01 09:31:44 [debug] Watching for changes to Job istio-install-job with timeout of 0s
2020/10/01 09:31:44 [debug] Add/Modify event for istio-install-job: ADDED
2020/10/01 09:31:44 [debug] istio-install-job: Jobs active: 0, jobs failed: 0, jobs succeeded: 0
2020/10/01 09:31:44 [debug] Add/Modify event for istio-install-job: MODIFIED
2020/10/01 09:31:44 [debug] istio-install-job: Jobs active: 1, jobs failed: 0, jobs succeeded: 0
2020/10/01 09:32:06 [debug] Add/Modify event for istio-install-job: MODIFIED
2020/10/01 09:32:06 [debug] istio-install-job: Jobs active: 1, jobs failed: 1, jobs succeeded: 0
2020/10/01 09:32:34 [debug] Add/Modify event for istio-install-job: MODIFIED
2020/10/01 09:32:34 [debug] istio-install-job: Jobs active: 1, jobs failed: 2, jobs succeeded: 0
2020/10/01 09:33:36 [debug] Add/Modify event for istio-install-job: MODIFIED
2020/10/01 09:33:36 [debug] uninstall: Deleting istio
2020/10/01 09:33:36 [debug] Starting delete for "istio-uninstall-job" Job
2020/10/01 09:33:36 [debug] jobs.batch "istio-uninstall-job" not found
2020/10/01 09:33:36 [debug] creating 1 resource(s)
2020/10/01 09:33:36 [debug] Watching for changes to Job istio-uninstall-job with timeout of 0s
2020/10/01 09:33:36 [debug] Add/Modify event for istio-uninstall-job: ADDED
2020/10/01 09:33:36 [debug] istio-uninstall-job: Jobs active: 0, jobs failed: 0, jobs succeeded: 0
2020/10/01 09:33:36 [debug] Add/Modify event for istio-uninstall-job: MODIFIED
2020/10/01 09:33:36 [debug] istio-uninstall-job: Jobs active: 1, jobs failed: 0, jobs succeeded: 0
2020/10/01 09:33:54 [debug] Add/Modify event for istio-uninstall-job: MODIFIED
2020/10/01 09:33:54 [debug] Starting delete for "istio-uninstall-job" Job
2020/10/01 09:33:59 [debug] Starting delete for "kyma-extra-manifests" ConfigMap
2020/10/01 09:33:59 [debug] Starting delete for "kyma-istio-control-plane-config" ConfigMap
2020/10/01 09:33:59 [debug] purge requested for istio
2020/10/01 09:33:59 Step error:  Details: Helm installation of release "istio" failed: failed post-install: job failed: BackoffLimitExceeded
Deleting release before retrying.
Helm delete of release "istio" was successfull
2020/10/01 09:33:59 Warning: Retry number 1 (sleeping for 10[s]).
```

```
$ k logs --namespace istio-system istio-install-job-2bjq4
istioctl manifest apply -f /etc/istio/config.yaml  --set "values.kyma_istio_operator=apiVersion" --set "values.kind=IstioOperator" --set "values.metadata=""" --set "values.  namespace=istio-system" --set "values.spec=""" --set "values.  components=""" --set "values.    ingressGateways=""" --set "values.    - name=istio-ingressgateway" --set "values.      k8s=""" --set "values.        hpaSpec=""" --set "values.          maxReplicas=10" --set "values.          minReplicas=3" --set "values.  values=""" --set "values.    global=""" --set "values.      proxy=""" --set "values.        resources=""" --set "values.          requests=""" --set "values.            cpu=150m" --set "values.            memory=128Mi" --set "values.          limits=""" --set "values.            cpu=500m" --set "values.            memory=1024Mi"
Error: invalid argument "\"values." for "-s, --set" flag: record on line 1; parse error on line 2, column 0: extraneous or missing " in quoted-field
```
