### ISSUE TITLE
Adding a new cluster addon configuration fails

### ISSUE THREAD

**Issue by suleymanakbas91** [kyma-project/kyma#9603]
**Description**

When I add a new cluster addon configuration using the URL `github.com/sap/xf-addons//addons/index.yaml?ref=0.11`, it fails with the following message:

![Screenshot 2020-10-01 at 15 12 28](https://user-images.githubusercontent.com/5543238/94813777-bc3fc280-03f8-11eb-8aa8-b8e85ccf3800.png)

Kyma version: 1.16.0-rc2

**Comment by magicmatatjahu** [comment]
Fixed by https://github.com/kyma-project/kyma/pull/9595
