### ISSUE TITLE
EventTriggers test in Console Backend fails

### ISSUE THREAD

**Issue by parostatkiem** [kyma-project/kyma#9612]
**Description**
https://status.build.kyma-project.io/view/gcs/kyma-prow-logs/logs/post-master-kyma-gke-central-connector/1311190859366010880
https://status.build.kyma-project.io/view/gcs/kyma-prow-logs/logs/post-master-kyma-gke-ver1_17_12-integration/1328639136214552576

**Expected result**

**Actual result**

**Steps to reproduce**

**Troubleshooting**

**Comment by kwiatekus** [comment]
We are getting rid of console backend and its tests
