### ISSUE TITLE
Tests fail on connection to DEX

### ISSUE THREAD

**Issue by tgorgol** [kyma-project/kyma#9618]
**Description**

Different tests fail because of errors while trying to connect to dex.

For example:
- apiserver-proxy tests [LOG](https://storage.googleapis.com/kyma-prow-logs/logs/post-master-kyma-integration/1312006363697647616/build-log.txt):
```
  2020/10/02 12:41:10 Retry: [0 / 4], error: Post https://dex.kyma.local/auth: dial tcp 10.164.0.29:443: connect: connection refused
```

- console-backend [LOG](https://storage.googleapis.com/kyma-prow-logs/logs/post-master-kyma-gke-integration/1311986104492101633/build-log.txt):
```
Post https://dex.gkeint-commit-f1b72a793-eoldb9q267.a.build.kyma-project.io/auth: read tcp 10.76.3.68:60476->35.204.168.25:443: read: connection reset by peer
```

- compass-runtime-agent-external-solution [LOG](https://storage.googleapis.com/kyma-prow-logs/logs/kyma-gke-compass-integration-daily/1310368934775492608/build-log.txt):
```
error: while performing HTTP POST on login endpoint: Post https://dex.gkecompint-commit-2f85e552d-o4gvjobgr6.a.build.kyma-project.io/auth/local?req=gz6cjafwayhhhfdbzsn4du4dq: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
```

**Comment by Tomasz-Smelcerz-SAP** [comment]
From the logs it's not clear what was the reason.
It may be that the DNS entry was misconfigured and the traffic never reached the cluster.
We can't reproduce it.
