### ISSUE TITLE
[Test Case] - Test end-to-end tracing

### ISSUE THREAD

**Issue by suleymanakbas91** [kyma-project/kyma#9631]
**Summary**

The purpose of this test is to ensure traces are getting carried end-to-end. We start with deploying the Commerce mock to the cluster and connect it with Kyma. Then, we create a sample function and send a sample event from the mock to this function. Finally, we observe from the Jaeger UI that the end-to-end flow is visible on the traces.

**Prerequisites**
- Kubeconfig is available 

**Test Steps**
1. Either in Kyma console or using kubectl, create a `tracing` namespace on Kyma
```bash
kubectl create namespace tracing
```

2. Create `mocks` namespace to deploy the commerce mock:

```bash
kubectl create namespace mocks
```
3. Deploy the commerce mock:

```bash
kubectl apply -f https://raw.githubusercontent.com/SAP/xf-application-mocks/master/commerce-mock/deployment/k8s.yaml -n mocks
kubectl apply -f https://raw.githubusercontent.com/SAP/xf-application-mocks/master/commerce-mock/deployment/kyma.yaml -n mocks
```

4. Create an Application on Kyma console and bind it to the `tracing` namespace:
     - Kyma Console->Integration->Applications/Systems->Create Application
5. To open the commerce mock, select the `mocks` namespace in Kyma console. Go to Discovery and Network->Services and under API Rules, click on Host URL.
6. Connect the application to the commerce mock:
    - Under Applications/Systems, select your application->Connect Application->Copy the URL
    - In the commerce mock, click `[Connect]` and paste the URL
6. In the commerce mock, register `Commerce Webservices` and `Events`:
    - Local APIs->SAP Commerce Cloud - Commerce Webservices->`[Register]`
    - Local APIs->SAP Commerce Cloud - Events->`[Register]`
7. On Kyma console, add instances for both to the `tracing` namespace:
   - Integration->Applications/Systems->the app you created in step 4->Create Binding->Select 'tracing' namespace->`[Create]`
   - `tracing` namespace->Service Management->Catalog->`SAP Commerce Cloud - Commerce Webservices`->`[Add Once]`->`[Create]`
   - `tracing` namespace->Service Management->Catalog->`SAP Commerce Cloud - Events`->`[Add Once]`->`[Create]`
8. In the `tracing` namespace, create a Function: Workloads->Functions->Create Function (use Node.js 12), copy and paste content of from [this sample](https://github.com/a-thaler/kyma-function-examples/tree/master/commerce):
    - `handler.js` into `Code->Sources` 
    - `package.json` into `Code->Dependencies`
    Save your changes
9. Configure the Function under `[Configuration]`:
   - Create Event Subscription -> Select `order.created` -> Save
   - Create Service Binding -> Choose service instance `sap-commerce-cloud-commerce-webservices_*` -> Create
   > For Kyma 2 enter Application Name: <the name passed in step 4>, enter Event Type: order.created
10. To send a sample event, open the commerce mock (see step 5) and go to:
    - Remote APIs->Commerce Cloud - Events->Select Event `order.created.v1`->Add some text to the event-body and disable `Cloud Event` switch->click `[Send Event]`
11. Go to Kyma Console->Diagnostics->Traces and select the Function name from the `[Service]` drop-down list and select `[Find Traces]`.
> For Kyma 2 Console->Observability->Tracing and select the Function name from the `[Service]` drop-down list and select `[Find Traces]`.
12. Check whether there is a trace from the mock to the Function.

**Expected Results**

 The end-to-end flow (from the mock to the Function) is visible on the traces.

**Comment by a-thaler** [comment]
Test case got fully automated
