### ISSUE TITLE
[Test Case] - Verify logs of observability components

### ISSUE THREAD

**Issue by suleymanakbas91** [kyma-project/kyma#9634]
**Summary**

The purpose of the test is to assure that there are no unexpected error logs in our components indicating potentially real issues

**Automation Steps**
Have a new test case that verifies all logs of our components and asserts on new error messages. There must be a way to whitelist errors.
The test case should be integrated into all typical test suites without having the assertion activated (only printing the results). At a later stage, we will activate the assertion.
There should be a new pre-submit job that is triggered only for our components which will assert

**Manual Test Cases**
```
kubectl logs --tail=-1 -l app=grafana -n kyma-system -c grafana | grep -v 'lvl=info'
kubectl logs --tail=-1 -l app=grafana -n kyma-system -c grafana-sc-dashboard-watcher
kubectl logs --tail=-1 -l app=grafana -n kyma-system -c grafana-sc-datasources-watcher
kubectl -n kyma-system logs -l app=prometheus -c prometheus --tail -1 | grep -v 'level=info'
kubectl -n kyma-system logs -l app=prometheus -c config-reloader --tail -1 | grep -v 'level=info'
kubectl -n kyma-system logs -l app=prometheus-node-exporter --tail -1 | grep -v 'level=info'
kubectl -n kyma-system logs -l app=monitoring-operator --tail -1 | grep -v 'level=info'
kubectl -n kyma-system logs -l app.kubernetes.io/name=alertmanager -c alertmanager --tail -1 | grep -v 'level=info'
kubectl -n kyma-system logs -l app.kubernetes.io/name=kube-state-metrics --tail -1
```

**Comment by a-thaler** [comment]
With the [removal of the monitoring component](https://github.com/kyma-project/kyma/issues/18258), this test case is obsolete
