### ISSUE TITLE
Serverless controller doesn't process functions created before controller starts

### ISSUE THREAD

**Issue by pbochynski** [kyma-project/kyma#9639]
**Description**
The controller doesn't create a build container for functions created earlier. Some functions can have unknown status.

**Expected result**
All functions should be reconciled.

**Actual result**
Only functions created after the controller starts are built.

**Steps to reproduce**

```
        kubectl apply -f assets/function.yaml
        helm upgrade --wait -i serverless resources/serverless --set $REGISTRY_VALUES -n kyma-system
```
Failing build: https://github.com/pbochynski/katacoda-scenarios/runs/1215381092?check_suite_focus=true

It works when you wait for controller to be ready:
```
      helm upgrade --wait -i serverless resources/serverless --set $REGISTRY_VALUES -n kyma-system
      kubectl wait --for condition=Ready=True pod -n kyma-system -l app=serverless
      kubectl apply -f assets/function.yaml
```  
Successful build: https://github.com/pbochynski/katacoda-scenarios/runs/1215392749?check_suite_focus=true

**Comment by aerfio** [comment]
It's kinda how controllers work @pbochynski, they are designed to react to events, as far as I'm aware (I may be wrong here though) k8s doesn't store those events anywhere to "resend" them again. If you want all functions to be reconciled we'd have to edit each function slightly (e.g add some kind of annotation), which I'd rather avoid. You've already provided solution to your problem and implementing mechanism, that would retrigger reconcilation of each and every resource would be kinda against how such a system works

**Comment by kwiatekus** [comment]
@pbochynski is it acceptable for you. Can we close it?
