### ISSUE TITLE
Application Connector sometimes fail to install

### ISSUE THREAD

**Issue by janmedrek** [kyma-project/kyma#9648]
**Description**

Application Connector sometimes fails to install on the first try due to Knative-related failures. Usually re-running the installation of this component solves the problem but this is not acceptable as we want to have a stable and resilient solution.

**Expected result**

Application Connector installation succeeds on the first run

**Actual result**

Sometimes the following error is returned and installation needs to be retriggered:
```
Error: Internal error occurred: failed calling webhook "legacysinkbindings.webhook.sources.knative.dev": Post https://eventing-webhook.knative-eventing.svc:443/legacysinkbindings?timeout=10s: dial tcp 10.43.51.249:443: connect: connection refused
```

**Steps to reproduce**

Installing Kyma on K3S usually results in this error

Related PR that fixed same problem in other namespaces: https://github.com/kyma-project/kyma/pull/9143

**Comment by k15r** [comment]
legacysinkbindings have been disabled in 1.19.1
