### ISSUE TITLE
api-gateway tests are failing in kyma-integration-gardener-aws job

### ISSUE THREAD

**Issue by sayanh** [kyma-project/kyma#9658]
**Description**

**Expected result**

It is found api-gateway tests are consistently failing in `kyma-integration-gardener-aws` job

Samples:
https://storage.googleapis.com/kyma-prow-logs/logs/kyma-integration-gardener-aws/1313841749050789888/build-log.txt

https://storage.googleapis.com/kyma-prow-logs/logs/kyma-integration-gardener-aws/1312754676076122112/build-log.txt

https://storage.googleapis.com/kyma-prow-logs/logs/kyma-integration-gardener-aws/1313117068794531840/build-log.txt

https://storage.googleapis.com/kyma-prow-logs/logs/kyma-integration-gardener-aws/1313479357636808704/build-log.txt

**Comment by strekm** [comment]
@sayanh can you please verify if it's still valid? please reopen if it's still making troubles.
