### ISSUE TITLE
kyma-upgrade-gardener-azure job fails in istio upgrade

### ISSUE THREAD

**Issue by sayanh** [kyma-project/kyma#9671]
**Description**

Samples:
https://storage.googleapis.com/kyma-prow-logs/logs/kyma-upgrade-gardener-azure/1314007844843950080/build-log.txt
https://storage.googleapis.com/kyma-prow-logs/logs/kyma-upgrade-gardener-azure/1313645451513171968/build-log.txt

**Comment by anishj0shi** [comment]
shall be addressed by: https://github.com/kyma-project/kyma/issues/8872
