### ISSUE TITLE
Think of a way to automatically test serverless runtimes' images

### ISSUE THREAD

**Issue by tgorgol** [kyma-project/kyma#9678]
**Description**

We are not verifying in any tests whether the variables available in lambda functions have all the fields correctly populated (such as Cloud Events metadata obtained from received headers).

The easiest way to achieve this would be to add such checks in serverless e2e tests but we wanted to avoid that. It may be better to create new tests that don't require full Kyma installation and test our runtime images by for example running them in docker and sending a request.

**Attachments**

Related issue: https://github.com/kyma-project/kyma/issues/9645

**Comment by kwiatekus** [comment]
It might me  good test case to try out git actions
Please contact @pbochynski to see how we could jump into this [project](https://github.com/kyma-incubator/local-kyma-k3d) with our test case

**Comment by kwiatekus** [comment]
When adding k3s based tests we should reduce the test scenarios running  on kyma integration, compass-integration jobs

**Comment by kwiatekus** [comment]
Tracked here https://github.com/kyma-project/kyma/issues/12849
