### ISSUE TITLE
istio-telemetry is unstable on loadtests

### ISSUE THREAD

**Issue by joek** [kyma-project/kyma#968]
**Description**
If I run a small load test, istio-telemetry is going into crashloop and no metrics are present in grafana.

The reason for the crash loop is out of memory. See attached mixer memory chart. 

![image](https://user-images.githubusercontent.com/202380/46082018-461b7c00-c19e-11e8-81f7-dec55b233f80.png)

If I increase the mixer memory to 524Mi memory limit, it is working fine.

![image](https://user-images.githubusercontent.com/202380/46082054-61868700-c19e-11e8-92c4-70d345670015.png)

**Expected result**

metrics in grafana even if the system is loaded.

**Actual result**
No Metrics, crashing istio-telemetry

**Steps to reproduce**

- Create small lambda and expose to the internet
- Run Load test with 200 paralel requests (does no so much matter how many but it should be some)

**Troubleshooting**
Have a look into kubernetes metrics. istio-telemetry is killed becaus of out of memory.

**Comment by pbochynski** [comment]
Should be easy to fix. Remember to keep low resources consumption in minikube (local).

**Comment by piotrmsc** [comment]
Ensure k8s QoS on istio control plane components for cluster setup

**Comment by piotrmsc** [comment]
Blocked by #382

**Comment by derberg** [comment]
you sure it is `good first issue` ?
