### ISSUE TITLE
[Test Case] - Check UI based getting started tutorials

### ISSUE THREAD

**Issue by kwiatekus** [kyma-project/kyma#9681]
**Summary**

Validates basic features of kyma  as application runtime.

**Prerequisites**
 - access to kyma runtime
 
**Environment**
Kyma runtime

**Test Steps**
Follow the [getting started guide](https://kyma-project.io/docs/master/root/getting-started/)

 - deploy a containerized microservice 
 - deploy a serverless function 
 - expose microservice/function via API Rule
 - consume redis service in the function/microservice
 - trigger the deployed microservice/function with an event.

**Comment by kwiatekus** [comment]
Lets close it once we have it automated via https://github.com/kyma-project/kyma/issues/10216

**Comment by k15r** [comment]
Removed `area/eventing` as this issue is always handled by someone from the ui teams
