### ISSUE TITLE
Fluent-bit stops processing input under pressure

### ISSUE THREAD

**Issue by hisarbalik** [kyma-project/kyma#9688]
**Description**
Caused by https://github.com/fluent/fluent-bit/issues/2621 fluent-bit can fall into a sleepy. It seems that only a re-start can bring it back into normal state. That affects the currently used fluent-bit version in 1.4.6

A fix hopefully will come with https://github.com/fluent/fluent-bit/pull/2672

A temporary workaround could be to add an alert rule informing about no cpu usage. Please check also existing alert rules of fluent-bit community to be incorporated.
.
**Reasons**

**Attachments**

**Comment by clebs** [comment]
Applied the changes in fluent/fluent-bit#2672 to our custom fluent-bit image.

After testing, the fix shows to be effective and log streams no longer get blocked.
