### ISSUE TITLE
Istio metrics are not properly aggregated

### ISSUE THREAD

**Issue by rakesh-garimella** [kyma-project/kyma#9701]
**Description**

At the moment the istio telemetry v2 gets used (not released yet, only master). The way of istio metrics needs to be processed changed heavily. Instead of scraping the single istio endpoint to get all metrics in an aggregated way, prometheus needs to scrape all pods directly and do the aggregation there.
To not overhelm prometheus with too many timeseries, the scraping is done on all pods but any notion of a pod gets dropped directly. Unfortunately, the aggregation part is missed and cannot be applied anymore. So it will keep the timeseries smaller but the values will not be correct.

Instead, all data needs to get scraped and aggregated indeed.
It seems that the only feasible solution is to introduce a dedicated prometheus instance responsible to scrape the istio metrics and doing the aggregation. The original prometheus instance will scrape the federation endpoint and will have the same responsibility and amount of data/timeseries as before the istio change happened.

**Expected result**

Istio metrics are correct

**Actual result**

Istio metrics are from one pod only, it is not the sum across all pods of a workload

**Steps to reproduce**

**Troubleshooting**

**Comment by a-thaler** [comment]
We tried to scrape the raw metrics from the pods and do the aggregation inside the existing prometheus. Unfortunately, the memory footprint is affected too heavy by dynamic workload. So instead we introduced a second lightweight prometheus taking care of only scraping and aggregating the istio metrics. The original prometheus will scrape that lightweight instance. As the time was too limited we couldn't achieve to document it proper, will be done with next release.
