### ISSUE TITLE
Alert in case of excessive Prometheus resource consumption on long running clusters

### ISSUE THREAD

**Issue by suleymanakbas91** [kyma-project/kyma#9704]
**Description**

We need to create an alert rule to be alerted in case Prometheus consumes the resources excessively on long-running clusters. This way we can discover any potential problems early on, notably OOM issues, that might come up in the user clusters.

**Implementation Steps** 

- Modify the current Alertmanager configurations to enable providing multiple Slack receivers.
- Create an alert rule that checks for Prometheus resource consumption (Memory, disk, etc.).
- Create a Slack API URL for an appropriate Slack channel to receive the alert.
- Create a Secret on Prow cluster including this API URL and Slack channel name.
- Create environment variables for both values and pass them as overrides in the GKE and Azure long-running cluster creation scripts on test-infra.
- Verify that an alert is fired in case Prometheus consumes the resources excessively on long-running clusters. 

**Acceptance Criteria**

- An alert is received in case Prometheus consumes the resources excessively on long-running clusters.

**Comment by a-thaler** [comment]
The overall approach has changed and the ticket is invalid
