### ISSUE TITLE
Fix minIO grafana chart queries 

### ISSUE THREAD

**Issue by m00g3n** [kyma-project/kyma#9727]
**Description**

MinIO grafana chart does not show data for the following queries:
- Data Transmited
- Data Received
- Total In/Out Throughput
- HTTP Requests duration/s

**Expected result**
Queries return data

**Actual result**

![image](https://user-images.githubusercontent.com/45931826/96431710-326b6400-1204-11eb-9469-513e15013da0.png)

**Steps to reproduce**
Go to Grafana page via Kyma web console. 

**Troubleshooting**
Change metrics in queries:
- minio_network_sent_bytes_total -> s3_tx_bytes_total
- minio_network_received_bytes_total -> s3_rx_bytes_total and internode_rx_bytes_total
- minio_http_requests_duration_seconds_sum -> s3_ttfb_seconds_sum

**Comment by a-thaler** [comment]
Fixed the charts by using the new metrics
