### ISSUE TITLE
no external postgresql db possible for Ory Hydra (1.15.1 or 1.16.0-rc2) during fresh installation

### ISSUE THREAD

**Issue by tehret77** [kyma-project/kyma#9745]
**Description**
We try to use Ory Hydra with an external PostgreSQL DB on Azure.
We provisioned a Azure Database for PostgreSQL server with default settings. One of the default settings is to enforce SSL connection.

For the initial deployment we used the description at [OAuth Server Profile > Production profile](https://kyma-project.io/docs/1.16/components/security/#configuration-o-auth2-server-profiles-use-the-production-profile) with the linked [User maintained](https://kyma-project.io/assets/docs/kyma/1.16/security/docs/assets/003-ory-db-custom.yaml) file as template.
As a side node: for Azure the parameters global.ory.hydra.persistence.user in the configmap and global.ory.hydra.persistence.password in the secret should be URL encoded. For the username it is required as the format is <username>@<hostname> which produce a problem in the DSN splitting later. For the password it is required in case special characters are used (like: * {).

It would be helpful to have a override parameter DNS_OPTS to specify required connection parameters.

**Expected result**

During the installation the configmap and secret overrides are used to generate the secret `ory-hydra-credentials` in the `kyma-system` namespace. The key DSN is generated with the value `postgres://<url encoded username with format username@hostname>:<url encoded password>@<hostname>.postgres.database.azure.com:5432/db4hydra?sslmode=require&max_conn_lifetime=10s`

**Actual result**

The key DSN is generated with the value `postgres://<url encoded username with format username@hostname>:<url encoded password>@<hostname>.postgres.database.azure.com:5432/db4hydra?sslmode=disable&max_conn_lifetime=10s`

**Steps to reproduce**

Follow the instruction to use a user maintained external PostgreSQL database
Check the secret `ory-hydra-credentials` during installation

**Troubleshooting**

Manually patch the key DSN in the secret `ory-hydra-credentials` once it is created during the installation procedure.

**Comment by piotrmsc** [comment]
I think we should describe the required DSN format in our docs and yeah DSN options we could provide configurable as well

**Comment by strekm** [comment]
need to take it out from 1.19

**Comment by strekm** [comment]
as of [kyma 2.2](https://kyma-project.io/blog/2022/5/4/release-notes-22#ory-stack-deprecation-note) ORY stack is deprecated since we decided that we would like to invest in closer integration with Istio. any work related to ORY will be discontinued. thank you for your understanding and stay tuned for new features :)
