### ISSUE TITLE
Add links to adequate https://kyma-project.io/ links in README.md files

### ISSUE THREAD

**Issue by kazydek** [kyma-project/kyma#9746]
**Description**

Our documentation strategy stresses the use of website docs rather than their GitHub sources, for example by the approach we have to [links](https://kyma-project.io/community/guidelines/content/#links-links). That's why we should clearly state in all `README.md` files in `docs` folders on repositories that have documentation exposed on the website that we have this approach, GitHub contains only sources of docs, links won't work there, and we encourage to use of docs on https://kyma-project.io/.

A note should be enough.

These are the repos that require it:

- `kyma/docs/README.md` -> https://kyma-project.io/docs/
- `community/docs/README.md` -> https://kyma-project.io/community/
- `cli/docs/README.md` ->  https://kyma-project.io/docs/cli/
- `control plane/docs/README.md` -> https://kyma-project.io/docs/control-plane/

**Area**

Website documentation

**Assignees**

@kyma-project/technical-writers

**Comment by mmitoraj** [comment]
The issue is no longer relevant for Kyma 2.0.
