### ISSUE TITLE
Istio Sidecar of istio-ingressgateway gets OOM killed

### ISSUE THREAD

**Issue by JonasBentz** [kyma-project/kyma#9751]
The istio sidecar of our istio ingressgateway pod gets OOM killed all the time. As a consequence our services is not reachable from outside the cluster. 
Kyma-Version: 1.15.1

![image](https://user-images.githubusercontent.com/73304260/96906089-9eb2c580-1499-11eb-8b18-eb40d10c9ee5.png)

**Expected result**

Ingress gateway comes up properly to serve traffic

**Actual result**

Ingress gateway doesnt get ready due to OOM of sidecar

**Steps to reproduce**

We have multiple clusters with the exact same deployment in it. We can reproduce the issue there aswell.

**Troubleshooting**

When we add RAM to the Resource limits the ingress gateway comes up properly.

**Comment by JonasBentz** [comment]
Problem still occurs even after giving the deployment 5x RAM. Istio-pilot has the same problem aswell now.

![image](https://user-images.githubusercontent.com/73304260/96976429-20e3ce00-151c-11eb-95a2-457f8b9eb6dd.png)


Are there any special logs that I should try to gather?

**Comment by JonasBentz** [comment]
Its possible to reproduce the problem in our other clusters aswell.

**Comment by piotrmsc** [comment]
Please provide more details about your setup, your load and if you can reproduce it, please provide steps so that we can reproduce it as well :)

**Comment by JonasBentz** [comment]
Upgrading to kyma 1.6 release candidate fixxed the issue. Issue seems only related to istio 1.5.

Issue is described here I guess: https://github.com/knative/serving/issues/7926

Are you still interested in more details about our setup?

**Comment by colunira** [comment]
Did you mean Kyma 1.16? It contains Istio in version 1.5, Kyma 1.15 has Istio 1.4. 

If Kyma 1.16 resolves this problem, please close the issue :)
