### ISSUE TITLE
Misleading configuration of IDPPresets CR

### ISSUE THREAD

**Issue by kubadz** [kyma-project/kyma#976]
**Description**

There are two fields in an IDPPresets CR: metadata.name and spec.name. The first one is the name of the k8s resource so it might be guessed that second should be used as the name of the preset. Turns out, that spec.name is not used anywhere still being a required field of the CR. 

Presets created through UI are created with both metadata.name and spec.name set to the same value, so the problem seems to not exist in that case as both values can't be different. Where it does occur is in the creation of IDPPreset from CR resource where it is not clear for what reason the spec.name value is used.
In the UI presets are distinguished by only one name value - the value received from graphql query. And that value comes from a metadata.name of CR what can be seen [here](https://github.com/kyma-project/kyma/blob/master/components/ui-api-layer/internal/domain/ui/idppreset_converter.go#L16). However, the tests seem to make [a proper assertion for the name](https://github.com/kyma-project/kyma/blob/master/components/ui-api-layer/internal/domain/ui/idppreset_converter_test.go#L31) (from spec, not metadata), but are passing only because IDPPreset configuration used in the test has the same values in spec.name and metadata.name.

There are two ways out:
- remove the spec.name field from IDPPreset CRD
- make the graphql service return the spec.name and make changes necessary for proper handling creation and deletion of resources 

**Expected result**

After creating IDPPreset from yaml:
```
apiVersion: ui.kyma.cx/v1alpha1
kind: IDPPreset
metadata:
  name: preset1
spec:
  issuer: https://example.com
  jwksUri: https://example.com/keys
  name: example"
```
I expect to see preset named "example" in the UI.

**Actual result**

I can see preset "preset1" in the UI.

**Comment by pbochynski** [comment]
Just to be sure - do you plan to remove name attribute from spec? Or do you plan to use it in the UI?
