### ISSUE TITLE
Optimize number of reconciliation calls in eventing-controller

### ISSUE THREAD

**Issue by nachtmaar** [kyma-project/kyma#9766]
Currently the number of reconciliations for one Subscription is very high because the status of the Subscription is changed multiple times (and written to etcd). An alternative to this is to only update the status at the end of the reconciliation. 

Please ensure that status changes are not lost (e.g. if the end of the reconcile method is never reached).

This approach will also help us to separate in the future the "K8S controlling" part, which will remain inside of eventing-controller and the "subscriptions manager (first BEB and later NATS)" which  will be moved outside of eventing-controller.

**Remarks**
-  [ ] check if code improvements can be implemented as well, or create a new ticket for such changes

Target: 
- aim for 1 update for subscription plus one for the status subresource

**Acceptance**
- [x] #13025
- [x] #13026

**Comment by radufa** [comment]
Refactoring the code should also try to use the K8S library instead of an external one (hashstructure package) to calculate the deep hash value, see:
Kubenetes controller https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/controller_utils.go#L1130-L1145.

**Comment by berkanercan** [comment]
1. Optimize calls to api server
2. Optimize the number of request to BEB (has higher prio)

**Comment by k15r** [comment]
estimate is just for the BEB part

**Comment by k15r** [comment]
- [ ] https://github.com/kyma-project/kyma/issues/12032
- [ ] https://github.com/kyma-project/kyma/issues/11988

**Comment by radufa** [comment]
Here is a comment which should be also solved: https://github.com/kyma-project/kyma/pull/13070/files#r784688541

**Comment by radufa** [comment]
For NATS controller, the PR: https://github.com/kyma-project/kyma/pull/13070 optimizes the reconcilations calls too, r3ducing them at the minimum.
