### ISSUE TITLE
Define readiness/liveness for eventing-controller

### ISSUE THREAD

**Issue by nachtmaar** [kyma-project/kyma#9769]
Define readiness/liveness for eventing-controller. Does kubebuilder come with a default readiness/liveness probe and is that enough for us?

**Comment by k15r** [comment]
https://github.com/kubernetes-sigs/kubebuilder/pull/1856/files

**Comment by berkanercan** [comment]
Expectation: basic readiness probes, which would return 200. (endpoints: /readyz, /healthz)
