### ISSUE TITLE
Introduce proper PodSecurityPolicy for function build job

### ISSUE THREAD

**Issue by aerfio** [kyma-project/kyma#9779]
**Description**

In serverless we're internally using [kaniko](https://github.com/GoogleContainerTools/kaniko) to build function images. Up till now we've not taken proper care for it's security, which needs to be changed. I propose to introduce PodSecurityPolicy resource for kaniko build jobs, which will take care of this issue.

**Reasons**

Proper permissions and restrictions need to be set in order to use cluster with ease and safety.

**Attachments**

https://github.com/GoogleContainerTools/kaniko#security

See also https://github.com/kyma-project/kyma/issues/9531

**Comment by kwiatekus** [comment]
Done with https://github.com/kyma-project/kyma/pull/10292
