### ISSUE TITLE
Unify instalation of k3s for all operating systems gitops tutorials

### ISSUE THREAD

**Issue by dbadura** [kyma-project/kyma#9788]
**Description**

We should link to installation page of k3s instead of limiting installation to macOS only.
Here is the tutorial: https://github.com/kyma-project/kyma/blob/f93abe9d94efdfc712e73e49b2c8850d9a6092a5/docs/serverless/08-07-sync-function-with-gitops.md
**Area**

Serverless

**Reasons**

Not everybody is using macOS and people who don't use macOS need to search the internet how to install k3s.

**Assignees**

@technical-writers

**Attachments**

**Comment by kwiatekus** [comment]
Closing. See linked issue
