### ISSUE TITLE
Enable private npm package repositories in serverless

### ISSUE THREAD

**Issue by kwiatekus** [kyma-project/kyma#9791]
**Description**

Support private npm repos in kyma serverless.
User should be able to provide credentials to private npm repos and consume private packages in their lambdas.

**AC**
 - users should be able to define secrets in the namespace that include access tokens (i.e NPM-TOKEN) 
 - STRETCH : check if we can accomplish the same mechanism for python runtime

**Reasons**

To keep functions as small as possible, it is required to outsource reusable logic into NPM packages. 
Right now, only public  npmjs.org is supported which prevents using private packages.

**Comment by nazarkulyk** [comment]
Maybe it should be posible to provide access to create .npmrc, or have an "Secret" tab on function settings, like github has on repositories, that can be used as token.

//registry.npmjs.org/:_authToken=${NPM_TOKEN}

See:
https://docs.npmjs.com/using-private-packages-in-a-ci-cd-workflow

**Comment by nazarkulyk** [comment]
Also i need a way to define other repositories than public official. As example one from github self...
@ibsolution-de:registry=https://npm.pkg.github.com/ibsolution-de

**Comment by kwiatekus** [comment]
Solution for node functions could be done by defining a secret in a namespace (including NPM_TOKEN) that would be looked up at the build time
https://docs.npmjs.com/using-private-packages-in-a-ci-cd-workflow
