### ISSUE TITLE
Unable to connect Applications mocks to Kyma after upgrade to istio-1.7

### ISSUE THREAD

**Issue by rakesh-garimella** [kyma-project/kyma#9795]
**Description**

While testing application mocks on kyma with istio-1.7 we see that the application mocks are not able to connect to kyma and they give following error:

```
Error: write EPROTO 139715443133288:error:14094418:SSL routines:ssl3_read_bytes:tlsv1 alert unknown ca:../deps/openssl/openssl/ssl/record/rec_layer_s3.c:1536:SSL alert number 48
```

Although its see sometimes we are able to connect but then it fails again during `register`.

**Expected result**

The application is able to connect to kyma without any issue.

**Actual result**

Connection of application to kyma fails.

**Steps to reproduce**

1. Install kyma with istio-1.7
2. Try to connect application mock.

**Troubleshooting**

**Comment by Demonsthere** [comment]
Possible culprit: on a managed certificate environment (like gardener) the `kyma-gateway-certs` secret which holds TLS certs is managed by cert-manager. It creates a CA entry in the file, which is used by istio-ingressgateway instead of our CA, which is being held in `kyma-gateway-certs-cacert`

**Comment by pbochynski** [comment]
https://istio.io/latest/docs/tasks/traffic-management/ingress/secure-ingress/#configure-a-mutual-tls-ingress-gateway
> Istio supports reading a few different Secret formats, to support integration with various tools such as cert-manager:
> - A TLS Secret with keys tls.key and tls.crt, as described above. For mutual TLS, a ca.crt key can be used.
> - A generic Secret with keys key and cert. For mutual TLS, a cacert key can be used.
> - A generic Secret with keys key and cert. For mutual TLS, a separate generic Secret named <secret>-cacert, with a cacert key. For example, httpbin-credential has key and cert, and httpbin-credential-cacert has cacert.

**Comment by Demonsthere** [comment]
Yeah, we know that. The problem is, that what you have sent us is the order of priority Istio uses. If a ca.crt field is found in the httpbin-credential, Istio is not looking up httpbin-credential-cacert has cacert, which acts as a fallback

**Comment by pbochynski** [comment]
Hmm. I have exactly such setup and it works. I have secret with 3 keys: tls.key, tls.crt and ca.crt (from lets encrypt). Another secret with suffix -cacert contains only cacert key. I am testing with istio 1.7.4. Both secrets are of type Opaque. First one generated by Gardener certificate manager.

**Comment by Demonsthere** [comment]
Update: It seems that it was a bug in the 1.7.1, which we were using. We have updated to 1.7.4 and it seems to work as expected. We are testing install and upgrade scenario on the newer version

**Comment by Demonsthere** [comment]
Related PR: https://github.com/kyma-project/kyma/pull/9845
