### ISSUE TITLE
post-master-kyma-gke-upgrade test failed

### ISSUE THREAD

**Issue by radufa** [kyma-project/kyma#9798]
**Description**

Upgrade test failed due to issues resolving the cluster domain from global.overrides

https://status.build.kyma-project.io/view/gcs/kyma-prow-logs/logs/post-master-kyma-gke-upgrade/1323191313440444416
https://status.build.kyma-project.io/view/gcs/kyma-prow-logs/logs/post-master-kyma-gke-upgrade/1321737842195435521

```Fetching logs
  Start of logs from container "tests" in pod "oct-tp-testsuite-all-before-upgrade-prepare-eventmeshupgradetest-0" in status "Failed"
  TESTING start
  time="2020-10-29T09:19:17Z" level=info msg="using domainName: "
  time="2020-10-29T09:19:17Z" level=fatal msg="while reading domain name from cluster: Could not get valid domain name"
  exit_code is 1
```

**Comment by k15r** [comment]
```
Fetching logs
  Start of logs from container "tests" in pod "oct-tp-testsuite-all-before-upgrade-prepare-eventmeshupgradetest-0" in status "Failed"
  TESTING start
  time="2020-10-29T09:19:17Z" level=info msg="using domainName: "
  time="2020-10-29T09:19:17Z" level=fatal msg="while reading domain name from cluster: Could not get valid domain name"
  exit_code is 1
```

**Comment by k15r** [comment]
Removed area/eventing label as the code that return the error is executed with every upgrade scenario. as can be seen on the links posted in the description not only eventing related tests are affected.
