### ISSUE TITLE
Knative kafka dispatcher/channel graphs in eventing dashboards 

### ISSUE THREAD

**Issue by sayanh** [kyma-project/kyma#9847]
**Description**

As a person on on-call, I'd like to see the delivery stats for an event on all pods it flows through. For Kyma which are provisioned with knative-kafka we don't have such stats/graphs in eventing dashboards. While debugging it is critical to understand the delivery status of knative-kafka channel(persists events to Azure eventhub(EH)) and knative-kafka dispatchers(triggers the subscriber with the event from the Azure EH).

**Reasons**

- Facilitates quick debugging at odd hours
- Helps to drill down the issues which happen over a long time

**Comment by pbochynski** [comment]
Please estimate the effort - we should not do it if it is not quick.

**Comment by k15r** [comment]
Will close for now, as we plan to replace knative kafka
