### ISSUE TITLE
Publishing Proxy for NATS

### ISSUE THREAD

**Issue by k15r** [kyma-project/kyma#9852]
as a kyma open source user i want to use the same documented publishing endpoint for sending events to NATS as i can use to send events to BEB, so that i do not have to change my code when i switch between OSS and managed offering of kyma

Acceptance Criteria:
- [ ] events get forwarded to NATS
- [ ] cloudevents 1.0 are accepted
- [ ] proxy gets installed and is available on the documented endpoint for the entire cluster

https://github.tools.sap/skydivingtunas/team/blob/master/roadmap.org#create-a-publishing-proxy-for-nats

**Comment by radufa** [comment]
See the related PR: https://github.com/kyma-project/kyma/pull/10331
