### ISSUE TITLE
Connect Publishing Proxy for BEB to application

### ISSUE THREAD

**Issue by k15r** [kyma-project/kyma#9861]
As a kyma user i want to be able to send events from my connected application to the eventing backend, so that i can later consume them in my workload

Acceptance Criteria:
- [x] proxy is installed as an optional component using kyma installer (SKR)
- [x] cloudevents 1.0 are accepted and forwarded to BEB
- [x] events sent from a connected application get forwarded to BEB
- [x] legacy events sent from an application shall be converted to cloudevents 1.0 automatically
- [x] OSS still works using event mesh

**Comment by berkanercan** [comment]
In the application operator, we need a switch to decide which charts to deploy. Option 1 is event mesh: knative eventing charts. Option 2: Event publish proxy; which should be configured with the application validator.
