### ISSUE TITLE
Migrate event-service functionality to publishing proxy

### ISSUE THREAD

**Issue by k15r** [kyma-project/kyma#9870]
As a kyma cluster administrator i do not want one event-service deployment per connected application in order to free resources. For eventing users this removes one hop from the communication per event, and will also improve performance

Acceptance Criteria:
- [x] legacy events sent to the publishing proxy will be converted to cloudevents
- [x] info endpoint needs to work

**Comment by sayanh** [comment]
Tasks:
- [ ] Design the workflow with functionalities
- [ ] Move event-service code to EPP
