### ISSUE TITLE
Put  the image "connecteverything/nats-operator:0.7.4" into the Kyma registry 

### ISSUE THREAD

**Issue by radufa** [kyma-project/kyma#9875]
Let's sync this image to the Kyma registry and use it: https://github.com/kyma-project/test-infra/blob/master/development/image-syncer/external-images.yaml

_Originally posted by @nachtmaar in https://github.com/kyma-project/kyma/pull/9864#r518151666_

**Comment by radufa** [comment]
See: https://github.com/kyma-project/kyma/pull/9864#discussion_r518151666

**Comment by radufa** [comment]
See also: https://github.com/kyma-project/kyma/pull/9864#discussion_r518151666

**Comment by k15r** [comment]
#10930
