### ISSUE TITLE
Kiali does not show graph and metrics for apps

### ISSUE THREAD

**Issue by a-thaler** [kyma-project/kyma#9886]
**Description**
After the upgrade to istio temetry v2 starting with kyma 1.16/1.17, in kiali the graph does not contain any edges anymore. Furthermore, any request metrics are missing including the request charts in the apps detail view.

In the kiali logs you can see these error messages:

```
Skipping {destination_service="kubernetes.default.svc.cluster.local", destination_service_name="kubernetes.default.svc.cluster.local", destination_service_namespace="unknown", destination_workload="unknown", destination_workload_namespace="unknown", source_workload="service-catalog-addons-service-binding-usage-controller", source_workload_namespace="kyma-system"}, missing expected TS labels
```

It turned out that when switching the monitoring stack to istio 1.5/1.7 the reduced label set is a problem for kiali. Currently the scrape config for the istio-proxy metrics is dropping specific labels like the "destination_canonical_revision" label. They were introduced with the new istio version and are not used in the istio grafana dashboards and are bringing no further information to the metric data. In order to decrease the already big cardinality they were dropped.

Unfortunately, the new kiali versions supporting istio 1.7 are requiring that labels, which is also documented here: https://github.com/jshaughn/kiali.io/blob/89536edabed604239c409b9609b1e43724be64eb/content/documentation/staging/faq/general/prom-metrics.adoc

Other people went into that trap as well as you can see here: https://github.com/kiali/kiali/issues/3289 or https://github.com/kiali/kiali/issues/1007

**Expected result**

Kiali is shown full graph and metrics about traffic for apps

**Actual result**

Kiali is not shown data infos

**Steps to reproduce**

**Troubleshooting**

You can remove the label drop by editing the prometheus-istio configuration.
Edit the configmap by
```kubectl -n kyma-system edit configmap monitoring-prometheus-istio-server```
 then remove the full "metric_relabel_configs" block from the scrape config.

Be aware of that this will increase the amount of timeseries being created in both prometheus instances and with that the memory footprint, dependent on the cardinality of communication topology.

**Comment by clebs** [comment]
This issue can be solved by removing the following part of the prometheus relabeling config:
https://github.com/kyma-project/kyma/blob/1.17.0-rc1/resources/monitoring/charts/prometheus-istio/values.yaml#L1281-L1285

Unfortunately, we can't apply this fix right now because it causes prometheus to run out of memory.
To apply this fix, first #9867 needs to be addressed.

**Comment by rakesh-garimella** [comment]
Created a following [issue](https://github.com/kiali/kiali/issues/3496) in the kiali to request the feature.

**Comment by rakesh-garimella** [comment]
After adding following labels to drop I see the kiali graphs are back and the side effect is we see close to 20K more timeseries after 24 hours.

```
^(grpc_response_status|request_protocol|source_version|destination_version|source_principal|destination_principal|source_app|destination_app)$
```

**Comment by a-thaler** [comment]
We made the droplabel regex configurable and introduced all required labels, with that kiali is fixed. If you run into memory problems with prometheus you can introduce label drops by:

`prometheus-istio.envoyStats.labeldropRegex: "^(grpc_response_status|source_version|source_principal|source_app|response_flags|request_protocol|destination_version|destination_principal|destination_app|destination_canonical_service|destination_canonical_revision|source_canonical_revision|source_canonical_service)$"`
