### ISSUE TITLE
Upgrade monitoring main chart

### ISSUE THREAD

**Issue by a-thaler** [kyma-project/kyma#9891]
**Description**
Nearly all applications used in the monitoring component require an update, same for the helm charts itself. So it is time to upgrade and consolidate.

AC:

- [x] Upgrade main chart separating the operator into an own sub-chart. Verify the naming of the statefulset and check if it is not causing problems on upgrade, upgrade image of operator and prometheus
- [x] Verify that for all chart upgrades note down at least as a comment the new chart version in the chart.yaml
- [x] Verify that for all images assure there are based on the kyma docker registry
- [x] Verify that for all re-builded docker images assure newest base image version is used
- [x] Verify setup by running monitoring test cases

**Reasons**

**Attachments**

**Comment by skhalash** [comment]
PR: https://github.com/kyma-project/kyma/pull/9957

**Comment by skhalash** [comment]
Merged  #9957. As per discussion with @a-thaler:
* `prometheus-istio` will be handled separately
* `prometheus-operator` will not be converted to a sub-chart to keep it aligned with the upstream chart

**Comment by a-thaler** [comment]
Main chart and prometheus image got upgraded
