### ISSUE TITLE
Upgrade to Loki 2

### ISSUE THREAD

**Issue by a-thaler** [kyma-project/kyma#9892]
**Description**
Loki 2.x is out and provides several new features. Time to offer them in kyma as well.

AC:
- [x] Upgrade to newest Loki version
- [x] Verify grafana usage
- [x] Verify pod logs and lambda logs in kyma console
- [x] Verify that an upgrade will keep old log data
- [ ] Check if unifying the index storage with the log storage is a meaningful default setup and create follow-up task 

**Reasons**

**Attachments**

**Comment by suleymanakbas91** [comment]
Upgrade has been merged using the current schema. I created a follow-up [task](https://github.com/kyma-project/kyma/issues/10592) to upgrade the schema later.
