### ISSUE TITLE
Upgrade monitoring sub-charts

### ISSUE THREAD

**Issue by a-thaler** [kyma-project/kyma#9897]
**Description**
Follow-up of https://github.com/kyma-project/kyma/issues/9891

Nearly all applications used in the monitoring component require an update, same for the helm charts itself. So it is time to upgrade and consolidate.

AC:
- [x] Upgrade grafana chart and image version (also k8s-sidecar and config-reloader)
- [x] Upgrade kube-state-metrics chart and image version
- [x] Upgrade prometheus-node-exporter chart and image version
- [x] Upgrade prometheus-pushgateway chart and image version
- [x] Upgrade prometheus-istio chart and image version
- [x] Verify that for all chart upgrades note down at least as a comment the new chart version in the chart.yaml
- [x] Verify that for all images assure there are based on the kyma docker registry
- [x] Verify that for all re-builded docker images assure newest base image version is used

**Reasons**

**Attachments**

**Comment by rakesh-garimella** [comment]
Prometheus-pushgateway
 * Image update: https://github.com/kyma-project/test-infra/pull/2978

**Comment by skhalash** [comment]
* grafana
Main image: https://github.com/kyma-project/test-infra/pull/2990
Sidecar image: https://github.com/kyma-incubator/third-party-images/pull/43
Chart: https://github.com/kyma-project/kyma/pull/10085
* prometheus-istio
Image: already used by main prometheus
Chart: https://github.com/kyma-project/kyma/pull/10067
* kube-state-metrics
Image: https://github.com/kyma-project/test-infra/pull/2985
Chart: https://github.com/kyma-project/kyma/pull/10065
* node-exporter
Image: https://github.com/kyma-incubator/third-party-images/pull/41
Chart: https://github.com/kyma-project/kyma/pull/10025

**Comment by a-thaler** [comment]
All sub-scharts updated
