### ISSUE TITLE
Define evaluation and production profile for console chart

### ISSUE THREAD

**Issue by kwiatekus** [kyma-project/kyma#9898]
**Description**

Define `production` and `evaluation` profiles for console chart.
 - For production, create a `profile-production.yaml` file. We can start with the current default values ( for cbs and console-web). Think which resources require higher values
 - For evaluation, create `profile-evaluation.yaml` file - request less cpu time and memory.

The defaults ( default values from values.yaml  - means "no profile" or default profile ) should be matching values in the middle between evaluation and production.

Current resources utilisation ( on  cluster with little trafic )
```
Name                                     CPU Requests  CPU Limits  Memory Requests  Memory Limits  
----                                     ------------  ----------  ---------------  ------------- 
console-web-77d55fd8db-5b52v                   0 (0%)      0 (0%)        64Mi (0%)     192Mi (1%)     
console-backend-865944bd45-cmnjx             75m (1%)   250m (6%)       128Mi (1%)     556Mi (4%)     
```
**Reasons**

There is no golden setup that fulfils all possible installation cases. Evaluation of kyma should be cheap and possible to realise on one node cluster. Production grade installation requires significant amount of processing time and memory ( especially on CBS)

**Attachments**

**Comment by pbochynski** [comment]
Resolved by https://github.com/kyma-project/kyma/pull/10133
