### ISSUE TITLE
Deletion of monitoring-custom-metrics resources throws permission errors

### ISSUE THREAD

**Issue by tobiscr** [kyma-project/kyma#9903]
**Description**

When running through the [KYMA monitoring-tutorial](https://kyma-project.io/docs/components/monitoring#tutorials-observe-application-metrics) on version KYMA 1.17.0-rc1, the first cleanup step throws several permission errors:

       kubectl delete all -l example=monitoring-custom-metrics -n testing-monitoring
       pod "sample-metrics-12345-wkhmz" deleted
       service "sample-metrics-8080" deleted
       service "sample-metrics-8081" deleted
       deployment.apps "sample-metrics" deleted
       replicaset.apps "sample-metrics-12345" deleted
       Error from server (Forbidden): sequences.flows.knative.dev is forbidden: User "admin@kyma.cx" cannot list resource "sequences" in API group "flows.knative.dev" in the namespace "testing-monitoring"
       Error from server (Forbidden): parallels.flows.knative.dev is forbidden: User "admin@kyma.cx" cannot list resource "parallels" in API group "flows.knative.dev" in the namespace "testing-monitoring"
       Error from server (Forbidden): apiserversources.sources.knative.dev is forbidden: User "admin@kyma.cx" cannot list resource "apiserversources" in API group "sources.knative.dev" in the namespace "testing-monitoring"
       Error from server (Forbidden): sinkbindings.sources.knative.dev is forbidden: User "admin@kyma.cx" cannot list resource "sinkbindings" in API group "sources.knative.dev" in the namespace "testing-monitoring"

Tested with KYMA version: 1.17.0-rc1
Cluster provider: GKE
Kubernetes version: v1.16.15-gke.4300
Kubectl version: 0.16.15

**Expected result**

No permission issues reported by kubectl during deletion.

**Actual result**

User "admin@kyma.cx is not allowed to list:
* sequences.flows.knative.dev
* parallels.flows.knative.dev
* apiserversources.sources.knative.dev
* sinkbindings.sources.knative.dev 

**Steps to reproduce**

Follow the steps described in the [KYMA monitoring-tutorial](https://kyma-project.io/docs/components/monitoring#tutorials-observe-application-metrics).

**Troubleshooting**

Namespace was deleted by K8s, but deletion took extremely long. No deeper analysis happened yet on my side.

**Comment by berkanercan** [comment]
<img width="786" alt="Screenshot 2020-12-07 at 20 15 46" src="https://user-images.githubusercontent.com/18217868/101394909-7c4dfd80-38c9-11eb-9c32-7e96072944bd.png">
I could not reproduce the issue. Can we check it later together @tobiscr?

**Comment by berkanercan** [comment]
I could recreate the issue when I downloaded the kubeconfig from kyma console. By this action I could test the issue with admin@kyma.cx user.

**Comment by berkanercan** [comment]
The fix is tesible on a gcp cluster called "berkan-deletion-bug"

**Comment by berkanercan** [comment]
Fix is merged with upstream master https://github.com/kyma-project/kyma/commit/1cb340d16d0ececadbe248e64804eb719a1e9d6b
