### ISSUE TITLE
Low request/second response when ApiRule is set to noop

### ISSUE THREAD

**Issue by valentinvieriu** [kyma-project/kyma#9940]
**Description**

Creating a simple service using an NGINX docker image with a simple static website, and an ApiRule with default configuration, we get  around 160-170 request/second for a 3 cluster nodes  ( 4cpu + 16GB ram ).
Setting the ApiRule to allow increases the req/sec considerable 800-900/req/seq

**Expected result**

We should get higher requests/s with default settings. ( 2000-3000 req/sec )

**Actual result**

We get 160-170 request/second for a 3 cluster nodes  ( 4cpu + 16GB ram ).

**Steps to reproduce**

Create a simple service using an NGINX docker image with a simple static website, and an ApiRule with default configuration.
Use `wrk` to test the response time:
```sh
wrk -t12 -c128 -d100s --latency https://art-explorer.prod.kymart.shoot.canary.k8s-hana.ondemand.com/
```

**Troubleshooting**

**Comment by pbochynski** [comment]
Short term solution: make Allow as default option

**Comment by Demonsthere** [comment]
Please keep in mind that the default setup of istio (istio-ingressgateway and proxy) will limit the number of req/s your tests will yield. Please retry your tests on the production profile, which has been tuned to provide better performance.
