### ISSUE TITLE
[Test Case] - Check Kiali integration

### ISSUE THREAD

**Issue by tobiscr** [kyma-project/kyma#9943]
**Summary**

The purpose of the test is to verify the basic functionality of the Kiali UI.

**Actions to replace manual test case**
We assume that the Kiali UI is functional and tested by the kiali community. When updating kiali that will be verified once manually. We need to focus on the kyma specifics which are mainly the integration aspects.

Have an automated test which is calling the kiali API and test:
- simulate a graph rendering by calling the graph API and see that graph data is returned (in the past it was enough to assure that the graph gets shown at all)
- check the component status via API, there should be no "red" or "yellow" integration components (on the top right nav bar)
- check that details for a specific workload gets returned
- check that the details of a workload provide metrics for incoming requests
- check that the details of a workload provide trace data

See also https://github.com/kiali/kiali/tree/master/tests/e2e

**Manual Test Steps**

1. Open Kyma dashboard and open Kiali UI:
-> Observability->Kiali
2. Verify all supported graphs:
Graph->Select `kyma-system` namespace and choose
* `App graph`, 
* `Service graph`,
* `Versioned app graph`,
* `Workload graph`.

    See screenshot.

~~3. Open the DEX workload view (URL path `/kiali/console/namespaces/kyma-system/workloads/dex?duration=60&refresh=0`). Verify the completeness of the page.~~

    See screenshot.

**Expected Results**

* Graph is shown containing vertices and corresponding edges.
* When selecting a vertice, the panel on the right provides additional information (e.g. incoming/outgoing traffic).
* The tracing tab is showing one trace at least. The jump-out URL to jaeger is working.

Example of Graph view:
<img width="1777" alt="kiali-appgraph" src="https://user-images.githubusercontent.com/73824711/98971686-c84b9380-2511-11eb-967f-01e5e0b9dc74.png">

Example of Workload view:
<img width="1768" alt="kiali-workloadgrafana" src="https://user-images.githubusercontent.com/73824711/98978003-93dbd580-2519-11eb-8a62-b5c5eeb0d9ea.png">

**Comment by chrkl** [comment]
Kiali has been removed with https://github.com/kyma-project/kyma/pull/16516

**Comment by Sawthis** [comment]
Manual test case removed for 2.11 release excel checklist.
