### ISSUE TITLE
Tiller shouldn't be used in UI API acceptance tests

### ISSUE THREAD

**Issue by michal-hudy** [kyma-project/kyma#995]
**Description**

- As Tiller will be not available from other pods than installator, we should stop using it in tests. Kubernetes API should be used.
- Cleanup readmes for the ups charts (charts anyway will be removed)
- Tests should work as host network
- Logs should contains clear answer if registering of ServiceBroker fail

**Reason**

Soon tiller will not be available for test applications.

**Comment by kazydek** [comment]
As part of the task, pls make sure that both below README.md docs are removed. They are copied from other public repos and do not follow our guidelines:
- https://github.com/kyma-project/kyma/blob/master/tests/ui-api-layer-acceptance-tests/domain/servicecatalog/testdata/charts/cluster-ups-broker/README.md
- https://github.com/kyma-project/kyma/blob/master/tests/ui-api-layer-acceptance-tests/domain/servicecatalog/testdata/charts/ups-broker/README.md

**Comment by mjasinski5** [comment]
Review: @pkosiec @michal-hudy
