### ISSUE TITLE
How to list Configuration value in Oauth2Client resource

### ISSUE THREAD

**Issue by sundarvc** [kyma-project/kyma#9966]
Hi team,

How can I use k8s api to list the details of an OAuth Client resource ? I am able to view the Secrets separately but what I would like to do , is a lot list the scopes assigned i.e the configuration . Is there any way to do this ?

Thanks,
Sundar

**Comment by piotrmsc** [comment]
@sundarvc scopes are on the Oauth2Client CR spec so to get only scopes you can do sth like this : ```kubectl  get oauth2clients.hydra.ory.sh -n $NAMESPACE $RESOURCE_NAME -o jsonpath='.spec.scope'```

**Comment by sundarvc** [comment]
Thanks that worked. Is there a way to use k8s javascript client api to create an OAuth Client ? I know this can be done from command line, but I have a UI that needs to create an Oauth Client.

**Comment by kwiatekus** [comment]
I think what you need is this [function](https://github.com/kubernetes-client/javascript/blob/master/src/gen/api/customObjectsApi.ts#L101)
and call it with  proper resource name, group, version (`apirules`, `gateway.kyma-project.io`,`v1alpha1`) and a proper json body.
