### ISSUE TITLE
console-backend tests fail with {"errors":[{"message":"Index with name ref does not exist","path":["triggers"]}],"data":{"triggers":null}}

### ISSUE THREAD

**Issue by akucharska** [kyma-project/kyma#9970]
https://status.build.kyma-project.io/view/gcs/kyma-prow-logs/logs/post-master-kyma-gke-ver1_18_10-integration/1328331356266041344

**Description**

**Expected result**

**Actual result**

**Steps to reproduce**

**Troubleshooting**

**Comment by pbochynski** [comment]
We are removing those tests.
