### ISSUE TITLE
How to access Kyma local installation from internet

### ISSUE THREAD

**Issue by crazzynko** [kyma-project/kyma#9982]
Hello,

I am trying to access my local Kyma installation from the internet, but I can't figure out how to access it. I am using Windows and Minikube on hyperv to set up. On my router (with public IP) I've DMZ which is pointing to my Minikube instance. I also have a domain, DNS record pointing to my public IP (minikube) and wildcard SSL certificate generated with Let's Encrypt.

First problem:
When I install Kyma localy with my own domain i can't access console. Right after log in it show "Not enough permissions"

![image](https://user-images.githubusercontent.com/34039080/99642296-a0958780-2a4b-11eb-970a-b5eb845cd78b.png)

I think this is related to Minikube which is using it's own SSL certificate and browser (Chrome, IE, Mozilla) is not happy about it.

I was also trying to install minikube with my certificate but with no luck. I came across a few problems and now I am facing something like this:
`error execution phase certs/apiserver: [certs] certificate apiserver not signed by CA certificate ca: x509: invalid signature: parent certificate cannot sign this kind of certificate`

This error only ocures when I am using certificate generated with Let's Encrypt. When I was using self signed certificate there was similar issue as when I was using certigicate generated by Minikube (but at least instalation was succesful).

Second problem:
I still don't know how to access my local Kyma installation from outside of my home network. I can't find any manual for this so is it even posible? I want to test it with SAP Sales/Service cloud without need for SCP, GKE etc.

From outside of local network I am getting something like this:

![image](https://user-images.githubusercontent.com/34039080/99650259-7cd73f00-2a55-11eb-87ee-d2278c44fc86.png)

I will be grateful for any help.

**Comment by Ressetkk** [comment]
It is just an idea, but have you tried the approach like creating a reverse proxy and accessing your local Kyma instance through it? This approach would look like that:
```
Net --> Reverse Proxy (eg. Nginx) /w LE SSL and custom domain --> Kyma instance /w self-signed cert
```
Install kyma normally, as you would do it locally, make sure it is exposed in your local network, then configure reverse proxy that handles the connection to your instance. Nginx eg.
```
/etc/nginx/sites-enabled/kyma.conf

server {
  server_name *.yourdomain.com;
  listen 443;
  location / {
    proxy_pass https://kyma_ip:8443
    proxy_set_header X-Forwarded-Host $host:$server_port;
    proxy_set_header X-Forwarded-Server $host;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_ssl_verify off; //disable verification of the cert for kyma.
  }
  // LE SSL configuration
}
```

Not sure if this would work, but it's worth giving a shot.

**Comment by crazzynko** [comment]
> It is just an idea, but have you tried the approach like creating a reverse proxy and accessing your local Kyma instance through it? This approach would look like that:
> 
> ```
> Net --> Reverse Proxy (eg. Nginx) /w LE SSL and custom domain --> Kyma instance /w self-signed cert
> ```
> 
> Install kyma normally, as you would do it locally, make sure it is exposed in your local network, then configure reverse proxy that handles the connection to your instance. Nginx eg.
> 
> ```
> /etc/nginx/sites-enabled/kyma.conf
> 
> server {
>   server_name *.yourdomain.com;
>   listen 443;
>   location / {
>     proxy_pass https://kyma_ip:8443
>     proxy_set_header X-Forwarded-Host $host:$server_port;
>     proxy_set_header X-Forwarded-Server $host;
>     proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
>     proxy_ssl_verify off; //disable verification of the cert for kyma.
>   }
>   // LE SSL configuration
> }
> ```
> 
> Not sure if this would work, but it's worth giving a shot.

Didn't try this yet but you are right this should work. I will try it soon.

**Comment by crazzynko** [comment]
It is working with reverse proxy.

If anybody else would try it here is my nginx conf:

```
server {
        if ($host = example.com) {
                return 301 https://console.example.com;
        }
        server_name  ~^(?<endpoint>.+)\.example\.com$;
        server_tokens off;
        #From /etc/resolv.conf
        resolver 127.0.0.53;

        access_log /var/log/nginx/reverse-access.log;
        error_log /var/log/nginx/reverse-error.log;
        location / {
                proxy_pass https://$host;
                proxy_http_version 1.1;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection "upgrade";
                proxy_ssl_server_name on;
        }
        listen [::]:443 ssl ipv6only=on; # managed by Certbot
        listen 443 ssl; # managed by Certbot
        ssl_certificate /fullchain.pem; # managed by Certbot
        ssl_certificate_key /privkey.pem; # managed by Certbot
        include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
        ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot
}
server {
        server_name  ~^(?<endpoint>.+)\.example\.com$;
        if ($host = $endpoint.kyma.anodius.icu) {
                return 301 https://$host$request_uri;
        }
        if ($host = example.com) {
                return 301 https://console.example.com;
        }
        listen 80;
        listen [::]:80;

        server_name example.com;
        return 404;
}
```

Add this to your /etc/hosts
```
{KymaIP} application-operator.example.com connector-service.example.com gateway.example.com apiserver.example.com console-backend.example.com console.example.com core-ui.example.com
{KymaIP} docs.example.com dex.example.com addons.example.com configurations-generator.example.com oauth2.example.com storage.example.com registry.example.com
{KymaIP} catalog.example.com
```

Generate certificates with letsencrypt like this:
```
certbot certonly –manual --rsa-key-size 4096 --preferred-challenges=dns --email {your_email} --server https://acme-v02.api.letsencrypt.org/directory --agree-tos -d *.example.com
```

My Kyma was installed under Windows. You have to move your trusted certs into:
```
C:\Users\{user}\.minikube\certs\example.com
```

Like this:
![image](https://user-images.githubusercontent.com/34039080/101497421-3fd2de00-396b-11eb-922e-354825991aa0.png)

Then install it in powershell:
```
kyma provision minikube --vm-driver hyperv --hypervVirtualSwitch "minikube" 
kyma install --domain example.com --tlsCert {your_cert} --tlsKey {your_privkey}
```

Right after installation you should be ready to test.
