### ISSUE TITLE
Updating code via CLI breaks injected ENVS

### ISSUE THREAD

**Issue by kwiatekus** [kyma-project/kyma#9986]
**Description**

Applying changes to function code via CLI gets the function pod disconnected from it's bound env variables

**Expected result**

Injected ENVs should still be usable after function is rebuilt following an apply action from CLI ( like it doeas in case function is edited via UI )

**Actual result**

After function is rebuilt ( following an update via CLI ) it looses the  ENVS  injected via pod preset
![Screen Shot 2020-11-19 at 13 35 26](https://user-images.githubusercontent.com/6783567/99667580-e6af1300-2a6c-11eb-8164-2f8b7b610f08.png)

**Steps to reproduce**

1. create a demo namespace
2. clone this repo https://github.com/kwiatekus/show-injected-credentials
3. modify config.yaml and adjust the `sourcePath` to match your folder name
4. run `kyma apply function`
5. In console UI expose the function via API rule
6. Call the function via HTTP. You will see the following response: `Redis HOST :undefined`
7. Configre an [addon](https://github.com/kyma-project/addons/releases/download/0.11.0/index-testing.yaml) containing a redis service class
8. Instantiate a micro plan of redis in demo namespace 
9. Bind redis instance to the function (w/o any prefix for the injected ENVs)
10. After function is redeployed, call it again via HTTP. Response will contain injected redis HOST environment (i.e `Redis HOST :hb-redis-micro-33712c55-4565-4f69-a781-87fb23ae17fc-redis.demo.svc.cluster.local`)
11. Modify the code locally ( not via UI ) and apply the changes via kyma CLI : `kyma function apply`
12. After function is rebuilt, call it again via HTTP to see that the injected value is undefined

**Troubleshooting**

**Comment by kfurgol** [comment]
The [#144](https://github.com/kyma-incubator/hydroform/pull/144) PR fixes the issue, but you need to remember that you have to use the `kyma sync function` command before modifying its code.
