### ISSUE TITLE
Update knative-kafka-controller image and document the reconcile settings for SKR

### ISSUE THREAD

**Issue by k15r** [kyma-project/kyma#9992]
As an SKR admin i want to see the kantive channel dispatcher to be recreated whenever it vanishes from the cluster, so that i can ensure that events are delivered in time.

Acceptance Criteria:
- [x] knative kafka channel controller images is updated to latest version (0.12.4)
- [x] reconcile interval is configured to rational defaults
- [x] reconcile interval setting is documented for SKR admins

**Comment by berkanercan** [comment]
reconcile interval 10 min.
