### ISSUE TITLE
Performance Test - Event Delivery

### ISSUE THREAD

**Issue by k15r** [kyma-project/kyma#9995]
As a kyma user i want to get some rough estimate how many events i am able to process on a managed kyma cluster.

Acceptance Criteria:
- [ ] Workload connected to BEB using webhook and secured using oauth
- [ ] event generation can be done on a developers machine
- [ ] documented: number of webhooks, number of events / sec

Ready to be implemented as soon as BEB RestAPI team allows us to run those tests

**Comment by k15r** [comment]
This test shall only deliver a rough estimate of the performance that can be achieved with the new solution. It does not have to be a fully automated solution, a simple script and a could do the job as well

**Comment by berkanercan** [comment]
limit 200 events/s

**Comment by k15r** [comment]
will be directly covered by https://github.com/kyma-project/kyma/issues/9997
