### ISSUE TITLE
Performance Test - Event Publishing

### ISSUE THREAD

**Issue by k15r** [kyma-project/kyma#9996]
As a kyma user i want to get some rough estimate how many events i am able to send to kyma to have them forwarded to BEB

Acceptance Criteria:

- [ ] Application connected to kyma.
- [ ] event generation can be done on a developers machine
- [ ] documented: number of applications,  number of events / sec

Ready to be implemented as soon as BEB RestAPI team allows us to run those tests

**Comment by k15r** [comment]
This test shall only deliver a rough estimate of the performance that can be achieved with the new solution. It does not have to be a fully automated solution, a simple script and a could do the job as well

**Comment by berkanercan** [comment]
Both endpoints should be tested. (legacy and cloud events)

**Comment by k15r** [comment]
will be directly covered by https://github.com/kyma-project/kyma/issues/9997
